import { type Document } from "mongodb";

const PlaySchema: Document = {
  bsonType: "object",
  required: ["_id", "metadata", "playId", "title", "author", "_archive"],
  additionalProperties: false,
  properties: {
    _id: { bsonType: "objectId" },
    _archive: {
      bsonType: "object",
      required: ["_type", "playId", "title"],
      additionalProperties: false,
      properties: {
        _type: { bsonType: "string", enum: ["play", "adaptation"] },
        playId: { bsonType: "string" },
        title: { bsonType: "string" },
        altTitle: { bsonType: "string" },
        synopsis: { bsonType: "string" },
        notes: { bsonType: "string" },
        production: { bsonType: "string" },
        organizations: { bsonType: "string" },
        publisher: { bsonType: "string" },
        music: { bsonType: "string" },
        genres: { bsonType: "string" },
        parts: { bsonType: "string" },
        reference: { bsonType: "string" },
        adaptingAuthor: { bsonType: "string" },
        productionLocation: { bsonType: "string" },
        productionYear: { bsonType: "string" },
        isbn: { bsonType: "string" },
        imgAlt: { bsonType: "string" },
        maleParts: { bsonType: "string" },
        femaleParts: { bsonType: "string" },
        otherParts: { bsonType: "string" },
      },
    },
    playId: { bsonType: "string" },
    metadata: {
      bsonType: "object",
      required: ["createdAt", "updatedAt", "scrapedAt", "sourceUrl"],
      additionalProperties: false,
      properties: {
        createdAt: { bsonType: "date" },
        updatedAt: { bsonType: "date" },
        scrapedAt: { bsonType: "date" },
        sourceUrl: { bsonType: "string" },
        needsReview: { bsonType: "bool" },
        needsReviewReason: { bsonType: "string" },
        needsReviewData: {
          bsonType: "object",
          additionalProperties: true,
        },
      },
    },

    rawFields: {
      bsonType: "object",
      additionalProperties: false,
      properties: {
        altTitle: { bsonType: "string" },
        publishingInfo: { bsonType: "string" },
        productionInfo: { bsonType: "string" },
      },
    },

    title: { bsonType: "string" },
    author: { bsonType: "string" },
    authorId: { bsonType: "objectId" },
    adaptingAuthor: { bsonType: "string" },
    genres: { bsonType: "string" },
    synopsis: { bsonType: "string" },
    notes: { bsonType: "string" },
    organizations: { bsonType: "string" },
    music: { bsonType: "string" },
    reference: { bsonType: "string" },
    publisher: { bsonType: "string" },
    publicationYear: { bsonType: "string" },
    containingWork: { bsonType: "string" },
    isbn: { bsonType: "string" },
    productionLocation: { bsonType: "string" },
    productionYear: { bsonType: "string" },
    partsCountMale: { bsonType: "number" },
    partsCountFemale: { bsonType: "number" },
    partsCountOther: { bsonType: "number" },
    partsCountTotal: { bsonType: "number" },
    partsTextMale: { bsonType: "string" },
    partsTextFemale: { bsonType: "string" },
    partsTextOther: { bsonType: "string" },
  },
};

export default PlaySchema;
