export default {
  "metadata": {
    "results": 609,
    "timeStamp": "2025-12-05T21:21:47.248Z",
    "url": "https://www.doollee.com/PlaywrightsA/A_playwrights_g-l.php"
  },
  "authors": {
    "AGABIAN Nancy": "agabian-nancy",
    "AGAMIAN Mariam": "agamian-mariam",
    "AGANS David J": "agans-david-j",
    "AGARD John": "agard-john",
    "AGARD Sandra": "agard-sandra",
    "AGATHA Sue": "agatha-sue",
    "AGBAJE Bola": "agbaje-bola",
    "AGBOLUAJE Oladipo": "agboluaje-oladipo",
    "AGBONLAHOR Charis": "agbonlahor-charis",
    "AGEE Joel": "agee-joel",
    "AGENT Sarah": "agent-sarah",
    "AGG Howard": "agg-howard",
    "AGISLAOU Yiannis": "agislaou-yiannis",
    "AGNEW F E M": "agnew-f-e-m",
    "AGNEW Pinky": "agnew-pinky",
    "AGNEW Steve": "agnew-steve",
    "AGNEW Will": "agnew-will",
    "AGNIEL Anna Marie": "agniel-anna-marie",
    "AGOSTON Gerty": "agoston-gerty",
    "AGRAWAL Nayna B": "agrawal-nayna-b",
    "AGRUPACION SENOR SERRANO ": "agrupacion-senor-serrano",
    "AGUEROS Jack": "agueros-jack",
    "AGUILA Kevin Del": "aguila-kevin-del",
    "AGUILAR Anthony": "aguilar-anthony",
    "AGUILAR Christopher Belen": "aguilar-christopher-belen",
    "AGUILER Louis": "aguiler-louis",
    "AGUILERA Carolina": "aguilera-carolina",
    "AGUILERA Yunior Garcia": "aguilera-yunior-garcia",
    "AGUIRRE Carmen": "aguirre-carmen",
    "AGUIRRE Isidora": "aguirre-isidora",
    "AGUIRRE Michael Allen": "aguirre-michael-allen",
    "AGUIRRE Mike": "aguirre-mike",
    "AGUIRRE-SACASA Roberto": "aguirre-sacasa-roberto",
    "AGULANSKY Leon": "agulansky-leon",
    "AGUSTIN Sandra": "agustin-sandra",
    "AGYEMANG Kofi": "agyemang-kofi",
    "AH HI Iaheto": "ah-hi-iaheto",
    "AHAD Nick": "ahad-nick",
    "AHAMED Masud": "ahamed-masud",
    "AHAMED Saikat": "ahamed-saikat",
    "AHARONI Michal": "aharoni-michal",
    "AHEARN Dan": "ahearn-dan",
    "AHERN Carrie": "ahern-carrie",
    "AHERN Lynne": "ahern-lynne",
    "AHERNS Lynn": "aherns-lynn",
    "AHIPENE Hori": "ahipene-hori",
    "AHLBOM Jakop": "ahlbom-jakop",
    "AHLERSMEYER Bob": "ahlersmeyer-bob",
    "AHLERT Richard": "ahlert-richard",
    "AHLFORS Bengt": "ahlfors-bengt",
    "AHLIN John": "ahlin-john",
    "AHLIN Margit": "ahlin-margit",
    "AHLQUIST Jane": "ahlquist-jane",
    "AHMAD Aamina": "ahmad-aamina",
    "AHMAD Dorothy": "ahmad-dorothy",
    "AHMAD Faizan": "ahmad-faizan",
    "AHMAD Marina Wolf": "ahmad-marina-wolf",
    "AHMAD Ruhksana": "ahmad-ruhksana",
    "AHMADI Nastaran": "ahmadi-nastaran",
    "AHMADZADEH Morteza": "ahmadzadeh-morteza",
    "AHMAN Aamina": "ahman-aamina",
    "AHMED Mediah": "ahmed-mediah",
    "AHMED Mukul": "ahmed-mukul",
    "AHMED Naylah": "ahmed-naylah",
    "AHMED Said Salah": "ahmed-said-salah",
    "AHMED Sharbari": "ahmed-sharbari",
    "AHMED Umar": "ahmed-umar",
    "AHN Byungkoo": "ahn-byungkoo",
    "AHNEN Pearl S": "ahnen-pearl-s",
    "AHNET Behsat": "ahnet-behsat",
    "AHOLA Robert Joseph": "ahola-robert-joseph",
    "AHONEN Derek": "ahonen-derek",
    "AHRENS Lynn": "ahrens-lynn",
    "AHRENS Renate": "ahrens-renate",
    "AHRONHEIM Adele": "ahronheim-adele",
    "AHSAM Richard": "ahsam-richard",
    "AIBEL Dan": "aibel-dan",
    "AICHER Sarah": "aicher-sarah",
    "AICHINGER Ilse": "aichinger-ilse",
    "AIDA Noriko": "aida-noriko",
    "AIDMAN Charles": "aidman-charles",
    "AIDOO Ama Ata (Christina)": "aidoo-ama-ata",
    "AIDOO Mina": "aidoo-mina",
    "AIKEN Alfred": "aiken-alfred",
    "AIKEN Conrad": "aiken-conrad",
    "AIKEN Ellen": "aiken-ellen",
    "AIKEN George": "aiken-george",
    "AIKEN Joan": "aiken-joan",
    "AIKEN III P Case": "aiken-iii-p-case",
    "AINARSSON Sveinn": "ainarsson-sveinn",
    "AINSCOW Faye": "ainscow-faye",
    "AINSLIE Maud": "ainslie-maud",
    "AINSWORTH Dave": "ainsworth-dave",
    "AINSWORTH Ford": "ainsworth-ford",
    "AINSWORTH Julia": "ainsworth-julia",
    "AINSWORTH Robert": "ainsworth-robert",
    "AIRES Jorge Cardosos": "aires-jorge-cardosos",
    "AISNER Keith": "aisner-keith",
    "AITA Deborah": "aita-deborah",
    "AITA Sean": "aita-sean",
    "AITCHISON Bill": "aitchison-bill",
    "AITCHTEY Rodney": "aitchtey-rodney",
    "AITKEN Ben": "aitken-ben",
    "AITKEN Dominic": "aitken-dominic",
    "AITKEN John": "aitken-john",
    "AITKEN Nikki": "aitken-nikki",
    "AITKEN Tamzin": "aitken-tamzin",
    "AJ ": "aj",
    "AJADI Adewale": "ajadi-adewale",
    "AJAMU ": "ajamu",
    "AJAYI Afolabi": "ajayi-afolabi",
    "AJEMIAN Chris": "ajemian-chris",
    "AJIBADE Yemi": "ajibade-yemi",
    "AJUONUMA Reg": "ajuonuma-reg",
    "AKALAITIS Joanne": "akalaitis-joanne",
    "AKAR John J": "akar-john-j",
    "AKEN Ann Wagooner": "aken-ann-wagooner",
    "AKERBAEK Tord": "akerbaek-tord",
    "AKEREDOLU Femi": "akeredolu-femi",
    "AKERFELT Hanna": "akerfelt-hanna",
    "AKERHOLT May-Britt": "akerholt-may-britt",
    "AKERLEY Kathleen": "akerley-kathleen",
    "AKERMAN Anthony": "akerman-anthony",
    "AKERS Dennis": "akers-dennis",
    "AKERS Mike": "akers-mike",
    "AKERS W M": "akers-w-m",
    "AKHTAR Ayad": "akhtar-ayad",
    "AKHTAR Selina": "akhtar-selina",
    "AKIMBO Deb'Bora": "akimbo-deb-bora",
    "AKIMOTO Matsuyo": "akimoto-matsuyo",
    "AKIN Ann": "akin-ann",
    "AKINSIPE Felix A": "akinsipe-felix-a",
    "AKIVA Maia": "akiva-maia",
    "AKIYAMA Daniel": "akiyama-daniel",
    "AKMAN Andrew": "akman-andrew",
    "AKRAM Yasmine": "akram-yasmine",
    "AKRIDGE Jayson": "akridge-jayson",
    "AKRILL Mark": "akrill-mark",
    "AKSYONOV Vasily": "aksyonov-vasily",
    "AL ASSADI Jawad": "al-assadi-jawad",
    "AL ATTAR Mohammad": "al-attar-mohammad",
    "ALABANZA Travis": "alabanza-travis",
    "ALAGIC Tea": "alagic-tea",
    "ALAGO Linda": "alago-linda",
    "ALAKIJA Olu": "alakija-olu",
    "AL-ALI Akkas": "al-ali-akkas",
    "ALAM Juan Shamsul": "alam-juan-shamsul",
    "ALAM Pervaiz": "alam-pervaiz",
    "ALAMAJI Jiwe": "alamaji-jiwe",
    "ALAMAZ Michael": "alamaz-michael",
    "AL-AMERI Abdul-Kareem": "al-ameri-abdul-kareem",
    "ALAMO Antonio": "alamo-antonio",
    "ALAN Glenn": "alan-glenn",
    "ALAN Scott": "alan-scott",
    "ALANCROFT Rick": "alancroft-rick",
    "ALARIC Terence": "alaric-terence",
    "ALASA Michelangelo": "alasa-michelangelo",
    "ALASSIO Saundra": "alassio-saundra",
    "ALAWJI Abdelrahim": "alawji-abdelrahim",
    "AL-AZRAKI A": "al-azraki-a",
    "ALAZRAQUI Carlos": "alazraqui-carlos",
    "ALBAKRI Zahim": "albakri-zahim",
    "ALBAN Carlo": "alban-carlo",
    "ALBANESE Eleanor": "albanese-eleanor",
    "ALBANESE James V": "albanese-james-v",
    "ALBANESE John": "albanese-john",
    "ALBANESE Michael": "albanese-michael",
    "ALBANO John": "albano-john",
    "ALBARELLA Joan": "albarella-joan",
    "ALBARN Damon": "albarn-damon",
    "AL-BASSAM Sulayman": "al-bassam-sulayman",
    "ALBATE Christopher": "albate-christopher",
    "ALBEE Edward": "albee-edward",
    "ALBERS Katherine": "albers-katherine",
    "ALBERT April": "albert-april",
    "ALBERT Carolyn": "albert-carolyn",
    "ALBERT Jan": "albert-jan",
    "ALBERT Jonathan": "albert-jonathan",
    "ALBERT Lauren Marie": "albert-lauren-marie",
    "ALBERT Lyle": "albert-lyle",
    "ALBERT Mark H": "albert-mark-h",
    "ALBERT Marvin": "albert-marvin",
    "ALBERT Michael Ross": "albert-michael-ross",
    "ALBERT Sandra J": "albert-sandra-j",
    "ALBERT Thomas": "albert-thomas",
    "ALBERTELLA Jorge": "albertella-jorge",
    "ALBERTIE Dante": "albertie-dante",
    "ALBERTO Luis": "alberto-luis",
    "ALBERTS David": "alberts-david",
    "ALBERTY R Patrick": "alberty-r-patrick",
    "ALBERY Peter": "albery-peter",
    "ALBERY Tim": "albery-tim",
    "ALBINO Mary": "albino-mary",
    "ALBISTON Lesley Ann": "albiston-lesley-ann",
    "ALBO Mike": "albo-mike",
    "ALBOM Mitch": "albom-mitch",
    "ALBON Nicola": "albon-nicola",
    "ALBORELLI H P": "alborelli-h-p",
    "ALBOROUGH Graham": "alborough-graham",
    "ALBREZZI Steve": "albrezzi-steve",
    "ALBRIGHT Dale": "albright-dale",
    "ALBRIGHT James": "albright-james",
    "ALBRIGHT Mia": "albright-mia",
    "ALBRIGHT Philip": "albright-philip",
    "ALBURY Barbara": "albury-barbara",
    "ALCANTARA Grace": "alcantara-grace",
    "ALCAREZ Jose": "alcarez-jose",
    "ALCID Edmond": "alcid-edmond",
    "ALCOFORADO Sister Mariana": "alcoforado-sister-mariana",
    "ALCORN Frank": "alcorn-frank",
    "ALCORN John": "alcorn-john",
    "ALCORN Seth": "alcorn-seth",
    "ALCORTA David": "alcorta-david",
    "ALCOTT Clapham": "alcott-clapham",
    "ALCOTT Louisa M": "alcott-louisa-m",
    "ALCOTT Todd": "alcott-todd",
    "ALDA Alan": "alda-alan",
    "ALDEN Jerome": "alden-jerome",
    "ALDEN Jonathan James": "alden-jonathan-james",
    "ALDEN Matt": "alden-matt",
    "ALDEN William": "alden-william",
    "ALDERMAN Elinor R": "alderman-elinor-r",
    "ALDERSON Jude": "alderson-jude",
    "ALDERSON Sophie": "alderson-sophie",
    "ALDERTON Alex": "alderton-alex",
    "ALDERTON Rob": "alderton-rob",
    "ALDIN Michele": "aldin-michele",
    "ALDOR Emil": "aldor-emil",
    "ALDOUS John": "aldous-john",
    "ALDRED David": "aldred-david",
    "ALDRIDGE Arthur": "aldridge-arthur",
    "ALDRIDGE James": "aldridge-james",
    "ALDRIDGE Ron": "aldridge-ron",
    "ALEANDRI Ernelise": "aleandri-ernelise",
    "ALED Gareth": "aled-gareth",
    "ALEGRIA Alonso": "alegria-alonso",
    "ALEGRIA Quiara": "alegria-quiara",
    "ALEICHEM Sholem": "aleichem-sholem",
    "ALEJANDRO Jan Michael": "alejandro-jan-michael",
    "ALEKAR Satish": "alekar-satish",
    "ALENICK Ashley": "alenick-ashley",
    "ALENIER Karren La Londe": "alenier-karren-la-londe",
    "ALESIA Dominick": "alesia-dominick",
    "ALESSANDRINI Gerald": "alessandrini-gerald",
    "ALESSI Lillian": "alessi-lillian",
    "ALETTE Carl": "alette-carl",
    "ALEX David": "alex-david",
    "ALEXANDER Aaron": "alexander-aaron",
    "ALEXANDER Alexa": "alexander-alexa",
    "ALEXANDER Annalita": "alexander-annalita",
    "ALEXANDER Ben": "alexander-ben",
    "ALEXANDER Bill": "alexander-bill",
    "ALEXANDER Brad": "alexander-brad",
    "ALEXANDER Constance": "alexander-constance",
    "ALEXANDER Darby": "alexander-darby",
    "ALEXANDER Donald W": "alexander-donald-w",
    "ALEXANDER E A": "alexander-e-a",
    "ALEXANDER Elaine": "alexander-elaine",
    "ALEXANDER Ewart": "alexander-ewart",
    "ALEXANDER F K": "alexander-f-k",
    "ALEXANDER Floyd Sephen": "alexander-floyd-sephen",
    "ALEXANDER Geraldine": "alexander-geraldine",
    "ALEXANDER Henry": "alexander-henry",
    "ALEXANDER Holmes": "alexander-holmes",
    "ALEXANDER J B": "alexander-j-b",
    "ALEXANDER Jackie": "alexander-jackie",
    "ALEXANDER Jane": "alexander-jane",
    "ALEXANDER Jeanne": "alexander-jeanne",
    "ALEXANDER Jill": "alexander-jill",
    "ALEXANDER Judy": "alexander-judy",
    "ALEXANDER Kathya": "alexander-kathya",
    "ALEXANDER Kevin": "alexander-kevin",
    "ALEXANDER Lawrence": "alexander-lawrence",
    "ALEXANDER Lee": "alexander-lee",
    "ALEXANDER Lewis M": "alexander-lewis-m",
    "ALEXANDER Linda Pace": "alexander-linda-pace",
    "ALEXANDER Lowell": "alexander-lowell",
    "ALEXANDER Luther": "alexander-luther",
    "ALEXANDER Maddy": "alexander-maddy",
    "ALEXANDER Mandy": "alexander-mandy",
    "ALEXANDER Meena": "alexander-meena",
    "ALEXANDER Megan": "alexander-megan",
    "ALEXANDER Michael": "alexander-michael",
    "ALEXANDER Myfanwy": "alexander-myfanwy",
    "ALEXANDER Nichol": "alexander-nichol",
    "ALEXANDER Paul": "alexander-paul",
    "ALEXANDER Paul (1)": "alexander-paul-1",
    "ALEXANDER Peter": "alexander-peter",
    "ALEXANDER Richard": "alexander-richard",
    "ALEXANDER Robert": "alexander-robert",
    "ALEXANDER Ronald": "alexander-ronald",
    "ALEXANDER Ross": "alexander-ross",
    "ALEXANDER Sascha": "alexander-sascha",
    "ALEXANDER Sharon": "alexander-sharon",
    "ALEXANDER Stephanie": "alexander-stephanie",
    "ALEXANDER Steven": "alexander-steven",
    "ALEXANDER Stewart": "alexander-stewart",
    "ALEXANDER Sue": "alexander-sue",
    "ALEXANDER Tania": "alexander-tania",
    "ALEXANDER Thorin": "alexander-thorin",
    "ALEXANDER Victor": "alexander-victor",
    "ALEXANDER Zakiyyah": "alexander-zakiyyah",
    "ALEXANDER III Alan": "alexander-iii-alan",
    "ALEXANDER SISTERS, THE ": "alexander-sisters",
    "ALEXANDERSSON David": "alexandersson-david",
    "ALEXANDRA ": "alexandra",
    "ALEXANDRATOS Jonathan": "alexandratos-jonathan",
    "ALEXANDRINO Du Carmo": "alexandrino-du-carmo",
    "ALEXANDRO Trish": "alexandro-trish",
    "ALEXANDROWICZ Conrad": "alexandrowicz-conrad",
    "ALEXIS Andre": "alexis-andre",
    "ALFARO Luis": "alfaro-luis",
    "ALFARO Rosanna Yamagiwa": "alfaro-rosanna-yamagiwa",
    "ALFIERI Richard": "alfieri-richard",
    "ALFIERI Vittorio": "alfieri-vittorio",
    "ALFONSO Mann": "alfonso-mann",
    "ALFORD David": "alford-david",
    "ALFORD Kenneth": "alford-kenneth",
    "ALFORD Lamar": "alford-lamar",
    "ALFORD Larry": "alford-larry",
    "ALFRED James T": "alfred-james-t",
    "ALFRED William": "alfred-william",
    "ALFREDS Mike": "alfreds-mike",
    "ALFSON Richie": "alfson-richie",
    "ALGER Richard": "alger-richard",
    "ALGIE Angus": "algie-angus",
    "ALGIE Daniel": "algie-daniel",
    "AL-HAKIM Tawfiq": "al-hakim-tawfiq",
    "ALI Dhanil": "ali-dhanil",
    "ALI Jamal": "ali-jamal",
    "ALI Lateef": "ali-lateef",
    "ALI Luqman": "ali-luqman",
    "ALI Ntare": "ali-ntare",
    "ALI Tariq": "ali-tariq",
    "ALI Wajahat": "ali-wajahat",
    "ALIANAK Hrant": "alianak-hrant",
    "ALIANIELLO Davis": "alianiello-davis",
    "ALIBAR Lucy": "alibar-lucy",
    "ALIBERTI Lucian": "aliberti-lucian",
    "ALIBERTI Vince": "aliberti-vince",
    "ALIBHAI-BROWN Yasmin": "alibhai-brown-yasmin",
    "ALICANDRO Daniel": "alicandro-daniel",
    "ALICK Claudia": "alick-claudia",
    "ALICK Jesse Cameron": "alick-jesse-cameron",
    "ALI-COLEMAN Khadijah": "ali-coleman-khadijah",
    "ALIPOOR Javaad": "alipoor-javaad",
    "ALISON David": "alison-david",
    "ALISON Joan": "alison-joan",
    "ALISON ANDREWS COMPANY ": "alison-andrews-company",
    "ALIX Francis": "alix-francis",
    "ALIZADEH Ali": "alizadeh-ali",
    "ALKAFRI Abdullah": "alkafri-abdullah",
    "AL-KASABA THEATRE ": "al-kasaba-theatre",
    "AL-KASSAB Sarah": "al-kassab-sarah",
    "ALL OR NOTHING ": "all-or-nothing",
    "ALLADICE Darryl E": "alladice-darryl-e",
    "ALLAIN Noel Joseph": "allain-noel-joseph",
    "ALLAIN Stephanie": "allain-stephanie",
    "ALLAN Amanda": "allan-amanda",
    "ALLAN Charlotte": "allan-charlotte",
    "ALLAN Dan": "allan-dan",
    "ALLAN Gene": "allan-gene",
    "ALLAN Laurence": "allan-laurence",
    "ALLAN Leigh": "allan-leigh",
    "ALLAN Lisa": "allan-lisa",
    "ALLAN Lotte": "allan-lotte",
    "ALLAN Robert": "allan-robert",
    "ALLAN Ross": "allan-ross",
    "ALLAN Ted": "allan-ted",
    "ALLANA Alam": "allana-alam",
    "ALLARD Brian": "allard-brian",
    "ALLARD Harry": "allard-harry",
    "ALLARD Janet": "allard-janet",
    "ALLAYIALIS Toni": "allayialis-toni",
    "ALLCOCK Jack": "allcock-jack",
    "ALLCROFT Charles": "allcroft-charles",
    "ALLDEN Richard": "allden-richard",
    "ALLDEN Rick": "allden-rick",
    "ALLDRIDGE John": "alldridge-john",
    "ALLEGRA Michael": "allegra-michael",
    "ALLEGRO John": "allegro-john",
    "ALLEMAN Ben": "alleman-ben",
    "ALLEMANN Bryce": "allemann-bryce",
    "ALLEN Albert": "allen-albert",
    "ALLEN Alex": "allen-alex",
    "ALLEN Andi": "allen-andi",
    "ALLEN Andrea": "allen-andrea",
    "ALLEN Anthony": "allen-anthony",
    "ALLEN Ashley": "allen-ashley",
    "ALLEN B C": "allen-b-c",
    "ALLEN Brooke": "allen-brooke",
    "ALLEN Catherine": "allen-catherine",
    "ALLEN Cathy Celesia": "allen-cathy-celesia",
    "ALLEN Claudia": "allen-claudia",
    "ALLEN Corey": "allen-corey",
    "ALLEN D E": "allen-d-e",
    "ALLEN David": "allen-david",
    "ALLEN Debbie": "allen-debbie",
    "ALLEN Dennis": "allen-dennis",
    "ALLEN Dominic John": "allen-dominic-john",
    "ALLEN Donald M": "allen-donald-m",
    "ALLEN Evelyn W": "allen-evelyn-w",
    "ALLEN Geoff": "allen-geoff",
    "ALLEN Graham": "allen-graham",
    "ALLEN Greg": "allen-greg",
    "ALLEN Ian": "allen-ian",
    "ALLEN Indi": "allen-indi",
    "ALLEN J Linn": "allen-j-linn",
    "ALLEN J P": "allen-j-p",
    "ALLEN Janet": "allen-janet",
    "ALLEN Jay Presson": "allen-jay-presson",
    "ALLEN Jennifer": "allen-jennifer",
    "ALLEN Jenny": "allen-jenny",
    "ALLEN Jim": "allen-jim",
    "ALLEN Jimmy": "allen-jimmy",
    "ALLEN Jo Harvey": "allen-jo-harvey",
    "ALLEN John": "allen-john",
    "ALLEN Joshua": "allen-joshua",
    "ALLEN Judith": "allen-judith",
    "ALLEN June": "allen-june",
    "ALLEN Justin": "allen-justin",
    "ALLEN Kimball": "allen-kimball",
    "ALLEN L H": "allen-l-h",
    "ALLEN Laurence": "allen-laurence",
    "ALLEN Laurie": "allen-laurie",
    "ALLEN Lisa Beth": "allen-lisa-beth",
    "ALLEN Lizzie": "allen-lizzie",
    "ALLEN Marilyn": "allen-marilyn",
    "ALLEN Marilyn M": "allen-marilyn-m",
    "ALLEN Martin": "allen-martin",
    "ALLEN Merridith": "allen-merridith",
    "ALLEN Michael (1)": "allen-michael-1",
    "ALLEN Michael (2)": "allen-michael-2",
    "ALLEN Morgan": "allen-morgan",
    "ALLEN Nathan": "allen-nathan",
    "ALLEN Nicholas": "allen-nicholas",
    "ALLEN Norman": "allen-norman",
    "ALLEN Olivia": "allen-olivia",
    "ALLEN Paul": "allen-paul",
    "ALLEN Paul (1)": "allen-paul-1",
    "ALLEN Peter": "allen-peter",
    "ALLEN Ralph G": "allen-ralph-g",
    "ALLEN Raymond": "allen-raymond",
    "ALLEN Renata": "allen-renata",
    "ALLEN Renee Bang": "allen-renee-bang",
    "ALLEN Richard": "allen-richard",
    "ALLEN Richard (1)": "allen-richard-1",
    "ALLEN Richard James": "allen-richard-james",
    "ALLEN Roger": "allen-roger",
    "ALLEN Roland": "allen-roland",
    "ALLEN Russell": "allen-russell",
    "ALLEN Seamus": "allen-seamus",
    "ALLEN Seth": "allen-seth",
    "ALLEN Stephen": "allen-stephen",
    "ALLEN Steve": "allen-steve",
    "ALLEN Stuart": "allen-stuart",
    "ALLEN Suzanne M": "allen-suzanne-m",
    "ALLEN Ted": "allen-ted",
    "ALLEN Terry": "allen-terry",
    "ALLEN Thoasena": "allen-thoasena",
    "ALLEN Tina Alexis": "allen-tina-alexis",
    "ALLEN Tony": "allen-tony",
    "ALLEN Trevor": "allen-trevor",
    "ALLEN Vera": "allen-vera",
    "ALLEN William": "allen-william",
    "ALLEN Woody": "allen-woody",
    "ALLEN II Dennis A": "allen-ii-dennis-a",
    "ALLENDE Isabel": "allende-isabel",
    "ALLEN-DUTTON Jordan": "allen-dutton-jordan",
    "ALLEN-MARTIN Tori": "allen-martin-tori",
    "ALLENSWORTH Carl": "allensworth-carl",
    "ALLENSWORTH Dorothy": "allensworth-dorothy",
    "ALLERDYCE James": "allerdyce-james",
    "ALLERS Roger": "allers-roger",
    "ALLEY Fred": "alley-fred",
    "ALLEY Rewl": "alley-rewl",
    "ALLEYNE Arthur": "alleyne-arthur",
    "ALLEYNE Carla Debbie": "alleyne-carla-debbie",
    "ALLING Bodil": "alling-bodil",
    "ALLINGHAM Phillip": "allingham-phillip",
    "ALLINSON C C": "allinson-c-c",
    "ALLISON Christina": "allison-christina",
    "ALLISON David": "allison-david",
    "ALLISON Diane": "allison-diane",
    "ALLISON Hugh": "allison-hugh",
    "ALLISON Hughes": "allison-hughes",
    "ALLISON John": "allison-john",
    "ALLISON Lynn": "allison-lynn",
    "ALLISON Susie": "allison-susie",
    "ALLMAN John": "allman-john",
    "ALLMAN Kevin": "allman-kevin",
    "ALLMAN Paul": "allman-paul",
    "ALLMAN Sheldon": "allman-sheldon",
    "ALLNUTT David": "allnutt-david",
    "ALLOWAY Katrina": "alloway-katrina",
    "ALLSHOUSE Aaron": "allshouse-aaron",
    "ALLSOPP Warwick": "allsopp-warwick",
    "ALLT Nicky": "allt-nicky",
    "ALLTOP Kayce": "alltop-kayce",
    "ALLTOP Michael": "alltop-michael",
    "ALLUM Dan": "allum-dan",
    "ALLWEIS Lian": "allweis-lian",
    "ALLWOOD Peter": "allwood-peter",
    "ALLWOOD Ralph": "allwood-ralph",
    "ALLWRIGHT Christophe": "allwright-christophe",
    "ALLY Usman": "ally-usman",
    "ALLYN David": "allyn-david",
    "ALLYN Richard": "allyn-richard",
    "ALMA THEATRE ": "alma-theatre",
    "ALMAGOR Dan": "almagor-dan",
    "ALMAN Michael Stuart": "alman-michael-stuart",
    "ALMANZA Joseph D": "almanza-joseph-d",
    "ALMARIO Andrea": "almario-andrea",
    "ALMASY Jessica": "almasy-jessica",
    "ALMAZ Michael": "almaz-michael",
    "ALMAZAN Raquel": "almazan-raquel",
    "ALMEDINGEN E M": "almedingen-e-m",
    "ALMEIDA David": "almeida-david",
    "ALMELA Laura": "almela-laura",
    "ALMELEK Yakup": "almelek-yakup",
    "ALMENDAREZ Liliana": "almendarez-liliana",
    "ALMERAZ Peilin Chou": "almeraz-peilin-chou",
    "ALMIRON Jennifer": "almiron-jennifer",
    "ALMODOVAR Pedro": "almodovar-pedro",
    "ALMOG Ronny": "almog-ronny",
    "ALMONACID Camilo": "almonacid-camilo",
    "ALMOND David": "almond-david",
    "ALMOND Scott": "almond-scott",
    "ALMOND Suzy": "almond-suzy",
    "ALMOND Todd": "almond-todd",
    "ALMOS Carolyn": "almos-carolyn",
    "ALMOS Matt": "almos-matt",
    "ALMOST HUMAN ": "almost-human",
    "ALMQUIST Gregg": "almquist-gregg",
    "ALOMA Rene": "aloma-rene",
    "ALON Aaron": "alon-aaron",
    "ALONG HUMAN LINES ": "along-human-lines",
    "ALONI Nissim": "aloni-nissim",
    "ALONSO Tom": "alonso-tom",
    "ALONZO Cecil": "alonzo-cecil",
    "ALONZO Chris": "alonzo-chris",
    "ALONZO Dan": "alonzo-dan",
    "ALPAUGH Craig": "alpaugh-craig",
    "ALPER Linda": "alper-linda",
    "ALPER Sam": "alper-sam",
    "ALPER Steven M": "alper-steven-m",
    "ALPERN Joanna": "alpern-joanna",
    "ALPERT Sidsel Taubo": "alpert-sidsel-taubo",
    "ALPHONSE George": "alphonse-george",
    "ALPRIN Paula": "alprin-paula",
    "AL-QADY Towfiq": "al-qady-towfiq",
    "AL-RAEE Nabil": "al-raee-nabil",
    "ALRAWI Karim": "alrawi-karim",
    "ALSBERG Arthur": "alsberg-arthur",
    "AL-SHAIKH Hanan": "al-shaikh-hanan",
    "ALSINA Laia": "alsina-laia",
    "ALSON Lawrence": "alson-lawrence",
    "ALSOO Timothy": "alsoo-timothy",
    "ALSOP Gulielma Fell": "alsop-gulielma-fell",
    "ALSPAUGH Johnny": "alspaugh-johnny",
    "ALSPAUGH Matt": "alspaugh-matt",
    "ALSTER Pamela": "alster-pamela",
    "ALSTON Quinn M": "alston-quinn-m",
    "ALSUP Glenn": "alsup-glenn",
    "ALTENBURG Andrew": "altenburg-andrew",
    "ALTENBURG Steve James": "altenburg-steve-james",
    "ALTER Brandon": "alter-brandon",
    "ALTER Eric": "alter-eric",
    "ALTER Gaby": "alter-gaby",
    "ALTER Louis": "alter-louis",
    "ALTERMAN Glenn": "alterman-glenn",
    "ALTERMAN Peter": "alterman-peter",
    "ALTERMAN Sara Faith": "alterman-sara-faith",
    "ALTERS Gerald": "alters-gerald",
    "ALTMAN Alison": "altman-alison",
    "ALTMAN Caroline": "altman-caroline",
    "ALTMAN Dennis": "altman-dennis",
    "ALTMAN Mark": "altman-mark",
    "ALTMAN Sean": "altman-sean",
    "ALTMAN Zach": "altman-zach",
    "ALTMANN Howard": "altmann-howard",
    "ALTOMARE Carlo": "altomare-carlo",
    "ALTON Andrea": "alton-andrea",
    "ALTROWS Rona": "altrows-rona",
    "ALTY Andrew": "alty-andrew",
    "ALUKO Tayo": "aluko-tayo",
    "ALUMIT Noel": "alumit-noel",
    "ALVARADO Albert": "alvarado-albert",
    "ALVARADO Mando": "alvarado-mando",
    "ALVAREZ Adolfo Perez": "alvarez-adolfo-perez",
    "ALVAREZ Boni B": "alvarez-boni-b",
    "ALVAREZ Bosco Israel Cayo": "alvarez-bosco-israel-cayo",
    "ALVAREZ Cesar": "alvarez-cesar",
    "ALVAREZ Geoffrey": "alvarez-geoffrey",
    "ALVAREZ Ivy": "alvarez-ivy",
    "ALVAREZ Jay": "alvarez-jay",
    "ALVAREZ John K": "alvarez-john-k",
    "ALVAREZ Lynne": "alvarez-lynne",
    "ALVAREZ Michael": "alvarez-michael",
    "ALVAREZ Nino": "alvarez-nino",
    "ALVARO Corrado": "alvaro-corrado",
    "ALVERSON Charles": "alverson-charles",
    "ALVIK David": "alvik-david",
    "ALVIN Raymond": "alvin-raymond",
    "ALVIS Justin": "alvis-justin",
    "ALWAJ Abdelrahim": "alwaj-abdelrahim",
    "ALWIN-HILL R": "alwin-hill-r",
    "AL-ZAIDI Ali Abdel-Nabi": "al-zaidi-ali-abdel-nabi",
    "ALZOUGBI Alian": "alzougbi-alian"
  }
};