export default {
  "metadata": {
    "results": 753,
    "timeStamp": "2025-12-05T21:21:53.385Z",
    "url": "https://www.doollee.com/PlaywrightsA/A_playwrights_m-r.php"
  },
  "authors": {
    "AMACKER Johnathan E": "amacker-johnathan-e",
    "AMADA Rich": "amada-rich",
    "AMADIO Liz": "amadio-liz",
    "AMADO Jorge": "amado-jorge",
    "AMADOR Fredericao": "amador-fredericao",
    "AMALRIK Andrey": "amalrik-andrey",
    "AMAN Michael": "aman-michael",
    "AMANDES Paul": "amandes-paul",
    "AMANI V": "amani-v",
    "AMANO Karen": "amano-karen",
    "AMARIS Lian": "amaris-lian",
    "AMAS Michele": "amas-michele",
    "AMATO E": "amato-e",
    "AMATO Joe": "amato-joe",
    "AMATO Mike": "amato-mike",
    "AMAYA Hector Humberto": "amaya-hector-humberto",
    "AMBACHER Richard J": "ambacher-richard-j",
    "AMBATIELOS Genna": "ambatielos-genna",
    "AMBERLEY Liz": "amberley-liz",
    "AMBERLEY Simon": "amberley-simon",
    "AMBERLY Liz": "amberly-liz",
    "AMBIENT Mark": "ambient-mark",
    "AMBLER Laura": "ambler-laura",
    "AMBLER Scott": "ambler-scott",
    "AMBROGI Davide": "ambrogi-davide",
    "AMBROSE David": "ambrose-david",
    "AMBROSE Joan": "ambrose-joan",
    "AMBROSE Joel": "ambrose-joel",
    "AMBROSE Kanika": "ambrose-kanika",
    "AMBROSE Mike": "ambrose-mike",
    "AMBROSINI Tommy": "ambrosini-tommy",
    "AMEEN Mark": "ameen-mark",
    "AMELIO Vincent": "amelio-vincent",
    "AMEN Luce": "amen-luce",
    "AMEND Howard T": "amend-howard-t",
    "AMENDOLA-ROGERS Adriana": "amendola-rogers-adriana",
    "AMENTA Mark": "amenta-mark",
    "AMERICAN LABORATORY, THE ": "american-laboratory",
    "AMERICAN REPERTORY THEATRE ": "american-repertory-theatre",
    "AMES Gustavo": "ames-gustavo",
    "AMES Jonathan": "ames-jonathan",
    "AMES Kirsten": "ames-kirsten",
    "AMESBURY Elisa": "amesbury-elisa",
    "AMEY Rachel": "amey-rachel",
    "AMICHAL-YEVIN Ada": "amichal-yevin-ada",
    "AMIDEI Aly Renee": "amidei-aly-renee",
    "AMIEL Denys": "amiel-denys",
    "AMIEL ": "amiel",
    "AMIES Brenton": "amies-brenton",
    "AMIES Stephanie Jayne": "amies-stephanie-jayne",
    "AMIN Dina": "amin-dina",
    "AMIRAULT Allison A": "amirault-allison-a",
    "AMIRKHANIAN Aida": "amirkhanian-aida",
    "AMIS Lola E": "amis-lola-e",
    "AMIS Martin": "amis-martin",
    "AMLEHN Paul": "amlehn-paul",
    "AMLEN Elinor": "amlen-elinor",
    "AMMA Sia": "amma-sia",
    "AMMAR Ryan": "ammar-ryan",
    "AMMERMAN John": "ammerman-john",
    "AMMIRATE Camilla": "ammirate-camilla",
    "AMO Thomas": "amo-thomas",
    "AMOASA Fasitua": "amoasa-fasitua",
    "AMOR Edward": "amor-edward",
    "AMOROS Larry": "amoros-larry",
    "AMOROSO Ronald": "amoroso-ronald",
    "AMOS Chris": "amos-chris",
    "AMOS Janet": "amos-janet",
    "AMOS Robert": "amos-robert",
    "AMOS Tori": "amos-tori",
    "AMOSA Fasitua": "amosa-fasitua",
    "AMPARANO Julie Ann": "amparano-julie-ann",
    "AMSBURY Beth": "amsbury-beth",
    "AMSBURY Zay": "amsbury-zay",
    "AMSTERDAM Diana": "amsterdam-diana",
    "AMUNDSEN Allen": "amundsen-allen",
    "AMUNDSON Connie": "amundson-connie",
    "AMY Remi": "amy-remi",
    "ANAGNOSTAKI Loula": "anagnostaki-loula",
    "ANALOGUE ": "analogue",
    "ANAND Mulk Raj": "anand-mulk-raj",
    "ANAST Jory": "anast-jory",
    "ANASTASI John": "anastasi-john",
    "ANASTASI Tom": "anastasi-tom",
    "ANASTASIO Trey": "anastasio-trey",
    "ANASTASSIOU Philip John": "anastassiou-philip-john",
    "ANCHANG Jude": "anchang-jude",
    "ANCHETA Karen": "ancheta-karen",
    "ANCLIFFE Leon": "ancliffe-leon",
    "ANCOWITZ Nancy": "ancowitz-nancy",
    "ANDERMAN Gunilla M": "anderman-gunilla-m",
    "ANDERS Christoph": "anders-christoph",
    "ANDERS Doug": "anders-doug",
    "ANDERSEN Anna": "andersen-anna",
    "ANDERSEN D R": "andersen-d-r",
    "ANDERSEN Dale": "andersen-dale",
    "ANDERSEN Daniel": "andersen-daniel",
    "ANDERSEN Dennis": "andersen-dennis",
    "ANDERSEN Emily": "andersen-emily",
    "ANDERSEN Lemon": "andersen-lemon",
    "ANDERSEN Mads Floor": "andersen-mads-floor",
    "ANDERSEN Mal": "andersen-mal",
    "ANDERSEN Marit": "andersen-marit",
    "ANDERSEN Mark": "andersen-mark",
    "ANDERSEN Paul": "andersen-paul",
    "ANDERSEN Suzanne": "andersen-suzanne",
    "ANDERSEN-BLOOMFIELD Doc": "andersen-bloomfield-doc",
    "ANDERSON Abigail": "anderson-abigail",
    "ANDERSON Adam C": "anderson-adam-c",
    "ANDERSON Adele": "anderson-adele",
    "ANDERSON Andre": "anderson-andre",
    "ANDERSON Andrew": "anderson-andrew",
    "ANDERSON Balfour": "anderson-balfour",
    "ANDERSON Barbara": "anderson-barbara",
    "ANDERSON Bart": "anderson-bart",
    "ANDERSON Beatrice": "anderson-beatrice",
    "ANDERSON Becca": "anderson-becca",
    "ANDERSON Ben": "anderson-ben",
    "ANDERSON Benedict": "anderson-benedict",
    "ANDERSON Bo": "anderson-bo",
    "ANDERSON Bonnie": "anderson-bonnie",
    "ANDERSON Brandon": "anderson-brandon",
    "ANDERSON Carol": "anderson-carol",
    "ANDERSON Cas": "anderson-cas",
    "ANDERSON Charlotte": "anderson-charlotte",
    "ANDERSON Chinita L": "anderson-chinita-l",
    "ANDERSON Christina": "anderson-christina",
    "ANDERSON Chuck": "anderson-chuck",
    "ANDERSON Clement": "anderson-clement",
    "ANDERSON Dana": "anderson-dana",
    "ANDERSON Daniel": "anderson-daniel",
    "ANDERSON Dave": "anderson-dave",
    "ANDERSON Davey": "anderson-davey",
    "ANDERSON David": "anderson-david",
    "ANDERSON Dean": "anderson-dean",
    "ANDERSON Dennis": "anderson-dennis",
    "ANDERSON Diana": "anderson-diana",
    "ANDERSON Donna Gay": "anderson-donna-gay",
    "ANDERSON Doug": "anderson-doug",
    "ANDERSON Douglas": "anderson-douglas",
    "ANDERSON Eliza": "anderson-eliza",
    "ANDERSON Ellen K": "anderson-ellen-k",
    "ANDERSON Emily": "anderson-emily",
    "ANDERSON Eric": "anderson-eric",
    "ANDERSON Erik": "anderson-erik",
    "ANDERSON Ernest": "anderson-ernest",
    "ANDERSON Eva": "anderson-eva",
    "ANDERSON Finn": "anderson-finn",
    "ANDERSON Freddy": "anderson-freddy",
    "ANDERSON Gai": "anderson-gai",
    "ANDERSON Gary L": "anderson-gary-l",
    "ANDERSON Graham": "anderson-graham",
    "ANDERSON Hilda": "anderson-hilda",
    "ANDERSON Iain F": "anderson-iain-f",
    "ANDERSON Ioanna": "anderson-ioanna",
    "ANDERSON J": "anderson-j",
    "ANDERSON Jane": "anderson-jane",
    "ANDERSON Jason": "anderson-jason",
    "ANDERSON Jen": "anderson-jen",
    "ANDERSON Jennifer Jean": "anderson-jennifer-jean",
    "ANDERSON Jim Tyler": "anderson-jim-tyler",
    "ANDERSON Jo": "anderson-jo",
    "ANDERSON John (1)": "anderson-john-1",
    "ANDERSON John (2)": "anderson-john-2",
    "ANDERSON John C": "anderson-john-c",
    "ANDERSON John Stuart": "anderson-john-stuart",
    "ANDERSON Joseph Reese": "anderson-joseph-reese",
    "ANDERSON Joy": "anderson-joy",
    "ANDERSON Jude": "anderson-jude",
    "ANDERSON Judy": "anderson-judy",
    "ANDERSON Julian": "anderson-julian",
    "ANDERSON Kate": "anderson-kate",
    "ANDERSON Kathleen McGhee": "anderson-kathleen-mcghee",
    "ANDERSON Kathy": "anderson-kathy",
    "ANDERSON Ken": "anderson-ken",
    "ANDERSON Kenneth": "anderson-kenneth",
    "ANDERSON Kent": "anderson-kent",
    "ANDERSON Kristen": "anderson-kristen",
    "ANDERSON Kyle": "anderson-kyle",
    "ANDERSON Laurie": "anderson-laurie",
    "ANDERSON Lea": "anderson-lea",
    "ANDERSON Lee": "anderson-lee",
    "ANDERSON Marilyn D": "anderson-marilyn-d",
    "ANDERSON Mark": "anderson-mark",
    "ANDERSON Mary": "anderson-mary",
    "ANDERSON Matthew S": "anderson-matthew-s",
    "ANDERSON Mattias": "anderson-mattias",
    "ANDERSON Maxwell": "anderson-maxwell",
    "ANDERSON Melody": "anderson-melody",
    "ANDERSON Michael": "anderson-michael",
    "ANDERSON Michael (1)": "anderson-michael-1",
    "ANDERSON Nancy K": "anderson-nancy-k",
    "ANDERSON Noel": "anderson-noel",
    "ANDERSON Odie": "anderson-odie",
    "ANDERSON Orjan": "anderson-orjan",
    "ANDERSON Pete": "anderson-pete",
    "ANDERSON Peter": "anderson-peter",
    "ANDERSON R A": "anderson-r-a",
    "ANDERSON Rachel": "anderson-rachel",
    "ANDERSON Randy": "anderson-randy",
    "ANDERSON Rica": "anderson-rica",
    "ANDERSON Richard": "anderson-richard",
    "ANDERSON Rita": "anderson-rita",
    "ANDERSON Rob Winn": "anderson-rob-winn",
    "ANDERSON Robert": "anderson-robert",
    "ANDERSON Robert A": "anderson-robert-a",
    "ANDERSON Robert Bruce \"Bo\"": "anderson-robert-bruce",
    "ANDERSON Rod": "anderson-rod",
    "ANDERSON Roger": "anderson-roger",
    "ANDERSON Ryan Vincent": "anderson-ryan-vincent",
    "ANDERSON Sara Pia": "anderson-sara-pia",
    "ANDERSON Shirley": "anderson-shirley",
    "ANDERSON Stanice": "anderson-stanice",
    "ANDERSON Steven": "anderson-steven",
    "ANDERSON Steven C": "anderson-steven-c",
    "ANDERSON T Dianne": "anderson-t-dianne",
    "ANDERSON Tammy": "anderson-tammy",
    "ANDERSON Trevor": "anderson-trevor",
    "ANDERSON Valdemar": "anderson-valdemar",
    "ANDERSON Valetta": "anderson-valetta",
    "ANDERSON Walt": "anderson-walt",
    "ANDERSON Will": "anderson-will",
    "ANDERSON COLLEGE SOUTH CAROLINA ": "anderson-college-south-carolina",
    "ANDERSON III T J": "anderson-iii-t-j",
    "ANDERSON-BLOOMFIELD Doc": "anderson-bloomfield-doc",
    "ANDERSON-COBB Nicole": "anderson-cobb-nicole",
    "ANDERSON-LOPEZ Kristen": "anderson-lopez-kristen",
    "ANDERSSON Benny": "andersson-benny",
    "ANDERSSON Kris": "andersson-kris",
    "ANDERSSON Mattias": "andersson-mattias",
    "ANDERSSON Ulla": "andersson-ulla",
    "ANDERT John": "andert-john",
    "ANDINO Eduardo": "andino-eduardo",
    "ANDO Yuka": "ando-yuka",
    "ANDOH Adjoa": "andoh-adjoa",
    "ANDOH-MENSON Kweku": "andoh-menson-kweku",
    "ANDOLORA Tom": "andolora-tom",
    "ANDRACCHI Erica": "andracchi-erica",
    "ANDRADE Christopher": "andrade-christopher",
    "ANDRADE Jorge": "andrade-jorge",
    "ANDRADE Monica": "andrade-monica",
    "ANDRADE Suzanne": "andrade-suzanne",
    "ANDRE Marion": "andre-marion",
    "ANDRE Rolls": "andre-rolls",
    "ANDRE Ty": "andre-ty",
    "ANDREACCHI Grace": "andreacchi-grace",
    "ANDREADI Ioli": "andreadi-ioli",
    "ANDREANI Sydney": "andreani-sydney",
    "ANDREAS Michael": "andreas-michael",
    "ANDREASON Don": "andreason-don",
    "ANDREI Amanda": "andrei-amanda",
    "ANDREI Julian": "andrei-julian",
    "ANDREINI John": "andreini-john",
    "ANDREIS Sandra Karloina": "andreis-sandra-karloina",
    "ANDREJKO David Alex": "andrejko-david-alex",
    "ANDRENELLI Cid": "andrenelli-cid",
    "ANDREOTTOLA Marc": "andreottola-marc",
    "ANDRES Brett": "andres-brett",
    "ANDREW Mark": "andrew-mark",
    "ANDREW Simon": "andrew-simon",
    "ANDREWA Peter": "andrewa-peter",
    "ANDREWARTHA Jessica": "andrewartha-jessica",
    "ANDREWS A P": "andrews-a-p",
    "ANDREWS Alison": "andrews-alison",
    "ANDREWS Andy": "andrews-andy",
    "ANDREWS Angeline": "andrews-angeline",
    "ANDREWS Bart": "andrews-bart",
    "ANDREWS Benedict": "andrews-benedict",
    "ANDREWS Beverley": "andrews-beverley",
    "ANDREWS Brian": "andrews-brian",
    "ANDREWS Casey Jay": "andrews-casey-jay",
    "ANDREWS Damon": "andrews-damon",
    "ANDREWS Debbie": "andrews-debbie",
    "ANDREWS Dwayne": "andrews-dwayne",
    "ANDREWS Graham": "andrews-graham",
    "ANDREWS Isobel": "andrews-isobel",
    "ANDREWS Jan": "andrews-jan",
    "ANDREWS Jenny": "andrews-jenny",
    "ANDREWS Jesse": "andrews-jesse",
    "ANDREWS John Neville": "andrews-john-neville",
    "ANDREWS Kate": "andrews-kate",
    "ANDREWS Kaye": "andrews-kaye",
    "ANDREWS Nick": "andrews-nick",
    "ANDREWS Norman": "andrews-norman",
    "ANDREWS Regina": "andrews-regina",
    "ANDREWS Richard": "andrews-richard",
    "ANDREWS Ross": "andrews-ross",
    "ANDREWS Stephen": "andrews-stephen",
    "ANDREWS Steve": "andrews-steve",
    "ANDREWS Tim": "andrews-tim",
    "ANDREWS Vicky": "andrews-vicky",
    "ANDREWS William": "andrews-william",
    "ANDREYEV Leonid": "andreyev-leonid",
    "ANDRIANO Vincent": "andriano-vincent",
    "ANDRIELLO Rita": "andriello-rita",
    "ANDRIST Eric": "andrist-eric",
    "ANDRON Ben": "andron-ben",
    "ANDRONICOS Kelly": "andronicos-kelly",
    "ANDRUCKI Martin": "andrucki-martin",
    "ANDRUSEWICZ Marie": "andrusewicz-marie",
    "ANELLI Paul": "anelli-paul",
    "ANFIELD Alexandria": "anfield-alexandria",
    "ANFILOGOFF Tim": "anfilogoff-tim",
    "ANG Gay Pin": "ang-gay-pin",
    "ANG Michelle": "ang-michelle",
    "ANGEL Leonard": "angel-leonard",
    "ANGEL Marie": "angel-marie",
    "ANGEL Nick": "angel-nick",
    "ANGEL Sabina": "angel-sabina",
    "ANGEL EXIT THEATRE ": "angel-exit-theatre",
    "ANGELICA Ethan": "angelica-ethan",
    "ANGELINI Claudio": "angelini-claudio",
    "ANGELINI Kieran": "angelini-kieran",
    "ANGELINI Tony": "angelini-tony",
    "ANGELL Glynis": "angell-glynis",
    "ANGELL Jeannette": "angell-jeannette",
    "ANGELO Judy Hart": "angelo-judy-hart",
    "ANGELOCH Alexandra": "angeloch-alexandra",
    "ANGELOS Maureen": "angelos-maureen",
    "ANGELOS Moe": "angelos-moe",
    "ANGELOU Maya": "angelou-maya",
    "ANGELS AND VIRGINS THEATRE COMPANY ": "angels-and-virgins-theatre-company",
    "ANGELS OF DISORDER ": "angels-of-disorder",
    "ANGELSON Sophie": "angelson-sophie",
    "ANGERSON Jeremy": "angerson-jeremy",
    "ANGLEY Cassie": "angley-cassie",
    "ANGLIN Michelle": "anglin-michelle",
    "ANGRESS Therese": "angress-therese",
    "ANGUS Gemma": "angus-gemma",
    "ANHALT Edward": "anhalt-edward",
    "ANHOLT Maddy": "anholt-maddy",
    "ANISSIMOVA Evelina": "anissimova-evelina",
    "ANKER Charlotte": "anker-charlotte",
    "ANKETELL Christine": "anketell-christine",
    "ANKUR PRODUCTIONS ADULT THEATRE WORKSHOP ": "ankur-productions-adult-theatre-workshop",
    "ANNA Anna": "anna-anna",
    "ANNA PROJECT ": "anna-project",
    "ANNAN Jim": "annan-jim",
    "ANNE Catherine": "anne-catherine",
    "ANNEN David": "annen-david",
    "ANNING Jane": "anning-jane",
    "ANNIS Melisa": "annis-melisa",
    "ANNOYANCE THEATER ": "annoyance-theater",
    "ANNTARES Tita": "anntares-tita",
    "ANON ": "anon",
    "ANONYMOUS ": "anonymous",
    "ANONYMOUS IRANIAN ": "anonymous-iranian",
    "ANOSA Rima": "anosa-rima",
    "ANOUILH Jean": "anouilh-jean",
    "ANSART Jim": "ansart-jim",
    "ANSDELL David": "ansdell-david",
    "ANSELL Adam J": "ansell-adam-j",
    "ANSELL Rod": "ansell-rod",
    "ANSELM Ludmila": "anselm-ludmila",
    "ANSELMI Barbara": "anselmi-barbara",
    "ANSELMI Marilynn Barner": "anselmi-marilynn-barner",
    "ANSELMO Christopher Michael": "anselmo-christopher-michael",
    "ANSELMO Tom": "anselmo-tom",
    "ANSKI Shalom": "anski-shalom",
    "ANSON Joe": "anson-joe",
    "ANSORGE Peter": "ansorge-peter",
    "ANSTRUTHER Gerald": "anstruther-gerald",
    "ANTAL Paul": "antal-paul",
    "ANTAR Eddie": "antar-eddie",
    "ANTHEIL George": "antheil-george",
    "ANTHILL THEATRE ": "anthill-theatre",
    "ANTHONY Adelina": "anthony-adelina",
    "ANTHONY Brian": "anthony-brian",
    "ANTHONY C L": "anthony-c-l",
    "ANTHONY Christina": "anthony-christina",
    "ANTHONY Dan": "anthony-dan",
    "ANTHONY Darren": "anthony-darren",
    "ANTHONY Earl": "anthony-earl",
    "ANTHONY Edward": "anthony-edward",
    "ANTHONY John": "anthony-john",
    "ANTHONY Marcus": "anthony-marcus",
    "ANTHONY Mark": "anthony-mark",
    "ANTHONY Meredith": "anthony-meredith",
    "ANTHONY Peter": "anthony-peter",
    "ANTHONY Robert": "anthony-robert",
    "ANTHONY Rock": "anthony-rock",
    "ANTHONY Terence": "anthony-terence",
    "ANTHONY Terrell": "anthony-terrell",
    "ANTHONY Trey": "anthony-trey",
    "ANTHONY ": "anthony",
    "ANTIEL Cory": "antiel-cory",
    "ANTLER THEATRE ": "antler-theatre",
    "ANTOLINI Jeanie": "antolini-jeanie",
    "ANTOLJAK Nina": "antoljak-nina",
    "ANTON Dorothy": "anton-dorothy",
    "ANTON Greg": "anton-greg",
    "ANTONACCI Greg": "antonacci-greg",
    "ANTONAKES Michael": "antonakes-michael",
    "ANTONE Tiffany": "antone-tiffany",
    "ANTONIO James": "antonio-james",
    "ANTONIO Raf": "antonio-raf",
    "ANTONIO Salvatore": "antonio-salvatore",
    "ANTONIOLI Courtney": "antonioli-courtney",
    "ANTONIOLI Siobhan": "antonioli-siobhan",
    "ANTONOCCI Greg": "antonocci-greg",
    "ANTROBUS John": "antrobus-john",
    "ANTRUM Janyia": "antrum-janyia",
    "ANU PRODUCTIONS ": "anu-productions",
    "ANWAR Keith": "anwar-keith",
    "ANWAR Subika": "anwar-subika",
    "ANWEN Gabrielle": "anwen-gabrielle",
    "ANYA Rain": "anya-rain",
    "ANZENGRUBER Ludwig": "anzengruber-ludwig",
    "ANZIA Lys": "anzia-lys",
    "ANZUELO David": "anzuelo-david",
    "AOKI Brenda Wong": "aoki-brenda-wong",
    "AOKI Dance": "aoki-dance",
    "AP EMRYS Jonathan": "ap-emrys-jonathan",
    "APARICIO Rebecca": "aparicio-rebecca",
    "APATICIO Ariel": "apaticio-ariel",
    "APELBAUM Stanley": "apelbaum-stanley",
    "APHRODITE Brigitte": "aphrodite-brigitte",
    "APIO Alan": "apio-alan",
    "APKER Susan": "apker-susan",
    "APLIN Jackie": "aplin-jackie",
    "APODACA Jackie": "apodaca-jackie",
    "APOLINAR Danny": "apolinar-danny",
    "APOLLINAIRE Guillaume": "apollinaire-guillaume",
    "APOLO Ignacio": "apolo-ignacio",
    "APONTE Marco": "aponte-marco",
    "APOSTOL Troy": "apostol-troy",
    "APOSTOLINA Steve": "apostolina-steve",
    "APPEL Allan": "appel-allan",
    "APPEL Camila": "appel-camila",
    "APPEL Dori": "appel-dori",
    "APPEL Elizabeth": "appel-elizabeth",
    "APPEL Greg": "appel-greg",
    "APPEL Jacob M": "appel-jacob-m",
    "APPEL Sonya": "appel-sonya",
    "APPELBAUM Marci": "appelbaum-marci",
    "APPELL Don": "appell-don",
    "APPELL Elizabeth": "appell-elizabeth",
    "APPINO Nikki": "appino-nikki",
    "APPLE Gary": "apple-gary",
    "APPLE Lawrence": "apple-lawrence",
    "APPLEBAUM Jessica Kaplow": "applebaum-jessica-kaplow",
    "APPLEBEE Bec": "applebee-bec",
    "APPLEBY Damian": "appleby-damian",
    "APPLEBY Jane": "appleby-jane",
    "APPLEBY Sue": "appleby-sue",
    "APPLEFORD David": "appleford-david",
    "APPLEGARTH Margaret T": "applegarth-margaret-t",
    "APPLEGATE Joe": "applegate-joe",
    "APPLEMAN Herbert": "appleman-herbert",
    "APPLEMAN M H": "appleman-m-h",
    "APPLETON Eric": "appleton-eric",
    "APPLIN Rebecca": "applin-rebecca",
    "APPOLLIS Basil": "appollis-basil",
    "APPRENTICED ACTORS COMPANY, THE ": "apprenticed-actors-company",
    "APPS Roy": "apps-roy",
    "APRAHAMIAN Steven": "aprahamian-steven",
    "APRILL Arnold": "aprill-arnold",
    "APSTEIN Theodore": "apstein-theodore",
    "APUKHTINE Alexis": "apukhtine-alexis",
    "APULEIUS ": "apuleius",
    "AQUENO Frank": "aqueno-frank",
    "AQUILA Pieter": "aquila-pieter",
    "AQUILANTE Michael Tommasone": "aquilante-michael-tommasone",
    "AQUILER Louis": "aquiler-louis",
    "AQUILINA Corinne": "aquilina-corinne",
    "AQUILINA Danielle": "aquilina-danielle",
    "AQUINO Nina": "aquino-nina",
    "AQUINO Regina": "aquino-regina",
    "ARACALANDANZA ": "aracalandanza",
    "ARAD GOCH ": "arad-goch",
    "ARAGNO Riccardo": "aragno-riccardo",
    "ARAGON Clyde James": "aragon-clyde-james",
    "ARAGON Joseph": "aragon-joseph",
    "ARAGON Louis": "aragon-louis",
    "ARAIZA Albert Antonio": "araiza-albert-antonio",
    "ARAIZA J Ed": "araiza-j-ed",
    "ARAKAWA Suzanne": "arakawa-suzanne",
    "ARAN Catherine": "aran-catherine",
    "ARANAS Pilbuen": "aranas-pilbuen",
    "ARANCIO Lawrence": "arancio-lawrence",
    "ARANEDA Cecilia": "araneda-cecilia",
    "ARANGIO Carmela": "arangio-carmela",
    "ARANHA Ray": "aranha-ray",
    "ARANSON Jack": "aranson-jack",
    "ARAPAI Arnette": "arapai-arnette",
    "ARATA Luis O": "arata-luis-o",
    "ARAUJO Luis": "araujo-luis",
    "ARAUJO Suzette": "araujo-suzette",
    "ARAVAYA Gene": "aravaya-gene",
    "ARBATOVA Maria": "arbatova-maria",
    "ARBEIT Rachel": "arbeit-rachel",
    "ARBER Gyda": "arber-gyda",
    "ARBER Steve": "arber-steve",
    "ARBERY Will": "arbery-will",
    "ARBUCIAS Joyce": "arbucias-joyce",
    "ARBUS Doon": "arbus-doon",
    "ARBUZOV Aleksei": "arbuzov-aleksei",
    "ARCA Jefferson": "arca-jefferson",
    "ARCADE Penny": "arcade-penny",
    "ARCESE Peter Vincent": "arcese-peter-vincent",
    "ARCH Jeff": "arch-jeff",
    "ARCHAMBAULT Francois": "archambault-francois",
    "ARCHBOLD Alan": "archbold-alan",
    "ARCHDEACON Sarah": "archdeacon-sarah",
    "ARCHER Daniel": "archer-daniel",
    "ARCHER Dudley": "archer-dudley",
    "ARCHER Elizabeth": "archer-elizabeth",
    "ARCHER Jeffrey": "archer-jeffrey",
    "ARCHER John": "archer-john",
    "ARCHER Kendall": "archer-kendall",
    "ARCHER Lavern": "archer-lavern",
    "ARCHER Robyn": "archer-robyn",
    "ARCHER Rodney": "archer-rodney",
    "ARCHER William": "archer-william",
    "ARCHIBALD Dan": "archibald-dan",
    "ARCHIBALD David": "archibald-david",
    "ARCHIBALD Douglas (Rupert)": "archibald-douglas-rupert",
    "ARCHIBALD Janet": "archibald-janet",
    "ARCHIBALD William": "archibald-william",
    "ARCIERI D T": "arcieri-d-t",
    "ARCINIEGAS Diego": "arciniegas-diego",
    "ARCO John R": "arco-john-r",
    "ARCURI Vincent James": "arcuri-vincent-james",
    "ARDAL Maja": "ardal-maja",
    "ARDEN Andrea": "arden-andrea",
    "ARDEN Annabel": "arden-annabel",
    "ARDEN Chris": "arden-chris",
    "ARDEN Ilayda": "arden-ilayda",
    "ARDEN Jane": "arden-jane",
    "ARDEN John": "arden-john",
    "ARDEN Leslie": "arden-leslie",
    "ARDERN Jonny": "ardern-jonny",
    "ARDERN Stuart": "ardern-stuart",
    "ARDIFF Karen": "ardiff-karen",
    "ARDITO Carlo": "ardito-carlo",
    "ARDITTI Michael": "arditti-michael",
    "ARDITTI Philip": "arditti-philip",
    "ARDO Zsuzsanna": "ardo-zsuzsanna",
    "ARDOLINO John": "ardolino-john",
    "ARDOV Viktor": "ardov-viktor",
    "ARDREY Robert": "ardrey-robert",
    "ARE David": "are-david",
    "ARELINA Pietro": "arelina-pietro",
    "AREMU Aduke": "aremu-aduke",
    "ARENDS Mark": "arends-mark",
    "ARENS Kellie": "arens-kellie",
    "ARENT Arthur": "arent-arthur",
    "ARETINO Pietro": "aretino-pietro",
    "ARGALL Liz": "argall-liz",
    "ARGALL T Gregory": "argall-t-gregory",
    "ARGENT Geoffrey Alan": "argent-geoffrey-alan",
    "ARGENT Rod": "argent-rod",
    "ARGENT Sarah": "argent-sarah",
    "ARGETSINGER Gerald S": "argetsinger-gerald-s",
    "ARGUE Karl": "argue-karl",
    "ARIADONE COMPANY ": "ariadone-company",
    "ARIAS Joey": "arias-joey",
    "ARIAS Leila": "arias-leila",
    "ARIAS Lola": "arias-lola",
    "ARIAS Maria-Jose Rague": "arias-maria-jose-rague",
    "ARIAS Roy": "arias-roy",
    "ARIAV Tali": "ariav-tali",
    "ARICO Ashley": "arico-ashley",
    "ARIEL TEATR ": "ariel-teatr",
    "ARIETI Olivia": "arieti-olivia",
    "ARIMOTO Kendra Chiyoko": "arimoto-kendra-chiyoko",
    "ARIN Jesper": "arin-jesper",
    "ARIOSTO Lodovico": "ariosto-lodovico",
    "ARISS Paddy": "ariss-paddy",
    "ARISS Peter": "ariss-peter",
    "ARISTARCO Maria": "aristarco-maria",
    "ARISTIDOU Dinos": "aristidou-dinos",
    "ARISTIZABAL Hector": "aristizabal-hector",
    "ARISTOPHANES ": "aristophanes",
    "ARIZA Rene": "ariza-rene",
    "ARIZMENDI Yareli": "arizmendi-yareli",
    "ARK THEATRE ": "ark-theatre",
    "ARKASS George": "arkass-george",
    "ARKEKETA Annette": "arkeketa-annette",
    "ARKHIPOV Alexander": "arkhipov-alexander",
    "ARKIN Alan": "arkin-alan",
    "ARKY Darian": "arky-darian",
    "ARKY Jake Marshall": "arky-jake-marshall",
    "ARLEN Albert": "arlen-albert",
    "ARLEN Harold": "arlen-harold",
    "ARLEN Michael": "arlen-michael",
    "ARLENE KARON STUDENTS ": "arlene-karon-students",
    "ARLETT Vera I": "arlett-vera-i",
    "ARLEY Catherine": "arley-catherine",
    "ARM Aaron": "arm-aaron",
    "ARMAH Esther": "armah-esther",
    "ARMAND Clara": "armand-clara",
    "ARMANDO Bruno": "armando-bruno",
    "ARMANI Nora": "armani-nora",
    "ARMBRUSTER Heidi": "armbruster-heidi",
    "ARME Robert": "arme-robert",
    "ARMENANTE Jillian": "armenante-jillian",
    "ARMENTO Kevin": "armento-kevin",
    "ARMENTO Paul": "armento-paul",
    "ARMER Jamie": "armer-jamie",
    "ARMES Helen": "armes-helen",
    "ARMESTO Carlos": "armesto-carlos",
    "ARMESTO Sebastian": "armesto-sebastian",
    "ARMFIELD Neil": "armfield-neil",
    "ARMIN Gerald": "armin-gerald",
    "ARMISTEAD Julian": "armistead-julian",
    "ARMITAGE Alex": "armitage-alex",
    "ARMITAGE Andy": "armitage-andy",
    "ARMITAGE Jenny": "armitage-jenny",
    "ARMITAGE Katharine": "armitage-katharine",
    "ARMITAGE Kimo": "armitage-kimo",
    "ARMITAGE Marigold": "armitage-marigold",
    "ARMITAGE Simon": "armitage-simon",
    "ARMITSTEAD Julian": "armitstead-julian",
    "ARMITT David": "armitt-david",
    "ARMOUR Toby": "armour-toby",
    "ARMSTRONG Alana": "armstrong-alana",
    "ARMSTRONG Anthony": "armstrong-anthony",
    "ARMSTRONG Billie Joe": "armstrong-billie-joe",
    "ARMSTRONG Bob": "armstrong-bob",
    "ARMSTRONG Caitlin": "armstrong-caitlin",
    "ARMSTRONG Charlotte": "armstrong-charlotte",
    "ARMSTRONG Craig": "armstrong-craig",
    "ARMSTRONG Dave": "armstrong-dave",
    "ARMSTRONG Doug": "armstrong-doug",
    "ARMSTRONG Frank": "armstrong-frank",
    "ARMSTRONG Gareth": "armstrong-gareth",
    "ARMSTRONG Gordon": "armstrong-gordon",
    "ARMSTRONG Ian": "armstrong-ian",
    "ARMSTRONG James": "armstrong-james",
    "ARMSTRONG Jo-Anne": "armstrong-jo-anne",
    "ARMSTRONG John": "armstrong-john",
    "ARMSTRONG Jon": "armstrong-jon",
    "ARMSTRONG Joy": "armstrong-joy",
    "ARMSTRONG Ken": "armstrong-ken",
    "ARMSTRONG Ken (1)": "armstrong-ken-1",
    "ARMSTRONG Margaret": "armstrong-margaret",
    "ARMSTRONG Michael": "armstrong-michael",
    "ARMSTRONG Neil": "armstrong-neil",
    "ARMSTRONG Robin": "armstrong-robin",
    "ARMSTRONG William": "armstrong-william",
    "ARMSTRONG-DE VREEZE Pamela": "armstrong-de-vreeze-pamela",
    "ARMSTRONG-TAYLOR Tim": "armstrong-taylor-tim",
    "ARNARSSON Thorleifur Orn": "arnarsson-thorleifur-orn",
    "ARNDT Walter": "arndt-walter",
    "ARNEL Seamus": "arnel-seamus",
    "ARNESON Donald": "arneson-donald",
    "ARNESON Heidi": "arneson-heidi",
    "ARNEST Lauren": "arnest-lauren",
    "ARNEST Mark": "arnest-mark",
    "ARNEY Helen": "arney-helen",
    "ARNFIELD Jane": "arnfield-jane",
    "ARNGRIM Alison": "arngrim-alison",
    "ARNHALT Edward": "arnhalt-edward",
    "ARNO Owen G": "arno-owen-g",
    "ARNOLD Andy": "arnold-andy",
    "ARNOLD Anthony": "arnold-anthony",
    "ARNOLD Ben": "arnold-ben",
    "ARNOLD Bill": "arnold-bill",
    "ARNOLD Bill (1)": "arnold-bill-1",
    "ARNOLD C D": "arnold-c-d",
    "ARNOLD Camilla": "arnold-camilla",
    "ARNOLD Damien": "arnold-damien",
    "ARNOLD Daniel": "arnold-daniel",
    "ARNOLD Diana": "arnold-diana",
    "ARNOLD Jessica": "arnold-jessica",
    "ARNOLD John": "arnold-john",
    "ARNOLD Josh": "arnold-josh",
    "ARNOLD Kenneth": "arnold-kenneth",
    "ARNOLD Lucy": "arnold-lucy",
    "ARNOLD Peter": "arnold-peter",
    "ARNOLD Scotty": "arnold-scotty",
    "ARNOLD William": "arnold-william",
    "ARNON Valerie": "arnon-valerie",
    "ARNOS Tori": "arnos-tori",
    "ARNOSKY Brian": "arnosky-brian",
    "ARNOTT Amanda": "arnott-amanda",
    "ARNOTT Deborah": "arnott-deborah",
    "ARNOTT Paul": "arnott-paul",
    "ARNOTT Peter": "arnott-peter",
    "ARNOTT Peter (1)": "arnott-peter-1",
    "ARNOTT Peter D": "arnott-peter-d",
    "ARNOTT W G": "arnott-w-g",
    "ARNSTEIN Felix G": "arnstein-felix-g",
    "ARNTSON Bruce": "amtson-bruce",
    "ARNTZ James": "arntz-james",
    "ARON Adrianne": "aron-adrianne",
    "ARON Geraldine": "aron-geraldine",
    "ARON Wendy": "aron-wendy",
    "ARONEAU Elisabeth": "aroneau-elisabeth",
    "ARONOFF Eddie": "aronoff-eddie",
    "ARONOFF Linda": "aronoff-linda",
    "ARONOFF Marc": "aronoff-marc",
    "ARONOV Michael": "aronov-michael",
    "ARONOVITCH Lawrence": "aronovitch-lawrence",
    "ARONOWITZ Sonya": "aronowitz-sonya",
    "ARONSON Alvin": "aronson-alvin",
    "ARONSON Barton": "aronson-barton",
    "ARONSON Billy": "aronson-billy",
    "ARONSON Henry": "aronson-henry",
    "ARONSON Linda": "aronson-linda",
    "ARONSON Shari": "aronson-shari",
    "ARONSON William": "aronson-william",
    "ARONSTEN Chris": "aronsten-chris",
    "ARONVITCH Lawrence": "aronvitch-lawrence",
    "ARORA Renu": "arora-renu",
    "AROUT Gabriel": "arout-gabriel",
    "ARQUEROS Joelle": "arqueros-joelle",
    "ARRABAL Fernando": "arrabal-fernando",
    "ARRAHALL ": "arrahall",
    "ARRAN Mathew": "arran-mathew",
    "ARRAND Ellen": "arrand-ellen",
    "ARREOLA Daniel": "arreola-daniel",
    "ARRICK Larry": "arrick-larry",
    "ARRIGHI Mel": "arrighi-mel",
    "ARRINGTON Don": "arrington-don",
    "ARRINGTON James": "arrington-james",
    "ARRINGTON John": "arrington-john",
    "ARRIVEE Alan": "arrivee-alan",
    "ARRIVI Fransisco": "arrivi-fransisco",
    "ARROWSMITH Beverly A": "arrowsmith-beverly-a",
    "ARROWSMITH William": "arrowsmith-william",
    "ARROYO Rane": "arroyo-rane",
    "ARSENAULT Cynthia Faith": "arsenault-cynthia-faith",
    "ARSENAULT Holly": "arsenault-holly",
    "ARSENEAUX Debbi": "arseneaux-debbi",
    "ARSHAD Sameer": "arshad-sameer",
    "ARSLANIAN Araxi": "arslanian-araxi",
    "ART HOUSE PRODUCTIONS ": "art-house-productions",
    "ARTAU Estrella": "artau-estrella",
    "ARTAUD Antonin": "artaud-antonin",
    "ARTHUR Alan": "arthur-alan",
    "ARTHUR Amy": "arthur-amy",
    "ARTHUR Andie": "arthur-andie",
    "ARTHUR Dave": "arthur-dave",
    "ARTHUR David": "arthur-david",
    "ARTHUR Dorne": "arthur-dorne",
    "ARTHUR Frank": "arthur-frank",
    "ARTHUR Robin": "arthur-robin",
    "ARTHUR Tabitha": "arthur-tabitha",
    "ARTHUR Tim": "arthur-tim",
    "ARTHUR Toni": "arthur-toni",
    "ARTICULATE ELBOW ": "articulate-elbow",
    "ARTIGUE Kevin": "artigue-kevin",
    "ARTISTE Cindy": "artiste-cindy",
    "ARUMBAKKAM Abhi": "arumbakkam-abhi",
    "ARUMEMI Victor": "arumemi-victor",
    "ARUNDEL Mark": "arundel-mark",
    "ARUNDEL Rex Howard": "arundel-rex-howard",
    "ARZEN Nic": "arzen-nic",
    "ARZOOMANIAN Ralph G": "arzoomanian-ralph-g",
    "ARZOUMANIAN Alexander": "arzoumanian-alexander",
    "ARZT Thomas": "arzt-thomas"
  }
};