export default {
  "metadata": {
    "results": 387,
    "timeStamp": "2025-12-05T21:21:55.592Z",
    "url": "https://www.doollee.com/PlaywrightsA/A_playwrights_s-z.php"
  },
  "authors": {
    "ASADOUR Zabel": "asadour-zabel",
    "ASAF George": "asaf-george",
    "ASARE Masi": "asare-masi",
    "ASARE-BEDIAKO Barbara K": "asare-bediako-barbara-k",
    "ASARO Tony": "asaro-tony",
    "ASBURY Peny": "asbury-peny",
    "ASCH Naomi": "asch-naomi",
    "ASCH Sholom": "asch-sholom",
    "ASCHER Kenny": "ascher-kenny",
    "ASCHOFF Maureen Jane": "aschoff-maureen-jane",
    "ASENSIO Ana": "asensio-ana",
    "ASERMELY Albert": "asermely-albert",
    "ASGARALI F N": "asgarali-f-n",
    "ASGOLD S": "asgold-s",
    "ASH Kathryn": "ash-kathryn",
    "ASH Kevin L": "ash-kevin-l",
    "ASH Margi-Brown": "ash-margi-brown",
    "ASHANTI Kahlil": "ashanti-kahlil",
    "ASHBERY John": "ashbery-john",
    "ASHBROOK Taylor": "ashbrook-taylor",
    "ASHBY James Sandlin": "ashby-james-sandlin",
    "ASHBY Sue": "ashby-sue",
    "ASHBY Sylvia": "ashby-sylvia",
    "ASHBY William Mobile": "ashby-william-mobile",
    "ASHBY-ROCK Jonathan": "ashby-rock-jonathan",
    "ASHCROFT Ceri": "ashcroft-ceri",
    "ASHCROFT Cloam": "ashcroft-cloam",
    "ASHCROFT Jefny": "ashcroft-jefny",
    "ASHCROFT Mike": "ashcroft-mike",
    "ASHDOWN Catharine": "ashdown-catharine",
    "ASHDOWN Niall": "ashdown-niall",
    "ASHDOWNE Olivia": "ashdowne-olivia",
    "ASHE Eugene": "ashe-eugene",
    "ASHE Keir": "ashe-keir",
    "ASHE Patrick": "ashe-patrick",
    "ASHEN Sophia": "ashen-sophia",
    "ASHER A B": "asher-a-b",
    "ASHER Cynthia Weiss": "asher-cynthia-weiss",
    "ASHER David": "asher-david",
    "ASHER Ron": "asher-ron",
    "ASHER Sandra Fenichel": "asher-sandra-fenichel",
    "ASHFORD David": "ashford-david",
    "ASHFORD John": "ashford-john",
    "ASHIZAWA Izumi": "ashizawa-izumi",
    "ASHKENASI Danny": "ashkenasi-danny",
    "ASHLEY Bob": "ashley-bob",
    "ASHLEY Christopher": "ashley-christopher",
    "ASHLEY Franklin": "ashley-franklin",
    "ASHLEY Jonathan": "ashley-jonathan",
    "ASHLEY Richard": "ashley-richard",
    "ASHLEY Trevor": "ashley-trevor",
    "ASHLEY William": "ashley-william",
    "ASHMAN Daniel": "ashman-daniel",
    "ASHMAN Howard": "ashman-howard",
    "ASHMORE Basil": "ashmore-basil",
    "ASHMORE Olly": "ashmore-olly",
    "ASHMORE Peter": "ashmore-peter",
    "ASHPITEL Ian": "ashpitel-ian",
    "ASHRAF Shazia": "ashraf-shazia",
    "ASHTON Barney": "ashton-barney",
    "ASHTON David": "ashton-david",
    "ASHTON E Bruce": "ashton-e-bruce",
    "ASHTON Emily": "ashton-emily",
    "ASHTON John": "ashton-john",
    "ASHTON Leandra": "ashton-leandra",
    "ASHTON Louisa": "ashton-louisa",
    "ASHTON Lysander": "ashton-lysander",
    "ASHTON Michael": "ashton-michael",
    "ASHTON Michael (1)": "ashton-michael-1",
    "ASHTON Michelle": "ashton-michelle",
    "ASHTON Nik": "ashton-nik",
    "ASHTON Penny": "ashton-penny",
    "ASHTON Wayne": "ashton-wayne",
    "ASHTON William": "ashton-william",
    "ASHTON Zawe": "ashton-zawe",
    "ASHWANDER Donald": "ashwander-donald",
    "ASHWELL Charlie": "ashwell-charlie",
    "ASHWORTH Arthur": "ashworth-arthur",
    "ASHWORTH Dan": "ashworth-dan",
    "AS-IF PRODUCTIONS ": "as-if-productions",
    "ASIIMWE Deborah": "asiimwe-deborah",
    "ASIKA Nkemba": "asika-nkemba",
    "ASIMOW Dyanne": "asimow-dyanne",
    "ASIS Stan": "asis-stan",
    "ASISTO Lesley": "asisto-lesley",
    "ASIYAMA Yaw": "asiyama-yaw",
    "ASIYANBI Bode": "asiyanbi-bode",
    "ASJES Alexa": "asjes-alexa",
    "ASKARI Brent": "askari-brent",
    "ASKEW Benjamin": "askew-benjamin",
    "ASKEW Maria": "askew-maria",
    "ASKHU Shepsu": "askhu-shepsu",
    "ASKIN Patrick": "askin-patrick",
    "ASKINS Rob": "askins-rob",
    "ASKINS Robert": "askins-robert",
    "ASLAN-LEVY Eylon": "aslan-levy-eylon",
    "ASMAR Tamara": "asmar-tamara",
    "ASMUNDSSON Doris R": "asmundsson-doris-r",
    "ASMUS James": "asmus-james",
    "ASMUSSEN Peter": "asmussen-peter",
    "ASPENGREN Kate": "aspengren-kate",
    "ASPINALL Mark": "aspinall-mark",
    "ASPINALL Steve": "aspinall-steve",
    "ASPINALL Tim": "aspinall-tim",
    "ASPLIN Henry": "asplin-henry",
    "ASRIEL Benjamin": "asriel-benjamin",
    "ASSAF Andrea": "assaf-andrea",
    "ASSANTE G A": "assante-g-a",
    "ASSANTE Isabelle": "assante-isabelle",
    "ASSEFA Yonas": "assefa-yonas",
    "ASSELIN Sara Jeanne": "asselin-sara-jeanne",
    "ASSELSTINE Robert": "asselstine-robert",
    "ASSEMBLY THEATRE PROJECT ": "assembly-theatre-project",
    "ASSENG Protais": "asseng-protais",
    "ASSINDER James": "assinder-james",
    "ASSINDER Peter": "assinder-peter",
    "ASSIS Luis": "assis-luis",
    "ASTBURY Tamsin": "astbury-tamsin",
    "ASTLE David": "astle-david",
    "ASTLE Robert": "astle-robert",
    "ASTLEY Tim": "astley-tim",
    "ASTON Manuel": "aston-manuel",
    "ASTON Mark": "aston-mark",
    "ASTON Matt": "aston-matt",
    "ASTON Nell": "aston-nell",
    "ASTORINO Amedeo": "astorino-amedeo",
    "ASTRACHAN Margot W": "astrachan-margot-w",
    "ASTRAL PLAYERS ": "astral-players",
    "ATABAI Kamyar": "atabai-kamyar",
    "ATACK Timothy X": "atack-timothy-x",
    "ATAIE Iraj Jannatie": "ataie-iraj-jannatie",
    "ATALLAH Mataz": "atallah-mataz",
    "ATCHESON Katie": "atcheson-katie",
    "ATEBE Camille": "atebe-camille",
    "ATENASIO Lisa": "atenasio-lisa",
    "ATERMAN Peter": "aterman-peter",
    "ATFIELD David": "atfield-david",
    "ATHAS-VAZQUEZ Geraldine": "athas-vazquez-geraldine",
    "ATHAYDE Roberto": "athayde-roberto",
    "ATHERDEN Geoffrey": "atherden-geoffrey",
    "ATHERTON Julie": "atherton-julie",
    "ATHEY Ron": "athey-ron",
    "ATIK Chiara": "atik-chiara",
    "ATIK Jeffery": "atik-jeffery",
    "ATIM Sheila": "atim-sheila",
    "ATKEY Mel": "atkey-mel",
    "ATKIN Barbara B": "atkin-barbara-b",
    "ATKIN Flora B": "atkin-flora-b",
    "ATKIN Louis": "atkin-louis",
    "ATKIN Mark": "atkin-mark",
    "ATKIN Pete": "atkin-pete",
    "ATKINS Alan": "atkins-alan",
    "ATKINS Damien": "atkins-damien",
    "ATKINS David": "atkins-david",
    "ATKINS Eileen": "atkins-eileen",
    "ATKINS Greg": "atkins-greg",
    "ATKINS John": "atkins-john",
    "ATKINS Nick": "atkins-nick",
    "ATKINS R J": "atkins-r-j",
    "ATKINS Richard": "atkins-richard",
    "ATKINS Russell": "atkins-russell",
    "ATKINS Sharif": "atkins-sharif",
    "ATKINS Stuart": "atkins-stuart",
    "ATKINSON Clinton J": "atkinson-clinton-j",
    "ATKINSON Crichton": "atkinson-crichton",
    "ATKINSON Dan": "atkinson-dan",
    "ATKINSON Dennis": "atkinson-dennis",
    "ATKINSON Dianne": "atkinson-dianne",
    "ATKINSON Harry": "atkinson-harry",
    "ATKINSON James": "atkinson-james",
    "ATKINSON James B": "atkinson-james-b",
    "ATKINSON Jason": "atkinson-jason",
    "ATKINSON Josh": "atkinson-josh",
    "ATKINSON Kate": "atkinson-kate",
    "ATKINSON Lawrence": "atkinson-lawrence",
    "ATKINSON Rebecca": "atkinson-rebecca",
    "ATKINSON Richard": "atkinson-richard",
    "ATKINSON Rowan": "atkinson-rowan",
    "ATKINSON Thomas M": "atkinson-thomas-m",
    "ATKINSON Tobin": "atkinson-tobin",
    "ATKINSON-LORD Rebecca": "atkinson-lord-rebecca",
    "ATLAKSON Philip": "atlakson-philip",
    "ATLAN Liliane": "atlan-liliane",
    "ATLAS Larry": "atlas-larry",
    "ATLAS GROUP ": "atlas-group",
    "ATRESBANDES ": "atresbandes",
    "ATTA Dean": "atta-dean",
    "ATTANAS John": "attanas-john",
    "ATTANASIE JR Steven": "attanasie-jr-steven",
    "ATTAR Farid Uddin": "attar-farid-uddin",
    "ATTAR Geula": "attar-geula",
    "ATTAR Shai Ben": "attar-shai-ben",
    "ATTAR Victor": "attar-victor",
    "ATTARD Tony": "attard-tony",
    "ATTAWAY Forrest": "attaway-forrest",
    "ATTEA Tom": "attea-tom",
    "ATTENWEILER Robert": "attenweiler-robert",
    "ATTERIDGE Harold": "atteridge-harold",
    "ATTIAS Daphna": "attias-daphna",
    "ATTIAS Erik": "attias-erik",
    "ATTINELLO Paul": "attinello-paul",
    "ATTIPOE Setor": "attipoe-setor",
    "ATTLEE Richard": "attlee-richard",
    "ATTRIDGE Steve": "attridge-steve",
    "ATTWOOD Alban": "attwood-alban",
    "ATTWOOD Thomas": "attwood-thomas",
    "ATUONA Diana Nneka": "atuona-diana-nneka",
    "ATWAL Sharanpreet Kaur": "atwal-sharanpreet-kaur",
    "ATWELL Gerry": "atwell-gerry",
    "ATWELL Sam": "atwell-sam",
    "ATWOOD Margaret": "atwood-margaret",
    "AUBIN Marc": "aubin-marc",
    "AUBREY Daniel": "aubrey-daniel",
    "AUBREY LC": "aubrey-lc",
    "AUBREY Stephen": "aubrey-stephen",
    "AUBURN David": "auburn-david",
    "AUDEN Scott": "auden-scott",
    "AUDEN W H": "auden-w-h",
    "AUDERGON Arlene": "audergon-arlene",
    "AUDIBERTI Jacques": "audiberti-jacques",
    "AUDIENCE, THE ": "audience",
    "AUDINI Lawrence": "audini-lawrence",
    "AUDLEY Elizabeth": "audley-elizabeth",
    "AUDLEY Matthew": "audley-matthew",
    "AUDLEY Natalie": "audley-natalie",
    "AUER Art": "auer-art",
    "AUER Nathan": "auer-nathan",
    "AUERBACH Arnold": "auerbach-arnold",
    "AUERBACH Kimberlee": "auerbach-kimberlee",
    "AUFRAY Gilles": "aufray-gilles",
    "AUGELLO Christina": "augello-christina",
    "AUGER Micheline": "auger-micheline",
    "AUGHEY Phil": "aughey-phil",
    "AUGIER Emile": "augier-emile",
    "AUGUST Ian": "august-ian",
    "AUGUST John": "august-john",
    "AUGUST June": "august-june",
    "AUGUST Kate": "august-kate",
    "AUGUSTANUS Xystus Betuluis": "augustanus-xystus-betuluis",
    "AUGUSTAS Isabela": "augustas-isabela",
    "AUGUSTAVE Hans": "augustave-hans",
    "AUGUSTIN Bill": "augustin-bill",
    "AUGUSTIN Jeff": "augustin-jeff",
    "AUGUSTIN William": "augustin-william",
    "AUGUSTINE John": "augustine-john",
    "AUGUSTINE Kevin": "augustine-kevin",
    "AUGUSTSON Scot": "augustson-scot",
    "AUKIN Liane": "aukin-liane",
    "AULA David": "aula-david",
    "AULD Eric K": "auld-eric-k",
    "AULETTA Robert": "auletta-robert",
    "AULICINO Armand": "aulicino-armand",
    "AULOV Vladimir": "aulov-vladimir",
    "AULTMAN Peggy": "aultman-peggy",
    "AUMILLER Tim": "aumiller-tim",
    "AUMUA Danny": "aumua-danny",
    "AUNAN Oda": "aunan-oda",
    "AURANSIA ": "auransia",
    "AURELIA THIERREE ": "aurelia-thierree",
    "AURELIUS Neville": "aurelius-neville",
    "AURERUS Leon": "aurerus-leon",
    "AURICOSTE Marianne": "auricoste-marianne",
    "AURORE Amontaine": "aurore-amontaine",
    "AURTHUR Robert Alan": "aurthur-robert-alan",
    "AUSBURN Garrison": "ausburn-garrison",
    "AUSLANDER Jordan": "auslander-jordan",
    "AUSTEN Alex": "austen-alex",
    "AUSTEN Alice": "austen-alice",
    "AUSTEN Leslie": "austen-leslie",
    "AUSTEN-PETERS Bolanle": "austen-peters-bolanle",
    "AUSTER Paul": "auster-paul",
    "AUSTER-ROSEN Megan": "auster-rosen-megan",
    "AUSTIN Alan": "austin-alan",
    "AUSTIN Alex": "austin-alex",
    "AUSTIN Brian": "austin-brian",
    "AUSTIN Daniel": "austin-daniel",
    "AUSTIN David": "austin-david",
    "AUSTIN Edward": "austin-edward",
    "AUSTIN Erin": "austin-erin",
    "AUSTIN Harry": "austin-harry",
    "AUSTIN Ian": "austin-ian",
    "AUSTIN Johnny": "austin-johnny",
    "AUSTIN Leslie": "austin-leslie",
    "AUSTIN Murray": "austin-murray",
    "AUSTIN Nigel": "austin-nigel",
    "AUSTIN Peter": "austin-peter",
    "AUSTIN Richard": "austin-richard",
    "AUSTIN Robert": "austin-robert",
    "AUSTRALIAN PERFORMING GROUP ": "australian-performing-group",
    "AUSUBEL Bobbi": "ausubel-bobbi",
    "AUTIER Paul": "autier-paul",
    "AVANT Lee": "avant-lee",
    "AVDI Anitgone": "avdi-anitgone",
    "AVELLA Frank J": "avella-frank-j",
    "AVELLA Mike": "avella-mike",
    "AVELONE Jesica": "avelone-jesica",
    "AVERIL Jerry": "averil-jerry",
    "AVERILL Jeanne": "averill-jeanne",
    "AVERILL Ric": "averill-ric",
    "AVERILL Will": "averill-will",
    "AVERILL-SNELL Ned": "averill-snell-ned",
    "AVERITT Dan": "averitt-dan",
    "AVERITT Suzan": "averitt-suzan",
    "AVERY Alan": "avery-alan",
    "AVERY Caryl S": "avery-caryl-s",
    "AVERY Eric F": "avery-eric-f",
    "AVERY H P": "avery-h-p",
    "AVERY Jacqueline": "avery-jacqueline",
    "AVERY John": "avery-john",
    "AVERY Juliana": "avery-juliana",
    "AVERY Lucy": "avery-lucy",
    "AVERY Mack": "avery-mack",
    "AVERY Matt": "avery-matt",
    "AVERY Peter": "avery-peter",
    "AVERY Stephen": "avery-stephen",
    "AVERY Wyckham": "avery-wyckham",
    "AVERY-CLARK Kenneth": "avery-clark-kenneth",
    "AVI ": "avi",
    "AVIDON Mallery": "avidon-mallery",
    "AVIDON Nelson": "avidon-nelson",
    "AVILA Elaine": "avila-elaine",
    "AVILA Juliette": "avila-juliette",
    "AVILA Tencha": "avila-tencha",
    "AVIS Meiret": "avis-meiret",
    "AVITAL Samuel": "avital-samuel",
    "AVNER Allan": "avner-allan",
    "AVNER Jon": "avner-jon",
    "AWAN Helen": "awan-helen",
    "AWDE Nick": "awde-nick",
    "AWEUSI Ali": "aweusi-ali",
    "AWKWARD ARTS ": "awkward-arts",
    "AWKWARD CITY ": "awkward-city",
    "AXELROD David": "axelrod-david",
    "AXELROD George": "axelrod-george",
    "AXELROD Laura": "axelrod-laura",
    "AXIS MIME THEATRE ": "axis-mime-theatre",
    "AXIS THEATRE COMPANY ": "axis-theatre-company",
    "AXLER Rachel": "axler-rachel",
    "AXLEROD David": "axlerod-david",
    "AXSTER Lilly": "axster-lilly",
    "AYACHE Makram": "ayache-makram",
    "AYALA Corina Katt": "ayala-corina-katt",
    "AYANOGLU Byron": "ayanoglu-byron",
    "AYBAR Trudy": "aybar-trudy",
    "AYCKBOURN Alan": "ayckbourn-alan",
    "AYCKBOURN Philip": "ayckbourn-philip",
    "AYCOCK Roger D": "aycock-roger-d",
    "AYERS Astrid": "ayers-astrid",
    "AYERS David H": "ayers-david-h",
    "AYERS Greg": "ayers-greg",
    "AYERS Marni": "ayers-marni",
    "AYERS Michael": "ayers-michael",
    "AYERS Shan R": "ayers-shan-r",
    "AYERS Trish": "ayers-trish",
    "AYERS Vivian": "ayers-vivian",
    "AYKROYD Juliet": "aykroyd-juliet",
    "AYLEN Leo": "aylen-leo",
    "AYLIN Simon": "aylin-simon",
    "AYLING Simon": "ayling-simon",
    "AYLOR Anne": "aylor-anne",
    "AYLWEN Ingraa": "aylwen-ingraa",
    "AYMAR Angels": "aymar-angels",
    "AYME Marcel": "ayme-marcel",
    "AYMER Geoff": "aymer-geoff",
    "AYMIE Alan": "aymie-alan",
    "AYOADE Richard": "ayoade-richard",
    "AYODEJI Julius": "ayodeji-julius",
    "AYRE Paul": "ayre-paul",
    "AYRES Tony": "ayres-tony",
    "AYRES Trish": "ayres-trish",
    "AYRES-FREDERICK Linda": "ayres-frederick-linda",
    "AYUB Zaf": "ayub-zaf",
    "AYVAS Emanuel": "ayvas-emanuel",
    "AYVAZIAN Leslie": "ayvazian-leslie",
    "AZAMA Michel": "azama-michel",
    "AZAR Raja": "azar-raja",
    "AZA-SELINGER George": "aza-selinger-george",
    "AZAZ Orit": "azaz-orit",
    "AZEVEDO Adrian": "azevedo-adrian",
    "AZEVEDO Marcos": "azevedo-marcos",
    "AZIMI Mohsen": "azimi-mohsen",
    "AZIZ Aya": "aziz-aya",
    "AZOUZ Josh": "azouz-josh",
    "AZRIEL Ilan": "azriel-ilan",
    "AZULAY-HASFARI Hana": "azulay-hasfari-hana",
    "AZURDIA Ivonne": "azurdia-ivonne",
    "AZZOUGA Saleem": "azzouga-saleem"
  }
};