export default {
  "metadata": {
    "results": 465,
    "timeStamp": "2025-12-05T21:21:59.467Z",
    "url": "https://www.doollee.com/PlaywrightsB/B_playwrights_baa-baq.php"
  },
  "authors": {
    "B Ara": "b-ara",
    "B Cheryl": "b-cheryl",
    "B Ed": "b-ed",
    "BAACK Alexander": "baack-alexander",
    "BAACK Hillary": "baack-hillary",
    "BAADE Jessica Curtis": "baade-jessica-curtis",
    "BAAL Frederic": "baal-frederic",
    "BAARDA Phil": "baarda-phil",
    "BAART Corien": "baart-corien",
    "BABAKAS ": "babakas",
    "BABATUNDE Akin": "babatunde-akin",
    "BABATUNDE Rotimi": "babatunde-rotimi",
    "BABAYANGA ": "babayanga",
    "BABB Roger": "babb-roger",
    "BABCOCK David": "babcock-david",
    "BABE Thomas": "babe-thomas",
    "BABEL Isaac": "babel-isaac",
    "BABIAK Todd": "babiak-todd",
    "BABILLA Assurbanipal": "babilla-assurbanipal",
    "BABIN Richard": "babin-richard",
    "BABINA Pietro": "babina-pietro",
    "BABLE Wendy": "bable-wendy",
    "BABULA William": "babula-william",
    "BABY Canter": "baby-canter",
    "BABY WANTS CANDY ": "baby-wants-candy",
    "BACALZO Dan": "bacalzo-dan",
    "BACCI Warren": "bacci-warren",
    "BACELAR Andre": "bacelar-andre",
    "BACH Jovanka": "bach-jovanka",
    "BACH Richard S": "bach-richard-s",
    "BACHAR Leah": "bachar-leah",
    "BACHARACH Burt": "bacharach-burt",
    "BACHELARD Gaston": "bachelard-gaston",
    "BACHELOT Laure": "bachelot-laure",
    "BACHER Danny": "bacher-danny",
    "BACHER Josh": "bacher-josh",
    "BACHMAN James": "bachman-james",
    "BACHMAN Maureen": "bachman-maureen",
    "BACHMAN Susan M": "bachman-susan-m",
    "BACHMANN Robert": "bachmann-robert",
    "BACHNER Suzanne": "bachner-suzanne",
    "BACHTOLD Ken": "bachtold-ken",
    "BACK Joyce": "back-joyce",
    "BACK Oli": "back-oli",
    "BACK TO BACK THEATRE ": "back-to-back-theatre",
    "BACKER Andy": "backer-andy",
    "BACKER Bill": "backer-bill",
    "BACKHAUS Jaclyn": "backhaus-jaclyn",
    "BACKHOUSE Elizabeth": "backhouse-elizabeth",
    "BACKIEWICZ Sebastian": "backiewicz-sebastian",
    "BACKLAND Ged": "backland-ged",
    "BACKMAN Thomas R": "backman-thomas-r",
    "BACKSTAIRS INFLUENCE ": "backstairs-influence",
    "BACKUS Dean": "backus-dean",
    "BACKUS Fred": "backus-fred",
    "BACKVALL Jens": "backvall-jens",
    "BACON Christine": "bacon-christine",
    "BACON Christylez": "bacon-christylez",
    "BACON David W": "bacon-david-w",
    "BACON Frank": "bacon-frank",
    "BACON Harrison John": "bacon-harrison-john",
    "BACON Helen H": "bacon-helen-h",
    "BACON Jean": "bacon-jean",
    "BACON Musa": "bacon-musa",
    "BACON Sean": "bacon-sean",
    "BACON Thomas John": "bacon-thomas-john",
    "BACON Varick": "bacon-varick",
    "BACOS John": "bacos-john",
    "BACZKIEWICZ Sebastian": "baczkiewicz-sebastian",
    "BADAC THEATRE COMPANY ": "badac-theatre-company",
    "BADAMO Jenifer": "badamo-jenifer",
    "BADDELY Victor": "baddely-victor",
    "BADDIEL David": "baddiel-david",
    "BADE Pheonix": "bade-pheonix",
    "BADER Jenny Lyn": "bader-jenny-lyn",
    "BADGER Justin": "badger-justin",
    "BADGERS, THE ": "badgers",
    "BADHAM Keith": "badham-keith",
    "BADHAM Van": "badham-van",
    "BADIAN Seydou": "badian-seydou",
    "BADLAM Robb": "badlam-robb",
    "BADMAN Stephen": "badman-stephen",
    "BADORREK Liesel": "badorrek-liesel",
    "BAEK Sora": "baek-sora",
    "BAER Andrew": "baer-andrew",
    "BAER Gwen": "baer-gwen",
    "BAER Richard": "baer-richard",
    "BAETA Virginia Lynn": "baeta-virginia-lynn",
    "BAETZ Stephen": "baetz-stephen",
    "BAEUR Carlos": "baeur-carlos",
    "BAEZA Macarena": "baeza-macarena",
    "BAGAN Eric": "bagan-eric",
    "BAGATOURIAN Bianca": "bagatourian-bianca",
    "BAGBY Benjamin": "bagby-benjamin",
    "BAGDASIAN Harry Michael": "bagdasian-harry-michael",
    "BAGG Robert": "bagg-robert",
    "BAGGAGE CO-OP ": "baggage-co-op",
    "BAGGOT Vanesa": "baggot-vanesa",
    "BAGGOTT Kevin": "baggott-kevin",
    "BAGGS Linda Escalera": "baggs-linda-escalera",
    "BAGIN Kristian": "bagin-kristian",
    "BAGLEY Ben": "bagley-ben",
    "BAGLEY Sarah": "bagley-sarah",
    "BAGNASCO Mica": "bagnasco-mica",
    "BAGNERIS Vernel": "bagneris-vernel",
    "BAGNOLD Enid": "bagnold-enid",
    "BAGSHAW Rachel": "bagshaw-rachel",
    "BAGSHAW Sarah": "bagshaw-sarah",
    "BAHAM Michael": "baham-michael",
    "BAHATI Amirh T": "bahati-amirh-t",
    "BAHNA-JAMES Tara": "bahna-james-tara",
    "BAHR Hermann": "bahr-hermann",
    "BAHR Iris": "bahr-iris",
    "BAIA Diane": "baia-diane",
    "BAIESU Ian": "baiesu-ian",
    "BAIG Bilal": "baig-bilal",
    "BAIG Moin Ali": "baig-moin-ali",
    "BAIG Samina": "baig-samina",
    "BAIL Margaret": "bail-margaret",
    "BAIL Rachel Elizabeth": "bail-rachel-elizabeth",
    "BAILEY A Peter": "bailey-a-peter",
    "BAILEY Adam": "bailey-adam",
    "BAILEY Adrian": "bailey-adrian",
    "BAILEY Alan": "bailey-alan",
    "BAILEY Andrew": "bailey-andrew",
    "BAILEY Bert": "bailey-bert",
    "BAILEY Beth": "bailey-beth",
    "BAILEY Brad": "bailey-brad",
    "BAILEY Brett": "bailey-brett",
    "BAILEY Bruce": "bailey-bruce",
    "BAILEY Chris": "bailey-chris",
    "BAILEY Christopher": "bailey-christopher",
    "BAILEY Christopher Brett": "bailey-christopher-brett",
    "BAILEY David": "bailey-david",
    "BAILEY Dennis": "bailey-dennis",
    "BAILEY Douglas Neil": "bailey-douglas-neil",
    "BAILEY Dyan": "bailey-dyan",
    "BAILEY E G": "bailey-e-g",
    "BAILEY Ellie": "bailey-ellie",
    "BAILEY Frederick": "bailey-frederick",
    "BAILEY Gerald H": "bailey-gerald-h",
    "BAILEY Glyn": "bailey-glyn",
    "BAILEY Ian": "bailey-ian",
    "BAILEY Jerry": "bailey-jerry",
    "BAILEY Jim": "bailey-jim",
    "BAILEY Joe": "bailey-joe",
    "BAILEY Larry": "bailey-larry",
    "BAILEY Larry J": "bailey-larry-j",
    "BAILEY Laura": "bailey-laura",
    "BAILEY Laura (1)": "bailey-laura-1",
    "BAILEY Lucy": "bailey-lucy",
    "BAILEY Maxine": "bailey-maxine",
    "BAILEY Michele": "bailey-michele",
    "BAILEY Norman A": "bailey-norman-a",
    "BAILEY Peter John": "bailey-peter-john",
    "BAILEY Pippa": "bailey-pippa",
    "BAILEY R S": "bailey-r-s",
    "BAILEY Ray": "bailey-ray",
    "BAILEY Roberta": "bailey-roberta",
    "BAILEY Sally": "bailey-sally",
    "BAILEY Sam": "bailey-sam",
    "BAILEY Sheri": "bailey-sheri",
    "BAILEY Stephen": "bailey-stephen",
    "BAILEY Steve": "bailey-steve",
    "BAILEY Terry": "bailey-terry",
    "BAILEY Tom": "bailey-tom",
    "BAILEY Trystin S": "bailey-trystin-s",
    "BAILEY, II Gilbert L": "bailey-ii-gilbert-l",
    "BAILLE Suzanne": "baille-suzanne",
    "BAILLIE Bruce": "baillie-bruce",
    "BAILLY Anthony": "bailly-anthony",
    "BAILY Stephen": "baily-stephen",
    "BAIN Allister": "bain-allister",
    "BAIN Andrew": "bain-andrew",
    "BAIN Byronn": "bain-byronn",
    "BAIN Christine": "bain-christine",
    "BAIN D M": "bain-d-m",
    "BAIN Dan": "bain-dan",
    "BAIN Jim": "bain-jim",
    "BAIN Julian": "bain-julian",
    "BAIN Julie": "bain-julie",
    "BAIN K Marjorie": "bain-k-marjorie",
    "BAIN Nick": "bain-nick",
    "BAIN Reginald": "bain-reginald",
    "BAIN Stephanie": "bain-stephanie",
    "BAIN Stephen": "bain-stephen",
    "BAINBRIDGE Beryl": "bainbridge-beryl",
    "BAINBRIDGE Melanie": "bainbridge-melanie",
    "BAINBRIDGE Pippa": "bainbridge-pippa",
    "BAINE Holly Baxter": "baine-holly-baxter",
    "BAINES Elizabeth": "baines-elizabeth",
    "BAINES Jim": "baines-jim",
    "BAINES Mercedes": "baines-mercedes",
    "BAINES Patrick": "baines-patrick",
    "BAINES Richard": "baines-richard",
    "BAINS Harwant S": "bains-harwant-s",
    "BAINS Lynn": "bains-lynn",
    "BAIR Alisa": "bair-alisa",
    "BAIR Vonn Scott": "bair-vonn-scott",
    "BAIRAMIAN Diane R": "bairamian-diane-r",
    "BAIRD Christina": "baird-christina",
    "BAIRD Danny": "baird-danny",
    "BAIRD Jenni": "baird-jenni",
    "BAIRD Katy": "baird-katy",
    "BAIRD Ruth": "baird-ruth",
    "BAIRD Veronica": "baird-veronica",
    "BAIREAD Brian": "bairead-brian",
    "BAISCH Lucas": "baisch-lucas",
    "BAISLEY Doris": "baisley-doris",
    "BAISTOW Myra": "baistow-myra",
    "BAITZ Jon Robin": "baitz-jon-robin",
    "BAIZLEY Doris": "baizley-doris",
    "BAJAJ Aman": "bajaj-aman",
    "BAJER Sharon": "bajer-sharon",
    "BAJTALA Janos": "bajtala-janos",
    "BAKAITIS Helmut": "bakaitis-helmut",
    "BAKER A J": "baker-a-j",
    "BAKER Aaron": "baker-aaron",
    "BAKER Alex": "baker-alex",
    "BAKER Allan": "baker-allan",
    "BAKER Allan J": "baker-allan-j",
    "BAKER Annie": "baker-annie",
    "BAKER August": "baker-august",
    "BAKER Bob": "baker-bob",
    "BAKER Bobby": "baker-bobby",
    "BAKER Brad": "baker-brad",
    "BAKER Brenna": "baker-brenna",
    "BAKER Chris": "baker-chris",
    "BAKER Christina": "baker-christina",
    "BAKER Christopher": "baker-christopher",
    "BAKER Cliff F": "baker-cliff-f",
    "BAKER Daniel \"Space Monkey\"": "baker-daniel",
    "BAKER Danielle": "baker-danielle",
    "BAKER Darren": "baker-darren",
    "BAKER David": "baker-david",
    "BAKER David L": "baker-david-l",
    "BAKER Denise": "baker-denise",
    "BAKER Dorothy": "baker-dorothy",
    "BAKER Douglas": "baker-douglas",
    "BAKER Edna": "baker-edna",
    "BAKER Edward Allan": "baker-edward-allan",
    "BAKER Elliot": "baker-elliot",
    "BAKER Elliott B": "baker-elliott-b",
    "BAKER Elna": "baker-elna",
    "BAKER Emily Zoey": "baker-emily-zoey",
    "BAKER Gale": "baker-gale",
    "BAKER Glenda": "baker-glenda",
    "BAKER Graham": "baker-graham",
    "BAKER H": "baker-h",
    "BAKER H Jones": "baker-h-jones",
    "BAKER Hannah": "baker-hannah",
    "BAKER Hannah Lucy": "baker-hannah-lucy",
    "BAKER Henriette": "baker-henriette",
    "BAKER Hillery": "baker-hillery",
    "BAKER Howard": "baker-howard",
    "BAKER Jackie": "baker-jackie",
    "BAKER James": "baker-james",
    "BAKER Jeffrey": "baker-jeffrey",
    "BAKER Joan M": "baker-joan-m",
    "BAKER Joe": "baker-joe",
    "BAKER John A": "baker-john-a",
    "BAKER John Roman": "baker-john-roman",
    "BAKER John S": "baker-john-s",
    "BAKER Kelley Tish": "baker-kelley-tish",
    "BAKER Kenneth": "baker-kenneth",
    "BAKER Leslie": "baker-leslie",
    "BAKER Lindsay Warren": "baker-lindsay-warren",
    "BAKER Lucille": "baker-lucille",
    "BAKER Maria Gabriele": "baker-maria-gabriele",
    "BAKER Max": "baker-max",
    "BAKER Patrick": "baker-patrick",
    "BAKER Paul": "baker-paul",
    "BAKER Paul (1)": "baker-paul-1",
    "BAKER Randy": "baker-randy",
    "BAKER Raymond W": "baker-raymond-w",
    "BAKER Rex": "baker-rex",
    "BAKER Richard S": "baker-richard-s",
    "BAKER Roger": "baker-roger",
    "BAKER Russell": "baker-russell",
    "BAKER Ruth Tyndall": "baker-ruth-tyndall",
    "BAKER Sarah Hamilton": "baker-sarah-hamilton",
    "BAKER Scott": "baker-scott",
    "BAKER Tammy Hailiopua": "baker-tammy-hailiopua",
    "BAKER Tim": "baker-tim",
    "BAKER Travis": "baker-travis",
    "BAKER Trista": "baker-trista",
    "BAKER Ward": "baker-ward",
    "BAKER William": "baker-william",
    "BAKER-OLIVER Courtney": "baker-oliver-courtney",
    "BAKING COMMITTEE ": "baking-committee",
    "BAKKER Kuno": "bakker-kuno",
    "BAKSHY Alexander": "bakshy-alexander",
    "BAKST Janet": "bakst-janet",
    "BAKU Shango": "baku-shango",
    "BALANCE Christopher": "balance-christopher",
    "BALAS Carmen": "balas-carmen",
    "BALASZ Bela": "balasz-bela",
    "BALCAZAR Cesar": "balcazar-cesar",
    "BALCAZO Dan": "balcazo-dan",
    "BALCHIN Stephen": "balchin-stephen",
    "BALCOURT Jon": "balcourt-jon",
    "BALDAN Bernard": "baldan-bernard",
    "BALDAS Nicholas": "baldas-nicholas",
    "BALDELLI Giovanni": "baldelli-giovanni",
    "BALDERSTON John L": "balderston-john-l",
    "BALDESSARI Mario": "baldessari-mario",
    "BALDICK Robert": "baldick-robert",
    "BALDINGER Thomas": "baldinger-thomas",
    "BALDOCK David": "baldock-david",
    "BALDRICK Robert": "baldrick-robert",
    "BALDRIDGE Mary Humphrey": "baldridge-mary-humphrey",
    "BALDRIDGE Richard": "baldridge-richard",
    "BALDUCCI Carolyn Feleppa": "balducci-carolyn-feleppa",
    "BALDUZZI Maximilian": "balduzzi-maximilian",
    "BALDWIN Audrey": "baldwin-audrey",
    "BALDWIN Charles": "baldwin-charles",
    "BALDWIN Christopher": "baldwin-christopher",
    "BALDWIN Craig": "baldwin-craig",
    "BALDWIN David": "baldwin-david",
    "BALDWIN Duane Kim": "baldwin-duane-kim",
    "BALDWIN James": "baldwin-james",
    "BALDWIN James (2)": "baldwin-james-2",
    "BALDWIN Joan": "baldwin-joan",
    "BALDWIN Johanna": "baldwin-johanna",
    "BALDWIN John": "baldwin-john",
    "BALDWIN Kevin T": "baldwin-kevin-t",
    "BALDWIN Margaret": "baldwin-margaret",
    "BALDWIN Matthew": "baldwin-matthew",
    "BALDWIN Michael Kevin": "baldwin-michael-kevin",
    "BALDWIN Nicola": "baldwin-nicola",
    "BALDWIN Nigel": "baldwin-nigel",
    "BALDWIN Rideaux Antoine": "baldwin-rideaux-antoine",
    "BALDWIN Stephen W": "baldwin-stephen-w",
    "BALDWIN Trista": "baldwin-trista",
    "BALE Antonia": "bale-antonia",
    "BALE David": "bale-david",
    "BALES Ted": "bales-ted",
    "BALESTRIERI James": "balestrieri-james",
    "BALETIC Hajdana": "baletic-hajdana",
    "BALEY Deborah B": "baley-deborah-b",
    "BALFOUR Alan": "balfour-alan",
    "BALFOUR Kinvara": "balfour-kinvara",
    "BALIAN James": "balian-james",
    "BALIAN Rick": "balian-rick",
    "BALIANI Marco": "baliani-marco",
    "BALINSKA Krystofa": "balinska-krystofa",
    "BALINT Sue": "balint-sue",
    "BALIT Christina": "balit-christina",
    "BALIZET Bernard": "balizet-bernard",
    "BALK H Wesley": "balk-h-wesley",
    "BALKIN Daniel": "balkin-daniel",
    "BALKWILL Peter": "balkwill-peter",
    "BALL Alan": "ball-alan",
    "BALL Christopher John": "ball-christopher-john",
    "BALL David": "ball-david",
    "BALL Gerald": "ball-gerald",
    "BALL J A": "ball-j-a",
    "BALL Mason": "ball-mason",
    "BALL Matt": "ball-matt",
    "BALL Melanie Anne": "ball-melanie-anne",
    "BALL Patrick": "ball-patrick",
    "BALL Philip": "ball-philip",
    "BALL Rachel": "ball-rachel",
    "BALLANCE Chris": "ballance-chris",
    "BALLANTINE Robert": "ballantine-robert",
    "BALLANTYNE Bill": "ballantyne-bill",
    "BALLANTYNE Drew": "ballantyne-drew",
    "BALLANTYNE Rachel": "ballantyne-rachel",
    "BALLARD Andrew P": "ballard-andrew-p",
    "BALLARD Charity": "ballard-charity",
    "BALLARD Deb Caperton": "ballard-deb-caperton",
    "BALLARD Glen": "ballard-glen",
    "BALLARD Rob": "ballard-rob",
    "BALLEN Kate": "ballen-kate",
    "BALLESTAD Amy": "ballestad-amy",
    "BALLESTEROS John": "ballesteros-john",
    "BALLINGER Pauline": "ballinger-pauline",
    "BALLINGER Robert": "ballinger-robert",
    "BALLON Richard": "ballon-richard",
    "BALLOO Julie": "balloo-julie",
    "BALLOU Ed": "ballou-ed",
    "BALMACEDA M": "balmaceda-m",
    "BALME Chris": "balme-chris",
    "BALME M G": "balme-m-g",
    "BALME Tim": "balme-tim",
    "BALODIS Bridget": "balodis-bridget",
    "BALODIS Janis": "balodis-janis",
    "BALOO Julie": "baloo-julie",
    "BALTHAZAR Perrie": "balthazar-perrie",
    "BALZAC Honore De": "balzac-honore-de",
    "BALZAR Julie Fei-Fan": "balzar-julie-fei-fan",
    "BALZER Derry": "balzer-derry",
    "BAMBER David": "bamber-david",
    "BAMBER Geoff": "bamber-geoff",
    "BAMBERGER Ana-Maria": "bamberger-ana-maria",
    "BAMBURY Keith": "bambury-keith",
    "BAMBUSEK Miroslav": "bambusek-miroslav",
    "BAMFORD Nick": "bamford-nick",
    "BAMKIN Rand M": "bamkin-r-m",
    "BAMMAN Gerry": "bamman-gerry",
    "BAMONTE Christopher": "bamonte-christopher",
    "BAMPTON-SMITH Adam": "bampton-smith-adam",
    "BAN Elizabeth": "ban-elizabeth",
    "BANACKI Raymond": "banacki-raymond",
    "BANANA BAG AND BODICE ": "banana-bag-and-bodice",
    "BANAS John": "banas-john",
    "BANCE Georgia": "bance-georgia",
    "BANCI Lewis": "banci-lewis",
    "BANCIL Parv": "bancil-parv",
    "BANCROFT Dan": "bancroft-dan",
    "BANDA Victor Hugo Rascon": "banda-victor-hugo-rascon",
    "BANDELE-THOMAS Biyi": "bandele-thomas-biyi",
    "BANDIERE Becca": "bandiere-becca",
    "BANDO DE TEATRO OLODUM ": "bando-de-teatro-olodum",
    "BANDY Sharon": "bandy-sharon",
    "BANDYOPADHYAY Samik": "bandyopadhyay-samik",
    "BANE Rodney": "bane-rodney",
    "BANERJEE Atri": "banerjee-atri",
    "BANG Heironymous": "bang-heironymous",
    "BANG Helen": "bang-helen",
    "BANGS Elliott": "bangs-elliott",
    "BANISTER Eve": "banister-eve",
    "BANJAMIN Nell Dunbar": "banjamin-nell-dunbar",
    "BANK Diane": "bank-diane",
    "BANK Jonathan": "bank-jonathan",
    "BANKA Sarovar": "banka-sarovar",
    "BANKS Annabel": "banks-annabel",
    "BANKS Catherine A": "banks-catherine-a",
    "BANKS David": "banks-david",
    "BANKS Greg": "banks-greg",
    "BANKS Hannah": "banks-hannah",
    "BANKS India": "banks-india",
    "BANKS Janet": "banks-janet",
    "BANKS Jeff": "banks-jeff",
    "BANKS Joseph": "banks-joseph",
    "BANKS Joseph Vernon": "banks-joseph-vernon",
    "BANKS Lynne Reid": "banks-lynne-reid",
    "BANKS Morton": "banks-morton",
    "BANKS Morwenna": "banks-morwenna",
    "BANKS Nathaniel": "banks-nathaniel",
    "BANKS Steven": "banks-steven",
    "BANKS-JONES Bill": "banks-jones-bill",
    "BANNER Helen Marie-Anne": "banner-helen-marie-anne",
    "BANNERMAN Kay": "bannerman-kay",
    "BANNISTER Bronwyn": "bannister-bronwyn",
    "BANNISTER Ivy": "bannister-ivy",
    "BANNISTER Linda": "bannister-linda",
    "BANNISTER Winifred": "bannister-winifred",
    "BANNOCKS Charlie": "bannocks-charlie",
    "BANNON James": "bannon-james",
    "BANNON Nancy": "bannon-nancy",
    "BANNOW Chris": "bannow-chris",
    "BANO Alia": "bano-alia",
    "BANON Jo": "banon-jo",
    "BANS Jenna": "bans-jenna",
    "BANTA Martha": "banta-martha",
    "BANTELMAN Jennifer": "bantelman-jennifer",
    "BANTOCK Nick": "bantock-nick",
    "BANTOCK Raymond": "bantock-raymond",
    "BANVILLE John": "banville-john",
    "BANYARD E": "banyard-e",
    "BANYAS Susan": "banyas-susan",
    "BAPST Don": "bapst-don",
    "BAPTISTE Diderot Jean": "baptiste-diderot-jean",
    "BAPTISTE Marianne Jean": "baptiste-marianne-jean"
  }
};