export default {
  "metadata": {
    "results": 489,
    "timeStamp": "2025-12-05T21:22:02.776Z",
    "url": "https://www.doollee.com/PlaywrightsB/B_playwrights_bar-bar.php"
  },
  "authors": {
    "BAR Hilla": "bar-hilla",
    "BAR Jospeh": "bar-jospeh",
    "BARA CAWS ": "bara-caws",
    "BARAB Seymour": "barab-seymour",
    "BARABAS Jutka T Emoke": "barabas-jutka-t-emoke",
    "BARABAS Suzanne": "barabas-suzanne",
    "BARABBAS ": "barabbas",
    "BARAITSER Marion": "baraitser-marion",
    "BARAKA Amiri": "baraka-amiri",
    "BARAKA Kenny": "baraka-kenny",
    "BARALDI John": "baraldi-john",
    "BARALL Michi": "barall-michi",
    "BARANCZAK Stanislaw": "baranczak-stanislaw",
    "BARANOVSKY Yuri": "baranovsky-yuri",
    "BARANOWSKI Henryk": "baranowski-henryk",
    "BARASCH Norman": "barasch-norman",
    "BARASCH Shirley R": "barasch-shirley-r",
    "BARASH Emma": "barash-emma",
    "BARASH Phyllis": "barash-phyllis",
    "BARATTA Alex": "baratta-alex",
    "BARATTA Maria": "baratta-maria",
    "BARBAGALLO Jess": "barbagallo-jess",
    "BARBANO Diana": "barbano-diana",
    "BARBARA Frank": "barbara-frank",
    "BARBAT Isabelle": "barbat-isabelle",
    "BARBEE Donald": "barbee-donald",
    "BARBER Benedict": "barber-benedict",
    "BARBER Benjamin R": "barber-benjamin-r",
    "BARBER David": "barber-david",
    "BARBER John": "barber-john",
    "BARBER Kathleen": "barber-kathleen",
    "BARBER Mary": "barber-mary",
    "BARBER Matthew": "barber-matthew",
    "BARBER Nicola": "barber-nicola",
    "BARBER P": "barber-p",
    "BARBER Roy": "barber-roy",
    "BARBER Sam": "barber-sam",
    "BARBER Stan": "barber-stan",
    "BARBER William": "barber-william",
    "BARBERA Kirsten": "barbera-kirsten",
    "BARBIE Richard A": "barbie-richard-a",
    "BARBOR Dick": "barbor-dick",
    "BARBOSA Marcos": "barbosa-marcos",
    "BARBOT Matt": "barbot-matt",
    "BARBOUR Floyd": "barbour-floyd",
    "BARBOUR Morgan": "barbour-morgan",
    "BARCAN Nan": "barcan-nan",
    "BARCASKI Lil A": "barcaski-lil-a",
    "BARCHERS Suzanne": "barchers-suzanne",
    "BARCLAY Alison": "barclay-alison",
    "BARCLAY Andrew": "barclay-andrew",
    "BARCLAY Bill": "barclay-bill",
    "BARCLAY Caitlyn": "barclay-caitlyn",
    "BARCLAY Clark": "barclay-clark",
    "BARCLAY James": "barclay-james",
    "BARCLAY Jennifer": "barclay-jennifer",
    "BARCLAY John": "barclay-john",
    "BARCLAY Julia Lee": "barclay-julia-lee",
    "BARCLAY Julianna": "barclay-julianna",
    "BARCLAY Julie": "barclay-julie",
    "BARCLAY Karen": "barclay-karen",
    "BARCLAY Paris": "barclay-paris",
    "BARCLAY Rachel": "barclay-rachel",
    "BARCODE Tim": "barcode-tim",
    "BARD Adam": "bard-adam",
    "BARD Georgina": "bard-georgina",
    "BARD Martin": "bard-martin",
    "BARDEN Alice": "barden-alice",
    "BARDEN Jimmy": "barden-jimmy",
    "BARDEN Jimmy C": "barden-jimmy-c",
    "BARDEN Thomas Earl": "barden-thomas-earl",
    "BARDIJEWSKI Henryk": "bardijewski-henryk",
    "BARDIN Joseph Raphael": "bardin-joseph-raphael",
    "BARDINELLI Giovanni": "bardinelli-giovanni",
    "BARDOLY Louis S": "bardoly-louis-s",
    "BARDOS Carolyn M": "bardos-carolyn-m",
    "BARDSLEY Julia": "bardsley-julia",
    "BARDSLEY Susan": "bardsley-susan",
    "BARDWELL Leland": "bardwell-leland",
    "BARE HAND WOLF CHOKERS ASSOCIATION ": "bare-hand-wolf-chokers",
    "BARE HUNT COLLECTIVE ": "bare-hunt-collective",
    "BAREFORD David": "bareford-david",
    "BARER Marshall": "barer-marshall",
    "BARFIELD Tanya": "barfield-tanya",
    "BARFOOT Lewis": "barfoot-lewis",
    "BARFUSS Lukas": "barfuss-lukas",
    "BARGATE Tracy": "bargate-tracy",
    "BARGUM Johan": "bargum-johan",
    "BARGY Jeanne": "bargy-jeanne",
    "BARHAM Stuart": "barham-stuart",
    "BARI Frank": "bari-frank",
    "BARIKA Carmen": "barika-carmen",
    "BARILAR Nic": "barilar-nic",
    "BARILE Paul": "barile-paul",
    "BARILLET Pierre": "barillet-pierre",
    "BARING Maurice": "baring-maurice",
    "BARING Tony": "baring-tony",
    "BARISICH Kyle": "barisich-kyle",
    "BARITOT-TUCKER Dianna": "baritot-tucker-dianna",
    "BARKAN Elizabeth": "barkan-elizabeth",
    "BARKAN Mark": "barkan-mark",
    "BARKDULL Leonard": "barkdull-leonard",
    "BARKE James": "barke-james",
    "BARKENTIN Marjorie": "barkentin-marjorie",
    "BARKER Clive": "barker-clive",
    "BARKER Clive (2)": "barker-clive-2",
    "BARKER Daniel": "barker-daniel",
    "BARKER Dean": "barker-dean",
    "BARKER George": "barker-george",
    "BARKER Hannah": "barker-hannah",
    "BARKER Howard": "barker-howard",
    "BARKER Jeff": "barker-jeff",
    "BARKER John W": "barker-john-w",
    "BARKER Karen Bohm": "barker-karen-bohm",
    "BARKER Lawrence": "barker-lawrence",
    "BARKER Megan": "barker-megan",
    "BARKER Meredydd": "barker-meredydd",
    "BARKER Pat": "barker-pat",
    "BARKER Patricia": "barker-patricia",
    "BARKER R J": "barker-r-j",
    "BARKER Robert C": "barker-robert-c",
    "BARKER Ronnie": "barker-ronnie",
    "BARKER Sara": "barker-sara",
    "BARKER Tim": "barker-tim",
    "BARKER Wayne": "barker-wayne",
    "BARKER-BEDNAR Lori": "barker-bednar-lori",
    "BARKEY Rita Kniess": "barkey-rita-kniess",
    "BARKHIMER Steven": "barkhimer-steven",
    "BARKLEY Lynette": "barkley-lynette",
    "BARKLEY Mark": "barkley-mark",
    "BARKLIE Lance": "barklie-lance",
    "BARKMAN Donna": "barkman-donna",
    "BARKSDALE William": "barksdale-william",
    "BARKWORTH Peter": "barkworth-peter",
    "BARLACH Ernst": "barlach-ernst",
    "BARLEY Georgina": "barley-georgina",
    "BARLIZO Marie-Leofeli R": "barlizo-marie-leofeli-r",
    "BARLOW Anna Marie": "barlow-anna-marie",
    "BARLOW Chris": "barlow-chris",
    "BARLOW David": "barlow-david",
    "BARLOW Gary": "barlow-gary",
    "BARLOW John Garfield": "barlow-john-garfield",
    "BARLOW Pamela": "barlow-pamela",
    "BARLOW Patrick": "barlow-patrick",
    "BARLOW Peppy": "barlow-peppy",
    "BARLOW Shirley A": "barlow-shirley-a",
    "BARLOW Simon": "barlow-simon",
    "BARLOW Steve": "barlow-steve",
    "BARLOW Tim": "barlow-tim",
    "BARMIE Geremie": "barmie-geremie",
    "BARNA Tom David": "barna-tom-david",
    "BARNARD Adam": "barnard-adam",
    "BARNARD Dan": "barnard-dan",
    "BARNARD Graham": "barnard-graham",
    "BARNARD Jim": "barnard-jim",
    "BARNARD Simon": "barnard-simon",
    "BARNARD Sorrel": "barnard-sorrel",
    "BARNATCHEZ Alicia": "barnatchez-alicia",
    "BARNES A C": "barnes-a-c",
    "BARNES Anna": "barnes-anna",
    "BARNES Aquaila": "barnes-aquaila",
    "BARNES Aubrey": "barnes-aubrey",
    "BARNES Aziza": "barnes-aziza",
    "BARNES Becca": "barnes-becca",
    "BARNES Billy": "barnes-billy",
    "BARNES Brian D": "barnes-brian-d",
    "BARNES Christopher": "barnes-christopher",
    "BARNES Claudia": "barnes-claudia",
    "BARNES David K": "barnes-david-k",
    "BARNES David Nathie": "barnes-david-nathie",
    "BARNES David-Matthew": "barnes-david-matthew",
    "BARNES Djuna": "barnes-djuna",
    "BARNES Edward": "barnes-edward",
    "BARNES Eric Lane": "barnes-eric-lane",
    "BARNES Gerry": "barnes-gerry",
    "BARNES Grace": "barnes-grace",
    "BARNES Harold C": "barnes-harold-c",
    "BARNES Hollis": "barnes-hollis",
    "BARNES Ian Richard": "barnes-ian-richard",
    "BARNES Janet": "barnes-janet",
    "BARNES Jem": "barnes-jem",
    "BARNES Joe": "barnes-joe",
    "BARNES Joseph C": "barnes-joseph-c",
    "BARNES Lee": "barnes-lee",
    "BARNES Luci Gorell": "barnes-luci-gorell",
    "BARNES Luke": "barnes-luke",
    "BARNES Maureen": "barnes-maureen",
    "BARNES Mick": "barnes-mick",
    "BARNES Nick": "barnes-nick",
    "BARNES Patrick": "barnes-patrick",
    "BARNES Perkin L": "barnes-perkin-l",
    "BARNES Peter": "barnes-peter",
    "BARNES R G": "barnes-r-g",
    "BARNES Roddy": "barnes-roddy",
    "BARNES Rof": "barnes-rof",
    "BARNES Rosy": "barnes-rosy",
    "BARNES Simon": "barnes-simon",
    "BARNES Terry": "barnes-terry",
    "BARNES Theo": "barnes-theo",
    "BARNES Tim": "barnes-tim",
    "BARNES Wilson": "barnes-wilson",
    "BARNETT Barb": "barnett-barb",
    "BARNETT Bill": "barnett-bill",
    "BARNETT C Z": "barnett-c-z",
    "BARNETT Charlie": "barnett-charlie",
    "BARNETT Claudia": "barnett-claudia",
    "BARNETT Dennis": "barnett-dennis",
    "BARNETT Douglas Q": "barnett-douglas-q",
    "BARNETT Gemma": "barnett-gemma",
    "BARNETT Gina": "barnett-gina",
    "BARNETT Ian": "barnett-ian",
    "BARNETT Jason": "barnett-jason",
    "BARNETT Julia": "barnett-julia",
    "BARNETT Katie": "barnett-katie",
    "BARNETT Leonard": "barnett-leonard",
    "BARNETT Linda": "barnett-linda",
    "BARNETT Margo": "barnett-margo",
    "BARNETT Marika": "barnett-marika",
    "BARNETT Pat": "barnett-pat",
    "BARNETT R M": "barnett-r-m",
    "BARNETT Rachel": "barnett-rachel",
    "BARNETT Robert": "barnett-robert",
    "BARNETT Sharon": "barnett-sharon",
    "BARNETT William": "barnett-william",
    "BARNEY Cary": "barney-cary",
    "BARNEY Steve": "barney-steve",
    "BARNFATHER Mick": "barnfather-mick",
    "BARNHAM Stuart": "barnham-stuart",
    "BARNHART Frank A": "barnhart-frank-a",
    "BARNHILL Gerg": "barnhill-gerg",
    "BARNHOUSE Dorothy": "barnhouse-dorothy",
    "BARNIEH Zina": "barnieh-zina",
    "BARNOSKY Adam": "barnosky-adam",
    "BARNSTONE Gabriella": "barnstone-gabriella",
    "BARNSTORM THEATRE COMPANY ": "barnstorm-theatre-company",
    "BAROCH Andrew": "baroch-andrew",
    "BAROMA Rebecca": "baroma-rebecca",
    "BARON Alec": "baron-alec",
    "BARON Anna": "baron-anna",
    "BARON Brad": "baron-brad",
    "BARON Courtney": "baron-courtney",
    "BARON David": "baron-david",
    "BARON J A": "baron-j-a",
    "BARON Jeff": "baron-jeff",
    "BARON Laignee": "baron-laignee",
    "BARON Mark": "baron-mark",
    "BARON Michael": "baron-michael",
    "BARON Michel": "baron-michel",
    "BARON Penny": "baron-penny",
    "BARON Robin": "baron-robin",
    "BARON Talila": "baron-talila",
    "BARONE Tina": "barone-tina",
    "BARONIAN Hagop": "baronian-hagop",
    "BARONNET Denis": "baronnet-denis",
    "BARON-PRAVDA Joseph": "baron-pravda-joseph",
    "BAROTO Michael": "baroto-michael",
    "BARR Alex": "barr-alex",
    "BARR Angus": "barr-angus",
    "BARR Christopher": "barr-christopher",
    "BARR Densil": "barr-densil",
    "BARR Donna": "barr-donna",
    "BARR Gordon": "barr-gordon",
    "BARR Hannah": "barr-hannah",
    "BARR Jennifer": "barr-jennifer",
    "BARR Jimmy": "barr-jimmy",
    "BARR June": "barr-june",
    "BARR Nancy": "barr-nancy",
    "BARR Robert": "barr-robert",
    "BARR Russell": "barr-russell",
    "BARR Sara": "barr-sara",
    "BARR III David": "barr-iii-david",
    "BARRA Stacie": "barra-stacie",
    "BARRACLOUGH Stephen": "barraclough-stephen",
    "BARRAKA Kenny": "barraka-kenny",
    "BARRAND Anita": "barrand-anita",
    "BARRAQUE Jorge": "barraque-jorge",
    "BARRAS Leonard": "barras-leonard",
    "BARRATT Julian": "barratt-julian",
    "BARRAULT Jean-Louis": "barrault-jean-louis",
    "BARRECA Carisa": "barreca-carisa",
    "BARREL ORGAN ": "barrel-organ",
    "BARRENO Maria Isabel": "barreno-maria-isabel",
    "BARRERA Genemichael": "barrera-genemichael",
    "BARRET Earl": "barret-earl",
    "BARRETO Alexander": "barreto-alexander",
    "BARRETO Eduardo": "barreto-eduardo",
    "BARRETT Andrew": "barrett-andrew",
    "BARRETT Andy": "barrett-andy",
    "BARRETT Anne": "barrett-anne",
    "BARRETT Billy": "barrett-billy",
    "BARRETT Carrie": "barrett-carrie",
    "BARRETT Catherine": "barrett-catherine",
    "BARRETT David": "barrett-david",
    "BARRETT Diana": "barrett-diana",
    "BARRETT E": "barrett-e",
    "BARRETT Felix": "barrett-felix",
    "BARRETT Glen": "barrett-glen",
    "BARRETT James Lee": "barrett-james-lee",
    "BARRETT John": "barrett-john",
    "BARRETT K K": "barrett-k-k",
    "BARRETT Kelly": "barrett-kelly",
    "BARRETT Lindsay": "barrett-lindsay",
    "BARRETT Nathan": "barrett-nathan",
    "BARRETT Nigel": "barrett-nigel",
    "BARRETT Patrick": "barrett-patrick",
    "BARRETT Paul": "barrett-paul",
    "BARRETT Richard": "barrett-richard",
    "BARRETT Ross": "barrett-ross",
    "BARRETT Ruth": "barrett-ruth",
    "BARRETT Steven": "barrett-steven",
    "BARRETT W S": "barrett-w-s",
    "BARRETT Zoe": "barrett-zoe",
    "BARRI Lisa": "barri-lisa",
    "BARRICO Alessandro": "barrico-alessandro",
    "BARRIE Frank": "barrie-frank",
    "BARRIE J M": "barrie-j-m",
    "BARRIE James": "barrie-james",
    "BARRIE Shirley": "barrie-shirley",
    "BARRIE Tom": "barrie-tom",
    "BARRIENTOS Marie": "barrientos-marie",
    "BARRINGER Michael": "barringer-michael",
    "BARRINGTON Don": "barrington-don",
    "BARRIOS Gregg": "barrios-gregg",
    "BARRIOS Will": "barrios-will",
    "BARRISH Seth": "barrish-seth",
    "BARROGA Jeannie": "barroga-jeannie",
    "BARRON Andrew": "barron-andrew",
    "BARRON Charles": "barron-charles",
    "BARRON Chris": "barron-chris",
    "BARRON Chris (1)": "barron-chris-1",
    "BARRON Clare": "barron-clare",
    "BARRON Craig": "barron-craig",
    "BARRON Douglas": "barron-douglas",
    "BARRON Jesse": "barron-jesse",
    "BARRON Laignee": "barron-laignee",
    "BARRON Mia": "barron-mia",
    "BARRON Ray": "barron-ray",
    "BARRON Rob": "barron-rob",
    "BARRON Sara": "barron-sara",
    "BARRON-WOOLFORD Ray": "barron-woolford-ray",
    "BARROSO Luis Q": "barroso-luis-q",
    "BARROW Amy Sabin": "barrow-amy-sabin",
    "BARROW Andy": "barrow-andy",
    "BARROW Anita": "barrow-anita",
    "BARROW Laura Kate": "barrow-laura-kate",
    "BARROW Scott": "barrow-scott",
    "BARROW Tim": "barrow-tim",
    "BARROW Will": "barrow-will",
    "BARROW William": "barrow-william",
    "BARROWS Anita": "barrows-anita",
    "BARROWS Eddy": "barrows-eddy",
    "BARROWS Stephen": "barrows-stephen",
    "BARRY Aideen": "barry-aideen",
    "BARRY Alice": "barry-alice",
    "BARRY Andrew": "barry-andrew",
    "BARRY B H": "barry-b-h",
    "BARRY Bob": "barry-bob",
    "BARRY Brian": "barry-brian",
    "BARRY Christian": "barry-christian",
    "BARRY Claire": "barry-claire",
    "BARRY Clifford": "barry-clifford",
    "BARRY David": "barry-david",
    "BARRY Eric": "barry-eric",
    "BARRY Frank": "barry-frank",
    "BARRY Ged": "barry-ged",
    "BARRY James": "barry-james",
    "BARRY Julian": "barry-julian",
    "BARRY Kevin": "barry-kevin",
    "BARRY Kevin (1)": "barry-1-kevin",
    "BARRY Kieron": "barry-kieron",
    "BARRY Leroy Elliston": "barry-leroy-elliston",
    "BARRY Lynda": "barry-lynda",
    "BARRY Marina": "barry-marina",
    "BARRY Michael": "barry-michael",
    "BARRY P J": "barry-p-j",
    "BARRY Paul": "barry-paul",
    "BARRY Pete": "barry-pete",
    "BARRY Philip": "barry-philip",
    "BARRY Ray": "barry-ray",
    "BARRY Scott": "barry-scott",
    "BARRY Sebastian": "barry-sebastian",
    "BARRY Simon": "barry-simon",
    "BARRY Thomas F": "barry-thomas-f",
    "BARRY Tom": "barry-tom",
    "BARRY Wendell": "barry-wendell",
    "BARSANTI-JACOBS Jarlath": "barsanti-jacobs-jarlath",
    "BARSBY John": "barsby-john",
    "BARSCH Norman": "barsch-norman",
    "BARSENESS Meghan": "barseness-meghan",
    "BARSHA Debra": "barsha-debra",
    "BARSHA Tony": "barsha-tony",
    "BARSKY Susan": "barsky-susan",
    "BARSLEY Michael": "barsley-michael",
    "BARSLUND Charlotte": "barslund-charlotte",
    "BARSNESS Andy": "barsness-andy",
    "BARSNESS Jonathan": "barsness-jonathan",
    "BARSOTTI Scott T": "barsotti-scott-t",
    "BARSTOW Stan": "barstow-stan",
    "BART Lionel": "bart-lionel",
    "BARTAVE Reine": "bartave-reine",
    "BARTEL Paul": "bartel-paul",
    "BARTEL Rob": "bartel-rob",
    "BARTEL Robert": "bartel-robert",
    "BARTELLE James": "bartelle-james",
    "BARTELSE Christel": "bartelse-christel",
    "BARTELT Martin M": "bartelt-martin-m",
    "BARTER Stuart": "barter-stuart",
    "BARTEVE Reine": "barteve-reine",
    "BARTH Crish": "barth-crish",
    "BARTH David": "barth-david",
    "BARTH Jim": "barth-jim",
    "BARTH Ruvin": "barth-ruvin",
    "BARTHA Caterina": "bartha-caterina",
    "BARTHEL George": "barthel-george",
    "BARTHELL Aleta Christine": "barthell-aleta-christine",
    "BARTHELME Donald": "barthelme-donald",
    "BARTHOL Bruce": "barthol-bruce",
    "BARTHOLOMAE Philip": "bartholomae-philip",
    "BARTHOLOMAEUS Nicholaus": "bartholomaeus-nicholaus",
    "BARTHOLOMEE Lowell": "bartholomee-lowell",
    "BARTHOLOMEW Clare": "bartholomew-clare",
    "BARTHOLOMEW Peter": "bartholomew-peter",
    "BARTHOLOMEW Vicki": "bartholomew-vicki",
    "BARTHOLOMEW Virginia": "bartholomew-virginia",
    "BARTINEIFF George": "bartineiff-george",
    "BARTLAU Penelope": "bartlau-penelope",
    "BARTLE Shane": "bartle-shane",
    "BARTLEBY H M": "bartleby-h-m",
    "BARTLEE Mike": "bartlee-mike",
    "BARTLETT Bob": "bartlett-bob",
    "BARTLETT Chris": "bartlett-chris",
    "BARTLETT D'Jamin": "bartlett-d-jamin",
    "BARTLETT Holley": "bartlett-holley",
    "BARTLETT Jayson": "bartlett-jayson",
    "BARTLETT Joyce": "bartlett-joyce",
    "BARTLETT Kate": "bartlett-kate",
    "BARTLETT Kenneth R": "bartlett-kenneth-r",
    "BARTLETT Matthew": "bartlett-matthew",
    "BARTLETT Mike": "bartlett-mike",
    "BARTLETT Neil": "bartlett-neil",
    "BARTLETT Nicholas": "bartlett-nicholas",
    "BARTLETT Rebecca": "bartlett-rebecca",
    "BARTLETT Robert Elwyn": "bartlett-robert-elwyn",
    "BARTLETT Roger": "bartlett-roger",
    "BARTLETT Ruth Dunlap": "bartlett-ruth-dunlap",
    "BARTLETT Will": "bartlett-will",
    "BARTLEY Charles B": "bartley-charles-b",
    "BARTLEY Jim": "bartley-jim",
    "BARTLEY Robert": "bartley-robert",
    "BARTO Michael": "barto-michael",
    "BARTOLONE Ben": "bartolone-ben",
    "BARTON Allen": "barton-allen",
    "BARTON Bob": "barton-bob",
    "BARTON Bronwen": "barton-bronwen",
    "BARTON Bruce": "barton-bruce",
    "BARTON Chris": "barton-chris",
    "BARTON Dave": "barton-dave",
    "BARTON Derek": "barton-derek",
    "BARTON Fred": "barton-fred",
    "BARTON Harry": "barton-harry",
    "BARTON Joe": "barton-joe",
    "BARTON John": "barton-john",
    "BARTON Jon": "barton-jon",
    "BARTON Lee": "barton-lee",
    "BARTON Lee (2)": "barton-lee-2",
    "BARTON Mary": "barton-mary",
    "BARTON Matthew": "barton-matthew",
    "BARTON Sally": "barton-sally",
    "BARTON Tammy": "barton-tammy",
    "BARTON Tiffany": "barton-tiffany",
    "BARTON Tony": "barton-tony",
    "BARTON-HOARE Charlotte": "barton-hoare-charlotte",
    "BARTRAM Neil": "bartram-neil",
    "BARTRAM Simon": "bartram-simon",
    "BARTSCH Hans": "bartsch-hans",
    "BARTSCH Paul Robert": "bartsch-paul-robert",
    "BARTUCCI Elizabeth": "bartucci-elizabeth",
    "BARUCH Brandon": "baruch-brandon",
    "BARUT Arda": "barut-arda",
    "BARUTI Osayande": "baruti-osayande",
    "BARWELL Leyland": "barwell-leyland",
    "BARWICK Liz": "barwick-liz",
    "BARWIS Michael": "barwis-michael",
    "BARYLLI Gabriel": "barylli-gabriel",
    "BAR-YOSEF Yosef": "bar-yosef-yosef",
    "BARZ Paul": "barz-paul",
    "BARZDUKAS Vidas": "barzdukas-vidas",
    "BARZILAY Anat": "barzilay-anat",
    "BARZUN Jacques": "barzun-jacques"
  }
};