export default {
  "metadata": {
    "results": 605,
    "timeStamp": "2025-12-05T21:22:07.195Z",
    "url": "https://www.doollee.com/PlaywrightsB/B_playwrights_bas-bel.php"
  },
  "authors": {
    "BASCH Abi": "basch-abi",
    "BASCH Peter": "basch-peter",
    "BASCHE Anastasia": "basche-anastasia",
    "BASCO Dante": "basco-dante",
    "BASCOMBE Ronald D": "bascombe-ronald-d",
    "BASDEN Tom": "basden-tom",
    "BASEL Clare": "basel-clare",
    "BASEMAN Peggy": "baseman-peggy",
    "BASESCU Jeremy": "basescu-jeremy",
    "BASH Todd": "bash-todd",
    "BASHAM A L": "basham-a-l",
    "BASHAM Melody": "basham-melody",
    "BASHAM Rebecca": "basham-rebecca",
    "BASHFORD John": "bashford-john",
    "BASHILINE Jessica": "bashiline-jessica",
    "BASHIRA Damali": "bashira-damali",
    "BASHWINER Meg": "bashwiner-meg",
    "BASIL TWIST CO ": "basil-twist-co",
    "BASILA Daniel": "basila-daniel",
    "BASILE Jean": "basile-jean",
    "BASKEYFIELD Gilly": "baskeyfield-gilly",
    "BASKIN Jeff": "baskin-jeff",
    "BASLOE Frank": "basloe-frank",
    "BASQUE Joe": "basque-joe",
    "BASS Chloe": "bass-chloe",
    "BASS Eric": "bass-eric",
    "BASS Francis": "bass-francis",
    "BASS George Houston": "bass-george-houston",
    "BASS Kyle": "bass-kyle",
    "BASS Mick": "bass-mick",
    "BASS Ronald": "bass-ronald",
    "BASS JR Kingsley B": "bass-jr-kingsley-b",
    "BASSANELLI Jacklyn": "bassanelli-jacklyn",
    "BASSEN Lois Shapley": "bassen-lois-shapley",
    "BASSEN Willa": "bassen-willa",
    "BASSETT Alexandra": "bassett-alexandra",
    "BASSETT C Dylan": "bassett-c-dylan",
    "BASSETT Natasha": "bassett-natasha",
    "BASSETT Nina Larissa": "bassett-nina-larissa",
    "BASSETT Rick V": "bassett-rick-v",
    "BASSETTI Alberto": "bassetti-alberto",
    "BASSEY Leemann Alexander": "bassey-leemann-alexander",
    "BASSIN Rose Ethel": "bassin-rose-ethel",
    "BASSO Beatrice": "basso-beatrice",
    "BASSO Daniel S": "basso-daniel-s",
    "BASSO Kimberly Davis": "basso-kimberly-davis",
    "BASSO Taylor": "basso-taylor",
    "BASTI Jawhar": "basti-jawhar",
    "BASTIAN Jon": "bastian-jon",
    "BASTIANES Maria": "bastianes-maria",
    "BASTIANO Anthony": "bastiano-anthony",
    "BASTIBLE Elaine": "bastible-elaine",
    "BASTIEN Marie-Josee": "bastien-marie-josee",
    "BASTIEN Stephen": "bastien-stephen",
    "BASTOCK Gill": "bastock-gill",
    "BASTONE Freddy": "bastone-freddy",
    "BASTRON Robert": "bastron-robert",
    "BATALION Judith": "batalion-judith",
    "BATALLA Perla": "batalla-perla",
    "BATALLA Rick": "batalla-rick",
    "BATAYOLA Maria": "batayola-maria",
    "BATCHELOR Don": "batchelor-don",
    "BATCHELOR Judd": "batchelor-judd",
    "BATCHELOR Ronald": "batchelor-ronald",
    "BATDORF Erika": "batdorf-erika",
    "BATE Jonathan": "bate-jonathan",
    "BATE Sam": "bate-sam",
    "BATELAAN Jetse": "batelaan-jetse",
    "BATEMAN David": "bateman-david",
    "BATEMAN Geoff": "bateman-geoff",
    "BATEMAN Joanna": "bateman-joanna",
    "BATEMAN Jonathan": "bateman-jonathan",
    "BATEMAN Lane": "bateman-lane",
    "BATEMAN Luke": "bateman-luke",
    "BATEMAN-GOLD Ira": "bateman-gold-ira",
    "BATES Alan": "bates-alan",
    "BATES Allan": "bates-allan",
    "BATES Brendon": "bates-brendon",
    "BATES Christopher D": "bates-christopher-d",
    "BATES David": "bates-david",
    "BATES Dianne": "bates-dianne",
    "BATES H E": "bates-h-e",
    "BATES H Jack": "bates-h-jack",
    "BATES Hank": "bates-hank",
    "BATES Helen": "bates-helen",
    "BATES Jaisey": "bates-jaisey",
    "BATES Jan": "bates-jan",
    "BATES Jess Holly": "bates-jess-holly",
    "BATES Jesse": "bates-jesse",
    "BATES Melody": "bates-melody",
    "BATES Natalie": "bates-natalie",
    "BATES Richard": "bates-richard",
    "BATES Stephen": "bates-stephen",
    "BATES Vanessa": "bates-vanessa",
    "BATESON David": "bateson-david",
    "BATH Michael": "bath-michael",
    "BATHOLOMEW Vicki": "batholomew-vicki",
    "BATHORY Kristof": "bathory-kristof",
    "BATHURST David": "bathurst-david",
    "BATHURST Robert": "bathurst-robert",
    "BATIENIEFF George": "batienieff-george",
    "BATISTICK Mike": "batistick-mike",
    "BATSFORD Marianne": "batsford-marianne",
    "BATSON Georg": "batson-georg",
    "BATSON George": "batson-george",
    "BATSON Susan": "batson-susan",
    "BATT Mike": "batt-mike",
    "BATTAN Rob": "battan-rob",
    "BATTEN Nikki": "batten-nikki",
    "BATTERSBY Charles": "battersby-charles",
    "BATTERSBY Liz": "battersby-liz",
    "BATTIMAMZEL PRODUCTIONS ": "battimamzel-productions",
    "BATTISTA Joseph John": "battista-joseph-john",
    "BATTLE Chris": "battle-chris",
    "BATTLE Hinton": "battle-hinton",
    "BATTLO Jean": "battlo-jean",
    "BATTMAN Duncan": "battman-duncan",
    "BATTOCCHIO Roy": "battocchio-roy",
    "BATTS Kate": "batts-kate",
    "BATTYE Don": "battye-don",
    "BATTYE Miriam": "battye-miriam",
    "BATTYE Susan": "battye-susan",
    "BATZ Michael": "batz-michael",
    "BAU Alan": "bau-alan",
    "BAUCHE Henri": "bauche-henri",
    "BAUDRILLARD Jean": "baudrillard-jean",
    "BAUER Andrew": "bauer-andrew",
    "BAUER Ann G": "bauer-ann-g",
    "BAUER C Andrew": "bauer-c-andrew",
    "BAUER Carlos": "bauer-carlos",
    "BAUER Edward": "bauer-edward",
    "BAUER Felice": "bauer-felice",
    "BAUER Irv": "bauer-irv",
    "BAUER James": "bauer-james",
    "BAUER Jim": "bauer-jim",
    "BAUER Kristina": "bauer-kristina",
    "BAUER Monica": "bauer-monica",
    "BAUER P Seth": "bauer-p-seth",
    "BAUER Ruth": "bauer-ruth",
    "BAUER Tim": "bauer-tim",
    "BAUER Todd": "bauer-todd",
    "BAUER V Stephen": "bauer-v-stephen",
    "BAUER Wolfgang": "bauer-wolfgang",
    "BAUER Wolfgang Maria": "bauer-wolfgang-maria",
    "BAUER  Monica": "bauer-monica",
    "BAUERFELD Jonathan": "bauerfeld-jonathan",
    "BAUERSIMA Igor": "bauersima-igor",
    "BAUGH Mike": "baugh-mike",
    "BAUGH Pat": "baugh-pat",
    "BAUGH Tereza": "baugh-tereza",
    "BAUGHMAN Andrew Lloyd": "baughman-andrew-lloyd",
    "BAUKHAGE Hilmar": "baukhage-hilmar",
    "BAULAND Peter": "bauland-peter",
    "BAUM Anna": "baum-anna",
    "BAUM Dan": "baum-dan",
    "BAUM L Frank": "baum-l-frank",
    "BAUM Martin": "baum-martin",
    "BAUM Ross Avery": "baum-ross-avery",
    "BAUM Samuel": "baum-samuel",
    "BAUM Terry": "baum-terry",
    "BAUM Tom": "baum-tom",
    "BAUMAN Brian": "bauman-brian",
    "BAUMAN Jessica": "bauman-jessica",
    "BAUMANN Stephen Wayne": "baumann-stephen-wayne",
    "BAUMBUSCH Paul": "baumbusch-paul",
    "BAUMUNG Jeremy": "baumung-jeremy",
    "BAURIEDEL Quinn": "bauriedel-quinn",
    "BAUS Ted": "baus-ted",
    "BAUSKE Kris": "bauske-kris",
    "BAUTISTA Kilusan": "bautista-kilusan",
    "BAVINTON George": "bavinton-george",
    "BAVOSO John": "bavoso-john",
    "BAWLER Stuart H": "bawler-stuart-h",
    "BAWTREE Michael": "bawtree-michael",
    "BAX Clifford": "bax-clifford",
    "BAXANDALL Lee": "baxandall-lee",
    "BAXENDALE Gary": "baxendale-gary",
    "BAXT George": "baxt-george",
    "BAXTER Annan Jenkinson": "baxter-annan-jenkinson",
    "BAXTER Craig": "baxter-craig",
    "BAXTER David": "baxter-david",
    "BAXTER Gary": "baxter-gary",
    "BAXTER Holly": "baxter-holly",
    "BAXTER James K": "baxter-james-k",
    "BAXTER Keith": "baxter-keith",
    "BAXTER Kyle": "baxter-kyle",
    "BAXTER Nikki-Fay": "baxter-nikki-fay",
    "BAXTER Susie": "baxter-susie",
    "BAXTER Trevor": "baxter-trevor",
    "BAXTER THEATRE CENTRE ": "baxter-theatre-centre",
    "BAXTRESSER Clark": "baxtresser-clark",
    "BAY Ellen": "bay-ellen",
    "BAYA Raisedon": "baya-raisedon",
    "BAYARDELLE Jeannette": "bayardelle-jeannette",
    "BAYBUTT Alexandra": "baybutt-alexandra",
    "BAY-CHENG Sarah": "bay-cheng-sarah",
    "BAYER Danny": "bayer-danny",
    "BAYER Eleanor": "bayer-eleanor",
    "BAYER Konrad": "bayer-konrad",
    "BAYER Leo": "bayer-leo",
    "BAYER Matt": "bayer-matt",
    "BAYER Teresa Ann Virginia": "bayer-teresa-ann-virginia",
    "BAYES Helen": "bayes-helen",
    "BAYES Sammy Dallas": "bayes-sammy-dallas",
    "BAYEZA Ifa": "bayeza-ifa",
    "BAYFIELD Jonnie": "bayfield-jonnie",
    "BAYIATES Andy": "bayiates-andy",
    "BAYLEY Alan": "bayley-alan",
    "BAYLEY Clare": "bayley-clare",
    "BAYLEY Robert": "bayley-robert",
    "BAYLY Jane": "bayly-jane",
    "BAYNTON Martin": "baynton-martin",
    "BAYS Carter L": "bays-carter-l",
    "BAYS Joe": "bays-joe",
    "BAYS Lisa": "bays-lisa",
    "BAZ Michael": "baz-michael",
    "BAZ PRODUCTIONS ": "baz-productions",
    "BAZALA Brian": "bazala-brian",
    "BAZARGAN Susan": "bazargan-susan",
    "BAZARINI Ronald": "bazarini-ronald",
    "BAZELL Jennie": "bazell-jennie",
    "BAZELL Matthew": "bazell-matthew",
    "BAZEMORE Jean": "bazemore-jean",
    "BAZER Bob": "bazer-bob",
    "BAZZINI Donald": "bazzini-donald",
    "BAZZONE Mark": "bazzone-mark",
    "BE Carlos": "be-carlos",
    "BEA Jennifer": "bea-jennifer",
    "BEACH Lewis": "beach-lewis",
    "BEACH Samantha": "beach-samantha",
    "BEACHAM Frank": "beacham-frank",
    "BEACHAM Richard": "beacham-richard",
    "BEACHAM Rod": "beacham-rod",
    "BEACHY Mark Andrew": "beachy-mark-andrew",
    "BEADLE Philip": "beadle-philip",
    "BEADLE Richard": "beadle-richard",
    "BEADLE-BLAIR Rikki": "beadle-blair-rikki",
    "BEAGAN Tara": "beagan-tara",
    "BEAGLEY Lee": "beagley-lee",
    "BEAGON James": "beagon-james",
    "BEAIRD Betty J": "beaird-betty-j",
    "BEAIRD David": "beaird-david",
    "BEAL Tita": "beal-tita",
    "BEALE Jack": "beale-jack",
    "BEALE Jane": "beale-jane",
    "BEALE Paul": "beale-paul",
    "BEALL Eric": "beall-eric",
    "BEALS Kurt": "beals-kurt",
    "BEAM Greg": "beam-greg",
    "BEAM Phoenix": "beam-phoenix",
    "BEAMAN James": "beaman-james",
    "BEAMAN Lawrence": "beaman-lawrence",
    "BEAME Edmond S": "beame-edmond-s",
    "BEAMES Margaret": "beames-margaret",
    "BEAMISH Jamie": "beamish-jamie",
    "BEAMISH Oliver": "beamish-oliver",
    "BEAN Anne": "bean-anne",
    "BEAN Jordan": "bean-jordan",
    "BEAN Kellie": "bean-kellie",
    "BEAN Melanie P": "bean-melanie-p",
    "BEAN Mimi": "bean-mimi",
    "BEAN Orson": "bean-orson",
    "BEAN Richard": "bean-richard",
    "BEAN Roger": "bean-roger",
    "BEAN Rupert": "bean-rupert",
    "BEANE Douglas Carter": "beane-douglas-carter",
    "BEAR A": "bear-a",
    "BEAR Jessie": "bear-jessie",
    "BEARD Francesca": "beard-francesca",
    "BEARD James Lair": "beard-james-lair",
    "BEARD Jocelyn": "beard-jocelyn",
    "BEARD Paul": "beard-paul",
    "BEARD Tom": "beard-tom",
    "BEARDSLEY Bonnie": "beardsley-bonnie",
    "BEARDSLEY Elaine": "beardsley-elaine",
    "BEARE Beryl": "beare-beryl",
    "BEASLEY Eloise": "beasley-eloise",
    "BEASLEY Mo": "beasley-mo",
    "BEASLEY William \"Bill\"": "beasley-william-bill",
    "BEASLEY William Martin": "beasley-william-martin",
    "BEASLEY-GARRIGAN Holly": "beasley-garrigan-holly",
    "BEASTROM Greg": "beastrom-greg",
    "BEAT Jackie": "beat-jackie",
    "BEATON Alistair": "beaton-alistair",
    "BEATON Calum": "beaton-calum",
    "BEATON Hilary": "beaton-hilary",
    "BEATON Norman": "beaton-norman",
    "BEATTIE Andrew": "beattie-andrew",
    "BEATTIE Dean H": "beattie-dean-h",
    "BEATTIE Douglas": "beattie-douglas",
    "BEATTIE Luke": "beattie-luke",
    "BEATTIE Simon": "beattie-simon",
    "BEATTS Anne": "beatts-anne",
    "BEATTY Doug": "beatty-doug",
    "BEATTY Glenn": "beatty-glenn",
    "BEATTY Glenn Stuart": "beatty-glenn-stuart",
    "BEATTY Jeffrey": "beatty-jeffrey",
    "BEATTY Lucille": "beatty-lucille",
    "BEATY Daniel": "beaty-daniel",
    "BEATY Tangie Brickhouse": "beaty-tangie-brickhouse",
    "BEAU Dickie": "beau-dickie",
    "BEAU Idgie": "beau-idgie",
    "BEAUCHEMIN Esther": "beauchemin-esther",
    "BEAUFOY Simon": "beaufoy-simon",
    "BEAUMARCHAIS ": "beaumarchais",
    "BEAUMONT Aaron": "beaumont-aaron",
    "BEAUMONT James": "beaumont-james",
    "BEAUMONT Robert": "beaumont-robert",
    "BEAUMONT Sally": "beaumont-sally",
    "BEAUPERT Fleur": "beaupert-fleur",
    "BEAUREGARD Jon": "beauregard-jon",
    "BEAUSEJOUR Marie Pierre": "beausejour-marie-pierre",
    "BEAUVOIR Simone De": "beauvoir-simone-de",
    "BEAVER Brad": "beaver-brad",
    "BEAVER Irene": "beaver-irene",
    "BEAVER Jim": "beaver-jim",
    "BEAVERS David P": "beavers-david-p",
    "BEAVERS Geoffrey": "beavers-geoffrey",
    "BEAVERS Jon": "beavers-jon",
    "BEAVIS Kara": "beavis-kara",
    "BEBBER Neil": "bebber-neil",
    "BEBER Joan": "beber-joan",
    "BEBER Neena": "beber-neena",
    "BECHER Alan": "becher-alan",
    "BECHER Bobby": "becher-bobby",
    "BECHER Eve": "becher-eve",
    "BECHER Ulrich": "becher-ulrich",
    "BECIJOS Jeanne": "becijos-jeanne",
    "BECK Alex": "beck-alex",
    "BECK D A": "beck-d-a",
    "BECK Daniel": "beck-daniel",
    "BECK David": "beck-david",
    "BECK Emilie": "beck-emilie",
    "BECK Frances Patricia": "beck-frances-patricia",
    "BECK Gary": "beck-gary",
    "BECK Jeremy": "beck-jeremy",
    "BECK Jessica": "beck-jessica",
    "BECK Joe": "beck-joe",
    "BECK Julian": "beck-julian",
    "BECK Raphe": "beck-raphe",
    "BECK Ryan": "beck-ryan",
    "BECK Sara": "beck-sara",
    "BECK Sarah": "beck-sarah",
    "BECK Terry": "beck-terry",
    "BECK Tom": "beck-tom",
    "BECKEMEYER Wesley": "beckemeyer-wesley",
    "BECKEMEYER Wesley Dalton": "beckemeyer-wesley-dalton",
    "BECKER Alan Bruce": "becker-alan-bruce",
    "BECKER Barbara": "becker-barbara",
    "BECKER Bill": "becker-bill",
    "BECKER Carson Grace": "becker-carson-grace",
    "BECKER Frawley": "becker-frawley",
    "BECKER John": "becker-john",
    "BECKER Lee": "becker-lee",
    "BECKER Lesley": "becker-lesley",
    "BECKER Rob": "becker-rob",
    "BECKER Steven": "becker-steven",
    "BECKERMAN Ellen": "beckerman-ellen",
    "BECKERMAN Howard": "beckerman-howard",
    "BECKERMAN Jim": "beckerman-jim",
    "BECKERS Patrick": "beckers-patrick",
    "BECKET Edward": "becket-edward",
    "BECKETT David": "beckett-david",
    "BECKETT Francis": "beckett-francis",
    "BECKETT Hal Foxton": "beckett-hal-foxton",
    "BECKETT Nancy": "beckett-nancy",
    "BECKETT Nathan": "beckett-nathan",
    "BECKETT Samuel": "beckett-samuel",
    "BECKETT Wendy": "beckett-wendy",
    "BECKHAM Barry": "beckham-barry",
    "BECKHAM Willard": "beckham-willard",
    "BECKIM Chad": "beckim-chad",
    "BECKLEY Ben": "beckley-ben",
    "BECKLEY Connie": "beckley-connie",
    "BECKLEY Jon": "beckley-jon",
    "BECKLEY Michael": "beckley-michael",
    "BECKLEY Piers": "beckley-piers",
    "BECKLEY Rafe": "beckley-rafe",
    "BECKMAN Anita": "beckman-anita",
    "BECKMAN Jill": "beckman-jill",
    "BECKMAN Jules": "beckman-jules",
    "BECKWITH Jeanne": "beckwith-jeanne",
    "BECKWITH Nikole": "beckwith-nikole",
    "BECKWITH-SMITH Susan": "beckwith-smith-susan",
    "BECQUE Henri": "becque-henri",
    "BEDARD Christian": "bedard-christian",
    "BEDARD Mark": "bedard-mark",
    "BEDDARD Jamie": "beddard-jamie",
    "BEDDOE Jack Dallas": "beddoe-jack-dallas",
    "BEDDOWS Chris": "beddows-chris",
    "BEDFORD Brian": "bedford-brian",
    "BEDFORD Debora": "bedford-debora",
    "BEDFORD George Randolph": "bedford-george-randolph",
    "BEDFORD Ian": "bedford-ian",
    "BEDFORD Jessica Lindsey": "bedford-jessica-lindsey",
    "BEDFORD Randolph": "bedford-randolph",
    "BEDFORD Tom": "bedford-tom",
    "BEDIAKO Barbara K Asare": "bediako-barbara-k-asare",
    "BEDILLION Jeff": "bedillion-jeff",
    "BEDLOE Christopher": "bedloe-christopher",
    "BEDLOW Henry": "bedlow-henry",
    "BEDNARCZYK Stefan": "bednarczyk-stefan",
    "BEDNARIK Jozef": "bednarik-jozef",
    "BED-STUY STREET ACADEMY ": "bed-stuy-street-academy",
    "BED-STUY THEATRE ": "bed-stuy-theatre",
    "BEDWELL Simon": "bedwell-simon",
    "BEE Sandra": "bee-sandra",
    "BEE GEES ": "beegees",
    "BEEBE Dick": "beebe-dick",
    "BEEBE Hank": "beebe-hank",
    "BEEBY George Stephenson": "beeby-george-stephenson",
    "BEECH Alex": "beech-alex",
    "BEECH J Michael": "beech-j-michael",
    "BEECH Maria Alexandria": "beech-maria-alexandria",
    "BEECH Marjorie": "beech-marjorie",
    "BEECH Nisha": "beech-nisha",
    "BEECH Richard": "beech-richard",
    "BEECHAM Cassie": "beecham-cassie",
    "BEECHAM Dolly": "beecham-dolly",
    "BEECHAM Emily": "beecham-emily",
    "BEECHAM Jahanna": "beecham-jahanna",
    "BEECHEN Adam": "beechen-adam",
    "BEECHER Emily": "beecher-emily",
    "BEECHWOOD Jeanne": "beechwood-jeanne",
    "BEECHY HIGH SCHOOL DRAMA CLUB ": "beechy-high-school-drama",
    "BEEDE Mike": "beede-mike",
    "BEEDLES Russell": "beedles-russell",
    "BEEGLE Rebecca": "beegle-rebecca",
    "BEEKER Jefferson Charles": "beeker-jefferson-charles",
    "BEELER David": "beeler-david",
    "BEEM John Lockwood": "beem-john-lockwood",
    "BEENY James": "beeny-james",
    "BEER David": "beer-david",
    "BEER Ilem": "beer-ilem",
    "BEER Val": "beer-val",
    "BEER SHEVA FRINGE THEATRE'S \u001cAYIT\u001d ENSEMBLE ": "beer-sheva-fringe-theatre-s-ayit-ensemble",
    "BEERMAN Josh": "beerman-josh",
    "BEERY Barbara N": "beery-barbara-n",
    "BEERY Erin": "beery-erin",
    "BEES Sam": "bees-sam",
    "BEESLEY Terence": "beesley-terence",
    "BEESLEY Victoria": "beesley-victoria",
    "BEESON Jane": "beeson-jane",
    "BEESON Mark": "beeson-mark",
    "BEESON Richard": "beeson-richard",
    "BEETON Daryl": "beeton-daryl",
    "BEEVERS Geoffrey": "beevers-geoffrey",
    "BEGAUDEAU Francois": "begaudeau-francois",
    "BEGGARLY Jim": "beggarly-jim",
    "BEGHEL Larry": "beghel-larry",
    "BEGLEY Michael": "begley-michael",
    "BEGLEY, JR Ed": "begley-jr-ed",
    "BEGUELIN Chad": "beguelin-chad",
    "BEGY J F": "begy-j-f",
    "BEHAN Brendan": "behan-brendan",
    "BEHAN Brian": "behan-brian",
    "BEHAN Dominic": "behan-dominic",
    "BEHAN Janet": "behan-janet",
    "BEHAN Lou Ann K": "behan-lou-ann-k",
    "BEHLMANN John": "behlmann-john",
    "BEHN Aphra": "behn-aphra",
    "BEHNING Janet": "behning-janet",
    "BEHR Caroline": "behr-caroline",
    "BEHR James": "behr-james",
    "BEHREN Ben": "behren-ben",
    "BEHRENS Peter": "behrens-peter",
    "BEHRENS Sean": "behrens-sean",
    "BEHRINGER Madison": "behringer-madison",
    "BEHRMAN Nicola": "behrman-nicola",
    "BEHRMAN S N": "behrman-s-n",
    "BEICH Albert": "beich-albert",
    "BEIDERMAN Robert": "beiderman-robert",
    "BEIER Christopher C": "beier-christopher-c",
    "BEIGEL Winston": "beigel-winston",
    "BEIHL Hans": "beihl-hans",
    "BEIM Norman": "beim-norman",
    "BEIRAO Ricky": "beirao-ricky",
    "BEISSEL Henry": "beissel-henry",
    "BEJAN Cristina": "bejan-cristina",
    "BEJOIAN Barbara": "bejoian-barbara",
    "BEK Jeff": "bek-jeff",
    "BEKEDEREMO J P Clark": "bekederemo-j-p-clark",
    "BEKERMAN-GREENBERG Riva": "bekerman-greenberg-riva",
    "BELANGER Hugo": "belanger-hugo",
    "BELANGER Jeff": "belanger-jeff",
    "BELARUS FREE THEATRE ": "belarus-free-theatre",
    "BELASCO David": "belasco-david",
    "BELBEL Sergi": "belbel-sergi",
    "BELBER Stephen": "belber-stephen",
    "BELC Anna": "belc-anna",
    "BELCHER Andrew": "belcher-andrew",
    "BELCHER David": "belcher-david",
    "BELD Jessica": "beld-jessica",
    "BELDEN Wendy": "belden-wendy",
    "BELDY Killian": "beldy-killian",
    "BELETSKY Rodion": "beletsky-rodion",
    "BELFIELD Lowell": "belfield-lowell",
    "BELFIELD Robin": "belfield-robin",
    "BELFIORE Michael": "belfiore-michael",
    "BELFORT Bernardo": "belfort-bernardo",
    "BELGHEL Larry": "belghel-larry",
    "BELGRADE TIE, COVENTRY ": "belgrade-tie-coventry",
    "BELGRADER Andrei": "belgrader-andrei",
    "BELGRAIER Bernett": "belgraier-bernett",
    "BELICH Sam": "belich-sam",
    "BELICH T James": "belich-t-james",
    "BELIVEAU Crystal": "beliveau-crystal",
    "BELIZARIO Moises Roberto": "belizario-moises-roberto",
    "BELKE David": "belke-david",
    "BELKIN Harriet": "belkin-harriet",
    "BELKIN Norman": "belkin-norman",
    "BELL A Craig": "bell-a-craig",
    "BELL Aidan": "bell-aidan",
    "BELL Amy": "bell-amy",
    "BELL Andrew": "bell-andrew",
    "BELL Brenda": "bell-brenda",
    "BELL Bruce": "bell-bruce",
    "BELL Chris": "bell-chris",
    "BELL Colin": "bell-colin",
    "BELL D": "bell-d",
    "BELL Daniel": "bell-daniel",
    "BELL David": "bell-david",
    "BELL David (1)": "bell-david-1",
    "BELL David H": "bell-david-h",
    "BELL Denise": "bell-denise",
    "BELL Diana": "bell-diana",
    "BELL Edward": "bell-edward",
    "BELL Ernest": "bell-ernest",
    "BELL Gelsey": "bell-gelsey",
    "BELL Gerard": "bell-gerard",
    "BELL Hilary": "bell-hilary",
    "BELL Hunter": "bell-hunter",
    "BELL J J": "bell-j-j",
    "BELL James A": "bell-james-a",
    "BELL Jim": "bell-jim",
    "BELL John": "bell-john",
    "BELL Jonathan": "bell-jonathan",
    "BELL Kate": "bell-kate",
    "BELL Kelvyn": "bell-kelvyn",
    "BELL Kenny": "bell-kenny",
    "BELL Kiri": "bell-kiri",
    "BELL Lucy": "bell-lucy",
    "BELL Maeve": "bell-maeve",
    "BELL Martyn": "bell-martyn",
    "BELL Melissa": "bell-melissa",
    "BELL Michael": "bell-michael",
    "BELL Mike": "bell-mike",
    "BELL Molly": "bell-molly",
    "BELL Nancy": "bell-nancy",
    "BELL Neal": "bell-neal",
    "BELL Nileah": "bell-nileah",
    "BELL Robert": "bell-robert",
    "BELL Ruth": "bell-ruth",
    "BELL Samantha": "bell-samantha",
    "BELL Suzanne": "bell-suzanne",
    "BELL Tim": "bell-tim",
    "BELL Tomas": "bell-tomas",
    "BELL Tommacina": "bell-tommacina",
    "BELL W Kamau": "bell-w-kamau",
    "BELL Winston Bello": "bell-winston-bello",
    "BELL JR Robert": "bell-jr-robert",
    "BELLA Rebecca": "bella-rebecca",
    "BELLAMO Samantha": "bellamo-samantha",
    "BELLAMY Brad": "bellamy-brad",
    "BELLAMY E C": "bellamy-e-c",
    "BELLAMY Holly": "bellamy-holly",
    "BELLAMY Jessica": "bellamy-jessica",
    "BELLAND Bruce": "belland-bruce",
    "BELLE Christine": "belle-christine",
    "BELLEAU Lesley": "belleau-lesley",
    "BELLEFEUILLE Robert": "bellefeuille-robert",
    "BELLEKOM Antony": "bellekom-antony",
    "BELLER Alexandra": "beller-alexandra",
    "BELLER JR James": "beller-james",
    "BELLIDO Jose-Maria": "bellido-jose-maria",
    "BELLIN Andy": "bellin-andy",
    "BELLING Larry": "belling-larry",
    "BELLINGHAM Natalie": "bellingham-natalie",
    "BELLINI D G": "bellini-d-g",
    "BELLITO Nick": "bellito-nick",
    "BELLMAN Barbara Lynn": "bellman-barbara-lynn",
    "BELLO Ademola": "bello-ademola",
    "BELLOMO John": "bellomo-john",
    "BELLOMY Cecelia": "bellomy-cecelia",
    "BELLON Gregg": "bellon-gregg",
    "BELLON Loleh": "bellon-loleh",
    "BELLONI Alessandra": "belloni-alessandra",
    "BELLOW Saul": "bellow-saul",
    "BELLU Paola": "bellu-paola",
    "BELLUSO John": "belluso-john",
    "BELL-WYKES Kamarra": "bell-wykes-kamarra",
    "BELMONT Dan": "belmont-dan",
    "BELMONT Mary": "belmont-mary",
    "BELOFF Jim": "beloff-jim",
    "BELOIN Edmund": "beloin-edmund",
    "BELONI Sidney": "beloni-sidney",
    "BELOV Chas": "belov-chas",
    "BELOV Sergie": "belov-sergie",
    "BELOVITCH Brian": "belovitch-brian",
    "BELPANNO Shawn": "belpanno-shawn",
    "BELSON Mark": "belson-mark",
    "BELTON Langston": "belton-langston",
    "BELWALKAR Prashant": "belwalkar-prashant",
    "BELY Andrei": "bely-andrei",
    "BELZ Albert": "belz-albert"
  }
};