export default {
  "metadata": {
    "results": 512,
    "timeStamp": "2025-12-05T21:22:10.566Z",
    "url": "https://www.doollee.com/PlaywrightsB/B_playwrights_bem-bev.php"
  },
  "authors": {
    "BEMARRO SISTERS ": "bemarro-sisters",
    "BEMBERG George": "bemberg-george",
    "BEMBRIDGE Joseph": "bembridge-joseph",
    "BEMELMANS Ludwig": "bemelmans-ludwig",
    "BEN ZA'AEV Chayim": "ben-za-aev-chayim",
    "BEN-ABDALLAH Leila": "ben-abdallah-leila",
    "BENACERRAF Nick": "benacerraf-nick",
    "BENALI Abdelkader": "benali-abdelkader",
    "BENARD Lynwoodt": "benard-lynwoodt",
    "BEN-ARIE David": "ben-arie-david",
    "BENASSI Marco": "benassi-marco",
    "BEN-ATAR Doron": "ben-atar-doron",
    "BENATSKY Ralph": "benatsky-ralph",
    "BENAVENTE David": "benavente-david",
    "BENAVENTE Jacinto": "benavente-jacinto",
    "BENAVIDES Leah": "benavides-leah",
    "BENCE Charlotte W": "bence-charlotte-w",
    "BENCHLEY Robert": "benchley-robert",
    "BENCHTOURS ": "benchtours",
    "BENCIVENGA Mike": "bencivenga-mike",
    "BENDER Emily": "bender-emily",
    "BENDER Jonathan": "bender-jonathan",
    "BENDER Katie": "bender-katie",
    "BENDER Lea": "bender-lea",
    "BENDER Russell": "bender-russell",
    "BENDON Chris": "bendon-chris",
    "BENDOTTI Marcelo L": "bendotti-marcelo-l",
    "BENECKE Patricia": "benecke-patricia",
    "BENEDETTI Jean": "benedetti-jean",
    "BENEDETTI Mario": "benedetti-mario",
    "BENEDETTO ": "benedetto",
    "BENEDICKT Michael": "benedickt-michael",
    "BENEDICT Amy": "benedict-amy",
    "BENEDICT David": "benedict-david",
    "BENEDICT E H": "benedict-e-h",
    "BENEDICT Helen": "benedict-helen",
    "BENEDICT Peter": "benedict-peter",
    "BENEDICT Stewart Hurd": "benedict-stewart-hurd",
    "BENEDICTSSON Victoria": "benedictsson-victoria",
    "BENEDICTUS David": "benedictus-david",
    "BENEDIKT Michael": "benedikt-michael",
    "BENEDYK Krystyn Jo": "benedyk-krystyn-jo",
    "BENEFIEL Hilary": "benefiel-hilary",
    "BENELLI Karen": "benelli-karen",
    "BENENSON Joel": "benenson-joel",
    "BENET Bebe Zahara": "benet-bebe-zahara",
    "BENET Stephen Vincent": "benet-stephen-vincent",
    "BENET I JORNET Josep Maria": "benet-i-jornet-josep-maria",
    "BENFIELD Derek": "benfield-derek",
    "BENFORF Robert": "benforf-robert",
    "BENGE Candice": "benge-candice",
    "BENGE Cheryl": "benge-cheryl",
    "BENGE Tony": "benge-tony",
    "BENGSON Abigail Nessen": "bengson-abigail-nessen",
    "BENGSON Shaun": "bengson-shaun",
    "BENHAM Aaron": "benham-aaron",
    "BENINGTON Roger": "benington-roger",
    "BENISON Ben": "benison-ben",
    "BENITEZ Hannah": "benitez-hannah",
    "BENJAMIN Adrian": "benjamin-adrian",
    "BENJAMIN Arthur": "benjamin-arthur",
    "BENJAMIN Dean A": "benjamin-dean-a",
    "BENJAMIN Joel": "benjamin-joel",
    "BENJAMIN Keith Alan": "benjamin-keith-alan",
    "BENJAMIN Kit": "benjamin-kit",
    "BENJAMIN Matthew": "benjamin-matthew",
    "BENJAMIN Nell": "benjamin-nell",
    "BENJAMIN Paul": "benjamin-paul",
    "BENJAMIN Peter": "benjamin-peter",
    "BENJAMIN Robert F": "benjamin-robert-f",
    "BENJAMIN Sam": "benjamin-sam",
    "BENJAMIN Saragail": "benjamin-saragail",
    "BENJAMIN Sean": "benjamin-sean",
    "BENJULIAN Jayne": "benjulian-jayne",
    "BENKO Tina": "benko-tina",
    "BENMUSSA Simone": "benmussa-simone",
    "BENN Alicia": "benn-alicia",
    "BENN Gottfried": "benn-gottfried",
    "BENNATHAN Joss": "bennathan-joss",
    "BENNEKE Patricia": "benneke-patricia",
    "BENNET Cherry": "bennet-cherry",
    "BENNET Eleanor": "bennet-eleanor",
    "BENNET Elinor": "bennet-elinor",
    "BENNET Mark": "bennet-mark",
    "BENNETT Alan": "bennett-alan",
    "BENNETT Alexandra": "bennett-alexandra",
    "BENNETT Andy": "bennett-andy",
    "BENNETT Annika": "bennett-annika",
    "BENNETT Beate Heine": "bennett-beate-heine",
    "BENNETT Betsy": "bennett-betsy",
    "BENNETT Brian": "bennett-brian",
    "BENNETT Carolyn": "bennett-carolyn",
    "BENNETT Catherine": "bennett-catherine",
    "BENNETT Cherie": "bennett-cherie",
    "BENNETT Colin": "bennett-colin",
    "BENNETT Connie J": "bennett-connie-j",
    "BENNETT David": "bennett-david",
    "BENNETT David H": "bennett-david-h",
    "BENNETT Elisabeth": "bennett-elisabeth",
    "BENNETT Elizabeth": "bennett-elizabeth",
    "BENNETT Emma": "bennett-emma",
    "BENNETT Erica Harriet": "bennett-erica-harriet",
    "BENNETT F J": "bennett-f-j",
    "BENNETT F R": "bennett-f-r",
    "BENNETT Garrett": "bennett-garrett",
    "BENNETT Gillian": "bennett-gillian",
    "BENNETT Gordon": "bennett-gordon",
    "BENNETT Harriet V": "bennett-harriet-v",
    "BENNETT J": "bennett-j",
    "BENNETT Jack": "bennett-jack",
    "BENNETT Jay": "bennett-jay",
    "BENNETT Jimmy": "bennett-jimmy",
    "BENNETT Joan Sterndale": "bennett-joan-sterndale",
    "BENNETT Joe": "bennett-joe",
    "BENNETT Joel": "bennett-joel",
    "BENNETT John": "bennett-john",
    "BENNETT Jordan": "bennett-jordan",
    "BENNETT Lorna": "bennett-lorna",
    "BENNETT Lucy": "bennett-lucy",
    "BENNETT Lucy (1)": "bennett-lucy-1",
    "BENNETT Mark": "bennett-mark",
    "BENNETT Matthew": "bennett-matthew",
    "BENNETT Matthew Ivan": "bennett-matthew-ivan",
    "BENNETT Michael": "bennett-michael",
    "BENNETT Mike": "bennett-mike",
    "BENNETT Nat": "bennett-nat",
    "BENNETT Ned": "bennett-ned",
    "BENNETT Oliver": "bennett-oliver",
    "BENNETT Rodney": "bennett-rodney",
    "BENNETT Roger": "bennett-roger",
    "BENNETT Russell": "bennett-russell",
    "BENNETT Sean David": "bennett-sean-david",
    "BENNETT Simon": "bennett-simon",
    "BENNETT Steve": "bennett-steve",
    "BENNETT Thom": "bennett-thom",
    "BENNETT Tony": "bennett-tony",
    "BENNETT Walter Allen": "bennett-walter-allen",
    "BENNETTE-HUME Peggy": "bennette-hume-peggy",
    "BENNETTS Anna": "bennetts-anna",
    "BENNETTS Brendon": "bennetts-brendon",
    "BENNI Stefano": "benni-stefano",
    "BENNION Barbara": "bennion-barbara",
    "BENNION Chris": "bennion-chris",
    "BENNITT Caroline": "bennitt-caroline",
    "BENN-LAWLER Alicia": "benn-lawler-alicia",
    "BENNUN Neil": "bennun-neil",
    "BENOLIEL Daniel": "benoliel-daniel",
    "BEN-ONI Rosebud": "ben-oni-rosebud",
    "BENOZA Noel": "benoza-noel",
    "BEN-SHALOM Miri": "ben-shalom-miri",
    "BENSINGER Lenore": "bensinger-lenore",
    "BENSON Angelyn": "benson-angelyn",
    "BENSON Carol": "benson-carol",
    "BENSON David": "benson-david",
    "BENSON Elizabeth": "benson-elizabeth",
    "BENSON Emma": "benson-emma",
    "BENSON Eugene": "benson-eugene",
    "BENSON Fi": "benson-fi",
    "BENSON France-Luce": "benson-france-luce",
    "BENSON Islay": "benson-islay",
    "BENSON Jennifer": "benson-jennifer",
    "BENSON Kate": "benson-kate",
    "BENSON Laura": "benson-laura",
    "BENSON Nicholas Alexander": "benson-nicholas-alexander",
    "BENSON Riou": "benson-riou",
    "BENSON Rob": "benson-rob",
    "BENSON Robby": "benson-robby",
    "BENSON Robert K": "benson-robert-k",
    "BENSON Sally": "benson-sally",
    "BENSUSSEN Melia": "bensussen-melia",
    "BENT Eliza": "bent-eliza",
    "BENT Norman": "bent-norman",
    "BENT Roxxy": "bent-roxxy",
    "BENT Simon": "bent-simon",
    "BENTHAM Trevor": "bentham-trevor",
    "BENTIN Sebastian Calderon": "bentin-sebastian-calderon",
    "BENTINCK Anna": "bentinck-anna",
    "BENTIS Tani": "bentis-tani",
    "BENTLEY Emma": "bentley-emma",
    "BENTLEY Eric": "bentley-eric",
    "BENTLEY Julia": "bentley-julia",
    "BENTLEY Matthew": "bentley-matthew",
    "BENTLEY Nyra": "bentley-nyra",
    "BENTLEY P E": "bentley-p-e",
    "BENTLEY Toni": "bentley-toni",
    "BENTLEY-FISHER Tom": "bentley-fisher-tom",
    "BENTLEY-QUINN Kari": "bentley-quinn-kari",
    "BENTON Bree": "benton-bree",
    "BENTON Heather": "benton-heather",
    "BENTON James Grant": "benton-james-grant",
    "BENTON Robert": "benton-robert",
    "BENTON Scott": "benton-scott",
    "BENTSIK Riccardo": "bentsik-riccardo",
    "BENYON Gwydin": "benyon-gwydin",
    "BENYON Lissa": "benyon-lissa",
    "BENYON Mike": "benyon-mike",
    "BENZING Jym": "benzing-jym",
    "BEOLCO Angelo": "beolco-angelo",
    "BERARDI Susan": "berardi-susan",
    "BERC Shelley": "berc-shelley",
    "BERCZIK Steve": "berczik-steve",
    "BERDINNER-BLADES Tai": "berdinner-blades-tai",
    "BEREFORD Michael": "bereford-michael",
    "BERENBEIM Glenn": "berenbeim-glenn",
    "BERENSON Deborah": "berenson-deborah",
    "BERESFORD Clare": "beresford-clare",
    "BERESFORD Hugh": "beresford-hugh",
    "BERESFORD Michael": "beresford-michael",
    "BERESFORD Philip": "beresford-philip",
    "BERESFORD Stephen": "beresford-stephen",
    "BERG Aaron": "berg-aaron",
    "BERG Barry": "berg-barry",
    "BERG Deena": "berg-deena",
    "BERG Dick": "berg-dick",
    "BERG Elizabeth": "berg-elizabeth",
    "BERG Jennifer": "berg-jennifer",
    "BERG Lynn": "berg-lynn",
    "BERG Matraca": "berg-matraca",
    "BERG Maureen Kane": "berg-maureen-kane",
    "BERG Neil": "berg-neil",
    "BERG Richard": "berg-richard",
    "BERG Sibylle": "berg-sibylle",
    "BERGEL Arthur": "bergel-arthur",
    "BERGEL Herbert": "bergel-herbert",
    "BERGEN Candice": "bergen-candice",
    "BERGEN D": "bergen-d",
    "BERGER Adam L": "berger-adam-l",
    "BERGER Bob": "berger-bob",
    "BERGER Cara": "berger-cara",
    "BERGER David": "berger-david",
    "BERGER Glen": "berger-glen",
    "BERGER Jacqueline": "berger-jacqueline",
    "BERGER Jesse": "berger-jesse",
    "BERGER John": "berger-john",
    "BERGER Karen": "berger-karen",
    "BERGER Lori": "berger-lori",
    "BERGER Maurice": "berger-maurice",
    "BERGER Robert": "berger-robert",
    "BERGER Ross": "berger-ross",
    "BERGER Sidney": "berger-sidney",
    "BERGER Tom": "berger-tom",
    "BERGER Walter": "berger-walter",
    "BERGER Wes": "berger-wes",
    "BERGERON Alexandra": "bergeron-alexandra",
    "BERGERSON Loris": "bergerson-loris",
    "BERGES Mayeda": "berges-mayeda",
    "BERGGREN Gabriella": "berggren-gabriella",
    "BERGH Andrew": "bergh-andrew",
    "BERGHOF Herbert": "berghof-herbert",
    "BERGIN Dan": "bergin-dan",
    "BERGMAN Alan": "bergman-alan",
    "BERGMAN Andrew": "bergman-andrew",
    "BERGMAN Arlene Sterne": "bergman-arlene-sterne",
    "BERGMAN Hjalmar": "bergman-hjalmar",
    "BERGMAN Ingmar": "bergman-ingmar",
    "BERGMAN J Peter": "bergman-j-peter",
    "BERGMAN Linda": "bergman-linda",
    "BERGMAN Marilyn": "bergman-marilyn",
    "BERGMAN Peter": "bergman-peter",
    "BERGMAN Steven": "bergman-steven",
    "BERGSSON Felix": "bergsson-felix",
    "BERGSTEIN Barbara": "bergstein-barbara",
    "BERGSTEIN Eleanor": "bergstein-eleanor",
    "BERGSTEIN Rachel Shaina": "bergstein-rachel-shaina",
    "BERHO Mauricio": "berho-mauricio",
    "BERIGAN Charles": "berigan-charles",
    "BERIRO Meny": "beriro-meny",
    "BERISH Michael": "berish-michael",
    "BERIUS Livia": "berius-livia",
    "BERK Juliene": "berk-juliene",
    "BERKE Marsha Frank": "berke-marsha-frank",
    "BERKELEY Michael": "berkeley-michael",
    "BERKENMEIER Liza": "berkenmeier-liza",
    "BERKEY Ralph": "berkey-ralph",
    "BERKHOUT Bjorn": "berkhout-bjorn",
    "BERKLEY Reginald": "berkley-reginald",
    "BERKLEY Sam": "berkley-sam",
    "BERKMAN Zak": "berkman-zak",
    "BERKNER Laurie": "berkner-laurie",
    "BERKOFF David": "berkoff-david",
    "BERKOFF Steven": "berkoff-steven",
    "BERKOW Jay": "berkow-jay",
    "BERKOWITZ Angelo": "berkowitz-angelo",
    "BERKOWITZ Dan": "berkowitz-dan",
    "BERKOWITZ I D": "berkowitz-i-d",
    "BERKOWITZ Joel": "berkowitz-joel",
    "BERKOWITZ Leonard D": "berkowitz-leonard-d",
    "BERKOWITZ Roy C": "berkowitz-roy-c",
    "BERKS Alan": "berks-alan",
    "BERKSON Bill": "berkson-bill",
    "BERKSON Brianne": "berkson-brianne",
    "BERKY Bob": "berky-bob",
    "BERLANGER Terry": "berlanger-terry",
    "BERLIN Anne": "berlin-anne",
    "BERLIN Eric": "berlin-eric",
    "BERLIN Herbert L": "berlin-herbert-l",
    "BERLIN Irving": "berlin-irving",
    "BERLIN Isaiah": "berlin-isaiah",
    "BERLIN ": "berlin",
    "BERLIND William": "berlind-william",
    "BERLINER Angela": "berliner-angela",
    "BERLINER Jonny": "berliner-jonny",
    "BERLINER Terry Lyn": "berliner-terry-lyn",
    "BERLOFF Andrea": "berloff-andrea",
    "BERLYAVSKY Vera": "berlyavsky-vera",
    "BERMAIGNE Barry": "bermaigne-barry",
    "BERMAN Boaz": "berman-boaz",
    "BERMAN Brooke": "berman-brooke",
    "BERMAN Carol W": "berman-carol-w",
    "BERMAN Ed": "berman-ed",
    "BERMAN Irene B": "berman-irene-b",
    "BERMAN Jennifer": "berman-jennifer",
    "BERMAN Jeremy Andrew": "berman-jeremy-andrew",
    "BERMAN Ken": "berman-ken",
    "BERMAN Mark": "berman-mark",
    "BERMAN Norman L": "berman-norman-l",
    "BERMAN Ronald L": "berman-ronald-l",
    "BERMAN Sabina": "berman-sabina",
    "BERMAN Simona": "berman-simona",
    "BERMANGE Alexander": "bermange-alexander",
    "BERMANGE Barry": "bermange-barry",
    "BERMEA Bobby": "bermea-bobby",
    "BERMEL Albert": "bermel-albert",
    "BERMEL Derek": "bermel-derek",
    "BERMINGHAM Billy": "bermingham-billy",
    "BERNABEI Alfio": "bernabei-alfio",
    "BERNADINE L C": "bernadine-l-c",
    "BERNAGOZZI Tom": "bernagozzi-tom",
    "BERNARD Cassandra": "bernard-cassandra",
    "BERNARD Emma": "bernard-emma",
    "BERNARD Ian": "bernard-ian",
    "BERNARD Jane": "bernard-jane",
    "BERNARD Jean-Jacques": "bernard-jean-jacques",
    "BERNARD Kenneth": "bernard-kenneth",
    "BERNARD Nadine": "bernard-nadine",
    "BERNARD Sheila Curran": "bernard-sheila-curran",
    "BERNARD Tristan": "bernard-tristan",
    "BERNARDI Bert": "bernardi-bert",
    "BERNARDO Danny": "bernardo-danny",
    "BERNAS Ron": "bernas-ron",
    "BERNASCONI Chrissie": "bernasconi-chrissie",
    "BERNAT Eric": "bernat-eric",
    "BERNAT Roger": "bernat-roger",
    "BERNATCHEZ Madeleine": "bernatchez-madeleine",
    "BERNAYS Tristan": "bernays-tristan",
    "BERNAZKY Kym": "bernazky-kym",
    "BERNBAUM Joel": "bernbaum-joel",
    "BERNES Lane": "bernes-lane",
    "BERNEY Sandra": "berney-sandra",
    "BERNEY William": "berney-william",
    "BERNFIELD Susan": "bernfield-susan",
    "BERNHARD Jim": "bernhard-jim",
    "BERNHARD Sandra": "bernhard-sandra",
    "BERNHARD Thomas": "bernhard-thomas",
    "BERNIER Alexis": "bernier-alexis",
    "BERNIER Bhunnie": "bernier-bhunnie",
    "BERNIER Eric": "bernier-eric",
    "BERNIER Michele": "bernier-michele",
    "BERNING Jerry": "berning-jerry",
    "BERNITT Daniel": "bernitt-daniel",
    "BERNLEF J": "bernlef-j",
    "BERNOFSKY Lauren": "bernofsky-lauren",
    "BERNS Bert": "berns-bert",
    "BERNS Julie": "berns-julie",
    "BERNSTEIN Amy": "bernstein-amy",
    "BERNSTEIN Carol": "bernstein-carol",
    "BERNSTEIN Danny K": "bernstein-danny-k",
    "BERNSTEIN Douglas": "bernstein-douglas",
    "BERNSTEIN Elizabeth": "bernstein-elizabeth",
    "BERNSTEIN Elsa": "bernstein-elsa",
    "BERNSTEIN Fred": "bernstein-fred",
    "BERNSTEIN Herman": "bernstein-herman",
    "BERNSTEIN John": "bernstein-john",
    "BERNSTEIN Jonathan": "bernstein-jonathan",
    "BERNSTEIN Jonathan-1": "bernstein-jonathan-1",
    "BERNSTEIN Julianne": "bernstein-julianne",
    "BERNSTEIN Leon": "bernstein-leon",
    "BERNSTEIN Leonard": "bernstein-leonard",
    "BERNSTEIN Lindsay Ilyse": "bernstein-lindsay-ilyse",
    "BERNSTEIN Michael": "bernstein-michael",
    "BERNSTEIN Richard N": "bernstein-richard-n",
    "BERNSTEIN Robin Margaret": "bernstein-robin-margaret",
    "BERNSTEIN Samuel": "bernstein-samuel",
    "BERNSTEIN Sarah": "bernstein-sarah",
    "BERNSTEIN Toby G": "bernstein-toby-g",
    "BERNTSON Mitch": "berntson-mitch",
    "BERNZWEIG Jay": "bernzweig-jay",
    "BERRIDGE Edward": "berridge-edward",
    "BERRIGAN Daniel": "berrigan-daniel",
    "BERRIS Anthony": "berris-anthony",
    "BERROLL Phillip": "berroll-phillip",
    "BERRY Adrian": "berry-adrian",
    "BERRY Arthur": "berry-arthur",
    "BERRY Cicely": "berry-cicely",
    "BERRY David Adams": "berry-david-adams",
    "BERRY Denny": "berry-denny",
    "BERRY Donna T": "berry-donna-t",
    "BERRY Elizabeth": "berry-elizabeth",
    "BERRY Emma": "berry-emma",
    "BERRY Gillian": "berry-gillian",
    "BERRY Jack J": "berry-jack-j",
    "BERRY Jeff": "berry-jeff",
    "BERRY Jennifer": "berry-jennifer",
    "BERRY Kelly-Marie": "berry-kelly-marie",
    "BERRY Kevin K": "berry-kevin-k",
    "BERRY Loni": "berry-loni",
    "BERRY Martin": "berry-martin",
    "BERRY Nina": "berry-nina",
    "BERRY Randi": "berry-randi",
    "BERRY Richard": "berry-richard",
    "BERRY Roman": "berry-roman",
    "BERRY Ron": "berry-ron",
    "BERRY Stephanie": "berry-stephanie",
    "BERRY Susie": "berry-susie",
    "BERRY Tom": "berry-tom",
    "BERRY Wendell": "berry-wendell",
    "BERRY-HART Tess": "berry-hart-tess",
    "BERRYMAN Jeff": "berryman-jeff",
    "BERRYMAN Ruby": "berryman-ruby",
    "BERSHAD Jon": "bershad-jon",
    "BERSSENBRUGGE Mei-Mei": "berssenbrugge-mei-mei",
    "BERSTEIN Douglas": "berstein-douglas",
    "BERSTLER Samantha": "berstler-samantha",
    "BERT Norman": "bert-norman",
    "BERTIE ": "bertie",
    "BERTO T": "berto-t",
    "BERTOCCI Adam": "bertocci-adam",
    "BERTOLINO David": "bertolino-david",
    "BERTON Rene": "berton-rene",
    "BERTONNEAU Christophe": "bertonneau-christophe",
    "BERTRAM Al": "bertram-al",
    "BERTRAM Anne": "bertram-anne",
    "BERTRAM Halliday": "bertram-halliday",
    "BERTRAM John": "bertram-john",
    "BERTRAN Jordi": "bertran-jordi",
    "BERTRAND Sandra": "bertrand-sandra",
    "BERTUCCIO Marcelo": "bertuccio-marcelo",
    "BERUBE Peter": "berube-peter",
    "BERWALD Beverly": "berwald-beverly",
    "BESBRODE Elisabeth": "besbrode-elisabeth",
    "BESCOBY Jerry": "bescoby-jerry",
    "BESECKER Joe": "besecker-joe",
    "BESHARA Toni J": "beshara-toni-j",
    "BESHARAH Ray": "besharah-ray",
    "BESHT, THE ": "besht",
    "BESIER Rudolf": "besier-rudolf",
    "BESNEHARD Daniel": "besnehard-daniel",
    "BESONG Lydia": "besong-lydia",
    "BESOYAN Rick": "besoyan-rick",
    "BESSER Rachel": "besser-rachel",
    "BESSERGLIK Bernard": "besserglik-bernard",
    "BESSERMAN Ellen": "besserman-ellen",
    "BESSET Jean-Marie": "besset-jean-marie",
    "BESSMAN Maurice": "bessman-maurice",
    "BEST Elizabeth": "best-elizabeth",
    "BEST Emily": "best-emily",
    "BEST Germaine": "best-germaine",
    "BEST Madeline": "best-madeline",
    "BEST Michelle": "best-michelle",
    "BEST Patricia": "best-patricia",
    "BESTERMAN Doug": "besterman-doug",
    "BESTERMAN Paul": "besterman-paul",
    "BESWICK Jordan": "beswick-jordan",
    "BESWICK Michael": "beswick-michael",
    "BESWICK Zanna": "beswick-zanna",
    "BETANCOURT Carmen": "betancourt-carmen",
    "BETANCOURT Joshua": "betancourt-joshua",
    "BETHALL Nicholas": "bethall-nicholas",
    "BETHEL Charlie": "bethel-charlie",
    "BETHELL Andrew": "bethell-andrew",
    "BETHELL Nicholas": "bethell-nicholas",
    "BETHENCOURT Joao": "bethencourt-joao",
    "BETSKO Kathleen": "betsko-kathleen",
    "BETSUYAKU Minoru": "betsuyaku-minoru",
    "BETT John": "bett-john",
    "BETTENBENDER Benjamin": "bettenbender-benjamin",
    "BETTENCOURT Michael": "bettencourt-michael",
    "BETTER Anthony": "better-anthony",
    "BETTI Ugo": "betti-ugo",
    "BETTINSON Rob": "bettinson-rob",
    "BETTIO Gabe": "bettio-gabe",
    "BETTIS Hilary": "bettis-hilary",
    "BETTMANN Robert": "bettmann-robert",
    "BETTO Mario": "betto-mario",
    "BETTRIDGE Ted": "bettridge-ted",
    "BETTS Dennis": "betts-dennis",
    "BETTS Jean": "betts-jean",
    "BETTS Jim": "betts-jim",
    "BETTS Kate": "betts-kate",
    "BETTS Lou": "betts-lou",
    "BETTS Lucy": "betts-lucy",
    "BETTS Torben": "betts-torben",
    "BETTTENCOURT Michael": "betttencourt-michael",
    "BETZ JR Edward L": "betz-jr-edward-l",
    "BETZIEN Angela": "betzien-angela",
    "BEUBIS Michael": "beubis-michael",
    "BEUTHIN Greg": "beuthin-greg",
    "BEVAN Dean": "bevan-dean",
    "BEVAN Donald": "bevan-donald",
    "BEVAN Lily": "bevan-lily",
    "BEVAN Oliver": "bevan-oliver",
    "BEVAN Richard": "bevan-richard",
    "BEVAN Scott": "bevan-scott",
    "BEVAN Sue J": "bevan-sue-j",
    "BEVEL Charles": "bevel-charles",
    "BEVERAGE Bob": "beverage-bob",
    "BEVERAGE Edward": "beverage-edward",
    "BEVERLY Nancy": "beverly-nancy",
    "BEVERLY Ron": "beverly-ron",
    "BEVERLY Tajma": "beverly-tajma",
    "BEVIR Cris": "bevir-cris",
    "BEVITT Sam": "bevitt-sam"
  }
};