export default {
  "metadata": {
    "results": 533,
    "timeStamp": "2025-12-05T21:22:14.159Z",
    "url": "https://www.doollee.com/PlaywrightsB/B_playwrights_bew-bla.php"
  },
  "authors": {
    "BEWES Rodney": "bewes-rodney",
    "BEWLEY Adrian": "bewley-adrian",
    "BEWLEY Sarah": "bewley-sarah",
    "BEWS Samantha": "bews-samantha",
    "BEXON Paul": "bexon-paul",
    "BEY Ruth": "bey-ruth",
    "BEY Salome": "bey-salome",
    "BEY Seraphina": "bey-seraphina",
    "BEYE Charles Rowan": "beye-charles-rowan",
    "BEYE Holly": "beye-holly",
    "BEYER Mike": "beyer-mike",
    "BEYER Simon": "beyer-simon",
    "BEYNON Gwydion": "beynon-gwydion",
    "BEYNON Richard": "beynon-richard",
    "BEZARES Andre": "bezares-andre",
    "BEZERRA Paco": "bezerra-paco",
    "BEZUIDENHOUT Zandra": "bezuidenhout-zandra",
    "B-FLOOR THEATRE COMPANY ": "b-floor-theatre-company",
    "BHALLA Alock": "bhalla-alock",
    "BHARADWAJ Radha": "bharadwaj-radha",
    "BHARATI Dharamvir": "bharati-dharamvir",
    "BHASA ": "bhasa",
    "BHASKER Sanjeev": "bhasker-sanjeev",
    "BHATT Shyam": "bhatt-shyam",
    "BHATT Sujata G": "bhatt-sujata-g",
    "BHATTACHARYYA Sonali": "bhattacharyya-sonali",
    "BHATTI Gurpreet Kaur": "bhatti-gurpreet-kaur",
    "BHAVABHUTI ": "bhavabhuti",
    "BHAWMIK Sudipta": "bhawmik-sudipta",
    "BHIM Michael": "bhim-michael",
    "BHUCHAR Sudha": "bhuchar-sudha",
    "BIADASZKIEWICZ K": "biadaszkiewicz-k",
    "BIAL Henry": "bial-henry",
    "BIALE Gary": "biale-gary",
    "BIANCAMANO Frank": "biancamano-frank",
    "BIANCARELLI Joanne": "biancarelli-joanne",
    "BIANCHI Dan": "bianchi-dan",
    "BIANCHI Heledd": "bianchi-heledd",
    "BIANCHI James": "bianchi-james",
    "BIANCHI Stephanie L": "bianchi-stephanie-l",
    "BIANCHI Victoria": "bianchi-victoria",
    "BIANCOSINO Michole": "biancosino-michole",
    "BIANCOSINO Tony": "biancosino-tony",
    "BIANKE Anna": "bianke-anna",
    "BIBB Randy": "bibb-randy",
    "BIBBY Jonathon": "bibby-jonathon",
    "BIBEAU J-F": "bibeau-j-f",
    "BIBI CREW ": "bibi-crew",
    "BICAT Tony": "bicat-tony",
    "BICECI Marco L": "biceci-marco-l",
    "BICHENKOV Oleg": "bichenkov-oleg",
    "BICKERTON Sarah": "bickerton-sarah",
    "BICKLEY Richard": "bickley-richard",
    "BICKNELL Arthur": "bicknell-arthur",
    "BICKNELL Joel": "bicknell-joel",
    "BICKNELL Marjorie": "bicknell-marjorie",
    "BICKNELL Peter": "bicknell-peter",
    "BICKWITH Reginald": "bickwith-reginald",
    "BIDDLE Jamie": "biddle-jamie",
    "BIDDLE John": "biddle-john",
    "BIDDLE Mare": "biddle-mare",
    "BIDDLE Narelle": "biddle-narelle",
    "BIDDLE Peter": "biddle-peter",
    "BIDDLE William B": "biddle-william-b",
    "BIDERMAN Ilene M": "biderman-ilene-m",
    "BIDINI Dave": "bidini-dave",
    "BIDWELL Tom Dalton": "bidwell-tom-dalton",
    "BIE Branson": "bie-branson",
    "BIEBER Ethel": "bieber-ethel",
    "BIEHLER Ray": "biehler-ray",
    "BIEITO Caliixto": "bieito-caliixto",
    "BIELAN Jack": "bielan-jack",
    "BIELAWSKI Brian": "bielawski-brian",
    "BIELE David": "biele-david",
    "BIELINSKI Maya": "bielinski-maya",
    "BIELLO Michael": "biello-michael",
    "BIELSKI Nella": "bielski-nella",
    "BIEM Bari": "biem-bari",
    "BIENSTOCK Jeff": "bienstock-jeff",
    "BIENVENUE Yvan": "bienvenue-yvan",
    "BIERCE Ambrose": "bierce-ambrose",
    "BIERHAUS Jed": "bierhaus-jed",
    "BIERMAN Arthur K": "bierman-arthur-k",
    "BIERMAN Bernard": "bierman-bernard",
    "BIERMAN James H": "bierman-james-h",
    "BIERN Bari": "biern-bari",
    "BIERWIRTH Judy": "bierwirth-judy",
    "BIES Lauren": "bies-lauren",
    "BIEVER Richard": "biever-richard",
    "BIEZA Larry": "bieza-larry",
    "BIG SCISSORS ": "big-scissors",
    "BIG STATE THEATRE ": "big-state-theatre",
    "BIG WOW ": "big-wow",
    "BIGELOW Gary E": "bigelow-gary-e",
    "BIGELOW Jesse": "bigelow-jesse",
    "BIGELOW Kathryn": "bigelow-kathryn",
    "BIGELOW Otis": "bigelow-otis",
    "BIGELOW Susan": "bigelow-susan",
    "BIGELOW William Coe": "bigelow-william-coe",
    "BIGGAR Joan": "biggar-joan",
    "BIGGERS Jeff": "biggers-jeff",
    "BIGGINS Jonathan": "biggins-jonathan",
    "BIGGS Claudine": "biggs-claudine",
    "BIGGS Robert": "biggs-robert",
    "BIGHAM Abra": "bigham-abra",
    "BIGUENET John": "biguenet-john",
    "BIGUS Harriet": "bigus-harriet",
    "BIHOVSKY Michael Joel": "bihovsky-michael-joel",
    "BIHUM Kit": "bihum-kit",
    "BIKEL Theodore": "bikel-theodore",
    "BIKONT Carolina": "bikont-carolina",
    "BILAS Angeline": "bilas-angeline",
    "BILDER Erica": "bilder-erica",
    "BILGUTAY Antay S": "bilgutay-antay-s",
    "BILIMANKHWE ARTS ": "bilimankhwe-arts",
    "BILL Andrew": "bill-andrew",
    "BILL Stephen": "bill-stephen",
    "BILLAM George": "billam-george",
    "BILLEN Mark": "billen-mark",
    "BILLER Maxim": "biller-maxim",
    "BILLETDOUX Francois": "billetdoux-francois",
    "BILLETER Walter": "billeter-walter",
    "BILLETTE Genevieve": "billette-genevieve",
    "BILLIG Josh": "billig-josh",
    "BILLING Graham": "billing-graham",
    "BILLING Shirley": "billing-shirley",
    "BILLINGHAM Peter": "billingham-peter",
    "BILLINGS Alexandra": "billings-alexandra",
    "BILLINGS Carol": "billings-carol",
    "BILLINGS Curtis": "billings-curtis",
    "BILLINGS Ian": "billings-ian",
    "BILLINGS Shereen": "billings-shereen",
    "BILLINGTON Joanna": "billington-joanna",
    "BILLINGTON Linda": "billington-linda",
    "BILLINGTON Miriam Kouzel": "billington-miriam-kouzel",
    "BILLINGTON Sandra": "billington-sandra",
    "BILLON Nicolas": "billon-nicolas",
    "BILLY THE MIME ": "billy-the-mime",
    "BILNEY Leeroy": "bilney-leeroy",
    "BILODEAU Chantal": "bilodeau-chantal",
    "BILOWIT Ira J": "bilowit-ira-j",
    "BILYAK Dianne": "bilyak-dianne",
    "BILYARD Charles Edward": "bilyard-charles-edward",
    "BIMONTE Richard": "bimonte-richard",
    "BINA Jan": "bina-jan",
    "BINCHY Cian": "binchy-cian",
    "BINCHY Maeve": "binchy-maeve",
    "BINCHY Sarah": "binchy-sarah",
    "BINDA Maurizia": "binda-maurizia",
    "BINDER Anton": "binder-anton",
    "BINET Alfred": "binet-alfred",
    "BING K M": "bing-k-m",
    "BINGE CULTURE COLLECTIVE ": "binge-culture-collective",
    "BINGHAM Charlotte": "bingham-charlotte",
    "BINGHAM George": "bingham-george",
    "BINGHAM Jack": "bingham-jack",
    "BINGHAM Madeleine": "bingham-madeleine",
    "BINGHAM Sallie": "bingham-sallie",
    "BINGHAM Sherhan": "bingham-sherhan",
    "BINHAM Philip": "binham-philip",
    "BINIAS John": "binias-john",
    "BINNIE Jean": "binnie-jean",
    "BINNIE John": "binnie-john",
    "BINNS Mitch": "binns-mitch",
    "BINNS-CALVEY Amy Elizabeth": "binns-calvey-amy-elizabeth",
    "BINOCHE Juliette": "binoche-juliette",
    "BINYON Laurence": "binyon-laurence",
    "BIOH Jocelyn": "bioh-jocelyn",
    "BIONDO Diane": "biondo-diane",
    "BIRAGHI Guglielmo": "biraghi-guglielmo",
    "BIRBIGLIA Mike": "birbiglia-mike",
    "BIRCH Alice": "birch-alice",
    "BIRCH Brad": "birch-brad",
    "BIRCH Carole": "birch-carole",
    "BIRCH Courtney": "birch-courtney",
    "BIRCH Gavin": "birch-gavin",
    "BIRCH Michael": "birch-michael",
    "BIRCH Oliver": "birch-oliver",
    "BIRCH Paul": "birch-paul",
    "BIRCH Zena": "birch-zena",
    "BIRCHALL Bruce": "birchall-bruce",
    "BIRCHALL Katy": "birchall-katy",
    "BIRCHARD Paul": "birchard-paul",
    "BIRCHENOUGH Tom": "birchenough-tom",
    "BIRCHFIELD Raymond": "birchfield-raymond",
    "BIRD Alan": "bird-alan",
    "BIRD Amy": "bird-amy",
    "BIRD Caroline": "bird-caroline",
    "BIRD David": "bird-david",
    "BIRD Frederick": "bird-frederick",
    "BIRD Herman J": "bird-herman-j",
    "BIRD Hunter": "bird-hunter",
    "BIRD Imogene": "bird-imogene",
    "BIRD John": "bird-john",
    "BIRD John C": "bird-john-c",
    "BIRD Jude": "bird-jude",
    "BIRD K": "bird-k",
    "BIRD Lucy": "bird-lucy",
    "BIRD Michael": "bird-michael",
    "BIRD Peter": "bird-peter",
    "BIRD Steve": "bird-steve",
    "BIRD Thomas": "bird-thomas",
    "BIRDMANN, THE ": "birdmann",
    "BIREK Laura": "birek-laura",
    "BIRIBIN, JR Renato": "biribin-jr-renato",
    "BIRIMISA George": "birimisa-george",
    "BIRKBECK Simon": "birkbeck-simon",
    "BIRKEFELD Brian": "birkefeld-brian",
    "BIRKENHEAD Susan": "birkenhead-susan",
    "BIRKENMEIER Liza": "birkenmeier-liza",
    "BIRKFELD Brian": "birkfeld-brian",
    "BIRKIN Andrew": "birkin-andrew",
    "BIRKINSHAW Nathan": "birkinshaw-nathan",
    "BIRKS Christopher": "birks-christopher",
    "BIRKSTED-BREEN Noah": "birksted-breen-noah",
    "BIRMINGHAM Michelle": "birmingham-michelle",
    "BIRNBAUM Mary": "birnbaum-mary",
    "BIRNBAUM Mickey": "birnbaum-mickey",
    "BIRNEY Benjamin": "birney-benjamin",
    "BIRNEY David": "birney-david",
    "BIRNKRANT Samuel": "birnkrant-samuel",
    "BIRO Lajos": "biro-lajos",
    "BIROS Jim": "biros-jim",
    "BIRRELL Suzanne": "birrell-suzanne",
    "BIRTILL Paul": "birtill-paul",
    "BIRTLES Andrew": "birtles-andrew",
    "BIRVE Ulli": "birve-ulli",
    "BISANTZ Jerry": "bisantz-jerry",
    "BISANTZ Kate": "bisantz-kate",
    "BISCH Louis E": "bisch-louis-e",
    "BISCHOFF Sara-Ashley": "bischoff-sara-ashley",
    "BISCOTTI MYSKOWSKI Dana": "biscotti-myskowski-dana",
    "BISCOTTO Charlie": "biscotto-charlie",
    "BISCUIT Rebecca": "biscuit-rebecca",
    "BISEN-HERSCH Seth": "bisen-hersch-seth",
    "BISH Janelle": "bish-janelle",
    "BISHKO Karen": "bishko-karen",
    "BISHOP Andra": "bishop-andra",
    "BISHOP Barton": "bishop-barton",
    "BISHOP Brian L": "bishop-brian-l",
    "BISHOP Conrad": "bishop-conrad",
    "BISHOP Des": "bishop-des",
    "BISHOP Eleanor": "bishop-eleanor",
    "BISHOP Helen Gary": "bishop-helen-gary",
    "BISHOP John": "bishop-john",
    "BISHOP John (1)": "bishop-john-1",
    "BISHOP John (2)": "bishop-john-2",
    "BISHOP Paul": "bishop-paul",
    "BISHOP Robyn": "bishop-robyn",
    "BISHOP Schuyler": "bishop-schuyler",
    "BISHOP Sherry": "bishop-sherry",
    "BISHOP Stuart": "bishop-stuart",
    "BISHOP Tom": "bishop-tom",
    "BISHTON Blake": "bishton-blake",
    "BISKY Tom": "bisky-tom",
    "BISLEY Naomi": "bisley-naomi",
    "BISMILLAH-R-RAHMANI-R-RAHMIN ": "bismillah-r-rahmani-r-rahmin",
    "BISPING Jamie": "bisping-jamie",
    "BISS Andrew": "biss-andrew",
    "BISSELL David Paul": "bissell-david-paul",
    "BISSELL Marian": "bissell-marian",
    "BISSELL Richard": "bissell-richard",
    "BISSET-SMITH Gabriel": "bisset-smith-gabriel",
    "BISSETT Alan": "bissett-alan",
    "BISSETT Cora": "bissett-cora",
    "BISSETT-SMITH Gabriel": "bissett-smith-gabriel",
    "BISSON Pat": "bisson-pat",
    "BISTRANSIN Cat": "bistransin-cat",
    "BISTRANSIN George": "bistransin-george",
    "BISWAS Anjan": "biswas-anjan",
    "BISWAS Ansuman": "biswas-ansuman",
    "BISWAS Neil": "biswas-neil",
    "BITETTI Bronwen": "bitetti-bronwen",
    "BITTERMAN Michael": "bitterman-michael",
    "BITTERMAN Shem": "bitterman-shem",
    "BITTLE Jerry": "bittle-jerry",
    "BITTON Eyal": "bitton-eyal",
    "BITTRICH Stephen": "bittrich-stephen",
    "BITZELBERGER Rick": "bitzelberger-rick",
    "BIURO PODROZY ": "biuro-podrozy",
    "BIVINS William": "bivins-william",
    "BIZARRE NOIR ": "bizarre-noir",
    "BIZIOREK Andrei": "biziorek-andrei",
    "BJORFORS Tilde": "bjorfors-tilde",
    "BJORKMAN B J": "bjorkman-b-j",
    "BJORKMAN Edwin": "bjorkman-edwin",
    "BJORNEBOE Jens": "bjorneboe-jens",
    "BJORNOV Ingrid": "bjornov-ingrid",
    "BJORNSON Bjornstjerne": "bjornson-bjornstjerne",
    "BLACK Allison": "black-allison",
    "BLACK Andrew": "black-andrew",
    "BLACK Angela": "black-angela",
    "BLACK Anthony": "black-anthony",
    "BLACK Arnold": "black-arnold",
    "BLACK Bill": "black-bill",
    "BLACK Bob": "black-bob",
    "BLACK Brent": "black-brent",
    "BLACK C Stewart": "black-c-stewart",
    "BLACK Campbell": "black-campbell",
    "BLACK David": "black-david",
    "BLACK Don": "black-don",
    "BLACK Dustin Lance": "black-dustin-lance",
    "BLACK F Scott": "black-f-scott",
    "BLACK Ian": "black-ian",
    "BLACK Ian Stuart": "black-ian-stuart",
    "BLACK Jean Ferguson": "black-jean-ferguson",
    "BLACK Jim": "black-jim",
    "BLACK Kitty": "black-kitty",
    "BLACK Laura": "black-laura",
    "BLACK Lewis": "black-lewis",
    "BLACK Michael": "black-michael",
    "BLACK Michael Ian": "black-michael-ian",
    "BLACK Mike": "black-mike",
    "BLACK Monstah": "black-monstah",
    "BLACK Muriel": "black-muriel",
    "BLACK Nancy": "black-nancy",
    "BLACK Neal": "black-neal",
    "BLACK Noel A": "black-noel-a",
    "BLACK Penny": "black-penny",
    "BLACK Robert": "black-robert",
    "BLACK Simon": "black-simon",
    "BLACK Stephanie": "black-stephanie",
    "BLACK Stephen": "black-stephen",
    "BLACK Steve": "black-steve",
    "BLACK Tom": "black-tom",
    "BLACK William Bascom": "black-william-bascom",
    "BLACK William Electric": "black-william-electric",
    "BLACK ARTS TROUPE ": "black-arts-troupe",
    "BLACK HOLE PRODUCTIONS ": "black-hole-productions",
    "BLACK LIGHT ": "black-light",
    "BLACK MIME THEATRE ": "black-mime-theatre",
    "BLACK MOON THEATRE COMPANY ": "black-moon-theatre-company",
    "BLACK THEATRE CO-OP ": "black-theatre-co-op",
    "BLACKADDER Neil": "blackadder-neil",
    "BLACKADDER Rosemary": "blackadder-rosemary",
    "BLACKALL Melissa": "blackall-melissa",
    "BLACKARD William": "blackard-william",
    "BLACKBURN Barbara": "blackburn-barbara",
    "BLACKBURN Bryan": "blackburn-bryan",
    "BLACKBURN Clifford": "blackburn-clifford",
    "BLACKBURN Jennifer": "blackburn-jennifer",
    "BLACKBURN Martin": "blackburn-martin",
    "BLACKBURN Nigel": "blackburn-nigel",
    "BLACKBURN Stephen": "blackburn-stephen",
    "BLACKBURN Stuart": "blackburn-stuart",
    "BLACKE-BRAGG Norma": "blacke-bragg-norma",
    "BLACKEDGE Aaron": "blackedge-aaron",
    "BLACKER Terence": "blacker-terence",
    "BLACKER Uilleam": "blacker-uilleam",
    "BLACKFORD Richard": "blackford-richard",
    "BLACK-HAWKINS Hugh": "black-hawkins-hugh",
    "BLACK-HAWKINS Piers": "black-hawkins-piers",
    "BLACKLEY Magdalena": "blackley-magdalena",
    "BLACKLEY Stuart": "blackley-stuart",
    "BLACKMAN Andrew": "blackman-andrew",
    "BLACKMAN David": "blackman-david",
    "BLACKMAN Edgar": "blackman-edgar",
    "BLACKMAN Honor": "blackman-honor",
    "BLACKMAN Malorie": "blackman-malorie",
    "BLACKMAN Rachel": "blackman-rachel",
    "BLACKMAN Tim": "blackman-tim",
    "BLACKMER Jennifer": "blackmer-jennifer",
    "BLACKMON D Terry": "blackmon-d-terry",
    "BLACKMON Melissa": "blackmon-melissa",
    "BLACKMORE Ernie": "blackmore-ernie",
    "BLACKMORE Julian": "blackmore-julian",
    "BLACKMORE Peter": "blackmore-peter",
    "BLACKMORE Tom": "blackmore-tom",
    "BLACKOUT THEATRE ": "blackout-theatre",
    "BLACKSKYWHITE ": "blackskywhite",
    "BLACKSTOCK Louise": "blackstock-louise",
    "BLACKWATER Jason": "blackwater-jason",
    "BLACKWELL Ali": "blackwell-ali",
    "BLACKWELL Charles": "blackwell-charles",
    "BLACKWELL Don": "blackwell-don",
    "BLACKWELL Erin": "blackwell-erin",
    "BLACKWELL James": "blackwell-james",
    "BLACKWELL Lavell V": "blackwell-lavell-v",
    "BLACKWELL Nicky": "blackwell-nicky",
    "BLACKWELL Phillip": "blackwell-phillip",
    "BLACKWELL Robert": "blackwell-robert",
    "BLACKWELL Tim": "blackwell-tim",
    "BLACKWELL Vera": "blackwell-vera",
    "BLACKWELL Zeke": "blackwell-zeke",
    "BLACKWELL-PAL Jaswinder": "blackwell-pal-jaswinder",
    "BLACKWOOD Chris": "blackwood-chris",
    "BLACKWOOD Gary L": "blackwood-gary-l",
    "BLACKWOOD Robert": "blackwood-robert",
    "BLACKWOOD Russ": "blackwood-russ",
    "BLACKWOOD Susan": "blackwood-susan",
    "BLADE Kenny": "blade-kenny",
    "BLADEL Richard": "bladel-richard",
    "BLADES Robin": "blades-robin",
    "BLAEMIRE Nick": "blaemire-nick",
    "BLAGDANIC Alma": "blagdanic-alma",
    "BLAGRAVE Mark": "blagrave-mark",
    "BLAIN R": "blain-r",
    "BLAIN Samantha": "blain-samantha",
    "BLAIN-ALLEN Oscar-Jackson": "blain-allen-oscar-jackson",
    "BLAINE Benjamin": "blaine-benjamin",
    "BLAINE Lawrence": "blaine-lawrence",
    "BLAINE Martin": "blaine-martin",
    "BLAINE Mickey": "blaine-mickey",
    "BLAINE Nicole": "blaine-nicole",
    "BLAINEY Anna": "blainey-anna",
    "BLAIR Alan": "blair-alan",
    "BLAIR Alanna": "blair-alanna",
    "BLAIR Clifton": "blair-clifton",
    "BLAIR Dale": "blair-dale",
    "BLAIR Gregory": "blair-gregory",
    "BLAIR Iain": "blair-iain",
    "BLAIR Jayson": "blair-jayson",
    "BLAIR Jon": "blair-jon",
    "BLAIR Kellen": "blair-kellen",
    "BLAIR Kitty Hunter": "blair-kitty-hunter",
    "BLAIR Les": "blair-les",
    "BLAIR Lionel": "blair-lionel",
    "BLAIR Randy": "blair-randy",
    "BLAIR Rhonda": "blair-rhonda",
    "BLAIR Ron": "blair-ron",
    "BLAIR Samuel": "blair-samuel",
    "BLAIR Wayne": "blair-wayne",
    "BLAIRE Natily": "blaire-natily",
    "BLAIS Dottie": "blais-dottie",
    "BLAIS Marie-Claire": "blais-marie-claire",
    "BLAISDELL Lydia": "blaisdell-lydia",
    "BLAKE Ben": "blake-ben",
    "BLAKE Cliff": "blake-cliff",
    "BLAKE Dave": "blake-dave",
    "BLAKE David": "blake-david",
    "BLAKE Diana": "blake-diana",
    "BLAKE Elizabeth": "blake-elizabeth",
    "BLAKE Eubie": "blake-eubie",
    "BLAKE Harry": "blake-harry",
    "BLAKE Howard": "blake-howard",
    "BLAKE Jan": "blake-jan",
    "BLAKE Jeff": "blake-jeff",
    "BLAKE Joan": "blake-joan",
    "BLAKE Jon": "blake-jon",
    "BLAKE Joseph P": "blake-joseph-p",
    "BLAKE Judson": "blake-judson",
    "BLAKE Leila": "blake-leila",
    "BLAKE Leslie (Hoban)": "blake-leslie-(hoban)",
    "BLAKE Lisabeth": "blake-lisabeth",
    "BLAKE Patrick": "blake-patrick",
    "BLAKE Paul": "blake-paul",
    "BLAKE Phil": "blake-phil",
    "BLAKE Phoebe": "blake-phoebe",
    "BLAKE Sarah-Jane": "blake-sarah-jane",
    "BLAKE Simon": "blake-simon",
    "BLAKE Thomas": "blake-thomas",
    "BLAKE Yemisi": "blake-yemisi",
    "BLAKE Yve": "blake-yve",
    "BLAKEBOROUGH Stephanie": "blakeborough-stephanie",
    "BLAKELEY Nora Brooks": "blakeley-nora-brooks",
    "BLAKELEY Steven": "blakeley-steven",
    "BLAKELY David": "blakely-david",
    "BLAKEMAN Dustin Robert": "blakeman-dustin-robert",
    "BLAKEMAN Grace": "blakeman-grace",
    "BLAKEMAN Helen": "blakeman-helen",
    "BLAKEMORE Kenneth": "blakemore-kenneth",
    "BLAKENEY Gavin": "blakeney-gavin",
    "BLAKESLEY Keith": "blakesley-keith",
    "BLAKESLEY Raymond": "blakesley-raymond",
    "BLAKESLEY Sue": "blakesley-sue",
    "BLAKESON Ken": "blakeson-ken",
    "BLAKEY Brian": "blakey-brian",
    "BLAKEY John": "blakey-john",
    "BLAKISTON Caroline": "blakiston-caroline",
    "BLALACK Russell": "blalack-russell",
    "BLAMIRE Larry": "blamire-larry",
    "BLANCHARD David": "blanchard-david",
    "BLANCHARD Gerald L": "blanchard-gerald-l",
    "BLANCHARD Johanna": "blanchard-johanna",
    "BLANCHARD Joshua": "blanchard-joshua",
    "BLANCHARD Kellen Conway": "blanchard-kellen-conway",
    "BLANCHARD Ryan": "blanchard-ryan",
    "BLANCHETT Frederick": "blanchett-frederick",
    "BLANCHETTE Frederick": "blanchette-frederick",
    "BLANCK Kim": "blanck-kim",
    "BLANCO Fred": "blanco-fred",
    "BLANCO Richard": "blanco-richard",
    "BLANCO Sierra": "blanco-sierra",
    "BLAND Carl": "bland-carl",
    "BLAND Eric": "bland-eric",
    "BLAND Frederick": "bland-frederick",
    "BLAND Jay": "bland-jay",
    "BLAND Joellen": "bland-joellen",
    "BLAND Peter": "bland-peter",
    "BLAND Rick": "bland-rick",
    "BLANDE Christopher": "blande-christopher",
    "BLANDFORD Gladys": "blandford-gladys",
    "BLANDFORD Steve": "blandford-steve",
    "BLANE Ralph": "blane-ralph",
    "BLANEY Darren Patrick": "blaney-darren-patrick",
    "BLANK Bill": "blank-bill",
    "BLANK Carla": "blank-carla",
    "BLANK G Kim": "blank-g-kim",
    "BLANK Jessica": "blank-jessica",
    "BLANK Martin": "blank-martin",
    "BLANK Radha": "blank-radha",
    "BLANK Roger": "blank-roger",
    "BLANK SLATE THEATRE ": "blank-slate-theatre",
    "BLANKENHORN Raymond": "blankenhorn-raymond",
    "BLANKER Beppie": "blanker-beppie",
    "BLANKFORT Dorothy": "blankfort-dorothy",
    "BLANKFORT Michael": "blankfort-michael",
    "BLANKMAN Howard": "blankman-howard",
    "BLANTON Gail": "blanton-gail",
    "BLASIAR Jean": "blasiar-jean",
    "BLASIUS Chuck": "blasius-chuck",
    "BLASK Dan": "blask-dan",
    "BLAST THEORY ": "blast-theory",
    "BLATCHLEY Joseph": "blatchley-joseph",
    "BLATNER Barbara": "blatner-barbara",
    "BLATT Beth": "blatt-beth",
    "BLATT Jerry": "blatt-jerry",
    "BLATTER Alfred": "blatter-alfred",
    "BLATTY William Peter": "blatty-william-peter",
    "BLAU Daniel J": "blau-daniel-j",
    "BLAU Eric": "blau-eric",
    "BLAU Lily": "blau-lily",
    "BLAU Molly C": "blau-molly-c",
    "BLAXILL Mike": "blaxill-mike",
    "BLAXLAND Doude": "blaxland-doude",
    "BLAXLAND Dougie": "blaxland-dougie",
    "BLAXLAND Wendy": "blaxland-wendy",
    "BLAY John": "blay-john",
    "BLAYDE Ariadne": "blayde-ariadne",
    "BLAYLOCK Brett": "blaylock-brett",
    "BLAZES Johnny": "blazes-johnny",
    "BLAZEVIC George": "blazevic-george",
    "BLAZQUES Eladia": "blazques-eladia"
  }
};