export default {
  "metadata": {
    "results": 531,
    "timeStamp": "2025-12-05T21:22:17.710Z",
    "url": "https://www.doollee.com/PlaywrightsB/B_playwrights_blb-bor.php"
  },
  "authors": {
    "BLEASDALE Alan": "bleasdale-alan",
    "BLEAU Kevin": "bleau-kevin",
    "BLECHER Hilary": "blecher-hilary",
    "BLECHER Lone Thygesen": "blecher-lone-thygesen",
    "BLECKLEY Piers": "bleckley-piers",
    "BLEECHER Hilary": "bleecher-hilary",
    "BLEEMER Nancy": "bleemer-nancy",
    "BLEIER Barbara": "bleier-barbara",
    "BLENHEIM Chester": "blenheim-chester",
    "BLESSED Rosalind": "blessed-rosalind",
    "BLESSING Lee": "blessing-lee",
    "BLESSINGTON Francis": "blessington-francis",
    "BLEVINS Michael": "blevins-michael",
    "BLICKER Seymour": "blicker-seymour",
    "BLICKLEY Mark": "blickley-mark",
    "BLICQ Ron": "blicq-ron",
    "BLIDEN Aaron": "bliden-aaron",
    "BLIEDEN Michael": "blieden-michael",
    "BLIGHT D N": "blight-d-n",
    "BLINCO Anthony": "blinco-anthony",
    "BLINCOE Nicholas": "blincoe-nicholas",
    "BLIND SUMMIT ": "blind-summit",
    "BLINN Denise": "blinn-denise",
    "BLISS Arthur": "bliss-arthur",
    "BLISS Blue": "bliss-blue",
    "BLISS Emily": "bliss-emily",
    "BLISS Georgia": "bliss-georgia",
    "BLISSET Chris": "blisset-chris",
    "BLITSTEIN Jonathan Ballard": "blitstein-jonathan-ballard",
    "BLITZSTEIN Marc": "blitzstein-marc",
    "BLITZSTEIN Marcus J": "blitzstein-marcus-j",
    "BLIXT David": "blixt-david",
    "BLIZARD Helen": "blizard-helen",
    "BLIZZARD Eve": "blizzard-eve",
    "BLOCH Andy Rooster": "bloch-andy-rooster",
    "BLOCH Benjamin": "bloch-benjamin",
    "BLOCH Bertram": "bloch-bertram",
    "BLOCH Pedro": "bloch-pedro",
    "BLOCK Anita Rowe": "block-anita-rowe",
    "BLOCK Cathy": "block-cathy",
    "BLOCK Randi Michaels": "block-randi-michaels",
    "BLOCK Simon": "block-simon",
    "BLOCK Tom": "block-tom",
    "BLOCK Toni": "block-toni",
    "BLOCKER Frank": "blocker-frank",
    "BLOCKER Liz": "blocker-liz",
    "BLODGETT Joe": "blodgett-joe",
    "BLOEDEL Peter": "bloedel-peter",
    "BLOEM Peter": "bloem-peter",
    "BLOK Alexander": "blok-alexander",
    "BLOKDIJK Tom": "blokdijk-tom",
    "BLOM Tamar": "blom-tamar",
    "BLOMAIN Karen": "blomain-karen",
    "BLOMFIELD Richard": "blomfield-richard",
    "BLOMFIELD Thor": "blomfield-thor",
    "BLOMQUIST David": "blomquist-david",
    "BLOMQVIST Johannes": "blomqvist-johannes",
    "BLOOD Lucy": "blood-lucy",
    "BLOOD Nick": "blood-nick",
    "BLOOD GROUP ": "blood-group",
    "BLOODLIPS ": "bloodlips",
    "BLOODWORTH-THOMASON Linda": "bloodworth-thomason-linda",
    "BLOOM Charles": "bloom-charles",
    "BLOOM David": "bloom-david",
    "BLOOM Harry": "bloom-harry",
    "BLOOM Jeremy": "bloom-jeremy",
    "BLOOM Joel": "bloom-joel",
    "BLOOM Ken": "bloom-ken",
    "BLOOM Lauren": "bloom-lauren",
    "BLOOM Michael": "bloom-michael",
    "BLOOM Murray Teigh": "bloom-murray-teigh",
    "BLOOM Nicki": "bloom-nicki",
    "BLOOM Samantha": "bloom-samantha",
    "BLOOM Ursula": "bloom-ursula",
    "BLOOMBERG Natasha": "bloomberg-natasha",
    "BLOOMER Steven": "bloomer-steven",
    "BLOOMER Susan": "bloomer-susan",
    "BLOOMFIELD Clara": "bloomfield-clara",
    "BLOOMFIELD Doron": "bloomfield-doron",
    "BLOOMFIELD Ian": "bloomfield-ian",
    "BLOOMFIELD Jennifer": "bloomfield-jennifer",
    "BLOOMFIELD Linda": "bloomfield-linda",
    "BLOOMFIELD Maggie": "bloomfield-maggie",
    "BLOOMFIELD Robert": "bloomfield-robert",
    "BLOOMSBURG THEATRE ENSEMBLE ": "bloomsburg-theatre-ensemble",
    "BLOOMSTEIN Henry": "bloomstein-henry",
    "BLOOR Thomas": "bloor-thomas",
    "BLOSSOM Joe": "blossom-joe",
    "BLOSSOM Larry E": "blossom-larry-e",
    "BLOUNT Robert (Bob)": "blount-robert",
    "BLOUNT Steve": "blount-steve",
    "BLOUNT JR Roy": "blount-roy",
    "BLOW Ben": "blow-ben",
    "BLOW Simon": "blow-simon",
    "BLOW Thomas": "blow-thomas",
    "BLOWFIELD Mick": "blowfield-mick",
    "BLUE Adrian": "blue-adrian",
    "BLUE Bryan Davidson": "blue-bryan-davidson",
    "BLUE Dan": "blue-dan",
    "BLUE David": "blue-david",
    "BLUE Elaine": "blue-elaine",
    "BLUE Elizabeth": "blue-elizabeth",
    "BLUE Erica": "blue-erica",
    "BLUE Jade": "blue-jade",
    "BLUE CLOUD Peter": "blue-cloud-peter",
    "BLUE DOG PRODUCTIONS ": "blue-dog-productions",
    "BLUE MOUNTAIN THEATRE ": "blue-mountain-theatre",
    "BLUE OWL HOOSER Philip": "blue-owl-hooser-philip",
    "BLUE PENGUIN ": "blue-penguin",
    "BLUEMOUTH INC ": "bluemouth-inc",
    "BLUESTEIN E Frank": "bluestein-e-frank",
    "BLUESTEIN Steve": "bluestein-steve",
    "BLUM Renon": "blum-renon",
    "BLUMBERG Michael": "blumberg-michael",
    "BLUME Kathryn": "blume-kathryn",
    "BLUMENFELD Ally": "blumenfeld-ally",
    "BLUMENFELD Esther": "blumenfeld-esther",
    "BLUMENFELD Leonore": "blumenfeld-leonore",
    "BLUMENKRANTZ Jeff": "blumenkrantz-jeff",
    "BLUMENTHAL Francesca": "blumenthal-francesca",
    "BLUMENTHAL Scott": "blumenthal-scott",
    "BLUMENTHAL-EHRLICH Barbara": "blumenthal-ehrlich-barbara",
    "BLUMER J A C": "blumer-j-a-c",
    "BLUMER Lorne": "blumer-lorne",
    "BLUMHAGEN Andrew": "blumhagen-andrew",
    "BLUMSTEIN Glenn": "blumstein-glenn",
    "BLUNDELL Emma": "blundell-emma",
    "BLUNDELL Sue": "blundell-sue",
    "BLUNT Manda Leigh": "blunt-manda-leigh",
    "BLUNT Rick": "blunt-rick",
    "BLUSH Sarah": "blush-sarah",
    "BLUTH Toby": "bluth-toby",
    "BLUTHAL Lisa": "bluthal-lisa",
    "BLUTO Tony": "bluto-tony",
    "BLY Robert": "bly-robert",
    "BLYTHE Alecky": "blythe-alecky",
    "BLYTHE Jemma": "blythe-jemma",
    "BLYTHE Jim": "blythe-jim",
    "BLYTHE M": "blythe-m",
    "BLYTHE Peter": "blythe-peter",
    "BLYTHE Richard": "blythe-richard",
    "BLYTON Enid": "blyton-enid",
    "BOADELLA Albert": "boadella-albert",
    "BOAGEY Eric": "boagey-eric",
    "BOAK Carissa": "boak-carissa",
    "BOAKYE Paul": "boakye-paul",
    "BOAL Augusto": "boal-augusto",
    "BOAL Chris": "boal-chris",
    "BOAR Rory": "boar-rory",
    "BOARD Matt": "board-matt",
    "BOARDMAN Nick": "boardman-nick",
    "BOARDMAN Stan": "boardman-stan",
    "BOARDMAN William": "boardman-william",
    "BOARDMAN-JACOBS Sam": "boardman-jacobs-sam",
    "BOATNER Edward": "boatner-edward",
    "BOBAK Sasha": "bobak-sasha",
    "BOBB Columpa": "bobb-columpa",
    "BOBBER Cupola": "bobber-cupola",
    "BOBBIE Walter": "bobbie-walter",
    "BOBBITT Betty": "bobbitt-betty",
    "BOBBITT Michael J": "bobbitt-michael-j",
    "BOBBITT Shantel": "bobbitt-shantel",
    "BOBIS Merlinda": "bobis-merlinda",
    "BOBKOFF Ned": "bobkoff-ned",
    "BOBRICK Jeanne": "bobrick-jeanne",
    "BOBRICK Sam": "bobrick-sam",
    "BOBROW Morris": "bobrow-morris",
    "BOB-WAKSBERG Raphael": "bob-waksberg-raphael",
    "BOCANEGRA Suzanne": "bocanegra-suzanne",
    "BOCAZ-LARSON D M": "bocaz-larson-d-m",
    "BOCCADILLO ": "boccadillo",
    "BOCCHIERI Emanuel": "bocchieri-emanuel",
    "BOCHERT Henning": "bochert-henning",
    "BOCK Adam": "bock-adam",
    "BOCK Andrew": "bock-andrew",
    "BOCK Carolyn": "bock-carolyn",
    "BOCK Jerry": "bock-jerry",
    "BOCKLEY Seth": "bockley-seth",
    "BODDEN Kurt": "bodden-kurt",
    "BODDEN Michael": "bodden-michael",
    "BODDY Alexis": "boddy-alexis",
    "BODDY Michael": "boddy-michael",
    "BODENSTEIN Michael": "bodenstein-michael",
    "BODI Sari": "bodi-sari",
    "BODIE Heather": "bodie-heather",
    "BODIE Jane": "bodie-jane",
    "BODIES IN FLIGHT ": "bodies-in-flight",
    "BODINE Greg Oliver": "bodine-greg-oliver",
    "BODLE Justin": "bodle-justin",
    "BODOR Rob": "bodor-rob",
    "BODOW Warren G": "bodow-warren-g",
    "BODYAN Jesse Glenn": "bodyan-jesse-glenn",
    "BOE Steven": "boe-steven",
    "BOE Whitney": "boe-whitney",
    "BOECK Bruce": "boeck-bruce",
    "BOECKER Ben": "boecker-ben",
    "BOEHLER Robert William": "boehler-robert-william",
    "BOEHM Carrie": "boehm-carrie",
    "BOEHM Philip": "boehm-philip",
    "BOEHNERT Kristo": "boehnert-kristo",
    "BOEKELHEIDE Amanda": "boekelheide-amanda",
    "BOERGERS Mark": "boergers-mark",
    "BOERLAGE Frans": "boerlage-frans",
    "BOERO Terry Amara": "boero-terry-amara",
    "BOES Bobbi": "boes-bobbi",
    "BOESEN Becky": "boesen-becky",
    "BOESEN Brad": "boesen-brad",
    "BOESING Martha": "boesing-martha",
    "BOESKY Bill": "boesky-bill",
    "BOETHIUS Gunilla": "boethius-gunilla",
    "BOETTCHER Kirk": "boettcher-kirk",
    "BOETTCHER-TATE Karen": "boettcher-tate-karen",
    "BOFILL Maggie": "bofill-maggie",
    "BOFILL Sylvia": "bofill-sylvia",
    "BOGAEV Oleg": "bogaev-oleg",
    "BOGARD Jerrod": "bogard-jerrod",
    "BOGART Anne": "bogart-anne",
    "BOGART Joanne": "bogart-joanne",
    "BOGART Steven": "bogart-steven",
    "BOGAS Paul": "bogas-paul",
    "BOGAVAC Jelena": "bogavac-jelena",
    "BOGAVAC Milena": "bogavac-milena",
    "BOGDANOV Malachi": "bogdanov-malachi",
    "BOGDANOV Michael": "bogdanov-michael",
    "BOGDANOWITSCH Jay J": "bogdanowitsch-jay-j",
    "BOGEN Nancy": "bogen-nancy",
    "BOGOSIAN Eric": "bogosian-eric",
    "BOGOSIAN Nicholas": "bogosian-nicholas",
    "BOGUE Lucile": "bogue-lucile",
    "BOGUSH Jennifer": "bogush-jennifer",
    "BOHAC Petr": "bohac-petr",
    "BOHANAN Mary": "bohanan-mary",
    "BOHANNON Emily": "bohannon-emily",
    "BOHANNON Sharai": "bohannon-sharai",
    "BOHL Jordan": "bohl-jordan",
    "BOHLKE Gary": "bohlke-gary",
    "BOHMER Mickey": "bohmer-mickey",
    "BOHMLER Craig": "bohmler-craig",
    "BOHN Tim": "bohn-tim",
    "BOHON Jason": "bohon-jason",
    "BOI DE MAMAO ": "boi-de-mamao",
    "BOIES Brian": "boies-brian",
    "BOIKO Claire": "boiko-claire",
    "BOILERHOUSE ": "boilerhouse",
    "BOILEROOM ": "boileroom",
    "BOISJOUX Susie": "boisjoux-susie",
    "BOISVERT Nathalie": "boisvert-nathalie",
    "BOIT Bundy": "boit-bundy",
    "BOJANOWSKI Darryl": "bojanowski-darryl",
    "BOJOVIC Igor": "bojovic-igor",
    "BOKHOUR Raymond": "bokhour-raymond",
    "BOKOR Maria": "bokor-maria",
    "BOKOR Pierre": "bokor-pierre",
    "BOKOWIEC Julie Amanda": "bokowiec-julie-amanda",
    "BOKSER Sherry": "bokser-sherry",
    "BOL Lorna": "bol-lorna",
    "BOLAJI Adebayo": "bolaji-adebayo",
    "BOLAM Ken": "bolam-ken",
    "BOLAN Blake E": "bolan-blake-e",
    "BOLAN Chloe": "bolan-chloe",
    "BOLAN Marc": "bolan-marc",
    "BOLAN Mary": "bolan-mary",
    "BOLAND Bill": "boland-bill",
    "BOLAND Bridget": "boland-bridget",
    "BOLAND Gene": "boland-gene",
    "BOLAND JR Clay": "boland-jr-clay",
    "BOLANO Roberto": "bolano-roberto",
    "BOLCH Suzanne": "bolch-suzanne",
    "BOLCHUNOS Brad": "bolchunos-brad",
    "BOLCIK Chip": "bolcik-chip",
    "BOLD Jose": "bold-jose",
    "BOLDEN Julia": "bolden-julia",
    "BOLEK POLIVKA CO ": "bolek-polivka-co",
    "BOLEN Dennis E": "bolen-dennis-e",
    "BOLEN John": "bolen-john",
    "BOLEN Lynne": "bolen-lynne",
    "BOLEN-GORDON Lydia": "bolen-gordon-lydia",
    "BOLES Brett": "boles-brett",
    "BOLES Jeffrey": "boles-jeffrey",
    "BOLES Robert": "boles-robert",
    "BOLGER David": "bolger-david",
    "BOLGER Dermot": "bolger-dermot",
    "BOLIA Steven": "bolia-steven",
    "BOLIN Eli": "bolin-eli",
    "BOLKHE Gary": "bolkhe-gary",
    "BOLL Heinrich": "boll-heinrich",
    "BOLLANS G E": "bollans-g-e",
    "BOLLAS Tony": "bollas-tony",
    "BOLLERUP Margaret": "bollerup-margaret",
    "BOLLINGER Henrietta": "bollinger-henrietta",
    "BOLLOW Ludmilla": "bollow-ludmilla",
    "BOLMER Mickey": "bolmer-mickey",
    "BOLOGNA Joseph": "bologna-joseph",
    "BOLOS Blanca": "bolos-blanca",
    "BOLOS Dee": "bolos-dee",
    "BOLSKY Debbie": "bolsky-debbie",
    "BOLSTAD Mette": "bolstad-mette",
    "BOLSTER Elena": "bolster-elena",
    "BOLT Carol": "bolt-carol",
    "BOLT Jonathan": "bolt-jonathan",
    "BOLT R R": "bolt-r-r",
    "BOLT Ranjit": "bolt-ranjit",
    "BOLT Robert": "bolt-robert",
    "BOLTE JR Carl E": "bolte-jr-carl-e",
    "BOLTON Chris": "bolton-chris",
    "BOLTON Darren": "bolton-darren",
    "BOLTON Guy": "bolton-guy",
    "BOLTON John": "bolton-john",
    "BOLTON Lawrence": "bolton-lawrence",
    "BOLTON Martha": "bolton-martha",
    "BOLTON Tonya Joy": "bolton-tonya-joy",
    "BOLUS Julia": "bolus-julia",
    "BOLUS Michael": "bolus-michael",
    "BOLWELL Jan": "bolwell-jan",
    "BOLYS Gavin": "bolys-gavin",
    "BOLZE Mathurin": "bolze-mathurin",
    "BOMAR Robert": "bomar-robert",
    "BOMBA Paul": "bomba-paul",
    "BOMBERG Cecily": "bomberg-cecily",
    "BOMMER Lawrence": "bommer-lawrence",
    "BONACCI Anna": "bonacci-anna",
    "BONAFEDE Bruce": "bonafede-bruce",
    "BONAIR Kat": "bonair-kat",
    "BONAIR-AGARD Roger": "bonair-agard-roger",
    "BONAL Denise": "bonal-denise",
    "BONAPACE Ruth": "bonapace-ruth",
    "BONARETTI Sue": "bonaretti-sue",
    "BONASORTE Gary": "bonasorte-gary",
    "BONATI Gina": "bonati-gina",
    "BONATO Joan": "bonato-joan",
    "BONAVITACOLA Patrick J": "bonavitacola-patrick-j",
    "BOND Alex": "bond-alex",
    "BOND Alma Halbert": "bond-alma-halbert",
    "BOND Chris": "bond-chris",
    "BOND Christopher": "bond-christopher",
    "BOND Derek": "bond-derek",
    "BOND Donna": "bond-donna",
    "BOND Edward": "bond-edward",
    "BOND Elizabeth": "bond-elizabeth",
    "BOND Frederick W": "bond-frederick-w",
    "BOND Geoffrey": "bond-geoffrey",
    "BOND Grahame": "bond-grahame",
    "BOND Hester": "bond-hester",
    "BOND Horace J": "bond-horace-j",
    "BOND Jez": "bond-jez",
    "BOND John": "bond-john",
    "BOND Jon Edgley": "bond-jon-edgley",
    "BOND Justin": "bond-justin",
    "BOND Kate": "bond-kate",
    "BOND Kathryn S": "bond-kathryn-s",
    "BOND Kelly": "bond-kelly",
    "BOND Ken": "bond-ken",
    "BOND Linda Thorsen": "bond-linda-thorsen",
    "BOND Matt": "bond-matt",
    "BOND Matthew": "bond-matthew",
    "BOND Nelson": "bond-nelson",
    "BOND Pat": "bond-pat",
    "BOND Phil Geoffrey": "bond-phil-geoffrey",
    "BOND Richard": "bond-richard",
    "BOND Robin": "bond-robin",
    "BOND Shelby": "bond-shelby",
    "BOND Timothy": "bond-timothy",
    "BOND Will": "bond-will",
    "BONDARIN Dev": "bondarin-dev",
    "BONDE Mick": "bonde-mick",
    "BONDER Nilton": "bonder-nilton",
    "BONDI Halley": "bondi-halley",
    "BOND-PABLE Elizabeth": "bond-pable-elizabeth",
    "BONDS Rachel": "bonds-rachel",
    "BONDY Halley": "bondy-halley",
    "BONE Ian": "bone-ian",
    "BONE Joe": "bone-joe",
    "BONE Nicholas": "bone-nicholas",
    "BONES Antonio": "bones-antonio",
    "BONFANTI Celeste": "bonfanti-celeste",
    "BONFANTI Eve": "bonfanti-eve",
    "BONFIGLIO Jon": "bonfiglio-jon",
    "BONGER Martin": "bonger-martin",
    "BONHAM Alex": "bonham-alex",
    "BONHAM Crispin": "bonham-crispin",
    "BONI John": "boni-john",
    "BONI Jon": "boni-jon",
    "BONILLA Alberto": "bonilla-alberto",
    "BONILLA Peter": "bonilla-peter",
    "BONIN-RODRIGUEZ Paul": "bonin-rodriguez-paul",
    "BONNA Katie": "bonna-katie",
    "BONNARD Robert A": "bonnard-robert-a",
    "BONNEE Marcus": "bonnee-marcus",
    "BONNEFIN Marcel": "bonnefin-marcel",
    "BONNEMA Ben": "bonnema-ben",
    "BONNEMA Jessica": "bonnema-jessica",
    "BONNER Ian": "bonner-ian",
    "BONNER Jeanette": "bonner-jeanette",
    "BONNER Marita": "bonner-marita",
    "BONNER Mary": "bonner-mary",
    "BONNET Alex": "bonnet-alex",
    "BONNET Leslie": "bonnet-leslie",
    "BONNETT Mary Frances": "bonnett-mary-frances",
    "BONNEVILLE Hugh": "bonneville-hugh",
    "BONNIN Roberta": "bonnin-roberta",
    "BONNINGTON Tom": "bonnington-tom",
    "BONNIWELL Beverly": "bonniwell-beverly",
    "BONOCORE Robert J": "bonocore-robert-j",
    "BONOTTO Robert": "bonotto-robert",
    "BONSEY Nigel": "bonsey-nigel",
    "BONSIGNORE Gregory": "bonsignore-gregory",
    "BONTATIBUS Michael": "bontatibus-michael",
    "BONTE Mossoux": "bonte-mossoux",
    "BONTE Richard": "bonte-richard",
    "BONTEMPO James": "bontempo-james",
    "BONTEMPS Arna": "bontemps-arna",
    "BONVIE Tom": "bonvie-tom",
    "BOOCK Paula": "boock-paula",
    "BOOCOCK Paul": "boocock-paul",
    "BOODEN D": "booden-d",
    "BOOGALOO STU ": "boogaloo-stu",
    "BOOK Stephen": "book-stephen",
    "BOOKER Charlotte": "booker-charlotte",
    "BOOKER Claire": "booker-claire",
    "BOOKER David": "booker-david",
    "BOOKER Malika": "booker-malika",
    "BOOKER Sue": "booker-sue",
    "BOOKLER Shelli Pentimall": "bookler-shelli-pentimall",
    "BOOM CHICAGO ": "boom-chicago",
    "BOON Jain": "boon-jain",
    "BOON Kevin": "boon-kevin",
    "BOON Mike": "boon-mike",
    "BOON Polly": "boon-polly",
    "BOONE Brian": "boone-brian",
    "BOONE David P": "boone-david-p",
    "BOONE JNR Mark": "boone-mark",
    "BOORMAN John": "boorman-john",
    "BOORSTIN David": "boorstin-david",
    "BOOSER Stephen": "booser-stephen",
    "BOOSTER Joel Kim": "booster-joel-kim",
    "BOOTH Allen": "booth-allen",
    "BOOTH Anthony": "booth-anthony",
    "BOOTH Connie": "booth-connie",
    "BOOTH Cynthia": "booth-cynthia",
    "BOOTH Eboni": "booth-eboni",
    "BOOTH Eric": "booth-eric",
    "BOOTH Hilliard": "booth-hilliard",
    "BOOTH Jack": "booth-jack",
    "BOOTH Laurie": "booth-laurie",
    "BOOTH Michael": "booth-michael",
    "BOOTH Phil": "booth-phil",
    "BOOTH Roger": "booth-roger",
    "BOOTH Roy C": "booth-roy-c",
    "BOOTH Samuel": "booth-samuel",
    "BOOTH Stewart": "booth-stewart",
    "BOOTH Tim": "booth-tim",
    "BOOTH Tony": "booth-tony",
    "BOOTHE Clare": "boothe-clare",
    "BOOTHROYD Michael": "boothroyd-michael",
    "BOOTY Jill": "booty-jill",
    "BOOZER Andrew Shepherd": "boozer-andrew-shepherd",
    "BOQUIST Darren": "boquist-darren",
    "BORAMAN Richard": "boraman-richard",
    "BORBELY Daniel": "borbely-daniel",
    "BORBERG Svend": "borberg-svend",
    "BORCHARDT Danuta": "borchardt-danuta",
    "BORCHERT Wolfgang": "borchert-wolfgang",
    "BORCHMEYER Florian": "borchmeyer-florian",
    "BORCIANI Mario": "borciani-mario",
    "BORDELON Margot": "bordelon-margot",
    "BORDEN Hal": "borden-hal",
    "BORDEN Lemuel": "borden-lemuel",
    "BORDEN Leon": "borden-leon",
    "BORDEN Tony": "borden-tony",
    "BORDEN Walter": "borden-walter",
    "BORDEN William": "borden-william",
    "BORDEWICH Jean P": "bordewich-jean-p",
    "BORDONI Alessio": "bordoni-alessio",
    "BOREN Heidi": "boren-heidi",
    "BORENGASSER Dan": "borengasser-dan",
    "BORENSTEIN Simcha": "borenstein-simcha",
    "BORER Mary Cathcart": "borer-mary-cathcart",
    "BORESI Matt": "boresi-matt",
    "BORETZ Allen": "boretz-allen",
    "BORETZ Alvin": "boretz-alvin",
    "BORG Christopher": "borg-christopher",
    "BORG Wes": "borg-wes",
    "BORGER Thomas": "borger-thomas",
    "BORGERS Helen": "borgers-helen",
    "BORGET Udo": "borget-udo",
    "BORGFELDT Mike": "borgfeldt-mike",
    "BORGIA Carmen": "borgia-carmen",
    "BORGIA Gianpiero": "borgia-gianpiero",
    "BORINI Joe": "borini-joe",
    "BORINSKY Alexander": "borinsky-alexander",
    "BORISS-KRIMSKY Carolyn": "boriss-krimsky-carolyn",
    "BORKHUIS Charles": "borkhuis-charles",
    "BORKOVEC Vera": "borkovec-vera",
    "BORKOWSKI Andrew": "borkowski-andrew",
    "BORKOWSKI Brian J": "borkowski-brian-j",
    "BORKOWSKI Mark": "borkowski-mark",
    "BORLAND Carroll": "borland-carroll",
    "BORLE Christian": "borle-christian",
    "BORMAN Phoebe": "borman-phoebe",
    "BORMET Gary": "bormet-gary",
    "BORNFIELD Mark": "bornfield-mark",
    "BORNSTEIN Ido": "bornstein-ido",
    "BORNSTEIN Jack": "bornstein-jack",
    "BORNSTEIN Kate": "bornstein-kate",
    "BORNSTEIN Rocky": "bornstein-rocky",
    "BORNSTEIN Stephanie": "bornstein-stephanie",
    "BORODIN Ivan": "borodin-ivan",
    "BOROSKI Kali": "boroski-kali",
    "BOROSON Martin": "boroson-martin",
    "BOROWKA Brian": "borowka-brian",
    "BOROWKA Steve": "borowka-steve",
    "BORRAS Manuel": "borras-manuel",
    "BORRELL Geraldine Palmer": "borrell-geraldine-palmer",
    "BORRELLI James": "borrelli-james",
    "BORRERO Guillermo": "borrero-guillermo",
    "BORRETT Liam": "borrett-liam",
    "BORRIS Leila": "borris-leila",
    "BORROW Antony": "borrow-antony",
    "BORROW Rena": "borrow-rena",
    "BORSHANSKY Adriel": "borshansky-adriel",
    "BORSKE Hal": "borske-hal",
    "BORSOI Edward": "borsoi-edward",
    "BORST-TARRANT Murielle": "borst-tarrant-murielle",
    "BORTNICKER Larry": "bortnicker-larry",
    "BORTON Michael": "borton-michael",
    "BORTUN Andreea": "bortun-andreea",
    "BORUFF John": "boruff-john",
    "BORUP Sandra K": "borup-sandra-k",
    "BORWICK Honor": "borwick-honor",
    "BORWICK Phoebe": "borwick-phoebe",
    "BORY Aurelien": "bory-aurelien"
  }
};