export default {
  "metadata": {
    "results": 582,
    "timeStamp": "2025-12-05T21:22:21.770Z",
    "url": "https://www.doollee.com/PlaywrightsB/B_playwrights_bos-bra.php"
  },
  "authors": {
    "BOS Deron": "bos-deron",
    "BOS Hannah": "bos-hannah",
    "BOSAKOWSKI Phil": "bosakowski-phil",
    "BOSAKOWSKY Phillip": "bosakowsky-phillip",
    "BOSANQUET Tim": "bosanquet-tim",
    "BOSBOOM Florence K": "bosboom-florence-k",
    "BOSCH Barbara": "bosch-barbara",
    "BOSCH Steven John": "bosch-steven-john",
    "BOSCHI Marella": "boschi-marella",
    "BOSCHI Nicholas": "boschi-nicholas",
    "BOSCOV Ellen": "boscov-ellen",
    "BOSCUTTI Stefano": "boscutti-stefano",
    "BOSE Siddhartha": "bose-siddhartha",
    "BOSEMAN Chadwick": "boseman-chadwick",
    "BOSGANG Jeremiah": "bosgang-jeremiah",
    "BOSIO Colin": "bosio-colin",
    "BOSJNAK Carla": "bosjnak-carla",
    "BOSLEY James": "bosley-james",
    "BOSLEY Laura Fois": "bosley-laura-fois",
    "BOSNJAK Carla": "bosnjak-carla",
    "BOSNJAK Elvis": "bosnjak-elvis",
    "BOSNJAK Slavko": "bosnjak-slavko",
    "BOSO Carlo": "boso-carlo",
    "BOSS A G": "boss-a-g",
    "BOSSEN Rebecca": "bossen-rebecca",
    "BOSSI Mauro": "bossi-mauro",
    "BOST Doug": "bost-doug",
    "BOST Pierre": "bost-pierre",
    "BOST Steven": "bost-steven",
    "BOSTIAN Kyle": "bostian-kyle",
    "BOSTICK Joseph": "bostick-joseph",
    "BOSTOCK Chris": "bostock-chris",
    "BOSTON L M": "boston-l-m",
    "BOSTON Stewart": "boston-stewart",
    "BOSTON, JR Robert C": "boston-jr-robert-c",
    "BOSTROM Arthur": "bostrom-arthur",
    "BOSTWICK Barry": "bostwick-barry",
    "BOSWELL Ella S": "boswell-ella-s",
    "BOSWELL Jack": "boswell-jack",
    "BOSWELL Katherine": "boswell-katherine",
    "BOSWELL Laurence": "boswell-laurence",
    "BOSWELL R J": "boswell-r-j",
    "BOSWELL III Sebastian": "boswell-iii-sebastian",
    "BOSWORTH Jen": "bosworth-jen",
    "BOSWORTH Michael": "bosworth-michael",
    "BOSWORTH Patricia": "bosworth-patricia",
    "BOSWORTH Philip": "bosworth-philip",
    "BOSWORTH Stanely": "bosworth-stanely",
    "BOTELLO Catalina": "botello-catalina",
    "BOTHWELL Alex": "bothwell-alex",
    "BOTTACHIO Roy": "bottachio-roy",
    "BOTTARI Michael P": "bottari-michael-p",
    "BOTTING Ashley": "botting-ashley",
    "BOTTING Bernard": "botting-bernard",
    "BOTTING Gary": "botting-gary",
    "BOTTOMLEY David": "bottomley-david",
    "BOTTOMLEY Gordon": "bottomley-gordon",
    "BOTTOMS Steve": "bottoms-steve",
    "BOTTRELL David": "bottrell-david",
    "BOTTRELL Louis": "bottrell-louis",
    "BOTTS Mark": "botts-mark",
    "BOTWINICK Amy": "botwinick-amy",
    "BOU Pep": "bou-pep",
    "BOUBLIL Alain": "boublil-alain",
    "BOUCHARD Michel Marc": "bouchard-michel-marc",
    "BOUCHAUD Elisabeth": "bouchaud-elisabeth",
    "BOUCHER Charlie": "boucher-charlie",
    "BOUCHER Denise": "boucher-denise",
    "BOUCHER Joan": "boucher-joan",
    "BOUCHER Serge": "boucher-serge",
    "BOUCICAULT Dion": "boucicault-dion",
    "BOUCKLEY Geoff": "bouckley-geoff",
    "BOUCQUEY Thierry": "boucquey-thierry",
    "BOUD John": "boud-john",
    "BOUDREAU Gordon": "boudreau-gordon",
    "BOUDREAUX Frank": "boudreaux-frank",
    "BOUFFARD Valerie B": "bouffard-valerie-b",
    "BOUGALL Gordon": "bougall-gordon",
    "BOUGHTON Walter": "boughton-walter",
    "BOUKIS John Paul": "boukis-john-paul",
    "BOULANGER A John": "boulanger-a-john",
    "BOULANGER-MASHBERG Anica": "boulanger-mashberg-anica",
    "BOULRICE Robert": "boulrice-robert",
    "BOULT Jenny": "boult-jenny",
    "BOULTON Hugh": "boulton-hugh",
    "BOULTON Rachael": "boulton-rachael",
    "BOULVA Josette": "boulva-josette",
    "BOUNACCORSI Debra": "bounaccorsi-debra",
    "BOUNDS Bryan": "bounds-bryan",
    "BOUNDY Neville": "boundy-neville",
    "BOURCIER Yolande": "bourcier-yolande",
    "BOURDAGES Michael": "bourdages-michael",
    "BOURDET Edouard": "bourdet-edouard",
    "BOURDET Gildas": "bourdet-gildas",
    "BOURDILLON Will": "bourdillon-will",
    "BOURGAUX Jacques": "bourgaux-jacques",
    "BOURGEADE Pierre": "bourgeade-pierre",
    "BOURGEOIS John": "bourgeois-john",
    "BOURGEOIS Pat": "bourgeois-pat",
    "BOURGEOIS Yoann": "bourgeois-yoann",
    "BOURGEOIS & MAURICE ": "bourgeois-maurice",
    "BOURJEILY Lucien": "bourjeily-lucien",
    "BOURKE Gary": "bourke-gary",
    "BOURKE Ger": "bourke-ger",
    "BOURKE Ken": "bourke-ken",
    "BOURNE Bette": "bourne-bette",
    "BOURNE James": "bourne-james",
    "BOURNE Lizzie": "bourne-lizzie",
    "BOURNE Lyndsey": "bourne-lyndsey",
    "BOURNE Mark C": "bourne-mark-c",
    "BOURNE Matthew": "bourne-matthew",
    "BOURNE ": "bourne",
    "BOURRET Adeline": "bourret-adeline",
    "BOURSEILLER Antoinne": "bourseiller-antoinne",
    "BOURTON Rayner": "bourton-rayner",
    "BOUSEL Stuart": "bousel-stuart",
    "BOUSER Steve": "bouser-steve",
    "BOUSFIELD Noni": "bousfield-noni",
    "BOUTHIETTE Jeffrey": "bouthiette-jeffrey",
    "BOUTHILLER Russell": "bouthiller-russell",
    "BOUTILLIER Fabian": "boutillier-fabian",
    "BOUTSAKIS Jeremy": "boutsakis-jeremy",
    "BOUTTE Duane": "boutte-duane",
    "BOUVET L": "bouvet-l",
    "BOUWMAN Robert": "bouwman-robert",
    "BOUYOUCAS Pan": "bouyoucas-pan",
    "BOVASSO Julie": "bovasso-julie",
    "BOVE Elizabeth": "bove-elizabeth",
    "BOVE Meredith": "bove-meredith",
    "BOVELL Andrew": "bovell-andrew",
    "BOVELL Brian": "bovell-brian",
    "BOVELL Corey": "bovell-corey",
    "BOVIE Palmer": "bovie-palmer",
    "BOVINO Jim": "bovino-jim",
    "BOVINO Marc": "bovino-marc",
    "BOVINO Paul": "bovino-paul",
    "BOWART Wolfe": "bowart-wolfe",
    "BOWDEN AriElla Beth": "bowden-ariella-beth",
    "BOWDEN Nigel": "bowden-nigel",
    "BOWDEN R H": "bowden-r-h",
    "BOWDEN Sarah": "bowden-sarah",
    "BOWDEN Stuart": "bowden-stuart",
    "BOWDITCH Caroline": "bowditch-caroline",
    "BOWEN Christopher Michael": "bowen-christopher-michael",
    "BOWEN Gail": "bowen-gail",
    "BOWEN Glory Sims": "bowen-glory-sims",
    "BOWEN James Lewis": "bowen-james-lewis",
    "BOWEN Jeff": "bowen-jeff",
    "BOWEN John": "bowen-john",
    "BOWEN Kate": "bowen-kate",
    "BOWEN Kevin": "bowen-kevin",
    "BOWEN Leah Simone": "bowen-leah-simone",
    "BOWEN Margaret": "bowen-margaret",
    "BOWEN Michael": "bowen-michael",
    "BOWEN Phil": "bowen-phil",
    "BOWEN Simon": "bowen-simon",
    "BOWEN Tricia": "bowen-tricia",
    "BOWER Caitlin": "bower-caitlin",
    "BOWER Chris": "bower-chris",
    "BOWER Humphrey": "bower-humphrey",
    "BOWERS Arla": "bowers-arla",
    "BOWERS Bern": "bowers-bern",
    "BOWERS Bill": "bowers-bill",
    "BOWERS Greg": "bowers-greg",
    "BOWERS Nadia": "bowers-nadia",
    "BOWERS Randy": "bowers-randy",
    "BOWERS Raymond": "bowers-raymond",
    "BOWERSOX Bob": "bowersox-bob",
    "BOWES Danny": "bowes-danny",
    "BOWES Simon": "bowes-simon",
    "BOWIE Bob": "bowie-bob",
    "BOWIE David": "bowie-david",
    "BOWIE Douglas": "bowie-douglas",
    "BOWIE Erik": "bowie-erik",
    "BOWKER Josh": "bowker-josh",
    "BOWLER Anmarie": "bowler-anmarie",
    "BOWLER Chris": "bowler-chris",
    "BOWLER Tim": "bowler-tim",
    "BOWLES Anthony": "bowles-anthony",
    "BOWLES Brett": "bowles-brett",
    "BOWLES Jane": "bowles-jane",
    "BOWLES Lauren": "bowles-lauren",
    "BOWLES Mark": "bowles-mark",
    "BOWLES N W": "bowles-n-w",
    "BOWLES Norma": "bowles-norma",
    "BOWLES Patrick": "bowles-patrick",
    "BOWLES Paul": "bowles-paul",
    "BOWLES Warren C": "bowles-warren-c",
    "BOWLIN Graham": "bowlin-graham",
    "BOWMAN Abie Philbin": "bowman-abie-philbin",
    "BOWMAN Ben": "bowman-ben",
    "BOWMAN Don": "bowman-don",
    "BOWMAN Edward": "bowman-edward",
    "BOWMAN Eva": "bowman-eva",
    "BOWMAN John": "bowman-john",
    "BOWMAN Kate": "bowman-kate",
    "BOWMAN Kathy": "bowman-kathy",
    "BOWMAN Katy": "bowman-katy",
    "BOWMAN Martin": "bowman-martin",
    "BOWMAN Paul": "bowman-paul",
    "BOWMAN Rob": "bowman-rob",
    "BOWN Abi": "bown-abi",
    "BOWN David": "bown-david",
    "BOWN Lesley": "bown-lesley",
    "BOWNE Alan": "bowne-alan",
    "BOWNESS Rob": "bowness-rob",
    "BOWSER Jessica": "bowser-jessica",
    "BOWSHER Rebekah": "bowsher-rebekah",
    "BOWSKILL Derek": "bowskill-derek",
    "BOWTELL Tom": "bowtell-tom",
    "BOX Moira Beebe": "box-moira-beebe",
    "BOXBERGER K R \"Skeeter\"": "boxberger-k-r",
    "BOY GEORGE ": "boy-george",
    "BOYACK Selina": "boyack-selina",
    "BOYCE Amy Rebecca": "boyce-amy-rebecca",
    "BOYCE Frank Cottrell": "boyce-frank-cottrell",
    "BOYCE James": "boyce-james",
    "BOYCE Nicola": "boyce-nicola",
    "BOYCE Stuart": "boyce-stuart",
    "BOYCHEV Hristo": "boychev-hristo",
    "BOYCHUK Peter": "boychuk-peter",
    "BOYD Andy": "boyd-andy",
    "BOYD B E": "boyd-b-e",
    "BOYD Carol": "boyd-carol",
    "BOYD Cathie": "boyd-cathie",
    "BOYD Christopher": "boyd-christopher",
    "BOYD David James": "boyd-david-james",
    "BOYD Frank": "boyd-frank",
    "BOYD George": "boyd-george",
    "BOYD Gregory": "boyd-gregory",
    "BOYD Hannah": "boyd-hannah",
    "BOYD John": "boyd-john",
    "BOYD Julianne": "boyd-julianne",
    "BOYD Justin": "boyd-justin",
    "BOYD M": "boyd-m",
    "BOYD Mari": "boyd-mari",
    "BOYD Michael A": "boyd-michael-a",
    "BOYD Pamela J": "boyd-pamela-j",
    "BOYD Paul": "boyd-paul",
    "BOYD Pom": "boyd-pom",
    "BOYD Samantha": "boyd-samantha",
    "BOYD Susan": "boyd-susan",
    "BOYD Vinetta": "boyd-vinetta",
    "BOYD William": "boyd-william",
    "BOYD-JONES Ernest": "boyd-jones-ernest",
    "BOYER Andrew": "boyer-andrew",
    "BOYER Carole": "boyer-carole",
    "BOYER Jay": "boyer-jay",
    "BOYER-WILLISSON Renee": "boyer-willisson-renee",
    "BOYETT Jim": "boyett-jim",
    "BOYETTE Patricia": "boyette-patricia",
    "BOYLAN Daryl": "boylan-daryl",
    "BOYLAN Joe": "boylan-joe",
    "BOYLAN John": "boylan-john",
    "BOYLAN Martin": "boylan-martin",
    "BOYLAN Mary": "boylan-mary",
    "BOYLAND James": "boyland-james",
    "BOYLE A J": "boyle-a-j",
    "BOYLE Bridget": "boyle-bridget",
    "BOYLE Brigid": "boyle-brigid",
    "BOYLE Catherine": "boyle-catherine",
    "BOYLE Craig": "boyle-craig",
    "BOYLE Daniel": "boyle-daniel",
    "BOYLE David": "boyle-david",
    "BOYLE Debra": "boyle-debra",
    "BOYLE Greg": "boyle-greg",
    "BOYLE Jackie": "boyle-jackie",
    "BOYLE Jimmy": "boyle-jimmy",
    "BOYLE Joe": "boyle-joe",
    "BOYLE Kenny": "boyle-kenny",
    "BOYLE Lucy": "boyle-lucy",
    "BOYLE Marilyn": "boyle-marilyn",
    "BOYLE Stephen": "boyle-stephen",
    "BOYLE Tom": "boyle-tom",
    "BOYLE Wickham": "boyle-wickham",
    "BOYLES Janea R": "boyles-janea-r",
    "BOYNTON Cindy Wolfe": "boynton-cindy-wolfe",
    "BOYNTON Keith": "boynton-keith",
    "BOYT Alex": "boyt-alex",
    "BOZI Rita": "bozi-rita",
    "BOZSIK Yvette": "bozsik-yvette",
    "BOZZONE Bill": "bozzone-bill",
    "BRAAK Chris": "braak-chris",
    "BRAATEN Heather": "braaten-heather",
    "BRAATZ Timothy": "braatz-timothy",
    "BRABAZON James": "brabazon-james",
    "BRABAZON OF TARA Lord": "brabazon-of-tara-lord",
    "BRABEN Eddie": "braben-eddie",
    "BRABHAM Alice R": "brabham-alice-r",
    "BRABHAM Robert C": "brabham-robert-c",
    "BRACE Adam": "brace-adam",
    "BRACHO Ricardo": "bracho-ricardo",
    "BRACK Joe": "brack-joe",
    "BRACKMAN Jacob": "brackman-jacob",
    "BRACO Jeffrey": "braco-jeffrey",
    "BRADATSCH Peter": "bradatsch-peter",
    "BRADBEER Suzanne": "bradbeer-suzanne",
    "BRADBURY A J": "bradbury-a-j",
    "BRADBURY David": "bradbury-david",
    "BRADBURY Helen": "bradbury-helen",
    "BRADBURY Malcolm": "bradbury-malcolm",
    "BRADBURY Megan": "bradbury-megan",
    "BRADBURY Parnell": "bradbury-parnell",
    "BRADBURY Ray": "bradbury-ray",
    "BRADBURY Richard": "bradbury-richard",
    "BRADBURY Simon": "bradbury-simon",
    "BRADBY David": "bradby-david",
    "BRADDOCK Nina": "braddock-nina",
    "BRADDON Russell": "braddon-russell",
    "BRADEN David": "braden-david",
    "BRADEN John": "braden-john",
    "BRADER Bob": "brader-bob",
    "BRADEY Lloyd": "bradey-lloyd",
    "BRADFIELD Dawn": "bradfield-dawn",
    "BRADFIELD Jon": "bradfield-jon",
    "BRADFORD Alex": "bradford-alex",
    "BRADFORD Barry": "bradford-barry",
    "BRADFORD Benjamin": "bradford-benjamin",
    "BRADFORD Blake": "bradford-blake",
    "BRADFORD Bryan": "bradford-bryan",
    "BRADFORD Michael": "bradford-michael",
    "BRADFORD Robin": "bradford-robin",
    "BRADFORD Sloan": "bradford-sloan",
    "BRADFORD Wade": "bradford-wade",
    "BRADFORD Zoe": "bradford-zoe",
    "BRADHURST Jane": "bradhurst-jane",
    "BRADLEY Adam": "bradley-adam",
    "BRADLEY Alex": "bradley-alex",
    "BRADLEY Alfred": "bradley-alfred",
    "BRADLEY Alison": "bradley-alison",
    "BRADLEY Belinda": "bradley-belinda",
    "BRADLEY Brendan": "bradley-brendan",
    "BRADLEY Brian": "bradley-brian",
    "BRADLEY Clive": "bradley-clive",
    "BRADLEY David": "bradley-david",
    "BRADLEY Everett": "bradley-everett",
    "BRADLEY F J": "bradley-f-j",
    "BRADLEY Gemma": "bradley-gemma",
    "BRADLEY Hannah": "bradley-hannah",
    "BRADLEY Ian": "bradley-ian",
    "BRADLEY J": "bradley-j",
    "BRADLEY Jack": "bradley-jack",
    "BRADLEY John": "bradley-john",
    "BRADLEY Jyll": "bradley-jyll",
    "BRADLEY Karen": "bradley-karen",
    "BRADLEY Karl": "bradley-karl",
    "BRADLEY Lynne": "bradley-lynne",
    "BRADLEY Martin": "bradley-martin",
    "BRADLEY Meg": "bradley-meg",
    "BRADLEY Michael": "bradley-michael",
    "BRADLEY Parris": "bradley-parris",
    "BRADLEY Sarah": "bradley-sarah",
    "BRADLEY Scott": "bradley-scott",
    "BRADLEY Sophie": "bradley-sophie",
    "BRADLEY-DYNE Michael": "bradley-dyne-michael",
    "BRADMAN Garrick": "bradman-garrick",
    "BRADSHAW Donna": "bradshaw-donna",
    "BRADSHAW Doug": "bradshaw-doug",
    "BRADSHAW Howard": "bradshaw-howard",
    "BRADSHAW Laura": "bradshaw-laura",
    "BRADSHAW Patti": "bradshaw-patti",
    "BRADSHAW Peter": "bradshaw-peter",
    "BRADSHAW Richard": "bradshaw-richard",
    "BRADSHAW Thomas": "bradshaw-thomas",
    "BRADSHAW JR Booker T": "bradshaw-jr-booker-t",
    "BRADSTREET Kyle": "bradstreet-kyle",
    "BRADT Anita": "bradt-anita",
    "BRADWELL Eric": "bradwell-eric",
    "BRADWELL John": "bradwell-john",
    "BRADWELL Mike": "bradwell-mike",
    "BRADY Heather C": "brady-heather-c",
    "BRADY J R": "brady-j-r",
    "BRADY James": "brady-james",
    "BRADY Jeanne Carberry": "brady-jeanne-carberry",
    "BRADY Jonathan": "brady-jonathan",
    "BRADY Joseph": "brady-joseph",
    "BRADY Ken": "brady-ken",
    "BRADY Lee": "brady-lee",
    "BRADY Leo": "brady-leo",
    "BRADY Mal": "brady-mal",
    "BRADY Margaret Ann": "brady-margaret-ann",
    "BRADY Matthew": "brady-matthew",
    "BRADY Michael": "brady-michael",
    "BRADY Patrick": "brady-patrick",
    "BRADY Peta": "brady-peta",
    "BRADY R K": "brady-r-k",
    "BRADY Ric": "brady-ric",
    "BRADY Robert": "brady-robert",
    "BRADY Stephen": "brady-stephen",
    "BRADY T J": "brady-t-j",
    "BRADY Tali": "brady-tali",
    "BRADY Terence": "brady-terence",
    "BRADY Veronica": "brady-veronica",
    "BRAFF Zach": "braff-zach",
    "BRAFMAN Charlie": "brafman-charlie",
    "BRAGANZA II Miguel": "braganza-ii-miguel",
    "BRAGEN Andy": "bragen-andy",
    "BRAGG Billy": "bragg-billy",
    "BRAGG David": "bragg-david",
    "BRAGG Jeannene": "bragg-jeannene",
    "BRAGG Melvyn": "bragg-melvyn",
    "BRAGGIOTTI Mario": "braggiotti-mario",
    "BRAGIN Irina": "bragin-irina",
    "BRAGINSKY Emil": "braginsky-emil",
    "BRAHAM Caroline": "braham-caroline",
    "BRAHE Per": "brahe-per",
    "BRAHMACHARI Sita": "brahmachari-sita",
    "BRAHMS Caryl": "brahms-caryl",
    "BRAILSFORD Ben": "brailsford-ben",
    "BRAILSFORD Kate": "brailsford-kate",
    "BRAILSFORD Mark": "brailsford-mark",
    "BRAIN A G": "brain-a-g",
    "BRAIN Jake": "brain-jake",
    "BRAINE Harriet": "braine-harriet",
    "BRAINE Richard": "braine-richard",
    "BRAININ Danny": "brainin-danny",
    "BRAITHWAITE Eddie Kamau": "braithwaite-eddie-kamau",
    "BRAITHWAITE Jax": "braithwaite-jax",
    "BRAITHWAITE Phil": "braithwaite-phil",
    "BRALY James": "braly-james",
    "BRAMBERG Joyce W": "bramberg-joyce-w",
    "BRAMBILLA Raul": "brambilla-raul",
    "BRAMBLE Forbes": "bramble-forbes",
    "BRAMBLE Mark": "bramble-mark",
    "BRAMER Shanon": "bramer-shanon",
    "BRAMHANDKAR Dipti": "bramhandkar-dipti",
    "BRAMLEY David": "bramley-david",
    "BRAMLEY Kate": "bramley-kate",
    "BRAMLEY Peter": "bramley-peter",
    "BRAMLEY-MOORE Z": "bramley-moore-z",
    "BRAMM Leslie": "bramm-leslie",
    "BRAMMAR Ellen": "brammar-ellen",
    "BRAMMELL Patrick": "brammell-patrick",
    "BRAMMER Peter": "brammer-peter",
    "BRAMMER Sidney": "brammer-sidney",
    "BRAMPTON Joan": "brampton-joan",
    "BRAMPTON Keith": "brampton-keith",
    "BRAMWELL David": "bramwell-david",
    "BRAMWELL Frank": "bramwell-frank",
    "BRANAGH Joyce": "branagh-joyce",
    "BRANAGH Kenneth": "branagh-kenneth",
    "BRANCATO Carolyn Kay": "brancato-carolyn-kay",
    "BRANCATO Robin F": "brancato-robin-f",
    "BRANCH Chris": "branch-chris",
    "BRANCH Eric": "branch-eric",
    "BRANCH Pamela": "branch-pamela",
    "BRANCH William": "branch-william",
    "BRANCHCOMB Sylvia Woingust": "branchcomb-sylvia-woingust",
    "BRANCO Guile": "branco-guile",
    "BRAND David A": "brand-david-a",
    "BRAND Ira": "brand-ira",
    "BRAND Jo": "brand-jo",
    "BRAND Ken": "brand-ken",
    "BRAND Mary": "brand-mary",
    "BRAND Mona": "brand-mona",
    "BRAND Neil": "brand-neil",
    "BRAND Oscar": "brand-oscar",
    "BRAND Ulrika": "brand-ulrika",
    "BRAND X ": "brand-x",
    "BRANDANE John": "brandane-john",
    "BRANDEL Marc": "brandell-marc",
    "BRANDENBERG Lance": "brandenberg-lance",
    "BRANDENBURG Indigo": "brandenburg-indigo",
    "BRANDES Alex": "brandes-alex",
    "BRANDES David": "brandes-david",
    "BRANDES Richard": "brandes-richard",
    "BRANDES Walter": "brandes-walter",
    "BRANDHURST Jane": "brandhurst-jane",
    "BRANDL Dave": "brandl-dave",
    "BRANDL Melissa": "brandl-melissa",
    "BRANDLI Jami": "brandli-jami",
    "BRANDNER Adam Gregory": "brandner-adam-gregory",
    "BRANDOM Helen": "brandom-helen",
    "BRANDON Beth": "brandon-beth",
    "BRANDON Christopher": "brandon-christopher",
    "BRANDON Dorothy": "brandon-dorothy",
    "BRANDON Eileen": "brandon-eileen",
    "BRANDON Johnny": "brandon-johnny",
    "BRANDON Lynne S": "brandon-lynne-s",
    "BRANDRETH Benet": "brandreth-benet",
    "BRANDRETH Gyles": "brandreth-gyles",
    "BRANDT Alan": "brandt-alan",
    "BRANDT Barbara": "brandt-barbara",
    "BRANDT Christy": "brandt-christy",
    "BRANDT Doug": "brandt-doug",
    "BRANDT George W": "brandt-george-w",
    "BRANDT Judith": "brandt-judith",
    "BRANDT Kirsten": "brandt-kirsten",
    "BRANDT Maria": "brandt-maria",
    "BRANDT Michael": "brandt-michael",
    "BRANDT Noreen K": "brandt-noreen-k",
    "BRANDT Sarah": "brandt-sarah",
    "BRANDT Val": "brandt-val",
    "BRANDT William": "brandt-william",
    "BRANDT Yanna Kroyt": "brandt-yanna-kroyt",
    "BRANDT-PIERCE Kwame": "brandt-pierce-kwame",
    "BRANDWEIN Judi Lee": "brandwein-judi-lee",
    "BRANDWEIN Rose-Marie": "brandwein-rose-marie",
    "BRANDY Arinne": "brandy-arinne",
    "BRANNAN Daniel William": "brannan-daniel-william",
    "BRANNAN Pascal": "brannan-pascal",
    "BRANNER Djola Bernard": "branner-djola-bernard",
    "BRANSCOMBE Arthur": "branscombe-arthur",
    "BRANSON Annie": "branson-annie",
    "BRANSON Greg": "branson-greg",
    "BRANSON Pip": "branson-pip",
    "BRANSON Tilly": "branson-tilly",
    "BRANT George": "brant-george",
    "BRANT Mike": "brant-mike",
    "BRANT Val": "brant-val",
    "BRANT William": "brant-william",
    "BRANTLEY J Stephen": "brantley-j-stephen",
    "BRANTON Dhana-Marie": "branton-dhana-marie",
    "BRANTON Melanie": "branton-melanie",
    "BRAR Amman Singh": "brar-amman-singh",
    "BRAROO Samesh": "braroo-samesh",
    "BRASCH Thomas": "brasch-thomas",
    "BRASELMAN Brooks": "braselman-brooks",
    "BRASH Peter": "brash-peter",
    "BRASHIER Anne": "brashier-anne",
    "BRASK Per": "brask-per",
    "BRASS Perry": "brass-perry",
    "BRASSARD April": "brassard-april",
    "BRASSARD Marie": "brassard-marie",
    "BRASSINGTON Chris": "brassington-chris",
    "BRASWELL John": "braswell-john",
    "BRASWELL Mark": "braswell-mark",
    "BRATER Jessica": "brater-jessica",
    "BRATHWAITE Tramaine": "brathwaite-tramaine",
    "BRATMAN Greg": "bratman-greg",
    "BRATOV Arnold": "bratov-arnold",
    "BRATT Harald": "bratt-harald",
    "BRAUD Michael": "braud-michael",
    "BRAULT Pierre": "brault-pierre",
    "BRAUN Harriet": "braun-harriet",
    "BRAUN Patrice": "braun-patrice",
    "BRAUN Richard Emil": "braun-richard-emil",
    "BRAUN Thom": "braun-thom",
    "BRAUN Timothy": "braun-timothy",
    "BRAUN Tricia": "braun-tricia",
    "BRAUN Volker": "braun-volker",
    "BRAUN Wilbur": "braun-wilbur",
    "BRAUNKE Gunar": "braunke-gunar",
    "BRAUNSHTEIN Doron": "braunshtein-doron",
    "BRAUNSTEIN Steve": "braunstein-steve",
    "BRAUSTEIN Alan": "braustein-alan",
    "BRAV Peter Gary": "brav-peter-gary",
    "BRAVACO Joe": "bravaco-joe",
    "BRAVERMAN Carole": "braverman-carole",
    "BRAVERMAN Danny": "braverman-danny",
    "BRAVERMAN Landon Seth": "braverman-landon-seth",
    "BRAVERMAN Paul": "braverman-paul",
    "BRAVO Awilda": "bravo-awilda",
    "BRAVO Brandi": "bravo-brandi",
    "BRAVO Luis": "bravo-luis",
    "BRAVO Paloma": "bravo-paloma",
    "BRAVO Victor": "bravo-victor",
    "BRAWER Ron": "brawer-ron",
    "BRAWN Nathan": "brawn-nathan",
    "BRAXTON Aaron": "braxton-aaron",
    "BRAXTON Stephanie": "braxton-stephanie",
    "BRAY Alexandra": "bray-alexandra",
    "BRAY Barbara": "bray-barbara",
    "BRAY Catherine": "bray-catherine",
    "BRAY Emma": "bray-emma",
    "BRAY Errol": "bray-errol",
    "BRAY Gregory Carl": "bray-gregory-carl",
    "BRAY James": "bray-james",
    "BRAY Jessica": "bray-jessica",
    "BRAY John Jefferson": "bray-john-jefferson",
    "BRAY John Patrick": "bray-john-patrick",
    "BRAY Lewis": "bray-lewis",
    "BRAY Oliver": "bray-oliver",
    "BRAY Stephen": "bray-stephen",
    "BRAY Tim": "bray-tim",
    "BRAY Winn": "bray-winn",
    "BRAYSHAW Teresa": "brayshaw-teresa",
    "BRAYTON Cass": "brayton-cass",
    "BRAZIER Paul": "brazier-paul",
    "BRAZIL Daynan": "brazil-daynan",
    "BRAZILL James": "brazill-james",
    "BRAZ-VALENTINE Claire": "braz-valentine-claire"
  }
};