export default {
  "metadata": {
    "results": 270,
    "timeStamp": "2025-12-05T21:22:23.142Z",
    "url": "https://www.doollee.com//PlaywrightsB/B_playwrights_brb-brn.php"
  },
  "authors": {
    "BREACH ": "breach",
    "BREAD & PUPPET ": "bread-puppet",
    "BREALEY Darren": "brealey-darren",
    "BREALEY Louise": "brealey-louise",
    "BREATHNACH Paraic": "breathnach-paraic",
    "BREBNER Andrew": "brebner-andrew",
    "BREBNER Ann": "brebner-ann",
    "BREBNER Morwyn": "brebner-morwyn",
    "BRECHT Bertolt": "brecht-bertolt",
    "BRECKON Mark": "breckon-mark",
    "BREDEHOEFT Ken": "bredehoeft-ken",
    "BREDEMEYER Frederick William": "bredemeyer-frederick-william",
    "BREDEN Simon": "breden-simon",
    "BREDEN Will W": "breden-will-w",
    "BREDSDORF Elias": "bredsdorf-elias",
    "BREDSDORFF Elias": "bredsdorff-elias",
    "BREE Germaine": "bree-germaine",
    "BREEDS Ian": "breeds-ian",
    "BREEN Anthony": "breen-anthony",
    "BREEN Brian": "breen-brian",
    "BREEN John": "breen-john",
    "BREEN Joseph": "breen-joseph",
    "BREEN Myles": "breen-myles",
    "BREEN Patrick": "breen-patrick",
    "BREEZE Naomi": "breeze-naomi",
    "BREEZE Tony": "breeze-tony",
    "BREFFORT Alexandre": "breffort-alexandre",
    "BREGMAN Erin": "bregman-erin",
    "BREHM Kate": "brehm-kate",
    "BREHMER Lin": "brehmer-lin",
    "BREIDENBACH Tom": "breidenbach-tom",
    "BREINDEL Alan": "breindel-alan",
    "BREIS ": "breis",
    "BREIT Harvey": "breit-harvey",
    "BREITANBACH Betsy": "breitanbach-betsy",
    "BREITHAUPT Don": "breithaupt-don",
    "BREITHAUPT Jeff": "breithaupt-jeff",
    "BREKKE William C": "brekke-william-c",
    "BRELSFORD Nick": "brelsford-nick",
    "BREMEL Albert": "bremel-albert",
    "BREMKAMP Jacob Stephen": "bremkamp-jacob-stephen",
    "BREMNER Belinda": "bremner-belinda",
    "BREMNER Rory": "bremner-rory",
    "BREN F D": "bren-f-d",
    "BRENDLINGER Carole": "brendlinger-carole",
    "BRENNAN Clara": "brennan-clara",
    "BRENNAN Craig": "brennan-craig",
    "BRENNAN Dominic": "brennan-dominic",
    "BRENNAN Frederick Hazlitt": "brennan-frederick-hazlitt",
    "BRENNAN Gerard": "brennan-gerard",
    "BRENNAN J Keirn": "brennan-j-keirn",
    "BRENNAN Jimmy": "brennan-jimmy",
    "BRENNAN Joe": "brennan-joe",
    "BRENNAN Julia": "brennan-julia",
    "BRENNAN Kathleen": "brennan-kathleen",
    "BRENNAN Kit": "brennan-kit",
    "BRENNAN Liam": "brennan-liam",
    "BRENNAN Lyra": "brennan-lyra",
    "BRENNAN Mark": "brennan-mark",
    "BRENNAN Michael": "brennan-michael",
    "BRENNAN Nick": "brennan-nick",
    "BRENNAN Pat": "brennan-pat",
    "BRENNAN Patrick M": "brennan-patrick-m",
    "BRENNAN Paul": "brennan-paul",
    "BRENNAN Peter": "brennan-peter",
    "BRENNAN Ray": "brennan-ray",
    "BRENNAN Scott": "brennan-scott",
    "BRENNAN Sharon": "brennan-sharon",
    "BRENNAN Stephen Vincent": "brennan-stephen-vincent",
    "BRENNAN Tom": "brennan-tom",
    "BRENNEMAN Joey": "brenneman-joey",
    "BRENNEN Anna": "brennen-anna",
    "BRENNER Alfred": "brenner-alfred",
    "BRENNER Anna Alison": "brenner-anna-alison",
    "BRENNER Daniel": "brenner-daniel",
    "BRENNER Donald": "brenner-donald",
    "BRENNER Evan": "brenner-evan",
    "BRENNER Janet": "brenner-janet",
    "BRENNER Larry": "brenner-larry",
    "BRENNER Marc": "brenner-marc",
    "BRENNERT Alan": "brennert-alan",
    "BRENNON Julie": "brennon-julie",
    "BRENT David Milton": "brent-david-milton",
    "BRENT Doris": "brent-doris",
    "BRENT Jackie S": "brent-jackie-s",
    "BRENT Marcus": "brent-marcus",
    "BRENT Romney": "brent-romney",
    "BRENTNALL Huw": "brentnall-huw",
    "BRENTON Bree": "brenton-bree",
    "BRENTON Howard": "brenton-howard",
    "BRENTON Will": "brenton-will",
    "BRERETON Geoffrey": "brereton-geoffrey",
    "BRESKIN David": "breskin-david",
    "BRESLIN Anthony": "breslin-anthony",
    "BRESLIN Jimmy": "breslin-jimmy",
    "BRESLOW Julian William": "breslow-julian-william",
    "BRESLOW Maurice": "breslow-maurice",
    "BRESSENBRUGE Mei Mei": "bressenbruge-mei-mei",
    "BRESSLER Suzanne": "bressler-suzanne",
    "BRET David": "bret-david",
    "BRETON Natalie": "breton-natalie",
    "BRETT Alastair": "brett-alastair",
    "BRETT Annie": "brett-annie",
    "BRETT Bev": "brett-bev",
    "BRETT David": "brett-david",
    "BRETT David (1)": "brett-david-1",
    "BRETT Michael": "brett-michael",
    "BRETT Peter": "brett-peter",
    "BRETT Richard": "brett-richard",
    "BRETT Simon": "brett-simon",
    "BRETT Simon Michael": "brett-simon-michael",
    "BRETT Wayne": "brett-wayne",
    "BRETT-BAILEY Christopher": "brett-bailey-christopher",
    "BREUER Bill": "breuer-bill",
    "BREUER Lee": "breuer-lee",
    "BREULER Bob": "breuler-bob",
    "BREVARD Lizzie": "brevard-lizzie",
    "BREVIS Claudia": "brevis-claudia",
    "BREVIS Skip": "brevis-skip",
    "BREVOORT Deborah": "brevoort-deborah",
    "BREWER Delaney Britt": "brewer-delaney-britt",
    "BREWER Elly": "brewer-elly",
    "BREWER Gaylord": "brewer-gaylord",
    "BREWER Kevin": "brewer-kevin",
    "BREWER Roger L": "brewer-roger-l",
    "BREWER Sandy": "brewer-sandy",
    "BREWER, JR George": "brewer-jr-george",
    "BREWIN Jennifer": "brewin-jennifer",
    "BREWINGTON Larissa L": "brewington-larissa-l",
    "BREWIS Peter": "brewis-peter",
    "BREWSTER Josh": "brewster-josh",
    "BREWSTER Pachali": "brewster-pachali",
    "BREWSTER Townsend": "brewster-townsend",
    "BREWSTER Yvonne": "brewster-yvonne",
    "BREY Rebecca": "brey-rebecca",
    "BREYA Laurabeth": "breya-laurabeth",
    "BREYTENBACH Marisa": "breytenbach-marisa",
    "BREZNITSKY Erin": "breznitsky-erin",
    "BRIAN Margaret": "brian-margaret",
    "BRIAN Mitch": "brian-mitch",
    "BRIAN ": "brian",
    "BRIANT Lucy": "briant-lucy",
    "BRIARWOOD Stephanie": "briarwood-stephanie",
    "BRICENO Jacqueline": "briceno-jacqueline",
    "BRICK Scott": "brick-scott",
    "BRICKELL Edie": "brickell-edie",
    "BRICKELL Lisa": "brickell-lisa",
    "BRICKENDEN Catherine": "brickenden-catherine",
    "BRICKMAN Jessica": "brickman-jessica",
    "BRICKMAN Marshall": "brickman-marshall",
    "BRICKMAN Mattie": "brickman-mattie",
    "BRICKNER Danyele": "brickner-danyele",
    "BRICUSSE Leslie": "bricusse-leslie",
    "BRIDEL David": "bridel-david",
    "BRIDENSTINE Evan M": "bridenstine-evan-m",
    "BRIDES Ivory": "brides-ivory",
    "BRIDGE Dian Marie": "bridge-dian-marie",
    "BRIDGE Jude": "bridge-jude",
    "BRIDGEMAN Laura": "bridgeman-laura",
    "BRIDGEMONT Andrew": "bridgemont-andrew",
    "BRIDGER Alan": "bridger-alan",
    "BRIDGER Becky": "bridger-becky",
    "BRIDGER Jim": "bridger-jim",
    "BRIDGERS Ann Preston": "bridgers-ann-preston",
    "BRIDGES Amy": "bridges-amy",
    "BRIDGES Beau": "bridges-beau",
    "BRIDGES Bill": "bridges-bill",
    "BRIDGES Burnt": "bridges-burnt",
    "BRIDGES Emily": "bridges-emily",
    "BRIDGES Josh": "bridges-josh",
    "BRIDGES Keith": "bridges-keith",
    "BRIDGES Peter": "bridges-peter",
    "BRIDGES Rony": "bridges-rony",
    "BRIDGFORTH Sharon": "bridgforth-sharon",
    "BRIDGMONT Andrew": "bridgmont-andrew",
    "BRIDI Emmanuelle": "bridi-emmanuelle",
    "BRIDIE James": "bridie-james",
    "BRIDMONT Andrew": "bridmont-andrew",
    "BRIELLE Jon": "brielle-jon",
    "BRIENIK Salvatore": "brienik-salvatore",
    "BRIENZA Laura": "brienza-laura",
    "BRIER Harriet": "brier-harriet",
    "BRIERE Daniel": "briere-daniel",
    "BRIERLEY Gareth": "brierley-gareth",
    "BRIETIGAM George": "brietigam-george",
    "BRIEUX Eugene": "brieux-eugene",
    "BRIFFA Peter": "briffa-peter",
    "BRIFFAULT Hirma": "briffault-hirma",
    "BRIGANTINO Lisa": "brigantino-lisa",
    "BRIGANTINO Lori": "brigantino-lori",
    "BRIGG Gill": "brigg-gill",
    "BRIGGS Hailey": "briggs-hailey",
    "BRIGGS John R": "briggs-john-r",
    "BRIGGS Joshua": "briggs-joshua",
    "BRIGGS Laurie": "briggs-laurie",
    "BRIGGS Lou": "briggs-lou",
    "BRIGGS Nicholas": "briggs-nicholas",
    "BRIGGS Raymond": "briggs-raymond",
    "BRIGGS Rick": "briggs-rick",
    "BRIGGS Sam": "briggs-sam",
    "BRIGGS Stephen": "briggs-stephen",
    "BRIGGS Tom": "briggs-tom",
    "BRIGGS Tony": "briggs-tony",
    "BRIGGS-NOVAES Tereza": "briggs-novaes-tereza",
    "BRIGHOUSE Harold": "brighouse-harold",
    "BRIGHT Rochelle": "bright-rochelle",
    "BRIGHT Tom": "bright-tom",
    "BRIGHT CHOICE ": "bright-choice",
    "BRIGHT RED ": "bright-red",
    "BRIGHTON Pam": "brighton-pam",
    "BRIGHTWELL Donna": "brightwell-donna",
    "BRIGNALL Sarah": "brignall-sarah",
    "BRIGSTOCKE Marcus": "brigstocke-marcus",
    "BRIIKS Daniel": "briiks-daniel",
    "BRILEY John": "briley-john",
    "BRILL M": "brill-m",
    "BRILL Marius": "brill-marius",
    "BRILL Marty": "brill-marty",
    "BRILL Sarah": "brill-sarah",
    "BRIMIJOHN Mark": "brimijohn-mark",
    "BRINCKLOW Elizabeth A": "brincklow-elizabeth-a",
    "BRIND Matthew": "brind-matthew",
    "BRIND Morgan": "brind-morgan",
    "BRINDLEY Erin": "brindley-erin",
    "BRINE Adrian": "brine-adrian",
    "BRINE Salty": "brine-salty",
    "BRINEGAR David": "brinegar-david",
    "BRINGSVAED Tor Age": "bringsvaed-tor-age",
    "BRINING James": "brining-james",
    "BRINK Robert": "brink-robert",
    "BRINKERHOFF Cort": "brinkerhoff-cort",
    "BRINKHURST Tim": "brinkhurst-tim",
    "BRINKMAN Baba": "brinkman-baba",
    "BRINNEN Malcom": "brinnen-malcom",
    "BRINSTER Freddie": "brinster-freddie",
    "BRISBANE Jo Hull": "brisbane-jo-hull",
    "BRISBOIS Ken": "brisbois-ken",
    "BRISBY Kent": "brisby-kent",
    "BRISBY Nathan": "brisby-nathan",
    "BRISCOE Rachel": "briscoe-rachel",
    "BRISLAN Bill": "brislan-bill",
    "BRISTER Julie": "brister-julie",
    "BRITH GOF ": "brith-gof",
    "BRITISH THEATRE OF THE DEAF ": "british-theatre-of-the-deaf",
    "BRITO Anthony": "brito-anthony",
    "BRITON Jesse": "briton-jesse",
    "BRITT Antony N": "britt-antony-n",
    "BRITT Jason": "britt-jason",
    "BRITT Linda": "britt-linda",
    "BRITTAIN Jamie": "brittain-jamie",
    "BRITTAIN Jon": "brittain-jon",
    "BRITTAIN Rachel": "brittain-rachel",
    "BRITTAIN Victoria": "brittain-victoria",
    "BRITTAN Iain": "brittan-iain",
    "BRITTEN Matt": "britten-matt",
    "BRITTEN Tony": "britten-tony",
    "BRITTIN A": "brittin-a",
    "BRITTNEY Lynn": "brittney-lynn",
    "BRITTON Alfred": "britton-alfred",
    "BRITTON Chris": "britton-chris",
    "BRITTON D J": "britton-d-j",
    "BRITTON David": "britton-david",
    "BRITTON H R": "britton-h-r",
    "BRITTON Iain": "britton-iain",
    "BRITTON John": "britton-john",
    "BRITTON Julia": "britton-julia",
    "BRITTON Ronnie": "britton-ronnie",
    "BRITTON Sherry": "britton-sherry",
    "BRITTON Tim": "britton-tim",
    "BRNO Paul": "brno-paul"
  }
};