export default {
  "metadata": {
    "results": 1211,
    "timeStamp": "2025-12-05T21:22:48.038Z",
    "url": "https://www.doollee.com/PlaywrightsC/C_playwrights_a-f.php"
  },
  "authors": {
    "CAAN Scott": "caan-scott",
    "CABAL Fermin": "cabal-fermin",
    "CABALLERO Ernesto": "caballero-ernesto",
    "CABALLERO Luis": "caballero-luis",
    "CABALLERO Nstor": "caballero-nstor",
    "CABAN Andrea": "caban-andrea",
    "CABANILLA Gabino": "cabanilla-gabino",
    "CABANISS Mark": "cabaniss-mark",
    "CABANISS Thomas": "cabaniss-thomas",
    "CABELL Robert W": "cabell-robert-w",
    "CABICO Regie": "cabico-regie",
    "CABLE Christopher": "cable-christopher",
    "CABNET Evan": "cabnet-evan",
    "CABOT Annette": "cabot-annette",
    "CABOT Michael": "cabot-michael",
    "CABRANES-GRANT Leo F": "cabranes-grant-leo-f",
    "CABROL Yves": "cabrol-yves",
    "CABRUJAS Jose Ignacio": "cabrujas-jose-ignacio",
    "CABUR Beatriz": "cabur-beatriz",
    "CACACE Rosanna": "cacace-rosanna",
    "CACARES Leticia": "cacares-leticia",
    "CACCIABAUDO Sharon": "cacciabaudo-sharon",
    "CACCIATO Carmelo": "cacciato-carmelo",
    "CACHAPERO Patty": "cachapero-patty",
    "CACHIANES Ed": "cachianes-ed",
    "CACHO Daniel Gimeenez": "cacho-daniel-gimeenez",
    "CACIEDO Veronica": "caciedo-veronica",
    "CACOYANNIS Michael": "cacoyannis-michael",
    "CADDELL Yvonne": "caddell-yvonne",
    "CADDICK David": "caddick-david",
    "CADDICK Edward": "caddick-edward",
    "CADDICK Pippa": "caddick-pippa",
    "CADDY Leonard H": "caddy-leonard-h",
    "CADE Amy": "cade-amy",
    "CADE John": "cade-john",
    "CADE Rosana": "cade-rosana",
    "CADETTE G S": "cadette-g-s",
    "CADIEUX Jason": "cadieux-jason",
    "CADIOT Olivier": "cadiot-olivier",
    "CADIZ Melaena": "cadiz-melaena",
    "CADMAN Larry": "cadman-larry",
    "CADULLO Bert": "cadullo-bert",
    "CADWALLADER Gareth": "cadwallader-gareth",
    "CAEL Kestryl": "cael-kestryl",
    "CAESAR Adolf": "caesar-adolf",
    "CAESAR Arthur": "caesar-arthur",
    "CAESAR Irving": "caesar-irving",
    "CAFARELLA Jane": "cafarella-jane",
    "CAFFERKY Tony": "cafferky-tony",
    "CAFFEY John Michael": "caffey-john-michael",
    "CAFFEY Marion J": "caffey-marion-j",
    "CAFFINE George": "caffine-george",
    "CAFFREY Sean": "caffrey-sean",
    "CAFOLLA Vittoria": "cafolla-vittoria",
    "CAGAN Kayla": "cagan-kayla",
    "CAGAN Steve": "cagan-steve",
    "CAGGIANO Daniella": "caggiano-daniella",
    "CAGNACCI Lisa": "cagnacci-lisa",
    "CAHAN Dorothea": "cahan-dorothea",
    "CAHILL David": "cahill-david",
    "CAHILL Edward": "cahill-edward",
    "CAHILL Eilis": "cahill-eilis",
    "CAHILL Jordyn": "cahill-jordyn",
    "CAHILL Kathleen": "cahill-kathleen",
    "CAHILL Kendra": "cahill-kendra",
    "CAHILL Laura": "cahill-laura",
    "CAHILL Michael": "cahill-michael",
    "CAHILL Paul": "cahill-paul",
    "CAHILL Sylvia": "cahill-sylvia",
    "CAHILL Thomas J": "cahill-thomas-j",
    "CAHN Sammy": "cahn-sammy",
    "CAHN Victor L": "cahn-victor-l",
    "CAIA Didem": "caia-didem",
    "CAIN Bill": "cain-bill",
    "CAIN Candice": "cain-candice",
    "CAIN James": "cain-james",
    "CAIN Julia Harman": "cain-julia-harman",
    "CAIN Marie": "cain-marie",
    "CAIN Michael Thomas": "cain-michael-thomas",
    "CAIN Nicole": "cain-nicole",
    "CAIN Orlando": "cain-orlando",
    "CAINE John": "caine-john",
    "CAINE Peggy": "caine-peggy",
    "CAINE Sari": "caine-sari",
    "CAINER Daniel": "cainer-daniel",
    "CAINERO Ferruccio": "cainero-ferruccio",
    "CAINES Michael": "caines-michael",
    "CAIOLA Rose": "caiola-rose",
    "CAIRD John": "caird-john",
    "CAIRD Sam": "caird-sam",
    "CAIRNCROSS John": "cairncross-john",
    "CAIRNEY Fergal E": "cairney-fergal-e",
    "CAIRNEY John": "cairney-john",
    "CAIRNS Angela": "cairns-angela",
    "CAIRNS George A": "cairns-george-a",
    "CAIRNS Glen": "cairns-glen",
    "CAIRNS James": "cairns-james",
    "CAIRNS Laura": "cairns-laura",
    "CAIRNS Mark": "cairns-mark",
    "CAIRNS Mary": "cairns-mary",
    "CAIRNS Philip": "cairns-philip",
    "CAIRNS Susan": "cairns-susan",
    "CAIRNS Tom": "cairns-tom",
    "CAISLEY Robert": "caisley-robert",
    "CAITO Norman": "caito-norman",
    "CAJAL Oana Maria": "cajal-oana-maria",
    "CAKEBREAD Sonia": "cakebread-sonia",
    "CAKMIS Bill": "cakmis-bill",
    "CALA Caroline": "cala-caroline",
    "CALABRESE Rosalie": "calabrese-rosalie",
    "CALABRESE Tina": "calabrese-tina",
    "CALAFATO Aaron": "calafato-aaron",
    "CALAHAN Susan K": "calahan-susan-k",
    "CALAIS David": "calais-david",
    "CALAMONERI Tanya": "calamoneri-tanya",
    "CALANDRA Brian": "calandra-brian",
    "CALANDRA Denis": "calandra-denis",
    "CALANDRINO Paul": "calandrino-paul",
    "CALARCO Joe": "calarco-joe",
    "CALARCO Renee": "calarco-renee",
    "CALCATERRA Bradley": "calcaterra-bradley",
    "CALCOEN Nikolai": "calcoen-nikolai",
    "CALCUTT David": "calcutt-david",
    "CALCUTT Shannan": "calcutt-shannan",
    "CALCUTT Thomas": "calcutt-thomas",
    "CALDARONE Maria": "caldarone-maria",
    "CALDECOTT Andrew": "caldecott-andrew",
    "CALDECOTT Nick": "caldecott-nick",
    "CALDER Daniel": "calder-daniel",
    "CALDER Gowan": "calder-gowan",
    "CALDER Joan": "calder-joan",
    "CALDER John": "calder-john",
    "CALDERON Guillermo": "calderon-guillermo",
    "CALDERON Victoria E": "calderon-victoria-e",
    "CALDERON Yonatan": "calderon-yonatan",
    "CALDERON DE LA BARCA Pedro": "calderon-de-la-barca-pedro",
    "CALDERWOOD Alec": "calderwood-alec",
    "CALDERWOOD Daphne": "calderwood-daphne",
    "CALDICOTT Candida": "caldicott-candida",
    "CALDON John": "caldon-john",
    "CALDWELL Anne": "caldwell-anne",
    "CALDWELL Ben": "caldwell-ben",
    "CALDWELL Campbell": "caldwell-campbell",
    "CALDWELL David": "caldwell-david",
    "CALDWELL Edmond": "caldwell-edmond",
    "CALDWELL Erskine": "caldwell-erskine",
    "CALDWELL George": "caldwell-george",
    "CALDWELL James Ryan": "caldwell-james-ryan",
    "CALDWELL Joseph": "caldwell-joseph",
    "CALDWELL Katrina": "caldwell-katrina",
    "CALDWELL Lawson": "caldwell-lawson",
    "CALDWELL Lucy": "caldwell-lucy",
    "CALDWELL Patrick": "caldwell-patrick",
    "CALDWELL Stuart": "caldwell-stuart",
    "CALE David": "cale-david",
    "CALEB J Rufus": "caleb-j-rufus",
    "CALENDER June": "calender-june",
    "CALEO Bernard": "caleo-bernard",
    "CALHOON Zack": "calhoon-zack",
    "CALHORN G M": "calhorn-g-m",
    "CALHOUN Barbara": "calhoun-barbara",
    "CALHOUN Matthew": "calhoun-matthew",
    "CALHOUN Wil": "calhoun-wil",
    "CALIBAN Richard": "caliban-richard",
    "CALIGULA'S ALIBI ": "caligula-s-alibi",
    "CALINDAS Jonathan": "calindas-jonathan",
    "CALISTRO Paddy": "calistro-paddy",
    "CALIXTO Oscar": "calixto-oscar",
    "CALL Daniel": "call-daniel",
    "CALL Danna": "call-danna",
    "CALL James": "call-james",
    "CALLAGHAN Peter": "callaghan-peter",
    "CALLAGHAN Sheila": "callaghan-sheila",
    "CALLAGHAN Stace": "callaghan-stace",
    "CALLAGHAN-HOOKS Sandy": "callaghan-hooks-sandy",
    "CALLAHAN Darren": "callahan-darren",
    "CALLAHAN Francis Paul": "callahan-francis-paul",
    "CALLAHAN Jody": "callahan-jody",
    "CALLAHAN Matt": "callahan-matt",
    "CALLAHAN Neil": "callahan-neil",
    "CALLAHAN William": "callahan-william",
    "CALLAN Edward": "callan-edward",
    "CALLAN F G": "callan-f-g",
    "CALLANDER Marjory": "callander-marjory",
    "CALLANDER Peter": "callander-peter",
    "CALLARD Maurice": "callard-maurice",
    "CALLAS Ellen": "callas-ellen",
    "CALLE Sophie": "calle-sophie",
    "CALLELY Robert": "callely-robert",
    "CALLEN Harold": "callen-harold",
    "CALLEN Harold (1)": "callen-harold-1",
    "CALLEN John": "callen-john",
    "CALLEN Judi": "callen-judi",
    "CALLERI Joe": "calleri-joe",
    "CALLINAN Rachel": "callinan-rachel",
    "CALLINGHAM Judy": "callingham-judy",
    "CALLOW Simon": "callow-simon",
    "CALLOW, JR Christos": "callow-jr-christos",
    "CALMAN Craig": "calman-craig",
    "CALMSON Steven": "calmson-stephen",
    "CALNEK-SUGIN Rachel": "calnek-sugin-rachel",
    "CALONE Peter": "calone-peter",
    "CALONGE Nikki": "calonge-nikki",
    "CALOS-NAKANO Nancy": "calos-nakano-nancy",
    "CALOW Carl": "calow-carl",
    "CALTON W E": "calton-w-e",
    "CALUORI Malcolm R": "caluori-malcolm-r",
    "CALVANI Marco": "calvani-marco",
    "CALVER Sarah": "calver-sarah",
    "CALVERT Dave": "calvert-dave",
    "CALVERT E J C": "calvert-e-j-c",
    "CALVERT Misha": "calvert-misha",
    "CALVERT Raes": "calvert-raes",
    "CALVERT Robert": "calvert-robert",
    "CALVERT William H": "calvert-william-h",
    "CALVIN Darrell Taylor": "calvin-darrell-taylor",
    "CALVINO Italo": "calvino-italo",
    "CALVISI Dan": "calvisi-dan",
    "CALVIT Christina": "calvit-christina",
    "CALWAY Gareth": "calway-gareth",
    "CAMARENO Joe": "camareno-joe",
    "CAMBAGE Leonie": "cambage-leonie",
    "CAMBELL Maria": "cambell-maria",
    "CAMBELL Mark": "cambell-mark",
    "CAMBELL Paul N": "cambell-paul-n",
    "CAMBLIN Zina": "camblin-zina",
    "CAMBRIDGE Daniel G": "cambridge-daniel-g",
    "CAMDEN Steven 'Polarbear'": "camden-steven",
    "CAMDEN PEOPLE'S THEATRE ": "camden-peoples-theatre",
    "CAMERON Alister": "cameron-alister",
    "CAMERON Callum": "cameron-callum",
    "CAMERON Charles": "cameron-charles",
    "CAMERON Derek": "cameron-derek",
    "CAMERON Donna": "cameron-donna",
    "CAMERON Donnie": "cameron-donnie",
    "CAMERON Erin": "cameron-erin",
    "CAMERON Ian": "cameron-ian",
    "CAMERON John B": "cameron-john-b",
    "CAMERON Joshua": "cameron-joshua",
    "CAMERON Julia": "cameron-julia",
    "CAMERON Ken": "cameron-ken",
    "CAMERON Kenneth": "cameron-kenneth",
    "CAMERON Kenneth M": "cameron-kenneth-m",
    "CAMERON Kwesi": "cameron-kwesi",
    "CAMERON Margaret": "cameron-margaret",
    "CAMERON Mark": "cameron-mark",
    "CAMERON Matt": "cameron-matt",
    "CAMERON Nicola": "cameron-nicola",
    "CAMERON Norman E": "cameron-norman-e",
    "CAMERON Peter John": "cameron-peter-john",
    "CAMERON Richard": "cameron-richard",
    "CAMERON Robert": "cameron-robert",
    "CAMERON Rodrigo": "cameron-rodrigo",
    "CAMERON Samantha": "cameron-samantha",
    "CAMERON Sarah": "cameron-sarah",
    "CAMERON Saraid": "cameron-saraid",
    "CAMERON William": "cameron-william",
    "CAMICIA Jimmy": "camicia-jimmy",
    "CAMING Scott": "caming-scott",
    "CAMINS Alexis": "camins-alexis",
    "CAMOLETTI Marc": "camoletti-marc",
    "CAMP Bill": "camp-bill",
    "CAMP Jennifer": "camp-jennifer",
    "CAMP Lilly Elizabeth": "camp-lilly-elizabeth",
    "CAMP Robert Quillen": "camp-robert-quillen",
    "CAMP T J": "camp-t-j",
    "CAMPANARO Craig S": "campanaro-craig-s",
    "CAMPANELLA Joe": "campanella-joe",
    "CAMPAUX Francois": "campaux-francois",
    "CAMPBELL Alexi Kaye": "campbell-alexi-kaye",
    "CAMPBELL Alistair": "campbell-alistair",
    "CAMPBELL Alistair (1)": "campbell-alistair-1",
    "CAMPBELL Alistair (2)": "campbell-alistair-2",
    "CAMPBELL Alvin": "campbell-alvin",
    "CAMPBELL Apphia": "campbell-apphia",
    "CAMPBELL Barbara": "campbell-barbara",
    "CAMPBELL Beatrix": "campbell-beatrix",
    "CAMPBELL Beth": "campbell-beth",
    "CAMPBELL Brian": "campbell-brian",
    "CAMPBELL Carissa": "campbell-carissa",
    "CAMPBELL Catriona Lexy": "campbell-catriona-lexy",
    "CAMPBELL Chloe": "campbell-chloe",
    "CAMPBELL Chris": "campbell-chris",
    "CAMPBELL Clifton": "campbell-clifton",
    "CAMPBELL Craig C": "campbell-craig-c",
    "CAMPBELL D J": "campbell-d-j",
    "CAMPBELL Daisy": "campbell-daisy",
    "CAMPBELL David": "campbell-david",
    "CAMPBELL Debbie": "campbell-debbie",
    "CAMPBELL Del": "campbell-del",
    "CAMPBELL Derek": "campbell-derek",
    "CAMPBELL Dick": "campbell-dick",
    "CAMPBELL Donald": "campbell-donald",
    "CAMPBELL Edie": "campbell-edie",
    "CAMPBELL Edward": "campbell-edward",
    "CAMPBELL Elaine": "campbell-elaine",
    "CAMPBELL Erica": "campbell-erica",
    "CAMPBELL Gayle": "campbell-gayle",
    "CAMPBELL Graeme": "campbell-graeme",
    "CAMPBELL Guerney": "campbell-guerney",
    "CAMPBELL Herbert": "campbell-herbert",
    "CAMPBELL J Christopher": "campbell-j-christopher",
    "CAMPBELL J Douglas": "campbell-j-douglas",
    "CAMPBELL James": "campbell-james",
    "CAMPBELL Jill": "campbell-jill",
    "CAMPBELL John Gounod": "campbell-john-gounod",
    "CAMPBELL Julie": "campbell-julie",
    "CAMPBELL Justine": "campbell-justine",
    "CAMPBELL Kane": "campbell-kane",
    "CAMPBELL Katie": "campbell-katie",
    "CAMPBELL Ken": "campbell-ken",
    "CAMPBELL Lorne": "campbell-lorne",
    "CAMPBELL Lucy": "campbell-lucy",
    "CAMPBELL M J P": "campbell-m-j-p",
    "CAMPBELL Malcolm": "campbell-malcolm",
    "CAMPBELL Marcus": "campbell-marcus",
    "CAMPBELL Maria": "campbell-maria",
    "CAMPBELL Marilyn": "campbell-marilyn",
    "CAMPBELL Marilyn Anne": "campbell-marilyn-anne",
    "CAMPBELL Marilyn R": "campbell-marilyn-r",
    "CAMPBELL Marion May": "campbell-marion-may",
    "CAMPBELL Mark": "campbell-mark",
    "CAMPBELL Maura": "campbell-maura",
    "CAMPBELL Michael": "campbell-michael",
    "CAMPBELL Michelle": "campbell-michelle",
    "CAMPBELL Molly": "campbell-molly",
    "CAMPBELL N U": "campbell-n-u",
    "CAMPBELL Naomi": "campbell-naomi",
    "CAMPBELL Neil": "campbell-neil",
    "CAMPBELL Nick": "campbell-nick",
    "CAMPBELL Noa": "campbell-noa",
    "CAMPBELL Norman": "campbell-norman",
    "CAMPBELL Paddy": "campbell-paddy",
    "CAMPBELL Paddy (1)": "campbell-paddy-1",
    "CAMPBELL Peter": "campbell-peter",
    "CAMPBELL Peter A": "campbell-peter-a",
    "CAMPBELL Rachell": "campbell-rachell",
    "CAMPBELL Ralph": "campbell-ralph",
    "CAMPBELL Ray": "campbell-ray",
    "CAMPBELL Raymond": "campbell-raymond",
    "CAMPBELL Rayna": "campbell-rayna",
    "CAMPBELL Richard": "campbell-richard",
    "CAMPBELL Roy": "campbell-roy",
    "CAMPBELL Ryan": "campbell-ryan",
    "CAMPBELL Scottie": "campbell-scottie",
    "CAMPBELL Siofra": "campbell-siofra",
    "CAMPBELL Stephen": "campbell-stephen",
    "CAMPBELL Taylor": "campbell-taylor",
    "CAMPBELL Thomas Michael": "campbell-thomas-michael",
    "CAMPBELL Topher": "campbell-topher",
    "CAMPBELL William": "campbell-william",
    "CAMPBELL William Olson": "campbell-william-olson",
    "CAMPBELL Yisrael": "campbell-yisrael",
    "CAMPBELL RATE Alison": "campbell-rate-alison",
    "CAMPBELL-LOWE Marilyn R": "campbell-lowe-marilyn-r",
    "CAMPBELL-MOORE Roy": "campbell-moore-roy",
    "CAMPBELL-TAYLOR Leigh": "campbell-taylor-leigh",
    "CAMPION Christopher John": "campion-christopher-john",
    "CAMPION Cyril": "campion-cyril",
    "CAMPION Decent": "campion-decent",
    "CAMPION Sean": "campion-sean",
    "CAMPION Terri": "campion-terri",
    "CAMPION Thomas": "campion-thomas",
    "CAMPION Toby": "campion-toby",
    "CAMPION Tom": "campion-tom",
    "CAMPISI Megan": "campisi-megan",
    "CAMPLING Matthew": "campling-matthew",
    "CAMPLING Peter": "campling-peter",
    "CAMPO Antoine": "campo-antoine",
    "CAMPONE Merv": "campone-merv",
    "CAMPOS Jess G": "campos-jess-g",
    "CAMPOS Pierre": "campos-pierre",
    "CAMPOS Robert": "campos-robert",
    "CAMPTON David": "campton-david",
    "CAMUNAS Natalie": "camunas-natalie",
    "CAMUS Albert": "camus-albert",
    "CANAC-MARQUIS Normand": "canac-marquis-normand",
    "CANADAY Darren": "canaday-darren",
    "CANADAY Tami": "canaday-tami",
    "CANADY Darren": "canady-darren",
    "CANAHAM Dan": "canaham-dan",
    "CANALE Marco": "canale-marco",
    "CANALE Patricia": "canale-patricia",
    "CANALE Ray": "canale-ray",
    "CANALES David": "canales-david",
    "CANALESE E": "canalese-e",
    "CANAS Tania": "canas-tania",
    "CANAVAN Adam": "canavan-adam",
    "CANAVAN Dermot": "canavan-dermot",
    "CANAVAN Kelly": "canavan-kelly",
    "CANBY Vincent": "canby-vincent",
    "CANCELINO Alan": "cancelino-alan",
    "CANCELMI Louis": "cancelmi-louis",
    "CANDARAS Pat": "candaras-pat",
    "CANDELA Peter": "candela-peter",
    "CANDIDO Romeo": "candido-romeo",
    "CANDIDO ": "candido",
    "CANE Daniel": "cane-daniel",
    "CANE William": "cane-william",
    "CANETTI Elias": "canetti-elias",
    "CANETTI Veza": "canetti-veza",
    "CANFIELD James Cougar": "canfield-james-cougar",
    "CANFORA Jack": "canfora-jack",
    "CANGIANO Sabina": "cangiano-sabina",
    "CANHAM Dan": "canham-dan",
    "CANINO Frank": "canino-frank",
    "CANIVET Don": "canivet-don",
    "CANN Nathan Scott": "cann-nathan-scott",
    "CANN Peter": "cann-peter",
    "CANN Rosemary": "cann-rosemary",
    "CANNADY Darren": "cannady-darren",
    "CANNADY J D": "cannady-j-d",
    "CANNAM Peggie": "cannam-peggie",
    "CANNAN Alyssa": "cannan-alyssa",
    "CANNAN Dennis": "cannan-dennis",
    "CANNING Bob": "canning-bob",
    "CANNING Charles": "canning-charles",
    "CANNING Robert": "canning-robert",
    "CANNON Alice M": "cannon-alice-m",
    "CANNON Andy": "cannon-andy",
    "CANNON Cairo": "cannon-cairo",
    "CANNON Chuck": "cannon-chuck",
    "CANNON Feidlim": "cannon-feidlim",
    "CANNON Glyn": "cannon-glyn",
    "CANNON Jason": "cannon-jason",
    "CANNON Rita": "cannon-rita",
    "CANNON Robert": "cannon-robert",
    "CANNON Sean": "cannon-sean",
    "CANNON Steve": "cannon-steve",
    "CANNY Nicholas": "canny-nicholas",
    "CANNY Steven": "canny-steven",
    "CANOLLE Jean": "canolle-jean",
    "CANOVA Pattie": "canova-pattie",
    "CANSLEY Charles": "cansley-charles",
    "CANT Peter": "cant-peter",
    "CANTAN Mark": "cantan-mark",
    "CANTARELLA Kathleen": "cantarella-kathleen",
    "CANTER Ethan": "canter-ethan",
    "CANTER Jon": "canter-jon",
    "CANTIR Ruxy": "cantir-ruxy",
    "CANTON Alice": "canton-alice",
    "CANTON Ashley": "canton-ashley",
    "CANTONE Mario": "cantone-mario",
    "CANTOR David": "cantor-david",
    "CANTOR Hal": "cantor-hal",
    "CANTOR Louis": "cantor-louis",
    "CANTOR Lucas": "cantor-lucas",
    "CANTOS Mari Falcone": "cantos-mari-falcone",
    "CANTRELL Catherine": "cantrell-catherine",
    "CANTRELL Chris": "cantrell-chris",
    "CANTRELL Kinsey Madison": "cantrell-kinsey-madison",
    "CANTRELL Ruth": "cantrell-ruth",
    "CANTRELL Tom": "cantrell-tom",
    "CANTRELLE Carla": "cantrelle-carla",
    "CANTU Joe Turner": "cantu-joe-turner",
    "CANTWELL Jean Barker": "cantwell-jean-barker",
    "CANTWELL Melissa": "cantwell-melissa",
    "CANTY-SAMUEL Laura": "canty-samuel-laura",
    "CAO Karmia Chan": "cao-karmia-chan",
    "CAPACITOR ": "capacitor",
    "CAP-A-PIE ": "cap-a-pie",
    "CAPATIDES Christina": "capatides-christina",
    "CAPE THEATRE ": "cape-theatre",
    "CAPECE Manuela": "capece-manuela",
    "CAPEK Josef": "capek-josef",
    "CAPEK Karel": "capek-karel",
    "CAPEL Sharon": "capel-sharon",
    "CAPELA Jose": "capela-jose",
    "CAPELL Iris": "capell-iris",
    "CAPELLARO Catherine": "capellaro-catherine",
    "CAPELLE Bart": "capelle-bart",
    "CAPEN Donald S": "capen-donald-s",
    "CAPERS Nancy": "capers-nancy",
    "CAPES Derrell": "capes-derrell",
    "CAPICE Philip": "capice-philip",
    "CAPLAN Ben": "caplan-ben",
    "CAPLAN Cathy": "caplan-cathy",
    "CAPLAN Paula J": "caplan-paula-j",
    "CAPLAN-LONNER Carole": "caplan-lonner-carole",
    "CAPLIN Elliot": "caplin-elliot",
    "CAPLOW Jane": "caplow-jane",
    "CAPO John": "capo-john",
    "CAPOBIANCO D Marc": "capobianco-d-marc",
    "CAPODICASA Matthew": "capodicasa-matthew",
    "CAPONE Joseph": "capone-joseph",
    "CAPORALE Anthony": "caporale-anthony",
    "CAPOTE Truman": "capote-truman",
    "CAPOTORTO Carl": "capotorto-carl",
    "CAPOTORTO Mia": "capotorto-mia",
    "CAPOZZI Joe": "capozzi-joe",
    "CAPPEL Allen": "cappel-allen",
    "CAPPELLETTI John": "cappelletti-john",
    "CAPPER Penny": "capper-penny",
    "CAPPIELLO Katie": "cappiello-katie",
    "CAPRA Natalia": "capra-natalia",
    "CAPSIS Paul": "capsis-paul",
    "CAPSON Louis": "capson-louis",
    "CAPTAIN PHANTOM ": "captain-phantom",
    "CAPUNAY Anna": "capunay-anna",
    "CAPURRO Scott": "capurro-scott",
    "CAPUTO James": "caputo-james",
    "CAPUTO Leslie": "caputo-leslie",
    "CAPUTTO James": "caputto-james",
    "CARABAJAL Ruben": "carabajal-ruben",
    "CARABALLO Sunilda": "caraballo-sunilda",
    "CARABATSOS Eugenie": "carabatsos-eugenie",
    "CARABELLI Angela": "carabelli-angela",
    "CARAGIALE Ion": "caragiale-ion",
    "CARAPETIS Elena": "carapetis-elena",
    "CARAVANA Carl": "caravana-carl",
    "CARBAJAL Gabriel": "carbajal-gabriel",
    "CARBAJAL Ruben": "carbajal-ruben",
    "CARBALLIDO Emilio": "carballido-emilio",
    "CARBERI Dani": "carberi-dani",
    "CARBIENER Sarah": "carbiener-sarah",
    "CARBIS Gaylene": "carbis-gaylene",
    "CARBONE Dan": "carbone-dan",
    "CARBONE Donna M": "carbone-donna-m",
    "CARBONNIER Henrik": "carbonnier-henrik",
    "CARBUNARIU Gianina": "carbunariu-gianina",
    "CARCAMO Jose Alfonso": "carcamo-jose-alfonso",
    "CARCUEVA Aura": "carcueva-aura",
    "CARD Emily Janice": "card-emily-janice",
    "CARD Orson Scott": "card-orson-scott",
    "CARDACI Edward": "cardaci-edward",
    "CARDARELLI Alyn": "cardarelli-alyn",
    "CARDAZONE Rob": "cardazone-rob",
    "CARDEN Chaille": "carden-chaille",
    "CARDENAS Gisela": "cardenas-gisela",
    "CARDENAS Juan": "cardenas-juan",
    "CARDEY Lucinda": "cardey-lucinda",
    "CARDIFF Andrew": "cardiff-andrew",
    "CARDIFF Janet": "cardiff-janet",
    "CARDINAL Vincent J": "cardinal-vincent-j",
    "CARDINALE Anthony": "cardinale-anthony",
    "CARDINALE Dawn": "cardinale-dawn",
    "CARDINI Leo": "cardini-leo",
    "CARDNO Leighton": "cardno-leighton",
    "CARDONA Ed": "cardona-ed",
    "CARDONA Paola": "cardona-paola",
    "CARDONA, JR Ed": "cardona-jr-ed",
    "CARDOSO Pedro": "cardoso-pedro",
    "CARDWELL Dan": "cardwell-dan",
    "CARDY Geraint": "cardy-geraint",
    "CAREFOOT Ernest": "carefoot-ernest",
    "CAREN Jonathan": "caren-jonathan",
    "CARETAKER MINISTRY ": "caretaker-ministry",
    "CARETTE Elsa": "carette-elsa",
    "CAREW Jan": "carew-jan",
    "CAREY Adam Michael": "carey-adam-michael",
    "CAREY Alison": "carey-alison",
    "CAREY Andrea Fine": "carey-andrea-fine",
    "CAREY David": "carey-david",
    "CAREY Edward": "carey-edward",
    "CAREY J J": "carey-j-j",
    "CAREY James": "carey-james",
    "CAREY Jess": "carey-jess",
    "CAREY Pauline": "carey-pauline",
    "CAREY Rachel Katz": "carey-rachel-katz",
    "CAREY Rosalie": "carey-rosalie",
    "CAREY Sue": "carey-sue",
    "CAREY Zack": "carey-zack",
    "CARGILL Patrick": "cargill-patrick",
    "CARGILL Sue": "cargill-sue",
    "CARIAGA Daniel": "cariaga-daniel",
    "CARIANI John": "cariani-john",
    "CARILLI Theresa": "carilli-theresa",
    "CARIN Victor": "carin-victor",
    "CARIS Rachel": "caris-rachel",
    "CARISTI Vincent": "caristi-vincent",
    "CARKEET David": "carkeet-david",
    "CARL David": "carl-david",
    "CARL Frederick Henry": "carl-frederick-henry",
    "CARLAND Brian": "carland-brian",
    "CARLE Cynthia": "carle-cynthia",
    "CARLE Susan": "carle-susan",
    "CARLEBACH Joshua": "carlebach-joshua",
    "CARLEBACH Neshama": "carlebach-neshama",
    "CARLESS Victoria": "carless-victoria",
    "CARLETON Don": "carleton-don",
    "CARLETON Michael": "carleton-michael",
    "CARLETON Stephen": "carleton-stephen",
    "CARLEY Dave": "carley-dave",
    "CARLEY Steve": "carley-steve",
    "CARLIN Alan": "carlin-alan",
    "CARLIN Aviva Jane": "carlin-aviva-jane",
    "CARLIN Ben": "carlin-ben",
    "CARLIN Matthew": "carlin-matthew",
    "CARLIN Nancy": "carlin-nancy",
    "CARLING P L": "carling-p-l",
    "CARLINI Nello": "carlini-nello",
    "CARLINO Lewis John": "carlino-lewis-john",
    "CARLISLE Barbara": "carlisle-barbara",
    "CARLISLE Craig": "carlisle-craig",
    "CARLISLE Graham": "carlisle-graham",
    "CARLO Michelle": "carlo-michelle",
    "CARLONE Peter": "carlone-peter",
    "CARLOS Laurie": "carlos-laurie",
    "CARLOS William": "carlos-william",
    "CARLOS BULOSAN THEATRE COLLECTIVE ": "carlos-bulosan-theatre-collective",
    "CARLOS UVIEDO Juan": "carlos-uviedo-juan",
    "CARLSEN Tim": "carlsen-tim",
    "CARLSON Christopher Carl": "carlson-christopher-carl",
    "CARLSON Clifford": "carlson-clifford",
    "CARLSON Emma": "carlson-emma",
    "CARLSON Harry G": "carlson-harry-g",
    "CARLSON Jason Douglas": "carlson-jason-douglas",
    "CARLSON Kristin L": "carlson-kristin-l",
    "CARLSON Leonore": "carlson-leonore",
    "CARLSON Marvin A": "carlson-marvin-a",
    "CARLSON Nils T": "carlson-nils-t",
    "CARLSON Roberta": "carlson-roberta",
    "CARLSON Tim": "carlson-tim",
    "CARLSON Vincent": "carlson-vincent",
    "CARLSON DANCE COMPANY ": "carlson-dance-company",
    "CARLSTROM Todd": "carlstrom-todd",
    "CARLTON Bob": "carlton-bob",
    "CARLTON Clark": "carlton-clark",
    "CARLTON Daniel": "carlton-daniel",
    "CARLTON John": "carlton-john",
    "CARLUCCIO Sandra": "carluccio-sandra",
    "CARLYON David": "carlyon-david",
    "CARMELO ": "carmelo",
    "CARMEN Gemma": "carmen-gemma",
    "CARMEN Seanan": "carmen-seanan",
    "CARMEY Blaized": "carmey-blaized",
    "CARMEY Razanne": "carmey-razanne",
    "CARMICHAEL Fred": "carmichael-fred",
    "CARMICHAEL Hayley": "carmichael-hayley",
    "CARMICHAEL Jamie": "carmichael-jamie",
    "CARMICHAEL Leslie": "carmichael-leslie",
    "CARMICHAEL Patrick": "carmichael-patrick",
    "CARMICHI Jimmy": "carmichi-jimmy",
    "CARMINES Al": "carmines-al",
    "CARMODY Isobelle": "carmody-isobelle",
    "CARMODY Jack": "carmody-jack",
    "CARMODY Michael": "carmody-michael",
    "CARMONA Ben-Hur": "carmona-ben-hur",
    "CARMONA Jessica": "carmona-jessica",
    "CARNE Kim": "carne-kim",
    "CARNEGIE John": "carnegie-john",
    "CARNELIA Craig": "carnelia-craig",
    "CARNELL Stephen": "carnell-stephen",
    "CARNER Sam": "carner-sam",
    "CARNERE Jean-Claude": "carnere-jean-claude",
    "CARNESKY Marisa": "carnesky-marisa",
    "CARNEY Abigail": "carney-abigail",
    "CARNEY David": "carney-david",
    "CARNEY Frank": "carney-frank",
    "CARNEY John": "carney-john",
    "CARNEY Kieran": "carney-kieran",
    "CARNEY Kim": "carney-kim",
    "CARNEY Ruth": "carney-ruth",
    "CARNEY Tim S": "carney-tim-s",
    "CARNICKE Sharon M": "carnicke-sharon-m",
    "CARNICKE Susan": "carnicke-susan",
    "CARNIL Pepe": "carnil-pepe",
    "CARNWATH Drew": "carnwath-drew",
    "CAROL Joyce": "carol-joyce",
    "CAROLAN Maryann": "carolan-maryann",
    "CAROLAN Stuart": "carolan-stuart",
    "CAROLE Joseph": "carole-joseph",
    "CAROLINO Rey": "carolino-rey",
    "CAROLYN Joyce": "carolyn-joyce",
    "CARON Amy": "caron-amy",
    "CARON Guy": "caron-guy",
    "CARON Jean-Francois": "caron-jean-francois",
    "CARON Pierre": "caron-pierre",
    "CAROSELLA John": "carosella-john",
    "CAROTHERS A J": "carothers-a-j",
    "CAROTHERS Rachel": "carothers-rachel",
    "CARP Larry": "carp-larry",
    "CARPENTER Adam": "carpenter-adam",
    "CARPENTER Bridget": "carpenter-bridget",
    "CARPENTER Carleton": "carpenter-carleton",
    "CARPENTER Carol": "carpenter-carol",
    "CARPENTER Deborah": "carpenter-deborah",
    "CARPENTER Frank": "carpenter-frank",
    "CARPENTER Gary": "carpenter-gary",
    "CARPENTER Henry": "carpenter-henry",
    "CARPENTER Hugh": "carpenter-hugh",
    "CARPENTER Humphrey": "carpenter-humphrey",
    "CARPENTER Jay Hall": "carpenter-jay-hall",
    "CARPENTER Jeffrey": "carpenter-jeffrey",
    "CARPENTER Joyce Frances": "carpenter-joyce-frances",
    "CARPENTER Kim": "carpenter-kim",
    "CARPENTER Lance Theo": "carpenter-lance-theo",
    "CARPENTER Larry": "carpenter-larry",
    "CARPENTER Lindsay Alaine": "carpenter-lindsay-alaine",
    "CARPENTER Maurice": "carpenter-maurice",
    "CARPENTER Paul": "carpenter-paul",
    "CARPENTIER Hortense": "carpentier-hortense",
    "CARPETBAG THEATRE ": "carpetbag-theatre",
    "CARPIO Sean": "carpio-sean",
    "CARR Alison": "carr-alison",
    "CARR Andrew": "carr-andrew",
    "CARR Barbara": "carr-barbara",
    "CARR Bret": "carr-bret",
    "CARR Camilla": "carr-camilla",
    "CARR Cathleen": "carr-cathleen",
    "CARR Dorothy": "carr-dorothy",
    "CARR Erin": "carr-erin",
    "CARR George R": "carr-george-r",
    "CARR Gregory S": "carr-gregory-s",
    "CARR Hugh": "carr-hugh",
    "CARR Jason": "carr-jason",
    "CARR Kevin": "carr-kevin",
    "CARR Laura Leigh": "carr-laura-leigh",
    "CARR Laurence": "carr-laurence",
    "CARR Liz": "carr-liz",
    "CARR Marcia": "carr-marcia",
    "CARR Marina": "carr-marina",
    "CARR Patrick": "carr-patrick",
    "CARR Paul Louis": "carr-paul-louis",
    "CARR Peter": "carr-peter",
    "CARR Selena": "carr-selena",
    "CARR Shane": "carr-shane",
    "CARR Simon": "carr-simon",
    "CARR Sue": "carr-sue",
    "CARR Tim": "carr-tim",
    "CARR Uriah": "carr-uriah",
    "CARRA Lawrence": "carra-lawrence",
    "CARRA Marguerita": "carra-marguerita",
    "CARRADINE Sarah": "carradine-sarah",
    "CARRAGHER Jamie Andrew": "carragher-jamie-andrew",
    "CARRANE Jim": "carrane-jim",
    "CARRARA Guy": "carrara-guy",
    "CARRARO Joseph J": "carraro-joseph-j",
    "CARRAS Mari": "carras-mari",
    "CARRAS Nicholas": "carras-nicholas",
    "CARRASCO Enrique R": "carrasco-enrique-r",
    "CARRASCO Valentina": "carrasco-valentina",
    "CARRAWAY Gregory Paul": "carraway-gregory-paul",
    "CARRE Francois": "carre-francois",
    "CARRENO Gloria": "carreno-gloria",
    "CARRERO Jaime": "carrero-jaime",
    "CARRIAGA Daniel": "carriaga-daniel",
    "CARRICK Joanne": "carrick-joanne",
    "CARRIER Constance": "carrier-constance",
    "CARRIERE Jean-Claude": "carriere-jean-claude",
    "CARRIGAN Robin": "carrigan-robin",
    "CARRILLO Jaime Robert": "carrillo-jaime-robert",
    "CARRILLO Nick": "carrillo-nick",
    "CARRINGTON Grant": "carrington-grant",
    "CARRINGTON Jessica B": "carrington-jessica-b",
    "CARRINGTON Johnny": "carrington-johnny",
    "CARRINGTON Leonora": "carrington-leonora",
    "CARRO Michael": "carro-michael",
    "CARROLL A P": "carroll-a-p",
    "CARROLL Alex": "carroll-alex",
    "CARROLL Andrew": "carroll-andrew",
    "CARROLL Brad": "carroll-brad",
    "CARROLL Carrisa": "carroll-carrisa",
    "CARROLL Chanel": "carroll-chanel",
    "CARROLL Claire": "carroll-claire",
    "CARROLL Conor": "carroll-conor",
    "CARROLL Daniel": "carroll-daniel",
    "CARROLL Dennis": "carroll-dennis",
    "CARROLL Don": "carroll-don",
    "CARROLL Donna Kwanza": "carroll-donna-kwanza",
    "CARROLL Earl": "carroll-earl",
    "CARROLL Eliot": "carroll-eliot",
    "CARROLL Elizabeth": "carroll-elizabeth",
    "CARROLL George": "carroll-george",
    "CARROLL Gerry": "carroll-gerry",
    "CARROLL Ian": "carroll-ian",
    "CARROLL Jack F": "carroll-jack-f",
    "CARROLL John R": "carroll-john-r",
    "CARROLL Jon": "carroll-jon",
    "CARROLL Kieran": "carroll-kieran",
    "CARROLL Leslie Sara": "carroll-leslie-sara",
    "CARROLL Louisa": "carroll-louisa",
    "CARROLL Madeleine": "carroll-madeleine",
    "CARROLL Mark": "carroll-mark",
    "CARROLL N M": "carroll-n-m",
    "CARROLL Niall": "carroll-niall",
    "CARROLL Pat": "carroll-pat",
    "CARROLL Paul Vincent": "carroll-paul-vincent",
    "CARROLL R F": "carroll-r-f",
    "CARROLL Robert": "carroll-robert",
    "CARROLL Sidney": "carroll-sidney",
    "CARROLL Tim": "carroll-tim",
    "CARROLL Vienna": "carroll-vienna",
    "CARROLL Vinnette": "carroll-vinnette",
    "CARROLL JR Bob": "carroll-jr-bob",
    "CARROLLE Jean": "carrolle-jean",
    "CARRUTH Gordon": "carruth-gordon",
    "CARRUTHERS George S": "carruthers-george-s",
    "CARRUTHERS Peter": "carruthers-peter",
    "CARSON Anne": "carson-anne",
    "CARSON Darrow": "carson-darrow",
    "CARSON Dwight": "carson-dwight",
    "CARSON Gerald": "carson-gerald",
    "CARSON Gerald (1)": "carson-gerald-1",
    "CARSON Jo": "carson-jo",
    "CARSON Laura": "carson-laura",
    "CARSON Linda A": "carson-linda-a",
    "CARSON Luke": "carson-luke",
    "CARSON Nicole Antonia": "carson-nicole-antonia",
    "CARSON Sorrel": "carson-sorrel",
    "CARSON Teresa": "carson-teresa",
    "CARSON Troy": "carson-troy",
    "CARSTENS John": "carstens-john",
    "CARSTENSEN Candy": "carstensen-candy",
    "CARSWELL Donald": "carswell-donald",
    "CARTE BLANCHE ": "carte-blanche",
    "CARTER Aaron": "carter-aaron",
    "CARTER Alden R": "carter-alden-r",
    "CARTER Andre Lewis": "carter-andre-lewis",
    "CARTER Andrea": "carter-andrea",
    "CARTER Angela": "carter-angela",
    "CARTER Anna Grace": "carter-anna-grace",
    "CARTER Anton": "carter-anton",
    "CARTER Arthur": "carter-arthur",
    "CARTER Arthur Phillip": "carter-arthur-phillip",
    "CARTER Beatrix": "carter-beatrix",
    "CARTER Ben": "carter-ben",
    "CARTER Bill Bailey": "carter-bill-bailey",
    "CARTER Christopher Michael": "carter-christopher-michael",
    "CARTER Conrad C": "carter-conrad-c",
    "CARTER Daniel": "carter-daniel",
    "CARTER David": "carter-david",
    "CARTER Dennis": "carter-dennis",
    "CARTER Desmond": "carter-desmond",
    "CARTER Don": "carter-don",
    "CARTER Erin": "carter-erin",
    "CARTER Franklin": "carter-franklin",
    "CARTER Gary": "carter-gary",
    "CARTER Greg": "carter-greg",
    "CARTER James": "carter-james",
    "CARTER James (1)": "carter-james-1",
    "CARTER Janine": "carter-janine",
    "CARTER Jeff": "carter-jeff",
    "CARTER Jo": "carter-jo",
    "CARTER John": "carter-john",
    "CARTER John D": "carter-john-d",
    "CARTER Josephine": "carter-josephine",
    "CARTER Kate": "carter-kate",
    "CARTER Katherine M": "carter-katherine-m",
    "CARTER Kevin": "carter-kevin",
    "CARTER Leighton": "carter-leighton",
    "CARTER Lonnie": "carter-lonnie",
    "CARTER Margaret": "carter-margaret",
    "CARTER Marla Agul": "carter-marla-agul",
    "CARTER Michelle": "carter-michelle",
    "CARTER Mike": "carter-mike",
    "CARTER Mike (1)": "carter-mike-1",
    "CARTER Nicholas": "carter-nicholas",
    "CARTER Pamela": "carter-pamela",
    "CARTER Patrick": "carter-patrick",
    "CARTER Paul": "carter-paul",
    "CARTER Paula": "carter-paula",
    "CARTER Rachel": "carter-rachel",
    "CARTER Randolph": "carter-randolph",
    "CARTER Richard": "carter-richard",
    "CARTER Robert": "carter-robert",
    "CARTER Ross": "carter-ross",
    "CARTER Ruth": "carter-ruth",
    "CARTER Scott": "carter-scott",
    "CARTER Simon": "carter-simon",
    "CARTER Sonya": "carter-sonya",
    "CARTER Steve": "carter-steve",
    "CARTER Theo": "carter-theo",
    "CARTER Will Michael": "carter-will-michael",
    "CARTER JR Thomas G": "carter-jr-thomas-g",
    "CARTERFIELD Carmen": "carterfield-carmen",
    "CARTER-STEPHENSON Christian": "carter-stephenson-christian",
    "CARTHEW Mark": "carthew-mark",
    "CARTHEW Peter": "carthew-peter",
    "CARTHEW Pier": "carthew-pier",
    "CARTIER Marie": "cartier-marie",
    "CARTLIDGE Katrin": "cartlidge-katrin",
    "CARTMEL Andrew": "cartmel-andrew",
    "CARTMELL Selina": "cartmell-selina",
    "CARTMILL Christopher": "cartmill-christopher",
    "CARTON Michael": "carton-michael",
    "CARTOON DE SALVO ": "cartoon-de-salvo",
    "CARTOON SARDINES ": "cartoon-sardines",
    "CARTWRIGHT Christopher": "cartwright-christopher",
    "CARTWRIGHT G": "cartwright-g",
    "CARTWRIGHT Jim": "cartwright-jim",
    "CARTWRIGHT Nancy": "cartwright-nancy",
    "CARTWRIGHT Nicolas": "cartwright-nicolas",
    "CARTWRIGHT Robert": "cartwright-robert",
    "CARTWRIGHT Serge": "cartwright-serge",
    "CARUANA Ed": "caruana-ed",
    "CARUSO Joseph George": "caruso-joseph-george",
    "CARUSO Vincent": "caruso-vincent",
    "CARVALHO Mike Francis": "carvalho-mike-francis",
    "CARVER Raymond": "carver-raymond",
    "CARVER Sidney": "carver-sidney",
    "CARVILLE Daragh": "carville-daragh",
    "CARY Falkland L": "cary-falkland-l",
    "CARY Jim": "cary-jim",
    "CARY Meghan": "cary-meghan",
    "CARY Morland": "cary-morland",
    "CARY Peter": "cary-peter",
    "CARY Robert": "cary-robert",
    "CASA Christina": "casa-christina",
    "CASA Vicky Araico": "casa-vicky-araico",
    "CASADEMONT Joan": "casademont-joan",
    "CASADO Denver": "casado-denver",
    "CASADOS Cyd": "casados-cyd",
    "CASADY Karen B": "casady-karen-b",
    "CASAGRANDE Enrico": "casagrande-enrico",
    "CASALE Mick": "casale-mick",
    "CASANO Michael A": "casano-michael-a",
    "CASANOVAS Jordi": "casanovas-jordi",
    "CASARINO Matt": "casarino-matt",
    "CASAS Charo Gonzalez": "casas-charo-gonzalez",
    "CASAS Joan": "casas-joan",
    "CASAS Jose": "casas-jose",
    "CASAS Vicky Araico": "casas-vicky-araico",
    "CASAULT Jean": "casault-jean",
    "CASAZZA Marco": "casazza-marco",
    "CASCIATO Cesare": "casciato-cesare",
    "CASDAGLI Penny": "casdagli-penny",
    "CASE Andrew": "case-andrew",
    "CASE Charles": "case-charles",
    "CASE Geoffrey": "case-geoffrey",
    "CASE Justin": "case-justin",
    "CASE Melanie": "case-melanie",
    "CASE Peter S": "case-peter-s",
    "CASE Stan": "case-stan",
    "CASE Sue-Ellen": "case-sue-ellen",
    "CASE, JR Delvyn C": "case-jr-delvyn-c",
    "CASEBOLT AND SMITH ": "casebolt-and-smith",
    "CASELLA Kirsten": "casella-kirsten",
    "CASELLA Martin": "casella-martin",
    "CASELLI Anthony": "caselli-anthony",
    "CASENAVE Jeannette H": "casenave-jeannette-h",
    "CASER Peter": "caser-peter",
    "CASERTANO Silvia": "casertano-silvia",
    "CASEY Anne-Marie": "casey-anne-marie",
    "CASEY Francis Michael": "casey-francis-michael",
    "CASEY Jace": "casey-jace",
    "CASEY Kevin": "casey-kevin",
    "CASEY Mary": "casey-mary",
    "CASEY Michael": "casey-michael",
    "CASEY Noah": "casey-noah",
    "CASEY Peter J": "casey-peter-j",
    "CASEY Ren": "casey-ren",
    "CASEY Rosemary": "casey-rosemary",
    "CASEY Rowen": "casey-rowen",
    "CASEY Shawna": "casey-shawna",
    "CASEY Steve": "casey-steve",
    "CASEY Warren": "casey-warren",
    "CASH Alice Katherine": "cash-alice-katherine",
    "CASH Aubrey": "cash-aubrey",
    "CASH Jonathan": "cash-jonathan",
    "CASH Lucy": "cash-lucy",
    "CASH Patrick": "cash-patrick",
    "CASHIN Carl": "cashin-carl",
    "CASHMAN Mary": "cashman-mary",
    "CASHMORE Bill": "cashmore-bill",
    "CASIANO Karina": "casiano-karina",
    "CASLER Lawrence": "casler-lawrence",
    "CASLING Tom": "casling-tom",
    "CASLON Denis H": "caslon-denis-h",
    "CASNER Howard W": "casner-howard-w",
    "CASONA Alejandro": "casona-alejandro",
    "CASPARY Alex": "caspary-alex",
    "CASPARY Vera": "caspary-vera",
    "CASPER Scott": "casper-scott",
    "CASPERS Jan": "caspers-jan",
    "CASPERSEN Dana": "caspersen-dana",
    "CASS Adam J A": "cass-adam-j-a",
    "CASSADY Keegan": "cassady-keegan",
    "CASSARO Nancy": "cassaro-nancy",
    "CASSAVAUGH Ryan": "cassavaugh-ryan",
    "CASSAVETTES John": "cassavettes-john",
    "CASSEDY Patrice": "cassedy-patrice",
    "CASSEL David": "cassel-david",
    "CASSENBAUM Nick": "cassenbaum-nick",
    "CASSI Maria": "cassi-maria",
    "CASSIDY Barbara": "cassidy-barbara",
    "CASSIDY David": "cassidy-david",
    "CASSIDY Howard": "cassidy-howard",
    "CASSIDY Mark": "cassidy-mark",
    "CASSIDY Mary Lou": "cassidy-mary-lou",
    "CASSIDY Nat": "cassidy-nat",
    "CASSIDY Nathan": "cassidy-nathan",
    "CASSIDY Sara": "cassidy-sara",
    "CASSIDY Sarah": "cassidy-sarah",
    "CASSIERS Guy": "cassiers-guy",
    "CASSIMALLY San": "cassimally-san",
    "CASSIMO Victoria": "cassimo-victoria",
    "CASSNBAUM Nick": "cassnbaum-nick",
    "CASSON Glynis": "casson-glynis",
    "CASSON John (1)": "casson-john-1",
    "CASSON John (2)": "casson-john-2",
    "CASSON Lionel": "casson-lionel",
    "CASSON Mark": "casson-mark",
    "CASSON Sue": "casson-sue",
    "CASSTEVENS Frances": "casstevens-frances",
    "CASSTEVENS William": "casstevens-william",
    "CAST OFFS YOUTH THEATRE GROUP ": "cast-offs-youth-theatre-group",
    "CAST, THE ": "cast-the",
    "CASTAGNA Felicity": "castagna-felicity",
    "CASTAGNI Aless": "castagni-aless",
    "CASTELL Rob": "castell-rob",
    "CASTELLANETA Dan": "castellaneta-dan",
    "CASTELLANI Catherine": "castellani-catherine",
    "CASTELLANO Anthony": "castellano-anthony",
    "CASTELLANO Debra": "castellano-debra",
    "CASTELLANOS Teo": "castellanos-teo",
    "CASTELLINO Bill": "castellino-bill",
    "CASTELLON Esmeralda": "castellon-esmeralda",
    "CASTELLUCCI Claudia": "castellucci-claudia",
    "CASTELLUCCI Romeo": "castellucci-romeo",
    "CASTER Todd": "caster-todd",
    "CASTIGLIA Carolyn": "castiglia-carolyn",
    "CASTIGLIONI Greg": "castiglioni-greg",
    "CASTILLO Liz Coronado": "castillo-liz-coronado",
    "CASTILLO Raul": "castillo-raul",
    "CASTILLO Sergio": "castillo-sergio",
    "CASTLE Charles": "castle-charles",
    "CASTLE Gene": "castle-gene",
    "CASTLE James": "castle-james",
    "CASTLE Marc": "castle-marc",
    "CASTLE Mark": "castle-mark",
    "CASTLE Nan": "castle-nan",
    "CASTLE Nikki": "castle-nikki",
    "CASTLE Richard": "castle-richard",
    "CASTLE Robert": "castle-robert",
    "CASTLEDINE Annie": "castledine-annie",
    "CASTLEMAN B J": "castleman-b-j",
    "CASTLEMAN Bud": "castleman-bud",
    "CASTLEMAN Margie": "castleman-margie",
    "CASTLEMILK YOUNG WOMEN WRITERS GROUP ": "castlemilk-young-women-writers-group",
    "CASTLES Paul Robert": "castles-paul-robert",
    "CASTRIQUE Sue": "castrique-sue",
    "CASTRO Christina Florencia": "castro-christina-florencia",
    "CASTRO David": "castro-david",
    "CASTRO Francisco": "castro-francisco",
    "CASTRO Juan": "castro-juan",
    "CASTRO Juan Antonio": "castro-juan-antonio",
    "CASTRO Solange": "castro-solange",
    "CASTRO-VARGAS Rosateresa": "castro-vargas-rosateresa",
    "CASWELL Chris": "caswell-chris",
    "CASWELL Troy": "caswell-troy",
    "CASWELL JR John": "caswell-john",
    "CASWELL-ROBINSON Amanda": "caswell-robinson-amanda",
    "CAT IN A CUP ": "cat-in-a-cup",
    "CATA Zolani": "cata-zolani",
    "CATALANO Elizabeth": "catalano-elizabeth",
    "CATALANO Jason": "catalano-jason",
    "CATALINA Cristina": "catalina-cristina",
    "CATALUNA Lee": "cataluna-lee",
    "CATANESE Ivana": "catanese-ivana",
    "CATANESE Jeff": "catanese-jeff",
    "CATAPULT THEATRE ": "catapult-theatre",
    "CATE Vanessa": "cate-vanessa",
    "CATE Virginia": "cate-virginia",
    "CATER Emma": "cater-emma",
    "CATESBY Deborah": "catesby-deborah",
    "CATESBY Robin": "catesby-robin",
    "CATHCART Sarah": "cathcart-sarah",
    "CATHEAD ": "cathead",
    "CATHERINE Lucy": "catherine-lucy",
    "CATHERINE WHEELS THEATRE CO ": "catherine-wheels-theatre-co",
    "CATHRO D C": "cathro-d-c",
    "CATLEDGE Jeremy": "catledge-jeremy",
    "CATLETT Mallory": "catlett-mallory",
    "CATLEY Mark": "catley-mark",
    "CATLIFF Louis": "catliff-louis",
    "CATLIN David": "catlin-david",
    "CATLIN Michael": "catlin-michael",
    "CATO Anders": "cato-anders",
    "CATO Christin": "cato-christin",
    "CATO Nancy": "cato-nancy",
    "CATON Matt": "caton-matt",
    "CATONA Brian": "catona-brian",
    "CATRACCHIA Roslyn": "catracchia-roslyn",
    "CATRINI Andre": "catrini-andre",
    "CATRON Louis E": "catron-louis-e",
    "CATTEANO Anne": "catteano-anne",
    "CATTELL Jo": "cattell-jo",
    "CATTELL Rohan": "cattell-rohan",
    "CATTERTON Jeremey": "catterton-jeremey",
    "CATTY Benet": "catty-benet",
    "CAUCCI Frank": "caucci-frank",
    "CAUDEVILLA Maria": "caudevilla-maria",
    "CAUDLE David": "caudle-david",
    "CAUGHEY Shona": "caughey-shona",
    "CAUGHT RED-HANDED ": "caught-red-handed",
    "CAULEY Harry": "cauley-harry",
    "CAULFIELD Annie": "caulfield-annie",
    "CAULFIELD Carl": "caulfield-carl",
    "CAULFIELD Dan": "caulfield-dan",
    "CAULLEY Darren": "caulley-darren",
    "CAUSEY Allan": "causey-allan",
    "CAUSLEY Charles": "causley-charles",
    "CAUTE David": "caute-david",
    "CAVALIERI Grace": "cavalieri-grace",
    "CAVALLARI Megan": "cavallari-megan",
    "CAVALLO Tony": "cavallo-tony",
    "CAVALLORO Daniela": "cavalloro-daniela",
    "CAVANAGH Alix": "cavanagh-alix",
    "CAVANAGH Dean": "cavanagh-dean",
    "CAVANAGH Maria": "cavanagh-maria",
    "CAVANAGH Sharon": "cavanagh-sharon",
    "CAVANAUGH Lauren M": "cavanaugh-lauren-m",
    "CAVANAUGH Tom": "cavanaugh-tom",
    "CAVANDER Kenneth": "cavander-kenneth",
    "CAVATINA ": "cavatina",
    "CAVAZOS Roberto": "cavazos-roberto",
    "CAVE Candida": "cave-candida",
    "CAVE Diane": "cave-diane",
    "CAVE Jo Blake": "cave-jo-blake",
    "CAVE Kathryn": "cave-kathryn",
    "CAVEDO Will": "cavedo-will",
    "CAVELLIER Lee": "cavellier-lee",
    "CAVEN Kristen": "caven-kristen",
    "CAVEN Michael": "caven-michael",
    "CAVENAUGH Lauren": "cavenaugh-lauren",
    "CAVENDER Kenneth": "cavender-kenneth",
    "CAVENDER Kevin": "cavender-kevin",
    "CAVENDIS Dominic": "cavendis-dominic",
    "CAVENDISH Clare": "cavendish-clare",
    "CAVENDISH Dominic": "cavendish-dominic",
    "CAVENDISH Nicola": "cavendish-nicola",
    "CAVENDISH Richard": "cavendish-richard",
    "CAVENY Leslie": "caveny-leslie",
    "CAVERNO Steve": "caverno-steve",
    "CAVILLE Daragh": "caville-daragh",
    "CAWKWELL Katy": "cawkwell-katy",
    "CAWLETI Dean T": "cawleti-dean-t",
    "CAWOOD Georgina": "cawood-georgina",
    "CAWOOD James": "cawood-james",
    "CAWS Brian": "caws-brian",
    "CAWS-ELWITT Jonathan": "caws-elwitt-jonathan",
    "CAYGILL Jovita": "caygill-jovita",
    "CAYLER Tom": "cayler-tom",
    "CAYLEY Jennifer": "cayley-jennifer",
    "CAYLEY Kate": "cayley-kate",
    "CAYONNE Johnny": "cayonne-johnny",
    "CAZARES Victor Ismael": "cazares-victor-ismael",
    "CAZORLA Hazel": "cazorla-hazel",
    "CEARLEY Edgar C": "cearley-edgar-c",
    "CEASE Howard": "cease-howard",
    "CEBALLOS Chris": "ceballos-chris",
    "CEBALLOS Oscar": "cebellos-oscar",
    "CEBULSKA Marcia": "cebulska-marcia",
    "CEC ": "cec",
    "CECCHI Valentina": "cecchi-valentina",
    "CECCHIN Kathleen": "cecchin-kathleen",
    "CECERA Rudy": "cecera-rudy",
    "CECIL Henry": "cecil-henry",
    "CECIL John": "cecil-john",
    "CECIL Kevin": "cecil-kevin",
    "CECILIA Karen": "cecilia-karen",
    "CECSARINI Lois": "cecsarini-lois",
    "CEDAR Paul": "cedar-paul",
    "CEDARS Stephen": "cedars-stephen",
    "CEDENO Daniel": "cedeno-daniel",
    "CEDERBERG Natasha L": "cederberg-natasha-l",
    "CEDILLO Joe Luis": "cedillo-joe-luis",
    "CEDNO Irma": "cedno-irma",
    "CEFALY Audrey": "cefaly-audrey",
    "CEJI Ron": "ceji-ron",
    "CELAN Kaca": "celan-kaca",
    "CELENZA James": "celenza-james",
    "CELESIA Cathy": "celesia-cathy",
    "CELESTE Michele": "celeste-michele",
    "CELSI T": "celsi-t",
    "CELT Odessa": "celt-odessa",
    "CENICEROZ Jonathan": "ceniceroz-jonathan",
    "CENNARD Branwen": "cennard-branwen",
    "CENSABELLA Laura Maria": "censabella-laura-maria",
    "CENTELLAS Jordi": "centellas-jordi",
    "CENTLIVRE Susannah": "centlivre-susannah",
    "CENTRE FOR PERFORMANCE RESEARCH ": "centre-for-performance-research",
    "CERASO Chris": "ceraso-chris",
    "CERCONE Janus": "cercone-janus",
    "CERDA David": "cerda-david",
    "CERENKO Ryan": "cerenko-ryan",
    "CERESA Cecilia": "ceresa-cecilia",
    "CERESOLI Cristian": "ceresoli-cristian",
    "CERICOLA Ralph": "cericola-ralph",
    "CERINI Angus": "cerini-angus",
    "CERIO Johnathan": "cerio-johnathan",
    "CERNOW Sean": "cernow-sean",
    "CERNY Duane Scott": "cerny-duane-scott",
    "CERNY Helena Weltman": "cerny-helena-weltman",
    "CERNY Pavel": "cerny-pavel",
    "CERRATO Anthony": "cerrato-anthony",
    "CERRELLA Ginny": "cerrella-ginny",
    "CERRONE John": "cerrone-john",
    "CERTAIN DARK THINGS THEATRE COMPANY ": "certain-dark-things-theatre-company",
    "CERULLO Jonathan Stuart": "cerullo-jonathan-stuart",
    "CERUZZI Frank": "ceruzzi-frank",
    "CERVANIA Mark": "cervania-mark",
    "CERVANTES Jesse": "cervantes-jesse",
    "CERVANTES Miguel": "cervantes-miguel",
    "CERVANTES Ray": "cervantes-ray",
    "CERVARICH Frank": "cervarich-frank",
    "CERVELLO Santo": "cervello-santo",
    "CERVERIS Michael": "cerveris-michael",
    "CERVERIS Todd": "cerveris-todd",
    "CERVINO Alvaro": "cervino-alvaro",
    "CERVO Gian Maria": "cervo-gian-maria",
    "CESAIRE Aime": "cesaire-aime",
    "CESAIRE Ina": "cesaire-ina",
    "CESARE Sal": "cesare-sal",
    "CESARI Elio": "cesari-elio",
    "CESARIO Don": "cesario-don",
    "CESCHI Valentina": "ceschi-valentina",
    "CESTARO Pete": "cestaro-pete",
    "CETINKAYA Tarkan": "cetinkaya-tarkan",
    "CEZEK Boris": "cezek-boris"
  }
};