export default {
  "metadata": {
    "results": 1061,
    "timeStamp": "2025-12-05T21:22:59.077Z",
    "url": "https://www.doollee.com/PlaywrightsC/C_playwrights_g-l.php"
  },
  "authors": {
    "CHABERSKI Chris": "chaberski-chris",
    "CHABERT Jean-Louis": "chabert-jean-louis",
    "CHABON Michael": "chabon-michael",
    "CHADBOURN Huw": "chadbourn-huw",
    "CHADHA Anjali Mya": "chadha-anjali-mya",
    "CHADHA Gurinder": "chadha-gurinder",
    "CHADSEY Gillian": "chadsey-gillian",
    "CHADWICK Goretti": "chadwick-goretti",
    "CHADWICK Graham": "chadwick-graham",
    "CHADWICK Helen": "chadwick-helen",
    "CHADWICK John": "chadwick-john",
    "CHADWICK Jon": "chadwick-jon",
    "CHADWICK Kate": "chadwick-kate",
    "CHADWICK Kefi": "chadwick-kefi",
    "CHADWICK Maureen": "chadwick-maureen",
    "CHADWICK Paul": "chadwick-paul",
    "CHADWICK Stephen": "chadwick-stephen",
    "CHADWICK William": "chadwick-william",
    "CHADWICKE Alice": "chadwicke-alice",
    "CHADWIN Nick": "chadwin-nick",
    "CHAE Esther K": "chae-esther-k",
    "CHAET Mark": "chaet-mark",
    "CHAFE Rick": "chafe-rick",
    "CHAFE Robert": "chafe-robert",
    "CHAFEE Claire": "chafee-claire",
    "CHAFER Joff": "chafer-joff",
    "CHAFFEE Matt": "chaffee-matt",
    "CHAFFER Don": "chaffer-don",
    "CHAG Niraj": "chag-niraj",
    "CHAGRIN Julian": "chagrin-julian",
    "CHAI Camyar": "chai-camyar",
    "CHAIKEN Stacie": "chaiken-stacie",
    "CHAIKIN Joseph": "chaikin-joseph",
    "CHAIS Pamela": "chais-pamela",
    "CHAISON Nicole": "chaison-nicole",
    "CHAIT Stuart": "chait-stuart",
    "CHAITIN Joy": "chaitin-joy",
    "CHAKA Ta": "chaka-ta",
    "CHAKRABARTI Lolita": "chakrabarti-lolita",
    "CHAKRABARTI Samrat": "chakrabarti-samrat",
    "CHALCROFT Sarah": "chalcroft-sarah",
    "CHALEM Denise": "chalem-denise",
    "CHALK Matty": "chalk-matty",
    "CHALLEN John": "challen-john",
    "CHALLENGER David": "challenger-david",
    "CHALLENGER Melanie": "challenger-melanie",
    "CHALLENOR W": "challenor-w",
    "CHALLIS Chris": "challis-chris",
    "CHALLIS John": "challis-john",
    "CHALLIS Roy C": "challis-roy-c",
    "CHALMERS Bryn": "chalmers-bryn",
    "CHALMERS Hannah": "chalmers-hannah",
    "CHALMERS James": "chalmers-james",
    "CHALMERS Jessica": "chalmers-jessica",
    "CHALMERS Tony": "chalmers-tony",
    "CHALUISAN Luis": "chaluisan-luis",
    "CHALY Peter": "chaly-peter",
    "CHAMBERLAIN Ann": "chamberlain-ann",
    "CHAMBERLAIN Anne": "chamberlain-anne",
    "CHAMBERLAIN Cathy": "chamberlain-cathy",
    "CHAMBERLAIN Garth": "chamberlain-garth",
    "CHAMBERLAIN Kat": "chamberlain-kat",
    "CHAMBERLAIN Marisha": "chamberlain-marisha",
    "CHAMBERLAIN Michael": "chamberlain-michael",
    "CHAMBERLAIN Ray": "chamberlain-ray",
    "CHAMBERLAIN Travis": "chamberlain-travis",
    "CHAMBERLAIN, JR Ralph": "chamberlain-jr-ralph",
    "CHAMBERLIN Lee": "chamberlin-lee",
    "CHAMBERLIN Pip": "chamberlin-pip",
    "CHAMBERLIN Susan West": "chamberlin-susan-west",
    "CHAMBERS Aidan": "chambers-aidan",
    "CHAMBERS Bruce": "chambers-bruce",
    "CHAMBERS Charlotte": "chambers-charlotte",
    "CHAMBERS Christine Jean": "chambers-christine-jean",
    "CHAMBERS Colin": "chambers-colin",
    "CHAMBERS Dan": "chambers-dan",
    "CHAMBERS David": "chambers-david",
    "CHAMBERS E Morris": "chambers-e-morris",
    "CHAMBERS Ernest": "chambers-ernest",
    "CHAMBERS Guy": "chambers-guy",
    "CHAMBERS Hal": "chambers-hal",
    "CHAMBERS Jane": "chambers-jane",
    "CHAMBERS Janys": "chambers-janys",
    "CHAMBERS John": "chambers-john",
    "CHAMBERS Josh": "chambers-josh",
    "CHAMBERS Kenneth": "chambers-kenneth",
    "CHAMBERS Linda": "chambers-linda",
    "CHAMBERS Miles": "chambers-miles",
    "CHAMBERS Nick": "chambers-nick",
    "CHAMBERS Ron": "chambers-ron",
    "CHAMBERS Steve": "chambers-steve",
    "CHAMBERS Wendy Mae": "chambers-wendy-mae",
    "CHAMBON Michael": "chambon-michael",
    "CHAMINADE Jacinta": "chaminade-jacinta",
    "CHAMPAGNE Dominic": "champagne-dominic",
    "CHAMPAGNE Lenora": "champagne-lenora",
    "CHAMPAGNE Michael": "champagne-michael",
    "CHAMPAGNE Susan": "champagne-susan",
    "CHAMPION Cyril": "champion-cyril",
    "CHAMPION Ron": "champion-ron",
    "CHAMPION Stephen": "champion-stephen",
    "CHAMPNESS Sam": "champness-sam",
    "CHAMPNEY Erik": "champney-erik",
    "CHAMY Constanza Hola": "chamy-constanza-hola",
    "CHAN Aliee": "chan-aliee",
    "CHAN Alvin": "chan-alvin",
    "CHAN Angela": "chan-angela",
    "CHAN Anthony": "chan-anthony",
    "CHAN Eugenie": "chan-eugenie",
    "CHAN Geoffrey": "chan-geoffrey",
    "CHAN J P": "chan-j-p",
    "CHAN Jasmine": "chan-jasmine",
    "CHAN Jeffrey": "chan-jeffrey",
    "CHAN Joanna": "chan-joanna",
    "CHAN Kai Tai": "chan-kai-tai",
    "CHAN Leilani": "chan-leilani",
    "CHAN Marjorie": "chan-marjorie",
    "CHAN Marty": "chan-marty",
    "CHAN Melissa": "chan-melissa",
    "CHAN Sammy": "chan-sammy",
    "CHANCE Jayne Newton": "chance-jayne-newton",
    "CHANCE Kelsie": "chance-kelsie",
    "CHANCE Rosemary": "chance-rosemary",
    "CHANCELLOR Robin": "chancellor-robin",
    "CHAND Paul": "chand-paul",
    "CHANDA Pearl": "chanda-pearl",
    "CHANDLER Chan": "chandler-chan",
    "CHANDLER Charlotte": "chandler-charlotte",
    "CHANDLER Erin": "chandler-erin",
    "CHANDLER Glenn": "chandler-glenn",
    "CHANDLER Katherine": "chandler-katherine",
    "CHANDLER Mark": "chandler-mark",
    "CHANDLER Neal": "chandler-neal",
    "CHANDLER Richard": "chandler-richard",
    "CHANDLER Sean": "chandler-sean",
    "CHANDRA Katrina": "chandra-katrina",
    "CHANDRA Pearl": "chandra-pearl",
    "CHANDRARATNA Nirmal": "chandraratna-nirmal",
    "CHANDRASEKHAR Anupama": "chandrasekhar-anupama",
    "CHANDWANEY Anita": "chandwaney-anita",
    "CHANEY Elizabeth": "chaney-elizabeth",
    "CHANG Dongshin": "chang-dongshin",
    "CHANG Du Yee": "chang-du-yee",
    "CHANG Iris": "chang-iris",
    "CHANG Jade": "chang-jade",
    "CHANG Richard": "chang-richard",
    "CHANG Tisa": "chang-tisa",
    "CHANGAR Murray Scott": "changar-murray-scott",
    "CHANGEINSPEAK ": "changeinspeak",
    "CHANNER Lisa": "channer-lisa",
    "CHANSE Sam": "chanse-sam",
    "CHANWAI-EARLE Lynda": "chanwai-earle-lynda",
    "CHANZIT Adam": "chanzit-adam",
    "CHAO Ray": "chao-ray",
    "CHAO Tom X": "chao-tom-x",
    "CHAO Vic Bonekrusher": "chao-vic-bonekrusher",
    "CHAO Zoe": "chao-zoe",
    "CHAOS Jacob": "chaos-jacob",
    "CHAPADJIEV Sabrina": "chapadjiev-sabrina",
    "CHAPADJIEV Sophia": "chapadjiev-sophia",
    "CHAPIN Anna Alice": "chapin-anna-alice",
    "CHAPIN Harry": "chapin-harry",
    "CHAPLAIN Hilary": "chaplain-hilary",
    "CHAPLER Harold J": "chapler-harold-j",
    "CHAPLIN Alison": "chaplin-alison",
    "CHAPLIN Angela": "chaplin-angela",
    "CHAPLIN Michael": "chaplin-michael",
    "CHAPLIN Patrice": "chaplin-patrice",
    "CHAPLIN Tom": "chaplin-tom",
    "CHAPLIN Victoria": "chaplin-victoria",
    "CHAPMAN Clair": "chapman-clair",
    "CHAPMAN Clay McLeod": "chapman-clay-mcleod",
    "CHAPMAN Con": "chapman-con",
    "CHAPMAN Cornelius": "chapman-cornelius",
    "CHAPMAN Cynthia": "chapman-cynthia",
    "CHAPMAN Dave": "chapman-dave",
    "CHAPMAN David": "chapman-david",
    "CHAPMAN Derek": "chapman-derek",
    "CHAPMAN Ed": "chapman-ed",
    "CHAPMAN George": "chapman-george",
    "CHAPMAN James": "chapman-james",
    "CHAPMAN John": "chapman-john",
    "CHAPMAN Jonathan": "chapman-jonathan",
    "CHAPMAN Kamarie": "chapman-kamarie",
    "CHAPMAN Ken": "chapman-ken",
    "CHAPMAN Kip": "chapman-kip",
    "CHAPMAN Linda S": "chapman-linda-s",
    "CHAPMAN Louise": "chapman-louise",
    "CHAPMAN Marshall": "chapman-marshall",
    "CHAPMAN Matt": "chapman-matt",
    "CHAPMAN Michael": "chapman-michael",
    "CHAPMAN Miles": "chapman-miles",
    "CHAPMAN Nathan": "chapman-nathan",
    "CHAPMAN R Jonathan": "chapman-r-jonathan",
    "CHAPMAN Robert": "chapman-robert",
    "CHAPMAN Robin": "chapman-robin",
    "CHAPMAN Sofia": "chapman-sofia",
    "CHAPMAN Tim": "chapman-tim",
    "CHAPMYN James": "chapmyn-james",
    "CHAPNICK Rachel": "chapnick-rachel",
    "CHAPPELL Chris": "chappell-chris",
    "CHAPPELL Crissa-Jean": "chappell-crissa-jean",
    "CHAPPELL Drew": "chappell-drew",
    "CHAPPELL Eric": "chappell-eric",
    "CHAPPELL Fred": "chappell-fred",
    "CHAPPELL Holly": "chappell-holly",
    "CHAPPELL In-Sook": "chappell-in-sook",
    "CHAPPELL L": "chappell-l",
    "CHAPPELL William": "chappell-william",
    "CHAPPLE Aliki": "chapple-aliki",
    "CHAPWELL Claire": "chapwell-claire",
    "CHARABANC ": "charabanc",
    "CHARBONNEAU J C": "charbonneau-j-c",
    "CHARING Phil": "charing-phil",
    "CHARLAND Ben": "charland-ben",
    "CHARLEBOIS Gaetan": "charlebois-gaetan",
    "CHARLES Ben": "charles-ben",
    "CHARLES Jason": "charles-jason",
    "CHARLES Joe": "charles-joe",
    "CHARLES Maggie": "charles-maggie",
    "CHARLES Martie": "charles-martie",
    "CHARLES Moie": "charles-moie",
    "CHARLES Monica": "charles-monica",
    "CHARLES Nancy Linehan": "charles-nancy-linehan",
    "CHARLES Norman": "charles-norman",
    "CHARLES Shaun": "charles-shaun",
    "CHARLES Vernon": "charles-vernon",
    "CHARLES-ROUSE Dominic": "charles-rouse-dominic",
    "CHARLESWORTH John": "charlesworth-john",
    "CHARLESWORTH Mike": "charlesworth-mike",
    "CHARLIP Samantha": "charlip-samantha",
    "CHARLOTTE Susan": "charlotte-susan",
    "CHARLOW Renee": "charlow-renee",
    "CHARLTON Emile": "charlton-emile",
    "CHARLTON James Martin": "charlton-james-martin",
    "CHARLTON Lois": "charlton-lois",
    "CHARLTON Margo": "charlton-margo",
    "CHARLTON Maureen": "charlton-maureen",
    "CHARLTON Paul": "charlton-paul",
    "CHARLTON Peter": "charlton-peter",
    "CHARLTON Royd": "charlton-royd",
    "CHARLTON Syd": "charlton-syd",
    "CHARLTON Verity": "charlton-verity",
    "CHARMAN Matt": "charman-matt",
    "CHARMS Daniel": "charms-daniel",
    "CHARNAS Fran": "charnas-fran",
    "CHARNEY Kuros": "charney-kuros",
    "CHARNEY Mark": "charney-mark",
    "CHARNIN Martin": "charnin-martin",
    "CHARNOCK Nigel": "charnock-nigel",
    "CHARTERIS Bob": "charteris-bob",
    "CHARTERIS Robyn": "charteris-robyn",
    "CHARTIER Michael": "chartier-michael",
    "CHARTKOFF Eli": "chartkoff-eli",
    "CHARTRAND Lina": "chartrand-lina",
    "CHARY EllaRose": "chary-ellarose",
    "CHASE Alec": "chase-alec",
    "CHASE David": "chase-david",
    "CHASE Jerry": "chase-jerry",
    "CHASE Leon": "chase-leon",
    "CHASE Mary": "chase-mary",
    "CHASE Olive": "chase-olive",
    "CHASE Sonora": "chase-sonora",
    "CHASLAND Jason": "chasland-jason",
    "CHASTAIN Nancy M": "chastain-nancy-m",
    "CHASTEN Gamal Abdel": "chasten-gamal-abdel",
    "CHASTON Colin": "chaston-colin",
    "CHATBURN Tom": "chatburn-tom",
    "CHATEAU Corinne": "chateau-corinne",
    "CHATER Andrew": "chater-andrew",
    "CHATER Joff": "chater-joff",
    "CHATER-ROBINSON Piers": "chater-robinson-piers",
    "CHATFIELD Gwendolen": "chatfield-gwendolen",
    "CHATFIELD Roy": "chatfield-roy",
    "CHATTEN Klaus": "chatten-klaus",
    "CHATTERJEE Debjani": "chatterjee-debjani",
    "CHATTERJEE Sourabh": "chatterjee-sourabh",
    "CHATTERJEE Sudipto": "chatterjee-sudipto",
    "CHATTERTON Anna": "chatterton-anna",
    "CHATTERTON John": "chatterton-john",
    "CHATTERTON Mark": "chatterton-mark",
    "CHAU Nora": "chau-nora",
    "CHAUDHARY Gurdip Kaur": "chaudhary-gurdip-kaur",
    "CHAUDRI Jabine": "chaudri-jabine",
    "CHAUDRY Hammaad": "chaudry-hammaad",
    "CHAUHAN Sharmila": "chauhan-sharmila",
    "CHAUNCEY Harrell Cordell": "chauncey-harrell-cordell",
    "CHAUNDY Suzanne": "chaundy-suzanne",
    "CHAURETTE Normand": "chaurette-normand",
    "CHAUVET Maurice": "chauvet-maurice",
    "CHAVES Richard": "chaves-richard",
    "CHAVKIN Rachel": "chavkin-rachel",
    "CHAWAGA Tim": "chawaga-tim",
    "CHAWLA Pooja": "chawla-pooja",
    "CHAWLA Sujit": "chawla-sujit",
    "CHAYEFSKY Helen": "chayefsky-helen",
    "CHAYEFSKY Paddy": "chayefsky-paddy",
    "CHAYES Jess": "chayes-jess",
    "CHAZIN Carol": "chazin-carol",
    "CHBOTSKY Stephen": "chbotsky-stephen",
    "CHEADLE Don": "cheadle-don",
    "CHEASTY James": "cheasty-james",
    "CHEATLE Callum": "cheatle-callum",
    "CHEATLE Syd": "cheatle-syd",
    "CHEATWOOD Vicki Caroline": "cheatwood-vicki-caroline",
    "CHEECHOO Shirley": "cheechoo-shirley",
    "CHEEK Hanna": "cheek-hanna",
    "CHEEK Justin": "cheek-justin",
    "CHEEK Timothy": "cheek-timothy",
    "CHEERYWILD ": "cheerywild",
    "CHEESEMAN Peter": "cheeseman-peter",
    "CHEESMAN Nick": "cheesman-nick",
    "CHEETHAM Deborah": "cheetham-deborah",
    "CHEETHAM Val": "cheetham-val",
    "CHEIFFET George": "cheiffet-george",
    "CHEIKEN Michael": "cheiken-michael",
    "CHEITEN Marvin": "cheiten-marvin",
    "CHEKHOV Anton": "chekhov-anton",
    "CHELL Kate": "chell-kate",
    "CHELTON Elaine": "chelton-elaine",
    "CHELU Chris": "chelu-chris",
    "CHELYABINSK Babii": "chelyabinsk-babii",
    "CHEMERS Michael M": "chemers-michael-m",
    "CHEN Anna": "chen-anna",
    "CHEN Christopher": "chen-christopher",
    "CHEN Dan": "chen-dan",
    "CHEN Huang": "chen-huang",
    "CHEN Joanna": "chen-joanna",
    "CHEN Kitty": "chen-kitty",
    "CHENAIL Chad": "chenail-chad",
    "CHENERY Julian": "chenery-julian",
    "CHENERY M": "chenery-m",
    "CHENG Andrea Apuy": "cheng-andrea-apuy",
    "CHENG Charlie": "cheng-charlie",
    "CHENG Kai": "cheng-kai",
    "CHENG Kipp Erante": "cheng-kipp-erante",
    "CHENG Lucky": "cheng-lucky",
    "CHENG Maria": "cheng-maria",
    "CHENG Vincent J": "cheng-vincent-j",
    "CHENG Wei Meng": "cheng-wei-meng",
    "CHENOWETH Brian": "chenoweth-brian",
    "CHENOWETH Doral": "chenoweth-doral",
    "CHENZIRA-PINNOCK Haj": "chenzira-pinnock-haj",
    "CHEONG-EUY Park": "cheong-euy-park",
    "CHEONG-LEEN Reggie": "cheong-leen-reggie",
    "CHEOROS David": "cheoros-david",
    "CHEPIGA Michael": "chepiga-michael",
    "CHEQUER Brad": "chequer-brad",
    "CHERBONNIER Philippe": "cherbonnier-philippe",
    "CHERCOVER Daniel J": "chercover-daniel-j",
    "CHEREAU Patrice": "chereau-patrice",
    "CHERI Angelica": "cheri-angelica",
    "CHERNEY Scott": "cherney-scott",
    "CHERNIAK Leah": "cherniak-leah",
    "CHERNIN Cayle": "chernin-cayle",
    "CHERNOFF Marvin": "chernoff-marvin",
    "CHERPAKOV Gary": "cherpakov-gary",
    "CHERRELL Gwen": "cherrell-gwen",
    "CHERRETT Don": "cherrett-don",
    "CHERRILL David": "cherrill-david",
    "CHERRINGTON John-Paul": "cherrington-john-paul",
    "CHERRY Christopher": "cherry-christopher",
    "CHERRY Paul": "cherry-paul",
    "CHERRY Shane": "cherry-shane",
    "CHERRY Sid": "cherry-sid",
    "CHERRY Simon": "cherry-simon",
    "CHERRY Steven": "cherry-steven",
    "CHERRY Wal": "cherry-wal",
    "CHERRYHOLMES H L": "cherryholmes-h-l",
    "CHERTOFF Arlene": "chertoff-arlene",
    "CHERVINSKY Alexander": "chervinsky-alexander",
    "CHERY-RAMIREZ Diana E": "chery-ramirez-diana-e",
    "CHESER Nancy Nachama": "cheser-nancy-nachama",
    "CHESHIRE Richard": "cheshire-richard",
    "CHESKY David": "chesky-david",
    "CHESLEY Robert": "chesley-robert",
    "CHESLIK-DEMAYER Steven": "cheslik-demayer-steven",
    "CHESMORE Matthew": "chesmore-matthew",
    "CHESNOFF Elia": "chesnoff-elia",
    "CHESSMAN Tony": "chessman-tony",
    "CHESTER Sharon": "chester-sharon",
    "CHESTERFIELD Alan": "chesterfield-alan",
    "CHETHAM-STRODE Warren": "chetham-strode-warren",
    "CHETKOVICH Kathryn": "chetkovich-kathryn",
    "CHETTY Nalini": "chetty-nalini",
    "CHETWYND Lionel": "chetwynd-lionel",
    "CHEUNG Cindy": "cheung-cindy",
    "CHEUNG Simon": "cheung-simon",
    "CHEVALIER Alexis": "chevalier-alexis",
    "CHEVALLIER Dominique": "chevallier-dominique",
    "CHEVANNES Amba": "chevannes-amba",
    "CHEVAT Richie": "chevat-richie",
    "CHEW Kevin": "chew-kevin",
    "CHI Jimmy": "chi-jimmy",
    "CHIA Juliet": "chia-juliet",
    "CHIA Quin": "chia-quin",
    "CHIANG Hope": "chiang-hope",
    "CHIANTA Paola": "chianta-paola",
    "CHIAPPONE Rebecca": "chiappone-rebecca",
    "CHIARAPA Martha": "chiarapa-martha",
    "CHIARAPA Richard": "chiarapa-richard",
    "CHIARELLA Denise": "chiarella-denise",
    "CHIARELLA Hugo": "chiarella-hugo",
    "CHIARELLI Charly": "chiarelli-charly",
    "CHIARELLI Luigi": "chiarelli-luigi",
    "CHIARENZA Marcello": "chiarenza-marcello",
    "CHIAS Edgar": "chias-edgar",
    "CHIASSON Gilles": "chiasson-gilles",
    "CHIASSON Hermenegilde": "chiasson-hermenegilde",
    "CHIBAS Marissa": "chibas-marissa",
    "CHIBNALL Chris": "chibnall-chris",
    "CHICHKANOVA Alexandra": "chichkanova-alexandra",
    "CHICKEN SHED TC ": "chicken-shed-tc",
    "CHICOREL Ralph": "chicorel-ralph",
    "CHICUREL Judy": "chicurel-judy",
    "CHIEFFET George L": "chieffet-george-l",
    "CHIEN Chong Tze": "chien-chong-tze",
    "CHIFFI Naomi": "chiffi-naomi",
    "CHIFUNYISE Stephen": "chifunyise-stephen",
    "CHIKURA Denton": "chikura-denton",
    "CHIKWAVA Brian": "chikwava-brian",
    "CHILALA Cheela F K": "chilala-cheela-f-k",
    "CHILD Ali": "child-ali",
    "CHILD Christine": "child-christine",
    "CHILD Drac": "child-drac",
    "CHILD Jamieson": "child-jamieson",
    "CHILD Tom": "child-tom",
    "CHILDERS Mark": "childers-mark",
    "CHILDERS Miranda": "childers-miranda",
    "CHILDRESS Alice": "childress-alice",
    "CHILDRESS Alvin": "childress-alvin",
    "CHILDS Emma": "childs-emma",
    "CHILDS Frances": "childs-frances",
    "CHILDS Greg": "childs-greg",
    "CHILDS James": "childs-james",
    "CHILDS Kirsten": "childs-kirsten",
    "CHILLERY Leah": "chillery-leah",
    "CHILTON Charles": "chilton-charles",
    "CHILVER Trevar Alan": "chilver-trevar-alan",
    "CHIM Jo": "chim-jo",
    "CHIMBAMUL ": "chimbamul",
    "CHIMONAS Dimitris": "chimonas-dimitris",
    "CHIMONIDES Jason": "chimonides-jason",
    "CHIN Cat": "chin-cat",
    "CHIN Curtis": "chin-curtis",
    "CHIN Frank": "chin-frank",
    "CHIN Grace": "chin-grace",
    "CHIN Jarrett": "chin-jarrett",
    "CHIN Justin": "chin-justin",
    "CHIN Staceyann": "chin-staceyann",
    "CHINA PLATE ": "china-plate",
    "CHING Carla": "ching-carla",
    "CHING Hi": "ching-hi",
    "CHING Lin-Ann": "ching-lin-ann",
    "CHINH Kim": "chinh-kim",
    "CHINMOY Sri": "chinmoy-sri",
    "CHINN Amy": "chinn-amy",
    "CHINN Dustin": "chinn-dustin",
    "CHINN Jimmie": "chinn-jimmie",
    "CHINN Justin": "chinn-justin",
    "CHINNA Steve": "chinna-steve",
    "CHIODO Tom": "chiodo-tom",
    "CHIPPENDALE Ian": "chippendale-ian",
    "CHISHOLM Alex": "chisholm-alex",
    "CHISHOLM Earle": "chisholm-earle",
    "CHISHOLM Edgar": "chisholm-edgar",
    "CHISHOLM Jimmy": "chisholm-jimmy",
    "CHISHOLM Mary-Colin": "chisholm-mary-colin",
    "CHISHOLM Tearrance": "chisholm-tearrance",
    "CHISLETT Anne": "chislett-anne",
    "CHISM Darby Wills": "chism-darby-wills",
    "CHISMAN Kate": "chisman-kate",
    "CHISNALL Edward H": "chisnall-edward-h",
    "CHISUM J": "chisum-j",
    "CHITTY Laura": "chitty-laura",
    "CHITTY Paula": "chitty-paula",
    "CHITWOOD Tad": "chitwood-tad",
    "CHIVERTON Barnaby": "chiverton-barnaby",
    "CHLAKI Ilja": "chlaki-ilja",
    "CHMELEWSKY Anne": "chmelewsky-anne",
    "CHMELKO Andy": "chmelko-andy",
    "CHMIEL Michael": "chmiel-michael",
    "CHO Aileen": "cho-aileen",
    "CHO Charlie": "cho-charlie",
    "CHO John": "cho-john",
    "CHO Julia": "cho-julia",
    "CHO Sarah": "cho-sarah",
    "CHO Vharlie": "cho-vharlie",
    "CHOAT Jonathan": "choat-jonathan",
    "CHOCHOLOUS Francisco": "chocholous-francisco",
    "CHOCRON Isaac": "chocron-isaac",
    "CHODES John": "chodes-john",
    "CHODOROV Edward": "chodorov-edward",
    "CHODOROV Jerome": "chodorov-jerome",
    "CHODOROV Rosemary": "chodorov-rosemary",
    "CHOEGYAL Tenzin": "choegyal-tenzin",
    "CHOHAN Satinder": "chohan-satinder",
    "CHOI Chul-Ki": "choi-chul-ki",
    "CHOI Ins": "choi-ins",
    "CHOINACKY Thomas": "choinacky-thomas",
    "CHOINIERE Olivier": "choiniere-olivier",
    "CHOLMONDELEYS AND FEATHERSTONEHAUGHS ": "cholmondeleys-featherstonehaughs",
    "CHONG Denise": "chong-denise",
    "CHONG Kevin": "chong-kevin",
    "CHONG Oliver": "chong-oliver",
    "CHONG Ping": "chong-ping",
    "CHOPEL Farid": "chopel-farid",
    "CHOPOURIAN Cassandra Victoria": "chopourian-cassandra-victoria",
    "CHORELL Walentin": "chorell-walentin",
    "CHORPENNING Charlotte B": "chorpenning-charlotte-b",
    "CHORUS Manipur": "chorus-manipur",
    "CHOU Jason": "chou-jason",
    "CHOU T C": "chou-t-c",
    "CHOUDHURY Naveen Bahar": "choudhury-naveen-bahar",
    "CHOULJENKO Tatiana": "chouljenko-tatiana",
    "CHOW Berton": "chow-berton",
    "CHOW Cara": "chow-cara",
    "CHOW Grace": "chow-grace",
    "CHOWDHARY Rishi": "chowdhary-rishi",
    "CHOWDHRY Maya": "chowdhry-maya",
    "CHOWDHURY Dipak": "chowdhury-dipak",
    "CHOWDHURY Misha": "chowdhury-misha",
    "CHOWN Patricia": "chown-patricia",
    "CHRAGER Lewis S": "chrager-lewis-s",
    "CHRETIEN Francesca": "chretien-francesca",
    "CHRISCOLI Emily": "chriscoli-emily",
    "CHRISLER Mark": "chrisler-mark",
    "CHRISTENBERRY Elizabeth": "christenberry-elizabeth",
    "CHRISTENFELD Seth": "christenfeld-seth",
    "CHRISTENSEN Nathan": "christensen-nathan",
    "CHRISTENSEN Peter": "christensen-peter",
    "CHRISTENSON David M": "christenson-david-m",
    "CHRISTENSON Jonathan": "christenson-jonathan",
    "CHRISTGAU Patricia Wilmot": "christgau-patricia-wilmot",
    "CHRISTIAN Beatrix": "christian-beatrix",
    "CHRISTIAN Claire": "christian-claire",
    "CHRISTIAN Heather": "christian-heather",
    "CHRISTIAN Jim": "christian-jim",
    "CHRISTIAN Mel": "christian-mel",
    "CHRISTIAN Peter A": "christian-peter-a",
    "CHRISTIAN Rod": "christian-rod",
    "CHRISTIAN Stephanie": "christian-stephanie",
    "CHRISTIANO Spencer": "christiano-spencer",
    "CHRISTIANSEN Arne": "christiansen-arne",
    "CHRISTIANSEN Debbie": "christiansen-debbie",
    "CHRISTIANSON Bob": "christianson-bob",
    "CHRISTIE Agatha": "christie-agatha",
    "CHRISTIE Campbell": "christie-campbell",
    "CHRISTIE Charmian": "christie-charmian",
    "CHRISTIE Craig": "christie-craig",
    "CHRISTIE Daniel": "christie-daniel",
    "CHRISTIE Dorothy": "christie-dorothy",
    "CHRISTIE Heather": "christie-heather",
    "CHRISTIE Joe": "christie-joe",
    "CHRISTIE Jon": "christie-jon",
    "CHRISTIE Veronique": "christie-veronique",
    "CHRISTIE William": "christie-william",
    "CHRISTNER David W": "christner-david-w",
    "CHRISTOFER Michael": "christofer-michael",
    "CHRISTOFI Alex": "christofi-alex",
    "CHRISTOFIS Christopher": "christofis-christopher",
    "CHRISTOPH Thom": "christoph-thom",
    "CHRISTOPHE Robert": "christophe-robert",
    "CHRISTOPHER Aaron": "christopher-aaron",
    "CHRISTOPHER David": "christopher-david",
    "CHRISTOPHER Don": "christopher-don",
    "CHRISTOPHER Frank": "christopher-frank",
    "CHRISTOPHER Greg": "christopher-greg",
    "CHRISTOPHER Hunter": "christopher-hunter",
    "CHRISTOPHER J Julian": "christopher-j-julian",
    "CHRISTOPHER James": "christopher-james",
    "CHRISTOPHER Jay": "christopher-jay",
    "CHRISTOPHER Karen": "christopher-karen",
    "CHRISTOPHER Morgan": "christopher-morgan",
    "CHRISTOPHER Nanci": "christopher-nanci",
    "CHRISTOPHER Samuel": "christopher-samuel",
    "CHRISTOPHER Tony": "christopher-tony",
    "CHRISTOPHER-DANIELS Alexa": "christopher-daniels-alexa",
    "CHRISTOPHERSON Jody": "christopherson-jody",
    "CHRISTOPHER-WOOD John": "christopher-wood-john",
    "CHRISTOU Georgia": "christou-georgia",
    "CHRISTOU Mirella": "christou-mirella",
    "CHRISTY Jacqueline": "christy-jacqueline",
    "CHRISTY James": "christy-james",
    "CHRITCHLEY D": "chritchley-d",
    "CHRONOWSKI Barbara": "chronowski-barbara",
    "CHU Andrew": "chu-andrew",
    "CHU Anh": "chu-anh",
    "CHUA Damon": "chua-damon",
    "CHUA Katherine": "chua-katherine",
    "CHUA Nora": "chua-nora",
    "CHUBB Justin": "chubb-justin",
    "CHUBB K Bailey": "chubb-k-bailey",
    "CHUBB Paul": "chubb-paul",
    "CHUDLEY Ron": "chudley-ron",
    "CHUKRAN Bobbi A": "chukran-bobbi-a",
    "CHUMA Yoshiko": "chuma-yoshiko",
    "CHUMBLEY Kenny": "chumbley-kenny",
    "CHUMLEY Daniel": "chumley-daniel",
    "CHUN Marc": "chun-marc",
    "CHUN Tom": "chun-tom",
    "CHUNG Chipo": "chung-chipo",
    "CHUNG Danielle": "chung-danielle",
    "CHUNG Kris": "chung-kris",
    "CHUNG Mia": "chung-mia",
    "CHUNG Philip W": "chung-philip-w",
    "CHUNG Robin Moyer": "chung-robin-moyer",
    "CHUPACK Cindy": "chupack-cindy",
    "CHURA Nathanael": "chura-nathanael",
    "CHURCH David": "church-david",
    "CHURCH Jeff": "church-jeff",
    "CHURCH Madeline": "church-madeline",
    "CHURCH Michael": "church-michael",
    "CHURCH Vernon": "church-vernon",
    "CHURCH Virginia": "church-virginia",
    "CHURCHETT Stephen": "churchett-stephen",
    "CHURCHILL Caryl": "churchill-caryl",
    "CHURCHILL Donald": "churchill-donald",
    "CHURCHILL Eton F": "churchill-eton-f",
    "CHURCHILL Myla": "churchill-myla",
    "CHURCHILL Patricia": "churchill-patricia",
    "CHURCHILL Polly": "churchill-polly",
    "CHURCHILL Sherry": "churchill-sherry",
    "CHURCHMAN Shawn": "churchman-shawn",
    "CHURILLA Jack A": "churilla-jack-a",
    "CHURLYAEVA Natalya": "churlyaeva-natalya",
    "CHURNEY Russell": "churney-russell",
    "CHURNIN Gavin": "churnin-gavin",
    "CHUTER Robert": "chuter-robert",
    "CHWAT Jaques": "chwat-jaques",
    "CHWENEYAGAE Presley": "chweneyagae-presley",
    "CHWILOWA Grupa": "chwilowa-grupa",
    "CHYE Kee Thuan": "chye-kee-thuan",
    "CIA LA INDUSTRIAL TEATRERA ": "cia-la-industrial-teatrera",
    "CIAMPI Maria": "ciampi-maria",
    "CIAN Annie": "cian-annie",
    "CIANNAVEI Andrea": "ciannavei-andrea",
    "CIAVARELLA Sam": "ciavarella-sam",
    "CICALA Teresa Anne": "cicala-teresa-anne",
    "CICCARELLO Alyssa": "ciccarello-alyssa",
    "CICCARONE Richard": "ciccarone-richard",
    "CICCHINI Emily Ball": "cicchini-emily-ball",
    "CICCOLINI John": "ciccolini-john",
    "CICCOTELLI Roberto F": "ciccotelli-roberto-f",
    "CICHOSZ Jedrzej": "cichosz-jedrzej",
    "CICVAK Martin": "cicvak-martin",
    "CIERI Dominique": "cieri-dominique",
    "CIESLAR Patrick": "cieslar-patrick",
    "CIESLINSKI John": "cieslinski-john",
    "CIESLINSKI Maureen": "cieslinski-maureen",
    "CIGALA Christina": "cigala-christina",
    "CIGAR Jonny": "cigar-jonny",
    "CIGLERIS Lena": "cigleris-lena",
    "CIGNAC Marie": "cignac-marie",
    "CIKANEK Ben": "cikanek-ben",
    "CILENTO Diane": "cilento-diane",
    "CILENTO Ruth": "cilento-ruth",
    "CILGWYN THEATRE COMPANY ": "cilgwyn-theatre-company",
    "CIMAROLLI Sydney": "cimarolli-sydney",
    "CIMINO Louis": "cimino-louis",
    "CINCONE / ROGANTE ": "cincone-rogante",
    "CINCOTTI Pia": "cincotti-pia",
    "CINK Lorraine": "cink-lorraine",
    "CINNAMON Mary": "cinnamon-mary",
    "CINO Maggie": "cino-maggie",
    "CINOMAN Susan": "cinoman-susan",
    "CINQUE Chris": "cinque-chris",
    "CINTRON Carol": "cintron-carol",
    "CINTRON Dave": "cintron-dave",
    "CIOFFI Gregory": "cioffi-gregory",
    "CION Raquel": "cion-raquel",
    "CIONEK Edmund": "cionek-edmund",
    "CIONGOLI-KOEPFINGER Coni": "ciongoli-koepfinger-coni",
    "CIPES Rick": "cipes-rick",
    "CIPRIAN G": "ciprian-g",
    "CIPRIANI Emily Hrivnak": "cipriani-emily-hrivnak",
    "CIPRIASO Celena": "cipriaso-celena",
    "CIRCO DIABOLO ": "circo-diabolo",
    "CIRCUS SPACE ": "circus-space",
    "CIRIGLIANO Rose": "cirigliano-rose",
    "CIRILLO Joe": "cirillo-joe",
    "CIRKUS CIRKOR ": "cirkus-cirkor",
    "CIRONE David": "cirone-david",
    "CIRONE Kevin": "cirone-kevin",
    "CIRQUE ALFRED ": "cirque-alfred",
    "CIRRONE Steve": "cirrone-steve",
    "CIRVES Brent": "cirves-brent",
    "CISCO Carlos": "cisco-carlos",
    "CISSEL Charles": "cissel-charles",
    "CISSNA William David": "cissna-william-david",
    "CISTONE Danny": "cistone-danny",
    "CITADEL ARTS GROUP ": "citadel-arts-group",
    "CITRON Alex": "citron-alex",
    "CITRON Jonathan R": "citron-jonathan-r",
    "CITRON Matt": "citron-matt",
    "CIUFO Paul": "ciufo-paul",
    "CIULEI Helga": "ciulei-helga",
    "CIVILIANS, THE ": "civilians-the",
    "CIVITELLO Nick": "civitello-nick",
    "CIXOUS Helene": "cixous-helene",
    "CIZMAR Paula": "cizmar-paula",
    "CL COLLECTIVE ": "cl-collective",
    "CLAASSEN Susan": "claassen-susan",
    "CLACHAN Liz": "clachan-liz",
    "CLACK Leslie": "clack-leslie",
    "CLAFF Rachel": "claff-rachel",
    "CLAFLIN John": "claflin-john",
    "CLAGUE Madeleine": "clague-madeleine",
    "CLAIR Katherine": "clair-katherine",
    "CLAIR Lisa": "clair-lisa",
    "CLAIRE Edie": "claire-edie",
    "CLAIRE Stephanie": "claire-stephanie",
    "CLAIRE-WALSH Chantelle": "claire-walsh-chantelle",
    "CLAMP Paula": "clamp-paula",
    "CLANCHY John": "clanchy-john",
    "CLANCY Dan": "clancy-dan",
    "CLANCY Hamilton": "clancy-hamilton",
    "CLANCY John": "clancy-john",
    "CLANCY Kevin": "clancy-kevin",
    "CLANCY Tara": "clancy-tara",
    "CLANCY Thomas": "clancy-thomas",
    "CLAPHAM Peter": "clapham-peter",
    "CLAPP Edward P": "clapp-edward-p",
    "CLAPP Patricia": "clapp-patricia",
    "CLAPSHAW Karel": "clapshaw-karel",
    "CLARDY Andrea Fleck": "clardy-andrea-fleck",
    "CLARE Ben": "clare-ben",
    "CLARE Maddalene": "clare-maddalene",
    "CLARE Preston": "clare-preston",
    "CLARK Adrienne": "clark-adrienne",
    "CLARK Aileen": "clark-aileen",
    "CLARK Alexander": "clark-alexander",
    "CLARK Alison": "clark-alison",
    "CLARK Anne Mclaren": "clark-anne-mclaren",
    "CLARK Anthony": "clark-anthony",
    "CLARK Austin": "clark-austin",
    "CLARK Barbara": "clark-barbara",
    "CLARK Barrett H": "clark-barrett-h",
    "CLARK Bethany": "clark-bethany",
    "CLARK Bev": "clark-bev",
    "CLARK Brian": "clark-brian",
    "CLARK Brianna Catherine": "clark-brianna-catherine",
    "CLARK Bronwyn": "clark-bronwyn",
    "CLARK Bruce": "clark-bruce",
    "CLARK Burgess": "clark-burgess",
    "CLARK Cameron": "clark-cameron",
    "CLARK China": "clark-china",
    "CLARK Colin": "clark-colin",
    "CLARK Craig J": "clark-craig-j",
    "CLARK Curt Dale": "clark-curt-dale",
    "CLARK Daniel Haben": "clark-daniel-haben",
    "CLARK Darren": "clark-darren",
    "CLARK Darryl": "clark-darryl",
    "CLARK Dave": "clark-dave",
    "CLARK Dave (2)": "clark-dave-2",
    "CLARK David": "clark-david",
    "CLARK Denise": "clark-denise",
    "CLARK Dorothy": "clark-dorothy",
    "CLARK Edward": "clark-edward",
    "CLARK Eli": "clark-eli",
    "CLARK Eliza": "clark-eliza",
    "CLARK Emily Kathleen": "clark-emily-kathleen",
    "CLARK Gary": "clark-gary",
    "CLARK George": "clark-george",
    "CLARK Georgia": "clark-georgia",
    "CLARK Gerardine": "clark-gerardine",
    "CLARK Guy": "clark-guy",
    "CLARK Gwyn": "clark-gwyn",
    "CLARK Helen Russell": "clark-helen-russell",
    "CLARK Jacqueline": "clark-jacqueline",
    "CLARK James Nisbet": "clark-james-nisbet",
    "CLARK Jaylene": "clark-jaylene",
    "CLARK Jeremy": "clark-jeremy",
    "CLARK Joan": "clark-joan",
    "CLARK Jocelyn": "clark-jocelyn",
    "CLARK John": "clark-john",
    "CLARK John Pepper": "clark-john-pepper",
    "CLARK Kathleen": "clark-kathleen",
    "CLARK Ken": "clark-ken",
    "CLARK Larkin": "clark-larkin",
    "CLARK Laura J": "clark-laura-j",
    "CLARK Laurence": "clark-laurence",
    "CLARK Leroy": "clark-leroy",
    "CLARK Lou": "clark-lou",
    "CLARK Margaret": "clark-margaret",
    "CLARK Marjorie RM": "clark-marjorie-rm",
    "CLARK Maurice": "clark-maurice",
    "CLARK Maximilian Avery": "clark-maximilian-avery",
    "CLARK Michael": "clark-michael",
    "CLARK Noel": "clark-noel",
    "CLARK Patricia": "clark-patricia",
    "CLARK Patrick Sean": "clark-patrick-sean",
    "CLARK Paul": "clark-paul",
    "CLARK Phil": "clark-phil",
    "CLARK Rodney": "clark-rodney",
    "CLARK Ron": "clark-ron",
    "CLARK Ros": "clark-ros",
    "CLARK Rosana": "clark-rosana",
    "CLARK Ross": "clark-ross",
    "CLARK Sadie": "clark-sadie",
    "CLARK Sally": "clark-sally",
    "CLARK Sharon": "clark-sharon",
    "CLARK Stanley": "clark-stanley",
    "CLARK Stephen": "clark-stephen",
    "CLARK Steve": "clark-steve",
    "CLARK Steve Michael": "clark-steve-michael",
    "CLARK Sue": "clark-sue",
    "CLARK Tena": "clark-tena",
    "CLARK Tom Edward": "clark-tom-edward",
    "CLARKE Alan": "clarke-alan",
    "CLARKE Anastasia": "clarke-anastasia",
    "CLARKE Andrew": "clarke-andrew",
    "CLARKE Andrew Joseph": "clarke-andrew-joseph",
    "CLARKE Angela": "clarke-angela",
    "CLARKE Austin": "clarke-austin",
    "CLARKE Austin (2)": "clarke-austin-2",
    "CLARKE Barbara": "clarke-barbara",
    "CLARKE Breena": "clarke-breena",
    "CLARKE Brian M": "clarke-brian-m",
    "CLARKE Catrin": "clarke-catrin",
    "CLARKE Cheril N": "clarke-cheril-n",
    "CLARKE Christopher": "clarke-christopher",
    "CLARKE David": "clarke-david",
    "CLARKE David Ulysses": "clarke-david-ulysses",
    "CLARKE Doreen": "clarke-doreen",
    "CLARKE Doug": "clarke-doug",
    "CLARKE George Elliott": "clarke-george-elliott",
    "CLARKE Gillian": "clarke-gillian",
    "CLARKE Jackie": "clarke-jackie",
    "CLARKE Janey": "clarke-janey",
    "CLARKE Jenny": "clarke-jenny",
    "CLARKE Joan": "clarke-joan",
    "CLARKE Jocelyn": "clarke-jocelyn",
    "CLARKE Jocelyn (1)": "clarke-jocelyn-1",
    "CLARKE John": "clarke-john",
    "CLARKE Jordan": "clarke-jordan",
    "CLARKE Keith": "clarke-keith",
    "CLARKE Kevin": "clarke-kevin",
    "CLARKE Les": "clarke-les",
    "CLARKE Lorin": "clarke-lorin",
    "CLARKE Malcolm": "clarke-malcolm",
    "CLARKE Marcus": "clarke-marcus",
    "CLARKE Margaret": "clarke-margaret",
    "CLARKE Martha": "clarke-martha",
    "CLARKE Mary Ruth": "clarke-mary-ruth",
    "CLARKE Maximillian Avery": "clarke-maximillian-avery",
    "CLARKE Mollie": "clarke-mollie",
    "CLARKE Morgan": "clarke-morgan",
    "CLARKE Nick": "clarke-nick",
    "CLARKE Noel": "clarke-noel",
    "CLARKE Paul": "clarke-paul",
    "CLARKE Rebecca": "clarke-rebecca",
    "CLARKE Roy": "clarke-roy",
    "CLARKE Sebastian": "clarke-sebastian",
    "CLARKE Stephen": "clarke-stephen",
    "CLARKE Steve": "clarke-steve",
    "CLARKE Stuart": "clarke-stuart",
    "CLARKE Tamsin": "clarke-tamsin",
    "CLARKE Terence": "clarke-terence",
    "CLARKE Tim": "clarke-tim",
    "CLARKE Toby": "clarke-toby",
    "CLARKE Tom": "clarke-tom",
    "CLARKE II Buriel": "clarke-ii-buriel",
    "CLARKIN Kate": "clarkin-kate",
    "CLARKSON Adrienne": "clarkson-adrienne",
    "CLARKSON Anna": "clarkson-anna",
    "CLARKSON Daniel": "clarkson-daniel",
    "CLARKSON Don": "clarkson-don",
    "CLARKSON Ellen": "clarkson-ellen",
    "CLARKSON Helena G": "clarkson-helena-g",
    "CLARKSON Jonathan": "clarkson-jonathan",
    "CLARKSON Michael": "clarkson-michael",
    "CLARKSON Michael Patrick": "clarkson-michael-patrick",
    "CLARKSON Paul": "clarkson-paul",
    "CLARKSON Stephen": "clarkson-stephen",
    "CLARKSON Tom": "clarkson-tom",
    "CLARON ": "claron",
    "CLARVOE Anthony": "clarvoe-anthony",
    "CLARY Beth": "clary-beth",
    "CLARY Craig": "clary-craig",
    "CLATE Marco Jo": "clate-marco-jo",
    "CLATWORTHY Alex": "clatworthy-alex",
    "CLAUDE Ben": "claude-ben",
    "CLAUDEL Christine": "claudel-christine",
    "CLAUDEL Paul": "claudel-paul",
    "CLAUGHTON John": "claughton-john",
    "CLAUS Cal": "claus-cal",
    "CLAUS Hugo": "claus-hugo",
    "CLAUS Nona": "claus-nona",
    "CLAUSE Hugo": "clause-hugo",
    "CLAUSEN Hans K": "clausen-hans-k",
    "CLAUSEN Matthew": "clausen-matthew",
    "CLAUSSEN Amy": "claussen-amy",
    "CLAVANE Anthony": "clavane-anthony",
    "CLAWSON Ben": "clawson-ben",
    "CLAY Atesis": "clay-atesis",
    "CLAY Burial": "clay-burial",
    "CLAY Carl": "clay-carl",
    "CLAY Cecil": "clay-cecil",
    "CLAY Cynthia Joyce": "clay-cynthia-joyce",
    "CLAY Diskin": "clay-diskin",
    "CLAY Elliot": "clay-elliot",
    "CLAY John": "clay-john",
    "CLAY Jonathan": "clay-jonathan",
    "CLAY Kyra Renee": "clay-kyra-renee",
    "CLAY M H": "clay-m-h",
    "CLAY Mel": "clay-mel",
    "CLAY Melissa": "clay-melissa",
    "CLAY Melvin": "clay-melvin",
    "CLAY N L": "clay-n-l",
    "CLAY Stanley Bennett": "clay-stanley-bennett",
    "CLAYDEN James": "clayden-james",
    "CLAYDEN-LEWIS Jordan": "clayden-lewis-jordan",
    "CLAYE Rachael": "claye-rachael",
    "CLAYTON Frederick": "clayton-frederick",
    "CLAYTON Nancy Gall": "clayton-nancy-gall",
    "CLAYTON Paul": "clayton-paul",
    "CLAYTON Sally Pomme": "clayton-sally-pomme",
    "CLAYTON Stanley": "clayton-stanley",
    "CLAYTON Syd": "clayton-syd",
    "CLAYTON Tony": "clayton-tony",
    "CLEAGE Pearl": "cleage-pearl",
    "CLEAN BREAK ": "clean-break",
    "CLEAR Tom": "clear-tom",
    "CLEARY Ann": "cleary-ann",
    "CLEARY Bryan": "cleary-bryan",
    "CLEARY Daniel": "cleary-daniel",
    "CLEARY Grace": "cleary-grace",
    "CLEARY Patrick": "cleary-patrick",
    "CLEARY Pippa": "cleary-pippa",
    "CLEARY Sophie": "cleary-sophie",
    "CLEAVER Benjamin": "cleaver-benjamin",
    "CLEAVER Matthew": "cleaver-matthew",
    "CLEBB Richard Claverhouse": "clebb-richard-claverhouse",
    "CLEBERG Steve": "cleberg-steve",
    "CLEESE John": "cleese-john",
    "CLEGG Katie": "clegg-katie",
    "CLEGHORN Genevive": "cleghorn-genevive",
    "CLELAND Jane K": "cleland-jane-k",
    "CLELAND Katherine": "cleland-katherine",
    "CLEMANN Attila": "clemann-attila",
    "CLEMENS Brian": "clemens-brian",
    "CLEMENT Carole": "clement-carole",
    "CLEMENT Dick": "clement-dick",
    "CLEMENTE Pia": "clemente-pia",
    "CLEMENTE Rosalba": "clemente-rosalba",
    "CLEMENTS Alexis": "clements-alexis",
    "CLEMENTS Carol": "clements-carol",
    "CLEMENTS Colin": "clements-colin",
    "CLEMENTS John": "clements-john",
    "CLEMENTS Marie H": "clements-marie-h",
    "CLEMENTS Mark": "clements-mark",
    "CLEMENTS Otis": "clements-otis",
    "CLEMENTS Pat": "clements-pat",
    "CLEMINSON Chelsey": "cleminson-chelsey",
    "CLENDINNING David": "clendinning-david",
    "CLEPPER Gina Marie": "clepper-gina-marie",
    "CLEPPER P M": "clepper-p-m",
    "CLERKE Rachael": "clerke-rachael",
    "CLERKIN Angela": "clerkin-angela",
    "CLERKIN Maire": "clerkin-maire",
    "CLEUGH Grae": "cleugh-grae",
    "CLEVEDON John": "clevedon-john",
    "CLEVELAND Charles": "cleveland-charles",
    "CLEVELAND Rick": "cleveland-rick",
    "CLEVEN Vivienne": "cleven-vivienne",
    "CLEVER PETER ": "clever-peter",
    "CLEVERLY Casey": "cleverly-casey",
    "CLEVILLE Joan": "cleville-joan",
    "CLEWLOW Carol": "clewlow-carol",
    "CLEWORTH Wayne": "cleworth-wayne",
    "CLEWS Alan": "clews-alan",
    "CLIBURN Dee": "cliburn-dee",
    "CLIFF Alan": "cliff-alan",
    "CLIFF Paul": "cliff-paul",
    "CLIFF Penny": "cliff-penny",
    "CLIFF R": "cliff-r",
    "CLIFF HANGER THEATRE COMPANY ": "cliff-hanger-theatre-company",
    "CLIFFORD Christen": "clifford-christen",
    "CLIFFORD Derek": "clifford-derek",
    "CLIFFORD Jo": "clifford-jo",
    "CLIFFORD John": "clifford-john",
    "CLIFFORD Keith": "clifford-keith",
    "CLIFFORD Mary": "clifford-mary",
    "CLIFFORD Paula": "clifford-paula",
    "CLIFFORD Sara": "clifford-sara",
    "CLIFFORD Sigerson": "clifford-sigerson",
    "CLIFTON Glenn": "clifton-glenn",
    "CLIFTON John": "clifton-john",
    "CLIFTON Michael": "clifton-michael",
    "CLILVERD Rob": "clilverd-rob",
    "CLIMIE David": "climie-david",
    "CLIMONS Artie": "climons-artie",
    "CLINE Heidi": "cline-heidi",
    "CLINE Jamie": "cline-jamie",
    "CLINE John": "cline-john",
    "CLINE Michael": "cline-michael",
    "CLINKMAN Dana": "clinkman-dana",
    "CLINTON Alistair": "clinton-alistair",
    "CLINTON Andrea": "clinton-andrea",
    "CLINTON Craig": "clinton-craig",
    "CLINTON Douglas": "clinton-douglas",
    "CLINTON Edward": "clinton-edward",
    "CLINTON George S": "clinton-george-s",
    "CLINTON Judith": "clinton-judith",
    "CLINTON Robert": "clinton-robert",
    "CLINTSMAN Troy": "clintsman-troy",
    "CLIVE John P": "clive-john-p",
    "CLIVE Lesley": "clive-lesley",
    "CLIVE Misha": "clive-misha",
    "CLIVE Rachel": "clive-rachel",
    "CLOD ENSEMBLE, THE ": "clod-ensemble-the",
    "CLOEMAN Bob": "cloeman-bob",
    "CLOETE Helene": "cloete-helene",
    "CLOETER Paul Daniel": "cloeter-paul-daniel",
    "CLOHESSY Denis": "clohessy-denis",
    "CLOONAN Therese": "cloonan-therese",
    "CLOQUEMIN Richard": "cloquemin-richard",
    "CLORAN Daryl": "cloran-daryl",
    "CLORK Harry": "clork-harry",
    "CLOS Thomas Edward": "clos-thomas-edward",
    "CLOSE Ajay": "close-ajay",
    "CLOSE Alan": "close-alan",
    "CLOSE Glenn": "close-glenn",
    "CLOSE Marvin": "close-marvin",
    "CLOSE Phil": "close-phil",
    "CLOSE Roy M": "close-roy-m",
    "CLOSSHEY Charleene": "closshey-charleene",
    "CLOUD Darrah": "cloud-darrah",
    "CLOUD Earl": "cloud-earl",
    "CLOUGH Ben Cato": "clough-ben-cato",
    "CLOUGH D G": "clough-d-g",
    "CLOUGH David": "clough-david",
    "CLOUGH Greta": "clough-greta",
    "CLOUGHLEY Micharne": "cloughley-micharne",
    "CLOUSTON Erlend": "clouston-erlend",
    "CLOUT THEATRE ": "clout-theatre",
    "CLOUTIER Fabien": "cloutier-fabien",
    "CLOUTIER Stefanie": "clouter-stefanie",
    "CLOVER Jack": "clover-jack",
    "CLOWDUS Brian": "clowdus-brian",
    "CLOWES St John L": "clowes-st-john-l",
    "CLOWNAGOGO ": "clownagogo",
    "CLOWNS ANONYMOUS ": "clowns-anonymous",
    "CLUA Guillem": "clua-guillem",
    "CLUBB Dare": "clubb-dare",
    "CLUCAS Daniel": "clucas-daniel",
    "CLUCAS Judith": "clucas-judith",
    "CLUCHEY Bob": "cluchey-bob",
    "CLUCHEY Rick": "cluchey-rick",
    "CLUE Tim": "clue-tim",
    "CLUFF Susan": "cluff-susan",
    "CLUGSTON Kathy": "clugston-kathy",
    "CLUGSTONE Jim": "clugstone-jim",
    "CLUM John": "clum-john",
    "CLUNE Jackie": "clune-jackie",
    "CLUNIE Gloria Bond": "clunie-gloria-bond",
    "CLUNIE Michelle": "clunie-michelle",
    "CLUSTER BOMB COLLECTIVE ": "cluster-bomb-collective",
    "CLUTTON James": "clutton-james",
    "CLYMAN Bob": "clyman-bob"
  }
};