export default {
  "metadata": {
    "results": 1677,
    "timeStamp": "2025-12-05T21:23:22.717Z",
    "url": "https://www.doollee.com/PlaywrightsC/C_playwrights_m-r.php"
  },
  "authors": {
    "COACHE Claire": "coache-claire",
    "COADY Brian": "coady-brian",
    "COAKLEY Jacob": "coakley-jacob",
    "COAKLEY Patriac": "coakley-patriac",
    "COAL ": "coal",
    "COAR Stephen": "coar-stephen",
    "COASE Hal": "coase-hal",
    "COASH Tom": "coash-tom",
    "COATES Aaron": "coates-aaron",
    "COATES Charlotte": "coates-charlotte",
    "COATES Irene": "coates-irene",
    "COATES John": "coates-john",
    "COATES Josh": "coates-josh",
    "COATES Norman": "coates-norman",
    "COATES Paul": "coates-paul",
    "COATES Rae": "coates-rae",
    "COATS Jacqueline": "coats-jacqueline",
    "COATS Josh": "coats-josh",
    "COBB Andy": "cobb-andy",
    "COBB Nicole Anderson": "cobb-nicole-anderson",
    "COBB William": "cobb-william",
    "COBEY Patricia": "cobey-patricia",
    "COBHAM P J": "cobham-p-j",
    "COBLE Eric": "coble-eric",
    "COBLE Tom": "coble-tom",
    "COBLEY Derek": "cobley-derek",
    "COBURN Ann": "coburn-ann",
    "COBURN Anthony": "coburn-anthony",
    "COBURN D L": "coburn-d-l",
    "COBURN Mickey": "coburn-mickey",
    "COBURN Veronica": "coburn-veronica",
    "COCA Jordi": "coca-jordi",
    "COCCA-LEFFLER Marryann": "cocca-leffler-marryann",
    "COCEK Christina": "cocek-christina",
    "COCHRAN Adam Westfall": "cochran-adam-westfall",
    "COCHRAN Betty": "cochran-betty",
    "COCHRAN Dave": "cochran-dave",
    "COCHRAN Josh": "cochran-josh",
    "COCHRAN Karina Eugenia": "cochran-karina-eugenia",
    "COCHRAN Kevin": "cochran-kevin",
    "COCHRANE Alan": "cochrane-alan",
    "COCHRANE Brendan": "cochrane-brendan",
    "COCHRANE Brian": "cochrane-brian",
    "COCHRANE Chris": "cochrane-chris",
    "COCHRANE David F": "cochrane-david-f",
    "COCHRANE Pierre": "cochrane-pierre",
    "COCKBURN Emma": "cockburn-emma",
    "COCKBURN Ruth E": "cockburn-ruth-e",
    "COCKBURN Tom": "cockburn-tom",
    "COCKE Pete": "cocke-pete",
    "COCKER W D": "cocker-w-d",
    "COCKERHAM James Vinson": "cockerham-james-vinson",
    "COCKETT Stephen": "cockett-stephen",
    "COCKEY Bernadine": "cockey-bernadine",
    "COCKING John": "cocking-john",
    "COCKRAM Jeremi": "cockram-jeremi",
    "COCKRAN Tony": "cockran-tony",
    "COCKROACH THEATRE ": "cockroach-theatre",
    "COCKS Harvey": "cocks-harvey",
    "COCKSHOTT David": "cockshott-david",
    "COCO Paula": "coco-paula",
    "COCONIS Sarah": "coconis-sarah",
    "COCTEAU Jean": "cocteau-jean",
    "COCULUZZI Chris": "coculuzzi-chris",
    "CODDEN Donny": "codden-donny",
    "CODLING Bess": "codling-bess",
    "CODRINGTON Lisa": "codrington-lisa",
    "CODY Gab": "cody-gab",
    "CODY Shawn": "cody-shawn",
    "COE David": "coe-david",
    "COE Duncan": "coe-duncan",
    "COE Jonathan": "coe-jonathan",
    "COE Justin": "coe-justin",
    "COE Peter": "coe-peter",
    "COE Richard": "coe-richard",
    "COE Robert": "coe-robert",
    "COEL Michaela": "coel-michaela",
    "COELHO Joseph": "coelho-joseph",
    "COELHO Rui Pina": "coelho-rui-pina",
    "COEN Dana": "coen-dana",
    "COEN Ethan": "coen-ethan",
    "COEN Joel": "coen-joel",
    "COEN Larry": "coen-larry",
    "COENEN Kristof": "coenen-kristof",
    "COETZEE Greig": "coetzee-greig",
    "COFFEE Bryan": "coffee-bryan",
    "COFFEY Bysshe": "coffey-bysshe",
    "COFFEY Denise": "coffey-denise",
    "COFFEY Heather": "coffey-heather",
    "COFFEY Lee": "coffey-lee",
    "COFFEY Mary": "coffey-mary",
    "COFFEY Michael": "coffey-michael",
    "COFFEY Tom": "coffey-tom",
    "COFFEY Vanessa": "coffey-vanessa",
    "COFFIN Gregg": "coffin-gregg",
    "COFFIN Justin D": "coffin-justin-d",
    "COFFMAN Steven": "coffman-steven",
    "COFTA Mark": "cofta-mark",
    "COGAN Elyse": "cogan-elyse",
    "COGAN Karen": "cogan-karen",
    "COGAN Priscilla": "cogan-priscilla",
    "COGAN Suzanne": "cogan-suzanne",
    "COGGINS Howard": "coggins-howard",
    "COGHILL Chris": "coghill-chris",
    "COGHILL Joy": "coghill-joy",
    "COGHILL Nevill": "coghill-nevill",
    "COGHLAN Alice": "coghlan-alice",
    "COGHLAN Lin": "coghlan-lin",
    "COGHLAN Nicholas": "coghlan-nicholas",
    "COGLAN Lin": "coglan-lin",
    "COGO-FAWCETT Robert": "cogo-fawcett-robert",
    "COHAGAN Carolyn": "cohagan-carolyn",
    "COHAN George M": "cohan-george-m",
    "COHEN Abbey": "cohen-abbey",
    "COHEN Abi": "cohen-abi",
    "COHEN Adam": "cohen-adam",
    "COHEN Adam Michael": "cohen-adam-michael",
    "COHEN Ailie": "cohen-ailie",
    "COHEN Alan": "cohen-alan",
    "COHEN Alice Eve": "cohen-alice-eve",
    "COHEN Allen": "cohen-allen",
    "COHEN Andi": "cohen-andi",
    "COHEN Arnold L": "cohen-arnold-l",
    "COHEN Bennett": "cohen-bennett",
    "COHEN Bern": "cohen-bern",
    "COHEN Bob": "cohen-bob",
    "COHEN Burton": "cohen-burton",
    "COHEN Cary": "cohen-cary",
    "COHEN Chelsea": "cohen-chelsea",
    "COHEN David": "cohen-david",
    "COHEN Deborah": "cohen-deborah",
    "COHEN Douglas J": "cohen-douglas-j",
    "COHEN Edward M": "cohen-edward-m",
    "COHEN Eldad": "cohen-eldad",
    "COHEN Eric M": "cohen-eric-m",
    "COHEN Eric R": "cohen-eric-r",
    "COHEN Frumi": "cohen-frumi",
    "COHEN Gary P": "cohen-gary-p",
    "COHEN Harold": "cohen-harold",
    "COHEN Ian": "cohen-ian",
    "COHEN Isobel": "cohen-isobel",
    "COHEN Jaffe": "cohen-jaffe",
    "COHEN Janet Langhart": "cohen-janet-langhart",
    "COHEN Jay": "cohen-jay",
    "COHEN Jeff": "cohen-jeff",
    "COHEN Jessica": "cohen-jessica",
    "COHEN Jim": "cohen-jim",
    "COHEN John Melville": "cohen-john-melville",
    "COHEN Jonas": "cohen-jonas",
    "COHEN Joshua H": "cohen-joshua-h",
    "COHEN Karen M": "cohen-karen-m",
    "COHEN Larry": "cohen-larry",
    "COHEN Lawrence D": "cohen-lawrence-d",
    "COHEN Leah": "cohen-leah",
    "COHEN Lee": "cohen-lee",
    "COHEN Leonard": "cohen-leonard",
    "COHEN Lisa-Catherine": "cohen-lisa-catherine",
    "COHEN Loraine": "cohen-loraine",
    "COHEN Lysbeth": "cohen-lysbeth",
    "COHEN Margery": "cohen-margery",
    "COHEN Mark Bentley": "cohen-mark-bentley",
    "COHEN Marvin": "cohen-marvin",
    "COHEN Marya": "cohen-marya",
    "COHEN Matthew Loren": "cohen-matthew-loren",
    "COHEN Megan": "cohen-megan",
    "COHEN Mercedes Frances": "cohen-mercedes-frances",
    "COHEN Michael J": "cohen-michael-j",
    "COHEN Mimi": "cohen-mimi",
    "COHEN Nancy": "cohen-nancy",
    "COHEN Norma": "cohen-norma",
    "COHEN Norman": "cohen-norman",
    "COHEN Paul": "cohen-paul",
    "COHEN Paul (1)": "cohen-paul-1",
    "COHEN Peter Zachary": "cohen-peter-zachary",
    "COHEN Peter-Adrian": "cohen-peter-adrian",
    "COHEN Priscila": "cohen-priscila",
    "COHEN R M": "cohen-r-m",
    "COHEN Randy": "cohen-randy",
    "COHEN Rebecca": "cohen-rebecca",
    "COHEN Rob": "cohen-rob",
    "COHEN Robert": "cohen-robert",
    "COHEN Robert (1)": "cohen-robert-1",
    "COHEN Robert (2)": "cohen-robert-2",
    "COHEN Robert S": "cohen-robert-s",
    "COHEN Robin M": "cohen-robin-m",
    "COHEN Ronald Jay": "cohen-ronald-jay",
    "COHEN Ronnie": "cohen-ronnie",
    "COHEN Sarah Blacher": "cohen-sarah-blacher",
    "COHEN Sharleen Cooper": "cohen-sharleen-cooper",
    "COHEN Sona Robbins": "cohen-sona-robbins",
    "COHEN Stephen": "cohen-stephen",
    "COHEN Trudi": "cohen-trudi",
    "COHEN Urton": "cohen-urton",
    "COHN James": "cohn-james",
    "COHN John": "cohn-john",
    "COHN Lauren": "cohn-lauren",
    "COHN Meryl": "cohn-meryl",
    "COHN Nik": "cohn-nik",
    "COHN Steven Mark": "cohn-steven-mark",
    "COKE Peter": "coke-peter",
    "COKER Antonia Kemi": "coker-antonia-kemi",
    "COKER Niyi": "coker-niyi",
    "COKER Turkar": "coker-turkar",
    "COLACO Maria": "colaco-maria",
    "COLAIZZO Paul Downs": "colaizzo-paul-downs",
    "COLBERG Andrew": "colberg-andrew",
    "COLBERT David Brian": "colbert-david-brian",
    "COLBO Torquil": "colbo-torquil",
    "COLBORNE Adam": "colborne-adam",
    "COLBORNE Jez": "colborne-jez",
    "COLBRON Grace Isabel": "colbron-grace-isabel",
    "COLBURN Randall": "colburn-randall",
    "COLBY Charles": "colby-charles",
    "COLBY Kelly": "colby-kelly",
    "COLBY Michael": "colby-michael",
    "COLBY Robert": "colby-robert",
    "COLDHAM Luke": "coldham-luke",
    "COLE Allen": "cole-allen",
    "COLE Barbara": "cole-barbara",
    "COLE Barrie": "cole-barrie",
    "COLE Bryan": "cole-bryan",
    "COLE Catherine": "cole-catherine",
    "COLE Christiana": "cole-christiana",
    "COLE Curtis": "cole-curtis",
    "COLE David S": "cole-david-s",
    "COLE Drey": "cole-drey",
    "COLE Eva": "cole-eva",
    "COLE Gerald": "cole-gerald",
    "COLE Giles": "cole-giles",
    "COLE Gregory": "cole-gregory",
    "COLE Honor B": "cole-honor-b",
    "COLE Jack": "cole-jack",
    "COLE Jeffrey": "cole-jeffrey",
    "COLE Jeremy": "cole-jeremy",
    "COLE Joshua": "cole-joshua",
    "COLE Joshua Bastian": "cole-joshua-bastian",
    "COLE Judith": "cole-judith",
    "COLE Kathleen": "cole-kathleen",
    "COLE Kay": "cole-kay",
    "COLE Keith R": "cole-keith-r",
    "COLE Kelly": "cole-kelly",
    "COLE Kezia": "cole-kezia",
    "COLE L E": "cole-l-e",
    "COLE Laine": "cole-laine",
    "COLE Lester": "cole-lester",
    "COLE Mark": "cole-mark",
    "COLE Melisa": "cole-melisa",
    "COLE Neil": "cole-neil",
    "COLE Paul": "cole-paul",
    "COLE Robert": "cole-robert",
    "COLE Robert (1)": "cole-robert-1",
    "COLE Ross": "cole-ross",
    "COLE Serenah": "cole-serenah",
    "COLE Shorelle": "cole-shorelle",
    "COLE Simon": "cole-simon",
    "COLE Stephen": "cole-stephen",
    "COLE Susan G": "cole-susan-g",
    "COLE Thomas D": "cole-thomas-d",
    "COLE Tom": "cole-tom",
    "COLE Trish": "cole-trish",
    "COLE William R": "cole-william-r",
    "COLEBROOK Vera": "colebrook-vera",
    "COLE-HOWARD Christian": "cole-howard-christian",
    "COLE-HUGHES Steve": "cole-hughes-steve",
    "COLEITE Aron Eli": "coleite-aron-eli",
    "COLEMAN Aaron": "coleman-aaron",
    "COLEMAN Annie R": "coleman-annie-r",
    "COLEMAN Bronwen": "coleman-bronwen",
    "COLEMAN Cy": "coleman-cy",
    "COLEMAN Dan": "coleman-dan",
    "COLEMAN Danielle": "coleman-danielle",
    "COLEMAN Delle": "coleman-delle",
    "COLEMAN Di": "coleman-di",
    "COLEMAN Eddie": "coleman-eddie",
    "COLEMAN Elizabeth": "coleman-elizabeth",
    "COLEMAN Fiz": "coleman-fiz",
    "COLEMAN James": "coleman-james",
    "COLEMAN Jon": "coleman-jon",
    "COLEMAN L Winifred": "coleman-l-winifred",
    "COLEMAN Landon": "coleman-landon",
    "COLEMAN Layne": "coleman-layne",
    "COLEMAN Lily Ann": "coleman-lily-ann",
    "COLEMAN Lonnie": "coleman-lonnie",
    "COLEMAN Lyn": "coleman-lyn",
    "COLEMAN Maggie": "coleman-maggie",
    "COLEMAN Martyn": "coleman-martyn",
    "COLEMAN Mike": "coleman-mike",
    "COLEMAN Nisha": "coleman-nisha",
    "COLEMAN Paul": "coleman-paul",
    "COLEMAN Ralf \"Meshack\"": "coleman-ralf",
    "COLEMAN Richard": "coleman-richard",
    "COLEMAN Slash": "coleman-slash",
    "COLEMAN Stephen": "coleman-stephen",
    "COLEMAN Warren": "coleman-warren-1",
    "COLEMAN William": "coleman-william",
    "COLEMAN William S E": "coleman-william-s-e",
    "COLEMAN X": "coleman-x",
    "COLEMAN Zane": "coleman-zane",
    "COLEMAN-BROWN Lisa": "coleman-brown-lisa",
    "COLERIDGE E P": "coleridge-e-p",
    "COLES Enid": "coles-enid",
    "COLES Helen": "coles-helen",
    "COLES Jane": "coles-jane",
    "COLES Jennie": "coles-jennie",
    "COLES Richard": "coles-richard",
    "COLES Robert": "coles-robert",
    "COLES Robert A": "coles-robert-a",
    "COLES Zaida": "coles-zaida",
    "COLETTE ": "colette",
    "COLETTI Stefanie R": "coletti-stefanie-r",
    "COLEY Josh": "coley-josh",
    "COLFELT Barry M": "colfelt-barry-m",
    "COLFER Eoin": "colfer-eoin",
    "COLFORD Wesley J": "colford-wesley-j",
    "COLFORD William E": "colford-william-e",
    "COLGLAZIER Phillip H": "colglazier-phillip-h",
    "COLIMON Magaly": "colimon-magaly",
    "COLIN Aubrey": "colin-aubrey",
    "COLIO Barbara": "colio-barbara",
    "COLIONOMOS Jean (Nuchtern)": "colionomos-jean",
    "COLKER Jerry": "colker-jerry",
    "COLLABORATION TOWN ": "collaboration-town",
    "COLLAPSABLE GIRAFFE ": "collapsable-giraffe",
    "COLLAPSING HORSE THEATRE COMPANY ": "collapsing-horse-theatre-company",
    "COLLECTIF IDIL! ELDI ": "collectif-idil-eldi",
    "COLLECTIVE AOC ": "collective-aoc",
    "COLLECTIVE ARTISTES ": "collective-artistes",
    "COLLECTIVE UNCONSCIOUS ": "collective-unconscious",
    "COLLEE John": "collee-john",
    "COLLENDER Martina": "collender-martina",
    "COLLERAN Jim": "colleran-jim",
    "COLLETT Nicholas": "collett-nicholas",
    "COLLETTE Paul": "collette-paul",
    "COLLEY David": "colley-david",
    "COLLEY Nat": "colley-nat",
    "COLLEY Peter": "colley-peter",
    "COLLEY Stephen": "colley-stephen",
    "COLLIE Kelsey E": "collie-kelsey-e",
    "COLLIE Natasha": "collie-natasha",
    "COLLIE Therese": "collie-therese",
    "COLLIER Aaron": "collier-aaron",
    "COLLIER Alexandra": "collier-alexandra",
    "COLLIER David": "collier-david",
    "COLLIER Euginia": "collier-euginia",
    "COLLIER F H": "collier-f-h",
    "COLLIER Hilary": "collier-hilary",
    "COLLIER Michael": "collier-michael",
    "COLLIER Samantha": "collier-samantha",
    "COLLIER Simon James": "collier-simon-james",
    "COLLIER Simone": "collier-simone",
    "COLLIER William": "collier-william",
    "COLLIN Len": "collin-len",
    "COLLIN Martin R": "collin-martin-r",
    "COLLIN Terri": "collin-terri",
    "COLLINGS Bill": "collings-bill",
    "COLLINGS John": "collings-john",
    "COLLINGS Paul": "collings-paul",
    "COLLINGWOOD Kate": "collingwood-kate",
    "COLLINS A": "collins-a",
    "COLLINS A M": "collins-a-m",
    "COLLINS Aletta": "collins-aletta",
    "COLLINS Barry": "collins-barry",
    "COLLINS Bernard": "collins-bernard",
    "COLLINS Carmen": "collins-carmen",
    "COLLINS Dale": "collins-dale",
    "COLLINS Dan": "collins-dan",
    "COLLINS Daniel": "collins-daniel",
    "COLLINS Dave": "collins-dave",
    "COLLINS David": "collins-david",
    "COLLINS F B": "collins-f-b",
    "COLLINS Fiona": "collins-fiona",
    "COLLINS Freda": "collins-freda",
    "COLLINS Gemma": "collins-gemma",
    "COLLINS Ginny": "collins-ginny",
    "COLLINS Gregor Grant": "collins-gregor-grant",
    "COLLINS Helen": "collins-helen",
    "COLLINS Jackie": "collins-jackie",
    "COLLINS Jo": "collins-jo",
    "COLLINS Judith Glass": "collins-judith-glass",
    "COLLINS Kathleen": "collins-kathleen",
    "COLLINS Ken A": "collins-ken-a",
    "COLLINS Kenneth Sean": "collins-kenneth-sean",
    "COLLINS Leslie": "collins-leslie",
    "COLLINS Louiza": "collins-louiza",
    "COLLINS Matt": "collins-matt",
    "COLLINS Michael": "collins-michael",
    "COLLINS Mika": "collins-mika",
    "COLLINS Mike": "collins-mike",
    "COLLINS Nigel": "collins-nigel",
    "COLLINS Peter": "collins-peter",
    "COLLINS Peter (1)": "collins-peter-1",
    "COLLINS Phil": "collins-phil",
    "COLLINS Ranell": "collins-ranell",
    "COLLINS Roger Lanzing": "collins-roger-lanzing",
    "COLLINS Sarah": "collins-sarah",
    "COLLINS Seamus": "collins-seamus",
    "COLLINS Tess": "collins-tess",
    "COLLINS Therese": "collins-therese",
    "COLLINS Tim": "collins-tim",
    "COLLINS Tricia": "collins-tricia",
    "COLLINS-MOORE Richard": "collins-moore-richard",
    "COLLINSON Alan S": "collinson-alan-s",
    "COLLINSON Ian": "collinson-ian",
    "COLLINSON Laurence": "collinson-laurence",
    "COLLINSON Tom": "collinson-tom",
    "COLLIS Archie W J": "collis-archie-w-j",
    "COLLIS John": "collis-john",
    "COLLIS Rose": "collis-rose",
    "COLLODI Carlo": "collodi-carlo",
    "COLLUM Ronald Benjamin": "collum-ronald-benjamin",
    "COLLUMBELL Chris": "collumbell-chris",
    "COLLYER Andy": "collyer-andy",
    "COLLYER Barry": "collyer-barry",
    "COLLYER David J": "collyer-david-j",
    "COLLYER Emilie": "collyer-emilie",
    "COLLYER Ysabel": "collyer-ysabel",
    "COLMAN Alyssa Biber": "colman-alyssa-biber",
    "COLMAN Gary": "colman-gary",
    "COLMAN George": "colman-george",
    "COLMAN Richard": "colman-richard",
    "COLMAN Xan": "colman-xan",
    "COLODNY Lester": "colodny-lester",
    "COLOGNA Allison": "cologna-ally",
    "COLOMINAS Jordi": "colominas-jordi",
    "COLON Kristiana": "colon-kristiana",
    "COLON Oscar A": "colon-oscar-a",
    "COLONOMOS Jean": "colonomos-jean",
    "COLON-ZAYAS Liza": "colon-zayas-liza",
    "COLORADO Elvira": "colorado-elvira",
    "COLORADO Hortensia": "colorado-hortensia",
    "COLQUHOUN C D": "colquhoun-c-d",
    "COLQUHOUN Hilary": "colquhoun-hilary",
    "COLSON David Cherrill": "colson-david-cherrill",
    "COLSON Janet": "colson-janet",
    "COLSON Nicola": "colson-nicola",
    "COLT Nick": "colt-nick",
    "COLTON John": "colton-john",
    "COLUBRIALE Greg": "colubriale-greg",
    "COLUMBIA ENCYCLOPEDIA ": "columbia-encyclopedia",
    "COLUMBUS Brian": "columbus-brian",
    "COLUMBUS Curt": "columbus-curt",
    "COLVILL Billy": "colvill-billy",
    "COLVILL Bobby": "colvill-bobby",
    "COLVIN Sarah": "colvin-sarah",
    "COLWELL Max": "colwell-max",
    "COLWELL Ryan": "colwell-ryan",
    "COLYER Howard": "colyer-howard",
    "COLYER Yvonne": "colyer-yvonne",
    "COMAN Sherry": "coman-sherry",
    "COMANS Susie": "comans-susie",
    "COMASIO Sandra": "comasio-sandra",
    "COMBE Peter": "combe-peter",
    "COMBES Anna": "combes-anna",
    "COMBES Jo": "combes-jo",
    "COMBINE, THE ": "combine-the",
    "COMBS Frederick": "combs-frederick",
    "COMBS Patrick": "combs-patrick",
    "COMDEN Betty": "comden-betty",
    "COME AS SOON AS YOU HEAR ": "come-as-soon-as-you-hear",
    "COMEAU Paul": "comeau-paul",
    "COMECON THEATRE ": "comecon-theatre",
    "COMEDY Lab": "comedy-lab",
    "COMEDY COMICS ": "comedy-comics",
    "COMEDY PRACTICE, THE ": "comedy-practice-the",
    "COMER Bruce": "comer-bruce",
    "COMER J Douglas": "comer-j-douglas",
    "COMERFORD Amanda Sage": "comerford-amanda-sage",
    "COMERFORD Henry": "comerford-henry",
    "COMFORT Gardiner": "comfort-gardiner",
    "COMFORT Jane": "comfort-jane",
    "COMISAR Emily": "comisar-emily",
    "COMLISH Michael": "comlish-michael",
    "COMMANDER Cat": "commander-cat",
    "COMMANDER David": "commander-david",
    "COMMANDER Imogen": "commander-imogen",
    "COMMAROTO Jeffrey": "commaroto-jeffrey",
    "COMMIRE Anne": "commire-anne",
    "COMMON Ron": "common-ron",
    "COMMON WEALTH ": "common-wealth",
    "COMMOTION ": "commotion",
    "COMMUNICADO THEATRE COMPANY ": "communicado-theatre-company",
    "COMPAGNIA TPO ": "compagnia-tpo",
    "COMPAGNIE La": "compagnie-la",
    "COMPAGNIE RHAPSODIE ": "compagnie-rhapsodie",
    "COMPANY F Z ": "company-f-z",
    "COMPANY OF CLERKS ": "company-of-clerks",
    "COMPANY OF CREATIVE ARTISTS ": "company-of-creative-artists",
    "COMPANY OF STRANGERS ": "company-of-strangers",
    "COMPANY THEATRE OF MUMBAI ": "company-theatre-of-mumbai",
    "COMPANY, THE ": "company-the",
    "COMPORT Brian": "comport-brian",
    "COMPTON Ben": "compton-ben",
    "COMPTON Christopher Lord": "compton-christopher-lord",
    "COMPTON Guy": "compton-guy",
    "COMPTON James": "compton-james",
    "COMPTON Jennifer": "compton-jennifer",
    "COMPTON Jethro": "compton-jethro",
    "COMPTON Rick": "compton-rick",
    "COMPTON JR Jimmie Davis": "compton-jr-jimmie-davis",
    "COMSTOCK Howard Warren": "comstock-howard-warren",
    "COMSTOCK-HEITZMAN Jennilyn Marie": "comstock-heitzman-jennilyn-marie",
    "COMTOIS James": "comtois-james",
    "CONACHER Desmond J": "conacher-desmond-j",
    "CONAGLEN Katrina": "conaglen-katrina",
    "CONAN DOYLE Arthur": "conan-doyle-arthur",
    "CONANT Ailin": "conant-ailin",
    "CONBERE Emily": "conbere-emily",
    "CONCANNON Amy": "concannon-amy",
    "CONCEISON Claire": "conceison-claire",
    "CONCKLIN Eric": "concklin-eric",
    "CONCRETE GENERATION ": "concrete-generation",
    "CONDE Alix Elizabeth": "conde-alix-elizabeth",
    "CONDE Maryse": "conde-maryse",
    "CONDELL Pat": "condell-pat",
    "CONDIT Megan": "condit-megan",
    "CONDO Rose": "condo-rose",
    "CONDON Bill": "condon-bill",
    "CONDON Frank": "condon-frank",
    "CONDON Janie": "condon-janie",
    "CONDON Maureen": "condon-maureen",
    "CONDON Thomas J": "condon-thomas-j",
    "CONDREN Conal": "condren-conal",
    "CONDREN Dustin": "condren-dustin",
    "CONDY Caitlin": "condy-caitlin",
    "CONE Jeremy": "cone-jeremy",
    "CONE Tamara": "cone-tamara",
    "CONE Tom": "cone-tom",
    "CONEJERO Alberto": "conejero-alberto",
    "CONEY ": "coney",
    "CONEYBEARE Wilson": "coneybeare-wilson",
    "CONFLICT RELIEF ": "conflict-relief",
    "CONFORD Ros": "conford-ros",
    "CONFORTES Claude": "confortes-claude",
    "CONFORTI John": "conforti-john",
    "CONFOY Quincy": "confoy-quincy",
    "CONGDON Constance S": "congdon-constance-s",
    "CONGDON Kirby": "congdon-kirby",
    "CONGER Eric": "conger-eric",
    "CONGRESS Julie": "congress-julie",
    "CONGRESS Sarah": "congress-sarah",
    "CONIGRAVE Tim": "conigrave-tim",
    "CONISBEE Giles": "conisbee-giles",
    "CONISON David": "conison-david",
    "CONKEL Joshua": "conkel-joshua",
    "CONKLE E P": "conkle-e-p",
    "CONKLIN Bill": "conklin-bill",
    "CONKLIN John": "conklin-john",
    "CONKLIN Tom": "conklin-tom",
    "CONKLING Louise": "conkling-louise",
    "CONLEY Brian": "conley-brian",
    "CONLEY Christine": "conley-christine",
    "CONLEY Cory": "conley-cory",
    "CONLEY John J": "conley-john-j",
    "CONLEY Madeline": "conley-madeline",
    "CONLEY Michael": "conley-michael",
    "CONLEY Miyoko R": "conley-miyoko-r",
    "CONLEY P C": "conley-p-c",
    "CONLEY Willy": "conley-willy",
    "CONLIN Franny": "conlin-franny",
    "CONLON Anne": "conlon-anne",
    "CONLON Lucille": "conlon-lucille",
    "CONLON Richard": "conlon-richard",
    "CONLON Richard Lyons": "conlon-richard-lyons",
    "CONN Marjorie": "conn-marjorie",
    "CONN Stewart": "conn-stewart",
    "CONN Suzy": "conn-suzy",
    "CONNATS ": "connats",
    "CONNAUGHTON Shane": "connaughton-shane",
    "CONNELL Jenny": "connell-jenny",
    "CONNELL Josh": "connell-josh",
    "CONNELL Kevin": "connell-kevin",
    "CONNELL Pat": "connell-pat",
    "CONNELL Steve": "connell-steve",
    "CONNELLY Brendan": "connelly-brendan",
    "CONNELLY Carolyn": "connelly-carolyn",
    "CONNELLY Joe": "connelly-joe",
    "CONNELLY Marc": "connelly-marc",
    "CONNELLY Patricia": "connelly-patricia",
    "CONNELLY Wes": "connelly-wes",
    "CONNER Matt": "conner-matt",
    "CONNER Todd": "conner-todd",
    "CONNICK JR Harry": "connick-jr-harry",
    "CONNIFFE Michael": "conniffe-michael",
    "CONNINGTON Bill": "connington-bill",
    "CONNOLLEY Bill": "connolley-bill",
    "CONNOLLY Cyril": "connolly-cyril",
    "CONNOLLY Donald A": "connolly-donald-a",
    "CONNOLLY Eileen": "connolly-eileen",
    "CONNOLLY H": "connolly-h",
    "CONNOLLY Janice": "connolly-janice",
    "CONNOLLY John": "connolly-john",
    "CONNOLLY John Austin": "connolly-john-austin",
    "CONNOLLY Joseph F": "connolly-joseph-f",
    "CONNOLLY Katherine": "connolly-katherine",
    "CONNOLLY Margot": "connolly-margot",
    "CONNOLLY Maria": "connolly-maria",
    "CONNOLLY Maureen A": "connolly-maureen-a",
    "CONNOLLY Will": "connolly-will",
    "CONNOR Amy": "connor-amy",
    "CONNOR Andrew": "connor-andrew",
    "CONNOR Colin": "connor-colin",
    "CONNOR Fiona": "connor-fiona",
    "CONNOR Francis": "connor-francis",
    "CONNOR Frankie": "connor-frankie",
    "CONNOR Gerladine": "connor-gerladine",
    "CONNOR Ken": "connor-ken",
    "CONNOR Laurie": "connor-laurie",
    "CONNOR Michael Donnel": "connor-michael-donnel",
    "CONNOR Rachel": "connor-rachel",
    "CONNOR Rosa": "connor-rosa",
    "CONNOR Tim": "connor-tim",
    "CONNOR Tommie": "connor-tommie",
    "CONNOR Tony": "connor-tony",
    "CONNOR Wesley N": "connor-wesley-n",
    "CONNOR William": "connor-william",
    "CONNORS Barry": "connors-barry",
    "CONNORS Jason": "connors-jason",
    "CONNORS Kevin": "connors-kevin",
    "CONOLLY Muriel": "conolly-muriel",
    "CONOR Sally": "conor-sally",
    "CONOVER Grandin": "conover-grandin",
    "CONQUEST Charlotte": "conquest-charlotte",
    "CONRAD Ameera": "conrad-ameera",
    "CONRAD Gail": "conrad-gail",
    "CONRAD Hy": "conrad-hy",
    "CONRAD Sandy": "conrad-sandy",
    "CONRADT Mark": "conradt-mark",
    "CONROY Amy": "conroy-amy",
    "CONROY David Raymond": "conroy-david-raymond",
    "CONROY John": "conroy-john",
    "CONROY Mary K": "conroy-mary-k",
    "CONSANI Christopher": "consani-christopher",
    "CONSIDINE Ciara": "considine-ciara",
    "CONSIDINE Mary": "considine-mary",
    "CONSPIRACY ": "conspiracy",
    "CONSTABLE John": "constable-john",
    "CONSTABLE Paul": "constable-paul",
    "CONSTANCE Dana": "constance-dana",
    "CONSTANCE Zeno": "constance-zeno",
    "CONSTANDUROS Denis": "constanduros-denis",
    "CONSTANDUROS Mabel": "constanduros-mabel",
    "CONSTANS Gabriel": "constans-gabriel",
    "CONSTANT Vanya": "constant-vanya",
    "CONSTANTI Cesar": "constanti-cesar",
    "CONSTANTINE Alex": "constantine-alex",
    "CONSTANTINE Martin": "constantine-martin",
    "CONSTANTINE Peter": "constantine-peter",
    "CONSTANTINIDIS Stratos E": "constantinidis-stratos-e",
    "CONSTANTINO Thea": "constantino-thea",
    "CONSTANZO Anthony": "constanzo-anthony",
    "CONTE Michel": "conte-michel",
    "CONTE Rick": "conte-rick",
    "CONTEMPORARY MUSIC GROUP ": "contemporary-music-group",
    "CONTI Dominic": "conti-dominic",
    "CONTI Nicholas": "conti-nicholas",
    "CONTINI George": "contini-george",
    "CONTINI Philip": "contini-philip",
    "CONTINO Rosalie H": "contino-rosalie-h",
    "CONTO C": "conto-c",
    "CONTORNO Mark": "contorno-mark",
    "CONTOSKI Victor": "contoski-victor",
    "CONTOSKI Wieslawa": "contoski-wieslawa",
    "CONTRERAS Bernadette": "contreras-bernadette",
    "CONTRERAS Julissa": "contreras-julissa",
    "CONTRERAS Maya": "contreras-maya",
    "CONTRERAS Sara": "contreras-sara",
    "CONTUZZI Jennie": "contuzzi-jennie",
    "CONVERSE Connie": "converse-connie",
    "CONVILLE David": "conville-david",
    "CONWAY Amy": "conway-amy",
    "CONWAY Carla J": "conway-carla-j",
    "CONWAY Dominic": "conway-dominic",
    "CONWAY Eric": "conway-eric",
    "CONWAY John": "conway-john",
    "CONWAY Jon": "conway-jon",
    "CONWAY Lenora Webb": "conway-lenora-webb",
    "CONWAY Mark": "conway-mark",
    "CONWAY Mel": "conway-mel",
    "CONWAY Mila": "conway-mila",
    "CONWAY Paul": "conway-paul",
    "CONWAY Rem": "conway-rem",
    "CONWAY Steve": "conway-steve",
    "CONYBEARE Yvonne": "conybeare-yvonne",
    "CONYERS Michael": "conyers-michael",
    "CONYNGHAM Barbara": "conyngham-barbara",
    "COO Clarence": "coo-clarence",
    "COOGAN Cynthia Burns": "coogan-cynthia-burns",
    "COOK Albert": "cook-albert",
    "COOK Andrew": "cook-andrew",
    "COOK Cecil Raymond": "cook-cecil-raymond",
    "COOK Charles W": "cook-charles-w",
    "COOK Christofer": "cook-christofer",
    "COOK Colleen": "cook-colleen",
    "COOK Curtiss I'": "cook-curtiss-i",
    "COOK David": "cook-david",
    "COOK Deborah": "cook-deborah",
    "COOK Elinor": "cook-elinor",
    "COOK Elizabeth": "cook-elizabeth",
    "COOK Ella": "cook-ella",
    "COOK Ernestine": "cook-ernestine",
    "COOK Gareth": "cook-gareth",
    "COOK Henry": "cook-henry",
    "COOK Jennifer Lucy": "cook-jennifer-lucy",
    "COOK Jenny Newell": "cook-jenny-newell",
    "COOK Joe": "cook-joe",
    "COOK Jonathan": "cook-jonathan",
    "COOK Judith": "cook-judith",
    "COOK Judy Simpson": "cook-judy-simpson",
    "COOK Kate": "cook-kate",
    "COOK Kay": "cook-kay",
    "COOK Kenneth": "cook-kenneth",
    "COOK Lesley": "cook-lesley",
    "COOK Marianne": "cook-marianne",
    "COOK Mark Edward": "cook-mark-edward",
    "COOK Mary Ann": "cook-mary-ann",
    "COOK Mel": "cook-mel",
    "COOK Michael (1)": "cook-michael-1",
    "COOK Michael (2)": "cook-michael-2",
    "COOK Pat": "cook-pat",
    "COOK Patrick": "cook-patrick",
    "COOK Peter": "cook-peter",
    "COOK Peter J": "cook-peter-j",
    "COOK Ralph": "cook-ralph",
    "COOK Randall David": "cook-randall-david",
    "COOK Ray": "cook-ray",
    "COOK Rebecca": "cook-rebecca",
    "COOK Rich": "cook-rich",
    "COOK Roderick": "cook-roderick",
    "COOK Sadie": "cook-sadie",
    "COOK Sam": "cook-sam",
    "COOK Sean": "cook-sean",
    "COOK Susana": "cook-susana",
    "COOK Thomas S": "cook-thomas-s",
    "COOK Tim": "cook-tim",
    "COOK Tina": "cook-tina",
    "COOK-DAFNER Geraldine": "cook-dafner-geraldine",
    "COOKE Alex": "cooke-alex",
    "COOKE Bal": "cooke-bal",
    "COOKE Brian": "cooke-brian",
    "COOKE Bruno": "cooke-bruno",
    "COOKE Carol": "cooke-carol",
    "COOKE Caroline Burns": "cooke-caroline-burns",
    "COOKE Dominic": "cooke-dominic",
    "COOKE James": "cooke-james",
    "COOKE Martin": "cooke-martin",
    "COOKE Mick": "cooke-mick",
    "COOKE Mike": "cooke-mike",
    "COOKE Trish": "cooke-trish",
    "COOKMAN Lesley": "cookman-lesley",
    "COOKSON Catherine": "cookson-catherine",
    "COOKSON Freda": "cookson-freda",
    "COOKSON Michael": "cookson-michael",
    "COOKSON Sally": "cookson-sally",
    "COOL Walter": "cool-walter",
    "COOL HUNTING ": "cool-hunting",
    "COOLIDGE Lucy": "coolidge-lucy",
    "COOLING Terence": "cooling-terence",
    "COOLLEY Peter": "coolley-peter",
    "COOMBE Julie": "coombe-julie",
    "COOMBES Brydie": "coombes-brydie",
    "COON Suzette": "coon-suzette",
    "COONAN Donal": "coonan-donal",
    "COONEY Doug": "cooney-doug",
    "COONEY Marcus": "cooney-marcus",
    "COONEY Michael": "cooney-michael",
    "COONEY Ray": "cooney-ray",
    "COONROD Karin": "coonrod-karin",
    "COONS Cheryl": "coons-cheryl",
    "COONS Rick": "coons-rick",
    "COOPER Adam": "cooper-adam",
    "COOPER Alice": "cooper-alice",
    "COOPER Alice Mary": "cooper-alice-mary",
    "COOPER Alison J": "cooper-alison-j",
    "COOPER Anna Julia": "cooper-anna-julia",
    "COOPER Ben": "cooper-ben",
    "COOPER Benjamin": "cooper-benjamin",
    "COOPER Beverley": "cooper-beverley",
    "COOPER Brian": "cooper-brian",
    "COOPER Chris": "cooper-chris",
    "COOPER Colin": "cooper-colin",
    "COOPER Craig": "cooper-craig",
    "COOPER Cynthia L": "cooper-cynthia-l",
    "COOPER David": "cooper-david",
    "COOPER Dennis": "cooper-dennis",
    "COOPER Dominic": "cooper-dominic",
    "COOPER Dorothy S": "cooper-dorothy-s",
    "COOPER Edwin": "cooper-edwin",
    "COOPER Emma J": "cooper-emma-j",
    "COOPER Fergus": "cooper-fergus",
    "COOPER Gareth": "cooper-gareth",
    "COOPER Ged": "cooper-ged",
    "COOPER Giles": "cooper-giles",
    "COOPER Greg": "cooper-greg",
    "COOPER Grub": "cooper-grub",
    "COOPER Helen": "cooper-helen",
    "COOPER Irving": "cooper-irving",
    "COOPER J B": "cooper-j-b",
    "COOPER J P": "cooper-j-p",
    "COOPER Jack": "cooper-jack",
    "COOPER Jesse": "cooper-jesse",
    "COOPER Joan": "cooper-joan",
    "COOPER John": "cooper-john",
    "COOPER John (2)": "cooper-john-2",
    "COOPER Jon": "cooper-jon",
    "COOPER Jordan E": "cooper-jordan-e",
    "COOPER Justin": "cooper-justin",
    "COOPER Keith": "cooper-keith",
    "COOPER Lauren": "cooper-lauren",
    "COOPER Linda Nell": "cooper-linda-nell",
    "COOPER M Thomas": "cooper-m-thomas",
    "COOPER Martin": "cooper-martin",
    "COOPER Mary": "cooper-mary",
    "COOPER Melissa": "cooper-melissa",
    "COOPER Melody": "cooper-melody",
    "COOPER Michael L": "cooper-michael-l",
    "COOPER Mick": "cooper-mick",
    "COOPER Miriam": "cooper-miriam",
    "COOPER Norton": "cooper-norton",
    "COOPER Patricia": "cooper-patricia",
    "COOPER Peter John": "cooper-peter-john",
    "COOPER Rachael": "cooper-rachael",
    "COOPER Rolin": "cooper-rolin",
    "COOPER Rose": "cooper-rose",
    "COOPER Saida": "cooper-saida",
    "COOPER Sara": "cooper-sara",
    "COOPER Sara (1)": "cooper-sara-1",
    "COOPER Sean": "cooper-sean",
    "COOPER Sharon E": "cooper-sharon-e",
    "COOPER Stephen": "cooper-stephen",
    "COOPER Susan": "cooper-susan",
    "COOPER T G": "cooper-t-g",
    "COOPER Timothy": "cooper-timothy",
    "COOPER Will": "cooper-will",
    "COOPER Zoe": "cooper-zoe",
    "COOPER Zoe (1)": "cooper-zoe-1",
    "COOPER Zoe (2)": "cooper-zoe-2",
    "COOPERMAN Alvin": "cooperman-alvin",
    "COOPERMAN Melvin I": "cooperman-melvin-i",
    "COOPER-NOVACK Gemma": "cooper-novack-gemma",
    "COOPERSMITH Jerome": "coopersmith-jerome",
    "COOPERSTEIN Ronda": "cooperstein-ronda",
    "COOPES Rachael": "coopes-rachael",
    "COOPRIDER Fred": "cooprider-fred",
    "COOTSONA Marcus": "cootsona-marcus",
    "COOVER Robert": "coover-robert",
    "COPANI Peter": "copani-peter",
    "COPE Christopher": "cope-christopher",
    "COPE Eddie": "cope-eddie",
    "COPE Jon Lee": "cope-jon-lee",
    "COPE Matthew": "cope-matthew",
    "COPE Timothy": "cope-timothy",
    "COPELAND Brian": "copeland-brian",
    "COPELAND Cecilia": "copeland-cecilia",
    "COPELAND D C": "copeland-d-c",
    "COPELAND Joan": "copeland-joan",
    "COPELAND Thomas": "copeland-thomas",
    "COPELIN David": "copelin-david",
    "COPI Victor": "copi-victor",
    "COPI ": "copi",
    "COPLAN Elizabeth": "coplan-elizabeth",
    "COPLEY Frank O": "copley-frank-o",
    "COPLEY Paul": "copley-paul",
    "COPP Corina": "copp-corina",
    "COPPARD J A S": "coppard-j-a-s",
    "COPPEDGE Rosanna E": "coppedge-rosanna-e",
    "COPPEL Alec": "coppel-alec",
    "COPPEL Fernanda": "coppel-fernanda",
    "COPPEL Myra": "coppel-myra",
    "COPPEN Neil": "coppen-neil",
    "COPPENGER Royston": "coppenger-royston",
    "COPPER Kelly": "copper-kelly",
    "COPPER William": "copper-william",
    "COPPIN Tyler": "coppin-tyler",
    "COPPING Gemma": "copping-gemma",
    "COPPOLA Alex": "coppola-alex",
    "COPPOLA Joseph R": "coppola-joseph-r",
    "COPPOLA Louis A": "coppola-louis-a",
    "COPPOLA Tom": "coppola-tom",
    "COPSTICK K M": "copstick-k-m",
    "CORAM Jez": "coram-jez",
    "CORAZZI Alessandro": "corazzi-alessandro",
    "CORBEIL Carole": "corbeil-carole",
    "CORBEIL Michel": "corbeil-michel",
    "CORBEIL-COLEMAN Charlotte": "corbeil-coleman-charlotte",
    "CORBETT Bill": "corbett-bill",
    "CORBETT Chris": "corbett-chris",
    "CORBETT Karen": "corbett-karen",
    "CORBETT Poppy": "corbett-poppy",
    "CORBETT Sheila": "corbett-sheila",
    "CORBETT Stephanie": "corbett-stephanie",
    "CORBETT T J": "corbett-t-j",
    "CORBIN Ann Palmer": "corbin-ann-palmer",
    "CORBIN Barry": "corbin-barry",
    "CORBIN Gary": "corbin-gary",
    "CORBIN Jarid": "corbin-jarid",
    "CORBITT Wayne": "corbitt-wayne",
    "CORBLE Simon": "corble-simon",
    "CORCORAN Chris": "corcoran-chris",
    "CORCORAN Josephine": "corcoran-josephine",
    "CORCORAN Luke": "corcoran-luke",
    "CORCORAN, JR John": "corcoran-jr-john",
    "CORDAL Alfredo": "cordal-alfredo",
    "CORDEIRO Steven": "cordeiro-steven",
    "CORDEIRO Will": "cordeiro-will",
    "CORDEL Alexander": "cordel-alexander",
    "CORDERO Frankie": "cordero-frankie",
    "CORDERO Ricardo": "cordero-ricardo",
    "CORDES Lisa": "cordes-lisa",
    "CORDES Marya Spring": "cordes-marya-spring",
    "CORDES Noah": "cordes-noah",
    "CORDING Alastair": "cording-alastair",
    "CORDINGLEY Julie": "cordingley-julie",
    "COREIL Clyde": "coreil-clyde",
    "COREN Ben": "coren-ben",
    "COREN Martin": "coren-martin",
    "COREN Victoria": "coren-victoria",
    "CORETH Susie": "coreth-susie",
    "COREY Herb": "corey-herb",
    "CORFIELD Katherine": "corfield-katherine",
    "CORFIELD Robin S": "corfield-robin-s",
    "CORIN Tahli": "corin-tahli",
    "CORINOTIS Fay": "corinotis-fay",
    "CORINS John Robert": "corins-john-robert",
    "CORIS Hector": "coris-hector",
    "CORK Adam": "cork-adam",
    "CORK Malcolm": "cork-malcolm",
    "CORK Thomas": "cork-thomas",
    "CORLETT William": "corlett-william",
    "CORLEY Diane": "corley-diane",
    "CORLEY Elisabeth Lewis": "corley-elisabeth-lewis",
    "CORLEY Hal": "corley-hal",
    "CORLEY Nick": "corley-nick",
    "CORLEY Richard": "corley-richard",
    "CORMACK Matthew": "cormack-matthew",
    "CORMAN Avery": "corman-avery",
    "CORMAN Randy": "corman-randy",
    "CORMAN Roger": "corman-roger",
    "CORMANN Enzo": "cormann-enzo",
    "CORMEY Theodore": "cormey-theodore",
    "CORMIER Michael Dennis": "cormier-michael-dennis",
    "CORN Lesllie": "corn-lesllie",
    "CORNALL Jan": "cornall-jan",
    "CORNEIL Zaida": "corneil-zaida",
    "CORNEILLE Pierre": "corneille-pierre",
    "CORNELIA Cornelia O": "cornelia-cornelia-o",
    "CORNELISON Gayle": "cornelison-gayle",
    "CORNELISSEN Ignace": "cornelissen-ignace",
    "CORNELIUS John L": "cornelius-john-l",
    "CORNELIUS Patricia": "cornelius-patricia",
    "CORNELIUS II John L": "cornelius-john-l",
    "CORNELL Justin": "cornell-justin",
    "CORNELL Kendall": "cornell-kendall",
    "CORNELL Mark": "cornell-mark",
    "CORNER Henry": "corner-henry",
    "CORNFOOT Ben": "cornfoot-ben",
    "CORNIBERT Christopher": "cornibert-christopher",
    "CORNICARD Stephane": "cornicard-stephane",
    "CORNINE Stephen": "cornine-stephen",
    "CORNISH Archie": "cornish-archie",
    "CORNISH Kasper": "cornish-kasper",
    "CORNISH Roger": "cornish-roger",
    "CORNISH THEATRE COLLECTIVE ": "cornish-theatre-collective",
    "CORNTHWAITE Robert": "cornthwaite-robert",
    "CORNUE David": "cornue-david",
    "CORNWELL Phil": "cornwell-phil",
    "COROMINA Josep Maria Miro": "coromina-josep-maria-miro",
    "COROZINE Richard": "corozine-richard",
    "CORPUS SOMA ": "corpus-soma",
    "CORPUZ Christine": "corpuz-christine",
    "CORR Frances": "corr-frances",
    "CORR Grant": "corr-grant",
    "CORRAL Gregorio G": "corral-gregorio-g",
    "CORRAL Joseph": "corral-joseph",
    "CORRAO Katina": "corrao-katina",
    "CORREA Jasmine": "correa-jasmine",
    "CORREA Mario": "correa-mario",
    "CORREN Andy": "corren-andy",
    "CORRIDAN Claire": "corridan-claire",
    "CORRIDOR Laci": "corridor-laci",
    "CORRIE Joe": "corrie-joe",
    "CORRIEL Matt": "corriel-matt",
    "CORRIERE Michael": "corriere-michael",
    "CORRIGAN James": "corrigan-james",
    "CORRIGAN Kevin": "corrigan-kevin",
    "CORRIGAN Paul": "corrigan-paul",
    "CORRIGAN Robert": "corrigan-robert",
    "CORRIGAN Robert W": "corrigan-robert-w",
    "CORRIN Dean": "corrin-dean",
    "CORRIS Colston": "corris-colston",
    "CORSANO Arlene": "corsano-arlene",
    "CORSARO Frank": "corsaro-frank",
    "CORTELEZZI Louis": "cortelezzi-louis",
    "CORTES Christian": "cortes-christian",
    "CORTES Esteban Navajas": "cortes-esteban-navajas",
    "CORTES Naomi": "cortes-naomi",
    "CORTES Noelia Ortiz": "cortes-noelia-ortiz",
    "CORTESE Raimondo": "cortese-raimondo",
    "CORTESI Aaron": "cortesi-aaron",
    "CORTEZ Cristina": "cortez-cristina",
    "CORTEZ Rose": "cortez-rose",
    "CORTHRON Kara Lee": "corthron-kara-lee",
    "CORTHRON Kia": "corthron-kia",
    "CORTI Victor": "corti-victor",
    "CORTINAS Jorge Ignacio": "cortinas-jorge-ignacio",
    "CORTONA David": "cortona-david",
    "CORUM Mark": "corum-mark",
    "CORWIN John": "corwin-john",
    "CORWIN Norman": "corwin-norman",
    "CORWIN T C": "corwin-t-c",
    "CORWIN Walter": "corwin-walter",
    "CORY Robert": "cory-robert",
    "COSEGLIA Jared": "coseglia-jared",
    "COSENTINO Joseph": "cosentino-joseph",
    "COSENTINO Laura": "cosentino-laura",
    "COSGRIFF Bill": "cosgriff-bill",
    "COSGROVE Aedin": "cosgrove-aedin",
    "COSGROVE Colleen": "cosgrove-colleen",
    "COSGROVE David": "cosgrove-david",
    "COSGROVE Mark J": "cosgrove-mark-j",
    "COSLETT Martin": "coslett-martin",
    "COSLOW Sam": "coslow-sam",
    "COSMOS ": "cosmos",
    "COSPAR Matt": "cospar-matt",
    "COSS Clare": "coss-clare",
    "COSSA Frank": "cossa-frank",
    "COSSA Roberto": "cossa-roberto",
    "COSSON Steven": "cosson-steven",
    "COSSONS W Ernest": "cossons-w-ernest",
    "COSTA Bernard Da": "costa-bernard-da",
    "COSTA Carol": "costa-carol",
    "COSTA Cheryl": "costa-cheryl",
    "COSTA Tony": "costa-tony",
    "COSTABLE Liana": "costable-liana",
    "COSTALES Kathleen": "costales-kathleen",
    "COSTA-MALCOLM Julia": "costa-malcolm-julia",
    "COSTANTINO Thea": "costantino-thea",
    "COSTANZA Joe": "costanza-joe",
    "COSTANZA William": "costanza-william",
    "COSTANZO Anthony": "costanzo-anthony",
    "COSTELLO Che": "costello-che",
    "COSTELLO Darryl": "costello-darryl",
    "COSTELLO Dylan": "costello-dylan",
    "COSTELLO Hugh": "costello-hugh",
    "COSTELLO Jake": "costello-jake",
    "COSTELLO Josh": "costello-josh",
    "COSTELLO Mark John": "costello-mark-john",
    "COSTELLO Michael": "costello-michael",
    "COSTELLO Paul": "costello-paul",
    "COSTI Angela": "costi-angela",
    "COSTIGAN Christina": "costigan-christina",
    "COSTIGAN George": "costigan-george",
    "COSTIGAN James": "costigan-james",
    "COSTIGAN Katy": "costigan-katy",
    "COSTIN Andrea": "costin-andrea",
    "COSTON Peter": "coston-peter",
    "COT Doo": "cot-doo",
    "COTE David": "cote-david",
    "COTE Lorraine": "cote-lorraine",
    "COTILLARD CO ": "cotillard-co",
    "COTLER Gordon": "cotler-gordon",
    "COTT Jonathan": "cott-jonathan",
    "COTTER Don": "cotter-don",
    "COTTER Kevin": "cotter-kevin",
    "COTTER Patricia": "cotter-patricia",
    "COTTERELL A F": "cotterell-a-f",
    "COTTERILL Ken": "cotterill-ken",
    "COTTERMAN Seth": "cotterman-seth",
    "COTTILARD COMPANY ": "cottilard-company",
    "COTTIS David": "cottis-david",
    "COTTLE Dan": "cottle-dan",
    "COTTLE Jon": "cottle-jon",
    "COTTLES Christina": "cottles-christina",
    "COTTON Laura": "cotton-laura",
    "COTTON Oliver": "cotton-oliver",
    "COTTON Stanislas": "cotton-stanislas",
    "COTTON Travis": "cotton-travis",
    "COTTON Walter": "cotton-walter",
    "COTTONE D A": "cottone-d-a",
    "COTTRELL Ed": "cottrell-ed",
    "COTTRELL Karen": "cottrell-karen",
    "COTTRELL Matthew": "cottrell-matthew",
    "COTTRELL Richard": "cottrell-richard",
    "COTTRELL Richard (1)": "cottrell-richard-1",
    "COTTRELL Tony": "cottrell-tony",
    "COTTRELL-BOYCE Frank": "cottrell-boyce-frank",
    "COTTS Kristin": "cotts-kristin",
    "COTUGNO Vincent": "cotugno-vincent",
    "COUCH Cheryl": "couch-cheryl",
    "COUCH Joseph": "couch-joseph",
    "COUCH Robert": "couch-robert",
    "COUDERT Jo": "coudert-jo",
    "COUDLE-KING Kathleen": "coudle-king-kathleen",
    "COUGAR Van": "cougar-van",
    "COUGHLAN Alice": "coughlan-alice",
    "COUGHLAN John Alban": "coughlan-john-alban",
    "COUGHLAN Samantha": "coughlan-samantha",
    "COUGHLIN Kathryn": "coughlin-kathryn",
    "COUGHLIN Tim": "coughlin-tim",
    "COUGHRAN Bruce": "coughran-bruce",
    "COULAM Graeme": "coulam-graeme",
    "COULING Della": "couling-della",
    "COULING Orion": "couling-orion",
    "COULLET Rhonda": "coullet-rhonda",
    "COULOMBE Jeannine": "coulombe-jeannine",
    "COULSON Sam": "coulson-sam",
    "COULSON Steven": "coulson-steven",
    "COULT Averil": "coult-averil",
    "COULT Tony": "coult-tony",
    "COULTER John": "coulter-john",
    "COULTER Paul": "coulter-paul",
    "COULTER Phil": "coulter-phil",
    "COULTON Jonathan": "coulton-jonathan",
    "COUMIN Christian": "coumin-christian",
    "COUNTING SQUARES THEATRE ": "counting-squares-theatre",
    "COUNTS Angela": "counts-angela",
    "COUPE Nick": "coupe-nick",
    "COUPER Matthew": "couper-matthew",
    "COUPERTHWAITE Adam": "couperthwaite-adam",
    "COUPLAND Douglas": "coupland-douglas",
    "COURIE Jon": "courie-jon",
    "COURIE Laylage": "courie-laylage",
    "COURLANDER Scott": "courlander-scott",
    "COURSER Anthony": "courser-anthony",
    "COURTELINE Georges": "courteline-georges",
    "COURTENAY Tom": "courtenay-tom",
    "COURTNEY C C": "courtney-c-c",
    "COURTNEY Dennis": "courtney-dennis",
    "COURTNEY Donal": "courtney-donal",
    "COURTNEY Erin": "courtney-erin",
    "COURTNEY Meg": "courtney-meg",
    "COURTNEY Michael": "courtney-michael",
    "COURTNEY Ragan": "courtney-ragan",
    "COURTNEY Rose": "courtney-rose",
    "COURTNEY Susan": "courtney-susan",
    "COURTNEY Suzanne": "courtney-suzanne",
    "COURTNEY Ward": "courtney-ward",
    "COURTNEY-WOLFMAN Leora": "courtney-wolfman-leora",
    "COURTS Randy": "courts-randy",
    "COUSIN Gabriel": "cousin-gabriel",
    "COUSINEAU Jorge": "cousineau-jorge",
    "COUSINS E G": "cousins-e-g",
    "COUSINS John": "cousins-john",
    "COUSINS Linda": "cousins-linda",
    "COUSINS Norman": "cousins-norman",
    "COUSINS Rhiannon": "cousins-rhiannon",
    "COUSINS Robert": "cousins-robert",
    "COUSINS Robin": "cousins-robin",
    "COUSINS-NEWTON Linda": "cousins-newton-linda",
    "COUSSE Raymond": "cousse-raymond",
    "COUTINHO Russell J": "coutinho-russell-j",
    "COUTTS Adam": "coutts-adam",
    "COUTURIER Gracia": "couturier-gracia",
    "COVAL Kevin": "coval-kevin",
    "COVAR Ronald S": "covar-ronald-s",
    "COVE Michael": "cove-michael",
    "COVE Rosemary": "cove-rosemary",
    "COVELL Joshua A": "covell-joshua-a",
    "COVELL Kevin": "covell-kevin",
    "COVENEY Alan": "coveney-alan",
    "COVERACK Jenny": "coverack-jenny",
    "COVERDALE Beth": "coverdale-beth",
    "COVERT Christopher": "covert-christopher",
    "COVERT Ralph": "covert-ralph",
    "COVILLE Bruce": "coville-bruce",
    "COVINGTON C M": "covington-c-m",
    "COVINGTON Dennis": "covington-dennis",
    "COVINGTON Sarita": "covington-sarita",
    "COW Michael": "cow-michael",
    "COWAN Billy": "cowan-billy",
    "COWAN Cindy": "cowan-cindy",
    "COWAN Claire": "cowan-claire",
    "COWAN David": "cowan-david",
    "COWAN Geoffrey": "cowan-geoffrey",
    "COWAN Maurice": "cowan-maurice",
    "COWAN Ron": "cowan-ron",
    "COWAN Russ": "cowan-russ",
    "COWAN Sarah": "cowan-sarah",
    "COWAN Steven Dow": "cowan-steven-dow",
    "COWARD David": "coward-david",
    "COWARD H": "coward-h",
    "COWARD Matt": "coward-matt",
    "COWARD Noel": "coward-noel",
    "COWARS Elizabeth": "cowars-elizabeth",
    "COWART Adam": "cowart-adam",
    "COWART Albert": "cowart-albert",
    "COWBURY Tim": "cowbury-tim",
    "COWELL Ariel": "cowell-ariel",
    "COWELL Brendan": "cowell-brendan",
    "COWELL Nick": "cowell-nick",
    "COWELL Will   ": "cowell-will",
    "COWEN Ron": "cowen-ron",
    "COWEY Chris": "cowey-chris",
    "COWHIG Frances Ya-Chu": "cowhig-frances-ya-chu",
    "COWIE Andrew": "cowie-andrew",
    "COWIE Megan": "cowie-megan",
    "COWIE Victor": "cowie-victor",
    "COWLAM Peter": "cowlam-peter",
    "COWLES Virginia": "cowles-virginia",
    "COWLES Yvette": "cowles-yvette",
    "COWLEY Graham": "cowley-graham",
    "COWLEY Joy": "cowley-joy",
    "COWLEY Kelly": "cowley-kelly",
    "COWLEY Matt": "cowley-matt",
    "COWLEY Sheila": "cowley-sheila",
    "COWLEY Tom": "cowley-tom",
    "COWLISHAW J Basil": "cowlishaw-j-basil",
    "COWNIE Tony": "cownie-tony",
    "COWPER Trevor": "cowper-trevor",
    "COWPERTHWAIT James": "cowperthwait-james",
    "COX Alex": "cox-alex",
    "COX Andy": "cox-andy",
    "COX Brian Newton": "cox-brian-newton",
    "COX Constance": "cox-constance",
    "COX Dee Jae": "cox-dee-jae",
    "COX Gerard": "cox-gerard",
    "COX Gordon": "cox-gordon",
    "COX Haley": "cox-haley",
    "COX Jacob Joseph": "cox-jacob-joseph",
    "COX Jarrad": "cox-jarrad",
    "COX Jason": "cox-jason",
    "COX Joseph Mason Andrew": "cox-joseph-mason-andrew",
    "COX Laura": "cox-laura",
    "COX Lucia": "cox-lucia",
    "COX Mark": "cox-mark",
    "COX Ned": "cox-ned",
    "COX Oliver": "cox-oliver",
    "COX Paul": "cox-paul",
    "COX Peter": "cox-peter",
    "COX Peter (1)": "cox-peter-1",
    "COX Rita Maree": "cox-rita-maree",
    "COX Simon": "cox-simon",
    "COX Susan": "cox-susan",
    "COX Tony": "cox-tony",
    "COX Tony (1)": "cox-tony-1",
    "COX Vivian A": "cox-vivian-a",
    "COXE Louis O": "coxe-louis-o",
    "COXEN Chris": "coxen-chris",
    "COXHEAD David": "coxhead-david",
    "COX-O'CONNELL Frank": "cox-o-connell-frank",
    "COXON Caroline": "coxon-caroline",
    "COXON Lucinda": "coxon-lucinda",
    "COX-WILLIAMS Stephanie": "cox-williams-stephanie",
    "COY Peter": "coy-peter",
    "COYKENDALL Milton": "coykendall-milton",
    "COYLE Blaze Kelly": "coyle-blaze-kelly",
    "COYLE Daisy": "coyle-daisy",
    "COYLE J J": "coyle-j-j",
    "COYLE Kevin": "coyle-kevin",
    "COYLE Lily Baber": "coyle-lily-baber",
    "COYLE McCarthy": "coyle-mccarthy",
    "COYLE Nicholas": "coyle-nicholas",
    "COYLE Nick": "coyle-nick",
    "COYLE P Hogan": "coyle-p-hogan",
    "COYLE Padraig": "coyle-padraig",
    "COYLE Sean": "coyle-sean",
    "COYLE Terry": "coyle-terry",
    "COYLE Thomas": "coyle-thomas",
    "COYLE Wendy": "coyle-wendy",
    "COYLE William": "coyle-william",
    "COYLE William Patrick": "coyle-william-patrick",
    "COYNE Alan": "coyne-alan",
    "COYNE Dave \"Dclugi\"": "coyne-dave",
    "COYNE Fiona": "coyne-fiona",
    "COYNE Joseph": "coyne-joseph",
    "COYNE Susan": "coyne-susan",
    "COYOTE Dom": "coyote-dom",
    "COZAD M A": "cozad-m-a",
    "COZBY Paul Woods": "cozby-paul-woods",
    "COZIER Avery": "cozier-avery",
    "COZIER Christian Anthony": "cozier-christian-anthony",
    "COZZOLA Mary-Terese": "cozzola-mary-terese",
    "CPT COMPANY ": "cpt-company",
    "CPT YOUTH THEATRE ": "cpt-youth-theatre",
    "CRABB Cathy": "crabb-cathy",
    "CRABB David": "crabb-david",
    "CRABB Kara": "crabb-kara",
    "CRABBE K C": "crabbe-k-c",
    "CRABBE Kerry Lee": "crabbe-kerry-lee",
    "CRABTREE Audrey": "crabtree-audrey",
    "CRABTREE Colleen": "crabtree-colleen",
    "CRABTREE Howard": "crabtree-howard",
    "CRABTREE Ian": "crabtree-ian",
    "CRABTREE Jim": "crabtree-jim",
    "CRABTREE John": "crabtree-john",
    "CRABTREE Paul": "crabtree-paul",
    "CRACE Anna": "crace-anna",
    "CRACKNELL Carrie": "cracknell-carrie",
    "CRADDOCK Christopher": "craddock-christopher",
    "CRADDOCK Kate": "craddock-kate",
    "CRADDOX Kenneth G": "craddox-kenneth-g",
    "CRAFFORD James": "crafford-james",
    "CRAFFORD Robert": "crafford-robert",
    "CRAFT Andy": "craft-andy",
    "CRAFT B Dwayne": "craft-b-dwayne",
    "CRAFT Howard L": "craft-howard-l",
    "CRAFT Janis": "craft-janis",
    "CRAFT ENSEMBLE ": "craft-ensemble",
    "CRAFTS Gregory": "crafts-gregory",
    "CRAGG Stephen": "cragg-stephen",
    "CRAGIN Chris": "cragin-chris",
    "CRAGO Jim": "crago-jim",
    "CRAIG Alec": "craig-alec",
    "CRAIG Bill": "craig-bill",
    "CRAIG Catriona": "craig-catriona",
    "CRAIG Colleen": "craig-colleen",
    "CRAIG David": "craig-david",
    "CRAIG David S": "craig-david-s",
    "CRAIG Deborah": "craig-deborah",
    "CRAIG Gloria": "craig-gloria",
    "CRAIG Jason": "craig-jason",
    "CRAIG Jules": "craig-jules",
    "CRAIG Kathleen": "craig-kathleen",
    "CRAIG Mike": "craig-mike",
    "CRAIG Phillis": "craig-phillis",
    "CRAIG Rose Maclennan": "craig-rose-maclennan",
    "CRAIG Ryan": "craig-ryan",
    "CRAIG Shari Ajemian": "craig-shari-ajemian",
    "CRAIG Ted": "craig-ted",
    "CRAIG-CLAAR Deborah": "craig-claar-deborah",
    "CRAIG-GALVAN Inda": "craig-galvan-inda",
    "CRAIGHEAD Mikey": "craighead-mikey",
    "CRAIGIE Sandie": "craigie-sandie",
    "CRAIL Archie": "crail-archie",
    "CRAIN Cameron": "crain-cameron",
    "CRAM Alan": "cram-alan",
    "CRAM Cusi": "cram-cusi",
    "CRAM Marc": "cram-marc",
    "CRAMER Kevin": "cramer-kevin",
    "CRAMER Rosalind": "cramer-rosalind",
    "CRAMMES E P": "crammes-e-p",
    "CRAMOND Jodi": "cramond-jodi",
    "CRANDALL Kathleen": "crandall-kathleen",
    "CRANDELL Dawn": "crandell-dawn",
    "CRANE Alison": "crane-alison",
    "CRANE Cheryll": "crane-cheryll",
    "CRANE David": "crane-david",
    "CRANE Farrah": "crane-farrah",
    "CRANE James": "crane-james",
    "CRANE Jillian": "crane-jillian",
    "CRANE K J": "crane-k-j",
    "CRANE Larry": "crane-larry",
    "CRANE M": "crane-m",
    "CRANE Nancy": "crane-nancy",
    "CRANE Richard": "crane-richard",
    "CRANE Richard (1)": "crane-richard-1",
    "CRANE Roger": "crane-roger",
    "CRANENDONK Terence": "cranendonk-terence",
    "CRANERT Terrence": "cranert-terrence",
    "CRANEY P P": "craney-p-p",
    "CRANKO John": "cranko-john",
    "CRANKSHAW Edward": "crankshaw-edward",
    "CRANNEY Hellie": "cranney-hellie",
    "CRANNEY Jon": "cranney-jon",
    "CRANNEY P P": "cranney-p-p",
    "CRANO Brian": "crano-brian",
    "CRANOR Jeffrey": "cranor-jeffrey",
    "CRANSTON Jerneral": "cranston-jerneral",
    "CRAPELLI Vincent": "crapelli-vincent",
    "CRAVEIRO Joana": "craveiro-joana",
    "CRAVEN Douglas": "craven-douglas",
    "CRAVEN Frank": "craven-frank",
    "CRAVEN Hal": "craven-hal",
    "CRAVEN Jim": "craven-jim",
    "CRAVEN Nemonie": "craven-nemonie",
    "CRAVER Mike": "craver-mike",
    "CRAVIOTTO Darlene": "craviotto-darlene",
    "CRAWFORD Calvin": "crawford-calvin",
    "CRAWFORD Christina": "crawford-christina",
    "CRAWFORD David Wright": "crawford-david-wright",
    "CRAWFORD Dylan": "crawford-dylan",
    "CRAWFORD Gary": "crawford-gary",
    "CRAWFORD Helen": "crawford-helen",
    "CRAWFORD India": "crawford-india",
    "CRAWFORD Jamie": "crawford-jamie",
    "CRAWFORD Jerry L": "crawford-jerry-l",
    "CRAWFORD Jim": "crawford-jim",
    "CRAWFORD Johnny": "crawford-johnny",
    "CRAWFORD Laurence": "crawford-laurence",
    "CRAWFORD Loren": "crawford-loren",
    "CRAWFORD Lynda": "crawford-lynda",
    "CRAWFORD Mark": "crawford-mark",
    "CRAWFORD Martin": "crawford-martin",
    "CRAWFORD Nance": "crawford-nance",
    "CRAWFORD Norman": "crawford-norman",
    "CRAWFORD Ray Scott": "crawford-ray-scott",
    "CRAWFORD Robert": "crawford-robert",
    "CRAWFORD Rowena": "crawford-rowena",
    "CRAWFORD Sean H": "crawford-sean-h",
    "CRAWFORD Sharon": "crawford-sharon",
    "CRAWFORD Stephanie": "crawford-stephanie",
    "CRAWFORD Terence": "crawford-terence",
    "CRAWFORD Trace": "crawford-trace",
    "CRAWLEY Brian": "crawley-brian",
    "CRAWLEY Edward": "crawley-edward",
    "CRAWLEY Hazel L": "crawley-hazel-l",
    "CRAWLEY Linda Segal": "crawley-linda-segal",
    "CRAWLING Richard": "crawling-richard",
    "CRAWSHAW Tom": "crawshaw-tom",
    "CRAYFORD Chelsie Preston": "crayford-chelsie-preston",
    "CRAZE James": "craze-james",
    "CRAZE Tony": "craze-tony",
    "CRAZY HORSE TC ": "crazy-horse-tc",
    "CREA Teresa": "crea-teresa",
    "CREAGH Henry M": "creagh-henry-m",
    "CREAGLE Charmian": "creagle-charmian",
    "CREAMER Tom": "creamer-tom",
    "CREAN Robert": "crean-robert",
    "CREAR Bobby": "crear-bobby",
    "CREASED ": "creased",
    "CREASEY Beverly": "creasey-beverly",
    "CREASEY Joel": "creasey-joel",
    "CREASEY John": "creasey-john",
    "CREATIVE ELECTRIC ": "creative-electric",
    "CREATORE Luigi": "creatore-luigi",
    "CRECCA Fred": "crecca-fred",
    "CREE Sam": "cree-sam",
    "CREECH Andrew Lee": "creech-andrew-lee",
    "CREECH Sharon": "creech-sharon",
    "CREECHAN Bernadette Maria": "creechan-bernadette-maria",
    "CREED Don": "creed-don",
    "CREED Rupert": "creed-rupert",
    "CREED Tom": "creed-tom",
    "CREEDON Barrie": "creedon-barrie",
    "CREEDON Conal": "creedon-conal",
    "CREEDON Don": "creedon-don",
    "CREEGAN Paul": "creegan-paul",
    "CREELEY Robert": "creeley-robert",
    "CREELY Edwin": "creely-edwin",
    "CREELY Niamh": "creely-niamh",
    "CREES Michala": "crees-michala",
    "CREESE Fiona": "creese-fiona",
    "CREESE Rick": "creese-rick",
    "CREEZ Ellis": "creez-ellis",
    "CREFELD Jon": "crefeld-jon",
    "CREGAN David": "cregan-david",
    "CREHAN Matthew": "crehan-matthew",
    "CREHORE Tom Oliver": "crehore-tom-oliver",
    "CREIGHTON Anthony": "creighton-anthony",
    "CREIGHTON Michael Cyril": "creighton-michael-cyril",
    "CREIGHTON Robert": "creighton-robert",
    "CRENSHW Kimberle": "crenshw-kimberle",
    "CREOLA Lissa": "creola-lissa",
    "CRESCENZO Mary": "crescenzo-mary",
    "CRESCITELI Jim": "cresciteli-jim",
    "CRESPIN Patricia": "crespin-patricia",
    "CRESPO Frederico": "crespo-frederico",
    "CRESPO Sol": "crespo-sol",
    "CRESPY David": "crespy-david",
    "CRESS Noemi Martinez": "cress-noemi-martinez",
    "CRESSEVICH Vanesa": "cressevich-vanesa",
    "CRESSWELL Catherine": "cresswell-catherine",
    "CRESSWELL Janet": "cresswell-janet",
    "CRESSWELL Luke": "cresswell-luke",
    "CRESWELL Catherine": "creswell-catherine",
    "CRESWELL Chris": "creswell-chris",
    "CRESWELL Trent A": "creswell-trent-a",
    "CREW Tim": "crew-tim",
    "CREWDSON Christa": "crewdson-christa",
    "CREWE Bob": "crewe-bob",
    "CREWS Andre": "crews-andre",
    "CREWS Harry": "crews-harry",
    "CREYTON Barry": "creyton-barry",
    "CRIBB Reg": "cribb-reg",
    "CRIBBS Diane": "cribbs-diane",
    "CRICHTON Iain": "crichton-iain",
    "CRICHTON Kyle": "crichton-kyle",
    "CRIDER Amy": "crider-amy",
    "CRIGHTON Jackie": "crighton-jackie",
    "CRILLY Joseph": "crilly-joseph",
    "CRIM Carey": "crim-carey",
    "CRIMMINS James": "crimmins-james",
    "CRIMP Catherine": "crimp-catherine",
    "CRIMP Martin": "crimp-martin",
    "CRIPPIN Gavin": "crippin-gavin",
    "CRIPPS Harry": "cripps-harry",
    "CRISCIONE Frank": "criscione-frank",
    "CRISP Jack H": "crisp-jack-h",
    "CRISP N J": "crisp-n-j",
    "CRISP Quentin": "crisp-quentin",
    "CRISPIN Philip": "crispin-philip",
    "CRISPINI Giuliano": "crispini-giuliano",
    "CRISPINO Orietta": "crispino-orietta",
    "CRISTALDI Jonathan": "cristaldi-jonathan",
    "CRISTOFER Michael": "cristofer-michael",
    "CRISWELL Kim": "criswell-kim",
    "CRITCH Tom": "critch-tom",
    "CRITCHLEY Bob": "critchley-bob",
    "CRITCHLEY George": "critchley-george",
    "CRITCHLEY Kitty": "critchley-kitty",
    "CRITCHLEY Tom": "critchley-tom",
    "CRITOPH Alex": "critoph-alex",
    "CRITT C J": "critt-c-j",
    "CRITTENDEN Evangeline": "crittenden-evangeline",
    "CRITTENDEN Jordan": "crittenden-jordan",
    "CROAL Aida M": "croal-aida-m",
    "CROALL Jonathan": "croall-jonathan",
    "CROCE Arlene": "croce-arlene",
    "CROCITTO Frank": "crocitto-frank",
    "CROCKER Alan": "crocker-alan",
    "CROCKER Ben": "crocker-ben",
    "CROCKER John": "crocker-john",
    "CROCKER Temple": "crocker-temple",
    "CROCKER Warner": "crocker-warner",
    "CROCKETT Charles Vivian": "crockett-charles-vivian",
    "CROCKETT Emily": "crockett-emily",
    "CROCKETTE Juli": "crockette-juli",
    "CROFOOT Leonard": "crofoot-leonard",
    "CROFT David": "croft-david",
    "CROFT Giles": "croft-giles",
    "CROFT Julia": "croft-julia",
    "CROFT Martin": "croft-martin",
    "CROFT Stephen": "croft-stephen",
    "CROFTS Karla": "crofts-karla",
    "CROGGON Alison": "croggon-alison",
    "CROGHAN Declan": "croghan-declan",
    "CROKE Matthew": "croke-matthew",
    "CROKER Temple": "croker-temple",
    "CROLEY Colin": "croley-colin",
    "CROLL Stewart": "croll-stewart",
    "CROLL Tina": "croll-tina",
    "CROM Rick": "crom-rick",
    "CROMBIE Kathleen": "crombie-kathleen",
    "CROME Karla": "crome-karla",
    "CROME Wayne": "crome-wayne",
    "CROMIE Aaron": "cromie-aaron",
    "CROMIE Kathleen": "cromie-kathleen",
    "CROMMELYNCK Fernand": "crommelynck-fernand",
    "CROMPTON Ben": "crompton-ben",
    "CROMPTON Margaret": "crompton-margaret",
    "CROMPTON Michael": "crompton-michael",
    "CROMWELL John": "cromwell-john",
    "CRONACHER Karen": "cronacher-karen",
    "CRONE Brandon": "crone-brandon",
    "CRONE Joshua": "crone-joshua",
    "CRONIN Anthony": "cronin-anthony",
    "CRONIN Bobby": "cronin-bobby",
    "CRONIN David": "cronin-david",
    "CRONIN Harry": "cronin-harry",
    "CRONIN John": "cronin-john",
    "CRONIN Maggie": "cronin-maggie",
    "CRONSHAW Bill": "cronshaw-bill",
    "CRONYN Hume": "cronyn-hume",
    "CROOK David": "crook-david",
    "CROOK Jean": "crook-jean",
    "CROOK Kevin": "crook-kevin",
    "CROOK Laura": "crook-laura",
    "CROOKER Earl": "crooker-earl",
    "CROOKES Eric": "crookes-eric",
    "CROOKS Barry": "crooks-barry",
    "CROOKSHANK Rebecca": "crookshank-rebecca",
    "CROOME Andrew": "croome-andrew",
    "CROOT Cynthia": "croot-cynthia",
    "CROPP M J": "cropp-m-j",
    "CROPPER Anna": "cropper-anna",
    "CROSBIE Mary": "crosbie-mary",
    "CROSBY Linda L": "crosby-linda-l",
    "CROSBY Meghan": "crosby-meghan",
    "CROSBY Steve": "crosby-steve",
    "CROSE Brandon M": "crose-brandon-m",
    "CROSS Ben": "cross-ben",
    "CROSS Beverley": "cross-beverley",
    "CROSS Cherise": "cross-cherise",
    "CROSS Clare": "cross-clare",
    "CROSS Colin": "cross-colin",
    "CROSS Felix": "cross-felix",
    "CROSS Ian": "cross-ian",
    "CROSS Jason": "cross-jason",
    "CROSS John Keir": "cross-john-keir",
    "CROSS Jonathan": "cross-jonathan",
    "CROSS L B": "cross-l-b",
    "CROSS Meg Henry": "cross-meg-henry",
    "CROSS Michael": "cross-michael",
    "CROSS Murphy": "cross-murphy",
    "CROSS Nathan": "cross-nathan",
    "CROSS Phil": "cross-phil",
    "CROSSER Tyler": "crosser-tyler",
    "CROSSLAND Jackie": "crossland-jackie",
    "CROSSLEY Doug": "crossley-doug",
    "CROSSLEY Jacob": "crossley-jacob",
    "CROST Ken": "crost-ken",
    "CROSTHWAITE Bernie": "crosthwaite-bernie",
    "CROSWELL Anne": "croswell-anne",
    "CROTHERS Rachel": "crothers-rachel",
    "CROTHERS Susan": "crothers-susan",
    "CROTON William Hugel": "croton-william-hugel",
    "CROUCH Bill": "crouch-bill",
    "CROUCH Jason": "crouch-jason",
    "CROUCH Julian": "crouch-julian",
    "CROUCH Nel": "crouch-nel",
    "CROUCH Rob": "crouch-rob",
    "CROUCH Tim": "crouch-tim",
    "CROUCH William Thompson": "crouch-william-thompson",
    "CROUSE Russell": "crouse-russell",
    "CROUSE Timothy": "crouse-timothy",
    "CROW Esther": "crow-esther",
    "CROW Liz": "crow-liz",
    "CROW Michael": "crow-michael",
    "CROW Sheryl": "crow-sheryl",
    "CROWDER Ben": "crowder-ben",
    "CROWDER Daniel": "crowder-daniel",
    "CROWDER David Llloyd": "crowder-david-llloyd",
    "CROWE Allen": "crowe-allen",
    "CROWE C J": "crowe-c-j",
    "CROWE Christine": "crowe-christine",
    "CROWE E V": "crowe-e-v",
    "CROWE George": "crowe-george",
    "CROWE Haidee": "crowe-haidee",
    "CROWE Richard": "crowe-richard",
    "CROWE S Peter": "crowe-s-peter",
    "CROWE Stephen": "crowe-stephen",
    "CROWE Thomas": "crowe-thomas",
    "CROWFOOT-SUEDE Lance": "crowfoot-suede-lance",
    "CROWLE Nigel": "crowle-nigel",
    "CROWLEY Alan": "crowley-alan",
    "CROWLEY Anthony": "crowley-anthony",
    "CROWLEY Colin": "crowley-colin",
    "CROWLEY Colin Speer": "crowley-colin-speer",
    "CROWLEY George Tynan": "crowley-george-tynan",
    "CROWLEY Jeananne": "crowley-jeananne",
    "CROWLEY Kevin": "crowley-kevin",
    "CROWLEY Mart": "crowley-mart",
    "CROWLEY Matt": "crowley-matt",
    "CROWLEY Michael": "crowley-michael",
    "CROWLEY Michael Yates": "crowley-michael-yates",
    "CROWLEY Tom": "crowley-tom",
    "CROWNS John": "crowns-john",
    "CROWTHER Colin": "crowther-colin",
    "CROWTHER Jihan": "crowther-jihan",
    "CROWTHER Mary": "crowther-mary",
    "CROWTHER Simon": "crowther-simon",
    "CROWTHER Stuart": "crowther-stuart",
    "CROYDEN Christine": "croyden-christine",
    "CROYLE Matt": "croyle-matt",
    "CROYSTON John": "croyston-john",
    "CROZIER Avery": "crozier-avery",
    "CRUCE Lance": "cruce-lance",
    "CRUDEN Thomas": "cruden-thomas",
    "CRUICKSHANK Andrew": "cruickshank-andrew",
    "CRUICKSHANK D W": "cruickshank-d-w",
    "CRUICKSHANK Helen B": "cruickshank-helen-b",
    "CRUICKSHANK Marty": "cruickshank-marty",
    "CRUIKSHANK Ciaran": "cruikshank-ciaran",
    "CRUISE Leonie": "cruise-leonie",
    "CRUISE Maryjane": "cruise-maryjane",
    "CRUIZE Ron": "cruize-ron",
    "CRUM Anthony": "crum-anthony",
    "CRUM Jane Ann": "crum-jane-ann",
    "CRUMMEY Michael": "crummey-michael",
    "CRUMMEY Sean": "crummey-sean",
    "CRUMP Evan": "crump-evan",
    "CRUMP Owen": "crump-owen",
    "CRUMPS THEATRE OF MARBLES ": "crumps-theatre-of-marbles",
    "CRUSH THEATRE COMPANY ": "crush-theatre-company",
    "CRUSTO Eve": "crusto-eve",
    "CRUTCHER D L": "crutcher-d-l",
    "CRUTCHER Julie": "crutcher-julie",
    "CRUTCHFIELD John": "crutchfield-john",
    "CRUTTWELL Hugh": "cruttwell-hugh",
    "CRUZ Angie": "cruz-angie",
    "CRUZ Ari Maniel": "cruz-ari-maniel",
    "CRUZ Bob": "cruz-bob",
    "CRUZ Evelyn Diaz": "cruz-evelyn-diaz",
    "CRUZ Isagani R": "cruz-isagani-r",
    "CRUZ Jaime": "cruz-jaime",
    "CRUZ Joseph": "cruz-joseph",
    "CRUZ Luis Miguel Gonzalez": "cruz-luis-miguel-gonzalez",
    "CRUZ Melissa": "cruz-melissa",
    "CRUZ Migdalia": "cruz-migdalia",
    "CRUZ Nilo": "cruz-nilo",
    "CRUZ-TORRUELLAS Elsia": "cruz-torruellas-elsia",
    "CRYER Barry": "cryer-barry",
    "CRYER Bob": "cryer-bob",
    "CRYER Gretchen": "cryer-gretchen",
    "CRYSTAL Amber": "crystal-amber",
    "CRYSTAL Billy": "crystal-billy",
    "CRYSTAL Clark": "crystal-clark",
    "CRYSTAL Raphael": "crystal-raphael"
  }
};