export default {
  "metadata": {
    "results": 1436,
    "timeStamp": "2025-12-05T21:23:44.267Z",
    "url": "https://www.doollee.com/PlaywrightsD/D_playwrights_a-f.php"
  },
  "authors": {
    "D Ramola": "d-ramola",
    "DA COSTA Bernard": "da-costa-bernard",
    "DA COSTA Bernard (1)": "da-costa-bernard-1",
    "DA COSTA Simon Mendes": "da-costa-simon-mendes",
    "DA COSTA Suneeta Peres": "da-costa-suneeta-peres",
    "DA CUNHA Rahul": "da-cunha-rahul",
    "DA DA DUMB ": "da-da-dumb",
    "DA PONTE Lorenzo": "da-ponte-lorenzo",
    "DAAB Hyatt": "daab-hyatt",
    "DAACK Esther": "daack-esther",
    "DABBON David": "dabbon-david",
    "DABROSKI Kristen": "dabroski-kristen",
    "DABROWSKA Maria": "dabrowska-maria",
    "DABROWSKI Kristen": "dabrowski-kristen",
    "DABROWSKI Mike": "dabrowski-mike",
    "D'ABUNDANCE Jehan": "d-abundance-jehan",
    "DACE Wallace": "dace-wallace",
    "DACEY Jack F": "dacey-jack-f",
    "DACOSTA Morton": "dacosta-morton",
    "DACUS Katy": "dacus-katy",
    "DADA Tolula": "dada-tolula",
    "D'ADDARIO Ronnie": "d-addario-ronnie",
    "DADS' THEATRE GROUP ": "dads-theatre-group",
    "DAEDALUS THEATRE ": "daedalus-theatre",
    "DAFF Adriane": "daff-adriane",
    "DAFFI ": "daffi",
    "DAFNEROS Maria": "dafneros-maria",
    "DAFOE Willem": "dafoe-willem",
    "DAFYDD Catrin": "dafydd-catrin",
    "DAFYDD Gwenno": "dafydd-gwenno",
    "DAGERMAN Stig": "dagerman-stig",
    "DAGGER Matt Porter": "dagger-matt-porter",
    "DAGGER Peter": "dagger-peter",
    "DAGGER Will": "dagger-will",
    "DAGGETT John": "daggett-john",
    "DAGNY Robert": "dagny-robert",
    "D'AGOSTINO Bill": "d-agostino-bill",
    "D'AGOSTINO Frank": "d-agostino-frank",
    "D'AGOSTINO Joseph D": "d-agostino-joseph-d",
    "D'AGOSTINO Ornella": "d-agostino-ornella",
    "D'AGUIAR Fred": "d-aguiar-fred",
    "DAHDAH Robert": "dahdah-robert",
    "DAHL Janea": "dahl-janea",
    "DAHL Kirsten": "dahl-kirsten",
    "DAHL Michael": "dahl-michael",
    "DAHL Mikael": "dahl-mikael",
    "DAHL Niels Fr": "dahl-niels-fr",
    "DAHL Roald": "dahl-roald",
    "DAHLBACKA Nara": "dahlbacka-nara",
    "DAHLINGER Nicola": "dahlinger-nicola",
    "DAHLQUIST Gordon": "dahlquist-gordon",
    "DAHLSTROM Magnus": "dahlstrom-magnus",
    "DAHM Madeleine": "dahm-madeleine",
    "DAIGLE Cody": "daigle-cody",
    "DAIGLE Jean": "daigle-jean",
    "DAILY Bill": "daily-bill",
    "DAILY Patrick": "daily-patrick",
    "DAIMON Shiro": "daimon-shiro",
    "DAINOFF Andrew": "dainoff-andrew",
    "DAIRMAN Tara": "dairman-tara",
    "DAISEY Mike": "daisey-mike",
    "D'AIUTOLO Jacy": "d-aiutolo-jacy",
    "DALAGER Stig": "dalager-stig",
    "DALBIS Nicholas Joseph": "dalbis-nicholas-joseph",
    "DAL-BOSCO Andrew": "dal-bosco-andrew",
    "DALBY Krista": "dalby-krista",
    "DALDRY Stephen": "daldry-stephen",
    "DALE Adrian": "dale-adrian",
    "DALE Alice": "dale-alice",
    "DALE Alwyn": "dale-alwyn",
    "DALE Bruce": "dale-bruce",
    "DALE Eric": "dale-eric",
    "DALE Janet": "dale-janet",
    "DALE Jim": "dale-jim",
    "DALE Phil": "dale-phil",
    "DALE Stephanie": "dale-stephanie",
    "DALE-JONES Josie": "dale-jones-josie",
    "DALE-JONES Shon": "dale-jones-shon",
    "D'ALESSANDRIS Paula": "d-alessandris-paula",
    "D'ALESSANDRO Franco": "d-alessandro-franco",
    "D'ALESSANDRO John Totarella": "d-alessandro-john-totarella",
    "D'ALESSANDRO HATT Michelle": "d-alessandro-hatt-michelle",
    "DALEY Andy": "daley-andy",
    "DALEY Danielle": "daley-danielle",
    "DALEY Dona": "daley-dona",
    "DALEY Donna": "daley-donna",
    "DALEY Keira": "daley-keira",
    "DALEY Liam Thomas": "daley-liam-thomas",
    "DALEY Marcus": "daley-marcus",
    "DALEY Neil": "daley-neil",
    "DALEY Patrick": "daley-patrick",
    "DALEY Richard M": "daley-richard-m",
    "DALEY Ronald E": "daley-ronald-e",
    "DALEY Sandra": "daley-sandra",
    "DALEY Tracey": "daley-tracey",
    "DALGLISH Jim": "dalglish-jim",
    "DALLAM Belle": "dallam-belle",
    "DALLAS Jack": "dallas-jack",
    "DALLAS Karl": "dallas-karl",
    "DALLAS Patricka": "dallas-patricka",
    "DALLAS Tony": "dallas-tony",
    "DALLAS Walter": "dallas-walter",
    "DALLAS-DAMIS Athena": "dallas-damis-athena",
    "D'ALLESSANDRO Robbi": "d-allessandro-robbi",
    "DALLIMORE John": "dallimore-john",
    "DALLIN Heidi J": "dallin-heidi-j",
    "DALLIN Howard": "dallin-howard",
    "DALLMEYER Andrew": "dallmeyer-andrew",
    "DALMON Charles": "dalmon-charles",
    "D'ALOIS Roberta": "d-alois-roberta",
    "DALPE Jean Marc": "dalpe-jean-marc",
    "DALRYMPLE Angus": "dalrymple-angus",
    "DALRYMPLE Jean": "dalrymple-jean",
    "DALRYMPLE Staci": "dalrymple-staci",
    "DALSIMER Susan": "dalsimer-susan",
    "DALTNER Diane": "daltner-diane",
    "DALTON Amanda": "dalton-amanda",
    "DALTON Anne": "dalton-anne",
    "DALTON Dave": "dalton-dave",
    "DALTON Ernest": "dalton-ernest",
    "DALTON Jack": "dalton-jack",
    "DALTON Jill": "dalton-jill",
    "DALTON Kathleen": "dalton-kathleen",
    "DALTON Lisa": "dalton-lisa",
    "DALTON Louisiana": "dalton-louisiana",
    "DALTON Mike": "dalton-mike",
    "DALTON Muriel": "dalton-muriel",
    "DALTON Susannah": "dalton-susannah",
    "DALTON Tony": "dalton-tony",
    "DALTON Walter": "dalton-walter",
    "D'ALTON Evan Lee": "d-alton-evan-lee",
    "D'ALTON Louis": "d-alton-louis",
    "DALTON JR George H": "dalton-jr-george-h",
    "DALTRY Stephen": "daltry-stephen",
    "DALUZ Terryl": "daluz-terryl",
    "DALWITZ David": "dalwitz-david",
    "DALY A": "daly-a",
    "DALY Beth": "daly-beth",
    "DALY Bob": "daly-bob",
    "DALY Cyril": "daly-cyril",
    "DALY Dennis": "daly-dennis",
    "DALY Ella": "daly-ella",
    "DALY Emily": "daly-emily",
    "DALY Geoff": "daly-geoff",
    "DALY Jim": "daly-jim",
    "DALY Miriam": "daly-miriam",
    "DALY Nancy": "daly-nancy",
    "DALY Nicholas": "daly-nicholas",
    "DALY Pat": "daly-pat",
    "DALY Paul Emelion": "daly-paul-emelion",
    "DALY Peter": "daly-peter",
    "DALY Sinead": "daly-sinead",
    "DALY Timothy": "daly-timothy",
    "DALY Victoria Z": "daly-victoria-z",
    "DALY Wally K": "daly-wally-k",
    "DALZELL Drew": "dalzell-drew",
    "DALZELL William": "dalzell-william",
    "DALZIEL Marjorie Hooper": "dalziel-marjorie-hooper",
    "DALZIEL Quentin": "dalziel-quentin",
    "DALZON Wilfred": "dalzon-wilfred",
    "DAMANTE Susan": "damante-susan",
    "D'AMARIO Dan": "d-amario-dan",
    "DAMASHEK Barbara": "damashek-barbara",
    "DAMATO Anthony": "damato-anthony",
    "D'AMATO Chris": "d-amato-chris",
    "D'AMATO Darren": "d-amato-darren",
    "DAMBAEK Kim": "dambaek-kim",
    "D'AMBROSI Dario": "d-ambrosi-dario",
    "D'AMBROSIO Butch": "d-ambrosio-butch",
    "DAME Nathan": "dame-nathan",
    "DAME Robert": "dame-robert",
    "DAME Terry": "dame-terry",
    "DAMER Rod": "damer-rod",
    "DAMGEN Carol Lynne": "damgen-carol-lynne",
    "DAMIANO Daniel": "damiano-daniel",
    "DAMICO Frank": "damico-frank",
    "D'AMICO John": "d-amico-john",
    "DAMIEN Dechelle": "damien-dechelle",
    "DAMIGOS Katherine": "damigos-katherine",
    "DAMJANOVSKI Sasha C": "damjanovski-sasha-c",
    "DAMNED, THE ": "damned",
    "DAMON Jeffrey": "damon-jeffrey",
    "D'AMORE Carlo": "d-amore-carlo",
    "D'AMOUR Lisa": "d-amour-lisa",
    "DAMPIER Alfred": "dampier-alfred",
    "DAMSCHRODER Caleb": "damschroder-caleb",
    "DAMU ": "damu",
    "DAN AND JEFF ": "dan-jeff",
    "DANA Barbara": "dana-barbara",
    "DANA Max": "dana-max",
    "DANA Paul": "dana-paul",
    "DANAHER Katie": "danaher-katie",
    "DANALAKE Brett": "danalake-brett",
    "DANBY Trevor": "danby-trevor",
    "DANCE Carol": "dance-carol",
    "DANCE Chris": "dance-chris",
    "DANCE Suzanne": "dance-suzanne",
    "DANCOES Elizabeth": "dancoes-elizabeth",
    "DANDADE Neal": "dandade-neal",
    "D'ANDREA Paul": "d-andrea-paul",
    "DANDRIDGE David": "dandridge-david",
    "DANE Clemence": "dane-clemence",
    "DANE John": "dane-john",
    "DANE Thomas": "dane-thomas",
    "DANESCO Beth": "danesco-beth",
    "DANFY Richard": "danfy-richard",
    "DANG Tim": "dang-tim",
    "DANGAREMBA Tsitsi": "dangaremba-tsitsi",
    "D'ANGELIS J Michael": "d-angelis-j-michael",
    "D'ANGELO Sabrina": "d-angelo-sabrina",
    "DANGERFIELD Elma": "dangerfield-elma",
    "DANICKOVA Eva": "danickova-eva",
    "DANIEL Andy": "daniel-andy",
    "DANIEL Barbara": "daniel-barbara",
    "DANIEL Bruce": "daniel-bruce",
    "DANIEL Brunet": "daniel-brunet",
    "DANIEL Cricket": "daniel-cricket",
    "DANIEL Gloria": "daniel-gloria",
    "DANIEL Helen": "daniel-helen",
    "DANIEL Jamie": "daniel-jamie",
    "DANIEL Jamie Owen": "daniel-jamie-owen",
    "DANIEL Laura": "daniel-laura",
    "DANIEL Lea": "daniel-lea",
    "DANIEL Sarah \"Fitzrea\"": "daniel-sarah",
    "D'ANIEL Robin": "d-aniel-robin",
    "DANIELLE BROTHERS ": "danielle-brothers",
    "DANIELS A Frederick": "daniels-a-frederick",
    "DANIELS Alan Aaron": "daniels-alan-aaron",
    "DANIELS Brian": "daniels-brian",
    "DANIELS Carey": "daniels-carey",
    "DANIELS Dan": "daniels-dan",
    "DANIELS Demetria": "daniels-demetria",
    "DANIELS Eric K": "daniels-eric-k",
    "DANIELS Gina": "daniels-gina",
    "DANIELS Guy": "daniels-guy",
    "DANIELS Heather": "daniels-heather",
    "DANIELS Jeff": "daniels-jeff",
    "DANIELS Julie": "daniels-julie",
    "DANIELS Julie Dawson": "daniels-julie-dawson",
    "DANIELS Patrick": "daniels-patrick",
    "DANIELS Peter": "daniels-peter",
    "DANIELS Ron": "daniels-ron",
    "DANIELS S L": "daniels-s-l",
    "DANIELS Sarah": "daniels-sarah",
    "DANIELS Sean": "daniels-sean",
    "DANIELS Stan": "daniels-stan",
    "DANIELS Stan (1)": "daniels-stan-1",
    "DANIELS Tim": "daniels-tim",
    "DANIELSEN Carl": "danielsen-carl",
    "DANIELS-TAYLOR Annette": "daniels-taylor-annette",
    "DANIS Daniel": "danis-daniel",
    "DANIS Louison": "danis-louison",
    "DANISCHEWSKY Brenda": "danischewsky-brenda",
    "DANISCHEWSKY Monja": "danischewsky-monja",
    "DANJURO Ichikawa": "danjuro-ichikawa",
    "DANKWORTH Johnny": "dankworth-john",
    "DANLEY Kate": "danley-kate",
    "DANLEY Lora": "danley-lora",
    "DANLY Erin": "danly-erin",
    "DANN George Landen": "dann-george-landen",
    "DANN Matt": "dann-matt",
    "DANN Max": "dann-max",
    "DANN Sam": "dann-sam",
    "DANN Wendy": "dann-wendy",
    "D'ANNA Chiara": "d-anna-chiara",
    "DANNENFELSER Beth": "dannenfelser-beth",
    "DANNENFELSER David": "dannenfelser-david",
    "DANNEQUIN Laura": "dannequin-laura",
    "DANNER Alexander": "danner-alexander",
    "D'ANNUNZIO Gabriele": "d-annunzio-gabriele",
    "DANOS Victoria": "danos-victoria",
    "DANOWSKI Chris": "danowski-chris",
    "DANSICKER Michael": "dansicker-michael",
    "DANSON Dan": "danson-dan",
    "DANSON Frank C": "danson-frank-c",
    "DANTE Nicholas": "dante-nicholas",
    "DANTE Ron": "dante-ron",
    "DANTEZ ": "dantez",
    "D'ANTONIO Michael": "d-antonio-michael",
    "DANZ Cassandra": "danz-cassandra",
    "DANZA Domenick": "danza-domenick",
    "DANZIGER Dennis": "danziger-dennis",
    "DANZIGER Jackie": "danziger-jackie",
    "DANZIGER Martin": "danziger-martin",
    "DAOUD Anissa": "daoud-anissa",
    "DAPLYN Tom": "daplyn-tom",
    "DAPOLITO John": "dapolito-john",
    "D'AQUILA Fabio": "d-aquila-fabio",
    "D'AQUILA Kenny": "d-aquila-kenny",
    "DAR Azma": "dar-azma",
    "DARA Olu": "dara-olu",
    "DARA Owen": "dara-owen",
    "DARAGO John": "darago-john",
    "DARBON Leslie": "darbon-leslie",
    "DARBY Bryan": "darby-bryan",
    "DARBY Camille": "darby-camille",
    "DARBY James": "darby-james",
    "DARBY Katy": "darby-katy",
    "DARBYSHIRE Hugh": "darbyshire-hugh",
    "DARCHUK Heidi": "darchuk-heidi",
    "D'ARCY Emma": "d-arcy-emma",
    "D'ARCY Margaretta": "d-arcy-margaretta",
    "DARDAI Bilal": "dardai-bilal",
    "DARDEN Jean": "darden-jean",
    "DARDENNE John": "dardenne-john",
    "DARE Bill": "dare-bill",
    "DARE Jamie": "dare-jamie",
    "DARG Phil": "darg-phil",
    "DARGAN Marcus": "dargan-marcus",
    "DARGEL Corey": "dargel-corey",
    "DARIA Robert John": "daria-robert-john",
    "D'ARIENZO Chris": "d-arienzo-chris",
    "DARION Joe": "darion-joe",
    "DARIUS Adam": "darius-adam",
    "DARK Charlie": "dark-charlie",
    "DARK Kimberley": "dark-kimberley",
    "DARK Randall Paris": "dark-randall-paris",
    "DARKE Barrie": "darke-barrie",
    "DARKE Delsie": "darke-delsie",
    "DARKE Nick": "darke-nick",
    "DARKE Nick (1)": "darke-nick-1",
    "DARKIN Fleur": "darkin-fleur",
    "DARKLAND COLLECTIVE ": "darkland-collective",
    "DARKLY Dandy": "darkly-dandy",
    "DARLEY Emmanuel": "darley-emmanuel",
    "DARLING Joan": "darling-joan",
    "DARLING Julia": "darling-julia",
    "DARLINGS, THE ": "darling",
    "DARLINGTON Tim": "darlington-tim",
    "DARLONE Mia": "darlone-mia",
    "DARNALL Colleen": "darnall-colleen",
    "DARNBROUGH John": "darnbrough-john",
    "DARNELL G Brent": "darnell-g-brent",
    "DARNELL Leaven": "darnell-leaven",
    "DARNEY Peter": "darney-peter",
    "DARNOSKY Sally": "darnosky-sally",
    "DARRELL George": "darrell-george",
    "DARRELLE Dharvi": "darrelle-dharvi",
    "D'ARRIETTA Stewart": "d-arrietta-stewart",
    "D'ARRIGO Londos": "d-arrigo-londos",
    "DARROH Gladney Boyd": "darroh-gladney-boyd",
    "DARROW David": "darrow-david",
    "DARROW Jason": "darrow-jason",
    "DARROW Jill": "peterson-liz",
    "DARST Jeanne": "darst-jeanne",
    "DART Iris R": "dart-iris-r",
    "DART Iris Rainer": "dart-iris-rainer",
    "DART Philip": "dart-philip",
    "DARTER Tom": "darter-tom",
    "DARTINGTON Tim": "dartington-tim",
    "DARTNELL Guy": "dartnell-guy",
    "DARVILL Arthur": "darvill-arthur",
    "DARVILL Keith": "darvill-keith",
    "DARWISH Adel": "darwish-adel",
    "DAS Devika": "das-devika",
    "DAS Gucharan": "das-gucharan",
    "DAS K": "das-k",
    "DASHE Leah": "dashe-leah",
    "DASHOW Deborah": "dashow-deborah",
    "DASHOW Ken": "dashow-ken",
    "DASHWOOD William": "dashwood-william",
    "DASILVA Howard": "dasilva-howard",
    "D'ASSEAU Arnaud": "d-asseau-arnaud",
    "DASSIN Jules": "dassin-jules",
    "DAT Ron": "dat-ron",
    "DATI Evelyn": "dati-evelyn",
    "D'ATRI Shelia": "d-atri-shelia",
    "DATTANI Mahesh": "dattani-mahesh",
    "DATTILO Mary": "dattilo-mary",
    "DAUBE Akiva": "daube-akiva",
    "DAUBER Jeremy": "dauber-jeremy",
    "DAUBLE Chuck": "dauble-chuck",
    "DAUCHAN Darian": "dauchan-darian",
    "DAUGHERTY Bill": "daugherty-bill",
    "DAUGHERTY Linda": "daugherty-linda",
    "DAUGHERTY Rex": "daugherty-rex",
    "D'AULAIRE Nils": "d-aulaire-nils",
    "DAULTE Javier": "daulte-javier",
    "DAUM Jill": "daum-jill",
    "DAUNT Steve": "daunt-steve",
    "DAURIO Ken": "daurio-ken",
    "DAUSSAT Patsy Hester": "daussat-patsy-hester",
    "DAUT Steve": "daut-steve",
    "DAVALOS David": "davalos-david",
    "DAVAS Nick": "davas-nick",
    "DAVENPORT Barbara": "davenport-barbara",
    "DAVENPORT Chris": "davenport-chris",
    "DAVENPORT Danielle": "davenport-danielle",
    "DAVENPORT Edward": "davenport-edward",
    "DAVENPORT Gwen": "davenport-gwen",
    "DAVENPORT John C": "davenport-john-c",
    "DAVENPORT Ken": "davenport-ken",
    "DAVENPORT Lauren": "davenport-lauren",
    "DAVENPORT Mary": "davenport-mary",
    "DAVENPORT Peter": "davenport-peter",
    "DAVENPORT Susan": "davenport-susan",
    "DAVEY Andre Labelle": "davey-andre-labelle",
    "DAVEY C J": "davey-c-j",
    "DAVEY Justine Mitchell": "davey-justine-mitchell",
    "DAVEY Maude": "davey-maude",
    "DAVEY Richard": "davey-richard",
    "DAVEY Shaun": "davey-shaun",
    "DAVID Arvind Ethan": "david-arvind-ethan",
    "DAVID Hal": "david-hal",
    "DAVID Henry": "david-henry",
    "DAVID Jamal": "david-jamal",
    "DAVID Janina": "david-janina",
    "DAVID Jim": "david-jim",
    "DAVID John": "david-john",
    "DAVID Kole": "david-kole",
    "DAVID Larry": "david-larry",
    "DAVID Lionel": "david-lionel",
    "DAVID Mansel": "david-mansel",
    "DAVID Martin A": "david-martin-a",
    "DAVID Mary Stewart": "david-mary-stewart",
    "DAVID Matthew": "david-matthew",
    "DAVID Michael": "david-michael",
    "DAVID Michael (1)": "david-michael-1",
    "DAVID Michael R": "david-michael-r",
    "DAVID Rob": "david-rob",
    "DAVID Sean": "david-sean",
    "DAVID Valerie": "david-valerie",
    "DAVID Vanessa": "david-vanessa",
    "DAVID-DEAN Lisa": "david-dean-lisa",
    "D'AVIDIO Joe": "d-avidio-joe",
    "DAVIDOFF Leslie": "davidoff-leslie",
    "DAVIDON Ann Morrissett": "davidon-ann-morrissett",
    "DAVIDOVICH Bram": "davidovich-bram",
    "DAVIDOWITZ Stacy": "davidowitz-stacy",
    "DAVIDSON Aerin": "davidson-aerin",
    "DAVIDSON Bryan": "davidson-bryan",
    "DAVIDSON Cecelia": "davidson-cecelia",
    "DAVIDSON Conrad E": "davidson-conrad-e",
    "DAVIDSON Craig": "davidson-craig",
    "DAVIDSON Derek": "davidson-derek",
    "DAVIDSON Donna Rae": "davidson-donna-rae",
    "DAVIDSON Ellen": "davidson-ellen",
    "DAVIDSON Frank": "davidson-frank",
    "DAVIDSON George F": "davidson-george-f",
    "DAVIDSON Gordon": "davidson-gordon",
    "DAVIDSON Harlan": "davidson-harlan",
    "DAVIDSON Ian": "davidson-ian",
    "DAVIDSON Jim": "davidson-jim",
    "DAVIDSON Jody": "davidson-jody",
    "DAVIDSON John": "davidson-john",
    "DAVIDSON Jonathan L": "davidson-jonathan-l",
    "DAVIDSON Kate": "davidson-kate",
    "DAVIDSON Ken": "davidson-ken",
    "DAVIDSON Leah": "davidson-leah",
    "DAVIDSON Marcus": "davidson-marcus",
    "DAVIDSON N R": "davidson-n-r",
    "DAVIDSON Patricia": "davidson-patricia",
    "DAVIDSON Richard": "davidson-richard",
    "DAVIDSON Rob": "davidson-rob",
    "DAVIDSON Robert": "davidson-robert",
    "DAVIDSON Sylvia": "davidson-sylvia",
    "DAVIDSON William": "davidson-william",
    "DAVIDSON-ZIELSKE Gay": "davidson-zielske-gay",
    "DAVIE John": "davie-john",
    "DAVIES Allison": "davies-allison",
    "DAVIES And": "davies-and",
    "DAVIES Andrew": "davies-andrew",
    "DAVIES Andrew (1)": "davies-andrew-1",
    "DAVIES Andrew J": "davies-andrew-j",
    "DAVIES Bembo": "davies-bembo",
    "DAVIES Ben Norton": "davies-ben-norton",
    "DAVIES Bill": "davies-bill",
    "DAVIES Branwen": "davies-branwen",
    "DAVIES C J": "davies-c-j",
    "DAVIES Carl": "davies-carl",
    "DAVIES Carmel": "davies-carmel",
    "DAVIES Cecil": "davies-cecil",
    "DAVIES Colin": "davies-colin",
    "DAVIES D T": "davies-d-t",
    "DAVIES Dave": "davies-dave",
    "DAVIES David Stuart": "davies-david-stuart",
    "DAVIES Drew": "davies-drew",
    "DAVIES Eic": "davies-eic",
    "DAVIES Glen": "davies-glen",
    "DAVIES Hannah": "davies-hannah",
    "DAVIES Heather": "davies-heather",
    "DAVIES Hubert Henry": "davies-hubert-henry",
    "DAVIES Jack Rhys": "davies-jack-rhys",
    "DAVIES Jeremy Hylton": "davies-jeremy-hylton",
    "DAVIES Joe": "davies-joe",
    "DAVIES John Graham": "davies-john-graham",
    "DAVIES John O": "davies-john-o",
    "DAVIES Kim": "davies-kim",
    "DAVIES Kitchener": "davies-kitchener",
    "DAVIES Kyle": "davies-kyle",
    "DAVIES Lewis": "davies-lewis",
    "DAVIES Luke": "davies-luke",
    "DAVIES Luke (2)": "davies-luke-2",
    "DAVIES Luke (3)": "davies-luke-3",
    "DAVIES Mark": "davies-mark",
    "DAVIES Matthew": "davies-matthew",
    "DAVIES Meirion": "davies-meirion",
    "DAVIES Michael": "davies-michael",
    "DAVIES Michael (1)": "davies-michael-1",
    "DAVIES Mike": "davies-mike",
    "DAVIES Molly": "davies-molly",
    "DAVIES Molly (1)": "davies-molly-1",
    "DAVIES Nic": "davies-nic",
    "DAVIES Nick": "davies-nick",
    "DAVIES Nicola Jorden": "davies-nicola-jorden",
    "DAVIES Oliver Ford": "davies-oliver-ford",
    "DAVIES Olwen": "davies-olwen",
    "DAVIES Paul (1)": "davies-paul-1",
    "DAVIES Paul (2)": "davies-paul-2",
    "DAVIES Paul B": "davies-paul-b",
    "DAVIES Peter Maxwell": "davies-peter-maxwell",
    "DAVIES Phil": "davies-phil",
    "DAVIES Ray": "davies-ray",
    "DAVIES Robertson": "davies-robertson",
    "DAVIES Robin": "davies-robin",
    "DAVIES Sarah": "davies-sarah",
    "DAVIES Sasha Milavic": "davies-sasha-milavic",
    "DAVIES Seiriol": "davies-seiriol",
    "DAVIES Sheldon": "davies-sheldon",
    "DAVIES Simon": "davies-simon",
    "DAVIES Siobhan": "davies-siobhan",
    "DAVIES Steve": "davies-steve",
    "DAVIES Stratford": "davies-stratford",
    "DAVIES Susan": "davies-susan",
    "DAVIES Terry": "davies-terry",
    "DAVIES Thetudor": "davies-thetudor",
    "DAVIES Toby (1)": "davies-toby-1",
    "DAVIES Toby (2)": "davies-toby-2",
    "DAVIES Tom": "davies-tom",
    "DAVIES Trina": "davies-trina",
    "DAVIES Tudor": "davies-tudor",
    "DAVIES Victor": "davies-victor",
    "DAVIES Will": "davies-will",
    "DAVIH Mic": "davih-mic",
    "DAVIN Nicolas Flood": "davin-nicolas-flood",
    "DAVIN Patrick": "davin-patrick",
    "DAVIN-POWER Maurice": "davin-power-maurice",
    "DAVIOT Gordon": "daviot-gordon",
    "DAVIOT Michael": "daviot-michael",
    "DAVIS A I": "davis-a-i",
    "DAVIS Al": "davis-al",
    "DAVIS Alan R": "davis-alan-r",
    "DAVIS Alison": "davis-alison",
    "DAVIS Amanda": "davis-amanda",
    "DAVIS Amanda Blake": "davis-amanda-blake",
    "DAVIS Andrea E": "davis-andrea-e",
    "DAVIS Barry": "davis-barry",
    "DAVIS Benjamin": "davis-benjamin",
    "DAVIS Bill C": "davis-bill-c",
    "DAVIS Brionne": "davis-brionne",
    "DAVIS Buffy": "davis-buffy",
    "DAVIS Buster": "davis-buster",
    "DAVIS Carl": "davis-carl",
    "DAVIS Carlos": "davis-carlos",
    "DAVIS Carol": "davis-carol",
    "DAVIS Cecile": "davis-cecile",
    "DAVIS Cherrye J": "davis-cherrye-j",
    "DAVIS Cheryl L": "davis-cheryl-l",
    "DAVIS Chris": "davis-chris",
    "DAVIS Clair": "davis-clair",
    "DAVIS Colin": "davis-colin",
    "DAVIS David": "davis-david",
    "DAVIS David Eric": "davis-david-eric",
    "DAVIS Donald": "davis-donald",
    "DAVIS Dre": "davis-dre",
    "DAVIS Drew": "davis-drew",
    "DAVIS Eddie": "davis-eddie",
    "DAVIS Edward": "davis-edward",
    "DAVIS Eisa": "davis-eisa",
    "DAVIS Eliot": "davis-eliot",
    "DAVIS Elisabeth S": "davis-elisabeth-s",
    "DAVIS Elise Marie": "davis-elise-marie",
    "DAVIS Elizabeth M": "davis-elizabeth-m",
    "DAVIS Ellen Brook": "davis-ellen-brook",
    "DAVIS Elliot": "davis-elliot",
    "DAVIS Emily": "davis-emily",
    "DAVIS Eric": "davis-eric",
    "DAVIS Fai Walker": "davis-fai-walker",
    "DAVIS Gabriel": "davis-gabriel",
    "DAVIS Garrett": "davis-garrett",
    "DAVIS Gavin": "davis-gavin",
    "DAVIS Gavin G": "davis-gavin-g",
    "DAVIS Geri Turner": "davis-geri-turner",
    "DAVIS Ginny": "davis-ginny",
    "DAVIS Glendora": "davis-glendora",
    "DAVIS Glynne": "davis-glynne",
    "DAVIS Guy": "davis-guy",
    "DAVIS Gwen": "davis-gwen",
    "DAVIS J P": "davis-j-p",
    "DAVIS Jack": "davis-jack",
    "DAVIS Jackie": "davis-jackie",
    "DAVIS James P": "davis-james-p",
    "DAVIS Jeffrey": "davis-jeffrey",
    "DAVIS Jenny": "davis-jenny",
    "DAVIS Jenny Connell": "davis-jenny-connell",
    "DAVIS Jim": "davis-jim",
    "DAVIS Jo": "davis-jo",
    "DAVIS John Arthur": "davis-john-arthur",
    "DAVIS John E": "davis-john-e",
    "DAVIS John Henry": "davis-john-henry",
    "DAVIS Judith": "davis-judith",
    "DAVIS Julia": "davis-julia",
    "DAVIS Julianne Wick": "davis-julianne-wick",
    "DAVIS Larry": "davis-larry",
    "DAVIS Lawrence E": "davis-lawrence-e",
    "DAVIS Lloyd": "davis-lloyd",
    "DAVIS Luther": "davis-luther",
    "DAVIS Mara": "davis-mara",
    "DAVIS Margaret": "davis-margaret",
    "DAVIS Marian": "davis-marian",
    "DAVIS Marty": "davis-marty",
    "DAVIS Mary Gonzalez": "davis-mary-gonzalez",
    "DAVIS Mary Patricia": "davis-mary-patricia",
    "DAVIS Matthew Ethan": "davis-matthew-ethan",
    "DAVIS Maximillian": "davis-maximillian",
    "DAVIS Michael Philip": "davis-michael-philip",
    "DAVIS Michele": "davis-michele",
    "DAVIS Michelle R": "davis-michelle-r",
    "DAVIS Mike": "davis-mike",
    "DAVIS Milburn": "davis-milburn",
    "DAVIS Nathan Alan": "davis-nathan-alan",
    "DAVIS Nicky": "davis-nicky",
    "DAVIS Ossie": "davis-ossie",
    "DAVIS Owen": "davis-owen",
    "DAVIS Pat": "davis-pat",
    "DAVIS Patricia": "davis-patricia",
    "DAVIS Paul O": "davis-paul-o",
    "DAVIS Peg": "davis-peg",
    "DAVIS Peter": "davis-peter",
    "DAVIS Philip": "davis-philip",
    "DAVIS R G": "davis-r-g",
    "DAVIS Rae": "davis-rae",
    "DAVIS Reid": "davis-reid",
    "DAVIS Rib": "davis-rib",
    "DAVIS Rick": "davis-rick",
    "DAVIS Robb Leigh": "davis-robb-leigh",
    "DAVIS Robert O": "davis-robert-o",
    "DAVIS Rosemary L": "davis-rosemary-l",
    "DAVIS Russell": "davis-russell",
    "DAVIS Sasha Milavic": "davis-sasha-milavic",
    "DAVIS Scott": "davis-scott",
    "DAVIS Scott H": "davis-scott-h",
    "DAVIS Skot": "davis-skot",
    "DAVIS Spenser": "davis-spenser",
    "DAVIS Stephan": "davis-stephan",
    "DAVIS Stephen": "davis-stephen",
    "DAVIS Stephen (2)": "davis-stephen-2",
    "DAVIS Stephen (3)": "davis-stephen-3",
    "DAVIS Ted": "davis-ted",
    "DAVIS Terry S": "davis-terry-s",
    "DAVIS Thad": "davis-thad",
    "DAVIS Thom": "davis-thom",
    "DAVIS Thompson": "davis-thompson",
    "DAVIS Thulani": "davis-thulani",
    "DAVIS Tom Arthur": "davis-tom-arthur",
    "DAVIS Wick": "davis-wick",
    "DAVIS William Angelo": "davis-william-angelo",
    "DAVIS Wyn": "davis-wyn",
    "DAVIS III Allen": "davis-iii-allen",
    "DAVISON Anthony": "davison-anthony",
    "DAVISON Denis": "davison-denis",
    "DAVISON Dennis": "davison-dennis",
    "DAVISON John": "davison-john",
    "DAVISON Pam": "davison-pam",
    "DAVISON Philip": "davison-philip",
    "DAVISON Richard": "davison-richard",
    "DAVISON Sarah": "davison-sarah",
    "DAVIS-SPLITTER Susie": "davis-splitter-susie",
    "DAVIS-STEWART George": "davis-stewart-george",
    "DAVIS-THOMPSON Dewey": "davis-thompson-dewey",
    "DAVITT John": "davitt-john",
    "DAVOY Napua": "davoy-napua",
    "DAVSON Win": "davson-win",
    "DAW Simon": "daw-simon",
    "DAWE Bruce": "dawe-bruce",
    "DAWE Linda": "dawe-linda",
    "DAWE T J": "dawe-t-j",
    "DAWE Victoria": "dawe-victoria",
    "DAWES Adrienne": "dawes-adrienne",
    "DAWES Dan": "dawes-dan",
    "DAWES Kwame": "dawes-kwame",
    "DAWES Sean C": "dawes-sean-c",
    "DAWES Tom": "dawes-tom",
    "DAWES Tudor": "dawes-tudor",
    "DAWKINS Cecil": "dawkins-cecil",
    "DAWKINS Philip": "dawkins-philip",
    "DAWN Natasha": "dawn-natasha",
    "DAWN November": "dawn-november",
    "DAWS Josh": "daws-josh",
    "DAWS Martin": "daws-martin",
    "DAWSON Alex": "dawson-alex",
    "DAWSON Andrew": "dawson-andrew",
    "DAWSON Basil": "dawson-basil",
    "DAWSON Christopher M": "dawson-christopher-m",
    "DAWSON Daniel": "dawson-daniel",
    "DAWSON Dylan": "dawson-dylan",
    "DAWSON Gregory": "dawson-gregory",
    "DAWSON James": "dawson-james",
    "DAWSON Jennifer": "dawson-jennifer",
    "DAWSON Jonathan": "dawson-jonathan",
    "DAWSON Keith": "dawson-keith",
    "DAWSON Lizzie": "dawson-lizzie",
    "DAWSON Peter": "dawson-peter",
    "DAWSON Richard": "dawson-richard",
    "DAWSON Steven": "dawson-steven",
    "DAWSON Ted": "dawson-ted",
    "DAWSON Zoey": "dawson-zoey",
    "DAY Andy": "day-andy",
    "DAY Barbara": "day-barbara",
    "DAY Barry": "day-barry",
    "DAY Cath": "day-cath",
    "DAY Chris Cragin": "day-chris-cragin",
    "DAY Colby": "day-colby",
    "DAY Django": "day-django",
    "DAY Doris M": "day-doris-m",
    "DAY Edward": "day-edward",
    "DAY Gary L": "day-gary-l",
    "DAY Gerry": "day-gerry",
    "DAY Gregory": "day-gregory",
    "DAY Julie": "day-julie",
    "DAY Katie": "day-katie",
    "DAY Kevin": "day-kevin",
    "DAY Kingsley": "day-kingsley",
    "DAY Marc": "day-marc",
    "DAY Richard": "day-richard",
    "DAY Richard Digby": "day-richard-digby",
    "DAY Rodney": "day-rodney",
    "DAY Simon": "day-simon",
    "DAY Spencer": "day-spencer",
    "DAY Tammis": "day-tammis",
    "DAYAN Ami": "dayan-ami",
    "DAYETT Christopher": "dayett-christopher",
    "DAYLEY Grace": "dayley-grace",
    "DAYLEY K Newell": "dayley-k-newell",
    "DAYTON Katherine": "dayton-katherine",
    "DAYTOP COMPANY ": "daytop-company",
    "DE Claire": "de-claire",
    "DE Richard": "de-richard",
    "DE ABBREU Luis Alberto": "de-abbreu-luis-alberto",
    "DE ALARCON Juan Ruiz": "de-alarcon-juan-ruiz",
    "DE ALBUGUERQUE VIEIRA SANTOS FILHO Ernesto": "de-albuguerque-vieira-santos-filho-ernesto",
    "DE ALTHAUS Mariana": "de-althaus-mariana",
    "DE ANGELIS April": "de-angelis-april",
    "DE ASSERETO Laylah Muran": "de-assereto-laylah-muran",
    "DE ASSIS Joachim Maria Machado": "de-assis-joachim-maria-machado",
    "DE BAAN Peter": "de-baan-peter",
    "DE BALBIAN VERSTER Karen": "de-balbian-verster-karen",
    "DE BANZIE Graham": "de-banzie-graham",
    "DE BASSAN Eli": "de-bassan-eli",
    "DE BERGERAC Denise": "de-bergerac-denise",
    "DE BERNIERES Louis": "de-bernieres-louis",
    "DE BERRY David": "de-berry-david",
    "DE BHRUN Amy": "de-bhrun-amy",
    "DE BIE Peter": "de-bie-peter",
    "DE BISWAS Soumyak Kanti": "de-biswas-soumyak-kanti",
    "DE BLESER Karolien": "de-bleser-karolien",
    "DE BOER Lodewijk": "de-boer-lodewijk",
    "DE BOISSIERE Ralph": "de-boissiere-ralph",
    "DE BONT Ad": "de-bont-ad",
    "DE BREA Diego": "de-brea-diego",
    "DE BRI Jeda": "de-bri-jeda",
    "DE BRUYNE Charlotte": "de-bruyne-charlotte",
    "DE BURCA Seamus": "de-burca-seamus",
    "DE BUYSSER Pieter": "de-buysser-pieter",
    "DE CARDENAS Raul": "de-cardenas-raul",
    "DE CARI Gioia": "de-cari-gioia",
    "DE CARVAJAL Miguel": "de-carvajal-miguel",
    "DE CASMAKER Aron": "de-casmaker-aron",
    "DE CASTRO Angela": "de-castro-angela",
    "DE CASTRO Gilanie E": "de-castro-gilanie-e",
    "DE CASTRO Mauricio Paroni": "de-castro-mauricio-paroni",
    "DE CASTRO Thelma Virata": "de-castro-thelma-virata",
    "DE CESARE Barbara": "de-cesare-barbara",
    "DE CESPEDES Luis": "de-cespedes-luis",
    "DE CHICKERA Ruwanthie": "de-chickera-ruwanthie",
    "DE COGAIN Mairtin": "de-cogain-mairtin",
    "DE CORAS Jean": "de-coras-jean",
    "DE COURVILLE Albert": "de-courville-albert",
    "DE DADELSEN Eric": "de-dadelsen-eric",
    "DE DANSERS ": "de-dansers",
    "DE DEA Bob": "de-dea-bob",
    "DE DECKER Jaques": "de-decker-jaques",
    "DE FACTORIJ ": "de-factorij",
    "DE FEO Cecilia": "de-feo-cecilia",
    "DE FILIPPO Eduardo": "de-filippo-eduardo",
    "DE FOREST Marian": "de-forest-marian",
    "DE FRANCQUEN Leonard": "de-francquen-leonard",
    "DE GELDER Cerise": "de-gelder-cerise",
    "DE GHELDER Stephen": "de-ghelder-stephen",
    "DE GHELDERODE Michel": "de-ghelderode-michel",
    "DE GIORGI Arianna": "de-giorgi-arianna",
    "DE GIORGIO David": "de-giorgio-david",
    "DE GONDRA Borja Ortiz": "de-gondra-borja-ortiz",
    "DE GOUVEIA Philip": "de-gouveia-philip",
    "DE GRAAF Rob": "de-graaf-rob",
    "DE GRAFF Rosemary": "de-graff-rosemary",
    "DE GRAFT J C": "de-graft-j-c",
    "DE GRAZIA Edward": "de-grazia-edward",
    "DE GRE Christian": "de-gre-christian",
    "DE GREY Eliza": "de-grey-eliza",
    "DE GROEN Alma": "de-groen-alma",
    "DE GUEVARA Luis Velez": "de-guevara-luis-velez",
    "DE HARO Inigo Ramirez": "de-haro-inigo-ramirez",
    "DE HARTOG Jan": "de-hartog-jan",
    "DE HELEN Sandra": "de-helen-sandra",
    "DE HENNEZEL Maria": "de-hennezel-maria",
    "DE JESUS Carmen": "de-jesus-carmen",
    "DE JONG Lisette": "de-jong-lisette",
    "DE JONGH James": "de-jongh-james",
    "DE JONGH Nicholas": "de-jongh-nicholas",
    "DE KATER Sofieke": "de-kater-sofieke",
    "DE KERVENO Yann Le Gouic": "de-kerveno-yann-le-gouic",
    "DE KEYSER Pia": "de-keyser-pia",
    "DE KEYZER Aaron": "de-keyzer-aaron",
    "DE KLER Glenn": "de-kler-glenn",
    "DE LA CHENELIERE Evelyne": "de-la-cheneliere-evelyne",
    "DE LA CONCHA Marc": "de-la-concha-marc",
    "DE LA CRUZ Alison": "de-la-cruz-alison",
    "DE LA CRUZ Sor Juana Ines": "de-la-cruz-sor-juana-ines",
    "DE LA FUENTE Olga": "de-la-fuente-olga",
    "DE LA LOMBANA Luis Carlos": "de-la-lombana-luis-carlos",
    "DE LA LUZ Caridad": "de-la-luz-caridad",
    "DE LA PARA Antonio": "de-la-para-antonio",
    "DE LA PARRA Lorena": "de-la-parra-lorena",
    "DE LA PARRA Marco Antonio": "de-la-parra-marco-antonio",
    "DE LA PUENTE Noemi": "de-la-puente-noemi",
    "DE LA RIVA Yadira": "de-la-riva-yadira",
    "DE LA TORRE MULHARE Mirta": "de-la-torre-mulhare-mirta",
    "DE LA TOUR Andy": "de-la-tour-andy",
    "DE LACY Ian": "de-lacy-ian",
    "DE LAIGLESIA Alvaro": "de-laiglesia-alvaro",
    "DE LARA Aminta": "de-lara-aminta",
    "DE LARA Marita": "de-lara-marita",
    "DE LARIA Lea": "de-laria-lea",
    "DE LISO Debra": "de-liso-debra",
    "DE LONG Richard C": "de-long-richard-c",
    "DE LORDE Andre": "de-lorde-andre",
    "DE LOTBINIERE-HARWOOD Susanne": "de-lotbiniere-harwood-susanne",
    "DE LUBICZ-MILOSZ Oscar V": "de-lubicz-milosz-oscar-v",
    "DE LUCA Angela": "de-luca-angela",
    "DE LUCA Bill": "de-luca-bill",
    "DE LUCA Michael": "de-luca-michael",
    "DE LUCIA Amy": "de-lucia-amy",
    "DE LUNA Fred": "de-luna-fred",
    "DE MARNE Dennis": "de-marne-dennis",
    "DE MATATIA ABOAB Isaac": "de-matatia-aboab-isaac",
    "DE MATTEO Donna": "de-matteo-donna",
    "DE MAY Phillip": "de-may-phillip",
    "DE MELO Wolfgang": "de-melo-wolfgang",
    "DE MENDONCA Guilherme": "de-mendonca-guilherme",
    "DE MOLINA Tirso": "de-molina-tirso",
    "DE MONTHERLANT Henry": "de-montherlant-henry",
    "DE MORAES Paulo": "de-moraes-paulo",
    "DE MORATIN Leandro Fernandez": "de-moratin-leandro-fernandez",
    "DE MORGAN Grace": "de-morgan-grace",
    "DE MUSSET Alfred": "de-musset-alfred",
    "DE NAJAC Emile": "de-najac-emile",
    "DE NASCIEMENTO Emmanuel": "de-nasciemento-emmanuel",
    "DE OBALDIA Rene": "de-obaldia-rene",
    "DE OLIVEIRA Eddie": "de-oliveira-eddie",
    "DE PALMA Toni": "de-palma-toni",
    "DE PAOLA Christopher": "de-paola-christopher",
    "DE PENA Aurora Stewart": "de-pena-aurora-stewart",
    "DE PERROT Dimitri": "de-perrot-dimitri",
    "DE PINNA David": "de-pinna-david",
    "DE PIXERECOURT Rene-Charles Guilbert": "de-pixerecourt-rene-charles-guilbert",
    "DE PONTCHARRA Natacha": "de-pontcharra-natacha",
    "DE RAMUS Betty": "de-ramus-betty",
    "DE ROEST Sam": "de-roest-sam",
    "DE ROJAS Fernando": "de-rojas-fernando",
    "DE ROOS Michael": "de-roos-michael",
    "DE ROURE Rodrigo": "de-roure-rodrigo",
    "DE RUEDA Lope": "de-rueda-lope",
    "DE S PINTO V": "de-s-pinto-v",
    "DE SADE Marquis": "de-sade-marquis",
    "DE SANTIS Edmund": "de-santis-edmund",
    "DE SANTOS Jose Luis Alonso": "de-santos-jose-luis-alonso",
    "DE SAVIGNE Faith": "de-savigne-faith",
    "DE SCHUTTER Marjan": "de-schutter-marjan",
    "DE SHIELDS Andre": "de-shields-andre",
    "DE SILVA David": "de-silva-david",
    "DE SILVA Mark Beau": "de-silva-mark-beau",
    "DE SILVA Sanjit": "de-silva-sanjit",
    "DE SIMONE Joanne": "de-simone-joanne",
    "DE SLOOVER Karl": "de-sloover-karl",
    "DE SMET Johan": "de-smet-johan",
    "DE SMITH Alice": "de-smith-alice",
    "DE SOLEIL Baraka": "de-soleil-baraka",
    "DE SOMERE Sophie": "de-somere-sophie",
    "DE SOUSA Alice": "de-sousa-alice",
    "DE SOUSA Xavier": "de-sousa-xavier",
    "DE SOUZA Douglas": "de-souza-douglas",
    "DE SOUZA Jodi": "de-souza-jodi",
    "DE STAIC Aindrias": "de-staic-aindrias",
    "DE STOPPANI Bindu": "de-stoppani-bindu",
    "DE SYLVA Buddy": "de-sylva-buddy",
    "DE TIENNE Patti": "de-tienne-patti",
    "DE TOURDONNET Vincent": "de-tourdonnet-vincent",
    "DE TURK Scott": "de-turk-scott",
    "DE VALDIVIELSO Josef": "de-valdivielso-josef",
    "DE VEGA Lope": "de-vega-lope",
    "DE VERE WHITE Terence": "de-vere-white-terence",
    "DE VILLIERS Dirk": "de-villiers-dirk",
    "DE VILLIERS Gys": "de-villiers-gys",
    "DE VILLIERS Jaci": "de-villiers-jaci",
    "DE VITO Shelly": "de-vito-shelly",
    "DE VOS Remi": "de-vos-remi",
    "DE VRIES Marion": "de-vries-marion",
    "DE VRIES Peter": "de-vries-peter",
    "DE WAAL Erik": "de-waal-erik",
    "DE WAAL Kit": "de-waal-kit",
    "DE WALD Jenn": "de-wald-jenn",
    "DE WET Cindy": "de-wet-cindy",
    "DE WET Reza": "de-wet-reza",
    "DE WITT Alex": "de-witt-alex",
    "DE WITT WALSH Thomas": "de-witt-walsh-thomas",
    "DE WOLF Cecilia": "de-wolf-cecilia",
    "DE WULF Wim": "de-wulf-wim",
    "DE YOUNG Dennis": "de-young-dennis",
    "DEABLER Justin": "deabler-justin",
    "DEACON James": "deacon-james",
    "DEACON Robin": "deacon-robin",
    "DEACON Simon": "deacon-simon",
    "DEAD CENTRE ": "dead-centre",
    "DEAD FACE ": "dead-face",
    "DEAD LEAF ": "dead-leaf",
    "DEADMAN R": "deadman-r",
    "DEAFINITELY THEATRE ": "deafinitely-theatre",
    "DEAK Ernie": "deak-ernie",
    "DEAKIN Emma": "deakin-emma",
    "DEAKIN Michael": "deakin-michael",
    "DEAKIN Paul": "deakin-paul",
    "DEAKIN Richard": "deakin-richard",
    "DEAL Dennis": "deal-dennis",
    "DEALE Kenneth E L": "deale-kenneth-e-l",
    "DEALEY Maggie": "dealey-maggie",
    "DEALLY Philip": "deally-philip",
    "DE'ALTRY Rachel": "de-altry-rachel",
    "DEAMER Dulcie": "deamer-dulcie",
    "DEAN Aaron": "dean-aaron",
    "DEAN Emma": "dean-emma",
    "DEAN Eva": "dean-eva",
    "DEAN Gabriel Jason": "dean-gabriel-jason",
    "DEAN Jack": "dean-jack",
    "DEAN Jason": "dean-jason",
    "DEAN John Hugh": "dean-john-hugh",
    "DEAN Julia Lee": "dean-julia-lee",
    "DEAN Kate": "dean-kate",
    "DEAN Kristopher": "dean-kristopher",
    "DEAN Laura Jane": "dean-laura-jane",
    "DEAN Leamond": "dean-leamond",
    "DEAN Marina": "dean-marina",
    "DEAN Marla": "dean-marla",
    "DEAN Nancy": "dean-nancy",
    "DEAN Philip": "dean-philip",
    "DEAN Phillip Hayes": "dean-phillip-hayes",
    "DEAN Russell": "dean-russell",
    "DEAN Sally": "dean-sally",
    "DEAN Tyler": "dean-tyler",
    "DEAN Uther": "dean-uther",
    "DEAN-BAHAM Angela": "dean-baham-angela",
    "DEANDA Peter": "deanda-peter",
    "DEANDREA Josiah": "deandrea-josiah",
    "DEANE Bridget": "deane-bridget",
    "DEANE Hamilton": "deane-hamilton",
    "DEANE Kadeem": "deane-kadeem",
    "DEANELLO Peter": "deanello-peter",
    "DEANGELIS J Michael": "deangelis-j-michael",
    "DEANS Christopher": "deans-christopher",
    "DEANS M J": "deans-m-j",
    "DEANS Mark": "deans-mark",
    "DEAR Nick": "dear-nick",
    "DEAR Terry": "dear-terry",
    "DEARBORN Rob": "dearborn-rob",
    "DEARDEN Harold": "dearden-harold",
    "DEARDEN James": "dearden-james",
    "DEARDEN Layne": "dearden-layne",
    "DEARING Annabel": "dearing-annabel",
    "DEARING Sally": "dearing-sally",
    "DEARLOVE David": "dearlove-david",
    "DEARS Emma": "dears-emma",
    "DEARSLEY A P": "dearsley-a-p",
    "DEARY Terry": "deary-terry",
    "DEASE Rachael": "dease-rachael",
    "DEASY Frank": "deasy-frank",
    "DEATH DEFYING THEATRE ": "death-defying-theatre",
    "DEATON Boyce Logan": "deaton-boyce-logan",
    "DEAZLEY Treena": "deazley-treena",
    "DEB'BORA ": "deb-bora",
    "DEBESSONET Lear": "debessonet-lear",
    "DEBISWAS Soumyak Kanti": "debiswas-soumyak-kanti",
    "DEBOY David": "deboy-david",
    "DECAMP Dot": "decamp-dot",
    "DECANEY Maria": "decaney-maria",
    "DECARLO Chris": "decarlo-chris",
    "DECARLO Elisa": "decarlo-elisa",
    "DECENT Campion": "decent-campion",
    "DECESARE Stephen": "decesare-stephen",
    "DECESARIS Janet": "decesaris-janet",
    "DECHANEL Adam": "dechanel-adam",
    "DECHARY Jenet Lynn": "dechary-jenet-lynn",
    "DECHERY Chloe": "dechery-chloe",
    "DECHRISTOPHER Dave": "dechristopher-dave",
    "DECKER Keith": "decker-keith",
    "DECKER Scott": "decker-scott",
    "DECKER Tom": "decker-tom",
    "DECOTTIGNIES Michelle": "decottignies-michelle",
    "DECOY Robert H": "decoy-robert-h",
    "DECROCE Seth": "decroce-seth",
    "DECTER Matthew": "decter-matthew",
    "DEDEAUX Richard": "dedeaux-richard",
    "DEDES Kevin": "dedes-kevin",
    "DEDOMENICI Richard": "dedomenici-richard",
    "DEE Angela": "dee-angela",
    "DEE Eamonn": "dee-eamonn",
    "DEE Peter": "dee-peter",
    "DEE Ronnie": "dee-ronnie",
    "DEE Ruby": "dee-ruby",
    "DEE Sylvia": "dee-sylvia",
    "DEEFHOLTS Simon": "deefholts-simon",
    "DEEGAN Denise": "deegan-denise",
    "DEEGAN Loughlin": "deegan-loughlin",
    "DEEMAR Stacy": "deemar-stacy",
    "DEEMER Charles": "deemer-charles",
    "DEEMER Joe": "deemer-joe",
    "DEEN Mashuq Mushtag": "deen-mashuq-mushtag",
    "DEEP Michael": "deep-michael",
    "DEER Maxine": "deer-maxine",
    "DEER Sandra": "deer-sandra",
    "DEERING Andrew": "deering-andrew",
    "DEERING Sally": "deering-sally",
    "DEERING Spencer": "deering-spencer",
    "DEETHARDT John": "deethardt-john",
    "DEEVY Teresa": "deevy-teresa",
    "DEFAZIO Alex": "defazio-alex",
    "DEFELICE James": "defelice-james",
    "DEFERIE Steph": "deferie-steph",
    "DEFFAA Chip": "deffaa-chip",
    "DEFOE Ty": "defoe-ty",
    "DEFOREST Raymond": "deforest-raymond",
    "DEFOREST Walter": "deforest-walter",
    "DEFORME Lori": "deforme-lori",
    "DEGADILLO JR Efren": "degadillo-jr-efren",
    "DEGAETANO Dominick": "degaetano-dominick",
    "DEGAETANO John": "degaetano-john",
    "DEGIORGIO David": "degiorgio-david",
    "DEGNAN Laura": "degnan-laura",
    "DEHAAS John B": "dehaas-john-b",
    "DEHAAS Lisi": "dehaas-lisi",
    "DEHN Paul": "dehn-paul",
    "DEHNERT Amanda": "dehnert-amanda",
    "DEIGHAN Steve": "deighan-steve",
    "DEIHIM Susan": "deihim-susan",
    "DEIKE Taggart": "deike-taggart",
    "DEIKER Tom": "deiker-tom",
    "DEIR Puelo": "deir-puelo",
    "DEISS Paul": "deiss-paul",
    "DEJOHN Paul": "dejohn-paul",
    "DEJONGH James": "dejongh-james",
    "DEJORAS Sara": "dejoras-sara",
    "DEJOSIA Francesca": "dejosia-francesca",
    "DEKEL Ayelet": "dekel-ayelet",
    "DEKKERS-REIHANA Neenah": "dekkers-reihana-neenah",
    "DEL Ramon": "del-ramon",
    "DEL AGUILA Kevin": "del-aguila-kevin",
    "DEL GRANDE Louis": "del-grande-louis",
    "DEL GRECO Marcus": "del-greco-marcus",
    "DEL MORAL Ignacio": "del-moral-ignacio",
    "DEL NERO Carlos": "del-nero-carlos",
    "DEL RIO Bobby": "del-rio-bobby",
    "DEL ROBLE-DUCHESNE Coralie": "del-roble-duchesne-coralie",
    "DEL ROSSO Kathy": "del-rosso-kathy",
    "DEL ROSSO Lisa": "del-rosso-lisa",
    "DEL VALE Peter": "del-vale-peter",
    "DEL VALLE Elaine": "del-valle-elaine",
    "DEL VALLE Janis Astor": "del-valle-janis-astor",
    "DEL VALLE Peter": "del-valle-peter",
    "DEL VECCHIO John": "del-vecchio-john",
    "DELABBIO Dan": "delabbio-dan",
    "DELACOUR Alfred": "delacour-alfred",
    "DELAGUILA Kevin": "delaguila-kevin",
    "DE-LAHAY Rachel": "de-lahay-rachel",
    "DELAHOY Craig": "delahoy-craig",
    "DELAHUNTY Sarah": "delahunty-sarah",
    "DELAMARE Susan": "delamare-susan",
    "DELAMONTE Mike": "delamonte-mike",
    "DELAMOTTE Roy C": "delamotte-roy-c",
    "DELANCEY Craig": "delancey-craig",
    "DELANCY Dale": "delancy-dale",
    "DELANEY Betsy Marks": "delaney-betsy-marks",
    "DELANEY Bryan": "delaney-bryan",
    "DELANEY Cat": "delaney-cat",
    "DELANEY Charlotte": "delaney-charlotte",
    "DELANEY Doug": "delaney-doug",
    "DELANEY Jason": "delaney-jason",
    "DELANEY Linda Bidwell": "delaney-linda-bidwell",
    "DELANEY Mary": "delaney-mary",
    "DELANEY Paul": "delaney-paul",
    "DELANEY Shelagh": "delaney-shelagh",
    "DELANEY Talaya": "delaney-talaya",
    "DELANEY Vincent": "delaney-vincent",
    "DELANEY-WINN Tucker": "delaney-winn-tucker",
    "DELAPLIAINE Andrew": "delapliaine-andrew",
    "DELAPPE Sarah": "delappe-sarah",
    "DELAROZIERE Francoise": "delaroziere-francoise",
    "DELATORI Cecilia": "delatori-cecilia",
    "DELAUHTNY Sarah": "delauhtny-sarah",
    "DELAUP Typhaine": "delaup-typhaine",
    "DELAURIER Peter": "delaurier-peter",
    "DELBO Charlotte": "delbo-charlotte",
    "DELDERFIELD R F": "delderfield-r-f",
    "DELEAGE Emmanuel": "deleage-emmanuel",
    "DELEHANTY Nick": "delehanty-nick",
    "DELEO Bernie": "deleo-bernie",
    "DELESTON Kathleen": "deleston-kathleen",
    "DELFORES Clayelle": "delfores-clayelle",
    "DELFOSO Anna-Maria": "delfoso-anna-maria",
    "DELGADO Alan": "delgado-alan",
    "DELGADO Maria M": "delgado-maria-m",
    "DELGADO Ramon": "delgado-ramon",
    "DELGADO Sandra": "delgado-sandra",
    "DELIA Adam": "delia-adam",
    "D'ELIA Tina": "d-elia-tina",
    "DELIBERATE MOTION ": "deliberate-motion",
    "DELILKAN Sharu": "delilkan-sharu",
    "DELILLO Don": "delillo-don",
    "DELIO Renee": "delio-renee",
    "DELIRIOUS THEATRE COMPANY ": "delirious-theatre-company",
    "DELIRIUM ": "delirium",
    "DELISLE Jeanne-Mance": "delisle-jeanne-mance",
    "DELIZZA Julie": "delizza-julie",
    "DELL Henry": "dell-henry",
    "DELL Jack Holton": "dell-jack-holton",
    "DELLA FAZIA Alba": "della-fazia-alba",
    "DELLA VENTURA Mark": "della-ventura-mark",
    "DELLACEY John": "dellacey-john",
    "DELLAGIARINO Lisa": "dellagiarino-lisa",
    "DELL'ANGELO Tabitha": "dell-angelo-tabitha",
    "DELLAPINA Matthew": "dellapina-matthew",
    "DELLAPINA Ron": "dellapina-ron",
    "DELLA-PORTA Isabel": "della-porta-isabel",
    "DELL'ARTE COMPANY ": "dell-arte-company",
    "DELLIMORE Craig": "dellimore-craig",
    "D'ELLOSO Anna Maria": "d-elloso-anna-maria",
    "DELMAN Norbert": "delman-norbert",
    "DELMAR Anton": "delmar-anton",
    "DELMAR Vina": "delmar-vina",
    "DELMATTEO Chip": "delmatteo-chip",
    "DELMONT James Paul": "delmont-james-paul",
    "DELONG Chuck": "delong-chuck",
    "DELOPOLUS Eleni": "delopolus-eleni",
    "DELORENZO Christine Stevens": "delorenzo-christine-stevens",
    "DELORIO Victoria": "delorio-victoria",
    "DELOTTE-BENNETT Margaux": "delotte-bennett-margaux",
    "DELUCA Maria": "deluca-maria",
    "DELUCA Stuart": "deluca-stuart",
    "DELUXE Steve": "deluxe-steve",
    "DELVES Stuart": "delves-stuart",
    "DELZELL Ruthe": "delzell-ruthe",
    "DEMAIO Amanda Tischer": "demaio-amanda-tischer",
    "DEMAN Peter": "deman-peter",
    "DEMAREST Janet Emily": "demarest-janet-emily",
    "DEMARIA Janine Magan": "demaria-janine-magan",
    "DEMARSE James": "demarse-james",
    "DEMARTINO Ty": "demartino-ty",
    "DEMAS George": "demas-george",
    "DEMAYO Amelia": "demayo-amelia",
    "DEMAYO Devon": "demayo-devon",
    "DEMAYO Mark": "demayo-mark",
    "DEMBINA Ivor": "dembina-ivor",
    "DEMBOWSKI Elizabeth": "dembowski-elizabeth",
    "DEMCHUK David": "demchuk-david",
    "DEMENKOFF Tom": "demenkoff-tom",
    "DEMENT Elizabeth": "dement-elizabeth",
    "DEMEO Michael": "demeo-michael",
    "DEMERS Sean David": "demers-sean-david",
    "DEMETRIOS Eames": "demetrios-eames",
    "DEMEUR Tony": "demeur-tony",
    "DEMIAN ": "demian",
    "D'EMILIA Dani": "d-emilia-dani",
    "DEMING Sean": "deming-sean",
    "DEMOPOULOS Alaina Rose": "demopoulos-alaina-rose",
    "DEMOS Nick": "demos-nick",
    "DEMOS-BROWN Christopher": "demos-brown-christopher",
    "DEMOSS Tomas": "demoss-tomas",
    "DEMOTT Dan H": "demott-dan-h",
    "DEMPSEY John": "dempsey-john",
    "DEMPSEY Katie": "dempsey-katie",
    "DEMPSEY Martyn": "dempsey-martyn",
    "DEMPSEY Mike": "dempsey-mike",
    "DEMPSEY Ro": "dempsey-ro",
    "DEMPSEY Sandra": "dempsey-sandra",
    "DEMPSEY Shawna": "dempsey-shawna",
    "DEMPSTER Alicia": "dempster-alicia",
    "DEMPSTER Curt": "dempster-curt",
    "DEN HARTOG Anna": "den-hartog-anna",
    "DEN HOLLANDER Jung Sun": "den-hollander-jung-sun",
    "DEN TEX Charles": "den-tex-charles",
    "DENBAUM Drew": "denbaum-drew",
    "DENBY Alan": "denby-alan",
    "DENDINGER Emily": "dendinger-emily",
    "DENDY III J Brooks": "dendy-iii-j-brooks",
    "DENEULIN Luc": "deneulin-luc",
    "DENEVI Marco": "denevi-marco",
    "DENFHY Wayne": "denfhy-wayne",
    "DENFORD Harry": "denford-harry",
    "DENFORD Jocelyn": "denford-jocelyn",
    "DENG Ezeldin": "deng-ezeldin",
    "DENHAM Arnold": "denham-arnold",
    "DENHAM Christopher": "denham-christopher",
    "DENHAM John": "denham-john",
    "DENHAM Lilian": "denham-lilian",
    "DENHAM Peter": "denham-peter",
    "DENHAM Reginald": "denham-reginald",
    "DENHOLTZ Elaine G": "denholtz-elaine-g",
    "DENICOFF Marvin": "denicoff-marvin",
    "DENISON Merrill": "denison-merrill",
    "DENISOV Viktor": "denisov-viktor",
    "DENK Charles E": "denk-charles-e",
    "DENKER Henry": "denker-henry",
    "DENMAN Dody": "denman-dody",
    "DENMAN Jeffry": "denman-jeffry",
    "DENMAN Peter": "denman-peter",
    "DENMAN Stan": "denman-stan",
    "DENMAN Stuart": "denman-stuart",
    "DENN Jon": "denn-jon",
    "DENNEN Barry": "dennen-barry",
    "DENNING Sylvia": "denning-sylvia",
    "DENNIS Charles": "dennis-charles",
    "DENNIS Christopher": "dennis-christopher",
    "DENNIS CJ": "dennis-cj",
    "DENNIS Dan": "dennis-dan",
    "DENNIS Darrell": "dennis-darrell",
    "DENNIS Kip": "dennis-kip",
    "DENNIS Les": "dennis-les",
    "DENNIS Lin": "dennis-lin",
    "DENNIS Michael": "dennis-michael",
    "DENNIS Nigel": "dennis-nigel",
    "DENNIS Richard": "dennis-richard",
    "DENNIS Robert": "dennis-robert",
    "DENNIS Ron": "dennis-ron",
    "DENNIS Rosie": "dennis-rosie",
    "DENNIS Steven": "dennis-steven",
    "DENNIS Tony": "dennis-tony",
    "DENNIS Vita": "dennis-vita",
    "DENNISON George": "dennison-george",
    "DENNISON Joe": "dennison-joe",
    "DENNISTON Christine": "denniston-christine",
    "DENNY Janet": "denny-janet",
    "DENNYS Joyce": "dennys-joyce",
    "DENOON Christine": "denoon-christine",
    "DENROSE Erik": "denrose-erik",
    "DENSLEY Kevin": "densley-kevin",
    "DENSON Wil": "denson-wil",
    "DENT Anthony": "dent-anthony",
    "DENT Chuck": "dent-chuck",
    "DENT Edward J": "dent-edward-j",
    "DENT Jonathan Louis": "dent-jonathan-louis",
    "DENT Tom": "dent-tom",
    "DENTATO John": "dentato-john",
    "DENTE Eric C": "dente-eric-c",
    "DENTON Annie Periam": "denton-annie-periam",
    "DENTON Deon": "denton-deon",
    "DENTON Nell": "denton-nell",
    "DENTON Tim": "denton-tim",
    "DENTON-DAVIS Browen": "denton-davis-browen",
    "D'ENTREMONT James": "d-entremont-james",
    "DENU Mark": "denu-mark",
    "DENUSZEK J Marshall": "denuszek-j-marshall",
    "DENVER Jo": "denver-jo",
    "DENVER Peter": "denver-peter",
    "DENVER Simon": "denver-simon",
    "DENYER Heather": "denyer-heather",
    "DENYER Peter": "denyer-peter",
    "DENYER Sean": "denyer-sean",
    "DENYS Chris": "denys-chris",
    "DEOL Jaz": "deol-jaz",
    "DEPAUL Frank": "depaul-frank",
    "DEPAUL Greg": "depaul-greg",
    "DEPHILLIPS Natalina": "dephillips-natalina",
    "DEPIANO Hillary": "depiano-hillary",
    "DEPIETRO Peter": "depietro-peter",
    "DEPINTO Kent": "depinto-kent",
    "DEPOTTIE Gordon": "depottie-gordon",
    "DEPPE Ethan": "deppe-ethan",
    "DEPROOST Steven": "deproost-steven",
    "DERATANY Jay Paul": "deratany-jay-paul",
    "DERBY Dan": "derby-dan",
    "DERBYSHIRE Geraint": "derbyshire-geraint",
    "DERBYSHIRE Harry": "derbyshire-harry",
    "DERBYSHIRE J D": "derbyshire-j-d",
    "DERBYSHIRE J L": "derbyshire-j-l",
    "DERBYSHIRE Jan": "derbyshire-jan",
    "DERBYSHIRE John": "derbyshire-john",
    "DEREVO ": "derevo",
    "DERFNER Joel": "derfner-joel",
    "DERIU Laura": "deriu-laura",
    "DERMAN Alexa": "derman-alexa",
    "DERMAN Derya": "derman-derya",
    "DERMODY Scott": "dermody-scott",
    "DEROCERS Rick": "derocers-rick",
    "DEROCHEA Beth": "derochea-beth",
    "DEROCHER Laura": "derocher-laura",
    "DERREBERRY Caleigh": "derreberry-caleigh",
    "DERRETT Bridget": "derrett-bridget",
    "DERRICK Clyde": "derrick-clyde",
    "DERRICK Daphne": "derrick-daphne",
    "DERRINGER William": "derringer-william",
    "DERRY Alex": "derry-alex",
    "DERRY Charles": "derry-charles",
    "DERSOFI Nancy": "dersofi-nancy",
    "DERVISHI Teki": "dervishi-teki",
    "DERWENT A D": "derwent-a-d",
    "DESAI Snehal": "desai-snehal",
    "DESALVO Anne": "desalvo-anne",
    "DESAUTELS Brian": "desautels-brian",
    "DESCALZO Jose Luis Martin": "descalzo-jose-luis-martin",
    "DESCHAMPS Jerome": "deschamps-jerome",
    "DESENA John Paul": "desena-john-paul",
    "DESENA Paul": "desena-paul",
    "DESHPANDE Gauri": "deshpande-gauri",
    "DESILVA Buddy G": "desilva-buddy-g",
    "DESILVA Mark Beau": "desilva-mark-beau",
    "DESILVA Sanjit": "desilva-sanjit",
    "DESISTO A Michael": "desisto-a-michael",
    "DESLEAL Alvaro Menen": "desleal-alvaro-menen",
    "DESLOOVERE Martin": "desloovere-martin",
    "DESMARAIS Freya": "desmarais-freya",
    "DESMARTEAU Alicia": "desmarteau-alicia",
    "DESMON Jeremy": "desmon-jeremy",
    "DESMOND Brian": "desmond-brian",
    "DESNOS Robert": "desnos-robert",
    "DESOKEY Monir": "desokey-monir",
    "DESPAIN Lisa": "despain-lisa",
    "DESPREZ Ross": "desprez-ross",
    "DESROCHRES Nadine": "desrochres-nadine",
    "DESSAIX Robert": "dessaix-robert",
    "DESSCA Yves": "dessca-yves",
    "DESSNER Aaron": "dessner-aaron",
    "DESSNER Bryce": "dessner-bryce",
    "DESTEFANO Joe": "destefano-joe",
    "DESTEFANO Lorenzo": "destefano-lorenzo",
    "DESTEFANO Mike": "destefano-mike",
    "DESTOUCHES Phillippe Nericault": "destouches-phillippe-nericault",
    "DESVALLIERES Maurice": "desvallieres-maurice",
    "DESVIGNES Rejane": "desvignes-rejane",
    "DESYLVA B G": "desylva-b-g",
    "DETHRIDGE Lisa": "dethridge-lisa",
    "DETKOV Alexander": "detkov-alexander",
    "DETRICK Erin": "detrick-erin",
    "DETTELBACH Cindy": "dettelbach-cindy",
    "DETTMAN Robyn": "dettman-robyn",
    "DETURK Scott": "deturk-scott",
    "DEUPREE Daiva": "deupree-daiva",
    "DEUTSCH E K": "deutsch-e-k",
    "DEUTSCH Troy": "deutsch-troy",
    "DEVA Ramachandra": "deva-ramachandra",
    "DEVAL Jacques": "deval-jacques",
    "DEVANEY Christine": "devaney-christine",
    "DEVANEY Doug": "devaney-doug",
    "DEVANEY Kacie": "devaney-kacie",
    "DEVANEY Karen": "devaney-karen",
    "DEVANEY Pauline": "devaney-pauline",
    "DEVANY Edward": "devany-edward",
    "DEVANY Victoria": "devany-victoria",
    "DEVARON Tina": "devaron-tina",
    "DEVDARIANI Dimitri": "devdariani-dimitri",
    "DEVEAU David": "deveau-david",
    "DEVEAUX Alexis": "deveaux-alexis",
    "DEVELLARD Jean-Paul": "devellard-jean-paul",
    "DEVENIE Laurel": "devenie-laurel",
    "DEVENISH Luke": "devenish-luke",
    "DEVEREAUX Matthew": "devereaux-matthew",
    "DEVEREAUX Michael": "devereaux-michael",
    "DEVERELL Rex": "deverell-rex",
    "DEVEREUX Andrew": "devereux-andrew",
    "DEVEREUX Isabelle": "devereux-isabelle",
    "DEVI Mahasweta": "devi-mahasweta",
    "DEVILLE Abigail": "deville-abigail",
    "DEVIL'S VIOLIN ": "devils-violin",
    "DEVIN Alexandra": "devin-alexandra",
    "DEVIN Denise": "devin-denise",
    "DEVIN Diane": "devin-diane",
    "DEVIN Tristan": "devin-tristan",
    "DEVIN Z J": "devin-z-j",
    "DEVINE Alicia": "devine-alicia",
    "DEVINE Art": "devine-art",
    "DEVINE Jerry": "devine-jerry",
    "DEVIOUS THEATRE COMPANY ": "devious-theatre-company",
    "DEVITA Doug": "devita-doug",
    "DEVITA James": "devita-james",
    "DEVITO Michael": "devito-michael",
    "DEVITT Marian": "devitt-marian",
    "DEVLIN Anne": "devlin-anne",
    "DEVLIN Brian": "devlin-brian",
    "DEVLIN Graham": "devlin-graham",
    "DEVLIN Terry": "devlin-terry",
    "DEVNEY Sean": "devney-sean",
    "DEVON Alexandra": "devon-alexandra",
    "DEVONALD Angharad": "devonald-angharad",
    "DEVORAH Miriam": "devorah-miriam",
    "DEVORE John": "devore-john",
    "DEVOTI Emily": "devoti-emily",
    "DEVOY Jane": "devoy-jane",
    "DEVRIENDT Alexander": "devriendt-alexander",
    "DEVRIES Peter": "devries-peter",
    "DEWAAL Jo": "dewaal-jo",
    "DEWAN Christopher": "dewan-christopher",
    "DEWAN Joseph A": "dewan-joseph-a",
    "DEWAN Veronica": "dewan-veronica",
    "DEWAR Ian": "dewar-ian",
    "DEWBERRY Elizabeth": "dewberry-elizabeth",
    "DEWELL Michael": "dewell-michael",
    "DEWESTER Nanette": "dewester-nanette",
    "DEWEY Donald": "dewey-donald",
    "DEWEY Priscilla B": "dewey-priscilla-b",
    "DEWEY Sheila": "dewey-sheila",
    "DEWEY Tommy": "dewey-tommy",
    "DEWHURST Keith": "dewhurst-keith",
    "DEWINDT Hal": "dewindt-hal",
    "DEWITT Alex": "dewitt-alex",
    "DEWITT David": "dewitt-david",
    "DEWITT Patrick": "dewitt-patrick",
    "DEXTER Colin": "dexter-colin",
    "DEXTER Harriet": "dexter-harriet",
    "DEXTER Paul": "dexter-paul",
    "DEXTER Stephanie-elise": "dexter-stephanie-elise",
    "DEXTER Steven": "dexter-steven",
    "DEY Brent": "dey-brent",
    "DEY Claudia": "dey-claudia",
    "DEY James Paul": "dey-james-paul",
    "DEY Tim": "dey-tim",
    "DEYOUNG Dennis": "deyoung-dennis",
    "DEYOUNG Karyn Joy": "deyoung-karyn-joy",
    "DEYOUNG Marissa": "deyoung-marissa",
    "DEZFOULI Liza": "dezfouli-liza"
  }
};