export default {
  "metadata": {
    "results": 338,
    "timeStamp": "2025-12-05T21:23:46.189Z",
    "url": "https://www.doollee.com/PlaywrightsD/D_playwrights_g-l.php"
  },
  "authors": {
    "DHAENENS Valentijn": "dhaenens-valentijn",
    "DHALIWAL Amrita": "dhaliwal-amrita",
    "D'HARNONCOURT Everard": "d-harnoncourt-everard",
    "DHAWAN Ashanti": "dhawan-ashanti",
    "DHERY Robert": "dhery-robert",
    "DHINGRA Dolly": "dhingra-dolly",
    "DHONDY Danyal": "dhondy-danyal",
    "DHONDY Farrukh": "dhondy-farrukh",
    "DHYANNA ": "dhyanna",
    "DI Bia": "di-bia",
    "DI CANZIO William": "di-canzio-william",
    "DI CERTO Bridget": "di-certo-bridget",
    "DI CESARE Eva": "di-cesare-eva",
    "DI CIACCA John Mark": "di-ciacca-john-mark",
    "DI CINTIO Matt": "di-cintio-matt",
    "DI FONZO Benito": "di-fonzo-benito",
    "DI GIROLAMO Emilia": "di-girolamo-emilia",
    "DI GUGLIELMO Carmelina": "di-guglielmo-carmelina",
    "DI MAMBRO Ann Marie": "di-mambro-ann-marie",
    "DI MAMBRO Daniella": "di-mambro-daniella",
    "DI MILO Leroi B": "di-milo-leroi-b",
    "DI PAOLO Matt": "di-paolo-matt",
    "DI PASQUA Tim": "di-pasqua-tim",
    "DI PIERO W S": "di-piero-w-s",
    "DI SUVERO Henry": "di-suvero-henry",
    "DIAAB Jahidah": "diaab-jahidah",
    "DIAL Lawrence": "dial-lawrence",
    "DIAMANT Anita": "diamant-anita",
    "DIAMANTI C": "diamanti-c",
    "DIAMENT Mario": "diament-mario",
    "DIAMOND Betty": "diamond-betty",
    "DIAMOND Daniel": "diamond-daniel",
    "DIAMOND Dick": "diamond-dick",
    "DIAMOND Elizabeth": "diamond-elizabeth",
    "DIAMOND Eric": "diamond-eric",
    "DIAMOND J Lois": "diamond-j-lois",
    "DIAMOND James": "diamond-james",
    "DIAMOND Leonard": "diamond-leonard",
    "DIAMOND Lydia R": "diamond-lydia-r",
    "DIAMOND Marc": "diamond-marc",
    "DIAMOND Michael": "diamond-michael",
    "DIAMOND Noah": "diamond-noah",
    "DIAMOND Ronni A": "diamond-ronni-a",
    "DIAMOND Sarah": "diamond-sarah",
    "DIAMOND Sarah C": "diamond-sarah-c",
    "DIAMOND Terence": "diamond-terence",
    "DIAMOND Theresa M": "diamond-theresa-m",
    "DIANA Raffaella": "diana-raffaella",
    "DIANA Troy": "diana-troy",
    "DIANTONIO Michael": "diantonio-michael",
    "DIAS Annalisa": "dias-annalisa",
    "DIAS Earl J": "dias-earl-j",
    "DIAS Gary": "dias-gary",
    "DIAS Jay": "dias-jay",
    "DIAZ Alberto Villarreal": "diaz-alberto-villarreal",
    "DIAZ David": "diaz-david",
    "DIAZ Dolores": "diaz-dolores",
    "DIAZ Haydn": "diaz-haydn",
    "DIAZ Ivan": "diaz-ivan",
    "DIAZ Jorge": "diaz-jorge",
    "DIAZ Kristoffer": "diaz-kristoffer",
    "DIAZ Lorena": "diaz-lorena",
    "DIAZ Michelle": "diaz-michelle",
    "DIAZ Milton": "diaz-milton",
    "DIAZ Nelson": "diaz-nelson",
    "DIAZ Ralph": "diaz-ralph",
    "DIAZ Rodolfo D": "diaz-rodolfo-d",
    "DIAZ-MARCANO Nelson": "diaz-marcano-nelson",
    "DIBATTISTA Patrick": "dibattista-patrick",
    "DIBBELL Dominique": "dibbell-dominique",
    "DIBBLE Susan": "dibble-susan",
    "DIBBLE Warren": "dibble-warren",
    "DIBENEDETTO John": "dibenedetto-john",
    "DIBLASI Gaspare": "diblasi-gaspare",
    "DIBLEY David J": "dibley-david-j",
    "DIBLEY Nancy P": "dibley-nancy-p",
    "DIBUONO Toni": "dibuono-toni",
    "DICAIRANO Jerry": "dicairano-jerry",
    "DICANDER Jorgen": "dicander-jorgen",
    "DICARLO Angela": "dicarlo-angela",
    "DICE, JR Michael": "dice-jr-michael",
    "DICESARE Michaela": "dicesare-michaela",
    "DICHELE Anne": "dichele-anne",
    "DICK Adam": "dick-adam",
    "DICK Jennifer": "dick-jennifer",
    "DICK Montana": "dick-montana",
    "DICK Paul": "dick-paul",
    "DICK R A": "dick-r-a",
    "DICK Steven": "dick-steven",
    "DICKEN Matthew": "dicken-matthew",
    "DICKENS A": "dickens-a",
    "DICKENS Barry": "dickens-barry",
    "DICKENS Ned": "dickens-ned",
    "DICKENSON Ben": "dickenson-ben",
    "DICKERSON Brandon": "dickerson-brandon",
    "DICKERSON Chris": "dickerson-chris",
    "DICKERSON Glenda": "dickerson-glenda",
    "DICKERSON Gregory W": "dickerson-gregory-w",
    "DICKERSON Meghan": "dickerson-meghan",
    "DICKERSON-DESPENZA Erika": "dickerson-despenza-erika",
    "DICKEY Jessica": "dickey-jessica",
    "DICKIE Peter": "dickie-peter",
    "DICKIE Will": "dickie-will",
    "DICKINS Barry": "dickins-barry",
    "DICKINS Chris": "dickins-chris",
    "DICKINS Christopher": "dickins-christopher",
    "DICKINS Shani": "dickins-shani",
    "DICKINSON Andy": "dickinson-andy",
    "DICKINSON Bonnie": "dickinson-bonnie",
    "DICKINSON Ian": "dickinson-ian",
    "DICKINSON Kate": "dickinson-kate",
    "DICKINSON Kathryn": "dickinson-kathryn",
    "DICKINSON Laura": "dickinson-laura",
    "DICKINSON Marjorie": "dickinson-marjorie",
    "DICKINSON Mike": "dickinson-mike",
    "DICKINSON Mikee": "dickinson-mikee",
    "DICKINSON Patric": "dickinson-patric",
    "DICKINSON Samantha": "dickinson-samantha",
    "DICKINSON Steph": "dickinson-steph",
    "DICKLER Gloria Joyce": "dickler-gloria-joyce",
    "DICKLER Pam": "dickler-pam",
    "DICKMAN Christopher J": "dickman-christopher-j",
    "DICKS Terrence": "dicks-terrence",
    "DICKSON Angela Allen": "dickson-angela-allen",
    "DICKSON Barbara": "dickson-barbara",
    "DICKSON Bruce": "dickson-bruce",
    "DICKSON Glen": "dickson-glen",
    "DICKSON Graham": "dickson-graham",
    "DICKSON Jack": "dickson-jack",
    "DICKSON Lauren": "dickson-lauren",
    "DICKSON Miles": "dickson-miles",
    "DICKSON Rachel": "dickson-rachel",
    "DICKSON Stuart": "dickson-stuart",
    "DICKSTEIN Mindi": "dickstein-mindi",
    "DICKSTEIN Rachel": "dickstein-rachel",
    "DICLAUDIO Dennis": "diclaudio-dennis",
    "DICONCETTO Karen": "diconcetto-karen",
    "DIDEROT Denis": "diderot-denis",
    "DIDION Joan": "didion-joan",
    "DIDONNA Gian": "didonna-gian",
    "DIEBEL John F": "diebel-john-f",
    "DIEFENBACH Jake": "diefenbach-jake",
    "DIEL Antoine": "diel-antoine",
    "DIEL Matt": "diel-matt",
    "DIELI Patrick": "dieli-patrick",
    "DIELLEMAN Dale": "dielleman-dale",
    "DIELMAN Andrew": "dielman-andrew",
    "DIENES Michelle": "dienes-michelle",
    "DIENNET Pierre-Marc": "diennet-pierre-marc",
    "DIERKES Stephen": "dierkes-stephen",
    "DIESPECKER Don": "diespecker-don",
    "DIETER Mark": "dieter-mark",
    "DIETJEN James": "dietjen-james",
    "DIETRICH Bruce": "dietrich-bruce",
    "DIETRICH John": "dietrich-john",
    "DIETZ Dan": "dietz-dan",
    "DIETZ David": "dietz-david",
    "DIETZ Howard": "dietz-howard",
    "DIETZ Kyra": "dietz-kyra",
    "DIETZ Stacey": "dietz-stacey",
    "DIETZ Steven": "dietz-steven",
    "DIFELICE John": "difelice-john",
    "DIFFER Philip": "differ-philip",
    "DIFRANGIA Avel": "difrangia-avel",
    "DIFUSCO John": "difusco-john",
    "DIGAETANO Michael": "digaetano-michael",
    "DIGGLE Tony": "diggle-tony",
    "DIGGS Elizabeth": "diggs-elizabeth",
    "DIGGS Thomas H": "diggs-thomas-h",
    "DIGGS Tom": "diggs-tom",
    "DIGHTON John": "dighton-john",
    "DIGILIO Nick": "digilio-nick",
    "DIGIOVANNI Chris": "digiovanni-chris",
    "DIGIOVANNI Christine L": "digiovanni-christine-l",
    "DIGRAZIA Christopher": "digrazia-christopher",
    "DIIORIO Gino": "diiorio-gino",
    "DIJEH Lizzy": "dijeh-lizzy",
    "DIJK Otto": "dijk-otto",
    "DIKAIOS Euripides": "dikaios-euripides",
    "DIKE Fatima": "dike-fatima",
    "DIKOTLA Phillip": "dikotla-phillip",
    "DILALLO Susan": "dilallo-susan",
    "DILAURO Stephen": "dilauro-stephen",
    "DILELLA Paul": "dilella-paul",
    "DILKS Daniel David Moses": "dilks-daniel-david-moses",
    "DILL Catharine": "dill-catharine",
    "DILLARD Denise Kay": "dillard-denise-kay",
    "DILLARD Gavin": "dillard-gavin",
    "DILLARD Molly": "dillard-molly",
    "DILLARD R H W": "dillard-r-h-w",
    "DILLEHAY Thomas C": "dillehay-thomas-c",
    "DILLEMUTH Angel": "dillemuth-angel",
    "DILLEN Frederick": "dillen-frederick",
    "DILLEN Leslie Harrell": "dillen-leslie-harrell",
    "DILLEY Justin": "dilley-justin",
    "DILLEY Rob": "dilley-rob",
    "DILLMAN Lisa": "dillman-lisa",
    "DILLMAN Valerie Lee": "dillman-valerie-lee",
    "DILLON David": "dillon-david",
    "DILLON Des": "dillon-des",
    "DILLON Eileen": "dillon-eileen",
    "DILLON Ellis": "dillon-ellis",
    "DILLON George": "dillon-george",
    "DILLON George (1)": "dillon-george-1",
    "DILLON John": "dillon-john",
    "DILLON Loretta": "dillon-loretta",
    "DILLON Peter": "dillon-peter",
    "DILMEN Gungor": "dilmen-gungor",
    "DILOP Birago": "dilop-birago",
    "DILORIO Gino": "dilorio-gino",
    "DILSTON William": "dilston-william",
    "DILWORTH Sharon": "dilworth-sharon",
    "DIMAGGIO Lou": "dimaggio-lou",
    "DIMAGGIO Stephanie": "dimaggio-stephanie",
    "DIMAKIS Phillippa": "dimakis-phillippa",
    "DIMARCO Damon": "dimarco-damon",
    "DIMATTEI Nicole": "dimattei-nicole",
    "DIMBLEBY Kate": "dimbleby-kate",
    "DIMENNA Meredith": "dimenna-meredith",
    "DIMERY Martin": "dimery-martin",
    "DIMINO Mary": "dimino-mary",
    "DIMITO Tony": "dimito-tony",
    "DIMITRIADIS Koraly": "dimitriadis-koraly",
    "DIMITRIJEVIC Selma": "dimitrijevic-selma",
    "DIMITROV Ditimar": "dimitrov-ditimar",
    "DIMITROV Ivan": "dimitrov-ivan",
    "DIMOCK Anne": "dimock-anne",
    "DIMOCK George E": "dimock-george-e",
    "DIMON Nobby": "dimon-nobby",
    "DIMOND Christopher": "dimond-christopher",
    "DIMOU Akis": "dimou-akis",
    "DIMOVA Theodora": "dimova-theodora",
    "DIMURRO Tony": "dimurro-tony",
    "DIN Ayub Khan": "din-ayub-khan",
    "DIN Ishy": "din-ishy",
    "DINAPOLI Anthony": "dinapoli-anthony",
    "DINARDO Gary Bernard": "dinardo-gary-bernard",
    "DINARDO Robert E": "dinardo-robert-e",
    "DINEEN Patrick": "dineen-patrick",
    "DINELARIS Alexander": "dinelaris-alexander",
    "DINELLI Mel": "dinelli-mel",
    "DINES Michael": "dines-michael",
    "DING FOUNDATION ": "ding-foundation",
    "DINGMAN Sam": "dingman-sam",
    "DINGSDALE Daniel": "dingsdale-daniel",
    "DINGWELL John": "dingwell-john",
    "DINICOLA Karen Denise": "dinicola-karen-denise",
    "DINIZ Andre": "diniz-andre",
    "DINKIN Marc": "dinkin-marc",
    "DINKOVA Elizabeth": "dinkova-elizabeth",
    "DINNELL David": "dinnell-david",
    "DINNEN Paul": "dinnen-paul",
    "DINNER William": "dinner-william",
    "DINNER-LEVIN Stacey": "dinner-levin-stacey",
    "DINNIE Jean": "dinnie-jean",
    "DINOVELLI Donna": "dinovelli-donna",
    "DINSDALE Stephen": "dinsdale-stephen",
    "DINSMORE John": "dinsmore-john",
    "DINSON J M": "dinson-j-m",
    "DINWIDDIE Andrew": "dinwiddie-andrew",
    "DINWIDDIE Michael": "dinwiddie-michael",
    "DION Andre": "dion-andre",
    "DIONYSIOS Nikos": "dionysios-nikos",
    "DIONYSIOU Monica": "dionysiou-monica",
    "DIOP Birago": "diop-birago",
    "DIORIO Laura Francesca": "diorio-laura-francesca",
    "DIOS Paul": "dios-paul",
    "DIOSDADO Ana": "diosdado-ana",
    "DIPALERMO Frank": "dipalermo-frank",
    "DIPAOLA Vincent J": "dipaola-vincent-j",
    "DIPAOLO Cara": "dipaolo-cara",
    "DIPAOLO Elvira": "dipaolo-elvira",
    "DIPIETRO Jay": "dipietro-jay",
    "DIPIETRO Joe": "dipietro-joe",
    "DIPIETRO Marylou": "dipietro-marylou",
    "DIPINTO John": "dipinto-john",
    "DIPPER David": "dipper-david",
    "DIPPOLD Katie": "dippold-katie",
    "DIR Drew": "dir-drew",
    "DIRCH Alice": "dirch-alice",
    "DIRE Antonio": "dire-antonio",
    "DI-RE Christiane": "di-re-christiane",
    "DIRGES Wallace": "dirges-wallace",
    "DIRIWACHTER Tom": "diriwachter-tom",
    "DIRRIGI John": "dirrigi-john",
    "DIRTY MARKET ": "dirty-market",
    "DISABATINO Brandon Thomas": "disabatino-brandon-thomas",
    "DISALLE Glauco": "disalle-glauco",
    "DISAVINO Katherine": "disavino-katherine",
    "DISCH Jacob Mitchell": "disch-jacob-mitchell",
    "DISCOMBE Nick": "discombe-nick",
    "DISCORDIA Dana": "discordia-dana",
    "DISKANT Ben": "diskant-ben",
    "DISNEY Stanley": "disney-stanley",
    "DISPLACE YOURSELF THEATRE ": "displace-yourself-theatre",
    "DISSENT ENSEMBLE ": "dissent-ensemble",
    "DISTEFANO Madi": "distefano-madi",
    "DITSAN Harry": "ditsan-harry",
    "DITSELE Oarabile": "ditsele-oarabile",
    "DITTA Aschlin": "ditta-aschlin",
    "DITTERLINE Will": "ditterline-will",
    "DITTON Cordelia": "ditton-cordelia",
    "DITTRICH Dorothy": "dittrich-dorothy",
    "DIUBALDO Steve": "diubaldo-steve",
    "DIVER Shirley": "diver-shirley",
    "DIVERIS Leigh": "diveris-leigh",
    "DIVERSIONS, DANCE COMPANY OF WALES ": "diversions-dance-company-of-wales",
    "DIVERTISSEMENT ": "divertissement",
    "DIVINE Johanna": "divine-johanna",
    "DIXEY Caroline": "dixey-caroline",
    "DIXEY Marcia": "dixey-marcia",
    "DIXON Barbara": "dixon-barbara",
    "DIXON Chris": "dixon-chris",
    "DIXON Ed": "dixon-ed",
    "DIXON Geoff": "dixon-geoff",
    "DIXON Jean": "dixon-jean",
    "DIXON John": "dixon-john",
    "DIXON Joshua": "dixon-joshua",
    "DIXON Lewis": "dixon-lewis",
    "DIXON Lorna": "dixon-lorna",
    "DIXON Luke": "dixon-luke",
    "DIXON Melvin": "dixon-melvin",
    "DIXON Michael Bigelow": "dixon-michael-bigelow",
    "DIXON Natasha M": "dixon-natasha-m",
    "DIXON Richard": "dixon-richard",
    "DIXON Sean": "dixon-sean",
    "DIXON Tami": "dixon-tami",
    "DIXON Tony": "dixon-tony",
    "DIXON Victor": "dixon-victor",
    "DIYAB Mahmud": "diyab-mahmud",
    "DIZENZO Charles": "dizenzo-charles",
    "DIZON Louella": "dizon-louella",
    "DIZOZZA Peter": "dizozza-peter",
    "DIZRAELI ": "dizraeli",
    "DJ EXCALIBAH ": "dj-excalibah",
    "DJERASSI Carl": "djerassi-carl",
    "DJURDEVIC Bob": "djurdevic-bob",
    "DLUGOLECKI Cindy Rock": "dlugolecki-cindy-rock"
  }
};