export default {
  "metadata": {
    "results": 623,
    "timeStamp": "2025-12-05T21:23:52.074Z",
    "url": "https://www.doollee.com/PlaywrightsD/D_playwrights_m-r.php"
  },
  "authors": {
    "DM COLLECTIVE ": "dm-collective",
    "DMITRY KRYMOV LAB ": "dmitry-krymov-lab",
    "DO Tuyen": "do-tuyen",
    "DO VALE Louis Sartori": "do-vale-louis-sartori",
    "DOAN Dinh": "doan-dinh",
    "DOAN Nicholas": "doan-nicholas",
    "DOANE Suzanne": "doane-suzanne",
    "DOBB Andy": "dobb-andy",
    "DOBBINS Jeff": "dobbins-jeff",
    "DOBBINS Ray": "dobbins-ray",
    "DOBBS Georgia": "dobbs-georgia",
    "DOBBS Hamish": "dobbs-hamish",
    "DOBBY Harrie": "dobby-harrie",
    "DOBBY Harriet": "dobby-harriet",
    "DOBERMAN Martin": "doberman-martin",
    "DOBIE Laurence": "dobie-laurence",
    "DOBIE Laurence (1)": "dobie-laurence-1",
    "DOBIES Kevin": "dobies-kevin",
    "DOBLE John": "doble-john",
    "DOBOS Eva": "dobos-eva",
    "DOBOS Nikki": "dobos-nikki",
    "DOBRIN Arnold": "dobrin-arnold",
    "DOBRISH Jeremy": "dobrish-jeremy",
    "DOBROWOLSKI Chris": "dobrowolski-chris",
    "DOBRUSKY Pavel": "dobrusky-pavel",
    "DOBRY Anthea": "dobry-anthea",
    "DOBRZANSKA Ania": "dobrzanska-ania",
    "DOBSON Albert": "dobson-albert",
    "DOBSON Brian": "dobson-brian",
    "DOBSON Dale": "dobson-dale",
    "DOBSON Geoff": "dobson-geoff",
    "DOBSON Margaret": "dobson-margaret",
    "DOBSON Mary Lynn": "dobson-mary-lynn",
    "DOBULAR Russell": "dobular-russell",
    "DOCHERTY Abigail": "docherty-abigail",
    "DOCHERTY Anne Nygren": "docherty-anne-nygren",
    "DOCHERTY Franz": "docherty-franz",
    "DOCHERTY George": "docherty-george",
    "DOCKEN Pamela Norton": "docken-pamela-norton",
    "DOCKERY Martin": "dockery-martin",
    "DOCKRILL Laura": "dockrill-laura",
    "DOCTOROW E L": "doctorow-e-l",
    "DODD A E": "dodd-a-e",
    "DODD Amber Lee": "dodd-amber-lee",
    "DODD John Patrick": "dodd-john-patrick",
    "DODD Lynley": "dodd-lynley",
    "DODD Nancy Kierspe": "dodd-nancy-kierspe",
    "DODD Rhonda": "dodd-rhonda",
    "DODD Simon": "dodd-simon",
    "DODD Stephanie": "dodd-stephanie",
    "DODDS Andrea": "dodds-andrea",
    "DODDS Robert": "dodds-robert",
    "DODGE Anthony": "dodge-anthony",
    "DODGE Jenny": "dodge-jenny",
    "DODGE Marcia Milgrom": "dodge-marcia-milgrom",
    "DODGE Mel": "dodge-mel",
    "DODGSON Elyse": "dodgson-elyse",
    "DODGSON Paul": "dodgson-paul",
    "DODGY CLUTCH ": "dodgy-clutch",
    "DODI Gideon": "dodi-gideon",
    "DODIN Lev": "dodin-lev",
    "DODSON Owen": "dodson-owen",
    "DODWELL Stephen": "dodwell-stephen",
    "DOERING Chad": "doering-chad",
    "DOERMAN Dale": "doerman-dale",
    "DOG KENNEL HILL PROJECT ": "dog-kennel-hill-project",
    "DOGGART Sebastian": "doggart-sebastian",
    "DOGGETT Victoria": "doggett-victoria",
    "DOGS IN HONEY ": "dogs-in-honey",
    "DOGSTAR THEATRE ": "dogstar-theatre",
    "DOHAN Meital": "dohan-meital",
    "DOHERTY Amy": "doherty-amy",
    "DOHERTY Anne Nygren": "doherty-anne-nygren",
    "DOHERTY Berlie": "doherty-berlie",
    "DOHERTY Brian": "doherty-brian",
    "DOHERTY Brooke": "doherty-brooke",
    "DOHERTY Della": "doherty-della",
    "DOHERTY Felix": "doherty-felix",
    "DOHERTY Gina": "doherty-gina",
    "DOHERTY James": "doherty-james",
    "DOHERTY Jim": "doherty-jim",
    "DOHERTY John": "doherty-john",
    "DOHERTY Lucy": "doherty-lucy",
    "DOHERTY Mark": "doherty-mark",
    "DOHERTY Matt": "doherty-matt",
    "DOHERTY Miche": "doherty-miche",
    "DOHERTY Nancy": "doherty-nancy",
    "DOHERTY Neil": "doherty-neil",
    "DOHERTY Philip": "doherty-philip",
    "DOHERTY Robert": "doherty-robert",
    "DOHERTY Taylor": "doherty-taylor",
    "DOHNERT Michael": "dohnert-michael",
    "DOHRN Zayd": "dohrn-zayd",
    "DOIASHVILI David": "doiashvili-david",
    "DOIDGE Isla": "doidge-isla",
    "DOIRON Stephen Andrew": "doiron-stephen-andrew",
    "DOLAN Andrew": "dolan-andrew",
    "DOLAN Chris": "dolan-chris",
    "DOLAN Harry": "dolan-harry",
    "DOLAN Laurence": "dolan-laurence",
    "DOLAN Liam": "dolan-liam",
    "DOLAN Mark": "dolan-mark",
    "DOLAN Monica": "dolan-monica",
    "DOLAN Ryan Patrick": "dolan-ryan-patrick",
    "DOLAN-SMITH Karen": "dolan-smith-karen",
    "DOLCINO Doug": "dolcino-doug",
    "DOLDER Nicole": "dolder-nicole",
    "DOLE John": "dole-john",
    "DOLE Patricia": "dole-patricia",
    "DOLEZALOVA Neela": "dolezalova-neela",
    "DOLGINOFF Stephen": "dolginoff-stephen",
    "DOLIVIO Leonard": "dolivio-leonard",
    "DOLLARD Will": "dollard-will",
    "DOLLOSO Felino": "dolloso-felino",
    "DOLMAN Glen": "dolman-glen",
    "DOLMAN Kathryn": "dolman-kathryn",
    "DOLPHIN Josh": "dolphin-josh",
    "DOMAGIABA John Luca": "domagiaba-john-luca",
    "DOMANOWSKI Michelle": "domanowski-michelle",
    "DOMBOIS Lane": "dombois-lane",
    "DOMEIER Renee": "domeier-renee",
    "DOMENCIC Joseph Lawrence": "domencic-joseph-lawrence",
    "DOMENECH Blanca": "domenech-blanca",
    "DOMET Sally": "domet-sally",
    "DOMINGO Angel": "domingo-angel",
    "DOMINGO Colman": "domingo-colman",
    "DOMINGUE Nina": "domingue-nina",
    "DOMINGUES Dan": "domingues-dan",
    "DOMINGUES Luis": "domingues-luis",
    "DOMINGUEZ Jose Manuel": "dominguez-jose-manuel",
    "DOMINGUEZ Nicole": "dominguez-nicole",
    "DOMINGUEZ Robert": "dominguez-robert",
    "DOMINIK Marika": "dominik-marika",
    "DOMINIQUE Nina": "dominique-nina",
    "DOMINY Amy": "dominy-amy",
    "DOMINY Jeannine": "dominy-jeannine",
    "DOMITROVICH Michael": "domitrovich-michael",
    "DOMMY B ": "dommy-b",
    "DONACASTER Bill": "donacaster-bill",
    "DONAGHY Charlene A": "donaghy-charlene-a",
    "DONAGHY Craig": "donaghy-craig",
    "DONAGHY Tom": "donaghy-tom",
    "DONAHOE Jonny": "donahoe-jonny",
    "DONAHOO Logan": "donahoo-logan",
    "DONAHUE Guen": "donahue-guen",
    "DONAHUE Jack": "donahue-jack",
    "DONAHUE John Clark": "donahue-john-clark",
    "DONAHUE Lauri": "donahue-lauri",
    "DONALD Douglas": "donald-douglas",
    "DONALD Miles": "donald-miles",
    "DONALD Papa": "donald-papa",
    "DONALD Paul Morgan": "donald-paul-morgan",
    "DONALD Simon": "donald-simon",
    "DONALDSON Andrea": "donaldson-andrea",
    "DONALDSON Herb": "donaldson-herb",
    "DONALDSON Julia": "donaldson-julia",
    "DONALDSON Norah": "donaldson-norah",
    "DONALDSON Norman": "donaldson-norman",
    "DONALDSON Toby Mitchell": "donaldson-toby-mitchell",
    "DONATUS Sister Mary": "donatus-sister-mary",
    "DONAVON Catherine": "donavon-catherine",
    "DONCASTER Bill": "doncaster-bill",
    "DONDA Jerry": "donda-jerry",
    "DONDINES Alejandra": "dondines-alejandra",
    "DONEGAN Martin": "donegan-martin",
    "DONEGHY Patrick M": "doneghy-patrick-m",
    "DONEMAN Michael": "doneman-michael",
    "DONEN Adam": "donen-adam",
    "DONEV Kamen": "donev-kamen",
    "DONFELD Noelle": "donfeld-noelle",
    "DONHUE John Clark": "donhue-john-clark",
    "DONIGER Paul E": "doniger-paul-e",
    "DONISTHORPE Gladys Sheila": "donisthorpe-gladys-sheila",
    "DONKIN Michelle": "donkin-michelle",
    "DONLEAVY J P": "donleavy-j-p",
    "DONLEY Jan": "donley-jan",
    "DONLEY Michael": "donley-michael",
    "DONLEY Michael Pearce": "donley-michael-pearce",
    "DONNELL Sarah Hayes": "donnell-sarah-hayes",
    "DONNELLAN Declan": "donnellan-declan",
    "DONNELLAN Don": "donnellan-don",
    "DONNELLAN Mick": "donnellan-mick",
    "DONNELLAN Siobhan": "donnellan-siobhan",
    "DONNELLY Barry": "donnelly-barry",
    "DONNELLY Bill": "donnelly-bill",
    "DONNELLY Brian Thomas": "donnelly-brian-thomas",
    "DONNELLY Donal": "donnelly-donal",
    "DONNELLY Jamie": "donnelly-jamie",
    "DONNELLY John": "donnelly-john",
    "DONNELLY John A": "donnelly-john-a",
    "DONNELLY Kathleen": "donnelly-kathleen",
    "DONNELLY Ken": "donnelly-ken",
    "DONNELLY Mark": "donnelly-mark",
    "DONNELLY Mary": "donnelly-mary",
    "DONNELLY Mary Catherine": "donnelly-mary-catherine",
    "DONNELLY Mary Queen": "donnelly-mary-queen",
    "DONNELLY Neil": "donnelly-neil",
    "DONNELLY Paul J": "donnelly-paul-j",
    "DONNELLY Steffan": "donnelly-steffan",
    "DONNELLY William": "donnelly-william",
    "DONNELLY-CRUICKSHANK Jane": "donnelly-cruickshank-jane",
    "DONOGHUE Eddie": "donoghue-eddie",
    "DONOGHUE Emma": "donoghue-emma",
    "DONOGHUE Mary Agnes": "donoghue-mary-agnes",
    "DONOGHUE Vickie": "donoghue-vickie",
    "DONOHOE Kim": "donohoe-kim",
    "DONOHUE Darren": "donohue-darren",
    "DONOHUE Moira Rose": "donohue-moira-rose",
    "DONOHUE Nancy": "donohue-nancy",
    "DONOVAN Andrew": "donovan-andrew",
    "DONOVAN Anne": "donovan-anne",
    "DONOVAN Bryan T": "donovan-bryan-t",
    "DONOVAN Erin": "donovan-erin",
    "DONOVAN Maripat": "donovan-maripat",
    "DONOVAN Sean": "donovan-sean",
    "DONOVAN Spatz": "donovan-spatz",
    "DONOVAN Vilma Ortiz": "donovan-vilma-ortiz",
    "DONSKOY Daniel": "donskoy-daniel",
    "DONSKY Seth Michael": "donsky-seth-michael",
    "DOOD Alice": "dood-alice",
    "DOOD PAARD ": "dood-paard",
    "DOODY Sarah": "doody-sarah",
    "DOODY Warren": "doody-warren",
    "DOODY William J": "doody-william-j",
    "DOOLAN Lita": "doolan-lita",
    "DOOLEY Aidan": "dooley-aidan",
    "DOOLEY Caroline": "dooley-caroline",
    "DOOLEY Elizabeth Brown": "dooley-elizabeth-brown",
    "DOOLEY Jeff": "dooley-jeff",
    "DOOLEY John": "dooley-john",
    "DOOLEY Mark": "dooley-mark",
    "DOOLEY Paul": "dooley-paul",
    "DOOLING Amy": "dooling-amy",
    "DOOLITTLE Joyce": "doolittle-joyce",
    "DOOLITTLE Quenten": "doolittle-quenten",
    "DOOMADGEE Kylie": "doomadgee-kylie",
    "DOONA John": "doona-john",
    "DOPFLER Ulrike": "dopfler-ulrike",
    "DOPH Dennis": "doph-dennis",
    "DOPPELGANGER THEATRE ": "doppelganger-theatre",
    "DOPPIO Teatro": "doppio-teatro",
    "DORADO Yolanda": "dorado-yolanda",
    "DORALL Edward": "dorall-edward",
    "DORAN Bathsheba": "doran-bathsheba",
    "DORAN Gregory": "doran-gregory",
    "DORAN James": "doran-james",
    "DORAN Nolan": "doran-nolan",
    "DORAN Peter": "doran-peter",
    "DORAN Sean": "doran-sean",
    "DORAN Thomas": "doran-thomas",
    "DORBISH Jeremy": "dorbish-jeremy",
    "DORCHEN Jeffrey": "dorchen-jeffrey",
    "DORE Deirdre C": "dore-deirdre-c",
    "DORE Isabelle": "dore-isabelle",
    "DORE Margaret Seguin": "dore-margaret-seguin",
    "DORES Pascal": "dores-pascal",
    "DOREY Jules": "dorey-jules",
    "DORF Fran": "dorf-fran",
    "DORF Jonathan": "dorf-jonathan",
    "DORFMAN Ariel": "dorfman-ariel",
    "DORFMAN Ethan": "dorfman-ethan",
    "DORFMAN Nat N": "dorfman-nat-n",
    "DORFMAN Rodrigo": "dorfman-rodrigo",
    "DORFMAN Toni": "dorfman-toni",
    "DORIADIS Andonis": "doriadis-andonis",
    "DORIAN Elise": "dorian-elise",
    "DORIAN Wallace": "dorian-wallace",
    "DORIS-PIERCE Brendan": "doris-pierce-brendan",
    "DORLAND Keith": "dorland-keith",
    "DORM Francoise": "dorm-francoise",
    "DORMAN Edwina": "dorman-edwina",
    "DORMANDY Simon": "dormandy-simon",
    "DORMER Richard": "dormer-richard",
    "DORMOY-SAVAGE Nadine": "dormoy-savage-nadine",
    "DORN Michael Howard": "dorn-michael-howard",
    "DORN Patrick": "dorn-patrick",
    "DORN Zayd": "dorn-zayd",
    "DORNEY Marcel": "dorney-marcel",
    "DORNFORD-MAY Mark": "dornford-may-mark",
    "DORNVILLE Matthew": "dornville-matthew",
    "DORO Davide": "doro-davide",
    "DOROUGH Bob": "dorough-bob",
    "DORR Donald": "dorr-donald",
    "DORRAS Joanne": "dorras-joanne",
    "DORRELL Mike": "dorrell-mike",
    "DORRELL Paul": "dorrell-paul",
    "DORRELL Rosemary": "dorrell-rosemary",
    "DORRICOTT Ian": "dorricott-ian",
    "DORSEN Annie": "dorsen-annie",
    "DORSEY Brian J": "dorsey-brian-j",
    "DORSEY Jeanne": "dorsey-jeanne",
    "DORSEY Lee": "dorsey-lee",
    "DORST Tankred": "dorst-tankred",
    "DORWICK Keith": "dorwick-keith",
    "DOS SANTOS Marcelo": "dos-santos-marcelo",
    "DOSSETT Laurelyn": "dossett-laurelyn",
    "DOSTOEVSKY Feodor": "dostoevsky-feodor",
    "DOSWELL Billy": "doswell-billy",
    "DOTEN Alaina Motisi": "doten-alaina-motisi",
    "DOTSON Edisol Wayne": "dotson-edisol-wayne",
    "DOTTINO Suzanne": "dottino-suzanne",
    "DOTY Chris": "doty-chris",
    "DOTY Joel Henning": "doty-joel-henning",
    "DOUBA Adam": "douba-adam",
    "DOUBLE Drama": "double-drama",
    "DOUBTFUL SOUND ": "doubtful-sound",
    "DOUCET Clive": "doucet-clive",
    "DOUCETTE John": "doucette-john",
    "DOUD Elizabeth": "doud-elizabeth",
    "DOUGALL Edwin": "dougall-edwin",
    "DOUGALL Gordon": "dougall-gordon",
    "DOUGAN Michael": "dougan-michael",
    "DOUGE Amanda": "douge-amanda",
    "DOUGHERTY Doc": "dougherty-doc",
    "DOUGHERTY Dylan": "dougherty-dylan",
    "DOUGHERTY Joseph": "dougherty-joseph",
    "DOUGHERTY Peggy": "dougherty-peggy",
    "DOUGHERTY Robert": "dougherty-robert",
    "DOUGHTY B L": "doughty-b-l",
    "DOUGHTY Jack": "doughty-jack",
    "DOUGHTY Mike": "doughty-mike",
    "DOUGLAS A I": "douglas-a-i",
    "DOUGLAS Aaron": "douglas-aaron",
    "DOUGLAS Alfred": "douglas-alfred",
    "DOUGLAS Angus": "douglas-angus",
    "DOUGLAS B J": "douglas-b-j",
    "DOUGLAS Bill": "douglas-bill",
    "DOUGLAS Calvin M": "douglas-calvin-m",
    "DOUGLAS Christopher": "douglas-christopher",
    "DOUGLAS Delanie": "douglas-delanie",
    "DOUGLAS Derek": "douglas-derek",
    "DOUGLAS Diana": "douglas-diana",
    "DOUGLAS Dominic": "douglas-dominic",
    "DOUGLAS Elizabeth": "douglas-elizabeth",
    "DOUGLAS Felicity": "douglas-felicity",
    "DOUGLAS J D": "douglas-j-d",
    "DOUGLAS James": "douglas-james",
    "DOUGLAS James (1)": "douglas-james-1",
    "DOUGLAS Jerry": "douglas-jerry",
    "DOUGLAS Joe": "douglas-joe",
    "DOUGLAS Katie": "douglas-katie",
    "DOUGLAS Katrina": "douglas-katrina",
    "DOUGLAS Leigh": "douglas-leigh",
    "DOUGLAS Margie": "douglas-margie",
    "DOUGLAS Michael": "douglas-michael",
    "DOUGLAS Pavel": "douglas-pavel",
    "DOUGLAS Richard": "douglas-richard",
    "DOUGLAS Rodney K": "douglas-rodney-k",
    "DOUGLAS Ross": "douglas-ross",
    "DOUGLAS Scott": "douglas-scott",
    "DOUGLAS Tim": "douglas-tim",
    "DOUGLAS Warren": "douglas-warren",
    "DOUGLAS William": "douglas-william",
    "DOUGLASS Archie": "douglass-archie",
    "DOUGLASS Jean Ann": "douglass-jean-ann",
    "DOUGLASS Kathleen": "douglass-kathleen",
    "DOUGLASS Sean Mcmahon": "douglass-sean-mcmahon",
    "DOUGLASS Stephanie": "douglass-stephanie",
    "DOUGLASS Stuart": "douglass-stuart",
    "DOULTON Leo": "doulton-leo",
    "DOURIS Rochelle": "douris-rochelle",
    "DOUST Paul": "doust-paul",
    "DOUTHIT Lue M": "douthit-lue-m",
    "DOVALINA Fernando": "dovalina-fernando",
    "DOVE Jonathan": "dove-jonathan",
    "DOVE Judy Merryman": "dove-judy-merryman",
    "DOVE Kate": "dove-kate",
    "DOVE Martin": "dove-martin",
    "DOVE Pheralyn": "dove-pheralyn",
    "DOVE Rita": "dove-rita",
    "DOVIZI DA BIBBIENA Bernardo": "dovizi-da-bibbiena-bernardo",
    "DOVRENI Mira": "dovreni-mira",
    "DOW Jan Henson": "dow-jan-henson",
    "DOW Robert": "dow-robert",
    "DOW Shannon Michal": "dow-shannon-michal",
    "DOW Sylvia": "dow-sylvia",
    "DOW-BLYTON Katherine": "dow-blyton-katherine",
    "DOWD Ciaran": "dowd-ciaran",
    "DOWD Jack": "dowd-jack",
    "DOWD Jim": "dowd-jim",
    "DOWD Peter": "dowd-peter",
    "DOWD Timothy": "dowd-timothy",
    "DOWDALL E P": "dowdall-e-p",
    "DOWELL Coleman": "dowell-coleman",
    "DOWELL L Henry": "dowell-l-henry",
    "DOWGIN John P": "dowgin-john-p",
    "DOWIE Anne": "dowie-anne",
    "DOWIE Claire": "dowie-claire",
    "DOWIE John": "dowie-john",
    "DOWIE Layla": "dowie-layla",
    "DOWLATSHAHI Layla": "dowlatshahi-layla",
    "DOWLER Ryan": "dowler-ryan",
    "DOWLIN Tim": "dowlin-tim",
    "DOWLING Clare": "dowling-clare",
    "DOWLING Deidre": "dowling-deidre",
    "DOWLING Oliver": "dowling-oliver",
    "DOWLING Sam": "dowling-sam",
    "DOWLING Sean": "dowling-sean",
    "DOWLING Susanna": "dowling-susanna",
    "DOWLING Tom": "dowling-tom",
    "DOWLING Vincent": "dowling-vincent",
    "DOWN Garry": "down-garry",
    "DOWN Mark": "down-mark",
    "DOWN Mickey": "down-mickey",
    "DOWN Oliphant": "down-oliphant",
    "DOWNEND Michael": "downend-michael",
    "DOWNER Alan S": "downer-alan-s",
    "DOWNES Bernie": "downes-bernie",
    "DOWNES Brian": "downes-brian",
    "DOWNES Catherine": "downes-catherine",
    "DOWNES Peta": "downes-peta",
    "DOWNES R J": "downes-r-j",
    "DOWNEY Campbell": "downey-campbell",
    "DOWNEY Dik": "downey-dik",
    "DOWNEY Graham": "downey-graham",
    "DOWNEY Mike": "downey-mike",
    "DOWNEY Patricia": "downey-patricia",
    "DOWNEY Roger": "downey-roger",
    "DOWNEY Ryan William": "downey-ryan-william",
    "DOWNIE Anne": "downie-anne",
    "DOWNIE John": "downie-john",
    "DOWNIE Tim": "downie-tim",
    "DOWNING Ethan": "downing-ethan",
    "DOWNING Josh": "downing-josh",
    "DOWNING Martin": "downing-martin",
    "DOWNING Michael": "downing-michael",
    "DOWNING R A": "downing-r-a",
    "DOWNING Richard": "downing-richard",
    "DOWNS Brooke": "downs-brooke",
    "DOWNS Caroline": "downs-caroline",
    "DOWNS Claire": "downs-claire",
    "DOWNS Cliff": "downs-cliff",
    "DOWNS Lilia": "downs-lilia",
    "DOWNS Stephen": "downs-stephen",
    "DOWNS William Missouri": "downs-william-missouri",
    "DOWSETT Kevin": "dowsett-kevin",
    "DOWSETT Morgan": "dowsett-morgan",
    "DOWSON Ian": "dowson-ian",
    "DOYLE Alexander Janosek": "doyle-alexander-janosek",
    "DOYLE Andrew": "doyle-andrew",
    "DOYLE Brian": "doyle-brian",
    "DOYLE Carolyn": "doyle-carolyn",
    "DOYLE Colin": "doyle-colin",
    "DOYLE Duke": "doyle-duke",
    "DOYLE Finbarr": "doyle-finbarr",
    "DOYLE Fiona": "doyle-fiona",
    "DOYLE Glen": "doyle-glen",
    "DOYLE Jackie": "doyle-jackie",
    "DOYLE Jean": "doyle-jean",
    "DOYLE Jim": "doyle-jim",
    "DOYLE Jimmy Walsh": "doyle-jimmy-walsh",
    "DOYLE John": "doyle-john",
    "DOYLE Julian": "doyle-julian",
    "DOYLE Kevin": "doyle-kevin",
    "DOYLE Maggie": "doyle-maggie",
    "DOYLE Maryanne": "doyle-maryanne",
    "DOYLE Michael Wrynne": "doyle-michael-wrynne",
    "DOYLE Mollie": "doyle-mollie",
    "DOYLE Monte": "doyle-monte",
    "DOYLE Owen": "doyle-owen",
    "DOYLE Rex": "doyle-rex",
    "DOYLE Richard": "doyle-richard",
    "DOYLE Robert": "doyle-robert",
    "DOYLE Roddy": "doyle-roddy",
    "DOYLE Roger": "doyle-roger",
    "DOYLE Rosemary": "doyle-rosemary",
    "DOYLE S E": "doyle-s-e",
    "DOYLE Sarah": "doyle-sarah",
    "DOYLE Simon": "doyle-simon",
    "DOYLE Stephen": "doyle-stephen",
    "DOYLE Tammis": "doyle-tammis",
    "DOYLE Tom": "doyle-tom",
    "DOZER David": "dozer-david",
    "DOZIER Lamont": "dozier-lamont",
    "DOZORTSEV Valadien": "dozortsev-valadien",
    "DR JUESS ": "dr-juess",
    "DR KACK'S INFAMOUS FREAKSHOW ": "dr-kack",
    "DRABEK David": "drabek-david",
    "DRABEK Jan": "drabek-jan",
    "DRABWELL Gary": "drabwell-gary",
    "DRACHTMAN Ted": "drachtman-ted",
    "DRADER Brian": "drader-brian",
    "DRAESEL Bert": "draesel-bert",
    "DRAESEL Herbert G": "draesel-herbert-g",
    "DRAGANIC Vanja": "draganic-vanja",
    "DRAGAR Igor": "dragar-igor",
    "DRAGO Johnny": "drago-johnny",
    "DRAGOIU Georgeta": "dragoiu-georgeta",
    "DRAGON Uma": "dragon-uma",
    "DRAGUN Osvaldo": "dragun-osvaldo",
    "DRAGUNSKAYA Ksenia": "dragunskaya-ksenia",
    "DRAGUTIN Joel": "dragutin-joel",
    "DRAHEIM David": "draheim-david",
    "DRAI Martine": "drai-martine",
    "DRAIN Richard": "drain-richard",
    "DRAINE Kevin": "draine-kevin",
    "DRAKE Alfred": "drake-alfred",
    "DRAKE Amy": "drake-amy",
    "DRAKE David": "drake-david",
    "DRAKE Donald C": "drake-donald-c",
    "DRAKE Ervin": "drake-ervin",
    "DRAKE Gillian": "drake-gillian",
    "DRAKE James Langston": "drake-james-langston",
    "DRAKE Larry": "drake-larry",
    "DRAKE Mary": "drake-mary",
    "DRAKE Mervyn": "drake-mervyn",
    "DRAKE Nick": "drake-nick",
    "DRAKE Peter": "drake-peter",
    "DRAKE Robyn Herbert-": "drake-robyn-herbert",
    "DRAKE Sunny": "drake-sunny",
    "DRAKE Tza": "drake-tza",
    "DRAKE W Raymond": "drake-w-raymond",
    "DRAKE-BROCKMAN Henrietta": "drake-brockman-henrietta",
    "DRAKES Danielle A": "drakes-danielle-a",
    "DRAMA Arnold": "drama-arnold",
    "DRAMMATICO VEGETALE ": "drammatico-vegetale",
    "DRANCE George": "drance-george",
    "DRANE David": "drane-david",
    "DRAPE Stephen": "drape-stephen",
    "DRAPER Amy": "draper-amy",
    "DRAPER Darrel": "draper-darrel",
    "DRAPER Dave": "draper-dave",
    "DRAPER Emma": "draper-emma",
    "DRAPER Faye": "draper-faye",
    "DRAPER Samuel": "draper-samuel",
    "DRAPER Stuart": "draper-stuart",
    "DRATLER Jay": "dratler-jay",
    "DRATWA Mathilde": "dratwa-mathilde",
    "DRAUS Susan": "draus-susan",
    "DRAXLER Rosalyn": "draxler-rosalyn",
    "DRAXTON Jonathan": "draxton-jonathan",
    "DRAYA Ren": "draya-ren",
    "DRAYSON-KNIGGE Sloane": "drayson-knigge-sloane",
    "DRAYTON Mary": "drayton-mary",
    "DRAYTON Ronald": "drayton-ronald",
    "DRAYTON Tom": "drayton-tom",
    "DRAZDOW Uladzimir": "drazdow-uladzimir",
    "DREAMTHINKSPEAK ": "dreamthinkspeak",
    "DREHAJ Ismail": "drehaj-ismail",
    "DREHER Sarah": "dreher-sarah",
    "DRELL E R": "drell-e-r",
    "DREMANN Alex": "dremann-alex",
    "DRENMAN Jeanne": "drenman-jeanne",
    "DRESCHER-JONES Christine": "drescher-jones-christine",
    "DRESDEN Danielle": "dresden-danielle",
    "DRESDEN Lindsay": "dresden-lindsay",
    "DRESNER Hal": "dresner-hal",
    "DRESNER Mara": "dresner-mara",
    "DRESSER Richard": "dresser-richard",
    "DRESSLER Leslie Anne": "dressler-leslie-anne",
    "DREUX Diane": "dreux-diane",
    "DREW Anthony": "drewe-anthony",
    "DREW Carrie Elizabeth": "drew-carrie-elizabeth",
    "DREW Joshua": "drew-joshua",
    "DREW Phelim": "drew-phelim",
    "DREW Rani": "drew-rani",
    "DREW Warren": "drew-warren",
    "DREW William": "drew-william",
    "DREW JNR Charles E": "drew-jnr-charles-e",
    "DREWE Anthony": "drewe-anthony",
    "DREWERY Tanya": "drewery-tanya",
    "DREWRY John": "drewry-john",
    "DREWS Nadia": "drews-nadia",
    "DREW-SMYTHE David": "drew-smythe-david",
    "DREXLER Lee": "drexler-lee",
    "DREXLER Rosalyn": "drexler-rosalyn",
    "DREYER Marien": "dreyer-marien",
    "DREYFUS David": "dreyfus-david",
    "DREYFUSS Allan": "dreyfuss-allan",
    "DREZNIN Sergei": "dreznin-sergei",
    "DRIGGS Margaret Barton": "driggs-margaret-barton",
    "DRIMMER Josh": "drimmer-josh",
    "DRIN Michael": "drin-michael",
    "DRING Lisa": "dring-lisa",
    "DRISCOLL Dennis": "driscoll-dennis",
    "DRISCOLL Faye": "driscoll-faye",
    "DRISCOLL Robin": "driscoll-robin",
    "DRISCOLL Tim": "driscoll-tim",
    "DRIVER Donald": "driver-donald",
    "DRIVER John": "driver-john",
    "DRIVER Oliver": "driver-oliver",
    "DRIVER Patrick": "driver-patrick",
    "DRIVER Tony": "driver-tony",
    "DROEGE Drew": "droege-drew",
    "DROKE Harvey": "droke-harvey",
    "DROLLINGER D'Arcy": "drollinger-d-arcy",
    "DROMGOOLE Maud": "dromgoole-maud",
    "DROMGOOLE Nicholas": "dromgoole-nicholas",
    "DROTSKY Adrian": "drotsky-adrian",
    "DROWN Tony": "drown-tony",
    "DROXLER Dave": "droxler-dave",
    "DRUCE Michael": "druce-michael",
    "DRUCK Mark": "druck-mark",
    "DRUCKER Colin": "drucker-colin",
    "DRUCKER Timothy Michael": "drucker-timothy-michael",
    "DRUCKER Vanessa": "drucker-vanessa",
    "DRUICK Don": "druick-don",
    "DRUKMAN Steven": "drukman-steven",
    "DRUM Brian": "drum-brian",
    "DRUMMER Zachary": "drummer-zachary",
    "DRUMMOND Amy": "drummond-amy",
    "DRUMMOND Chris": "drummond-chris",
    "DRUMMOND David": "drummond-david",
    "DRUMMOND Evan": "drummond-evan",
    "DRUMMOND John": "drummond-john",
    "DRUMMOND Rob": "drummond-rob",
    "DRUNKEN CHORUS ": "drunken-chorus",
    "DRURY Alan": "drury-alan",
    "DRURY C S": "drury-c-s",
    "DRURY Carolyn": "drury-carolyn",
    "DRURY David": "drury-david",
    "DRURY Jackie Sibblies": "drury-jackie-sibblies",
    "DRURY Maggie": "drury-maggie",
    "DRURY Martin": "drury-martin",
    "DRUXMAN Michael B": "druxman-michael-b",
    "DRY Chih": "dry-chih",
    "DRYBURGH Lesa": "dryburgh-lesa",
    "DRYDEN Ellen": "dryden-ellen",
    "DRYDEN John": "dryden-john",
    "DRYDEN Ken": "dryden-ken",
    "DRYDEN Sarah": "dryden-sarah",
    "DRYLAND Gordon": "dryland-gordon",
    "DRYMALA Joe": "drymala-joe"
  }
};