export default {
  "metadata": {
    "results": 459,
    "timeStamp": "2025-12-05T21:23:55.027Z",
    "url": "https://www.doollee.com/PlaywrightsD/D_playwrights_s-z.php"
  },
  "authors": {
    "D'SOUZA Neil": "d-souza-neil",
    "DU John": "du-john",
    "DU Wesley": "du-wesley",
    "DU BROCK Neal": "du-brock-neal",
    "DU FEU John": "du-feu-john",
    "DU MAURIER Daphne": "du-maurier-daphne",
    "DU PREZ John": "du-prez-john",
    "DU RAND Le Clanche": "du-rand-le-clanche",
    "DU RYER Pierre": "du-ryer-pierre",
    "DU SAUTOY Marcus": "du-sautoy-marcus",
    "DUANNE Frank": "duanne-frank",
    "DUANY Jennylin": "duany-jennylin",
    "DUARTE Amanda": "duarte-amanda",
    "DUARTE Birgit Schreyer": "duarte-birgit-schreyer",
    "DUARTE Joanna": "duarte-joanna",
    "DUARTE Marilyn": "duarte-marilyn",
    "DUARTE Myrna E": "duarte-myrna-e",
    "DUBAC Robert": "dubac-robert",
    "DUBAY Bren J": "dubay-bren-j",
    "DUBBE Jackie": "dubbe-jackie",
    "DUBBLEMAN Peta": "dubbleman-peta",
    "DUBBS Will": "dubbs-will",
    "DUBE Marcel": "dube-marcel",
    "DUBERMAN Martin": "duberman-martin",
    "DUBERSTEIN Helen": "duberstein-helen",
    "DUBEY Lillete": "dubey-lillete",
    "DUBEY Matt": "dubey-matt",
    "DUBIEL John": "dubiel-john",
    "DUBILLARD Roland": "dubillard-roland",
    "DUBIN Al": "dubin-al",
    "DUBIN Kitty S": "dubin-kitty-s",
    "DUBINER Julie Felise": "dubiner-julie-felise",
    "DUBNYK Devon": "dubnyk-devon",
    "DUBOFF Josh": "duboff-josh",
    "DUBOIS Elise": "dubois-elise",
    "DUBOIS Elle": "dubois-elle",
    "DUBOIS Ellie": "dubois-ellie",
    "DUBOIS Graham": "dubois-graham",
    "DUBOIS Katherine": "dubois-katherine",
    "DUBOIS P B": "dubois-p-b",
    "DUBOIS Peter": "dubois-peter",
    "DUBOIS Rene-Daniel": "dubois-rene-daniel",
    "DUBOIS Rochelle Holt": "dubois-rochelle-holt",
    "DUBOIS Shirley Graham": "dubois-shirley-graham",
    "DUBOSE Rachel Ashley": "dubose-rachel-ashley",
    "DUBRAWSKY Aino": "dubrawsky-aino",
    "DUBROW Marsha": "dubrow-marsha",
    "DUBUS Elizabeth Nell": "dubus-elizabeth-nell",
    "DUCEY Robin L": "ducey-robin-l",
    "DUCHAN Peter": "duchan-peter",
    "DUCHARME Rejean": "ducharme-rejean",
    "DUCHEN Jessica": "duchen-jessica",
    "DUCHENE Kate": "duchene-kate",
    "DUCHIN David": "duchin-david",
    "DUCK Ko Sun": "duck-ko-sun",
    "DUCKE Joe": "ducke-joe",
    "DUCKER Amelia": "ducker-amelia",
    "DUCKETT Jim": "duckett-jim",
    "DUCKRIC Lackaal": "duckric-lackaal",
    "DUCKWORTH Colin": "duckworth-colin",
    "DUCKWORTH Paul": "duckworth-paul",
    "DUCKWORTH Stuart": "duckworth-stuart",
    "DUCOVNY Amram": "ducovny-amram",
    "DUCREUX Louis": "ducreux-louis",
    "DUCROS Phillippe": "ducros-phillippe",
    "DUDA Beth Lynn": "duda-beth-lynn",
    "DUDAPAIVA COMPANY ": "dudapaiva-company",
    "DUDAREW-OSSETYNSKI Leonides": "dudarew-ossetynski-leonides",
    "DUDDLE Alison": "duddle-alison",
    "DUDEK James": "dudek-james",
    "DUDEK Jennifer Lee": "dudek-jennifer-lee",
    "DUDENDANCE ": "dudendance",
    "DUDER Tess": "duder-tess",
    "DUDGEON Wayne": "dudgeon-wayne",
    "DUDLEY Anton": "dudley-anton",
    "DUDLEY Ben": "dudley-ben",
    "DUDLEY Bill": "dudley-bill",
    "DUDLEY Ernest": "dudley-ernest",
    "DUDLEY Sian": "dudley-sian",
    "DUDOWARD Valerie": "dudoward-valerie",
    "DUDOWICZ Edward": "dudowicz-edward",
    "DUDZICK Tom": "dudzick-tom",
    "DUELL Sheila": "duell-sheila",
    "DUELL William R": "duell-william-r",
    "DUEMLER Corrina": "duemler-corrina",
    "DUER Veronika": "duer-veronika",
    "DUERKOP Eileen": "duerkop-eileen",
    "DUERR Seth": "duerr-seth",
    "DUFAULT Eric": "dufault-eric",
    "DUFF J": "duff-j",
    "DUFF James": "duff-james",
    "DUFF Scott": "duff-scott",
    "DUFFER Jay": "duffer-jay",
    "DUFFIELD B": "duffield-b",
    "DUFFIELD Marjorie": "duffield-marjorie",
    "DUFFIELD Neil": "duffield-neil",
    "DUFFIELD William Scott": "duffield-william-scott",
    "DUFFIN Cheryl D": "duffin-cheryl-d",
    "DUFFIN Shay": "duffin-shay",
    "DUFFORD Tanner": "dufford-tanner",
    "DUFFY Alec": "duffy-alec",
    "DUFFY Andy": "duffy-andy",
    "DUFFY Antoinette": "duffy-antoinette",
    "DUFFY Carol Ann": "duffy-carol-ann",
    "DUFFY Clare": "duffy-clare",
    "DUFFY David": "duffy-david",
    "DUFFY Gene": "duffy-gene",
    "DUFFY George Gavan": "duffy-george-gavan",
    "DUFFY Gillian": "duffy-gillian",
    "DUFFY Gordon B": "duffy-gordon-b",
    "DUFFY Jonathan": "duffy-jonathan",
    "DUFFY Maureen": "duffy-maureen",
    "DUFFY Mike": "duffy-mike",
    "DUFFY Padraic": "duffy-padraic",
    "DUFFY Richard": "duffy-richard",
    "DUFFY Stella": "duffy-stella",
    "DUFFY Trisha": "duffy-trisha",
    "DUFFY-MCGHIE Gordon": "duffy-mcghie-gordon",
    "DUFORD Chip": "duford-chip",
    "DUFOUR Mark": "dufour-mark",
    "DUFRESNE John": "dufresne-john",
    "DUFRESNY Charles Riviere": "dufresny-charles-riviere",
    "DUFTON Bill": "dufton-bill",
    "DUFTY Richard": "duffy-richard",
    "DUGAN Michael": "dugan-michael",
    "DUGAN Mike": "dugan-mike",
    "DUGAN Robert": "dugan-robert",
    "DUGAN Terry": "dugan-terry",
    "DUGAS Candi": "dugas-candi",
    "DUGDALE Sasha": "dugdale-sasha",
    "DUGGAN Dave": "duggan-dave",
    "DUGGAN Edmund": "duggan-edmund",
    "DUGGAN Gary": "duggan-gary",
    "DUGGAN Ross": "duggan-ross",
    "DUGGAN Shaun": "duggan-shaun",
    "DUGGAN Terry": "duggan-terry",
    "DUGGAN Tom": "duggan-tom",
    "DUGGAN-RYAN Damian": "duggan-ryan-damian",
    "DUGGINS Tom": "duggins-tom",
    "DUGON Nora": "dugon-nora",
    "DUGRENIER Chris": "dugrenier-chris",
    "DUHAMEL Christian": "duhamel-christian",
    "DUIGNAN William": "duignan-william",
    "DUKE A": "duke-a",
    "DUKE Ben": "duke-ben",
    "DUKE Bill": "duke-bill",
    "DUKE Edward": "duke-edward",
    "DUKE G": "duke-g",
    "DUKE James": "duke-james",
    "DUKE Michael": "duke-michael",
    "DUKE Mick": "duke-mick",
    "DUKE Rebecca": "duke-rebecca",
    "DUKES Alan": "dukes-alan",
    "DUKES Ashley": "dukes-ashley",
    "DUKES Brid": "dukes-brid",
    "DUKES Gerry": "dukes-gerry",
    "DUKES Lindsay": "dukes-lindsay",
    "DUKOR Jerrold": "dukor-jerrold",
    "DUKORE Lawrence": "dukore-lawrence",
    "DUKOVSKI Dejan": "dukovski-dejan",
    "DULACK Tom": "dulack-tom",
    "DULANEY Margaret": "dulaney-margaret",
    "DULBERG Judy": "dulberg-judy",
    "DULCHIN Edwin": "dulchin-edwin",
    "DULEX Geraldine": "dulex-geraldine",
    "DULING Dan": "duling-dan",
    "DULLARD Caitlin": "dullard-caitlin",
    "DULLIN Fanny": "dullin-fanny",
    "DULMAGE Sam": "dulmage-sam",
    "DUMAN David": "duman-david",
    "DUMAR Kelly": "dumar-kelly",
    "DUMARESQ William": "dumaresq-william",
    "DUMAS Aaron": "dumas-aaron",
    "DUMAS Charles": "dumas-charles",
    "DUMAS Daisy": "dumas-daisy",
    "DUMAS Eric-Anthony": "dumas-eric-anthony",
    "DUMAS FILS Alexandre": "dumas-fils-alexandre",
    "DUMAS PERE Alexandre": "dumas-pere-alexandre",
    "DUMAS-FEATHERSTONE Daisy": "dumas-featherstone-daisy",
    "DUMB TYPE ": "dumb-type",
    "DUMBLY Tug": "dumbly-tug",
    "DUMBSHOW ": "dumbshow",
    "DUMMELOW Tash": "dummelow-tash",
    "DUMONT Dawn": "dumont-dawn",
    "DUMONT Marla": "dumont-marla",
    "DUN Dennis": "dun-dennis",
    "DUN Tan": "dun-tan",
    "DUNBAR Andrea": "dunbar-andrea",
    "DUNBAR Jordan": "dunbar-jordan",
    "DUNBAR Kim": "dunbar-kim",
    "DUNBAR Mark": "dunbar-mark",
    "DUNBAR Michael": "dunbar-michael",
    "DUNBAR Paul Laurence": "dunbar-paul-laurence",
    "DUNBAR Robert": "dunbar-robert",
    "DUNBAR Zachary": "dunbar-zachary",
    "DUNCAN Barnie": "duncan-barnie",
    "DUNCAN Catherine": "duncan-catherine",
    "DUNCAN Clive": "duncan-clive",
    "DUNCAN David James": "duncan-david-james",
    "DUNCAN Emily Marie": "duncan-emily-marie",
    "DUNCAN Geoffrey": "duncan-geoffrey",
    "DUNCAN Graham": "duncan-graham",
    "DUNCAN Hal": "duncan-hal",
    "DUNCAN James": "duncan-james",
    "DUNCAN Janice": "duncan-janice",
    "DUNCAN Jody": "duncan-jody",
    "DUNCAN Katie": "duncan-katie",
    "DUNCAN Kirk": "duncan-kirk",
    "DUNCAN Martin": "duncan-martin",
    "DUNCAN Oonagh": "duncan-oonagh",
    "DUNCAN Paul": "duncan-paul",
    "DUNCAN Peter": "duncan-peter",
    "DUNCAN Ronald": "duncan-ronald",
    "DUNCAN Sarah M": "duncan-sarah-m",
    "DUNCAN Sheila": "duncan-sheila",
    "DUNCAN Thelma Myrtle": "duncan-thelma-myrtle",
    "DUNCAN Thembi": "duncan-thembi",
    "DUNCAN Thom": "duncan-thom",
    "DUNCAN William Carey": "duncan-william-carey",
    "DUNCANSON Julie": "duncanson-julie",
    "DUNCHEON Tim": "duncheon-tim",
    "DUNCOMBE Charles A": "duncombe-charles-a",
    "DUNCOMBE Peta": "duncombe-peta",
    "DUNCUM Ken": "duncum-ken",
    "DUNDAS Shane": "dundas-shane",
    "DUNDAS-GRANT Craig": "dundas-grant-craig",
    "DUNDEE Kulua": "dundee-kulua",
    "DUNDERDALE Sue": "dunderdale-sue",
    "DUNDY Calua": "dundy-calua",
    "DUNDY Elaine": "dundy-elaine",
    "DUNFORD Antony": "dunford-antony",
    "DUNFORD Caroline": "dunford-caroline",
    "DUNGAN Myles": "dungan-myles",
    "DUNGAN Ross": "dungan-ross",
    "DUNGATE Rod": "dungate-rod",
    "DUNGEY Lori": "dungey-lori",
    "DUNHAM Katherine": "dunham-katherine",
    "DUNHAM Leonard Joseph": "dunham-leonard-joseph",
    "DUNK Jim": "dunk-jim",
    "DUNKLEY Chris": "dunkley-chris",
    "DUNLAP Bridgette": "dunlap-bridgette",
    "DUNLAP Julie": "dunlap-julie",
    "DUNLAP S Melinda": "dunlap-s-melinda",
    "DUNLAP Valerie": "dunlap-valerie",
    "DUNLAP William": "dunlap-william",
    "DUNLEAVY Bernard": "dunleavy-bernard",
    "DUNLEAVY Vincent": "dunleavy-vincent",
    "DUNLOP Bill": "dunlop-bill",
    "DUNLOP Christopher": "dunlop-christopher",
    "DUNLOP Frank": "dunlop-frank",
    "DUNLOP Megan": "dunlop-megan",
    "DUNLOP Ricky": "dunlop-ricky",
    "DUNLOP Russell": "dunlop-russell",
    "DUNMORE Alix": "dunmore-alix",
    "DUNMORE Heather": "dunmore-heather",
    "DUNMORE John": "dunmore-john",
    "DUNN Antony": "dunn-antony",
    "DUNN Bernard": "dunn-bernard",
    "DUNN Beverley": "dunn-beverley",
    "DUNN Briony": "dunn-briony",
    "DUNN Clare": "dunn-clare",
    "DUNN Dale": "dunn-dale",
    "DUNN Doug": "dunn-doug",
    "DUNN Douglas": "dunn-douglas",
    "DUNN E Robert": "dunn-e-robert",
    "DUNN Emily": "dunn-emily",
    "DUNN Ian": "dunn-ian",
    "DUNN James": "dunn-james",
    "DUNN Jay": "dunn-jay",
    "DUNN Jeff": "dunn-jeff",
    "DUNN Jimmy": "dunn-jimmy",
    "DUNN Joan F": "dunn-joan-f",
    "DUNN Kate": "dunn-kate",
    "DUNN Kirk": "dunn-kirk",
    "DUNN Laura": "dunn-laura",
    "DUNN Lori": "dunn-lori",
    "DUNN Mark": "dunn-mark",
    "DUNN Mary": "dunn-mary",
    "DUNN Meg": "dunn-meg",
    "DUNN Nell": "dunn-nell",
    "DUNN Nicholas": "dunn-nicholas",
    "DUNN Paul": "dunn-paul",
    "DUNN Paul (1)": "dunn-paul-1",
    "DUNN Robert": "dunn-robert",
    "DUNN Roxy": "dunn-roxy",
    "DUNN Russ": "dunn-russ",
    "DUNN Ryan": "dunn-ryan",
    "DUNN Theo M": "dunn-theo-m",
    "DUNN Thomas C": "dunn-thomas-c",
    "DUNN Thomas G": "dunn-thomas-g",
    "DUNN Tom": "dunn-tom",
    "DUNNE Frank": "dunne-frank",
    "DUNNE Jess": "dunne-jess",
    "DUNNE John": "dunne-john",
    "DUNNE Lee": "dunne-lee",
    "DUNNE Melissa": "dunne-melissa",
    "DUNNE Owen": "dunne-owen",
    "DUNNE Peter": "dunne-peter",
    "DUNNE Philip": "dunne-philip",
    "DUNNE Sean": "dunne-sean",
    "DUNNE Shaun": "dunne-shaun",
    "DUNNE Will": "dunne-will",
    "DUNNELL-SMITH James": "dunnell-smith-james",
    "DUNNETT Alastair M": "dunnett-alastair-m",
    "DUNNING Philip": "dunning-philip",
    "DUNPHY Anne": "dunphy-anne",
    "DUNPHY Caroline": "dunphy-caroline",
    "DUNPHY Jack": "dunphy-jack",
    "DUNPHY Shay": "dunphy-shay",
    "DUNS Stornaway": "duns-stornaway",
    "DUNSKI Jonathan": "dunski-jonathan",
    "DUNSMORE Ross": "dunsmore-ross",
    "DUNSTAN Frederica": "dunstan-frederica",
    "DUNSTER Mark": "dunster-mark",
    "DUNSTER Matthew": "dunster-matthew",
    "DUNSTIN Darin": "dunstin-darin",
    "DUNSTONE Stephen": "dunstone-stephen",
    "DUNTHORNE Joe": "dunthorne-joe",
    "DUONG Le Quy": "duong-le-quy",
    "DUPRE Charlie": "dupre-charlie",
    "DUPREE Ceri": "dupree-ceri",
    "DUPREZ John": "duprez-john",
    "DUPUIS Herve": "dupuis-herve",
    "DUPUY Derek": "dupuy-derek",
    "DURAND Ray": "durand-ray",
    "DURANG Christopher": "durang-christopher",
    "DURANTE Craig": "durante-craig",
    "DURANTE Ed": "durante-ed",
    "DURAS Marguerite": "duras-marguerite",
    "DURBACH Errol": "durbach-errol",
    "DURBAND Alan": "durband-alan",
    "DURBIN Bruce W": "durbin-bruce-w",
    "DURBRIDGE Francis": "durbridge-francis",
    "DURCAN Paul": "durcan-paul",
    "DURELS Adolfo Costa": "durels-adolfo-costa",
    "DUREN Daniel": "duren-daniel",
    "DURER C S": "durer-c-s",
    "DURHAM James": "durham-james",
    "DURHAM Kelli": "durham-kelli",
    "DURHAM Vincent Terrell": "durham-vincent-terrell",
    "DURICKO Erma": "duricko-erma",
    "DURITZ Adam": "duritz-adam",
    "DURIVAGE-JACOBS Sarah": "durivage-jacobs-sarah",
    "DURKEE Norman": "durkee-norman",
    "DURKEE Sarah": "durkee-sarah",
    "DURKIN Tish": "durkin-tish",
    "DURLING Roger Arturo": "durling-roger-arturo",
    "DURMUSH Fatma": "durmush-fatma",
    "DURNENKOV Vyacheslav": "durnenkov-vyacheslav",
    "DURNEZ Eric": "durnez-eric",
    "DURNIN John": "durnin-john",
    "DURNING Jeanie": "durning-jeanie",
    "DUROJAIYE Adegoke": "durojaiye-adegoke",
    "DUROVICOVA Natasha": "durovicova-natasha",
    "DURRAH James": "durrah-james",
    "DURRAH James W": "durrah-james-w",
    "DURRANT Geraldine": "durrant-geraldine",
    "DURRANT Peter": "durrant-peter",
    "DURRELL Lawrence": "durrell-lawrence",
    "DURRENMATT Friedrich": "durrenmatt-friedrich",
    "DURRINGER Xavier": "durringer-xavier",
    "D'URSO Sandra": "d-urso-sandra",
    "DURST James": "durst-james",
    "DURSTEWITZ Mark": "durstewitz-mark",
    "DURUZ James": "duruz-james",
    "DURWOOD Scout": "durwood-scout",
    "DURY Ian": "dury-ian",
    "DURYEE Cornelia": "duryee-cornelia",
    "DUSA Piero": "dusa-piero",
    "DUSETTE Chantelle": "dusette-chantelle",
    "DUSING David": "dusing-david",
    "DUSS Roger": "duss-roger",
    "DUSSAULT Louisette": "dussault-louisette",
    "D'USSEAU Arnaud": "d-usseau-arnaud",
    "DUST ": "dust",
    "DUTHIE James": "duthie-james",
    "DUTILH Deborah": "dutilh-deborah",
    "DUTT Sukhendu": "dutt-sukhendu",
    "DUTTA Shomit": "dutta-shomit",
    "DUTTON Jaquie": "dutton-jaquie",
    "DUTTON Sandra": "dutton-sandra",
    "DUUS Anders": "duus-anders",
    "DUVA Christopher": "duva-christopher",
    "DUVALL Any Grau": "duvall-any-grau",
    "DUVALL Bill": "duvall-bill",
    "DUWHITE Timothy": "duwhite-timothy",
    "DUX Francis": "dux-francis",
    "DUXBURY Andrew": "duxbury-andrew",
    "DUXBURY Robert": "duxbury-robert",
    "DUZOVA Cem": "duzova-cem",
    "DV8 PHYSICAL ": "dv8-physical",
    "D'VER Stuart": "d-ver-stuart",
    "DVORACEK Delray": "dvoracek-delray",
    "DVORAK Paul F": "dvorak-paul-f",
    "DVORETZKY Eward": "dvoretzky-eward",
    "DVORKIN Ellie": "dvorkin-ellie",
    "DWIGGINS Tyler": "dwiggins-tyler",
    "DWORKIN Susan": "dworkin-susan",
    "DWORKIN Susie": "dworkin-susie",
    "DWORMAN Steven": "dworman-steven",
    "DWORZAN Helene": "dworzan-helene",
    "DWYER CeCe": "dwyer-cece",
    "DWYER Frank": "dwyer-frank",
    "DWYER Isaac": "dwyer-isaac",
    "DWYER Jill": "dwyer-jill",
    "DWYER John": "dwyer-john",
    "DWYER Jon": "dwyer-jon",
    "DWYER K J": "dwyer-k-j",
    "DWYER Killy": "dwyer-killy",
    "DWYER Paul": "dwyer-paul",
    "DYAS Grace": "dyas-grace",
    "DYBALL R": "dyball-r",
    "DYBAT Kenneth": "dybat-kenneth",
    "DYBEK Stuart": "dybek-stuart",
    "DYCHES Samuel": "dyches-samuel",
    "DYDE Sue": "dyde-sue",
    "DYE Bru": "dye-bru",
    "DYE Matthew": "dye-matthew",
    "DYER C Raymond": "dyer-c-raymond",
    "DYER Callum": "dyer-callum",
    "DYER Charles": "dyer-charles",
    "DYER Eric": "dyer-eric",
    "DYER Frank": "dyer-frank",
    "DYER Gavin": "dyer-gavin",
    "DYER John": "dyer-john",
    "DYER Julian": "dyer-julian",
    "DYER Kevin": "dyer-kevin",
    "DYER William": "dyer-william",
    "DYJK Otto": "dyjk-otto",
    "DYKEMAN Molly": "dykeman-molly",
    "DYKES Steven": "dykes-steven",
    "DYKSTRA Brian": "dykstra-brian",
    "DYKSTRA Russell": "dykstra-russell",
    "DYKSTRA Ted": "dykstra-ted",
    "DYLAN Bob": "dylan-bob",
    "DYLAN J P": "dylan-j-p",
    "DYMENT M": "dyment-m",
    "DYMOKE Katie": "dymoke-katie",
    "DYMOND Andrea": "dymond-andrea",
    "DYNASTY HANDBAG ": "dynasty-handbag",
    "DYNE Michael": "dyne-michael",
    "DYNE Nicholas": "dyne-nicholas",
    "DYRECTOR Joyce": "dyrector-joyce",
    "DYRECTOR Stanley": "dyrector-stanley",
    "DYRENFORTH James": "dyrenforth-james",
    "DYSFUNCTIONAL THEATRE COMPANY ": "dysfunctional-theatre-company",
    "DYSON Catherine": "dyson-catherine",
    "DYSON Jeremy": "dyson-jeremy",
    "DYSON Ketaki Kushari": "dyson-ketaki-kushari",
    "DYSON Nancy": "dyson-nancy",
    "DYSON Victoria": "dyson-victoria",
    "DYSON-MCGREGOR Rachael": "dyson-mcgregor-rachael",
    "DYVILLE Jack": "dyville-jack",
    "DZEBO Alena": "dzebo-alena",
    "DZHERZHINSKY Aleksander": "dzherzhinsky-aleksander",
    "DZHERZHINSKY Stephan": "dzherzhinsky-stephan",
    "DZIEGLEWSKA Katarzyna": "dzieglewska-katarzyna",
    "DZINWASHA Takudzwa": "dzinwasha-takudzwa",
    "DZURICKY Beth": "dzuricky-beth"
  }
};