export default {
  "metadata": {
    "results": 290,
    "timeStamp": "2025-12-05T21:23:56.827Z",
    "url": "https://www.doollee.com/PlaywrightsE/E_playwrights_a-f.php"
  },
  "authors": {
    "EACH Molly": "each-molly",
    "EACH WORLD ": "each-world",
    "EADES Alex": "eades-alex",
    "EADINGTON Joan": "eadington-joan",
    "EADMEAD Amantha": "eadmead-amantha",
    "EADY Hannah": "eady-hannah",
    "EAGER Edward": "eager-edward",
    "EAGLEHAWLK Wallea": "eaglehawlk-wallea",
    "EAGLES Stephen": "eagles-stephen",
    "EAGLESHAM Graham": "eaglesham-graham",
    "EAGLETON Oliver": "eagleton-oliver",
    "EAGLETON Terry": "eagleton-terry",
    "EAKIN Thelma": "eakin-thelma",
    "EALDEN Toby": "ealden-toby",
    "EALES Steve": "eales-steve",
    "EAMES J D": "eames-j-d",
    "EAMES Manon": "eames-manon",
    "EARING A C": "earing-a-c",
    "EARL Andrea": "earl-andrea",
    "EARL Vanessa": "earl-vanessa",
    "EARLE Belinda": "earle-belinda",
    "EARLE Christopher": "earle-christopher",
    "EARLE David": "earle-david",
    "EARLE Emma": "earle-emma",
    "EARLE Susan": "earle-susan",
    "EARLEY Eric": "earley-eric",
    "EARLS Nicholas": "earls-nicholas",
    "EARLY Ann": "early-ann",
    "EARLY Chas": "early-chas",
    "EARLY Clayton": "early-clayton",
    "EARLY Jacqueline": "early-jacqueline",
    "EARLY John": "early-john",
    "EARLY Nancy": "early-nancy",
    "EARNEST Cathy": "earnest-cathy",
    "EARNEST John David": "earnest-john-david",
    "EARNEST Matthew": "earnest-matthew",
    "EARNHART Stephen": "earnhart-stephen",
    "EARNSHAW Tony": "earnshaw-tony",
    "EARTHFALL ": "earthfall",
    "EASMON R Sarif": "easmon-r-sarif",
    "EASON Bo": "eason-bo",
    "EASON Joe Oliver": "eason-joe-oliver",
    "EASON Laura": "eason-laura",
    "EASON Tom": "eason-tom",
    "EASSON Kay": "easson-kay",
    "EAST Donald F": "east-donald-f",
    "EAST Helen": "east-helen",
    "EAST Lizzie": "east-lizzie",
    "EAST Robert": "east-robert",
    "EAST Ron": "east-ron",
    "EAST CLEVLAND COMMUNITY THEATRE ": "east-clevland-community-theatre",
    "EASTER Mark": "easter-mark",
    "EASTERBY Jony": "easterby-jony",
    "EASTERLING H J": "easterling-h-j",
    "EASTERLING P E": "easterling-p-e",
    "EASTERN ANGLES ": "eastern-angles",
    "EASTGATE Nigel": "eastgate-nigel",
    "EASTHER Elisabeth": "easther-elisabeth",
    "EASTMAN Charles": "eastman-charles",
    "EASTMAN George": "eastman-george",
    "EASTMAN George C": "eastman-george-c",
    "EASTMAN Gilbert C": "eastman-gilbert-c",
    "EASTMAN Helen": "eastman-helen",
    "EASTMAN Merridy": "eastman-merridy",
    "EASTMAN P D": "eastman-p-d",
    "EASTMAN Sonhara J": "eastman-sonhara-j",
    "EASTON Alex": "easton-alex",
    "EASTON Cat": "easton-cat",
    "EASTON Ken": "easton-ken",
    "EASTON Kirsten": "easton-kirsten",
    "EASTON Sidney": "easton-sidney",
    "EASTWOOD Curtis": "eastwood-curtis",
    "EASTWOOD E C": "eastwood-e-c",
    "EATOCK Helen": "eatock-helen",
    "EATON Bob": "eaton-bob",
    "EATON Danny": "eaton-danny",
    "EATON David": "eaton-david",
    "EATON Dawn": "eaton-dawn",
    "EATON Dilys": "eaton-dilys",
    "EATON Edward": "eaton-edward",
    "EATON Holly M": "eaton-holly-m",
    "EATON James": "eaton-james",
    "EATON Kate": "eaton-kate",
    "EATON Lori": "eaton-lori",
    "EATON Mark Allen": "eaton-mark-allen",
    "EATON Michael": "eaton-michael",
    "EATON Nathaniel": "eaton-nathaniel",
    "EATON Robin": "eaton-robin",
    "EATON Sam": "eaton-sam",
    "EATON-JONES Barnaby": "eaton-jones-barnaby",
    "EATOUGH Graham": "eatough-graham",
    "EAVES Christopher": "eaves-christopher",
    "EBARP Erik N": "ebarp-erik-n",
    "EBASHI A I": "ebashi-a-i",
    "EBB Fred": "ebb-fred",
    "EBBS Dan": "ebbs-dan",
    "EBEJER Francis": "ebejer-francis",
    "EBERHARD Leslie": "eberhard-leslie",
    "EBERHARDT Sharon": "eberhardt-sharon",
    "EBERLEIN Jared": "eberlein-jared",
    "EBERSOLE Lisa": "ebersole-lisa",
    "EBERT Roger": "ebert-roger",
    "EBERWEIN Eric": "eberwein-eric",
    "EBIHARA Richard": "ebihara-richard",
    "EBLE Julie": "eble-julie",
    "EBONY TALENT ": "ebony-talent",
    "EBOWE Efosa": "ebowe-efosa",
    "EBSEN Buddy": "ebsen-buddy",
    "ECCHERT Elizabeth": "ecchert-elizabeth",
    "ECCHERT Marino": "ecchert-marino",
    "ECCLES Frank": "eccles-frank",
    "ECCLES Tif": "eccles-tif",
    "ECCLESHARE Thomas": "eccleshare-thomas",
    "ECCLESTON Greg": "eccleston-greg",
    "ECHEGARAY Jose": "echegaray-jose",
    "ECHEVERRIA Florencia Martinez": "echeverria-florencia-martinez",
    "ECHOL Ann J": "echol-ann-j",
    "ECHOUAFNI Houda": "echouafni-houda",
    "ECKERSLEY Adrian": "eckersley-adrian",
    "ECKERSLEY Tom": "eckersley-tom",
    "ECKERT Paul": "eckert-paul",
    "ECKERT Rinde": "eckert-rinde",
    "ECKERT Scott": "eckert-scott",
    "ECKERT Scott A": "eckert-scott-a",
    "ECKERT Sierra": "eckert-sierra",
    "ECKHART Alan": "eckhart-alan",
    "ECKMAN Deborah": "eckman-deborah",
    "ECKSTEIN Zac": "eckstein-zac",
    "ECLAIR Jenny": "eclair-jenny",
    "ECLAIR-POWELL Phoebe": "eclair-powell-phoebe",
    "ECOBELLI Lora Lee": "ecobelli-lora-lee",
    "ECOBELLI Tom": "ecobelli-tom",
    "ECONOMOPOULOS Spiro": "economopoulos-spiro",
    "EDA-YOUNG Barbara": "eda-young-barbara",
    "EDDEY Paul": "eddey-paul",
    "EDDINGTON Alex": "eddington-alex",
    "EDDISON Robert": "eddison-robert",
    "EDDOLLS Phil": "eddolls-phil",
    "EDDY Alex James": "eddy-alex-james",
    "EDDY David": "eddy-david",
    "EDDY Jillie Mae": "eddy-jillie-mae",
    "EDDY Joan": "eddy-joan",
    "EDE Adam": "ede-adam",
    "EDE Ethan": "ede-ethan",
    "EDELE Lizz": "edele-lizz",
    "EDELMAN Nate Rufus": "edelman-nate-rufus",
    "EDELSON Loren": "edelson-loren",
    "EDELSON Rae": "edelson-rae",
    "EDELSTEIN Barry": "edelstein-barry",
    "EDELSTEIN Gordon": "edelstein-gordon",
    "EDELSTEIN Lisa": "edelstein-lisa",
    "EDEN Beth": "eden-beth",
    "EDEN Dan": "eden-dan",
    "EDEN David Chayim": "eden-david-chayim",
    "EDEN Evert": "eden-evert",
    "EDEN Mark": "eden-mark",
    "EDEN Paul": "eden-paul",
    "EDEN Roy": "eden-roy",
    "EDEN Tony": "eden-tony",
    "EDENBOROUGH Sam": "edenborough-sam",
    "EDGAR Alison": "edgar-alison",
    "EDGAR David": "edgar-david",
    "EDGAR Iwan": "edgar-iwan",
    "EDGAR Jennifer": "edgar-jennifer",
    "EDGAR John": "edgar-john",
    "EDGAR Kate": "edgar-kate",
    "EDGAR Michael": "edgar-michael",
    "EDGECOMBE David": "edgecombe-david",
    "EDGERTON Clyde": "edgerton-clyde",
    "EDGERTON Earle": "edgerton-earle",
    "EDGERTON Matt": "edgerton-matt",
    "EDGEWORTH Patrick": "edgeworth-patrick",
    "EDGINGTON Jonathan": "edgington-jonathan",
    "EDGREN Derick": "edgren-derick",
    "EDIDI Dane Figueroa": "edidi-dane-figueroa",
    "EDIE Elise Forier": "edie-elise-forier",
    "EDINBOROUGH Campbell": "edinborough-campbell",
    "EDIPIDI Eleni": "edipidi-eleni",
    "EDIS Steve": "edis-steve",
    "EDISON Matthew": "edison-matthew",
    "EDKIN Joe": "edkin-joe",
    "EDKINS Lucy": "edkins-lucy",
    "EDLER Lucas S": "edler-lucas-s",
    "EDLESTON Kathleen": "edleston-kathleen",
    "EDLOW Fielding": "edlow-fielding",
    "EDMEAD Amantha": "edmead-amantha",
    "EDMETT Nicholas": "edmett-nicholas",
    "EDMOND Murray": "edmond-murray",
    "EDMOND Terence": "edmond-terence",
    "EDMONDS Charles Michael": "edmonds-charles-michael",
    "EDMONDS Henriette": "edmonds-henriette",
    "EDMONDS Leigh": "edmonds-leigh",
    "EDMONDS Paul": "edmonds-paul",
    "EDMONDS Philip": "edmonds-philip",
    "EDMONDS Randolph": "edmonds-randolph",
    "EDMONDS Rory": "edmonds-rory",
    "EDMONDSON Adrian": "edmondson-adrian",
    "EDMONDSON Alexandra": "edmondson-alexandra",
    "EDMUND Chris": "edmund-chris",
    "EDMUND Reginald": "edmund-reginald",
    "EDMUNDS Candice": "edmunds-candice",
    "EDMUNDS John": "edmunds-john",
    "EDMUNDS Reginald ": "edmunds-reginald",
    "EDMUNDS Richard": "edmunds-richard",
    "EDMUNDS Robert": "edmunds-robert",
    "EDMUNDSON Helen": "edmundson-helen",
    "EDNEY David": "edney-david",
    "EDO Eva": "edo-eva",
    "EDOGA Miata": "edoga-miata",
    "EDOSOMWAN Esosa": "edosomwan-esosa",
    "EDRIDGE-WAKS Robert": "edridge-waks-robert",
    "EDSON Margaret": "edson-margaret",
    "EDVARDSEN Mette": "edvardsen-mette",
    "EDWALL Allan": "edwall-allan",
    "EDWARD Bryan": "edward-bryan",
    "EDWARD Jaimee": "edward-jaimee",
    "EDWARD Joseph": "edward-joseph",
    "EDWARD Maurice": "edward-maurice",
    "EDWARD-HUGHES David": "edward-hughes-david",
    "EDWARDS Alan": "edwards-alan",
    "EDWARDS Alexandra": "edwards-alexandra",
    "EDWARDS Amanda": "edwards-amanda",
    "EDWARDS Anderson": "edwards-anderson",
    "EDWARDS Andy": "edwards-andy",
    "EDWARDS Blake": "edwards-blake",
    "EDWARDS Caitlin Innes": "edwards-caitlin-innes",
    "EDWARDS Caterina": "edwards-caterina",
    "EDWARDS Craig": "edwards-craig",
    "EDWARDS Craig Alan": "edwards-craig-alan",
    "EDWARDS Darren": "edwards-darren",
    "EDWARDS Denis": "edwards-denis",
    "EDWARDS Dic": "edwards-dic",
    "EDWARDS Dyfed": "edwards-dyfed",
    "EDWARDS Elizabeth": "edwards-elizabeth",
    "EDWARDS F": "edwards-f",
    "EDWARDS Finneas": "edwards-finneas",
    "EDWARDS Frank": "edwards-frank",
    "EDWARDS Gale": "edwards-gale",
    "EDWARDS Greg": "edwards-greg",
    "EDWARDS Gus": "edwards-gus",
    "EDWARDS Gwynne": "edwards-gwynne",
    "EDWARDS Hazel": "edwards-hazel",
    "EDWARDS Iris": "edwards-iris",
    "EDWARDS J B": "edwards-j-b",
    "EDWARDS James Eldred": "edwards-james-eldred",
    "EDWARDS James V": "edwards-james-v",
    "EDWARDS Janet": "edwards-janet",
    "EDWARDS Jeff": "edwards-jeff",
    "EDWARDS Jessica": "edwards-jessica",
    "EDWARDS John": "edwards-john",
    "EDWARDS Joseph": "edwards-joseph",
    "EDWARDS Julia C": "edwards-julia-c",
    "EDWARDS Justin": "edwards-justin",
    "EDWARDS Keith": "edwards-keith",
    "EDWARDS Linda Wood": "edwards-linda-wood",
    "EDWARDS M": "edwards-m",
    "EDWARDS Mark": "edwards-mark",
    "EDWARDS Martin": "edwards-martin",
    "EDWARDS Matthew J": "edwards-matthew-j",
    "EDWARDS Meredith": "edwards-meredith",
    "EDWARDS Michael": "edwards-michael",
    "EDWARDS Michael (1)": "edwards-michael-1",
    "EDWARDS Mike": "edwards-mike",
    "EDWARDS Neil A": "edwards-neil-a",
    "EDWARDS Nicholas": "edwards-nicholas",
    "EDWARDS Owen Dudley": "edwards-owen-dudley",
    "EDWARDS Pat": "edwards-pat",
    "EDWARDS Patricia": "edwards-patricia",
    "EDWARDS Paul": "edwards-paul",
    "EDWARDS Peter": "edwards-peter",
    "EDWARDS Phillip": "edwards-phillip",
    "EDWARDS Rex": "edwards-rex",
    "EDWARDS Ron": "edwards-ron",
    "EDWARDS Ronnie Claire": "edwards-ronnie-claire",
    "EDWARDS Royce": "edwards-royce",
    "EDWARDS S W": "edwards-s-w",
    "EDWARDS Sherman": "edwards-sherman",
    "EDWARDS Sian": "edwards-sian",
    "EDWARDS Stephen": "edwards-stephen",
    "EDWARDS T J": "edwards-t-j",
    "EDWARDS Timothy": "edwards-timothy",
    "EDWARDS Tony": "edwards-tony",
    "EDWARDS Waylon": "edwards-waylon",
    "EDWARDS Yvonne": "edwards-yvonne",
    "EDWARDS Zena": "edwards-zena",
    "EDWARTOWSKI Margaret": "edwartowski-margaret",
    "EDWARTOWSKI Melissa": "edwartowski-melissa",
    "EFFINGER-WEINTRAUB Eli": "effinger-weintraub-eli",
    "EFFLER Damian": "effler-damian",
    "EFRON Marshall": "efron-marshall"
  }
};