export default {
  "metadata": {
    "results": 351,
    "timeStamp": "2025-12-05T21:24:00.523Z",
    "url": "https://www.doollee.com/PlaywrightsE/E_playwrights_g-l.php"
  },
  "authors": {
    "EGAN Chris": "egan-chris",
    "EGAN Constance Humphrey": "egan-constance-humphrey",
    "EGAN David": "egan-david",
    "EGAN James": "egan-james",
    "EGAN Marty": "egan-marty",
    "EGAN Michael": "egan-michael",
    "EGAN Robert": "egan-robert",
    "EGBUNA Obi B": "egbuna-obi-b",
    "EGER Henrik": "eger-henrik",
    "EGERMAN Ben": "egerman-ben",
    "EGERTON Simon": "egerton-simon",
    "EGGERT Joakim": "eggert-joakim",
    "EGGINTON Rob": "egginton-rob",
    "EGGLESTON John": "eggleston-john",
    "EGGLETON Jennie": "eggleton-jennie",
    "EGGS COLLECTIVE ": "eggs-collective",
    "EGILSON Joan": "egilson-joan",
    "EGK Werner": "egk-werner",
    "EGLOFF Elizabeth": "egloff-elizabeth",
    "EGLOFF Holley": "egloff-holley",
    "EGNOS Bertha": "egnos-bertha",
    "EGOYAN Atom": "egoyan-atom",
    "EGRESSY Zoltan": "egressy-zoltan",
    "EHLERS Heather": "ehlers-heather",
    "EHLY Kim": "ehly-kim",
    "EHN Erik": "ehn-erik",
    "EHRENBERG Bette S": "ehrenberg-bette-s",
    "EHRENREICH Alden": "ehrenreich-alden",
    "EHRENREICH Jake": "ehrenreich-jake",
    "EHRHARDT Debra": "ehrhardt-debra",
    "EHRLICH C J": "ehrlich-c-j",
    "EHRLICH Stephanie": "ehrlich-stephanie",
    "EHRMANN Amanda": "ehrmann-amanda",
    "EICHELBERGER Ethyl": "eichelberger-ethyl",
    "EICHENBAUM Miriam": "eichenbaum-miriam",
    "EICHMAN Mark": "eichman-mark",
    "EICHNER Billy": "eichner-billy",
    "EICKE Harry": "eicke-harry",
    "EICKMANN Christopher": "eickmann-christopher",
    "EIGHNER Lars": "eighner-lars",
    "EIKERENKOETTER Allison": "eikerenkoetter-allison",
    "EILBACHER Karen": "eilbacher-karen",
    "EILENBERG Charlotte": "eilenberg-charlotte",
    "EILER Jim": "eiler-jim",
    "EILERT Gundi": "eilert-gundi",
    "EINARSSON Svein": "einarsson-svein",
    "EINBINDER Cory": "einbinder-cory",
    "EINBINDER Harvey": "einbinder-harvey",
    "EINHORN Abe": "einhorn-abe",
    "EINHORN Aliza": "einhorn-aliza",
    "EINHORN Arthur": "einhorn-arthur",
    "EINHORN Edward": "einhorn-edward",
    "EINHORN Faryn": "einhorn-faryn",
    "EINHORN Harry": "einhorn-harry",
    "EINSPANIER Sarah": "einspanier-sarah",
    "EINSTEIN Rob": "einstein-rob",
    "EIRIAN Sion": "eirian-sion",
    "EISELE Robert": "eisele-robert",
    "EISEMAN Paul": "eiseman-paul",
    "EISEN Alexander Gregory": "eisen-alexander-gregory",
    "EISEN Nick": "eisen-nick",
    "EISEN Seth": "eisen-seth",
    "EISENBACH Helen": "eisenbach-helen",
    "EISENBERG Avner": "eisenberg-avner",
    "EISENBERG Deborah": "eisenberg-deborah",
    "EISENBERG Jess": "eisenberg-jess",
    "EISENBERG Jesse": "eisenberg-jesse",
    "EISENBERG Mike": "eisenberg-mike",
    "EISENBERG Ned": "eisenberg-ned",
    "EISENBERG Rick": "eisenberg-rick",
    "EISENBERG Victor": "eisenberg-victor",
    "EISENMAN James M": "eisenman-james-m",
    "EISENSTEIN Janet": "eisenstein-janet",
    "EISENSTEIN Linda": "eisenstein-linda",
    "EISENSTEIN Sam": "eisenstein-sam",
    "EISENSTOCK Jonah": "eisenstock-jonah",
    "EISLER Ken": "eisler-ken",
    "EISLER Lucinka": "eisler-lucinka",
    "EISMAN Mark": "eisman-mark",
    "EISMAN Paul": "eisman-paul",
    "EISMEN Lisa": "eismen-lisa",
    "EISNBACH Helen": "eisnbach-helen",
    "EISNER Jane": "eisner-jane",
    "EISNER Michael": "eisner-michael",
    "EISTENSTARK Dave": "eistenstark-dave",
    "EITE Barbara A": "eite-barbara-a",
    "EITEL Barry": "eitel-barry",
    "EITZEL Mark": "eitzel-mark",
    "EK PERFORMANCE ": "ek-performance",
    "EKIZIAN John G": "ekizian-john-g",
    "EKLAND Britt": "ekland-britt",
    "EKLOND John Layton": "eklond-john-layton",
    "EKSTRAND Laura": "ekstrand-laura",
    "EKSTROM Peter": "ekstrom-peter",
    "EKULONA Ademola": "ekulona-ademola",
    "EL Freedome": "el-freedome",
    "EL Leatrice": "el-leatrice",
    "EL ANSARY Chirine": "el-ansary-chirine",
    "EL BUSHRA Suhayla": "el-bushra-suhayla",
    "EL GUINDI Yussef": "el-guindi-yussef",
    "EL HAGAR Adam": "el-hagar-adam",
    "EL KHATIB Mohamed": "el-khatib-mohamed",
    "EL KHOURY Tania": "el-khoury-tania",
    "EL MUHAJIR ": "el-muhajir",
    "EL NUSAIRI Sara": "el-nusairi-sara",
    "EL PATIO TEATRO ": "el-patio-teatro",
    "EL TAMAMI Weam": "el-tamami-weam",
    "EL TRICICLE ": "el-tricicle",
    "ELAM Irving": "elam-irving",
    "ELAMS Inua": "elams-inua",
    "ELAN WALES ": "elan-wales",
    "ELANDIS Kelli": "elandis-kelli",
    "ELANGOVAN ": "elangovan",
    "EL-ATTAR Suehyla": "el-attar-suehyla",
    "ELAYNOW Michael": "elaynow-michael",
    "ELBAKYAN Arthur": "elbakyan-arthur",
    "EL-BUSHRA Suhayla": "el-bushra-suhayla",
    "ELCOCK Patricia": "elcock-patricia",
    "ELDER Lonne": "elder-lonne",
    "ELDER Marina": "elder-marina",
    "ELDER Michael": "elder-michael",
    "ELDER Mollie": "elder-mollie",
    "ELDRED Ava": "eldred-ava",
    "ELDREDGE Kay": "eldredge-kay",
    "ELDREDGE Kelly Jo": "eldredge-kelly-jo",
    "ELDREDGE Letitia": "eldredge-letitia",
    "ELDRIDGE Becky": "eldridge-becky",
    "ELDRIDGE David": "eldridge-david",
    "ELDRIDGE Elizabeth": "eldridge-elizabeth",
    "ELDRIDGE Kay": "eldridge-kay",
    "ELDRIDGE Sandra": "eldridge-sandra",
    "ELECTRIC COMPANY ": "electric-company",
    "ELECTRIC HEAD ": "electric-head",
    "ELEFTERION Edward": "elefterion-edward",
    "ELEN Angharad": "elen-angharad",
    "ELEN Ceri": "elen-ceri",
    "ELERI Carys": "eleri-carys",
    "ELERS-JARLEMAN Agneta": "elers-jarleman-agneta",
    "ELETHEA Abba": "elethea-abba",
    "ELEVATOR REPAIR SERVICE ": "elevator-repair-service",
    "ELEY Gavin": "eley-gavin",
    "ELFENBEIN Curtis": "elfenbein-curtis",
    "ELFYN Menna": "elfyn-menna",
    "ELGAR Geoffrey": "elgar-geoffrey",
    "ELGOOD Tim": "elgood-tim",
    "ELGSTRAND Kris": "elgstrand-kris",
    "ELGUE Maxime": "elgue-maxime",
    "ELHAI Robert A": "elhai-robert-a",
    "EL-HAKIM Tewfik": "el-hakim-tewfik",
    "ELI Quinn D": "eli-quinn-d",
    "ELIAS Isidore": "elias-isidore",
    "ELIAS Jane": "elias-jane",
    "ELIAS Michael": "elias-michael",
    "ELIASCH Amanda": "eliasch-amanda",
    "ELIASON James": "eliason-james",
    "ELICE Eric": "elice-eric",
    "ELICE Rick": "elice-rick",
    "ELIE Rachelle": "elie-rachelle",
    "ELIET David": "eliet-david",
    "ELINA Rick A": "elina-rick-a",
    "ELINGER Jared": "elinger-jared",
    "ELIOT T S": "eliot-t-s",
    "ELIOT Tim": "eliot-tim",
    "ELIRAZ Israel": "eliraz-israel",
    "ELIS Islwyn Ffowc": "elis-islwyn-ffowc",
    "ELISCU Edward": "eliscu-edward",
    "ELISCU Laurie": "eliscu-laurie",
    "ELISH Dan": "elish-dan",
    "ELISHA Danielle": "elisha-danielle",
    "ELISHA Ron": "elisha-ron",
    "ELISTON Mike": "eliston-mike",
    "ELISTON, JR E Burns": "eliston-jr-e-burns",
    "ELIZABETH Helen": "elizabeth-helen",
    "ELIZABETH M": "elizabeth-m",
    "ELJANABI Abas": "eljanabi-abas",
    "ELK Rob": "elk-rob",
    "EL-KHAIRY Omar": "el-khairy-omar",
    "EL-KHOURY Rinsala": "el-khoury-rinsala",
    "ELKIN Gilly": "elkin-gilly",
    "ELKIN Jessica": "elkin-jessica",
    "ELKINGTON John": "elkington-john",
    "ELKINS Doug": "elkins-doug",
    "ELKINS Hillel": "elkins-hillel",
    "ELKINS Peter": "elkins-peter",
    "ELKINS Stephen": "elkins-stephen",
    "ELKINS Stephen Anthony": "elkins-stephen-anthony",
    "ELKS Edward": "elks-edward",
    "ELLACOTT Nigel": "ellacott-nigel",
    "ELLAMS Inua": "ellams-inua",
    "ELLAMS Pippa": "ellams-pippa",
    "ELLEFSON Merry": "ellefson-merry",
    "ELLEMARK Ulrika": "ellemark-ulrika",
    "ELLEN Cliff": "ellen-cliff",
    "ELLENBOGEN Nicholas": "ellenbogen-nicholas",
    "ELLENTUCK Ben": "ellentuck-ben",
    "ELLERT Gundi": "ellert-gundi",
    "ELLEX Lisa": "ellex-lisa",
    "ELLICOTT Douglas": "ellicott-douglas",
    "ELLINGTON Justin": "ellington-justin",
    "ELLINSON Lucy": "ellinson-lucy",
    "ELLIOT Alistair": "elliot-alistair",
    "ELLIOT Anna Maria": "elliot-anna-maria",
    "ELLIOT Bixby": "elliot-bixby",
    "ELLIOT Daniel": "elliot-daniel",
    "ELLIOT David": "elliot-david",
    "ELLIOT Elizabeth": "elliot-elizabeth",
    "ELLIOT Henry": "elliot-henry",
    "ELLIOT Jack": "elliot-jack",
    "ELLIOT John": "elliot-john",
    "ELLIOT Liz": "elliot-liz",
    "ELLIOT Lorne": "elliot-lorne",
    "ELLIOT Marc": "elliot-marc",
    "ELLIOT Olga": "elliot-olga",
    "ELLIOT Pearse": "elliot-pearse",
    "ELLIOTT Aidan": "elliott-aidan",
    "ELLIOTT Annie Harrison": "elliott-annie-harrison",
    "ELLIOTT Barry": "elliott-barry",
    "ELLIOTT Cathy": "elliott-cathy",
    "ELLIOTT Chris Lorne": "elliott-chris-lorne",
    "ELLIOTT Dean": "elliott-dean",
    "ELLIOTT Devlin": "elliott-devlin",
    "ELLIOTT Eliza": "elliott-eliza",
    "ELLIOTT Geoff": "elliott-geoff",
    "ELLIOTT Greg": "elliott-greg",
    "ELLIOTT J Sean": "elliott-j-sean",
    "ELLIOTT John": "elliott-john",
    "ELLIOTT Jonathan": "elliott-jonathan",
    "ELLIOTT Joshua": "elliott-joshua",
    "ELLIOTT Karen": "elliott-karen",
    "ELLIOTT Kelly": "elliott-kelly",
    "ELLIOTT Kenneth": "elliott-kenneth",
    "ELLIOTT Lynn": "elliott-lynn",
    "ELLIOTT Michelle": "elliott-michelle",
    "ELLIOTT Naneki": "elliott-naneki",
    "ELLIOTT Nicholas": "elliott-nicholas",
    "ELLIOTT Paul": "elliott-paul",
    "ELLIOTT Paul (1)": "elliott-paul-1",
    "ELLIOTT Robert": "elliott-robert",
    "ELLIOTT Sarah": "elliott-sarah",
    "ELLIOTT Searle": "elliott-searle",
    "ELLIOTT Stephan": "elliott-stephan",
    "ELLIOTT Sumner Locke": "elliott-sumner-locke",
    "ELLIOTT TJ": "elliott-tj",
    "ELLIOTT Tom": "elliott-tom",
    "ELLIOTT Winnie": "elliott-winnie",
    "ELLIS Alan": "ellis-alan",
    "ELLIS Alex": "ellis-alex",
    "ELLIS Andy": "ellis-andy",
    "ELLIS Becky": "ellis-becky",
    "ELLIS Ben": "ellis-ben",
    "ELLIS Bob": "ellis-bob",
    "ELLIS Brandon": "ellis-brandon",
    "ELLIS Brendan": "ellis-brendan",
    "ELLIS Bret Easton": "ellis-bret-easton",
    "ELLIS Bryan": "ellis-bryan",
    "ELLIS Christopher": "ellis-christopher",
    "ELLIS Daniel": "ellis-daniel",
    "ELLIS David": "ellis-david",
    "ELLIS Duncan": "ellis-duncan",
    "ELLIS Edith": "ellis-edith",
    "ELLIS Elizabeth": "ellis-elizabeth",
    "ELLIS Gareth": "ellis-gareth",
    "ELLIS Grace": "ellis-grace",
    "ELLIS Hannah": "ellis-hannah",
    "ELLIS Hugh": "ellis-hugh",
    "ELLIS James Anthony": "ellis-james-anthony",
    "ELLIS Jamil": "ellis-jamil",
    "ELLIS Jodie": "ellis-jodie",
    "ELLIS John": "ellis-john",
    "ELLIS John (1)": "ellis-john-1",
    "ELLIS John Caldwell": "ellis-john-caldwell",
    "ELLIS Julia Richdale": "ellis-julia-richdale",
    "ELLIS Keith": "ellis-keith",
    "ELLIS Lee G": "ellis-lee-g",
    "ELLIS Lois": "ellis-lois",
    "ELLIS Lynne": "ellis-lynne",
    "ELLIS Marian": "ellis-marian",
    "ELLIS Mark": "ellis-mark",
    "ELLIS Michael J": "ellis-michael-j",
    "ELLIS Nels'On Narie": "ellis-nels-on-narie",
    "ELLIS Rob": "ellis-rob",
    "ELLIS Rowan": "ellis-rowan",
    "ELLIS Samantha": "ellis-samantha",
    "ELLIS Scott": "ellis-scott",
    "ELLIS Sharon": "ellis-sharon",
    "ELLIS Siwan": "ellis-siwan",
    "ELLIS Sue": "ellis-sue",
    "ELLIS Terry": "ellis-terry",
    "ELLIS Tim": "ellis-tim",
    "ELLIS Todd": "ellis-todd",
    "ELLIS Trey": "ellis-trey",
    "ELLIS Vivian": "ellis-vivian",
    "ELLISON Arthur": "ellison-arthur",
    "ELLISON Elizabeth Burnham": "ellison-elizabeth-burnham",
    "ELLISON Karen": "ellison-karen",
    "ELLISON Leslie": "ellison-leslie",
    "ELLISON Liz": "ellison-liz",
    "ELLISON Michael": "ellison-michael",
    "ELLISON Ralph": "ellison-ralph",
    "ELLISON Richard Anthony": "ellison-richard-anthony",
    "ELLISON Robert (1)": "ellison-robert-1",
    "ELLISON Robert (2)": "ellison-robert-2",
    "ELLISTON Mike": "elliston-mike",
    "ELLMANN Lucy": "ellmann-lucy",
    "ELLOR Elizabeth": "ellor-elizabeth",
    "ELLSMORE Siho": "ellsmore-siho",
    "ELLSTEIN Abraham": "ellstein-abraham",
    "ELLSWORTH Patrick": "ellsworth-patrick",
    "ELLWOOD H K": "ellwood-h-k",
    "ELM Steve": "elm-steve",
    "ELMAN Irving": "elman-irving",
    "ELMAN Richard": "elman-richard",
    "ELMEGREEN Scott": "elmegreen-scott",
    "ELMHIRST Louise": "elmhirst-louise",
    "ELMO Christine": "elmo-christine",
    "ELMSLIE Kenward": "elmslie-kenward",
    "ELOVICH Richard": "elovich-richard",
    "ELPHICKE Conan": "elphicke-conan",
    "ELRIDGE Becky": "elridge-becky",
    "ELS JOGLARS ": "els-joglars",
    "ELSAFFAR Amir": "elsaffar-amir",
    "ELSASSER Greg": "elsasser-greg",
    "ELSE Chris": "else-chris",
    "ELSER Don": "elser-don",
    "ELSER Frank B": "elser-frank-b",
    "ELSLEY Bryan": "elsley-bryan",
    "ELSMORE Bronwyn": "elsmore-bronwyn",
    "ELSO Leo": "elso-leo",
    "ELSON Jane": "elson-jane",
    "ELSON Lynne": "elson-lynne",
    "ELSTEIN Hendrick": "elstein-hendrick",
    "ELSTON Glenn": "elston-glenn",
    "ELSTON Jon": "elston-jon",
    "ELTER Sheldon": "elter-sheldon",
    "ELTHAM Ben": "eltham-ben",
    "ELTON Ben": "elton-ben",
    "ELTON Benjamin Charles": "elton-benjamin-charles",
    "ELTON Lotti": "elton-lotti",
    "ELTON Max": "elton-max",
    "ELUFOWOJU Femi": "elufowoju-femi",
    "ELVERMAN Bill": "elverman-bill",
    "ELVGREN JR Gillette": "elvgren-jr-gillette",
    "ELWARD James": "elward-james",
    "ELWELL Chris": "elwell-chris",
    "ELWELL Jeffery Scott": "elwell-jeffery-scott",
    "ELWELL Matt": "elwell-matt",
    "ELWES Magdalen": "elwes-magdalen",
    "ELY Neil": "ely-neil",
    "ELY Richard": "ely-richard",
    "ELYANOW Michael": "elyanow-michael",
    "ELYOT Kevin": "elyot-kevin"
  }
};