export default {
  "metadata": {
    "results": 592,
    "timeStamp": "2025-12-05T21:24:16.650Z",
    "url": "https://www.doollee.com/PlaywrightsF/F_playwrights_g-l.php"
  },
  "authors": {
    "FIAT LUX ": "fiat-lux",
    "FIBER Jon": "fiber-jon",
    "FICH Arne": "fich-arne",
    "FICKETT Hal": "fickett-hal",
    "FICKMAN Andy": "fickman-andy",
    "FIDDAMAN Mark": "fiddaman-mark",
    "FIDLER Donald Carl": "fidler-donald-carl",
    "FIDLER Joyce": "fidler-joyce",
    "FIDLER Kathleen": "fidler-kathleen",
    "FIDLER Michael": "fidler-michael",
    "FIDRAM Christopher": "fidram-christopher",
    "FIEGEL Ethan": "fiegel-ethan",
    "FIEHN Stephen": "fiehn-stephen",
    "FIELBERT Ed": "fielbert-ed",
    "FIELD Andy": "field-andy",
    "FIELD Barbara": "field-barbara",
    "FIELD Betsy": "field-betsy",
    "FIELD Brad": "field-brad",
    "FIELD Crystal": "field-crystal",
    "FIELD David C": "field-david-c",
    "FIELD Doug": "field-doug",
    "FIELD Ivana Jilovcova": "field-ivana-jilovcova",
    "FIELD John": "field-john",
    "FIELD Jonathan": "field-jonathan",
    "FIELD Nathan": "field-nathan",
    "FIELD Nick": "field-nick",
    "FIELD Rachel": "field-rachel",
    "FIELD Thalia": "field-thalia",
    "FIELDEN Charlotte": "fielden-charlotte",
    "FIELDER David": "fielder-david",
    "FIELDER Jez": "fielder-jez",
    "FIELDING David": "fielding-david",
    "FIELDING Ethel": "fielding-ethel",
    "FIELDING Helen": "fielding-helen",
    "FIELDING Henry": "fielding-henry",
    "FIELDING Jonnie": "fielding-jonnie",
    "FIELDING Noel": "fielding-noel",
    "FIELDING Ollie": "fielding-ollie",
    "FIELDS Aaron William": "fields-aaron-william",
    "FIELDS Barbara": "fields-barbara",
    "FIELDS Ben": "fields-ben",
    "FIELDS Chip": "fields-chip",
    "FIELDS Dan": "fields-dan",
    "FIELDS Dorothy": "fields-dorothy",
    "FIELDS Herbert": "fields-herbert",
    "FIELDS Joel": "fields-joel",
    "FIELDS Joseph": "fields-joseph",
    "FIELDS Kirby": "fields-kirby",
    "FIELDS Lew M": "fields-lew-m",
    "FIELDS Maurice": "fields-maurice",
    "FIELDS Michael": "fields-michael",
    "FIELDS Mike": "fields-mike",
    "FIELDS Peter Anthony": "fields-peter-anthony",
    "FIELDS Robert": "fields-robert",
    "FIELDSON Peter": "fieldson-peter",
    "FIELDSTEEL Robert": "fieldsteel-robert",
    "FIENSTEIN Joe": "fienstein-joe",
    "FIERRO David": "fierro-david",
    "FIERSTEIN Harvey": "fierstein-harvey",
    "FIFE Cameron": "fife-cameron",
    "FIFE Graeme": "fife-graeme",
    "FIFE Stephen": "fife-stephen",
    "FIFIELD Tim": "fifield-tim",
    "FIGERT S Albert": "figert-s-albert",
    "FIGG Olly": "figg-olly",
    "FIGGIS Mike": "figgis-mike",
    "FIGLMILLER John": "figlmiller-john",
    "FIGS IN WIGS ": "figs-in-wigs",
    "FIGUEIREDO Franko": "figueiredo-franko",
    "FIGUEIREDO Guilherne": "figueiredo-guilherne",
    "FIGUEROA Stephanie": "figueroa-stephanie",
    "FIGURENTHEATER TUBINGEN ": "figurentheater-tubingen",
    "FILANGIERI Keith": "filangieri-keith",
    "FILAR Ella": "filar-ella",
    "FILES Gary": "files-gary",
    "FILEWOOD Alan": "filewood-alan",
    "FILHO Paulo Biscaia": "filho-paulo-biscaia",
    "FILIPOWICZ H": "filipowicz-h",
    "FILIPPUSDOTTIR Nina Dogg": "filippusdottir-nina-dogg",
    "FILL Simon": "fill-simon",
    "FILLEBROWN Chris": "fillebrown-chris",
    "FILLER Deb": "filler-deb",
    "FILLINGER Johan": "fillinger-johan",
    "FILLIS Brian": "fillis-brian",
    "FILLOUX Catherine": "filloux-catherine",
    "FILLOUX-BENNETT Henry": "filloux-bennett-henry",
    "FILMER Kath": "filmer-kath",
    "FILTER THEATRE ": "filter-theatre",
    "FINCH John": "finch-john",
    "FINCH Peter": "finch-peter",
    "FINCH Robert": "finch-robert",
    "FINCHAM Peter": "fincham-peter",
    "FINDLAY Bill": "findlay-bill",
    "FINDLAY Carly": "findlay-carly",
    "FINDLAY Iver": "findlay-iver",
    "FINDLAY Jim": "findlay-jim",
    "FINDLAY Sophie": "findlay-sophie",
    "FINDLEY Timothy": "findley-timothy",
    "FINDSEN Troels Hagen": "findsen-troels-hagen",
    "FINE Anne": "fine-anne",
    "FINE Kaethe": "fine-kaethe",
    "FINE Keni": "fine-keni",
    "FINE Lois": "fine-lois",
    "FINE Stan": "fine-stan",
    "FINE Zack": "fine-zack",
    "FINE CHISEL ": "fine-chisel",
    "FINEBERG Larry": "fineberg-larry",
    "FINEGOLD Stephen": "finegold-stephen",
    "FINEMAN Jake": "fineman-jake",
    "FINES Ian": "fines-ian",
    "FINFER June": "finfer-june",
    "FINGERMAN Dan": "fingerman-dan",
    "FINGLETON Anthony": "fingleton-anthony",
    "FINITSIS Dimitris": "finitsis-dimitris",
    "FINK Charlie": "fink-charlie",
    "FINK Enrico": "fink-enrico",
    "FINK Joseph": "fink-joseph",
    "FINK Len": "fink-len",
    "FINKE Michael Charles": "finke-michael-charles",
    "FINKEL Gertrude B": "finkel-gertrude-b",
    "FINKEL Ian": "finkel-ian",
    "FINKELSTEIN Brian": "finkelstein-brian",
    "FINKELSTEIN David": "finkelstein-david",
    "FINKELSTEIN Deborah": "finkelstein-deborah",
    "FINKELSTEIN Jerry": "finkelstein-jerry",
    "FINKELSTEIN Kevin": "finkelstein-kevin",
    "FINKELSTEIN Naomi": "finkelstein-naomi",
    "FINKLAIRE Lottie": "finklaire-lottie",
    "FINKLE David": "finkle-david",
    "FINKLE Kenny": "finkle-kenny",
    "FINKLEHOFFE Fred F": "finklehoffe-fred-f",
    "FINKLESTEIN Deborah": "finklestein-deborah",
    "FINKLESTEIN Harvey": "finklestein-harvey",
    "FINLAY Byjonas": "finlay-byjonas",
    "FINLAY Daniel": "finlay-daniel",
    "FINLAY Diane": "finlay-diane",
    "FINLAY Ian Hamilton": "finlay-ian-hamilton",
    "FINLAY Jonas": "finlay-jonas",
    "FINLAY Joseph": "finlay-joseph",
    "FINLAY Peter": "finlay-peter",
    "FINLAY Robertson": "finlay-robertson",
    "FINLAY Steve": "finlay-steve",
    "FINLAY Suzanne": "finlay-suzanne",
    "FINLAY Wes": "finlay-wes",
    "FINLAYSON Alex": "finlayson-alex",
    "FINLEY Becca": "finley-becca",
    "FINLEY Cory": "finley-cory",
    "FINLEY David": "finley-david",
    "FINLEY Harold": "finley-harold",
    "FINLEY Ian": "finley-ian",
    "FINLEY Karen": "finley-karen",
    "FINLEY Mark": "finley-mark",
    "FINMAN John": "finman-john",
    "FINN Ben": "finn-ben",
    "FINN Billy": "finn-billy",
    "FINN Crystal": "finn-crystal",
    "FINN Jeanne C": "finn-jeanne-c",
    "FINN Jeffrey": "finn-jeffrey",
    "FINN Mike": "finn-mike",
    "FINN Stephen": "finn-stephen",
    "FINN Tim": "finn-tim",
    "FINN William": "finn-william",
    "FINNAN Paschal": "finnan-paschal",
    "FINNEGAN Amy": "finnegan-amy",
    "FINNEGAN Billy": "finnegan-billy",
    "FINNEGAN Jack": "finnegan-jack",
    "FINNEGAN Joan": "finnegan-joan",
    "FINNEGAN Rosie": "finnegan-rosie",
    "FINNEGAN Seamus": "finnegan-seamus",
    "FINNEMORE John": "finnemore-john",
    "FINNERAN William B": "finneran-william-b",
    "FINNEY Charles": "finney-charles",
    "FINNEY Paul": "finney-paul",
    "FINNIGAN Bryan": "finnigan-bryan",
    "FINNIGAN David": "finnigan-david",
    "FINOCCHIARO Dominic": "finocchiaro-dominic",
    "FINSTERER Anni": "finsterer-anni",
    "FINSTROM Tony": "finstrom-tony",
    "FINTZI Ariel": "fintzi-ariel",
    "FINUCANE Moira": "finucane-moira",
    "FINZI Susannah": "finzi-susannah",
    "FIORE Jessamyn": "fiore-jessamyn",
    "FIORENTINO Tony": "fiorentino-tony",
    "FIORI Flippo": "fiori-flippo",
    "FIORI Lucy": "fiori-lucy",
    "FIORILLO John": "fiorillo-john",
    "FIRCHOW P E": "firchow-p-e",
    "FIRDA Andrew": "firda-andrew",
    "FIREBIRD THEATRE ": "firebird-theatre",
    "FIREHOUSE CREATIVE PRODUCTIONS ": "firehouse-creative-productions",
    "FIREHOUSE THEATRE ": "firehouse-theatre",
    "FIRKE Benjamin": "firke-benjamin",
    "FIRKUSNY-CALLEGARI Veronique": "firkusny-callegari-veronique",
    "FIRLA Brandon": "firla-brandon",
    "FIRLA Kurt": "firla-kurt",
    "FIRMAN Jon": "hoenig-ron-and-jon-firman",
    "FIRPO-CAPPIELLO Robert": "firpo-cappiello-robert",
    "FIRST Phoebe": "first-phoebe",
    "FIRST FLOOR ": "first-floor",
    "FIRSTBORN THEATRE ": "firstborn-theatre",
    "FIRTH Ivan": "firth-ivan",
    "FIRTH John": "firth-john",
    "FIRTH Mike": "firth-mike",
    "FIRTH Olivia": "firth-olivia",
    "FIRTH Simon": "firth-simon",
    "FIRTH Tim": "firth-tim",
    "FISCH Adam J": "fisch-adam-j",
    "FISCH Victor": "fisch-victor",
    "FISCHBEIN Dahlia": "fischbein-dahlia",
    "FISCHER Carl A": "fischer-carl-a",
    "FISCHER Corey": "fischer-corey",
    "FISCHER Eileen": "fischer-eileen",
    "FISCHER Ernest": "fischer-ernest",
    "FISCHER Esta": "fischer-esta",
    "FISCHER Ilene A": "fischer-ilene-a",
    "FISCHER Justin S": "fischer-justin-s",
    "FISCHER Kai": "fischer-kai",
    "FISCHER Kathleen": "fischer-kathleen",
    "FISCHER Kim": "fischer-kim",
    "FISCHER Lori": "fischer-lori",
    "FISCHER Margaret": "fischer-margaret",
    "FISCHER Saskia": "fischer-saskia",
    "FISCHER Stephen": "fischer-stephen",
    "FISCHER / SPACKMAN ": "fischer-spackman",
    "FISCHEROVA Daniela": "fischerova-daniela",
    "FISCHER-SMITH Jeffrey": "fischer-smith-jeffrey",
    "FISCHMAN Shelia": "fischman-shelia",
    "FISCHOFF George": "fischoff-george",
    "FISET Joan": "fiset-joan",
    "FISH Daniel": "fish-daniel",
    "FISH Mike": "fish-mike",
    "FISH & GAME ": "fish-game",
    "FISHAMBLE: THE NEW PLAY COMPANY ": "fishamble",
    "FISHBACK Dan": "fishback-dan",
    "FISHBANE Joel": "fishbane-joel",
    "FISHBEYN Anna": "fishbeyn-anna",
    "FISHBURNE Laurence": "fishburne-laurence",
    "FISHBURNE Rodes": "fishburne-rodes",
    "FISHELSON David": "fishelson-david",
    "FISHER Adrian": "fisher-adrian",
    "FISHER Aileen": "fisher-aileen",
    "FISHER Amanda Stuart": "fisher-amanda-stuart",
    "FISHER Bennett": "fisher-bennett",
    "FISHER Bob": "fisher-bob",
    "FISHER Brian": "fisher-brian",
    "FISHER Carrie": "fisher-carrie",
    "FISHER Charlie Edwin": "fisher-charlie-edwin",
    "FISHER Chris": "fisher-chris",
    "FISHER Corinne": "fisher-corinne",
    "FISHER D": "fisher-d",
    "FISHER Dorothy Canfield": "fisher-dorothy-canfield",
    "FISHER Ellen": "fisher-ellen",
    "FISHER Emma": "fisher-emma",
    "FISHER Fred J": "fisher-fred-j",
    "FISHER Gregg": "fisher-gregg",
    "FISHER Harriet": "fisher-harriet",
    "FISHER Jessica Marie": "fisher-jessica-marie",
    "FISHER Joel": "fisher-joel",
    "FISHER John": "fisher-john",
    "FISHER John (1)": "fisher-john-1",
    "FISHER Joseph": "fisher-joseph",
    "FISHER Kevin": "fisher-kevin",
    "FISHER Layna": "fisher-layna",
    "FISHER Mark": "fisher-mark",
    "FISHER Michael Shaw": "fisher-michael-shaw",
    "FISHER Nick": "fisher-nick",
    "FISHER P H": "fisher-p-h",
    "FISHER Robert": "fisher-robert",
    "FISHER Rodney": "fisher-rodney",
    "FISHER Shawn": "fisher-shawn",
    "FISHER Steve": "fisher-steve",
    "FISHER Steven": "fisher-steven",
    "FISHER T J": "fisher-t-j",
    "FISHER T Langdon": "fisher-t-langdon",
    "FISHER Thomas": "fisher-thomas",
    "FISHER Van Dirk": "fisher-van-dirk",
    "FISHER William": "fisher-william",
    "FISHER-JOHNSON Tomasin": "fisher-johnson-tomasin",
    "FISHMAN Andrew": "fishman-andrew",
    "FISHMAN Grace": "fishman-grace",
    "FISHMAN Howard": "fishman-howard",
    "FISHMAN Ian": "fishman-ian",
    "FISHMAN Joan": "fishman-joan",
    "FISHMAN Nancy": "fishman-nancy",
    "FISK Bruce": "fisk-bruce",
    "FISK Dorothy M": "fisk-dorothy-m",
    "FISKE Jeffrey": "fiske-jeffrey",
    "FISKE-HARRISON Alexander": "fiske-harrison-alexander",
    "FISKIN Gene": "fiskin-gene",
    "FISTER-OXMAN Ellen": "fister-oxman-ellen",
    "FITCH Alan": "fitch-alan",
    "FITCH Clyde": "fitch-clyde",
    "FITCH Georgia": "fitch-georgia",
    "FITCHETT Lucie": "fitchett-lucie",
    "FITCHETT Richard": "fitchett-richard",
    "FITE Jason": "fite-jason",
    "FITHIAN Diana": "fithian-diana",
    "FITHIAN Zachary": "fithian-zachary",
    "FITT Brad": "fitt-brad",
    "FITTOCK Chris": "fittock-chris",
    "FITTS Dudley": "fitts-dudley",
    "FITTS Jonathan": "fitts-jonathan",
    "FITZ Chris": "fitz-chris",
    "FITZGERAL Anna": "fitzgeral-anna",
    "FITZGERALD Ara": "fitzgerald-ara",
    "FITZGERALD Beth": "fitzgerald-beth",
    "FITZGERALD Brendan": "fitzgerald-brendan",
    "FITZGERALD Catherine": "fitzgerald-catherine",
    "FITZGERALD Constantine": "fitzgerald-constantine",
    "FITZGERALD Frank T": "fitzgerald-frank-t",
    "FITZGERALD Gary": "fitzgerald-gary",
    "FITZGERALD Gerald": "fitzgerald-gerald",
    "FITZGERALD Geraldine": "fitzgerald-geraldine",
    "FITZGERALD Grace": "fitzgerald-grace",
    "FITZGERALD Hugh": "fitzgerald-hugh",
    "FITZGERALD J": "fitzgerald-j",
    "FITZGERALD Jack": "fitzgerald-jack",
    "FITZGERALD James": "fitzgerald-james",
    "FITZGERALD Jim": "fitzgerald-jim",
    "FITZGERALD Jo": "fitzgerald-jo",
    "FITZGERALD Karen": "fitzgerald-karen",
    "FITZGERALD Kitty": "fitzgerald-kitty",
    "FITZGERALD Laura": "fitzgerald-laura",
    "FITZGERALD Lynne": "fitzgerald-lynne",
    "FITZGERALD M J": "fitzgerald-m-j",
    "FITZGERALD Maureen": "fitzgerald-maureen",
    "FITZGERALD Neil C": "fitzgerald-neil-c",
    "FITZGERALD Patrick": "fitzgerald-patrick",
    "FITZGERALD Patrik": "fitzgerald-patrik",
    "FITZGERALD Robert": "fitzgerald-robert",
    "FITZGERALD Ron": "fitzgerald-ron",
    "FITZGERALD Rosemary": "fitzgerald-rosemary",
    "FITZGERALD Sarah Moore": "fitzgerald-sarah-moore",
    "FITZ-GERALD Allen": "fitz-gerald-allen",
    "FITZGIBBEN Constantine": "fitzgibben-constantine",
    "FITZGIBBON Brian": "fitzgibbon-brian",
    "FITZGIBBON Emelie": "fitzgibbon-emelie",
    "FITZGIBBON Ger": "fitzgibbon-ger",
    "FITZGIBBON Sarah": "fitzgibbon-sarah",
    "FITZGIBBONS Mark": "fitzgibbons-mark",
    "FITZHUGH Ellen": "fitzhugh-ellen",
    "FITZJOHN Donald": "fitzjohn-donald",
    "FITZJOHN Eric": "fitzjohn-eric",
    "FITZMACKEN Tom": "fitzmacken-tom",
    "FITZMAURICE Annie": "fitzmaurice-annie",
    "FITZMAURICE George": "fitzmaurice-george",
    "FITZMORRIS Jim": "fitzmorris-jim",
    "FITZPATRICK Alexa": "fitzpatrick-alexa",
    "FITZPATRICK Ciaran": "fitzpatrick-ciaran",
    "FITZPATRICK Frank": "fitzpatrick-frank",
    "FITZPATRICK John": "fitzpatrick-john",
    "FITZPATRICK Julie": "fitzpatrick-julie",
    "FITZPATRICK Katy": "fitzpatrick-katy",
    "FITZPATRICK Kurt": "fitzpatrick-kurt",
    "FITZPATRICK Peter": "fitzpatrick-peter",
    "FITZPATRICK Rachel": "fitzpatrick-rachel",
    "FITZPATRICK Steve": "fitzpatrick-steve",
    "FITZPATRICK Tim": "fitzpatrick-tim",
    "FITZPATRICK Tom": "fitzpatrick-tom",
    "FITZPATRICK Tony": "fitzpatrick-tony",
    "FITZROY Kate": "fitzroy-kate",
    "FITZSIMMONS Kelly Jean": "fitzsimmons-kelly-jean",
    "FITZSIMMONS Michelle": "fitzsimmons-michelle",
    "FITZSIMONS Raymund": "fitzsimons-raymund",
    "FIUMANO-FARLEY Donna": "fiumano-farley-donna",
    "FIVE FLIGHTS THEATER COMPANY ": "five-flights-theater-company",
    "FIVE GALLANTS ": "five-gallants",
    "FIVE LESBIAN BROTHERS ": "five-lesbian-brothers",
    "FIX Michelle": "fix-michelle",
    "FIXEL Michael": "fixel-michael",
    "FIZZARD Anne": "fizzard-anne",
    "FJELDE Rolf": "fjelde-rolf",
    "FLACK Eamon": "flack-eamon",
    "FLACK Jonathan": "flack-jonathan",
    "FLACK Stuart": "flack-stuart",
    "FLACKS Diane": "flacks-diane",
    "FLACKS Matthew": "flacks-matthew",
    "FLADI Ulrich": "fladi-ulrich",
    "FLAGER Gwen": "flager-gwen",
    "FLAGG Ann": "flagg-ann",
    "FLAGG Kim": "flagg-kim",
    "FLAHAVEN Sean Patrick": "flahaven-sean-patrick",
    "FLAHERTY Katherine Bryant": "flaherty-katherine-bryant",
    "FLAHERTY Lanny": "flaherty-lanny",
    "FLAHERTY Nancy": "flaherty-nancy",
    "FLAHERTY Peter D": "flaherty-peter-d",
    "FLAHERTY Robert J": "flaherty-robert-j",
    "FLAHERTY Stephen": "flaherty-stephen",
    "FLAHERTY Tim": "flaherty-tim",
    "FLAHIVE Liz": "flahive-liz",
    "FLAKS Diana": "flaks-diana",
    "FLAME ": "flame",
    "FLAMING THEATRE ": "flaming-theatre",
    "FLANAGAN Alan": "flanagan-alan",
    "FLANAGAN Anne": "flanagan-anne",
    "FLANAGAN Christine": "flanagan-christine",
    "FLANAGAN Dennis": "flanagan-dennis",
    "FLANAGAN Elizabeth": "flanagan-elizabeth",
    "FLANAGAN Gerry": "flanagan-gerry",
    "FLANAGAN Hallie": "flanagan-hallie",
    "FLANAGAN John": "flanagan-john",
    "FLANAGAN June": "flanagan-june",
    "FLANAGAN Kristen M": "flanagan-kristen-m",
    "FLANAGAN Maile": "flanagan-maile",
    "FLANAGAN Mary": "flanagan-mary",
    "FLANAGAN Nicholas": "flanagan-nicholas",
    "FLANAGAN Peter J": "flanagan-peter-j",
    "FLANAGAN COLLECTIVE ": "flanagan-collective",
    "FLANDERS Ash": "flanders-ash",
    "FLANDERS Michael": "flanders-michael",
    "FLANIGAN Peter": "flanigan-peter",
    "FLANIGAN Tom": "flanigan-tom",
    "FLANNERY Gemma": "flannery-gemma",
    "FLANNERY Pauline": "flannery-pauline",
    "FLANNERY Peter": "flannery-peter",
    "FLANNERY Sheri": "flannery-sheri",
    "FLANNERY Timothy": "flannery-timothy",
    "FLANTZ Richard": "flantz-richard",
    "FLASKOVA Zuzana": "flaskova-zuzana",
    "FLATHER Patti": "flather-patti",
    "FLATRATE ": "flatrate",
    "FLATT Kate": "flatt-kate",
    "FLATT Robyn": "flatt-robyn",
    "FLATTO Michele": "flatto-michele",
    "FLAUM Becky": "flaum-becky",
    "FLAUTT Paula B": "flautt-paula-b",
    "FLAUTT Paula Y": "flautt-paula-y",
    "FLAVIN Dick": "flavin-dick",
    "FLAWS Christy": "flaws-christy",
    "FLAXMAN Gary": "flaxman-gary",
    "FLAXMAN John": "flaxman-john",
    "FLAYTON Leigh": "flayton-leigh",
    "FLECK Erin": "fleck-erin",
    "FLECK John": "fleck-john",
    "FLEET Greg": "fleet-greg",
    "FLEET Henry": "fleet-henry",
    "FLEISCHER Julie": "fleischer-julie",
    "FLEISCHHACKER D J": "fleischhacker-d-j",
    "FLEISCHMAN Paul": "fleischman-paul",
    "FLEISCHMAN Sid": "fleischman-sid",
    "FLEISCHMANN Emanuel": "fleischmann-emanuel",
    "FLEISCHMANN Stephanie": "fleischmann-stephanie",
    "FLEISHER David": "fleisher-david",
    "FLEISHMAN Alan Ross": "fleishman-alan-ross",
    "FLEISSER Marieluise": "fleisser-marieluise",
    "FLEITAS Christopher": "fleitas-christopher",
    "FLEITMAN Jessica": "fleitman-jessica",
    "FLEMING Amanda": "fleming-amanda",
    "FLEMING Anne": "fleming-anne",
    "FLEMING Anne (1)": "fleming-anne-1",
    "FLEMING Bill": "fleming-bill",
    "FLEMING Brian": "fleming-brian",
    "FLEMING Carolyn": "fleming-carolyn",
    "FLEMING Don": "fleming-don",
    "FLEMING Jack W": "fleming-jack-w",
    "FLEMING Jill": "fleming-jill",
    "FLEMING Jo": "fleming-jo",
    "FLEMING John": "fleming-john",
    "FLEMING Justin": "fleming-justin",
    "FLEMING Leon": "fleming-leon",
    "FLEMING Maureen": "fleming-maureen",
    "FLEMING Maurice": "fleming-maurice",
    "FLEMING Neil": "fleming-neil",
    "FLEMING Neil (2)": "fleming-neil-2",
    "FLEMING Peter": "fleming-peter",
    "FLEMING Sandra": "fleming-sandra",
    "FLEMING Tom": "fleming-tom",
    "FLEMINGS Renee": "flemings-renee",
    "FLEMMING Brian": "flemming-brian",
    "FLEMMING Denise B": "flemming-denise-b",
    "FLEMMING Maureen": "flemming-maureen",
    "FLESZAR Dewey": "fleszar-dewey",
    "FLETCHER Alan": "fletcher-alan",
    "FLETCHER Anthony": "fletcher-anthony",
    "FLETCHER B B": "fletcher-b-b",
    "FLETCHER Chris": "fletcher-chris",
    "FLETCHER Destiny Candyce P": "fletcher-destiny-candyce-p",
    "FLETCHER Eric": "fletcher-eric",
    "FLETCHER Gregory": "fletcher-gregory",
    "FLETCHER Hamish": "fletcher-hamish",
    "FLETCHER Hugh L": "fletcher-hugh-l",
    "FLETCHER Janine": "fletcher-janine",
    "FLETCHER Jeremy James": "fletcher-jeremy-james",
    "FLETCHER Joe": "fletcher-joe",
    "FLETCHER John": "fletcher-john",
    "FLETCHER Lucille": "fletcher-lucille",
    "FLETCHER Mark": "fletcher-mark",
    "FLETCHER Matt": "fletcher-matt",
    "FLETCHER Paddy": "fletcher-paddy",
    "FLETCHER Rebecca Joy": "fletcher-rebecca-joy",
    "FLETCHER Russell": "fletcher-russell",
    "FLETCHER Sophie": "fletcher-sophie",
    "FLETCHER Steven": "fletcher-steven",
    "FLEURANTIN Stephanie": "fleurantin-stephanie",
    "FLEURY Claire": "fleury-claire",
    "FLEURY Patrick": "fleury-patrick",
    "FLEWITT Lee": "flewitt-lee",
    "FLEXER Michael J": "flexer-michael-j",
    "FLEXIBLE DEADLOCK ": "flexible-deadlock",
    "FLICK Matt": "flick-matt",
    "FLICKER Bob": "flicker-bob",
    "FLICKER Theodore J": "flicker-theodore-j",
    "FLIND Sarah": "flind-sarah",
    "FLINN Kevin": "flinn-kevin",
    "FLINN Lewis": "flinn-lewis",
    "FLINT Austin": "flint-austin",
    "FLINT C S": "flint-c-s",
    "FLINT Daniel": "flint-daniel",
    "FLINT Diana": "flint-diana",
    "FLINTER Daniel": "flinter-daniel",
    "FLINTHAM Frazer": "flintham-frazer",
    "FLINTOFF Beth": "flintoff-beth",
    "FLINTOFF Ian": "flintoff-ian",
    "FLISAR Evald": "flisar-evald",
    "FLITTON Dave": "flitton-dave",
    "FLITTON Martin": "flitton-martin",
    "FLITTON Sheila": "flitton-sheila",
    "FLOATING PARTNERS ": "floating-partners",
    "FLODEN Lea": "floden-lea",
    "FLODEN Mary Lea": "floden-mary-lea",
    "FLOODS OF INK ": "floods-of-ink",
    "FLOR Robert Francis": "flor-robert-francis",
    "FLORA David": "flora-david",
    "FLOREN Kari": "floren-kari",
    "FLORENCE Rob": "florence-rob",
    "FLORENCIANI ": "florenciani",
    "FLORENTINO Alberto": "florentino-alberto",
    "FLORES Angel": "flores-angel",
    "FLORES David": "flores-david",
    "FLORES Derek": "flores-derek",
    "FLORES Dyan": "flores-dyan",
    "FLORES Elixeo": "flores-elixeo",
    "FLORES Guadalupe": "flores-guadalupe",
    "FLORES Lane": "flores-lane",
    "FLORES Ronald": "flores-ronald",
    "FLOREZ Dave": "florez-dave",
    "FLORI Alex": "flori-alex",
    "FLORIDO Blanca": "florido-blanca",
    "FLORIO Julie": "florio-julie",
    "FLORSCHUTZ Melanie": "florschutz-melanie",
    "FLORY Erin": "flory-erin",
    "FLORY Louise": "flory-louise",
    "FLORY Monica": "flory-monica",
    "FLOURAKIS Andreas": "flourakis-andreas",
    "FLOWER Alan": "flower-alan",
    "FLOWER Bettina": "flower-bettina",
    "FLOWER Cedric": "flower-cedric",
    "FLOWER Janice": "flower-janice",
    "FLOWER Pat": "flower-pat",
    "FLOWERS Herbert": "flowers-herbert",
    "FLOY Gregory": "floy-gregory",
    "FLOY Monica": "floy-monica",
    "FLOYD Jacquelyn": "floyd-jacquelyn",
    "FLOYD Lawrence": "floyd-lawrence",
    "FLOYD Peter M": "floyd-peter-m",
    "FLOYD Ronald": "floyd-ronald",
    "FLOYD-MILLER Cherryl": "floyd-miller-cherryl",
    "FLUDD III Quitmann": "fludd-quitmann",
    "FLUHARTY Jeff": "fluharty-jeff",
    "FLUHR James": "fluhr-james",
    "FLUHR Nancy Steffen": "fluhr-nancy-steffen",
    "FLUTUR Vasile": "flutur-vasile",
    "FLYING CARPET ": "flying-carpet",
    "FLYING EYE ": "flying-eye",
    "FLYING INVALID COMPANY ": "flying-invalid-company",
    "FLYING KARAMOZOV BROTHERS, THE ": "flying-karamozov-brothers",
    "FLYING MACHINE, THE ": "flying-machine-the",
    "FLYNN Adrian": "flynn-adrian",
    "FLYNN Bryan": "flynn-bryan",
    "FLYNN Clancy": "flynn-clancy",
    "FLYNN Dennis": "flynn-dennis",
    "FLYNN Dominic": "flynn-dominic",
    "FLYNN Don": "flynn-don",
    "FLYNN Frank": "flynn-frank",
    "FLYNN Gerard Mannix": "flynn-gerard-mannix",
    "FLYNN Graeme": "flynn-graeme",
    "FLYNN Jimmy": "flynn-jimmy",
    "FLYNN John": "flynn-john",
    "FLYNN Keely": "flynn-keely",
    "FLYNN Kelly": "flynn-kelly",
    "FLYNN Lance": "flynn-lance",
    "FLYNN Louis": "flynn-louis",
    "FLYNN Megan": "flynn-megan",
    "FLYNN Neil": "flynn-neil",
    "FLYNN Neil (2)": "flynn-neil-2",
    "FLYNN Nick": "flynn-nick",
    "FLYNN Nigel": "flynn-nigel",
    "FLYNN Patrick": "flynn-patrick",
    "FLYNN Paul": "flynn-paul",
    "FLYNN Robert L": "flynn-robertl",
    "FLYNN Thomas Fitzgerald": "flynn-thomas-fitzgerald",
    "FLYNN Tony": "flynn-tony"
  }
};