export default {
  "metadata": {
    "results": 930,
    "timeStamp": "2025-12-05T21:24:25.410Z",
    "url": "https://www.doollee.com/PlaywrightsF/F_playwrights_m-r.php"
  },
  "authors": {
    "FO Dario": "fo-dario",
    "FOAD Nathan": "foad-nathan",
    "FOARD Sylvia-elaine": "foard-sylvia-elaine",
    "FOBISTER Waawaate": "fobister-waawaate",
    "FODOR Kate": "fodor-kate",
    "FODOR Ladislaus": "fodor-ladislaus",
    "FOERSTER Wendy": "foerster-wendy",
    "FOFI David": "fofi-david",
    "FOG Nina": "fog-nina",
    "FOGARTY Benedict": "fogarty-benedict",
    "FOGARTY Matthew": "fogarty-matthew",
    "FOGARTY Molly": "fogarty-molly",
    "FOGARTY Nick": "fogarty-nick",
    "FOGARTY Ryan": "fogarty-ryan",
    "FOGARTY Sharon": "fogarty-sharon",
    "FOGARTY Sharon (1)": "fogarty-sharon-1",
    "FOGARTY Thom": "fogarty-thom",
    "FOGARTY-GRAVESON Gabriel": "fogarty-graveson-gabriel",
    "FOGEL Bryan": "fogel-bryan",
    "FOGEL Susanna": "fogel-susanna",
    "FOGELMAN Steven": "fogelman-steven",
    "FOGERSON Barbara": "fogerson-barbara",
    "FOGGO Cheryl": "foggo-cheryl",
    "FOGGO John": "foggo-john",
    "FOGLER Dan": "fogler-dan",
    "FOGLINO Paul": "foglino-paul",
    "FOLANI Femi": "folani-femi",
    "FOLAYAN Omodele": "folayan-omodele",
    "FOLDS Ben": "folds-ben",
    "FOLEY Chris": "foley-chris",
    "FOLEY Connor M": "foley-connor-m",
    "FOLEY Daniel": "foley-daniel",
    "FOLEY David": "foley-david",
    "FOLEY Erin": "foley-erin",
    "FOLEY J R": "foley-j-r",
    "FOLEY John": "foley-john",
    "FOLEY Laura-Jane": "foley-laura-jane",
    "FOLEY Melinda Corazon": "foley-melinda-corazon",
    "FOLEY Mike": "foley-mike",
    "FOLEY Patrick": "foley-patrick",
    "FOLEY Pete": "foley-pete",
    "FOLEY Peter": "foley-peter",
    "FOLEY Rosemary": "foley-rosemary",
    "FOLEY Sean": "foley-sean",
    "FOLEY Tim": "foley-tim",
    "FOLEY Tomaseen": "foley-tomaseen",
    "FOLEY Valerie": "foley-valerie",
    "FOLIE Mike": "folie-mike",
    "FOLINO Thomas F": "folino-thomas-f",
    "FOLK Roland": "folk-roland",
    "FOLLES ALLIEES ": "folles-alliees",
    "FOLLOWS Edwina": "follows-edwina",
    "FOLS Craig": "fols-craig",
    "FOLSCHINSKY Jeff": "folschinsky-jeff",
    "FOLSTEIN Ben": "folstein-ben",
    "FOLTZ Teri Ann": "foltz-teri-ann",
    "FOLWELL David": "folwell-david",
    "FON Bryn": "fon-bryn",
    "FONDA Jane": "fonda-jane",
    "FONDAKOWSKI Leigh": "fondakowski-leigh",
    "FONDREN Fred": "fondren-fred",
    "FONG Christopher": "fong-christopher",
    "FONG Gilbert C F": "fong-gilbert-c-f",
    "FONG Howard": "fong-howard",
    "FONG Jason": "fong-jason",
    "FONGENIE Vivian": "fongenie-vivian",
    "FONTAINE Robert": "fontaine-robert",
    "FONTAINE Ton": "fontaine-ton",
    "FONTANA Thomas M": "fontana-thomas-m",
    "FONTANES Chris": "fontanes-chris",
    "FONTAYNE Fine Time": "fontayne-fine-time",
    "FONTE Len": "fonte-len",
    "FONTEBOA Fidel": "fonteboa-fidel",
    "FONTECILLA Camilo": "fontecilla-camilo",
    "FONTENBOA Fidel": "fontenboa-fidel",
    "FONUA Lolo": "fonua-lolo",
    "FONVIZIN Denis Ivanovich": "fonvizin-denis-ivanovich",
    "FOOLS PROOF THEATRE ": "fools-proof-theatre",
    "FOON Dennis": "foon-dennis",
    "FOORD Isabelle": "foord-isabelle",
    "FOOT Alistair": "foot-alistair",
    "FOOT Lara": "foot-lara",
    "FOOTE Christina": "foote-christina",
    "FOOTE Daisy": "foote-daisy",
    "FOOTE Ethan": "foote-ethan",
    "FOOTE Graham": "foote-graham",
    "FOOTE Horton": "foote-horton",
    "FOOTE Magill": "foote-magill",
    "FOOTSBARN ": "footsbarn",
    "FOR Lee Joo": "for-lee-joo",
    "FOR WE ARE MANY ": "for-we-are-many",
    "FORAN Adrienne": "foran-adrienne",
    "FORAN Barney": "foran-barney",
    "FORBES Alastair": "forbes-alastair",
    "FORBES Annie": "forbes-annie",
    "FORBES C Scott": "forbes-c-scott",
    "FORBES Cameron": "forbes-cameron",
    "FORBES Caroline": "forbes-caroline",
    "FORBES Charles": "forbes-charles",
    "FORBES Fred J": "forbes-fred-j",
    "FORBES Jamie": "forbes-jamie",
    "FORBES Lynne": "forbes-lynne",
    "FORBES Michael": "forbes-michael",
    "FORBES Roger": "forbes-roger",
    "FORBES Thomas": "forbes-thomas",
    "FORBRITCH Joe": "forbritch-joe",
    "FORCED ENTERTAINMENT ": "forced-entertainment",
    "FORD Alan": "ford-alan",
    "FORD Andre": "ford-andre",
    "FORD Bethany": "ford-bethany",
    "FORD Brooke A": "ford-brooke-a",
    "FORD Charles": "ford-charles",
    "FORD Charlotte": "ford-charlotte",
    "FORD Corey": "ford-corey",
    "FORD David": "ford-david",
    "FORD David Douglas": "ford-david-douglas",
    "FORD David S": "ford-david-s",
    "FORD Ernest": "ford-ernest",
    "FORD Evelyn": "ford-evelyn",
    "FORD Fergus": "ford-fergus",
    "FORD Frank B": "ford-frank-b",
    "FORD Gaby": "ford-gaby",
    "FORD Garret": "ford-garret",
    "FORD James Robert": "ford-james-robert",
    "FORD James-Allen": "ford-james-allen",
    "FORD Jane": "ford-jane",
    "FORD Jason": "ford-jason",
    "FORD Joan": "ford-joan",
    "FORD Joe Taylor": "ford-joe-taylor",
    "FORD Joshua": "ford-joshua",
    "FORD Julie": "ford-julie",
    "FORD Laura": "ford-laura",
    "FORD Lin": "ford-lin",
    "FORD Megan": "ford-megan",
    "FORD Michael James": "ford-michael-james",
    "FORD Mick": "ford-mick",
    "FORD Nancy": "ford-nancy",
    "FORD Randy": "ford-randy",
    "FORD Robert": "ford-robert",
    "FORD Robert John": "ford-robert-john",
    "FORD Ruth": "ford-ruth",
    "FORD Sarah": "ford-sarah",
    "FORD Simon": "ford-simon",
    "FORD T Cat": "ford-t-cat",
    "FORD Tim": "ford-tim",
    "FORD Timothy": "ford-timothy",
    "FORD Tramaine Montell": "ford-tramaine-montell",
    "FORD William": "ford-william",
    "FORDE Adam": "forde-adam",
    "FORDE B Bil": "forde-b-bil",
    "FORDE Catherine": "forde-catherine",
    "FORDE Elizabeth": "forde-elizabeth",
    "FORDE Ida": "forde-ida",
    "FORDE Leila": "forde-leila",
    "FORDE Margery": "forde-margery",
    "FORDE Michael": "forde-michael",
    "FORDE Nigel": "forde-nigel",
    "FORDE Patricia": "forde-patricia",
    "FORDE Rogerson": "forde-rogerson",
    "FORDHAM Debra": "fordham-debra",
    "FORDHAM Finn": "fordham-finn",
    "FORDHAM Philippa": "fordham-philippa",
    "FORDHAM Rosy": "fordham-rosy",
    "FORDRED Chris": "fordred-chris",
    "FORDYCE Maxwell": "fordyce-maxwell",
    "FORDYCE Robin": "fordyce-robin",
    "FOREMAN Bridget": "foreman-bridget",
    "FOREMAN Cecilia": "foreman-cecilia",
    "FOREMAN Gill": "foreman-gill",
    "FOREMAN Karole": "foreman-karole",
    "FOREMAN Lauren": "foreman-lauren",
    "FOREMAN Martin": "foreman-martin",
    "FOREMAN Paul": "foreman-paul",
    "FOREMAN Richard": "foreman-richard",
    "FOREMAN Ronlin": "foreman-ronlin",
    "FOREMAN Sam": "foreman-sam",
    "FOREMAN Samuel L": "foreman-samuel-l",
    "FOREMAN Tom": "foreman-tom",
    "FORESMAN Becca": "foresman-becca",
    "FOREST Chris": "forest-chris",
    "FOREST D'yan": "forest-d-yan",
    "FOREST Jean": "forest-jean",
    "FOREST Robert": "forest-robert",
    "FORESTER Wayne": "forester-wayne",
    "FOREY Margaret": "forey-margaret",
    "FORGASH Adam": "forgash-adam",
    "FORGASZ Rachel": "forgasz-rachel",
    "FORGETTE Katie": "forgette-katie",
    "FORGIE Derek": "forgie-derek",
    "FORIER Elise": "forier-elise",
    "FORKBEARD FANTASY ": "forkbeard-fantasy",
    "FORMA Anthony": "forma-anthony",
    "FORMAN David": "forman-david",
    "FORMAN Joan": "forman-joan",
    "FORMAN John D": "forman-john-d",
    "FORMAN Sam": "forman-sam",
    "FORMAN Susan": "forman-susan",
    "FORMBY Dana Lynn": "formby-dana-lynn",
    "FORMISANO Laura": "formisano-laura",
    "FORNACE Sarah": "fornace-sarah",
    "FORNAROLA Drew": "fornarola-drew",
    "FORNES Maria Irene": "fornes-maria-irene",
    "FORNOFF Frederick H": "fornoff-frederick-h",
    "FORNSHELL Sarah": "fornshell-sarah",
    "FORRELL Lisa": "forrell-lisa",
    "FORREST Angela": "forrest-angela",
    "FORREST David": "forrest-david",
    "FORREST Diane": "forrest-diane",
    "FORREST Donald": "forrest-donald",
    "FORREST George": "forrest-george",
    "FORREST Robert": "forrest-robert",
    "FORREST Robert C": "forrest-robert-c",
    "FORRESTER Brian": "forrester-brian",
    "FORRESTER Lynne": "forrester-lynne",
    "FORREST-TURNER Lorraine": "forrest-turner-lorraine",
    "FORRISTAL Desmond": "forristal-desmond",
    "FORSAITH Ann": "forsaith-ann",
    "FORSBERG Julia": "forsberg-julia",
    "FORSBERG Kent": "forsberg-kent",
    "FORSBERG Rolf": "forsberg-rolf",
    "FORSHAW Robert Pierpont": "forshaw-robert-pierpont",
    "FORSHAY-LUNSFORD Cin": "forshay-lunsford-cin",
    "FORSSELL Boel": "forssell-boel",
    "FORSSELL Lars": "forssell-lars",
    "FORSTEN Michele": "forsten-michele",
    "FORSTER Benjamin": "forster-benjamin",
    "FORSTER David": "forster-david",
    "FORSTER Joan S": "forster-joan-s",
    "FORSTER John": "forster-john",
    "FORSTER Juliet": "forster-juliet",
    "FORSTER Michelanne": "forster-michelanne",
    "FORSYTH Anna": "forsyth-anna",
    "FORSYTH Anthony": "forsyth-anthony",
    "FORSYTH Frederick": "forsyth-frederick",
    "FORSYTH Graeme": "forsyth-graeme",
    "FORSYTH Ian": "forsyth-ian",
    "FORSYTH James": "forsyth-james",
    "FORSYTH Julian": "forsyth-julian",
    "FORSYTH Julie": "forsyth-julie",
    "FORSYTH Louise H": "forsyth-louise-h",
    "FORSYTH Margarete": "forsyth-margarete",
    "FORSYTH Oli": "forsyth-oli",
    "FORSYTH William": "forsyth-william",
    "FORSYTHE Drew": "forsythe-drew",
    "FORSYTHE Tracy": "forsythe-tracy",
    "FORSYTHE William": "forsythe-william",
    "FORT Bernadette": "fort-bernadette",
    "FORTE Gian Marco Lo": "forte-gian-marco-lo",
    "FORTE James": "forte-james",
    "FORTENBERRY Dorothy": "fortenberry-dorothy",
    "FORTEY Stuart": "fortey-stuart",
    "FORTH Laura J": "forth-laura-j",
    "FORTH Sally": "forth-sally",
    "FORTI Laura": "forti-laura",
    "FORTIN Larry Gene": "fortin-larry-gene",
    "FORTIN Simon": "fortin-simon",
    "FORTSON Deborah Lake": "fortson-deborah-lake",
    "FORTSON Leigh": "fortson-leigh",
    "FORTUNATI ": "fortunati",
    "FORTUNATO Raymond": "fortunato-raymond",
    "FORTUNE Eddie": "fortune-eddie",
    "FORTUNE James": "fortune-james",
    "FORTUNE Jaye": "fortune-jaye",
    "FORTUNE Rebekah": "fortune-rebekah",
    "FOSBERG Michael Sidney": "fosberg-michael-sidney",
    "FOSBROOK Michael": "fosbrook-michael",
    "FOS'I Opetaia": "fos-i-opetaia",
    "FOSKOLOU Nadia": "foskolou-nadia",
    "FOSS Lucas": "foss-lucas",
    "FOSS Rene": "foss-rene",
    "FOSSE Bob": "fosse-bob",
    "FOSSE Jon": "fosse-jon",
    "FOSSE Nicole": "fosse-nicole",
    "FOSSEY Eleanor": "fossey-eleanor",
    "FOSTER Abbie": "foster-abbie",
    "FOSTER Adam": "foster-adam",
    "FOSTER Alex": "foster-alex",
    "FOSTER Alison": "foster-alison",
    "FOSTER Andy": "foster-andy",
    "FOSTER Annette": "foster-annette",
    "FOSTER Ben": "foster-ben",
    "FOSTER Beverley Anne": "foster-beverley-anne",
    "FOSTER Brian": "foster-brian",
    "FOSTER Brian D": "foster-brian-d",
    "FOSTER C Stephen": "foster-c-stephen",
    "FOSTER Christine": "foster-christine",
    "FOSTER Dawn L": "foster-dawn-l",
    "FOSTER Dutton": "foster-dutton",
    "FOSTER Eden": "foster-eden",
    "FOSTER Emmett": "foster-emmett",
    "FOSTER F A": "foster-f-a",
    "FOSTER George Cecil": "foster-george-cecil",
    "FOSTER Gerard": "foster-gerard",
    "FOSTER Gordon": "foster-gordon",
    "FOSTER Gregory": "foster-gregory",
    "FOSTER Helen": "foster-helen",
    "FOSTER Hunter": "foster-hunter",
    "FOSTER Hutchins": "foster-hutchins",
    "FOSTER Jamie": "foster-jamie",
    "FOSTER Jessica": "foster-jessica",
    "FOSTER John": "foster-john",
    "FOSTER John Wilson": "foster-john-wilson",
    "FOSTER Joseph": "foster-joseph",
    "FOSTER K R S": "foster-k-r-s",
    "FOSTER Kate": "foster-kate",
    "FOSTER Keith": "foster-keith",
    "FOSTER Kimberly": "foster-kimberly",
    "FOSTER Kirk": "foster-kirk",
    "FOSTER Lucy": "foster-lucy",
    "FOSTER Mathew": "foster-mathew",
    "FOSTER Matthew": "foster-matthew",
    "FOSTER Michael": "foster-michael",
    "FOSTER Miranda": "foster-miranda",
    "FOSTER Murray": "foster-murray",
    "FOSTER Neal": "foster-neal",
    "FOSTER Norm": "foster-norm",
    "FOSTER Paul": "foster-paul",
    "FOSTER Paul B": "foster-paul-b",
    "FOSTER Rick": "foster-rick",
    "FOSTER Rosemary": "foster-rosemary",
    "FOSTER Skip": "foster-skip",
    "FOSTER Sophie": "foster-sophie",
    "FOSTER Stephen": "foster-stephen",
    "FOSTER Tony": "foster-tony",
    "FOSTER Winnie": "foster-winnie",
    "FOSTER (PAFOSTER) Paul": "foster-paul-2",
    "FOSTINI John": "fostini-john",
    "FOTHERGILL Robert": "fothergill-robert",
    "FOTHERINGHAM Elizabeth": "fotheringham-elizabeth",
    "FOTHERINGHAM Richard": "fotheringham-richard",
    "FOTI John": "foti-john",
    "FOTIS Matt": "fotis-matt",
    "FOTIS Mike": "fotis-mike",
    "FOUCARD Alexandra": "foucard-alexandra",
    "FOUCHE Gene": "fouche-gene",
    "FOUDY Austin": "foudy-austin",
    "FOUERE Olwen": "fouere-olwen",
    "FOULDS Adam": "foulds-adam",
    "FOULDS John": "foulds-john",
    "FOULTER James": "foulter-james",
    "FOUND Katie": "found-katie",
    "FOUNTAIN Bill": "fountain-bill",
    "FOUNTAIN Brooks Lyle": "fountain-brooks-lyle",
    "FOUNTAIN Nev": "fountain-nev",
    "FOUNTAIN Tim": "fountain-tim",
    "FOUR BROTHERS, THE ": "four-brothers",
    "FOUR HORSEMEN, THE ": "four-horsemen",
    "FOURACES George": "fouraces-george",
    "FOURIE Charles J": "fourie-charles-j",
    "FOURNIER Jack": "fournier-jack",
    "FOURNIER John": "fournier-john",
    "FOURSIGHT THEATRE ": "foursight-theatre",
    "FOURTH LEAF THEATRE COMPANY ": "fourth-leaf-theatre-company",
    "FOURTH MONKEY THEATRE COMPANY ": "fourth-monkey-theatre-company",
    "FOUST Joe": "foust-joe",
    "FOVARGE Oscar": "fovarge-oscar",
    "FOW Elizabeth": "fow-elizabeth",
    "FOWKES William": "fowkes-william",
    "FOWLER Arthur": "fowler-arthur",
    "FOWLER Darcy": "fowler-darcy",
    "FOWLER David Jean": "fowler-david-jean",
    "FOWLER Earl Leslie": "fowler-earl-leslie",
    "FOWLER Elizabeth Anne": "fowler-elizabeth-anne",
    "FOWLER Eric": "fowler-eric",
    "FOWLER Jeffrey Jay": "fowler-jeffrey-jay",
    "FOWLER Jeri": "fowler-jeri",
    "FOWLER Jim": "fowler-jim",
    "FOWLER John": "fowler-john",
    "FOWLER Jude": "fowler-jude",
    "FOWLER Kim": "fowler-kim",
    "FOWLER Mayhill": "fowler-mayhill",
    "FOWLER Molly": "fowler-molly",
    "FOWLER Stephanie": "fowler-stephanie",
    "FOWLER-WATT Duncan": "fowler-watt-duncan",
    "FOWLES John": "fowles-john",
    "FOWLIE Wallace": "fowlie-wallace",
    "FOX Adam": "fox-adam",
    "FOX Akiva": "fox-akiva",
    "FOX Albert (Al)": "fox-albert",
    "FOX Amy": "fox-amy",
    "FOX Anna": "fox-anna",
    "FOX Ben": "fox-ben",
    "FOX Brian": "fox-brian",
    "FOX Brooke": "fox-brooke",
    "FOX Bylesley": "fox-bylesley",
    "FOX Cenarth": "fox-cenarth",
    "FOX Charles": "fox-charles",
    "FOX Dave": "fox-dave",
    "FOX Dian": "fox-dian",
    "FOX Diana": "fox-diana",
    "FOX Ellen": "fox-ellen",
    "FOX Gabrielle": "fox-gabrielle",
    "FOX Helena": "fox-helena",
    "FOX Jamie M": "fox-jamie-m",
    "FOX John": "fox-john",
    "FOX Josh": "fox-josh",
    "FOX Julian": "fox-julian",
    "FOX Karen": "fox-karen",
    "FOX Kate": "fox-kate",
    "FOX Krys": "fox-krys",
    "FOX Lawrence B": "fox-lawrence-b",
    "FOX Liam": "fox-liam",
    "FOX Loren": "fox-loren",
    "FOX Louise": "fox-louise",
    "FOX Maggie": "fox-maggie",
    "FOX Martin": "fox-martin",
    "FOX Matt": "fox-matt",
    "FOX Matthew Stanford": "fox-matthew-stanford",
    "FOX Michael": "fox-michael",
    "FOX Molly": "fox-molly",
    "FOX Paul Hervey": "fox-paul-hervey",
    "FOX Phil": "fox-phil",
    "FOX Ray Errol": "fox-ray-errol",
    "FOX Raymond": "fox-raymond",
    "FOX Robbie": "fox-robbie",
    "FOX Sam": "fox-sam",
    "FOX Skylar": "fox-skylar",
    "FOX Stephen": "fox-stephen",
    "FOX Steve": "fox-steve",
    "FOX Terry Curtis": "fox-terry-curtis",
    "FOX Tom": "fox-tom",
    "FOX W H": "fox-w-h",
    "FOXALL Vince": "foxall-vince",
    "FOX-HARTIN Sam": "fox-hartin-sam",
    "FOXSMITH Daniel": "foxsmith-daniel",
    "FOXTON David": "foxton-david",
    "FOXWELL Chris": "foxwell-chris",
    "FOXX Daniel": "foxx-daniel",
    "FOXY AND HUSK ": "foxy-and-husk",
    "FOY Douglas B": "foy-douglas-b",
    "FOYLE Naomi": "foyle-naomi",
    "FOYSTER Brian": "foyster-brian",
    "FRACHT J Albert": "fracht-j-albert",
    "FRADKIN Allison": "fradkin-allison",
    "FRADRICH James": "fradrich-james",
    "FRAGOLA Christina": "fragola-christina",
    "FRAHM Frederick": "frahm-frederick",
    "FRAISTAT Ann": "fraistat-ann",
    "FRAISTAT Shawn": "fraistat-shawn",
    "FRAKES Jack": "frakes-jack",
    "FRALEY Brian D": "fraley-brian-d",
    "FRALLER Larry": "fraller-larry",
    "FRAM Dori": "fram-dori",
    "FRAME Alen": "frame-alen",
    "FRAME Arthur": "frame-arthur",
    "FRAME Chet": "frame-chet",
    "FRAME Janet": "frame-janet",
    "FRAME Ronald": "frame-ronald",
    "FRAN WEN ": "fran-wen",
    "FRANCABVILLA Christine": "francabvilla-christine",
    "FRANCE Anna Kay": "france-anna-kay",
    "FRANCE Jane": "france-jane",
    "FRANCE Juliann": "france-juliann",
    "FRANCE Michelle": "france-michelle",
    "FRANCE Peter": "france-peter",
    "FRANCE Richard": "france-richard",
    "FRANCES Charlotte": "frances-charlotte",
    "FRANCES Ruth": "frances-ruth",
    "FRANCESCA Undine": "francesca-undine",
    "FRANCESCHETTI Antonio": "franceschetti-antonio",
    "FRANCESCHI Antonia": "franceschi-antonia",
    "FRANCESCHILD Donna": "franceschild-donna",
    "FRANCESCHINA John": "franceschina-john",
    "FRANCESCHINI Crystal": "franceschini-crystal",
    "FRANCESCHINI John": "franceschini-john",
    "FRANCES-WHITE Deborah": "frances-white-deborah",
    "FRANCIERE Arlette": "franciere-arlette",
    "FRANCIS Alan": "francis-alan",
    "FRANCIS Alasdair": "francis-alasdair",
    "FRANCIS Ann Margaret": "francis-ann-margaret",
    "FRANCIS Ashton": "francis-ashton",
    "FRANCIS Ben": "francis-ben",
    "FRANCIS Cara": "francis-cara",
    "FRANCIS Clive": "francis-clive",
    "FRANCIS David": "francis-david",
    "FRANCIS Diane": "francis-diane",
    "FRANCIS Dominic": "francis-dominic",
    "FRANCIS Gordon": "francis-gordon",
    "FRANCIS James": "francis-james",
    "FRANCIS Jane Lloyd": "francis-jane-lloyd",
    "FRANCIS Jason": "francis-jason",
    "FRANCIS John Oswald": "francis-john-oswald",
    "FRANCIS Juliana": "francis-juliana",
    "FRANCIS Kati": "francis-kati",
    "FRANCIS Marvin": "francis-marvin",
    "FRANCIS Mary": "francis-mary",
    "FRANCIS Matthew (1)": "francis-matthew-1",
    "FRANCIS Matthew (2)": "francis-matthew-2",
    "FRANCIS Maurice": "francis-maurice",
    "FRANCIS Paul": "francis-paul",
    "FRANCIS Robert J": "francis-robert-j",
    "FRANCIS Seseen": "francis-seseen",
    "FRANCIS Silvano Griffith": "francis-silvano-griffith",
    "FRANCIS Simon": "francis-simon",
    "FRANCIS Stephen": "francis-stephen",
    "FRANCIS Thais": "francis-thais",
    "FRANCIS Tom": "francis-tom",
    "FRANCIS William": "francis-william",
    "FRANCISCO Sam": "francisco-sam",
    "FRANCKE Caroline": "francke-caroline",
    "FRANCO Cris": "franco-cris",
    "FRANCO Henry": "franco-henry",
    "FRANCO Steve": "franco-steve",
    "FRANCOEUR Bill": "francoeur-bill",
    "FRANCOIS Kat": "francois-kat",
    "FRANCOUER Bill": "francouer-bill",
    "FRANDIN Stephen": "frandin-stephen",
    "FRANDSEN Carl": "frandsen-carl",
    "FRANDSEN Erik": "frandsen-erik",
    "FRANDSEN Kenn L D": "frandsen-kenn-l-d",
    "FRANGIONE Lucia": "frangione-lucia",
    "FRANGUI Leah": "frangui-leah",
    "FRANK Alicia": "frank-alicia",
    "FRANK Andrew": "frank-andrew",
    "FRANK Chandra": "frank-chandra",
    "FRANK Charles": "frank-charles",
    "FRANK Chris": "frank-chris",
    "FRANK Cynthia": "frank-cynthia",
    "FRANK D F": "frank-d-f",
    "FRANK Daniel B": "frank-daniel-b",
    "FRANK Dieter": "frank-dieter",
    "FRANK Doug": "frank-doug",
    "FRANK Glenda": "frank-glenda",
    "FRANK Jessica": "frank-jessica",
    "FRANK Joseph": "frank-joseph",
    "FRANK Josh": "frank-josh",
    "FRANK Karen Ilene": "frank-karen-ilene",
    "FRANK Mathew": "frank-mathew",
    "FRANK Melvin": "frank-melvin",
    "FRANK Miguel": "frank-miguel",
    "FRANK Nancy Cooper": "frank-nancy-cooper",
    "FRANK Raccoon": "frank-raccoon",
    "FRANK Scott": "frank-scott",
    "FRANK T S": "frank-t-s",
    "FRANKAU Ronald": "frankau-ronald",
    "FRANKCOM Sarah": "frankcom-sarah",
    "FRANKEL Doris": "frankel-doris",
    "FRANKEL Etan": "frankel-etan",
    "FRANKEL J P": "frankel-j-p",
    "FRANKEL Leland": "frankel-leland",
    "FRANKEL Robert": "frankel-robert",
    "FRANKEL Ron": "frankel-ron",
    "FRANKEL Scott": "frankel-scott",
    "FRANKEN Gerardine": "franken-gerardine",
    "FRANKEN Rose": "franken-rose",
    "FRANKENBURG Daniel": "frankenburg-daniel",
    "FRANKFURT Asher": "frankfurt-asher",
    "FRANKLAND Emma": "frankland-emma",
    "FRANKLAND John": "frankland-john",
    "FRANKLAND Richard": "frankland-richard",
    "FRANKLAND Tom": "frankland-tom",
    "FRANKLE Sophie": "frankle-sophie",
    "FRANKLIN Anita": "franklin-anita",
    "FRANKLIN Annie": "franklin-annie",
    "FRANKLIN Brian Lee": "franklin-brian-lee",
    "FRANKLIN Caroline Kelly": "franklin-caroline-kelly",
    "FRANKLIN Clarence": "franklin-clarence",
    "FRANKLIN Clay": "franklin-clay",
    "FRANKLIN David": "franklin-david",
    "FRANKLIN Edward": "franklin-edward",
    "FRANKLIN Elizabeth": "franklin-elizabeth",
    "FRANKLIN Harold": "franklin-harold",
    "FRANKLIN J E": "franklin-j-e",
    "FRANKLIN Jennifer": "franklin-jennifer",
    "FRANKLIN Josh": "franklin-josh",
    "FRANKLIN Mary": "franklin-mary",
    "FRANKLIN Miles": "franklin-miles",
    "FRANKLIN Nicco": "franklin-nicco",
    "FRANKLIN Richard": "franklin-richard",
    "FRANKLIN Sandra": "franklin-sandra",
    "FRANKLIN Tim": "franklin-tim",
    "FRANKLIN Will": "franklin-will",
    "FRANKLIN-YOUNG (AKA IFE) Gail F": "franklin-young-gail-f",
    "FRANKONIS W A": "frankonis-w-a",
    "FRANKOVICH Virginia": "frankovich-virginia",
    "FRANKS Alan": "franks-alan",
    "FRANKS Cynthia": "franks-cynthia",
    "FRANKS Jennie": "franks-jennie",
    "FRANKS Richard": "franks-richard",
    "FRANKSON David": "frankson-david",
    "FRANTIC ASSEMBLY ": "frantic-assembly",
    "FRANZEN Jonathan": "franzen-jonathan",
    "FRANZESE Daniel": "franzese-daniel",
    "FRANZMANN Vivienne": "franzmann-vivienne",
    "FRASER Alan": "fraser-alan",
    "FRASER Alister": "fraser-alister",
    "FRASER Antonia": "fraser-antonia",
    "FRASER Barbara Means": "fraser-barbara-means",
    "FRASER Brad": "fraser-brad",
    "FRASER Bruce": "fraser-bruce",
    "FRASER Dan": "fraser-dan",
    "FRASER David Gustav": "fraser-david-gustav",
    "FRASER Dennie Sullivan": "fraser-dennie-sullivan",
    "FRASER Donald": "fraser-donald",
    "FRASER Douglas": "fraser-douglas",
    "FRASER Flip": "fraser-flip",
    "FRASER Flora": "fraser-flora",
    "FRASER Gilly": "fraser-gilly",
    "FRASER Graham": "fraser-graham",
    "FRASER Grant": "fraser-grant",
    "FRASER Hadley": "fraser-hadley",
    "FRASER Helen": "fraser-helen",
    "FRASER Ian": "fraser-ian",
    "FRASER Isabella": "fraser-isabella",
    "FRASER Jennifer": "fraser-jennifer",
    "FRASER Jessica": "fraser-jessica",
    "FRASER John AD": "fraser-john-ad",
    "FRASER Jon": "fraser-jon",
    "FRASER Kon": "fraser-kon",
    "FRASER Malcolm": "fraser-malcolm",
    "FRASER Mat": "fraser-mat",
    "FRASER Michael": "fraser-michael",
    "FRASER Olive": "fraser-olive",
    "FRASER P": "fraser-p",
    "FRASER Patti": "fraser-patti",
    "FRASER Paul": "fraser-paul",
    "FRASER Prudence": "fraser-prudence",
    "FRASER Robert": "fraser-robert",
    "FRASER Sonia": "fraser-sonia",
    "FRASER Steven": "fraser-steven",
    "FRASER Theo": "fraser-theo",
    "FRASER Toa": "fraser-toa",
    "FRASER William": "fraser-william",
    "FRASER Zach": "fraser-zach",
    "FRASER Zannie": "fraser-zannie",
    "FRASER-MUNRO Ronald": "fraser-munro-ronald",
    "FRATER Scott": "frater-scott",
    "FRATICELLI Rina": "fraticelli-rina",
    "FRATTARE Tom": "frattare-tom",
    "FRATTI Mario": "fratti-mario",
    "FRATTINI Di": "frattini-di",
    "FRATUS Tiziano": "fratus-tiziano",
    "FRAVAL Antoine": "fraval-antoine",
    "FRAWLEY Malcolm": "frawley-malcolm",
    "FRAY Jacques": "fray-jacques",
    "FRAYN Alan": "frayn-alan",
    "FRAYN Michael": "frayn-michael",
    "FRAZAO Joana": "frazao-joana",
    "FRAZAO Leticia": "frazao-leticia",
    "FRAZER Jenny": "frazer-jenny",
    "FRAZER Kon": "frazer-kon",
    "FRAZER Ronald": "frazer-ronald",
    "FRAZIER Hank": "frazier-hank",
    "FRAZIER Kati": "frazier-kati",
    "FRAZIER Kermit": "frazier-kermit",
    "FRAZIER JR Levi": "frazier-jr-levi",
    "FREAKSHOW ": "freakshow",
    "FRECHETTE Carole": "frechette-carol",
    "FRECHTMAN Bernard": "frechtman-bernard",
    "FREDA Jon": "freda-jon",
    "FREDEN Sofia": "freden-sofia",
    "FREDERICK David": "frederick-david",
    "FREDERICK Ifeyinwa": "frederick-ifeyinwa",
    "FREDERICK Jack": "frederick-jack",
    "FREDERICK HENDRICKS YOUTH ENSEMBLE OF ATLANTA ": "frederick-hendricks-youth-ensemble-of-atlanta",
    "FREDERICKS Claude": "fredericks-claude",
    "FREDERICKSON Christine M": "frederickson-christine-m",
    "FREDERICKSON David": "frederickson-david",
    "FREDMAN Richard": "fredman-richard",
    "FREDO John": "fredo-john",
    "FREDRIC Barnaby": "fredric-barnaby",
    "FREDRICK Judith": "fredrick-judith",
    "FREDRICKS Katherine Brann": "fredricks-katherine-brann",
    "FREDRICKSSON Kristin": "fredricksson-kristin",
    "FREDRO Aleksander": "fredro-aleksander",
    "FREE Alana Ruben": "free-alana-ruben",
    "FREE Colin": "free-colin",
    "FREE Kevin R": "free-kevin-r",
    "FREE Richard": "free-richard",
    "FREE Scott": "free-scott",
    "FREE SOUTHERN THEATRE ": "free-southern-theatre",
    "FREE STREET THEATER ENSEMBLE ": "free-street-theater-ensemble",
    "FREEBERG Debra L": "freeberg-debra-l",
    "FREEBURG Erin Alyssa": "freeburg-erin-alyssa",
    "FREED Amy": "freed-amy",
    "FREED Arthur": "freed-arthur",
    "FREED Donald": "freed-donald",
    "FREED Jenna Lauren": "freed-jenna-lauren",
    "FREED John": "freed-john",
    "FREED Judy": "freed-judy",
    "FREED Paul": "freed-paul",
    "FREEDMAN Ben": "freedman-ben",
    "FREEDMAN Colette": "freedman-colette",
    "FREEDMAN Gerald": "freedman-gerald",
    "FREEDMAN Harris W": "freedman-harris-w",
    "FREEDMAN John": "freedman-john",
    "FREEDMAN Max": "freedman-max",
    "FREEDMAN Philip": "freedman-philip",
    "FREEDMAN Rachel": "freedman-rachel",
    "FREEDMAN Robert L": "freedman-robert-l",
    "FREEDMAN Sylvia": "freedman-sylvia",
    "FREEDOM THEATRE ": "freedom-theatre",
    "FREEK George": "freek-george",
    "FREELAND Benjamin": "freeland-benjamin",
    "FREEMAN Aaron": "freeman-aaron",
    "FREEMAN Alan": "freeman-alan",
    "FREEMAN Brian": "freeman-brian",
    "FREEMAN Bud": "freeman-bud",
    "FREEMAN Carol": "freeman-carol",
    "FREEMAN Charles K": "freeman-charles-k",
    "FREEMAN Cyndi": "freeman-cyndi",
    "FREEMAN Dan": "freeman-dan",
    "FREEMAN Dave": "freeman-dave",
    "FREEMAN David": "freeman-david",
    "FREEMAN David (1)": "freeman-david-1",
    "FREEMAN David (2)": "freeman-david-2",
    "FREEMAN David E": "freeman-david-e",
    "FREEMAN Deborah": "freeman-deborah",
    "FREEMAN Dexter": "freeman-dexter",
    "FREEMAN Edward": "freeman-edward",
    "FREEMAN Elena": "freeman-elena",
    "FREEMAN Emily": "freeman-emily",
    "FREEMAN Everett": "freeman-everett",
    "FREEMAN Greg": "freeman-greg",
    "FREEMAN Jackie": "freeman-jackie",
    "FREEMAN Joanne": "freeman-joanne",
    "FREEMAN Jonathan Marshall": "freeman-jonathan-marshall",
    "FREEMAN Leayne": "freeman-leayne",
    "FREEMAN Lee": "freeman-lee",
    "FREEMAN Lucy": "freeman-lucy",
    "FREEMAN Maree": "freeman-maree",
    "FREEMAN Matt": "freeman-matt",
    "FREEMAN Matthew": "freeman-matthew",
    "FREEMAN Michael": "freeman-michael",
    "FREEMAN Nathan Ross": "freeman-nathan-ross",
    "FREEMAN Neal": "freeman-neal",
    "FREEMAN Papi Kymone": "freeman-papi-kymone",
    "FREEMAN Polly": "freeman-polly",
    "FREEMAN Sam": "freeman-sam",
    "FREEMAN Sam H": "freeman-sam-h",
    "FREEMAN Sandra": "freeman-sandra",
    "FREEMAN Scott": "freeman-scott",
    "FREEMAN Seth": "freeman-seth",
    "FREEMAN Stan": "freeman-stan",
    "FREEMAN Ted": "freeman-ted",
    "FREEMAN-SAYER Philip": "freeman-sayer-philip",
    "FREENAN Declan": "freenan-declan",
    "FREESE Ross": "freese-ross",
    "FREESON Jeremy": "freeson-jeremy",
    "FREESTONE Alan": "freestone-alan",
    "FREESTONE Elizabeth": "freestone-elizabeth",
    "FREI Nicki": "frei-nicki",
    "FREIBACH Shir": "freibach-shir",
    "FREIBERGER Jack \"Fry\"": "freiberger-jack",
    "FREIBURG Johanna": "freiburg-johanna",
    "FREIDERICI Kathy": "freiderici-kathy",
    "FREIDLICH Max W": "freidlich-max-w",
    "FREIER Greg": "freier-greg",
    "FREIJ Julien": "freij-julien",
    "FREILICH Josh": "freilich-josh",
    "FREIMAN Lexi": "freiman-lexi",
    "FREIMAN Louis": "freiman-louis",
    "FREISTADT Berta": "freistadt-berta",
    "FREMI Edith": "fremi-edith",
    "FRENCH Amy": "french-amy",
    "FRENCH Arthur W": "french-arthur-w",
    "FRENCH David": "french-david",
    "FRENCH Dawn": "french-dawn",
    "FRENCH Jack": "french-jack",
    "FRENCH Judith": "french-judith",
    "FRENCH Lorna": "french-lorna",
    "FRENCH Michael": "french-michael",
    "FRENCH Patti": "french-patti",
    "FRENCH Robin": "french-robin",
    "FRENCH Sam": "french-sam",
    "FRENCH Samuel": "french-samuel",
    "FRENCH Segun Lee": "french-segun-lee",
    "FRENCH Timothy": "french-timothy",
    "FRENCH Vivian": "french-vivian",
    "FRENCH III Arthur W": "french-iii-arthur-w",
    "FRENI Edith": "freni-edith",
    "FRENI Nicole": "freni-nicole",
    "FRENKIEL Nevil": "frenkiel-nevil",
    "FRENZ Horst": "frenz-horst",
    "FRERE Jane": "frere-jane",
    "FRERICHS Sue": "frerichs-sue",
    "FRESCO Dylan": "fresco-dylan",
    "FRESCO TC ": "fresco-tc",
    "FRESSON Jeremy": "fresson-jeremy",
    "FREUND Anne": "freund-anne",
    "FREUND Philip": "freund-philip",
    "FREUNDT Michael": "freundt-michael",
    "FREWEN Arthur": "frewen-arthur",
    "FREY L W": "frey-l-w",
    "FREY Robert Irviing": "frey-robert-irviing",
    "FREYER Frederick Q": "freyer-frederick-q",
    "FREYMAN Jay": "freyman-jay",
    "FREZZA Marco": "frezza-marco",
    "FRIAR Kimon": "friar-kimon",
    "FRIBOURG Stephanie": "fribourg-stephanie",
    "FRICK Nancy": "frick-nancy",
    "FRICKER John": "fricker-john",
    "FRID Catherine": "frid-catherine",
    "FRIDEN Chris": "friden-chris",
    "FRIED Adam": "fried-adam",
    "FRIED Barbara": "fried-barbara",
    "FRIED Don": "fried-don",
    "FRIED Emanuel": "fried-emanuel",
    "FRIED Gerald": "fried-gerald",
    "FRIED Stephen": "fried-stephen",
    "FRIEDBERG William": "friedberg-william",
    "FRIEDEL Sarah": "friedel-sarah",
    "FRIEDENN Neva": "friedenn-neva",
    "FRIEDKIN Jenirose": "friedkin-jenirose",
    "FRIEDLAND Dahlia": "friedland-dahlia",
    "FRIEDMAN Alan Foster": "friedman-alan-foster",
    "FRIEDMAN Allan Jay": "friedman-allan-jay",
    "FRIEDMAN Bobby": "friedman-bobby",
    "FRIEDMAN Brad": "friedman-brad",
    "FRIEDMAN Bruce Jay": "friedman-bruce-jay",
    "FRIEDMAN Dan": "friedman-dan",
    "FRIEDMAN E Fisher": "friedman-e-fisher",
    "FRIEDMAN Edward": "friedman-edward",
    "FRIEDMAN Esther": "friedman-esther",
    "FRIEDMAN Eve": "friedman-eve",
    "FRIEDMAN Gary William": "friedman-gary-william",
    "FRIEDMAN Hannah": "friedman-hannah",
    "FRIEDMAN Jena": "friedman-jena",
    "FRIEDMAN Joel P": "friedman-joel-p",
    "FRIEDMAN Josh Ben": "friedman-josh-ben",
    "FRIEDMAN Karl": "friedman-karl",
    "FRIEDMAN Ken": "friedman-ken",
    "FRIEDMAN Leon": "friedman-leon",
    "FRIEDMAN Maria": "friedman-maria",
    "FRIEDMAN Mark": "friedman-mark",
    "FRIEDMAN Meridith": "friedman-meridith",
    "FRIEDMAN Michael": "friedman-michael",
    "FRIEDMAN Philip": "friedman-philip",
    "FRIEDMAN Robert Marc": "friedman-robert-marc",
    "FRIEDMAN Rosalind": "friedman-rosalind",
    "FRIEDMAN Rosemary": "friedman-rosemary",
    "FRIEDMAN Roy": "friedman-roy",
    "FRIEDMAN Seth": "friedman-seth",
    "FRIEDMAN Sheldon E": "friedman-sheldon-e",
    "FRIEDMAN Sherry": "friedman-sherry",
    "FRIEDMAN Steve": "friedman-steve",
    "FRIEDMAN Tracy": "friedman-tracy",
    "FRIEDMAN Zach": "friedman-zach",
    "FRIEDMAN Zack": "friedman-zack",
    "FRIEDRICH Nancy": "friedrich-nancy",
    "FRIEDRICHITHOSAS Jorg": "friedrichithosas-jorg",
    "FRIEL Brian": "friel-brian",
    "FRIEL George": "friel-george",
    "FRIEL Michael": "friel-michael",
    "FRIELBACH Shir": "frielbach-shir",
    "FRIEND Cassie": "friend-cassie",
    "FRIEND David": "friend-david",
    "FRIEND Michael": "friend-michael",
    "FRIEND Rick": "friend-rick",
    "FRIEND Simon": "friend-simon",
    "FRIERSON Andrea": "frierson-andrea",
    "FRIERSON Eddie": "frierson-eddie",
    "FRIERSON-TONEY Andrea": "frierson-toney-andrea",
    "FRIES Kenny": "fries-kenny",
    "FRIESEN Patrick": "friesen-patrick",
    "FRINGS Ketti": "frings-ketti",
    "FRINK Charles": "frink-charles",
    "FRINKE David": "frinke-david",
    "FRISBY Terence": "frisby-terence",
    "FRISCH Max": "frisch-max",
    "FRISCH Peter": "frisch-peter",
    "FRISCH Robert": "frisch-robert",
    "FRISHBERG Dave": "frishberg-dave",
    "FRISINO-TOOHEY Rosemary": "frisino-toohey-rosemary",
    "FRITH Bob": "frith-bob",
    "FRITH Daniel": "frith-daniel",
    "FRITH Roger": "frith-roger",
    "FRITH Tim": "frith-tim",
    "FRITSCH Werner": "fritsch-werner",
    "FRITSCHER Jack": "fritscher-jack",
    "FRITTS Tamara": "fritts-tamara",
    "FRITZ James": "fritz-james",
    "FRITZ John": "fritz-john",
    "FRITZ Joni": "fritz-joni",
    "FRITZIUS Eric": "fritzius-eric",
    "FRITZLER Jim": "fritzler-jim",
    "FROBERG Kristin Anna": "froberg-kristin-anna",
    "FROCHARDE Pierre": "frocharde-pierre",
    "FROCKT Deborah Lynn": "frockt-deborah-lynn",
    "FROEHLING Simon": "froehling-simon",
    "FROELICH Anne": "froelich-anne",
    "FROHARDT Robin": "frohardt-robin",
    "FROHLICH Pea": "frohlich-pea",
    "FROIDEVAUX Guillaumarc": "froidevaux-guillaumarc",
    "FROLOV Diane": "frolov-diane",
    "FROM THE STREET THEATRE COMPANY ": "from-the-street-theatre-company",
    "FROMSTEIN Ron": "fromstein-ron",
    "FRONT Jeremy": "front-jeremy",
    "FRONT LAWN, THE ": "front-lawn",
    "FRONT ROW THEATRE GROUP ": "front-row-theatre-group",
    "FROST Christopher": "frost-christopher",
    "FROST Cy": "frost-cy",
    "FROST Danny": "frost-danny",
    "FROST Emma": "frost-emma",
    "FROST Gina T": "frost-gina-t",
    "FROST Helen": "frost-helen",
    "FROST James": "frost-james",
    "FROST Joseph": "frost-joseph",
    "FROST Rex": "frost-rex",
    "FROST Rich": "frost-rich",
    "FROST Richard": "frost-richard",
    "FROST Robert": "frost-robert",
    "FROST Sadie": "frost-sadie",
    "FROST Shari D": "frost-shari-d",
    "FROST Warren": "frost-warren",
    "FROSTICK David": "frostick-david",
    "FROTE Jason": "frote-jason",
    "FROW Gerald": "frow-gerald",
    "FROZEN CHARLOTTE ": "frozen-charlotte",
    "FROZEN LIGHT ": "frozen-light",
    "FRUCHTMAN Stephen Michael": "fruchtman-stephen-michael",
    "FRUET William": "fruet-william",
    "FRUGE Wesley": "fruge-wesley",
    "FRUMIN Sue": "frumin-sue",
    "FRUTKIN Jill": "frutkin-jill",
    "FRY Christopher": "fry-christopher",
    "FRY Garry": "fry-garry",
    "FRY Jack": "fry-jack",
    "FRY Katie": "fry-katie",
    "FRY Michael": "fry-michael",
    "FRY Ray": "fry-ray",
    "FRY Richard": "fry-richard",
    "FRY Stephen": "fry-stephen",
    "FRY William": "fry-william",
    "FRY JR Gary Raymond": "fry-jr-gary-raymond",
    "FRYE Andrew": "frye-andrew",
    "FRYE Joy Beresford": "frye-joy-beresford",
    "FRYE Peter": "frye-peter",
    "FRYE Tom": "frye-tom",
    "FRYER Nick": "fryer-nick"
  }
};