export default {
  "metadata": {
    "results": 99,
    "timeStamp": "2025-12-05T21:24:25.922Z",
    "url": "https://www.doollee.com/PlaywrightsF/F_playwrights_s-z.php"
  },
  "authors": {
    "FU Josh": "fu-josh",
    "FUCHS Barbara": "fuchs-barbara",
    "FUCHS Carolyn": "fuchs-carolyn",
    "FUCHS Elinor": "fuchs-elinor",
    "FUCHS Francis": "fuchs-francis",
    "FUCHS Howard": "fuchs-howard",
    "FUCHS Ira Hayes": "fuchs-ira-hayes",
    "FUCHS Kenneth": "fuchs-kenneth",
    "FUCHS Siegmund": "fuchs-siegmund",
    "FUCILLA Joseph G": "fucilla-joseph-g",
    "FUDGE Anthony": "fudge-anthony",
    "FUEMANA Dianna": "fuemana-dianna",
    "FUENTES Carlos": "fuentes-carlos",
    "FUENTES Elizabeth": "fuentes-elizabeth",
    "FUENTES Martha Ayers": "fuentes-martha-ayers",
    "FUENTES Pablo": "fuentes-pablo",
    "FUENTES Susana": "fuentes-susana",
    "FUERSTENBERG Anna": "fuerstenberg-anna",
    "FUGARD Athol": "fugard-athol",
    "FUGATE James": "fugate-james",
    "FUGELSANG John": "fugelsang-john",
    "FUHER Kent": "fuher-kent",
    "FUHRER Gil": "fuhrer-gil",
    "FUJIKAWA Cynthia Gates": "fujikawa-cynthia-gates",
    "FUJIMOTO Paul": "fujimoto-paul",
    "FULCO David": "fulco-david",
    "FULCO Richard": "fulco-richard",
    "FULFORD Geoff": "fulford-geoff",
    "FULFORD John": "fulford-john",
    "FULFORD Robin": "fulford-robin",
    "FULGHUM Robert": "fulghum-robert",
    "FULHAM Mary": "fulham-mary",
    "FULKERTON Vance": "fulkerton-vance",
    "FULKS Amanda": "fulks-amanda",
    "FULKS Kadence": "fulks-kadence",
    "FULL FRONTAL THEATRE ": "full-frontal-theatre",
    "FULLARTON Morag": "fullarton-morag",
    "FULLER Charles": "fuller-charles",
    "FULLER David": "fuller-david",
    "FULLER David Gillam": "fuller-david-gillam",
    "FULLER Dean": "fuller-dean",
    "FULLER Elizabeth": "fuller-elizabeth",
    "FULLER Emily": "fuller-emily",
    "FULLER Frat": "fuller-frat",
    "FULLER Frit": "fuller-frit",
    "FULLER James": "fuller-james",
    "FULLER John G": "fuller-john-g",
    "FULLER Julie": "fuller-julie",
    "FULLER Katherine": "fuller-katherine",
    "FULLER Lorenzo": "fuller-lorenzo",
    "FULLER Sarah": "fuller-sarah",
    "FULLER Ted": "fuller-ted",
    "FULLERTON Morag": "fullerton-morag",
    "FULTHORPE Douglas": "fulthorpe-douglas",
    "FULTON Andrea J": "fulton-andrea-j",
    "FULTON Heather": "fulton-heather",
    "FULTON J M": "fulton-j-m",
    "FULTON Rikki": "fulton-rikki",
    "FULTON Will": "fulton-will",
    "FUMMEY Bruce": "fummey-bruce",
    "FUNG Josef": "fung-josef",
    "FUNG Rocelia": "fung-rocelia",
    "FURA DELS BAUS ": "fura-dels-baus",
    "FURBER Douglas": "furber-douglas",
    "FUREY Cate": "furey-cate",
    "FURLANI Jason": "furlani-jason",
    "FURLETTI Andressa": "furletti-andressa",
    "FURLONG David": "furlong-david",
    "FURLONG Ingrid": "furlong-ingrid",
    "FURLONG Tony": "furlong-tony",
    "FURMAN Roger": "furman-roger",
    "FURNELL John": "furnell-john",
    "FURNESS Mark": "furness-mark",
    "FURNISS Darren A": "furniss-darren-a",
    "FURNIVAL Christine": "furnival-christine",
    "FURSE Anna": "furse-anna",
    "FURSE John": "furse-john",
    "FURST Gretchen Klinedinst": "furst-gretchen-klinedinst",
    "FURST Joshua": "furst-joshua",
    "FURST Steve": "furst-steve",
    "FURTH George": "furth-george",
    "FURUMOTO David": "furumoto-david",
    "FUSARO Darrell": "fusaro-darrell",
    "FUSCO Anthony": "fusco-anthony",
    "FUSCO Coco": "fusco-coco",
    "FUSCO Robin": "fusco-robin",
    "FUSE THEATRE ": "fuse-theatre",
    "FUSEK-PETERS Andrew": "fusek-peters-andrew",
    "FUTCHER Michael": "futcher-michael",
    "FUTTERMAN Enid": "futterman-enid",
    "FYFE Jim": "fyfe-jim",
    "FYFE Peter": "fyfe-peter",
    "FYFFE Laurie": "fyffe-laurie",
    "FYLAKTAKI Penny": "fylaktaki-penny",
    "FYLEMAN Rose": "fyleman-rose",
    "FYLES Franklin": "fyles-franklin",
    "FYNN-AIDUENU Tristan": "fynn-aiduenu-tristan",
    "FYSA THEATRE ": "fysa-theatre",
    "FYWELL Tim": "fywell-tim"
  }
};