export default {
  "metadata": {
    "results": 544,
    "timeStamp": "2025-12-05T21:24:39.636Z",
    "url": "https://www.doollee.com/PlaywrightsG/G_playwrights_g-l.php"
  },
  "authors": {
    "GHAJARRAHIMI Sanaz": "ghajarrahimi-sanaz",
    "GHANIZADEH Homayun": "ghanizadeh-homayun",
    "GHARAVI Lance": "gharavi-lance",
    "GHARORO-AKPOJOTOR Joy": "gharoro-akpojotor-joy",
    "GHAZALI Ahmed": "ghazali-ahmed",
    "GHAZNAVI Leila": "ghaznavi-leila",
    "GHAZOUL Rabab": "ghazoul-rabab",
    "GHEBREHARIAT Lwam": "ghebrehariat-lwam",
    "GHELANI Sheila": "ghelani-sheila",
    "GHELARDI Marco": "ghelardi-marco",
    "GHELDER Stephan De": "ghelder-stephan-de",
    "GHEON Henri": "gheon-henri",
    "GHIR Kulvinder": "ghir-kulvinder",
    "GHISALBERTI Mario": "ghisalberti-mario",
    "GHOREYEB Sue": "ghoreyeb-sue",
    "GHOSAL Mita": "ghosal-mita",
    "GHOSE Nandita": "ghose-nandita",
    "GIACIN Alex": "giacin-alex",
    "GIACINO Dennis": "giacino-dennis",
    "GIACINTO Fred": "giacinto-fred",
    "GIACOPASI Theresa": "giacopasi-theresa",
    "GIACOSA Giuseppe": "giacosa-giuseppe",
    "GIALANELLA Victor": "gialanella-victor",
    "GIAMATTI A Bartlett": "giamatti-a-bartlett",
    "GIAMBRA Joseph G": "giambra-joseph-g",
    "GIAMMETTA Carolina": "giammetta-carolina",
    "GIANAKAS-DALLAS Athena": "gianakas-dallas-athena",
    "GIANAKOS Michael": "gianakos-michael",
    "GIANCI Brian": "gianci-brian",
    "GIANNACHI Gabriella": "giannachi-gabriella",
    "GIANNOU Charalampos": "giannou-charalampos",
    "GIANNUNZIO Mitchell": "giannunzio-mitchell",
    "GIANTURCO Steven": "gianturco-steven",
    "GIANTVALLEY Scott": "giantvalley-scott",
    "GIARDINA Anthony": "giardina-anthony",
    "GIARDINA Joe": "giardina-joe",
    "GIARMO Chris": "giarmo-chris",
    "GIARNIERO Richard P": "giarniero-richard-p",
    "GIBB Andrea": "gibb-andrea",
    "GIBB Mike": "gibb-mike",
    "GIBB Monica": "gibb-monica",
    "GIBBENS Kate Sullivan": "gibbens-kate-sullivan",
    "GIBBINS Dan": "gibbins-dan",
    "GIBBON Lewis Grassic": "gibbon-lewis-grassic",
    "GIBBONS Eilleen": "gibbons-eilleen",
    "GIBBONS Frank": "gibbons-frank",
    "GIBBONS Katherine": "gibbons-katherine",
    "GIBBONS Rawle": "gibbons-rawle",
    "GIBBONS Reginald": "gibbons-reginald",
    "GIBBONS Thomas": "gibbons-thomas",
    "GIBBS Alexander": "gibbs-alexander",
    "GIBBS Ann L": "gibbs-ann-l",
    "GIBBS Chris": "gibbs-chris",
    "GIBBS Deborah": "gibbs-deborah",
    "GIBBS Donald B": "gibbs-donald-b",
    "GIBBS James": "gibbs-james",
    "GIBBS Jennifer": "gibbs-jennifer",
    "GIBBS Margaret": "gibbs-margaret",
    "GIBBS Paige": "gibbs-paige",
    "GIBBS Peter": "gibbs-peter",
    "GIBBS Robert J": "gibbs-robert-j",
    "GIBERGA Jane Sughrue": "giberga-jane-sughrue",
    "GIBNEY Paul": "gibney-paul",
    "GIBNEY Sheridan": "gibney-sheridan",
    "GIBRAN Kahlil": "gibran-kahlil",
    "GIBSON Alec": "gibson-alec",
    "GIBSON Barbara": "gibson-barbara",
    "GIBSON Bill": "gibson-bill",
    "GIBSON Carrie": "gibson-carrie",
    "GIBSON Chloe": "gibson-chloe",
    "GIBSON E": "gibson-e",
    "GIBSON Edwin Lee": "gibson-edwin-lee",
    "GIBSON Elizabeth": "gibson-elizabeth",
    "GIBSON Emma": "gibson-emma",
    "GIBSON Eren T": "gibson-eren-t",
    "GIBSON Florence": "gibson-florence",
    "GIBSON Harry": "gibson-harry",
    "GIBSON Hugh": "gibson-hugh",
    "GIBSON Izze": "gibson-izze",
    "GIBSON James": "gibson-james",
    "GIBSON James (1)": "gibson-james-1",
    "GIBSON Jim": "gibson-jim",
    "GIBSON Jo": "gibson-jo",
    "GIBSON Joan": "gibson-joan",
    "GIBSON John": "gibson-john",
    "GIBSON Justin": "gibson-justin",
    "GIBSON Kate Erin": "gibson-kate-erin",
    "GIBSON Katie": "gibson-katie",
    "GIBSON Lewis": "gibson-lewis",
    "GIBSON Mary Jane": "gibson-mary-jane",
    "GIBSON Meg": "gibson-meg",
    "GIBSON Melissa James": "gibson-melissa-james",
    "GIBSON Mira": "gibson-mira",
    "GIBSON P J": "gibson-p-j",
    "GIBSON Polly": "gibson-polly",
    "GIBSON Regina": "gibson-regina",
    "GIBSON Rod": "gibson-rod",
    "GIBSON Scott": "gibson-scott",
    "GIBSON Steve": "gibson-steve",
    "GIBSON William": "gibson-william",
    "GIDDINS K D": "giddins-k-d",
    "GIDDISH Kelli": "giddish-kelli",
    "GIDDY Horton": "giddy-horton",
    "GIDDY OX ": "giddy-ox",
    "GIDE Andre": "gide-andre",
    "GIDEON Killeon": "gideon-killeon",
    "GIDEON Llewella": "gideon-llewella",
    "GIDNEY James": "gidney-james",
    "GIEBEL Jean D": "giebel-jean-d",
    "GIEDRIS Nick": "giedris-nick",
    "GIEDROYC Mel": "giedroyc-mel",
    "GIELGUD John": "gielgud-john",
    "GIELGUD Val": "gielgud-val",
    "GIEN Pamela": "gien-pamela",
    "GIERING Jenny": "giering-jenny",
    "GIESCHEN Christopher": "gieschen-christopher",
    "GIESELMANN David": "gieselmann-david",
    "GIESSER Mark R": "giesser-mark-r",
    "GIFFIN Elisabeth": "giffin-elisabeth",
    "GIFFIN Helen": "giffin-helen",
    "GIFFORD Barry": "gifford-barry",
    "GIFFORD Kathie Lee": "gifford-kathie-lee",
    "GIFFORD Lane": "gifford-lane",
    "GIFFORD Mary-Anne": "gifford-mary-anne",
    "GIGGLE Debbie": "giggle-debbie",
    "GIL V V": "gil-v-v",
    "GILANELLA Victor": "gilanella-victor",
    "GILBANE Steve": "gilbane-steve",
    "GILBERT Craig": "gilbert-craig",
    "GILBERT Hy": "gilbert-hy",
    "GILBERT Ilsa": "gilbert-ilsa",
    "GILBERT James": "gilbert-james",
    "GILBERT Jenny": "gilbert-jenny",
    "GILBERT Jonathan Matthew": "gilbert-jonathan-matthew",
    "GILBERT Julie": "gilbert-julie",
    "GILBERT Justin": "gilbert-justin",
    "GILBERT Kate": "gilbert-kate",
    "GILBERT Kevin John": "gilbert-kevin-john",
    "GILBERT Louise": "gilbert-louise",
    "GILBERT Mara": "gilbert-mara",
    "GILBERT Michael": "gilbert-michael",
    "GILBERT Nick": "gilbert-nick",
    "GILBERT Paul": "gilbert-paul",
    "GILBERT Peter": "gilbert-peter",
    "GILBERT Robert": "gilbert-robert",
    "GILBERT Samuel": "gilbert-samuel",
    "GILBERT Seth": "gilbert-seth",
    "GILBERT Siobhan": "gilbert-siobhan",
    "GILBERT Sky": "gilbert-sky",
    "GILBERT Stuart": "gilbert-stuart",
    "GILBERT Valerie": "gilbert-valerie",
    "GILBERT W Stephen": "gilbert-w-stephen",
    "GILBERT Willie": "gilbert-willie",
    "GILBERTSON Onalea": "gilbertson-onalea",
    "GILBEY Alan": "gilbey-alan",
    "GILBEY Alex John": "gilbey-alex-john",
    "GILBEY Andrew": "gilbey-andrew",
    "GILBREATH Timothy": "gilbreath-timothy",
    "GILBROOK David": "gilbrook-david",
    "GILCHRIST Andrew": "gilchrist-andrew",
    "GILCHRIST Bruce": "gilchrist-bruce",
    "GILCHRIST Jane": "gilchrist-jane",
    "GILCHRIST Pete": "gilchrist-pete",
    "GILCHRIST Terence": "gilchrist-terence",
    "GILD David": "gild-david",
    "GILDAY Kevin P": "gilday-kevin-p",
    "GILDEA Kerry": "gildea-kerry",
    "GILDEA Kevin": "gildea-kevin",
    "GILENO Jason": "gileno-jason",
    "GILES Alex": "giles-alex",
    "GILES C R": "giles-c-r",
    "GILES Charlotte": "giles-charlotte",
    "GILES Dan": "giles-dan",
    "GILES David": "giles-david",
    "GILES Harry": "giles-harry",
    "GILES Mike": "giles-mike",
    "GILES Nancy": "giles-nancy",
    "GILES Stephen": "giles-stephen",
    "GILET Ivan": "gilet-ivan",
    "GILFEDDER Eugene": "gilfedder-eugene",
    "GILFOND Henry": "gilfond-henry",
    "GILFORD C B": "gilford-c-b",
    "GILFORD Joe": "gilford-joe",
    "GILGER Paul": "gilger-paul",
    "GILHANEY Evelyn": "gilhaney-evelyn",
    "GILHOOLEY Jack": "gilhooley-jack",
    "GILHOULEY James": "gilhouley-james",
    "GILKER Alexa": "gilker-alexa",
    "GILKISON Jason": "gilkison-jason",
    "GILKYSON Terry": "gilkyson-terry",
    "GILL Alan W": "gill-alan-w",
    "GILL Anton": "gill-anton",
    "GILL Billy": "gill-billy",
    "GILL Bob": "gill-bob",
    "GILL Ehsan": "gill-ehsan",
    "GILL Fionn": "gill-fionn",
    "GILL Kate": "gill-kate",
    "GILL Maximillian Singh": "gill-maximillian-singh",
    "GILL Nick": "gill-nick",
    "GILL Peter": "gill-peter",
    "GILL Richard": "gill-richard",
    "GILL Rod": "gill-rod",
    "GILL Sean": "gill-sean",
    "GILL Suzy": "gill-suzy",
    "GILL William": "gill-william",
    "GILLAM Cliff": "gillam-cliff",
    "GILLAM-SMITH James": "gillam-smith-james",
    "GILLAN Dan": "gillan-dan",
    "GILLARD-BENTLEY Paddy": "gillard-bentley-paddy",
    "GILLARD-RANDOLPH Evern": "gillard-randolph-evern",
    "GILLEAN CULLAIG COMPANY ": "gillean-cullaig-company",
    "GILLELAND Beth": "gilleland-beth",
    "GILLEN Curtis": "gillen-curtis",
    "GILLEN Leon": "gillen-leon",
    "GILLER Kyle": "giller-kyle",
    "GILLES D B": "gilles-d-b",
    "GILLESE Kevin": "gillese-kevin",
    "GILLESPIE Adelma": "gillespie-adelma",
    "GILLESPIE Ann": "gillespie-ann",
    "GILLESPIE David": "gillespie-david",
    "GILLESPIE Gerald": "gillespie-gerald",
    "GILLESPIE Lucy": "gillespie-lucy",
    "GILLESPIE Robert": "gillespie-robert",
    "GILLESPIE Tom": "gillespie-tom",
    "GILLET Catherine": "gillet-catherine",
    "GILLETT Jeremy": "gillett-jeremy",
    "GILLETT Michael": "gillett-michael",
    "GILLETT Rodney": "gillett-rodney",
    "GILLETTE Gene": "gillette-gene",
    "GILLETTE Scott Halvorsen": "gillette-scott-halvorsen",
    "GILLETTE William": "gillette-william",
    "GILLHAM Geoff": "gillham-geoff",
    "GILLHOULEY James": "gillhouley-james",
    "GILLHOULEY James D": "gillhouley-james-d",
    "GILLIAM Carolyn": "gilliam-carolyn",
    "GILLIAM Michele": "gilliam-michele",
    "GILLIAM Ryan": "gilliam-ryan",
    "GILLIAM Theodore E": "gilliam-theodore-e",
    "GILLIAT Jack": "gilliat-jack",
    "GILLIATT Penelope": "gilliatt-penelope",
    "GILLICK Kate": "gillick-kate",
    "GILLIE Iain": "gillie-iain",
    "GILLIES Andrea": "gillies-andrea",
    "GILLIES Cliff": "gillies-cliff",
    "GILLIES David": "gillies-david",
    "GILLIES Hamish": "gillies-hamish",
    "GILLIES Jade": "gillies-jade",
    "GILLIES Max": "gillies-max",
    "GILLIS Andrew": "gillis-andrew",
    "GILLIS Andy": "gillis-andy",
    "GILLIS Caroline": "gillis-caroline",
    "GILLIS Graeme": "gillis-graeme",
    "GILLIS Jonathan": "gillis-jonathan",
    "GILLIS Pennie": "gillis-pennie",
    "GILLIS Verna": "gillis-verna",
    "GILLMAN J": "gillman-j",
    "GILLMOR Teri": "gillmor-teri",
    "GILLNER Robert": "gillner-robert",
    "GILLON Shelley Herman": "gillon-shelley-herman",
    "GILMAN Charlotte Perkins": "gilman-charlotte-perkins",
    "GILMAN Rebecca": "gilman-rebecca",
    "GILMAN Stuart": "gilman-stuart",
    "GILMARTIN Michael": "gilmartin-michael",
    "GILMER Sigrid": "gilmer-sigrid",
    "GILMOR Teri": "gilmor-teri",
    "GILMORE Christopher": "gilmore-christopher",
    "GILMORE Helen": "gilmore-helen",
    "GILMORE Kate": "gilmore-kate",
    "GILMORE Natasha": "gilmore-natasha",
    "GILMORE William": "gilmore-william",
    "GILMORGAN E D": "gilmorgan-e-d",
    "GILMOUR Adam": "gilmour-adam",
    "GILMOUR Alan": "gilmour-alan",
    "GILMOUR John C": "gilmour-john-c",
    "GILMOUR L": "gilmour-l",
    "GILMOUR Scott": "gilmour-scott",
    "GILMOUR Steve": "gilmour-steve",
    "GILMOUR Suzy": "gilmour-suzy",
    "GILNA David": "gilna-david",
    "GIL-ORRIOS Angel": "gil-orrios-angel",
    "GILOT Emmanuel": "gilot-emmanuel",
    "GILOVICH Paula": "gilovich-paula",
    "GILPIN James": "gilpin-james",
    "GILRAY Bruce W": "gilray-bruce-w",
    "GILROY Frank D": "gilroy-frank-d",
    "GILROY Laureen G": "gilroy-laureen-g",
    "GILROY Mary Ellen T": "gilroy-mary-ellen-t",
    "GILROY Steve": "gilroy-steve",
    "GILROY Tom": "gilroy-tom",
    "GILROY-SINCLAIR Michael M": "gilroy-sinclair-michael-m",
    "GILSENAN Alan": "gilsenan-alan",
    "GILSENAN Nancy": "gilsenan-nancy",
    "GIL-SHERIDAN Peter": "gil-sheridan-peter",
    "GILSTRAP Barbara": "gilstrap-barbara",
    "GILTINAN Donal": "giltinan-donal",
    "GILVIN Tim": "gilvin-tim",
    "GIMBALL Norman": "gimball-norman",
    "GIMBLETT Matt": "gimblett-matt",
    "GIN Steve": "gin-steve",
    "GINDICK Mark": "gindick-mark",
    "GINDRO Sandro": "gindro-sandro",
    "GINGRICH Chris": "gingrich-chris",
    "GINGRICH-JONES Rebecca": "gingrich-jones-rebecca",
    "GINIVAN Garry": "ginivan-garry",
    "GINK Daniil": "gink-daniil",
    "GINKAS Kama": "ginkas-kama",
    "GINMAN John": "ginman-john",
    "GINN David": "ginn-david",
    "GINNES Abram S": "ginnes-abram-s",
    "GINRAS Robbie": "ginras-robbie",
    "GINSBERG Aaron": "ginsberg-aaron",
    "GINSBERG Allen": "ginsberg-allen",
    "GINSBERG Howard": "ginsberg-howard",
    "GINSBERG Jeremiah": "ginsberg-jeremiah",
    "GINSBERG Ned": "ginsberg-ned",
    "GINSBERG Wendy": "ginsberg-wendy",
    "GINSBURG Aaron": "ginsburg-aaron",
    "GINSBURG Joshua Steven": "ginsburg-joshua-steven",
    "GINSBURG Mirra": "ginsburg-mirra",
    "GINSBURG Ned Paul": "ginsburg-ned-paul",
    "GINSBURG Randy": "ginsburg-randy",
    "GINSBURY Norman": "ginsbury-norman",
    "GINTERS Laura": "ginters-laura",
    "GINTY E B": "ginty-e-b",
    "GINZBURG Natalia": "ginzburg-natalia",
    "GIODANO Anthony": "giodano-anthony",
    "GIOFFRE Marissa": "gioffre-marissa",
    "GIOMBETTI Karen Pauline": "giombetti-karen-pauline",
    "GIONFRIDDO Gina": "gionfriddo-gina",
    "GIORDANO Angie": "giordano-angie",
    "GIORDANO Anthony": "giordano-anthony",
    "GIORDANO Elisa": "giordano-elisa",
    "GIORDANO Lisa": "giordano-lisa",
    "GIORDANO Mark": "giordano-mark",
    "GIORDANO Monica": "giordano-monica",
    "GIORDANO Tony": "giordano-tony",
    "GIORDANO Tyrone": "giordano-tyrone",
    "GIORGIO Anthony": "giorgio-anthony",
    "GIOVANNANGELI Monia": "giovannangeli-monia",
    "GIOVANNETTI Gary": "giovannetti-gary",
    "GIOVANNI Greg": "giovanni-greg",
    "GIOVANNI Paul": "giovanni-paul",
    "GIOVANNONI Dan": "giovannoni-dan",
    "GIPE George": "gipe-george",
    "GIPPIUS Zinadia": "gippius-zinadia",
    "GIPSON Keelay": "gipson-keelay",
    "GIRARD David": "girard-david",
    "GIRARD Deirdre": "girard-deirdre",
    "GIRARD Michael Paul": "girard-michael-paul",
    "GIRARDEAU Janet": "girardeau-janet",
    "GIRASUOLO Stephen": "girasuolo-stephen",
    "GIRAUDOUX Jean": "giraudoux-jean",
    "GIRBEA Horia": "girbea-horia",
    "GIRDLER Martha": "girdler-martha",
    "GIRE Tom": "gire-tom",
    "GIRION Gilbert": "girion-gilbert",
    "GIRLING Jackie": "girling-jackie",
    "GIROD Allan": "girod-allan",
    "GIROD Kelley Nicole": "girod-kelley-nicole",
    "GIRON Arthur": "giron-arthur",
    "GIRON-TOWERS Thomas": "giron-towers-thomas",
    "GIROUND Kelley": "giround-kelley",
    "GIROUX Ben": "giroux-ben",
    "GIRRBACH Tim": "girrbach-tim",
    "GIRTEN Mierka": "girten-mierka",
    "GIRTS Michael": "girts-michael",
    "GISBY Paul": "gisby-paul",
    "GISBY Tomas": "gisby-tomas",
    "GISH Zurbon": "gish-zurbon",
    "GISMONDI Rebecca": "gismondi-rebecca",
    "GIST Anglea": "gist-anglea",
    "GITLITZ David": "gitlitz-david",
    "GITTENS-JONES Cheryl": "gittens-jones-cheryl",
    "GITTLEMAN Jill": "gittleman-jill",
    "GIUFFRE Joe": "giuffre-joe",
    "GIUGNI A M": "giugni-a-m",
    "GIULIANO Linda": "giuliano-linda",
    "GIUNTA Anthony": "giunta-anthony",
    "GIUSTI Justin": "giusti-justin",
    "GIUSTO Michelle": "giusto-michelle",
    "GIVE IT A NAME ": "give-it-a-name",
    "GIVENS Bettye H": "givens-bettye-h",
    "GIVENS Daniel": "givens-daniel",
    "GJELTEN Elizabeth": "gjelten-elizabeth",
    "GJERLOW Frode": "gjerlow-frode",
    "GLADDEN Frank": "gladden-frank",
    "GLADILIN Pyotr": "gladilin-pyotr",
    "GLADSTONE Amiel": "gladstone-amiel",
    "GLADSTONE Jeff": "gladstone-jeff",
    "GLADSTONE Ryan": "gladstone-ryan",
    "GLADU April-Dawn": "gladu-april-dawn",
    "GLADWELL F E": "gladwell-f-e",
    "GLADWIN Bruce": "gladwin-bruce",
    "GLADWIN Philip": "gladwin-philip",
    "GLAISTER Kel": "glaister-kel",
    "GLAISTER Larry": "glaister-larry",
    "GLANCE Vivienne": "glance-vivienne",
    "GLANCY Diane": "glancy-diane",
    "GLANCY Sara": "glancy-sara",
    "GLANCY-O'SHEA Marie": "glancy-o-shea-marie",
    "GLANDER Scott": "glander-scott",
    "GLANDFIELD Lou": "glandfield-lou",
    "GLANFIELD Ben": "glanfield-ben",
    "GLANVILLE Brian": "glanville-brian",
    "GLANVILLE Maxwell": "glanville-maxwell",
    "GLANVILLE Peter": "glanville-peter",
    "GLANVILLE Roderick": "glanville-roderick",
    "GLANZ Maria": "glanz-maria",
    "GLAS(S) PERFORMANCE ": "glass-performance",
    "GLASCO Gordon": "glasco-gordon",
    "GLASER E D": "glaser-e-d",
    "GLASER Sherry": "glaser-sherry",
    "GLASGOW Alex": "glasgow-alex",
    "GLASGOW Andrew": "glasgow-andrew",
    "GLASGOW Tian": "glasgow-tian",
    "GLASHEEN Anne-Marie": "glasheen-anne-marie",
    "GLASIER Ned": "glasier-ned",
    "GLASNER Anne": "glasner-anne",
    "GLASPELL Susan": "glaspell-susan",
    "GLASS Alan": "glass-alan",
    "GLASS D": "glass-d",
    "GLASS David": "glass-david",
    "GLASS Dimitri": "glass-dimitri",
    "GLASS Dudley": "glass-dudley",
    "GLASS Ewen": "glass-ewen",
    "GLASS Guy Fredrick": "glass-guy-fredrick",
    "GLASS Harry": "glass-harry",
    "GLASS Joanna Mcclelland": "glass-joanna-mcclelland",
    "GLASS John": "glass-john",
    "GLASS Kat": "glass-kat",
    "GLASS Keith": "glass-keith",
    "GLASS Ken": "glass-ken",
    "GLASS Philip": "glass-philip",
    "GLASS Ryan": "glass-ryan",
    "GLASS Simon": "glass-simon",
    "GLASS Stephanie": "glass-stephanie",
    "GLASS Suzanne": "glass-suzanne",
    "GLASS Victoria": "glass-victoria",
    "GLASSBERG Roy": "glassberg-roy",
    "GLASSBORROW Philip": "glassborrow-philip",
    "GLASSCO Bill": "glassco-bill",
    "GLASSCOE Louise": "glasscoe-louise",
    "GLASSMAN Seth": "glassman-seth",
    "GLASSMAN Sharon Lee": "glassman-sharon-lee",
    "GLASSMAN Stephen": "glassman-stephen",
    "GLASSTONE Ben": "glasstone-ben",
    "GLATTHORN Dylan James": "glatthorn-dylan-james",
    "GLAUDINI Bob": "glaudini-bob",
    "GLAUDON Barbara": "glaudon-barbara",
    "GLAVIN Helen": "glavin-helen",
    "GLAWSON Ben": "glawson-ben",
    "GLAZ Matt": "glaz-matt",
    "GLAZENER Mary U": "glazener-mary-u",
    "GLAZER Peter": "glazer-peter",
    "GLAZER Tony": "glazer-tony",
    "GLAZIER Eli": "glazier-eli",
    "GLEADOW Rupert": "gleadow-rupert",
    "GLEASON James": "gleason-james",
    "GLEASON James (2)": "gleason-james-2",
    "GLEASON Katherine": "gleason-katherine",
    "GLEASON Mary Pat": "gleason-mary-pat",
    "GLEASON William": "gleason-william",
    "GLEAVES Richard": "gleaves-richard",
    "GLEE CLUB ": "glee-club",
    "GLEESON Brendan": "gleeson-brendan",
    "GLEESON Ger": "gleeson-ger",
    "GLEESON Niamh": "gleeson-niamh",
    "GLEESON Veronica": "gleeson-veronica",
    "GLEESON Victoria": "gleeson-victoria",
    "GLENAAN Kenneth": "glenaan-kenneth",
    "GLENDINNING Robin": "glendinning-robin",
    "GLENFIELD Mary": "glenfield-mary",
    "GLENN Daniel": "glenn-daniel",
    "GLENN Don Wilson": "glenn-don-wilson",
    "GLENN Erica": "glenn-erica",
    "GLENN Max Daniel": "glenn-max-daniel",
    "GLENN Robert": "glenn-robert",
    "GLENN Sean": "glenn-sean",
    "GLENN Sharlee": "glenn-sharlee",
    "GLENNON John": "glennon-john",
    "GLENNON William": "glennon-william",
    "GLENNVILLE John": "glennville-john",
    "GLENNY Michael": "glenny-michael",
    "GLENVILLE Peter": "glenville-peter",
    "GLEW J": "glew-j",
    "GLEZ Mar Gomez": "glez-mar-gomez",
    "GLICK Jesse T": "glick-jesse-t",
    "GLICK Liat": "glick-liat",
    "GLICK Michelle": "glick-michelle",
    "GLICK Natalie": "glick-natalie",
    "GLICK Stefanie": "glick-stefanie",
    "GLICKFELD Carole": "glickfeld-carole",
    "GLICKMAN Norah": "glickman-norah",
    "GLICKMAN Stephanie": "glickman-stephanie",
    "GLICKMAN Will": "glickman-will",
    "GLICKSTEIN Avi": "glickstein-avi",
    "GLICKSTEIN Sari Caine": "glickstein-sari-caine",
    "GLIDDEN Russ": "glidden-russ",
    "GLIDEWELL Brian": "glidewell-brian",
    "GLIKEN Vicki": "gliken-vicki",
    "GLINES John": "glines-john",
    "GLINKSKI Tim": "glinkski-tim",
    "GLINSKI Marek": "glinski-marek",
    "GLISOVIC Smiljana": "glisovic-smiljana",
    "GLOR Gordon": "glor-gordon",
    "GLORE John": "glore-john",
    "GLORE Ricky": "glore-ricky",
    "GLORIA THEATRE COMPANY ": "gloria-theatre-company",
    "GLOSSMAN James": "glossman-james",
    "GLOSSMAN Nicky": "glossman-nicky",
    "GLOSSOP Karen": "glossop-karen",
    "GLOUCHEVITCH John": "glouchevitch-john",
    "GLOUDEN Barbara": "glouden-barbara",
    "GLOVER Alex": "glover-alex",
    "GLOVER Chanel": "glover-chanel",
    "GLOVER Daniel": "glover-daniel",
    "GLOVER Dawn": "glover-dawn",
    "GLOVER Evelyn": "glover-evelyn",
    "GLOVER Frederic": "glover-frederic",
    "GLOVER Gavin": "glover-gavin",
    "GLOVER Greg": "glover-greg",
    "GLOVER Jessica E": "glover-jessica-e",
    "GLOVER Julian": "glover-julian",
    "GLOVER Justine": "glover-justine",
    "GLOVER Kate": "glover-kate",
    "GLOVER Katherine": "glover-katherine",
    "GLOVER Keith": "glover-keith",
    "GLOVER Mark": "glover-mark",
    "GLOVER Richard": "glover-richard",
    "GLOVER Rob": "glover-rob",
    "GLOVER Sue": "glover-sue",
    "GLOVER Tom": "glover-tom",
    "GLOWACKA Zuza": "glowacka-zuza",
    "GLOWACKI Janusz": "glowacki-janusz",
    "GLTNKSKI Tim": "gltnkski-tim",
    "GLUCK Johannes": "gluck-johannes",
    "GLUCK Victor": "gluck-victor",
    "GLUCKSMAN Cynthia": "glucksman-cynthia",
    "GLUCKSMAN Ron": "glucksman-ron",
    "GLUTH William": "gluth-william",
    "GLUZMAN Yelena": "gluzman-yelena",
    "GLYN Gwyneth": "glyn-gwyneth",
    "GLYN-JONES Erica": "glyn-jones-erica",
    "GLYNN Martin": "glynn-martin"
  }
};