export default {
  "metadata": {
    "results": 1592,
    "timeStamp": "2025-12-05T21:25:01.615Z",
    "url": "https://www.doollee.com/PlaywrightsG/G_playwrights_m-r.php"
  },
  "authors": {
    "GNATOWSKI Philana": "gnatowski-philana",
    "GNIMBLEY THE GNOME ": "gnimbley-the-gnome",
    "GNISCI Jennifer": "gnisci-jennifer",
    "GNOME Shirley": "gnome-shirley",
    "GOALEN Helen": "goalen-helen",
    "GOAN Katie": "goan-katie",
    "GOAN Roise": "goan-roise",
    "GOAT ISLAND ": "goat-island",
    "GOATLEY Cynthia": "goatley-cynthia",
    "GOATZE Paul": "goatze-paul",
    "GOB SQUAD ": "gob-squad",
    "GOBIOFF Neil": "gobioff-neil",
    "GODA Billy": "goda-billy",
    "GODBER John": "godber-john",
    "GODBOLD Darren": "godbold-darren",
    "GODCHAUX Stephen": "godchaux-stephen",
    "GODDARD Andrew": "goddard-andrew",
    "GODDARD Antonia": "goddard-antonia",
    "GODDARD David": "goddard-david",
    "GODDARD Janet": "goddard-janet",
    "GODDARD Kate": "goddard-kate",
    "GODDARD Paul": "goddard-paul",
    "GODDARD Robin": "goddard-robin",
    "GODDARD Sandra": "goddard-sandra",
    "GODDEN Ezra": "godden-ezra",
    "GODDEN Salena": "godden-salena",
    "GODDESS Rha": "goddess-rha",
    "GODE Alexander": "gode-alexander",
    "GODFREE William": "godfree-william",
    "GODFREY Adam": "godfrey-adam",
    "GODFREY Amber": "godfrey-amber",
    "GODFREY Beth": "godfrey-beth",
    "GODFREY Joe": "godfrey-joe",
    "GODFREY John": "godfrey-john",
    "GODFREY Milton": "godfrey-milton",
    "GODFREY Paul": "godfrey-paul",
    "GODFREY Peter": "godfrey-peter",
    "GODFREY Philip": "godfrey-philip",
    "GODFREY Traci": "godfrey-traci",
    "GODFREY ": "godfrey-",
    "GODLEY Janey": "godley-janey",
    "GODLEY Joe Andrew": "godley-joe-andrew",
    "GODLEY Simon": "godley-simon",
    "GODWIN Christopher": "godwin-christopher",
    "GODWIN James": "godwin-james",
    "GODWIN Peter": "godwin-peter",
    "GODWIN Randall": "godwin-randall",
    "GODZIEK Simon": "godziek-simon",
    "GOEBBELS Heiner": "goebbels-heiner",
    "GOEBEL Alex": "goebel-alex",
    "GOENCZ Arpad": "goencz-arpad",
    "GOERING Reinhard": "goering-reinhard",
    "GOES Marta": "goes-marta",
    "GOETHE Johann Wolfgang Von": "goethe",
    "GOETZ Augustus": "goetz-augustus",
    "GOETZ Kari": "goetz-kari",
    "GOETZ Rainald": "goetz-rainald",
    "GOETZ Ruth": "goetz-ruth",
    "GOETZEE Paul": "goetzee-paul",
    "GOETZ-STANKIEWICZ Marketa": "goetz-stankiewicz-marketa",
    "GOFF Mark": "goff-mark",
    "GOFF Sandi": "goff-sandi",
    "GOFF Sheila": "goff-sheila",
    "GOFFMAN Andrew": "goffman-andrew",
    "GOFORTH Frances": "goforth-frances",
    "GOFORTH Molly": "goforth-molly",
    "GOGERTY Megan": "gogerty-megan",
    "GOGGIN Dan": "goggin-dan",
    "GOGLIORMELLA Vincent": "gogliormella-vincent",
    "GOGOL Nikolai": "gogol-nikolai",
    "GOH Davina": "goh-davina",
    "GOHEEN Doug": "goheen-doug",
    "GOHEEN Marcella": "goheen-marcella",
    "GOHEI III Namiki": "gohei-iii-namiki",
    "GOIDEL Emma": "goidel-emma",
    "GOKHALE Shanta": "gokhale-shanta",
    "GOKHALE Vedant": "gokhale-vedant",
    "GOLABEK Mona": "golabek-mona",
    "GOLAMCO Michael": "golamco-michael",
    "GOLAN Liel": "golan-liel",
    "GOLASZEWSKI Stefan": "golaszewski-stefan",
    "GOLD Barry": "gold-barry",
    "GOLD Caroline": "gold-caroline",
    "GOLD Dave": "gold-dave",
    "GOLD Edward Louis": "gold-edward-louis",
    "GOLD Franklin": "gold-franklin",
    "GOLD Gaby": "gold-gaby",
    "GOLD Gina": "gold-gina",
    "GOLD Heather": "gold-heather",
    "GOLD Irving": "gold-irving",
    "GOLD J Burton": "gold-j-burton",
    "GOLD Jeffrey": "gold-jeffrey",
    "GOLD Joshua": "gold-joshua",
    "GOLD Judy": "gold-judy",
    "GOLD Lara": "gold-lara",
    "GOLD Leslie B": "gold-leslie-b",
    "GOLD Lloyd": "gold-lloyd",
    "GOLD Lucky": "gold-lucky",
    "GOLD Marthe Rachel": "gold-marthe-rachel",
    "GOLD Murray": "gold-murray",
    "GOLD Nanou Blair": "gold-nanou-blair",
    "GOLD Penny": "gold-penny",
    "GOLD Steve": "gold-steve",
    "GOLD Vera": "gold-vera",
    "GOLDBERG Alex": "goldberg-alex",
    "GOLDBERG Allison": "goldberg-allison",
    "GOLDBERG Alvin H": "goldberg-alvin-h",
    "GOLDBERG Andy": "goldberg-andy",
    "GOLDBERG Deborah": "goldberg-deborah",
    "GOLDBERG Dick": "goldberg-dick",
    "GOLDBERG Geoffrey": "goldberg-geoffrey",
    "GOLDBERG Isaac": "goldberg-isaac",
    "GOLDBERG Janice": "goldberg-janice",
    "GOLDBERG Jason Aaron": "goldberg-jason-aaron",
    "GOLDBERG Jesse": "goldberg-jesse",
    "GOLDBERG Jessica": "goldberg-jessica",
    "GOLDBERG Jonathan": "goldberg-jonathan",
    "GOLDBERG Lawrence": "goldberg-lawrence",
    "GOLDBERG Moses": "goldberg-moses",
    "GOLDBERG Sidney": "goldberg-sidney",
    "GOLDBERG Tanya": "goldberg-tanya",
    "GOLDBERG Will": "goldberg-will",
    "GOLDBY Derek": "goldby-derek",
    "GOLDEMBERG Rose Leiman": "goldemberg-rose-leiman",
    "GOLDEN Alfred L": "golden-alfred-l",
    "GOLDEN Amy": "golden-amy",
    "GOLDEN Brian": "golden-brian",
    "GOLDEN Grant": "golden-grant",
    "GOLDEN Holly": "golden-holly",
    "GOLDEN Iseult": "golden-iseult",
    "GOLDEN Mario": "golden-mario",
    "GOLDEN Maxwell": "golden-maxwell",
    "GOLDENBERG Jane": "goldenberg-jane",
    "GOLDENBERG William": "goldenberg-william",
    "GOLDENTHAL Jolene": "goldenthal-jolene",
    "GOLDER Herbert": "golder-herbert",
    "GOLDER Michael": "golder-michael",
    "GOLDER Michelle": "golder-michelle",
    "GOLDFADEN Avrom": "goldfaden-avrom",
    "GOLDFADER Laura": "goldfader-laura",
    "GOLDFARB Daniel": "goldfarb-daniel",
    "GOLDFARB Ed": "goldfarb-ed",
    "GOLDFARB Michael": "goldfarb-michael",
    "GOLDFARB Sidney": "goldfarb-sidney",
    "GOLDFIN Robin": "goldfin-robin",
    "GOLDFINGER Jacqueline": "goldfinger-jacqueline",
    "GOLDFLAM Arnost": "goldflam-arnost",
    "GOLDHABER Michaela Shally": "goldhaber-michaela-shally",
    "GOLDHAGEN Julian": "goldhagen-julian",
    "GOLDIE Kathleen A": "goldie-kathleen-a",
    "GOLDIE Kathryn": "goldie-kathryn",
    "GOLDIE W J": "goldie-w-j",
    "GOLDIN Nan": "goldin-nan",
    "GOLDINA Miriam": "goldina-miriam",
    "GOLDING Amy": "golding-amy",
    "GOLDING Dominic Hong Duc": "golding-dominic-hong-duc",
    "GOLDING James": "golding-james",
    "GOLDING Joanna": "golding-joanna",
    "GOLDING Kathryn": "golding-kathryn",
    "GOLDING Sarah": "golding-sarah",
    "GOLDING William": "golding-william",
    "GOLDMAN A E O": "goldman-a-e-o",
    "GOLDMAN Aaron": "goldman-aaron",
    "GOLDMAN Andrea": "goldman-andrea",
    "GOLDMAN Andrew": "goldman-andrew",
    "GOLDMAN Barbara": "goldman-barbara",
    "GOLDMAN Daniel": "goldman-daniel",
    "GOLDMAN Derek": "goldman-derek",
    "GOLDMAN Donald": "goldman-donald",
    "GOLDMAN Jake": "goldman-jake",
    "GOLDMAN James": "goldman-james",
    "GOLDMAN Lee": "goldman-lee",
    "GOLDMAN Leo": "goldman-leo",
    "GOLDMAN Lisa": "goldman-lisa",
    "GOLDMAN Liz": "goldman-liz",
    "GOLDMAN Marianne": "goldman-marianne",
    "GOLDMAN Matt": "goldman-matt",
    "GOLDMAN Michael": "goldman-michael",
    "GOLDMAN Peter": "goldman-peter",
    "GOLDMAN Robert": "goldman-robert",
    "GOLDMAN William": "goldman-william",
    "GOLDMAN-MACLACHLAN Aaron": "goldman-maclachlan-aaron",
    "GOLDNER Sharon": "goldner-sharon",
    "GOLDONI Carlo": "goldoni-carlo",
    "GOLDRICH Zina": "goldrich-zina",
    "GOLDRING Steve": "goldring-steve",
    "GOLDSACK Pete": "goldsack-pete",
    "GOLDSBY Angela": "goldsby-angela",
    "GOLDSBY Derek": "goldsby-derek",
    "GOLDSBY Matthew": "goldsby-matthew",
    "GOLDSBY Robert": "goldsby-robert",
    "GOLDSMAN Samuel": "goldsman-samuel",
    "GOLDSMITH Benjamin Bond": "goldsmith-benjamin-bond",
    "GOLDSMITH Bruce": "goldsmith-bruce",
    "GOLDSMITH Clifford": "goldsmith-clifford",
    "GOLDSMITH David": "goldsmith-david",
    "GOLDSMITH Gloria": "goldsmith-gloria",
    "GOLDSMITH John": "goldsmith-john",
    "GOLDSMITH Lee": "goldsmith-lee",
    "GOLDSMITH Marc": "goldsmith-marc",
    "GOLDSMITH Oliver": "goldsmith-oliver",
    "GOLDSMITH Pauline": "goldsmith-pauline",
    "GOLDSMITH Richard": "goldsmith-richard",
    "GOLDSMITH Roger": "goldsmith-roger",
    "GOLDSMITH Rosalind": "goldsmith-rosalind",
    "GOLDSMITH Sally": "goldsmith-sally",
    "GOLDSMITH Sophie L": "goldsmith-sophie-l",
    "GOLDSMITH Vernon": "goldsmith-vernon",
    "GOLDSTEIN Aliza": "goldstein-aliza",
    "GOLDSTEIN Ann": "goldstein-ann",
    "GOLDSTEIN Ben": "goldstein-ben",
    "GOLDSTEIN Carrie": "goldstein-carrie",
    "GOLDSTEIN Cathrine": "goldstein-cathrine",
    "GOLDSTEIN Dana Leslie": "goldstein-dana-leslie",
    "GOLDSTEIN Daniel": "goldstein-daniel",
    "GOLDSTEIN David": "goldstein-david",
    "GOLDSTEIN Gary": "goldstein-gary",
    "GOLDSTEIN Grant": "goldstein-grant",
    "GOLDSTEIN Jason": "goldstein-jason",
    "GOLDSTEIN Jeremy": "goldstein-jeremy",
    "GOLDSTEIN Jerold": "goldstein-jerold",
    "GOLDSTEIN Jonathan Marc": "goldstein-jonathan-marc",
    "GOLDSTEIN Joshua": "goldstein-joshua",
    "GOLDSTEIN Kenneth": "goldstein-kenneth",
    "GOLDSTEIN Kit": "goldstein-kit",
    "GOLDSTEIN Lionel": "goldstein-lionel",
    "GOLDSTEIN Michael": "goldstein-michael",
    "GOLDSTEIN Michael (1)": "goldstein-michael-1",
    "GOLDSTEIN Myrna": "goldstein-myrna",
    "GOLDSTEIN Shelly": "goldstein-shelly",
    "GOLDSTEIN Tara": "goldstein-tara",
    "GOLDSTEINN Bob": "goldsteinn-bob",
    "GOLDSTICK Oliver": "goldstick-oliver",
    "GOLDSTONE Bruce": "goldstone-bruce",
    "GOLDSTONE Jean Stock": "goldstone-jean-stock",
    "GOLDSTONE Patricia": "goldstone-patricia",
    "GOLDSWORTHY Fred": "goldsworthy-fred",
    "GOLDSWORTHY Peter": "goldsworthy-peter",
    "GOLDTHORP Mark": "goldthorp-mark",
    "GOLDTHORPE David": "goldthorpe-david",
    "GOLDWASSER Robin": "goldwasser-robin",
    "GOLDWYN Helen": "goldwyn-helen",
    "GOLDYN David": "goldyn-david",
    "GOLIGHTLY Max C": "golightly-max-c",
    "GOLIGHTLY Peter": "golightly-peter",
    "GOLL Ivan": "goll-ivan",
    "GOLLADAY Nancy": "golladay-nancy",
    "GOLUB Alan Jay": "golub-alan-jay",
    "GOLUBOFF Bryan": "goluboff-bryan",
    "GOLUBOV Mila": "golubov-mila",
    "GOLVAN Colin": "golvan-colin",
    "GOMBAR Dodo (Jozef)": "gombar-dodo",
    "GOMBEENS THETRE COMPANY ": "gombeens-thetre-company",
    "GOMBROWICZ Witold": "gombrowicz-witold",
    "GOMER Barry Sebastian": "gomer-barry-sebastian",
    "GOMES Carlos": "gomes-carlos",
    "GOMES Crystal": "gomes-crystal",
    "GOMES Dias": "gomes-dias",
    "GOMES Emmanuel": "gomes-emmanuel",
    "GOMES Kym": "gomes-kym",
    "GOMES Luisa Costa": "gomes-luisa-costa",
    "GOMEZ Antonio Enriquez": "gomez-antonio-enriquez",
    "GOMEZ Gabriel Rivas": "gomez-gabriel-rivas",
    "GOMEZ Gina M": "gomez-gina-m",
    "GOMEZ Jewelle": "gomez-jewelle",
    "GOMEZ Magdalena": "gomez-magdalena",
    "GOMEZ Marga": "gomez-marga",
    "GOMEZ Terry": "gomez-terry",
    "GOMEZ-PENA Guillermo": "gomez-pena-guillermo",
    "GOMITO PRODUCTIONS ": "gomito-productions",
    "GOMOLVILAS Prince": "gomolvilas-prince",
    "GOMPERS Robert Charles": "gompers-robert-charles",
    "GONCALVES Sarah": "goncalves-sarah",
    "GONNET Sarah": "gonnet-sarah",
    "GONON Daniel": "gonon-daniel",
    "GONSALVES Roanna": "gonsalves-roanna",
    "GONSHER Geoffrey": "gonsher-geoffrey",
    "GONTARCZYK Kuba": "gontarczyk-kuba",
    "GONTIER Robert": "gontier-robert",
    "GONYO Robert A K": "gonyo-robert-a-k",
    "GONZALES Danny": "gonzales-danny",
    "GONZALES Ivan": "gonzales-ivan",
    "GONZALES Kathleen": "gonzales-kathleen",
    "GONZALES Lillian": "gonzales-lillian",
    "GONZALES Miriam Rose": "gonzales-miriam-rose",
    "GONZALES Phil": "gonzales-phil",
    "GONZALES S Silvia": "gonzales-s-silvia",
    "GONZALEZ Aimee": "gonzalez-aimee",
    "GONZALEZ Alex": "gonzalez-alex",
    "GONZALEZ Anita": "gonzalez-anita",
    "GONZALEZ Carl": "gonzalez-carl",
    "GONZALEZ David": "gonzalez-david",
    "GONZALEZ Gloria": "gonzalez-gloria",
    "GONZALEZ Ivan": "gonzalez-ivan",
    "GONZALEZ Javier Antonio": "gonzalez-javierantonio",
    "GONZALEZ Jose Cruz": "gonzales-jose-cruz",
    "GONZALEZ Juancho": "gonzalez-juancho",
    "GONZALEZ Lyanisha": "gonzalez-lyanisha",
    "GONZALEZ Marvin": "gonzalez-marvin",
    "GONZALEZ Mike": "gonzalez-mike",
    "GONZALEZ Ricardo Perez": "gonzalez-ricardo-perez",
    "GONZALEZ S Silvia": "gonzalez-s-silvia",
    "GONZALEZ-CRUZ Luis": "gonzalez-cruz-luis",
    "GONZALEZ-RISSO Kico": "gonzalez-risso-kico",
    "GONZO MOOSE ": "gonzo-moose",
    "GOOCH Bruce": "gooch-bruce",
    "GOOCH Dan": "gooch-dan",
    "GOOCH Steve": "gooch-steve",
    "GOOD Ella": "good-ella",
    "GOOD Jack": "good-jack",
    "GOOD John": "good-john",
    "GOOD Maurice": "good-maurice",
    "GOOD Sophie": "good-sophie",
    "GOOD COP BAD COP ": "good-cop-bad-cop",
    "GOOD EVENING THEATRE COMPANY ": "good-evening-theatre-company",
    "GOODA Sarah": "gooda-sarah",
    "GOODALE David": "goodale-david",
    "GOODALE Robert": "goodale-robert",
    "GOODALL Adam": "goodall-adam",
    "GOODALL Cameron": "goodall-cameron",
    "GOODALL Howard": "goodall-howard",
    "GOODALL Julie": "goodall-julie",
    "GOODALL Rod": "goodall-rod",
    "GOODALL Simon": "goodall-simon",
    "GOODBODY Buzz": "goodbody-buzz",
    "GOODCHILD Peter": "goodchild-peter",
    "GOODE Chris": "goode-chris",
    "GOODE James": "goode-james",
    "GOODE Jeff": "goode-jeff",
    "GOODE Joshua": "goode-joshua",
    "GOODE Merle": "goode-merle",
    "GOODELL Susan": "goodell-susan",
    "GOODELL Theo": "goodell-theo",
    "GOODEN Lee": "gooden-lee",
    "GOODENOUGH Gay": "goodenough-gay",
    "GOODERSON David": "gooderson-david",
    "GOODES Joyce": "goodes-joyce",
    "GOODEY Kyla": "goodey-kyla",
    "GOODFRIEND Michael": "goodfriend-michael",
    "GOODGE Frederick": "goodge-frederick",
    "GOODHALL Adam": "goodhall-adam",
    "GOODHALL Howard": "goodhall-howard",
    "GOODHART Esther": "goodhart-esther",
    "GOODHART William": "goodhart-william",
    "GOODING Louise": "gooding-louise",
    "GOODING Scott": "gooding-scott",
    "GOODING Tim": "gooding-tim",
    "GOODISMAN Leonard": "goodisman-leonard",
    "GOODLAND Charlotte": "goodland-charlotte",
    "GOODLAND David": "goodland-david",
    "GOODLAND Pete": "goodland-pete",
    "GOODLET Harry": "goodlet-harry",
    "GOODLIFFE Jim": "goodliffe-jim",
    "GOODMAN Arthur": "goodman-arthur",
    "GOODMAN Ben": "goodman-ben",
    "GOODMAN Bernard": "goodman-bernard",
    "GOODMAN Bob": "goodman-bob",
    "GOODMAN Bruce": "goodman-bruce",
    "GOODMAN Bryce": "goodman-bryce",
    "GOODMAN Burton": "goodman-burton",
    "GOODMAN Christine": "goodman-christine",
    "GOODMAN Darryl": "goodman-darryl",
    "GOODMAN David G": "goodman-david-g",
    "GOODMAN Dean": "goodman-dean",
    "GOODMAN Jason": "goodman-jason",
    "GOODMAN Jeff": "goodman-jeff",
    "GOODMAN Joel": "goodman-joel",
    "GOODMAN Kenneth": "goodman-kenneth",
    "GOODMAN Kenneth Sawyer": "goodman-kenneth-sawyer",
    "GOODMAN Lawrence": "goodman-lawrence",
    "GOODMAN Linda": "goodman-linda",
    "GOODMAN Lori": "goodman-lori",
    "GOODMAN Lorraine": "goodman-lorraine",
    "GOODMAN Malka": "goodman-malka",
    "GOODMAN Mark": "goodman-mark",
    "GOODMAN Michael Evan": "goodman-michael-evan",
    "GOODMAN Norman": "goodman-norman",
    "GOODMAN Paul": "goodman-paul",
    "GOODMAN Paul Scott": "goodman-paul-scott",
    "GOODMAN Philip S": "goodman-philip-s",
    "GOODMAN Richard C": "goodman-richard-c",
    "GOODMAN Robert": "goodman-robert",
    "GOODMAN Tayla": "goodman-tayla",
    "GOODMAN Vernon": "goodman-vernon",
    "GOODNER Don": "goodner-don",
    "GOODNIGHT Kristina": "goodnight-kristina",
    "GOODNOW Natalie": "goodnow-natalie",
    "GOODRICH Bruce": "goodrich-bruce",
    "GOODRICH Frances": "goodrich-frances",
    "GOODRICH Harlene": "goodrich-harlene",
    "GOODRICH Joseph": "goodrich-joseph",
    "GOODRIDGE Estenia": "goodridge-estenia",
    "GOODRUM Don": "goodrum-don",
    "GOODRUM John": "goodrum-john",
    "GOODSON Alan": "goodson-alan",
    "GOODSON Emily": "goodson-emily",
    "GOODSON Jonathan": "goodson-jonathan",
    "GOODSTEIN Debbie": "goodstein-debbie",
    "GOODWIN Christopher": "goodwin-christopher",
    "GOODWIN Colin": "goodwin-colin",
    "GOODWIN David": "goodwin-david",
    "GOODWIN Dennis": "goodwin-dennis",
    "GOODWIN Derrick": "goodwin-derrick",
    "GOODWIN G H": "goodwin-g-h",
    "GOODWIN Idris": "goodwin-idris",
    "GOODWIN Janna L": "goodwin-janna-l",
    "GOODWIN John": "goodwin-john",
    "GOODWIN Jonathan": "goodwin-jonathan",
    "GOODWIN Mackaella": "goodwin-mackaella",
    "GOODWIN Marcus": "goodwin-marcus",
    "GOODWIN Mike": "goodwin-mike",
    "GOODWIN Nathan": "goodwin-nathan",
    "GOODWIN Paul": "goodwin-paul",
    "GOODWIN Paul H": "goodwin-paul-h",
    "GOODWIN Pete": "goodwin-pete",
    "GOODWIN Raymond": "goodwin-raymond",
    "GOODWIN Reiko": "goodwin-reiko",
    "GOODWIN Richard N": "goodwin-richard-n",
    "GOODWIN Sam": "goodwin-sam",
    "GOODWIN Valerie": "goodwin-valerie",
    "GOODWIN-TULLY Jason": "goodwin-tully-jason",
    "GOODY Bob": "goody-bob",
    "GOODYEAR Elizabeth": "goodyear-elizabeth",
    "GOODYER Greg": "goodyer-greg",
    "GOOLD Rupert": "goold-rupert",
    "GOOLD-VERSCHOYLE N": "goold-verschoyle-n",
    "GOOLEY Sam": "gooley-sam",
    "GOOS Maria": "goos-maria",
    "GOOTKIND Peter": "gootkind-peter",
    "GOPIE Rajesh": "gopie-rajesh",
    "GOPNIK Adam": "gopnik-adam",
    "GORANOV Velyo": "goranov-velyo",
    "GORCZYNSKI Joseph": "gorczynski-joseph",
    "GORDIN Jacob": "gordin-jacob",
    "GORDON Aalan": "gordon-aalan",
    "GORDON Aaron": "gordon-aaron",
    "GORDON Adele": "gordon-adele",
    "GORDON Ain": "gordon-ain",
    "GORDON Alan": "gordon-alan",
    "GORDON Alex": "gordon-alex",
    "GORDON Alice": "gordon-alice",
    "GORDON Alison": "gordon-alison",
    "GORDON Andi": "gordon-andi",
    "GORDON Andrew": "gordon-andrew",
    "GORDON Arthur": "gordon-arthur",
    "GORDON Barbara": "gordon-barbara",
    "GORDON Barry": "gordon-barry",
    "GORDON Barry J": "gordon-barry-j",
    "GORDON Bill": "gordon-bill",
    "GORDON Charles F": "gordon-charles-f",
    "GORDON Charles OyamO": "gordon-charles-oyamo",
    "GORDON Chuck": "gordon-chuck",
    "GORDON Dan": "gordon-dan",
    "GORDON Dan (2)": "gordon-dan-2",
    "GORDON Dan (3)": "gordon-dan-3",
    "GORDON Daniel B": "gordon-daniel-b",
    "GORDON David": "gordon-david",
    "GORDON Don": "gordon-don",
    "GORDON Douglas": "gordon-douglas",
    "GORDON Edwin": "gordon-edwin",
    "GORDON Eric": "gordon-eric",
    "GORDON Fred": "gordon-fred",
    "GORDON Fred Jay": "gordon-fred-jay",
    "GORDON Gaelyn": "gordon-gaelyn",
    "GORDON Geoffrey": "gordon-geoffrey",
    "GORDON George": "gordon-george",
    "GORDON Glen": "gordon-glen",
    "GORDON Greg": "gordon-greg",
    "GORDON James": "gordon-james",
    "GORDON Janie": "gordon-janie",
    "GORDON Jill": "gordon-jill",
    "GORDON Jim": "gordon-jim",
    "GORDON John": "gordon-john",
    "GORDON John R": "gordon-john-r",
    "GORDON Keith": "gordon-keith",
    "GORDON Ken": "gordon-ken",
    "GORDON Kurtz": "gordon-kurtz",
    "GORDON Lloyd": "gordon-lloyd",
    "GORDON Mackenzie": "gordon-mackenzie",
    "GORDON Maggie May": "gordon-maggie-may",
    "GORDON Mark Robert": "gordon-mark-robert",
    "GORDON Martin": "gordon-martin",
    "GORDON Mel": "gordon-mel",
    "GORDON Michael David": "gordon-michael-david",
    "GORDON Mick": "gordon-mick",
    "GORDON Miriam": "gordon-miriam",
    "GORDON Patricia": "gordon-patricia",
    "GORDON Patrick": "gordon-patrick",
    "GORDON Paul": "gordon-paul",
    "GORDON Peggy": "gordon-peggy",
    "GORDON Peter": "gordon-peter",
    "GORDON Peter (1)": "gordon-peter-1",
    "GORDON Radhika": "gordon-radhika",
    "GORDON Richard (1)": "gordon-richard-1",
    "GORDON Richard (2)": "gordon-richard-2",
    "GORDON Ricky Ian": "gordon-ricky-ian",
    "GORDON Robert": "gordon-robert",
    "GORDON Roxy": "gordon-roxy",
    "GORDON Ruth": "gordon-ruth",
    "GORDON Sarah": "gordon-sarah",
    "GORDON Sheila": "gordon-sheila",
    "GORDON Stuart": "gordon-stuart",
    "GORDON Sue": "gordon-sue",
    "GORDON Toni": "gordon-toni",
    "GORDONE Charles": "gordone-charles",
    "GORDON-SMITH Lee": "gordon-smith-lee",
    "GORDON-SOLMON Tasha": "gordon-solmon-tasha",
    "GORDY Berry": "gordy-berry",
    "GORDY Graham": "gordy-graham",
    "GORE Addison": "gore-addison",
    "GORE Catherine": "gore-catherine",
    "GORE Christopher": "gore-christopher",
    "GORE Jared": "gore-jared",
    "GORE Neil": "gore-neil",
    "GORE Rick": "gore-rick",
    "GORE Susan": "gore-susan",
    "GORE Tashi": "gore-tashi",
    "GORE Tom": "gore-tom",
    "GORE Will": "gore-will",
    "GORE-BROWN R": "gore-brown-r",
    "GOREING Andrew": "goreing-andrew",
    "GOREN Jeremy": "goren-jeremy",
    "GOREY Edward": "gorey-edward",
    "GORFIEN Rahti": "gorfien-rahti",
    "GORGEY Gabor": "gorgey-gabor",
    "GORHAM George H": "gorham-george-h",
    "GORHAM Nicholas": "gorham-nicholas",
    "GORIELY Serge": "goriely-serge",
    "GORILLA REPERTORY THEATER ": "gorilla-repertory-theater",
    "GORIN Grigory": "gorin-grigory",
    "GORING John M": "goring-john-m",
    "GORING Marius": "goring-marius",
    "GORING Victoria": "goring-victoria",
    "GORIS Jennifer": "goris-jennifer",
    "GORKY Maxim": "gorky-maxim",
    "GORLING Wendy": "gorling-wendy",
    "GORMAN Brian": "gorman-brian",
    "GORMAN Christina": "gorman-christina",
    "GORMAN Christopher": "gorman-christopher",
    "GORMAN Clem": "gorman-clem",
    "GORMAN Damian": "gorman-damian",
    "GORMAN Declan": "gorman-declan",
    "GORMAN Hogan": "gorman-hogan",
    "GORMAN Mari": "gorman-mari",
    "GORMAN Michael": "gorman-michael",
    "GORMAN Mike": "gorman-mike",
    "GORMAN Patrick T": "gorman-patrick-t",
    "GORMAN Paul": "gorman-paul",
    "GORMAN Robyn Barr": "gorman-robyn-barr",
    "GORMAN Suzanne": "gorman-suzanne",
    "GORMAN William": "gorman-william",
    "GORMEZANO Jessi Blue": "gormezano-jessi-blue",
    "GORMLEY Paddy": "gormley-paddy",
    "GORN Albi": "gorn-albi",
    "GOROSTI Carlos": "gorosti-carlos",
    "GOROSTIZA Carlos": "gorostiza-carlos",
    "GORRIE John": "gorrie-john",
    "GORRIS Jan-Albert": "gorris-jan-albert",
    "GORSKI Jamie": "gorski-jamie",
    "GORSON Peggy": "gorson-peggy",
    "GORTON Ali": "gorton-ali",
    "GOSHEFF Laura": "gosheff-laura",
    "GOSHKO Leslie": "goshko-leslie",
    "GOSHTA Mitrachi": "goshta-mitrachi",
    "GOSLING Alan": "gosling-alan",
    "GOSS Bernard": "goss-bernard",
    "GOSS Clay": "goss-clay",
    "GOSS Coby": "goss-coby",
    "GOSS Graydon": "goss-graydon",
    "GOSS James": "goss-james",
    "GOSS John": "goss-john",
    "GOSS Judy Baker": "goss-judy-baker",
    "GOSS Linda": "goss-linda",
    "GOSS Robert": "goss-robert",
    "GOSSE Edmund": "gosse-edmund",
    "GOSSES Sarah": "gosses-sarah",
    "GOSSETT Mitchell": "gossett-mitchell",
    "GOSSETT Neeley": "gossett-neeley",
    "GOSWAMI Rajeev": "goswami-rajeev",
    "GOTANDA Philip Kan": "gotanda-philip-kan",
    "GOTESTAM Birgitta": "gotestam-birgitta",
    "GOTESTAM Staffan": "gotestam-staffan",
    "GOTFURT Dorothea": "gotfurt-dorothea",
    "GOTHE Staffan": "gothe-staffan",
    "GOTHEINER Zvi": "gotheiner-zvi",
    "GOTLIB Alan": "gotlib-alan",
    "GOTLIEB Kenny": "gotlieb-kenny",
    "GOTO Edward": "goto-edward",
    "GOTSILL Tom": "gotsill-tom",
    "GOTT Sheila": "gott-sheila",
    "GOTT Susan": "gott-susan",
    "GOTTA Jessi": "gotta-jessi",
    "GOTTBERG Ki": "gottberg-ki",
    "GOTTESFELD Charles": "gottesfeld-charles",
    "GOTTESFELD Jeff": "gottesfeld-jeff",
    "GOTTESMAN Carl A": "gottesman-carl-a",
    "GOTTFRED Brad T": "gottfred-brad-t",
    "GOTTFRIDSSON Christina": "gottfridsson-christina",
    "GOTTFRIED Gilbert": "gottfried-gilbert",
    "GOTTFRIED Joseph Gath": "gottfried-joseph-gath",
    "GOTTLEIB Anne": "gottleib-anne",
    "GOTTLEIB Steven": "gottleib-steven",
    "GOTTLIEB Alex": "gottlieb-alex",
    "GOTTLIEB Maggie": "gottlieb-maggie",
    "GOTTLIEB Nathan": "gottlieb-nathan",
    "GOTTLIEB Noa": "gottlieb-noa",
    "GOTTLIEB Vera": "gottlieb-vera",
    "GOTTS George": "gotts-george",
    "GOTTS Kath": "gotts-kath",
    "GOTTSCHALL Grant": "gottschall-grant",
    "GOTTSCHE Brenda": "gottsche-brenda",
    "GOUCHIS R A": "gouchis-r-a",
    "GOUDIE Ray": "goudie-ray",
    "GOUDSMIT Judith": "goudsmit-judith",
    "GOUGH Andy": "gough-andy",
    "GOUGH Gina": "gough-gina",
    "GOUGH Jill": "gough-jill",
    "GOUGH Julian": "gough-julian",
    "GOUGH Lucy": "gough-lucy",
    "GOUGH Martin W": "gough-martin-w",
    "GOUGH Milo": "gough-milo",
    "GOUGH Orlando": "gough-orlando",
    "GOUGH Richard": "gough-richard",
    "GOUGH Robert D": "gough-robert-d",
    "GOUGH Sam": "gough-sam",
    "GOUGH Steve": "gough-steve",
    "GOUGH Toby": "gough-toby",
    "GOUGH Wendy": "gough-wendy",
    "GOUGIS R A": "gougis-r-a",
    "GOULD Carol": "gould-carol",
    "GOULD Ellen": "gould-ellen",
    "GOULD Franklin": "gould-franklin",
    "GOULD Howard M": "gould-howard-m",
    "GOULD Jeff": "gould-jeff",
    "GOULD John": "gould-john",
    "GOULD Madeline": "gould-madeline",
    "GOULD Marshall": "gould-marshall",
    "GOULD Matt": "gould-matt",
    "GOULD Rebecca": "gould-rebecca",
    "GOULD Robert": "gould-robert",
    "GOULD Steve": "gould-steve",
    "GOULD Terry": "gould-terry",
    "GOULD Victoria": "gould-victoria",
    "GOULDER Cody Benjamin": "goulder-cody-benjamin",
    "GOULDING Anthony": "goulding-anthony",
    "GOULDING Christopher": "goulding-christopher",
    "GOULDING Philip": "goulding-philip",
    "GOULET Laurent": "goulet-laurent",
    "GOULET Mary E": "goulet-mary-e",
    "GOULISH Matthew": "goulish-matthew",
    "GOUPIL Laval": "goupil-laval",
    "GOURLAY Elizabeth": "gourlay-elizabeth",
    "GOUSHEGIR Ezzat": "goushegir-ezzat",
    "GOV Anat": "gov-anat",
    "GOVAN Anita": "govan-anita",
    "GOVEAS Janice": "goveas-janice",
    "GOVENAR Alan": "govenar-alan",
    "GOVENDER Krijay": "govender-krijay",
    "GOVENDER Ronnie": "govender-ronnie",
    "GOVER Martin": "gover-martin",
    "GOVER Stuart": "gover-stuart",
    "GOVERNALI Anna": "governali-anna",
    "GOVERNOR Mark": "governor-mark",
    "GOVIER Mark": "govier-mark",
    "GOVIER Michael": "govier-michael",
    "GOW David": "gow-david",
    "GOW James": "gow-james",
    "GOW Keith": "gow-keith",
    "GOW L Kalo": "gow-l-kalo",
    "GOW Michael": "gow-michael",
    "GOW Ronald": "gow-ronald",
    "GOW Ruth": "gow-ruth",
    "GOWAN Elsie Park": "gowan-elsie-park",
    "GOWANS Elizabeth": "gowans-elizabeth",
    "GOWDA Ihor": "gowda-ihor",
    "GOWEN Peter": "gowen-peter",
    "GOWER Douglas": "gower-douglas",
    "GOWER Ian": "gower-ian",
    "GOWER Peggy": "gower-peggy",
    "GOWERS Patrick": "gowers-patrick",
    "GOWLAND Gus": "gowland-gus",
    "GOY Alan": "goy-alan",
    "GOZA Dennis": "goza-dennis",
    "GOZZI Carlo": "gozzi-carlo",
    "GRAALMAN Sarah": "graalman-sarah",
    "GRABANIA Anna-Maria": "grabania-anna-maria",
    "GRABENSTEIN Chris": "grabenstein-chris",
    "GRABER Benjamin": "graber-benjamin",
    "GRABER Sam": "graber-sam",
    "GRABER Sarah Rose": "graber-sarah-rose",
    "GRABINER Sam": "grabiner-sam",
    "GRABOW John": "grabow-john",
    "GRABOWSKY Paul": "grabowsky-paul",
    "GRACE Alan": "grace-alan",
    "GRACE Dom": "grace-dom",
    "GRACE Dominic": "grace-dominic",
    "GRACE Ella": "grace-ella",
    "GRACE Fraser": "grace-fraser",
    "GRACE Ginger": "grace-ginger",
    "GRACE Liliane": "grace-liliane",
    "GRACE Lucy": "grace-lucy",
    "GRACE Michael L": "grace-michael-l",
    "GRACE Paula L": "grace-paula-l",
    "GRACE Rebecca Becket": "grace-rebecca-becket",
    "GRACE Richard M": "grace-richard-m",
    "GRACE Rob": "grace-rob",
    "GRACE Vivienne": "grace-vivienne",
    "GRACE-DUFF Brian": "grace-duff-brian",
    "GRACE-SMITH Briar": "grace-smith-briar",
    "GRACEY Eric": "gracey-eric",
    "GRACIA Chad": "gracia-chad",
    "GRACIA Stephen": "gracia-stephen",
    "GRACIAS Bettina": "gracias-bettina",
    "GRACZYK Ed": "graczyk-ed",
    "GRADONE Ricky Ian": "gradona-ricky-ian",
    "GRADY Chris": "grady-chris",
    "GRADY Jim": "grady-jim",
    "GRADY John": "grady-john",
    "GRADY Michael": "grady-michael",
    "GRADY Michael J": "grady-michael-j",
    "GRADY Robert": "grady-robert",
    "GRADY Tom": "grady-tom",
    "GRADY-HALL Michael": "grady-hall-michael",
    "GRAE David": "grae-david",
    "GRAEAE ": "graeae",
    "GRAEFE Sara": "graefe-sara",
    "GRAEL Barry Alan": "grael-barry-alan",
    "GRAETZ Fay Ellen": "graetz-fay-ellen",
    "GRAF Kathryn": "graf-kathryn",
    "GRAF Wendy": "graf-wendy",
    "GRAFF Laurie": "graff-laurie",
    "GRAFF Rosemary": "graff-rosemary",
    "GRAFF Todd": "graff-todd",
    "GRAFFITI THEATRE COMPANY ": "graffiti-theatre-company",
    "GRAFFOE Boothby": "graffoe-boothby",
    "GRAHAM Ana": "graham-ana",
    "GRAHAM Andy": "graham-andy",
    "GRAHAM Anne": "graham-anne",
    "GRAHAM Arthur J": "graham-arthur-j",
    "GRAHAM Barbara": "graham-barbara",
    "GRAHAM Bertha N": "graham-bertha-n",
    "GRAHAM Beth": "graham-beth",
    "GRAHAM Billy": "graham-billy",
    "GRAHAM Boyd": "graham-boyd",
    "GRAHAM Bruce": "graham-bruce",
    "GRAHAM Burton": "graham-burton",
    "GRAHAM Caroline": "graham-caroline",
    "GRAHAM Carolyn": "graham-carolyn",
    "GRAHAM Connor": "graham-connor",
    "GRAHAM David": "graham-david",
    "GRAHAM David Wesley": "graham-david-wesley",
    "GRAHAM Dean": "graham-dean",
    "GRAHAM Debbie": "graham-debbie",
    "GRAHAM Duncan": "graham-duncan",
    "GRAHAM Duncan W": "graham-duncan-w",
    "GRAHAM Ellen K": "graham-ellen-k",
    "GRAHAM Fiona": "graham-fiona",
    "GRAHAM Gabrielle Cunningham": "graham-gabrielle-cunningham",
    "GRAHAM Gordon": "graham-gordon",
    "GRAHAM Hannah": "graham-hannah",
    "GRAHAM Harry": "graham-harry",
    "GRAHAM James": "graham-james",
    "GRAHAM James (1)": "graham-james-1",
    "GRAHAM Jim": "graham-jim",
    "GRAHAM Jo": "graham-jo",
    "GRAHAM Joe": "graham-joe",
    "GRAHAM John": "graham-john",
    "GRAHAM Jonathan": "graham-jonathan",
    "GRAHAM Joseph": "graham-joseph",
    "GRAHAM Maribeth": "graham-maribeth",
    "GRAHAM Marion": "graham-marion",
    "GRAHAM Matt": "graham-matt",
    "GRAHAM Mim": "graham-mim",
    "GRAHAM Nadine": "graham-nadine",
    "GRAHAM Patrick": "graham-patrick",
    "GRAHAM Philip": "graham-philip",
    "GRAHAM Ranald": "graham-ranald",
    "GRAHAM Ray Harrison": "graham-ray-harrison",
    "GRAHAM Richard": "graham-richard",
    "GRAHAM Ricky": "graham-ricky",
    "GRAHAM Robin": "graham-robin",
    "GRAHAM Ronald": "graham-ronald",
    "GRAHAM Ronny": "graham-ronny",
    "GRAHAM Ruth": "graham-ruth",
    "GRAHAM Samantha": "graham-samantha",
    "GRAHAM Sarah": "graham-sarah",
    "GRAHAM Scott": "graham-scott",
    "GRAHAM Tony": "graham-tony",
    "GRAHAM Travis": "graham-travis",
    "GRAHAM Wanda R": "graham-wanda-r",
    "GRAHAM William H": "graham-william-h",
    "GRAHAM-ADRIANI Tom": "graham-adriani-tom",
    "GRAHAM-CAMPBELL Alison": "graham-campbell-alison",
    "GRAHAM-CAMPBELL Angus": "graham-campbell-angus",
    "GRAHAM-DAVIES John": "graham-davies-john",
    "GRAHAME Alec": "grahame-alec",
    "GRAHAME Vivien": "grahame-vivien",
    "GRAHAM-JONES Jean": "graham-jones-jean",
    "GRAHAM-LUJAN James": "graham-lujan-james",
    "GRAHAM-YOUNG David": "graham-young-david",
    "GRAHN Judy": "grahn-judy",
    "GRAINE Sharon L": "graine-sharon-l",
    "GRAINGER Felix": "grainger-felix",
    "GRAINGER Gawn": "grainger-gawn",
    "GRAINGER Tom": "grainger-tom",
    "GRALLEY Jean": "gralley-jean",
    "GRAM Jon": "gram-jon",
    "GRAMAGLIA Caterina": "gramaglia-caterina",
    "GRAMMY Tara": "grammy-tara",
    "GRAN Maurice": "gran-maurice",
    "GRANAHAN Mim": "granahan-mim",
    "GRANATA Gici Ganzini": "granata-gici-ganzini",
    "GRANBY Fay": "granby-fay",
    "GRAND Jeff": "grand-jeff",
    "GRANDAGE Iain": "grandage-iain",
    "GRANDBOIS Peter": "grandbois-peter",
    "GRANDIN Temple": "grandin-temple",
    "GRANDISHER Thom": "grandisher-thom",
    "GRANEY Sean": "graney-sean",
    "GRANFIELD Suzanne": "granfield-suzanne",
    "GRANGE Henry": "grange-henry",
    "GRANGE John": "grange-john",
    "GRANGER Mason": "granger-mason",
    "GRANGER Milton": "granger-milton",
    "GRANGER Natasha": "granger-natasha",
    "GRANGER Percy": "granger-percy",
    "GRANGER-TAYLOR Peter": "granger-taylor-peter",
    "GRANICK Harry": "granick-harry",
    "GRANJA Miguel": "granja-miguel",
    "GRANNEMAN Ken": "granneman-ken",
    "GRANO Megan": "grano-megan",
    "GRANOFF Chase": "granoff-chase",
    "GRANT Abi": "grant-abi",
    "GRANT Adrian": "grant-adrian",
    "GRANT Antoy": "grant-antoy",
    "GRANT Barra": "grant-barra",
    "GRANT Barry": "grant-barry",
    "GRANT Ben Z": "grant-ben-z",
    "GRANT Bob": "grant-bob",
    "GRANT Cameron": "grant-cameron",
    "GRANT Christina": "grant-christina",
    "GRANT Cory": "grant-cory",
    "GRANT Craig Mums": "grant-craig-mums",
    "GRANT Cynthia": "grant-cynthia",
    "GRANT David": "grant-david",
    "GRANT David Marshall": "grant-david-marshall",
    "GRANT Diane": "grant-diane",
    "GRANT Douglas": "grant-douglas",
    "GRANT Eric": "grant-eric",
    "GRANT George Cameron": "grant-george-cameron",
    "GRANT Ian": "grant-ian",
    "GRANT James Shaw": "grant-james-shaw",
    "GRANT Jason": "grant-jason",
    "GRANT John Angell": "grant-john-angell",
    "GRANT Julian": "grant-julian",
    "GRANT Kathryn": "grant-kathryn",
    "GRANT Kit Goldstein": "grant-kit-goldstein",
    "GRANT L H": "grant-l-h",
    "GRANT Lydia": "grant-lydia",
    "GRANT Michael": "grant-michael",
    "GRANT Mick": "grant-mick",
    "GRANT Micki": "grant-micki",
    "GRANT Pamela": "grant-pamela",
    "GRANT Robyn": "grant-robyn",
    "GRANT Ronnie": "grant-ronnie",
    "GRANT Steve": "grant-steve",
    "GRANT Suzanne": "grant-suzanne",
    "GRANT William": "grant-william",
    "GRANTAM Kevin P": "grantam-kevin-p",
    "GRANTON Wes": "granton-wes",
    "GRANVILLE Kolby": "granville-kolby",
    "GRANVILLE-BARKER Harley": "granville-barker-harley",
    "GRANVILLE-BARKER Helen": "granville-barker-helen",
    "GRAPER Charlotte P": "graper-charlotte-p",
    "GRAPES Jack": "grapes-jack",
    "GRAPES II David": "grapes-ii-david",
    "GRAPPO Connie": "grappo-connie",
    "GRASER Jorg": "graser-jorg",
    "GRASET Esteve": "graset-esteve",
    "GRASHAW Robert": "grashaw-robert",
    "GRASHIN Nadrae": "grashin-nadrae",
    "GRASL Jason": "grasl-jason",
    "GRASS Alan": "grass-alan",
    "GRASS Gunter": "grass-gunter",
    "GRASSHOPPER Peter": "grasshopper-peter",
    "GRASSI Sandee": "grassi-sandee",
    "GRASSMARKET PROJECT, THE ": "grassmarket-project",
    "GRASSO Carl": "grasso-carl",
    "GRASZ Jennifer Sullivan": "grasz-jennifer-sullivan",
    "GRATION Steven": "gration-steven",
    "GRATTAN Gillian": "grattan-gillian",
    "GRATTAN Kevin P": "grattan-kevin-p",
    "GRATTON Simon": "gratton-simon",
    "GRATWICK A S": "gratwick-a-s",
    "GRATZON Fred": "gratzon-fred",
    "GRAUBARD Allan": "graubard-allan",
    "GRAUBERT S D": "graubert-s-d",
    "GRAUER Rita": "grauer-rita",
    "GRAUGNARD Andrea C": "graugnard-andrea-c",
    "GRAULS Carla": "grauls-carla",
    "GRAVEL Cliff": "gravel-cliff",
    "GRAVER E": "graver-e",
    "GRAVER Laurel": "graver-laurel",
    "GRAVES Gary": "graves-gary",
    "GRAVES Geoff": "graves-geoff",
    "GRAVES Gloria": "graves-gloria",
    "GRAVES Jocelyn": "graves-jocelyn",
    "GRAVES Paul": "graves-paul",
    "GRAVES Warren": "graves-warren",
    "GRAVOIS Michael": "gravois-michael",
    "GRAY Afsaneh": "gray-afsaneh",
    "GRAY Alasdair": "gray-alasdair",
    "GRAY Alexandra": "gray-alexandra",
    "GRAY Amber": "gray-amber",
    "GRAY Amlin": "gray-amlin",
    "GRAY Andy": "gray-andy",
    "GRAY Arielle": "gray-arielle",
    "GRAY C": "gray-c",
    "GRAY Caroline": "gray-caroline",
    "GRAY Catharine Clark": "gray-catharine-clark",
    "GRAY Dean": "gray-dean",
    "GRAY Deborah": "gray-deborah",
    "GRAY Derek": "gray-derek",
    "GRAY Dominic": "gray-dominic",
    "GRAY Dulcie": "gray-dulcie",
    "GRAY Dylan Coburn": "gray-dylan-coburn",
    "GRAY Elisabeth": "gray-elisabeth",
    "GRAY Ernie": "gray-ernie",
    "GRAY Frances": "gray-frances",
    "GRAY Frederick Victor": "gray-frederick-victor",
    "GRAY Gene": "gray-gene",
    "GRAY George": "gray-george",
    "GRAY Gwendolyn": "gray-gwendolyn",
    "GRAY I M": "gray-i-m",
    "GRAY Jack": "gray-jack",
    "GRAY Jodi": "gray-jodi",
    "GRAY John": "gray-john",
    "GRAY Karen": "gray-karen",
    "GRAY Katharine Clark": "gray-katharine-clark",
    "GRAY Kendall": "gray-kendall",
    "GRAY Kerry": "gray-kerry",
    "GRAY Larry": "gray-larry",
    "GRAY Layon": "gray-layon",
    "GRAY Leslie K": "gray-leslie-k",
    "GRAY Lewis": "gray-lewis",
    "GRAY Madeleine": "gray-madeleine",
    "GRAY Martin Laud": "gray-martin-laud",
    "GRAY Millie": "gray-millie",
    "GRAY Muriel": "gray-muriel",
    "GRAY Nicholas": "gray-nicholas",
    "GRAY Nicholas Stuart": "gray-nicholas-stuart",
    "GRAY Nigel": "gray-nigel",
    "GRAY Norman": "gray-norman",
    "GRAY Oriel": "gray-oriel",
    "GRAY Owen": "gray-owen",
    "GRAY Pamela": "gray-pamela",
    "GRAY Ramin": "gray-ramin",
    "GRAY Richard": "gray-richard",
    "GRAY Rick": "gray-rick",
    "GRAY Rudy": "gray-rudy",
    "GRAY Simon": "gray-simon",
    "GRAY Spalding": "gray-spalding",
    "GRAY Stephen": "gray-stephen",
    "GRAY Susan": "gray-susan",
    "GRAY Tanemahuta": "gray-tanemahuta",
    "GRAY Timothy": "gray-timothy",
    "GRAY Todd": "gray-todd",
    "GRAY Tomas": "gray-tomas",
    "GRAY Virginia H": "gray-virginia-h",
    "GRAY William": "gray-william",
    "GRAY Yulia": "gray-yulia",
    "GRAY ": "gray",
    "GRAY JR Alfred Rudolph": "gray-alfred-rudolph",
    "GRAYBILL Chris": "graybill-chris",
    "GRAYBILL Christopher": "graybill-christopher",
    "GRAYBURN Tim": "grayburn-tim",
    "GRAYHON Joseph": "grayhon-joseph",
    "GRAYLING A C": "grayling-a-c",
    "GRAY-PIPER Amy": "gray-piper-amy",
    "GRAYS Donnetta Lavinia": "grays-donnetta-lavinia",
    "GRAYSON Adam": "grayson-adam",
    "GRAYSON Heather": "grayson-heather",
    "GRAYSON Pamela Weiler": "grayson-pamela-weiler",
    "GRAYSON William": "grayson-william",
    "GRAZIANO David": "graziano-david",
    "GREAD Geoffrey": "gread-geoffrey",
    "GREANE David": "greane-david",
    "GREAT FREDINI, THE ": "great-fredini",
    "GREAT JONES REPERTORY ": "great-jones-repertory",
    "GREAT SMALL WORKS ": "great-small-works",
    "GREAT WORLD AMUSEMENT CENTER ": "great-world-amusement-center",
    "GREAVES Daphne": "greaves-daphne",
    "GREAVES James": "greaves-james",
    "GREAVES Jamie": "greaves-jamie",
    "GREBER Denise": "greber-denise",
    "GREBINSKI Stephen J": "grebinski-stephen-j",
    "GRECIAN Philip": "grecian-philip",
    "GRECO Jeremy (Jorgenson)": "greco-jeremy-jorgenson",
    "GRECO Marco": "greco-marco",
    "GRECO Stephen": "greco-stephen",
    "GREDY Jean Pierre": "gredy-jean-pierre",
    "GREEDER Armin": "greeder-armin",
    "GREEFF Rachelle": "greeff-rachelle",
    "GREEK H F": "greek-h-f",
    "GREELEY William": "greeley-william",
    "GREEN Adolph": "green-adolph",
    "GREEN Adrian": "green-adrian",
    "GREEN Albert": "green-albert",
    "GREEN Alex": "green-alex",
    "GREEN Alistair": "green-alistair",
    "GREEN Amanda": "green-amanda",
    "GREEN Amy": "green-amy",
    "GREEN Andrea": "green-andrea",
    "GREEN Babbie": "green-babbie",
    "GREEN Barry": "green-barry",
    "GREEN Benny": "green-benny",
    "GREEN Brian Lane": "green-brian-lane",
    "GREEN Carolyn": "green-carolyn",
    "GREEN Carrie": "green-carrie",
    "GREEN Cee Lo": "green-cee-lo",
    "GREEN Christopher": "green-christopher",
    "GREEN Conor": "green-conor",
    "GREEN Cromer": "green-cromer",
    "GREEN Dan": "green-dan",
    "GREEN debbie tucker": "green-debbie-tucker",
    "GREEN Doris": "green-doris",
    "GREEN Eric": "green-eric",
    "GREEN George Macewan": "green-george-macewan",
    "GREEN Georgia": "green-georgia",
    "GREEN Gretchen": "green-gretchen",
    "GREEN Hayley A": "green-hayley-a",
    "GREEN Jack": "green-jack",
    "GREEN Jamey": "green-jamey",
    "GREEN Janet": "green-janet",
    "GREEN Jason Parker": "green-jason-parker",
    "GREEN Jenny": "green-jenny",
    "GREEN Jeremy": "green-jeremy",
    "GREEN Jess": "green-jess",
    "GREEN Jim": "green-jim",
    "GREEN John": "green-john",
    "GREEN Jonathan L": "green-jonathan-l",
    "GREEN Joseph": "green-joseph",
    "GREEN Julien": "green-julien",
    "GREEN Julius": "green-julius",
    "GREEN Katie": "green-katie",
    "GREEN Keith": "green-keith",
    "GREEN L A": "green-l-a",
    "GREEN Lynda": "green-lynda",
    "GREEN Malcolm": "green-malcolm",
    "GREEN Marjorie": "green-marjorie",
    "GREEN Maro": "green-maro",
    "GREEN Mawby": "green-mawby",
    "GREEN Megan": "green-megan",
    "GREEN Michael": "green-michael",
    "GREEN Michael (2)": "green-michael-2",
    "GREEN Nathaniel": "green-nathaniel",
    "GREEN Niamh": "green-niamh",
    "GREEN Nic": "green-nic",
    "GREEN Nick": "green-nick",
    "GREEN Nick (2)": "green-nick-2",
    "GREEN Paul": "green-paul",
    "GREEN Paul A": "green-paul-a",
    "GREEN Paula": "green-paula",
    "GREEN Pelagie-May": "green-pelagie-may",
    "GREEN Peter": "green-peter",
    "GREEN Phill": "green-phill",
    "GREEN Phoebe": "green-phoebe",
    "GREEN R Dennis": "green-r-dennis",
    "GREEN Rod": "green-rod",
    "GREEN Roger Lancelyn": "green-roger-lancelyn",
    "GREEN Ros": "green-ros",
    "GREEN Ryan": "green-ryan",
    "GREEN Sarah Genevieve": "green-sarah-genevieve",
    "GREEN Schuyler": "green-schuyler",
    "GREEN Sevan Kaloustian": "green-sevan-kaloustian",
    "GREEN Sian": "green-sian",
    "GREEN Simon": "green-simon",
    "GREEN Spencer": "green-spencer",
    "GREEN Stanley Roger": "green-stanley-roger",
    "GREEN Steph": "green-steph",
    "GREEN Steven": "green-steven",
    "GREEN Tanaera": "green-tanaera",
    "GREEN Thom": "green-thom",
    "GREEN Todd Jordan": "green-todd-jordan",
    "GREEN Tom": "green-tom",
    "GREEN Tony": "green-tony",
    "GREEN Vivian": "green-vivian",
    "GREEN Warren": "green-warren",
    "GREEN William": "green-william",
    "GREEN Xander": "green-xander",
    "GREEN GINGER ": "green-ginger",
    "GREEN JR Sam": "green-jr-sam",
    "GREEN LIGHT ": "green-light",
    "GREENALL Doug": "greenall-doug",
    "GREENAWAY Alfred": "greenaway-alfred",
    "GREENAWAY L R": "greenaway-l-r",
    "GREENAWAY Peter": "greenaway-peter",
    "GREENBACK Alan": "greenback-alan",
    "GREENBANK Percy": "greenbank-percy",
    "GREENBERG Barbara": "greenberg-barbara",
    "GREENBERG David": "greenberg-david",
    "GREENBERG Edward": "greenberg-edward",
    "GREENBERG Evan": "greenberg-evan",
    "GREENBERG Faye": "greenberg-faye",
    "GREENBERG Gail": "greenberg-gail",
    "GREENBERG Gordon": "greenberg-gordon",
    "GREENBERG Gregg": "greenberg-gregg",
    "GREENBERG Jamie": "greenberg-jamie",
    "GREENBERG Joel": "greenberg-joel",
    "GREENBERG Jonathan": "greenberg-jonathan",
    "GREENBERG Julia": "greenberg-julia",
    "GREENBERG Karl": "greenberg-karl",
    "GREENBERG Martin": "greenberg-martin",
    "GREENBERG Mike": "greenberg-mike",
    "GREENBERG Minette": "greenberg-minette",
    "GREENBERG Mona": "greenberg-mona",
    "GREENBERG Neil": "greenberg-neil",
    "GREENBERG Richard": "greenberg-richard",
    "GREENBERG Shoshana": "greenberg-shoshana",
    "GREENBERG Stanley R": "greenberg-stanley-r",
    "GREENBERG Talia": "greenberg-talia",
    "GREENBERG Tamir": "greenberg-tamir",
    "GREENBERGER Harold": "greenberger-harold",
    "GREENBLATT Jamie": "greenblatt-jamie",
    "GREENBLATT Richard": "greenblatt-richard",
    "GREENBLATT Stephen": "greenblatt-stephen",
    "GREENBURG Dan": "greenburg-dan",
    "GREENBURG Edwin": "greenburg-edwin",
    "GREENE Bert": "greene-bert",
    "GREENE Bertram": "greene-bertram",
    "GREENE Brian": "greene-brian",
    "GREENE Clay M": "greene-clay-m",
    "GREENE David": "greene-david",
    "GREENE Declan": "greene-declan",
    "GREENE Evan": "greene-evan",
    "GREENE Frederick Dennis": "greene-frederick-dennis",
    "GREENE Gayle": "greene-gayle",
    "GREENE Goldee": "greene-goldee",
    "GREENE Graham": "greene-graham",
    "GREENE J": "greene-j",
    "GREENE Jennifer S": "greene-jennifer-s",
    "GREENE Justin": "greene-justin",
    "GREENE Ken": "greene-ken",
    "GREENE Mark": "greene-mark",
    "GREENE Matthew": "greene-matthew",
    "GREENE Otis": "greene-otis",
    "GREENE Patrick": "greene-patrick",
    "GREENE Patterson": "greene-patterson",
    "GREENE Rhonney": "greene-rhonney",
    "GREENE S": "greene-s",
    "GREENE Sevan Kaloustian": "greene-sevan-kaloustian",
    "GREENE Will": "greene-will",
    "GREENFELD Josh": "greenfeld-josh",
    "GREENFIELD Debra": "greenfield-debra",
    "GREENFIELD Ellen": "greenfield-ellen",
    "GREENFIELD Joseph": "greenfield-joseph",
    "GREENFIELD Josh": "greenfield-josh",
    "GREENFIELD Kathleen": "greenfield-kathleen",
    "GREENFIELD Kelleen Conway": "greenfield-kelleen-conway",
    "GREENFIELD Lisa": "greenfield-lisa",
    "GREENFIELD Mark": "greenfield-mark",
    "GREENGRASS Paul": "greengrass-paul",
    "GREENHALGH Jill": "greenhalgh-jill",
    "GREENHAM David": "greenham-david",
    "GREENHILL Ella Carmen": "greenhill-ella-carmen",
    "GREENHORN Stephen": "greenhorn-stephen",
    "GREENHOUSE Joel": "greenhouse-joel",
    "GREENHUT Deborah": "greenhut-deborah",
    "GREENIDGE Gertrude": "greenidge-gertrude",
    "GREENIDGE Kirsten": "greenidge-kirsten",
    "GREENING Joan": "greening-joan",
    "GREENING Nancy": "greening-nancy",
    "GREENLAND Abbi": "greenland-abbi",
    "GREENLAND Bill": "greenland-bill",
    "GREENLAND Gerry": "greenland-gerry",
    "GREENLAND Jackie": "greenland-jackie",
    "GREENLAND Phill": "greenland-phill",
    "GREENLAND Seth": "greenland-seth",
    "GREENLEAF John": "greenleaf-john",
    "GREENLEE Margot": "greenlee-margot",
    "GREENLEE Sam": "greenlee-sam",
    "GREENMAN Sarah": "greenman-sarah",
    "GREENMAN Stuart": "greenman-stuart",
    "GREENSILL Rebecca": "greensill-rebecca",
    "GREENSLADE Emily": "greenslade-emily",
    "GREENSLADE-LALONDE Gayle": "greenslade-lalonde-gayle",
    "GREENSPAN David": "greenspan-david",
    "GREENSPAN Henry": "greenspan-henry",
    "GREENSPAN Robin": "greenspan-robin",
    "GREENSPUN Michael": "greenspun-michael",
    "GREENSTEIN Larry": "greenstein-larry",
    "GREENSTEIN Louis": "greenstein-louis",
    "GREENSTEIN Rebecca": "greenstein-rebecca",
    "GREENSTREET Hannah": "greenstreet-hannah",
    "GREENUP P": "greenup-p",
    "GREENWALD Toby Klein": "greenwald-toby-klein",
    "GREENWALD Tom": "greenwald-tom",
    "GREENWAY Wil": "greenway-wil",
    "GREENWELL J R": "greenwell-j-r",
    "GREENWELL P": "greenwell-p",
    "GREENWELL Peter": "greenwell-peter",
    "GREENWELL Wayne K": "greenwell-wayne-k",
    "GREENWICH Ellie": "greenwich-ellie",
    "GREENWOOD Abigail": "greenwood-abigail",
    "GREENWOOD Bethany": "greenwood-bethany",
    "GREENWOOD Clive": "greenwood-clive",
    "GREENWOOD David": "greenwood-david",
    "GREENWOOD David Valdes": "greenwood-david-valdes",
    "GREENWOOD Diana": "greenwood-diana",
    "GREENWOOD Duncan": "greenwood-duncan",
    "GREENWOOD Lynn": "greenwood-lynn",
    "GREENWOOD Walter": "greenwood-walter",
    "GREER Aaron": "greer-aaron",
    "GREER Andrew": "greer-andrew",
    "GREER Bonnie": "greer-bonnie",
    "GREER Bruce": "greer-bruce",
    "GREER Christiaan": "greer-christiaan",
    "GREER Colin": "greer-colin",
    "GREER D M W": "greer-d-m-w",
    "GREER David": "greer-david",
    "GREER Germaine": "greer-germaine",
    "GREER Herb": "greer-herb",
    "GREER Jim": "greer-jim",
    "GREER Luanshya": "greer-luanshya",
    "GREER Mcadoo": "greer-mcadoo",
    "GREER Michael": "greer-michael",
    "GREER Rew David": "greer-rew-david",
    "GREER Robert": "greer-robert",
    "GREER Sarah Elizabeth": "greer-sarah-elizabeth",
    "GREER Scott": "greer-scott",
    "GREER Terence": "greer-terence",
    "GREFALDA Reme": "grefalda-reme",
    "GREGAN David": "gregan-david",
    "GREGAN Lisa Marie": "gregan-lisa-marie",
    "GREGAN Sheila": "gregan-sheila",
    "GREGG Al": "gregg-al",
    "GREGG Andy": "gregg-andy",
    "GREGG Hubert": "gregg-hubert",
    "GREGG Hugh": "gregg-hugh",
    "GREGG Jess": "gregg-jess",
    "GREGG Kevin": "gregg-kevin",
    "GREGG Rob Standish": "gregg-rob-standish",
    "GREGG Roger": "gregg-roger",
    "GREGG Stacey": "gregg-stacey",
    "GREGG Stephen": "gregg-stephen",
    "GREGG William": "gregg-william",
    "GREGOR John": "gregor-john",
    "GREGOR Katherine": "gregor-katherine",
    "GREGORDY Robin": "gregordy-robin",
    "GREGORIO John": "gregorio-john",
    "GREGOROPOULOS Noah": "gregoropoulos-noah",
    "GREGORSKI Nathan": "gregorski-nathan",
    "GREGORY Alexis": "gregory-alexis",
    "GREGORY Allison": "gregory-allison",
    "GREGORY Amber Onat": "gregory-amber-onat",
    "GREGORY Andre": "gregory-andre",
    "GREGORY Brendan": "gregory-brendan",
    "GREGORY Bryan": "gregory-bryan",
    "GREGORY D W": "gregory-d-w",
    "GREGORY Dina": "gregory-dina",
    "GREGORY Gillian": "gregory-gillian",
    "GREGORY H": "gregory-h",
    "GREGORY Irving": "gregory-irving",
    "GREGORY Joy": "gregory-joy",
    "GREGORY Julia": "gregory-julia",
    "GREGORY Justin": "gregory-justin",
    "GREGORY Lady": "gregory-lady",
    "GREGORY Leonard": "gregory-leonard",
    "GREGORY Lewis": "gregory-lewis",
    "GREGORY Liane": "gregory-liane",
    "GREGORY Mary": "gregory-mary",
    "GREGORY Matthew A J": "gregory-matthew-a-j",
    "GREGORY Nigel": "gregory-nigel",
    "GREGORY R G": "gregory-r-g",
    "GREGORY Richard": "gregory-richard",
    "GREGORY Robin": "gregory-robin",
    "GREGORY Sean": "gregory-sean",
    "GREGORY Shira": "gregory-shira",
    "GREGORY Tim": "gregory-tim",
    "GREGORY William": "gregory-william",
    "GREGORY William S": "gregory-william-s",
    "GREGORY-ROBERTS Emily": "gregory-roberts-emily",
    "GREGSON Isabelle": "gregson-isabelle",
    "GREGSON James": "gregson-james",
    "GREGSON Sean": "gregson-sean",
    "GREI Shadley": "grei-shadley",
    "GREIG Alan": "greig-alan",
    "GREIG David": "greig-david",
    "GREIG Elise": "greig-elise",
    "GREIG Jonathan": "greig-jonathan",
    "GREIG Marjory": "greig-marjory",
    "GREIG Noel": "greig-noel",
    "GREIG Rebecca": "greig-rebecca",
    "GREINER-FERRIS John": "greiner-ferris-john",
    "GRELIS Murray": "grelis-murray",
    "GRELLER Ken": "greller-ken",
    "GRELLONG Paul": "grellong-paul",
    "GREMINA Yelena": "gremina-yelena",
    "GRENDEL Leonard": "grendel-leonard",
    "GRENE David": "grene-david",
    "GRENFELL Colin": "grenfell-colin",
    "GRENFELL David": "grenfell-david",
    "GRENFELL-HILL Jeffrey": "grenfell-hill-jeffrey",
    "GRENKE Karen": "grenke-karen",
    "GRENLEE Rachel": "grenlee-rachel",
    "GRENNAN Eamon": "grennan-eamon",
    "GRENNAN Sean": "grennan-sean",
    "GRENOT Dominic": "grenot-dominic",
    "GRENROCK Joshua": "grenrock-joshua",
    "GRESHAM Xanthe": "gresham-xanthe",
    "GRESSEN Sherry Love": "gressen-sherry-love",
    "GRESSIEKER Hermann": "gressieker-hermann",
    "GRETH Roma": "greth-roma",
    "GREWAL Ray": "grewal-ray",
    "GREWELDINGER Yannick": "greweldinger-yannick",
    "GREY Clifford": "grey-clifford",
    "GREY Mark": "grey-mark",
    "GREY Raymond": "grey-raymond",
    "GREYSCALE ": "greyscale",
    "GRGAR Julie": "grgar-julie",
    "GRIBBEN Dennis Stephen": "gribben-dennis-stephen",
    "GRIBBIN Gordon": "gribbin-gordon",
    "GRIBBLE Dorothy Rose": "gribble-dorothy-rose",
    "GRIBOYEDOV Alexander Sergeyevich": "griboyedov-alexander-sergeyevich",
    "GRICE Richie": "grice-richie",
    "GRICEVICH Andy": "gricevich-andy",
    "GRID IRON ": "grid-iron",
    "GRIDLEY Steven": "gridley-steven",
    "GRIEG Nordahl": "grieg-nordahl",
    "GRIER Josclynne": "grier-josclynne",
    "GRIERSON Sandy": "grierson-sandy",
    "GRIESSMAN Benjamine Ugene": "griessman-benjamine-ugene",
    "GRIEVE Ian": "grieve-ian",
    "GRIEVE Rachel": "grieve-rachel",
    "GRIEVES Tom": "grieves-tom",
    "GRIF THEATER ": "grif-theater",
    "GRIFFIN Andy": "griffin-andy",
    "GRIFFIN Annie": "griffin-annie",
    "GRIFFIN Ashley": "griffin-ashley",
    "GRIFFIN Brendan": "griffin-brendan",
    "GRIFFIN Brian": "griffin-brian",
    "GRIFFIN Caroline": "griffin-caroline",
    "GRIFFIN Chas": "griffin-chas",
    "GRIFFIN Chris": "griffin-chris",
    "GRIFFIN Elizabeth": "griffin-elizabeth",
    "GRIFFIN H": "griffin-h",
    "GRIFFIN Helen": "griffin-helen",
    "GRIFFIN J": "griffin-j",
    "GRIFFIN James": "griffin-james",
    "GRIFFIN Joel": "griffin-joel",
    "GRIFFIN John": "griffin-john",
    "GRIFFIN June L": "griffin-june-l",
    "GRIFFIN Kalila": "griffin-kalila",
    "GRIFFIN L R": "griffin-l-r",
    "GRIFFIN Lance": "griffin-lance",
    "GRIFFIN Margaret": "griffin-margaret",
    "GRIFFIN Oscar": "griffin-oscar",
    "GRIFFIN Patty": "griffin-patty",
    "GRIFFIN Robert": "griffin-robert",
    "GRIFFIN Susan": "griffin-susan",
    "GRIFFIN Tamzin": "griffin-tamzin",
    "GRIFFIN Thomas": "griffin-thomas",
    "GRIFFIN Tim": "griffin-tim",
    "GRIFFIN Todd": "griffin-todd",
    "GRIFFIN Tom": "griffin-tom",
    "GRIFFIN William": "griffin-william",
    "GRIFFIN-PRESSLEY Deaon": "griffin-pressley-deaon",
    "GRIFFINS Fiona": "griffins-fiona",
    "GRIFFINS Geraldine": "griffins-geraldine",
    "GRIFFITH Alan": "griffith-alan",
    "GRIFFITH Eugene": "griffith-eugene",
    "GRIFFITH Ingrid": "griffith-ingrid",
    "GRIFFITH Katherine": "griffith-katherine",
    "GRIFFITH Mair": "griffith-mair",
    "GRIFFITH Meg": "griffith-meg",
    "GRIFFITH Michael": "griffith-michael",
    "GRIFFITH P J": "griffith-p-j",
    "GRIFFITH Patricia": "griffith-patricia",
    "GRIFFITH Peter": "griffith-peter",
    "GRIFFITH-FRANCIS Silvano": "griffith-francis-silvano",
    "GRIFFITH-JONES Krystyna": "griffith-jones-krystyna",
    "GRIFFITHS Alan": "griffiths-alan",
    "GRIFFITHS Andy": "griffiths-andy",
    "GRIFFITHS Annabel": "griffiths-annabel",
    "GRIFFITHS Bob": "griffiths-bob",
    "GRIFFITHS Braden": "griffiths-braden",
    "GRIFFITHS Ciaran": "griffiths-ciaran",
    "GRIFFITHS David": "griffiths-david",
    "GRIFFITHS David P": "griffiths-david-p",
    "GRIFFITHS Derek": "griffiths-derek",
    "GRIFFITHS Diana": "griffiths-diana",
    "GRIFFITHS Drew": "griffiths-drew",
    "GRIFFITHS Geraldine": "griffiths-geraldine",
    "GRIFFITHS Hubert": "griffiths-hubert",
    "GRIFFITHS Jamie": "griffiths-jamie",
    "GRIFFITHS Jane Montgomery": "griffiths-jane-montgomery",
    "GRIFFITHS Jay": "griffiths-jay",
    "GRIFFITHS Joe": "griffiths-joe",
    "GRIFFITHS Kelly": "griffiths-kelly",
    "GRIFFITHS Leon": "griffiths-leon",
    "GRIFFITHS Linda": "griffiths-linda",
    "GRIFFITHS Linda Marshall": "griffiths-linda-marshall",
    "GRIFFITHS Malcolm": "griffiths-malcolm",
    "GRIFFITHS Mark": "griffiths-mark",
    "GRIFFITHS Paul": "griffiths-paul",
    "GRIFFITHS Philip": "griffiths-philip",
    "GRIFFITHS Ridley R": "griffiths-ridley-r",
    "GRIFFITHS Roger": "griffiths-roger",
    "GRIFFITHS Tamara": "griffiths-tamara",
    "GRIFFITHS Trevor": "griffiths-trevor",
    "GRIFFITHS Zack": "griffiths-zack",
    "GRIFFO Michael": "griffo-michael",
    "GRIGAL Helen": "grigal-helen",
    "GRIGG David": "grigg-david",
    "GRIGG-EDO Claudia": "grigg-edo-claudia",
    "GRIGGS Ashley Danielle": "griggs-ashley-danielle",
    "GRIGGS George": "griggs-george",
    "GRIGGS Thurston": "griggs-thurston",
    "GRIGGS William M": "griggs-william-m",
    "GRIGNARD Christopher": "grignard-christopher",
    "GRIGOLIA-ROSENBAUM Jacob": "grigolia-rosenbaum-jacob",
    "GRIGSBY James": "grigsby-james",
    "GRIGSBY Tristan": "grigsby-tristan",
    "GRILLO Denise J": "grillo-denise-j",
    "GRILLO Gilda": "grillo-gilda",
    "GRILLO John": "grillo-john",
    "GRILLO Marie": "grillo-marie",
    "GRILLPARZER Franz": "grillparzer-franz",
    "GRIM Johnny": "grim-johnny",
    "GRIMALDI Tony": "grimaldi-tony",
    "GRIMBERG Deborah": "grimberg-deborah",
    "GRIMES Conor": "grimes-conor",
    "GRIMES Frank": "grimes-frank",
    "GRIMES Jimmy": "grimes-jimmy",
    "GRIMES Ken": "grimes-ken",
    "GRIMES Kenneth": "grimes-kenneth",
    "GRIMES Peter": "grimes-peter",
    "GRIMES Rebbecca": "grimes-rebbecca",
    "GRIMES Tyler": "grimes-tyler",
    "GRIMKE Angelina Weld": "grimke-angelina-weld",
    "GRIMLEY Scott": "grimley-scott",
    "GRIMM David": "grimm-david",
    "GRIMME Don": "grimme-don",
    "GRIMMER Mark": "grimmer-mark",
    "GRIMMETT John": "grimmett-john",
    "GRIMSHAW John": "grimshaw-john",
    "GRIMSHAW Nigel": "grimshaw-nigel",
    "GRIMSLEY Jim": "grimsley-jim",
    "GRIMSLEY Sidney": "grimsley-sidney",
    "GRIMWOOD Darrin": "grimwood-darrin",
    "GRINDLEY David": "grindley-david",
    "GRINDSTAFF Jessica": "grindstaff-jessica",
    "GRINGRAS Marcus J": "gringras-marcus-j",
    "GRINGRAS Robbie": "gringras-robbie",
    "GRINSLEY Jim": "grinsley-jim",
    "GRINTER Daniel": "grinter-daniel",
    "GRIPPA Rob": "grippa-rob",
    "GRIPPO Charles": "grippo-charles",
    "GRIPS THEATRE OF BERLIN ": "grips-theatre-of-berlin",
    "GRISANTI Diana": "grisanti-diana",
    "GRISHAM Jamey": "grisham-jamey",
    "GRISHKOVETS Evgeny": "grishkovets-evgeny",
    "GRISSMER John": "grissmer-john",
    "GRISSOM Doug": "grissom-doug",
    "GRISSOM Hubert": "grissom-hubert",
    "GRISSOM Lisa Kenner": "grissom-lisa-kenner",
    "GRIST Mark": "grist-mark",
    "GRISWOLD Julia": "griswold-julia",
    "GRISWOLD Megan": "griswold-megan",
    "GRITTANI Vince": "grittani-vince",
    "GRITTEN Charles": "gritten-charles",
    "GROAG Lillian": "groag-lillian",
    "GROB Anne": "grob-anne",
    "GROCE Michael": "groce-michael",
    "GROCHALA Sarah": "grochala-sarah",
    "GRODIN Charles": "grodin-charles",
    "GRODIN Sophie": "grodin-sophie",
    "GRODSKY Sarah": "grodsky-sarah",
    "GRODY Donald": "grody-donald",
    "GRODY Ian": "grody-ian",
    "GROENVELD Garret Jon": "groenveld-garret-jon",
    "GROFF Albert": "groff-albert",
    "GROFF Rinne": "groff-rinne",
    "GROFF Timothy": "groff-timothy",
    "GROGAN Erin N": "grogan-erin-n",
    "GROGAN John": "grogan-john",
    "GROLL Ted": "groll-ted",
    "GROLL Theodore J": "groll-theodore-j",
    "GROME Nancy": "grome-nancy",
    "GROMELSKI Brad": "gromelski-brad",
    "GRONE Jack": "grone-jack",
    "GRONING Eleonora": "groning-eleonora",
    "GRONOWICZ Antoni": "gronowicz-antoni",
    "GROOM Peter": "groom-peter",
    "GROOTBOOM Paul": "grootboom-paul",
    "GROOVE Spring": "groove-spring",
    "GROPPER Catherine": "gropper-catherine",
    "GROSBARD Ulu": "grosbard-ulu",
    "GROSCH Greta": "grosch-greta",
    "GROSE Carl": "grose-carl",
    "GROSE Polly": "grose-polly",
    "GROSS Alan": "gross-alan",
    "GROSS Alex": "gross-alex",
    "GROSS Alexander": "gross-alexander",
    "GROSS Brian": "gross-brian",
    "GROSS Daniel Franklin": "gross-daniel-franklin",
    "GROSS Dayna M": "gross-dayna-m",
    "GROSS Hugh": "gross-hugh",
    "GROSS Joel": "gross-joel",
    "GROSS Jonathan": "gross-jonathan",
    "GROSS Milt": "gross-milt",
    "GROSS Oded": "gross-oded",
    "GROSS Paul": "gross-paul",
    "GROSS Robert": "gross-robert",
    "GROSS Simon": "gross-simon",
    "GROSS Theodore": "gross-theodore",
    "GROSS Todd David": "gross-todd-david",
    "GROSSBAUER Bryan": "grossbauer-bryan",
    "GROSSENBACHER Melanie": "grossenbacher-melanie",
    "GROSSETTI Adam": "grossetti-adam",
    "GROSSFIELD Norman J": "grossfield-norman-j",
    "GROSSMAN Alec": "grossman-alec",
    "GROSSMAN Budd": "grossman-budd",
    "GROSSMAN David": "grossman-david",
    "GROSSMAN Jan": "grossman-jan",
    "GROSSMAN Jason S": "grossman-jason-s",
    "GROSSMAN Larry": "grossman-larry",
    "GROSSMAN Matthew": "grossman-matthew",
    "GROSSMAN Naomi": "grossman-naomi",
    "GROSSMAN Rachel": "grossman-rachel",
    "GROSSMAN Suzanne": "grossman-suzanne",
    "GROSSMAN Terry": "grossman-terry",
    "GROSSMITH George": "grossmith-george",
    "GROSSO Andrew": "grosso-andrew",
    "GROSSO Nick": "grosso-nick",
    "GROSVENOR Catherine": "grosvenor-catherine",
    "GROSVENOR Douglas A": "grosvenor-douglas-a",
    "GROSZ Peter": "grosz-peter",
    "GROTE James E": "grote-james-e",
    "GROTE Jason": "grote-jason",
    "GROTH Joakim": "groth-joakim",
    "GROTH L": "groth-l",
    "GROTHUIS Irma": "grothuis-irma",
    "GROTOWSKI Jerzy": "grotowski-jerzy",
    "GROUMAS Dennis": "groumas-dennis",
    "GROUND Kelly": "ground-kelly",
    "GROUNDS Tony": "grounds-tony",
    "GROUP THEATRE TOO ": "group-theatre-too",
    "GROVE Jeff": "grove-jeff",
    "GROVE Reuben": "grove-reuben",
    "GROVER Jim": "grover-jim",
    "GROVERLAND Jack": "groverland-jack",
    "GROVES Bill": "groves-bill",
    "GROVES Ellen": "groves-ellen",
    "GROVES Kelly": "groves-kelly",
    "GROVES Mac": "groves-mac",
    "GROVES Paul": "groves-paul",
    "GROVES Rob": "groves-rob",
    "GROW Jeff": "grow-jeff",
    "GROZIER Catriona": "grozier-catriona",
    "GRUBER Charles": "gruber-charles",
    "GRUBER Michael": "gruber-michael",
    "GRUDEFF Marian": "grudeff-marian",
    "GRUEN John": "gruen-john",
    "GRUEN Mary Anne": "gruen-mary-anne",
    "GRUENERT Virginia Wall": "gruenert-virginia-wall",
    "GRUENLOH Taylor": "gruenloh-taylor",
    "GRUENWALD Sandy": "gruenwald-sandy",
    "GRUETTER Robert": "gruetter-robert",
    "GRUFFYDD Annes": "gruffydd-annes",
    "GRUFFYDD Arwell": "gruffydd-arwell",
    "GRUFFYDD Mair": "gruffydd-mair",
    "GRUFFYDD A DYFED THOMAS Robin": "gruffydd-a-dyfed-thomas-robin",
    "GRUMBERG Jean-Claude": "grumberg-jean-claude",
    "GRUNBERGER Richard": "grunberger-richard",
    "GRUND Francoise": "grund-francoise",
    "GRUNDMANN Tim": "grundmann-tim",
    "GRUNDY Stella": "grundy-stella",
    "GRUNFIELD Itai": "grunfield-itai",
    "GRUNN Richard": "grunn-richard",
    "GRUNWALD Rachel": "grunwald-rachel",
    "GRUSECKI Robert": "grusecki-robert",
    "GRUSETSKIE Andrew": "grusetskie-andrew",
    "GRUSH Stephen Louis": "grush-stephen-louis",
    "GRUSKOVA Anna": "gruskova-anna",
    "GRYGO Eugene": "grygo-eugene",
    "GRYLLS Sarah": "grylls-sarah",
    "GRYPARIS Joannis": "gryparis-joannis",
    "GRYPHIUS Andreas": "gryphius-andreas",
    "GRYZBOWSKI Matt": "gryzbowski-matt",
    "GRZIC Mark": "grzic-mark",
    "GRZYBEK Elizabeth": "grzybek-elizabeth"
  }
};