export default {
  "metadata": {
    "results": 214,
    "timeStamp": "2025-12-05T21:25:02.725Z",
    "url": "https://www.doollee.com/PlaywrightsG/G_playwrights_s-z.php"
  },
  "authors": {
    "GSCHWIND Ian": "gschwind-ian",
    "GUADAGNI Nicky": "guadagni-nicky",
    "GUADAGNOLI Toniann": "guadagnoli-toniann",
    "GUAITA Giovanni": "guaita-giovanni",
    "GUALTIERI Tom": "gualtieri-tom",
    "GUANGTIAN Zhang": "guangtian-zhang",
    "GUARD Philip": "guard-philip",
    "GUARD Rick": "guard-rick",
    "GUARE John": "guare-john",
    "GUARINI Giovanni": "guarini-giovanni",
    "GUARINO Stephen": "guarino-stephen",
    "GUARRASI Annette": "guarrasi-annette",
    "GUASPARI David": "guaspari-david",
    "GUATARASMA Andres Correa": "guatarasma-andres-correa",
    "GUAY Paul": "guay-paul",
    "GUBARYEV Vladimir": "gubaryev-vladimir",
    "GUBBINS Sarah": "gubbins-sarah",
    "GUBSER Michael": "gubser-michael",
    "GUCHU Wonder": "guchu-wonder",
    "GUDGEON Mac": "gudgeon-mac",
    "GUDGEON Vernon": "gudgeon-vernon",
    "GUDMUNDSDOTTIR Hrafnhildur Hagalin": "gudmundsdottir-hrafnhildur",
    "GUDMUNDSSON Einar Mar": "gudmundsson-einar-mar",
    "GUEDAS Oscar": "guedas-oscar",
    "GUEHRING Brian": "guehring-brian",
    "GUEKI Mou Gon": "gueki-mou-gon",
    "GUENTHER Kirsten ": "guenther-kirsten",
    "GUERDAT Andrew": "guerdat-andrew",
    "GUERDIN David": "guerdin-david",
    "GUERIN Ciji": "guerin-ciji",
    "GUERIN Tony": "guerin-tony",
    "GUEROULT Aurelien": "gueroult-aurelien",
    "GUERRA Dylan": "guerra-dylan",
    "GUERRERA Midge": "guerrera-midge",
    "GUERRERIO Vid": "guerrerio-vid",
    "GUERRERO Daniel Alexander": "guerrero-daniel-alexander",
    "GUERRERO Javier": "guerrero-javier",
    "GUERRERO Wilfrido Maria": "guerrero-wilfrido-maria",
    "GUERRIEN Gerardo": "guerrien-gerardo",
    "GUEST Maia": "guest-maia",
    "GUEST Terry": "guest-terry",
    "GUETTEL Adam": "guettel-adam",
    "GUETTI Annie": "guetti-annie",
    "GUGGENHEIM Amy": "guggenheim-amy",
    "GUHA Dipika": "guha-dipika",
    "GUIDI Firenza": "guidi-firenza",
    "GUIDOTE-ALVAREZ Cecile": "guidote-alvarez-cecile",
    "GUIGNI A M": "guigni-a-m",
    "GUIHER James M": "guiher-james-m",
    "GUILD Amelia": "guild-amelia",
    "GUILFORD-BLAKE Evan": "guilford-blake-evan",
    "GUILLAUD Maurice": "guillaud-maurice",
    "GUILLAUME Susana": "guillaume-susana",
    "GUILLORY Letitia": "guillory-letitia",
    "GUILLOT Timothy J": "guillot-timothy-j",
    "GUIMARAES Jorge": "guimaraes-jorge",
    "GUIN Christopher Michael": "guin-christopher-michael",
    "GUINEE Christopher": "guinee-christopher",
    "GUINESS Owen": "guiness-owen",
    "GUINIER Sary": "guinier-sary",
    "GUINNESS Alec": "guinness-alec",
    "GUINNESS Valentine": "guinness-valentine",
    "GUIOCHINS Elena": "guiochins-elena",
    "GUIRAUD Rose Marie": "guiraud-rose-marie",
    "GUIRGIS Stephen Adly": "guirgis-stephen-adly",
    "GULACK Robert": "gulack-robert",
    "GULAN Genco": "gulan-genco",
    "GULBRANDSEN Frede": "gulbrandsen-frede",
    "GULICK Cath": "gulick-cath",
    "GULINO Paul Joseph": "gulino-paul-joseph",
    "GULLA Joe": "gulla-joe",
    "GULLA Romualdo": "gulla-romualdo",
    "GULLANS Sandy Hotchkiss": "gullans-sandy-hotchkiss",
    "GULLETT Trish": "gullett-trish",
    "GULLETTE D": "gullette-d",
    "GULLIKSON Andy": "gullikson-andy",
    "GULLINGS Kyle": "gullings-kyle",
    "GULLO Bill": "gullo-bill",
    "GULOTTA Josh": "gulotta-josh",
    "GULP ": "gulp",
    "GULPILIL David": "gulpilil-david",
    "GUMBLE Wayne": "gumble-wayne",
    "GUMBLEY Ross": "gumbley-ross",
    "GUMMER Joan": "gummer-joan",
    "GUMMERSON Penny": "gummerson-penny",
    "GUNA NUA THEATRE COMPANY ": "guna-nua-theatre-company",
    "GUNARY Steph": "gunary-steph",
    "GUNAWAN Edward": "gunawan-edward",
    "GUNBY George": "gunby-george",
    "GUNDERSHEIMER Lee": "gundersheimer-lee",
    "GUNDERSON Lauren": "gunderson-lauren",
    "GUNDY Elizabeth": "gundy-elizabeth",
    "GUNN Andrew": "gunn-andrew",
    "GUNN Bill": "gunn-bill",
    "GUNN Carlee": "gunn-carlee",
    "GUNN Edward M": "gunn-edward-m",
    "GUNN George": "gunn-george",
    "GUNN Neil M": "gunn-neil-m",
    "GUNN Nicola": "gunn-nicola",
    "GUNN Sue Ann": "gunn-sue-ann",
    "GUNN Suzy": "gunn-suzy",
    "GUNNELL Leisa": "gunnell-leisa",
    "GUNSAN Simge": "gunsan-simge",
    "GUNTER Anthony": "gunter-anthony",
    "GUNTER John": "gunter-john",
    "GUNTER Penny": "gunter-penny",
    "GUNTER Peter Henry": "gunter-peter-henry",
    "GUNTER Violet L": "gunter-violet-l",
    "GUNTHER John": "gunther-john",
    "GUNZBURG Darrelyn": "gunzburg-darrelyn",
    "GUODEI David": "guodei-david",
    "GUPTA Amit": "gupta-amit",
    "GUPTA Atiha Sen": "gupta-atiha-sen",
    "GUPTA Deepali": "gupta-deepali",
    "GUPTA Deepti": "gupta-deepti",
    "GUPTA Prashant": "gupta-prashant",
    "GUPTA Rahila": "gupta-rahila",
    "GUPTA Rati": "gupta-rati",
    "GUPTA Sachin": "gupta-sachin",
    "GUPTA Sanjay": "gupta-sanjay",
    "GUPTA Tanika": "gupta-tanika",
    "GUPTON Eric": "gupton-eric",
    "GURALNICK June": "guralnick-june",
    "GURGANUS Allan": "gurganus-allan",
    "GURIK Robert": "gurik-robert",
    "GURIN Michael": "gurin-michael",
    "GURIRA Danai": "gurira-danai",
    "GURLEY Nan Arnold": "gurley-nan-arnold",
    "GURNEY A R": "gurney-a-r",
    "GURNEY Claude": "gurney-claude",
    "GURNEY-RANDALL Ross": "gurney-randall-ross",
    "GURR Michael": "gurr-michael",
    "GURR T Stuart": "gurr-t-stuart",
    "GURREN Matthew": "gurren-matthew",
    "GURSKIS Dan": "gurskis-dan",
    "GURSKY David": "gursky-david",
    "GURTLER Rita": "gurtler-rita",
    "GURWITCH Annabelle": "gurwitch-annabelle",
    "GUSS Jack Raphael": "guss-jack-raphael",
    "GUSSIN Debra M": "gussin-debra-m",
    "GUSTAFSON Anita": "gustafson-anita",
    "GUSTAFSON Elise": "gustafson-elise",
    "GUSTAFSON James A": "gustafson-james-a",
    "GUSTAFSON Jim": "gustafson-jim",
    "GUSTAFSSON Walter": "gustafsson-walter",
    "GUSTIN Richard": "gustin-richard",
    "GUTELIUS Josepha": "gutelius-josepha",
    "GUTH M K": "guth-m-k",
    "GUTHERZ Alec": "gutherz-alec",
    "GUTHRIE Donna W": "guthrie-donna-w",
    "GUTHRIE Tyrone": "guthrie-tyrone",
    "GUTIERREZ Dixon": "gutierrez-dixon",
    "GUTIERREZ Miguel": "gutierrez-miguel",
    "GUTIERREZ Nitra": "gutierrez-nitra",
    "GUTIERREZ Stephen": "gutierrez-stephen",
    "GUTMACHER Benito": "gutmacher-benito",
    "GUTMANN Max": "gutmann-max",
    "GUTOWSKI Bob": "gutowski-bob",
    "GUTSCHICK Matthew": "gutschick-matthew",
    "GUTTERIDGE Elizabeth": "gutteridge-elizabeth",
    "GUTTERIDGE Penny": "gutteridge-penny",
    "GUTTERIDGE Tim": "gutteridge-tim",
    "GUTTERMAN Elizabeth C": "gutterman-elizabeth-c",
    "GUTTO Anna": "gutto-anna",
    "GUTTORMSGAARD Anna": "guttormsgaard-anna",
    "GUTTWILLIG Stephen": "guttwillig-stephen",
    "GUTZKOW Karl Ferdinand": "gutzkow-karl-ferdinand",
    "GUY Bette": "guy-bette",
    "GUY Chris": "guy-chris",
    "GUY Daniel": "guy-daniel",
    "GUY Darren": "guy-darren",
    "GUY Dylan": "guy-dylan",
    "GUY Joyce": "guy-joyce",
    "GUY Rachael": "guy-rachael",
    "GUY Ray": "guy-ray",
    "GUY Rosa": "guy-rosa",
    "GUY Russell": "guy-russell",
    "GUY Scott": "guy-scott",
    "GUY Shirley": "guy-shirley",
    "GUYAN Alexander": "guyan-alexander",
    "GUYER Jane": "guyer-jane",
    "GUYER Murphy": "guyer-murphy",
    "GUYET Paul": "guyet-paul",
    "GUYS Harry": "guys-harry",
    "GUYTON Daniel": "guyton-daniel",
    "GUYTON Kate": "guyton-kate",
    "GUYTON Leslie": "guyton-leslie",
    "GUZHA Daves": "guzha-daves",
    "GUZMAN Henry": "guzman-henry",
    "GUZMAN Jack": "guzman-jack",
    "GUZOWSKI Irene": "guzowski-irene",
    "GUZY-SPRAGUE Zoe": "guzy-sprague-zoe",
    "GUZZETTA Marli": "guzzetta-marli",
    "GUZZI Perry": "guzzi-perry",
    "GVIRTZMAN Zac": "gvirtzman-zac",
    "GW JR ": "gw-jr",
    "GWENT THEATRE COMPANY, THE ": "gwent-theatre-company",
    "GWILDIS Stefan": "gwildis-stefan",
    "GWILYM Mari": "gwilym-mari",
    "GWINN Brandon": "gwinn-brandon",
    "GWINN Brandon James": "gwinn-brandon-james",
    "GWINN Peter": "gwinn-peter",
    "GWON Adam": "gwon-adam",
    "GWYN Leslie": "gwyn-leslie",
    "GWYTHER Alex": "gwyther-alex",
    "GYARFAS Miklos": "gyarfas-miklos",
    "GYLEN Ellen": "gylen-ellen",
    "GYLES Shelia": "gyles-shelia",
    "GYNA ": "gyna",
    "GYNGELL Michael": "gyngell-michael",
    "GYORGYEY Clara": "gyorgyey-clara",
    "GYSELINK Wannes": "gyselink-wannes",
    "GYSELINX Jean": "gyselinx-jean",
    "GYTRI Julia": "gytri-julia"
  }
};