export default {
  "metadata": {
    "results": 337,
    "timeStamp": "2025-12-05T21:25:40.862Z",
    "url": "https://www.doollee.com/PlaywrightsH/H_playwrights_g-l.php"
  },
  "authors": {
    "HGUYEN Hung": "hguyen-hung",
    "HIAASEN Carl": "hiaasen-carl",
    "HIAM Juliane": "hiam-juliane",
    "HIATT Joseph Ferron": "hiatt-joseph-ferron",
    "HIBBERD Jack": "hibberd-jack",
    "HIBBERD Tim": "hibberd-tim",
    "HIBBERDINE Peter": "hibberdine-peter",
    "HIBBERT Alun": "hibbert-alun",
    "HIBBERT Guy": "hibbert-guy",
    "HIBBS Shelby-Allison": "hibbs-shelby-allison",
    "HICKAM Homer": "hickam-homer",
    "HICKENLOOPER George L": "hickenlooper-george-l",
    "HICKEY Carol": "hickey-carol",
    "HICKEY Eugene": "hickey-eugene",
    "HICKEY J J": "hickey-j-j",
    "HICKEY Jerry": "hickey-jerry",
    "HICKEY Margaret": "hickey-margaret",
    "HICKEY Mike": "hickey-mike",
    "HICKEY Robert": "hickey-robert",
    "HICKEY Susan": "hickey-susan",
    "HICKMAN Craig": "hickman-craig",
    "HICKMAN Darryl": "hickman-darryl",
    "HICKMAN Derek": "hickman-derek",
    "HICKMAN Katy": "hickman-katy",
    "HICKMAN Natalie": "hickman-natalie",
    "HICKMAN Philip J": "hickman-philip-j",
    "HICKMAN Tremane": "hickman-tremane",
    "HICKS Bev": "hicks-bev",
    "HICKS Caitlin": "hicks-caitlin",
    "HICKS Carolyn": "hicks-carolyn",
    "HICKS Chris": "hicks-chris",
    "HICKS Erin": "hicks-erin",
    "HICKS James": "hicks-james",
    "HICKS Peter": "hicks-peter",
    "HICKS Rodney": "hicks-rodney",
    "HICKS Sander": "hicks-sander",
    "HICKS Terry": "hicks-terry",
    "HICKS Tom": "hicks-tom",
    "HICKS Tommy R": "hicks-tommy-r",
    "HICKS JR Hilly": "hicks-jr-hilly",
    "HICKSON Ella": "hickson-ella",
    "HICKSON James": "hickson-james",
    "HICKSON Mary": "hickson-mary",
    "HICKSON Tony": "hickson-tony",
    "HICTON Douglas": "hicton-douglas",
    "HIDALGO Claudia": "hidalgo-claudia",
    "HIDALGO Michael P": "hidalgo-michael-p",
    "HIDDEN GRIN ": "hidden-grin",
    "HIDE Louise": "hide-louise",
    "HIDGESON Paul": "hidgeson-paul",
    "HIENER J E": "hiener-j-e",
    "HIENER W": "hiener-w",
    "HIERONYMOUS BANG ": "hieronymous-bang",
    "HIGA Lori": "higa-lori",
    "HIGBEE Rand": "higbee-rand",
    "HIGGIN-HOUSER Alex": "higgin-houser-alex",
    "HIGGINS Charlotte": "higgins-charlotte",
    "HIGGINS Christopher": "higgins-christopher",
    "HIGGINS Colin": "higgins-colin",
    "HIGGINS Dave": "higgins-dave",
    "HIGGINS Dick": "higgins-dick",
    "HIGGINS Frank": "higgins-frank",
    "HIGGINS Joe": "higgins-joe",
    "HIGGINS Joel": "higgins-joel",
    "HIGGINS Maeve": "higgins-maeve",
    "HIGGINS Matt Crehan": "higgins-matt-crehan",
    "HIGGINS Matthew": "higgins-matthew",
    "HIGGINS Michael John": "higgins-michael-john",
    "HIGGINS Neil": "higgins-neil",
    "HIGGINS Paul": "higgins-paul",
    "HIGGINS Peter": "higgins-peter",
    "HIGGINS Peter M": "higgins-peter-m",
    "HIGGINS Phoebe": "higgins-phoebe",
    "HIGGINS Richard": "higgins-richard",
    "HIGGINS Rita Ann": "higgins-rita-ann",
    "HIGGINS Robert": "higgins-robert",
    "HIGGINS Ryan": "higgins-ryan",
    "HIGGINS Sandi": "higgins-sandi",
    "HIGGINS Sydney": "higgins-sydney",
    "HIGGINS Tess": "higgins-tess",
    "HIGGINS Thomas": "higgins-thomas",
    "HIGGINS Vincent": "higgins-vincent",
    "HIGGINSEN Vy": "higginsen-vy",
    "HIGGINSON Craig": "higginson-craig",
    "HIGGINSON John": "higginson-john",
    "HIGGINSON Steve": "higginson-steve",
    "HIGGONS Keith R": "higgons-keith-r",
    "HIGH Bernard G": "high-bernard-g",
    "HIGH Susan": "high-susan",
    "HIGHAM Emma": "higham-emma",
    "HIGHLY SPRUNG ": "highly-sprung",
    "HIGHTOWER Charlie": "hightower-charlie",
    "HIGHTOWER Diane": "hightower-diane",
    "HIGHTOWER Robert": "hightower-robert",
    "HIGHWAY Tomson": "highway-tomson",
    "HIGHWAY DINER ": "highway-diner",
    "HIGNETT Sean": "hignett-sean",
    "HIGO Jim": "higo-jim",
    "HIGSON Charlie": "higson-charlie",
    "HII Ming-Zhu": "hii-ming-zhu",
    "HIJINX THEATRE ": "hijinx-theatre",
    "HIKMET Nazim": "hikmet-nazim",
    "HILAIRE Patricia": "hilaire-patricia",
    "HILBE Katrin": "hilbe-katrin",
    "HILBURN James": "hilburn-james",
    "HILDEBRAND Karen": "hildebrand-karen",
    "HILDER David": "hilder-david",
    "HILDESHEIM Wolfgang": "hildesheim-wolfgang",
    "HILDESHEIMER Wolfgang": "hildesheimer-wolfgang",
    "HILDRETH John": "hildreth-john",
    "HILFINGER Sharmon J": "hilfinger-sharmon-j",
    "HILL Abram": "hill-abram",
    "HILL Ally": "hill-ally",
    "HILL Amy": "hill-amy",
    "HILL Andrew N": "hill-andrew-n",
    "HILL Armenter": "hill-armenter",
    "HILL Arnold": "hill-arnold",
    "HILL Barry": "hill-barry",
    "HILL Brendan": "hill-brendan",
    "HILL Brian": "hill-brian",
    "HILL Christopher William": "hill-christopher-william",
    "HILL Damon": "hill-damon",
    "HILL Daniel": "hill-daniel",
    "HILL Dave": "hill-dave",
    "HILL David": "hill-david",
    "HILL David (2)": "hill-david-2",
    "HILL David C": "hill-david-c",
    "HILL Declan": "hill-declan",
    "HILL Don": "hill-don",
    "HILL Douglas": "hill-douglas",
    "HILL Emily": "hill-emily",
    "HILL Ernestine": "hill-ernestine",
    "HILL Errol": "hill-errol",
    "HILL F": "hill-f",
    "HILL Gary Leon": "hill-gary-leon",
    "HILL Geoffrey": "hill-geoffrey",
    "HILL Gordon": "hill-gordon",
    "HILL Harry": "hill-harry",
    "HILL Heather": "hill-heather",
    "HILL Helen": "hill-helen",
    "HILL Ian W": "hill-ian-w",
    "HILL Jane": "hill-jane",
    "HILL Jean O": "hill-jean-o",
    "HILL Jeanette W": "hill-jeanette-w",
    "HILL Jessi D": "hill-jessi-d",
    "HILL Jo": "hill-jo",
    "HILL Joe": "hill-joe",
    "HILL John": "hill-john",
    "HILL John Wesley": "hill-john-wesley",
    "HILL Joshua": "hill-joshua",
    "HILL Julie": "hill-julie",
    "HILL Kay": "hill-kay",
    "HILL Ken": "hill-ken",
    "HILL Ken (1)": "hill-ken-1",
    "HILL Kenneth": "hill-kenneth",
    "HILL Kimberly": "hill-kimberly",
    "HILL Kirsten": "hill-kirsten",
    "HILL Lannie": "hill-lannie",
    "HILL Leslie": "hill-leslie",
    "HILL Louisa": "hill-louisa",
    "HILL Lucienne": "hill-lucienne",
    "HILL Maddie": "hill-maddie",
    "HILL Malcom": "hill-malcom",
    "HILL Mars": "hill-mars",
    "HILL Martin D": "hill-martin-d",
    "HILL Matt": "hill-matt",
    "HILL Maurice": "hill-maurice",
    "HILL Megan": "hill-megan",
    "HILL Michael": "hill-michael",
    "HILL Philip": "hill-philip",
    "HILL Rebecca": "hill-rebecca",
    "HILL Ryan": "hill-ryan",
    "HILL Samm": "hill-samm",
    "HILL Sheila": "hill-sheila",
    "HILL Susan": "hill-susan",
    "HILL Ted": "hill-ted",
    "HILL Thomas": "hill-thomas",
    "HILL Tim": "hill-tim",
    "HILL Tom": "hill-tom",
    "HILL V H": "hill-v-h",
    "HILLARD Shirley": "hillard-shirley",
    "HILLE Veda": "hille-veda",
    "HILLERT Margaret": "hillert-margaret",
    "HILLEY Seamus": "hilley-seamus",
    "HILLGARTNER Malcolm": "hillgartner-malcolm",
    "HILLHOUSE Larry": "hillhouse-larry",
    "HILLIARD Bob": "hilliard-bob",
    "HILLIARD Doris": "hilliard-doris",
    "HILLIARD Jane": "hilliard-jane",
    "HILLIARD Michael": "hilliard-michael",
    "HILLIER Robert P": "hillier-robert-p",
    "HILLING Anja": "hilling-anja",
    "HILLIS Anna": "hillis-anna",
    "HILLMAN Barry L": "hillman-barry-l",
    "HILLMAN Gerald": "hillman-gerald",
    "HILLMAN Jenifer": "hillman-jenifer",
    "HILLMANN Marilyn": "hillmann-marilyn",
    "HILLS Adam": "hills-adam",
    "HILLS Anne": "hills-anne",
    "HILLS Derek": "hills-derek",
    "HILLS Gary": "hills-gary",
    "HILLS Mike": "hills-mike",
    "HILLS Richard": "hills-richard",
    "HILLYARD Ainsley": "hillyard-ainsley",
    "HILTON Andrew": "hilton-andrew",
    "HILTON Daniel": "hilton-daniel",
    "HILTON Frank": "hilton-frank",
    "HILTON John": "hilton-john",
    "HILTON Joni": "hilton-joni",
    "HILTON Julian": "hilton-julian",
    "HILTON Julian K": "hilton-julian-k",
    "HILTON Nick": "hilton-nick",
    "HILTON Paula": "hilton-paula",
    "HILTON Peter": "hilton-peter",
    "HILTON Ralph": "hilton-ralph",
    "HILTON Sinclair": "hilton-sinclair",
    "HILTON Tony": "hilton-tony",
    "HILTZIK Scott": "hiltzik-scott",
    "HIMBERG Philip": "himberg-philip",
    "HIME Ed": "hime-ed",
    "HIMEBAUGH Amelia": "himebaugh-amelia",
    "HIMMELMAN Isaac": "himmelman-isaac",
    "HIMS Katie": "hims-katie",
    "HINATH Lucas": "hinath-lucas",
    "HINCH Joe": "hinch-joe",
    "HINCHLEY Pippa": "hinchley-pippa",
    "HINCHLIFF Luisa": "hinchliff-luisa",
    "HINCHLIFFE Arnold": "hinchliffe-arnold",
    "HIND Archie": "hind-archie",
    "HIND Claire": "hind-claire",
    "HINDE Liesl": "hinde-liesl",
    "HINDE Rodney": "hinde-rodney",
    "HINDELL Keith": "hindell-keith",
    "HINDEN Lucette": "hinden-lucette",
    "HINDERAKER Andrew": "hinderaker-andrew",
    "HINDLEY Donald": "hindley-donald",
    "HINDMAN David": "hindman-david",
    "HINDMAN James": "hindman-james",
    "HINDMAN Jim": "hindman-jim",
    "HINDMARSH Will": "hindmarsh-will",
    "HINDS Andrew": "hinds-andrew",
    "HINDS Andy": "hinds-andy",
    "HINDS Darryl": "hinds-darryl",
    "HINDS Jessica": "hinds-jessica",
    "HINDS Rickerby": "hinds-rickerby",
    "HINE Dan": "hine-dan",
    "HINE Paul": "hine-paul",
    "HINES Anne": "hines-anne",
    "HINES Barry": "hines-barry",
    "HINES David": "hines-david",
    "HINES Deirdre": "hines-deirdre",
    "HINES Derrek": "hines-derrek",
    "HINES Karen": "hines-karen",
    "HINES Kim": "hines-kim",
    "HINES Maurice": "hines-maurice",
    "HINES Phil": "hines-phil",
    "HINES Sandra": "hines-sandra",
    "HINGHAM Charles": "hingham-charles",
    "HINGLEY James": "hingley-james",
    "HINGLEY Ronald": "hingley-ronald",
    "HINGORANI Dominic": "hingorani-dominic",
    "HINKLE Cory": "hinkle-cory",
    "HINKLE Vernon": "hinkle-vernon",
    "HINKS Gerry": "hinks-gerry",
    "HINOJOSA Richard": "hinojosa-richard",
    "HINRICHS Renata": "hinrichs-renata",
    "HINTON Dudley": "hinton-dudley",
    "HINTON Gregory": "hinton-gregory",
    "HINTON John": "hinton-john",
    "HINTON Nigel": "hinton-nigel",
    "HINTON Peter": "hinton-peter",
    "HINTON S E": "hinton-s-e",
    "HINTON Tam": "hinton-tam",
    "HINTON JR James": "hinton-jr-james",
    "HINZE Karl J": "hinze-karl-j",
    "HIP-FLORES Rick": "hip-flores-rick",
    "HIPKENS Robert": "hipkens-robert",
    "HIPKIN J": "hipkin-j",
    "HIPKINS Billy": "hipkins-billy",
    "HIPKINS Robert": "hipkins-robert",
    "HIPPI Juha": "hippi-juha",
    "HIPPLE Stephanie M": "hipple-stephanie-m",
    "HIPPOLYTE Kendel": "hippolyte-kendel",
    "HIRABAYASHI Shawn B": "hirabayashi-shawn-b",
    "HIRD Jason": "hird-jason",
    "HIRDWALL Jacob": "hirdwall-jacob",
    "HIRO Dilip": "hiro-dilip",
    "HIROHAMA David": "hirohama-david",
    "HIRONS Rachel": "hirons-rachel",
    "HIROSE Brent": "hirose-brent",
    "HIROWATARI Tsunetoshi": "hirowatari-tsunetoshi",
    "HIRSCH Becky": "hirsch-becky",
    "HIRSCH Farrell": "hirsch-farrell",
    "HIRSCH Henric": "hirsch-henric",
    "HIRSCH Huck": "hirsch-huck",
    "HIRSCH Joshua": "hirsch-joshua",
    "HIRSCH Ken": "hirsch-ken",
    "HIRSCH Richard Martin": "hirsch-richard-martin",
    "HIRSCH Vicki": "hirsch-vicki",
    "HIRSCHBEIN Peretz": "hirschbein-peretz",
    "HIRSCHBERG Laura": "hirschberg-laura",
    "HIRSCHFIELD Muriel": "hirschfield-muriel",
    "HIRSCHHORN Elizabeth": "hirschhorn-elizabeth",
    "HIRSCHHORN Joel": "hirschhorn-joel",
    "HIRSCHMAN Aliza": "hirschman-aliza",
    "HIRSEN Ron": "hirsen-ron",
    "HIRSHBEIN Peretz": "hirshbein-peretz",
    "HIRSON David": "hirson-david",
    "HIRSON Roger O": "hirson-roger-o",
    "HIRST David": "hirst-david",
    "HIRST Garnet": "hirst-garnet",
    "HIRST Olivia": "hirst-olivia",
    "HIRST Stephen": "hirst-stephen",
    "HIRSTON Bobby": "hirston-bobby",
    "HIRSTREET Michael": "hirstreet-michael",
    "HIRTH Paula": "hirth-paula",
    "HIRZEL David": "hirzel-david",
    "HISCHAK Gregory": "hischak-gregory",
    "HISCHAK Thomas": "hischak-thomas",
    "HISCOCK Catherine": "hiscock-catherine",
    "HISCOTT Gillian": "hiscott-gillian",
    "HISLOP Ian": "hislop-ian",
    "HISLOP Susanna": "hislop-susanna",
    "HISSONG Terrence Craig": "hissong-terrence-craig",
    "HITCHAOUGH Jim": "hitchaough-jim",
    "HITCHCOCK Geoffrey": "hitchcock-geoffrey",
    "HITCHCOCK Jane Stanton": "hitchcock-jane-stanton",
    "HITCHEN Tracy": "hitchen-tracy",
    "HITCHENS Shawn": "hitchens-shawn",
    "HITCHMOUGH Jim": "hitchmough-jim",
    "HITCHNER Anne": "hitchner-anne",
    "HITE Rick": "hite-rick",
    "HITREC Hrvoje": "hitrec-hrvoje",
    "HIUNI Dahn": "hiuni-dahn",
    "HIVNOR Mary": "hivnor-mary",
    "HIVNOR Robert": "hivnor-robert",
    "HIXSON Lin": "hixson-lin"
  }
};