export default {
  "metadata": {
    "results": 884,
    "timeStamp": "2025-12-05T21:25:50.180Z",
    "url": "https://www.doollee.com/PlaywrightsH/H_playwrights_m-r.php"
  },
  "authors": {
    "HNATH Lucas": "hnath-lucas",
    "HO Daniel": "ho-daniel",
    "HO Fred": "ho-fred",
    "HO Howard": "ho-howard",
    "HO Isaac": "ho-isaac",
    "HO Kim": "ho-kim",
    "HO Minfong": "ho-minfong",
    "HOAAS Solrun": "hoaas-solrun",
    "HOACHIN' STUSHIE ": "hoachin-stushie",
    "HOAG Jason D": "hoag-jason-d",
    "HOAK Jackie": "hoak-jackie",
    "HOAR Peter": "hoar-peter",
    "HOAR Stuart": "hoar-stuart",
    "HOARE Ken": "hoare-ken",
    "HOARE Tim": "hoare-tim",
    "HOASHI Keisuke": "hoashi-keisuke",
    "HOBAN Russell": "hoban-russell",
    "HOBART Dotty": "hobart-dotty",
    "HOBART George V": "hobart-george-v",
    "HOBART Liz": "hobart-liz",
    "HOBART Lois J": "hobart-lois-j",
    "HOBARTNER Elisabeth": "hobartner-elisabeth",
    "HOBBA Julian": "hobba-julian",
    "HOBBES Dwight": "hobbes-dwight",
    "HOBBINS Malcolm": "hobbins-malcolm",
    "HOBBINS Mat": "hobbins-mat",
    "HOBBS Becky": "hobbs-becky",
    "HOBBS Ben": "hobbs-ben",
    "HOBBS Greg": "hobbs-greg",
    "HOBBS J Kline": "hobbs-j-kline",
    "HOBBS Jenna May": "hobbs-jenna-may",
    "HOBBS Joe": "hobbs-joe",
    "HOBBS Jules": "hobbs-jules",
    "HOBBS Margaret May": "hobbs-margaret-may",
    "HOBBS Martyn": "hobbs-martyn",
    "HOBDAY Nicki": "hobday-nicki",
    "HOBDAY Peter": "hobday-peter",
    "HOBGOOD Andrew": "hobgood-andrew",
    "HOBIN Timothy": "hobin-timothy",
    "HOBKINSON Caroline": "hobkinson-caroline",
    "HOBLER Randolph": "hobler-randolph",
    "HOBSBAUM Phillip": "hobsbaum-phillip",
    "HOBSON Daniel": "hobson-daniel",
    "HOBSON Louis B": "hobson-louis-b",
    "HOBSON Sally": "hobson-sally",
    "HOCH Danny": "hoch-danny",
    "HOCHE Jon": "hoche-jon",
    "HOCHHAUSER Jeff": "hochhauser-jeff",
    "HOCHHEISER Linda": "hochheiser-linda",
    "HOCHHUTH Rolf": "hochhuth-rolf",
    "HOCHTNER A E": "hochtner-a-e",
    "HOCHWALDER Fritz": "hochwalder-fritz",
    "HOCK Oana-Maria": "hock-oana-maria",
    "HOCK Robert D": "hock-robert-d",
    "HOCKADAY Barbara": "hockaday-barbara",
    "HOCKADAY Lindsay": "hockaday-lindsay",
    "HOCKING Kate-Lynn": "hocking-kate-lynn",
    "HOCKLEY Megan": "hockley-megan",
    "HODAK Christine": "hodak-christine",
    "HODARA Susan": "hodara-susan",
    "HODD Mike": "hodd-mike",
    "HODDA Julian": "hodda-julian",
    "HODDA Noel": "hodda-noel",
    "HODDINOTT Derek": "hoddinott-derek",
    "HODDINOTT Pat": "hoddinott-pat",
    "HODDLE D": "hoddle-d",
    "HODERA Leonard": "hodera-leonard",
    "HODGE Amy": "hodge-amy",
    "HODGE Chinaka": "hodge-chinaka",
    "HODGE Douglas": "hodge-douglas",
    "HODGE John": "hodge-john",
    "HODGE Michael": "hodge-michael",
    "HODGE Paul": "hodge-paul",
    "HODGE Pol": "hodge-pol",
    "HODGE Robert W": "hodge-robert-w",
    "HODGE Sandra D": "hodge-sandra-d",
    "HODGE Stephen": "hodge-stephen",
    "HODGE Tia Dionne": "hodge-tia-dionne",
    "HODGE-HAMPTON Sandra": "hodge-hampton-sandra",
    "HODGES Adrian": "hodges-adrian",
    "HODGES Chas": "hodges-chas",
    "HODGES Colin": "hodges-colin",
    "HODGES Jackie": "hodges-jackie",
    "HODGES Jesse J": "hodges-jesse-j",
    "HODGES Michael": "hodges-michael",
    "HODGES Mike": "hodges-mike",
    "HODGES Sara Fischer": "hodges-sara-fischer",
    "HODGES Thomas": "hodges-thomas",
    "HODGES Tiffany": "hodges-tiffany",
    "HODGETTS Susan": "hodgetts-susan",
    "HODGKINSON Constance": "hodgkinson-constance",
    "HODGKINSON Jacob": "hodgkinson-jacob",
    "HODGKINSON Jean": "hodgkinson-jean",
    "HODGKINSON Margaret H": "hodgkinson-margaret-h",
    "HODGSON Corrina": "hodgson-corrina",
    "HODGSON Harold": "hodgson-harold",
    "HODGSON Natasha": "hodgson-natasha",
    "HODGSON Sheila": "hodgson-sheila",
    "HODGSON Tracie": "hodgson-tracie",
    "HODKINS Don": "hodkins-don",
    "HODSOLL Lisa": "hodsoll-lisa",
    "HODSON Chris": "hodson-chris",
    "HODSON J L": "hodson-j-l",
    "HODSON Mathew": "hodson-mathew",
    "HODSON Paul": "hodson-paul",
    "HOECK Mary": "hoeck-mary",
    "HOEFFEL Rachel": "hoeffel-rachel",
    "HOEFNER Tom": "hoefner-tom",
    "HOEGGER Gitta": "hoegger-gitta",
    "HOEHLER Richard": "hoehler-richard",
    "HOEHN Max": "hoehn-max",
    "HOELCFFENER Larry": "hoelcffener-larry",
    "HOELLE Nicole": "hoelle-nicole",
    "HOELZEL Thomas": "hoelzel-thomas",
    "HOENIG Marion": "hoenig-marion",
    "HOENIG Ron": "hoenig-ron",
    "HOERNER Mary Beth": "hoerner-mary-beth",
    "HOERSCH Joanne": "hoersch-joanne",
    "HOESL Joseph": "hoesl-joseph",
    "HOFBAUER Hayley": "hofbauer-hayley",
    "HOFBERG David": "hofberg-david",
    "HOFELD Elizabeth Suzanne": "hofeld-elizabeth-suzanne",
    "HOFF Syd": "hoff-syd",
    "HOFFBAUER Patricia": "hoffbauer-patricia",
    "HOFFER Eben": "hoffer-eben",
    "HOFFMAN Avi": "hoffman-avi",
    "HOFFMAN Benjamin": "hoffman-benjamin",
    "HOFFMAN Bill": "hoffman-bill",
    "HOFFMAN C S": "hoffman-c-s",
    "HOFFMAN Cary": "hoffman-cary",
    "HOFFMAN Catherine": "hoffman-catherine",
    "HOFFMAN Frances": "hoffman-frances",
    "HOFFMAN Francis": "hoffman-francis",
    "HOFFMAN Gordy": "hoffman-gordy",
    "HOFFMAN Guy": "hoffman-guy",
    "HOFFMAN Heinrich": "hoffman-heinrich",
    "HOFFMAN Jeff": "hoffman-jeff",
    "HOFFMAN Joseph": "hoffman-joseph",
    "HOFFMAN Kate": "hoffman-kate",
    "HOFFMAN Lauran": "hoffman-lauran",
    "HOFFMAN Lynn": "hoffman-lynn",
    "HOFFMAN Maggie": "hoffman-maggie",
    "HOFFMAN Margaret": "hoffman-margaret",
    "HOFFMAN Michael": "hoffman-michael",
    "HOFFMAN Miriam": "hoffman-miriam",
    "HOFFMAN Nan Laura": "hoffman-nan-laura",
    "HOFFMAN Richard Lee": "hoffman-richard-lee",
    "HOFFMAN Roald": "hoffman-roald",
    "HOFFMAN Sandra": "hoffman-sandra",
    "HOFFMAN Stephen": "hoffman-stephen",
    "HOFFMAN Theodore": "hoffman-theodore",
    "HOFFMAN Warren": "hoffman-warren",
    "HOFFMAN William M": "hoffman-william-m",
    "HOFFMANN B": "hoffmann-b",
    "HOFFMANN Catherine": "hoffmann-catherine",
    "HOFFMANN Jessica": "hoffmann-jessica",
    "HOFFMANN Kristin Skye": "hoffmann-kristin-skye",
    "HOFFMANN-GILL Daniel": "hoffmann-gill-daniel",
    "HOFFOWER Kate": "hoffower-kate",
    "HOFMANN Gert": "hofmann-gert",
    "HOFMANN Jackob G": "hofmann-jackob-g",
    "HOFMANN Michael": "hofmann-michael",
    "HOFSISS Jack": "hofsiss-jack",
    "HOGAN Allyson": "hogan-allyson",
    "HOGAN Ben": "hogan-ben",
    "HOGAN Brendan": "hogan-brendan",
    "HOGAN Brianne": "hogan-brianne",
    "HOGAN Darcy": "hogan-darcy",
    "HOGAN Desmond": "hogan-desmond",
    "HOGAN Frank": "hogan-frank",
    "HOGAN Harlan": "hogan-harlan",
    "HOGAN James": "hogan-james",
    "HOGAN Julia": "hogan-julia",
    "HOGAN Linda": "hogan-linda",
    "HOGAN Michael": "hogan-michael",
    "HOGAN Patrick": "hogan-patrick",
    "HOGAN Philip Michael": "hogan-philip-michael",
    "HOGAN PJ": "hogan-p-j",
    "HOGAN Robert": "hogan-robert",
    "HOGAN Sean": "hogan-sean",
    "HOGAN Stefan M": "hogan-stefan-m",
    "HOGAN Zoe": "hogan-zoe",
    "HOGAN COYLE P": "hogan-coyle-p",
    "HOGAN II Andre R": "hogan-ii-andre-r",
    "HOGARTH Nick": "hogarth-nick",
    "HOGG Anne": "hogg-anne",
    "HOGG Christopher": "hogg-christopher",
    "HOGG Clare Dwyer": "hogg-clare-dwyer",
    "HOGG Gladys M": "hogg-gladys-m",
    "HOGG James": "hogg-james",
    "HOGG Jimmy": "hogg-jimmy",
    "HOGGARTH John": "hoggarth-john",
    "HOGGER Richard": "hogger-richard",
    "HOGGETT Steven": "hoggett-steven",
    "HOGHE Raimund": "hoghe-raimund",
    "HOGUE James": "hogue-james",
    "HOGUE Muriel": "hogue-muriel",
    "HOHKI Kazuko": "hohki-kazuko",
    "HOHMANN Christine": "hohmann-christine",
    "HOHORST Frederick August": "hohorst-frederick-august",
    "HOI YUN CHAN Catherine": "hoi-yun-chan-catherine",
    "HOILE Edward V": "hoile-edward-v",
    "HOILE Helen": "hoile-helen",
    "HOIPOLLOI ": "hoipolloi",
    "HOKE Donna": "hoke-donna",
    "HOKE-WITHERSPOON Kenneth F": "hoke-witherspoon-kenneth-f",
    "HOLAHAN Breffini": "holahan-breffini",
    "HOLBECHE Yvonne": "holbeche-yvonne",
    "HOLBERG Ludwig": "holberg-ludwig",
    "HOLBOROUGH Jacqueline": "holborough-jacqueline",
    "HOLBROOK Andrea": "holbrook-andrea",
    "HOLBROOK Ben": "holbrook-ben",
    "HOLBROOK Chris": "holbrook-chris",
    "HOLBROOK David": "holbrook-david",
    "HOLBROOK Joanne": "holbrook-joanne",
    "HOLBROOK Marion": "holbrook-marion",
    "HOLBY Jonathan": "holby-jonathan",
    "HOLCENBERG David": "holcenberg-david",
    "HOLCOLM Allison M": "holcolm-allison-m",
    "HOLCOM Chris": "holcom-chris",
    "HOLCOMB Justin R G": "holcomb-justin-r-g",
    "HOLCROFT Jonathan": "holcroft-jonathan",
    "HOLCROFT Sam": "holcroft-sam",
    "HOLCROFT Tombasden": "holcroft-tombasden",
    "HOLDEN Andy": "holden-andy",
    "HOLDEN Arthur": "holden-arthur",
    "HOLDEN Brian": "holden-brian",
    "HOLDEN C": "holden-c",
    "HOLDEN Henry": "holden-henry",
    "HOLDEN Joan": "holden-joan",
    "HOLDEN Judith": "holden-judith",
    "HOLDEN Kate": "holden-kate",
    "HOLDEN Len": "holden-len",
    "HOLDEN-BASHAR Kelly": "holden-bashar-kelly",
    "HOLDER Bobby": "holder-bobby",
    "HOLDER Carl": "holder-carl",
    "HOLDER Iona": "holder-iona",
    "HOLDER Jakob": "holder-jakob",
    "HOLDER James Wesley": "holder-james-wesley",
    "HOLDER Jirah Breon": "holder-jirah-breon",
    "HOLDER Judith": "holder-judith",
    "HOLDER Kanene": "holder-kanene",
    "HOLDER Laurence": "holder-laurence",
    "HOLDER Leopold": "holder-leopold",
    "HOLDER Owen": "holder-owen",
    "HOLDER Rachel": "holder-rachel",
    "HOLDERLIN Frederich": "holderlin-frederich",
    "HOLDING Jane": "holding-jane",
    "HOLDORF C": "holdorf-c",
    "HOLDRIDGE Eleanor": "holdridge-eleanor",
    "HOLDSWORTH Lisa": "holdsworth-lisa",
    "HOLDSWORTH Richard": "holdsworth-richard",
    "HOLE Rick": "hole-rick",
    "HOLEMAN Julia": "holeman-julia",
    "HOLETS George": "holets-george",
    "HOLGATE Michael": "holgate-michael",
    "HOLGATE Ron": "holgate-ron",
    "HOLIDAY Christian": "holiday-christian",
    "HOLKNER Jean": "holkner-jean",
    "HOLLADAY Kevin": "holladay-kevin",
    "HOLLAND Aaron": "holland-aaron",
    "HOLLAND Alec": "holland-alec",
    "HOLLAND Amy Lynne": "holland-amy-lynne",
    "HOLLAND Andrew": "holland-andrew",
    "HOLLAND Anthony": "holland-anthony",
    "HOLLAND Bill": "holland-bill",
    "HOLLAND Brian": "holland-brian",
    "HOLLAND Clive": "holland-clive",
    "HOLLAND Craig": "holland-craig",
    "HOLLAND Dorothy": "holland-dorothy",
    "HOLLAND Eddie": "holland-eddie",
    "HOLLAND Edward J": "holland-edward-j",
    "HOLLAND Endesha Ida Mae": "holland-endesha-ida-mae",
    "HOLLAND Fannon": "holland-fannon",
    "HOLLAND Gerry": "holland-gerry",
    "HOLLAND Guy": "holland-guy",
    "HOLLAND James": "holland-james",
    "HOLLAND Jeffrey": "holland-jeffrey",
    "HOLLAND Kate": "holland-kate",
    "HOLLAND Kristine": "holland-kristine",
    "HOLLAND Llysa": "holland-llysa",
    "HOLLAND Merlin": "holland-merlin",
    "HOLLAND Michael": "holland-michael",
    "HOLLAND Michael (1)": "holland-michael-1",
    "HOLLAND Nicki": "holland-nicki",
    "HOLLAND Norman": "holland-norman",
    "HOLLAND Paul Kessell": "holland-paul-kessell",
    "HOLLAND Peter": "holland-peter",
    "HOLLAND Sharon": "holland-sharon",
    "HOLLAND Stevie": "holland-stevie",
    "HOLLAND Taylor": "holland-taylor",
    "HOLLAND Tom": "holland-tom",
    "HOLLAND Walter": "holland-walter",
    "HOLLAND, JR Edward": "holland-jr-edward",
    "HOLLANDER Anita": "hollander-anita",
    "HOLLANDER Jaron": "hollander-jaron",
    "HOLLANDS Guy": "hollands-guy",
    "HOLLANDS Sjahari": "hollands-sjahari",
    "HOLLEMAN John": "holleman-john",
    "HOLLEMAN Julia": "holleman-julia",
    "HOLLEMAN Warren": "holleman-warren",
    "HOLLENBACH Bill": "hollenbach-bill",
    "HOLLENBACH Shawn": "hollenbach-shawn",
    "HOLLES Robert": "holles-robert",
    "HOLLEY Pat": "holley-pat",
    "HOLLEY-HORSEMAN Sam": "holley-horseman-sam",
    "HOLLIDAY Graham": "holliday-graham",
    "HOLLIDAY John": "holliday-john",
    "HOLLIDAY Joyce": "holliday-joyce",
    "HOLLIDAY Mandy": "holliday-mandy",
    "HOLLIDAY Sheena": "holliday-sheena",
    "HOLLIMAN O C": "holliman-o-c",
    "HOLLINGER Michael": "hollinger-michael",
    "HOLLINGHURST Alan": "hollinghurst-alan",
    "HOLLINGSHEAD Iain": "hollingshead-iain",
    "HOLLINGSWORTH Chris": "hollingsworth-chris",
    "HOLLINGSWORTH Margaret": "hollingsworth-margaret",
    "HOLLINGSWORTH Michael": "hollingsworth-michael",
    "HOLLINGWORTH Andrew": "hollingworth-andrew",
    "HOLLINGWORTH Guy": "hollingworth-guy",
    "HOLLINGWORTH John": "hollingworth-john",
    "HOLLINSON Jayne": "hollinson-jayne",
    "HOLLIS Dave": "hollis-dave",
    "HOLLISTER Sarah": "hollister-sarah",
    "HOLLMAN Jeff": "hollman-jeff",
    "HOLLMAN Jeffrey L": "hollman-jeffrey-l",
    "HOLLMANN Mark": "hollmann-mark",
    "HOLLO Anselm": "hollo-anselm",
    "HOLLO Tamsin": "hollo-tamsin",
    "HOLLOWAY Ann": "holloway-ann",
    "HOLLOWAY Arnett J": "holloway-arnett-j",
    "HOLLOWAY Ashley G": "holloway-ashley-g",
    "HOLLOWAY C Robert": "holloway-c-robert",
    "HOLLOWAY Jack": "holloway-jack",
    "HOLLOWAY Jonathan": "holloway-jonathan",
    "HOLLOWAY Levi": "holloway-levi",
    "HOLLOWAY Nigel": "holloway-nigel",
    "HOLLOWAY Patti": "holloway-patti",
    "HOLLOWAY Sister MarcElla Marie": "holloway-sister-marcella-marie",
    "HOLLOWAY Taberah Joy": "holloway-taberah-joy",
    "HOLLOWAY Tom": "holloway-tom",
    "HOLLOWAY Tom H C": "holloway-tom-h-c",
    "HOLLUM Suli": "hollum-suli",
    "HOLLYWOOD Daniel": "hollywood-daniel",
    "HOLLYWOOD John": "hollywood-john",
    "HOLM Janis Butler": "holm-janis-butler",
    "HOLM John Cecil": "holm-john-cecil",
    "HOLM Peter": "holm-peter",
    "HOLMAN Amaya": "holman-amaya",
    "HOLMAN Bob": "holman-bob",
    "HOLMAN David": "holman-david",
    "HOLMAN Hunt": "holman-hunt",
    "HOLMAN M Carl": "holman-m-carl",
    "HOLMAN Robbi D": "holman-robbi-d",
    "HOLMAN Robert": "holman-robert",
    "HOLMAN Scott": "holman-scott",
    "HOLMBERG Steven": "holmberg-steven",
    "HOLME Christopher": "holme-christopher",
    "HOLME Constance": "holme-constance",
    "HOLME H E": "holme-h-e",
    "HOLME Stanford": "holme-stanford",
    "HOLME Timothy": "holme-timothy",
    "HOLMES Andrew": "holmes-andrew",
    "HOLMES B L": "holmes-b-l",
    "HOLMES Bretton B": "holmes-bretton-b",
    "HOLMES Christopher": "holmes-christopher",
    "HOLMES Davey": "holmes-davey",
    "HOLMES Dyron": "holmes-dyron",
    "HOLMES Eddie": "holmes-eddie",
    "HOLMES Federay": "holmes-federay",
    "HOLMES Gary": "holmes-gary",
    "HOLMES Graeme": "holmes-graeme",
    "HOLMES Jack": "holmes-jack",
    "HOLMES Jake": "holmes-jake",
    "HOLMES Jasper": "holmes-jasper",
    "HOLMES Jesse N": "holmes-jesse-n",
    "HOLMES Jill": "holmes-jill",
    "HOLMES Jonathan": "holmes-jonathan",
    "HOLMES K J": "holmes-k-j",
    "HOLMES Kat": "holmes-kat",
    "HOLMES Martin": "holmes-martin",
    "HOLMES Matthew": "holmes-matthew",
    "HOLMES Natasha": "holmes-natasha",
    "HOLMES Prudence Wright": "holmes-prudence-wright",
    "HOLMES Rupert": "holmes-rupert",
    "HOLMES Sarah Bebe": "holmes-sarah-bebe",
    "HOLMES Shannon": "holmes-shannon",
    "HOLMES Shirlene": "holmes-shirlene",
    "HOLMES Viki": "holmes-viki",
    "HOLMGREN Maxine": "holmgren-maxine",
    "HOLMSTROM John": "holmstrom-john",
    "HOLMSTROM Ronald O": "holmstrom-ronald-o",
    "HOLNES Darrel": "holnes-darrel",
    "HOLNESS Matthew": "holness-matthew",
    "HOLODY Dick": "holody-dick",
    "HOLOF Georgia Bogardus": "holof-georgia-bogardus",
    "HOLOFCENER Lawrence": "holofcener-lawrence",
    "HOLOYDA Christopher": "holoyda-christopher",
    "HOLROYD G H": "holroyd-g-h",
    "HOLROYD Stuart": "holroyd-stuart",
    "HOLSCLAW Doug": "holsclaw-doug",
    "HOLSEN Hans": "holsen-hans",
    "HOLSEY Ron": "holsey-ron",
    "HOLSON Nancy": "holson-nancy",
    "HOLSON-SCHWARTZ Amy": "holson-schwartz-amy",
    "HOLSOPPLE Ryan": "holsopple-ryan",
    "HOLSTED Jo": "holsted-jo",
    "HOLSTEIN Barbara": "holstein-barbara",
    "HOLSTEIN David": "holstein-david",
    "HOLT A-lan": "holt-a-lan",
    "HOLT Alexander": "holt-alexander",
    "HOLT Clifford": "holt-clifford",
    "HOLT D": "holt-d",
    "HOLT Jim": "holt-jim",
    "HOLT John R": "holt-john-r",
    "HOLT Liz": "holt-liz",
    "HOLT Louis": "holt-louis",
    "HOLT Maria": "holt-maria",
    "HOLT Marion Peter": "holt-marion-peter",
    "HOLT Monique": "holt-monique",
    "HOLT Rochelle Lynn": "holt-rochelle-lynn",
    "HOLT Stephen": "holt-stephen",
    "HOLT Timm": "holt-timm",
    "HOLT Will": "holt-will",
    "HOLTBY Winifred": "holtby-winifred",
    "HOLTER Ike": "holter-ike",
    "HOLTHAM J": "holtham-j",
    "HOLTOM Robert": "holtom-robert",
    "HOLTON Lew": "holton-lew",
    "HOLTZ Douglas": "holtz-douglas",
    "HOLTZ Gregory A": "holtz-gregory-a",
    "HOLTZ Laura": "holtz-laura",
    "HOLTZ Martin": "holtz-martin",
    "HOLTZAPPLE Sam": "holtzapple-sam",
    "HOLTZCLAW Matthew": "holtzclaw-matthew",
    "HOLTZMAN Willy": "holtzman-willy",
    "HOLUB Lisa Margaret": "holub-lisa-margaret",
    "HOLUM Suli": "holum-suli",
    "HOLWELL Ash": "holwell-ash",
    "HOLYOAKE Emily": "holyoake-emily",
    "HOLZER Hans": "holzer-hans",
    "HOLZKNECHT G K": "holzknecht-g-k",
    "HOLZMAN Laurence": "holzman-laurence",
    "HOLZMAN Terry Anne": "holzman-terry-anne",
    "HOLZMAN Winnie": "holzman-winnie",
    "HOM Rodney": "hom-rodney",
    "HOMAN Richard": "homan-richard",
    "HOME Jefferey": "home-jefferey",
    "HOME William Douglas": "home-william-douglas",
    "HOMER Jean": "homer-jean",
    "HOMER Keith": "homer-keith",
    "HOMER Mark": "homer-mark",
    "HOMMEL Beth": "hommel-beth",
    "HOMMEL David": "hommel-david",
    "HOMMEL Julie": "hommel-julie",
    "HOMMERSAND Hope": "hommersand-hope",
    "HOMOKAY Julianne": "homokay-julianne",
    "HOMOSEXUAL LIBERATION GROUP ": "homosexual-liberation-group",
    "HOMSBY Laurie": "homsby-laurie",
    "HONARD Justin": "honard-justin",
    "HONEGGER Gitta": "honegger-gitta",
    "HONESS-MARTIN Jacquelyn": "honess-martin-jacquelyn",
    "HONEY Joan": "honey-joan",
    "HONEYCOMBE Gordon": "honeycombe-gordon",
    "HONEYMAN Janice": "honeyman-janice",
    "HONEYWELL Robert": "honeywell-robert",
    "HONEYWILL Pamela S": "honeywill-pamela-s",
    "HONG Edison": "hong-edison",
    "HONG Howard Jonathan": "hong-howard-jonathan",
    "HONG Juyoung": "hong-juyoung",
    "HONG Neil Chue": "hong-neil-chue",
    "HONG Sin Cha": "hong-sin-cha",
    "HONIG Edwin": "honig-edwin",
    "HONNOR Seth": "honnor-seth",
    "HONOR Mary": "honor-mary",
    "HONOVICH Jessica": "honovich-jessica",
    "HOO Jasmin": "hoo-jasmin",
    "HOO Judy Soo": "hoo-judy-soo",
    "HOO Stephen": "hoo-stephen",
    "HOOD Basil": "hood-basil",
    "HOOD Dictynna": "hood-dictynna",
    "HOOD Duncan": "hood-duncan",
    "HOOD Evelyn": "hood-evelyn",
    "HOOD Jamey": "hood-jamey",
    "HOOD Kerry": "hood-kerry",
    "HOOD Kevin": "hood-kevin",
    "HOOD Lynley": "hood-lynley",
    "HOOD Stuart": "hood-stuart",
    "HOOGENDOORN Bruce": "hoogendoorn-bruce",
    "HOOGLAND Cornelia": "hoogland-cornelia",
    "HOOK Brian": "hook-brian",
    "HOOK James": "hook-james",
    "HOOKE Adrian": "hooke-adrian",
    "HOOKE Michael": "hooke-michael",
    "HOOKE Nina Warner": "hooke-nina-warner",
    "HOOKER Brian": "hooker-brian",
    "HOOKER Claire": "hooker-claire",
    "HOOKER Jake": "hooker-jake",
    "HOOKER Mark": "hooker-mark",
    "HOOKER Pat": "hooker-pat",
    "HOOKHITCH THEATRE ": "hookhitch-theatre",
    "HOOKS Joel": "hooks-joel",
    "HOOKS II Ulyses B": "hooks-ii-ulyses-b",
    "HOOLEY Ruth": "hooley-ruth",
    "HOOPER Ashley": "hooper-ashley",
    "HOOPER Ben": "hooper-ben",
    "HOOPER Ewan": "hooper-ewan",
    "HOOPER Laura": "hooper-laura",
    "HOOPER Martin": "hooper-martin",
    "HOOPER Robin": "hooper-robin",
    "HOOPER Tobe": "hooper-tobe",
    "HOOPER-HAMERSLY Samantha": "hooper-hamersly-samantha",
    "HOOPES Melanie": "hoopes-melanie",
    "HOORNEMAN Margaret": "hoorneman-margaret",
    "HOOVEN Evelyn": "hooven-evelyn",
    "HOOVER Alexandra": "hoover-alexandra",
    "HOOVER Andy James": "hoover-andy-james",
    "HOOVER Ben Nicholas": "hoover-ben-nicholas",
    "HOOVER Marjorie": "hoover-marjorie",
    "HOOVER Nicolas": "hoover-nicolas",
    "HOOVER Silas": "hoover-silas",
    "HOOVER Ted": "hoover-ted",
    "HOPE Alex": "hope-alex",
    "HOPE Dan": "hope-dan",
    "HOPE David Brendon": "hope-david-brendon",
    "HOPE Deborah": "hope-deborah",
    "HOPE Dorothy": "hope-dorothy",
    "HOPE Hommersand": "hope-hommersand",
    "HOPE Karen": "hope-karen",
    "HOPE Miranda": "hope-miranda",
    "HOPE Nicholas": "hope-nicholas",
    "HOPE Nicholas (1)": "hope-nicholas-1",
    "HOPE Richard": "hope-richard",
    "HOPE Sarah": "hope-sarah",
    "HOPE Tom": "hope-tom",
    "HOPE Wayne": "hope-wayne",
    "HOPES David Brendan": "hopes-david-brendan",
    "HOPF Janet": "hopf-janet",
    "HOPGOOD Alan": "hopgood-alan",
    "HOPGOOD Tim": "hopgood-tim",
    "HOPKINS Antony": "hopkins-antony",
    "HOPKINS Beau": "hopkins-beau",
    "HOPKINS Ben": "hopkins-ben",
    "HOPKINS Beth": "hopkins-beth",
    "HOPKINS Bill": "hopkins-bill",
    "HOPKINS C J": "hopkins-c-j",
    "HOPKINS Claire": "hopkins-claire",
    "HOPKINS Cynthia": "hopkins-cynthia",
    "HOPKINS David": "hopkins-david",
    "HOPKINS Eirwen": "hopkins-eirwen",
    "HOPKINS Elly": "hopkins-elly",
    "HOPKINS Emma": "hopkins-emma",
    "HOPKINS Erin": "hopkins-erin",
    "HOPKINS Glenn": "hopkins-glenn",
    "HOPKINS Helen": "hopkins-helen",
    "HOPKINS I B": "hopkins-i-b",
    "HOPKINS Jay": "hopkins-jay",
    "HOPKINS John": "hopkins-john",
    "HOPKINS Linda": "hopkins-linda",
    "HOPKINS Loretta": "hopkins-loretta",
    "HOPKINS Lucy": "hopkins-lucy",
    "HOPKINS Matthew": "hopkins-matthew",
    "HOPKINS Ned": "hopkins-ned",
    "HOPKINS Raymond": "hopkins-raymond",
    "HOPKINS Robin": "hopkins-robin",
    "HOPKINS Simon": "hopkins-simon",
    "HOPKINS Sophi Sagall": "hopkins-sophi-sagall",
    "HOPKINS Suzi": "hopkins-suzi",
    "HOPKINS U T": "hopkins-u-t",
    "HOPKINSON Laura": "hopkinson-laura",
    "HOPKINSON Matthew": "hopkinson-matthew",
    "HOPKINSON Simon": "hopkinson-simon",
    "HOPLEY Lizzie": "hopley-lizzie",
    "HOPLEY Steven": "hopley-steven",
    "HOPP Lisa": "hopp-lisa",
    "HOPPE Gip": "hoppe-gip",
    "HOPPE-HOUSE Jennifer": "hoppe-house-jennifer",
    "HOPPE-LONG Michelle Caroline": "hoppe-long-michelle-caroline",
    "HOPPER Duncan": "hopper-duncan",
    "HOPPER John": "hopper-john",
    "HORAK Bruce": "horak-bruce",
    "HORAN Adelind": "horan-adelind",
    "HORAN Tom": "horan-tom",
    "HORDER Dzindra": "horder-dzindra",
    "HORDER John": "horder-john",
    "HOREIS Vit": "horejs-vit",
    "HORGAN Matt": "horgan-matt",
    "HORGER Jeff": "horger-jeff",
    "HORINE Charles": "horine-charles",
    "HORITZ Tony": "horitz-tony",
    "HORKIN Zita": "horkin-zita",
    "HORLER Ken": "horler-ken",
    "HORLOCK David": "horlock-david",
    "HORN Donnie": "horn-donnie",
    "HORN Marek": "horn-marek",
    "HORN Robert": "horn-robert",
    "HORN William Andrew": "horn-william-andrew",
    "HORNAL Daniel": "hornal-daniel",
    "HORNBLOW JR Arthur": "hornblow-jr-arthur",
    "HORNBUCKLE Paola Soto": "hornbuckle-paola-soto",
    "HORNBY Angela": "hornby-angela",
    "HORNBY Ian": "hornby-ian",
    "HORNBY June": "hornby-june",
    "HORNBY Richard": "hornby-richard",
    "HORNBY Stephen M": "hornby-stephen-m",
    "HORNE David": "horne-david",
    "HORNE David (1)": "horne-david-1",
    "HORNE Jeffrey": "horne-jeffrey",
    "HORNE Jules": "horne-jules",
    "HORNE Kenneth": "horne-kenneth",
    "HORNE Kevin": "horne-kevin",
    "HORNE Lederick": "horne-lederick",
    "HORNER John Arthur": "horner-john-arthur",
    "HORNER Kristen": "horner-kristen",
    "HORNER Mark": "horner-mark",
    "HORNICK Neil": "hornick-neil",
    "HORNSBY Adrian": "hornsby-adrian",
    "HORNSBY Kristin": "hornsby-kristin",
    "HORNSBY Laurie": "hornsby-laurie",
    "HORNUNG Brianne": "hornung-brianne",
    "HOROBIN Gilbert": "horobin-gilbert",
    "HOROSCAK Marek": "horoscak-marek",
    "HOROVITZ Adam": "horovitz-adam",
    "HOROVITZ Israel": "horovitz-israel",
    "HOROVITZ Joseph": "horovitz-joseph",
    "HOROWITZ Alexander": "horowitz-alexander",
    "HOROWITZ Anthony": "horowitz-anthony",
    "HOROWITZ Dan": "horowitz-dan",
    "HOROWITZ Jimmy": "horowitz-jimmy",
    "HOROWITZ Joanna": "horowitz-joanna",
    "HOROWITZ Nicole": "horowitz-nicole",
    "HOROWITZ Susan": "horowitz-susan",
    "HORRIGAN Dan": "horrigan-dan",
    "HORRIGAN Dan (1)": "horrigan-dan-1",
    "HORRIGAN Jack": "horrigan-jack",
    "HORROCKS Christy": "horrocks-christy",
    "HORROCKS Jane": "horrocks-jane",
    "HORROCKS-HOPAYIAN Cevanne": "horrocks-hopayian-cevanne",
    "HORSBURGH Elizabeth": "horsburgh-elizabeth",
    "HORSBURGH Jan": "horsburgh-jan",
    "HORSBURGH Janine": "horsburgh-janine",
    "HORSE Harry": "horse-harry",
    "HORSFIELD Debbie": "horsfield-debbie",
    "HORSLEN Ben": "horslen-ben",
    "HORSLER Peter": "horsler-peter",
    "HORSNELL Horace": "horsnell-horace",
    "HORSPOOL Michael": "horspool-michael",
    "HORST Phil": "horst-phil",
    "HORT Lenny": "hort-lenny",
    "HORTIE Reed": "hortie-reed",
    "HORTON Caroline": "horton-caroline",
    "HORTON G L": "horton-g-l",
    "HORTON Geralyn": "horton-geralyn",
    "HORTON Joanna": "horton-joanna",
    "HORTON Joseph": "horton-joseph",
    "HORTON Tom": "horton-tom",
    "HORTUA Joe": "hortua-joe",
    "HORVAT Martin": "horvat-martin",
    "HORVATH Beverly": "horvath-beverly",
    "HORVATH Ian": "horvath-ian",
    "HORVATH Russell Alex": "horvath-russell-alex",
    "HORWICH Steven David": "horwich-steven-david",
    "HORWIN Jerry": "horwin-jerry",
    "HORWIN Louis": "horwin-louis",
    "HORWITT Arnold B": "horwitt-arnold-b",
    "HORWITZ Benjamin A": "horwitz-benjamin-a",
    "HORWITZ Murray": "horwitz-murray",
    "HORWOOD Craig Revel": "horwood-craig-revel",
    "HORWOOD Joel": "horwood-joel",
    "HOSCHNA Carl": "hoschna-carl",
    "HOSE Peter": "hose-peter",
    "HOSEIN Carla": "hosein-carla",
    "HOSHI Ryohei": "hoshi-ryohei",
    "HOSHINA Yuriko": "hoshina-yuriko",
    "HOSKER Stuart William": "hosker-stuart-william",
    "HOSKING Pauline": "hosking-pauline",
    "HOSKING Sandra": "hosking-sandra",
    "HOSKING Tiffany": "hosking-tiffany",
    "HOSKINS Bob": "hoskins-bob",
    "HOSKINS Brenda": "hoskins-brenda",
    "HOSOKAWA Momoko": "hosokawa-momoko",
    "HOSSAIN Taniya": "hossain-taniya",
    "HOSSAIN Tasnim": "hossain-tasnim",
    "HOSSEINPOUR Amir": "hosseinpour-amir",
    "HOT COALS THEATRE ENSEMBLE ": "hot-coals-theatre-ensemble",
    "HOT TUBS AND TRAMPOLINES ": "hot-tubs-and-trampolines",
    "HOTBUCKLE THEATRE COMPANY ": "hotbuckle-theatre-company",
    "HOTCHKIS Dan": "hotchkis-dan",
    "HOTCHKISS Frank": "hotchkiss-frank",
    "HOTCHNER A E": "hotchner-a-e",
    "HOTCHNER Kathy": "hotchner-kathy",
    "HOTCHNER Stephen": "hotchner-stephen",
    "HOTEL MODERN ": "hotel-modern",
    "HOTFORTHEATRE ": "hotfortheatre",
    "HOTTA Masaru": "hotta-masaru",
    "HOUBEN Jos": "houben-jos",
    "HOUGH Anthony": "hough-anthony",
    "HOUGH Aries Mi Hae": "hough-aries-mi-hae",
    "HOUGH Jon": "hough-jon",
    "HOUGH Julian": "hough-julian",
    "HOUGH Richard": "hough-richard",
    "HOUGHLY Young": "houghly-young",
    "HOUGHTAILING Ann Marie": "houghtailing-ann-marie",
    "HOUGHTON Brad Howell": "houghton-brad-howell",
    "HOUGHTON Jacki": "houghton-jacki",
    "HOUGHTON Jemma": "houghton-jemma",
    "HOUGHTON Katharine": "houghton-katharine",
    "HOUGHTON Peter": "houghton-peter",
    "HOUGHTON Stanley": "houghton-stanley",
    "HOUGLAND Kriss": "hougland-kriss",
    "HOUK Craig": "houk-craig",
    "HOULDERS Joseph": "houlders-joseph",
    "HOULE Glenn": "houle-glenn",
    "HOULT Colin": "hoult-colin",
    "HOULTON Jennifer": "houlton-jennifer",
    "HOUNSELL-ROBERT Kate": "hounsell-robert-kate",
    "HOUSE Alicia": "house-alicia",
    "HOUSE Amy": "house-amy",
    "HOUSE Christine": "house-christine",
    "HOUSE Jack": "house-jack",
    "HOUSE Janet": "house-janet",
    "HOUSE Ron": "house-ron",
    "HOUSE Stephen": "house-stephen",
    "HOUSELL-ROBERTS Kathleen": "housell-roberts-kathleen",
    "HOUSEMAN Heath": "houseman-heath",
    "HOUSEMAN Laurence": "houseman-laurence",
    "HOUSER Oliver": "houser-oliver",
    "HOUSER Robert": "houser-robert",
    "HOUSLEY Kirsty": "housley-kirsty",
    "HOUSMAN Laurence": "housman-laurence",
    "HOUSMAN Ruth": "housman-ruth",
    "HOUSTLE Alice H": "houstle-alice-h",
    "HOUSTON Aja": "houston-aja",
    "HOUSTON Andrew": "houston-andrew",
    "HOUSTON Anna": "houston-anna",
    "HOUSTON Eric": "houston-eric",
    "HOUSTON G": "houston-g",
    "HOUSTON Jane": "houston-jane",
    "HOUSTON Josiah": "houston-josiah",
    "HOUSTON Mark": "houston-mark",
    "HOUSTON Samantha": "houston-samantha",
    "HOUSTON Sterling": "houston-sterling",
    "HOUSTON Velina Hasu": "houston-velina-hasu",
    "HOUSTON-JONES Ishmael": "houston-jones-ishmael",
    "HOUSTOUN Wendy": "houstoun-wendy",
    "HOUYING Dai": "houying-dai",
    "HOVDE Colin": "hovde-colin",
    "HOVENDEN Valery": "hovenden-valery",
    "HOVENKAMP Henry": "hovenkamp-henry",
    "HOVERMAN Mark": "hoverman-mark",
    "HOVERMAN Matt": "hoverman-matt",
    "HOVEY Richard": "hovey-richard",
    "HOVIS Keith": "hovis-keith",
    "HOWARD Aaron": "howard-aaron",
    "HOWARD Adam": "howard-adam",
    "HOWARD Angela": "howard-angela",
    "HOWARD Anthony": "howard-anthony",
    "HOWARD Anto": "howard-anto",
    "HOWARD Bart": "howard-bart",
    "HOWARD Carly": "howard-carly",
    "HOWARD Chad": "howard-chad",
    "HOWARD Cheryl": "howard-cheryl",
    "HOWARD Chris": "howard-chris",
    "HOWARD Christopher": "howard-christopher",
    "HOWARD Daniel": "howard-daniel",
    "HOWARD David": "howard-david",
    "HOWARD Desmond Warwick": "howard-desmond-warwick",
    "HOWARD Dot": "howard-dot",
    "HOWARD Duke": "howard-duke",
    "HOWARD Dumont": "howard-dumont",
    "HOWARD Ed": "howard-ed",
    "HOWARD Eleanor Harris": "howard-eleanor-harris",
    "HOWARD Geoffrey": "howard-geoffrey",
    "HOWARD Hart": "howard-hart",
    "HOWARD Helen": "howard-helen",
    "HOWARD Jackie": "howard-jackie",
    "HOWARD James": "howard-james",
    "HOWARD Jane R": "howard-jane-r",
    "HOWARD Jon": "howard-jon",
    "HOWARD Jonathan": "howard-jonathan",
    "HOWARD Joy": "howard-joy",
    "HOWARD Judy": "howard-judy",
    "HOWARD Kate": "howard-kate",
    "HOWARD Key": "howard-key",
    "HOWARD Kim": "howard-kim",
    "HOWARD Lauren": "howard-lauren",
    "HOWARD Lawrence": "howard-lawrence",
    "HOWARD Lee": "howard-lee",
    "HOWARD Lisa": "howard-lisa",
    "HOWARD Lorin": "howard-lorin",
    "HOWARD Mark": "howard-mark",
    "HOWARD Maureen": "howard-maureen",
    "HOWARD Mavis": "howard-mavis",
    "HOWARD Mel": "howard-mel",
    "HOWARD Pamela": "howard-pamela",
    "HOWARD Peter": "howard-peter",
    "HOWARD Peter (2)": "howard-peter-2",
    "HOWARD Philip": "howard-philip",
    "HOWARD Richard": "howard-richard",
    "HOWARD Richard (2)": "howard-richard-2",
    "HOWARD Robert": "howard-robert",
    "HOWARD Roger": "howard-roger",
    "HOWARD Ross": "howard-ross",
    "HOWARD Ross (1)": "howard-ross-1",
    "HOWARD Sidney": "howard-sidney",
    "HOWARD Spencer": "howard-spencer",
    "HOWARD Teresa": "howard-teresa",
    "HOWARD Tony": "howard-tony",
    "HOWARD-WILLIAMS Miranda": "howard-williams-miranda",
    "HOWARTH David": "howarth-david",
    "HOWARTH Donald": "howarth-donald",
    "HOWARTH Hella": "howarth-hella",
    "HOWARTH John": "howarth-john",
    "HOWARTH Len": "howarth-len",
    "HOWARTH Tony": "howarth-tony",
    "HOWATSON Rob": "howatson-rob",
    "HOWDEN Kath": "howden-kath",
    "HOWE Adrian": "howe-adrian",
    "HOWE Eloise": "howe-eloise",
    "HOWE George": "howe-george",
    "HOWE Gerry": "howe-gerry",
    "HOWE Giles": "howe-giles",
    "HOWE Leanne": "howe-leanne",
    "HOWE Peter": "howe-peter",
    "HOWE Susan": "howe-susan",
    "HOWE Tina": "howe-tina",
    "HOWE Tom": "howe-tom",
    "HOWE Winifred": "howe-winifred",
    "HOWELL Adam": "howell-adam",
    "HOWELL Dana": "howell-dana",
    "HOWELL Debbie": "howell-debbie",
    "HOWELL Emma": "howell-emma",
    "HOWELL Gerry": "howell-gerry",
    "HOWELL James": "howell-james",
    "HOWELL Kristina Anne": "howell-kristina-anne",
    "HOWELL Ralph McCubbin": "howell-ralph-mccubbin",
    "HOWELLS Abby": "howells-abby",
    "HOWELLS Adrian": "howells-adrian",
    "HOWELLS Arthur": "howells-arthur",
    "HOWELLS Greg": "howells-greg",
    "HOWELLS Martin": "howells-martin",
    "HOWELLS Rosie": "howells-rosie",
    "HOWELLS Simone": "howells-simone",
    "HOWES Alithea": "howes-alithea",
    "HOWES Emily Watson": "howes-emily-watson",
    "HOWES Karen J P": "howes-karen-j-p",
    "HOWES Lynn": "howes-lynn",
    "HOWES Nina": "howes-nina",
    "HOWES Sarah": "howes-sarah",
    "HOWEY Christine": "howey-christine",
    "HOWGARTH Susie": "howgarth-susie",
    "HOWIE Betsy": "howie-betsy",
    "HOWIE Diana": "howie-diana",
    "HOWIE Robert": "howie-robert",
    "HOWISON James David": "howison-james-david",
    "HOWITT Charlie": "howitt-charlie",
    "HOWL Jona": "howl-jona",
    "HOWLE Fleur": "howle-fleur",
    "HOWLE Jonathan": "howle-jonathan",
    "HOWLETT Brett": "howlett-brett",
    "HOWLETT Chris": "howlett-chris",
    "HOWLEY Steven": "howley-steven",
    "HOWSAM Tess": "howsam-tess",
    "HOWSON Helen Kaut": "howson-helen-kaut",
    "HOWSON Jack": "howson-jack",
    "HOWSON John-Michael": "howson-john-michael",
    "HOWSON Stewart": "howson-stewart",
    "HOWZE Perry": "howze-perry",
    "HOWZE Phillip": "howze-phillip",
    "HOYDAL Annika": "hoydal-annika",
    "HOYLAND John": "hoyland-john",
    "HOYLE Chris": "hoyle-chris",
    "HOYLE Dan": "hoyle-dan",
    "HOYLE David": "hoyle-david",
    "HOYLE David (1)": "hoyle-david-1",
    "HOYLE Fred": "hoyle-fred",
    "HOYLE Geoff": "hoyle-geoff",
    "HOYLE John F K": "hoyle-john-f-k",
    "HOYT Matthew": "hoyt-matthew",
    "HOYT-DISICK Gabrielle": "hoyt-disick-gabrielle",
    "HOZA Paula": "hoza-paula",
    "HOZMAN Winnie": "hozman-winnie",
    "HRUSKA Alan": "hruska-alan",
    "HRYMAK Melanie": "hrymak-melanie"
  }
};