export default {
  "metadata": {
    "results": 463,
    "timeStamp": "2025-12-05T21:25:53.268Z",
    "url": "https://www.doollee.com/PlaywrightsH/H_playwrights_s-z.php"
  },
  "authors": {
    "HSIEH Kathy": "hsieh-kathy",
    "HSIUNG S I": "hsiung-s-i",
    "HSU Amber": "hsu-amber",
    "HSU Emmie": "hsu-emmie",
    "HSU Joshua N": "hsu-joshua-n",
    "HSU Krystal": "hsu-krystal",
    "HSU V V": "hsu-v-v",
    "HUANG Allen": "huang-allen",
    "HUANG Chloe Luting": "huang-chloe-luting",
    "HUANG Jessica": "huang-jessica",
    "HUANG Steve": "huang-steve",
    "HUANG Timothy": "huang-timothy",
    "HUANG Zoe": "huang-zoe",
    "HUBA Miranda": "huba-miranda",
    "HUBALEK Claus": "hubalek-claus",
    "HUBAND David": "huband-david",
    "HUBBARD Alison": "hubbard-alison",
    "HUBBARD Graham": "hubbard-graham",
    "HUBBARD Jennifer": "hubbard-jennifer",
    "HUBBARD Jenny": "hubbard-jenny",
    "HUBBARD John": "hubbard-john",
    "HUBBARD Merle": "hubbard-merle",
    "HUBBARD Steve": "hubbard-steve",
    "HUBBS Matt": "hubbs-matt",
    "HUBER Albert": "huber-albert",
    "HUBER Dominic": "huber-dominic",
    "HUBER Kathleen": "huber-kathleen",
    "HUBER Richard": "huber-richard",
    "HUBER Walter": "huber-walter",
    "HUBERMAN Edward": "huberman-edward",
    "HUBERMAN Lisa": "huberman-lisa",
    "HUBERT Cam": "hubert-cam",
    "HUBERT Nina Warner": "hubert-nina-warner",
    "HUBLEY Bob": "hubley-bob",
    "HUBNER Lutz": "hubner-lutz",
    "HUCKELBURY Charles": "huckelbury-charles",
    "HUCKLE Alan": "huckle-alan",
    "HUCKLESBY Jill": "hucklesby-jill",
    "HUDA Tuheen": "huda-tuheen",
    "HUDACEK David L": "hudacek-david-l",
    "HUDD Roy": "hudd-roy",
    "HUDDLESTON Cheryldee": "huddleston-cheryldee",
    "HUDDLESTON Will": "huddleston-will",
    "HUDES Quiara Alegria": "hudes-quiara-alegria",
    "HUDGINS Edward L": "hudgins-edward-l",
    "HUDI Laszlo": "hudi-laszlo",
    "HUDSON Anthony": "hudson-anthony",
    "HUDSON Ben": "hudson-ben",
    "HUDSON Carter": "hudson-carter",
    "HUDSON Dave": "hudson-dave",
    "HUDSON Fred": "hudson-fred",
    "HUDSON Jimmie D": "hudson-jimmie-d",
    "HUDSON Joanne": "hudson-joanne",
    "HUDSON John": "hudson-john",
    "HUDSON Ken (1)": "hudson-ken-1",
    "HUDSON Ken (2)": "hudson-ken-2",
    "HUDSON Lori Wolter": "hudson-lori-wolter",
    "HUDSON Mike": "hudson-mike",
    "HUDSON Robert": "hudson-robert",
    "HUDSON S L": "hudson-s-l",
    "HUDSON Scott": "hudson-scott",
    "HUEI-MIN Lee": "huei-min-lee",
    "HUENGER Thom": "huenger-thom",
    "HUERTAS Justin": "huertas-justin",
    "HUERTAS Kelly L": "huertas-kelly-l",
    "HUEY Tom": "huey-tom",
    "HUFF Betty Tracy": "huff-betty-tracy",
    "HUFF Keith": "huff-keith",
    "HUFFMAN Jon": "huffman-jon",
    "HUFFSTICKLER Shannon": "huffstickler-shannon",
    "HUFKER Paul": "hufker-paul",
    "HUG Zachary": "hug-zachary",
    "HUGEL William": "hugel-william",
    "HUGGETT Richard": "huggett-richard",
    "HUGGINS Tyrone": "huggins-tyrone",
    "HUGGONS Trevor": "huggons-trevor",
    "HUGH Ian": "hugh-ian",
    "HUGHES Adam": "hughes-adam",
    "HUGHES Alan": "hughes-alan",
    "HUGHES Anne": "hughes-anne",
    "HUGHES Austin": "hughes-austin",
    "HUGHES B Peter": "hughes-b-peter",
    "HUGHES Babette": "hughes-babette",
    "HUGHES Ben": "hughes-ben",
    "HUGHES Callum": "hughes-callum",
    "HUGHES David": "hughes-david",
    "HUGHES Declan": "hughes-declan",
    "HUGHES Donald": "hughes-donald",
    "HUGHES Doug": "hughes-doug",
    "HUGHES Douglas E": "hughes-douglas-e",
    "HUGHES Dusty": "hughes-dusty",
    "HUGHES Ellen": "hughes-ellen",
    "HUGHES Eve": "hughes-eve",
    "HUGHES Faye": "hughes-faye",
    "HUGHES Gary": "hughes-gary",
    "HUGHES Geraldine": "hughes-geraldine",
    "HUGHES Glenn": "hughes-glenn",
    "HUGHES Glyn": "hughes-glyn",
    "HUGHES Gwen": "hughes-gwen",
    "HUGHES Gwyneth": "hughes-gwyneth",
    "HUGHES Holly": "hughes-holly",
    "HUGHES Hugh": "hughes-hugh",
    "HUGHES Hunter Lee": "hughes-hunter-lee",
    "HUGHES Ian": "hughes-ian",
    "HUGHES J M": "hughes-j-m",
    "HUGHES Jeff": "hughes-jeff",
    "HUGHES Jenny": "hughes-jenny",
    "HUGHES Jill": "hughes-jill",
    "HUGHES Jill Elaine": "hughes-jill-elaine",
    "HUGHES Jim": "hughes-jim",
    "HUGHES John Osborne": "hughes-john-osborne",
    "HUGHES Julia Stubbs": "hughes-julia-stubbs",
    "HUGHES L T": "hughes-l-t",
    "HUGHES Langston": "hughes-langston",
    "HUGHES Lesley": "hughes-lesley",
    "HUGHES Lindsey Anne": "hughes-lindsey-anne",
    "HUGHES Maureen": "hughes-maureen",
    "HUGHES Megan": "hughes-megan",
    "HUGHES Michal I": "hughes-michal-i",
    "HUGHES Nick": "hughes-nick",
    "HUGHES Patrick": "hughes-patrick",
    "HUGHES Paul": "hughes-paul",
    "HUGHES Paul (1)": "hughes-paul-1",
    "HUGHES Paul (2)": "hughes-paul-2",
    "HUGHES Rebecca": "hughes-rebecca",
    "HUGHES Richard": "hughes-richard",
    "HUGHES Richard M": "hughes-richard-m",
    "HUGHES Richy": "hughes-richy",
    "HUGHES Rupert": "hughes-rupert",
    "HUGHES Sarah McDonald": "hughes-sarah-mcdonald",
    "HUGHES Sean": "hughes-sean",
    "HUGHES Simon": "hughes-simon",
    "HUGHES Sonia": "hughes-sonia",
    "HUGHES Steven Cole": "hughes-steven-cole",
    "HUGHES Ted": "hughes-ted",
    "HUGHES Terence Patrick": "hughes-terence-patrick",
    "HUGHES Terry": "hughes-terry",
    "HUGHES Trevor": "hughes-trevor",
    "HUGHES Vashti": "hughes-vashti",
    "HUGHES Vera C": "hughes-vera-c",
    "HUGHES-D'AETH Charlie": "hughes-d-aeth-charlie",
    "HUGO Victor": "hugo-victor",
    "HUGO & INES ": "hugo-ines",
    "HUGUENIN Patrick": "huguenin-patrick",
    "HUGUENIN Scott": "huguenin-scott",
    "HUI Karen": "hui-karen",
    "HUI Yi Man": "hui-yi-man",
    "HUIE Karen": "huie-karen",
    "HUISH Ian": "huish-ian",
    "HULBERT C": "hulbert-c",
    "HULBERT Jack": "hulbert-jack",
    "HULBERT Judy Carlson": "hulbert-judy-carlson",
    "HULET Todd": "hulet-todd",
    "HULETT Michael J": "hulett-michael-j",
    "HULICK Betsy": "hulick-betsy",
    "HULING Jay": "huling-jay",
    "HULJAK Irena": "huljak-irena",
    "HULL Daphne R": "hull-daphne-r",
    "HULL Jason": "hull-jason",
    "HULL Laura Conners": "hull-laura-conners",
    "HULL Nathan": "hull-nathan",
    "HULL Raymond": "hull-raymond",
    "HULL Richard": "hull-richard",
    "HULLETT Joseph": "hullett-joseph",
    "HULLEY Annie": "hulley-annie",
    "HULLICK Betsy": "hullick-betsy",
    "HULLS Tessa": "hulls-tessa",
    "HULME George": "hulme-george",
    "HULME Tony": "hulme-tony",
    "HULME-BEAMAN Genevieve": "hulme-beaman-genevieve",
    "HULME-CROSS Benjamin": "hulme-cross-benjamin",
    "HULSE Alex": "hulse-alex",
    "HULSE Toby": "hulse-toby",
    "HULSTINE Nick": "hulstine-nick",
    "HULTON Peter": "hulton-peter",
    "HUMBERSTONE Shane": "humberstone-shane",
    "HUMBERTSON Lisa": "humbertson-lisa",
    "HUMBLE Christopher": "humble-christopher",
    "HUMBLE William": "humble-william",
    "HUMBLOT Pierre": "humblot-pierre",
    "HUME Bob": "hume-bob",
    "HUME Cassandra": "hume-cassandra",
    "HUME Colin": "hume-colin",
    "HUME Gillian": "hume-gillian",
    "HUME Michael J": "hume-michael-j",
    "HUME Mike": "hume-mike",
    "HUME Sean J": "hume-sean-j",
    "HUME Tony": "hume-tony",
    "HUMFRESS Steve": "humfress-steve",
    "HUMISTON Dan": "humiston-dan",
    "HUMMER Robert": "hummer-robert",
    "HUMMON Marcus": "hummon-marcus",
    "HUMPHREY Alex": "humphrey-alex",
    "HUMPHREY George": "humphrey-george",
    "HUMPHREY Harry E": "humphrey-harry-e",
    "HUMPHREY Mark": "humphrey-mark",
    "HUMPHREY Olga": "humphrey-olga",
    "HUMPHREY Sheridan": "humphrey-sheridan",
    "HUMPHREYS Emma": "humphreys-emma",
    "HUMPHREYS Emyr": "humphreys-emyr",
    "HUMPHREYS Gary": "humphreys-gary",
    "HUMPHREYS Martha": "humphreys-martha",
    "HUMPHREYS Rachel": "humphreys-rachel",
    "HUMPHREYS Simon": "humphreys-simon",
    "HUMPHREYS Stephen": "humphreys-stephen",
    "HUMPHRIES Barry": "humphries-barry",
    "HUMPHRIES Barry (1)": "humphries-barry-1",
    "HUMPHRIES Bridgette": "humphries-bridgette",
    "HUMPHRIES Martin": "humphries-martin",
    "HUMPTON Fred": "humpton-fred",
    "HUNAULT Adam": "hunault-adam",
    "HUNDEMER Greg": "hundemer-greg",
    "HUNDEMER John Robert": "hundemer-john-robert",
    "HUNDERT Rena": "hundert-rena",
    "HUNDLEY Cat": "hundley-cat",
    "HUNE-BROWN Nicholas": "hune-brown-nicholas",
    "HUNG Chloe": "hung-chloe",
    "HUNGERFORD Andrew": "hungerford-andrew",
    "HUNKA George": "hunka-george",
    "HUNKEN Monica": "hunken-monica",
    "HUNKINS Lee": "hunkins-lee",
    "HUNSAKER Dave": "hunsaker-dave",
    "HUNSAKER David": "hunsaker-david",
    "HUNSTAD Yves": "hunstad-yves",
    "HUNT Albert": "hunt-albert",
    "HUNT Alison": "hunt-alison",
    "HUNT Ava": "hunt-ava",
    "HUNT Brendan": "hunt-brendan",
    "HUNT C J": "hunt-c-j",
    "HUNT Carolyn A": "hunt-carolyn-a",
    "HUNT Charlotte": "hunt-charlotte",
    "HUNT David": "hunt-david",
    "HUNT Dayle Ann": "hunt-dayle-ann",
    "HUNT F V": "hunt-f-v",
    "HUNT Holly": "hunt-holly",
    "HUNT Irvine": "hunt-irvine",
    "HUNT Jan": "hunt-jan",
    "HUNT John": "hunt-john",
    "HUNT John F": "hunt-john-f",
    "HUNT Lisa": "hunt-lisa",
    "HUNT Mame": "hunt-mame",
    "HUNT Margaret": "hunt-margaret",
    "HUNT Mark": "hunt-mark",
    "HUNT Moira": "hunt-moira",
    "HUNT Robyn": "hunt-robyn",
    "HUNT Sandra": "hunt-sandra",
    "HUNT Scott": "hunt-scott",
    "HUNT Sheilagh": "hunt-sheilagh",
    "HUNT Stephen": "hunt-stephen",
    "HUNT Steve": "hunt-steve",
    "HUNT Steven R": "hunt-steven-r",
    "HUNT Zachary": "hunt-zachary",
    "HUNTER Adriana": "hunter-adriana",
    "HUNTER Ailie": "hunter-ailie",
    "HUNTER Amelia Jane": "hunter-amelia-jane",
    "HUNTER Bianca": "hunter-bianca",
    "HUNTER Blake": "hunter-blake",
    "HUNTER Casha": "hunter-casha",
    "HUNTER Dan": "hunter-dan",
    "HUNTER Elizabeth": "hunter-elizabeth",
    "HUNTER Evan": "hunter-evan",
    "HUNTER Frederic": "hunter-frederic",
    "HUNTER Ian Mclellan": "hunter-ian-mclellan",
    "HUNTER John": "hunter-john",
    "HUNTER John (1)": "hunter-john-1",
    "HUNTER Kate": "hunter-kate",
    "HUNTER Kathryn": "hunter-kathryn",
    "HUNTER Kelly": "hunter-kelly",
    "HUNTER Laurel": "hunter-laurel",
    "HUNTER Lee": "hunter-lee",
    "HUNTER Les": "hunter-les",
    "HUNTER Lindsay Brandon": "hunter-lindsay-brandon",
    "HUNTER Lucy": "hunter-lucy",
    "HUNTER Lynn": "hunter-lynn",
    "HUNTER M Katie": "hunter-m-katie",
    "HUNTER Mark": "hunter-mark",
    "HUNTER Martin": "hunter-martin",
    "HUNTER Maureen": "hunter-maureen",
    "HUNTER Melanie": "hunter-melanie",
    "HUNTER Mollie": "hunter-mollie",
    "HUNTER N C": "hunter-n-c",
    "HUNTER Paul": "hunter-paul",
    "HUNTER Paul (1)": "hunter-paul-1",
    "HUNTER Reginald D": "hunter-reginald-d",
    "HUNTER Robert": "hunter-robert",
    "HUNTER Robin": "hunter-robin",
    "HUNTER Samuel D": "hunter-samuel-d",
    "HUNTER Sarah": "hunter-sarah",
    "HUNTER Scott": "hunter-scott",
    "HUNTER Sophie": "hunter-sophie",
    "HUNTER Susan C": "hunter-susan-c",
    "HUNTER Tim": "hunter-tim",
    "HUNTER Tom": "hunter-tom",
    "HUNTINGTON Nick": "huntington-nick",
    "HUNTRODS James": "huntrods-james",
    "HUNTSBERRY W E": "huntsberry-w-e",
    "HUNTSMAN H": "huntsman-h",
    "HUNZIKER Peter": "hunziker-peter",
    "HURD Catherine Koenig": "hurd-catherine-koenig",
    "HURD Harry": "hurd-harry",
    "HURD James E": "hurd-james-e",
    "HURFORD Richard": "hurford-richard",
    "HURIHANGANUI Hone": "hurihanganui-hone",
    "HURLBUT Bruce": "hurlbut-bruce",
    "HURLBUT Gladys": "hurlbut-gladys",
    "HURLEY Amanda": "hurley-amanda",
    "HURLEY Colin": "hurley-colin",
    "HURLEY Dean": "hurley-dean",
    "HURLEY Dennis": "hurley-dennis",
    "HURLEY Gemma": "hurley-gemma",
    "HURLEY Joan Mason": "hurley-joan-mason",
    "HURLEY John Paul": "hurley-john-paul",
    "HURLEY Jon": "hurley-jon",
    "HURLEY Kathy": "hurley-kathy",
    "HURLEY Kieran": "hurley-kieran",
    "HURLEY Liam": "hurley-liam",
    "HURLIN Dan": "hurlin-dan",
    "HURLL Michael": "hurll-michael",
    "HURSE Michael": "hurse-michael",
    "HURSEY Brett": "hursey-brett",
    "HURSEY Khiyon": "hursey-khiyon",
    "HURST James": "hurst-james",
    "HURST Katharine": "hurst-katharine",
    "HURST Keith": "hurst-keith",
    "HURST Michael": "hurst-michael",
    "HURST Michael (1)": "hurst-michael-1",
    "HURST Phoebe": "hurst-phoebe",
    "HURST Richard": "hurst-richard",
    "HURST Robbie Lee": "hurst-robbie-lee",
    "HURST Zoe": "hurst-zoe",
    "HURSTON Zora Neale": "hurston-zora-neale",
    "HURT Allen": "hurt-allen",
    "HURT Casey": "hurt-casey",
    "HURT Matthew": "hurt-matthew",
    "HURT Michael": "hurt-michael",
    "HURT Paul": "hurt-paul",
    "HURT Valerie": "hurt-valerie",
    "HURTGEN JR Peter": "hurtgen-jr-peter",
    "HUSAIN Shahrukh": "husain-shahrukh",
    "HUSEBO Jac": "husebo-jac",
    "HUSEIN Adam": "husein-adam",
    "HUSHLAK Mary Ann": "hushlak-mary-ann",
    "HUSIAK Laryssa": "husiak-laryssa",
    "HUSKEY Maureen": "huskey-maureen",
    "HUSSAIN Emteaz": "hussain-emteaz",
    "HUSSAIN Madhia": "hussain-madhia",
    "HUSSEIN Ghazi": "hussein-ghazi",
    "HUSSEY Emma Spurgin": "hussey-emma-spurgin",
    "HUSSEY John": "hussey-john",
    "HUSSEY Peter": "hussey-peter",
    "HUSSON A": "husson-a",
    "HUSTIS Jono": "hustis-jono",
    "HUSTMYRE Chuck": "hustmyre-chuck",
    "HUSTON River": "huston-river",
    "HUSTVEDT Sri": "hustvedt-sri",
    "HUSZCZA Jen": "huszcza-jen",
    "HUTCHESON Joe": "hutcheson-joe",
    "HUTCHESON Katherine Grosvenor": "hutcheson-katherine-grosvenor",
    "HUTCHINGS Geoffrey": "hutchings-geoffrey",
    "HUTCHINS Guy": "hutchins-guy",
    "HUTCHINS Jeannie": "hutchins-jeannie",
    "HUTCHINS Pat": "hutchins-pat",
    "HUTCHINS Phil": "hutchins-phil",
    "HUTCHINS Scott Andrew": "hutchins-scott-andrew",
    "HUTCHINS Sean P": "hutchins-sean-p",
    "HUTCHINSON Alexander": "hutchinson-alexander",
    "HUTCHINSON Ben": "hutchinson-ben",
    "HUTCHINSON Caroline": "hutchinson-caroline",
    "HUTCHINSON Chisa": "hutchinson-chisa",
    "HUTCHINSON David": "hutchinson-david",
    "HUTCHINSON David Malcolm": "hutchinson-david-malcolm",
    "HUTCHINSON Duncan": "hutchinson-duncan",
    "HUTCHINSON G O": "hutchinson-g-o",
    "HUTCHINSON George": "hutchinson-george",
    "HUTCHINSON Glenn": "hutchinson-glenn",
    "HUTCHINSON Heidi": "hutchinson-heidi",
    "HUTCHINSON Mary": "hutchinson-mary",
    "HUTCHINSON Ron": "hutchinson-ron",
    "HUTCHINSON Sandra": "hutchinson-sandra",
    "HUTCHINSON Sarah": "hutchinson-sarah",
    "HUTCHINSON Stephanie": "hutchinson-stephanie",
    "HUTCHINSON Vic": "hutchinson-vic",
    "HUTCHISON Caroline": "hutchison-caroline",
    "HUTCHISON Charlotte": "hutchison-charlotte",
    "HUTCHISON Nick": "hutchison-nick",
    "HUTCHMAN David": "hutchman-david",
    "HUTH Angela": "huth-angela",
    "HUTLEY Peter": "hutley-peter",
    "HUTSELL-MANNING Linda": "hutsell-manning-linda",
    "HUTSON Esther": "hutson-esther",
    "HUTSON Lucy": "hutson-lucy",
    "HUTSON Ron": "hutson-ron",
    "HUTSON Rowena": "hutson-rowena",
    "HUTTER Gardi": "hutter-gardi",
    "HUTTON Arlene": "hutton-arlene",
    "HUTTON Megan": "hutton-megan",
    "HUTTON Michael Clayton": "hutton-michael-clayton",
    "HUTTON Neal": "hutton-neal",
    "HUTTON Neville": "hutton-neville",
    "HUTTON Tom": "hutton-tom",
    "HUTZLER Richard": "hutzler-richard",
    "HUTZULAK Clint": "hutzulak-clint",
    "HUUSKA Tapio Mikael": "huuska-tapio-mikael",
    "HUWS Anwen": "huws-anwen",
    "HUWS Catrin Fflur": "huws-catrin-fflur",
    "HUWS Sioned": "huws-sioned",
    "HUXLEY Aldous": "huxley-aldous",
    "HUXLEY David": "huxley-david",
    "HUXLEY Frances": "huxley-frances",
    "HUXLEY Henry": "huxley-henry",
    "HUXLEY Jane": "huxley-jane",
    "HUXTER Robert": "huxter-robert",
    "HUYHN Aileen": "huyhn-aileen",
    "HUYNH Christine": "huynh-christine",
    "HUYNH Helen": "huynh-helen",
    "HUZE Sean": "huze-sean",
    "HWANG David Henry": "hwang-david-henry",
    "HWANG Sookyung": "hwang-sookyung",
    "HYAMS Tor": "hyams-tor",
    "HYATT Bill": "hyatt-bill",
    "HYATT John": "hyatt-john",
    "HYATT Patricia R": "hyatt-patricia-r",
    "HYDE Dan": "hyde-dan",
    "HYDE Douglas": "hyde-douglas",
    "HYDE G": "hyde-g",
    "HYDE Julia": "hyde-julia",
    "HYDE Kurt": "hyde-kurt",
    "HYDE Nigel": "hyde-nigel",
    "HYDE Paul R": "hyde-paul-r",
    "HYDER Tony": "hyder-tony",
    "HYDE-THOMPSON Rodney": "hyde-thompson-rodney",
    "HYEM Jill": "hyem-jill",
    "HYER David C": "hyer-david-c",
    "HYETT Steve": "hyett-steve",
    "HYLAND James": "hyland-james",
    "HYLANDS Ian": "hylands-ian",
    "HYLTON Jeff": "hylton-jeff",
    "HYMAN Andy": "hyman-andy",
    "HYMAN David": "hyman-david",
    "HYMAN Fracaswell": "hyman-fracaswell",
    "HYMAN Frankie": "hyman-frankie",
    "HYMAN Jack G": "hyman-jack-g",
    "HYMAN Robert": "hyman-robert",
    "HYMAN Yehuda": "hyman-yehuda",
    "HYMEN Mark Harvey": "hymen-mark-harvey",
    "HYMES-ESPOSITO Richard": "hymes-esposito-richard",
    "HYNAM John": "hynam-john",
    "HYNDMAN Tom": "hyndman-tom",
    "HYNDS Pete": "hynds-pete",
    "HYNEK Angie": "hynek-angie",
    "HYNEK Joe": "hynek-joe",
    "HYNEK Lauren": "hynek-lauren",
    "HYNES Abi Fernandez-Arias": "hynes-abi-fernandez-arias",
    "HYNES Alexandra": "hynes-alexandra",
    "HYNES Allyssa Marie": "hynes-allyssa-marie",
    "HYNES Garry": "hynes-garry",
    "HYNES Jessica": "hynes-jessica",
    "HYNES Pat": "hynes-pat",
    "HYNES Rachel": "hynes-rachel",
    "HYRST Chris": "hyrst-chris",
    "HYSELL Hugh": "hysell-hugh",
    "HYTHE Romney": "hythe-romney",
    "HYWEL Dafydd": "hywel-dafydd"
  }
};