export default {
  "metadata": {
    "results": 37,
    "timeStamp": "2025-12-05T21:25:56.811Z",
    "url": "https://www.doollee.com/PlaywrightsI/I_playwrights_g-l.php"
  },
  "authors": {
    "IGER Arnold": "iger-arnold",
    "IGGULDEN Hal": "iggulden-hal",
    "IGNACIO Cynthia Q": "ignacio-cynthia-q",
    "IGNACIO Jose": "ignacio-jose",
    "IGNAS Lorelei": "ignas-lorelei",
    "IGNITE THEATRE ": "ignite-theatre",
    "IGOE Ben": "igoe-ben",
    "IGREJAS Manuel": "igrejas-manuel",
    "IGUH Thomas": "iguh-thomas",
    "IHIMAERA Witi": "ihimaera-witi",
    "IIZUKA Naomi": "iizuka-naomi",
    "IJAMES James": "ijames-james",
    "IJIMERE O": "ijimere-o",
    "IKAHEIMONEN-LINDGREN Silja": "ikaheimonen-lindgren-silja",
    "IKEDA John": "ikeda-john",
    "IKEUCHI Mansaku": "ikeuchi-mansaku",
    "IKO Momoko": "iko-momoko",
    "IKOKO Theresa": "ikoko-theresa",
    "IKOLI Tunde": "ikoli-tunde",
    "IKUMELO Gbemisola": "ikumelo-gbemisola",
    "ILAND Paula": "iland-paula",
    "ILBIJERRI THEATRE COMPANY ": "ilbijerri-theatre-company",
    "ILDAN Mehmet Murat": "ildan-mehmet-murat",
    "ILES Robert": "iles-robert",
    "ILGENFRITZ Pedro": "ilgenfritz-pedro",
    "ILIEV Konstantin": "iliev-konstantin",
    "ILIFFE David": "iliffe-david",
    "ILIFFE Roy": "iliffe-roy",
    "ILIKA Aaron J": "ilika-aaron-j",
    "ILLEGITIMATE PLAYERS, THE ": "illegitimate-players",
    "ILLIATOVITCH-GOLDMAN Sarah": "illiatovitch-goldman-sarah",
    "ILLICK Hilary": "illick-hilary",
    "ILLIS Mark": "illis-mark",
    "ILLOPOULOS George": "illopoulos-george",
    "ILOTT Craig": "ilott-craig",
    "ILSON Saul": "ilson-saul",
    "ILYASOVA Alla": "ilyasova-alla"
  }
};