export default {
  "metadata": {
    "results": 161,
    "timeStamp": "2025-12-05T21:26:00.484Z",
    "url": "https://www.doollee.com/PlaywrightsI/I_playwrights_m-r.php"
  },
  "authors": {
    "IMA Kim": "ima-kim",
    "IMAGINARY PEOPLE, THE ": "imaginary-people",
    "IMAI Masayuki": "imai-masayuki",
    "IMAN Yusef": "iman-yusef",
    "IMBODEN Christian": "imboden-christian",
    "IMBRIE Mccrae": "imbrie-mccrae",
    "IMBRIE Timothy": "imbrie-timothy",
    "IMFURST Mimi": "imfurst-mimi",
    "IMIELSKI Michal": "imielski-michal",
    "IMITATING THE DOG ": "imitating-the-dog",
    "IMLAY James": "imlay-james",
    "IMMS Peter": "imms-peter",
    "IMPERFECT PICTURES ": "imperfect-pictures",
    "IMPERIAL Dean": "imperial-dean",
    "IMPROBABLE THEATRE ": "improbable-theatre",
    "IMPROVISED THEATRE ": "improvised-theatre",
    "IMPROVISORS, THE ": "improvisors-the",
    "IN TRIPLICATE ": "in-triplicate",
    "INAD THEATRE COMPANY ": "inad-theatre-company",
    "INCAVO Jeff": "incavo-jeff",
    "INCE Caitlin": "ince-caitlin",
    "INCE James": "ince-james",
    "INCE Karen": "ince-karen",
    "INCROCCI Uma": "incrocci-uma",
    "INDEFINITE ARTICLES ": "indefinite-articles",
    "INDIANA Gary": "indiana-gary",
    "INDIANOS Elizabeth": "indianos-elizabeth",
    "INDOMITABLE IMPOSTER ": "indomitable-imposter",
    "INES Deborah A": "ines-deborah-a",
    "INFANTINO Lindsay": "infantino-lindsay",
    "INGALLS Jeremy": "ingalls-jeremy",
    "INGBER David": "ingber-david",
    "INGBER Hillary": "ingber-hillary",
    "INGE William": "inge-william",
    "INGEBORG Gertraud": "ingeborg-gertraud",
    "INGELBRECHT Suzanne": "ingelbrecht-suzanne",
    "INGERSON Martin": "ingerson-martin",
    "INGHAM Anna": "ingham-anna",
    "INGHAM Richard": "ingham-richard",
    "INGHAM Robert": "ingham-robert",
    "INGHAM William": "ingham-william",
    "INGIMARSSON Kristjan": "ingimarsson-kristjan",
    "INGLE Roisin": "ingle-roisin",
    "INGLEDEW David": "ingledew-david",
    "INGLETON Sue": "ingleton-sue",
    "INGLIS Andrea": "inglis-andrea",
    "INGLIS Daizie": "inglis-daizie",
    "INGLIS Rob": "inglis-rob",
    "INGOLD Jon": "ingold-jon",
    "INGOLDSBY Maeve": "ingoldsby-maeve",
    "INGOLDSBY Pat": "ingoldsby-pat",
    "INGRAFFI Sam": "ingraffi-sam",
    "INGRAHAM Elizabeth": "ingraham-elizabeth",
    "INGRAM Brettcardie": "ingram-brettcardie",
    "INGRAM F A": "ingram-f-a",
    "INGRAM James": "ingram-james",
    "INGRAM Joan": "ingram-joan",
    "INGRAMS Richard": "ingrams-richard",
    "INGRASCIOTTA Frank": "ingrasciotta-frank",
    "INGRASSIA Anthony": "ingrassia-anthony",
    "INGS Welby": "ings-welby",
    "INGULSRUD Leon": "ingulsrud-leon",
    "INHOON Che": "inhoon-che",
    "INKFISH ": "inkfish",
    "INLENDER Avraham": "inlender-avraham",
    "INMAN James": "inman-james",
    "INMAN Jim": "inman-jim",
    "INMAN Robert": "inman-robert",
    "INNAURATO Albert": "innaurato-albert",
    "INNEO Anthony": "inneo-anthony",
    "INNER PRINCESS ": "inner-princess",
    "INNES Gavin J": "innes-gavin-j",
    "INNES Molly": "innes-molly",
    "INNES Neil": "innes-neil",
    "INNES Peggy": "innes-peggy",
    "INNISS Michelle": "inniss-michelle",
    "INNOCENTI Giulia": "innocenti-giulia",
    "INNUINUIT THEATRE CO NALUJUK PLAYERS ": "innuinuit-theatre-co-nalujuk-players",
    "INOUE Hisashi": "inoue-hisashi",
    "INOUYE Lisa Toishigawa": "inouye-lisa-toishigawa",
    "INSOMNIAC PRODUCTIONS ": "insomniac-productions",
    "INSPECTOR SANDS ": "inspector-sands",
    "INSTANT CLASSICS ": "instant-classics",
    "INSTITUTE, THE ": "institute",
    "INSTON Robert": "inston-robert",
    "INSTONE Alfred": "instone-alfred",
    "INSUA Juan": "insua-juan",
    "INTRABARTOLO Damon": "intrabartolo-damon",
    "INTRAVIA Tim": "intravia-tim",
    "INTROCASO John C": "introcaso-john-c",
    "INTRODANS ENSEMBLE FOR YOUTH ": "introdans-ensemble-for-youth",
    "INTRONATI, THE ": "intronati",
    "IOAN Gareth": "ioan-gareth",
    "IOANNOU Lucy": "ioannou-lucy",
    "IOGNA Luciano": "iogna-luciano",
    "IOMHA ILDANACH ": "iomha-ildanach",
    "ION Vera": "ion-vera",
    "IONESCO Eugene": "ionesco-eugene",
    "IONESCO Marie-France": "ionesco-marie-france",
    "IONESCU Ion": "ionescu-ion",
    "IORDANOVA Elissaveta": "iordanova-elissaveta",
    "IOSIFESCU Mark": "iosifescu-mark",
    "IOTA ": "iota",
    "IOU THEATRE ": "iou-theatre",
    "IOVINO Brenda": "iovino-brenda",
    "IPPOLITO David": "ippolito-david",
    "IPSEN Carlotta": "ipsen-carlotta",
    "IRANI Anosh": "irani-anosh",
    "IRANI Kayhan": "irani-kayhan",
    "IRCINK Jeffrey James": "ircink-jeffrey-james",
    "IREDALE Jane": "iredale-jane",
    "IREDYNSKI Ireneusz": "iredynski-ireneusz",
    "IRELAND David": "ireland-david",
    "IRELAND David (1)": "ireland-david-1",
    "IRELAND John": "ireland-john",
    "IRELAND Kenny": "ireland-kenny",
    "IRELAND Stanley": "ireland-stanley",
    "IRELAND Vicky": "ireland-vicky",
    "IRELAND-REEVES Dan": "ireland-reeves-dan",
    "IRENE Maria": "irene-maria",
    "IRESON Richard": "ireson-richard",
    "IRETON Catherine": "ireton-catherine",
    "IREY Mary": "irey-mary",
    "IRGLOVA Marketa": "irglova-marketa",
    "IRIBARNE Louis": "iribarne-louis",
    "IRIGUCHI Mamoru": "iriguchi-mamoru",
    "IRION Nicholas Dean": "irion-nicholas-dean",
    "IRISH Gemma": "irish-gemma",
    "IRIZARRY Daniel": "irizarry-daniel",
    "IRIZARRY Richard": "irizarry-richard",
    "IRNAN Kasisi Yusef": "irnan-kasisi-yusef",
    "IRONDALE ENSEMBLE ": "irondale-ensemble",
    "IRONDUKE ": "ironduke",
    "IRONS Andrew": "irons-andrew",
    "IRONS Creighton Manning": "irons-creighton-manning",
    "IRONS David": "irons-david",
    "IRONSIDE Lewis": "ironside-lewis",
    "IRONSIDE Louisa": "ironside-louisa",
    "IRONSIDE Virginia": "ironside-virginia",
    "IRVIN J": "irvin-j",
    "IRVINE Anne": "irvine-anne",
    "IRVINE Barbara": "irvine-barbara",
    "IRVINE Dougal": "irvine-dougal",
    "IRVINE Douglas": "irvine-douglas",
    "IRVINE Will": "irvine-will",
    "IRVING George S": "irving-george-s",
    "IRVING Lee": "irving-lee",
    "IRVING Michael": "irving-michael",
    "IRVING Todd": "irving-todd",
    "IRVING Vaughn": "irving-vaughn",
    "IRVIS Erick": "irvis-erick",
    "IRVWN Will": "irvwn-will",
    "IRWIN Bill": "irwin-bill",
    "IRWIN Elizabeth": "irwin-elizabeth",
    "IRWIN Janet": "irwin-janet",
    "IRWIN Leonard": "irwin-leonard",
    "IRWIN Louis": "irwin-louis",
    "IRWIN Shari": "irwin-shari",
    "IRWIN Tamsin": "irwin-tamsin",
    "IRWIN Vera Rushforth": "irwin-vera-rushforth",
    "IRWIN Will": "irwin-will"
  }
};