export default {
  "metadata": {
    "results": 77,
    "timeStamp": "2025-12-05T21:26:03.299Z",
    "url": "https://www.doollee.com/PlaywrightsI/I_playwrights_s-z.php"
  },
  "authors": {
    "ISAAC Alberto": "isaac-alberto",
    "ISAAC Salio": "isaac-salio",
    "ISAACS Chris": "isaacs-chris",
    "ISAACS David": "isaacs-david",
    "ISAACS Herb": "isaacs-herb",
    "ISAACS Jerry": "isaacs-jerry",
    "ISAACS Naomi Karz": "isaacs-naomi-karz",
    "ISAACS Philip M": "isaacs-philip-m",
    "ISAACSON David": "isaacson-david",
    "ISAAK Isaak Esmail": "isaak-isaak-esmail",
    "ISAKSEN Ike": "isaksen-ike",
    "ISAROV Boris": "isarov-boris",
    "ISBELL John": "isbell-john",
    "ISBELL Tom": "isbell-tom",
    "ISCOVITZ Stephanie": "iscovitz-stephanie",
    "ISEMAN Jim": "iseman-jim",
    "ISEN Richard": "isen-richard",
    "ISENHOUR Thomas L": "isenhour-thomas-l",
    "ISHEE Suzanne": "ishee-suzanne",
    "ISHERWOOD Christopher": "isherwood-christopher",
    "ISHIGURO Kazuo": "ishiguro-kazuo",
    "ISHII Leslie": "ishii-leslie",
    "ISIS ": "isis",
    "ISITT Debbie": "isitt-debbie",
    "ISKANDER Helen": "iskander-helen",
    "ISKANDER Tarek": "iskander-tarek",
    "ISKAYEV E": "iskayev-e",
    "ISLE Mike": "isle-mike",
    "ISLER Seth": "isler-seth",
    "ISLEY Edwin L": "isley-edwin-l",
    "ISLINGTON YOUTH THEATRE ": "islington-youth-theatre",
    "ISOM Stacey": "isom-stacey",
    "ISOMAKI Mikko": "isomaki-mikko",
    "ISQUITH Betty Jane": "isquith-betty-jane",
    "ISRAEL Daniel Evan": "israel-daniel-evan",
    "ISRAEL Gissa G": "israel-gissa-g",
    "ISRAEL Henry": "israel-henry",
    "ISRAEL Joel": "israel-joel",
    "ISRAEL Sara": "israel-sara",
    "ISRAEL Steve Ben": "israel-steve-ben",
    "ISRAELI Henry": "israeli-henry",
    "ISRAELY Razia": "israely-razia",
    "ISREAL Sarah": "isreal-sarah",
    "ISSAK I E": "issak-i-e",
    "ISSAQ Lameece": "issaq-lameece",
    "ISSEL-PITRE Katie": "issel-pitre-katie",
    "ISSENDORF John": "issendorf-john",
    "ITALIANO Laura": "italiano-laura",
    "ITO Shoko": "ito-shoko",
    "ITO Teiji": "ito-teiji",
    "ITTE Lisa Levin": "itte-lisa-levin",
    "ITZIN Catherine": "itzin-catherine",
    "ITZKOW Ethan": "itzkow-ethan",
    "IVANOVICH Denis": "ivanovich-denis",
    "IVANOVICH Yahimovich Sergey": "ivanovich-yahimovich-sergey",
    "IVAY Jon": "ivay-jon",
    "IVERSON Aaron": "iverson-aaron",
    "IVERSON Roger": "iverson-roger",
    "IVERSON Ryan": "iverson-ryan",
    "IVES David": "ives-david",
    "IVES Denys": "ives-denys",
    "IVES Derek": "ives-derek",
    "IVES Philip": "ives-philip",
    "IVES Steve": "ives-steve",
    "IVES-MOIBA Mariama": "ives-moiba-mariama",
    "IVESON Mike": "iveson-mike",
    "IVISON Dawn": "ivison-dawn",
    "IVORY Terrence Tyrie": "ivory-terrence-tyrie",
    "IVORY William": "ivory-william",
    "IWAMOTO Gary": "iwamoto-gary",
    "IWASUK James": "iwasuk-james",
    "IWASZKO Danusia": "iwaszko-danusia",
    "IWATAKI Joel": "iwataki-joel",
    "IYENGAR Niranjan": "iyengar-niranjan",
    "IZBUDAK Mehmet": "izbudak-mehmet",
    "IZUKA Scott": "izuka-scott",
    "IZZO Ben": "izzo-ben"
  }
};