export default {
  "metadata": {
    "results": 609,
    "timeStamp": "2025-12-05T21:26:10.399Z",
    "url": "https://www.doollee.com/PlaywrightsJ/J_playwrights_a-f.php"
  },
  "authors": {
    "JA JA JA NE NE NE PL ": "ja-ja-ja-ne-ne-ne-pl",
    "JABARA Paul": "jabara-paul",
    "JABAUT Mark": "jabaut-mark",
    "JABER Corinne": "jaber-corinne",
    "JABER Fernanda": "jaber-fernanda",
    "JABLONSKI Carla": "jablonski-carla",
    "JABLONSKI Marcia": "jablonski-marcia",
    "JABOR Andrea": "jabor-andrea",
    "JABRE Jarrod": "jabre-jarrod",
    "JACH Anotoni": "jach-anotoni",
    "JACHIMOWSKI Henrik": "jachimowski-henrik",
    "JACK Alex": "jack-alex",
    "JACK Donald Lamont": "jack-donald-lamont",
    "JACK Hannah": "jack-hannah",
    "JACK Sandy": "jack-sandy",
    "JACK Steven": "jack-steven",
    "JACK Susan": "jack-susan",
    "JACK Tina": "jack-tina",
    "JACK Tracy": "jack-tracy",
    "JACKASS A M": "jackass-a-m",
    "JACKER Corinne": "jacker-corinne",
    "JACKETTE Roger": "jackette-roger",
    "JACKINABOX PRODUCTIONS ": "jackinabox-productions",
    "JACKMAN Adam": "jackman-adam",
    "JACKMAN Godfrey": "jackman-godfrey",
    "JACKMAN Stuart B": "jackman-stuart-b",
    "JACKNOW Alexis": "jacknow-alexis",
    "JACKS David": "jacks-david",
    "JACKSON Abigail": "jackson-abigail",
    "JACKSON Adrian": "jackson-adrian",
    "JACKSON Alan": "jackson-alan",
    "JACKSON Alex": "jackson-alex",
    "JACKSON Angus": "jackson-angus",
    "JACKSON Brigid": "jackson-brigid",
    "JACKSON C Bernard": "jackson-c-bernard",
    "JACKSON Christopher": "jackson-christopher",
    "JACKSON Claire": "jackson-claire",
    "JACKSON Crystal": "jackson-crystal",
    "JACKSON D C": "jackson-d-c",
    "JACKSON Dave": "jackson-dave",
    "JACKSON Debbie Minter": "jackson-debbie-minter",
    "JACKSON Donald": "jackson-donald",
    "JACKSON Donna": "jackson-donna",
    "JACKSON Douglas": "jackson-douglas",
    "JACKSON Dylan": "jackson-dylan",
    "JACKSON Elaine": "jackson-elaine",
    "JACKSON Elizabeth": "jackson-elizabeth",
    "JACKSON Erik": "jackson-erik",
    "JACKSON Eugenia Lutcher": "jackson-eugenia-lutcher",
    "JACKSON Frank": "jackson-frank",
    "JACKSON Graziella": "jackson-graziella",
    "JACKSON Gregory": "jackson-gregory",
    "JACKSON Guy J": "jackson-guy-j",
    "JACKSON Heidi": "jackson-heidi",
    "JACKSON Herbert Montague": "jackson-herbert-montague",
    "JACKSON James Thomas": "jackson-james-thomas",
    "JACKSON Jamie A": "jackson-jamie-a",
    "JACKSON Jeff": "jackson-jeff",
    "JACKSON Jeffrey": "jackson-jeffrey",
    "JACKSON Jim": "jackson-jim",
    "JACKSON Josephine": "jackson-josephine",
    "JACKSON Judith Alexa": "jackson-judith-alexa",
    "JACKSON Julia": "jackson-julia",
    "JACKSON Keith": "jackson-keith",
    "JACKSON Ken": "jackson-ken",
    "JACKSON Kenyetta": "jackson-kenyetta",
    "JACKSON Kim": "jackson-kim",
    "JACKSON Laura": "jackson-laura",
    "JACKSON Lauren": "jackson-lauren",
    "JACKSON Leigh": "jackson-leigh",
    "JACKSON Marilee": "jackson-marilee",
    "JACKSON Mark": "jackson-mark",
    "JACKSON Marsha": "jackson-marsha",
    "JACKSON Mary": "jackson-mary",
    "JACKSON Michael": "jackson-michael",
    "JACKSON Michael D": "jackson-michael-d",
    "JACKSON Michael R": "jackson-michael-r",
    "JACKSON Nagle": "jackson-nagle",
    "JACKSON Nathan Louis": "jackson-nathan-louis",
    "JACKSON Ned": "jackson-ned",
    "JACKSON Pamela": "jackson-pamela",
    "JACKSON Penny": "jackson-penny",
    "JACKSON Philip": "jackson-philip",
    "JACKSON R Eugene": "jackson-r-eugene",
    "JACKSON Rachel": "jackson-rachel",
    "JACKSON Reginald Andre": "jackson-reginald-andre",
    "JACKSON Reuben": "jackson-reuben",
    "JACKSON Rex Emerson": "jackson-rex-emerson",
    "JACKSON Richard": "jackson-richard",
    "JACKSON River": "jackson-river",
    "JACKSON Robert": "jackson-robert",
    "JACKSON Robert Jason": "jackson-robert-jason",
    "JACKSON Sam Peter": "jackson-sam-peter",
    "JACKSON Savannah": "jackson-savannah",
    "JACKSON Shirley": "jackson-shirley",
    "JACKSON Simon": "jackson-simon",
    "JACKSON Stephen": "jackson-stephen",
    "JACKSON Steve": "jackson-steve",
    "JACKSON Susan": "jackson-susan",
    "JACKSON Thomas": "jackson-thomas",
    "JACKSON Trevor": "jackson-trevor",
    "JACKSON Uke": "jackson-uke",
    "JACKSON Wade": "jackson-wade",
    "JACKSON Wayne Steven": "jackson-wayne-steven",
    "JACKSON William": "jackson-william",
    "JACKSON / STANWOOD ": "jackson-stanwood",
    "JACKSON JR James Murray": "jackson-jr-james-murray",
    "JACK-VERNEY Margueritte": "jack-verney-margueritte",
    "JACOB Allyson W": "jacob-allyson-w",
    "JACOB Bill": "jacob-bill",
    "JACOB Micheal": "jacob-micheal",
    "JACOB Norman": "jacob-norman",
    "JACOB Patti": "jacob-patti",
    "JACOB Shekinah": "jacob-shekinah",
    "JACOB Stephanie": "jacob-stephanie",
    "JACOBI David": "jacobi-david",
    "JACOBS Adena": "jacobs-adena",
    "JACOBS Amanda": "jacobs-amanda",
    "JACOBS Angela": "jacobs-angela",
    "JACOBS Anna": "jacobs-anna",
    "JACOBS Anna K": "jacobs-anna-k",
    "JACOBS Carroll": "jacobs-carroll",
    "JACOBS Casey": "jacobs-casey",
    "JACOBS D W": "jacobs-d-w",
    "JACOBS Gene": "jacobs-gene",
    "JACOBS Gretchen": "jacobs-gretchen",
    "JACOBS Ivan": "jacobs-ivan",
    "JACOBS Jacob": "jacobs-jacob",
    "JACOBS Jarlath Barsanti": "jacobs-jarlath-barsanti",
    "JACOBS Jason": "jacobs-jason",
    "JACOBS Jim": "jacobs-jim",
    "JACOBS Jonathan": "jacobs-jonathan",
    "JACOBS Judith A": "jacobs-judith-a",
    "JACOBS Leonard Arnold": "jacobs-leonard-arnold",
    "JACOBS Lori": "jacobs-lori",
    "JACOBS Marc": "jacobs-marc",
    "JACOBS Matthew": "jacobs-matthew",
    "JACOBS Michael": "jacobs-michael",
    "JACOBS Naomi Karz": "jacobs-naomi-karz",
    "JACOBS Olivia": "jacobs-olivia",
    "JACOBS Paul": "jacobs-paul",
    "JACOBS Pauline": "jacobs-pauline",
    "JACOBS Peter": "jacobs-peter",
    "JACOBS Phil": "jacobs-phil",
    "JACOBS Pieter": "jacobs-pieter",
    "JACOBS Reza": "jacobs-reza",
    "JACOBS Shayanna Marrie": "jacobs-shayanna-marrie",
    "JACOBS Steven": "jacobs-steven",
    "JACOBS Tovya": "jacobs-tovya",
    "JACOBS-JENKINS Branden": "jacobs-jenkins-branden",
    "JACOBSON Ashley J": "jacobson-ashley-j",
    "JACOBSON Cherie": "jacobson-cherie",
    "JACOBSON Jackie Ruggiero": "jacobson-jackie-ruggiero",
    "JACOBSON Jay": "jacobson-jay",
    "JACOBSON Josepha": "jacobson-josepha",
    "JACOBSON Leslie": "jacobson-leslie",
    "JACOBSON Ruth": "jacobson-ruth",
    "JACOBSON Steven M": "jacobson-steven-m",
    "JACOBSON Tom": "jacobson-tom",
    "JACOBS-ROSEMAN Gregory": "jacobs-roseman-gregory",
    "JACOBUS Lee A": "jacobus-lee-a",
    "JACOBY Alana": "jacoby-alana",
    "JACOBY Bruce": "jacoby-bruce",
    "JACOBY Coleman": "jacoby-coleman",
    "JACOBY Oren": "jacoby-oren",
    "JACOT Michal": "jacot-michal",
    "JACQMIN Laura": "jacqmin-laura",
    "JACQUES Brigitte": "jacques-brigitte",
    "JACQUES Hattie": "jacques-hattie",
    "JAEGAR C K": "jaegar-c-k",
    "JAEGTNES Hilde Susan": "jaegtnes-hilde-susan",
    "JAENSCH Terry": "jaensch-terry",
    "JAFF Sophie": "jaff-sophie",
    "JAFFE Bob": "jaffe-bob",
    "JAFFE Dana C": "jaffe-dana-c",
    "JAFFE Sandra": "jaffe-sandra",
    "JAFFE Saul": "jaffe-saul",
    "JAFFEE Zac": "jaffee-zac",
    "JAFFERIS Aaron": "jafferis-aaron",
    "JAFRI Anwer": "jafri-anwer",
    "JAGASIA Mark": "jagasia-mark",
    "JAGGER Brian Scott": "jagger-brian-scott",
    "JAGGER Simon": "jagger-simon",
    "JAGO Hari": "jago-hari",
    "JAGODOWSKI T J": "jagodowski-t-j",
    "JAGRAN ": "jagran",
    "JAHNKE John": "jahnke-john",
    "JAHNKE Mackenzie": "jahnke-mackenzie",
    "JAHNN Hans Henny": "jahnn-hans-henny",
    "JAIBI Fadhel": "jaibi-fadhel",
    "JAIN Asha": "jain-asha",
    "JAIN Justin": "jain-justin",
    "JAIN Ravi": "jain-ravi",
    "JAIVIN Linda": "jaivin-linda",
    "JAJA Bless Ji": "jaja-bless-ji",
    "JAJEH Jennifer": "jajeh-jennifer",
    "JAKES John": "jakes-john",
    "JAKOBI Gabriele": "jakobi-gabriele",
    "JAKOBSEN Mette": "jakobsen-mette",
    "JAKOBSSON Jokull": "jakobsson-jokull",
    "JAKOBSSON Robert": "jakobsson-robert",
    "JAKSH Helen": "jaksh-helen",
    "JAKSZEWICZ Tara": "jakszewicz-tara",
    "JAKUCIONIS Michael": "jakucionis-michael",
    "JALAKAS Peeter": "jalakas-peeter",
    "JALALY Sonyia": "jalaly-sonyia",
    "JALBERT Jolie": "jalbert-jolie",
    "JALBERT Michael": "jalbert-michael",
    "JALENAK Jan": "jalenak-jan",
    "JALLO Zainabu": "jallo-zainabu",
    "JALLOH Usifu": "jalloh-usifu",
    "JAMAIL Steven": "jamail-steven",
    "JAMAJZELI Jan": "jamajzeli-jan",
    "JAMAL ": "jamal",
    "JAMBOR Joseph": "jambor-joseph",
    "JAMERSON Pauline": "jamerson-pauline",
    "JAMERSON Tommy": "jamerson-tommy",
    "JAMES Adam-Michael": "james-adam-michael",
    "JAMES Adrian": "james-adrian",
    "JAMES Alby": "james-alby",
    "JAMES Alec": "james-alec",
    "JAMES Allston": "james-allston",
    "JAMES Andrea": "james-andrea",
    "JAMES Annie": "james-annie",
    "JAMES Anthony": "james-anthony",
    "JAMES Brian": "james-brian",
    "JAMES C L R": "james-c-l-r",
    "JAMES Caroline": "james-caroline",
    "JAMES Cary": "james-cary",
    "JAMES Charlene": "james-charlene",
    "JAMES Christopher": "james-christopher",
    "JAMES Clive": "james-clive",
    "JAMES Colin": "james-colin",
    "JAMES Creighton": "james-creighton",
    "JAMES Dafydd": "james-dafydd",
    "JAMES Daniel": "james-daniel",
    "JAMES Darius": "james-darius",
    "JAMES Darren": "james-darren",
    "JAMES David": "james-david",
    "JAMES Derek": "james-derek",
    "JAMES Diqui": "james-diqui",
    "JAMES E L": "james-e-l",
    "JAMES Eli": "james-eli",
    "JAMES Elis": "james-elis",
    "JAMES Emily": "james-emily",
    "JAMES Eric": "james-eric",
    "JAMES Georgia": "james-georgia",
    "JAMES Grace": "james-grace",
    "JAMES Guy": "james-guy",
    "JAMES Harold Dean": "james-harold-dean",
    "JAMES Henry": "james-henry",
    "JAMES Hugh": "james-hugh",
    "JAMES J W": "james-j-w",
    "JAMES James": "james-james",
    "JAMES Jeff": "james-jeff",
    "JAMES Jennye": "james-jennye",
    "JAMES Jeremy": "james-jeremy",
    "JAMES Jeremy (1)": "james-jeremy-1",
    "JAMES Jerry": "james-jerry",
    "JAMES Jimmie": "james-jimmie",
    "JAMES Johanna": "james-johanna",
    "JAMES John": "james-john",
    "JAMES Joshua": "james-joshua",
    "JAMES Julia": "james-julia",
    "JAMES Karl": "crouch-tim",
    "JAMES Kate": "james-kate",
    "JAMES Katherine": "james-katherine",
    "JAMES Laurie": "james-laurie",
    "JAMES Lennie": "james-lennie",
    "JAMES Lisa Michelle": "james-lisa-michelle",
    "JAMES Martin": "james-martin",
    "JAMES Martinson": "james-martinson",
    "JAMES Matthew": "james-matthew",
    "JAMES Michael": "james-michael",
    "JAMES Michael T": "james-michael-t",
    "JAMES Mike": "james-mike",
    "JAMES Natasha": "james-natasha",
    "JAMES Nathan": "james-nathan",
    "JAMES Paul": "james-paul",
    "JAMES Richard": "james-richard",
    "JAMES Rowan": "james-rowan",
    "JAMES Sarah C": "james-sarah-c",
    "JAMES Sheila": "james-sheila",
    "JAMES Sidney": "james-sidney",
    "JAMES Stella Wyn": "james-stella-wyn",
    "JAMES Stephen": "james-stephen",
    "JAMES Steve Eaton": "james-steve-eaton",
    "JAMES Terry": "james-terry",
    "JAMES Tyler": "james-tyler",
    "JAMES Vlad": "james-vlad",
    "JAMES Winsome": "james-winsome",
    "JAMESON Bethany": "jameson-bethany",
    "JAMESON Greg": "jameson-greg",
    "JAMESON James Wayne": "jameson-james-wayne",
    "JAMESON Louise": "jameson-louise",
    "JAMESON Luda": "jameson-luda",
    "JAMESON Martin": "jameson-martin",
    "JAMESON Matthew": "jameson-matthew",
    "JAMESON Rebecca": "jameson-rebecca",
    "JAMESON Samuel": "jameson-samuel",
    "JAMESON Stephen": "jameson-stephen",
    "JAMIE Kathleen": "jamie-kathleen",
    "JAMIESON Daniel": "jamieson-daniel",
    "JAMIESON Dawn": "jamieson-dawn",
    "JAMIESON Dylan": "jamieson-dylan",
    "JAMIESON Morley": "jamieson-morley",
    "JAMIESON Nigel": "jamieson-nigel",
    "JAMIESON Trevor": "jamieson-trevor",
    "JAMIESON-KARAHA Tess": "jamieson-karaha-tess",
    "JAMISON Jesse": "jamison-jesse",
    "JAMISON Robert Edward": "jamison-robert-edward",
    "JAMISON JR Charles N": "jamison-jr-charles-n",
    "JAMMY VOO ": "jammy-voo",
    "JAMROZ Gerard": "jamroz-gerard",
    "JAMULA Jen": "jamula-jen",
    "JAN Lars": "jan-lars",
    "JAN FABRE CO, THE ": "jan-fabre-co",
    "JANACZEWSKA Noelle": "janaczewska-noelle",
    "JANARO Richard": "janaro-richard",
    "JANCKE Carter": "jancke-carter",
    "JANDA J": "janda-j",
    "JANDL Ernst": "jandl-ernst",
    "JANDRELL Gareth": "jandrell-gareth",
    "JANE Betty": "jane-betty",
    "JANE Eris": "jane-eris",
    "JANE Lara": "jane-lara",
    "JANE Mary": "jane-mary",
    "JANES Alan": "janes-alan",
    "JANES Hugh": "janes-hugh",
    "JANES Joe": "janes-joe",
    "JANES Kenneth": "janes-kenneth",
    "JANES Tad": "janes-tad",
    "JANEWAY Carol Brown": "janeway-carol-brown",
    "JANG Patricia": "jang-patricia",
    "JANICE Obehi": "janice-obehi",
    "JANIK Ada": "janik-ada",
    "JANIN Zuzanna": "janin-zuzanna",
    "JANIS Byron": "janis-byron",
    "JANIS Gay": "janis-gay",
    "JANIS Victoria": "janis-victoria",
    "JANIUREK Lenka": "janiurek-lenka",
    "JANK Rick": "jank-rick",
    "JANKELL Alice": "jankell-alice",
    "JANKO Gary": "janko-gary",
    "JANKO-SZEP Yvette": "janko-szep-yvette",
    "JANKOWIAK Gunter": "jankowiak-gunter",
    "JANNATIE Iraj": "jannatie-iraj",
    "JANNEY Tony": "janney-tony",
    "JANNUZZI Luigi": "jannuzzi-luigi",
    "JANOS Novak": "janos-novak",
    "JANOVE David": "janove-david",
    "JANOWICZ Sasha": "janowicz-sasha",
    "JANOWSKI Maurycy": "janowski-maurycy",
    "JANS Alaric": "jans-alaric",
    "JANSE Saskia": "janse-saskia",
    "JANSEN Catherine": "jansen-catherine",
    "JANSEN Paul": "jansen-paul",
    "JANSEN Peter": "jansen-peter",
    "JANSEN Vallimar": "jansen-vallimar",
    "JANSON Julie": "janson-julie",
    "JANSONS Andrejs": "jansons-andrejs",
    "JANSSEN Berni": "janssen-berni",
    "JANSSEN Jacob": "janssen-jacob",
    "JANSSEN Stephanie": "janssen-stephanie",
    "JANSSEN-FAITH Ishah": "janssen-faith-ishah",
    "JANZ Heidi": "janz-heidi",
    "JAO Radmar": "jao-radmar",
    "JAQMIN Laura": "jaqmin-laura",
    "JAQUES Howard": "jaques-howard",
    "JAQUES Martyn": "jaques-martyn",
    "JAQUET Krista": "jaquet-krista",
    "JAQUISH Jeannette": "jaquish-jeannette",
    "JARBOE Richard": "jarboe-richard",
    "JARCHO Julia": "jarcho-julia",
    "JAREL Julia": "jarel-julia",
    "JARMAN Robert": "jarman-robert",
    "JARMAN Tama": "jarman-tama",
    "JARMAN Tim": "jarman-tim",
    "JARMY Rachael": "jarmy-rachael",
    "JARREAU Marcy": "jarreau-marcy",
    "JARRELL Adam": "jarrell-adam",
    "JARRETT Andrew": "jarrett-andrew",
    "JARRETT Candice": "jarrett-candice",
    "JARRETT Isabella": "jarrett-isabella",
    "JARRETT Jennifer": "jarrett-jennifer",
    "JARRETT Keith ": "jarrett-keith",
    "JARROW Kyle": "jarrow-kyle",
    "JARRY Alfred": "jarry-alfred",
    "JARVIK Elaine": "jarvik-elaine",
    "JARVIS Charlotte": "jarvis-charlotte",
    "JARVIS Liam": "jarvis-liam",
    "JARVIS Martin": "jarvis-martin",
    "JARVIS Sarah": "jarvis-sarah",
    "JARVIS Seth Michael": "jarvis-seth-michael",
    "JARZYNA Grzegorz": "jarzyna-grzegorz",
    "JASINA Joseph": "jasina-joseph",
    "JASON Michael": "jason-michael",
    "JASON Neil": "jason-neil",
    "JASON Riley": "jason-riley",
    "JASPER Jennifer": "jasper-jennifer",
    "JASPER May": "jasper-may",
    "JASPERS Carleen R": "jaspers-carleen-r",
    "JASPERS Edward": "jaspers-edward",
    "JASPRIZZA Sharon": "jasprizza-sharon",
    "JASSPE Arthur": "jasspe-arthur",
    "JASTER Mark": "jaster-mark",
    "JASTROCH Beth": "jastroch-beth",
    "JASTROW Terry": "jastrow-terry",
    "JASTRZEBSKA Maria": "jastrzebska-maria",
    "JAVERBAUM David": "javerbaum-david",
    "JAVIE Ken": "javie-ken",
    "JAVITTS Joan": "javitts-joan",
    "JAVOR Isabella": "javor-isabella",
    "JAWOROWSKI Ken": "jaworowski-ken",
    "JAY Ami": "jay-ami",
    "JAY Anthony": "jay-anthony",
    "JAY Dave": "jay-dave",
    "JAY David": "jay-david",
    "JAY Harriet": "jay-harriet",
    "JAY Jake": "jay-jake",
    "JAY M": "jay-m",
    "JAY Ronald": "jay-ronald",
    "JAY Simon": "jay-simon",
    "JAY Stevie": "jay-stevie",
    "JAY Tina": "jay-tina",
    "JAYNE Lillie": "jayne-lillie",
    "JAYSEN Jill": "jaysen-jill",
    "JAYSMITH Sarah": "jaysmith-sarah",
    "JAYYUSI Salma Khadra": "jayyusi-salma-khadra",
    "JAZZ FREDDY ": "jazz-freddy",
    "JDARRA Kooemba": "jdarra-kooemba",
    "JE COMPANY ": "j-e-company",
    "JEALOUS WHALE THEATRE ": "jealous-whale-theatre",
    "JEANES Dave": "jeanes-dave",
    "JEANMARIE Veronique": "jeanmarie-veronique",
    "JEAN-PHILIPPE Pharah": "jean-philippe-pharah",
    "JEAN-PIERRE Edwige": "jean-pierre-edwige",
    "JEANS A A": "jeans-a-a",
    "JEANS Ronald": "jeans-ronald",
    "JEARY Mark": "jeary-mark",
    "JEAVONS Amy": "jeavons-amy",
    "JEBB Richard Claverhouse": "jebb-richard-claverhouse",
    "JEEP Dr": "jeep-dr",
    "JEFF Paul": "jeff-paul",
    "JEFFERIES Bill": "jefferies-bill",
    "JEFFERIES Claudia": "jefferies-claudia",
    "JEFFERIES Clint": "jefferies-clint",
    "JEFFERS Andy": "jeffers-andy",
    "JEFFERS David": "jeffers-david",
    "JEFFERS Gaye": "jeffers-gaye",
    "JEFFERS Juliette": "jeffers-juliette",
    "JEFFERS Oliver": "jeffers-oliver",
    "JEFFERS Robinson": "jeffers-robinson",
    "JEFFERSON Anna": "jefferson-anna",
    "JEFFERSON Blind Lemon": "jefferson-blind-lemon",
    "JEFFERSON Emily": "jefferson-emily",
    "JEFFERSON Ian": "jefferson-ian",
    "JEFFERSON Ollie L": "jefferson-ollie-l",
    "JEFFERSON Samuel": "jefferson-samuel",
    "JEFFERSON Teddy": "jefferson-teddy",
    "JEFFERY Heather": "jeffery-heather",
    "JEFFERY Lawrence": "jeffery-lawrence",
    "JEFFERY Michael": "jeffery-michael",
    "JEFFERY Michael (1)": "jeffery-michael-1",
    "JEFFORDS Trent": "jeffords-trent",
    "JEFFREY Bob": "jeffrey-bob",
    "JEFFREY C F": "jeffrey-c-f",
    "JEFFREY Colin": "jeffrey-colin",
    "JEFFREY Ewan": "jeffrey-ewan",
    "JEFFREY Michael": "jeffrey-michael",
    "JEFFREY Michaela": "jeffrey-michaela",
    "JEFFREY Ronnie": "jeffrey-ronnie",
    "JEFFREY Tillie": "jeffrey-tillie",
    "JEFFREY-POULTER Stephen": "jeffrey-poulter-stephen",
    "JEFFREYS Ben": "jeffreys-ben",
    "JEFFREYS Robert": "jeffreys-robert",
    "JEFFREYS Stephen": "jeffreys-stephen",
    "JEFFREYS Stephen (1)": "jeffreys-stephen-1",
    "JEFFRIES Brian": "jeffries-brian",
    "JEFFRIES Charles R": "jeffries-charles-r",
    "JEFFRIES Chris": "jeffries-chris",
    "JEFFRIES Diane": "jeffries-diane",
    "JEFFRIES Jay": "jeffries-jay",
    "JEFFRIES Mike": "jeffries-mike",
    "JEFFRIES Ty": "jeffries-ty",
    "JEFFS Ann": "jeffs-ann",
    "JEFFS Anna": "jeffs-anna",
    "JEFRIES III James": "jefries-iii-james",
    "JEHLEN Wendy": "jehlen-wendy",
    "JELINEK Elfriede": "jelinek-elfriede",
    "JELLICOE Ann": "jellicoe-ann",
    "JELLIFFE Jessica": "jelliffe-jessica",
    "JEMMETT Dan": "jemmett-dan",
    "JENDEN Paul": "jenden-paul",
    "JENDER Jem": "jender-jem",
    "JENKIN Guy": "jenkin-guy",
    "JENKIN Len": "jenkin-len",
    "JENKIN SM": "jenkin-sm",
    "JENKINS Annie": "jenkins-annie",
    "JENKINS Cecil": "jenkins-cecil",
    "JENKINS Daniel": "jenkins-daniel",
    "JENKINS David": "jenkins-david",
    "JENKINS David (1)": "jenkins-david-1",
    "JENKINS Diana R": "jenkins-diana-r",
    "JENKINS Emily": "jenkins-emily",
    "JENKINS Genevieve": "jenkins-genevieve",
    "JENKINS Greg": "jenkins-greg",
    "JENKINS Jeff": "jenkins-jeff",
    "JENKINS Jimmy": "jenkins-jimmy",
    "JENKINS Juliet": "jenkins-juliet",
    "JENKINS Ken": "jenkins-ken",
    "JENKINS Lee": "jenkins-lee",
    "JENKINS Lindsay": "jenkins-lindsay",
    "JENKINS Louie": "jenkins-louie",
    "JENKINS Louis": "jenkins-louis",
    "JENKINS Lowri": "jenkins-lowri",
    "JENKINS Mark": "jenkins-mark",
    "JENKINS Maureen": "jenkins-maureen",
    "JENKINS Megan": "jenkins-megan",
    "JENKINS Mercilee": "jenkins-mercilee",
    "JENKINS Nikki M": "jenkins-nikki-m",
    "JENKINS Paul": "jenkins-paul",
    "JENKINS Peter": "jenkins-peter",
    "JENKINS Ray": "jenkins-ray",
    "JENKINS Robert": "jenkins-robert",
    "JENKINS Robin": "jenkins-robin",
    "JENKINS Ron": "jenkins-ron",
    "JENKINS Roy": "jenkins-roy",
    "JENKINS Sylvia Ann": "jenkins-sylvia-ann",
    "JENKINS Valoreyne Brandt": "jenkins-valoreyne-brandt",
    "JENKINS Warren": "jenkins-warren",
    "JENKINSON Kinahan": "jenkinson-kinahan",
    "JENKINSON Mark": "jenkinson-mark",
    "JENKINSON Rosemary": "jenkinson-rosemary",
    "JENKINS-SHAW Sam": "jenkins-shaw-sam",
    "JENKO Erika": "jenko-erika",
    "JENKS JR Almet F": "jenks-jr-almet-f",
    "JENNESS David": "jenness-david",
    "JENNINGS Adam": "jennings-adam",
    "JENNINGS Brad": "jennings-brad",
    "JENNINGS Caleen Sinnette": "jennings-caleen-sinnette",
    "JENNINGS Charles": "jennings-charles",
    "JENNINGS Chris": "jennings-chris",
    "JENNINGS Coleman A": "jennings-coleman-a",
    "JENNINGS Corrine": "jennings-corrine",
    "JENNINGS Fabian": "jennings-fabian",
    "JENNINGS James": "jennings-james",
    "JENNINGS John": "jennings-john",
    "JENNINGS Karla": "jennings-karla",
    "JENNINGS Kelly A": "jennings-kelly-a",
    "JENNINGS Ken": "jennings-ken",
    "JENNINGS Matt": "jennings-matt",
    "JENNINGS Paul": "jennings-paul",
    "JENNINGS Raul": "jennings-raul",
    "JENNINGS Richard": "jennings-richard",
    "JENNINGS Sandra": "jennings-sandra",
    "JENNINGS Sharon": "jennings-sharon",
    "JENNINGS Sue Emmy": "jennings-sue-emmy",
    "JENNINGS Wayne": "jennings-wayne",
    "JENNISON Joe": "jennison-joe",
    "JENSEN Amy": "jensen-amy",
    "JENSEN Craig": "jensen-craig",
    "JENSEN David": "jensen-david",
    "JENSEN Erica": "jensen-erica",
    "JENSEN Erik": "jensen-erik",
    "JENSEN Eugenia": "jensen-eugenia",
    "JENSEN Holly L": "jensen-holly-l",
    "JENSEN Julie": "jensen-julie",
    "JENSEN Lorre": "jensen-lorre",
    "JENSEN Mark Steven": "jensen-mark-steven",
    "JENSEN Tom": "jensen-tom",
    "JENT Deanna": "jent-deanna",
    "JEPHCOTT Mark": "jephcott-mark",
    "JEPHTA Amy": "jephta-amy",
    "JEPPSON Jake": "jeppson-jake",
    "JEPSON Paul": "jepson-paul",
    "JEREMY Susan": "jeremy-susan",
    "JERMAIN Clive": "jermain-clive",
    "JERMIN Mark": "jermin-mark",
    "JERMOND Simon": "jermond-simon",
    "JERMYN Gary": "jermyn-gary",
    "JERNIGAN Charles": "jernigan-charles",
    "JERNIGAN Laura Bess": "jernigan-laura-bess",
    "JEROME Carlos": "jerome-carlos",
    "JEROME Helen": "jerome-helen",
    "JEROME DESCHAMPS CO ": "jerome-deschamps-co",
    "JERRIS Tony": "jerris-tony",
    "JESERUN John": "jeserun-john",
    "JESKE Joel": "jeske-joel",
    "JESKE Juliet": "jeske-juliet",
    "JESSE Bill": "jesse-bill",
    "JESSE F Tennyson": "jesse-f-tennyson",
    "JESSEE Genevieve": "jessee-genevieve",
    "JESSEL Raymond": "jessel-raymond",
    "JESSEN Craig": "jessen-craig",
    "JESSON-DIDLEY David": "jesson-didley-david",
    "JESSUP Frances": "jessup-frances",
    "JESTER Michael": "jester-michael",
    "JESTER Nick": "jester-nick",
    "JESTROVIC Silvija": "jestrovic-silvija",
    "JESURUN John": "jesurun-john",
    "JESUS AND TRACY ": "jesus-and-tracy",
    "JETER John": "jeter-john",
    "JETNIKOFF Peter": "jetnikoff-peter",
    "JETT Luther": "jett-luther",
    "JEVICKI Adrian": "jevicki-adrian",
    "JEWELL Susan Carroll": "jewell-susan-carroll",
    "JEYAKUMAR Vishakan": "jeyakumar-vishakan",
    "JEYNES Karen": "jeynes-karen"
  }
};