export default {
  "metadata": {
    "results": 698,
    "timeStamp": "2025-12-05T21:26:18.872Z",
    "url": "https://www.doollee.com/PlaywrightsJ/J_playwrights_m-r.php"
  },
  "authors": {
    "JOACHIM Thomas William": "joachim-thomas-william",
    "JOAQUIN Nick": "joaquin-nick",
    "JOB Heather Noel": "job-heather-noel",
    "JOBBINS Sheridan": "jobbins-sheridan",
    "JOBES Stephen": "jobes-stephen",
    "JOBIN Gilles": "jobin-gilles",
    "JOBLING David Paul": "jobling-david-paul",
    "JOBLING Ed": "jobling-ed",
    "JOBURN Dorothea": "joburn-dorothea",
    "JOCELYN Ann Henning": "jocelyn-ann-henning",
    "JOCELYN Matthew": "jocelyn-matthew",
    "JODI Gallagher": "jodi-gallagher",
    "JOE Nathan": "joe-nathan",
    "JOE T Y": "joe-t-y",
    "JOEL Isaac Ben": "joel-isaac-ben",
    "JOEL Micah": "joel-micah",
    "JOELLE Lindsay": "joelle-lindsay",
    "JOENKS Mark": "joenks-mark",
    "JOES Richard T": "joes-richard-t",
    "JOEYS, THE ": "joeys-the",
    "JOFFE Andrew": "joffe-andrew",
    "JOFFE NUMEROFF Laura": "joffe-numeroff-laura",
    "JOFFRE Sara Elotilde": "joffre-sara-elotilde",
    "JOFFREY Lanna": "joffrey-lanna",
    "JOGLARS Els": "joglars-els",
    "JOHAARDIEN Ashraf": "johaardien-ashraf",
    "JOHANNSEN Ernst": "johannsen-ernst",
    "JOHANSEN Herman": "johansen-herman",
    "JOHANSEN Rob": "johansen-rob",
    "JOHANSON Jon": "johanson-jon",
    "JOHANSON Lynn-Steven": "johanson-lynn-steven",
    "JOHANSON Robert": "johanson-robert",
    "JOHANSSON Emily": "johansson-emily",
    "JOHANSSON Eva C": "johansson-eva-c",
    "JOHN Cornell S": "john-cornell-s",
    "JOHN David": "john-david",
    "JOHN Elton": "john-elton",
    "JOHN Emyr": "john-emyr",
    "JOHN Eric John": "john-eric-john",
    "JOHN Errol": "john-errol",
    "JOHN George": "john-george",
    "JOHN Graham": "john-graham",
    "JOHN Hywel": "john-hywel",
    "JOHN Josephine": "john-josephine",
    "JOHN Liz": "john-liz",
    "JOHN Lynn": "john-lynn",
    "JOHN Miriam": "john-miriam",
    "JOHN Peter": "john-peter",
    "JOHN Rob": "john-rob",
    "JOHN Rosemary": "john-rosemary",
    "JOHN Sean Tuan": "john-sean-tuan",
    "JOHN WRIGHT COMPANY ": "john-wright-company",
    "JOHN-ANTHONY Patrick": "john-anthony-patrick",
    "JOHNKE Erik": "johnke-erik",
    "JOHNNY'S HORSE ": "johnny-s-horse",
    "JOHNS Andrew": "johns-andrew",
    "JOHNS Ariana": "johns-ariana",
    "JOHNS Christina Jacqueline": "johns-christina-jacqueline",
    "JOHNS Dave": "johns-dave",
    "JOHNS Gavin": "johns-gavin",
    "JOHNS Megan": "johns-megan",
    "JOHNS Merryn": "johns-merryn",
    "JOHNS Patti": "johns-patti",
    "JOHNS R": "johns-r",
    "JOHNS Sarah": "johns-sarah",
    "JOHNS Ted": "johns-ted",
    "JOHNS Tere": "johns-tere",
    "JOHNSON Aaron James": "johnson-aaron-james",
    "JOHNSON Adrian": "johnson-adrian",
    "JOHNSON Alex": "johnson-alex",
    "JOHNSON Alexander J": "johnson-alexander-j",
    "JOHNSON Alicia": "johnson-alicia",
    "JOHNSON Angie": "johnson-angie",
    "JOHNSON Anna": "johnson-anna",
    "JOHNSON B S": "johnson-b-s",
    "JOHNSON Berit": "johnson-berit",
    "JOHNSON Bill": "johnson-bill",
    "JOHNSON Brad": "johnson-brad",
    "JOHNSON Brandon": "johnson-brandon",
    "JOHNSON Brandon F": "johnson-brandon-f",
    "JOHNSON Brandt": "johnson-brandt",
    "JOHNSON Brian": "johnson-brian",
    "JOHNSON BS": "johnson-bs",
    "JOHNSON C A": "johnson-c-a",
    "JOHNSON C J": "johnson-c-j",
    "JOHNSON Cam": "johnson-cam",
    "JOHNSON Carleene": "johnson-carleene",
    "JOHNSON Carol": "johnson-carol",
    "JOHNSON Catherine": "johnson-catherine",
    "JOHNSON Charles R": "johnson-charles-r",
    "JOHNSON Chris": "johnson-chris",
    "JOHNSON Christine Toy": "johnson-christine-toy",
    "JOHNSON Christopher": "johnson-christopher",
    "JOHNSON Christopher (1)": "johnson-christopher-1",
    "JOHNSON Cindy Lou": "johnson-cindy-lou",
    "JOHNSON Claudia": "johnson-claudia",
    "JOHNSON Clifton Theodore": "johnson-clifton-theodore",
    "JOHNSON Colette R": "johnson-colette-r",
    "JOHNSON Colleen": "johnson-colleen",
    "JOHNSON Collin": "johnson-collin",
    "JOHNSON Craig": "johnson-craig",
    "JOHNSON Crane": "johnson-crane",
    "JOHNSON Dale": "johnson-dale",
    "JOHNSON Daniel": "johnson-daniel",
    "JOHNSON Daran": "johnson-daran",
    "JOHNSON Darrick": "johnson-darrick",
    "JOHNSON Daryl": "johnson-daryl",
    "JOHNSON Dave": "johnson-dave",
    "JOHNSON David": "johnson-david",
    "JOHNSON David P": "johnson-david-p",
    "JOHNSON Dean": "johnson-dean",
    "JOHNSON Deborah": "johnson-deborah",
    "JOHNSON Denis": "johnson-denis",
    "JOHNSON Diana Marr": "johnson-diana-marr",
    "JOHNSON Donna": "johnson-donna",
    "JOHNSON Donovan": "johnson-donovan",
    "JOHNSON Douglas": "johnson-douglas",
    "JOHNSON E Patrick": "johnson-e-patrick",
    "JOHNSON Ebonee J": "johnson-ebonee-j",
    "JOHNSON Elli": "johnson-elli",
    "JOHNSON Eric": "johnson-eric",
    "JOHNSON Eugene": "johnson-eugene",
    "JOHNSON Eva": "johnson-eva",
    "JOHNSON Eva (1)": "johnson-eva-1",
    "JOHNSON Frankie": "johnson-frankie",
    "JOHNSON George M": "johnson-george-m",
    "JOHNSON Georgia Douglas": "johnson-georgia-douglas",
    "JOHNSON Gib": "johnson-gib",
    "JOHNSON Glenn": "johnson-glenn",
    "JOHNSON Glenn Conner": "johnson-glenn-conner",
    "JOHNSON Greer": "johnson-greer",
    "JOHNSON Hank": "johnson-hank",
    "JOHNSON Harvey": "johnson-harvey",
    "JOHNSON Herman": "johnson-herman",
    "JOHNSON Howard": "johnson-howard",
    "JOHNSON J C": "johnson-j-c",
    "JOHNSON James": "johnson-james",
    "JOHNSON James Weldon": "johnson-james-weldon",
    "JOHNSON Javon": "johnson-javon",
    "JOHNSON Jay": "johnson-jay",
    "JOHNSON Jay (1)": "johnson-jay-1",
    "JOHNSON Jen Geigle": "johnson-jen-geigle",
    "JOHNSON Jeremy": "johnson-jeremy",
    "JOHNSON Jeremy B": "johnson-jeremy-b",
    "JOHNSON Jesse David": "johnson-jesse-david",
    "JOHNSON Jessica": "johnson-jessica",
    "JOHNSON Jessica Lynn": "johnson-jessica-lynn",
    "JOHNSON Jill": "johnson-jill",
    "JOHNSON Joan Eyles": "johnson-joan-eyles",
    "JOHNSON Joe": "johnson-joe",
    "JOHNSON Joel Drake": "johnson-joel-drake",
    "JOHNSON Joel R": "johnson-joel-r",
    "JOHNSON Jon Jon": "johnson-jon-jon",
    "JOHNSON Jordan": "johnson-jordan",
    "JOHNSON Judith": "johnson-judith",
    "JOHNSON Karena": "johnson-karena",
    "JOHNSON Keith": "johnson-keith",
    "JOHNSON Kenneth O": "johnson-kenneth-o",
    "JOHNSON Kevin": "johnson-kevin",
    "JOHNSON Kevin Ray": "johnson-kevin-ray",
    "JOHNSON Lance": "johnson-lance",
    "JOHNSON Larry": "johnson-larry",
    "JOHNSON Lauren": "johnson-lauren",
    "JOHNSON Lee": "johnson-lee",
    "JOHNSON Libby": "johnson-libby",
    "JOHNSON Lisa": "johnson-lisa",
    "JOHNSON Lola": "johnson-lola",
    "JOHNSON Louis": "johnson-louis",
    "JOHNSON Lucy": "johnson-lucy",
    "JOHNSON M Zachary": "johnson-m-zachary",
    "JOHNSON Marcia": "johnson-marcia",
    "JOHNSON Marion": "johnson-marion",
    "JOHNSON Mark": "johnson-mark",
    "JOHNSON Mary Donnet": "johnson-mary-donnet",
    "JOHNSON Matt": "johnson-matt",
    "JOHNSON Matthew": "johnson-matthew",
    "JOHNSON Maureen Brady": "johnson-maureen-brady",
    "JOHNSON Melody": "johnson-melody",
    "JOHNSON Michelle T": "johnson-michelle-t",
    "JOHNSON Mike": "johnson-mike",
    "JOHNSON Mike (2)": "johnson-mike-2",
    "JOHNSON Miki": "johnson-miki",
    "JOHNSON Monika": "johnson-monika",
    "JOHNSON Niki": "johnson-niki",
    "JOHNSON Nunnally": "johnson-nunnally",
    "JOHNSON Onni": "johnson-onni",
    "JOHNSON Oscar L": "johnson-oscar-l",
    "JOHNSON Pamela Hansford": "johnson-pamela-hansford",
    "JOHNSON Patricia": "johnson-patricia",
    "JOHNSON Paul": "johnson-paul",
    "JOHNSON Paul (1)": "johnson-paul-1",
    "JOHNSON Paul Alan": "johnson-paul-alan",
    "JOHNSON Paul L": "johnson-paul-l",
    "JOHNSON Pete": "johnson-pete",
    "JOHNSON Peter": "johnson-peter",
    "JOHNSON Phil": "johnson-phil",
    "JOHNSON Philip": "johnson-philip",
    "JOHNSON Quynn": "johnson-quynn",
    "JOHNSON Randy": "johnson-randy",
    "JOHNSON Ray": "johnson-ray",
    "JOHNSON Rebekka": "johnson-rebekka",
    "JOHNSON Reuben": "johnson-reuben",
    "JOHNSON Rhondda": "johnson-rhondda",
    "JOHNSON Richard": "johnson-richard",
    "JOHNSON Richard T": "johnson-richard-t",
    "JOHNSON Rob": "johnson-rob",
    "JOHNSON Robert": "johnson-robert",
    "JOHNSON Robert Henry": "johnson-robert-henry",
    "JOHNSON Robin": "johnson-robin",
    "JOHNSON S Ann": "johnson-s-ann",
    "JOHNSON Sandee": "johnson-sandee",
    "JOHNSON Sandi L": "johnson-sandi-l",
    "JOHNSON Sarah": "johnson-sarah",
    "JOHNSON Sarah East": "johnson-sarah-east",
    "JOHNSON Sarah Jane": "johnson-sarah-jane",
    "JOHNSON Sherrie": "johnson-sherrie",
    "JOHNSON Sofia": "johnson-sofia",
    "JOHNSON Star": "johnson-star",
    "JOHNSON Starina": "johnson-starina",
    "JOHNSON Stephanie": "johnson-stephanie",
    "JOHNSON Stephen Burge": "johnson-stephen-burge",
    "JOHNSON Susan E": "johnson-susan-e",
    "JOHNSON Terry": "johnson-terry",
    "JOHNSON Tom": "johnson-tom",
    "JOHNSON Tom (1)": "johnson-tom-1",
    "JOHNSON Tom S": "johnson-tom-s",
    "JOHNSON Trevor": "johnson-trevor",
    "JOHNSON Trish": "johnson-trish",
    "JOHNSON Troy Britton": "johnson-troy-britton",
    "JOHNSON W Christopher": "johnson-w-christopher",
    "JOHNSON Walter": "johnson-walter",
    "JOHNSON Will": "johnson-will",
    "JOHNSON William": "johnson-william",
    "JOHNSON William P": "johnson-william-p",
    "JOHNSON Willie": "johnson-willie",
    "JOHNSON III Clifford Lee": "johnson-iii-clifford-lee",
    "JOHNSON-ERDAY Emily": "johnson-erday-emily",
    "JOHNSON-MUNDAY Oli": "johnson-munday-oli",
    "JOHNSSON Melker": "johnsson-melker",
    "JOHNSTON Aaron": "johnston-aaron",
    "JOHNSTON Alex": "johnston-alex",
    "JOHNSTON Anthony": "johnston-anthony",
    "JOHNSTON Arnold": "johnston-arnold",
    "JOHNSTON Audre": "johnston-audre",
    "JOHNSTON Bob": "johnston-bob",
    "JOHNSTON Brian": "johnston-brian",
    "JOHNSTON Chloe": "johnston-chloe",
    "JOHNSTON Chris": "johnston-chris",
    "JOHNSTON Christine": "johnston-christine",
    "JOHNSTON Clinton": "johnston-clinton",
    "JOHNSTON David": "johnston-david",
    "JOHNSTON David (2)": "johnston-david-2",
    "JOHNSTON Denis": "johnston-denis",
    "JOHNSTON Douglas Lee": "johnston-douglas-lee",
    "JOHNSTON Dru": "johnston-dru",
    "JOHNSTON Fred": "johnston-fred",
    "JOHNSTON George": "johnston-george",
    "JOHNSTON Gregory": "johnston-gregory",
    "JOHNSTON Heather": "johnston-heather",
    "JOHNSTON Howard": "johnston-howard",
    "JOHNSTON Ian": "johnston-ian",
    "JOHNSTON J M": "johnston-j-m",
    "JOHNSTON Jennifer": "johnston-jennifer",
    "JOHNSTON Kate": "johnston-kate",
    "JOHNSTON M G": "johnston-m-g",
    "JOHNSTON Mel": "johnston-mel",
    "JOHNSTON Michael": "johnston-michael",
    "JOHNSTON Michael Corkett": "johnston-michael-corkett",
    "JOHNSTON Patricia D": "johnston-patricia-d",
    "JOHNSTON Rea": "johnston-rea",
    "JOHNSTON Rick": "johnston-rick",
    "JOHNSTON Rob": "johnston-rob",
    "JOHNSTON Robert": "johnston-robert",
    "JOHNSTON Rosemary": "johnston-rosemary",
    "JOHNSTON Simon": "johnston-simon",
    "JOHNSTON Susan": "johnston-susan",
    "JOHNSTON Tommy Lee": "johnston-tommy-lee",
    "JOHNSTONBROWN Anne": "johnstonbrown-anne",
    "JOHNSTONE Caito": "johnstone-caito",
    "JOHNSTONE David W W": "johnstone-david-w-w",
    "JOHNSTONE Deborah": "johnstone-deborah",
    "JOHNSTONE Iain": "johnstone-iain",
    "JOHNSTONE J Andrew": "johnstone-j-andrew",
    "JOHNSTONE Keith": "johnstone-keith",
    "JOHNSTONE Kenneth": "johnstone-kenneth",
    "JOHNSTONE Leigh": "johnstone-leigh",
    "JOHNSTONE Stephanie": "johnstone-stephanie",
    "JOHNSTONE Steven": "johnstone-steven",
    "JOHNSTONE Will B": "johnstone-will-b",
    "JOH-YEOL Park": "joh-yeol-park",
    "JOINER Brandon": "joiner-brandon",
    "JOINER Evan": "joiner-evan",
    "JOINER Rob": "joiner-rob",
    "JOINT STOCK ": "joint-stock",
    "JOIO Vicki Dello": "joio-vicki-dello",
    "JOKELA Juha": "jokela-juha",
    "JOLAS Maria": "jolas-maria",
    "JOLAYEMI Demola": "jolayemi-demola",
    "JOLIE ": "jolie",
    "JOLING Teo": "joling-teo",
    "JOLIVET Ben": "jolivet-ben",
    "JOLLES Annette": "jolles-annette",
    "JOLLEY Mildred": "jolley-mildred",
    "JOLLEY Rachael": "jolley-rachael",
    "JOLLIFFE Edmund": "jolliffe-edmund",
    "JOLLIFFE-HAAS Darin L": "jolliffe-haas-darin-l",
    "JOLLY Alice": "jolly-alice",
    "JOLLY Arthur M": "jolly-arthur-m",
    "JOLLY Donald": "jolly-donald",
    "JOLLY Russ": "jolly-russ",
    "JOLLY LLAMA GROUP, THE ": "jolly-llama-group",
    "JONAS George": "jonas-george",
    "JONAS Josh": "jonas-josh",
    "JONAS Julia May": "jonas-julia-may",
    "JONAS Nita": "jonas-nita",
    "JONASSON Jon Atli": "jonasson-jon-atli",
    "JONE Jess Mabel": "jone-jess-mabel",
    "JONES Aaron": "jones-aaron",
    "JONES Adam": "jones-adam",
    "JONES Adriana": "jones-adriana",
    "JONES Aled": "jones-aled",
    "JONES Alex": "jones-alex",
    "JONES Ami": "jones-ami",
    "JONES Andre N": "jones-andre-n",
    "JONES Andrew": "jones-andrew",
    "JONES Andy": "jones-andy",
    "JONES Anna": "jones-anna",
    "JONES Anna G": "jones-anna-g",
    "JONES Anton": "jones-anton",
    "JONES Arlitia M": "jones-arlitia-m",
    "JONES Ash": "jones-ash",
    "JONES B M": "jones-b-m",
    "JONES Barbara M": "jones-barbara-m",
    "JONES Bart": "jones-bart",
    "JONES Bernadette": "jones-bernadette",
    "JONES Bill": "jones-bill",
    "JONES Bill T": "jones-bill-t",
    "JONES Brian": "jones-brian",
    "JONES Bruce G": "jones-bruce-g",
    "JONES Buddug James": "jones-buddug-james",
    "JONES C Robert": "jones-c-robert",
    "JONES Camilla": "jones-camilla",
    "JONES Carol Byrne": "jones-carol-byrne",
    "JONES Carolyn": "jones-carolyn",
    "JONES Casey": "jones-casey",
    "JONES Cat": "jones-cat",
    "JONES Catrin Wyn": "jones-catrin-wyn",
    "JONES Cedric": "jones-cedric",
    "JONES Charles": "jones-charles",
    "JONES Charlotte": "jones-charlotte",
    "JONES Christina": "jones-christina",
    "JONES Christine": "jones-christine",
    "JONES Christopher": "jones-christopher",
    "JONES Claire": "jones-claire",
    "JONES Claire (2)": "jones-claire-2",
    "JONES Cliff": "jones-cliff",
    "JONES Clifton": "jones-clifton",
    "JONES D": "jones-d",
    "JONES D J": "jones-d-j",
    "JONES Dallas": "jones-dallas",
    "JONES Dan": "jones-dan",
    "JONES Daniel Alexander": "jones-daniel-alexander",
    "JONES Darren": "jones-darren",
    "JONES Dave": "jones-dave",
    "JONES Davey": "jones-davey",
    "JONES David": "jones-david",
    "JONES David (1)": "jones-david-1",
    "JONES David Paul": "jones-david-paul",
    "JONES Deb": "jones-deb",
    "JONES Debbie": "jones-debbie",
    "JONES Debbie (1)": "jones-debbie-1",
    "JONES Dedwydd": "jones-dedwydd",
    "JONES Delyth": "jones-delyth",
    "JONES Dennis": "jones-dennis",
    "JONES Desmond": "jones-desmond",
    "JONES Douglas": "jones-douglas",
    "JONES Duane": "jones-duane",
    "JONES Dyfrig": "jones-dyfrig",
    "JONES Edward P": "jones-edward-p",
    "JONES Elinor": "jones-elinor",
    "JONES Elizabeth Adlington": "jones-elizabeth-adlington",
    "JONES Ellis": "jones-ellis",
    "JONES Ellis O": "jones-ellis-o",
    "JONES Elroyce": "jones-elroyce",
    "JONES Elton Townend": "jones-elton-townend",
    "JONES Eric Christopher": "jones-eric-christopher",
    "JONES Eugene": "jones-eugene",
    "JONES Evan": "jones-evan",
    "JONES Ffion": "jones-ffion",
    "JONES Frank (1)": "jones-frank-1",
    "JONES Frank (2)": "jones-frank-2",
    "JONES Gan": "jones-gan",
    "JONES Gareth": "jones-gareth",
    "JONES Gareth (2)": "jones-gareth-2",
    "JONES Gari": "jones-gari",
    "JONES Garr": "jones-garr",
    "JONES Geinor": "jones-geinor",
    "JONES Gene": "jones-gene",
    "JONES Gene-Olivar": "jones-gene-olivar",
    "JONES George": "jones-george",
    "JONES Gerald Everett": "jones-gerald-everett",
    "JONES Glesni Haf": "jones-glesni-haf",
    "JONES Glyn": "jones-glyn",
    "JONES Graham": "jones-graham",
    "JONES Gregory": "jones-gregory",
    "JONES Guy": "jones-guy",
    "JONES Gwen": "jones-gwen",
    "JONES Gwenyth": "jones-gwenyth",
    "JONES Hanna Wyn": "jones-hanna-wyn",
    "JONES Harry": "jones-harry",
    "JONES Heather": "jones-heather",
    "JONES Heather L": "jones-heather-l",
    "JONES Helena": "jones-helena",
    "JONES Henry": "jones-henry",
    "JONES Herman": "jones-herman",
    "JONES Hilary": "jones-hilary",
    "JONES Ignatius": "jones-ignatius",
    "JONES Irene Marchegiani": "jones-irene-marchegiani",
    "JONES J J": "jones-j-j",
    "JONES J R": "jones-j-r",
    "JONES James Arlington": "jones-james-arlington",
    "JONES Jane": "jones-jane",
    "JONES Jara": "jones-jara",
    "JONES Jay Jeff": "jones-jay-jeff",
    "JONES Jeanine": "jones-jeanine",
    "JONES Jeannine": "jones-jeannine",
    "JONES Jeffrey": "jones-jeffrey",
    "JONES Jeffrey M": "jones-jeffrey-m",
    "JONES Jeffrey Swan": "jones-jeffrey-swan",
    "JONES Jennifer": "jones-jennifer",
    "JONES Jennifer S": "jones-jennifer-s",
    "JONES Jerome": "jones-jerome",
    "JONES Jessie": "jones-jessie",
    "JONES Jessie (1)": "jones-jessie-1",
    "JONES Jim": "jones-jim",
    "JONES Joel": "jones-joel",
    "JONES John": "jones-john",
    "JONES John Christopher": "jones-john-christopher",
    "JONES John Henry": "jones-john-henry",
    "JONES John Joseph": "jones-john-joseph",
    "JONES John Kevin": "jones-john-kevin",
    "JONES John Melville": "jones-john-melville",
    "JONES John Peter": "jones-john-peter",
    "JONES Jomama": "jones-jomama",
    "JONES Joseph": "jones-joseph",
    "JONES Joseph R": "jones-joseph-r",
    "JONES Judith": "jones-judith",
    "JONES Julia": "jones-julia",
    "JONES Juliana": "jones-juliana",
    "JONES Karen": "jones-karen",
    "JONES Kelly": "jones-kelly",
    "JONES Ken": "jones-ken",
    "JONES Kenneth": "jones-kenneth",
    "JONES Kevin": "jones-kevin",
    "JONES Kevin (1)": "jones-kevin-1",
    "JONES Kincaid": "jones-kincaid",
    "JONES Leroi": "jones-leroi",
    "JONES Lindal": "jones-lindal",
    "JONES Lisa": "jones-lisa",
    "JONES Liz": "jones-liz",
    "JONES Liz (1)": "jones-liz-1",
    "JONES Lloyd": "jones-lloyd",
    "JONES Llywelyn": "jones-llywelyn",
    "JONES Lola Amis": "jones-lola-amis",
    "JONES Loren (B C)": "jones-loren",
    "JONES Louise": "jones-louise",
    "JONES Lucy": "jones-lucy",
    "JONES Luke": "jones-luke",
    "JONES Lyndal": "jones-lyndal",
    "JONES Lynne": "jones-lynne",
    "JONES M Labier": "jones-m-labier",
    "JONES Mab": "jones-mab",
    "JONES Mali Tudno": "jones-mali-tudno",
    "JONES Marcus": "jones-marcus",
    "JONES Margaret E": "jones-margaret-e",
    "JONES Maria P": "jones-maria-p",
    "JONES Marie": "jones-marie",
    "JONES Marie (1)": "jones-marie-1",
    "JONES Mark": "jones-mark",
    "JONES Martha Harrison": "jones-martha-harrison",
    "JONES Martin": "jones-martin",
    "JONES Matthew": "jones-matthew",
    "JONES Matthew Floyd": "jones-matthew-floyd",
    "JONES Meghan E": "jones-meghan-e",
    "JONES Mei": "jones-mei",
    "JONES Melanie": "jones-melanie",
    "JONES Melissa Mason": "jones-melissa-mason",
    "JONES Merrill D": "jones-merrill-d",
    "JONES Michael": "jones-michael",
    "JONES Naomi": "jones-naomi",
    "JONES Naomi Mcdougall": "jones-naomi-mcdougall",
    "JONES Nia Wyn": "jones-nia-wyn",
    "JONES Nick": "jones-nick",
    "JONES Nick (2)": "jones-nick-2",
    "JONES Nick (3)": "jones-nick-3",
    "JONES Nicki": "jones-nicki",
    "JONES Nicola": "jones-nicola",
    "JONES O A": "jones-o-a",
    "JONES Oliver": "jones-oliver",
    "JONES P": "jones-p",
    "JONES Pat": "jones-pat",
    "JONES Patrick": "jones-patrick",
    "JONES Paul": "jones-paul",
    "JONES Peter": "jones-peter",
    "JONES Philip": "jones-philip",
    "JONES Pip": "jones-pip",
    "JONES Preston": "jones-preston",
    "JONES R B": "jones-r-b",
    "JONES Rae Desmond": "jones-rae-desmond",
    "JONES Raymond": "jones-raymond",
    "JONES Raymond (1)": "jones-raymond-1",
    "JONES Rebecca H": "jones-rebecca-h",
    "JONES Rebecca Manson": "jones-rebecca-manson",
    "JONES Rhodessa": "jones-rhodessa",
    "JONES Rick": "jones-rick",
    "JONES Rob": "jones-rob",
    "JONES Robert": "jones-robert",
    "JONES Robert Preston": "jones-robert-preston",
    "JONES Robert T": "jones-robert-t",
    "JONES Robin": "jones-robin",
    "JONES Rochelle": "jones-rochelle",
    "JONES Rodessa": "jones-rodessa",
    "JONES Roger": "jones-roger",
    "JONES Rolin": "jones-rolin",
    "JONES Ron": "jones-ron",
    "JONES Rupert": "jones-rupert",
    "JONES Sandra": "jones-sandra",
    "JONES Sarah": "jones-sarah",
    "JONES Shane": "jones-shane",
    "JONES Shirley": "jones-shirley",
    "JONES Silas": "jones-silas",
    "JONES Sinjin": "jones-sinjin",
    "JONES Sioned": "jones-sioned",
    "JONES Stella": "jones-stella",
    "JONES Stephanie": "jones-stephanie",
    "JONES Stephen Mack": "jones-stephen-mack",
    "JONES Steve P": "jones-steve-p",
    "JONES Sukari": "jones-sukari",
    "JONES Syl": "jones-syl",
    "JONES T Marshall": "jones-t-marshall",
    "JONES T Y": "jones-t-y",
    "JONES Taylor": "jones-taylor",
    "JONES Thomas": "jones-thomas",
    "JONES Thomas Morgan": "jones-thomas-morgan",
    "JONES Tim Prottery": "jones-tim-prottery",
    "JONES Timothy": "jones-timothy",
    "JONES Timothy (1)": "jones-timothy-1",
    "JONES Tina": "jones-tina",
    "JONES Toby": "jones-toby",
    "JONES Tom": "jones-tom",
    "JONES Tom (1)": "jones-tom-1",
    "JONES Tyrrell": "jones-tyrrell",
    "JONES Valmai": "jones-valmai",
    "JONES Vic": "jones-vic",
    "JONES Vicky": "jones-vicky",
    "JONES Vince": "jones-vince",
    "JONES Walter": "jones-walter",
    "JONES Walton": "jones-walton",
    "JONES Wendell": "jones-wendell",
    "JONES Wendy": "jones-wendy",
    "JONES Wil Sam": "jones-wil-sam",
    "JONES Willa Saunders": "jones-willa-saunders",
    "JONES William A": "jones-william-a",
    "JONES William Ron": "jones-william-ron",
    "JONES (1) Michael": "jones-michael-1",
    "JONES (2) Michael": "jones-michael-2",
    "JONES (3) Michael": "jones-michael-3",
    "JONES (4) Michael": "jones-michael-4",
    "JONES II Thomas W": "jones-ii-thomas-w",
    "JONES, JR Cornelius": "jones-jr-cornelius",
    "JONES-COHEN Riley": "jones-cohen-riley",
    "JONES-EVANS Eric": "jones-evans-eric",
    "JONIC Bettina": "jonic-bettina",
    "JONIGK Thomas": "jonigk-thomas",
    "JONSDOTTIR Eynun Osk": "jonsdottir-eynun-osk",
    "JONSON Ben": "jonson-ben",
    "JONSON Donald": "jonson-donald",
    "JONSON Holly": "jonson-holly",
    "JONSON Kent": "jonson-kent",
    "JONSON Marian": "jonson-marian",
    "JONTE Miranda": "jonte-miranda",
    "JONZI D ": "jonzi-d",
    "JOOSTEN Melanie": "joosten-melanie",
    "JOPLING Heather": "jopling-heather",
    "JORDAN Alana": "jordan-alana",
    "JORDAN Anna": "jordan-anna",
    "JORDAN Brian": "jordan-brian",
    "JORDAN Bruce": "jordan-bruce",
    "JORDAN Chris": "jordan-chris",
    "JORDAN Clarke": "jordan-clarke",
    "JORDAN D": "jordan-d",
    "JORDAN Dennis": "jordan-dennis",
    "JORDAN Elizabeth": "jordan-elizabeth",
    "JORDAN Hugh": "jordan-hugh",
    "JORDAN James": "jordan-james",
    "JORDAN Jeannie": "jordan-jeannie",
    "JORDAN Jennifer": "jordan-jennifer",
    "JORDAN Jennifer Lynn": "jordan-jennifer-lynn",
    "JORDAN Joel": "jordan-joel",
    "JORDAN Julia": "jordan-julia",
    "JORDAN Julie": "jordan-julie",
    "JORDAN June": "jordan-june",
    "JORDAN Kay": "jordan-kay",
    "JORDAN La'Chris": "jordan-la-chris",
    "JORDAN Leslie": "jordan-leslie",
    "JORDAN Louis": "jordan-louis",
    "JORDAN Matt": "jordan-matt",
    "JORDAN Melanie": "jordan-melanie",
    "JORDAN Mikki": "jordan-mikki",
    "JORDAN Neil": "jordan-neil",
    "JORDAN Norman": "jordan-norman",
    "JORDAN Pat": "jordan-pat",
    "JORDAN Peter": "jordan-peter",
    "JORDAN Richard": "jordan-richard",
    "JORDAN Sheba": "jordan-sheba",
    "JORDAN Steve": "jordan-steve",
    "JORDAN Wayne": "jordan-wayne",
    "JORDON Edward": "jordon-edward",
    "JORELLE Lauren": "jorelle-lauren",
    "JORGENSON Tim": "jorgenson-tim",
    "JORY Jon": "jory-jon",
    "JOSE Many": "jose-many",
    "JOSE Simon": "jose-simon",
    "JOSEF Josef Bar": "josef-josef-bar",
    "JOSELOVITZ Ernest": "joselovitz-ernest",
    "JOSEPH Allen": "joseph-allen",
    "JOSEPH Camvshan-Rc": "joseph-camvshan-rc",
    "JOSEPH David": "joseph-david",
    "JOSEPH Elliot": "joseph-elliot",
    "JOSEPH Georgann": "joseph-georgann",
    "JOSEPH Jamal": "joseph-jamal",
    "JOSEPH Jane": "joseph-jane",
    "JOSEPH Jo": "joseph-jo",
    "JOSEPH Joanne": "joseph-joanne",
    "JOSEPH Kymberle": "joseph-kymberle",
    "JOSEPH Marc Bamuthi": "joseph-marc-bamuthi",
    "JOSEPH Martin": "joseph-martin",
    "JOSEPH Melanie": "joseph-melanie",
    "JOSEPH Nadir": "joseph-nadir",
    "JOSEPH Paterson": "joseph-paterson",
    "JOSEPH Paul": "joseph-paul",
    "JOSEPH Rajiv": "joseph-rajiv",
    "JOSEPH Robert": "joseph-robert",
    "JOSEPH Robert Farras": "joseph-robert-farras",
    "JOSEPH Robert L": "joseph-robert-l",
    "JOSEPH Samuel Warren": "joseph-samuel-warren",
    "JOSEPH Victor": "joseph-victor",
    "JOSEPH Victoria T": "joseph-victoria-t",
    "JOSEPH Wendy": "joseph-wendy",
    "JOSEPHINE Charlotte": "josephine-charlotte",
    "JOSEPHINE Leyla": "josephine-leyla",
    "JOSEPHS Alice": "josephs-alice",
    "JOSEPHS Alice (1)": "josephs-alice-1",
    "JOSEPHS Susan": "josephs-susan",
    "JOSEPHSON Ben": "josephson-ben",
    "JOSEPHSON Jonathan": "josephson-jonathan",
    "JOSEPHSON Steve": "josephson-steve",
    "JOSEPHSON Yafit": "josephson-yafit",
    "JOSHI Abhijat": "joshi-abhijat",
    "JOSHUA George E": "joshua-george-e",
    "JOSIFFE Simon": "josiffe-simon",
    "JOSIPOVICI Gabriel": "josipovici-gabriel",
    "JOSKI-JETHI Cassiah": "joski-jethi-cassiah",
    "JOSS David": "joss-david",
    "JOSS W H D": "joss-w-h-d",
    "JOST Nicole": "jost-nicole",
    "JOUANNEAU Joel": "jouanneau-joel",
    "JOUBERT Elsa": "joubert-elsa",
    "JOUCLA Peter": "joucla-peter",
    "JOUDRY Patricia": "joudry-patricia",
    "JOUISSANCE ": "jouissance",
    "JOURDEN Brynna": "jourden-brynna",
    "JOURDHEUIL Jean": "jourdheuil-jean",
    "JOURNET Terrence": "journet-terrence",
    "JOVANOVIC Dusan": "jovanovic-dusan",
    "JOWETT Emma": "jowett-emma",
    "JOWETT James": "jowett-james",
    "JOY Jonathan": "joy-jonathan",
    "JOY Lindsay": "joy-lindsay",
    "JOYCE Anne": "joyce-anne",
    "JOYCE Catherine": "joyce-catherine",
    "JOYCE David Alan": "joyce-david-alan",
    "JOYCE Ella": "joyce-ella",
    "JOYCE Esther-Imogen": "joyce-esther-imogen",
    "JOYCE James": "joyce-james",
    "JOYCE Kevin": "joyce-kevin",
    "JOYCE Kevin P": "joyce-kevin-p",
    "JOYCE Paul": "joyce-paul",
    "JOYCE Rachel B": "joyce-rachel-b",
    "JOYCE Sara": "joyce-sara",
    "JOYCE Stephen": "joyce-stephen",
    "JOYNER Empress": "joyner-empress",
    "JOYNER Gareth": "joyner-gareth",
    "JOYNER Jo": "joyner-jo",
    "JOYNER Paul": "joyner-paul",
    "JOYNER Trevor": "joyner-trevor",
    "JOYNES Alex": "joynes-alex",
    "JOYNSON-WREFORD P": "joynson-wreford-p"
  }
};