export default {
  "metadata": {
    "results": 83,
    "timeStamp": "2025-12-05T21:26:19.327Z",
    "url": "https://www.doollee.com/PlaywrightsJ/J_playwrights_s-z.php"
  },
  "authors": {
    "JUAN Anton": "juan-anton",
    "JUAREZ Tino": "juarez-tino",
    "JUBER Hope": "juber-hope",
    "JUBER Laurence": "juber-laurence",
    "JUCHA Brian": "jucha-brian",
    "JUCHAU Mireille": "juchau-mireille",
    "JUCKES Gillian": "juckes-gillian",
    "JUDD Brian": "judd-brian",
    "JUDD James": "judd-james",
    "JUDD John": "judd-john",
    "JUDD Joy": "judd-joy",
    "JUDD Judy": "judd-judy",
    "JUDD Karlan": "judd-karlan",
    "JUDD Peter M": "judd-peter-m",
    "JUDD Steven": "judd-steven",
    "JUDD Yazmine": "judd-yazmine",
    "JUDDERY Mark": "juddery-mark",
    "JUDE Elayne": "jude-elayne",
    "JUDES Daniel": "judes-daniel",
    "JUDGE Chris": "judge-chris",
    "JUDGE David": "judge-david",
    "JUDGE Erin": "judge-erin",
    "JUDGE Glynis": "judge-glynis",
    "JUDGE Harminder": "judge-harminder",
    "JUDGE Ian": "judge-ian",
    "JUDGE Michael": "judge-michael",
    "JUDITH Adong": "judith-adong",
    "JUDSON Tom": "judson-tom",
    "JUDY DWORIN PERFORMANCE ENSEMBLE ": "judy-dworin-performance-ensemble",
    "JUE Mark": "jue-mark",
    "JUHN Paul": "juhn-paul",
    "JUKES Mary": "jukes-mary",
    "JUKES Peter": "jukes-peter",
    "JUKU Sankai": "juku-sankai",
    "JULI Sara": "juli-sara",
    "JULIA Andrea": "julia-andrea",
    "JULIAN Christopher J": "julian-christopher-j",
    "JULIAN Donald": "julian-donald",
    "JULIAN Donald H": "julian-donald-h",
    "JULIAN Faye": "julian-faye",
    "JULIAN Jay": "julian-jay",
    "JULIAN Joseph": "julian-joseph",
    "JULIAN Josh": "julian-josh",
    "JULIAN Maddy": "julian-maddy",
    "JULIAN Steve": "julian-steve",
    "JULIEN Donald": "julien-donald",
    "JULIEN Edward": "julien-edward",
    "JULIEN Jay": "julien-jay",
    "JUMARA Nick": "jumara-nick",
    "JUMBO Cush": "jumbo-cush",
    "JUN Christina Y": "jun-christina-y",
    "JUNCTION 25 ": "junction-25",
    "JUNCTION AVENUE THEATRE COMPANY ": "junction-avenue-theatre-company",
    "JUNE Roma": "june-roma",
    "JUNG Hansol": "jung-hansol",
    "JUNGE Alexa": "junge-alexa",
    "JUNGES ENSEMBLE STUTTGART ": "junges-ensemble-stuttgart",
    "JUNGLE JIM ENSEMBLE ": "jungle-jim-ensemble",
    "JUNGR Barb": "jungr-barb",
    "JUNGWIRTH Andreas": "jungwirth-andreas",
    "JUNIO James": "junio-james",
    "JUNIPER Emily": "juniper-emily",
    "JUNKER Lily": "junker-lily",
    "JUNTUNEN Jacob": "juntunen-jacob",
    "JUNYENT Sebastian": "junyent-sebastian",
    "JUPE Justine": "jupe-justine",
    "JUPP Kenneth": "jupp-kenneth",
    "JURABOEV Yuldosh": "juraboev-yuldosh",
    "JURD Felicity": "jurd-felicity",
    "JURS-MUNBY Karen": "jurs-munby-karen",
    "JURY Laura": "jury-laura",
    "JURY Rachel": "jury-rachel",
    "JUST Freddy": "just-freddy",
    "JUST Julianne": "just-julianne",
    "JUST Travis": "just-travis",
    "JUST THE LADS ": "just-the-lads",
    "JUSTICE Catherine Johnson": "justice-catherine-johnson",
    "JUSTICE Jimmy": "justice-jimmy",
    "JUSTICE John": "justice-john",
    "JUSTIN Benj": "justin-benj",
    "JUSTINGER Alex": "justinger-alex",
    "JUSUINO Kevin": "jusuino-kevin",
    "JWANOUSKOS Barbara Marie": "jwanouskos-barbara-marie"
  }
};