export default {
  "metadata": {
    "results": 583,
    "timeStamp": "2025-12-05T21:26:37.990Z",
    "url": "https://www.doollee.com/PlaywrightsK/K_playwrights_g-l.php"
  },
  "authors": {
    "KHABOROVA Tanya": "khaborova-tanya",
    "KHAIREH Fatuma": "khaireh-fatuma",
    "KHAJA Anna": "khaja-anna",
    "KHALEZIN Nikolai": "khalezin-nikolai",
    "KHALIDI Ismail": "khalidi-ismail",
    "KHALIL Hannah": "khalil-hannah",
    "KHALIL Rania": "khalil-rania",
    "KHALITOV Elena": "khalitov-elena",
    "KHALLADI Kamal": "khalladi-kamal",
    "KHAMOU Noor": "khamou-noor",
    "KHAN Ahmed": "khan-ahmed",
    "KHAN Aisha": "khan-aisha",
    "KHAN Akram": "khan-akram",
    "KHAN Brian Faizul": "khan-brian-faizul",
    "KHAN Keith": "khan-keith",
    "KHAN Leila": "khan-leila",
    "KHAN N S R": "khan-n-s-r",
    "KHAN Nazish": "khan-nazish",
    "KHAN Pervaiz": "khan-pervaiz",
    "KHAN Ricardo": "khan-ricardo",
    "KHAN Robert": "khan-robert",
    "KHAN Shaheen": "khan-shaheen",
    "KHAN Shahid Iqbal": "khan-shahid-iqbal",
    "KHAN Shan": "khan-shan",
    "KHAN Yasmeen": "khan-yasmeen",
    "KHARKONGOR Nicholas": "kharkongor-nicholas",
    "KHARMS Daniil": "kharms-daniil",
    "KHAZAM Anne": "khazam-anne",
    "KHAZNADAR Francoise Grund": "khaznadar-francoise-grund",
    "KHEMIRI Jonas Hassen": "khemiri-jonas-hassen",
    "KHIMM Suzy": "khimm-suzy",
    "KHLEIF Baheej": "khleif-baheej",
    "KHODAIJI Ninaz": "khodaiji-ninaz",
    "KHODOSH Ilya": "khodosh-ilya",
    "KHODR Arze": "khodr-arze",
    "KHOLOS Jay": "kholos-jay",
    "KHOO Aurorae": "khoo-aurorae",
    "KHOSHKAM Kayvon": "khoshkam-kayvon",
    "KHOTSIANOVSKY Piotr": "khotsianovsky-piotr",
    "KHOURY Elias": "khoury-elias",
    "KHOURY Jamil": "khoury-jamil",
    "KHOURY Sylvia": "khoury-sylvia",
    "KHROMEYCHUK Olesya": "khromeychuk-olesya",
    "KHROUSTALIOV Isambard": "khroustaliov-isambard",
    "KHUNOANE Kgomotso": "khunoane-kgomotso",
    "KHUTAN Ranjit": "khutan-ranjit",
    "KHYTE Arkady": "khyte-arkady",
    "KIAMCO Rich": "kiamco-rich",
    "KIANI Ali": "kiani-ali",
    "KIBBEE Roland": "kibbee-roland",
    "KIBBLE David": "kibble-david",
    "KICKING K ": "kicking-k",
    "KIDD Benjamin": "kidd-benjamin",
    "KIDD Duncan": "kidd-duncan",
    "KIDD Grant F": "kidd-grant-f",
    "KIDD Michael": "kidd-michael",
    "KIDD Nick": "kidd-nick",
    "KIDD Richard": "kidd-richard",
    "KIDD Ronald": "kidd-ronald",
    "KIDD Stephen": "kidd-stephen",
    "KIDD Terrence": "kidd-terrence",
    "KIDD Virginia": "kidd-virginia",
    "KIDDER-MOSTROM Christopher": "kidder-mostrom-christopher",
    "KIDER R": "kider-r",
    "KIDWELL Jennifer": "kidwell-jennifer",
    "KIECHEL Claire": "kiechel-claire",
    "KIEFER Nancy": "kiefer-nancy",
    "KIELTY Gerry": "kielty-gerry",
    "KIELTY James": "kielty-james",
    "KIELTY John": "kielty-john",
    "KIELY Grace": "kiely-grace",
    "KIELY Joe": "kiely-joe",
    "KIELY John": "kiely-john",
    "KIEMAN Robert": "kieman-robert",
    "KIENITZ Tony": "kienitz-tony",
    "KIENNER Robert": "kienner-robert",
    "KIENZEL Olivia": "kienzel-olivia",
    "KIERES Bert": "kieres-bert",
    "KIESCHE Tom": "kiesche-tom",
    "KIFFMEIER Rolf": "kiffmeier-rolf",
    "KIFT Roy": "kift-roy",
    "KIGEL Liora": "kigel-liora",
    "KIGGEL Ryan": "kiggel-ryan",
    "KIGHT Josh James": "kight-josh-james",
    "KIGHTLEY Oscar": "kightley-oscar",
    "KIKOVIN Sergei": "kikovin-sergei",
    "KIKUCHI Paul K": "kikuchi-paul-k",
    "KIKUMURA Akemi": "kikumura-akemi",
    "KILALEA Rory": "kilalea-rory",
    "KILBEY Emma": "kilbey-emma",
    "KILBORNE Sarah": "kilborne-sarah",
    "KILBORNE William S": "kilborne-william-s",
    "KILBY David": "kilby-david",
    "KILBY Ray": "kilby-ray",
    "KILCONQUHAR Robert": "kilconquhar-robert",
    "KILCOYNE Catherine": "kilcoyne-catherine",
    "KILCOYNE Elizabeth Aidan": "kilcoyne-elizabeth-aidan",
    "KILCUP Rick": "kilcup-rick",
    "KILDUFF Stephen": "kilduff-stephen",
    "KILE Michael": "kile-michael",
    "KILEY Grace": "kiley-grace",
    "KILEY Jonathon": "kiley-jonathon",
    "KILGALLEN Dorothy": "kilgallen-dorothy",
    "KILGARRIFF Michael": "kilgarriff-michael",
    "KILGOUR Fran": "kilgour-fran",
    "KILGOUR Kylie": "kilgour-kylie",
    "KILIAN Linda Byrd": "kilian-linda-byrd",
    "KILIANSKI Brenda Jean": "kilianski-brenda-jean",
    "KILKELLY Terry": "kilkelly-terry",
    "KILL THE BEAST ": "kill-the-beast",
    "KILLBORNE JR William S": "killborne-jr-william-s",
    "KILLEBREW Boo": "killebrew-boo",
    "KILLEEN Benjamin": "killeen-benjamin",
    "KILLEN Paula": "killen-paula",
    "KILLENS John Oliver": "killens-john-oliver",
    "KILLIBREW Boo": "killibrew-boo",
    "KILLICK Jerry": "killick-jerry",
    "KILLICK John": "killick-john",
    "KILLICK Paul": "killick-paul",
    "KILLIGREW Tom": "killigrew-tom",
    "KILLIGREW Valerie": "killigrew-valerie",
    "KILLINGER H M": "killinger-h-m",
    "KILLINGER Marion": "killinger-marion",
    "KILLINGWORTH Gerald": "killingworth-gerald",
    "KILLINGWORTH Ray": "killingworth-ray",
    "KILLY Peter": "killy-peter",
    "KILMER Nicholas": "kilmer-nicholas",
    "KILMOVITSKAYA Polina": "kilmovitskaya-polina",
    "KILMURRY Mark": "kilmurry-mark",
    "KILONFE Oba": "kilonfe-oba",
    "KILPATRICK Dave": "kilpatrick-dave",
    "KILPATRICK David": "kilpatrick-david",
    "KILPATRICK Fleur": "kilpatrick-fleur",
    "KILPINEN Inkeri": "kilpinen-inkeri",
    "KILROY Ian": "kilroy-ian",
    "KILROY James H": "kilroy-james-h",
    "KILROY Thomas": "kilroy-thomas",
    "KILTY Jerome": "kilty-jerome",
    "KIM Chungmi": "kim-chungmi",
    "KIM David Johann": "kim-david-johann",
    "KIM Dennis": "kim-dennis",
    "KIM Eddie": "kim-eddie",
    "KIM Euijoon": "kim-euijoon",
    "KIM Eui-Kyung": "kim-eui-kyung",
    "KIM Garrett": "kim-garrett",
    "KIM Gina": "kim-gina",
    "KIM Haerry": "kim-haerry",
    "KIM Hank": "kim-hank",
    "KIM Hyehoung": "kim-hyehoung",
    "KIM Janet S": "kim-janet-s",
    "KIM Jason": "kim-jason",
    "KIM John": "kim-john",
    "KIM Jun": "kim-jun",
    "KIM Jung Han": "kim-jung-han",
    "KIM Lucy J": "kim-lucy-j",
    "KIM Mi Jeong": "kim-mi-jeong",
    "KIM Nancy": "kim-nancy",
    "KIM Natalie": "kim-natalie",
    "KIM Nic Cha": "kim-nic-cha",
    "KIM Pil Rim": "kim-pil-rim",
    "KIM Soomi": "kim-soomi",
    "KIM Susan": "kim-susan",
    "KIM Tessa": "kim-tessa",
    "KIMBALL Callie": "kimball-callie",
    "KIMBALL Carol": "kimball-carol",
    "KIMBALL Edmund": "kimball-edmund",
    "KIMBALL Frederic": "kimball-frederic",
    "KIMBALL Michael": "kimball-michael",
    "KIMBALL Whitney": "kimball-whitney",
    "KIMBALL-DEUTSCH Eileen": "kimball-deutsch-eileen",
    "KIMBELL Jon": "kimbell-jon",
    "KIMBER Jack": "kimber-jack",
    "KIMBER Robert": "kimber-robert",
    "KIMBERLIN V E": "kimberlin-v-e",
    "KIMBERLING Brian": "kimberling-brian",
    "KIMBERLY Michael": "kimberly-michael",
    "KIMBLE G D": "kimble-g-d",
    "KIMBRO Robert": "kimbro-robert",
    "KIMBRO Tod": "kimbro-tod",
    "KIME Haddon": "kime-haddon",
    "KIMMEL Adam": "kimmel-adam",
    "KIMMEL Bruce": "kimmel-bruce",
    "KIMMEL Daniel M": "kimmel-daniel-m",
    "KIMMEL H B": "kimmel-h-b",
    "KIMMEL Hank": "kimmel-hank",
    "KIMMEL Henry": "kimmel-henry",
    "KIMMEL Henry W": "kimmel-henry-w",
    "KIMMEL Joel": "kimmel-joel",
    "KIMMETT Deborah": "kimmett-deborah",
    "KIMMETT Kevin": "kimmett-kevin",
    "KIMMINGS Bryony": "kimmings-bryony",
    "KIMMINS Anthony": "kimmins-anthony",
    "KIMOCHI Sid": "kimochi-sid",
    "KIMPLE David L": "kimple-david-l",
    "KIMPTON Mig": "kimpton-mig",
    "KIMSER Fran": "kimser-fran",
    "KIMURA Sachi": "kimura-sachi",
    "KIN Jeffrey": "kin-jeffrey",
    "KINAHAN Deirdre": "kinahan-deirdre",
    "KINANE Emma": "kinane-emma",
    "KINAST Robert L": "kinast-robert-l",
    "KINCAID John": "kincaid-john",
    "KINCAID William": "kincaid-william",
    "KINCH Daniel": "kinch-daniel",
    "KINCH Don": "kinch-don",
    "KINCH Karen M": "kinch-karen-m",
    "KINCH Martin": "kinch-martin",
    "KIND Chris": "kind-chris",
    "KINDLE Billy": "kindle-billy",
    "KINDLE THEATRE ": "kindle-theatre",
    "KINDLEY Jeffrey": "kindley-jeffrey",
    "KINDRYD Andreea": "kindryd-andreea",
    "KINEHAN Deirdre": "kinehan-deirdre",
    "KINERK Robert": "kinerk-robert",
    "KINETIC ENERGY THEATRE COMPANY,, THE ": "kinetic-energy-theatre-company",
    "KINEVANE Pat": "kinevane-pat",
    "KING Alessandro": "king-alessandro",
    "KING Alonia": "king-alonia",
    "KING Andrea": "king-andrea",
    "KING Anthony": "king-anthony",
    "KING Ashley": "king-ashley",
    "KING Barbara P": "king-barbara-p",
    "KING Bruce": "king-bruce",
    "KING Cass": "king-cass",
    "KING Cheryl": "king-cheryl",
    "KING Chris Savage": "king-chris-savage",
    "KING Christopher": "king-christopher",
    "KING Clive": "king-clive",
    "KING Darryn": "king-darryn",
    "KING David": "king-david",
    "KING David T": "king-david-t",
    "KING Dawn": "king-dawn",
    "KING Denis": "king-denis",
    "KING Di": "king-di",
    "KING Dion": "king-dion",
    "KING Dominic": "king-dominic",
    "KING Fred": "king-fred",
    "KING H": "king-h",
    "KING Hilary": "king-hilary",
    "KING Ian W": "king-ian-w",
    "KING Ivan": "king-ivan",
    "KING James": "king-james",
    "KING James Gordon": "king-james-gordon",
    "KING Jamie": "king-jamie",
    "KING Jeff": "king-jeff",
    "KING Jenny": "king-jenny",
    "KING Joanne": "king-joanne",
    "KING John J": "king-john-j",
    "KING Josh": "king-josh",
    "KING Katherine": "king-katherine",
    "KING Kathy": "king-kathy",
    "KING Kathy Coudle": "king-kathy-coudle",
    "KING Keith": "king-keith",
    "KING Kevin": "king-kevin",
    "KING Larry L": "king-larry-l",
    "KING Laura": "king-laura",
    "KING Leah": "king-leah",
    "KING Libby": "king-libby",
    "KING Monnie O": "king-monnie-o",
    "KING Moynan": "king-moynan",
    "KING Nell": "king-nell",
    "KING Nicholas": "king-nicholas",
    "KING Norman": "king-norman",
    "KING Paul": "king-paul",
    "KING Paul (1)": "king-paul-1",
    "KING Peter": "king-peter",
    "KING Phil": "king-phil",
    "KING Philip": "king-philip",
    "KING Ramona": "king-ramona",
    "KING Ray": "king-ray",
    "KING Robert": "king-robert",
    "KING Robert (1)": "king-robert-1",
    "KING Rolf": "king-rolf",
    "KING Rufus": "king-rufus",
    "KING Russ": "king-russ",
    "KING S D": "king-s-d",
    "KING Shandell": "king-shandell",
    "KING Shirley": "king-shirley",
    "KING Stephen": "king-stephen",
    "KING Steve": "king-steve",
    "KING Tessa": "king-tessa",
    "KING Tim": "king-tim",
    "KING Timothy R": "king-timothy-r",
    "KING Valerie": "king-valerie",
    "KING Vanessa": "king-vanessa",
    "KING TALENT ": "king-talent",
    "KINGDOM Bob": "kingdom-bob",
    "KING-HALL Stephen": "king-hall-stephen",
    "KINGHAM Kelly": "kingham-kelly",
    "KINGHAM Robert": "kingham-robert",
    "KINGHORN Jeffery": "kinghorn-jeffery",
    "KINGKADE Howard": "kingkade-howard",
    "KINGREA Eric": "kingrea-eric",
    "KINGSBURY Marty": "kingsbury-marty",
    "KINGSBURY Michael": "kingsbury-michael",
    "KINGSBURY Stephen": "kingsbury-stephen",
    "KINGSFORD Katherine": "kingsford-katherine",
    "KINGSFORD Mark": "kingsford-mark",
    "KINGSHILL Sophia": "kingshill-sophia",
    "KINGSLAND Ben": "kingsland-ben",
    "KINGSLAND Robin": "kingsland-robin",
    "KINGSLEY Barbara": "kingsley-barbara",
    "KINGSLEY Evangelia Costantakos": "kingsley-evangelia-costantakos",
    "KINGSLEY Gershon": "kingsley-gershon",
    "KINGSLEY Mira": "kingsley-mira",
    "KINGSLEY Sidney": "kingsley-sidney",
    "KINGSLEY-SMITH Terry": "kingsley-smith-terry",
    "KINGSMILL David": "kingsmill-david",
    "KINGSTON Catherine": "kingston-catherine",
    "KINGSTON Jeremy": "kingston-jeremy",
    "KINGSTON Leonard": "kingston-leonard",
    "KINGSTON Philip": "kingston-philip",
    "KINGSTON Robert": "kingston-robert",
    "KINGSTON Valerie": "kingston-valerie",
    "KINGSTON-STRAYER Kelley": "kingston-strayer-kelley",
    "KINGTON Miles": "kington-miles",
    "KINLOCH Maggie": "kinloch-maggie",
    "KINNAIRD Glen Curtis": "kinnaird-glen-curtis",
    "KINNEAR James Larry": "kinnear-james-larry",
    "KINNEAR Rory": "kinnear-rory",
    "KINNEBREW Rick": "kinnebrew-rick",
    "KINNEY Marylisa": "kinney-marylisa",
    "KINNEY Sean": "kinney-sean",
    "KINNINGS Max": "kinnings-max",
    "KINNINMONT Tom": "kinninmont-tom",
    "KINNOCH Ronald": "kinnoch-ronald",
    "KINOSHITA Junji": "kinoshita-junji",
    "KINOSHITA Taurie": "kinoshita-taurie",
    "KINOSIAN Joe": "kinosian-joe",
    "KINOY Ernest": "kinoy-ernest",
    "KINSEL Jay Frank": "kinsel-jay-frank",
    "KINSELLA Hugh": "kinsella-hugh",
    "KINSELLA Julie": "kinsella-julie",
    "KINSELLA Kelly": "kinsella-kelly",
    "KINSELLA Patrick": "kinsella-patrick",
    "KINSEY Chris": "kinsey-chris",
    "KINSLEY Drina": "kinsley-drina",
    "KINSMAN Catherine": "kinsman-catherine",
    "KINSTLE Jimi": "kinstle-jimi",
    "KINTER Rod": "kinter-rod",
    "KINZER Sonja": "kinzer-sonja",
    "KIONGOZI Niah Harding": "kiongozi-niah-harding",
    "KIPINIAK Chris": "kipiniak-chris",
    "KIPNESS Joseph": "kipness-joseph",
    "KIPNIS Lois": "kipnis-lois",
    "KIPP Alex": "kipp-alex",
    "KIPP Ryan": "kipp-ryan",
    "KIPPHARDT Heinar": "kipphardt-heinar",
    "KIRALY Anna": "kiraly-anna",
    "KIRALY Sherwood": "kiraly-sherwood",
    "KIRA-MANNETTE Alice": "kira-mannette-alice",
    "KIRAZIAN Lisa": "kirazian-lisa",
    "KIRBY Andy": "kirby-andy",
    "KIRBY D": "kirby-d",
    "KIRBY Dave": "kirby-dave",
    "KIRBY Deborah": "kirby-deborah",
    "KIRBY J D": "kirby-j-d",
    "KIRBY Jane": "kirby-jane",
    "KIRBY Margaret": "kirby-margaret",
    "KIRBY Michael": "kirby-michael",
    "KIRBY Paul": "kirby-paul",
    "KIRBY Ray": "kirby-ray",
    "KIRBY Robert": "kirby-robert",
    "KIRBY Roger": "kirby-roger",
    "KIRBY Roger (1)": "kirby-roger-1",
    "KIRCHNER A": "kirchner-a",
    "KIRCHNER Brian": "kirchner-brian",
    "KIRCHOFF Nan": "kirchoff-nan",
    "KIRCHWEY Karl": "kirchwey-karl",
    "KIRJOLA Jouni": "kirjola-jouni",
    "KIRK Alexander": "kirk-alexander",
    "KIRK Amy A": "kirk-amy-a",
    "KIRK Andrew": "kirk-andrew",
    "KIRK Dan": "kirk-dan",
    "KIRK David": "kirk-david",
    "KIRK Devin": "kirk-devin",
    "KIRK Gene David": "kirk-gene-david",
    "KIRK Geoffrey S": "kirk-geoffrey-s",
    "KIRK Gill": "kirk-gill",
    "KIRK John": "kirk-john",
    "KIRK John W": "kirk-john-w",
    "KIRK Keith Byron": "kirk-keith-byron",
    "KIRK Lynn": "kirk-lynn",
    "KIRK Michael": "kirk-michael",
    "KIRK Peader": "kirk-peader",
    "KIRK Samuel": "kirk-samuel",
    "KIRKBRIDE Marietta": "kirkbride-marietta",
    "KIRKBRIDE Stash": "kirkbride-stash",
    "KIRKBY Mark": "kirkby-mark",
    "KIRKEBY Jennifer": "kirkeby-jennifer",
    "KIRKEBY Kim": "kirkeby-kim",
    "KIRKEGAARD Jacon": "kirkegaard-jacon",
    "KIRKHAM Gary": "kirkham-gary",
    "KIRKLAND Jack": "kirkland-jack",
    "KIRKLAND-LAFFEY Jenny": "kirkland-laffey-jenny",
    "KIRKLEY Donald": "kirkley-donald",
    "KIRKPATRICK Jena": "kirkpatrick-jena",
    "KIRKPATRICK John": "kirkpatrick-john",
    "KIRKPATRICK Karey": "kirkpatrick-karey",
    "KIRKPATRICK Sean": "kirkpatrick-sean",
    "KIRKPATRICK Tim": "kirkpatrick-tim",
    "KIRKPATRICK Wayne": "kirkpatrick-wayne",
    "KIRKUP James": "kirkup-james",
    "KIRKWOOD Deedee": "kirkwood-deedee",
    "KIRKWOOD James": "kirkwood-james",
    "KIRKWOOD Lucy": "kirkwood-lucy",
    "KIRKWOOD Richard": "kirkwood-richard",
    "KIRLE Bruce": "kirle-bruce",
    "KIRMSER Fran": "kirmser-fran",
    "KIRSCH Matthew": "kirsch-matthew",
    "KIRSCHENBAUM Scott": "kirschenbaum-scott",
    "KIRSCHNER Ruth": "kirschner-ruth",
    "KIRSCHNER Seth": "kirschner-seth",
    "KIRSHENBAUM David": "kirshenbaum-david",
    "KIRSHON Vladimir": "kirshon-vladimir",
    "KIRST Brian": "kirst-brian",
    "KIRTLEY Jojo": "kirtley-jojo",
    "KIRTON Matt": "kirton-matt",
    "KIRWAN Emmet": "kirwan-emmet",
    "KIRWAN Larry": "kirwan-larry",
    "KIRWAN Maggie": "kirwan-maggie",
    "KIRWAN Valerie": "kirwan-valerie",
    "KIRWIN Frederick": "kirwin-frederick",
    "KIRWIN Michael": "kirwin-michael",
    "KISCH Ruth": "kisch-ruth",
    "KISCHUCK Bill": "kischuck-bill",
    "KISE Roger": "kise-roger",
    "KISH Cuauhtemoc Q": "kish-cuauhtemoc-q",
    "KISH Richard": "kish-richard",
    "KISHON Ephraim": "kishon-ephraim",
    "KISLINGER Harald": "kislinger-harald",
    "KISOR David": "kisor-david",
    "KISS Miriam": "kiss-miriam",
    "KISSAS Annaki": "kissas-annaki",
    "KISSEL Benjamin": "kissel-benjamin",
    "KISSIN Carl": "kissin-carl",
    "KISSMAN Lee": "kissman-lee",
    "KIST Tamara": "kist-tamara",
    "KITAS Frida": "kitas-frida",
    "KITASAKI Kurt": "kitasaki-kurt",
    "KITCHELL Iva": "kitchell-iva",
    "KITCHEN Bethan": "kitchen-bethan",
    "KITCHEN Lee": "kitchen-lee",
    "KITCHENER J": "kitchener-j",
    "KITCHENER Shaun": "kitchener-shaun",
    "KITCHENS Emily": "kitchens-emily",
    "KITCHER Bill": "kitcher-bill",
    "KITCHIN Therese": "kitchin-therese",
    "KITCHING Gary": "kitching-gary",
    "KITCHING Hugo": "kitching-hugo",
    "KITCHING Kym": "kitching-kym",
    "KITE Carol": "kite-carol",
    "KITOWSKI Chris": "kitowski-chris",
    "KITROSSER Dan": "kitrosser-dan",
    "KITSAKOS Stephen": "kitsakos-stephen",
    "KITSON Alan": "kitson-alan",
    "KITSON Daniel": "kitson-daniel",
    "KITSOPOULOU Lena": "kitsopoulou-lena",
    "KITT Tom": "kitt-tom",
    "KITTEL Muriel": "kittel-muriel",
    "KITTEN HAS CLAWS ": "kitten-has-claws",
    "KITTI Tommi": "kitti-tommi",
    "KITTLESON Ole": "kittleson-ole",
    "KITTO H D F": "kitto-h-d-f",
    "KITTS Thomas M": "kitts-thomas-m",
    "KITTSON Jean": "kittson-jean",
    "KITTY Alan": "kitty-alan",
    "KITTY Marisa Smith": "kitty-marisa-smith",
    "KITZHABER Amy": "kitzhaber-amy",
    "KITZINGER Rachel": "kitzinger-rachel",
    "KIVINEN Maria": "kivinen-maria",
    "KIYOTSUGU Kwanami": "kiyotsugu-kwanami",
    "KJELBYE Mats": "kjelbye-mats",
    "KLABUND ": "klabund",
    "KLAFF Jack": "klaff-jack",
    "KLAITZ Jay": "klaitz-jay",
    "KLAMBATSEA Marika": "klambatsea-marika",
    "KLAN Matt": "klan-matt",
    "KLANE Robert": "klane-robert",
    "KLAPPERICH Phillip C": "klapperich-phillip-c",
    "KLAPPERT Walt": "klappert-walt",
    "KLAR Ernesto": "klar-ernesto",
    "KLAS George": "klas-george",
    "KLASFELD Adam": "klasfeld-adam",
    "KLASS Brian": "klass-brian",
    "KLASS Judy": "klass-judy",
    "KLASSEN Kevin": "klassen-kevin",
    "KLATA Jan": "klata-jan",
    "KLAUS Anoushka": "klaus-anoushka",
    "KLAUSNER Julie": "klausner-julie",
    "KLAUSNITZER Rudi": "klausnitzer-rudi",
    "KLAUSS Patricia": "klauss-patricia",
    "KLAVAN Laurence": "klavan-laurence",
    "KLAVAN Scott": "klavan-scott",
    "KLAVDIEV Yury": "klavdiev-yury",
    "KLAWITTER Ken": "klawitter-ken",
    "KLAYMAN Deborah": "klayman-deborah",
    "KLAYMAN Jeff": "klayman-jeff",
    "KLEB Tom": "kleb-tom",
    "KLEBAN Edward": "kleban-edward",
    "KLEEFIELD Jackie": "kleefield-jackie",
    "KLEEMAN Susanna": "kleeman-susanna",
    "KLEES Paul": "klees-paul",
    "KLEH Tom": "kleh-tom",
    "KLEIDER Todd": "kleider-todd",
    "KLEIMAN Sheilah": "kleiman-sheilah",
    "KLEIN Andrew Howard": "klein-andrew-howard",
    "KLEIN Arthur": "klein-arthur",
    "KLEIN Debby": "klein-debby",
    "KLEIN Erica Levy": "klein-erica-levy",
    "KLEIN Florian": "klein-florian",
    "KLEIN Isaac": "klein-isaac",
    "KLEIN J D": "klein-j-d",
    "KLEIN Jared": "klein-jared",
    "KLEIN Jean": "klein-jean",
    "KLEIN Jen": "klein-jen",
    "KLEIN Jess": "klein-jess",
    "KLEIN Johnny": "klein-johnny",
    "KLEIN Jon": "klein-jon",
    "KLEIN Maxine": "klein-maxine",
    "KLEIN Melanie": "klein-melanie",
    "KLEIN Michael": "klein-michael",
    "KLEIN Neil Kevin": "klein-neil-kevin",
    "KLEIN Randolph I": "klein-randolph-i",
    "KLEIN Sophie": "klein-sophie",
    "KLEIN Stacy": "klein-stacy",
    "KLEIN Stan": "klein-stan",
    "KLEIN Tanya": "klein-tanya",
    "KLEIN Viviane Sophie": "klein-viviane-sophie",
    "KLEINBAUM Laura Kristen": "kleinbaum-laura-kristen",
    "KLEINBERG David": "kleinberg-david",
    "KLEINBORT Barry": "kleinbort-barry",
    "KLEINE Andrea": "kleine-andrea",
    "KLEINER Peter": "kleiner-peter",
    "KLEINMAN Margit": "kleinman-margit",
    "KLEINMANN Kurt": "kleinmann-kurt",
    "KLEM Rachel": "klem-rachel",
    "KLEMEYER John": "klemeyer-john",
    "KLEMPNER Avid": "klempner-avid",
    "KLEPICA Vedrana": "klepica-vedrana",
    "KLEPPER Steve": "klepper-steve",
    "KLESTILOVA Iva": "klestilova-iva",
    "KLEYNER Mark": "kleyner-mark",
    "KLIER Ron": "klier-ron",
    "KLIEWER Warren": "kliewer-warren",
    "KLIMA Ivan": "klima-ivan",
    "KLIMA Jeff": "klima-jeff",
    "KLIMEK Ellicia": "klimek-ellicia",
    "KLIMOVITSKAYA Polina": "klimovitskaya-polina",
    "KLIMOVSKY Keren": "klimovsky-keren",
    "KLINDER Stephen": "klinder-stephen",
    "KLINE Elmer L": "kline-elmer-l",
    "KLINE Joseph": "kline-joseph",
    "KLINE Julie": "kline-julie",
    "KLINE Linda": "kline-linda",
    "KLINE Norman": "kline-norman",
    "KLINE Shannon": "kline-shannon",
    "KLINE Victor": "kline-victor",
    "KLINE Zac": "kline-zac",
    "KLING Kevin": "kling-kevin",
    "KLING Sharon": "kling-sharon",
    "KLING Woody": "kling-woody",
    "KLINGENSTEIN Tom": "klingenstein-tom",
    "KLINGER Friedrich Maximilian": "klinger-friedrich-maximilian",
    "KLINGER Jule": "klinger-jule",
    "KLINKENBERG Rob": "klinkenberg-rob",
    "KLINSKY Michele Ann": "klinsky-michele-ann",
    "KLITGAARD Kamron": "klitgaard-kamron",
    "KLOCKE Thomas": "klocke-thomas",
    "KLOCKE Todd": "klocke-todd",
    "KLOKO Christopher": "kloko-christopher",
    "KLONSKY Kenneth": "klonsky-kenneth",
    "KLORES Dan": "klores-dan",
    "KLOSE Justin": "klose-justin",
    "KLOST Casey": "klost-casey",
    "KLUFT Matthew": "kluft-matthew",
    "KLUGER Bruce": "kluger-bruce",
    "KLUGER Garry Michael": "kluger-garry-michael",
    "KLUGER Helen": "kluger-helen",
    "KLUGER Steve": "kluger-steve",
    "KLUGHERZ Alice": "klugherz-alice",
    "KLUNZINGER Thomas E": "klunzinger-thomas-e",
    "KLUNZINGER Tom": "klunzinger-tom"
  }
};