export default {
  "metadata": {
    "results": 531,
    "timeStamp": "2025-12-05T21:26:41.642Z",
    "url": "https://www.doollee.com/PlaywrightsK/K_playwrights_m-r.php"
  },
  "authors": {
    "KNABLE Jim": "knable-jim",
    "KNAG Paul": "knag-paul",
    "KNAPIK Suzanne": "knapik-suzanne",
    "KNAPMAN Timothy": "knapman-timothy",
    "KNAPP Bettina L": "knapp-bettina-l",
    "KNAPP Betty": "knapp-betty",
    "KNAPP David": "knapp-david",
    "KNAPP K": "knapp-k",
    "KNAPP Sarah": "knapp-sarah",
    "KNAPP Wolf": "knapp-wolf",
    "KNAPP Zelda": "knapp-zelda",
    "KNAPPE Gerd": "knappe-gerd",
    "KNAPPETT Bruce": "knappett-bruce",
    "KNAUSS John": "knauss-john",
    "KNAZEN Primrose Madayag": "knazen-primrose-madayag",
    "KNEALE Nigel": "kneale-nigel",
    "KNEE Allan": "knee-allan",
    "KNEEHIGH THEATRE COMPANY ": "kneehigh-theatre-company",
    "KNEUBUHL Victoria Nalani": "kneubuhl-victoria-nalani",
    "KNEVITT Charles": "knevitt-charles",
    "KNEWSTUBB Brad": "knewstubb-brad",
    "KNEZEVIC Duca": "knezevic-duca",
    "KNEZEVIC Sime": "knezevic-sime",
    "KNIBBS Julia": "knibbs-julia",
    "KNIGHT A": "knight-a",
    "KNIGHT A J": "knight-a-j",
    "KNIGHT Adam": "knight-adam",
    "KNIGHT Alanna": "knight-alanna",
    "KNIGHT Alison": "knight-alison",
    "KNIGHT Andrew": "knight-andrew",
    "KNIGHT Anne": "knight-anne",
    "KNIGHT Arthur Winfield": "knight-arthur-winfield",
    "KNIGHT Ben": "knight-ben",
    "KNIGHT Cheryl": "knight-cheryl",
    "KNIGHT Christa": "knight-christa",
    "KNIGHT Ingle": "knight-ingle",
    "KNIGHT James A": "knight-james-a",
    "KNIGHT Jerry": "knight-jerry",
    "KNIGHT Johnny": "knight-johnny",
    "KNIGHT Jonah": "knight-jonah",
    "KNIGHT Krista": "knight-krista",
    "KNIGHT Mandy": "knight-mandy",
    "KNIGHT Max": "knight-max",
    "KNIGHT Meredith": "knight-meredith",
    "KNIGHT Michael": "knight-michael",
    "KNIGHT Percival": "knight-percival",
    "KNIGHT R C": "knight-r-c",
    "KNIGHT Rick": "knight-rick",
    "KNIGHT Samsun": "knight-samsun",
    "KNIGHT Stephen": "knight-stephen",
    "KNIGHT Steven": "knight-steven",
    "KNIGHT Steven (1)": "knight-steven-1",
    "KNIGHT Waymon": "knight-waymon",
    "KNIGHT JR Larry": "knight-jr-larry",
    "KNIGHTLEY Mark": "knightley-mark",
    "KNIGHTON Nan": "knighton-nan",
    "KNIGHTS Matthew": "knights-matthew",
    "KNIGHTS OF THE INVISIBLE ": "knights-of-the-invisible",
    "KNIPE JR Richard Edwin": "knipe-jr-richard-edwin",
    "KNITTEL John": "knittel-john",
    "KNIVETON Nancy": "kniveton-nancy",
    "KNOBLOCK Edward": "knoblock-edward",
    "KNOLL Jacob": "knoll-jacob",
    "KNOPF Robert": "knopf-robert",
    "KNOPP Peter F": "knopp-peter-f",
    "KNOTT Alexander": "knott-alexander",
    "KNOTT Frederick": "knott-frederick",
    "KNOTTS Jenny": "knotts-jenny",
    "KNOTTS Karen": "knotts-karen",
    "KNOWLES Ashley": "knowles-ashley",
    "KNOWLES Fiona": "knowles-fiona",
    "KNOWLES John": "knowles-john",
    "KNOWLES Katherine": "knowles-katherine",
    "KNOWLES Keith": "knowles-keith",
    "KNOWLES Kieran": "knowles-kieran",
    "KNOWLES Louise E": "knowles-louise-e",
    "KNOWLES Marjorie": "knowles-marjorie",
    "KNOWLES Mark W": "knowles-mark-w",
    "KNOWLES Peter": "knowles-peter",
    "KNOWLES Rebecca": "knowles-rebecca",
    "KNOWLES Rex": "knowles-rex",
    "KNOWLES Ric": "knowles-ric",
    "KNOWLES Roy": "knowles-roy",
    "KNOWLES Ryan": "knowles-ryan",
    "KNOWLES William Anthony": "knowles-william-anthony",
    "KNOWN Jim": "known-jim",
    "KNOWSLEY John": "knowsley-john",
    "KNOX Alex": "knox-alex",
    "KNOX Alexander": "knox-alexander",
    "KNOX Ben": "knox-ben",
    "KNOX Charles": "knox-charles",
    "KNOX Charlie": "knox-charlie",
    "KNOX David": "knox-david",
    "KNOX Gillian": "knox-gillian",
    "KNOX Lorraine": "knox-lorraine",
    "KNOX Paul": "knox-paul",
    "KNUCKLE Robert": "knuckle-robert",
    "KNUCKLES ": "knuckles",
    "KNUDSON K": "knudson-k",
    "KNYAZEV Yuri": "knyazev-yuri",
    "KNYGHT-SMITH Douglas": "knyght-smith-douglas",
    "KO Leon": "ko-leon",
    "KOALE Beulah": "koale-beulah",
    "KOBAYASHI Yuriko": "kobayashi-yuriko",
    "KOBELI Marcus": "kobeli-marcus",
    "KOBER Arthur": "kober-arthur",
    "KOBLER Flip": "kobler-flip",
    "KOCA Bogdan": "koca-bogdan",
    "KOCEVAR Rudolf": "kocevar-rudolf",
    "KOCH Bill": "koch-bill",
    "KOCH Howard": "koch-howard",
    "KOCH Joanne": "koch-joanne",
    "KOCH Kenneth": "koch-kenneth",
    "KOCH Lisa": "koch-lisa",
    "KOCH Primrose Madayag": "koch-primrose-madayag",
    "KOCH JR William Henry": "koch-jr-william-henry",
    "KOCHANOWSKI Jan": "kochanowski-jan",
    "KOCHANSKI Kerri": "kochanski-kerri",
    "KOCHBERG Searle": "kochberg-searle",
    "KOCHENDERFER Tim": "kochenderfer-tim",
    "KOCHENSPARGER Anthony Donald": "kochensparger-anthony-donald",
    "KOCHMER Eric Michael": "kochmer-eric-michael",
    "KOCIELA Ed": "kociela-ed",
    "KOCIOLEK Ted": "kociolek-ted",
    "KOCKOVIC Marijan": "kockovic-marijan",
    "KOCZEN Kerri": "koczen-kerri",
    "KODIAK Paul": "kodiak-paul",
    "KOEBERNICK Brandon": "koebernick-brandon",
    "KOEBNICK S M": "koebnick-s-m",
    "KOEDFOED Bjorn": "koedfoed-bjorn",
    "KOEFLER Werner R": "koefler-werner-r",
    "KOEHLER Robert": "koehler-robert",
    "KOEHLER Ted": "koehler-ted",
    "KOEL Leonard": "koel-leonard",
    "KOEMER Kati": "koemer-kati",
    "KOENIG Emma": "koenig-emma",
    "KOENIG Kipp C": "koenig-kipp-c",
    "KOENIG Laird": "koenig-laird",
    "KOENIG Lea": "koenig-lea",
    "KOENIG Ralf": "koenig-ralf",
    "KOENIG Ronnie": "koenig-ronnie",
    "KOENIG Tim": "koenig-tim",
    "KOENIGER George": "koeniger-george",
    "KOENIGSBERG Josh": "koenigsberg-josh",
    "KOENIGSBERG Neil": "koenigsberg-neil",
    "KOEPFINGER Coni": "koepfinger-coni",
    "KOEPKE Jay": "koepke-jay",
    "KOERNER Laconia": "koerner-laconia",
    "KOERNER Michael": "koerner-michael",
    "KOESIS Robert": "koesis-robert",
    "KOESTLER Vicki Riba": "koestler-vicki-riba",
    "KOFMAN Gil": "kofman-gil",
    "KOFOD Lisa A": "kofod-lisa-a",
    "KOGER Derek": "koger-derek",
    "KOHAN Alan": "kohan-alan",
    "KOHAN Buz": "kohan-buz",
    "KOHL Gloria": "kohl-gloria",
    "KOHL Hannah": "kohl-hannah",
    "KOHLER Anna": "kohler-anna",
    "KOHLER Estelle": "kohler-estelle",
    "KOHLER Marie": "kohler-marie",
    "KOHLI Hardeep Singh": "kohli-hardeep-singh",
    "KOHM Angus": "kohm-angus",
    "KOHN Chris": "kohn-chris",
    "KOHN Lisa": "kohn-lisa",
    "KOHN Marissa": "kohn-marissa",
    "KOHN Rita": "kohn-rita",
    "KOHNER Lloyd": "kohner-lloyd",
    "KOHNER Poppy": "kohner-poppy",
    "KOHOUT Pavel": "kohout-pavel",
    "KOIS Dan": "kois-dan",
    "KOIVISTO Ellen": "koivisto-ellen",
    "KOKAMI Shoji": "kokami-shoji",
    "KOKKELKOREN Erwin": "kokkelkoren-erwin",
    "KOKOSCHKA Oskar": "kokoschka-oskar",
    "KOKOVKIN Sergei": "kokovkin-sergei",
    "KOKX Anthony": "kokx-anthony",
    "KOLARU Max": "kolaru-max",
    "KOLB Miriam Raiken": "kolb-miriam-raiken",
    "KOLECKO Petr": "kolecko-petr",
    "KOLIADA Natalia": "koliada-natalia",
    "KOLIADA Yuriy": "koliada-yuriy",
    "KOLK Jaan": "kolk-jaan",
    "KOLLAR Lorraine": "kollar-lorraine",
    "KOLLE Ray": "kolle-ray",
    "KOLLER Katherine": "koller-katherine",
    "KOLLMER Jennifer": "kollmer-jennifer",
    "KOLO Fred": "kolo-fred",
    "KOLOMATSKY Tina Esper": "kolomatsky-tina-esper",
    "KOLPAK Diana": "kolpak-diana",
    "KOLSON Rob": "kolson-rob",
    "KOLTES Bernard-Marie": "koltes-bernard-marie",
    "KOLUBAYEV Cat": "kolubayev-cat",
    "KOLVENBACH John": "kolvenbach-john",
    "KOLVIN Philip": "kolvin-philip",
    "KOLYADA Natalia": "kolyada-natalia",
    "KOLYADA Nikolai": "kolyada-nikolai",
    "KOMAKI Judi": "komaki-judi",
    "KOMAR Ingrid": "komar-ingrid",
    "KOMLOSY Mary": "komlosy-mary",
    "KOMONDOR Krista": "komondor-krista",
    "KOMUNYAKAA Yusef": "komunyakaa-yusef",
    "KON Stella": "kon-stella",
    "KONDEK Charles": "kondek-charles",
    "KONDEK Chris": "kondek-chris",
    "KONDO Dorinne": "kondo-dorinne",
    "KONDOL Jenny": "kondol-jenny",
    "KONDOLEON Harry": "kondoleon-harry",
    "KONE Tom": "kone-tom",
    "KONERTH Matthew Robert": "konerth-matthew-robert",
    "KONG Chil": "kong-chil",
    "KONIC THEATRE ": "konic-theatre",
    "KONICEK Janes": "konicek-janes",
    "KONIG Dave": "konig-dave",
    "KONIGGRATZ Samuel": "koniggratz-samuel",
    "KONIK Mark": "konik-mark",
    "KONTOYIANNIS Tiffany": "kontoyiannis-tiffany",
    "KONTROL Pass": "kontrol-pass",
    "KOO Alexander": "koo-alexander",
    "KOOGLER Abe": "koogler-abe",
    "KOOHESTANI Amir Reza": "koohestani-amir-reza",
    "KOOMAN Michael A": "kooman-michael-a",
    "KOON Robert": "koon-robert",
    "KOONTZ Amelia Elizabeth": "koontz-amelia-elizabeth",
    "KOOPERMAN Paul": "kooperman-paul",
    "KOOSER Brian": "kooser-brian",
    "KOPIT Arthur": "kopit-arthur",
    "KOPLAN Adam": "koplan-adam",
    "KOPP Annie": "kopp-annie",
    "KOPPEN Jean": "koppen-jean",
    "KOPPETT Katherine": "koppett-katherine",
    "KOPPLIN Justin": "kopplin-justin",
    "KOPPMAN Steve": "koppman-steve",
    "KOPS Bernard": "kops-bernard",
    "KORAHAIS Matt": "korahais-matt",
    "KORBAR Steven": "korbar-steven",
    "KORBESMEYER Brad": "korbesmeyer-brad",
    "KORBLUTH Josh": "korbluth-josh",
    "KORCZYNSKI J Karol": "korczynski-j-karol",
    "KORDER Howard": "korder-howard",
    "KORDY Elaine": "kordy-elaine",
    "KOREL Edward": "korel-edward",
    "KORELL Ryan": "korell-ryan",
    "KOREN David": "koren-david",
    "KOREN Greg": "koren-greg",
    "KOREN Gur": "koren-gur",
    "KOREN Justin": "koren-justin",
    "KOREY Stanton": "korey-stanton",
    "KORFHAGE Andrew": "korfhage-andrew",
    "KORIE Michael": "korie-michael",
    "KORMAKUR Baltaskar": "kormakur-baltaskar",
    "KORMAN Jess J": "korman-jess-j",
    "KORN Brielle": "korn-brielle",
    "KORN David M": "korn-david-m",
    "KORN Eric": "korn-eric",
    "KORN John": "korn-john",
    "KORN Nicholas": "korn-nicholas",
    "KORNBLUTH Josh": "kornbluth-josh",
    "KORNFELD David": "kornfeld-david",
    "KORNFELD Eric": "kornfeld-eric",
    "KORNFELD Robert": "kornfeld-robert",
    "KORNFIELD Eric": "kornfield-eric",
    "KORNHABER David": "kornhaber-david",
    "KORNHAUSER Barry": "kornhauser-barry",
    "KORNHISER Bob": "kornhiser-bob",
    "KORNHISER Robert": "kornhiser-robert",
    "KORNICKI Dunstan": "kornicki-dunstan",
    "KORNS Helen T": "korns-helen-t",
    "KORNSTEIN Stephen": "kornstein-stephen",
    "KOROBACZ Clair": "korobacz-clair",
    "KORON Barry": "koron-barry",
    "KOROTKIN Judy": "korotkin-judy",
    "KORP Bethany M": "korp-bethany-m",
    "KORRIE Michael": "korrie-michael",
    "KORSTEN Irene": "korsten-irene",
    "KORTY Carol": "korty-carol",
    "KORZEN Annie": "korzen-annie",
    "KOSAR Sarah": "kosar-sarah",
    "KOSH David": "kosh-david",
    "KOSHIKAWA Daisuke": "koshikawa-daisuke",
    "KOSICKA Jadwiga": "kosicka-jadwiga",
    "KOSKY Barrie": "kosky-barrie",
    "KOSLOFF Gerald": "kosloff-gerald",
    "KOSLOSKY Hannah": "koslosky-hannah",
    "KOSLOW Jules": "koslow-jules",
    "KOSMAS Kristen": "kosmas-kristen",
    "KOSNIK Kiki": "kosnik-kiki",
    "KOSOFF Susan": "kosoff-susan",
    "KOSPIAH Michael": "kospiah-michael",
    "KOSSOFF David": "kossoff-david",
    "KOSTE V Glasgow": "koste-v-glasgow",
    "KOSTELANETZ Richard": "kostelanetz-richard",
    "KOSTER Paul": "koster-paul",
    "KOSTIC Kevin": "kostic-kevin",
    "KOSTICK Gavin": "kostick-gavin",
    "KOSTINA Irina": "kostina-irina",
    "KOSTMAYER Kos": "kostmayer-kos",
    "KOSTRZEWA Natalia": "kostrzewa-natalia",
    "KOSUB David": "kosub-david",
    "KOSZULINSKI George": "koszulinski-george",
    "KOTAK Ash": "kotak-ash",
    "KOTELES David": "koteles-david",
    "KOTIN Lisa": "kotin-lisa",
    "KOTIS Greg": "kotis-greg",
    "KOTOWSKI Mariusz": "kotowski-mariusz",
    "KOTTAKIS Julie": "kottakis-julie",
    "KOTZ Cappy": "kotz-cappy",
    "KOTZWINKLE William": "kotzwinkle-william",
    "KOUISTO Ellen": "kouisto-ellen",
    "KOUKA Hone": "kouka-hone",
    "KOURI Charles": "kouri-charles",
    "KOURILSKY Francoise": "kourilsky-francoise",
    "KOUT Wendy": "kout-wendy",
    "KOUTOUKAS H M": "koutoukas-h-m",
    "KOUTSAKIS Polychronis": "koutsakis-polychronis",
    "KOUTSAKOS Yiannis": "koutsakos-yiannis",
    "KOVACEVIC Dusan": "kovacevic-dusan",
    "KOVACS David": "kovacs-david",
    "KOVACS George": "kovacs-george",
    "KOVACS Tony": "kovacs-tony",
    "KOVACSIK William": "kovacsik-william",
    "KOVAKS David": "kovaks-david",
    "KOVETZ Lisa Beth": "kovetz-lisa-beth",
    "KOVICH Robert": "kovich-robert",
    "KOWACKI Darren": "kowacki-darren",
    "KOWALCHUK Matthew": "kowalchuk-matthew",
    "KOWALCHUK Tannis": "kowalchuk-tannis",
    "KOWSAR Mohammad": "kowsar-mohammad",
    "KOYAMA Joji": "koyama-joji",
    "KOZACK Aaron": "kozack-aaron",
    "KOZAK Aaron": "kozak-aaron",
    "KOZAK Alexis": "kozak-alexis",
    "KOZBIAL Aaron": "kozbial-aaron",
    "KOZEL Vicki": "kozel-vicki",
    "KOZLENKO William": "kozlenko-william",
    "KOZLOWSKI Rob": "kozlowski-rob",
    "KRAAR Adam": "kraar-adam",
    "KRAAY Heidi": "kraay-heidi",
    "KRAEMER Bruce Al": "kraemer-bruce-al",
    "KRAFCHICK David": "krafchick-david",
    "KRAFT Arthur M": "kraft-arthur-m",
    "KRAFT Charlotte": "kraft-charlotte",
    "KRAFT Hy": "kraft-hy",
    "KRAIEM Eliam": "kraiem-eliam",
    "KRAIGHER Alenka": "kraigher-alenka",
    "KRAINZ Frankie": "krainz-frankie",
    "KRAKER Brian": "kraker-brian",
    "KRAKOW Ross": "krakow-ross",
    "KRAKOWER Bob": "krakower-bob",
    "KRAL Brian": "kral-brian",
    "KRALJ Darinka": "kralj-darinka",
    "KRAMEN Holly K": "kramen-holly-k",
    "KRAMER Alan": "kramer-alan",
    "KRAMER Andrew": "kramer-andrew",
    "KRAMER Brad": "kramer-brad",
    "KRAMER Casey": "kramer-casey",
    "KRAMER Daniel": "kramer-daniel",
    "KRAMER Daniel Elihu": "kramer-daniel-elihu",
    "KRAMER David": "kramer-david",
    "KRAMER Frederick": "kramer-frederick",
    "KRAMER Greg": "kramer-greg",
    "KRAMER Julie": "kramer-julie",
    "KRAMER Kathleen": "kramer-kathleen",
    "KRAMER Larry": "kramer-larry",
    "KRAMER Laura I": "kramer-laura-i",
    "KRAMER Leslie": "kramer-leslie",
    "KRAMER May": "kramer-may",
    "KRAMER Michael R": "kramer-michael-r",
    "KRAMER Radha": "kramer-radha",
    "KRAMER Randall": "kramer-randall",
    "KRAMER Richard": "kramer-richard",
    "KRAMER Seth": "kramer-seth",
    "KRAMER Sherry": "kramer-sherry",
    "KRAMER Travis": "kramer-travis",
    "KRAMISEN Jae": "kramisen-jae",
    "KRAMM Joseph": "kramm-joseph",
    "KRAMSKOY Adrian": "kramskoy-adrian",
    "KRANE David": "krane-david",
    "KRANES David": "kranes-david",
    "KRANITZ Lionel": "kranitz-lionel",
    "KRANSKY SISTERS ": "kransky-sisters",
    "KRANTZ Joel": "krantz-joel",
    "KRANTZ Kara Emily": "krantz-kara-emily",
    "KRANTZ Megan": "krantz-megan",
    "KRANTZ Morgan": "krantz-morgan",
    "KRAOUNAKIS Stamatis": "kraounakis-stamatis",
    "KRAPIVINA Marina": "krapivina-marina",
    "KRAS Carolyn": "kras-carolyn",
    "KRASA Hans": "krasa-hans",
    "KRASINSKI Zygmunt": "krasinski-zygmunt",
    "KRASNA Norman": "krasna-norman",
    "KRASNER-KARPEN Justin": "krasner-karpen-justin",
    "KRASNIQI Arian": "krasniqi-arian",
    "KRASNOGOROV Valentin": "krasnogorov-valentin",
    "KRASNOSTEIN Natalie": "krasnostein-natalie",
    "KRASS Carolyn": "krass-carolyn",
    "KRASS Danny": "krass-danny",
    "KRAUS Joanna Halpert": "kraus-joanna-halpert",
    "KRAUS Karl": "kraus-karl",
    "KRAUS Ryan": "kraus-ryan",
    "KRAUSE Carol Wright": "krause-carol-wright",
    "KRAUSE Emily": "krause-emily",
    "KRAUSE Mark": "krause-mark",
    "KRAUSE Stafford": "krause-stafford",
    "KRAUSER Lawrence": "krauser-lawrence",
    "KRAUSNICK Dennis": "krausnick-dennis",
    "KRAUSS Amanda": "krauss-amanda",
    "KRAUSS Leah D": "krauss-leah-d",
    "KRAUSS Ruth": "krauss-ruth",
    "KRAUSS Tracy": "krauss-tracy",
    "KRAUSSER Helmut": "krausser-helmut",
    "KRAUT Laura": "kraut-laura",
    "KRAUTH Nigel": "krauth-nigel",
    "KRAVETZ Jonathan": "kravetz-jonathan",
    "KRAVITZ Alan H": "kravitz-alan-h",
    "KRAWCZYK Joseph P": "krawczyk-joseph-p",
    "KRAWIEC Richard": "krawiec-richard",
    "KRAY Charles": "kray-charles",
    "KREBS Ron": "krebs-ron",
    "KREBS Thor Bjorn": "krebs-thor-bjorn",
    "KREEGER Evan": "kreeger-evan",
    "KREFT Steffen": "kreft-steffen",
    "KREIDL Margret": "kreidl-margret",
    "KREIDLER Todd": "kreidler-todd",
    "KREILING Christopher": "kreiling-christopher",
    "KREIMENDAHL Basil": "kreimendahl-basil",
    "KREISLER Georg": "kreisler-georg",
    "KREISLER Jeff": "kreisler-jeff",
    "KREISS Stephen": "kreiss-stephen",
    "KREITH Ari Laura": "kreith-ari-laura",
    "KREITH Laura": "kreith-laura",
    "KREITMAN Margery": "kreitman-margery",
    "KREITZER Carson": "kreitzer-carson",
    "KREIZ Alit": "kreiz-alit",
    "KREJCI Christopher J": "krejci-christopher-j",
    "KRELL David Farrell": "krell-david-farrell",
    "KRELL Jeff": "krell-jeff",
    "KRELL-OISHI Mary": "krell-oishi-mary",
    "KREMER Dan": "kremer-dan",
    "KREMER Scott": "kremer-scott",
    "KREMMYDA Erato": "kremmyda-erato",
    "KREN Sheree Rainbolt": "kren-sheree-rainbolt",
    "KRENS Carla": "krens-carla",
    "KREPPEL Paul": "kreppel-paul",
    "KRESSAL Kimberlea": "kressal-kimberlea",
    "KRESSEN Nathaniel": "kressen-nathaniel",
    "KRESSMAN Margaret": "kressman-margaret",
    "KRESTAN Jo-Ann": "krestan-jo-ann",
    "KRETCHIK Grant": "kretchik-grant",
    "KRETZMER Herbert": "kretzmer-herbert",
    "KREUTZ Gregg": "kreutz-gregg",
    "KREUTZ Phoebe": "kreutz-phoebe",
    "KREUTZER Leah": "kreutzer-leah",
    "KREUTZIGER Marie": "kreutziger-marie",
    "KREVAT Devyn Elena": "krevat-devyn-elena",
    "KREVOLIN Richard": "krevolin-richard",
    "KREY Andy": "krey-andy",
    "KREYL Jenny": "kreyl-jenny",
    "KREZELL Charles": "krezell-charles",
    "KRIANC John": "krianc-john",
    "KRIBUS Serge": "kribus-serge",
    "KRICHEFSKI Bernard": "krichefski-bernard",
    "KRICHEFSKI Jacob": "krichefski-jacob",
    "KRICHELDORF Rebekka": "kricheldorf-rebekka",
    "KRICORIAN Nancy": "kricorian-nancy",
    "KRIEBEL Seth": "kriebel-seth",
    "KRIEGEL Gail": "kriegel-gail",
    "KRIEGEL Marilyn H": "kriegel-marilyn-h",
    "KRIEGER Barbara Zinn": "krieger-barbara-zinn",
    "KRIEGER Henry": "krieger-henry",
    "KRIEGLER Sarah": "kriegler-sarah",
    "KRIEGMAN Mitchell": "kriegman-mitchell",
    "KRIER Jennifer": "krier-jennifer",
    "KRIMPAS Titania": "krimpas-titania",
    "KRING Katie": "kring-katie",
    "KRINKEL N J": "krinkel-n-j",
    "KRINKLE Nancy": "krinkle-nancy",
    "KRISHNA Maya": "krishna-maya",
    "KRISIUKNAS John": "krisiuknas-john",
    "KRISTIAN John": "kristian-john",
    "KRISTIE Rob": "kristie-rob",
    "KRISTJANSDOTTIR Kristin Ros": "kristjansdottir-kristin-ros",
    "KRISTJANSSON Vikingur": "kristjansson-vikingur",
    "KRISTOF Nicholas D": "kristof-nicholas-d",
    "KRISTOFFERSEN Ranghild": "kristoffersen-ranghild",
    "KRISTOPHER Thomas": "kristopher-thomas",
    "KRIWACZEK Paul": "kriwaczek-paul",
    "KRIZANC John": "krizanc-john",
    "KRIZEL John": "krizel-john",
    "KRODMAN Melissa": "krodman-melissa",
    "KROEGER Perry Arthur": "kroeger-perry-arthur",
    "KROETZ David Xaver": "kroetz-david-xaver",
    "KROETZ FrANZ Xaver": "kroetz-franz-xaver",
    "KROFTA Jakub": "krofta-jakub",
    "KROGERUS Anna": "krogerus-anna",
    "KROHN Tanya": "krohn-tanya",
    "KROLL Jeri": "kroll-jeri",
    "KROMER Helen": "kromer-helen",
    "KROMETIS Damon": "krometis-damon",
    "KROMM William": "kromm-william",
    "KRON Lisa": "kron-lisa",
    "KRON Mary": "kron-mary",
    "KRONENBERGER Jonathan": "kronenberger-jonathan",
    "KRONENBERGER Louis": "kronenberger-louis",
    "KRONENGOLD A J": "kronengold-a-j",
    "KRONIS Tina": "kronis-tina",
    "KRONK Robert": "kronk-robert",
    "KROOK III Russel J": "krook-iii-russel-j",
    "KROPF Richard": "kropf-richard",
    "KROPKOWSKI Martine": "kropkowski-martine",
    "KROTHAPALI Peter": "krothapali-peter",
    "KRUCKEMEYER Finegan": "kruckemeyer-finegan",
    "KRUCKER Fides": "krucker-fides",
    "KRUCZKOWSKI Leon": "kruczkowski-leon",
    "KRUEGER Anton Robert": "krueger-anton-robert",
    "KRUEGER Bruce F": "krueger-bruce-f",
    "KRUEGER Lucas William": "krueger-lucas-william",
    "KRUEGER Luke": "krueger-luke",
    "KRUGER Chaddie": "kruger-chaddie",
    "KRUH David": "kruh-david",
    "KRUKOWSKI W": "krukowski-w",
    "KRUMBEIN Violet": "krumbein-violet",
    "KRUMINS Ralph": "krumins-ralph",
    "KRUMPELMAN John T": "krumpelman-john-t",
    "KRUMPLE THEATRE COMPANY ": "krumple-theatre-company",
    "KRUPER Ken": "kruper-ken",
    "KRUPINSKI Rennie": "krupinski-rennie",
    "KRUSE Kathryn": "kruse-kathryn",
    "KRUSIEC Michelle": "krusiec-michelle",
    "KRYAH Nicholas": "kryah-nicholas",
    "KRYMOV Dmitry": "krymov-dmitry"
  }
};