export default {
  "metadata": {
    "results": 172,
    "timeStamp": "2025-12-05T21:26:42.497Z",
    "url": "https://www.doollee.com/PlaywrightsK/K_playwrights_s-z.php"
  },
  "authors": {
    "KSIKES Driss": "ksikes-driss",
    "KUANG Robert Ye": "kuang-robert-ye",
    "KUBA ": "kuba",
    "KUBIK Karolina": "kubik-karolina",
    "KUBIN Paul": "kubin-paul",
    "KUBLY Herbert": "kubly-herbert",
    "KUBOTA Glenn": "kubota-glenn",
    "KUBOTA Ken": "kubota-ken",
    "KUBOTA Warren Sumio": "kubota-warren-sumio",
    "KUBU Joseph S": "kubu-joseph-s",
    "KUBZANSKY Jessica": "kubzansky-jessica",
    "KUCH Melissa": "kuch-melissa",
    "KUCHAR Kevin": "kuchar-kevin",
    "KUCHER David": "kucher-david",
    "KUCHKINA Olga": "kuchkina-olga",
    "KUCHLEWSKA Andrea": "kuchlewska-andrea",
    "KUCKENBAKER Chris": "kuckenbaker-chris",
    "KUDELKA Jan": "kudelka-jan",
    "KUDIAN M": "kudian-m",
    "KUDISCH Erica": "kudisch-erica",
    "KUEBLER John": "kuebler-john",
    "KUEHNEMANN Eric": "kuehnemann-eric",
    "KUEPPER Ed": "kuepper-ed",
    "KUFRIN Joan": "kufrin-joan",
    "KUGLER D D": "kugler-d-d",
    "KUHARSKI Allen": "kuharski-allen",
    "KUHL Christiana": "kuhl-christiana",
    "KUHL Helmut": "kuhl-helmut",
    "KUHLMAN Richard": "kuhlman-richard",
    "KUHLMAN Walter C": "kuhlman-walter-c",
    "KUHN Donald": "kuhn-donald",
    "KUHN John": "kuhn-john",
    "KUHN Jonathan": "kuhn-jonathan",
    "KUHN Jonson": "kuhn-jonson",
    "KUHN Liam": "kuhn-liam",
    "KUHN Tom": "kuhn-tom",
    "KUHN Tony": "kuhn-tony",
    "KUHNER Herbert": "kuhner-herbert",
    "KUHNS Alice": "kuhns-alice",
    "KUHNS Bill": "kuhns-bill",
    "KUIJPER Menno": "kuijper-menno",
    "KUJOVIC Marco": "kujovic-marco",
    "KUKAHIKO Chad": "kukahiko-chad",
    "KULA Irwin": "kula-irwin",
    "KULA Michael": "kula-michael",
    "KULAKOW Allan M": "kulakow-allan-m",
    "KULICK Brian": "kulick-brian",
    "KULICK Miriam": "kulick-miriam",
    "KULIK Maggie": "kulik-maggie",
    "KULIK Sam": "kulik-sam",
    "KULINSKI Victor": "kulinski-victor",
    "KULL Anna": "kull-anna",
    "KULLER Richard": "kuller-richard",
    "KUMA Lisa": "kuma-lisa",
    "KUMALO Alton": "kumalo-alton",
    "KUMALO Duma": "kumalo-duma",
    "KUMAR Anu": "kumar-anu",
    "KUMAR Pravesh": "kumar-pravesh",
    "KUMBLE Roger": "kumble-roger",
    "KUMIN Marissa": "kumin-marissa",
    "KUMMEL Philip": "kummel-philip",
    "KUMMEL Tamar": "kummel-tamar",
    "KUMMER Clare": "kummer-clare",
    "KUNDA Chanje": "kunda-chanje",
    "KUNDERA Milan": "kundera-milan",
    "KUNDTZ David": "kundtz-david",
    "KUNER Mildred C": "kuner-mildred-c",
    "KUNES Steven": "kunes-steven",
    "KUNICH John Charles": "kunich-john-charles",
    "KUNID Masahiro": "kunid-masahiro",
    "KUNIK John": "kunik-john",
    "KUNIN Alaina": "kunin-alaina",
    "KUNJAPPY Annie": "kunjappy-annie",
    "KUNKEL Benjamin": "kunkel-benjamin",
    "KUNKEL Caitlin Regina": "kunkel-caitlin-regina",
    "KUNKEN Stephen": "kunken-stephen",
    "KUNO Gil": "kuno-gil",
    "KUNOFSKY Larry": "kunofsky-larry",
    "KUNSTLER Avi": "kunstler-avi",
    "KUNSTWERK-BLEND ": "kunstwerk-blend",
    "KUNTZ John": "kuntz-john",
    "KUNTZ John B": "kuntz-john-b",
    "KUNTZEVICH Richard": "kuntzevich-richard",
    "KUNTZMAN Gersh": "kuntzman-gersh",
    "KUNUTZ John": "kunutz-john",
    "KUNZE Michael": "kunze-michael",
    "KUNZE Michael R": "kunze-michael-r",
    "KUNZI Rick": "kunzi-rick",
    "KUO Jay": "kuo-jay",
    "KUO L Jay": "kuo-l-jay",
    "KUO Pao Kun": "kuo-pao-kun",
    "KUO Paul": "kuo-paul",
    "KUO Peter": "kuo-peter",
    "KUPFERBERG Tuli": "kupferberg-tuli",
    "KUPFERBLUM Markus": "kupferblum-markus",
    "KUPPER Gary": "kupper-gary",
    "KUPPNER Frank": "kuppner-frank",
    "KURACINA Elaine": "kuracina-elaine",
    "KURAMATO Soh": "kuramato-soh",
    "KURANDA Richard": "kuranda-richard",
    "KURANI David": "kurani-david",
    "KURAS Benjamin": "kuras-benjamin",
    "KURCHAK Scott": "kurchak-scott",
    "KUREICHYK Andrei": "kureichyk-andrei",
    "KUREISHI Hanif": "kureishi-hanif",
    "KURI Jorge": "kuri-jorge",
    "KURILOFF Linda": "kuriloff-linda",
    "KURITSKY Jocelyn": "kuritsky-jocelyn",
    "KURITZKES Justin": "kuritzkes-justin",
    "KURKENDAAL Lee": "kurkendaal-lee",
    "KURKJIAN John": "kurkjian-john",
    "KURNITZ Harry": "kurnitz-harry",
    "KUROCHKIN Maksym": "kurochkin-maksym",
    "KURODA Sherry": "kuroda-sherry",
    "KUROWSKI Mary": "kurowski-mary",
    "KURTH Frederick W": "kurth-frederick-w",
    "KURTTI Casey": "kurtti-casey",
    "KURTZ Cleveland": "kurtz-cleveland",
    "KURTZ Jack": "kurtz-jack",
    "KURTZ Joe": "kurtz-joe",
    "KURTZ Marcia Jean": "kurtz-marcia-jean",
    "KURUP Shishir": "kurup-shishir",
    "KURUVILLA Sunil": "kuruvilla-sunil",
    "KUSANGA Eiji": "kusanga-eiji",
    "KUSHNER Anna": "kushner-anna",
    "KUSHNER Brian \"Dyalekt\"": "kushner-brian-dyalekt",
    "KUSHNER Ellen": "kushner-ellen",
    "KUSHNER Martin H": "kushner-martin-h",
    "KUSHNER Michele Aldin": "kushner-michele-aldin",
    "KUSHNER Tony": "kushner-tony",
    "KUSHNIR Andrew": "kushnir-andrew",
    "KUSKE Ashley": "kuske-ashley",
    "KUSTOW Michael": "kustow-michael",
    "KUSUGAK Michael": "kusugak-michael",
    "KUSZ Fitzgerald": "kusz-fitzgerald",
    "KUTI Elizabeth": "kuti-elizabeth",
    "KUTI Fela Anikulapo": "kuti-fela-anikulapo",
    "KUTSCHIED Mandy": "kutschied-mandy",
    "KUWAHARA Gary": "kuwahara-gary",
    "KUWAYAMA Yoshihisa": "kuwayama-yoshihisa",
    "KUYKENDALL Les": "kuykendall-les",
    "KUZLER Frank": "kuzler-frank",
    "KUZMIN Mikhail": "kuzmin-mikhail",
    "KVALE Helene": "kvale-helene",
    "KVARES Don": "kvares-don",
    "KVARES Donald": "kvares-donald",
    "KVARNSTROM Kenneth": "kvarnstrom-kenneth",
    "KWAHULE Koffi": "kwahule-koffi",
    "KWAI Ajak": "kwai-ajak",
    "KWAN Paul": "kwan-paul",
    "KWEI-ARMAH Kwame": "kwei-armah-kwame",
    "KWIAT David": "kwiat-david",
    "KWIATKOWSKI Laura": "kwiatkowski-laura",
    "KWONG Dale Lee": "kwong-dale-lee",
    "KWONG Dan": "kwong-dan",
    "KYA-HILL Robert": "kya-hill-robert",
    "KYD Marcus": "kyd-marcus",
    "KYDD Jonathan": "kydd-jonathan",
    "KYDD Mark": "kydd-mark",
    "KYLE Barry": "kyle-barry",
    "KYLE Christopher": "kyle-christopher",
    "KYLE Emie": "kyle-emie",
    "KYLE Sacha": "kyle-sacha",
    "KYNASTON Margaret": "kynaston-margaret",
    "KYNE Dorothy": "kyne-dorothy",
    "KYOGEN ": "kyogen",
    "KYOO-HYUN Cho": "kyoo-hyun-cho",
    "KYPRIOS ": "kyprios",
    "KYRIELEISON Jack": "kyrieleison-jack",
    "KYSER Erma": "kyser-erma",
    "KYTE Mary": "kyte-mary",
    "KYUNG-WOOK Kim": "kyung-wook-kim"
  }
};