export default {
  "metadata": {
    "results": 1736,
    "timeStamp": "2025-12-05T21:27:09.838Z",
    "url": "https://www.doollee.com/PlaywrightsL/L_playwrights_a-f.php"
  },
  "authors": {
    "L Jess": "l-jess",
    "L A DANCE MACHINE ": "l-a-dance-machine",
    "LA CLEF Karl": "la-clef-karl",
    "LA COMPAGNIE DE PARTI-PRIS ": "la-compagnie-de-parti-pris",
    "LA COMPANIA ": "la-compania",
    "LA FARGE Phyllis": "la-farge-phyllis",
    "LA FLAMME Michelle": "la-flamme-michelle",
    "LA FORTUNE Felicity": "la-fortune-felicity",
    "LA FRENAIS Ian": "la-frenais-ian",
    "LA GALLIENNE Eva": "la-gallienne-eva",
    "LA JOHNJOSEPH ": "la-johnjoseph",
    "LA PUENTE Noemi De": "la-puente-noemi-de",
    "LA PUMA Christopher": "la-puma-christopher",
    "LA RIBOT ": "la-ribot",
    "LA ROCCA Robert": "la-rocca-robert",
    "LA RUSSO Anthony": "la-russo-anthony",
    "LA RUSSO II Louis": "la-russo-louis",
    "LA SCALA Lili": "la-scala-lili",
    "LA TEMPA Susan": "la-tempa-susan",
    "LA TORRACA Gerard": "la-torraca-gerard",
    "LA TOUCHE John": "la-touche-john",
    "LA TOURETTE Aileen": "la-tourette-aileen",
    "LAB 1 ": "lab-1",
    "LAB COLLECTIVE ": "lab-collective",
    "LABAN Marcus Anthony-Alexander": "laban-marcus-anthony-alexander",
    "LABANAUSKAITE Gabriele": "labanauskaite-gabriele",
    "LABANCA Christopher": "labanca-christopher",
    "LABANCA Matthew": "labanca-matthew",
    "LABAR Tom": "labar-tom",
    "LABARGE Peter": "labarge-peter",
    "LABERGE Marie": "laberge-marie",
    "LABERGE Matthew": "laberge-matthew",
    "LABEY Russell": "labey-russell",
    "LABICHE Eugene": "labiche-eugene",
    "LABIN Claudia": "labin-claudia",
    "LABLE Lorna": "lable-lorna",
    "LABONTE Maureen": "labonte-maureen",
    "LABORATORY THEATER ": "laboratory-theater",
    "LABORDE Charles": "laborde-charles",
    "LABORDE Rosa": "laborde-rosa",
    "LABOUNTY David": "labounty-david",
    "LABOUREUR Laura": "laboureur-laura",
    "LABRIOLA Matthew": "labriola-matthew",
    "LABRONE Meshaun": "labrone-meshaun",
    "LABUTE Neil": "labute-neil",
    "LABYRINTH THEATRE ": "labyrinth-theatre",
    "LACAMARA Carlos": "lacamara-carlos",
    "LACEY Alexander Matthew": "lacey-alexander-matthew",
    "LACEY Archie": "lacey-archie",
    "LACEY Franklin": "lacey-franklin",
    "LACEY J": "lacey-j",
    "LACEY John Rivera": "lacey-john-rivera",
    "LACEY Josh": "lacey-josh",
    "LACEY Maggie": "lacey-maggie",
    "LACEY Samantha": "lacey-samantha",
    "LACEY Sandra": "lacey-sandra",
    "LACEY Tom": "lacey-tom",
    "LACEY Vincent": "lacey-vincent",
    "LACH Jerzy": "lach-jerzy",
    "LACHAMBRE Benoit": "lachambre-benoit",
    "LACHAUD Marie Celine": "lachaud-marie-celine",
    "LACHENMEYER Nathaniel": "lachenmeyer-nathaniel",
    "LACHIUSA Matthew": "lachiusa-matthew",
    "LACHIUSA Michael John": "lachiusa-michael-john",
    "LACHLAN Iain": "lachlan-iain",
    "LACHLAN Wry": "lachlan-wry",
    "LACHMAN Craig": "lachman-craig",
    "LACHOW Stan": "lachow-stan",
    "LACKAAL DUCKRIC ": "lackaal-duckric",
    "LACKER Will": "lacker-will",
    "LACKEY Thomas": "lackey-thomas",
    "LACKEY William Benjamin": "lackey-william-benjamin",
    "LACONTE Stephen": "laconte-stephen",
    "LACOUR Barbara Babin": "lacour-barbara-babin",
    "LACROIX Bruno": "lacroix-bruno",
    "LACROIX Deborah": "lacroix-deborah",
    "LACUSTA Deb": "lacusta-deb",
    "LACY Jerry": "lacy-jerry",
    "LADBROOK Martin": "ladbrook-martin",
    "LADD Alex": "ladd-alex",
    "LADD Diane": "ladd-diane",
    "LADD Eddie": "ladd-eddie",
    "LADD John": "ladd-john",
    "LADDERMAN David": "ladderman-david",
    "LADEN Barry": "laden-barry",
    "LADENSON Michael": "ladenson-michael",
    "LADUE Byron": "ladue-byron",
    "LADUTKE Rachel Rubin": "ladutke-rachel-rubin",
    "LADY JUNK THEATRE ": "lady-junk-theatre",
    "LADYKO Natalia": "ladyko-natalia",
    "LAFAVE Susan": "lafave-susan",
    "LAFEVERE Brenda": "lafevere-brenda",
    "LAFFAN Kevin": "laffan-kevin",
    "LAFFEL Jeff": "laffel-jeff",
    "LAFFERTY Marcy": "lafferty-marcy",
    "LAFFERTY Tim": "lafferty-tim",
    "LAFFERTY Zoe": "lafferty-zoe",
    "LAFFOON Anne": "laffoon-anne",
    "LAFOND Sandrine": "lafond-sandrine",
    "LAFORCE Monique": "laforce-monique",
    "LAFOSTA Alex": "lafosta-alex",
    "LAFRAGE Sam": "lafrage-sam",
    "LAGACE Paul": "lagace-paul",
    "LAGANA Greg": "lagana-greg",
    "LAGARCE Jean-Luc": "lagarce-jean-luc",
    "LAGER Martin": "lager-martin",
    "LAGERCRANTZ Marika": "lagercrantz-marika",
    "LAGERKVIST Par": "lagerkvist-par",
    "LAGERLOF Malin": "lagerlof-malin",
    "LAGERSTEDT Margaret": "lagerstedt-margaret",
    "LAGIS Armelle": "lagis-armelle",
    "LAGOMARSINO Ron": "lagomarsino-ron",
    "LAGRANDEUR Tamara": "lagrandeur-tamara",
    "LAGRAVENESE Richard": "lagravenese-richard",
    "LAGRECA Charlie": "lagreca-charlie",
    "LAGRECA Jeff": "lagreca-jeff",
    "LAGREE Bret": "lagree-bret",
    "LAGRONE Kheven": "lagrone-kheven",
    "LAGRONOVA Lenka": "lagronova-lenka",
    "LAGUNA Sofie": "laguna-sofie",
    "LAHAIE David": "lahaie-david",
    "LAHAIE Scot": "lahaie-scot",
    "LAHAIE Ute": "lahaie-ute",
    "LAHAV Amit": "lahav-amit",
    "LAHERTY Simon": "laherty-simon",
    "LAHNE Sam": "lahne-sam",
    "LAHR John": "lahr-john",
    "LAI Evan": "lai-evan",
    "LAI Stan": "lai-stan",
    "LAIDIG Charlotte": "laidig-charlotte",
    "LAIDLAW Charlie": "laidlaw-charlie",
    "LAIDLAW Lorna": "laidlaw-lorna",
    "LAINE Bob": "laine-bob",
    "LAINE Cliff": "laine-cliff",
    "LAING Jamie": "laing-jamie",
    "LAING Janet": "laing-janet",
    "LAING Lucy": "laing-lucy",
    "LAING R D": "laing-r-d",
    "LAING Robert": "laing-robert",
    "LAING Stewart": "laing-stewart",
    "LAIRD Fiona": "laird-fiona",
    "LAIRD Jenny": "laird-jenny",
    "LAIRD Jenny (1)": "laird-jenny-1",
    "LAIRD Marvin": "laird-marvin",
    "LAIRD Nick": "laird-nick",
    "LAITH Khalid": "laith-khalid",
    "LAI-TUEN Lucy Chau": "lai-tuen-lucy-chau",
    "LAKE Abi": "lake-abi",
    "LAKE Deborah": "lake-deborah",
    "LAKE Frederick C": "lake-frederick-c",
    "LAKE Gerry Anthony": "lake-gerry-anthony",
    "LAKEMAN Barry": "lakeman-barry",
    "LAKES Suzanne": "lakes-suzanne",
    "LAKEVOLD Dale": "lakevold-dale",
    "LAKIER Gail": "lakier-gail",
    "LAKIN Chuck": "lakin-chuck",
    "LAKIN Sarah Elizabeth": "lakin-sarah-elizabeth",
    "LAKRA Arun": "lakra-arun",
    "LAL Ananda": "lal-ananda",
    "LAL P": "lal-p",
    "LALA Lottie": "lala-lottie",
    "LALANDE Francoise": "lalande-francoise",
    "LALER John": "laler-john",
    "LALL A F": "lall-a-f",
    "LALLONE Laura": "lallone-laura",
    "LALL-WILLIAMSON Shash": "lall-williamson-shash",
    "LALLY David": "lally-david",
    "LALLY Soinbhe": "lally-soinbhe",
    "LALLY Steven": "lally-steven",
    "LALONDE Jacques": "lalonde-jacques",
    "LALOR Stephanie": "lalor-stephanie",
    "LAM Angel": "lam-angel",
    "LAM Catherine": "lam-catherine",
    "LAM Edward": "lam-edward",
    "LAM Greg": "lam-greg",
    "LAM Richard": "lam-richard",
    "LAMA Tsering": "lama-tsering",
    "LAMACRAFT Jane": "lamacraft-jane",
    "LAMAR Cyriaque": "lamar-cyriaque",
    "LAMARE Alenka": "lamare-alenka",
    "LAMARRE Jacques": "lamarre-jacques",
    "LAMAY Sharilyn": "lamay-sharilyn",
    "LAMB A Clifton": "lamb-a-clifton",
    "LAMB David": "lamb-david",
    "LAMB Dylan": "lamb-dylan",
    "LAMB Evelyn": "lamb-evelyn",
    "LAMB Gary": "lamb-gary",
    "LAMB Georgina": "lamb-georgina",
    "LAMB Jenni": "lamb-jenni",
    "LAMB Margaret": "lamb-margaret",
    "LAMB Myrna": "lamb-myrna",
    "LAMB Peter": "lamb-peter",
    "LAMB Philip J": "lamb-philip-j",
    "LAMB Robert Boyden": "lamb-robert-boyden",
    "LAMB Roger": "lamb-roger",
    "LAMB Sabrina": "lamb-sabrina",
    "LAMB Stacey": "lamb-stacey",
    "LAMBDA Betty Paul": "lambda-betty-paul",
    "LAMBE Michael": "lambe-michael",
    "LAMBECK Mark": "lambeck-mark",
    "LAMBERG Marc": "lamberg-marc",
    "LAMBERT Alix": "lambert-alix",
    "LAMBERT Ann": "lambert-ann",
    "LAMBERT Anna": "lambert-anna",
    "LAMBERT Betty": "lambert-betty",
    "LAMBERT Brandon": "lambert-brandon",
    "LAMBERT Charles": "lambert-charles",
    "LAMBERT Christopher": "lambert-christopher",
    "LAMBERT Dallas": "lambert-dallas",
    "LAMBERT David": "lambert-david",
    "LAMBERT David Henry": "lambert-david-henry",
    "LAMBERT Dorothy": "lambert-dorothy",
    "LAMBERT James G": "lambert-james-g",
    "LAMBERT Justine": "lambert-justine",
    "LAMBERT Katie": "lambert-katie",
    "LAMBERT Kit": "lambert-kit",
    "LAMBERT Lisa": "lambert-lisa",
    "LAMBERT Lucien": "lambert-lucien",
    "LAMBERT Mark": "lambert-mark",
    "LAMBERT Max": "lambert-max",
    "LAMBERT Molly": "lambert-molly",
    "LAMBERT Sally": "lambert-sally",
    "LAMBERT Steve": "lambert-steve",
    "LAMBERT Steve (1)": "lambert-steve-1",
    "LAMBERTY Scott": "lamberty-scott",
    "LAMBRIANIDIS Christine": "lambrianidis-christine",
    "LAMBRIGHT Alexis": "lambright-alexis",
    "LAME Amy": "lame-amy",
    "LAMEDMAN Debbie": "lamedman-debbie",
    "LAMKIN Patricia": "lamkin-patricia",
    "LAMKIN Speed": "lamkin-speed",
    "LAMM Catherine": "lamm-catherine",
    "LAMMIN Daniel": "lammin-daniel",
    "LAMMOND Zoe": "lammond-zoe",
    "LAMONT Alonzo D": "lamont-alonzo-d",
    "LAMONT Juliet": "lamont-juliet",
    "LAMONT N B": "lamont-n-b",
    "LAMOR Carfer": "lamor-carfer",
    "LAMOREAUX Sherry": "lamoreaux-sherry",
    "LAMORTE Betty": "lamorte-betty",
    "LAMOS Mark": "lamos-mark",
    "LAMPANELLI Lisa": "lampanelli-lisa",
    "LAMPERT Diane C": "lampert-diane-c",
    "LAMPERT Nellwyn": "lampert-nellwyn",
    "LAMPERT Rachel": "lampert-rachel",
    "LAMPHERE Eula A": "lamphere-eula-a",
    "LAMPITOC Sunshine Pearl": "lampitoc-sunshine-pearl",
    "LAMPLEY Oni Faida": "lampley-oni-faida",
    "LAMPORT F J": "lamport-f-j",
    "LAMPORT Paul": "lamport-paul",
    "LAMUDE Terence": "lamude-terence",
    "LAMUM Catherine": "lamum-catherine",
    "LAN David": "lan-david",
    "LANASA Amy": "lanasa-amy",
    "LANCASTER Andre": "lancaster-andre",
    "LANCASTER Metro-Boulot-Dodo": "lancaster-metro-boulot-dodo",
    "LANCASTER Sylvia": "lancaster-sylvia",
    "LANCASTER WALK Peter": "lancaster-walk-peter",
    "LANCE James": "lance-james",
    "LANCE Rory": "lance-rory",
    "LANCEFIELD Steven": "lancefield-steven",
    "LANCELLOTTI John R": "lancellotti-john-r",
    "LANCIERS Barbara": "lanciers-barbara",
    "LANCRENON Sebastian": "lancrenon-sebastian",
    "LANCY Michael": "lancy-michael",
    "LAND John Mallory": "land-john-mallory",
    "LAND Kevin": "land-kevin",
    "LAND Peter": "land-peter",
    "LANDAU David": "landau-david",
    "LANDAU Denis": "landau-denis",
    "LANDAU Fred": "landau-fred",
    "LANDAU Helen": "landau-helen",
    "LANDAU John": "landau-john",
    "LANDAU Leah": "landau-leah",
    "LANDAU Niki": "landau-niki",
    "LANDAU Tina": "landau-tina",
    "LANDAY David": "landay-david",
    "LANDAYAN Rudy": "landayan-rudy",
    "LANDER David": "lander-david",
    "LANDER Jonathan Ari": "lander-jonathan-ari",
    "LANDER Suzanne": "lander-suzanne",
    "LANDERS Alexandra": "landers-alexandra",
    "LANDERS Jane": "landers-jane",
    "LANDERS Linda": "landers-linda",
    "LANDERS Matthew": "landers-matthew",
    "LANDERS W M": "landers-w-m",
    "LANDES S H": "landes-s-h",
    "LANDES Sidney Harold": "landes-sidney-harold",
    "LANDES William-Alan": "landes-william-alan",
    "LANDESMAN Fran": "landesman-fran",
    "LANDESMAN Jay": "landesman-jay",
    "LANDFIELD Matthew H": "landfield-matthew-h",
    "LANDGREN Mia": "landgren-mia",
    "LANDI Damian": "landi-damian",
    "LANDI Paolo Emilio": "landi-paolo-emilio",
    "LANDIS C Kay \"Andy\"": "landis-c-kay",
    "LANDIS Cynthia": "landis-cynthia",
    "LANDIS Joseph C": "landis-joseph-c",
    "LANDIS Paul": "landis-paul",
    "LANDLES Iain": "landles-iain",
    "LANDON David ": "landon-david",
    "LANDON-SMITH Kristine": "landon-smith-kristine",
    "LANDOR Alfred": "landor-alfred",
    "LANDOR Gina": "landor-gina",
    "LANDOVSKY Pavel": "landovsky-pavel",
    "LANDOWNE Mahayana": "landowne-mahayana",
    "LANDRIGAN Christopher": "landrigan-christopher",
    "LANDRIGAN Stephen": "landrigan-stephen",
    "LANDRON Jack": "landron-jack",
    "LANDRUM Sally": "landrum-sally",
    "LANDRUM Sherry": "landrum-sherry",
    "LANDRY Jim": "landry-jim",
    "LANDRY Joe": "landry-joe",
    "LANDRY Ryan": "landry-ryan",
    "LANDSBERG David": "landsberg-david",
    "LANDSMAN Aaron": "landsman-aaron",
    "LANDUCCI Greg": "landucci-greg",
    "LANDVATTER Ali": "landvatter-ali",
    "LANDWEHR Michael": "landwehr-michael",
    "LANDY Michael": "landy-michael",
    "LANDY Robert Jay": "landy-robert-jay",
    "LANE Alexander": "lane-alexander",
    "LANE Amber": "lane-amber",
    "LANE Andrew": "lane-andrew",
    "LANE Brian Alan": "lane-brian-alan",
    "LANE Burton": "lane-burton",
    "LANE Carla": "lane-carla",
    "LANE Carolyn B": "lane-carolyn-b",
    "LANE Chris": "lane-chris",
    "LANE Cyrus": "lane-cyrus",
    "LANE David": "lane-david",
    "LANE Dorothy": "lane-dorothy",
    "LANE Eric": "lane-eric",
    "LANE Faye": "lane-faye",
    "LANE Gerard": "lane-gerard",
    "LANE Harry": "lane-harry",
    "LANE Helen R": "lane-helen-r",
    "LANE Jack": "lane-jack",
    "LANE Jeffrey": "lane-jeffrey",
    "LANE Jennifer": "lane-jennifer",
    "LANE Joan": "lane-joan",
    "LANE John": "lane-john",
    "LANE John G": "lane-john-g",
    "LANE Jon": "lane-jon",
    "LANE Judith C": "lane-judith-c",
    "LANE Larry": "lane-larry",
    "LANE Lourds": "lane-lourds",
    "LANE Maggie": "lane-maggie",
    "LANE Nathan": "lane-nathan",
    "LANE Nick": "lane-nick",
    "LANE Preston": "lane-preston",
    "LANE R L": "lane-r-l",
    "LANE Robert": "lane-robert",
    "LANE Ros": "lane-ros",
    "LANE Samuel": "lane-samuel",
    "LANE Saskia": "lane-saskia",
    "LANE Sharyn": "lane-sharyn",
    "LANE Sheila": "lane-sheila",
    "LANE Stacey": "lane-stacey",
    "LANE Stewart F": "lane-stewart-f",
    "LANFER Stefan Graves": "lanfer-stefan-graves",
    "LANG Alison": "lang-alison",
    "LANG Allan": "lang-allan",
    "LANG Andrew": "lang-andrew",
    "LANG Debra T": "lang-debra-t",
    "LANG Gene": "lang-gene",
    "LANG Harold": "lang-harold",
    "LANG Jack": "lang-jack",
    "LANG Joe": "lang-joe",
    "LANG Louisa": "lang-louisa",
    "LANG Matt": "lang-matt",
    "LANG Nick": "lang-nick",
    "LANG Sean": "lang-sean",
    "LANG Stephen": "lang-stephen",
    "LANG Tony": "lang-tony",
    "LANG V R": "lang-v-r",
    "LANG William": "lang-william",
    "LANGA Mandla": "langa-mandla",
    "LANGAN Dustin": "langan-dustin",
    "LANGAN John": "langan-john",
    "LANGDON John": "langdon-john",
    "LANGDON Peter": "langdon-peter",
    "LANGE A R": "lange-a-r",
    "LANGE Ed": "lange-ed",
    "LANGE Greta": "lange-greta",
    "LANGE Leanora": "lange-leanora",
    "LANGE Sue": "lange-sue",
    "LANGE Ted": "lange-ted",
    "LANGEN Timothy": "langen-timothy",
    "LANGENBERG Gwen": "langenberg-gwen",
    "LANGENHEIM Michael": "langenheim-michael",
    "LANGER Arthur": "langer-arthur",
    "LANGER Lawrence": "langer-lawrence",
    "LANGER Ruth": "langer-ruth",
    "LANGER Ryan Zachary": "langer-ryan-zachary",
    "LANGERT Max": "langert-max",
    "LANGFORD Darren John": "langford-darren-john",
    "LANGFORD Gary": "langford-gary",
    "LANGFORD Gemma": "langford-gemma",
    "LANGFORD Guy": "langford-guy",
    "LANGFORD Jennie": "langford-jennie",
    "LANGFORD Paul": "langford-paul",
    "LANGFORD Peter": "langford-peter",
    "LANGHAM Chris": "langham-chris",
    "LANGHAM Joseph": "langham-joseph",
    "LANGHAM Mark": "langham-mark",
    "LANGHOFF Anna": "langhoff-anna",
    "LANGLEY Ben": "langley-ben",
    "LANGLEY Charles": "langley-charles",
    "LANGLEY Lee": "langley-lee",
    "LANGLEY Niki": "langley-niki",
    "LANGLEY Noel": "langley-noel",
    "LANGLEY Rachel": "langley-rachel",
    "LANGLEY Rod": "langley-rod",
    "LANGLEY Steven": "langley-steven",
    "LANGLINAIS M Pepper": "langlinais-m-pepper",
    "LANGLOIS Tristan": "langlois-tristan",
    "LANGMAN Catherine": "langman-catherine",
    "LANGMAN Peter F": "langman-peter-f",
    "LANGNER Armina Marshall": "langner-armina-marshall",
    "LANGNER Lawrence": "langner-lawrence",
    "LANGNER Pat": "langner-pat",
    "LANGNER Ruth": "langner-ruth",
    "LANGRIDGE Natasha": "langridge-natasha",
    "LANGRIDGE Richard": "langridge-richard",
    "LANGS John Patrick": "langs-john-patrick",
    "LANGSNER Meron": "langsner-meron",
    "LANGSTON Stephen": "langston-stephen",
    "LANGSTROTH Gail": "langstroth-gail",
    "LANGTRY Brian": "langtry-brian",
    "LANGUIRAND Jacques": "languirand-jacques",
    "LANGWORTH Joe": "langworth-joe",
    "LANGWORTHY Douglas": "langworthy-douglas",
    "LANIADO Howard I": "laniado-howard-i",
    "LANIER Wayne": "lanier-wayne",
    "LANIGAN Damian": "lanigan-damian",
    "LANIGAN Robert": "lanigan-robert",
    "LANIUS Jessica": "lanius-jessica",
    "LANKFORD Dave": "lankford-dave",
    "LANNON Pete": "lannon-pete",
    "LANNON Tom": "lannon-tom",
    "LANNOY Aurelie": "lannoy-aurelie",
    "LANOUX Victor": "lanoux-victor",
    "LANSKI Cathy": "lanski-cathy",
    "LANSLEY Oliver": "lansley-oliver",
    "LANTER Tom": "lanter-tom",
    "LANTOS Jeff": "lantos-jeff",
    "LANTRY Karen": "lantry-karen",
    "LANTZ James": "lantz-james",
    "LANTZ Lou": "lantz-lou",
    "LANYON Angela": "lanyon-angela",
    "LANZAFAMA Mike": "lanzafama-mike",
    "LANZARA Joseph": "lanzara-joseph",
    "LANZILLOTTO Annie": "lanzillotto-annie",
    "LANZL Martha": "lanzl-martha",
    "LAPADULA Marc Andrew": "lapadula-marc-andrew",
    "LAPAINE Daniel": "lapaine-daniel",
    "LAPERCHE Brian": "laperche-brian",
    "LAPHAM Fabian": "lapham-fabian",
    "LAPID Shulamit": "lapid-shulamit",
    "LAPIDO Duro": "lapido-duro",
    "LAPIERRE Mark": "lapierre-mark",
    "LAPIERRE Robert": "lapierre-robert",
    "LAPINE James": "lapine-james",
    "LAPINSKY Michael": "lapinsky-michael",
    "LAPLANT Don": "laplant-don",
    "LAPORTE Alexandria": "laporte-alexandria",
    "LAPORTE Bryan": "laporte-bryan",
    "LAPORTE Stephane": "laporte-stephane",
    "LAPOTAIRE Jane": "lapotaire-jane",
    "LAPPIN Anthony": "lappin-anthony",
    "LAPUMA Deborah": "lapuma-deborah",
    "LAPWORTH Paul": "lapworth-paul",
    "LARAE Cristal": "larae-cristal",
    "LARAIA Luigi": "laraia-luigi",
    "LARANGEIRA Crispin": "larangeira-crispin",
    "LARBEY Bob": "larbey-bob",
    "LARCHE Douglas W": "larche-douglas-w",
    "LARCHE Will": "larche-will",
    "LARDERA Natasha": "lardera-natasha",
    "LARDNER JR Ring": "lardner-jr-ring",
    "LARGE Keith": "large-keith",
    "LARGESS Bill": "largess-bill",
    "LARIMER Andrew": "larimer-andrew",
    "LARIMER Robert": "larimer-robert",
    "LARIMORE Drew": "larimore-drew",
    "LARISCY Nichole": "lariscy-nichole",
    "LARK Caroline": "lark-caroline",
    "LARKIN Anna": "larkin-anna",
    "LARKIN Breda": "larkin-breda",
    "LARKIN George": "larkin-george",
    "LARKIN Jonathan": "larkin-jonathan",
    "LARKIN Lauren": "larkin-lauren",
    "LARKIN Maeve": "larkin-maeve",
    "LARKIN Michelle": "larkin-michelle",
    "LARLHAM Margaret": "larlham-margaret",
    "LARNACH Julian": "larnach-julian",
    "LARNER Chris": "larner-chris",
    "LARNER Daniel": "larner-daniel",
    "LARNYOH George": "larnyoh-george",
    "LAROCCA James A": "larocca-james-a",
    "LAROCCA James L": "larocca-james-l",
    "LAROCQUE Conor Hague": "larocque-conor-hague",
    "LAROCQUE Dan": "larocque-dan",
    "LAROCQUE Linda": "larocque-linda",
    "LAROCQUE Stephen": "larocque-stephen",
    "LAROSE Kenneth": "larose-kenneth",
    "LAROSE Melba": "larose-melba",
    "LARRIEU Fred": "larrieu-fred",
    "LARRIMORE Drew": "larrimore-drew",
    "LARRY Elephant": "larry-elephant",
    "LARSEN Anika": "larsen-anika",
    "LARSEN Bethany": "larsen-bethany",
    "LARSEN Carl": "larsen-carl",
    "LARSEN Daniel": "larsen-daniel",
    "LARSEN Katie": "larsen-katie",
    "LARSEN Kristian": "larsen-kristian",
    "LARSEN Lance": "larsen-lance",
    "LARSEN Milt": "larsen-milt",
    "LARSEN Peter": "larsen-peter",
    "LARSEN Polash": "larsen-polash",
    "LARSEN Ronnie": "larsen-ronnie",
    "LARSEN Stephen": "larsen-stephen",
    "LARSEN Susan": "larsen-susan",
    "LARSEN Wolf": "larsen-wolf",
    "LARSON Jack": "larson-jack",
    "LARSON James": "larson-james",
    "LARSON Jayne Amelia": "larson-jayne-amelia",
    "LARSON Jonathan": "larson-jonathan",
    "LARSON Joshua Caleb": "larson-joshua-caleb",
    "LARSON Larry": "larson-larry",
    "LARSON Layne": "larson-layne",
    "LARSON Melissa Leilani": "larson-melissa-leilani",
    "LARSON Peter": "larson-peter",
    "LARSON T J": "larson-t-j",
    "LARSSON Stefan": "larsson-stefan",
    "LARSSON Stig": "larsson-stig",
    "LARTEY Leonnie": "lartey-leonnie",
    "LARUSSO II Louis": "la-russo-ii-louis",
    "LAS Guy": "las-guy",
    "LASARUS Gwen": "lasarus-gwen",
    "LASCA Norman": "lasca-norman",
    "LASCELLES Kendrew": "lascelles-kendrew",
    "LASCH Stefan": "lasch-stefan",
    "LASDEN-LYMAN Zoe": "lasden-lyman-zoe",
    "LASDON David": "lasdon-david",
    "LASDUN Gary": "lasdun-gary",
    "LASER Antonia": "laser-antonia",
    "LASHER Margot": "lasher-margot",
    "LASHMAN Kal": "lashman-kal",
    "LASHOF Carol S": "lashof-carol-s",
    "LASITER Ian": "lasiter-ian",
    "LASKA Edward": "laska-edward",
    "LASKER Philip Jayson": "lasker-philip-jayson",
    "LASKER-SCHULER Else": "lasker-schuler-else",
    "LASKEY Margaux": "laskey-margaux",
    "LASKI Marghanita": "laski-marghanita",
    "LASKIN John": "laskin-john",
    "LASKIN Jon": "laskin-jon",
    "LASKO Jim": "lasko-jim",
    "LASKOWSKI Jacek": "laskowski-jacek",
    "LASKY Jason": "lasky-jason",
    "LASLETT Mary": "laslett-mary",
    "LASLEY Teresa Michelle": "lasley-teresa-michelle",
    "LASSER B": "lasser-b",
    "LASSER Brian": "lasser-brian",
    "LASSIG David": "lassig-david",
    "LASSITER B M": "lassiter-b-m",
    "LASSITER Edward C": "lassiter-edward-c",
    "LASSITER Greg": "lassiter-greg",
    "LASSITER Jim": "lassiter-jim",
    "LAST Jack": "last-jack",
    "LAST Rex": "last-rex",
    "LAST CHANCE SALOON ": "last-chance-saloon",
    "LAST FANCIES ": "last-fancies",
    "LASTER Lori Ann": "laster-lori-ann",
    "LASZLO Carl": "laszlo-carl",
    "LASZLO Miklos": "laszlo-miklos",
    "LATARO Ed": "lataro-ed",
    "LATHAM Aaron": "latham-aaron",
    "LATHAM Alexis": "latham-alexis",
    "LATHAM Donna": "latham-donna",
    "LATHAM Jean Lee": "latham-jean-lee",
    "LATHAM Russell P": "latham-russell-p",
    "LATHAM Tim": "latham-tim",
    "LATHAN Peter": "lathan-peter",
    "LATHROP Aline K": "lathrop-aline-k",
    "LATHROP Mara": "lathrop-mara",
    "LATIMER Andrew": "latimer-andrew",
    "LATIMER Lizi": "latimer-lizi",
    "LATIMER Randy Sue": "latimer-randy-sue",
    "LATINA Aaron R": "latina-aaron-r",
    "LATOURETTE Charles": "latourette-charles",
    "LATOWICKI Jessica": "latowicki-jessica",
    "LATRO Christopher B": "latro-christopher-b",
    "LATTANZI Bill": "lattanzi-bill",
    "LATTIG Lance": "lattig-lance",
    "LATTIMORE Richmond": "lattimore-richmond",
    "LATTUADA Laura": "lattuada-laura",
    "LAU Anthony": "lau-anthony",
    "LAU Barbara": "lau-barbara",
    "LAU Gregory": "lau-gregory",
    "LAU Rick": "lau-rick",
    "LAU Tabia": "lau-tabia",
    "LAUB Kevin": "laub-kevin",
    "LAUBACH Susan": "laubach-susan",
    "LAUBER Bea": "lauber-bea",
    "LAUCHLAN Iain": "lauchlan-iain",
    "LAUCHMAN Richard": "lauchman-richard",
    "LAUCK Carol": "lauck-carol",
    "LAUCKNER Rolf": "lauckner-rolf",
    "LAUDERDALE Jason": "lauderdale-jason",
    "LAUDERDALE Joe": "lauderdale-joe",
    "LAUER Ben": "lauer-ben",
    "LAUER Rob": "lauer-rob",
    "LAUFER Deborah Zoe": "laufer-deborah-zoe",
    "LAUFER Linda E": "laufer-linda-e",
    "LAUFER Paulette": "laufer-paulette",
    "LAUGHEAD Scott": "laughead-scott",
    "LAUGHTON Charles": "laughton-charles",
    "LAUGHTON Stephen": "laughton-stephen",
    "LAUGHTON Verity": "laughton-verity",
    "LAUHER Bobby": "lauher-bobby",
    "LAUINGER Joe": "lauinger-joe",
    "LAUMBERG Tony": "laumberg-tony",
    "LAUNAY Andre": "launay-andre",
    "LAUNDER Dimitri": "launder-dimitri",
    "LAUNDRA Linda": "laundra-linda",
    "LAUPER Cyndi": "lauper-cyndi",
    "LAUPUS Adam": "laupus-adam",
    "LAUPUS Arthur": "laupus-arthur",
    "LAURA Anthony Michael": "laura-anthony-michael",
    "LAURA Dina": "laura-dina",
    "LAURANCE Adrian": "laurance-adrian",
    "LAUREN Jillian": "lauren-jillian",
    "LAUREN Maggie": "lauren-maggie",
    "LAUREN S K": "lauren-s-k",
    "LAURENCE Charles": "laurence-charles",
    "LAURENCE Dan H": "laurence-dan-h",
    "LAURENCE Eliot": "laurence-eliot",
    "LAURENCE Evan": "laurence-evan",
    "LAURENCE Kristen": "laurence-kristen",
    "LAURENCE Michael": "laurence-michael",
    "LAURENCE Rachael": "laurence-rachael",
    "LAURENCEAU Wanda": "laurenceau-wanda",
    "LAURENS Joanna": "laurens-joanna",
    "LAURENT Holly": "laurent-holly",
    "LAURENTS Arthur": "laurents-arthur",
    "LAURENTY Michael": "laurenty-michael",
    "LAURIA Courtney Brooke": "lauria-courtney-brooke",
    "LAURIA Dan": "lauria-dan",
    "LAURIE Sallie": "laurie-sallie",
    "LAURO Shirley": "lauro-shirley",
    "LAUSUND Ingrid": "lausund-ingrid",
    "LAUTE Sarah": "laute-sarah",
    "LAUTEN Elodie": "lauten-elodie",
    "LAUVER Ned W": "lauver-ned-w",
    "LAUWERS Jan": "lauwers-jan",
    "LAUZON June Walker": "lauzon-june-walker",
    "LAVAGNINO Tom": "lavagnino-tom",
    "LAVAL Maurice": "laval-maurice",
    "LAVALLEE Spencer": "lavallee-spencer",
    "LAVECCHIA Antoinette": "lavecchia-antoinette",
    "LAVELL Stephen": "lavell-stephen",
    "LAVELLE Gregory J": "lavelle-gregory-j",
    "LAVELLE Peter": "lavelle-peter",
    "LAVENDAR Dan": "lavendar-dan",
    "LAVENDER Andy": "lavender-andy",
    "LAVENDER-SMITH Evan": "lavender-smith-evan",
    "LAVER Franz": "laver-franz",
    "LAVERCOMBE Jesse": "lavercombe-jesse",
    "LAVERTON Joe": "laverton-joe",
    "LAVERTY Ashley": "laverty-ashley",
    "LAVERTY Maura": "laverty-maura",
    "LAVERTY Paul": "laverty-paul",
    "LAVERY Bryony": "lavery-bryony",
    "LAVERY Emmet": "lavery-emmet",
    "LAVIE Oren": "lavie-oren",
    "LAVIGNE Louis-Dominique": "lavigne-louis-dominique",
    "LAVILLE Mark": "laville-mark",
    "LAVILLE Pierre": "laville-pierre",
    "LAVIN Cinzi": "lavin-cinzi",
    "LAVIN Deborah": "lavin-deborah",
    "LAVIN Kevin": "lavin-kevin",
    "LAVINE David": "lavine-david",
    "LAVIOLETTE Byron": "laviolette-byron",
    "LAVOHN Robert": "lavohn-robert",
    "LAVOIE Kitt": "lavoie-kitt",
    "LAVOIE Mike": "lavoie-mike",
    "LAVRAKAS Paul": "lavrakas-paul",
    "LAVRIK Silvester": "lavrik-silvester",
    "LAW Adam": "law-adam",
    "LAW Alma H": "law-alma-h",
    "LAW Bob": "law-bob",
    "LAW Frank": "law-frank",
    "LAW Gretchen Anna": "law-gretchen-anna",
    "LAW J Sibley": "law-j-sibley",
    "LAW John": "law-john",
    "LAW Kieran": "law-kieran",
    "LAW Kirsten": "law-kirsten",
    "LAW Larry": "law-larry",
    "LAW Michael": "law-michael",
    "LAWAL Farah": "lawal-farah",
    "LAWFORD Ningali": "lawford-ningali",
    "LAWING Lee Richard": "lawing-lee-richard",
    "LAWLER Dwayne": "lawler-dwayne",
    "LAWLER Frank": "lawler-frank",
    "LAWLER Janet": "lawler-janet",
    "LAWLER Kevin": "lawler-kevin",
    "LAWLER Mary F": "lawler-mary-f",
    "LAWLER Ray": "lawler-ray",
    "LAWLER Twana": "lawler-twana",
    "LAWLESS Elinor": "lawless-elinor",
    "LAWLESS Fred": "lawless-fred",
    "LAWLESS Malachy": "lawless-malachy",
    "LAWLESS Sue": "lawless-sue",
    "LAWLOR Sean": "lawlor-sean",
    "LAWLOR Tim": "lawlor-tim",
    "LAWRENCE Adam": "lawrence-adam",
    "LAWRENCE Alison": "lawrence-alison",
    "LAWRENCE Amanda": "lawrence-amanda",
    "LAWRENCE Andy": "lawrence-andy",
    "LAWRENCE Anne": "lawrence-anne",
    "LAWRENCE Beth": "lawrence-beth",
    "LAWRENCE Bill": "lawrence-bill",
    "LAWRENCE Billy": "lawrence-billy",
    "LAWRENCE Brad": "lawrence-brad",
    "LAWRENCE C E": "lawrence-c-e",
    "LAWRENCE Callum Smith": "lawrence-callum-smith",
    "LAWRENCE Charles": "lawrence-charles",
    "LAWRENCE Christopher": "lawrence-christopher",
    "LAWRENCE Colin": "lawrence-colin",
    "LAWRENCE Curtis": "lawrence-curtis",
    "LAWRENCE Dan": "lawrence-dan",
    "LAWRENCE Danny": "lawrence-danny",
    "LAWRENCE David": "lawrence-david",
    "LAWRENCE Diana": "lawrence-diana",
    "LAWRENCE Eddie": "lawrence-eddie",
    "LAWRENCE Eleanor": "lawrence-eleanor",
    "LAWRENCE Gavin": "lawrence-gavin",
    "LAWRENCE Gwilym": "lawrence-gwilym",
    "LAWRENCE Harriet Vee": "lawrence-harriet-vee",
    "LAWRENCE Jack": "lawrence-jack",
    "LAWRENCE Jean": "lawrence-jean",
    "LAWRENCE Jeremy": "lawrence-jeremy",
    "LAWRENCE Jerome": "lawrence-jerome",
    "LAWRENCE Joan": "lawrence-joan",
    "LAWRENCE Judy": "lawrence-judy",
    "LAWRENCE Katherine": "lawrence-katherine",
    "LAWRENCE Kelly": "lawrence-kelly",
    "LAWRENCE Maggie": "lawrence-maggie",
    "LAWRENCE Maureen": "lawrence-maureen",
    "LAWRENCE Mike": "lawrence-mike",
    "LAWRENCE Naomi": "lawrence-naomi",
    "LAWRENCE Natalie Parker": "lawrence-natalie-parker",
    "LAWRENCE Paul": "lawrence-paul",
    "LAWRENCE Paul J": "lawrence-paul-j",
    "LAWRENCE Philip": "lawrence-philip",
    "LAWRENCE Ray": "lawrence-ray",
    "LAWRENCE Reginald": "lawrence-reginald",
    "LAWRENCE Ruth": "lawrence-ruth",
    "LAWRENCE William": "lawrence-william",
    "LAWRENCE William G": "lawrence-william-g",
    "LAWRENSON Matt": "lawrenson-matt",
    "LAWRIE-PAUL Alisha": "lawrie-paul-alisha",
    "LAWRY Jim": "lawry-jim",
    "LAWS Karen": "laws-karen",
    "LAWS Mary": "laws-mary",
    "LAWS Valerie": "laws-valerie",
    "LAWSON Aletta": "lawson-aletta",
    "LAWSON David": "lawson-david",
    "LAWSON Gary": "lawson-gary",
    "LAWSON Geoff": "lawson-geoff",
    "LAWSON Josh": "lawson-josh",
    "LAWSON Pete": "lawson-pete",
    "LAWSON Philip": "lawson-philip",
    "LAWSON Phillip": "lawson-phillip",
    "LAWSON Richard": "lawson-richard",
    "LAWSON Robert": "lawson-robert",
    "LAWSON Sebastien": "lawson-sebastien",
    "LAWSON Stephen": "lawson-stephen",
    "LAWSON Steve": "lawson-steve",
    "LAWSON Taio Rene": "lawson-taio-rene",
    "LAWSON Veva Dianne": "lawson-veva-dianne",
    "LAWSON-SMITH Hayley": "lawson-smith-hayley",
    "LAWTON Anthony": "lawton-anthony",
    "LAWTON David": "lawton-david",
    "LAWTON Jacqueline E": "lawton-jacqueline-e",
    "LAWTON Leslie": "lawton-leslie",
    "LAWTON Richard": "lawton-richard",
    "LAWTON Sally": "lawton-sally",
    "LAWTON Tony": "lawton-tony",
    "LAWTON Will": "lawton-will",
    "LAX Annecy": "lax-annecy",
    "LAXDAL Vivienne": "laxdal-vivienne",
    "LAY Richard": "lay-richard",
    "LAYA Jean-Louis": "laya-jean-louis",
    "LAYBERRY Janet": "layberry-janet",
    "LAYCOCK W M B": "laycock-w-m-b",
    "LAYERA Ramon": "layera-ramon",
    "LAYNE Marcia": "layne-marcia",
    "LAYTE Henry": "layte-henry",
    "LAYTON Ashley Scott": "layton-ashley-scott",
    "LAYTON Erin": "layton-erin",
    "LAYTON Joe": "layton-joe",
    "LAYTON Jon Pawinski": "layton-jon-pawinski",
    "LAYTON Peter": "layton-peter",
    "LAYTON Richard": "layton-richard",
    "LAYTON Tony": "layton-tony",
    "LAYZELL Richard": "layzell-richard",
    "LAZAN Michael": "lazan-michael",
    "LAZAR Alan": "lazar-alan",
    "LAZAR Jerry": "lazar-jerry",
    "LAZARD Naomi": "lazard-naomi",
    "LAZARE Magdelena": "lazare-magdelena",
    "LAZARIAN Kristen": "lazarian-kristen",
    "LAZAROO Kit": "lazaroo-kit",
    "LAZARUS Frank": "lazarus-frank",
    "LAZARUS Ginger": "lazarus-ginger",
    "LAZARUS John": "lazarus-john",
    "LAZARUS Lory": "lazarus-lory",
    "LAZARUS Milton": "lazarus-milton",
    "LAZARUS Natalia": "lazarus-natalia",
    "LAZEBNIK Claire": "lazebnik-claire",
    "LAZEBNIK Ken": "lazebnik-ken",
    "LAZEBNIK Philip": "lazebnik-philip",
    "LAZELL Estelle Bernice": "lazell-estelle-bernice",
    "LAZENBY Belinda": "lazenby-belinda",
    "LAZOUR Daniel": "lazour-daniel",
    "LAZOUR Patrick": "lazour-patrick",
    "LAZURUS John": "lazurus-john",
    "LAZURUS Lory": "lazurus-lory",
    "LAZZARO Emily": "lazzaro-emily",
    "LAZZARO Erin": "lazzaro-erin",
    "LAZZI ": "lazzi",
    "LCDT ": "lcdt",
    "L'DERA Ray": "l-dera-ray",
    "LE HaiHa": "le-haiha",
    "LE Lien": "le-lien",
    "LE Tony": "le-tony",
    "LE Viet": "le-viet",
    "LE BAR Tom": "le-bar-tom",
    "LE BLANC Jennifer": "le-blanc-jennifer",
    "LE BOND Sue": "le-bond-sue",
    "LE BRETON Andrew": "le-breton-andrew",
    "LE BRETON DE HAUTEROCHE Noel": "le-breton-de-hauteroche-noel",
    "LE CLANCHE DU RANDE ": "le-clanche-du-rande",
    "LE CORNEE Gael": "le-cornee-gael",
    "LE DREW Ronnie": "le-drew-ronnie",
    "LE GALLIENNE Eva": "le-gallienne-eva",
    "LE GASSICK James": "le-gassick-james",
    "LE HUNTE Pramila": "le-hunte-pramila",
    "LE MAR Angie": "le-mar-angie",
    "LE MESURIER Nick": "le-mesurier-nick",
    "LE MOINE Philippe": "le-moine-philippe",
    "LE MOT JUSTE ": "le-mot-juste",
    "LE NAVET BETE ": "le-navet-bete",
    "LE NGUYEN Tony": "le-nguyen-tony",
    "LE QUATUOR ": "le-quatuor",
    "LE QUY Doung": "le-quy-doung",
    "LE ROY Warner": "le-roy-warner",
    "LE SORANO ": "le-sorano",
    "LE VASSEUR Will": "le-vasseur-will",
    "LE WILHELM ": "le-wilhelm",
    "LEA Helen": "lea-helen",
    "LEA Jessica": "lea-jessica",
    "LEA Patricia": "lea-patricia",
    "LEABHART Thomas": "leabhart-thomas",
    "LEACH Amy": "leach-amy",
    "LEACH Ashley Christopher": "leach-ashley-christopher",
    "LEACH Casey": "leach-casey",
    "LEACH Colin": "leach-colin",
    "LEACH James": "leach-james",
    "LEACH Karoline": "leach-karoline",
    "LEACH Kristina": "leach-kristina",
    "LEACH Norman": "leach-norman",
    "LEACH Roger": "leach-roger",
    "LEACH Toby": "leach-toby",
    "LEACH Wilford": "leach-wilford",
    "LEACOCK Steven": "leacock-steven",
    "LEADER Avraham": "leader-avraham",
    "LEADER Beatrice": "leader-beatrice",
    "LEADER Brian": "leader-brian",
    "LEAF Claudia": "leaf-claudia",
    "LEAF Ellis": "leaf-ellis",
    "LEAF Jonathan": "leaf-jonathan",
    "LEAF Justin": "leaf-justin",
    "LEAHIGH Pamela": "leahigh-pamela",
    "LEAHY Arthur R": "leahy-arthur-r",
    "LEAHY Brian Patrick": "leahy-brian-patrick",
    "LEAHY Ian": "leahy-ian",
    "LEAHY Karen": "leahy-karen",
    "LEAHY Kathi": "leahy-kathi",
    "LEAHY Megan": "leahy-megan",
    "LEAHY Rory": "leahy-rory",
    "LEAKE Damien": "leake-damien",
    "LEAL Douglas": "leal-douglas",
    "LEALE Geraldine": "leale-geraldine",
    "LEAMING Greg": "leaming-greg",
    "LEAN Ferelith": "lean-ferelith",
    "LEANDER Michael": "leander-michael",
    "LEAR Norman": "lear-norman",
    "LEAR Tina": "lear-tina",
    "LEARD Jim": "leard-jim",
    "LEARN Sondra": "learn-sondra",
    "LEARNER Laurence": "learner-laurence",
    "LEARNER Tobsha": "learner-tobsha",
    "LEARNING Walter": "learning-walter",
    "LEARY Brandy": "leary-brandy",
    "LEARY Gordon": "leary-gordon",
    "LEARY Helen": "leary-helen",
    "LEARY John": "leary-john",
    "LEARY Nolan": "leary-nolan",
    "LEARY Simon K": "leary-simon-k",
    "LEAS Adele": "leas-adele",
    "LEAS Allan": "leas-allan",
    "LEASK Chris": "leask-chris",
    "LEASK John": "leask-john",
    "LEASON Barney": "leason-barney",
    "LEASOR James": "leasor-james",
    "LEATHER Nick": "leather-nick",
    "LEATHERS Michael": "leathers-michael",
    "LEAVENGOOD Wm S": "leavengood-wm-s",
    "LEAVENS Nick": "leavens-nick",
    "LEAVER Phillip": "leaver-phillip",
    "LEAVER Sarah": "leaver-sarah",
    "LEAVERTON Lisa": "leaverton-lisa",
    "LEAVESLEY Christian": "leavesley-christian",
    "LEAVINS Chris": "leavins-chris",
    "LEAVITT Amir": "leavitt-amir",
    "LEAVITT Gracie": "leavitt-gracie",
    "LEAVITT Johnny Blaze": "leavitt-johnny-blaze",
    "LEBANK Ezra": "lebank-ezra",
    "LEBARON David": "lebaron-david",
    "LEBBY Marsha": "lebby-marsha",
    "LEBEAU Suzanne": "lebeau-suzanne",
    "LEBENSTRAUM THEATRE GROUP ": "lebenstraum-theatre-group",
    "LEBER Jerry": "leber-jerry",
    "LE-BERT Camila": "le-bert-camila",
    "LEBETKIN Steven": "lebetkin-steven",
    "LEBLANC Daniel J": "leblanc-daniel-j",
    "LEBLANC-CRAWFORD Susan": "leblanc-crawford-susan",
    "LEBOURDAIS Vanessa": "lebourdais-vanessa",
    "LEBOVIC Djordje": "lebovic-djordje",
    "LEBOVICI Jeff": "lebovici-jeff",
    "LEBOVITS Phil": "lebovits-phil",
    "LEBOW Barbara": "lebow-barbara",
    "LECAT Lisette": "lecat-lisette",
    "LECESNE James": "lecesne-james",
    "LECHAY Jo": "lechay-jo",
    "LECHNER Andrea": "lechner-andrea",
    "LECHNER Jack": "lechner-jack",
    "LECHUGA Pablo": "lechuga-pablo",
    "LECIS Lelio": "lecis-lelio",
    "LECLAIR Mick": "leclair-mick",
    "LECLERC Felix": "leclerc-felix",
    "LECOAT Jenny": "lecoat-jenny",
    "LECOQ Jacques": "lecoq-jacques",
    "LECOURAS Peter G": "lecouras-peter-g",
    "LEDDICK David": "leddick-david",
    "LEDDY David": "leddy-david",
    "LEDDY Erin": "leddy-erin",
    "LEDERER Andre": "lederer-andre",
    "LEDERER Charles": "lederer-charles",
    "LEDERER Jenn": "lederer-jenn",
    "LEDERER Michael": "lederer-michael",
    "LEDERER Suzanne": "lederer-suzanne",
    "LEDERMAN Anne": "lederman-anne",
    "LEDERMAN Eve": "lederman-eve",
    "LEDESMA Will": "ledesma-will",
    "LEDGER David": "ledger-david",
    "LEDGERWOOD Mhairi": "ledgerwood-mhairi",
    "LEDINGHAM Rod": "ledingham-rod",
    "LEDOUX Chris": "ledoux-chris",
    "LEDOUX David": "ledoux-david",
    "LEDOUX Paul": "ledoux-paul",
    "LEDWABA John": "ledwaba-john",
    "LEDWICH Anna": "ledwich-anna",
    "LEE Alex": "lee-alex",
    "LEE Alex (1)": "lee-alex-1",
    "LEE Alice": "lee-alice",
    "LEE Amy": "lee-amy",
    "LEE Angela M": "lee-angela-m",
    "LEE Ann": "lee-ann",
    "LEE Annette": "lee-annette",
    "LEE Annie": "lee-annie",
    "LEE Anthony": "lee-anthony",
    "LEE Audrey": "lee-audrey",
    "LEE Bart": "lee-bart",
    "LEE Bernice": "lee-bernice",
    "LEE Bert": "lee-bert",
    "LEE Billy J": "lee-billy-j",
    "LEE Bomi": "lee-bomi",
    "LEE Brandon Marianne": "lee-brandon-marianne",
    "LEE Brandon T": "lee-brandon-t",
    "LEE Brian": "lee-brian",
    "LEE C P": "lee-c-p",
    "LEE C Y": "lee-c-y",
    "LEE Carol": "lee-carol",
    "LEE Caroline": "lee-caroline",
    "LEE Charles": "lee-charles",
    "LEE Cherylene": "lee-cherylene",
    "LEE Chie-Hoon": "lee-chie-hoon",
    "LEE Chris": "lee-chris",
    "LEE Christopher": "lee-christopher",
    "LEE Corolyn": "lee-corolyn",
    "LEE Cynthia Cozette": "lee-cynthia-cozette",
    "LEE David": "lee-david",
    "LEE David (1)": "lee-david-1",
    "LEE David Ian": "lee-david-ian",
    "LEE David Karl": "lee-david-karl",
    "LEE David Lan": "lee-david-lan",
    "LEE Dennis": "lee-dennis",
    "LEE Ed": "lee-ed",
    "LEE Eddie": "lee-eddie",
    "LEE Edward Bok": "lee-edward-bok",
    "LEE Eliaha": "lee-eliaha",
    "LEE Eugene": "lee-eugene",
    "LEE Gerard": "lee-gerard",
    "LEE Gina": "lee-gina",
    "LEE H Fletcher": "lee-h-fletcher",
    "LEE J C": "lee-j-c",
    "LEE James Henry": "lee-james-henry",
    "LEE Jeffrey A": "lee-jeffrey-a",
    "LEE Jennifer": "lee-jennifer",
    "LEE Jenny": "lee-jenny",
    "LEE Ji Hyun": "lee-ji-hyun",
    "LEE Jim": "lee-jim",
    "LEE John": "lee-john",
    "LEE John J F": "lee-john-j-f",
    "LEE John Quincy": "lee-john-quincy",
    "LEE John Rafter": "lee-john-rafter",
    "LEE Jonathan (Jo)": "lee-jonathan",
    "LEE Joyce": "lee-joyce",
    "LEE Jun Bin": "lee-jun-bin",
    "LEE K H": "lee-k-h",
    "LEE Kaiulani": "lee-kaiulani",
    "LEE Kari": "lee-kari",
    "LEE Kathleen": "lee-kathleen",
    "LEE Ken": "lee-ken",
    "LEE Kenneth": "lee-kenneth",
    "LEE Kerry": "lee-kerry",
    "LEE Kevin": "lee-kevin",
    "LEE Kevin L": "lee-kevin-l",
    "LEE Kimber": "lee-kimber",
    "LEE Kirsten": "lee-kirsten",
    "LEE Lance": "lee-lance",
    "LEE Lauren": "lee-lauren",
    "LEE Leslie": "lee-leslie",
    "LEE Levi": "lee-levi",
    "LEE Lisa": "lee-lisa",
    "LEE Maggie": "lee-maggie",
    "LEE Mark": "lee-mark",
    "LEE Mary": "lee-mary",
    "LEE Maryat": "lee-maryat",
    "LEE Maureen": "lee-maureen",
    "LEE May M": "lee-may-m",
    "LEE Melanie N": "lee-melanie-n",
    "LEE Melinda": "lee-melinda",
    "LEE Melissa": "lee-melissa",
    "LEE Michael Justin": "lee-michael-justin",
    "LEE Michele": "lee-michele",
    "LEE Myung-Il": "lee-myung-il",
    "LEE Nathaniel": "lee-nathaniel",
    "LEE Patrick": "lee-patrick",
    "LEE Paul": "lee-paul",
    "LEE Ralph": "lee-ralph",
    "LEE Ray": "lee-ray",
    "LEE Richard": "lee-richard",
    "LEE Rob": "lee-rob",
    "LEE Robert": "lee-robert",
    "LEE Robert C": "lee-robert-c",
    "LEE Robert E": "lee-robert-e",
    "LEE Robert J": "lee-robert-j",
    "LEE Rodney": "lee-rodney",
    "LEE S G": "lee-s-g",
    "LEE Samantha": "lee-samantha",
    "LEE Samira M": "lee-samira-m",
    "LEE Sandra": "lee-sandra",
    "LEE Soo-Jin": "lee-soo-jin",
    "LEE Steven": "lee-steven",
    "LEE Steven (2)": "lee-steven-2",
    "LEE Stuart": "lee-stuart",
    "LEE Suzanne": "lee-suzanne",
    "LEE T K": "lee-t-k",
    "LEE Terry": "lee-terry",
    "LEE Tina": "lee-tina",
    "LEE Tom": "lee-tom",
    "LEE Tracey Conyer": "lee-tracey-conyer",
    "LEE Trisha": "lee-trisha",
    "LEE Wayne C": "lee-wayne-c",
    "LEE Young Jean": "lee-young-jean",
    "LEE Zabra": "lee-zabra",
    "LEE Zach": "lee-zach",
    "LEE & DAWES ": "lee-dawes",
    "LEE BROWN Rachael": "lee-brown-rachael",
    "LEECH Roger": "leech-roger",
    "LEEDES Julie": "leedes-julie",
    "LEEDS Charlie": "leeds-charlie",
    "LEEDS Dorothy": "leeds-dorothy",
    "LEEDS Michael": "leeds-michael",
    "LEEDS Nancy": "leeds-nancy",
    "LEEDS Robert": "leeds-robert",
    "LEEDS Vic": "leeds-vic",
    "LEEDS PLAYHOUSE Tie": "leeds-playhouse-tie",
    "LEEDY Michael": "leedy-michael",
    "LEE-FRENCH Segun": "lee-french-segun",
    "LEE-GAN Chantal": "lee-gan-chantal",
    "LEE-KENNEDY Brydie": "lee-kennedy-brydie",
    "LEEMAN Dane": "leeman-dane",
    "LEEMING Carol": "leeming-carol",
    "LEEMING Owen": "leeming-owen",
    "LEEN Gwen": "leen-gwen",
    "LEEPER David": "leeper-david",
    "LEEPER Paul": "leeper-paul",
    "LEE-REKERS Alexander": "lee-rekers-alexander",
    "LEES David G": "lees-david-g",
    "LEES Gilian": "lees-gilian",
    "LEES Harold P": "lees-harold-p",
    "LEES Julie": "lees-julie",
    "LEES Richard": "lees-richard",
    "LEES Rob": "lees-rob",
    "LEES Russell": "lees-russell",
    "LEES-BLAKEY Dorothy": "lees-blakey-dorothy",
    "LEESE Joan": "leese-joan",
    "LEESON George": "leeson-george",
    "LEESON Michael": "leeson-michael",
    "LEESON Sylvia": "leeson-sylvia",
    "LEE-YANG May": "lee-yang-may",
    "LEF Last": "lef-last",
    "LEFAS Dianna": "lefas-dianna",
    "LEFCOURT Peter": "lefcourt-peter",
    "LEFCOWITZ Al": "lefcowitz-al",
    "LEFCOWITZ Allan": "lefcowitz-allan",
    "LEFEBVRE Dennis": "lefebvre-dennis",
    "LEFEBVRE Phillipe": "lefebvre-phillipe",
    "LEFER Diane": "lefer-diane",
    "LEFEVRE Adam": "lefevre-adam",
    "LEFFERTS George": "lefferts-george",
    "LEFFLER-MCCABE Laura": "leffler-mccabe-laura",
    "LEFKOW Jessica": "lefkow-jessica",
    "LEFKOWITZ Allen": "lefkowitz-allen",
    "LEFKOWITZ David": "lefkowitz-david",
    "LEFKOWITZ Joni": "lefkowitz-joni",
    "LEFKOWITZ Josh": "lefkowitz-josh",
    "LEFRANC Dan": "lefranc-dan",
    "LEFTCOURT Peter": "leftcourt-peter",
    "LEFTER Anne M": "lefter-anne-m",
    "LEGAAN Kira": "legaan-kira",
    "LEGACY C S": "legacy-c-s",
    "LEGAT Michael": "legat-michael",
    "LEGAULT Anne": "legault-anne",
    "LEGAULT Gary": "legault-gary",
    "LEGAULT Greg": "legault-greg",
    "LEGENDRE Thomas": "legendre-thomas",
    "LEGERE Stewart": "legere-stewart",
    "LEGG Rodney": "legg-rodney",
    "LEGGE Felix": "legge-felix",
    "LEGGE Michael": "legge-michael",
    "LEGGE Sonia": "legge-sonia",
    "LEGGETT Dominic": "leggett-dominic",
    "LEGGETT Frank": "leggett-frank",
    "LEGGE-WILKINSON Jacinta": "legge-wilkinson-jacinta",
    "LEGHORN V B": "leghorn-v-b",
    "LEGRAND Celia": "legrand-celia",
    "LEGRAND Michel": "legrand-michel",
    "LEGRANT Ashly": "legrant-ashly",
    "LEGS ON THE WALL ": "legs-on-the-wall",
    "LEGUIZAMO John": "leguizamo-john",
    "LEHAN Robert": "lehan-robert",
    "LEHANE Dennis": "lehane-dennis",
    "LEHAV Amit": "lehav-amit",
    "LEHMAN Adam": "lehman-adam",
    "LEHMAN Adam (2)": "lehman-adam-2",
    "LEHMAN Ben": "lehman-ben",
    "LEHMAN Jessica": "lehman-jessica",
    "LEHMAN Leo": "lehman-leo",
    "LEHMAN Linda": "lehman-linda",
    "LEHMAN Lucas Roy": "lehman-lucas-roy",
    "LEHMAN Luke": "lehman-luke",
    "LEHMAN Sarah": "lehman-sarah",
    "LEHMANN Harold": "lehmann-harold",
    "LEHMANN Maria": "lehmann-maria",
    "LEHMANN Stephanie": "lehmann-stephanie",
    "LEHMKUHL Vance": "lehmkuhl-vance",
    "LEHNHOFF Allie": "lehnhoff-allie",
    "LEHRER Jim": "lehrer-jim",
    "LEHRER Steven": "lehrer-steven",
    "LEHRMAN Olivia": "lehrman-olivia",
    "LEIB Mark": "leib-mark",
    "LEIB Russell": "leib-russell",
    "LEIB Ted": "leib-ted",
    "LEIBER Jerry": "leiber-jerry",
    "LEIBERMAN Douglas L": "leiberman-douglas-l",
    "LEIBMAN Steve": "leibman-steve",
    "LEICESTER Chris": "leicester-chris",
    "LEICHMAN Seymour": "leichman-seymour",
    "LEICHT Allan": "leicht-allan",
    "LEICHT Michael": "leicht-michael",
    "LEICHT Michael (1)": "leicht-michael-1",
    "LEICHTER Aaron": "leichter-aaron",
    "LEICHTER Hilary Jess": "leichter-hilary-jess",
    "LEICHTER Nicholas": "leichter-nicholas",
    "LEICHTMAN David": "leichtman-david",
    "LEICHTY Christy": "leichty-christy",
    "LEIDENFROST-WILSON Rick": "leidenfrost-wilson-rick",
    "LEIDER Brian": "leider-brian",
    "LEIDER Justin": "leider-justin",
    "LEIDY Alex": "leidy-alex",
    "LEIF Dan": "leif-dan",
    "LEIGH Alan": "leigh-alan",
    "LEIGH Andrew": "leigh-andrew",
    "LEIGH Bianca": "leigh-bianca",
    "LEIGH Carolyn": "leigh-carolyn",
    "LEIGH Eve": "leigh-eve",
    "LEIGH M Simon": "leigh-m-simon",
    "LEIGH Maria": "leigh-maria",
    "LEIGH Michele": "leigh-michele",
    "LEIGH Mike": "leigh-mike",
    "LEIGH Mitch": "leigh-mitch",
    "LEIGH Nathan": "leigh-nathan",
    "LEIGH Paul": "leigh-paul",
    "LEIGH Philip": "leigh-philip",
    "LEIGH Rowland": "leigh-rowland",
    "LEIGH Roy": "leigh-roy",
    "LEIGH Sylvia": "leigh-sylvia",
    "LEIGHT Warren": "leight-warren",
    "LEIGHTON Maxinne R": "leighton-maxinne-r",
    "LEIGHTON Richard": "leighton-richard",
    "LEIGHTON William": "leighton-william",
    "LEIGHTON-POPE Carl": "leighton-pope-carl",
    "LEIKE Keira": "leike-keira",
    "LEIMAN Brad": "leiman-brad",
    "LEIMAN Rose Leiman": "leiman-rose-leiman",
    "LEIN Beth": "lein-beth",
    "LEIPACHER Mark": "leipacher-mark",
    "LEIPART Charles": "leipart-charles",
    "LEIPZIG Adam": "leipzig-adam",
    "LEIREN-YOUNG Mark": "leiren-young-mark",
    "LEISER-MOORE Deborah": "leiser-moore-deborah",
    "LEISEWITZ Johann Anton": "leisewitz-johann-anton",
    "LEISTEN Annette": "leisten-annette",
    "LEITE Ashleigh": "leite-ashleigh",
    "LEITH Christopher": "leith-christopher",
    "LEITMAN Margot": "leitman-margot",
    "LEIVA Steven Paul": "leiva-steven-paul",
    "LEIVICK H": "leivick-h",
    "LEKAN William": "lekan-william",
    "LELISI Shimpal": "lelisi-shimpal",
    "LELLO Beverley": "lello-beverley",
    "LEMAITRE Corene": "lemaitre-corene",
    "LEMASTER David J": "lemaster-david-j",
    "LEMAY Bonnie": "lemay-bonnie",
    "LEMAY Harding": "lemay-harding",
    "LEMAY Stephen": "lemay-stephen",
    "LEMBERG David": "lemberg-david",
    "LEMBKE Janet": "lembke-janet",
    "LEMIEUX Pierre Yves": "lemieux-pierre-yves",
    "LEMKOW Tutte": "lemkow-tutte",
    "LEMME Mike": "lemme-mike",
    "LEMOINE Greg": "lemoine-greg",
    "LEMOINE Jo": "lemoine-jo",
    "LEMOINE Stewart": "lemoine-stewart",
    "LEMON Andrea": "lemon-andrea",
    "LEMON Nina": "lemon-nina",
    "LEMON Ralph": "lemon-ralph",
    "LEMON Spud": "lemon-spud",
    "LEMON Wayne": "lemon-wayne",
    "LEMONDE Connie": "lemonde-connie",
    "LEMOS David": "lemos-david",
    "LEMPER Ute": "lemper-ute",
    "LEMPERT Carol": "lempert-carol",
    "LEN Daniel": "len-daniel",
    "LENESKIE-KOTTE Lea": "leneskie-kotte-lea",
    "LENGEL Brenton": "lengel-brenton",
    "LENGELLE Reinekke": "lengelle-reinekke",
    "LENGFELDER Bill": "lengfelder-bill",
    "LENGSFELDER H J": "lengsfelder-h-j",
    "LENGYEL Melchior": "lengyel-melchior",
    "LENHARD Gabrielle": "lenhard-gabrielle",
    "LENIER Sue": "lenier-sue",
    "LENKIEWICZ Rebecca": "lenkiewicz-rebecca",
    "LENMART Isobel": "lenmart-isobel",
    "LENNIE David": "lennie-david",
    "LENNON Del": "lennon-del",
    "LENNON Gary": "lennon-gary",
    "LENNON John": "lennon-john",
    "LENNON Mattie": "lennon-mattie",
    "LENOIRE Rosetta": "lenoire-rosetta",
    "LENORMAND Henry Rene": "lenormand-henry-rene",
    "LENSKI Sophie": "lenski-sophie",
    "LENTINI Liza": "lentini-liza",
    "LENTON Matthew": "lenton-matthew",
    "LENTON Patrick": "lenton-patrick",
    "LENTS Stacie": "lents-stacie",
    "LENTZ David B": "lentz-david-b",
    "LENTZ Martin Rowe": "lentz-martin-rowe",
    "LENZ Jacob": "lenz-jacob",
    "LENZ Richard": "lenz-richard",
    "LENZI Gail": "lenzi-gail",
    "LENZI Paul": "lenzi-paul",
    "LEO Carl": "leo-carl",
    "LEO Jean": "leo-jean",
    "LEO Joe": "leo-joe",
    "LEO John": "leo-john",
    "LEO Katie": "leo-katie",
    "LEO Okko": "leo-okko",
    "LEO Trisha": "leo-trisha",
    "LEOKUM Arkady": "leokum-arkady",
    "LEON Federico": "leon-federico",
    "LEON Felix": "leon-felix",
    "LEON Mike": "leon-mike",
    "LEON HILL Gary": "leon-hill-gary",
    "LEONARD Alison": "leonard-alison",
    "LEONARD Andy": "leonard-andy",
    "LEONARD Brett C": "leonard-brett-c",
    "LEONARD Hugh": "leonard-hugh",
    "LEONARD Jim": "leonard-jim",
    "LEONARD Joann": "leonard-joann",
    "LEONARD Kevin": "leonard-kevin",
    "LEONARD Kevin (2)": "leonard-kevin-2",
    "LEONARD Libby": "leonard-libby",
    "LEONARD Luke Landric": "leonard-luke-landric",
    "LEONARD Mark": "leonard-mark",
    "LEONARD Rebecca": "leonard-rebecca",
    "LEONARD Russell": "leonard-russell",
    "LEONARD Susan": "leonard-susan",
    "LEONARD Tom": "leonard-tom",
    "LEONARD W Keith": "leonard-w-keith",
    "LEONARD Wayne": "leonard-wayne",
    "LEONARD JR Jim": "leonard-jr-jim",
    "LEONARD, JR Donald": "leonard-donald",
    "LEONARDI Simon": "leonardi-simon",
    "LEONARDO Joe": "leonardo-joe",
    "LEONCAVALLO Ruggero": "leoncavallo-ruggero",
    "LEONG Julian": "leong-julian",
    "LEONG Page": "leong-page",
    "LEONI Michael": "leoni-michael",
    "LEONI Victor": "leoni-victor",
    "LEONTOVICH Eugenie": "leontovich-eugenie",
    "LEOPOLD Lizzie": "leopold-lizzie",
    "LEOPOLD Tom": "leopold-tom",
    "LEORA Judith": "leora-judith",
    "LEPAGE Gordon": "lepage-gordon",
    "LEPAGE Pete": "lepage-pete",
    "LEPAGE Robert": "lepage-robert",
    "LEPCIO Andrea": "lepcio-andrea",
    "LEPENDORF Jeffrey": "lependorf-jeffrey",
    "LEPINE Kristen": "lepine-kristen",
    "LEPORE Rachel": "lepore-rachel",
    "LEPORE Seth": "lepore-seth",
    "LEPPAJARVI Juha": "leppajarvi-juha",
    "LEPPARD Meryl": "leppard-meryl",
    "LEPPER John": "lepper-john",
    "LEPRE Todd": "lepre-todd",
    "LERET Xavier": "leret-xavier",
    "LERMAN Adam": "lerman-adam",
    "LERMAN Lior": "lerman-lior",
    "LERMAN Liz": "lerman-liz",
    "LERMAN Peter": "lerman-peter",
    "LERMAN Rebecca Lee": "lerman-rebecca-lee",
    "LERMAN Rhoda": "lerman-rhoda",
    "LERMOND Vivian C": "lermond-vivian-c",
    "LERMONTOV Mikhail": "lermontov-mikhail",
    "LERNER Alan Jay": "lerner-alan-jay",
    "LERNER Elissa": "lerner-elissa",
    "LERNER Ellyn Gersh": "lerner-ellyn-gersh",
    "LERNER Erwin H": "lerner-erwin-h",
    "LERNER Harold": "lerner-harold",
    "LERNER Motti": "lerner-motti",
    "LERNER Neal": "lerner-neal",
    "LERNER Robin": "lerner-robin",
    "LERNER Samuel M": "lerner-samuel-m",
    "LERNER-LEY Rachel": "lerner-ley-rachel",
    "LEROUX Louis Patrick": "leroux-louis-patrick",
    "LEROY Gen": "leroy-gen",
    "LEROY Leslie (Hurley)": "leroy-leslie",
    "LERRIGO Charley": "lerrigo-charley",
    "LERYCH Lynne": "lerych-lynne",
    "LES COUSINS ": "les-cousins",
    "LES PETITS ": "les-petits",
    "LESAGE Alain-Rene": "lesage-alain-rene",
    "LESCA Bertrand": "lesca-bertrand",
    "LESCHEN Paul": "leschen-paul",
    "LESCHIN Louisa": "leschin-louisa",
    "LESCOT David": "lescot-david",
    "LESEMANN Mara": "lesemann-mara",
    "LESHI Nick": "leshi-nick",
    "LESLEE Ray": "leslee-ray",
    "LESLEY Caroline": "lesley-caroline",
    "LESLEY Katherine Jean": "lesley-katherine-jean",
    "LESLIE Aleen": "leslie-aleen",
    "LESLIE Deborah": "leslie-deborah",
    "LESLIE Diane": "leslie-diane",
    "LESLIE Dudley": "leslie-dudley",
    "LESLIE Eddie": "leslie-eddie",
    "LESLIE F Andrew": "leslie-f-andrew",
    "LESLIE Karani Marcia": "leslie-karani-marcia",
    "LESLIE Lew": "leslie-lew",
    "LESLIE Marcia L": "leslie-marcia-l",
    "LESLIE Michael": "leslie-michael",
    "LESLIE Struan": "leslie-struan",
    "LESLIE-PELECKY Diandra": "leslie-pelecky-diandra",
    "LESNIEWSKI Victor": "lesniewski-victor",
    "LESOINE Robert E": "lesoine-robert-e",
    "LESS Jerry": "less-jerry",
    "LESS IS MORE ": "less-is-more",
    "LESSAC Michael": "lessac-michael",
    "LESSER Anton": "lesser-anton",
    "LESSER Felice": "lesser-felice",
    "LESSER Gene": "lesser-gene",
    "LESSER Mike": "lesser-mike",
    "LESSER Robert Coleman": "lesser-robert-coleman",
    "LESSER Tony": "lesser-tony",
    "LESSING Doris": "lessing-doris",
    "LESSING Gotthold Ephraim": "lessing-gotthold-ephraim",
    "LESSING Mary-Alice": "lessing-mary-alice",
    "LESSING Norman": "lessing-norman",
    "LESSLIE Michael": "lesslie-michael",
    "LESSNER Joanne Sydney": "lessner-joanne-sydney",
    "LESSOF-GENDLER Noa": "lessof-gendler-noa",
    "LESTER Gideon": "lester-gideon",
    "LESTER Howard": "lester-howard",
    "LESTER Marilyn": "lester-marilyn",
    "LESY Nadia": "lesy-nadia",
    "LETCH Jessica": "letch-jessica",
    "LETCHER Marshaline": "letcher-marshaline",
    "LETELLIER Lauren": "letellier-lauren",
    "LETEN Nicolaas": "leten-nicolaas",
    "LETHBRIDGE Nemone": "lethbridge-nemone",
    "LETHORN Tim": "lethorn-tim",
    "LETIEN Katie": "letien-katie",
    "LETIZIA Ryan": "letizia-ryan",
    "LETOURNEAU Francois": "letourneau-francois",
    "LETSON Al": "letson-al",
    "LETTAU Reinhard": "lettau-reinhard",
    "LETTE Kathy": "lette-kathy",
    "LETTICH Sheldon": "lettich-sheldon",
    "LETTON Francis": "letton-francis",
    "LETTON Jenette": "letton-jenette",
    "LETTRE Peter": "lettre-peter",
    "LETTS Tracy": "letts-tracy",
    "LETTUNICH Mateo": "lettunich-mateo",
    "LETWIN Kat": "letwin-kat",
    "LEUNG Cynthia": "leung-cynthia",
    "LEUSER Eleanor D": "leuser-eleanor-d",
    "LEVASSEUR Joe": "levasseur-joe",
    "LEVASSEUR Will": "levasseur-will",
    "LEVEAUX David": "leveaux-david",
    "LEVEL Maurice": "level-maurice",
    "LEVELS Calvin": "levels-calvin",
    "LEVEN Jeremy": "leven-jeremy",
    "LEVENBERG Mitch": "levenberg-mitch",
    "LEVENDORF E O": "levendorf-e-o",
    "LEVENDOSKY Dara M": "levendosky-dara-m",
    "LEVENE Philip": "levene-philip",
    "LEVENSHUS Samantha": "levenshus-samantha",
    "LEVENSON Mark": "levenson-mark",
    "LEVENSON Steven": "levenson-steven",
    "LEVENTMAN Aaron": "leventman-aaron",
    "LEVER Walter": "lever-walter",
    "LEVER Yasmine": "lever-yasmine",
    "LEVERSHA Pam": "leversha-pam",
    "LEVESON Brian": "leveson-brian",
    "LEVESQUE Michael": "levesque-michael",
    "LEVETT Lyn": "levett-lyn",
    "LEVEY Barry": "levey-barry",
    "LEVI Amir": "levi-amir",
    "LEVI Kenneth": "levi-kenneth",
    "LEVI Stephen": "levi-stephen",
    "LEVI Steven": "levi-steven",
    "LEVIN Charlie": "levin-charlie",
    "LEVIN D B": "levin-d-b",
    "LEVIN Daniel Frederick": "levin-daniel-frederick",
    "LEVIN David": "levin-david",
    "LEVIN Elizabeth": "levin-elizabeth",
    "LEVIN Hanoch": "levin-hanoch",
    "LEVIN Hillel": "levin-hillel",
    "LEVIN Ira": "levin-ira",
    "LEVIN Jack P": "levin-jack-p",
    "LEVIN Jay": "levin-jay",
    "LEVIN John": "levin-john",
    "LEVIN John Freeman": "levin-john-freeman",
    "LEVIN Jon": "levin-jon",
    "LEVIN Kendra": "levin-kendra",
    "LEVIN Kim": "levin-kim",
    "LEVIN Lissa": "levin-lissa",
    "LEVIN Maggie": "levin-maggie",
    "LEVIN Meyer": "levin-meyer",
    "LEVIN Reid": "levin-reid",
    "LEVINE Abbe M": "levine-abbe-m",
    "LEVINE Art": "levine-art",
    "LEVINE Barry I": "levine-barry-i",
    "LEVINE David": "levine-david",
    "LEVINE David I": "levine-david-i",
    "LEVINE Emily": "levine-emily",
    "LEVINE Gene": "levine-gene",
    "LEVINE Gregory": "levine-gregory",
    "LEVINE Hanoch": "levine-hanoch",
    "LEVINE Jennifer": "levine-jennifer",
    "LEVINE Jes": "levine-jes",
    "LEVINE John": "levine-john",
    "LEVINE Jory": "levine-jory",
    "LEVINE Josh": "levine-josh",
    "LEVINE Joshua": "levine-joshua",
    "LEVINE Justin": "levine-justin",
    "LEVINE Ken": "levine-ken",
    "LEVINE Mark": "levine-mark",
    "LEVINE Mark Harvey": "levine-mark-harvey",
    "LEVINE Max": "levine-max",
    "LEVINE Mike": "levine-mike",
    "LEVINE Paul": "levine-paul",
    "LEVINE Peter": "levine-peter",
    "LEVINE Rachel": "levine-rachel",
    "LEVINE Richard N": "levine-richard-n",
    "LEVINE Ross M": "levine-ross-m",
    "LEVINE Sara": "levine-sara",
    "LEVINE Simmie": "levine-simmie",
    "LEVINE Stanley": "levine-stanley",
    "LEVINGSTON Steven": "levingston-steven",
    "LEVINSKY Rene": "levinsky-rene",
    "LEVINSON Alfred": "levinson-alfred",
    "LEVINSON Barry": "levinson-barry",
    "LEVINSON Blake": "levinson-blake",
    "LEVINSON Bonnie": "levinson-bonnie",
    "LEVINSON Brad": "levinson-brad",
    "LEVINSON Dana": "levinson-dana",
    "LEVINSON David": "levinson-david",
    "LEVINSON Leonard Louis": "levinson-leonard-louis",
    "LEVINSON Martin": "levinson-martin",
    "LEVINSON Maurice": "levinson-maurice",
    "LEVINSON Richard": "levinson-richard",
    "LEVINSON Suzanne": "levinson-suzanne",
    "LEVINTON Michael": "levinton-michael",
    "LEVIS Melissa": "levis-melissa",
    "LEVIS Tajlei": "levis-tajlei",
    "LEVIS Walter B": "levis-walter-b",
    "LEVISON Jenny": "levison-jenny",
    "LEVISON Martin": "levison-martin",
    "LEVISON Richard": "levison-richard",
    "LEVITICUS Louis I": "leviticus-louis-i",
    "LEVITIN Jerry": "levitin-jerry",
    "LEVITIN Sonia": "levitin-sonia",
    "LEVITSKY Howard": "levitsky-howard",
    "LEVITSKY Melinia": "levitsky-melinia",
    "LEVITT Alan J": "levitt-alan-j",
    "LEVITT Gene": "levitt-gene",
    "LEVITT Saul": "levitt-saul",
    "LEVITZ Eric": "levitz-eric",
    "LEVKOWICZ Valentina": "levkowicz-valentina",
    "LEVOWITZ Adam": "levowitz-adam",
    "LEVOY Myron": "levoy-myron",
    "LEVY Aaron": "levy-aaron",
    "LEVY Aaron Wigdor": "levy-aaron-wigdor",
    "LEVY Alicia": "levy-alicia",
    "LEVY Annie G": "levy-annie-g",
    "LEVY Barry": "levy-barry",
    "LEVY Benn W": "levy-benn-w",
    "LEVY Daniel": "levy-daniel",
    "LEVY David": "levy-david",
    "LEVY Deborah": "levy-deborah",
    "LEVY Ed": "levy-ed",
    "LEVY Eric": "levy-eric",
    "LEVY Frederick": "levy-frederick",
    "LEVY Hector": "levy-hector",
    "LEVY Jacques": "levy-jacques",
    "LEVY James": "levy-james",
    "LEVY Jeff": "levy-jeff",
    "LEVY John": "levy-john",
    "LEVY Jonathan": "levy-jonathan",
    "LEVY Lindsay": "levy-lindsay",
    "LEVY Lisa": "levy-lisa",
    "LEVY Lorraine": "levy-lorraine",
    "LEVY Marianne": "levy-marianne",
    "LEVY Maya": "levy-maya",
    "LEVY Meredith Dayna": "levy-meredith-dayna",
    "LEVY Mike": "levy-mike",
    "LEVY Nyla": "levy-nyla",
    "LEVY Parke": "levy-parke",
    "LEVY Peter": "levy-peter",
    "LEVY Robert Gerald": "levy-robert-gerald",
    "LEVY Ronna": "levy-ronna",
    "LEVY Simon": "levy-simon",
    "LEVY Simona": "levy-simona",
    "LEVY-TANAY Sara": "levy-tanay-sara",
    "LEW Andy": "lew-andy",
    "LEW Bevan": "lew-bevan",
    "LEW Kimberly": "lew-kimberly",
    "LEW Mike": "lew-mike",
    "LEWANDOWSKI Sheila": "lewandowski-sheila",
    "LEWELLEN Faye": "lewellen-faye",
    "LEWENSTEIN Rose": "lewenstein-rose",
    "LEWER Steven": "lewer-steven",
    "LEWIN Alex": "lewin-alex",
    "LEWIN Earl": "lewin-earl",
    "LEWIN Eva": "lewin-eva",
    "LEWIN J": "lewin-j",
    "LEWIN John": "lewin-john",
    "LEWIS Alana B": "lewis-alana-b",
    "LEWIS Ali": "lewis-ali",
    "LEWIS Allan": "lewis-allan",
    "LEWIS Allen Jack": "lewis-allen-jack",
    "LEWIS Alwyn D": "lewis-alwyn-d",
    "LEWIS Amy": "lewis-amy",
    "LEWIS Ben": "lewis-ben",
    "LEWIS Benjamin": "lewis-benjamin",
    "LEWIS Berwyn": "lewis-berwyn",
    "LEWIS Bethan": "lewis-bethan",
    "LEWIS Caleb": "lewis-caleb",
    "LEWIS Carter W": "lewis-carter-w",
    "LEWIS Cassandra": "lewis-cassandra",
    "LEWIS Chad": "lewis-chad",
    "LEWIS Cole": "lewis-cole",
    "LEWIS Cynthia Louise": "lewis-cynthia-louise",
    "LEWIS David": "lewis-david",
    "LEWIS David (1)": "lewis-david-1",
    "LEWIS David (2)": "lewis-david-2",
    "LEWIS Dianna A": "lewis-dianna-a",
    "LEWIS Donald": "lewis-donald",
    "LEWIS Drew": "lewis-drew",
    "LEWIS E M": "lewis-e-m",
    "LEWIS Eduard": "lewis-eduard",
    "LEWIS Edwin": "lewis-edwin",
    "LEWIS Elizabeth": "lewis-elizabeth",
    "LEWIS Ellen": "lewis-ellen",
    "LEWIS Emily": "lewis-emily",
    "LEWIS Emsley Clair": "lewis-emsley-clair",
    "LEWIS Erica": "lewis-erica",
    "LEWIS Eve": "lewis-eve",
    "LEWIS F": "lewis-f",
    "LEWIS Georgina": "lewis-georgina",
    "LEWIS Geraint": "lewis-geraint",
    "LEWIS Greg": "lewis-greg",
    "LEWIS Gwyneth": "lewis-gwyneth",
    "LEWIS Hal": "lewis-hal",
    "LEWIS Helena D": "lewis-helena-d",
    "LEWIS Henry": "lewis-henry",
    "LEWIS Holly": "lewis-holly",
    "LEWIS Ian": "lewis-ian",
    "LEWIS Imani": "lewis-imani",
    "LEWIS Ira": "lewis-ira",
    "LEWIS Izzy": "lewis-izzy",
    "LEWIS James": "lewis-james",
    "LEWIS Jason-Edward": "lewis-jason-edward",
    "LEWIS Jenny": "lewis-jenny",
    "LEWIS Jessica": "lewis-jessica",
    "LEWIS Jim": "lewis-jim",
    "LEWIS John": "lewis-john",
    "LEWIS Jonathan": "lewis-jonathan",
    "LEWIS Jonathan Guy": "lewis-jonathan-guy",
    "LEWIS Julia": "lewis-julia",
    "LEWIS Julia Rose": "lewis-julia-rose",
    "LEWIS Julie": "lewis-julie",
    "LEWIS Justin": "lewis-justin",
    "LEWIS Karen L": "lewis-karen-l",
    "LEWIS Kevin": "lewis-kevin",
    "LEWIS L Susan": "lewis-l-susan",
    "LEWIS Leopold": "lewis-leopold",
    "LEWIS Leslie Christine": "lewis-leslie-christine",
    "LEWIS Lisa": "lewis-lisa",
    "LEWIS Lloyd": "lewis-lloyd",
    "LEWIS Louise": "lewis-louise",
    "LEWIS M E H": "lewis-m-e-h",
    "LEWIS Marilyn": "lewis-marilyn",
    "LEWIS Matt": "lewis-matt",
    "LEWIS Michael": "lewis-michael",
    "LEWIS Michael J": "lewis-michael-j",
    "LEWIS Mort": "lewis-mort",
    "LEWIS Neal Alexander": "lewis-neal-alexander",
    "LEWIS Nicole": "lewis-nicole",
    "LEWIS Paul": "lewis-paul",
    "LEWIS Peter": "lewis-peter",
    "LEWIS Philip C": "lewis-philip-c",
    "LEWIS Preston": "lewis-preston",
    "LEWIS Richard": "lewis-richard",
    "LEWIS Richard (1)": "lewis-richard-1",
    "LEWIS Rick": "lewis-rick",
    "LEWIS Rita": "lewis-rita",
    "LEWIS Robert Joseph": "lewis-robert-joseph",
    "LEWIS Roy Harley": "lewis-roy-harley",
    "LEWIS Russell": "lewis-russell",
    "LEWIS Saunders": "lewis-saunders",
    "LEWIS Sean Christopher": "lewis-sean-christopher",
    "LEWIS Sean Edward": "lewis-sean-edward",
    "LEWIS Sharon": "lewis-sharon",
    "LEWIS Sinclair": "lewis-sinclair",
    "LEWIS Stephen": "lewis-stephen",
    "LEWIS Stephen (1)": "lewis-stephen-1",
    "LEWIS Stephen (2)": "lewis-stephen-2",
    "LEWIS Steve": "lewis-steve",
    "LEWIS Tom E": "lewis-tom-e",
    "LEWIS Tony": "lewis-tony",
    "LEWIS Victoria Ann": "lewis-victoria-ann",
    "LEWIS Walt": "lewis-walt",
    "LEWIS Wiliam R": "lewis-wiliam-r",
    "LEWIS William": "lewis-william",
    "LEWIS William H": "lewis-william-h",
    "LEWIS William R": "lewis-william-r",
    "LEWIS Zoe": "lewis-zoe",
    "LEWIS III Charles": "lewis-iii-charles",
    "LEWIS-BARR Laura": "lewis-barr-laura",
    "LEWISON David": "lewison-david",
    "LEWIS-SMITH Lachlan": "lewis-smith-lachlan",
    "LEWIS-THOMAS Annemarie": "lewis-thomas-annemarie",
    "LEWIT Marge": "lewit-marge",
    "LEWKOWICZ K S": "lewkowicz-k-s",
    "LEWMAN Dave": "lewman-dave",
    "LEWONCZYK Jeff": "lewonczyk-jeff",
    "LEWSON Charles": "lewson-charles",
    "LEWTER John": "lewter-john",
    "LEWTON Martin": "lewton-martin",
    "LEWTON Randall": "lewton-randall",
    "LEWY Walter": "lewy-walter",
    "LEXEN Tommy": "lexen-tommy",
    "LEY Deborah": "ley-deborah",
    "LEY Duncan": "ley-duncan",
    "LEY James": "ley-james",
    "LEY Pablo": "ley-pablo",
    "LEY Stephen": "ley-stephen",
    "LEYDORF Mark": "leydorf-mark",
    "LEYGNAC Philippe": "leygnac-philippe",
    "LEYIN John": "leyin-john",
    "LEYLAND Bruce": "leyland-bruce",
    "LEYLAND Corey": "leyland-corey",
    "LEYLAND David": "leyland-david",
    "LEYRA Ignacio Pajon": "leyra-ignacio-pajon",
    "LEYS Bryan D": "leys-bryan-d",
    "LEYSER Jules": "leyser-jules",
    "LEYSER Matilda": "leyser-matilda",
    "LEYSHON Nell": "leyshon-nell",
    "LEYTON Dominic": "leyton-dominic",
    "LEYTON Matthew": "leyton-matthew",
    "LEYVA Chris": "leyva-chris",
    "LEYVA Humberto": "leyva-humberto",
    "LEYVA Lucas": "leyva-lucas",
    "LEZNOFF Glenda": "leznoff-glenda"
  }
};