export default {
  "metadata": {
    "results": 425,
    "timeStamp": "2025-12-05T21:27:12.470Z",
    "url": "https://www.doollee.com/PlaywrightsL/L_playwrights_g-l.php"
  },
  "authors": {
    "LHOTA Barbara": "lhota-barbara",
    "LI Anna": "li-anna",
    "LI Jennifer": "li-jennifer",
    "LI Melissa": "li-melissa",
    "LI Yan": "li-yan",
    "LIADSKY Jessica": "liadsky-jessica",
    "LIANG Elisabeth": "liang-elisabeth",
    "LIANG Rennee": "liang-rennee",
    "LIANG West": "liang-west",
    "LIAO Angela": "liao-angela",
    "LIAUTAUD Leslie": "liautaud-leslie",
    "LIBBOTT Robert Yale": "libbott-robert-yale",
    "LIBBY Heather": "libby-heather",
    "LIBER Vera": "liber-vera",
    "LIBERA Antoni": "libera-antoni",
    "LIBERIS Emily Kaye": "liberis-emily-kaye",
    "LIBERMAN Judith Weinshall": "liberman-judith-weinshall",
    "LIBERTI Louie": "liberti-louie",
    "LIBERTY Anita": "liberty-anita",
    "LIBII Kobi": "libii-kobi",
    "LIBIN Barry M": "libin-barry-m",
    "LIBINATI Allegra": "libinati-allegra",
    "LIBMAN Carol": "libman-carol",
    "LIBMAN Daniel": "libman-daniel",
    "LIBMAN Jonathan David": "libman-jonathan-david",
    "LIBMAN Paul": "libman-paul",
    "LIBRETTO Chas": "libretto-chas",
    "LIBRIZZI Andrew": "librizzi-andrew",
    "LICASTRI Michael": "licastri-michael",
    "LICATA Matt": "licata-matt",
    "LICATA Tim": "licata-tim",
    "LICATA Vince": "licata-vince",
    "LICEDEI MINUS 4 ": "licedei-minus-4",
    "LICHA Marian": "licha-marian",
    "LICHT David": "licht-david",
    "LICHTBLAU Lucile": "lichtblau-lucile",
    "LICHTENSTEIN Jonathan": "lichtenstein-jonathan",
    "LICHTER Morton": "lichter-morton",
    "LICHTI Joanne": "lichti-joanne",
    "LICHTIG Robin Rice": "lichtig-robin-rice",
    "LICHTMAN-FIELDS Myla": "lichtman-fields-myla",
    "LICHTWAR Nathan": "lichtwar-nathan",
    "LICHWICK Marissa": "lichwick-marissa",
    "LICWINKO Michael": "licwinko-michael",
    "LIDDELL Angelica": "liddell-angelica",
    "LIDDELL Janice": "liddell-janice",
    "LIDDELLE Vicki": "liddelle-vicki",
    "LIDINGTON Tony": "lidington-tony",
    "LIDSKY Katya": "lidsky-katya",
    "LIDSTROM Lennart": "lidstrom-lennart",
    "LIE Swedian": "lie-swedian",
    "LIEB Mark": "lieb-mark",
    "LIEBER Molly": "lieber-molly",
    "LIEBERMAN Edith": "lieberman-edith",
    "LIEBERMAN Ernest David": "lieberman-ernest-david",
    "LIEBERMAN Hal": "lieberman-hal",
    "LIEBERMAN Harold": "lieberman-harold",
    "LIEBERMAN Harvey": "lieberman-harvey",
    "LIEBERMAN Jennifer": "lieberman-jennifer",
    "LIEBERMAN Susan": "lieberman-susan",
    "LIEBERMAN Tyler": "lieberman-tyler",
    "LIEBESKIND Arthur S": "liebeskind-arthur-s",
    "LIEBLER Paul": "liebler-paul",
    "LIEBLICH Jerry": "lieblich-jerry",
    "LIEBMAN Max": "liebman-max",
    "LIEBMAN Steve": "liebman-steve",
    "LIEBMAN Wayne Peter": "liebman-wayne-peter",
    "LIEBOWITZ Robert": "liebowitz-robert",
    "LIEBRECHT Savyon": "liebrecht-savyon",
    "LIEDLE Richard": "liedle-richard",
    "LIEDTKE Tanja": "liedtke-tanja",
    "LIEND Jeremiah": "liend-jeremiah",
    "LIEPE-LEVINSON Katherine": "liepe-levinson-katherine",
    "LIEPMANN Lise": "liepmann-lise",
    "LIEPOLT Werner": "liepolt-werner",
    "LIEU Chi": "lieu-chi",
    "LIEVE Cesare": "lieve-cesare",
    "LIEVONEN Sari": "lievonen-sari",
    "LIEWINKO Michael": "liewinko-michael",
    "LIFSCHITZ Marvin": "lifschitz-marvin",
    "LIFSON David": "lifson-david",
    "LIFTON Barbara": "lifton-barbara",
    "LIFTON Betty Jean": "lifton-betty-jean",
    "LIGGATT James": "liggatt-james",
    "LIGHT Greg": "light-greg",
    "LIGHT T K": "light-t-k",
    "LIGHT Tess": "light-tess",
    "LIGHTBODY Stuart": "lightbody-stuart",
    "LIGHTFOOT Michael": "lightfoot-michael",
    "LIGHTFOOT Philip": "lightfoot-philip",
    "LIGHTWORK ": "lightwork",
    "LIIGUCHL Mamoru": "liiguchl-mamoru",
    "LIITOJA Hillar": "liitoja-hillar",
    "LIKHARI Sonia": "likhari-sonia",
    "LIKING Werewere": "liking-werewere",
    "LILAR Suzanne": "lilar-suzanne",
    "LILJENQUIST Don C": "liljenquist-don-c",
    "LILL Michael": "lill-michael",
    "LILL Wendy": "lill-wendy",
    "LILLESTROEM K Lauren": "lillestroem-k-lauren",
    "LILLEY Mike": "lilley-mike",
    "LILLFORD Daniel R": "lillford-daniel-r",
    "LILLIAS Matthew": "lillias-matthew",
    "LILLIBRIDGE Adam": "lillibridge-adam",
    "LILLICRAP Christopher": "lillicrap-christopher",
    "LILLIE Brian": "lillie-brian",
    "LILLIE Peter": "lillie-peter",
    "LILLINGTON Kenneth": "lillington-kenneth",
    "LILLIS Padraic": "lillis-padraic",
    "LILLO George": "lillo-george",
    "LILLY Brenda": "lilly-brenda",
    "LILLY Destiny": "lilly-destiny",
    "LILLY Judlyne A": "lilly-judlyne-a",
    "LILTH GROUP, THE ": "lilth-group",
    "LILY Peta": "lily-peta",
    "LIM Dean": "lim-dean",
    "LIM Emily": "lim-emily",
    "LIM Genny": "lim-genny",
    "LIM Keith": "lim-keith",
    "LIM Paul Stephen": "lim-paul-stephen",
    "LIM Sean": "lim-sean",
    "LIM Yuhan": "lim-yuhan",
    "LIMA Frank": "lima-frank",
    "LIMA Rafael": "lima-rafael",
    "LIMA Robert": "lima-robert",
    "LIMB Hyoung-Taek": "limb-hyoung-taek",
    "LIMB Jeremy": "limb-jeremy",
    "LIMBER Christopher": "limber-christopher",
    "LIMBOS Agnes": "limbos-agnes",
    "LIMBREY James": "limbrey-james",
    "LIMENTANI Rick": "limentani-rick",
    "LIMER Julia": "limer-julia",
    "LIMIN Yang": "limin-yang",
    "LIMINABOZO ": "liminabozo",
    "LIMITS Dusty": "limits-dusty",
    "LIMM Nicholas": "limm-nicholas",
    "LIMOLI Howard": "limoli-howard",
    "LIMOLI Justin": "limoli-justin",
    "LIMON Oscar F": "limon-oscar-f",
    "LIMONCELLI Frances": "limoncelli-frances",
    "LIN David": "lin-david",
    "LIN Elizabeth": "lin-elizabeth",
    "LIN I-Jong": "lin-i-jong",
    "LIN Jakov": "lin-jakov",
    "LIN Kenneth": "lin-kenneth",
    "LIN Kuei-Ming": "lin-kuei-ming",
    "LIN Patricia H": "lin-patricia-h",
    "LIN Serena": "lin-serena",
    "LIN Shen": "lin-shen",
    "LIN Weiko": "lin-weiko",
    "LINCOLN Rachel": "lincoln-rachel",
    "LIND Jessica": "lind-jessica",
    "LIND Phyllis": "lind-phyllis",
    "LINDAY Barbara": "linday-barbara",
    "LINDBERG Linsey": "lindberg-linsey",
    "LINDBERG Mark": "lindberg-mark",
    "LINDBERG Sandra": "lindberg-sandra",
    "LINDBERG Wayne": "lindberg-wayne",
    "LINDEMANN Yehudi": "lindemann-yehudi",
    "LINDEN Connor": "linden-connor",
    "LINDEN Sonja": "linden-sonja",
    "LINDEN Stella": "linden-stella",
    "LINDENBERG James": "lindenberg-james",
    "LINDER Evan": "linder-evan",
    "LINDER Robert": "linder-robert",
    "LINDERMAN Ed": "linderman-ed",
    "LINDERS Jeanie": "linders-jeanie",
    "LINDFIELD Richard": "lindfield-richard",
    "LINDGREN Torgny": "lindgren-torgny",
    "LINDHOLM Marita": "lindholm-marita",
    "LINDLE Darian": "lindle-darian",
    "LINDLEY Valrose": "lindley-valrose",
    "LINDNER Jason": "lindner-jason",
    "LINDOW Laura": "lindow-laura",
    "LINDREN Torgny": "lindren-torgny",
    "LINDROTH Malin": "lindroth-malin",
    "LINDS Brian": "linds-brian",
    "LINDSAY Andrew": "lindsay-andrew",
    "LINDSAY Barbara": "lindsay-barbara",
    "LINDSAY Chris": "lindsay-chris",
    "LINDSAY Christine": "lindsay-christine",
    "LINDSAY David": "lindsay-david",
    "LINDSAY Ellen": "lindsay-ellen",
    "LINDSAY Frederic": "lindsay-frederic",
    "LINDSAY Harold Arthur": "lindsay-harold-arthur",
    "LINDSAY Hertencer": "lindsay-hertencer",
    "LINDSAY Hilaire": "lindsay-hilaire",
    "LINDSAY Howard": "lindsay-howard",
    "LINDSAY Ian": "lindsay-ian",
    "LINDSAY Kate": "lindsay-kate",
    "LINDSAY Kenny": "lindsay-kenny",
    "LINDSAY Laura": "lindsay-laura",
    "LINDSAY Martin": "lindsay-martin",
    "LINDSAY Michelle": "lindsay-michelle",
    "LINDSAY Robin": "lindsay-robin",
    "LINDSAY-ABAIRE David": "lindsay-abaire-david",
    "LINDSEY-NASSIF Robert": "lindsey-nassif-robert",
    "LINDSTROM Tom": "lindstrom-tom",
    "LINEBERGER James": "lineberger-james",
    "LINEHAN Fergus": "linehan-fergus",
    "LINEHAN Graham": "linehan-graham",
    "LINEHAN Rosaleen": "linehan-rosaleen",
    "LINEHAN Shay": "linehan-shay",
    "LINER Elaine": "liner-elaine",
    "LINES Marian": "lines-marian",
    "LINFANTE Michele": "linfante-michele",
    "LINFORD Zac": "linford-zac",
    "LING Nils": "ling-nils",
    "LINGAN Edmund B": "lingan-edmund-b",
    "LINGO Allegra J": "lingo-allegra-j",
    "LINK David": "link-david",
    "LINK Patrick": "link-patrick",
    "LINK Peter": "link-peter",
    "LINK Richard": "link-richard",
    "LINK Ruth": "link-ruth",
    "LINK William": "link-william",
    "LINKA Peter": "linka-peter",
    "LINKE Don": "linke-don",
    "LINKE Paul": "linke-paul",
    "LINKLATER Eric": "linklater-eric",
    "LINKLATER Hamish": "linklater-hamish",
    "LINKLATER Leonard": "linklater-leonard",
    "LINKLATER Tom": "linklater-tom",
    "LINLEY Jamie": "linley-jamie",
    "LINMARK R Zamora": "linmark-r-zamora",
    "LINNEHAN Nicholas A": "linnehan-nicholas-a",
    "LINNELL Jim": "linnell-jim",
    "LINNEY Romulus": "linney-romulus",
    "LINSKY Leanne": "linsky-leanne",
    "LINSLEY Johanna": "linsley-johanna",
    "LINSTRUM Catherine": "linstrum-catherine",
    "LINSTRUM John": "linstrum-john",
    "LINTHWAITE Illona": "linthwaite-illona",
    "LINTON Logan": "linton-logan",
    "LINTON Lynette": "linton-lynette",
    "LINTULA Douglas": "lintula-douglas",
    "LINTZ Sharon": "lintz-sharon",
    "LINZ Talia": "linz-talia",
    "LINZEY Jake": "linzey-jake",
    "LION Eugene": "lion-eugene",
    "LION & UNICOM ": "lion-unicom",
    "LIPEZ Erica": "lipez-erica",
    "LIPHSHIZ Oded": "liphshiz-oded",
    "LIPINER Michael": "lipiner-michael",
    "LIPKIN Dmitry": "lipkin-dmitry",
    "LIPKIN Joan": "lipkin-joan",
    "LIPKIN Robert": "lipkin-robert",
    "LIPMAN Daniel": "lipman-daniel",
    "LIPMAN Dennis": "lipman-dennis",
    "LIPMAN Jake": "lipman-jake",
    "LIPMAN Maureen": "lipman-maureen",
    "LIPNER Matthew": "lipner-matthew",
    "LIPPA Andrew": "lippa-andrew",
    "LIPPA Louis": "lippa-louis",
    "LIPPE Steve": "lippe-steve",
    "LIPPEATT Lauren Nicole": "lippeatt-lauren-nicole",
    "LIPPERT Ann": "lippert-ann",
    "LIPPERT Raewyn": "lippert-raewyn",
    "LIPPERT Sharon": "lippert-sharon",
    "LIPPMAN Anna": "lippman-anna",
    "LIPPMAN Richard A": "lippman-richard-a",
    "LIPPMAN Robert L": "lippman-robert-l",
    "LIPSCHUS Kimberley": "lipschus-kimberley",
    "LIPSCOMB Thomas": "lipscomb-thomas",
    "LIPSCOMB William Percy": "lipscomb-william-percy",
    "LIPSCOTT Alan": "lipscott-alan",
    "LIPSERVICE ": "lipservice",
    "LIPSIUS Adam": "lipsius-adam",
    "LIPSKY Jon": "lipsky-jon",
    "LIPSON Brian": "lipson-brian",
    "LIPSON Jacob Morris": "lipson-jacob-morris",
    "LIPSON Katy": "lipson-katy",
    "LIPTON Andrew": "lipton-andrew",
    "LIPTON Beverly Bremers": "lipton-beverly-bremers",
    "LIPTON Brody": "lipton-brody",
    "LIPTON Dan": "lipton-dan",
    "LIPTON Ethan": "lipton-ethan",
    "LIPTON Hugh": "lipton-hugh",
    "LIPTON James": "lipton-james",
    "LIPTON Lynne": "lipton-lynne",
    "LIPTON Michelle": "lipton-michelle",
    "LIPTSIN Oleg": "liptsin-oleg",
    "LIQUID THEATRE ": "liquid-theatre",
    "LIRON Jonny": "liron-jonny",
    "LISA Monique": "lisa-monique",
    "LISA FLANAGAN Lisa": "lisa-flanagan-lisa",
    "LISHEN Kristen": "lishen-kristen",
    "LISKA Pavol": "liska-pavol",
    "LISKE Cazimir": "liske-cazimir",
    "LISS Stephanie": "liss-stephanie",
    "LISSAK Monica": "lissak-monica",
    "LISSER Alison": "lisser-alison",
    "LIST Bo": "list-bo",
    "LIST Rob": "list-rob",
    "LISTER Derek": "lister-derek",
    "LISTER Heather": "lister-heather",
    "LISTER Polly": "lister-polly",
    "LISTER Rebecca": "lister-rebecca",
    "LISTER Tom W": "lister-tom-w",
    "LISTERMAN Randall": "listerman-randall",
    "LITALIEN Camille": "litalien-camille",
    "LITMAN Jody": "litman-jody",
    "LITMAN Joel M": "litman-joel-m",
    "LITMAN Ron": "litman-ron",
    "LITRAS Andreas": "litras-andreas",
    "LITSCHER Hans-Peter": "litscher-hans-peter",
    "LITSEY Alan": "litsey-alan",
    "LITT Jennifer A": "litt-jennifer-a",
    "LITT Toby": "litt-toby",
    "LITTELL Philip": "littell-philip",
    "LITTLE Bruce J": "little-bruce-j",
    "LITTLE Frederick F": "little-frederick-f",
    "LITTLE George": "little-george",
    "LITTLE Kirstie": "little-kirstie",
    "LITTLE Larry": "little-larry",
    "LITTLE Ruth": "little-ruth",
    "LITTLE Simon": "little-simon",
    "LITTLE ANGEL THEATRE ": "little-angel-theatre",
    "LITTLE BULB THEATRE ": "little-bulb-theatre",
    "LITTLE WONDER ": "little-wonder",
    "LITTLER Chris": "littler-chris",
    "LITTLER Emile": "littler-emile",
    "LITTLER Tom": "littler-tom",
    "LITTLEWAY Lorna": "littleway-lorna",
    "LITTLEWOOD Clayton": "littlewood-clayton",
    "LITTLEWOOD Joan": "littlewood-joan",
    "LITTLEWOOD Kate": "littlewood-kate",
    "LITTMAN Adam Stuart": "littman-adam-stuart",
    "LITVAK Barry": "litvak-barry",
    "LITWAK Ezra": "litwak-ezra",
    "LITWAK Jessica": "litwak-jessica",
    "LITZ David": "litz-david",
    "LITZ Robert": "litz-robert",
    "LITZKY Andrew": "litzky-andrew",
    "LIU Cynthia Gates": "liu-cynthia-gates",
    "LIU Grace": "liu-grace",
    "LIU Jeffrey": "liu-jeffrey",
    "LIU Mingji": "liu-mingji",
    "LIU Yilong": "liu-yilong",
    "LIVE THEATRE ": "live-theatre",
    "LIVEART ": "liveart",
    "LIVEARTSHOW ": "liveartshow",
    "LIVELY Derek": "lively-derek",
    "LIVELY John Marc": "lively-john-marc",
    "LIVERIGHT Josh": "liveright-josh",
    "LIVERMAN Debbra": "liverman-debbra",
    "LIVERMORE Reg": "livermore-reg",
    "LIVERMORE Steve": "livermore-steve",
    "LIVING SPIT ": "living-spit",
    "LIVING STRUCTURES ": "living-structures",
    "LIVINGATON Laura": "livingaton-laura",
    "LIVINGS Henry": "livings-henry",
    "LIVINGSTON Andrew": "livingston-andrew",
    "LIVINGSTON Arthur": "livingston-arthur",
    "LIVINGSTON Ben": "livingston-ben",
    "LIVINGSTON Erica": "livingston-erica",
    "LIVINGSTON Ivy": "livingston-ivy",
    "LIVINGSTON Jane": "livingston-jane",
    "LIVINGSTON Jay": "livingston-jay",
    "LIVINGSTON Laura": "livingston-laura",
    "LIVINGSTON Patrick": "livingston-patrick",
    "LIVINGSTON Paul": "livingston-paul",
    "LIVINGSTON Robert H": "livingston-robert-h",
    "LIVINGSTONE Arthur": "livingstone-arthur",
    "LIVINGSTONE Douglas": "livingstone-douglas",
    "LIVINSTON Jay": "livinston-jay",
    "LIYES Manny": "liyes-manny",
    "LIZARDI Joseph": "lizardi-joseph",
    "LIZZIMORE Clare": "lizzimore-clare",
    "LLEAF Fredric": "lleaf-fredric",
    "LLEWELLYN Casey": "llewellyn-casey",
    "LLEWELLYN Jack": "llewellyn-jack",
    "LLEWELLYN Robert": "llewellyn-robert",
    "LLEWELLYN Sally": "llewellyn-sally",
    "LLEWELLYN Vic": "llewellyn-vic",
    "LLEWELLYN-JONES Lloyd": "llewellyn-jones-lloyd",
    "LLEWELYN Dafydd": "llewelyn-dafydd",
    "LLEWELYN Miriam": "llewelyn-miriam",
    "LLEWELYN Owen": "llewelyn-owen",
    "LLEWELYN Tony": "llewelyn-tony",
    "LLITERAS D S": "lliteras-d-s",
    "LLOSA Mario Vargas": "llosa-mario-vargas",
    "LLOYD Annie": "lloyd-annie",
    "LLOYD Bob": "lloyd-bob",
    "LLOYD Cariad": "lloyd-cariad",
    "LLOYD Christian": "lloyd-christian",
    "LLOYD Davidson": "lloyd-davidson",
    "LLOYD Emma": "lloyd-emma",
    "LLOYD Gary": "lloyd-gary",
    "LLOYD Gayle Ponder": "lloyd-gayle-ponder",
    "LLOYD Harry": "lloyd-harry",
    "LLOYD Ione": "lloyd-ione",
    "LLOYD J M": "lloyd-j-m",
    "LLOYD Jake": "lloyd-jake",
    "LLOYD Jamie": "lloyd-jamie",
    "LLOYD Jeremy": "lloyd-jeremy",
    "LLOYD Jeremy K": "lloyd-jeremy-k",
    "LLOYD Johnny": "lloyd-johnny",
    "LLOYD Jonathan": "lloyd-jonathan",
    "LLOYD Kanoa": "lloyd-kanoa",
    "LLOYD Lawrence": "lloyd-lawrence",
    "LLOYD Marcus": "lloyd-marcus",
    "LLOYD Mari": "lloyd-mari",
    "LLOYD Mark": "lloyd-mark",
    "LLOYD Matthew": "lloyd-matthew",
    "LLOYD Morgan": "lloyd-morgan",
    "LLOYD Pat": "lloyd-pat",
    "LLOYD Patricia Ione": "lloyd-patricia-ione",
    "LLOYD Peter": "lloyd-peter",
    "LLOYD Rhys": "lloyd-rhys",
    "LLOYD Richard": "lloyd-richard",
    "LLOYD Richard Arthur": "lloyd-richard-arthur",
    "LLOYD Rick": "lloyd-rick",
    "LLOYD Sue": "lloyd-sue",
    "LLOYD Toby": "lloyd-toby",
    "LLOYD Trevor": "lloyd-trevor",
    "LLOYD-BUTLER Mary": "lloyd-butler-mary",
    "LLOYD-JONES Hugh": "lloyd-jones-hugh",
    "LLOYD-PARRY Richard": "lloyd-parry-richard",
    "LLOYD-PARRY Roland": "lloyd-parry-roland",
    "LLUBERES Michael": "lluberes-michael",
    "LLUCH Jordi": "lluch-jordi",
    "LLWYD Iestyn": "llwyd-iestyn",
    "LLYWELYN Miriam": "llywelyn-miriam",
    "LLZUKA Naomi": "llzuka-naomi"
  }
};