export default {
  "metadata": {
    "results": 928,
    "timeStamp": "2025-12-05T21:29:08.215Z",
    "url": "https://www.doollee.com/PlaywrightsM/M_playwrights_m-r.php"
  },
  "authors": {
    "MNISI Sizwesandile": "mnisi-sizwesandile",
    "MNOOKIN Stephanie": "mnookin-stephanie",
    "MNOUCHKINE Ariane": "mnouchkine-ariane",
    "MNQWAZANA Sihie": "mnqwazana-sihie",
    "MO Elaine": "mo-elaine",
    "MO Lab Ky": "mo-lab-ky",
    "MO Nguyen Y": "mo-nguyen-y",
    "MO' Keb'": "mo-keb",
    "MOA Suli": "moa-suli",
    "MOAYED Arian": "moayed-arian",
    "MOBERG David": "moberg-david",
    "MOBERG Verne": "moberg-verne",
    "MOCH Cheryl": "moch-cheryl",
    "MOCK Aspen": "mock-aspen",
    "MOCK Teresa": "mock-teresa",
    "MODE Becky": "mode-becky",
    "MODELL Glen": "modell-glen",
    "MODERN Bruno": "modern-bruno",
    "MODERN THEATER OF BUDAPEST ": "modern-theater-of-budapest",
    "MODERNO TRIO ": "moderno-trio",
    "MODLIN Ross": "modlin-ross",
    "MODOTTI Tina": "modotti-tina",
    "MOE Christian H": "moe-christian-h",
    "MOE John": "moe-john",
    "MOED Claire Olivia": "moed-claire-olivia",
    "MOELLER Greg": "moeller-greg",
    "MOELLER Tahirih": "moeller-tahirih",
    "MOELLER Tommy": "moeller-tommy",
    "MOENCH Anna": "moench-anna",
    "MOENNIG Hans": "moennig-hans",
    "MOESCHL Richard": "moeschl-richard",
    "MOETARA Teina": "moetara-teina",
    "MOFFAT Graham": "moffat-graham",
    "MOFFAT Peter": "moffat-peter",
    "MOFFAT Robbie": "moffat-robbie",
    "MOFFATT John": "moffatt-john",
    "MOFFATT Jonny": "moffatt-jonny",
    "MOFFATT Lucy Montague": "moffatt-lucy-montague",
    "MOFFATT Nigel": "moffatt-nigel",
    "MOFFATT Sean": "moffatt-sean",
    "MOFFATT Susan": "moffatt-susan",
    "MOFFIT John C": "moffit-john-c",
    "MOGEL Christopher": "mogel-christopher",
    "MOGER Doreen": "moger-doreen",
    "MOGGACH Deborah": "moggach-deborah",
    "MOGGRIDGE Alex": "moggridge-alex",
    "MOGOL Allen": "mogol-allen",
    "MOGOLOV David": "mogolov-david",
    "MOHAMATHNO Maramy": "mohamathno-maramy",
    "MOHAMMAD Avaes": "mohammad-avaes",
    "MOHAMMED K Silem": "mohammed-k-silem",
    "MOHANBHAI Tarun": "mohanbhai-tarun",
    "MOHER Frank": "moher-frank",
    "MOHER Kenneth": "moher-kenneth",
    "MOHER Zia": "moher-zia",
    "MOHIMEN Akash": "mohimen-akash",
    "MOHLMAN Danielle": "mohlman-danielle",
    "MOHN Leslie": "mohn-leslie",
    "MOHR Christopher": "mohr-christopher",
    "MOHR Frederic": "mohr-frederic",
    "MOHR Howard": "mohr-howard",
    "MOHRBACHER Paul": "mohrbacher-paul",
    "MOHRI Tomio": "mohri-tomio",
    "MOIE Charles": "moie-charles",
    "MOIR Cameron": "moir-cameron",
    "MOIR Elizabeth": "moir-elizabeth",
    "MOIR Emily": "moir-emily",
    "MOIR Paul": "moir-paul",
    "MOIRA Lissa": "moira-lissa",
    "MOISE Lenelle": "moise-lenelle",
    "MOJICA Monique": "mojica-monique",
    "MOJTABAIE Hadi": "mojtabaie-hadi",
    "MOKADI Amos": "mokadi-amos",
    "MOKARAKA Rob": "mokaraka-rob",
    "MOKID Mina": "mokid-mina",
    "MOKUAMI Kawatake": "mokuami-kawatake",
    "MOL Pauline": "mol-pauline",
    "MOLANDER Anita": "molander-anita",
    "MOLAR Lee": "molar-lee",
    "MOLASSES Fancy": "molasses-fancy",
    "MOLCHONOFF Helen": "molchonoff-helen",
    "MOLDOFSKY Mitch": "moldofsky-mitch",
    "MOLDOVAN Ioana": "moldovan-ioana",
    "MOLE Rea": "mole-rea",
    "MOLE Simon": "mole-simon",
    "MOLEBA Eliot": "moleba-eliot",
    "MOLETTE Barbara": "molette-barbara",
    "MOLETTE Carlton": "molette-carlton",
    "MOLIERE ": "moliere",
    "MOLINA Armando": "molina-armando",
    "MOLINA Raul Quiros": "molina-raul-quiros",
    "MOLINARO Julius A": "molinaro-julius-a",
    "MOLINARO Katie": "molinaro-katie",
    "MOLINARO U": "molinaro-u",
    "MOLINE Lisanne Nathalia": "moline-lisanne-nathalia",
    "MOLINE Tait": "moline-tait",
    "MOLINEAUX Michael": "molineaux-michael",
    "MOLINO Anthony": "molino-anthony",
    "MOLINS Lorraine": "molins-lorraine",
    "MOLITERNO Gino": "moliterno-gino",
    "MOLITOR Claudia": "molitor-claudia",
    "MOLL Elick": "moll-elick",
    "MOLLEL Tolowa": "mollel-tolowa",
    "MOLLIN Larry": "mollin-larry",
    "MOLLOY Chris": "molloy-chris",
    "MOLLOY Connor": "molloy-connor",
    "MOLLOY Jodie": "molloy-jodie",
    "MOLLOY John": "molloy-john",
    "MOLLOY Kenneth": "molloy-kenneth",
    "MOLLOY M J": "molloy-m-j",
    "MOLLOY Richard": "molloy-richard",
    "MOLLY Dave": "molly-dave",
    "MOLNAR Donald": "molnar-donald",
    "MOLNAR Ferenc": "molnar-ferenc",
    "MOLNAROVA Kristina": "molnarova-kristina",
    "MOLONEY Jan": "moloney-jan",
    "MOLONEY Sarah-Jane": "moloney-sarah-jane",
    "MOLOSI Donald": "molosi-donald",
    "MOLUMBY Mollie": "molumby-mollie",
    "MOLUSI Omphile": "molusi-omphile",
    "MOLYNEAUX Thomas": "molyneaux-thomas",
    "MOLYNEUX Chris": "molyneux-chris",
    "MOLYNEUX Sarah": "molyneux-sarah",
    "MOMADAY N Scott": "momaday-n-scott",
    "MOMBERGER Karla": "momberger-karla",
    "MOMENT'S PEACE ": "moments-peace",
    "MOMENTUM ": "momentum",
    "MONACO Dan": "monaco-dan",
    "MONACO James Harrison": "monaco-james-harrison",
    "MONACO Ron": "monaco-ron",
    "MONAFU Megan Piercey": "monafu-megan-piercey",
    "MONAGHAN Jim": "monaghan-jim",
    "MONAGHAN Kate": "monaghan-kate",
    "MONAGHAN Louise": "monaghan-louise",
    "MONAGHAN Neil": "monaghan-neil",
    "MONAGHAN Peter": "monaghan-peter",
    "MONAGHAN Stephen": "monaghan-stephen",
    "MONAGLE Ashleigh": "monagle-ashleigh",
    "MONAHAN Jackie": "monahan-jackie",
    "MONAHAN Sean Patrick": "monahan-sean-patrick",
    "MONARCH THEATER COMPANY ": "monarch-theater-company",
    "MONARQUE Steve": "monarque-steve",
    "MONASTER Nate": "monaster-nate",
    "MONASTERIO Luis Enrique Gutierrez Ortiz": "monasterio-luis-enrique-gutierrez-ortiz",
    "MONAT Donald": "monat-donald",
    "MONCADA Luis Mario": "moncada-luis-mario",
    "MONCADA Santiago": "moncada-santiago",
    "MONCKTON Thom": "monckton-thom",
    "MONCRIEFF Nathaniel": "moncrieff-nathaniel",
    "MONCRIEFF W T": "moncrieff-w-t",
    "MONCURE Joseph": "moncure-joseph",
    "MONDAY Dick": "monday-dick",
    "MONDE Lisa": "monde-lisa",
    "MONDI Max": "mondi-max",
    "MONDOK Elizabeth": "mondok-elizabeth",
    "MONDOT Lexie Martin": "mondot-lexie-martin",
    "MONDRAGON Carole": "mondragon-carole",
    "MONDZAK Susan": "mondzak-susan",
    "MONET Emma": "monet-emma",
    "MONETTI Sandro": "monetti-sandro",
    "MONFROOE Amanda": "monfrooe-amanda",
    "MONG Melissa": "mong-melissa",
    "MONGE-RAFULS Pedro R": "monge-rafuls-pedro-r",
    "MONGIWEKHAYA ": "mongiwekhaya",
    "MONIACI Jon": "moniaci-jon",
    "MONICO David": "monico-david",
    "MONIGHAN Logan": "monighan-logan",
    "MONJO Justin": "monjo-justin",
    "MONK Andrew": "monk-andrew",
    "MONK Debra": "monk-debra",
    "MONK Ed": "monk-ed",
    "MONK Isabell": "monk-isabell",
    "MONK Joseph": "monk-joseph",
    "MONK Meredith": "monk-meredith",
    "MONK Pamela": "monk-pamela",
    "MONK Roger": "monk-roger",
    "MONK Seonag": "monk-seonag",
    "MONKEY BAA ": "monkey-baa",
    "MONKHOUSE Allan": "monkhouse-allan",
    "MONKHOUSE Jonathan": "monkhouse-jonathan",
    "MONKMAN Kent": "monkman-kent",
    "MONKS Chris": "monks-chris",
    "MONKS Helen": "monks-helen",
    "MONKS Philip": "monks-philip",
    "MONKS JR John": "monks-jr-john",
    "MONNOT Susan Price": "monnot-susan-price",
    "MONOKIAN Brandon": "monokian-brandon",
    "MONOLOGUE BLOGGER ": "monologue-blogger",
    "MONRO Briar": "monro-briar",
    "MONRO Robert": "monro-robert",
    "MONRO Sean": "monro-sean",
    "MONROE Andy": "monroe-andy",
    "MONROE Bruce A": "monroe-bruce-a",
    "MONROE Henry": "monroe-henry",
    "MONROE Janet": "monroe-janet",
    "MONROE Michael": "monroe-michael",
    "MONROE Steve": "monroe-steve",
    "MONROE Tyler": "monroe-tyler",
    "MONSEF Ramiz": "monsef-ramiz",
    "MONSELL Jordan": "monsell-jordan",
    "MONSEU Stephanie": "monseu-stephanie",
    "MONSEY Derek": "monsey-derek",
    "MONSON J R": "monson-j-r",
    "MONSON Jeremy": "monson-jeremy",
    "MONSON Susan K": "monson-susan-k",
    "MONSOUR Anne": "monsour-anne",
    "MONSTROUS REGIMENT ": "monstrous-regiment",
    "MONT Daniel": "mont-daniel",
    "MONTAGUE Judy": "montague-judy",
    "MONTALTO Chiara": "montalto-chiara",
    "MONTANDIN Derland": "montandin-derland",
    "MONTANEZ Vicente": "montanez-vicente",
    "MONTANGA Helene": "montanga-helene",
    "MONTE Bonnie J": "monte-bonnie-j",
    "MONTE Eric": "monte-eric",
    "MONTEIGNE Margaret": "monteigne-margaret",
    "MONTEIRO Sttau": "monteiro-sttau",
    "MONTEITH John": "monteith-john",
    "MONTEITH Johnmichael": "monteith-johnmichael",
    "MONTEL Michael": "montel-michael",
    "MONTELEONE John": "monteleone-john",
    "MONTELEONE Tom": "monteleone-tom",
    "MONTELIUS Martina": "montelius-martina",
    "MONTENEGRO Robert": "montenegro-robert",
    "MONTERO Gloria": "montero-gloria",
    "MONTERO Jezabel": "montero-jezabel",
    "MONTEVERDE Gay": "monteverde-gay",
    "MONTEZ Paul-Felix": "montez-paul-felix",
    "MONTFORT Vanessa": "montfort-vanessa",
    "MONTGOMERY Andrea": "montgomery-andrea",
    "MONTGOMERY Bruce": "montgomery-bruce",
    "MONTGOMERY Carole": "montgomery-carole",
    "MONTGOMERY Catherine": "montgomery-catherine",
    "MONTGOMERY Cisco": "montgomery-cisco",
    "MONTGOMERY Denise": "montgomery-denise",
    "MONTGOMERY E": "montgomery-e",
    "MONTGOMERY James": "montgomery-james",
    "MONTGOMERY Jason R": "montgomery-jason-r",
    "MONTGOMERY Jenny": "montgomery-jenny",
    "MONTGOMERY Jon": "montgomery-jon",
    "MONTGOMERY Kris": "montgomery-kris",
    "MONTGOMERY Lesley": "montgomery-lesley",
    "MONTGOMERY Leyland": "montgomery-leyland",
    "MONTGOMERY Lucy": "montgomery-lucy",
    "MONTGOMERY Mitch": "montgomery-mitch",
    "MONTGOMERY Molly": "montgomery-molly",
    "MONTGOMERY Robert": "montgomery-robert",
    "MONTGOMERY Sara": "montgomery-sara",
    "MONTGOMERY Susan Scarlett": "montgomery-susan-scarlett",
    "MONTLEY Pat": "montley-pat",
    "MONTOUREDES Rita": "montouredes-rita",
    "MONTOUREDES Tom": "montouredes-tom",
    "MONTOYA Jerry R": "montoya-jerry-r",
    "MONTOYA Richard": "montoya-richard",
    "MONVID Grazyna": "monvid-grazyna",
    "MONVID-JENKINSON Carla Jo": "monvid-jenkinson-carla-jo",
    "MONZAEMON Chikamatsu": "monzaemon-chikamatsu",
    "MOODEY Claire": "moodey-claire",
    "MOODIE Andrew": "moodie-andrew",
    "MOODIE Marie": "moodie-marie",
    "MOODY Allison": "moody-allison",
    "MOODY Barbara": "moody-barbara",
    "MOODY Doug": "moody-doug",
    "MOODY Jeff": "moody-jeff",
    "MOODY Joleene": "moody-joleene",
    "MOODY Michael Dorn": "moody-michael-dorn",
    "MOODY Nell": "moody-nell",
    "MOODY Steffon": "moody-steffon",
    "MOOMEY Kristen": "moomey-kristen",
    "MOON Addae": "moon-addae",
    "MOON Andrea": "moon-andrea",
    "MOON Eva": "moon-eva",
    "MOON Farzana": "moon-farzana",
    "MOON Gerald": "moon-gerald",
    "MOON Sarah": "moon-sarah",
    "MOONEY John": "mooney-john",
    "MOONEY Jonathan": "mooney-jonathan",
    "MOONEY Kate": "mooney-kate",
    "MOONEY Kay": "mooney-kay",
    "MOONEY Lauren": "mooney-lauren",
    "MOONEY Martin": "mooney-martin",
    "MOONEY Michael": "mooney-michael",
    "MOONEY Owen": "mooney-owen",
    "MOONEY Ray": "mooney-ray",
    "MOONEY Timothy": "mooney-timothy",
    "MOONEY Vicki Lynn": "mooney-vicki-lynn",
    "MOON-LITTLE Christopher": "moon-little-christopher",
    "MOONMAN Kobus": "moonman-kobus",
    "MOOR Ben": "moor-ben",
    "MOORE Allison": "moore-allison",
    "MOORE Angela": "moore-angela",
    "MOORE Anne": "moore-anne",
    "MOORE Anthony": "moore-anthony",
    "MOORE Athene": "moore-athene",
    "MOORE Betsy": "moore-betsy",
    "MOORE Brett": "moore-brett",
    "MOORE Brian": "moore-brian",
    "MOORE Cairn": "moore-cairn",
    "MOORE Cameryn": "moore-cameryn",
    "MOORE Cara": "moore-cara",
    "MOORE Carroll": "moore-carroll",
    "MOORE Charles M": "moore-charles-m",
    "MOORE Charlie": "moore-charlie",
    "MOORE Charlotte": "moore-charlotte",
    "MOORE Chinsook Kim": "moore-chinsook-kim",
    "MOORE Christopher": "moore-christopher",
    "MOORE Curtis": "moore-curtis",
    "MOORE D C": "moore-d-c",
    "MOORE Dale E": "moore-dale-e",
    "MOORE Daphne": "moore-daphne",
    "MOORE Davey": "moore-davey",
    "MOORE David Alan": "moore-david-alan",
    "MOORE Dawson": "moore-dawson",
    "MOORE Donna": "moore-donna",
    "MOORE Dudley": "moore-dudley",
    "MOORE Edward J": "moore-edward-j",
    "MOORE Elise": "moore-elise",
    "MOORE Emma": "moore-emma",
    "MOORE Ewen Caden": "moore-ewen-caden",
    "MOORE Gary": "moore-gary",
    "MOORE Geoff": "moore-geoff",
    "MOORE George": "moore-george",
    "MOORE Gerald Arthur": "moore-gerald-arthur",
    "MOORE Harry": "moore-harry",
    "MOORE Heather": "moore-heather",
    "MOORE Honor": "moore-honor",
    "MOORE Ian": "moore-ian",
    "MOORE J": "moore-j",
    "MOORE Jack": "moore-jack",
    "MOORE James": "moore-james",
    "MOORE Jason": "moore-jason",
    "MOORE Jeffrey": "moore-jeffrey",
    "MOORE Jerrard": "moore-jerrard",
    "MOORE Jim": "moore-jim",
    "MOORE John": "moore-john",
    "MOORE John (1)": "moore-john-1",
    "MOORE John Carlisle": "moore-john-carlisle",
    "MOORE John P": "moore-john-p",
    "MOORE John Patrick": "moore-john-patrick",
    "MOORE Jonathan": "moore-jonathan",
    "MOORE Joseph": "moore-joseph",
    "MOORE Julian": "moore-julian",
    "MOORE Kim": "moore-kim",
    "MOORE Kyle": "moore-kyle",
    "MOORE Lauren": "moore-lauren",
    "MOORE Lenny": "moore-lenny",
    "MOORE Lindsey": "moore-lindsey",
    "MOORE Lorrie": "moore-lorrie",
    "MOORE Marsha": "moore-marsha",
    "MOORE Mavor": "moore-mavor",
    "MOORE Maxine D": "moore-maxine-d",
    "MOORE Meital": "moore-meital",
    "MOORE Melba": "moore-melba",
    "MOORE Nicholas": "moore-nicholas",
    "MOORE Nick": "moore-nick",
    "MOORE Oscar E": "moore-oscar-e",
    "MOORE Rasheeda": "moore-rasheeda",
    "MOORE Richard": "moore-richard",
    "MOORE Ronald": "moore-ronald",
    "MOORE Rosemary": "moore-rosemary",
    "MOORE Sam": "moore-sam",
    "MOORE Sandra": "moore-sandra",
    "MOORE Sandy": "moore-sandy",
    "MOORE Sarah": "moore-sarah",
    "MOORE Sascha": "moore-sascha",
    "MOORE Scotto": "moore-scotto",
    "MOORE Simon": "moore-simon",
    "MOORE Sonal": "moore-sonal",
    "MOORE Steve": "moore-steve",
    "MOORE Ted": "moore-ted",
    "MOORE Todd Jefferson": "moore-todd-jefferson",
    "MOORE Tony": "moore-tony",
    "MOORE Wayne": "moore-wayne",
    "MOORE Wesley": "moore-wesley",
    "MOORE-HAINES Chrissy": "moore-haines-chrissy",
    "MOORES Ben": "moores-ben",
    "MOORES Tony": "moores-tony",
    "MOORES JR John J": "moores-jr-john-j",
    "MOORE-WILLIAMS Karen": "moore-williams-karen",
    "MOORHEAD Finola": "moorhead-finola",
    "MOORHOUSE Frank": "moorhouse-frank",
    "MOORHOUSE John": "moorhouse-john",
    "MOORHOUSE Justin": "moorhouse-justin",
    "MOORS Leonard": "moors-leonard",
    "MOORTHY Rani": "moorthy-rani",
    "MOOSA Corey": "moosa-corey",
    "MOOSSY Joan Marie": "moossy-joan-marie",
    "MOOTZ Troodie": "mootz-troodie",
    "MOPTOPS ": "moptops",
    "MORA Gia": "mora-gia",
    "MORA J M": "mora-j-m",
    "MORAES Tuca": "moraes-tuca",
    "MORAGA Cherrie": "moraga-cherrie",
    "MORAHAN Rebecca": "morahan-rebecca",
    "MORALES Alejandro": "morales-alejandro",
    "MORALES Marc": "morales-marc",
    "MORALES Vita": "morales-vita",
    "MORALES Wallace-Ruby": "morales-wallace-ruby",
    "MORAN Caroline": "moran-caroline",
    "MORAN Dolores": "moran-dolores",
    "MORAN Dylan": "moran-dylan",
    "MORAN Evelyn M": "moran-evelyn-m",
    "MORAN Heather": "moran-heather",
    "MORAN James": "moran-james",
    "MORAN James David": "moran-james-david",
    "MORAN Janet": "moran-janet",
    "MORAN Jim": "moran-jim",
    "MORAN Jim Patrick": "moran-jim-patrick",
    "MORAN Joe": "moran-joe",
    "MORAN John": "moran-john",
    "MORAN Justin": "moran-justin",
    "MORAN Kate": "moran-kate",
    "MORAN Manuel A": "moran-manuel-a",
    "MORAN Martin": "moran-martin",
    "MORAN Matt": "moran-matt",
    "MORAN Meg": "moran-meg",
    "MORAN Melissa": "moran-melissa",
    "MORAN Michael": "moran-michael",
    "MORAN Michelle": "moran-michelle",
    "MORAN Mike": "moran-mike",
    "MORAN Nicholas": "moran-nicholas",
    "MORAN Nick": "moran-nick",
    "MORAN Rachel": "moran-rachel",
    "MORAN Seamus": "moran-seamus",
    "MORAN Sharon": "moran-sharon",
    "MORAN Thomas": "moran-thomas",
    "MORAN Vincent J": "moran-vincent-j",
    "MORASH Karen": "morash-karen",
    "MORATTI Celeste": "moratti-celeste",
    "MORAVEC Luke": "moravec-luke",
    "MORAVEK Vladimir": "moravek-vladimir",
    "MORDAIN Richard": "mordain-richard",
    "MORDDEN Ethan": "mordden-ethan",
    "MORDEN Daniel": "morden-daniel",
    "MORDUCH Irana": "morduch-irana",
    "MORDUCH Tina": "morduch-tina",
    "MORE Julian": "more-julian",
    "MORE Rachel": "more-rachel",
    "MORE Robert": "more-robert",
    "MOREA Matt": "morea-matt",
    "MOREHOUSE III Ward": "morehouse-iii-ward",
    "MOREIN Heide": "morein-heide",
    "MOREL Eugene": "morel-eugene",
    "MOREL Paul": "morel-paul",
    "MOREL Valerie": "morel-valerie",
    "MORELAND David W": "moreland-david-w",
    "MORELAND Michael": "moreland-michael",
    "MORELL Musette": "morell-musette",
    "MORELL Purni": "morell-purni",
    "MORELL Richard": "morell-richard",
    "MORELLA Paul": "morella-paul",
    "MORELLI Daniela": "morelli-daniela",
    "MORELLI Domenick": "morelli-domenick",
    "MORELLI Ron": "morelli-ron",
    "MORELLO Brett": "morello-brett",
    "MORELLO Jo": "morello-jo",
    "MORENO A": "moreno-a",
    "MORENO Mateo": "moreno-mateo",
    "MORENO Mitchell": "moreno-mitchell",
    "MORENO Newton": "moreno-newton",
    "MORENO Rene": "moreno-rene",
    "MORENO Rowena": "moreno-rowena",
    "MORENO Sam": "moreno-sam",
    "MORENO-PENSON Desi": "moreno-penson-desi",
    "MORETO Agustin": "moreto-agustin",
    "MORETON Elle": "moreton-elle",
    "MORETTA Anthony": "moretta-anthony",
    "MOREY Arthur John": "morey-arthur-john",
    "MOREY Charles": "morey-charles",
    "MORGAN Abi": "morgan-abi",
    "MORGAN Al": "morgan-al",
    "MORGAN Amanda Wansa": "morgan-amanda-wansa",
    "MORGAN Anthony": "morgan-anthony",
    "MORGAN Barbara White": "morgan-barbara-white",
    "MORGAN Bayard Quincey": "morgan-bayard-quincey",
    "MORGAN Bethan": "morgan-bethan",
    "MORGAN Brian": "morgan-brian",
    "MORGAN Carmel": "morgan-carmel",
    "MORGAN Cass": "morgan-cass",
    "MORGAN Charles": "morgan-charles",
    "MORGAN Chris": "morgan-chris",
    "MORGAN Christopher": "morgan-christopher",
    "MORGAN Claire": "morgan-claire",
    "MORGAN Clark": "morgan-clark",
    "MORGAN Daniel": "morgan-daniel",
    "MORGAN Dave": "morgan-dave",
    "MORGAN Devon": "morgan-devon",
    "MORGAN Diana": "morgan-diana",
    "MORGAN Edwin": "morgan-edwin",
    "MORGAN Elaine": "morgan-elaine",
    "MORGAN Elmo": "morgan-elmo",
    "MORGAN Fidelis": "morgan-fidelis",
    "MORGAN Gayla D": "morgan-gayla-d",
    "MORGAN George D": "morgan-george-d",
    "MORGAN Ian": "morgan-ian",
    "MORGAN Jenny May": "morgan-jenny-may",
    "MORGAN Jim": "morgan-jim",
    "MORGAN Joan": "morgan-joan",
    "MORGAN John": "morgan-john",
    "MORGAN Josua": "morgan-josua",
    "MORGAN Kathleen": "morgan-kathleen",
    "MORGAN Katie": "morgan-katie",
    "MORGAN Ken": "morgan-ken",
    "MORGAN Kevin": "morgan-kevin",
    "MORGAN Lenore": "morgan-lenore",
    "MORGAN Liz": "morgan-liz",
    "MORGAN Lloyd Eyre": "morgan-lloyd-eyre",
    "MORGAN Lloyd Malcolm": "morgan-lloyd-malcolm",
    "MORGAN Malcolm": "morgan-malcolm",
    "MORGAN Natasha": "morgan-natasha",
    "MORGAN Nicholas": "morgan-nicholas",
    "MORGAN Nicole": "morgan-nicole",
    "MORGAN Pat": "morgan-pat",
    "MORGAN Peter": "morgan-peter",
    "MORGAN Philip": "morgan-philip",
    "MORGAN Poppy Burton": "morgan-poppy-burton",
    "MORGAN Rebekah": "morgan-rebekah",
    "MORGAN Richard": "morgan-richard",
    "MORGAN Robert": "morgan-robert",
    "MORGAN S Robert": "morgan-s-robert",
    "MORGAN Sally": "morgan-sally",
    "MORGAN Sharon": "morgan-sharon",
    "MORGAN Sheila": "morgan-sheila",
    "MORGAN Willard": "morgan-willard",
    "MORGAN Yvonne": "morgan-yvonne",
    "MORGAN Zoe": "morgan-zoe",
    "MORGAN-HAWKES Kay": "morgan-hawkes-kay",
    "MORGAN-PRICE Sophie": "morgan-price-sophie",
    "MORGANS Lyndon": "morgans-lyndon",
    "MORGENSTEIN Gary": "morgenstein-gary",
    "MORGENSTERN Frieda Homnick": "morgenstern-frieda-homnick",
    "MORGILLO Antonietta": "morgillo-antonietta",
    "MORGON Mariana Tesch": "morgon-mariana-tesch",
    "MORHACOVA Katarina": "morhacova-katarina",
    "MORHEAD E D A": "morhead-e-d-a",
    "MORI Brian": "mori-brian",
    "MORIARTY Jay": "moriarty-jay",
    "MORIARTY Roisin": "moriarty-roisin",
    "MORICETTE Nancy": "moricette-nancy",
    "MORII Shigeki": "morii-shigeki",
    "MORILLE Jordan William": "morille-jordan-william",
    "MORILLO Matt": "morillo-matt",
    "MORIN Patricia L": "morin-patricia-l",
    "MORINELLI Emlyn": "morinelli-emlyn",
    "MORINELLI Tony Devaney": "morinelli-tony-devaney",
    "MORISON Ivan": "morison-ivan",
    "MORISON Jennifer": "morison-jennifer",
    "MORISON Thomas": "morison-thomas",
    "MORISSEAU Dominique": "morisseau-dominique",
    "MORITA Walter": "morita-walter",
    "MORITZ Dennis Lawrence": "moritz-dennis-lawrence",
    "MORIYA Shige": "moriya-shige",
    "MORIZONO Lesli Jo": "morizono-lesli-jo",
    "MORLEY Annabel": "morley-annabel",
    "MORLEY Bea": "morley-bea",
    "MORLEY Christopher": "morley-christopher",
    "MORLEY Hal": "morley-hal",
    "MORLEY Jill": "morley-jill",
    "MORLEY John": "morley-john",
    "MORLEY Judith": "morley-judith",
    "MORLEY Leonard": "morley-leonard",
    "MORLEY Malcom": "morley-malcom",
    "MORLEY Maureen": "morley-maureen",
    "MORLEY Michael": "morley-michael",
    "MORLEY Robert": "morley-robert",
    "MORLEY Sheridan": "morley-sheridan",
    "MORLEY Simon": "morley-simon",
    "MORLEY Steve": "morley-steve",
    "MORLOCK Frank J": "morlock-frank-j",
    "MORMAN James": "morman-james",
    "MORNIN Daniel": "mornin-daniel",
    "MORO Andrea": "moro-andrea",
    "MOROCCO Paul": "morocco-paul",
    "MORODER Giorgio": "moroder-giorgio",
    "MOROGIELLO John": "morogiello-john",
    "MORONEY Molly": "moroney-molly",
    "MOROSCO Oliver": "morosco-oliver",
    "MOROSS Jerome": "moross-jerome",
    "MOROSSA Mary Beth": "morossa-mary-beth",
    "MOROWITZ Charles": "morowitz-charles",
    "MORPHETT Tony": "morphett-tony",
    "MORPHY-WALSH Hannah": "morphy-walsh-hannah",
    "MORPURGO Michael": "morpurgo-michael",
    "MORPURGO Tatiana": "morpurgo-tatiana",
    "MORREALE, JR Vin": "morreale-jr-vin",
    "MORREY Amelia": "morrey-amelia",
    "MORRILL Katherine": "morrill-katherine",
    "MORRIS Ade": "morris-ade",
    "MORRIS Aldyth": "morris-aldyth",
    "MORRIS Alfred": "morris-alfred",
    "MORRIS Anthony": "morris-anthony",
    "MORRIS Bob": "morris-bob",
    "MORRIS Brent": "morris-brent",
    "MORRIS Carl": "morris-carl",
    "MORRIS Chris": "morris-chris",
    "MORRIS Christopher": "morris-christopher",
    "MORRIS Colin": "morris-colin",
    "MORRIS David": "morris-david",
    "MORRIS David A": "morris-david-a",
    "MORRIS David Evans": "morris-david-evans",
    "MORRIS Deepak": "morris-deepak",
    "MORRIS Deirdra": "morris-deirdra",
    "MORRIS Edmund": "morris-edmund",
    "MORRIS Edna": "morris-edna",
    "MORRIS Eljai": "morris-eljai",
    "MORRIS Emer Mary": "morris-emer-mary",
    "MORRIS Eric William": "morris-eric-william",
    "MORRIS Frank": "morris-frank",
    "MORRIS Gadfan": "morris-gadfan",
    "MORRIS Garrett": "morris-garrett",
    "MORRIS Garry": "morris-garry",
    "MORRIS Genevieve": "morris-genevieve",
    "MORRIS Howard": "morris-howard",
    "MORRIS Hugh": "morris-hugh",
    "MORRIS Jamie": "morris-jamie",
    "MORRIS Jane": "morris-jane",
    "MORRIS Jean": "morris-jean",
    "MORRIS Jennifer": "morris-jennifer",
    "MORRIS Jeremiah": "morris-jeremiah",
    "MORRIS Jill": "morris-jill",
    "MORRIS Jim": "morris-jim",
    "MORRIS John": "morris-john",
    "MORRIS Jon": "morris-jon",
    "MORRIS Joshua": "morris-joshua",
    "MORRIS Kari": "morris-kari",
    "MORRIS Kate": "morris-kate",
    "MORRIS Kate (1)": "morris-kate-1",
    "MORRIS Kenya": "morris-kenya",
    "MORRIS Kim": "morris-kim",
    "MORRIS Libby": "morris-libby",
    "MORRIS Lloyd": "morris-lloyd",
    "MORRIS Lotty": "morris-lotty",
    "MORRIS Louise": "morris-louise",
    "MORRIS Luke": "morris-luke",
    "MORRIS Mary": "morris-mary",
    "MORRIS Mike": "morris-mike",
    "MORRIS Nikolaus": "morris-nikolaus",
    "MORRIS Noelle": "morris-noelle",
    "MORRIS Oliver Llewelyn": "morris-oliver-llewelyn",
    "MORRIS Patricia": "morris-patricia",
    "MORRIS Paul Anthony": "morris-paul-anthony",
    "MORRIS Peter": "morris-peter",
    "MORRIS Peter (1)": "morris-peter-1",
    "MORRIS Peter Charles": "morris-peter-charles",
    "MORRIS Richard (1)": "morris-richard-1",
    "MORRIS Richard (2)": "morris-richard-2",
    "MORRIS Robert": "morris-robert",
    "MORRIS Robert Michael": "morris-robert-michael",
    "MORRIS Ron": "morris-ron",
    "MORRIS Sidney": "morris-sidney",
    "MORRIS Stephen": "morris-stephen",
    "MORRIS Steven Charles": "morris-steven-charles",
    "MORRIS Steven Leigh": "morris-steven-leigh",
    "MORRIS T B": "morris-t-b",
    "MORRIS Tom": "morris-tom",
    "MORRIS Vera": "morris-vera",
    "MORRIS Vernon": "morris-vernon",
    "MORRIS William": "morris-william",
    "MORRIS Zach": "morris-zach",
    "MORRISEAU Dominique": "morriseau-dominique",
    "MORRISON Alick": "morrison-alick",
    "MORRISON Ann": "morrison-ann",
    "MORRISON Anne": "morrison-anne",
    "MORRISON Bill": "morrison-bill",
    "MORRISON Blake": "morrison-blake",
    "MORRISON Conall": "morrison-conall",
    "MORRISON Crysse": "morrison-crysse",
    "MORRISON Danny": "morrison-danny",
    "MORRISON David": "morrison-david",
    "MORRISON David Alan": "morrison-david-alan",
    "MORRISON DElla Rae": "morrison-della-rae",
    "MORRISON Ewan": "morrison-ewan",
    "MORRISON Grant": "morrison-grant",
    "MORRISON Greg": "morrison-greg",
    "MORRISON James": "morrison-james",
    "MORRISON John": "morrison-john",
    "MORRISON John (1)": "morrison-john-1",
    "MORRISON Joshua": "morrison-joshua",
    "MORRISON Julie": "morrison-julie",
    "MORRISON Lillian M": "morrison-lillian-m",
    "MORRISON Margaret": "morrison-margaret",
    "MORRISON Margaret M": "morrison-margaret-m",
    "MORRISON Mary": "morrison-mary",
    "MORRISON Matt": "morrison-matt",
    "MORRISON Megan Alaina": "morrison-megan-alaina",
    "MORRISON Mem": "morrison-mem",
    "MORRISON Nancy Brysson": "morrison-nancy-brysson",
    "MORRISON Nina": "morrison-nina",
    "MORRISON P L": "morrison-p-l",
    "MORRISON Robert": "morrison-robert",
    "MORRISON Sally": "morrison-sally",
    "MORRISON Steve": "morrison-steve",
    "MORRISON Sue": "morrison-sue",
    "MORRISON Suzanne": "morrison-suzanne",
    "MORRISON Terry": "morrison-terry",
    "MORRISON Thomas W": "morrison-thomas-w",
    "MORRISON Toni": "morrison-toni",
    "MORRISON Williams": "morrison-williams",
    "MORRISSETTE Sarah": "morrissette-sarah",
    "MORRISSEY Andrew": "morrissey-andrew",
    "MORRISSEY Dayna": "morrissey-dayna",
    "MORRISSEY Eamon": "morrissey-eamon",
    "MORRISSEY Kim": "morrissey-kim",
    "MORRISSEY Michael": "morrissey-michael",
    "MORRISSEY-FORONDA Laura": "morrissey-foronda-laura",
    "MORRISSON Matt": "morrisson-matt",
    "MORROCK Richard": "morrock-richard",
    "MORRONE Dina": "morrone-dina",
    "MORROW Charlie": "morrow-charlie",
    "MORROW Ellen": "morrow-ellen",
    "MORROW Geoff": "morrow-geoff",
    "MORROW Heather": "morrow-heather",
    "MORROW Hilary": "morrow-hilary",
    "MORROW Melvyn": "morrow-melvyn",
    "MORROW T B": "morrow-t-b",
    "MORROW Thornton": "morrow-thornton",
    "MORROW-BAX Mary": "morrow-bax-mary",
    "MORSE Ben": "morse-ben",
    "MORSE Carl": "morse-carl",
    "MORSE Emily": "morse-emily",
    "MORSE Linda": "morse-linda",
    "MORSE Paul": "morse-paul",
    "MORSE Ralph": "morse-ralph",
    "MORSE Robert H": "morse-robert-h",
    "MORSE Susan": "morse-susan",
    "MORSELL Frederick A": "morsell-frederick-a",
    "MORSHEAD E D A": "morshead-e-d-a",
    "MORSHIEL Geo S": "morshiel-geo-s",
    "MORSS Ben": "morss-ben",
    "MORT Bobby": "mort-bobby",
    "MORT Helen": "mort-helen",
    "MORTENSON Alissa": "mortenson-alissa",
    "MORTIBOY Tabitha": "mortiboy-tabitha",
    "MORTIMER Clare": "mortimer-clare",
    "MORTIMER Colin": "mortimer-colin",
    "MORTIMER Derek": "mortimer-derek",
    "MORTIMER Felix": "mortimer-felix",
    "MORTIMER Glenn": "mortimer-glenn",
    "MORTIMER John": "mortimer-john",
    "MORTIMER Johnnie": "mortimer-johnnie",
    "MORTIMER Peter": "mortimer-peter",
    "MORTIMER Vicki": "mortimer-vicki",
    "MORTIMER-SMITH Roger": "mortimer-smith-roger",
    "MORTLEY Kate": "mortley-kate",
    "MORTON Adam Kelly": "morton-adam-kelly",
    "MORTON Albert W": "morton-albert-w",
    "MORTON Andrew": "morton-andrew",
    "MORTON Andy": "morton-andy",
    "MORTON Billy": "morton-billy",
    "MORTON Bruce": "morton-bruce",
    "MORTON Carlos": "morton-carlos",
    "MORTON Chloe": "morton-chloe",
    "MORTON David": "morton-david",
    "MORTON Francisca": "morton-francisca",
    "MORTON John": "morton-john",
    "MORTON John Maddison": "morton-john-maddison",
    "MORTON Lisa": "morton-lisa",
    "MORTON Michael": "morton-michael",
    "MORTON Richard": "morton-richard",
    "MORTON Sarah": "morton-sarah",
    "MORTON Shane K": "morton-shane-k",
    "MORTON Shiona": "morton-shiona",
    "MORTON William": "morton-william",
    "MORTON-SMITH Tom": "morton-smith-tom",
    "MORUM William": "morum-william",
    "MORUZZI Ros": "moruzzi-ros",
    "MORWEN Emily": "morwen-emily",
    "MORWOOD James": "morwood-james",
    "MOSAKOWSKI Susan": "mosakowski-susan",
    "MOSBACHER Eric": "mosbacher-eric",
    "MOSBY Aaron": "mosby-aaron",
    "MOSCATO Chris Kadis": "moscato-chris-kadis",
    "MOSCHETTI Franco": "moschetti-franco",
    "MOSCHITTO Melissa Fendell": "moschitto-melissa-fendell",
    "MOSCHOS Alexander": "moschos-alexander",
    "MOSCO Maisie": "mosco-maisie",
    "MOSCO Natalie": "mosco-natalie",
    "MOSCONE Jonathan": "moscone-jonathan",
    "MOSCONI Joanne": "mosconi-joanne",
    "MOSCOS George": "moscos-george",
    "MOSCOVITCH Hannah": "moscovitch-hannah",
    "MOSDELL Chris": "mosdell-chris",
    "MOSEL Tad": "mosel-tad",
    "MOSELEY Andy": "moseley-andy",
    "MOSELEY James": "moseley-james",
    "MOSELEY Marian": "moseley-marian",
    "MOSELLE Tyler": "moselle-tyler",
    "MOSER Sonja": "moser-sonja",
    "MOSERE Christine": "mosere-christine",
    "MOSES Carolyn": "moses-carolyn",
    "MOSES Daniel David": "moses-daniel-david",
    "MOSES Itamar": "moses-itamar",
    "MOSES Matt": "moses-matt",
    "MOSES Micealaya": "moses-micealaya",
    "MOSES Miriam": "moses-miriam",
    "MOSHER Susan": "mosher-susan",
    "MOSHEY Michael Douglas": "moshey-michael-douglas",
    "MOSHINA Natalya": "moshina-natalya",
    "MOSHKOVITZ Tzahi": "moshkovitz-tzahi",
    "MOSIER Frank Moffett": "mosier-frank-moffett",
    "MOSKOVICH Yelena": "moskovich-yelena",
    "MOSKOVITZ Shlomi": "moskovitz-shlomi",
    "MOSKOWITZ Cheryl": "moskowitz-cheryl",
    "MOSKOWITZ Jason": "moskowitz-jason",
    "MOSLEY Brigham": "mosley-brigham",
    "MOSLEY Micia": "mosley-micia",
    "MOSLEY Nicholas": "mosley-nicholas",
    "MOSLEY Walter": "mosley-walter",
    "MOSNY Brano": "mosny-brano",
    "MOSS Chloe": "moss-chloe",
    "MOSS Christopher Edward": "moss-christopher-edward",
    "MOSS Dewey": "moss-dewey",
    "MOSS Gregory S": "moss-gregory-s",
    "MOSS Hannah": "moss-hannah",
    "MOSS Holly": "moss-holly",
    "MOSS Howard": "moss-howard",
    "MOSS J Patrick": "moss-j-patrick",
    "MOSS Jeffery": "moss-jeffery",
    "MOSS Jessica": "moss-jessica",
    "MOSS L": "moss-l",
    "MOSS Leland": "moss-leland",
    "MOSS Luke": "moss-luke",
    "MOSS Merrilee": "moss-merrilee",
    "MOSS Michael": "moss-michael",
    "MOSS Michael P": "moss-michael-p",
    "MOSS Nancy": "moss-nancy",
    "MOSS Raymond": "moss-raymond",
    "MOSS Richard": "moss-richard",
    "MOSS Roger S": "moss-roger-s",
    "MOSS Ruth Fennessy": "moss-ruth-fennessy",
    "MOSS Simon": "moss-simon",
    "MOSS Stephanie": "moss-stephanie",
    "MOSS Stephen": "moss-stephen",
    "MOSS Templeton": "moss-templeton",
    "MOSS Warwick": "moss-warwick",
    "MOSS-DALMAU Derran": "moss-dalmau-derran",
    "MOSSE Kate": "mosse-kate",
    "MOSSER Jeffrey": "mosser-jeffrey",
    "MOSSMAN Judith": "mossman-judith",
    "MOSSOP David": "mossop-david",
    "MOSSOUX Nicole": "mossoux-nicole",
    "MOSSOUX-BONTE ": "mossoux-bonte",
    "MOST Bruce W": "most-bruce-w",
    "MOST Glenn W": "most-glenn-w",
    "MOST Stephen": "most-stephen",
    "MOSTYN-BROWN Megan": "mostyn-brown-megan",
    "MOSULISHVILI Mikho": "mosulishvili-mikho",
    "MOTHERLODE ": "motherlode",
    "MOTHERSOLE Louise": "mothersole-louise",
    "MOTHERWELL Laurie": "motherwell-laurie",
    "MOTHERWELL Phil": "motherwell-phil",
    "MOTHOLA Neo": "mothola-neo",
    "MOTION Andrew": "motion-andrew",
    "MOTOJICHO ": "motojicho",
    "MOTOYA Yukiko": "motoya-yukiko",
    "MOTT Alyce": "mott-alyce",
    "MOTT David": "mott-david",
    "MOTTAU Daniel": "mottau-daniel",
    "MOTTLEY Peter": "mottley-peter",
    "MOTTON Gregory": "motton-gregory",
    "MOTTRAM Harry": "mottram-harry",
    "MOTTRAM Stephen": "mottram-stephen",
    "MOTYL Alexander": "motyl-alexander",
    "MOTZ Jeremy": "motz-jeremy",
    "MOUAWAD Wajdi": "mouawad-wajdi",
    "MOUGEL Magali": "mougel-magali",
    "MOUGHON Erin": "moughon-erin",
    "MOUKARZEL Bush": "moukarzel-bush",
    "MOULDEN Ken": "moulden-ken",
    "MOULDER Helen": "moulder-helen",
    "MOULDEY Rohan": "mouldey-rohan",
    "MOULDS Fran": "moulds-fran",
    "MOULDS Steve": "moulds-steve",
    "MOULE Jennifer": "moule-jennifer",
    "MOULIN THEATRE ": "moulin-theatre",
    "MOULTHROP Robert": "moulthrop-robert",
    "MOULTON Carroll": "moulton-carroll",
    "MOULTON Herbert": "moulton-herbert",
    "MOULTON Paul": "moulton-paul",
    "MOUNFIELD David": "mounfield-david",
    "MOUNTAIN Craig": "mountain-craig",
    "MOUNTFORD Charles": "mountford-charles",
    "MOUNTJOY Francis": "mountjoy-francis",
    "MOURAD Kevork": "mourad-kevork",
    "MOUSAWI Dina": "mousawi-dina",
    "MOUSHEY Eileen": "moushey-eileen",
    "MOUSHEY Jacob": "moushey-jacob",
    "MOUSSAFIR Raphaele": "moussafir-raphaele",
    "MOUSSEAU Richard E": "mousseau-richard-e",
    "MOUTHS OF LIONS ": "mouths-of-lions",
    "MOUTI David": "mouti-david",
    "MOUYIS Angelique": "mouyis-angelique",
    "MOUZARKEL Bush": "mouzarkel-bush",
    "MOVE Richard": "move-richard",
    "MOVER Richard": "mover-richard",
    "MOVING BEING PRODUCTIONS ": "moving-being-productions",
    "MOVING PICTURE MIME SHOW ": "moving-picture-mime-show",
    "MOWAT David": "mowat-david",
    "MOWAT John": "mowat-john",
    "MOWAT Nick": "mowat-nick",
    "MOWAT Rick": "mowat-rick",
    "MOWATT Anna Cora": "mowatt-anna-cora",
    "MOWATT John": "mowatt-john",
    "MOWERS David": "mowers-david",
    "MOWSHOWITZ Avi": "mowshowitz-avi",
    "MOXLEY Gina": "moxley-gina",
    "MOY Victoria L": "moy-victoria-l",
    "MOY-BORGEN Lena": "moy-borgen-lena",
    "MOYER Adam": "moyer-adam",
    "MOYER Dan": "moyer-dan",
    "MOYER Geff": "moyer-geff",
    "MOYER Jason": "moyer-jason",
    "MOYES Mark": "moyes-mark",
    "MOYES Patricia": "moyes-patricia",
    "MOYINHAN Elizabeth": "moyinhan-elizabeth",
    "MOYNIHAN Kenny": "moynihan-kenny",
    "MOYO Mzuri": "moyo-mzuri",
    "MOZGA Ilse": "mozga-ilse",
    "MOZGALA Gregg": "mozgala-gregg",
    "MOZO Jeronimo Lopez": "mozo-jeronimo-lopez",
    "MR PUGH'S VELVET GLOVE ": "mr-pughs-velvet-glove",
    "MR SOCIAL CONTROL ": "mr-social-control",
    "MRACEVICH Mark": "mracevich-mark",
    "MRAZ Mars": "mraz-mars",
    "MROCZKA Paul": "mroczka-paul",
    "MROUE Rabih": "mroue-rabih",
    "MROZEK Slawomir": "mrozek-slawomir",
    "MRS ARMSTRONG AND HER AMAZING NAKED SAMOANS ": "mrs-armstrong-and-her-amazing-naked-samoans"
  }
};