export default {
  "metadata": {
    "results": 457,
    "timeStamp": "2025-12-05T21:29:11.081Z",
    "url": "https://www.doollee.com/PlaywrightsM/M_playwrights_s-z.php"
  },
  "authors": {
    "MSAMATI Lucian": "msamati-lucian",
    "MSAMATI Wiina": "msamati-wiina",
    "MSOMI Welcome": "msomi-welcome",
    "MTP PRODUCTIONS ": "mtp-productions",
    "MTSHALI-JONES Thembi": "mtshali-jones-thembi",
    "MTWA Percy": "mtwa-percy",
    "MUAGUTUTI Tanya": "muagututi-tanya",
    "MUAGUTUTI'A Mishelle": "muagututi-a-mishelle",
    "MUASHER Karim": "muasher-karim",
    "MUBASHSHIR Daaimah": "mubashshir-daaimah",
    "MUCEK Sarah": "mucek-sarah",
    "MUDDLE-JUNIPER Pennand": "muddle-juniper-pennand",
    "MUDEN Mandy": "muden-mandy",
    "MUDGE Joy": "mudge-joy",
    "MUDGE Larry": "mudge-larry",
    "MUECKE Douglas": "muecke-douglas",
    "MUEHLECK Chance D": "muehleck-chance-d",
    "MUELLER Carl R": "mueller-carl-r",
    "MUELLER David": "mueller-david",
    "MUELLER Don A": "mueller-don-a",
    "MUELLER Harald": "mueller-harald",
    "MUELLER Lavonne": "mueller-lavonne",
    "MUELLER Lee": "mueller-lee",
    "MUELLER Mark": "mueller-mark",
    "MUELLER Megan": "mueller-megan",
    "MUELLER Ross": "mueller-ross",
    "MUELLER Tobin James": "mueller-tobin-james",
    "MUELLER Wilhelm": "mueller-wilhelm",
    "MUGENSHA TC ": "mugensha-tc",
    "MUGGERIDGE Malcolm": "muggeridge-malcolm",
    "MUGO Micere": "mugo-micere",
    "MUGRIDGE Laura": "mugridge-laura",
    "MUHAMMAD Exavier Wardlaw": "muhammad-exavier-wardlaw",
    "MUHL Karl O": "muhl-karl-o",
    "MUI Andrew": "mui-andrew",
    "MUINZER Louis": "muinzer-louis",
    "MUINZER Thomas": "muinzer-thomas",
    "MUIR Alan": "muir-alan",
    "MUIR Andrew": "muir-andrew",
    "MUIR Cat": "muir-cat",
    "MUIR David": "muir-david",
    "MUIR J K": "muir-j-k",
    "MUIR Jen": "muir-jen",
    "MUIR John": "muir-john",
    "MUIR Kenneth": "muir-kenneth",
    "MUIR Margaret M": "muir-margaret-m",
    "MUIR Sean": "muir-sean",
    "MUIRDEN Dan": "muirden-dan",
    "MUJU CREW ": "muju-crew",
    "MUKASHEVA Roza": "mukasheva-roza",
    "MUKHERJEE Myna": "mukherjee-myna",
    "MUKHERJEE Robin": "mukherjee-robin",
    "MUKHINA Olga": "mukhina-olga",
    "MUKI Mari": "muki-mari",
    "MUKKADAM Ashruf": "mukkadam-ashruf",
    "MULA Shireen": "mula-shireen",
    "MULA Tom": "mula-tom",
    "MULCAHEY Catherine": "mulcahey-catherine",
    "MULCAHY Jane": "mulcahy-jane",
    "MULCAHY Lance": "mulcahy-lance",
    "MULDER Hannah": "mulder-hannah",
    "MULDER Nan": "mulder-nan",
    "MULDOON Paul": "muldoon-paul",
    "MULDOON Roland": "muldoon-roland",
    "MULEI David": "mulei-david",
    "MULEKWA Charles": "mulekwa-charles",
    "MULFORD Toby": "mulford-toby",
    "MULGREW Gerry": "mulgrew-gerry",
    "MULGREW Martin": "mulgrew-martin",
    "MULHALL Deborah": "mulhall-deborah",
    "MULHERN Katy": "mulhern-katy",
    "MULHERON Danny": "mulheron-danny",
    "MULHOLLAND Susan": "mulholland-susan",
    "MULLANE Ann Mary": "mullane-ann-mary",
    "MULLANE Edwin": "mullane-edwin",
    "MULLANEY Tim": "mullaney-tim",
    "MULLARKEY Rory": "mullarkey-rory",
    "MULLEN Carol": "mullen-carol",
    "MULLEN Damian": "mullen-damian",
    "MULLEN Julie": "mullen-julie",
    "MULLEN Karen": "mullen-karen",
    "MULLEN Melissa": "mullen-melissa",
    "MULLER Carl Richard": "muller-carl-richard",
    "MULLER Caroline": "muller-caroline",
    "MULLER Eddie": "muller-eddie",
    "MULLER Elfriede": "muller-elfriede",
    "MULLER Harald": "muller-harald",
    "MULLER Heiner": "muller-heiner",
    "MULLER Janice": "muller-janice",
    "MULLER Jennifer": "muller-jennifer",
    "MULLER Liz": "muller-liz",
    "MULLER Nemeth": "muller-nemeth",
    "MULLER Olivia": "muller-olivia",
    "MULLER R": "muller-r",
    "MULLER Romeo": "muller-romeo",
    "MULLER Sandra": "muller-sandra",
    "MULLER Stefanie": "muller-stefanie",
    "MULLER Stephan": "muller-stephan",
    "MULLER Timothy": "muller-timothy",
    "MULLERY Shane": "mullery-shane",
    "MULLETT Andrew": "mullett-andrew",
    "MULLEY Kate": "mulley-kate",
    "MULLICH Jon": "mullich-jon",
    "MULLIGAN Carmen": "mulligan-carmen",
    "MULLIGAN Harry": "mulligan-harry",
    "MULLIGAN John": "mulligan-john",
    "MULLIGAN Robert S": "mulligan-robert-s",
    "MULLIGAN Sonya": "mulligan-sonya",
    "MULLIN Brian": "mullin-brian",
    "MULLIN Bronwen": "mullin-bronwen",
    "MULLIN Erin": "mullin-erin",
    "MULLIN Molly Ann": "mullin-molly-ann",
    "MULLIN Paul": "mullin-paul",
    "MULLINEAUX Conrad": "mullineaux-conrad",
    "MULLINEAUX Peter": "mullineaux-peter",
    "MULLINO Mark": "mullino-mark",
    "MULLINS Brighde": "mullins-brighde",
    "MULLINS Carol": "mullins-carol",
    "MULLINS Kevin": "mullins-kevin",
    "MULLINS Luke": "mullins-luke",
    "MULLINS Midge": "mullins-midge",
    "MULLINS Robert": "mullins-robert",
    "MULLINS Rosie": "mullins-rosie",
    "MULLINS Sam": "mullins-sam",
    "MULLOWNEY Patric": "mullowney-patric",
    "MULLOY Patrick": "mulloy-patrick",
    "MULLY George": "mully-george",
    "MULRINE Stephen": "mulrine-stephen",
    "MULROY Joseph": "mulroy-joseph",
    "MULROY Robert": "mulroy-robert",
    "MULRYNE Phil": "mulryne-phil",
    "MULTER Karen": "multer-karen",
    "MULTER Steve": "multer-steve",
    "MULVANEY Firestone": "mulvaney-firestone",
    "MULVANY Kate": "mulvany-kate",
    "MULVEY Christopher": "mulvey-christopher",
    "MULVEY Michael": "mulvey-michael",
    "MULVIHILL Michael": "mulvihill-michael",
    "MULVIHILL Susanna": "mulvihill-susanna",
    "MUMENI David": "mumeni-david",
    "MUMFORD Bruce": "mumford-bruce",
    "MUNCASTER David": "muncaster-david",
    "MUNCEY Elizabeth": "muncey-elizabeth",
    "MUNCH Ken": "munch-ken",
    "MUNDAIR Raman": "mundair-raman",
    "MUNDAY Jenny": "munday-jenny",
    "MUNDI Yosef": "mundi-yosef",
    "MUNDLE Sandra": "mundle-sandra",
    "MUNDY James": "mundy-james",
    "MUNDY Joseph": "mundy-joseph",
    "MUNGAVIN Craig": "mungavin-craig",
    "MUNGER C W": "munger-c-w",
    "MUNGER Paul": "munger-paul",
    "MUNIZ Carlos": "muniz-carlos",
    "MUNN Gary": "munn-gary",
    "MUNN Michael": "munn-michael",
    "MUNNERY Simon": "munnery-simon",
    "MUNOZ Aaron": "munoz-aaron",
    "MUNOZ German": "munoz-german",
    "MUNOZ Laura": "munoz-laura",
    "MUNOZ Ray": "munoz-ray",
    "MUNOZ Sam": "munoz-sam",
    "MUNRO Alice": "munro-alice",
    "MUNRO Fiona": "munro-fiona",
    "MUNRO George": "munro-george",
    "MUNRO Ian S": "munro-ian-s",
    "MUNRO Ilona": "munro-ilona",
    "MUNRO James A": "munro-james-a",
    "MUNRO Jamie A": "munro-jamie-a",
    "MUNRO Joe Ward": "munro-joe-ward",
    "MUNRO Julia": "munro-julia",
    "MUNRO Margaret T": "munro-margaret-t",
    "MUNRO Neil": "munro-neil",
    "MUNRO Norm": "munro-norm",
    "MUNRO Robin": "munro-robin",
    "MUNRO Rona": "munro-rona",
    "MUNRO Ronald Fraser": "munro-ronald-fraser",
    "MUNROE Chris": "munroe-chris",
    "MUNROE Jan": "munroe-jan",
    "MUNROW Joe Ward": "munrow-joe-ward",
    "MUNSCH Robert": "munsch-robert",
    "MUNSIL Janet": "munsil-janet",
    "MUNSON Daniel": "munson-daniel",
    "MUNSON Louise": "munson-louise",
    "MUNSON Nigel": "munson-nigel",
    "MUNSON Scott": "munson-scott",
    "MUNYEVU Tonderai": "munyevu-tonderai",
    "MUR Neville": "mur-neville",
    "MURAD Deborah": "murad-deborah",
    "MURAD Majd": "murad-majd",
    "MURAI Yu": "murai-yu",
    "MURAKAMI Erasmus": "murakami-erasmus",
    "MURAKAMI Haruki": "murakami-haruki",
    "MURAKOSHI Suzen": "murakoshi-suzen",
    "MURASHKOVSKY Sophia": "murashkovsky-sophia",
    "MURATA Yuko": "murata-yuko",
    "MURAVITSKY Yury": "muravitsky-yury",
    "MURAYAMA Milton": "murayama-milton",
    "MURCH Edward": "murch-edward",
    "MURCHISON Hugh": "murchison-hugh",
    "MURDOCH Alex": "murdoch-alex",
    "MURDOCH Felicity": "murdoch-felicity",
    "MURDOCH Helen": "murdoch-helen",
    "MURDOCH Iris": "murdoch-iris",
    "MURDOCH Keith": "murdoch-keith",
    "MURDOCH Lynsey": "murdoch-lynsey",
    "MURDOCH Shannon": "murdoch-shannon",
    "MURDOCH Stuart": "murdoch-stuart",
    "MURER Esther Greenleaf": "murer-esther-greenleaf",
    "MURFI Mikel": "murfi-mikel",
    "MURFIN Neil": "murfin-neil",
    "MURFITT Mary": "murfitt-mary",
    "MURIEL Ali": "muriel-ali",
    "MURILLO Carlos": "murillo-carlos",
    "MURJAS Teresa": "murjas-teresa",
    "MURNAK Richard": "murnak-richard",
    "MUROBUSHI Ko": "murobushi-ko",
    "MUROHY Huah": "murohy-huah",
    "MUROLO Giuseppe": "murolo-giuseppe",
    "MURPHET Richard": "murphet-richard",
    "MURPHEY Morgan": "murphey-morgan",
    "MURPHREE Gean": "murphree-gean",
    "MURPHY Aidan": "murphy-aidan",
    "MURPHY Angela": "murphy-angela",
    "MURPHY Anna Maria": "murphy-anna-maria",
    "MURPHY Arthur Lister": "murphy-arthur-lister",
    "MURPHY Benjamin Adair": "murphy-benjamin-adair",
    "MURPHY Bill": "murphy-bill",
    "MURPHY Brenda": "murphy-brenda",
    "MURPHY Brooke": "murphy-brooke",
    "MURPHY Buster": "murphy-buster",
    "MURPHY Caroline": "murphy-caroline",
    "MURPHY Christine": "murphy-christine",
    "MURPHY Clare Muireann": "murphy-clare-muireann",
    "MURPHY Colin": "murphy-colin",
    "MURPHY Colleen": "murphy-colleen",
    "MURPHY Dallas": "murphy-dallas",
    "MURPHY Dan": "murphy-dan",
    "MURPHY Dana": "murphy-dana",
    "MURPHY Danny": "murphy-danny",
    "MURPHY Darren": "murphy-darren",
    "MURPHY David": "murphy-david",
    "MURPHY Dermot": "murphy-dermot",
    "MURPHY Elaine": "murphy-elaine",
    "MURPHY Elizabeth": "murphy-elizabeth",
    "MURPHY Emily": "murphy-emily",
    "MURPHY Gabrielle": "murphy-gabrielle",
    "MURPHY Gerald": "murphy-gerald",
    "MURPHY Gerald P": "murphy-gerald-p",
    "MURPHY Greg": "murphy-greg",
    "MURPHY Gregory": "murphy-gregory",
    "MURPHY Hannah": "murphy-hannah",
    "MURPHY Harrison": "murphy-harrison",
    "MURPHY Hugh": "murphy-hugh",
    "MURPHY Hugh M": "murphy-hugh-m",
    "MURPHY Imelda": "murphy-imelda",
    "MURPHY Jack": "murphy-jack",
    "MURPHY James B": "murphy-james-b",
    "MURPHY Jeremiah": "murphy-jeremiah",
    "MURPHY Jill": "murphy-jill",
    "MURPHY Jimmy": "murphy-jimmy",
    "MURPHY Joe": "murphy-joe",
    "MURPHY John": "murphy-john",
    "MURPHY John Paul": "murphy-john-paul",
    "MURPHY Justin": "murphy-justin",
    "MURPHY Katherine": "murphy-katherine",
    "MURPHY Keith": "murphy-keith",
    "MURPHY Kevin": "murphy-kevin",
    "MURPHY Lee": "murphy-lee",
    "MURPHY Lindsay Joy": "murphy-lindsay-joy",
    "MURPHY Maeve": "murphy-maeve",
    "MURPHY Mark": "murphy-mark",
    "MURPHY Martin": "murphy-martin",
    "MURPHY Martin (1)": "murphy-martin-1",
    "MURPHY Marty": "murphy-marty",
    "MURPHY Mary Ann": "murphy-mary-ann",
    "MURPHY Matt   ": "murphy-matt",
    "MURPHY Michael": "murphy-michael",
    "MURPHY Mikel": "murphy-mikel",
    "MURPHY Nicole": "murphy-nicole",
    "MURPHY Owen": "murphy-owen",
    "MURPHY Paul": "murphy-paul",
    "MURPHY Peter": "murphy-peter",
    "MURPHY Phyllis": "murphy-phyllis",
    "MURPHY R D": "murphy-r-d",
    "MURPHY R G": "murphy-r-g",
    "MURPHY Rebecca": "murphy-rebecca",
    "MURPHY Robert": "murphy-robert",
    "MURPHY Sarah": "murphy-sarah",
    "MURPHY Scott": "murphy-scott",
    "MURPHY Sean": "murphy-sean",
    "MURPHY Simon": "murphy-simon",
    "MURPHY Stephen \"Spud\"": "murphy-stephen-spud",
    "MURPHY Stephen L": "murphy-stephen-l",
    "MURPHY Susan": "murphy-susan",
    "MURPHY Thomas": "murphy-thomas",
    "MURPHY Tim C": "murphy-tim-c",
    "MURPHY Timothy": "murphy-timothy",
    "MURPHY Tom": "murphy-tom",
    "MURPHY Tommy": "murphy-tommy",
    "MURPHY Vincent": "murphy-vincent",
    "MURPHY Vinnie": "murphy-vinnie",
    "MURPHY-GIBB Dwina": "murphy-gibb-dwina",
    "MURRAY Angela": "murray-angela",
    "MURRAY Braham": "murray-braham",
    "MURRAY Brendan": "murray-brendan",
    "MURRAY Charles": "murray-charles",
    "MURRAY Craig": "murray-craig",
    "MURRAY David Largman": "murray-david-largman",
    "MURRAY Diedre L": "murray-diedre-l",
    "MURRAY Donald S": "murray-donald-s",
    "MURRAY Elizabeth": "murray-elizabeth",
    "MURRAY Elspeth": "murray-elspeth",
    "MURRAY Gerald Majella": "murray-gerald-majella",
    "MURRAY Gilbert": "murray-gilbert",
    "MURRAY Henry": "murray-henry",
    "MURRAY Iain": "murray-iain",
    "MURRAY Jack": "murray-jack",
    "MURRAY Jed": "murray-jed",
    "MURRAY Jeff": "murray-jeff",
    "MURRAY Jeremiah": "murray-jeremiah",
    "MURRAY Jillian": "murray-jillian",
    "MURRAY Jim": "murray-jim",
    "MURRAY Joan": "murray-joan",
    "MURRAY Joel": "murray-joel",
    "MURRAY Joey": "murray-joey",
    "MURRAY John": "murray-john",
    "MURRAY John (1)": "murray-john-1",
    "MURRAY Joseph": "murray-joseph",
    "MURRAY K E": "murray-k-e",
    "MURRAY Kenny": "murray-kenny",
    "MURRAY Lavinia": "murray-lavinia",
    "MURRAY Mark": "murray-mark",
    "MURRAY Melainie J": "murray-melainie-j",
    "MURRAY Melissa": "murray-melissa",
    "MURRAY Michael": "murray-michael",
    "MURRAY Nadira": "murray-nadira",
    "MURRAY Nancy": "murray-nancy",
    "MURRAY Neil": "murray-neil",
    "MURRAY P": "murray-p",
    "MURRAY Paul": "murray-paul",
    "MURRAY Peta": "murray-peta",
    "MURRAY Robert": "murray-robert",
    "MURRAY Ruaraidh": "murray-ruaraidh",
    "MURRAY Stephen": "murray-stephen",
    "MURRAY Stephen (2)": "murray-stephen-2",
    "MURRAY Steve": "murray-steve",
    "MURRAY Sue": "murray-sue",
    "MURRAY T C": "murray-t-c",
    "MURRAY Thomas": "murray-thomas",
    "MURRAY Tom": "murray-tom",
    "MURRAY Wendy": "murray-wendy",
    "MURRAY William": "murray-william",
    "MURRAY-SMITH Joanna": "murray-smith-joanna",
    "MURRAY-WALKER Jeanne": "murray-walker-jeanne",
    "MURRELL Andrew": "murrell-andrew",
    "MURRELL John": "murrell-john",
    "MURRIN Tom": "murrin-tom",
    "MURSY L H": "mursy-l-h",
    "MURTAGH Ciaran": "murtagh-ciaran",
    "MURTAGH Hugh": "murtagh-hugh",
    "MURTAGH Joe": "murtagh-joe",
    "MURTHA Megan": "murtha-megan",
    "MURUYAMA Milton": "muruyama-milton",
    "MUSAPHIA Joseph": "musaphia-joseph",
    "MUSCARA Joe": "muscara-joe",
    "MUSCHAMP Catherine": "muschamp-catherine",
    "MUSCHAMP Thomas": "muschamp-thomas",
    "MUSCHELL David": "muschell-david",
    "MUSGRAVE Ben": "musgrave-ben",
    "MUSGROVE Dan": "musgrove-dan",
    "MUSGROVE Rachel": "musgrove-rachel",
    "MUSHABAC Jane": "mushabac-jane",
    "MUSIAL John": "musial-john",
    "MUSIC Rachel": "music-rachel",
    "MUSIC THEATRE WALES ": "music-theatre-wales",
    "MUSICO Valentino": "musico-valentino",
    "MUSIL Robert": "musil-robert",
    "MUSIOL Krissi": "musiol-krissi",
    "MUSK Adam": "musk-adam",
    "MUSKARIA Amanita": "muskaria-amanita",
    "MUSSELMAN Forrest": "musselman-forrest",
    "MUSSMANN Linda": "mussmann-linda",
    "MUSSO Joe": "musso-joe",
    "MUSTAQIYM Tyriq": "mustaqiym-tyriq",
    "MUSTATEA Kat M": "mustatea-kat-m",
    "MUSTILLO Louis": "mustillo-louis",
    "MUSTO Edward": "musto-edward",
    "MUSTOO Terence": "mustoo-terence",
    "MUSZKATBLIT Ronit": "muszkatblit-ronit",
    "MUTCH David": "mutch-david",
    "MUTE PANTOMIME THEATRE ": "mute-pantomime-theatre",
    "MUTH Lara": "muth-lara",
    "MUTHY Nessah Aisha": "muthy-nessah-aisha",
    "MUTINO Pamela Palmer": "mutino-pamela-palmer",
    "MUTLOATSE Mothobi": "mutloatse-mothobi",
    "MUTONE Matthew": "mutone-matthew",
    "MUTRUX Floyd": "mutrux-floyd",
    "MUTZ Philip": "mutz-philip",
    "MUXART Magali": "muxart-magali",
    "MUZ Julie Atlas": "muz-julie-atlas",
    "MWALIM ": "mwalim",
    "MWALUKO Nick": "mwaluko-nick",
    "MWANZA Ntonga": "mwanza-ntonga",
    "MWINE Ntare": "mwine-ntare",
    "MYAMORI Asataro": "myamori-asataro",
    "MYATT Anna": "myatt-anna",
    "MYATT Julie Marie": "myatt-julie-marie",
    "MYATT Paul": "myatt-paul",
    "MYERS Al": "myers-al",
    "MYERS Bernard": "myers-bernard",
    "MYERS Bruce": "myers-bruce",
    "MYERS Carolyn": "myers-carolyn",
    "MYERS Daniel": "myers-daniel",
    "MYERS David": "myers-david",
    "MYERS G R": "myers-g-r",
    "MYERS Henry": "myers-henry",
    "MYERS Jeffrey R": "myers-jeffrey-r",
    "MYERS Johnny": "myers-johnny",
    "MYERS Larry D": "myers-larry-d",
    "MYERS Lee": "myers-lee",
    "MYERS Lisa": "myers-lisa",
    "MYERS Lori M": "myers-lori-m",
    "MYERS Lucas": "myers-lucas",
    "MYERS Madeline Sarah": "myers-madeline-sarah",
    "MYERS Matt": "myers-matt",
    "MYERS Nick A": "myers-nick-a",
    "MYERS Peter": "myers-peter",
    "MYERS Richard": "myers-richard",
    "MYERS Robert": "myers-robert",
    "MYERS Roger P": "myers-roger-p",
    "MYERS Rosemary": "myers-rosemary",
    "MYERS Rupert": "myers-rupert",
    "MYERS Sarah": "myers-sarah",
    "MYERS Sky": "myers-sky",
    "MYERS Stanley": "myers-stanley",
    "MYERS Tanya": "myers-tanya",
    "MYERS Terry": "myers-terry",
    "MYERS Tyler B": "myers-tyler-b",
    "MYERS Walter Dean": "myers-walter-dean",
    "MYERS-MORGAN Bob": "myers-morgan-bob",
    "MYERSON Jesse Alexander": "myerson-jesse-alexander",
    "MYERSON Jonathan": "myerson-jonathan",
    "MYHILL Guy": "myhill-guy",
    "MYHILL John": "myhill-john",
    "MYLER Randal": "myler-randal",
    "MYLES Bruce": "myles-bruce",
    "MYLES Lynda": "myles-lynda",
    "MYLES Nick": "myles-nick",
    "MYNNE David": "mynne-david",
    "MYOI Yoko": "myoi-yoko",
    "MYRING Dorothy": "myring-dorothy",
    "MYROCEK ": "myrocek",
    "MYROUP Ronald Krine": "myroup-ronald-krine",
    "MYRTLE Amy": "myrtle-amy",
    "MYTHEN Sue": "mythen-sue",
    "MYTTON Liz": "mytton-liz"
  }
};