export default {
  "metadata": {
    "results": 521,
    "timeStamp": "2025-12-05T21:29:14.951Z",
    "url": "https://www.doollee.com/PlaywrightsN/N_playwrights_a-f.php"
  },
  "authors": {
    "NA Chuck": "na-chuck",
    "NAB Judith": "nab-judith",
    "NABBEAU Paul": "nabbeau-paul",
    "NABBEN John Anthony": "nabben-john-anthony",
    "NABEL Bill": "nabel-bill",
    "NABERS Janine": "nabers-janine",
    "NABOKOV Dmitri": "nabokov-dmitri",
    "NABOKOV Vladimir": "nabokov-vladimir",
    "NACHBAR Martin": "nachbar-martin",
    "NACHTMANN Rita": "nachtmann-rita",
    "NACHTRIEB Peter Sinn": "nachtrieb-peter-sinn",
    "NACOL Shawn": "nacol-shawn",
    "NACTHMANN Rita": "nacthmann-rita",
    "NADAL Kevin": "nadal-kevin",
    "NADA-RAJA Rebecca": "nada-raja-rebecca",
    "NADARAJAH Nadia": "nadarajah-nadia",
    "NADA-RAJAH Uma": "nada-rajah-uma",
    "NADASI Mia": "nadasi-mia",
    "NADEAU Michel": "nadeau-michel",
    "NADEN Cathy": "naden-cathy",
    "NADJ Josef": "nadj-josef",
    "NADLER Mark": "nadler-mark",
    "NADOUCE Philippe": "nadouce-philippe",
    "NAEEM Awatif": "naeem-awatif",
    "NAESS Petter": "naess-petter",
    "NAEYMI Samara": "naeymi-samara",
    "NAFTALI Joseph": "naftali-joseph",
    "NAGAI Ai": "nagai-ai",
    "NAGARKAR Kiran": "nagarkar-kiran",
    "NAGEL Werner": "nagel-werner",
    "NAGIM Farid": "nagim-farid",
    "NAGLE Jamie": "nagle-jamie",
    "NAGLE John": "nagle-john",
    "NAGLE Linda": "nagle-linda",
    "NAGLE Maggie": "nagle-maggie",
    "NAGLE Mary Kathryn": "nagle-mary-kathryn",
    "NAGLE Rosa": "nagle-rosa",
    "NAGORSKI Eva": "nagorski-eva",
    "NAGRIN Lee": "nagrin-lee",
    "NAGY Andras": "nagy-andras",
    "NAGY Estep": "nagy-estep",
    "NAGY Phyllis": "nagy-phyllis",
    "NAHAT Dennis": "nahat-dennis",
    "NAIAMBANA Patrice": "naiambana-patrice",
    "NAIDOO Beverley": "naidoo-beverley",
    "NAIL Robert": "nail-robert",
    "NAILS Jen": "nails-jen",
    "NAIR Karthika": "nair-karthika",
    "NAISH John": "naish-john",
    "NAJERA Rick": "najera-rick",
    "NAJIB Taher": "najib-taher",
    "NAJIMY Kathy": "najimy-kathy",
    "NAKA Katie": "naka-katie",
    "NAKAGAWA Masaye Okano": "nakagawa-masaye-okano",
    "NAKAMURA Aya": "nakamura-aya",
    "NAKANO Keiko": "nakano-keiko",
    "NAKAS Kestutis": "nakas-kestutis",
    "NAKASE Justine": "nakase-justine",
    "NAKATSUJI Hiroshi": "nakatsuji-hiroshi",
    "NAKAYASU Sawako": "nakayasu-sawako",
    "NAKLI Laith": "nakli-laith",
    "NALEBUFF Rachel Kaunder": "nalebuff-rachel-kaunder",
    "NALKOWSKA Zofia": "nalkowska-zofia",
    "NALLON Steve": "nallon-steve",
    "NAMAN Natalia": "naman-natalia",
    "NAMANWORTH Phillip L": "namanworth-phillip-l",
    "NAMIAND A": "namiand-a",
    "NAMIOKA Lensey": "namioka-lensey",
    "NAMM Devorah": "namm-devorah",
    "NAMM Diane": "namm-diane",
    "NAMMI Edward": "nammi-edward",
    "NANCE Catherine": "nance-catherine",
    "NANI Paolo": "nani-paolo",
    "NANIN Odalys": "nanin-odalys",
    "NANKIN St John": "nankin-st-john",
    "NANNI Giordano": "nanni-giordano",
    "NANNI Greg": "nanni-greg",
    "NANNI-MESSEGEE Lisa Marie": "nanni-messegee-lisa-marie",
    "NANNINGA Josh": "nanninga-josh",
    "NANTO David": "nanto-david",
    "NANTSOU Stefo": "nantsou-stefo",
    "NANUS Susan": "nanus-susan",
    "NAOGEORGUS Thomas": "naogeorgus-thomas",
    "NAPHTALI Amani": "naphtali-amani",
    "NAPIER Edward": "napier-edward",
    "NAPIER L D": "napier-l-d",
    "NAPIER Marshall": "napier-marshall",
    "NAPIER-BROWN Michael": "napier-brown-michael",
    "NAPOLI Jeanne": "napoli-jeanne",
    "NAPOLIN Leah": "napolin-leah",
    "NAPOLITANO Kara Ayn": "napolitano-kara-ayn",
    "NAPOLITANO Peter": "napolitano-peter",
    "NAPPI Nicholas": "nappi-nicholas",
    "NAPTHINE David": "napthine-david",
    "NAQUIN Bob": "naquin-bob",
    "NARANG Tracey Knight": "narang-tracey-knight",
    "NARASAKI Ken": "narasaki-ken",
    "NARAT Nakib": "narat-nakib",
    "NARENS Sherry": "narens-sherry",
    "NARESH Purva": "naresh-purva",
    "NARITA Jude": "narita-jude",
    "NARKLE Geoffrey": "narkle-geoffrey",
    "NARKUNSKI Michael": "narkunski-michael",
    "NAROGIN Mudrooroo": "narogin-mudrooroo",
    "NARTER David": "narter-david",
    "NARVER Allison": "narver-allison",
    "NASCIMENTO Roberto": "nascimento-roberto",
    "NASH Amber": "nash-amber",
    "NASH Ian": "nash-ian",
    "NASH Jane": "nash-jane",
    "NASH Jon": "nash-jon",
    "NASH Juliana": "nash-juliana",
    "NASH N Richard": "nash-n-richard",
    "NASH Ogden": "nash-ogden",
    "NASH Pamela": "nash-pamela",
    "NASH Phil": "nash-phil",
    "NASH Rob": "nash-rob",
    "NASH Rod": "nash-rod",
    "NASH Roderick Boyd": "nash-roderick-boyd",
    "NASH Ron": "nash-ron",
    "NASH Stephen": "nash-stephen",
    "NASH Susan": "nash-susan",
    "NASHMAN Adam": "nashman-adam",
    "NASHMAN Alan": "nashman-alan",
    "NASHMAN Alon": "nashman-alon",
    "NASIRU Akanji": "nasiru-akanji",
    "NASKOVA Elena": "naskova-elena",
    "NASON Bernadette": "nason-bernadette",
    "NASON Bryan": "nason-bryan",
    "NASR Carmen": "nasr-carmen",
    "NASS Elyse": "nass-elyse",
    "NASSA Avi": "nassa-avi",
    "NASSAR Mark": "nassar-mark",
    "NASSAU Paul": "nassau-paul",
    "NASSAUER Sharon": "nassauer-sharon",
    "NASSER Lana": "nasser-lana",
    "NASSER Roger": "nasser-roger",
    "NASSIF Robert Lindsey": "nassif-robert-lindsey",
    "NASSIVERA John": "nassivera-john",
    "NASSRI Rahaleh": "nassri-rahaleh",
    "NATAL Gael": "natal-gael",
    "NATALE Michele": "natale-michele",
    "NATALIE Angelo": "natalie-angelo",
    "NATANSON Jan": "natanson-jan",
    "NATARAJ Nirmala": "nataraj-nirmala",
    "NATARAJAN Meena": "natarajan-meena",
    "NATHAN Ansuya": "nathan-ansuya",
    "NATHAN Mark": "nathan-mark",
    "NATHAN Martin": "nathan-martin",
    "NATHAN Paul": "nathan-paul",
    "NATHAN Paul S": "nathan-paul-s",
    "NATHAN Richard": "nathan-richard",
    "NATHAN Vijay": "nathan-vijay",
    "NATHANIEL Indra": "nathaniel-indra",
    "NATHANIEL Linda": "nathaniel-linda",
    "NATHANSON Daniele": "nathanson-daniele",
    "NATHANSON Michael": "nathanson-michael",
    "NATION Terry": "nation-terry",
    "NATIONAL THEATER OF THE UNITED STATES OF AMERICA, THE ": "national-theater-usa",
    "NATOLI Anthony": "natoli-anthony",
    "NATSUI Takahiro": "natsui-takahiro",
    "NATTINO Luciano": "nattino-luciano",
    "NATTRASS Nicolle Trixie": "nattrass-nicolle-trixie",
    "NATURAL THEATRE COMPANY ": "natural-theatre-company",
    "NATURE THEATER OF OKLAHOMA ": "nature-theater-of-oklahoma",
    "NAUFFTS Geoffrey": "nauffts-geoffrey",
    "NAUGHTON Bill": "naughton-bill",
    "NAUGHTON James": "naughton-james",
    "NAUGHTON Joseph P": "naughton-joseph-p",
    "NAVARRA Lynn": "navarra-lynn",
    "NAVARRE Alan": "navarre-alan",
    "NAVARRE Yves": "navarre-yves",
    "NAVARRO Cambell": "navarro-cambell",
    "NAVARRO J Oconer": "navarro-j-oconer",
    "NAVARRO Ophilia": "navarro-ophilia",
    "NAVARRO AMADOR Maria del Puy": "navarro-amador-maria-del-puy",
    "NAVAS Eduardo": "navas-eduardo",
    "NAVE Bill": "nave-bill",
    "NAVIDAR Nahal": "navidar-nahal",
    "NAVO Cheryl": "navo-cheryl",
    "NAVOA James Nelson": "navoa-james-nelson",
    "NAWALOWALO Nina": "nawalowalo-nina",
    "NAWRAS Joshua": "nawras-joshua",
    "NAWROCKI Lila Louise": "nawrocki-lila-louise",
    "NAYAK Pradhuman": "nayak-pradhuman",
    "NAYDAN Michael M": "naydan-michael-m",
    "NAYFACK Shakina": "nayfack-shakina",
    "NAYLOR Clem": "naylor-clem",
    "NAYLOR Hattie": "naylor-hattie",
    "NAYLOR Henry": "naylor-henry",
    "NAYLOR Koryn": "naylor-koryn",
    "NAYLOR Molly": "naylor-molly",
    "NAYLOR Sophia": "naylor-sophia",
    "NAYO Barbara": "nayo-barbara",
    "NAZARENO May": "nazareno-may",
    "NAZARETH H O": "nazareth-h-o",
    "NAZAYKINSKAYA Polina": "nazaykinskaya-polina",
    "NAZLI Leyla": "nazli-leyla",
    "NDABA Smal": "ndaba-smal",
    "NDHLOVU Richard": "ndhlovu-richard",
    "NDIAYE Marie": "ndiaye-marie",
    "NDLOVU Duma": "ndlovu-duma",
    "NDUKWE Iheke": "ndukwe-iheke",
    "NEACE Sandra Brunell": "neace-sandra-brunell",
    "NEADS Jennifer": "neads-jennifer",
    "NEAGLE Anthea": "neagle-anthea",
    "NEAL Andrew": "neal-andrew",
    "NEAL Jennifer": "neal-jennifer",
    "NEAL Laura": "neal-laura",
    "NEAL Lori M": "neal-lori-m",
    "NEAL Rebecca": "neal-rebecca",
    "NEALE Jonathan": "neale-jonathan",
    "NEALE Zora": "neale-zora",
    "NEAR Stephen": "near-stephen",
    "NEARING Dawn": "nearing-dawn",
    "NEARY Jack": "neary-jack",
    "NEAT Annie": "neat-annie",
    "NEATE Patrick": "neate-patrick",
    "NEATH Glen": "neath-glen",
    "NEAVE C N": "neave-c-n",
    "NEBLETT Robert": "neblett-robert",
    "NEBLETT Shaun": "neblett-shaun",
    "NECESSARY Joseph Ryan": "necessary-joseph-ryan",
    "NECHWATAL Shae": "nechwatal-shae",
    "NEDBOY Marty": "nedboy-marty",
    "NEDVED William": "nedved-william",
    "NEE Little John": "nee-little-john",
    "NEE Phil": "nee-phil",
    "NEEDCOMPANY ": "needcompany",
    "NEEDHAM James": "needham-james",
    "NEEDHAM Kylie": "needham-kylie",
    "NEEDHAM Linda S": "needham-linda-s",
    "NEEDHAM Peter": "needham-peter",
    "NEEDHAM Tom": "needham-tom",
    "NEEDLE Jan": "needle-jan",
    "NEEDLEMAN Felicia": "needleman-felicia",
    "NEEDLES Dan": "needles-dan",
    "NEEDS Malcolm": "needs-malcolm",
    "NEEL K Brian": "neel-k-brian",
    "NEELS Chris": "neels-chris",
    "NEELY Evron": "neely-evron",
    "NEER Daniel": "neer-daniel",
    "NEESON Eoin": "neeson-eoin",
    "NEFF Angela": "neff-angela",
    "NEFF Debra": "neff-debra",
    "NEFF Esther": "neff-esther",
    "NEFF Matthew": "neff-matthew",
    "NEGATIVEQUITY ": "negativequity",
    "NEGBAUER Gary": "negbauer-gary",
    "NEGIN Louis": "negin-louis",
    "NEGRI Anne Catherine": "negri-anne-catherine",
    "NEGRIN David": "negrin-david",
    "NEGRON Taylor": "negron-taylor",
    "NEHAMEN Craig": "nehamen-craig",
    "NEHAMEN Dennis": "nehamen-dennis",
    "NEHLS David": "nehls-david",
    "NEHRING Larry": "nehring-larry",
    "NEIDEN Daniel": "neiden-daniel",
    "NEIDERMAN Michael": "neiderman-michael",
    "NEIDERMYER Dan": "neidermyer-dan",
    "NEIDJIE Bill": "neidjie-bill",
    "NEIL Alison": "neil-alison",
    "NEIL Andrew": "neil-andrew",
    "NEIL Chris": "neil-chris",
    "NEIL Deanna": "neil-deanna",
    "NEIL Janet Moran": "neil-janet-moran",
    "NEIL Jason": "neil-jason",
    "NEIL Jonathan": "neil-jonathan",
    "NEILAN John": "neilan-john",
    "NEILD Davied": "neild-davied",
    "NEILD Geoffrey": "neild-geoffrey",
    "NEILD Mary": "neild-mary",
    "NEILD Tom": "neild-tom",
    "NEILL Hallie": "neill-hallie",
    "NEILL Laura": "neill-laura",
    "NEILL Rob": "neill-rob",
    "NEILL Tom": "neill-tom",
    "NEILSEN Ted": "neilsen-ted",
    "NEILSON Anthony": "neilson-anthony",
    "NEILSON David": "neilson-david",
    "NEILSON Jane": "neilson-jane",
    "NEILSON K": "neilson-k",
    "NEILSON PJ": "neilson-pj",
    "NEILSON-GATTEY C": "neilson-gattey-c",
    "NEIMAN Andrew Michael": "neiman-andrew-michael",
    "NEIMAN Gilbert": "neiman-gilbert",
    "NEIMAN Irving Gaynor": "neiman-irving-gaynor",
    "NEIMANIS Mara": "neimanis-mara",
    "NEIPRIS David": "neipris-david",
    "NEIPRIS Janet L": "neipris-janet-l",
    "NEITHARDT Vanessa Lenz": "neithardt-vanessa-lenz",
    "NEJMAN Regina": "nejman-regina",
    "NELEGA Alina": "nelega-alina",
    "NELL DUBUS Elizabeth": "nell-dubus-elizabeth",
    "NELLHAUS Gerhard": "nellhaus-gerhard",
    "NELLIE TINDER ": "nellie-tinder",
    "NELLOR Daniel": "nellor-daniel",
    "NELLORE Usha": "nellore-usha",
    "NELMS Henning": "nelms-henning",
    "NELSEN Duane": "nelsen-duane",
    "NELSON Andrea": "nelson-andrea",
    "NELSON Anne": "nelson-anne",
    "NELSON Benno": "nelson-benno",
    "NELSON Bill": "nelson-bill",
    "NELSON Bill David": "nelson-bill-david",
    "NELSON Carl Alfred": "nelson-carl-alfred",
    "NELSON Carolyn": "nelson-carolyn",
    "NELSON Char": "nelson-char",
    "NELSON Claris": "nelson-claris",
    "NELSON Connie": "nelson-connie",
    "NELSON D Bennett": "nelson-d-bennett",
    "NELSON Daniel Allen": "nelson-daniel-allen",
    "NELSON David Lee": "nelson-david-lee",
    "NELSON Eva": "nelson-eva",
    "NELSON Fred": "nelson-fred",
    "NELSON Greg": "nelson-greg",
    "NELSON Hemmendy": "nelson-hemmendy",
    "NELSON Herbert": "nelson-herbert",
    "NELSON Hunter": "nelson-hunter",
    "NELSON Ian C": "nelson-ian-c",
    "NELSON Jemma": "nelson-jemma",
    "NELSON Jennifer L": "nelson-jennifer-l",
    "NELSON Joni": "nelson-joni",
    "NELSON Joshua": "nelson-joshua",
    "NELSON June": "nelson-june",
    "NELSON Kate": "nelson-kate",
    "NELSON Keith": "nelson-keith",
    "NELSON Lynn Wells": "nelson-lynn-wells",
    "NELSON Mary Elliott": "nelson-mary-elliott",
    "NELSON Michael": "nelson-michael",
    "NELSON Mike": "nelson-mike",
    "NELSON Patrick": "nelson-patrick",
    "NELSON Paul B": "nelson-paul-b",
    "NELSON Richard": "nelson-richard",
    "NELSON Robert Lawrence": "nelson-robert-lawrence",
    "NELSON Robert P": "nelson-robert-p",
    "NELSON Ronald Trifer": "nelson-ronald-trifer",
    "NELSON Ross Peter": "nelson-ross-peter",
    "NELSON Sandy": "nelson-sandy",
    "NELSON Sarah": "nelson-sarah",
    "NELSON Schaeffer": "nelson-schaeffer",
    "NELSON Stanley": "nelson-stanley",
    "NELSON Steve": "nelson-steve",
    "NELSON Tim Blake": "nelson-tim-blake",
    "NEMEC Gale": "nemec-gale",
    "NEMEC Jim": "nemec-jim",
    "NEMEC III James": "nemec-iii-james",
    "NEMEROV Howard": "nemerov-howard",
    "NEMETH Akos": "nemeth-akos",
    "NEMETH Ildiko": "nemeth-ildiko",
    "NEMETH Kevin": "nemeth-kevin",
    "NEMETH Sally": "nemeth-sally",
    "NEMIROFF Robert": "nemiroff-robert",
    "NEMSER Alexander": "nemser-alexander",
    "NEMSER Ian": "nemser-ian",
    "NENCINI Flaminio": "nencini-flaminio",
    "NEOFOTIS Peter": "neofotis-peter",
    "NEOPHYTOU Gioros": "neophytou-gioros",
    "NERBOSO Sarah": "nerboso-sarah",
    "NERENBERG Lloyd": "nerenberg-lloyd",
    "NERESIAN Arthur": "neresian-arthur",
    "NERI Barbara": "neri-barbara",
    "NERLAND Marie": "nerland-marie",
    "NERSESIAN Arthur": "nersesian-arthur",
    "NERSKA Alexander": "nerska-alexander",
    "NERY Peter Solis": "nery-peter-solis",
    "NESBITT Caroline": "nesbitt-caroline",
    "NESBITT Vivian": "nesbitt-vivian",
    "NESENGER Dickey": "nesenger-dickey",
    "NESIN Aziz": "nesin-aziz",
    "NESKOVSKI Bill": "neskovski-bill",
    "NESMITH Nathaniel G": "nesmith-nathaniel-g",
    "NESPOR Kelly": "nespor-kelly",
    "NESS Angela": "ness-angela",
    "NESS Erinina Marie": "ness-erinina-marie",
    "NESS Ethan": "ness-ethan",
    "NESTOR Eddie": "nestor-eddie",
    "NESTOR Larry": "nestor-larry",
    "NESTOR Ray James": "nestor-ray-james",
    "NESTROY Johann": "nestroy-johann",
    "NESVET Rebecca": "nesvet-rebecca",
    "NESVET Rebecca L": "nesvet-rebecca-l",
    "NETANYAHU Iddo": "netanyahu-iddo",
    "NETTLES Joyce": "nettles-joyce",
    "NETTLES ARTISTS COLLECTIVE ": "nettles-artists-collective",
    "NETZBAND Germaine": "netzband-germaine",
    "NETZEL Sally": "netzel-sally",
    "NEU Jim": "neu-jim",
    "NEUBAUER Adam": "neubauer-adam",
    "NEUBAUER Laura": "neubauer-laura",
    "NEUBERG Matt": "neuberg-matt",
    "NEUBRAND Christina": "neubrand-christina",
    "NEUDSTADT Gabriel": "neudstadt-gabriel",
    "NEUGROSCHEL Joachim": "neugroschel-joachim",
    "NEUHAUS Christian": "neuhaus-christian",
    "NEUMAN Colleen": "neuman-colleen",
    "NEUMAN Jeffrey": "neuman-jeffrey",
    "NEUMANN Alfred": "neumann-alfred",
    "NEUMANN Justus": "neumann-justus",
    "NEUMANN Steve": "neumann-steve",
    "NEUMARK-JONES Robert": "neumark-jones-robert",
    "NEUNER Christopher Thomas": "neuner-christopher-thomas",
    "NEURERBURG Stephanie": "neurerburg-stephanie",
    "NEUSS Carla": "neuss-carla",
    "NEUSTADT Gabriel": "neustadt-gabriel",
    "NEUWIRTH Olga": "neuwirth-olga",
    "NEUWIRTH Vivian": "neuwirth-vivian",
    "NEVAER Louis E V": "nevaer-loui-e-v",
    "NEVAREZ Nancy": "nevarez-nancy",
    "NEVEROW Irma J": "neverow-irma-j",
    "NEVES Abel": "neves-abel",
    "NEVEU Brett": "neveu-brett",
    "NEVEUX Georges": "neveux-georges",
    "NEVILL Maggie": "nevill-maggie",
    "NEVILLE Angela": "neville-angela",
    "NEVILLE Ann": "neville-ann",
    "NEVILLE David Ian": "neville-david-ian",
    "NEVILLE Edgar": "neville-edgar",
    "NEVILLE Edward": "neville-edward",
    "NEVILLE Michael": "neville-michael",
    "NEVILLE-SMITH Chris": "neville-smith-chris",
    "NEVIN Erik": "nevin-erik",
    "NEVIN Maureen": "nevin-maureen",
    "NEVINSON Nigel": "nevinson-nigel",
    "NEVITS Tim": "nevits-tim",
    "NEVITT Roy": "nevitt-roy",
    "NEVIUS Craig J": "nevius-craig-j",
    "NEW Chris": "new-chris",
    "NEW Joel B": "new-joel-b",
    "NEW INTERNATIONAL ENCOUNTER ": "new-international-encounter",
    "NEW PARADISE LABORATORIES ": "new-paradise-laboratories",
    "NEW STAGE THEATRE COMPANY ": "new-stage-theatre-company",
    "NEW STRIDES THEATRE ": "new-strides-theatre",
    "NEW THEATRE COMPANY ": "new-theatre-company",
    "NEW WONDERTWINS ": "new-wondertwins",
    "NEWALL Anthony": "newall-anthony",
    "NEWALL George": "newall-george",
    "NEWALL Helen": "newall-helen",
    "NEWALL John": "newall-john",
    "NEWBERRY Elizabeth": "newberry-elizabeth",
    "NEWBIGIN Nerida": "newbigin-nerida",
    "NEWBOLD Debs": "newbold-debs",
    "NEWBOLD Mike": "newbold-mike",
    "NEWBORN Emma": "newborn-emma",
    "NEWBORN Kristin": "newborn-kristin",
    "NEWBOUND Bernard Slade": "newbound-bernard-slade",
    "NEWBOUND Chris": "newbound-chris",
    "NEWBURGE David": "newburge-david",
    "NEWBY Thomas": "newby-thomas",
    "NEWCASTLE Anthony": "newcastle-anthony",
    "NEWCOMB Sarah": "newcomb-sarah",
    "NEWCOMBE Paul": "newcombe-paul",
    "NEWCOMER David M": "newcomer-david-m",
    "NEWELL Angela": "newell-angela",
    "NEWELL Anna": "newell-anna",
    "NEWELL Brian": "newell-brian",
    "NEWELL Martha Hill": "newell-martha-hill",
    "NEWELL Neil K": "newell-neil-k",
    "NEWENS Margaret": "newens-margaret",
    "NEWFIELD Anthony": "newfield-anthony",
    "NEWKIRK Dee Ann": "newkirk-dee-ann",
    "NEWKIRK W H": "newkirk-w-h",
    "NEWKIRK William L": "newkirk-william-l",
    "NEWLAND Courttia": "newland-courttia",
    "NEWLAR Mary": "newlar-mary",
    "NEWLEY Anthony": "newley-anthony",
    "NEWLYN Victoria": "newlyn-victoria",
    "NEWMAN Ben": "newman-ben",
    "NEWMAN Benjamin": "newman-benjamin",
    "NEWMAN Craig": "newman-craig",
    "NEWMAN David": "newman-david",
    "NEWMAN Deborah": "newman-deborah",
    "NEWMAN Eric": "newman-eric",
    "NEWMAN Fred": "newman-fred",
    "NEWMAN G F": "newman-g-f",
    "NEWMAN Greatrex": "newman-greatrex",
    "NEWMAN Harley": "newman-harley",
    "NEWMAN Heather": "newman-heather",
    "NEWMAN Jerry": "newman-jerry",
    "NEWMAN John": "newman-john",
    "NEWMAN Katin": "newman-katin",
    "NEWMAN Michael": "newman-michael",
    "NEWMAN Molly": "newman-molly",
    "NEWMAN Neal J": "newman-neal-j",
    "NEWMAN Nick": "newman-nick",
    "NEWMAN Paul": "newman-paul",
    "NEWMAN Peter R": "newman-peter-r",
    "NEWMAN Phyllis": "newman-phyllis",
    "NEWMAN Randy": "newman-randy",
    "NEWMAN Rex": "newman-rex",
    "NEWMAN Richard C": "newman-richard-c",
    "NEWMAN Robert": "newman-robert",
    "NEWMAN Sol": "newman-sol",
    "NEWMAN Steve": "newman-steve",
    "NEWMAN Terry": "newman-terry",
    "NEWMAN Tommy": "newman-tommy",
    "NEWMAN-HOLDEN John": "newman-holden-john",
    "NEWMAN-STOREN Renee": "newman-storen-renee",
    "NEWMARK Louise": "newmark-louise",
    "NEWMEIR John H": "newmeir-john-h",
    "NEWNHAM R": "newnham-r",
    "NEWPORT Conrad": "newport-conrad",
    "NEWPORT Elaina": "newport-elaina",
    "NEWSOME Herb": "newsome-herb",
    "NEWSOME Meg": "newsome-meg",
    "NEWSON Lloyd": "newson-lloyd",
    "NEWTON Adela": "newton-adela",
    "NEWTON Alan": "newton-alan",
    "NEWTON Gregory Lyle": "newton-gregory-lyle",
    "NEWTON Heather": "newton-heather",
    "NEWTON James": "newton-james",
    "NEWTON Lara Foot": "newton-lara-foot",
    "NEWTON Lionel": "newton-lionel",
    "NEWTON Nate": "newton-nate",
    "NEWTON Rebecca": "newton-rebecca",
    "NEWTON Robert G": "newton-robert-g",
    "NEWTON Tim": "newton-tim",
    "NEWTON Tony": "newton-tony",
    "NEY Diane": "ney-diane",
    "NEY Richard": "ney-richard",
    "NEYENS Harry": "neyens-harry"
  }
};