export default {
  "metadata": {
    "results": 189,
    "timeStamp": "2025-12-05T21:29:15.900Z",
    "url": "https://www.doollee.com/PlaywrightsN/N_playwrights_g-l.php"
  },
  "authors": {
    "NG Amy": "ng-amy",
    "NG Daniel": "ng-daniel",
    "NG John": "ng-john",
    "NG Kevin": "ng-kevin",
    "NGAI Serin": "ngai-serin",
    "NGCOBO James": "ngcobo-james",
    "NGEMA Mbongeni": "ngema-mbongeni",
    "NGO Pip": "ngo-pip",
    "NGOC Nguyen thi Minh": "ngoc-nguyen-thi-minh",
    "NGOSI Jahmar": "ngosi-jahmar",
    "NGUGI wa Thiong'o": "ngugi-wa-thiong-o",
    "NGUYEN Anh": "nguyen-anh",
    "NGUYEN Barry": "nguyen-barry",
    "NGUYEN Derek": "nguyen-derek",
    "NGUYEN Don": "nguyen-don",
    "NGUYEN Duy": "nguyen-duy",
    "NGUYEN Hung": "nguyen-hung",
    "NGUYEN Huong": "nguyen-huong",
    "NGUYEN Linh Thuy": "nguyen-linh-thuy",
    "NGUYEN Qui": "nguyen-qui",
    "NGUYEN Thao P": "nguyen-thao-p",
    "NHAN Ngo Thanh": "nhan-ngo-thanh",
    "NHUONG Huynh Quang": "nhuong-huynh-quang",
    "NI CHAOIMH Bairbre": "ni-chaoimh-bairbre",
    "NI CHUIRC Ciara": "ni-chuirc-ciara",
    "NI DHOMHNAILL Nuala": "ni-dhomhnaill-nuala",
    "NI RIAIN Ailis": "ni-riain-ailis",
    "NIBLOCK Phill Bill": "niblock-phill-bill",
    "NIBLOCK Robert": "niblock-robert",
    "NICCODEMI D": "niccodemi-d",
    "NICE Chuck": "nice-chuck",
    "NICE Pamela": "nice-pamela",
    "NICERSON Jerrell": "nicerson-jerrell",
    "NICHOL James W": "nichol-james-w",
    "NICHOL John": "nichol-john",
    "NICHOL Phil": "nichol-phil",
    "NICHOL Robin": "nichol-robin",
    "NICHOLAS Anna": "nicholas-anna",
    "NICHOLAS Clifford": "nicholas-clifford",
    "NICHOLAS Denise": "nicholas-denise",
    "NICHOLAS Glynn": "nicholas-glynn",
    "NICHOLAS Lindsey": "nicholas-lindsey",
    "NICHOLAS Rama": "nicholas-rama",
    "NICHOLAS Siobhan": "nicholas-siobhan",
    "NICHOLAS Teddy": "nicholas-teddy",
    "NICHOLAS Tom": "nicholas-tom",
    "NICHOLL Don": "nicholl-don",
    "NICHOLL Richard": "nicholl-richard",
    "NICHOLLS Benjamin": "nicholls-benjamin",
    "NICHOLLS Casey": "nicholls-casey",
    "NICHOLLS Claire": "nicholls-claire",
    "NICHOLLS David": "nicholls-david",
    "NICHOLLS Derek": "nicholls-derek",
    "NICHOLLS Gareth": "nicholls-gareth",
    "NICHOLLS Tony": "nicholls-tony",
    "NICHOLS Adriana Sevahn": "nichols-adriana-sevahn",
    "NICHOLS Anne": "nichols-anne",
    "NICHOLS Bonnie Jean": "nichols-bonnie-jean",
    "NICHOLS David": "nichols-david",
    "NICHOLS Dawson": "nichols-dawson",
    "NICHOLS Diane Therese": "nichols-diane-therese",
    "NICHOLS Glen Freeman": "nichols-glen-freeman",
    "NICHOLS Glynn": "nichols-glynn",
    "NICHOLS J": "nichols-j",
    "NICHOLS Kelly": "nichols-kelly",
    "NICHOLS Mark": "nichols-mark",
    "NICHOLS Marlene": "nichols-marlene",
    "NICHOLS Mike": "nichols-mike",
    "NICHOLS Nina daVinci": "nichols-nina-davinci",
    "NICHOLS Peter": "nichols-peter",
    "NICHOLS Stephen": "nichols-stephen",
    "NICHOLS Trey": "nichols-trey",
    "NICHOLSON David": "nicholson-david",
    "NICHOLSON Ian": "nicholson-ian",
    "NICHOLSON James": "nicholson-james",
    "NICHOLSON Jessie": "nicholson-jessie",
    "NICHOLSON John": "nicholson-john",
    "NICHOLSON Kenyon": "nicholson-kenyon",
    "NICHOLSON Lydia": "nicholson-lydia",
    "NICHOLSON Nicole": "nicholson-nicole",
    "NICHOLSON Paul": "nicholson-paul",
    "NICHOLSON Sara L": "nicholson-sara-l",
    "NICHOLSON William": "nicholson-william",
    "NICKEL John-Paul": "nickel-john-paul",
    "NICKENS Michelle R": "nickens-michelle-r",
    "NICKI Kendall": "nicki-kendall",
    "NICKLIN Andrew": "nicklin-andrew",
    "NICKLIN Hannah": "nicklin-hannah",
    "NICKOWITZ Peter": "nickowitz-peter",
    "NICKOWITZ Peter Barr": "nickowitz-peter-barr",
    "NICKSON Guy": "nickson-guy",
    "NICKSON Susan": "nickson-susan",
    "NICOL Alex": "nicol-alex",
    "NICOL Eric": "nicol-eric",
    "NICOL Eve": "nicol-eve",
    "NICOL Ron": "nicol-ron",
    "NICOLA James B": "nicola-james-b",
    "NICOLA ": "nicola",
    "NICOLAEFF Ariadne": "nicolaeff-ariadne",
    "NICOLAJ Aldo": "nicolaj-aldo",
    "NICOLESCU Mihael": "nicolescu-mihael",
    "NICOLINI Gianfranco": "nicolini-gianfranco",
    "NICOLL Lisa": "nicoll-lisa",
    "NICOLL Lisa (1)": "nicoll-lisa-1",
    "NICOLO Daniela": "nicolo-daniela",
    "NICOLS Maggie": "nicols-maggie",
    "NICOSIA Christina": "nicosia-christina",
    "NICOSON William": "nicoson-william",
    "NICOTRA Robert": "nicotra-robert",
    "NIE THEATRE ": "nie-theatre",
    "NIEBLING Doug": "niebling-doug",
    "NIEDERKORN William S": "niederkorn-william-s",
    "NIEDERMAN Michael": "niederman-michael",
    "NIEL Mark": "niel-mark",
    "NIELD David": "nield-david",
    "NIELD Maureen": "nield-maureen",
    "NIELD Sarah": "nield-sarah",
    "NIELDS David": "nields-david",
    "NIELSEN Alan": "nielsen-alan",
    "NIELSEN Anthony": "nielsen-anthony",
    "NIELSEN Lance": "nielsen-lance",
    "NIELSON Camilla": "nielson-camilla",
    "NIELSON Mark": "nielson-mark",
    "NIELSON Matthew": "nielson-matthew",
    "NIEMAN Christie": "nieman-christie",
    "NIEMAN Patty": "nieman-patty",
    "NIEMI Loren": "niemi-loren",
    "NIEMI Wayne": "niemi-wayne",
    "NIERENBERG Amelia Jane": "nierenberg-amelia-jane",
    "NIERING Christine": "niering-christine",
    "NIERLE Joe": "nierle-joe",
    "NIESEN Jim": "niesen-jim",
    "NIEVA Francisco": "nieva-francisco",
    "NIEVES Mel": "nieves-mel",
    "NIEVES-POWELL Linda": "nieves-powell-linda",
    "NIGGLI Josephine": "niggli-josephine",
    "NIGHTINGALE Emily": "nightingale-emily",
    "NIGRO Bob": "nigro-bob",
    "NIGRO Don": "nigro-don",
    "NIGRO Shaw": "nigro-shaw",
    "NIHIL T G": "nihil-t-g",
    "NIJJAR Steve": "nijjar-steve",
    "NIKHAMINA Kasia": "nikhamina-kasia",
    "NIKI Petre": "niki-petre",
    "NIKIFOROVA Victoria": "nikiforova-victoria",
    "NIKIFORUK Clay": "nikiforuk-clay",
    "NIKKO Kurt": "nikko-kurt",
    "NIKOLAJ Aldo": "nikolaj-aldo",
    "NIKOLCHEV Anthony": "nikolchev-anthony",
    "NIKOLOVA Iskra": "nikolova-iskra",
    "NIKORA Olga": "nikora-olga",
    "NILAND Bryan": "niland-bryan",
    "NILSSON Anna": "nilsson-anna",
    "NILSSON Byron": "nilsson-byron",
    "NILSSON Harry": "nilsson-harry",
    "NIMCHUK Michael John": "nimchuk-michael-john",
    "NIMMANNIT Sophie": "nimmannit-sophie",
    "NIMMO Heather": "nimmo-heather",
    "NIMMO Paul": "nimmo-paul",
    "NIMMO Stuart": "nimmo-stuart",
    "NIMOY Leonard": "nimoy-leonard",
    "NIN Caroline": "nin-caroline",
    "NINO Jairo Aniba": "nino-jairo-aniba",
    "NIPKOW Leslie": "nipkow-leslie",
    "NIR Phoebe": "nir-phoebe",
    "NIRENBERG Richard D": "nirenberg-richard-d",
    "NISENSON Aja": "nisenson-aja",
    "NISHIDA Toyoko": "nishida-toyoko",
    "NISHIKAWA Lane": "nishikawa-lane",
    "NISHIKAWA-HIRANO Miki": "nishikawa-hirano-miki",
    "NISHIMURA Masayo": "nishimura-masayo",
    "NISSEN Brian": "nissen-brian",
    "NISSENSON Gloria": "nissenson-gloria",
    "NITZBERG Julien": "nitzberg-julien",
    "NIVEN Kristine": "niven-kristine",
    "NIXON Carl": "nixon-carl",
    "NIXON Graeme": "nixon-graeme",
    "NIXON Jane": "nixon-jane",
    "NIXON Joseph": "nixon-joseph",
    "NIXON Luke": "nixon-luke",
    "NIXON Melody": "nixon-melody",
    "NIXON Oliva": "nixon-oliva",
    "NIXON Paul": "nixon-paul",
    "NIXON Peter": "nixon-peter",
    "NIXON Rob": "nixon-rob",
    "NIXON Roz": "nixon-roz",
    "NIXON Sarah A": "nixon-sarah-a",
    "NIXON-LLOYD Wyatt": "nixon-lloyd-wyatt",
    "NKOSI Lewis": "nkosi-lewis"
  }
};