export default {
  "metadata": {
    "results": 427,
    "timeStamp": "2025-12-05T21:29:27.050Z",
    "url": "https://www.doollee.com/PlaywrightsO/O_playwrights_a-f.php"
  },
  "authors": {
    "O Annie": "o-annie",
    "O BEIRN Seamus": "o-beirn-seamus",
    "O BRIAIN Art": "o-briain-art",
    "O BRIAIN Liam": "o-briain-liam",
    "O BRIAIN Michael": "o-briain-michael",
    "O BRIAIN Sean": "o-briain-sean",
    "O BRIEN John Edward": "o-brien-john-edward",
    "O BROIN Brian": "o-broin-brian",
    "O BROIN Leon": "o-broin-leon",
    "O BROIN Risteard": "o-broin-risteard",
    "O BROIN Ruairi": "o-broin-ruairi",
    "O BROIN Sean": "o-broin-sean",
    "O BROITHE Padraig": "o-broithe-padraig",
    "O CAIREALLAIN Gearoid": "o-caireallain-gearoid",
    "O CARRA Sean": "o-carra-sean",
    "O CATHAIN Muiris": "o-cathain-muiris",
    "O CATHAIN Padraig": "o-cathain-padraig",
    "O CEALLAIGH Liam": "o-ceallaigh-liam",
    "O CEALLAIGH Micheal": "o-ceallaigh-micheal",
    "O CEALLAIGH Rafael": "o-ceallaigh-rafael",
    "O CEALLAIGH Sean": "o-ceallaigh-sean",
    "O CEALLAIGH Tomas": "o-ceallaigh-tomas",
    "O CEARBHAILL Padraig": "o-cearbhaill-padraig",
    "O CIARGHUSA Colm": "o-ciarghusa-colm",
    "O CIARGHUSA Sean": "o-ciarghusa-sean",
    "O CLOCHARTAIGH Trevor": "o-clochartaigh-trevor",
    "O COISDEALBHA Sean": "o-coisdealbha-sean",
    "O CONAILL Bearnard": "o-conaill-bearnard",
    "O CONAILL Ciaran": "o-conaill-ciaran",
    "O CONAIRE Padraic": "o-conaire-padraic",
    "O CONAIRE Padraig Og": "o-conaire-padraig-og",
    "O CONAOLA Dara": "o-conaola-dara",
    "O CONCHUBHAIR Liam": "o-conchubhair-liam",
    "O CONCHUBHAIR Sean": "o-conchubhair-sean",
    "O CONCHUBHAIR Sean-Shean": "o-conchubhair-sean-shean",
    "O CONCHUIR Bosco": "o-conchuir-bosco",
    "O CONGHAILE Caoimhghin": "o-conghaile-caoimhghin",
    "O CONGHAILE Micheal": "o-conghaile-micheal",
    "O CORRBHUI Coilin": "o-corrbhui-coilin",
    "O CORRBUI Mairtin": "o-corrbui-mairtin",
    "O CREATHAIN Micheal": "o-creathain-micheal",
    "O CROININ Partholan": "o-croinin-partholan",
    "O CUILL Donal": "o-cuill-donal",
    "O CUINN Aindrias": "o-cuinn-aindrias",
    "O CUIV Shan": "o-cuiv-shan",
    "O CULAIN Peadar": "o-culain-peadar",
    "O DALAIGH Colm": "o-dalaigh-colm",
    "O DIOLUIN Tomas": "o-dioluin-tomas",
    "O DIREAIN Mairtin": "o-direain-mairtin",
    "O DOIBHLIN Breandan": "o-doibhlin-breandan",
    "O DOMHNAILL Aodh": "o-domhnaill-aodh",
    "O DOMHNAILL Liam": "o-domhnaill-liam",
    "O DOMHNAILL Maghnus": "o-domhnaill-maghnus",
    "O DOMHNAILL Padraig": "o-domhnaill-padraig",
    "O DONNCHADHA Tadhg": "o-donnchadha-tadhg",
    "O DROIGHNEAIN Micheal": "o-droighneain-micheal",
    "O DUBHGAIN Aodh": "o-dubhgain-aodh",
    "O DUIRINNE Seamus": "o-duirinne-seamus",
    "O FARACHAIN Roibeard": "o-farachain-roibeard",
    "O FATHARTA Macdara": "o-fatharta-macdara",
    "O FEINNEADHA P": "o-feinneadha-p",
    "O FLAITHEARTA Tom Saili": "o-flaithearta-tom-saili",
    "O FLATHARTA Antoine": "o-flatharta-antoine",
    "O FLOINN Criostoir": "o-floinn-criostoir",
    "O FOGHLU Colm": "o-foghlu-colm",
    "O FOGHLUDHA Risteard": "o-foghludha-risteard",
    "O FOGHLUDHA Sean": "o-foghludha-sean",
    "O GALLCHOIR Aindrias": "o-gallchoir-aindrias",
    "O GALLCHOIR Brid": "o-gallchoir-brid",
    "O GAORA Padraig": "o-gaora-padraig",
    "O GIOLLAGAIN Padhraig": "o-giollagain-padhraig",
    "O GOLDMAN A E": "o-goldman-a-e",
    "O GRIOFA Micheal": "o-griofa-micheal",
    "O HAIRT Padraig": "o-hairt-padraig",
    "O HALMHAIN Diarmuid": "o-halmhain-diarmuid",
    "O HANNRACHAIN Fachtna": "o-hannrachain-fachtna",
    "O HANNRACHAIN Peadar": "o-hannrachain-peadar",
    "O HAODHA Micheal": "o-haodha-micheal",
    "O HAODHA Seamus": "o-haodha-seamus",
    "O HAODHA Seamus (1)": "o-haodha-seamus-1",
    "O HAONGHUSA Traolach": "o-haonghusa-traolach",
    "O HEAGHRA Breandan": "o-heaghra-breandan",
    "O HEALUIGHTHE Tomas": "o-healuighthe-tomas",
    "O HEIDIRSCEOIL Sean": "o-heidirsceoil-sean",
    "O HEIGEARTAIGH Sean": "o-heigeartaigh-sean",
    "O HEIGHNEACHAIN Tomas": "o-heighneachain-tomas",
    "O HEITHIR Breandan": "o-heithir-breandan",
    "O HOGAIN Sean": "o-hogain-sean",
    "O HORAIN Sean": "o-horain-sean",
    "O HUAITHNE Daithi": "o-huaithne-daithi",
    "O LABHRADHA Alphonsus": "o-labhradha-alphonsus",
    "O LAIGHLEIS Re": "o-laighleis-re",
    "O LAOGHAIRE Liam": "o-laoghaire-liam",
    "O LOCHLAINN Gearoid": "o-lochlainn-gearoid",
    "O LOCHLAINN Sean": "o-lochlainn-sean",
    "O LOINGSIGH Amhlaoibh": "o-loingsigh-amhlaoibh",
    "O LOINGSIGH Fionan": "o-loingsigh-fionan",
    "O MAILLE Tomas S": "o-maille-tomas-s",
    "O MAOILEOIN Brian": "o-maoileoin-brian",
    "O MAONAIGH Proinsias": "o-maonaigh-proinsias",
    "O MATHUNA Coiril": "o-mathuna-coiril",
    "O MIODHACHAIN Proinsias": "o-miodhachain-proinsias",
    "O MORAIN An Canonach P": "o-morain-an-canonach-p",
    "O MUIRCHEARTAIGH Tomas": "o-muircheartaigh-tomas",
    "O MUIRTHILE Liam": "o-muirthile-liam",
    "O MUIRTHUILE Sean": "o-muirthuile-sean",
    "O MURCHADHA Diarmuid": "o-murchadha-diarmuid",
    "O MURCHU Liam": "o-murchu-liam",
    "O NEACHTAIN Eoghan": "o-neachtain-eoghan",
    "O NEACHTAIN Joe Steve": "o-neachtain-joe-steve",
    "O NEACHTAIN Padraig": "o-neachtain-padraig",
    "O NEACHTAIN Sean": "o-neachtain-sean",
    "O NEILL Eoghan": "o-neill-eoghan",
    "O NEILL Seamus": "o-neill-seamus",
    "O RAGHALLAIGH Caoimhin": "o-raghallaigh-caoimhin",
    "O RAGHALLAIGH Tomas": "o-raghallaigh-tomas",
    "O RAITHBHEARTAIGH Traolach": "o-raithbheartaigh-traolach",
    "O RIADA Sean": "o-riada-sean",
    "O RIAGAIN Brian": "o-riagain-brian",
    "O RIAIN Liam P": "o-riain-liam-p",
    "O RINN Liam": "o-rinn-liam",
    "O RIORDAIN Aodhan": "o-riordain-aodhan",
    "O RIORDAIN Domhnall": "o-riordain-domhnall",
    "O SCANAILL Tadhg": "o-scanaill-tadhg",
    "O SCOLAI Darach": "o-scolai-darach",
    "O SCOLAI Seamas": "o-scolai-seamas",
    "O SEAGHDHA Diarmuid": "o-seaghdha-diarmuid",
    "O SEAGHDHA Micheal": "o-seaghdha-micheal",
    "O SEAGHDHA Padraig": "o-seaghdha-padraig",
    "O SEAGHDHA Seamus": "o-seaghdha-seamus",
    "O SEARCAIGH Cathal": "o-searcaigh-cathal",
    "O SEOIGHE Tadhg S": "o-seoighe-tadhg-s",
    "O SIOCHFHRADHA Micheal": "o-siochfhradha-micheal",
    "O SIOCHFHRADHA Padraig": "o-siochfhradha-padraig",
    "O SIOCHRU Padraig": "o-siochru-padraig",
    "O SIORDAIN Niall": "o-siordain-niall",
    "O SLEIBHIN Gearoid": "o-sleibhin-gearoid",
    "O SNODAIGH Padraig": "o-snodaigh-padraig",
    "O SUILLEABHAIN Diarmuid (1)": "o-suilleabhain-diarmuid-1",
    "O SUILLEABHAIN Diarmuid (2)": "o-suilleabhain-diarmuid-2",
    "O SUILLEABHAIN Eoin": "o-suilleabhain-eoin",
    "O SUILLEABHAIN Micheal (2)": "o-suilleabhain-micheal-2",
    "O SUILLEABHAIN Micheal (3)": "o-suilleabhain-micheal-3",
    "O SUILLEABHAIN S": "o-suilleabhain-s",
    "O SUILLEABHAIN S L": "o-suilleabhain-s-l",
    "O SUILLEABHAIN Tomas": "o-suilleabhain-tomas",
    "O TALLAMHANN S": "o-tallamhann-s",
    "O TIGHEARNAIGH Gearoid": "o-tighearnaigh-gearoid",
    "O TUAIRISC Eoghan": "o-tuairisc-eoghan",
    "O TUAIRISC Padraig": "o-tuairisc-padraig",
    "O TUAMA Con": "o-tuama-con",
    "O TUAMA Seamus": "o-tuama-seamus",
    "O TUAMA Sean": "o-tuama-sean",
    "O TUAMA Tadhg": "o-tuama-tadhg",
    "OADES Roslyn": "oades-roslyn",
    "OAKES Bill": "oakes-bill",
    "OAKES Jimmy": "oakes-jimmy",
    "OAKES Kevin": "oakes-kevin",
    "OAKES Meredith": "oakes-meredith",
    "OAKES Michael": "oakes-michael",
    "OAKES Roy": "oakes-roy",
    "OAKES Russell J": "oakes-russell-j",
    "OAKES Vanessa": "oakes-vanessa",
    "OAKFIELD Tice": "oakfield-tice",
    "OAKLAND Ben": "oakland-ben",
    "OAKLEIGH Helen": "oakleigh-helen",
    "OAKLEY Barry": "oakley-barry",
    "OAKLEY George William": "oakley-george-william",
    "OAKLEY Mark Adrian": "oakley-mark-adrian",
    "OAKS John Thomas": "oaks-john-thomas",
    "OASTLER Henry": "oastler-henry",
    "OATES Alex": "oates-alex",
    "OATES Debbie": "oates-debbie",
    "OATES Joyce Carol": "oates-joyce-carol",
    "OATMAN Michael": "oatman-michael",
    "OBA Tunde": "oba-tunde",
    "OBAFEMI Olu": "obafemi-olu",
    "OBAN James": "oban-james",
    "OBANO Rex": "obano-rex",
    "OBARZANEK Gideon": "obarzanek-gideon",
    "OBASEKI Pedro": "obaseki-pedro",
    "OBASI Chuk": "obasi-chuk",
    "OBEDZINSKI Paul": "obedzinski-paul",
    "OBEIDALLAH Dean": "obeidallah-dean",
    "OBENEY Russell": "obeney-russell",
    "OBERACKER Richard": "oberacker-richard",
    "OBERFELDER Jody": "oberfelder-jody",
    "OBERG Richard": "oberg-richard",
    "OBERHAUSER Michael": "oberhauser-michael",
    "OBERMAN Sheldon": "oberman-sheldon",
    "OBERMAN Steven": "oberman-steven",
    "OBERMAN Tracy-Ann": "oberman-tracy-ann",
    "OBERMEIER Gerlinde": "obermeier-gerlinde",
    "OBERNDORFER Cory": "oberndorfer-cory",
    "OBERZAN Zachary": "oberzan-zachary",
    "OBEXER Margareth": "obexer-margareth",
    "OBEY Andre": "obey-andre",
    "OBIORA Chudi": "obiora-chudi",
    "OBISESAN Gbolahan": "obisesan-gbolahan",
    "OBLER Arch": "obler-arch",
    "OBLONGATA Donna": "oblongata-donna",
    "OBOLENSKY Kira": "obolensky-kira",
    "OBOLENSKY Masha": "obolensky-masha",
    "OBOLER Arch": "oboler-arch",
    "O'BOYLE Cis": "o-boyle-cis",
    "O'BOYLE John": "o-boyle-john",
    "O'BRANAGAIN Finn": "o-branagain-finn",
    "OBRENSKI Eve": "obrenski-eve",
    "O'BRIAIN BELL Rory": "o-briain-bell-rory",
    "O'BRIAN Ben": "o-brian-ben",
    "O'BRIEN Barret": "o-brien-barret",
    "O'BRIEN Caraid": "o-brien-caraid",
    "O'BRIEN Conor Cruise": "o-brien-conor-cruise",
    "O'BRIEN Dan": "o-brien-dan",
    "O'BRIEN Daniel": "o-brien-daniel",
    "O'BRIEN Daniel Richard": "o-brien-daniel-richard",
    "O'BRIEN Dara": "o-brien-dara",
    "O'BRIEN Eddie": "o-brien-eddie",
    "O'BRIEN Edna": "o-brien-edna",
    "O'BRIEN Elizabeth": "o-brien-elizabeth",
    "O'BRIEN Eric": "o-brien-eric",
    "O'BRIEN Eugene": "o-brien-eugene",
    "O'BRIEN Felix": "o-brien-felix",
    "O'BRIEN Flann": "o-brien-flann",
    "O'BRIEN Glenn": "o-brien-glenn",
    "O'BRIEN Jack": "o-brien-jack",
    "O'BRIEN Jaime": "o-brien-jaime",
    "O'BRIEN Jami": "o-brien-jami",
    "O'BRIEN John": "o-brien-john",
    "O'BRIEN John (1)": "o-brien-john-1",
    "O'BRIEN John Edward": "o-brien-john-edward",
    "O'BRIEN John Emmett": "o-brien-john-emmett",
    "O'BRIEN Julianne": "o-brien-julianne",
    "O'BRIEN Juliet": "o-brien-juliet",
    "O'BRIEN Justin": "o-brien-justin",
    "O'BRIEN Kate": "o-brien-kate",
    "O'BRIEN Liam": "o-brien-liam",
    "O'BRIEN Lorraine": "o-brien-lorraine",
    "O'BRIEN Lucy": "o-brien-lucy",
    "O'BRIEN Matte": "o-brien-matte",
    "O'BRIEN Maureen": "o-brien-maureen",
    "O'BRIEN Michael": "o-brien-michael",
    "O'BRIEN Michael (1)": "o-brien-michael-1",
    "O'BRIEN Michael (2)": "o-brien-michael-2",
    "O'BRIEN Paul": "o-brien-paul",
    "O'BRIEN Richard": "o-brien-richard",
    "O'BRIEN Robert": "o-brien-robert",
    "O'BRIEN Sean": "o-brien-sean",
    "O'BRIEN Sean (1)": "o-brien-sean-1",
    "O'BRIEN Sharon": "o-brien-sharon",
    "O'BRIEN Tim": "o-brien-tim",
    "O'BRIEN Tom": "o-brien-tom",
    "O'BRIEN Tom (1)": "o-brien-tom-1",
    "O'BRIEN Tom (2)": "o-brien-tom-2",
    "O'BRYANT Richard": "o-bryant-richard",
    "OBST Lynda": "obst-lynda",
    "O'BYRNE Joe": "o-byrne-joe",
    "O'BYRNE Joe (1)": "o-byrne-joe-1",
    "O'CALLAGHAN Briony": "o-callaghan-briony",
    "O'CALLAGHAN Jill": "o-callaghan-jill",
    "O'CALLAGHAN Ruth": "o-callaghan-ruth",
    "O'CARROLL Brendan": "o-carroll-brendan",
    "O'CARROLL Dean": "o-carroll-dean",
    "O'CARROLL Eilish": "o-carroll-eilish",
    "O'CARROLL Gavin": "o-carroll-gavin",
    "O'CARROLL Harriet": "o-carroll-harriet",
    "O'CASEY Sean": "o-casey-sean",
    "OCHI Yoshiaki": "ochi-yoshiaki",
    "OCHWAT Daniel Theodore": "ochwat-daniel-theodore",
    "OCKERBY Nerissa": "ockerby-nerissa",
    "OCKHAM'S RAZOR ": "ockhams-razor",
    "OCKRENT Ben": "ockrent-ben",
    "OCKRENT Mike": "ockrent-mike",
    "OCKS Matt": "ocks-matt",
    "O'CONNELL Andrew": "o-connell-andrew",
    "O'CONNELL Brendan": "o-connell-brendan",
    "O'CONNELL Chris": "o-connell-chris",
    "O'CONNELL E": "o-connell-e",
    "O'CONNELL Frances": "o-connell-frances",
    "O'CONNELL Geoffrey": "o-connell-geoffrey",
    "O'CONNELL James Mainard": "o-connell-james-mainard",
    "O'CONNELL Jason": "o-connell-jason",
    "O'CONNELL Kathryn Mainard": "o-connell-kathryn-mainard",
    "O'CONNELL Lorna": "o-connell-lorna",
    "O'CONNELL Oliver": "o-connell-oliver",
    "O'CONNELL Richard L": "o-connell-richard-l",
    "O'CONNELL Stephen": "o-connell-stephen",
    "O'CONNELL Steve": "o-connell-steve",
    "O'CONNELL Terence": "o-connell-terence",
    "O'CONNELL Trevor": "o-connell-trevor",
    "O'CONNELL Vincent": "o-connell-vincent",
    "O'CONNER Frank": "o-conner-frank",
    "O'CONNOR Anne-Marie": "o-connor-anne-marie",
    "O'CONNOR Bridget": "o-connor-bridget",
    "O'CONNOR Caroline": "o-connor-caroline",
    "O'CONNOR Catherine": "o-connor-catherine",
    "O'CONNOR Charles G": "o-connor-charles-g",
    "O'CONNOR Chris": "o-connor-chris",
    "O'CONNOR Chuck": "o-connor-chuck",
    "O'CONNOR Colin": "o-connor-colin",
    "O'CONNOR Conleth": "o-connor-conleth",
    "O'CONNOR Danny": "o-connor-danny",
    "O'CONNOR David": "o-connor-david",
    "O'CONNOR Deirdre": "o-connor-deirdre",
    "O'CONNOR Derek": "o-connor-derek",
    "O'CONNOR Desmond": "o-connor-desmond",
    "O'CONNOR Diegan": "o-connor-diegan",
    "O'CONNOR Edwin": "o-connor-edwin",
    "O'CONNOR Elizabeth": "o-connor-elizabeth",
    "O'CONNOR Eva": "o-connor-eva",
    "O'CONNOR Frank": "o-connor-frank",
    "O'CONNOR Garry": "o-connor-garry",
    "O'CONNOR Geraldine": "o-connor-geraldine",
    "O'CONNOR Helen": "o-connor-helen",
    "O'CONNOR James": "o-connor-james",
    "O'CONNOR James V": "o-connor-james-v",
    "O'CONNOR Jan": "o-connor-jan",
    "O'CONNOR Jim": "o-connor-jim",
    "O'CONNOR Joanne": "o-connor-joanne",
    "O'CONNOR John": "o-connor-john",
    "O'CONNOR Joseph": "o-connor-joseph",
    "O'CONNOR Kent": "o-connor-kent",
    "O'CONNOR Kevin": "o-connor-kevin",
    "O'CONNOR Kevin A": "o-connor-kevin-a",
    "O'CONNOR Luke": "o-connor-luke",
    "O'CONNOR Mariann M": "o-connor-mariann-m",
    "O'CONNOR Mark": "o-connor-mark",
    "O'CONNOR Martin": "o-connor-martin",
    "O'CONNOR Michael": "o-connor-michael",
    "O'CONNOR Milovan": "o-connor-milovan",
    "O'CONNOR Oria": "o-connor-oria",
    "O'CONNOR P J": "o-connor-p-j",
    "O'CONNOR Patricia": "o-connor-patricia",
    "O'CONNOR Patricia W": "o-connor-patricia-w",
    "O'CONNOR Patrick": "o-connor-patrick",
    "O'CONNOR Paul": "o-connor-paul",
    "O'CONNOR Penny": "o-connor-penny",
    "O'CONNOR Reg": "o-connor-reg",
    "O'CONNOR Robbie": "o-connor-robbie",
    "O'CONNOR Robert": "o-connor-robert",
    "O'CONNOR Ryan": "o-connor-ryan",
    "O'CONNOR Sara": "o-connor-sara",
    "O'CONNOR Sean": "o-connor-sean",
    "O'CONNOR Simon": "o-connor-simon",
    "O'CONNOR Steven Tylor": "o-connor-steven-tylor",
    "O'CONNOR Terry": "o-connor-terry",
    "O'CONNOR Trish": "o-connor-trish",
    "O'CONNOR Ulick": "o-connor-ulick",
    "O'CONOR Joseph": "o-conor-joseph",
    "O'DAY Michael C": "o-day-michael-c",
    "ODD MAN OUT ": "odd-man-out",
    "ODDBODIES ": "oddbodies",
    "ODDEN Denis": "odden-denis",
    "ODDMANOUT ": "oddmanout",
    "ODDY Nick": "oddy-nick",
    "O'DEBRA Tanya": "o-debra-tanya",
    "ODEMS Keninya": "odems-keninya",
    "ODEMS Kennyetta": "odems-kennyetta",
    "ODERBERG David S": "oderberg-david-s",
    "ODETS Clifford": "odets-clifford",
    "ODIA Thomas": "odia-thomas",
    "ODIMBA Chino": "odimba-chino",
    "ODIN TEATRET ": "odin-teatret",
    "O'DOHERTY Claudia": "o-doherty-claudia",
    "O'DOHERTY David": "o-doherty-david",
    "ODOM Alex": "odom-alex",
    "O'DONNACHADHA Cillian": "o-donnachadha-cillian",
    "O'DONNEL Sean": "o-donnel-sean",
    "O'DONNELL Bridget": "o-donnell-bridget",
    "O'DONNELL Chris": "o-donnell-chris",
    "O'DONNELL Daniel": "o-donnell-daniel",
    "O'DONNELL Darren": "o-donnell-darren",
    "O'DONNELL Dean": "o-donnell-dean",
    "O'DONNELL Frank": "o-donnell-frank",
    "O'DONNELL Geoffrey Decas": "o-donnell-geoffrey-decas",
    "O'DONNELL Jack": "o-donnell-jack",
    "O'DONNELL Jim": "o-donnell-jim",
    "O'DONNELL Joe": "o-donnell-joe",
    "O'DONNELL John P": "o-donnell-john-p",
    "O'DONNELL Karen": "o-donnell-karen",
    "O'DONNELL Kate": "o-donnell-kate",
    "O'DONNELL Kevin": "o-donnell-kevin",
    "O'DONNELL Kevin Kell": "o-donnell-kevin-kell",
    "O'DONNELL Margaret Ann": "o-donnell-margaret-ann",
    "O'DONNELL Mark": "o-donnell-mark",
    "O'DONNELL Peter": "o-donnell-peter",
    "O'DONNELL Richard P": "o-donnell-richard-p",
    "O'DONNELL Ronan": "o-donnell-ronan",
    "O'DONNELL Sean": "o-donnell-sean",
    "O'DONNELL Stephen": "o-donnell-stephen",
    "O'DONNELL Val": "o-donnell-val",
    "O'DONOGHUE John": "o-donoghue-john",
    "O'DONOGHUE Michael": "o-donoghue-michael",
    "O'DONOGHUE Noel": "o-donoghue-noel",
    "O'DONOGHUE Robert": "o-donoghue-robert",
    "O'DONOVAN John": "o-donovan-john",
    "O'DONOVAN John (1)": "o-donovan-john-1",
    "O'DONOVAN Terry": "o-donovan-terry",
    "O'DRISCOLL Ciaran": "o-driscoll-ciaran",
    "O'DRISCOLL Liam": "o-driscoll-liam",
    "O'DWYER Eamonn": "o-dwyer-eamonn",
    "O'DWYER Louise": "o-dwyer-louise",
    "O'DWYER Marion": "o-dwyer-marion",
    "O'DWYER Matthew": "o-dwyer-matthew",
    "OESER Kevin": "oeser-kevin",
    "OESTEREICH James": "oestereich-james",
    "OESTERMAN Philip": "oesterman-philip",
    "OESTREICHER Amy": "oestreicher-amy",
    "O'FARRELL John": "o-farrell-john",
    "O'FARRELL Joseph": "o-farrell-joseph",
    "O'FARRELL Padraic": "o-farrell-padraic",
    "O'FARRELL Rita": "o-farrell-rita",
    "O'FERRALL Courtney": "o-ferrall-courtney",
    "OFF LIMITS THEATRE COMPANY ": "off-limits-theatre-company",
    "OFFENBACH Gabby": "offenbach-gabby",
    "OFFER Judith": "offer-judith",
    "OFFORD Alexander": "offord-alexander",
    "OFFRICHT Kenneth": "offricht-kenneth",
    "O'FLAHERTY Michael": "o-flaherty-michael",
    "O'FLAHERTY Tracy": "o-flaherty-tracy",
    "O'FLAHERTY Wendy": "o-flaherty-wendy",
    "O'FLATHARTA Antoine": "o-flatharta-antoine",
    "OFLAZOGLU A Turzan": "oflazoglu-a-turzan",
    "O'FLYNN Criostoir": "o-flynn-criostoir",
    "O'FLYNN Mark": "o-flynn-mark",
    "O'FLYNN Niamh": "o-flynn-niamh",
    "OFORI Racheal": "ofori-racheal"
  }
};