export default {
  "metadata": {
    "results": 251,
    "timeStamp": "2025-12-05T21:29:28.922Z",
    "url": "https://www.doollee.com/PlaywrightsO/O_playwrights_g-l.php"
  },
  "authors": {
    "O'GARDEN Irene": "o-garden-irene",
    "OGATA Issey": "ogata-issey",
    "OGAWA Aya": "ogawa-aya",
    "OGAWA Ruby": "ogawa-ruby",
    "OGBORN Brandon": "ogborn-brandon",
    "OGBORN Michael": "ogborn-michael",
    "OGDEN Alan": "ogden-alan",
    "OGDEN Gill": "ogden-gill",
    "OGDEN Kevan": "ogden-kevan",
    "OGDEN Simon": "ogden-simon",
    "OGIDI Ann": "ogidi-ann",
    "OGILVIE David Ogilvie": "ogilvie-david-ogilvie",
    "OGILVY Ian": "ogilvy-ian",
    "OGILVY Kirstie": "ogilvy-kirstie",
    "OGILVY Rachel": "ogilvy-rachel",
    "OGILVY Tim": "ogilvy-tim",
    "OGLE Adam": "ogle-adam",
    "OGLE Mark D": "ogle-mark-d",
    "OGLE Sean": "ogle-sean",
    "OGLESBY Briandaniel": "oglesby-briandaniel",
    "OGLESBY Marshall": "oglesby-marshall",
    "OGLESBY Tamsin": "oglesby-tamsin",
    "OGNEV Ilya": "ognev-ilya",
    "O'GORMAN Keith": "o-gorman-keith",
    "O'GORMAN Simon": "o-gorman-simon",
    "O'GRADY Desmond": "o-grady-desmond",
    "O'GRADY Jennifer": "o-grady-jennifer",
    "O'GRADY Mairin": "o-grady-mairin",
    "O'GRADY Roderick": "o-grady-roderick",
    "OGRIN Dave": "ogrin-dave",
    "OGRYZKOV Nikolai": "ogryzkov-nikolai",
    "OGUNLEYE Foluke": "ogunleye-foluke",
    "OGUNS Femi": "oguns-femi",
    "OGUNTOKUN Wole": "oguntokun-wole",
    "OGUNYEMI Wale": "ogunyemi-wale",
    "OGWEN John": "ogwen-john",
    "OH Eugene": "oh-eugene",
    "OH Soon-teck": "oh-soon-teck",
    "OH Taesuk": "oh-taesuk",
    "OH Tony": "oh-tony",
    "O'HAGAN Andrew": "o-hagan-andrew",
    "O'HAGAN Jack": "o-hagan-jack",
    "O'HAGAN Lucy": "o-hagan-lucy",
    "O'HAGAN Mairin": "o-hagan-mairin",
    "O'HAGAN Terry": "o-hagan-terry",
    "O'HALLORAN Gretchen C": "o-halloran-gretchen-c",
    "O'HALLORAN Mark": "o-halloran-mark",
    "O'HANLON Ardal": "o-hanlon-ardal",
    "O'HANLON Emma": "o-hanlon-emma",
    "O'HANLON Jim": "o-hanlon-jim",
    "O'HANRAHAN Paul": "o-hanrahan-paul",
    "O'HARA David K": "o-hara-david-k",
    "O'HARA Frank": "o-hara-frank",
    "O'HARA James": "o-hara-james",
    "O'HARA John": "o-hara-john",
    "O'HARA John (1)": "o-hara-john-1",
    "O'HARA John (2)": "o-hara-john-2",
    "O'HARA Mary": "o-hara-mary",
    "O'HARA Michael Desmond": "o-hara-michael-desmond",
    "O'HARA Patricia": "o-hara-patricia",
    "O'HARA Riggs": "o-hara-riggs",
    "O'HARA Robert": "o-hara-robert",
    "O'HARE Caroline": "o-hare-caroline",
    "O'HARE Denis": "o-hare-denis",
    "O'HARE Eugene": "o-hare-eugene",
    "O'HARE Gaynor": "o-hare-gaynor",
    "O'HARE John": "o-hare-john",
    "O'HARE Kristian": "o-hare-kristian",
    "O'HARE Marcella": "o-hare-marcella",
    "O'HARRA Brooke": "o-harra-brooke",
    "OHASHI Yasuhiko": "ohashi-yasuhiko",
    "O'HAVER Sarah Kate": "o-haver-sarah-kate",
    "O'HEARN Kerry": "o-hearn-kerry",
    "O'HEARN Nigel": "o-hearn-nigel",
    "OHM Lori Allen": "ohm-lori-allen",
    "OHM Stephen": "ohm-stephen",
    "OHNO Yoshito": "ohno-yoshito",
    "O'HORA Margaret": "o-hora-margaret",
    "O'HORGAN Tom": "o-horgan-tom",
    "OHTA Shogo": "ohta-shogo",
    "OIDA Yoshi": "oida-yoshi",
    "OILART Luis": "oilart-luis",
    "OILY CART ": "oily-cart",
    "OIYE David": "oiye-david",
    "OJEDA Perry": "ojeda-perry",
    "OKADA Toshiki": "okada-toshiki",
    "OKADA Yutaka": "okada-yutaka",
    "OKAI Omar F": "okai-omar-f",
    "OKAMURA Akemi": "okamura-akemi",
    "O'KANE Maggie": "o-kane-maggie",
    "O'KASI Leann": "o-kasi-leann",
    "OKE Erin": "oke-erin",
    "O'KEEFE Andrew": "o-keefe-andrew",
    "O'KEEFE Catie": "o-keefe-catie",
    "O'KEEFE Damien": "o-keefe-damien",
    "O'KEEFE J F": "o-keefe-j-f",
    "O'KEEFE Jim": "o-keefe-jim",
    "O'KEEFE John": "o-keefe-john",
    "O'KEEFE Julia": "o-keefe-julia",
    "O'KEEFE Laurence": "o-keefe-laurence",
    "O'KEEFE Lester": "o-keefe-lester",
    "O'KEEFFE John": "o-keeffe-john",
    "O'KEEFFE Kelly": "o-keeffe-kelly",
    "O'KEEFFE Paul": "o-keeffe-paul",
    "O'KELL Hayley": "o-kell-hayley",
    "O'KELLY Donal": "o-kelly-donal",
    "O'KELLY Katie": "o-kelly-katie",
    "O'KELLY Seamus": "o-kelly-seamus",
    "OKEN Scott": "oken-scott",
    "OKIMOTO Jean Davies": "okimoto-jean-davies",
    "OKIN Matt": "okin-matt",
    "OKITA Dwight": "okita-dwight",
    "OKLADEK Mark": "okladek-mark",
    "OKLAHOMA D K": "oklahoma-d-k",
    "OKLOP Mika": "oklop-mika",
    "OKOH Janice": "okoh-janice",
    "OKOLI Onyi": "okoli-onyi",
    "OKOLI Tunde": "okoli-tunde",
    "OKPOKWASILI Okwui": "okpokwasili-okwui",
    "OKRAND Marc": "okrand-marc",
    "OKRANT Robyn": "okrant-robyn",
    "OKRENT Daniel": "okrent-daniel",
    "OKSANEN Sofi": "oksanen-sofi",
    "OKTEM Cigdem": "oktem-cigdem",
    "OKUN Stephanie": "okun-stephanie",
    "OLAFFSSON Olaf": "olaffsson-olaf",
    "OLAND Edith": "oland-edith",
    "OLAND Warner": "oland-warner",
    "OLANDER James F": "olander-james-f",
    "OLATUNJI Tunde": "olatunji-tunde",
    "OLBERT John": "olbert-john",
    "OLCOTT Nick": "olcott-nick",
    "OLDENDICK Tom": "oldendick-tom",
    "OLDERSHAW Jake": "oldershaw-jake",
    "OLDFIELD Ben": "oldfield-ben",
    "OLDFIELD Mary": "oldfield-mary",
    "OLDHAM Joseph": "oldham-joseph",
    "OLDHAM Reginald": "oldham-reginald",
    "OLDING Grant": "olding-grant",
    "OLDKNOW Charles": "oldknow-charles",
    "OLDKNOW Mark": "oldknow-mark",
    "O'LEARY Aileen": "o-leary-aileen",
    "O'LEARY Allen": "o-leary-allen",
    "O'LEARY Casey": "o-leary-casey",
    "O'LEARY Charlie": "o-leary-charlie",
    "O'LEARY Denise": "o-leary-denise",
    "O'LEARY Eileen": "o-leary-eileen",
    "O'LEARY Helen": "o-leary-helen",
    "O'LEARY Megan": "o-leary-megan",
    "O'LEARY Sarah": "o-leary-sarah",
    "O'LEARY Sean": "o-leary-sean",
    "O'LEARY Tim": "o-leary-tim",
    "OLEJNICZAK Alan": "olejniczak-alan",
    "OLER Kim": "oler-kim",
    "OLES Stephen": "oles-stephen",
    "OLESKER Lizzie": "olesker-lizzie",
    "OLESON-CORMACK Leif": "oleson-cormack-leif",
    "OLESZKO Mark": "oleszko-mark",
    "OLF Julian": "olf-julian",
    "OLFAT Beejan": "olfat-beejan",
    "OLFSON Lewy": "olfson-lewy",
    "OLIANSKY Joel": "oliansky-joel",
    "OLIENSIS Adam": "oliensis-adam",
    "OLINS Andrew": "olins-andrew",
    "OLIVA Ann Marie": "oliva-ann-marie",
    "OLIVA Judy Lee": "oliva-judy-lee",
    "OLIVARES Ivan": "olivares-ivan",
    "OLIVE Bruce": "olive-bruce",
    "OLIVE John": "olive-john",
    "OLIVER Amanda": "oliver-amanda",
    "OLIVER Anthony Michael": "oliver-anthony-michael",
    "OLIVER Brian": "oliver-brian",
    "OLIVER Bryan": "oliver-bryan",
    "OLIVER Christy": "oliver-christy",
    "OLIVER Clifford": "oliver-clifford",
    "OLIVER Donald": "oliver-donald",
    "OLIVER Donald (1)": "oliver-donald-1",
    "OLIVER Edgar": "oliver-edgar",
    "OLIVER Gordon": "oliver-gordon",
    "OLIVER Isaac": "oliver-isaac",
    "OLIVER Jake": "oliver-jake",
    "OLIVER Jill": "oliver-jill",
    "OLIVER Kathleen": "oliver-kathleen",
    "OLIVER Louise": "oliver-louise",
    "OLIVER Mark": "oliver-mark",
    "OLIVER Murray": "oliver-murray",
    "OLIVER Nancy": "oliver-nancy",
    "OLIVER Reggie": "oliver-reggie",
    "OLIVER Robert": "oliver-robert",
    "OLIVER Ryan Scott": "oliver-ryan-scott",
    "OLIVER Sean Harris": "oliver-sean-harris",
    "OLIVER Wilbert": "oliver-wilbert",
    "OLIVER William Stanley": "oliver-william-stanley",
    "OLIVEROS Pauline": "oliveros-pauline",
    "OLIVIA Sophie": "olivia-sophie",
    "OLIVIER Laurence": "olivier-laurence",
    "OLIVIERI Guy": "olivieri-guy",
    "OLLE Alex": "olle-alex",
    "OLLIES Amie-Jane": "ollies-amie-jane",
    "OLLSTEIN Laurel": "ollstein-laurel",
    "OLM James": "olm-james",
    "OLMI Veronique": "olmi-veronique",
    "OLMO Lauro": "olmo-lauro",
    "OLMOS Carlos": "olmos-carlos",
    "OLMOS Matthew Paul": "olmos-matthew-paul",
    "OLMS James": "olms-james",
    "OLMSTED Jeff": "olmsted-jeff",
    "OLNECK Madelaine": "olneck-madelaine",
    "OLNEY Nick": "olney-nick",
    "OLNEY Valerie": "olney-valerie",
    "OLOHAN Jack": "olohan-jack",
    "OLORUNTOBA-OJU Taiwo": "oloruntoba-oju-taiwo",
    "O'LOUGHLIN Alister": "o-loughlin-alister",
    "O'LOUGHLIN Em": "o-loughlin-em",
    "O'LOUGHLIN Siobhan": "o-loughlin-siobhan",
    "OLRY Stephane": "olry-stephane",
    "OLSEN Alfa-Betty": "olsen-alfa-betty",
    "OLSEN David": "olsen-david",
    "OLSEN Erik": "olsen-erik",
    "OLSEN Lorraine": "olsen-lorraine",
    "OLSEN Mark James": "olsen-mark-james",
    "OLSEN Mark V": "olsen-mark-v",
    "OLSEN Michael": "olsen-michael",
    "OLSEN Sven": "olsen-sven",
    "OLSEN Thomas W": "olsen-thomas-w",
    "OLSEN Tyler": "olsen-tyler",
    "OLSHANSKY Vladimir": "olshansky-vladimir",
    "OLSHER Laura": "olsher-laura",
    "OLSON Brandon": "olson-brandon",
    "OLSON Donald S": "olson-donald-s",
    "OLSON Doug": "olson-doug",
    "OLSON Ester E": "olson-ester-e",
    "OLSON John": "olson-john",
    "OLSON Joseph Allred": "olson-joseph-allred",
    "OLSON Lauren": "olson-lauren",
    "OLSON Mark": "olson-mark",
    "OLSON Marnie": "olson-marnie",
    "OLSON Neil": "olson-neil",
    "OLSON Paul": "olson-paul",
    "OLSON Phil": "olson-phil",
    "OLSON Richard Arthur": "olson-richard-arthur",
    "OLSON Thomas W": "olson-thomas-w",
    "OLSON Todd": "olson-todd",
    "OLSON Tyler": "olson-tyler",
    "OLSONI Kristen": "olsoni-kristen",
    "OLSSON Linda": "olsson-linda",
    "OLTHOF Linda": "olthof-linda",
    "OLTRA Vanessa": "oltra-vanessa",
    "OLUGWU Mewe": "olugwu-mewe",
    "OLWAGON Christiaan": "olwagon-christiaan",
    "OLYSLAEGERS Jeroen": "olyslaegers-jeroen"
  }
};