export default {
  "metadata": {
    "results": 247,
    "timeStamp": "2025-12-05T21:29:32.110Z",
    "url": "https://www.doollee.com/PlaywrightsO/O_playwrights_m-r.php"
  },
  "authors": {
    "O'MALLEY Fiona": "o-malley-fiona",
    "O'MALLEY Gerry": "o-malley-gerry",
    "O'MALLEY Glyn": "o-malley-glyn",
    "O'MALLEY Margaret": "o-malley-margaret",
    "O'MALLEY Mary": "o-malley-mary",
    "O'MALLEY Mike": "o-malley-mike",
    "O'MALLEY Sean T C": "o-malley-sean-t-c",
    "O'MALLEY Sybil": "o-malley-sybil",
    "O'MALLEY Tom": "o-malley-tom",
    "OMAN Severin": "oman-severin",
    "OMAR Cosh": "omar-cosh",
    "O'MARA Aisling": "o-mara-aisling",
    "OMARI Mariem": "omari-mariem",
    "OMATA Garrett H": "omata-garrett-h",
    "OMCHERI ": "omcheri",
    "OMDAHL Joel": "omdahl-joel",
    "OMIELAN Luisa": "omielan-luisa",
    "OMLIE Lisa": "omlie-lisa",
    "OMMANEY Lisa": "ommaney-lisa",
    "OMOROTIONMWAN Philana": "omorotionmwan-philana",
    "O'MORRISON Kevin": "o-morrison-kevin",
    "ON THE RUN ": "on-the-run",
    "O'NAN Ryan": "o-nan-ryan",
    "ONASHILE Adura": "onashile-adura",
    "ONBEKEND ": "onbekend",
    "ONBEKENDE Onbekend": "onbekende-onbekend",
    "ONDAATJE Michael": "ondaatje-michael",
    "ONDREJCAK Andrew": "ondrejcak-andrew",
    "ONE YELLOW RABBIT ": "one-yellow-rabbit",
    "O'NEAL Charles": "o-neal-charles",
    "O'NEAL Christopher": "o-neal-christopher",
    "O'NEAL James": "o-neal-james",
    "O'NEAL John": "o-neal-john",
    "O'NEAL Q": "o-neal-q",
    "O'NEAL S Denise": "o-neal-s-denise",
    "O'NEAL Shellie Kaye": "o-neal-shellie-kaye",
    "O'NEIL Dan": "o-neil-dan",
    "O'NEIL Mark": "o-neil-mark",
    "O'NEIL Miles": "o-neil-miles",
    "O'NEIL Patrick S": "o-neil-patrick-s",
    "O'NEIL Roy": "o-neil-roy",
    "O'NEIL Russell": "o-neil-russell",
    "O'NEIL Sean": "o-neil-sean",
    "O'NEIL Terrence": "o-neil-terrence",
    "O'NEIL Tom": "o-neil-tom",
    "O'NEIL William": "o-neil-william",
    "O'NEILL Brian": "o-neill-brian",
    "O'NEILL Cally": "o-neill-cally",
    "O'NEILL Catherine M": "o-neill-catherine-m",
    "O'NEILL Cecily": "o-neill-cecily",
    "O'NEILL Charles": "o-neill-charles",
    "O'NEILL Charlie": "o-neill-charlie",
    "O'NEILL Chris": "o-neill-chris",
    "O'NEILL Cordelia": "o-neill-cordelia",
    "O'NEILL Deborah": "o-neill-deborah",
    "O'NEILL Ellen": "o-neill-ellen",
    "O'NEILL Erica": "o-neill-erica",
    "O'NEILL Errol": "o-neill-errol",
    "O'NEILL Eugene": "o-neill-eugene",
    "O'NEILL Finnian": "o-neill-finnian",
    "O'NEILL James": "o-neill-james",
    "O'NEILL Jamie": "o-neill-jamie",
    "O'NEILL Jody": "o-neill-jody",
    "O'NEILL Jonathan": "o-neill-jonathan",
    "O'NEILL Karl": "o-neill-karl",
    "O'NEILL Kathleen A": "o-neill-kathleen-a",
    "O'NEILL Lesley Clare": "o-neill-lesley-clare",
    "O'NEILL Matt": "o-neill-matt",
    "O'NEILL Meghan": "o-neill-meghan",
    "O'NEILL Michael": "o-neill-michael",
    "O'NEILL Michael John": "o-neill-michael-john",
    "O'NEILL Nick": "o-neill-nick",
    "O'NEILL Noel": "o-neill-noel",
    "O'NEILL Owen": "o-neill-owen",
    "O'NEILL Randall": "o-neill-randall",
    "O'NEILL Rebecca Gorman": "o-neill-rebecca-gorman",
    "O'NEILL Richard": "o-neill-richard",
    "O'NEILL Richard Rai": "o-neill-richard-rai",
    "O'NEILL Rik": "o-neill-rik",
    "O'NEILL Rob": "o-neill-rob",
    "O'NEILL Robbie": "o-neill-robbie",
    "O'NEILL Rosary": "o-neill-rosary",
    "O'NEILL Russell": "o-neill-russell",
    "O'NEILL Sarah Jane": "o-neill-sarah-jane",
    "O'NEILL Seamus": "o-neill-seamus",
    "O'NEILL Sean": "o-neill-sean",
    "O'NEILL Shannon": "o-neill-shannon",
    "O'NEILL Stacy": "o-neill-stacy",
    "O'NEILL Tee": "o-neill-tee",
    "O'NEILL Terry": "o-neill-terry",
    "O'NEILL Thomas": "o-neill-thomas",
    "O'NEILL Tom": "o-neill-tom",
    "O'NEILL Vanessa": "o-neill-vanessa",
    "O'NEILL-BUTLER Marj": "o-neill-butler-marj",
    "ONEOHONE ": "oneohone",
    "ONETTI Antonio": "onetti-antonio",
    "ONG Han": "ong-han",
    "ONG Henry": "ong-henry",
    "ONG Nicholas": "ong-nicholas",
    "ONG Warren": "ong-warren",
    "ONI Julie Taiwo": "oni-julie-taiwo",
    "ONO Yoko": "ono-yoko",
    "ONODERA Kira": "onodera-kira",
    "ONORI Gianni": "onori-gianni",
    "ONROTT Barbara": "onrott-barbara",
    "ONSTAD Andrea": "onstad-andrea",
    "ONTROEREND GOED ": "ontroerend-goed",
    "ONWUEGBUTE Nduka": "onwuegbute-nduka",
    "ONWUEME Tess O": "onwueme-tess-o",
    "ONWURAH Chi": "onwurah-chi",
    "OOI Mike": "ooi-mike",
    "OOI Yang-May": "ooi-yang-may",
    "OOMEN Anne-Marie": "oomen-anne-marie",
    "OONDATJE Michael": "oondatje-michael",
    "OOSTHUYSEN Willem Stegmann": "oosthuysen-willem-stegmann",
    "OPAREI DeObia": "oparei-deobia",
    "OPATRNY Matthew": "opatrny-matthew",
    "OPELKA Gregg": "opelka-gregg",
    "OPEN CITY ": "open-city",
    "OPEN CLASP THEATRE COMPANY ": "open-clasp-theatre-company",
    "OPEN THEATRE ": "open-theatre",
    "OPENHEIMER JR Max": "openheimer-jr-max",
    "OPENSHAW Charles Elton": "openshaw-charles-elton",
    "OPHABOOM ": "ophaboom",
    "OPIE Jack": "opie-jack",
    "OPPENHEIM Jonas": "oppenheim-jonas",
    "OPPENHEIM Marella": "oppenheim-marella",
    "OPPENHEIM Yoni": "oppenheim-yoni",
    "OPPENHEIMER George": "oppenheimer-george",
    "OPPENHEIMER Jess": "oppenheimer-jess",
    "OPPENHEIMER Joel": "oppenheimer-joel",
    "OPROIU Okathrina": "oproiu-okathrina",
    "OPTRNY Matt": "optrny-matt",
    "ORAM Glynn": "oram-glynn",
    "ORAM Hiawyn": "oram-hiawyn",
    "ORAM Neil": "oram-neil",
    "ORBAN Judith": "orban-judith",
    "ORBAUM Jason": "orbaum-jason",
    "ORBISON Willie": "orbison-willie",
    "ORCHARD Matt": "orchard-matt",
    "ORCHID Ellen": "orchid-ellen",
    "ORCZY Baroness": "orczy-baroness",
    "ORDAZ Evangeline": "ordaz-evangeline",
    "ORDOVER Andrew C": "ordover-andrew-c",
    "ORDWAY Sally": "ordway-sally",
    "ORECK Les": "oreck-les",
    "O'REGAN Alan": "o-regan-alan",
    "O'REGAN Ed": "o-regan-ed",
    "O'REILLY Caitlin": "o-reilly-caitlin",
    "O'REILLY Christian": "o-reilly-christian",
    "O'REILLY Ciaran": "o-reilly-ciaran",
    "O'REILLY James": "o-reilly-james",
    "O'REILLY Kaite": "o-reilly-kaite",
    "O'REILLY Kate": "o-reilly-kate",
    "O'REILLY Kira": "o-reilly-kira",
    "O'REILLY Morgana": "o-reilly-morgana",
    "O'REILLY Niall": "o-reilly-niall",
    "O'REILLY P J": "o-reilly-p-j",
    "O'REILLY Wende": "o-reilly-wende",
    "OREM William": "orem-william",
    "ORENSTEIN Bernie": "orenstein-bernie",
    "ORENSTEIN Ellen": "orenstein-ellen",
    "ORENSTEIN Leo": "orenstein-leo",
    "OREZZOLI Hector": "orezzoli-hector",
    "ORF Kyle": "orf-kyle",
    "ORGAN Scott": "organ-scott",
    "ORGANIC THEATRE COMPANY, THE ": "organic-theatre-company",
    "ORI Lee": "ori-lee",
    "ORIJA Morayo": "orija-morayo",
    "O'RIORDAN Cathal": "o-riordan-cathal",
    "O'RIORDAN Kate": "o-riordan-kate",
    "O'RIORDAN Sean": "o-riordan-sean",
    "ORISTANO Mark": "oristano-mark",
    "ORKENY Istvan": "orkeny-istvan",
    "ORKIN Harvey": "orkin-harvey",
    "ORKOW Ben": "orkow-ben",
    "ORLANDERSMITH Dael": "orlandersmith-dael",
    "ORLANDI Marcus": "orlandi-marcus",
    "ORLANDO Dominic": "orlando-dominic",
    "ORLANDO Michael": "orlando-michael",
    "ORLANDO YOUTH ALLIANCE ": "orlando-youth-alliance",
    "ORLEY Emily": "orley-emily",
    "ORLIKOFF Rachel": "orlikoff-rachel",
    "ORLOCK John": "orlock-john",
    "ORLOFF Penny": "orloff-penny",
    "ORLOFF Rich": "orloff-rich",
    "ORLOV Stephen": "orlov-stephen",
    "ORMANDY Darren": "ormandy-darren",
    "ORME Anthony": "orme-anthony",
    "ORME H G": "orme-h-g",
    "ORMEROD John": "ormerod-john",
    "ORMEROD Nick": "ormerod-nick",
    "ORMISTON Fiona": "ormiston-fiona",
    "ORMOND Derek": "ormond-derek",
    "ORMONT David": "ormont-david",
    "ORMROD Phil": "ormrod-phil",
    "ORMSBY Alan": "ormsby-alan",
    "ORMSBY Phil": "ormsby-phil",
    "ORMSBY Rob": "ormsby-rob",
    "ORNADEL Cyril": "ornadel-cyril",
    "ORNDORFF Elizabeth": "orndorff-elizabeth",
    "ORNSTEIN J Alan": "ornstein-j-alan",
    "ORNSTEIN Tess R": "ornstein-tess-r",
    "ORONACHER Karen": "oronacher-karen",
    "OROPEZA Luis": "oropeza-luis",
    "O'RORK Denny": "o-rork-denny",
    "OROSKO Kirsty": "orosko-kirsty",
    "O'ROURKE Eamon": "o-rourke-eamon",
    "O'ROURKE P J": "o-rourke-p-j",
    "O'ROURKE Stephen": "o-rourke-stephen",
    "O'ROWE Mark": "o-rowe-mark",
    "OROZCO Beverly": "orozco-beverly",
    "OROZCO Hiram": "orozco-hiram",
    "ORR Anne Davey": "orr-anne-davey",
    "ORR Christine": "orr-christine",
    "ORR Elizabeth": "orr-elizabeth",
    "ORR Helen": "orr-helen",
    "ORR Jill": "orr-jill",
    "ORR John": "orr-john",
    "ORR Leonard H": "orr-leonard-h",
    "ORR Mary": "orr-mary",
    "ORR Megan": "orr-megan",
    "ORR Stuart": "orr-stuart",
    "ORR William": "orr-william",
    "ORRIOS Angel Gil": "orrios-angel-gil",
    "ORSLAND Chuck": "orsland-chuck",
    "ORTA Marisela Trevino": "orta-marisela-trevino",
    "ORTARDO Victor": "ortardo-victor",
    "ORTEGA Melody": "ortega-melody",
    "ORTESE Rebecca": "ortese-rebecca",
    "ORTHAL Cindy": "orthal-cindy",
    "ORTI Pilar": "orti-pilar",
    "ORTIZ Deborah Louise": "ortiz-deborah-louise",
    "ORTIZ James": "ortiz-james",
    "ORTIZ Lourdes": "ortiz-lourdes",
    "ORTIZ Santiago": "ortiz-santiago",
    "ORTIZ Tareke": "ortiz-tareke",
    "ORTIZ-PINATE Milta Iliana": "ortiz-pinate-milta-iliana",
    "ORTON Daisy": "orton-daisy",
    "ORTON Joe": "orton-joe",
    "ORTON Kimberley": "orton-kimberley",
    "ORTON Leslie": "orton-leslie",
    "ORTWEIN Terrance": "ortwein-terrance",
    "ORWELL Sonia": "orwell-sonia",
    "ORWIN Louise": "orwin-louise",
    "O'RYAN Conley": "o-ryan-conley",
    "ORYSHCHUK Nataliya": "oryshchuk-nataliya"
  }
};