export default {
  "metadata": {
    "results": 258,
    "timeStamp": "2025-12-05T21:29:35.365Z",
    "url": "https://www.doollee.com/PlaywrightsO/O_playwrights_s-z.php"
  },
  "authors": {
    "OSADIA ": "osadia",
    "OSAKWE Chima": "osakwe-chima",
    "OSATO Una Aya": "osato-una-aya",
    "OSBALDERSTON Jon": "osbalderston-jon",
    "OSBORN Louise": "osborn-louise",
    "OSBORN Matthew": "osborn-matthew",
    "OSBORN Paul": "osborn-paul",
    "OSBORN Tom": "osborn-tom",
    "OSBORNE Alan": "osborne-alan",
    "OSBORNE Charles": "osborne-charles",
    "OSBORNE Charles (1)": "osborne-charles-1",
    "OSBORNE Claudia": "osborne-claudia",
    "OSBORNE Hugh": "osborne-hugh",
    "OSBORNE Jason Dietz": "osborne-jason-dietz",
    "OSBORNE Jimmy": "osborne-jimmy",
    "OSBORNE John": "osborne-john",
    "OSBORNE John (1)": "osborne-john-1",
    "OSBORNE Joseph": "osborne-joseph",
    "OSBORNE Julia": "osborne-julia",
    "OSBORNE Melissa": "osborne-melissa",
    "OSBORNE Natalie": "osborne-natalie",
    "OSBORNE Nigel": "osborne-nigel",
    "OSBORNE Paul": "osborne-paul",
    "OSBORNE Rebecca": "osborne-rebecca",
    "OSBORNE Richard": "osborne-richard",
    "OSBORNE Roger": "osborne-roger",
    "OSBORNE Ron": "osborne-ron",
    "OSBORNE Tony": "osborne-tony",
    "OSBORNE Will": "osborne-will",
    "OSBORNE HUGHES John": "osborne-hughes-john",
    "OSBORN-LEE Azure D": "osborn-lee-azure-d",
    "OSBOURN Louise": "osbourn-louise",
    "OSBOURNE Jimmy": "osbourne-jimmy",
    "OSBOURNE Lloyd": "osbourne-lloyd",
    "OSCAR MIKE ": "oscar-mike",
    "OSEI-KUFFOUR Stacy": "osei-kuffour-stacy",
    "OSER Janice Auritt": "oser-janice-auritt",
    "OSGOOD Lawrence": "osgood-lawrence",
    "OSGOOD Nathan": "osgood-nathan",
    "O'SHAUGHNESSY Barunka": "o-shaughnessy-barunka",
    "O'SHAUGHNESSY Christopher": "o-shaughnessy-christopher",
    "O'SHAUGHNESSY Essie": "o-shaughnessy-essie",
    "O'SHAUGHNESSY Peter": "o-shaughnessy-peter",
    "O'SHEA Andrea": "o-shea-andrea",
    "O'SHEA Brendan": "o-shea-brendan",
    "O'SHEA Catherine": "o-shea-catherine",
    "O'SHEA Colm": "o-shea-colm",
    "O'SHEA Erin M": "o-shea-erin-m",
    "O'SHEA Gerard": "o-shea-gerard",
    "O'SHEA Heather": "o-shea-heather",
    "O'SHEA James": "o-shea-james",
    "O'SHEA Jennifer": "o-shea-jennifer",
    "O'SHEA John Donald": "o-shea-john-donald",
    "O'SHEA Marie Glancy": "o-shea-marie-glancy",
    "O'SHEA Shawn": "o-shea-shawn",
    "OSHO Andi": "osho-andi",
    "OSHODI Maria": "oshodi-maria",
    "OSIO Elaine": "osio-elaine",
    "OSIRIS Carlos": "osiris-carlos",
    "OSMAN Matthew": "osman-matthew",
    "OSMAN Nils": "osman-nils",
    "OSMENT Philip": "osment-philip",
    "OSMOND Adrian": "osmond-adrian",
    "OSMOND Gemma": "osmond-gemma",
    "OSMOND Gordon": "osmond-gordon",
    "OSMUNDSEN Dave": "osmundsen-dave",
    "OSNER Nigel": "osner-nigel",
    "OSOFISAN Femi": "osofisan-femi",
    "OSOFSKY Randy": "osofsky-randy",
    "OSORIO Pepon": "osorio-pepon",
    "OSPA Jon": "ospa-jon",
    "OSSA Felipe": "ossa-felipe",
    "OSSMAN A": "ossman-a",
    "OST Bob": "ost-bob",
    "OSTEN Suzanne": "osten-suzanne",
    "OSTER Michael": "oster-michael",
    "OSTER Tom": "oster-tom",
    "OSTERGREN Anna": "ostergren-anna",
    "OSTERMAIAR Albert": "ostermaiar-albert",
    "OSTERMAN Georg": "osterman-georg",
    "OSTREGA Jennifer": "ostrega-jennifer",
    "OSTROFF Alan": "ostroff-alan",
    "OSTROVSKY Alexander Nikolayevich": "ostrovsky-alexander-nikolayevich",
    "OSUCH Paul": "osuch-paul",
    "O'SULLIVAN Aileen": "o-sullivan-aileen",
    "O'SULLIVAN Alannah": "o-sullivan-alannah",
    "O'SULLIVAN Camille": "o-sullivan-camille",
    "O'SULLIVAN Ciara": "o-sullivan-ciara",
    "O'SULLIVAN Conor": "o-sullivan-conor",
    "O'SULLIVAN David": "o-sullivan-david",
    "O'SULLIVAN Evan": "o-sullivan-evan",
    "O'SULLIVAN Jennifer": "o-sullivan-jennifer",
    "O'SULLIVAN Kathleen": "o-sullivan-kathleen",
    "O'SULLIVAN Kathryn": "o-sullivan-kathryn",
    "O'SULLIVAN Lawrence": "o-sullivan-lawrence",
    "O'SULLIVAN Margaret": "o-sullivan-margaret",
    "O'SULLIVAN Matthew": "o-sullivan-matthew",
    "O'SULLIVAN Neil": "o-sullivan-neil",
    "O'SULLIVAN Nuala": "o-sullivan-nuala",
    "O'SULLIVAN Patrick": "o-sullivan-patrick",
    "O'SULLIVAN Richie": "o-sullivan-richie",
    "O'SULLIVAN Sam": "o-sullivan-sam",
    "O'SULLIVAN Stephen": "o-sullivan-stephen",
    "O'SULLIVAN Tom": "o-sullivan-tom",
    "O'SULLIVAN Vincent": "o-sullivan-vincent",
    "OSWALD Andrew": "oswald-andrew",
    "OSWALD Debra": "oswald-debra",
    "OSWALD Peter": "oswald-peter",
    "OSWALD Sally": "oswald-sally",
    "OSWALD Sylvan": "oswald-sylvan",
    "OSWALT Trevor": "oswalt-trevor",
    "OSWICK Ralph": "oswick-ralph",
    "OSWIN Cindy": "oswin-cindy",
    "OSWIN Leigh": "oswin-leigh",
    "OSZTREICHER Stephanie": "osztreicher-stephanie",
    "OTALVARO-HORMILLOSA Gigi": "otalvaro-hormillosa-gigi",
    "OTANO Brian": "otano-brian",
    "OTERO Felix": "otero-felix",
    "OTERO Nairoby": "otero-nairoby",
    "OTFINOSKI Steven": "otfinoski-steven",
    "OTHEN Duncan": "othen-duncan",
    "OTHER WAY WORKS ": "other-way-works",
    "OTHERS CLUB, THE ": "others-club",
    "O'THOMAS Mark": "o-thomas-mark",
    "OTIS Frank": "otis-frank",
    "OTIS Marilyn": "otis-marilyn",
    "O'TOOLE Austin": "o-toole-austin",
    "O'TOOLE Bet": "o-toole-bet",
    "O'TOOLE Esther": "o-toole-esther",
    "O'TOOLE James D B": "o-toole-james-d-b",
    "O'TOOLE John": "o-toole-john",
    "OTT Doyle": "ott-doyle",
    "OTT Gustavo": "ott-gustavo",
    "OTT J": "ott-j",
    "OTT John": "ott-john",
    "OTTANO Brian": "ottano-brian",
    "OTTE Charles": "otte-charles",
    "OTTEY Elma": "ottey-elma",
    "OTTO Rebecca B": "otto-rebecca-b",
    "OTTOSON Andy": "ottoson-andy",
    "OTWAY Travers": "otway-travers",
    "OUCHI Mieko": "ouchi-mieko",
    "OUELLETTE Joey": "ouellette-joey",
    "OULD Herman": "ould-herman",
    "OULTON Brian": "oulton-brian",
    "OURIQUE Lena": "ourique-lena",
    "OUSELLAM Naoufal": "ousellam-naoufal",
    "OUSSOREN Joanne": "oussoren-joanne",
    "OUTHOUSE PRODUCTIONS ": "outhouse-productions",
    "OUTLAN Anne": "outlan-anne",
    "OUTLAW Paul": "outlaw-paul",
    "OUTRAM Michelle": "outram-michelle",
    "OUTSIDE EDGE ": "outside-edge",
    "OUTWARDBOUND PROJET ": "outwardbound-projet",
    "OUTZEN Martin": "outzen-martin",
    "OUZOUNIAN Richard": "ouzounian-richard",
    "OUZOUNIDIS Christina": "ouzounidis-christina",
    "OVAL THEATRE GROUP OF LONDON ": "oval-theatre-group-of-london",
    "O'VALLE Violet": "o-valle-violet",
    "OVER THE EDGE ": "over-the-edge",
    "OVERBEY Kellie": "overbey-kellie",
    "OVERETT Adam": "overett-adam",
    "OVERMAN Sarah": "overman-sarah",
    "OVERMYER Eric": "overmyer-eric",
    "OVERSTREET Joe": "overstreet-joe",
    "OVERTON Bill": "overton-bill",
    "OVERTON David": "overton-david",
    "OVERTON Josh": "overton-josh",
    "OVERTON M": "overton-m",
    "OVERTON Marq": "overton-marq",
    "OVERTON Shawn": "overton-shawn",
    "OVERTREE Lee": "overtree-lee",
    "OWA ": "owa",
    "OWAD Steven": "owad-steven",
    "OWEN Alexander": "owen-alexander",
    "OWEN Alun": "owen-alun",
    "OWEN Amanda": "owen-amanda",
    "OWEN Armitage": "owen-armitage",
    "OWEN Ashleigh": "owen-ashleigh",
    "OWEN Beccy": "owen-beccy",
    "OWEN Bill": "owen-bill",
    "OWEN Bryan": "owen-bryan",
    "OWEN Carmel": "owen-carmel",
    "OWEN Chris": "owen-chris",
    "OWEN Christopher": "owen-christopher",
    "OWEN David": "owen-david",
    "OWEN Debbie": "owen-debbie",
    "OWEN Dilys": "owen-dilys",
    "OWEN E W": "owen-e-w",
    "OWEN Edward": "owen-edward",
    "OWEN Eluned": "owen-eluned",
    "OWEN Gabriel": "owen-gabriel",
    "OWEN Gareth": "owen-gareth",
    "OWEN Gary": "owen-gary",
    "OWEN George P": "owen-george-p",
    "OWEN Gregory J": "owen-gregory-j",
    "OWEN Harrison": "owen-harrison",
    "OWEN John": "owen-john",
    "OWEN John Glyn": "owen-john-glyn",
    "OWEN Jonathan": "owen-jonathan",
    "OWEN Kari Ann": "owen-kari-ann",
    "OWEN Katy": "owen-katy",
    "OWEN Ken": "owen-ken",
    "OWEN Laura": "owen-laura",
    "OWEN Luke": "owen-luke",
    "OWEN Lyla Hay": "owen-lyla-hay",
    "OWEN Mari Rhian": "owen-mari-rhian",
    "OWEN Mark": "owen-mark",
    "OWEN Matt": "owen-matt",
    "OWEN Rena": "owen-rena",
    "OWEN Richard": "owen-richard",
    "OWEN Robert": "owen-robert",
    "OWEN Sally": "owen-sally",
    "OWEN Sarah": "owen-sarah",
    "OWEN Sian": "owen-sian",
    "OWEN Susannah": "owen-susannah",
    "OWEN Will": "owen-will",
    "OWEN Will (1)": "owen-will-1",
    "OWEN Wynford Ellis": "owen-wynford-ellis",
    "OWENS Daniel W": "owens-daniel-w",
    "OWENS Greg": "owens-greg",
    "OWENS Ian Scott": "owens-ian-scott",
    "OWENS Jon Tyler": "owens-jon-tyler",
    "OWENS Jordana": "owens-jordana",
    "OWENS Kristopher": "owens-kristopher",
    "OWENS Lisa": "owens-lisa",
    "OWENS Robert": "owens-robert",
    "OWENS Rochelle": "owens-rochelle",
    "OWENS Ron": "owens-ron",
    "OWENS Sean": "owens-sean",
    "OWENS Sian": "owens-sian",
    "OWENS Stacia Saint": "owens-stacia-saint",
    "OWEN-WRIGHT Hannah": "owen-wright-hannah",
    "OWINGS Adrianne": "owings-adrianne",
    "OWREN Cate": "owren-cate",
    "OWUSU Martin": "owusu-martin",
    "OWUSU Nadia": "owusu-nadia",
    "OXENBOULD Jamie": "oxenbould-jamie",
    "OXFORD STAGE COMPANY ": "oxford-stage-company",
    "OXLEY Stephen": "oxley-stephen",
    "OXMAN Mark": "oxman-mark",
    "OYA Berkun": "oya-berkun",
    "OYAMA Sachi": "oyama-sachi",
    "OYAMO Ujamaa": "oyamo-ujamaa",
    "OYEDELE Obamola": "oyedele-obamola",
    "OYEDEPO Stella": "oyedepo-stella",
    "OYEN Alan": "oyen-alan",
    "OYEN Alexander Sage": "oyen-alexander-sage",
    "OYEWOLE Abiodun": "oyewole-abiodun",
    "OYEYEMI Helen": "oyeyemi-helen",
    "OYONO-MBIA Guillaume": "oyono-mbia-guillaume",
    "OZ Milo J": "oz-milo-j",
    "OZANICH David": "ozanich-david",
    "OZAWA Matthew": "ozawa-matthew",
    "OZBILGIN Handan": "ozbilgin-handan",
    "OZDOGRU Nuvit": "ozdogru-nuvit",
    "OZHABES Ozlem": "ozhabes-ozlem",
    "OZNIE Loren": "oznie-loren"
  }
};