export default {
  "metadata": {
    "results": 480,
    "timeStamp": "2025-12-05T21:29:56.192Z",
    "url": "https://www.doollee.com/PlaywrightsP/P_playwrights_g-l.php"
  },
  "authors": {
    "PHALLEN Tracey": "phallen-tracey",
    "PHAM Ethan": "pham-ethan",
    "PHAM Hoa": "pham-hoa",
    "PHAN Tuan": "phan-tuan",
    "PHANEUF Gail": "phaneuf-gail",
    "PHARRIS Chrystee": "pharris-chrystee",
    "PHARRISS Lotti Louise": "pharriss-lotti-louise",
    "PHEGAN Jane": "phegan-jane",
    "PHELAN Alina": "phelan-alina",
    "PHELAN Anna Hamilton": "phelan-anna-hamilton",
    "PHELAN Anne": "phelan-anne",
    "PHELAN Brian": "phelan-brian",
    "PHELAN J E": "phelan-j-e",
    "PHELAN Mike": "phelan-mike",
    "PHELAN Trish": "phelan-trish",
    "PHELOUNG Jon": "pheloung-jon",
    "PHELPS Barry": "phelps-barry",
    "PHELPS Courtney": "phelps-courtney",
    "PHELPS Jake": "phelps-jake",
    "PHELPS John": "phelps-john",
    "PHELPS Kate": "phelps-kate",
    "PHELPS Marita": "phelps-marita",
    "PHELPS Sarah": "phelps-sarah",
    "PHELPS Winifred": "phelps-winifred",
    "PHENNER Lee": "phenner-lee",
    "PHEWA Asanda": "phewa-asanda",
    "PHI Bao": "phi-bao",
    "PHIBES A V": "phibes-a-v",
    "PHILIP Eileen": "philip-eileen",
    "PHILIP John": "philip-john",
    "PHILIP M Nourbese": "philip-m-nourbese",
    "PHILIP Peter": "philip-peter",
    "PHILIPPI Jessica": "philippi-jessica",
    "PHILIPPI Renee": "philippi-renee",
    "PHILIPPOGLOU Kostas": "philippoglou-kostas",
    "PHILIPPOU Nick": "philippou-nick",
    "PHILIPS A": "philips-a",
    "PHILIPS Barbara": "philips-barbara",
    "PHILIPS Harrison": "philips-harrison",
    "PHILIPS James": "philips-james",
    "PHILIPS Maha Khan": "philips-maha-khan",
    "PHILIPS Pete": "philips-pete",
    "PHILIPS Robert": "philips-robert",
    "PHILIPS Stephen": "philips-stephen",
    "PHILL Kim": "phill-kim",
    "PHILLEY Cory": "philley-cory",
    "PHILLIP Bekah": "phillip-bekah",
    "PHILLIPPE Alexandre": "phillippe-alexandre",
    "PHILLIPPI Jessica": "phillippi-jessica",
    "PHILLIPPS R": "phillipps-r",
    "PHILLIPS Alison": "phillips-alison",
    "PHILLIPS Anne": "phillips-anne",
    "PHILLIPS April": "phillips-april",
    "PHILLIPS Arthur": "phillips-arthur",
    "PHILLIPS Arthur (1)": "phillips-arthur-1",
    "PHILLIPS Brian": "phillips-brian",
    "PHILLIPS Bruce": "phillips-bruce",
    "PHILLIPS Cally": "phillips-cally",
    "PHILLIPS Caryl": "phillips-caryl",
    "PHILLIPS Charlie": "phillips-charlie",
    "PHILLIPS Chris": "phillips-chris",
    "PHILLIPS Chrys": "phillips-chrys",
    "PHILLIPS Claudia E M": "phillips-claudia-e-m",
    "PHILLIPS Eden": "phillips-eden",
    "PHILLIPS Erin": "phillips-erin",
    "PHILLIPS Ethan": "phillips-ethan",
    "PHILLIPS Gregory Allen": "phillips-gregory-allen",
    "PHILLIPS Griff": "phillips-griff",
    "PHILLIPS Hannah": "phillips-hannah",
    "PHILLIPS Henry": "phillips-henry",
    "PHILLIPS Holly": "phillips-holly",
    "PHILLIPS Irving": "phillips-irving",
    "PHILLIPS James": "phillips-james",
    "PHILLIPS Jason": "phillips-jason",
    "PHILLIPS Jennifer": "phillips-jennifer",
    "PHILLIPS Julie": "phillips-julie",
    "PHILLIPS Kate": "phillips-kate",
    "PHILLIPS Kathleen": "phillips-kathleen",
    "PHILLIPS Klaus": "phillips-klaus",
    "PHILLIPS Lindsey": "phillips-lindsey",
    "PHILLIPS Lisa Faith": "phillips-lisa-faith",
    "PHILLIPS Louis": "phillips-louis",
    "PHILLIPS M": "phillips-m",
    "PHILLIPS Malanie": "phillips-malanie",
    "PHILLIPS Mary Bracken": "phillips-mary-bracken",
    "PHILLIPS Meg": "phillips-meg",
    "PHILLIPS Melanie": "phillips-melanie",
    "PHILLIPS Mike": "phillips-mike",
    "PHILLIPS Naima Kristel": "phillips-naima-kristel",
    "PHILLIPS Nathan": "phillips-nathan",
    "PHILLIPS Neville": "phillips-neville",
    "PHILLIPS Nicky": "phillips-nicky",
    "PHILLIPS Owen": "phillips-owen",
    "PHILLIPS Paul": "phillips-paul",
    "PHILLIPS Peggy": "phillips-peggy",
    "PHILLIPS Peter": "phillips-peter",
    "PHILLIPS Phillip": "phillips-phillip",
    "PHILLIPS Redmond": "phillips-redmond",
    "PHILLIPS Robert": "phillips-robert",
    "PHILLIPS Ron": "phillips-ron",
    "PHILLIPS Ronald Selwyn": "phillips-ronald-selwyn",
    "PHILLIPS Sarah": "phillips-sarah",
    "PHILLIPS Shereen Jasmin": "phillips-shereen-jasmin",
    "PHILLIPS Stephanie": "phillips-stephanie",
    "PHILLIPS Stephen": "phillips-stephen",
    "PHILLIPS Terry": "phillips-terry",
    "PHILLIPS Thaddeus": "phillips-thaddeus",
    "PHILLIPS Tony": "phillips-tony",
    "PHILLIPS W": "phillips-w",
    "PHILLIPS Zara": "phillips-zara",
    "PHILLIPS-MILES Kathryn": "phillips-miles-kathryn",
    "PHILLIS Michael": "phillis-michael",
    "PHILP Peter": "philp-peter",
    "PHILPOTT Chris": "philpott-chris",
    "PHILPOTT Lachlan": "philpott-lachlan",
    "PHIPPEN Angela": "phippen-angela",
    "PHIPPIN Jackson": "phippin-jackson",
    "PHIPPS Katy": "phipps-katy",
    "PHIPPS LaTonia": "phipps-latonia",
    "PHIPPS Wanda": "phipps-wanda",
    "PHIRI Saimon Mbazo": "phiri-saimon-mbazo",
    "PHOBOS Kaiser": "phobos-kaiser",
    "PHOENIX Charles": "phoenix-charles",
    "PHOENIX Grayian": "phoenix-grayian",
    "PHOENIX Isis": "phoenix-isis",
    "PHOENIX Mark": "phoenix-mark",
    "PHOENIX Nell": "phoenix-nell",
    "PHOENIX Sal Atlantis": "phoenix-sal-atlantis",
    "PHYSICAL Dv8": "physical-dv8",
    "PIANTADOSI Francesca": "piantadosi-francesca",
    "PIATEK Drew Derek": "piatek-drew-derek",
    "PIATELLI Mark": "piatelli-mark",
    "PIATIGORSKY Anton": "piatigorsky-anton",
    "PIATKA Naava": "piatka-naava",
    "PIAZA Jim": "piaza-jim",
    "PIAZZA Ben Daniel": "piazza-ben-daniel",
    "PIAZZA Jim": "piazza-jim",
    "PIAZZA Rene J F": "piazza-rene-j-f",
    "PICANO Felice": "picano-felice",
    "PICARDI John C": "picardi-john-c",
    "PICARDIE Michael": "picardie-michael",
    "PICASSO Pablo": "picasso-pablo",
    "PICAULT Adeline": "picault-adeline",
    "PICCININ Laura": "piccinin-laura",
    "PICCIONE Anthony J": "piccione-anthony-j",
    "PICCIONE Rachel Astarte": "piccione-rachel-astarte",
    "PICCIRILLO Tony": "piccirillo-tony",
    "PICCO Charles": "picco-charles",
    "PICCO Ulises Raul": "picco-ulises-raul",
    "PICCOLO Linda": "piccolo-linda",
    "PICHETTE David": "pichette-david",
    "PICHEY Martha": "pichey-martha",
    "PICK Dan": "pick-dan",
    "PICK J": "pick-j",
    "PICK J R": "pick-j-r",
    "PICKARD Christina": "pickard-christina",
    "PICKARD Edward Earl": "pickard-edward-earl",
    "PICKARD Jeremy": "pickard-jeremy",
    "PICKARD Lee": "pickard-lee",
    "PICKARD Liz": "pickard-liz",
    "PICKARD Wayland": "pickard-wayland",
    "PICKERING Barbara": "pickering-barbara",
    "PICKERING Felicity": "pickering-felicity",
    "PICKERING Ken": "pickering-ken",
    "PICKERING Paul": "pickering-paul",
    "PICKERING Steve": "pickering-steve",
    "PICKET Bobby": "picket-bobby",
    "PICKETT James Carroll": "pickett-james-carroll",
    "PICKETT Jane": "pickett-jane",
    "PICKETT Lenny": "pickett-lenny",
    "PICKETT Rex": "pickett-rex",
    "PICKETT Richard J": "pickett-richard-j",
    "PICKFORD Dennis": "pickford-dennis",
    "PICKIN Mary": "pickin-mary",
    "PICKLES Anne": "pickles-anne",
    "PICKLES Chris": "pickles-chris",
    "PICKLES Thomas": "pickles-thomas",
    "PICKTHALL Antony": "pickthall-antony",
    "PICKTHALL David": "pickthall-david",
    "PICKTHALL Jane": "pickthall-jane",
    "PICKUP Lawrence": "pickup-lawrence",
    "PICOT Guy": "picot-guy",
    "PICOULT Darci": "picoult-darci",
    "PICOULT Jodi": "picoult-jodi",
    "PICQ Jean-Yves": "picq-jean-yves",
    "PICUS Paul": "picus-paul",
    "PIDD David": "pidd-david",
    "PIE Anne": "pie-anne",
    "PIECH Brian Theodore": "piech-brian-theodore",
    "PIECZANSKI Juan": "pieczanski-juan",
    "PIEGARI Natalie": "piegari-natalie",
    "PIEHLER Christopher": "piehler-christopher",
    "PIEJUS Tanya": "piejus-tanya",
    "PIELMEIER John": "pielmeier-john",
    "PIEMME Jean-Marie": "piemme-jean-marie",
    "PIERACCINI Sita": "pieraccini-sita",
    "PIERCE Bob": "pierce-bob",
    "PIERCE Brooke": "pierce-brooke",
    "PIERCE Chris": "pierce-chris",
    "PIERCE Colleen": "pierce-colleen",
    "PIERCE Crystal": "pierce-crystal",
    "PIERCE Gregory": "pierce-gregory",
    "PIERCE Jeff": "pierce-jeff",
    "PIERCE Jennifer": "pierce-jennifer",
    "PIERCE Nina Bunche": "pierce-nina-bunche",
    "PIERCE Rebekah L": "pierce-rebekah-l",
    "PIERCE Richard LaMonte": "pierce-richard-lamonte",
    "PIERCE Thomas": "pierce-thomas",
    "PIERCE Walter": "pierce-walter",
    "PIEROTTI Greg": "pierotti-greg",
    "PIERPAN Nicholas": "pierpan-nicholas",
    "PIERRE Joseph Jomo": "pierre-joseph-jomo",
    "PIERSON June": "pierson-june",
    "PIERSON Lance": "pierson-lance",
    "PIERSON Lola": "pierson-lola",
    "PIESSE Joanna": "piesse-joanna",
    "PIETRI Pedro Juan": "pietri-pedro-juan",
    "PIETROWSKI John": "pietrowski-john",
    "PIETTE Alain": "piette-alain",
    "PIETZNER Carlo": "pietzner-carlo",
    "PIFER Drury": "pifer-drury",
    "PIG IRON COMPANY ": "pig-iron-company",
    "PIGE Guillaume": "pige-guillaume",
    "PIGGOTT Tom": "piggott-tom",
    "PIGNATARO Margie": "pignataro-margie",
    "PIGOTT Michael": "pigott-michael",
    "PIGOTT-SMITH Tim": "pigott-smith-tim",
    "PIGPEN THEATRE COMPANY ": "pigpen-theatre-company",
    "PIIZZI Dominick": "piizzi-dominick",
    "PIKE Alana": "pike-alana",
    "PIKE Bonnie": "pike-bonnie",
    "PIKE Charles": "pike-charles",
    "PIKE Charlotte": "pike-charlotte",
    "PIKE Earl A": "pike-earl-a",
    "PIKE J": "pike-j",
    "PIKE Lori": "pike-lori",
    "PIKE Neal": "pike-neal",
    "PILAPITIYA Rashmi": "pilapitiya-rashmi",
    "PILBEAM Peter": "pilbeam-peter",
    "PILCH Michael": "pilch-michael",
    "PILCHER Rosamunde": "pilcher-rosamunde",
    "PILDITCH Charles": "pilditch-charles",
    "PILGRIM Geraldine": "pilgrim-geraldine",
    "PILIKIAN Vaughan": "pilikian-vaughan",
    "PILK Henry": "pilk-henry",
    "PILKINGTON Ace": "pilkington-ace",
    "PILKINGTON Alan": "pilkington-alan",
    "PILKINGTON Gareth": "pilkington-gareth",
    "PILL Astrid": "pill-astrid",
    "PILLAI Govind": "pillai-govind",
    "PILLATZKI-WARZEHA Sara": "pillatzki-warzeha-sara",
    "PILLAY Kriben": "pillay-kriben",
    "PILLER Ileinar": "piller-ileinar",
    "PILLING Chris": "pilling-chris",
    "PILLING Jayne": "pilling-jayne",
    "PILLSBURY Corley": "pillsbury-corley",
    "PILLSBURY Marianne": "pillsbury-marianne",
    "PILOT THEATRE COMPANY ": "pilot-theatre-company",
    "PILTON Jacqueline": "pilton-jacqueline",
    "PIMLOTT Amelia": "pimlott-amelia",
    "PINA Gabrielle": "pina-gabrielle",
    "PINCHBECK Michael": "pinchbeck-michael",
    "PINCHON Kirk": "pinchon-kirk",
    "PINCHUK Ellen": "pinchuk-ellen",
    "PINCHVANISH ": "pinchvanish",
    "PINCKNEY Darryl": "pinckney-darryl",
    "PINCKNEY Tim": "pinckney-tim",
    "PINDER Alex": "pinder-alex",
    "PINE Darren": "pine-darren",
    "PINE Evelyn Jean": "pine-evelyn-jean",
    "PINE Robert": "pine-robert",
    "PINE William": "pine-william",
    "PINEAULI Wallace John": "pineauli-wallace-john",
    "PINERA Virgilio": "pinera-virgilio",
    "PINERO Arthur Wing": "pinero-arthur-wing",
    "PINERO Miguel": "pinero-miguel",
    "PINES Henry": "pines-henry",
    "PINES Hiram": "pines-hiram",
    "PINFIELD Geoff": "pinfield-geoff",
    "PING Chin Woon": "ping-chin-woon",
    "PINGET Robert": "pinget-robert",
    "PINHEIRO Sandra": "pinheiro-sandra",
    "PINILLA Pablo": "pinilla-pablo",
    "PINK Andrea Sloan": "pink-andrea-sloan",
    "PINK Colin": "pink-colin",
    "PINK Scarlet": "pink-scarlet",
    "PINKARD Jeremy": "pinkard-jeremy",
    "PINKERTON Daniel": "pinkerton-daniel",
    "PINKHAM Roger": "pinkham-roger",
    "PINKHAM Tylila": "pinkham-tylila",
    "PINKINS Tonya": "pinkins-tonya",
    "PINKNEY Darryl": "pinkney-darryl",
    "PINKNEY John": "pinkney-john",
    "PINKNEY Kendell R": "pinkney-kendell-r",
    "PINKOSH Mark": "pinkosh-mark",
    "PINKOWSKI Edward": "pinkowski-edward",
    "PINKUS Phillip": "pinkus-phillip",
    "PINNE Peter N": "pinne-peter-n",
    "PINNER David": "pinner-david",
    "PINNER David (1)": "pinner-david-1",
    "PINNER Richard": "pinner-richard",
    "PINNINGTON Misha": "pinnington-misha",
    "PINNINGTON Phil": "pinnington-phil",
    "PINNINGTON Yvonne": "pinnington-yvonne",
    "PINNOCK Winsome": "pinnock-winsome",
    "PINO H Patrick": "pino-h-patrick",
    "PINOCK Danielle": "pinock-danielle",
    "PINS AND NEEDLES ": "pins-and-needles",
    "PINSENT Gordon": "pinsent-gordon",
    "PINSKI David": "pinski-david",
    "PINSKY Richard": "pinsky-richard",
    "PINSKY Robert": "pinsky-robert",
    "PINSON Paul": "pinson-paul",
    "PINTAURO Joe": "pintauro-joe",
    "PINTER Harold": "pinter-harold",
    "PINTILEI Gabriel": "pintilei-gabriel",
    "PINTO Fernando Costa": "pinto-fernando-costa",
    "PINTO Gilberto": "pinto-gilberto",
    "PINTO Joanna": "pinto-joanna",
    "PINTO P William": "pinto-p-william",
    "PINTO Paul": "pinto-paul",
    "PINTO Ricardo": "pinto-ricardo",
    "PINYAN Andrea": "pinyan-andrea",
    "PIORECK Richard": "pioreck-richard",
    "PIOTROWSKI Andrew": "piotrowski-andrew",
    "PIPE Alana": "pipe-alana",
    "PIPER Andy": "piper-andy",
    "PIPER Christopher": "piper-christopher",
    "PIPER Debra Jo": "piper-debra-jo",
    "PIPER Elvi": "piper-elvi",
    "PIPER Leonard": "piper-leonard",
    "PIPER Myfanwy": "piper-myfanwy",
    "PIPES Eliana": "pipes-eliana",
    "PIPINO Kiara": "pipino-kiara",
    "PIPPA Cristina": "pippa-cristina",
    "PIPPIN Don": "pippin-don",
    "PIRANDELLO Luigi": "pirandello-luigi",
    "PIRE Felix": "pire-felix",
    "PIRIE Chris": "pirie-chris",
    "PIRIE Steve": "pirie-steve",
    "PIRINEN Joakim": "pirinen-joakim",
    "PIRIS Paul": "piris-paul",
    "PIRKO Angela": "pirko-angela",
    "PIRMOHAMED Taz": "pirmohamed-taz",
    "PIROMAN John": "piroman-john",
    "PIROS Sherry": "piros-sherry",
    "PIROT Steve": "pirot-steve",
    "PIROTTA Saviour": "pirotta-saviour",
    "PISANO-THOMSEN John": "pisano-thomsen-john",
    "PISARRA Drew": "pisarra-drew",
    "PISCATOR Erwin": "piscator-erwin",
    "PISEMSKY Alexey": "pisemsky-alexey",
    "PISONI Lorenzo": "pisoni-lorenzo",
    "PITA Arthur": "pita-arthur",
    "PITARD Sarah": "pitard-sarah",
    "PITCAIRNE Archibald": "pitcairne-archibald",
    "PITCHER Jeff": "pitcher-jeff",
    "PITCHER Oliver": "pitcher-oliver",
    "PITCHETT Georgia": "pitchett-georgia",
    "PITCHFORD Dean": "pitchford-dean",
    "PITCHFORTH Josiah Miles": "pitchforth-josiah-miles",
    "PITHIE I S": "pithie-i-s",
    "PITKIN Andrew Thomas": "pitkin-andrew-thomas",
    "PITKIN Bruce Alexander": "pitkin-bruce-alexander",
    "PITT Chris": "pitt-chris",
    "PITT Daniel": "pitt-daniel",
    "PITT Matthew": "pitt-matthew",
    "PITTENGER Jasmine": "pittenger-jasmine",
    "PITTENGER Laura A": "pittenger-laura-a",
    "PITTMAN Al": "pittman-al",
    "PITTMAN Arthur": "pittman-arthur",
    "PITTMAN Jason": "pittman-jason",
    "PITT-RIVERS Sonia": "pitt-rivers-sonia",
    "PITTS Daniel": "pitts-daniel",
    "PITTS Graham": "pitts-graham",
    "PITTS Lucia Mae": "pitts-lucia-mae",
    "PITTS Tom": "pitts-tom",
    "PITTU David": "pittu-david",
    "PITZER Stefine K": "pitzer-stefine-k",
    "PITZER Susanna": "pitzer-susanna",
    "PIUCCI Joanna": "piucci-joanna",
    "PIVAR Amy": "pivar-amy",
    "PIVEN Joshua": "piven-joshua",
    "PIVEN Joyce": "piven-joyce",
    "PIVEN Shira": "piven-shira",
    "PIX Mary": "pix-mary",
    "PIXLET Frank": "pixlet-frank",
    "PIZZANTE Raymond": "pizzante-raymond",
    "PIZZARELLO Jason": "pizzarello-jason",
    "PIZZARELLO Maria": "pizzarello-maria",
    "PIZZUTO John": "pizzuto-john",
    "PJM ": "pjm",
    "PLA Ruben": "pla-ruben",
    "PLACEY Evan": "placey-evan",
    "PLACZEK Walter": "placzek-walter",
    "PLAICE Andrew": "plaice-andrew",
    "PLAICE Neville": "plaice-neville",
    "PLAICE Stephen": "plaice-stephen",
    "PLAICE-SHEPHERD Morag": "plaice-shepherd-morag",
    "PLAMONDON Luc": "plamondon-luc",
    "PLANCHE J R": "planche-j-r",
    "PLANELL David": "planell-david",
    "PLANER Nigel": "planer-nigel",
    "PLANR Beatrice M": "planr-beatrice-m",
    "PLANT Michael": "plant-michael",
    "PLANT Peggy": "plant-peggy",
    "PLANT Philip Paul": "plant-philip-paul",
    "PLANT S R": "plant-s-r",
    "PLANTE Patricia": "plante-patricia",
    "PLASTICINE MEN ": "plasticine-men",
    "PLATEL Alain": "platel-alain",
    "PLATER Alan": "plater-alan",
    "PLATER Diana": "plater-diana",
    "PLATER Janet": "plater-janet",
    "PLATFORM 4 ": "platform-4",
    "PLATH J Argyl": "plath-j-argyl",
    "PLATH Sara": "plath-sara",
    "PLATH Sylvia": "plath-sylvia",
    "PLATT Adam": "platt-adam",
    "PLATT David": "platt-david",
    "PLATT Jason Gray": "platt-jason-gray",
    "PLATT Louise": "platt-louise",
    "PLATT Martin": "platt-martin",
    "PLATT Peggy": "platt-peggy",
    "PLATT Raymond": "platt-raymond",
    "PLATT Reg": "platt-reg",
    "PLATT Rory": "platt-rory",
    "PLATT Ruth": "platt-ruth",
    "PLATT Susan": "platt-susan",
    "PLATT Susan McMath": "platt-susan-mcmath",
    "PLATTS Moyra": "platts-moyra",
    "PLATTS-MILLS Ruby": "platts-mills-ruby",
    "PLAUTUS ": "plautus",
    "PLAYFAIR Nigel": "playfair-nigel",
    "PLAZA Begonya": "plaza-begonya",
    "PLEASANCE Donald": "pleasance-donald",
    "PLEASANT William": "pleasant-william",
    "PLEDGER David": "pledger-david",
    "PLENTIE Debbie": "plentie-debbie",
    "PLENZDORF Ulrich": "plenzdorf-ulrich",
    "PLESTED Clare": "plested-clare",
    "PLESTER Tim": "plester-tim",
    "PLEVA Ruth": "pleva-ruth",
    "PLEWS John": "plews-john",
    "PLEXUS ": "plexus",
    "PLIMPTON George": "plimpton-george",
    "PLINER Eric": "pliner-eric",
    "PLISKA Greg": "pliska-greg",
    "PLITZCO Christina": "plitzco-christina",
    "PLOETZ Richard": "ploetz-richard",
    "PLOMLEY Roy": "plomley-roy",
    "PLOPPER Ben": "plopper-ben",
    "PLOSS Jim": "ploss-jim",
    "PLOTCH Dina": "plotch-dina",
    "PLOTH Kevin B": "ploth-kevin-b",
    "PLOTKIN Richard James": "plotkin-richard-james",
    "PLOTKIN Sami": "plotkin-sami",
    "PLOTNICK Jack": "plotnick-jack",
    "PLOUFFE Gilles": "plouffe-gilles",
    "PLOUG Sidse": "ploug-sidse",
    "PLOWDEN Hugo": "plowden-hugo",
    "PLOWMAN Gillian": "plowman-gillian",
    "PLOWMAN Lynne": "plowman-lynne",
    "PLOWMAN Robert": "plowman-robert",
    "PLOWMAN Santa": "plowman-santa",
    "PLUESS Andre J": "pluess-andre-j",
    "PLUMB Emily": "plumb-emily",
    "PLUMB Kate": "plumb-kate",
    "PLUMB Vivienne": "plumb-vivienne",
    "PLUMLEY Norma J": "plumley-norma-j",
    "PLUMMER Joe": "plummer-joe",
    "PLUMMER Terri": "plummer-terri",
    "PLUMPTRE James": "plumptre-james",
    "PLUNKETT Edward": "plunkett-edward",
    "PLUNKETT James": "plunkett-james",
    "PLUNKETT Lorraine": "plunkett-lorraine",
    "PLUNKETT Paul": "plunkett-paul",
    "PLUNKETT Rebecca Elizabeth": "plunkett-rebecca-elizabeth",
    "PLUNKETT Stephen": "plunkett-stephen",
    "PLUTA Leonard": "pluta-leonard"
  }
};