export default {
  "metadata": {
    "results": 124,
    "timeStamp": "2025-12-05T21:30:02.241Z",
    "url": "https://www.doollee.com/PlaywrightsP/P_playwrights_s-z.php"
  },
  "authors": {
    "PSAILA Anthony": "psaila-anthony",
    "PSALMAYENE 24 ": "psalmayene-24",
    "PSHETZ Nicole": "pshetz-nicole",
    "PSOMAS Maria": "psomas-maria",
    "PTACEK Stephen": "ptacek-stephen",
    "PTSHKINA Nadezhda": "ptshkina-nadezhda",
    "PTTP ENSEMBLE, THE ": "pttp-ensemble",
    "PTUSHKINA Nadezhda": "ptushkina-nadezhda",
    "PUBLIC PARTS ": "public-parts",
    "PUBLICK TRANSPORT  ": "publick-transport",
    "PUCCIA Kyle": "puccia-kyle",
    "PUCCIANI Oreste F": "pucciani-oreste-f",
    "PUCCIONI Madeline": "puccioni-madeline",
    "PUCKETT Chuck": "puckett-chuck",
    "PUCKETT Patricia": "puckett-patricia",
    "PUGA Ana Elena": "puga-ana-elena",
    "PUGACH Brian": "pugach-brian",
    "PUGET Claude-Andre": "puget-claude-andre",
    "PUGH Ann": "pugh-ann",
    "PUGH Bob": "pugh-bob",
    "PUGH Brian": "pugh-brian",
    "PUGH Deborah": "pugh-deborah",
    "PUGH Gilly": "pugh-gilly",
    "PUGH Jane": "pugh-jane",
    "PUGH Jane (1)": "pugh-jane-1",
    "PUGH Michael": "pugh-michael",
    "PUGH Nigel": "pugh-nigel",
    "PUGLIESE Frank": "pugliese-frank",
    "PUGLIESE S": "pugliese-s",
    "PUGMIRE Neil": "pugmire-neil",
    "PUGSLEY Julian": "pugsley-julian",
    "PUGSLEY William": "pugsley-william",
    "PUIG Manuel": "puig-manuel",
    "PULEO Anthony": "puleo-anthony",
    "PULICK Dan": "pulick-dan",
    "PULINOVICH Yaroslava": "pulinovich-yaroslava",
    "PULL Barry": "pull-barry",
    "PULLAN Bruce": "pullan-bruce",
    "PULLAN Ru": "pullan-ru",
    "PULLEN Billy M": "pullen-billy-m",
    "PULLEN Denise": "pullen-denise",
    "PULLEN Elizabeth": "pullen-elizabeth",
    "PULLEN Melanie Clark": "pullen-melanie-clark",
    "PULLMAN Philip": "pullman-philip",
    "PULMAN Jack": "pulman-jack",
    "PULMAN Liza": "pulman-liza",
    "PULO Stella": "pulo-stella",
    "PULOS Rick": "pulos-rick",
    "PULSFORD Charles": "pulsford-charles",
    "PULSFORD Elizabeth": "pulsford-elizabeth",
    "PULSIPHER Anne Barbara": "pulsipher-anne-barbara",
    "PULVER John W": "pulver-john-w",
    "PULVERS Roger": "pulvers-roger",
    "PUMA Joan": "puma-joan",
    "PUMO David": "pumo-david",
    "PUNCHDRUNK ": "punchdrunk",
    "PUNCHES Nathaniel": "punches-nathaniel",
    "PUNG Alice": "pung-alice",
    "PUNSHON Sarah": "punshon-sarah",
    "PUNTER Michael": "punter-michael",
    "PUOHOTAUA Sonya": "puohotaua-sonya",
    "PURA Talia": "pura-talia",
    "PURCARETE Silviu": "purcarete-silviu",
    "PURCELL Alice": "purcell-alice",
    "PURCELL Charles": "purcell-charles",
    "PURCELL Deirdre": "purcell-deirdre",
    "PURCELL Erin Quinn": "purcell-erin-quinn",
    "PURCELL Harold": "purcell-harold",
    "PURCELL Ian": "purcell-ian",
    "PURCELL Joe": "purcell-joe",
    "PURCELL Kathleen": "purcell-kathleen",
    "PURCELL Kevin": "purcell-kevin",
    "PURCELL Kevin J": "purcell-kevin-j",
    "PURCELL Laura": "purcell-laura",
    "PURCELL Leah": "purcell-leah",
    "PURCELL Malcolm": "purcell-malcolm",
    "PURCEY R J": "purcey-r-j",
    "PURCHESE Barry": "purchese-barry",
    "PURDEY R J": "purdey-r-j",
    "PURDIE David": "purdie-david",
    "PURDIE Howard": "purdie-howard",
    "PURDUE Richard B": "purdue-richard-b",
    "PURDY Anna": "purdy-anna",
    "PURDY James": "purdy-james",
    "PURDY Jason": "purdy-jason",
    "PURDY Victor S": "purdy-victor-s",
    "PURNELL Chris": "purnell-chris",
    "PURNELL Richard": "purnell-richard",
    "PURNHAGEN Greg": "purnhagen-greg",
    "PUROHIT Deepa": "purohit-deepa",
    "PUROHIT Kiran": "purohit-kiran",
    "PURROY Marco": "purroy-marco",
    "PURSCELL Phyllis": "purscell-phyllis",
    "PURSELL Stuart": "pursell-stuart",
    "PURVES David": "purves-david",
    "PURVES John": "purves-john",
    "PURVIS Adam": "purvis-adam",
    "PURVIS Bronwyn": "purvis-bronwyn",
    "PURVIS Justin": "purvis-justin",
    "PURVIS Raymond": "purvis-raymond",
    "PUSCH Hans": "pusch-hans",
    "PUSCH Ruth": "pusch-ruth",
    "PUSHKIN Alexander": "pushkin-alexander",
    "PUSSYWILLOW Edgar": "pussywillow-edgar",
    "PUTCH Mark Anthony": "putch-mark-anthony",
    "PUTNAM Bryan": "putnam-bryan",
    "PUTT JR Barry M": "putt-barry-m",
    "PUWANARAJAH Prasanna": "puwanarajah-prasanna",
    "PUZZO Michael": "puzzo-michael",
    "PY Olivier": "py-olivier",
    "PYETTE Jason": "pyette-jason",
    "PYKE Charlotte": "pyke-charlotte",
    "PYKE Jim": "pyke-jim",
    "PYLE Howard": "pyle-howard",
    "PYLE Mary Thurman": "pyle-mary-thurman",
    "PYLIOTIS Hanna": "pyliotis-hanna",
    "PYM Barbara": "pym-barbara",
    "PYNCHON Kirk": "pynchon-kirk",
    "PYNN Irene L": "pynn-irene-l",
    "PYRAMIDE ": "pyramide",
    "PYRE Felix": "pyre-felix",
    "PYRLIK Kali": "pyrlik-kali",
    "PYROS John": "pyros-john",
    "PYTTLIK Olaf": "pyttlik-olaf"
  }
};