export default {
  "metadata": {
    "results": 98,
    "timeStamp": "2025-12-05T21:30:05.302Z",
    "url": "https://www.doollee.com/PlaywrightsQ/3PlaywrightsQdata.php"
  },
  "authors": {
    "Q ": "q",
    "Q Kimberley": "q-kimberley",
    "Q William George": "q-william-george",
    "Q BROTHERS ": "q-brothers",
    "QAIYUM Gregory J": "qaiyum-gregory-j",
    "QAIYUM Jeffrey": "qaiyum-jeffrey",
    "QUACKENBUSH Jan": "quackenbush-jan",
    "QUADE Vicki": "quade-vicki",
    "QUAID Amanda": "quaid-amanda",
    "QUAID Jack": "quaid-jack",
    "QUALE Drew": "quale-drew",
    "QUALLES Paris H": "qualles-paris-h",
    "QUALTER Elaine Yuko": "qualter-elaine-yuko",
    "QUAN Betty": "quan-betty",
    "QUAN Elyne": "quan-elyne",
    "QUANG Nu": "quang-nu",
    "QUANSAH Eddie": "quansah-eddie",
    "QUANTRILL Malcolm": "quantrill-malcolm",
    "QUAPPE Barrie": "quappe-barrie",
    "QUAPPE Chuck": "quappe-chuck",
    "QUARAISHI Ibrahim": "quaraishi-ibrahim",
    "QUARANTINE ": "quarantine",
    "QUARE HAWKS ": "quare-hawks",
    "QUARREL Johnnie": "quarrel-johnnie",
    "QUARRINGTON Paul": "quarrington-paul",
    "QUARTLEY Mark": "quartley-mark",
    "QUASH Toby": "quash-toby",
    "QUATRO Suzi": "quatro-suzi",
    "QUATRONE Rich": "quatrone-rich",
    "QUEBLEEN Rodolfo C": "quebleen-rodolfo-c",
    "QUEER SOUP COLLECTIVE ": "queer-soup-collective",
    "QUEER TEEN ENSEMBLE THEATER ": "queer-teen-ensemble-theater",
    "QUENELLE Nicole": "quenelle-nicole",
    "QUENTIN John": "quentin-john",
    "QUENTIN Pol": "quentin-pol",
    "QUESNE Philippe": "quesne-philippe",
    "QUICK Andrew": "quick-andrew",
    "QUICK Richard": "quick-richard",
    "QUICK Sarah": "quick-sarah",
    "QUICONQUE ": "quiconque",
    "QUIET WORD ": "quiet-word",
    "QUIGAN Alison": "quigan-alison",
    "QUIGLEY Bill": "quigley-bill",
    "QUIGLEY Gabriel": "quigley-gabriel",
    "QUIGLEY Patrick": "quigley-patrick",
    "QUIGLEY Peter": "quigley-peter",
    "QUIHUIS Adrian": "quihuis-adrian",
    "QUILL Erin": "quill-erin",
    "QUILL Sian": "quill-sian",
    "QUILL ": "quill",
    "QUILTER Peter": "quilter-peter",
    "QUIN Betty": "quin-betty",
    "QUIN Emrys": "quin-emrys",
    "QUIN James": "quin-james",
    "QUIN John Christian": "quin-john-christian",
    "QUINAN John": "quinan-john",
    "QUINLAN Jack": "quinlan-jack",
    "QUINN Bob": "quinn-bob",
    "QUINN Brian": "quinn-brian",
    "QUINN Colin": "quinn-colin",
    "QUINN Conall": "quinn-conall",
    "QUINN Cormac": "quinn-cormac",
    "QUINN Denise": "quinn-denise",
    "QUINN Dylan": "quinn-dylan",
    "QUINN Emrys": "quinn-emrys",
    "QUINN Gavin": "quinn-gavin",
    "QUINN James": "quinn-james",
    "QUINN Karl": "quinn-karl",
    "QUINN Katherine": "quinn-katherine",
    "QUINN Kelly": "quinn-kelly",
    "QUINN Laura": "quinn-laura",
    "QUINN Louise": "quinn-louise",
    "QUINN Mhairi": "quinn-mhairi",
    "QUINN Michael": "quinn-michael",
    "QUINN Niall": "quinn-niall",
    "QUINN Nicole": "quinn-nicole",
    "QUINN Pauline": "quinn-pauline",
    "QUINN Sarah": "quinn-sarah",
    "QUINN Terry": "quinn-terry",
    "QUINN Thomas Michael": "quinn-thomas-michael",
    "QUINN Yvonne": "quinn-yvonne",
    "QUINN JR Seabury": "quinn-jr-seabury",
    "QUINNOPOLIS ": "quinnopolis",
    "QUINONES Jesse": "quinones-jesse",
    "QUINONES Michael": "quinones-michael",
    "QUINT Peter": "quint-peter",
    "QUINTERO Hector": "quintero-hector",
    "QUINTERO Jesus": "quintero-jesus",
    "QUINTERO Joaquin Alvarez": "quintero-joaquin-alvarez",
    "QUINTERO Wayland": "quintero-wayland",
    "QUINTON Everett": "quinton-everett",
    "QUINTON Perry": "quinton-perry",
    "QUINTYNE Maxine": "quintyne-maxine",
    "QUIRK Brian": "quirk-brian",
    "QUIRKE Kieron": "quirke-kieron",
    "QUIRT Brian": "quirt-brian",
    "QUITE SENSIBLE ": "quite-sensible",
    "QUONIAM Bertrand": "quoniam-bertrand"
  }
};