export default {
  "metadata": {
    "results": 1042,
    "timeStamp": "2025-12-05T21:30:18.314Z",
    "url": "https://www.doollee.com/PlaywrightsR/R_playwrights_a-f.php"
  },
  "authors": {
    "RA Dada": "ra-dada",
    "RAAN Sigmund Van": "raan-sigmund-van",
    "RAASCH Rick": "raasch-rick",
    "RAATH A J": "raath-a-j",
    "RAATUS Cleo": "raatus-cleo",
    "RABBIT HOLE ENSEMBLE ": "rabbit-hole-ensemble",
    "RABE Anne": "rabe-anne",
    "RABE David": "rabe-david",
    "RABE Michael": "rabe-michael",
    "RABEL Caitlin": "rabel-caitlin",
    "RABEY David Ian": "rabey-david-ian",
    "RABEY Peter": "rabey-peter",
    "RABIN Adam": "rabin-adam",
    "RABIN Arnold": "rabin-arnold",
    "RABIN Kenn": "rabin-kenn",
    "RABIN Stephen": "rabin-stephen",
    "RABIN Susan": "rabin-susan",
    "RABINOW David": "rabinow-david",
    "RABINOWITZ Anna": "rabinowitz-anna",
    "RABINOWITZ Robert": "rabinowitz-robert",
    "RABINOWITZ Stephanie": "rabinowitz-stephanie",
    "RABORG JR Frederick A": "raborg-jr-frederick-a",
    "RABUNSKI Jonathan": "rabunski-jonathan",
    "RABUSHKA Jerrold": "rabushka-jerrold",
    "RABY D": "raby-d",
    "RABY Gyllian": "raby-gyllian",
    "RABY Henry": "raby-henry",
    "RABY Peter": "raby-peter",
    "RACE Holly": "race-holly",
    "RACELIS Felix": "racelis-felix",
    "RACHEFF James": "racheff-james",
    "RACHELLE Valerie": "rachelle-valerie",
    "RACHELSON-OSPA June": "rachelson-ospa-june",
    "RACHETT James": "rachett-james",
    "RACHUBA Remi": "rachuba-remi",
    "RACICOT Aaron": "racicot-aaron",
    "RACINE Bob": "racine-bob",
    "RACINE Darrell": "racine-darrell",
    "RACINE Jean": "racine-jean",
    "RACINE Ned": "racine-ned",
    "RACINE Tim": "racine-tim",
    "RACK Jeff G": "rack-jeff-g",
    "RACKAL Yasmin": "rackal-yasmin",
    "RACKHAM Ray": "rackham-ray",
    "RACKLEFF Owen S": "rackleff-owen-s",
    "RACZ Gregary J": "racz-gregary-j",
    "RACZKA Lulu": "raczka-lulu",
    "RADAKOVICH Daniel": "radakovich-daniel",
    "RADANO Lisa-Maria": "radano-lisa-maria",
    "RADATTI Mick": "radatti-mick",
    "RADAVICH David": "radavich-david",
    "RADAY Leanne": "raday-leanne",
    "RADBURN Trudy": "radburn-trudy",
    "RADCLIFF Jan": "radcliff-jan",
    "RADCLIFFE Grafton": "radcliffe-grafton",
    "RADCLIFFE Megan": "radcliffe-megan",
    "RADCLIFFE Virginia": "radcliffe-virginia",
    "RADCLYFFE Mimosa Valentina": "radclyffe-mimosa-valentina",
    "RADDOCK Charles": "raddock-charles",
    "RADEIS ": "radeis",
    "RADEMACHER G": "rademacher-g",
    "RADEMEYER Philip": "rademeyer-philip",
    "RADEVA Katherina": "radeva-katherina",
    "RADFORD Will": "radford-will",
    "RADI Michael": "radi-michael",
    "RADIC Leonard": "radic-leonard",
    "RADIC Therese": "radic-therese",
    "RADICE Betty": "radice-betty",
    "RADICE Neal": "radice-neal",
    "RADICE Ron": "radice-ron",
    "RADICE William": "radice-william",
    "RADICHKOV Yordan": "radichkov-yordan",
    "RADIOHOLE ": "radiohole",
    "RADISON Nelson": "radison-nelson",
    "RADIVOJEVIC Ratko": "radivojevic-ratko",
    "RADLEY Lynda": "radley-lynda",
    "RADLOFF Fred": "radloff-fred",
    "RADMALL Andre": "radmall-andre",
    "RADNAI Annamaria": "radnai-annamaria",
    "RADO James": "rado-james",
    "RADO Ted": "rado-ted",
    "RADOEV Ivan": "radoev-ivan",
    "RADOJICIC Katharine Rose Williams": "radojicic-katharine-rose-williams",
    "RADOSAVLJEVIC Duska": "radosavljevic-duska",
    "RADRIGAN Juan": "radrigan-juan",
    "RADSTROM Niklas": "radstrom-niklas",
    "RADTKE Bryan": "radtke-bryan",
    "RADY Brian": "rady-brian",
    "RADZINSKY Edvard": "radzinsky-edvard",
    "RAE Douglas": "rae-douglas",
    "RAE Julie": "rae-julie",
    "RAE Nola": "rae-nola",
    "RAE Robert": "rae-robert",
    "RAE Roisin": "rae-roisin",
    "RAE Ronald V": "rae-ronald-v",
    "RAE Sheilah": "rae-sheilah",
    "RAE Simon": "rae-simon",
    "RAEL Chris": "rael-chris",
    "RAEL Eisa Okun": "rael-eisa-okun",
    "RAEL Elsa": "rael-elsa",
    "RAETHER Margaret": "raether-margaret",
    "RAFAL Jeremy": "rafal-jeremy",
    "RAFAL Nathalie": "rafal-nathalie",
    "RAFALOWICZ Mira": "rafalowicz-mira",
    "RAFE Harriet": "rafe-harriet",
    "RAFE Jane": "rafe-jane",
    "RAFELLO Nick": "rafello-nick",
    "RAFELSON Peter": "rafelson-peter",
    "RAFFALOVICH Marc-Andre": "raffalovich-marc-andre",
    "RAFFANTI Susan": "raffanti-susan",
    "RAFFARD Tlell": "raffard-tlell",
    "RAFFERT Sean": "raffert-sean",
    "RAFFERTY Lisa": "rafferty-lisa",
    "RAFFERTY Lynn": "rafferty-lynn",
    "RAFFERTY Michael": "rafferty-michael",
    "RAFFERTY Tess": "rafferty-tess",
    "RAFFLE Diana": "raffle-diana",
    "RAFFO Heather": "raffo-heather",
    "RAFFO Peter": "raffo-peter",
    "RAFN E M": "rafn-e-m",
    "RAFTERTY Claire": "rafterty-claire",
    "RAGAN James E": "ragan-james-e",
    "RAGEN Naomi": "ragen-naomi",
    "RAGIR John": "ragir-john",
    "RAGLIN Rod": "raglin-rod",
    "RAGNI Gerome": "ragni-gerome",
    "RAGOOBARSINGH Richard": "ragoobarsingh-richard",
    "RAGOSIN Lydia": "ragosin-lydia",
    "RAGSDALE Richard": "ragsdale-richard",
    "RAGSDALE Stella Fawn": "ragsdale-stella-fawn",
    "RAH RAH THEATRE COMPANY ": "rah-rah-theatre-company",
    "RAHDER Karl": "rahder-karl",
    "RAHMAN Aishah": "rahman-aishah",
    "RAHMAN AR": "rahman-ar",
    "RAHMAN Obara Wali": "rahman-obara-wali",
    "RAHMANIAN Mohammad": "rahmanian-mohammad",
    "RAHNEV Elin": "rahnev-elin",
    "RAHN-LEE Charlotte": "rahn-lee-charlotte",
    "RAIA Chris": "raia-chris",
    "RAIA Courtenay": "raia-courtenay",
    "RAIF Ayshe": "raif-ayshe",
    "RAILSBACK Lisa": "railsback-lisa",
    "RAILTON Bernard": "railton-bernard",
    "RAILTON Lucy": "railton-lucy",
    "RAIMONDO Brad": "raimondo-brad",
    "RAIMUND Ferdinand": "raimund-ferdinand",
    "RAINE Brian": "raine-brian",
    "RAINE Craig": "raine-craig",
    "RAINE David S": "raine-david-s",
    "RAINE Moses": "raine-moses",
    "RAINE Nina": "raine-nina",
    "RAINER Dachine": "rainer-dachine",
    "RAINER Elizabeth": "rainer-elizabeth",
    "RAINER John": "rainer-john",
    "RAINER Marta": "rainer-marta",
    "RAINER Yvonne": "rainer-yvonne",
    "RAINES Pam": "raines-pam",
    "RAINEY Jessica": "rainey-jessica",
    "RAINEY Michael": "rainey-michael",
    "RAINNER Carrie B": "rainner-carrie-b",
    "RAINTREE Elizabeth": "raintree-elizabeth",
    "RAINTREE Russell": "raintree-russell",
    "RAIO Nick": "raio-nick",
    "RAIOLA Joe": "raiola-joe",
    "RAISIN Jonathan": "raisin-jonathan",
    "RAISNER Craig": "raisner-craig",
    "RAISON Jeremy": "raison-jeremy",
    "RAITH Mike": "raith-mike",
    "RAITHATHA Manoj": "raithatha-manoj",
    "RAITHEL Clayton": "raithel-clayton",
    "RAITZIN Dimitri": "raitzin-dimitri",
    "RAIZADA Sharon": "raizada-sharon",
    "RAIZIS M Byron": "raizis-m-byron",
    "RAJA Christopher": "raja-christopher",
    "RAJA Gautam": "raja-gautam",
    "RAJA Natasha": "raja-natasha",
    "RAJAN Andrew": "rajan-andrew",
    "RAJAN Jacob": "rajan-jacob",
    "RAJAN Vidya": "rajan-vidya",
    "RAJECKAS Paul": "rajeckas-paul",
    "RAJENDRAN Mathivanan": "rajendran-mathivanan",
    "RAJKUMAR Breman": "rajkumar-breman",
    "RAKER Cecelia": "raker-cecelia",
    "RAKER Scott": "raker-scott",
    "RAKOFF Alvin": "rakoff-alvin",
    "RAKOFF John D": "rakoff-john-d",
    "RAKOWITZ-HELFIELD Elly": "rakowitz-helfield-elly",
    "RAKOZ Kyall": "rakoz-kyall",
    "RAKSHIN N N": "rakshin-n-n",
    "RAKURAKU Maraea": "rakuraku-maraea",
    "RALEIGH Amanda": "raleigh-amanda",
    "RALEY John": "raley-john",
    "RALF David": "ralf-david",
    "RALF, RALF ": "ralf-ralf",
    "RALFE David": "ralfe-david",
    "RALLI George": "ralli-george",
    "RALLI Oliver": "ralli-oliver",
    "RALLI Susanna": "ralli-susanna",
    "RALPH Dennis": "ralph-dennis",
    "RALPH Gordon": "ralph-gordon",
    "RALPH Philip": "ralph-philip",
    "RALPH Syd": "ralph-syd",
    "RALPHS Tim": "ralphs-tim",
    "RALSTON Darren": "ralston-darren",
    "RAMABULANA Nat": "ramabulana-nat",
    "RAMACH Michael": "ramach-michael",
    "RAMAKRISHNAN S Karthick": "ramakrishnan-s-karthick",
    "RAMBERT Pascal": "rambert-pascal",
    "RAMBO David": "rambo-david",
    "RAMCHURN Punam": "ramchurn-punam",
    "RAME Franca": "rame-franca",
    "RAMEAU Ingez": "rameau-ingez",
    "RAMER Jack": "ramer-jack",
    "RAMIREZ Alfonso": "ramirez-alfonso",
    "RAMIREZ Bruno": "ramirez-bruno",
    "RAMIREZ Diana Chery": "ramirez-diana-chery",
    "RAMIREZ Jason": "ramirez-jason",
    "RAMIREZ Lidia": "ramirez-lidia",
    "RAMIREZ Lisa": "ramirez-lisa",
    "RAMIREZ Marco": "ramirez-marco",
    "RAMIREZ Maria-Corina": "ramirez-maria-corina",
    "RAMIREZ Michael": "ramirez-michael",
    "RAMIREZ Ramiro": "ramirez-ramiro",
    "RAMIREZ Vickie": "ramirez-vickie",
    "RAMJERDI Jan": "ramjerdi-jan",
    "RAMM Jessica": "ramm-jessica",
    "RAMM John": "ramm-john",
    "RAMMAGE Matthew": "rammage-matthew",
    "RAMMELKAMP Claire": "rammelkamp-claire",
    "RAMNARAYAN Gowri": "ramnarayan-gowri",
    "RAMO Marie-Paule": "ramo-marie-paule",
    "RAMOLETE Ed": "ramolete-ed",
    "RAMONI Michelle": "ramoni-michelle",
    "RAMOS Angel": "ramos-angel",
    "RAMOS Antonio": "ramos-antonio",
    "RAMOS Brandon": "ramos-brandon",
    "RAMOS Dania": "ramos-dania",
    "RAMOS Gregory": "ramos-gregory",
    "RAMOS Jorge Lopes": "ramos-jorge-lopes",
    "RAMOS Mollie": "ramos-mollie",
    "RAMOS Teri": "ramos-teri",
    "RAMOS-PEREA Roberto": "ramos-perea-roberto",
    "RAMPAL Jacques": "rampal-jacques",
    "RAMPAL Rochi": "rampal-rochi",
    "RAMPILLA Narayana Rao": "rampilla-narayana-rao",
    "RAMSAY Erik": "ramsay-erik",
    "RAMSAY G P": "ramsay-g-p",
    "RAMSAY Gilbert": "ramsay-gilbert",
    "RAMSAY Matthew": "ramsay-matthew",
    "RAMSAY Robin": "ramsay-robin",
    "RAMSAY Roy": "ramsay-roy",
    "RAMSAY T J": "ramsay-t-j",
    "RAMSAY Tony": "ramsay-tony",
    "RAMSAY William": "ramsay-william",
    "RAMSAY-DETHERAGE Linda": "ramsay-detherage-linda",
    "RAMSBURG Kat": "ramsburg-kat",
    "RAMSDELL Heather": "ramsdell-heather",
    "RAMSDEN Gayanne": "ramsden-gayanne",
    "RAMSDEN Lou": "ramsden-lou",
    "RAMSEL Adey": "ramsel-adey",
    "RAMSEY Calvin Alexander": "ramsey-calvin-alexander",
    "RAMSEY Doreen": "ramsey-doreen",
    "RAMSEY Erik": "ramsey-erik",
    "RAMSEY Helen": "ramsey-helen",
    "RAMSEY Lois": "ramsey-lois",
    "RAMSEY Matt": "ramsey-matt",
    "RAMSEY Nina Joshi": "ramsey-nina-joshi",
    "RAMSEY Patricia": "ramsey-patricia",
    "RAMSEY Peter": "ramsey-peter",
    "RAMSEY Regina Eliot": "ramsey-regina-eliot",
    "RAMSEY T J": "ramsey-t-j",
    "RAMUZ C F": "ramuz-c-f",
    "RANA James": "rana-james",
    "RANA Yasmine Beverly": "rana-yasmine-beverly",
    "RANBERG Chuck": "ranberg-chuck",
    "RANCE-REARDON Pearl": "rance-reardon-pearl",
    "RANCHOD Jett": "ranchod-jett",
    "RAND Ayn": "rand-ayn",
    "RAND David": "rand-david",
    "RAND Doug": "rand-doug",
    "RAND Jimi": "rand-jimi",
    "RAND Jonathan": "rand-jonathan",
    "RAND Julia Sandra": "rand-julia-sandra",
    "RAND Linda L": "rand-linda-l",
    "RAND Lisa": "rand-lisa",
    "RAND Richard Stockton": "rand-richard-stockton",
    "RAND Ronald": "rand-ronald",
    "RANDALL Addison": "randall-addison",
    "RANDALL Bob": "randall-bob",
    "RANDALL Christine": "randall-christine",
    "RANDALL Emily": "randall-emily",
    "RANDALL John": "randall-john",
    "RANDALL Joshua": "randall-joshua",
    "RANDALL Paul": "randall-paul",
    "RANDALL Paulette": "randall-paulette",
    "RANDEL Melissa R": "randel-melissa-r",
    "RANDERSON Jo": "randerson-jo",
    "RANDHAWA Jon": "randhawa-jon",
    "RANDICH Jean": "randich-jean",
    "RANDLE Katherine": "randle-katherine",
    "RANDLE Marjorie": "randle-marjorie",
    "RANDLES Kerri": "randles-kerri",
    "RANDOJA Karin": "randoja-karin",
    "RANDOLPH Aaron": "randolph-aaron",
    "RANDOLPH Ann": "randolph-ann",
    "RANDOLPH Clemence": "randolph-clemence",
    "RANDOLPH Grace": "randolph-grace",
    "RANDOLPH Jeremy": "randolph-jeremy",
    "RANDOLPH Larry": "randolph-larry",
    "RANDOLPH-WRIGHT Charles": "randolph-wright-charles",
    "RANDOM John": "random-john",
    "RANDOM ACCOMPLICE ": "random-accomplice",
    "RANDOY Stephen Thomas": "randoy-stephen-thomas",
    "RANDS Imogen": "rands-imogen",
    "RANELLI J": "ranelli-j",
    "RANGER Jeanette": "ranger-jeanette",
    "RANIELLO John": "raniello-john",
    "RANK Ellen": "rank-ellen",
    "RANK Hugh": "rank-hugh",
    "RANKEN Frederic": "ranken-frederic",
    "RANKIN Ben": "rankin-ben",
    "RANKIN Dillan": "rankin-dillan",
    "RANKIN Ian": "rankin-ian",
    "RANKIN James": "rankin-james",
    "RANKIN Jennifer": "rankin-jennifer",
    "RANKIN John Anderson": "rankin-john-anderson",
    "RANKIN Kenny": "rankin-kenny",
    "RANKIN Paul": "rankin-paul",
    "RANKIN Renee": "rankin-renee",
    "RANKIN Rick": "rankin-rick",
    "RANKIN Scott": "rankin-scott",
    "RANKINE Claudia": "rankine-claudia",
    "RANKINE David": "rankine-david",
    "RANKOWITZ-HELFELD Elly": "rankowitz-helfeld-elly",
    "RANKUS Susan": "rankus-susan",
    "RANNEY ": "ranney",
    "RANSCOMBE Pauline": "ranscombe-pauline",
    "RANSEY Calvin Alexander": "ransey-calvin-alexander",
    "RANSLEY Peter": "ransley-peter",
    "RANSOM Erik": "ransom-erik",
    "RANSOM Scott": "ransom-scott",
    "RANSOME Erik": "ransome-erik",
    "RANSOME Niall": "ransome-niall",
    "RANSON Rebecca": "ranson-rebecca",
    "RANSONE Preston M": "ransone-preston-m",
    "RANTERS THEATRE ": "ranters-theatre",
    "RAPER Kate": "raper-kate",
    "RAPHAEL Christopher": "raphael-christopher",
    "RAPHAEL Frederic": "raphael-frederic",
    "RAPHAEL Lennox": "raphael-lennox",
    "RAPHAEL Stephen": "raphael-stephen",
    "RAPHAELSON Mark": "raphaelson-mark",
    "RAPHAELSON Samson": "raphaelson-samson",
    "RAPI Nina": "rapi-nina",
    "RAPIER Darren": "rapier-darren",
    "RAPLEY Chris": "rapley-chris",
    "RAPLEY Edward": "rapley-edward",
    "RAPLEY Tommy": "rapley-tommy",
    "RAPOPORT Janis": "rapoport-janis",
    "RAPOSO Jacqueline": "raposo-jacqueline",
    "RAPOSO Joe": "raposo-joe",
    "RAPP Adam": "rapp-adam",
    "RAPP Anthony": "rapp-anthony",
    "RAPP Carol M": "rapp-carol-m",
    "RAPPA Giampiero": "rappa-giampiero",
    "RAPPAPORT Helen": "rappaport-helen",
    "RAPPOPORT David Steven": "rappoport-david-steven",
    "RAPPOPORT Janis": "rappoport-janis",
    "RA-RA ZOO ": "ra-ra-zoo",
    "RAREY Eli": "rarey-eli",
    "RASBERRY Michael": "rasberry-michael",
    "RASCHEFF James": "rascheff-james",
    "RASEM Mokhallad": "rasem-mokhallad",
    "RASEWSKI Monica": "rasewski-monica",
    "RASHDASH ": "rashdash",
    "RASHED Nimer": "rashed-nimer",
    "RASHEED James": "rasheed-james",
    "RASHID Sabura": "rashid-sabura",
    "RASHID Sophia": "rashid-sophia",
    "RASHIDI-ZAKUANI Serge": "rashidi-zakuani-serge",
    "RASHIP Carolyn": "raship-carolyn",
    "RASHLEIGH Andy": "rashleigh-andy",
    "RASINI Ollie": "rasini-ollie",
    "RASMUSSEN Piper Ellen": "rasmussen-piper-ellen",
    "RASMUSSEN Sarah": "rasmussen-sarah",
    "RASOOLY Yael": "rasooly-yael",
    "RASPANTI Celeste": "raspanti-celeste",
    "RASPOSO ": "rasposo",
    "RASSIOS Stefanos": "rassios-stefanos",
    "RASZEWSKI Monica": "raszewski-monica",
    "RATCLIFF Nora": "ratcliff-nora",
    "RATCLIFFE Alex": "ratcliffe-alex",
    "RATCLIFFE Bill": "ratcliffe-bill",
    "RATCLIFFE Lydia": "ratcliffe-lydia",
    "RATHBONE Christopher": "rathbone-christopher",
    "RATHBONE Isaac": "rathbone-isaac",
    "RATHBONE Robin": "rathbone-robin",
    "RATHIE S": "rathie-s",
    "RATHJE Helen": "rathje-helen",
    "RATHJE Steve": "rathje-steve",
    "RATHKOPF Linda Holland": "rathkopf-linda-holland",
    "RATNER Bill": "ratner-bill",
    "RATNER Ellen": "ratner-ellen",
    "RATNER Payne": "ratner-payne",
    "RATNER Scott K": "ratner-scott-k",
    "RATRAY Peter": "ratray-peter",
    "RATTENBURY Andrew": "rattenbury-andrew",
    "RATTIGAN Terence": "rattigan-terence",
    "RATTNER Bonnie Lee Moss": "rattner-bonnie-lee-moss",
    "RATTNER George": "rattner-george",
    "RATTNER Gregory": "rattner-gregory",
    "RATTRAY B": "rattray-b",
    "RATTRAY Chris": "rattray-chris",
    "RATY Mikko": "raty-mikko",
    "RAU Jennifer": "rau-jennifer",
    "RAU Michael": "rau-michael",
    "RAU Milo": "rau-milo",
    "RAU Rama Santha": "rau-rama-santha",
    "RAUCH Ben": "rauch-ben",
    "RAUCH Bill": "rauch-bill",
    "RAUCH Dhira": "rauch-dhira",
    "RAUCH Melissa": "rauch-melissa",
    "RAUCH Winston": "rauch-winston",
    "RAUCHER Herman": "raucher-herman",
    "RAUH Nicola": "rauh-nicola",
    "RAULO Hanna": "raulo-hanna",
    "RAUSCH Sidra": "rausch-sidra",
    "RAVEL Aviva": "ravel-aviva",
    "RAVELOMANANTSOA Glen Anthony": "ravelomanantsoa-glen-anthony",
    "RAVEN David": "raven-david",
    "RAVEN Rosie": "raven-rosie",
    "RAVEN Simon": "raven-simon",
    "RAVENAL Cornelia": "ravenal-cornelia",
    "RAVENHILL Mark": "ravenhill-mark",
    "RAVENNA Joni": "ravenna-joni",
    "RAVENSCROFT Edward": "ravenscroft-edward",
    "RAVENSDALE Pamela": "ravensdale-pamela",
    "RAVETCH Irving": "ravetch-irving",
    "RAVICCHIO Giacomo": "ravicchio-giacomo",
    "RAVING BEAUTIES, THE ": "raving-beauties",
    "RAVITS Richard": "ravits-richard",
    "RAVITTS Ricki G": "ravitts-ricki-g",
    "RAVOLD John D": "ravold-john-d",
    "RAWCLIFFE Rebecca": "rawcliffe-rebecca",
    "RAWITZ Naomi": "rawitz-naomi",
    "RAWLENCE Chris": "rawlence-chris",
    "RAWLEY Michael": "rawley-michael",
    "RAWLEY Wayne S": "rawley-wayne-s",
    "RAWLINGS Herbert": "rawlings-herbert",
    "RAWLINGS Margaret": "rawlings-margaret",
    "RAWLINGS Paul": "rawlings-paul",
    "RAWLS Eugenia": "rawls-eugenia",
    "RAWLS James": "rawls-james",
    "RAWNSLEY Keith": "rawnsley-keith",
    "RAWSON David": "rawson-david",
    "RAWSON Graham": "rawson-graham",
    "RAWSON Janet": "rawson-janet",
    "RAWSTHORNE Stephen": "rawsthorne-stephen",
    "RAY Brenda": "ray-brenda",
    "RAY Connie": "ray-connie",
    "RAY Danny": "ray-danny",
    "RAY David L": "ray-david-l",
    "RAY Gary": "ray-gary",
    "RAY Harper": "ray-harper",
    "RAY Kevin": "ray-kevin",
    "RAY Rebecca L": "ray-rebecca-l",
    "RAY Robin": "ray-robin",
    "RAY Roxanne": "ray-roxanne",
    "RAYBURN Joyce": "rayburn-joyce",
    "RAYFIEL David": "rayfiel-david",
    "RAYFIELD Donald": "rayfield-donald",
    "RAYFIELD Gordon": "rayfield-gordon",
    "RAYFIELD James": "rayfield-james",
    "RAYHER Phillip B": "rayher-phillip-b",
    "RAYMAN Sylvia": "rayman-sylvia",
    "RAYMENT Colette": "rayment-colette",
    "RAYMENT Mark": "rayment-mark",
    "RAYMOND Ann": "raymond-ann",
    "RAYMOND Antony": "raymond-antony",
    "RAYMOND Darren": "raymond-darren",
    "RAYMOND Frank": "raymond-frank",
    "RAYMOND Gordon": "raymond-gordon",
    "RAYMOND Jack": "raymond-jack",
    "RAYMOND Jay": "raymond-jay",
    "RAYMOND Katrine": "raymond-katrine",
    "RAYMOND Monica": "raymond-monica",
    "RAYMONT C E": "raymont-c-e",
    "RAYNA Justin Nicholas": "rayna-justin-nicholas",
    "RAYNE Michael": "rayne-michael",
    "RAYNER Daniel": "rayner-daniel",
    "RAYNER Elizabeth": "rayner-elizabeth",
    "RAYNER Julia": "rayner-julia",
    "RAYNER Lauren": "rayner-lauren",
    "RAYNER Max": "rayner-max",
    "RAYNER Stephen N": "rayner-stephen-n",
    "RAYNOR Allison": "raynor-allison",
    "RAYNOR Dave": "raynor-dave",
    "RAYNOR Helen": "raynor-helen",
    "RAYNOR Michael": "raynor-michael",
    "RAYNOR Molly": "raynor-molly",
    "RAYNOR Ruby Lynn": "raynor-ruby-lynn",
    "RAYNOR Ruth": "raynor-ruth",
    "RAYSON Beverley": "rayson-beverley",
    "RAYSON Hannie": "rayson-hannie",
    "RAYWORTH Melissa": "rayworth-melissa",
    "RAZ Jeff": "raz-jeff",
    "RAZA Salima": "raza-salima",
    "RAZAQ Rashid": "razaq-rashid",
    "RAZAVI William Mohammad": "razavi-william-mohammad",
    "RAZIA Ambreen": "razia-ambreen",
    "RAZUMOVSKAYA Ludmilla": "razumovskaya-ludmilla",
    "RAZZAQUE Rafika": "razzaque-rafika",
    "RBDC ": "rbdc",
    "REA Brian": "rea-brian",
    "REA Deborah": "rea-deborah",
    "REA Ian": "rea-ian",
    "REA Kenneth": "rea-kenneth",
    "REA Raymond": "rea-raymond",
    "REA-BRISKIN Christine": "rea-briskin-christine",
    "REACH James": "reach-james",
    "READ David": "read-david",
    "READ David West": "read-david-west",
    "READ Dylan": "read-dylan",
    "READ Herbert": "read-herbert",
    "READ Joanna": "read-joanna",
    "READ Jolly": "read-jolly",
    "READ Katie": "read-katie",
    "READ Martyn": "read-martyn",
    "READ Michael-Alan": "read-michael-alan",
    "READ Michelle": "read-michelle",
    "READ Mike": "read-mike",
    "READ Nick": "read-nick",
    "READ Peter": "read-peter",
    "READ Tom": "read-tom",
    "READE Alan": "reade-alan",
    "READE Charles": "reade-charles",
    "READE Harry": "reade-harry",
    "READE Orlando": "reade-orlando",
    "READE Simon": "reade-simon",
    "READE Yasmin": "reade-yasmin",
    "READER Nicholas": "reader-nicholas",
    "READING Anna": "reading-anna",
    "READING Bertice": "reading-bertice",
    "READMAN Andrew": "readman-andrew",
    "READY Stuart": "ready-stuart",
    "REAGON Bernice": "reagon-bernice",
    "REAKES Paul": "reakes-paul",
    "REAL Carole": "real-carole",
    "REAL Philip": "real-philip",
    "REALE Carole": "reale-carole",
    "REALE Robert": "reale-robert",
    "REALE Willie": "reale-willie",
    "REALI Stefano": "reali-stefano",
    "REALTY Hirise": "realty-hirise",
    "REAME-JAMES Milton": "reame-james-milton",
    "REANEY James": "reaney-james",
    "REARDON Daniel": "reardon-daniel",
    "REARDON Dennis J": "reardon-dennis-j",
    "REARDON Edward H": "reardon-edward-h",
    "REARDON Frank": "reardon-frank",
    "REARDON Tyler James": "reardon-tyler-james",
    "REASE Claudene": "rease-claudene",
    "REASON Christopher": "reason-christopher",
    "REASON John": "reason-john",
    "REAVEY G": "reavey-g",
    "REAVY James": "reavy-james",
    "REAVY Jean": "reavy-jean",
    "REAY Emma": "reay-emma",
    "REAY Ken": "reay-ken",
    "REBAIR Chianna": "rebair-chianna",
    "REBAR Kelly": "rebar-kelly",
    "REBECK Theresa": "rebeck-theresa",
    "REBELL Joshua": "rebell-joshua",
    "REBELL Sarah Anne": "rebell-sarah-anne",
    "REBELLATO Dan": "rebellato-dan",
    "REBHUN Paul": "rebhun-paul",
    "REBUSIT Nancy": "rebusit-nancy",
    "REBWAR ": "rebwar",
    "RECHY John": "rechy-john",
    "RECINOS Andrew": "recinos-andrew",
    "RECK Caroline": "reck-caroline",
    "RECK Tony": "reck-tony",
    "RECKFORD Kenneth J": "reckford-kenneth-j",
    "RECKLESS SLEEPERS ": "reckless-sleepers",
    "RECKORD Barry": "reckord-barry",
    "RECORDEDDELIVERY ": "recordeddelivery",
    "RECTOR Mark": "rector-mark",
    "RECUERDA Jose Martin": "recuerda-jose-martin",
    "RED BOBBLE THEATRE COMPANY ": "red-bobble-theatre-company",
    "RED CAPE THEATRE ": "red-cape-theatre",
    "RED EARTH THEATRE ": "red-earth-theatre",
    "RED LADDER THEATRE, THE ": "red-ladder-theatre",
    "RED LEAP ": "red-leap",
    "RED RAG ": "red-rag",
    "RED TERROR SQUAD ": "red-terror-squad",
    "REDA Lou": "reda-lou",
    "REDAVID Brigette": "redavid-brigette",
    "REDBRIDGE ADULT THEATRE WORKSHOP ": "redbridge-adult-theatre-workshop",
    "REDBRIDGE YOUNG THEATRE WORKSHOP ": "redbridge-young-theatre-workshop",
    "REDD Chris": "redd-chris",
    "REDD Randy": "redd-randy",
    "REDD Robert O": "redd-robert-o",
    "REDDAWAY Clare": "reddaway-clare",
    "REDDICK John": "reddick-john",
    "REDDIN Keith": "reddin-keith",
    "REDDING Edward C": "redding-edward-c",
    "REDDY Geetha": "reddy-geetha",
    "REDDY Leeanda": "reddy-leeanda",
    "REDDY Shawn": "reddy-shawn",
    "REDER Peter": "reder-peter",
    "REDER Philip": "reder-philip",
    "REDFERN Tim": "redfern-tim",
    "REDFERN Walter": "redfern-walter",
    "REDFIELD Mark": "redfield-mark",
    "REDFORD Ian": "redford-ian",
    "REDFORD Katie": "redford-katie",
    "REDGRAVE Corin": "redgrave-corin",
    "REDGRAVE Lynn": "redgrave-lynn",
    "REDGRAVE Michael": "redgrave-michael",
    "REDGRAVE Vanessa": "redgrave-vanessa",
    "REDGROVE Peter": "redgrove-peter",
    "REDHEAD Chazz": "redhead-chazz",
    "REDHEAD Natashha": "redhead-natashha",
    "REDHILL Michael": "redhill-michael",
    "REDICK Charlene": "redick-charlene",
    "REDINGTON Ginny": "redington-ginny",
    "REDISH Jessica": "redish-jessica",
    "REDLICH Nicki": "redlich-nicki",
    "REDLING Jennie S": "redling-jennie-s",
    "REDMAN Briony": "redman-briony",
    "REDMAN Effy": "redman-effy",
    "REDMAN Michael": "redman-michael",
    "REDMAN Nancy": "redman-nancy",
    "REDMAN Richard": "redman-richard",
    "REDMAN Stephen": "redman-stephen",
    "REDMAYNE C M": "redmayne-c-m",
    "REDMOND Barbara": "redmond-barbara",
    "REDMOND Diane": "redmond-diane",
    "REDMOND Eugene B": "redmond-eugene-b",
    "REDMOND Gary": "redmond-gary",
    "REDMOND Luke": "redmond-luke",
    "REDMOND Peter": "redmond-peter",
    "REDMOND Sarah": "redmond-sarah",
    "REDMOND Tim": "redmond-tim",
    "REDRAWS Tracey": "redraws-tracey",
    "REDSECKER Buffy": "redsecker-buffy",
    "REDSTARDOGFISH ": "redstardogfish",
    "REDSTONE Kit": "redstone-kit",
    "REDUCED SHAKESPEARE COMPANY ": "reduced-shakespeare-company",
    "REDWOOD John": "redwood-john",
    "REDWOOD John Ekert": "redwood-john-ekert",
    "REDWOOD John Henry": "redwood-john-henry",
    "REDWOOD Lee": "redwood-lee",
    "REDWOOD Mike": "redwood-mike",
    "REE Larry": "ree-larry",
    "REECE Arthur": "reece-arthur",
    "REECE R": "reece-r",
    "REED Alan L": "reed-alan-l",
    "REED Annabel Mutale": "reed-annabel-mutale",
    "REED Bill": "reed-bill",
    "REED Cameron": "reed-cameron",
    "REED David": "reed-david",
    "REED David Wayne": "reed-david-wayne",
    "REED Don": "reed-don",
    "REED Edwena": "reed-edwena",
    "REED Erica": "reed-erica",
    "REED F Edward": "reed-f-edward",
    "REED Graham": "reed-graham",
    "REED H": "reed-h",
    "REED Henry": "reed-henry",
    "REED Holly": "reed-holly",
    "REED Ishmael": "reed-ishmael",
    "REED Janet": "reed-janet",
    "REED Jason": "reed-jason",
    "REED Kevin": "reed-kevin",
    "REED Larry Allen": "reed-larry-allen",
    "REED Les": "reed-les",
    "REED Mark": "reed-mark",
    "REED Martin": "reed-martin",
    "REED Matt": "reed-matt",
    "REED Robert": "reed-robert",
    "REED Roland": "reed-roland",
    "REED Ron": "reed-ron",
    "REED Shannon": "reed-shannon",
    "REED Sylvia": "reed-sylvia",
    "REED Will": "reed-will",
    "REEDER Conrad": "reeder-conrad",
    "REEDER Lydia T": "reeder-lydia-t",
    "REEDMAN Linnie": "reedman-linnie",
    "REEDMAN Mark": "reedman-mark",
    "REEDY Charmaine": "reedy-charmaine",
    "REEDY Geetha": "reedy-geetha",
    "REEDY M Kilburg": "reedy-m-kilburg",
    "REEGER John": "reeger-john",
    "REEL Arthur": "reel-arthur",
    "REES Bedwyr": "rees-bedwyr",
    "REES Byron": "rees-byron",
    "REES David": "rees-david",
    "REES Douglas": "rees-douglas",
    "REES Jasper": "rees-jasper",
    "REES Keith": "rees-keith",
    "REES Leslie": "rees-leslie",
    "REES Marc": "rees-marc",
    "REES Noreen": "rees-noreen",
    "REES Parker": "rees-parker",
    "REES Phoebe M": "rees-phoebe-m",
    "REES Roger": "rees-roger",
    "REES Sara": "rees-sara",
    "REES Stephen Lee": "rees-stephen-lee",
    "REES Toby Parker": "rees-toby-parker",
    "REES Tony": "rees-tony",
    "REES-CUMMINGS Kevin": "rees-cummings-kevin",
    "REESE Andrea": "reese-andrea",
    "REESE Andy Arden": "reese-andy-arden",
    "REESE Bill": "reese-bill",
    "REESE Kevin M": "reese-kevin-m",
    "REESE Rob": "reese-rob",
    "REESE Robin": "reese-robin",
    "REESE Venus Opal": "reese-venus-opal",
    "REEVE Anastasia": "reeve-anastasia",
    "REEVE Claire": "reeve-claire",
    "REEVE Eva": "reeve-eva",
    "REEVE Franklin R": "reeve-franklin-r",
    "REEVE Jack": "reeve-jack",
    "REEVE Nick": "reeve-nick",
    "REEVE Stuart": "reeve-stuart",
    "REEVES Albert": "reeves-albert",
    "REEVES Brooks": "reeves-brooks",
    "REEVES C G": "reeves-c-g",
    "REEVES Dan Peter": "reeves-dan-peter",
    "REEVES David": "reeves-david",
    "REEVES Drew": "reeves-drew",
    "REEVES Emma": "reeves-emma",
    "REEVES James": "reeves-james",
    "REEVES John": "reeves-john",
    "REEVES Marcus": "reeves-marcus",
    "REEVES Melissa": "reeves-melissa",
    "REEVES Pamela": "reeves-pamela",
    "REEVES Phil": "reeves-phil",
    "REFAEL Shmuel": "refael-shmuel",
    "REGAL David": "regal-david",
    "REGAN Bernadette": "regan-bernadette",
    "REGAN Dean": "regan-dean",
    "REGAN Denyse Gervais": "regan-denyse-gervais",
    "REGAN Henry": "regan-henry",
    "REGAN Moma": "regan-moma",
    "REGAN Sylvia": "regan-sylvia",
    "REGAN Vincent": "regan-vincent",
    "REGAN Yarrow": "regan-yarrow",
    "REGELSKI Dan": "regelski-dan",
    "REGEN Haas": "regen-haas",
    "REGIMBAL Brendan": "regimbal-brendan",
    "REGINA Emilio": "regina-emilio",
    "REGINA-THON Stephen": "regina-thon-stephen",
    "REGINE L J": "regine-l-j",
    "REGIS John": "regis-john",
    "REGISTER Debra Ann": "register-debra-ann",
    "REGNARD Jean-Francios": "regnard-jean-francios",
    "REGNAULT Francois": "regnault-francois",
    "REGNIER Max": "regnier-max",
    "REGNIER Michael": "regnier-michael",
    "REGNIER-WILSON Iain": "regnier-wilson-iain",
    "REGO Jacqueline": "rego-jacqueline",
    "REGOS Esti": "regos-esti",
    "REHAK Jay": "rehak-jay",
    "REHDER Caroline": "rehder-caroline",
    "REHMAN Shabana": "rehman-shabana",
    "REICH Caral": "reich-caral",
    "REICH Dale": "reich-dale",
    "REICH Egan": "reich-egan",
    "REICH Jeffrey": "reich-jeffrey",
    "REICH John": "reich-john",
    "REICH Leo": "reich-leo",
    "REICH Richard": "reich-richard",
    "REICH Savannah": "reich-savannah",
    "REICH Steve": "reich-steve",
    "REICH Valerie": "reich-valerie",
    "REICHEL Cara": "reichel-cara",
    "REICHERT Jennifer": "reichert-jennifer",
    "REICHLIN Saul": "reichlin-saul",
    "REICHMAN Richard": "reichman-richard",
    "REID Alexander": "reid-alexander",
    "REID Alison": "reid-alison",
    "REID Andrew": "reid-andrew",
    "REID Angus": "reid-angus",
    "REID Ann": "reid-ann",
    "REID Benji": "reid-benji",
    "REID Caroline": "reid-caroline",
    "REID Chloe": "reid-chloe",
    "REID Christina": "reid-christina",
    "REID Derek": "reid-derek",
    "REID E M G": "reid-e-m-g",
    "REID Georgina": "reid-georgina",
    "REID Graham": "reid-graham",
    "REID Gregory": "reid-gregory",
    "REID Hazel": "reid-hazel",
    "REID Ilene": "reid-ilene",
    "REID Jamie": "reid-jamie",
    "REID Jimmy": "reid-jimmy",
    "REID Karin": "reid-karin",
    "REID Kate": "reid-kate",
    "REID Kerry": "reid-kerry",
    "REID Kieran James": "reid-kieran-james",
    "REID Lynne": "reid-lynne",
    "REID Mark": "reid-mark",
    "REID Mike": "reid-mike",
    "REID Nadrae": "reid-nadrae",
    "REID Netta Blair": "reid-netta-blair",
    "REID Nicolas": "reid-nicolas",
    "REID Peter": "reid-peter",
    "REID Rachel Rose": "reid-rachel-rose",
    "REID Robert": "reid-robert",
    "REID Sally": "reid-sally",
    "REID Stella": "reid-stella",
    "REID Vernon": "reid-vernon",
    "REID Wayne": "reid-wayne",
    "REIDEL James": "reidel-james",
    "REID-JAMIESON Marion": "reid-jamieson-marion",
    "REID-MEREDITH Amelia": "reid-meredith-amelia",
    "REIDY Gabrielle": "reidy-gabrielle",
    "REIFFEL David": "reiffel-david",
    "REIFLER Nelly": "reifler-nelly",
    "REIGHTON Ester": "reighton-ester",
    "REILLY Claudia": "reilly-claudia",
    "REILLY Fergus": "reilly-fergus",
    "REILLY Frank E": "reilly-frank-e",
    "REILLY Gary": "reilly-gary",
    "REILLY Nancy": "reilly-nancy",
    "REILLY Paden Baier": "reilly-paden-baier",
    "REILLY Terrence J": "reilly-terrence-j",
    "REILLY Tina": "reilly-tina",
    "REILLY William": "reilly-william",
    "REILLY William A": "reilly-william-a",
    "REILY Frank E": "reily-frank-e",
    "REILY George Wolfe": "reily-george-wolfe",
    "REILY Matt": "reily-matt",
    "REIMAN Sam": "reiman-sam",
    "REIMANN Michael": "reimann-michael",
    "REIMER Kristian": "reimer-kristian",
    "REIMOLD Peter": "reimold-peter",
    "REINACH Elizabeth": "reinach-elizabeth",
    "REINBLATT George": "reinblatt-george",
    "REINER Carl": "reiner-carl",
    "REINER Christopher": "reiner-christopher",
    "REINERS Ashley": "reiners-ashley",
    "REINERT Otto": "reinert-otto",
    "REINES Ariana": "reines-ariana",
    "REINES Bernard": "reines-bernard",
    "REINFRANK Arno": "reinfrank-arno",
    "REINGOLD Jacquelyn": "reingold-jacquelyn",
    "REINHARD Lauren": "reinhard-lauren",
    "REINHARD Maria": "reinhard-maria",
    "REINHARD Susan B": "reinhard-susan-b",
    "REINHARDT Gunther": "reinhardt-gunther",
    "REINHARDT Mary Anne": "reinhardt-mary-anne",
    "REINHARDT Virginia": "reinhardt-virginia",
    "REINHART Leisel": "reinhart-leisel",
    "REINHOLD Fran": "reinhold-fran",
    "REINHOLD Robert": "reinhold-robert",
    "REINHOLZ Randy": "reinholz-randy",
    "REINISCH Daniel": "reinisch-daniel",
    "REINKE Lisa": "reinke-lisa",
    "REINKING Ann": "reinking-ann",
    "REINSHAGEN Gerlind": "reinshagen-gerlind",
    "REINSILBER Justin": "reinsilber-justin",
    "REINSTEIN Ted": "reinstein-ted",
    "REIS Rita": "reis-rita",
    "REIS Ted": "reis-ted",
    "REISCH Paul": "reisch-paul",
    "REISENHOFER Heinrich": "reisenhofer-heinrich",
    "REISER Dave": "reiser-dave",
    "REISER Louise": "reiser-louise",
    "REISER Robert": "reiser-robert",
    "REISMAN Arnie": "reisman-arnie",
    "REISMAN Boaz": "reisman-boaz",
    "REISMAN Dolly": "reisman-dolly",
    "REISMAN Gabrielle": "reisman-gabrielle",
    "REISMAN Paul": "reisman-paul",
    "REISMAN Sam": "reisman-sam",
    "REISS Alvin H": "reiss-alvin-h",
    "REISS Andy": "reiss-andy",
    "REISS Anya": "reiss-anya",
    "REISS Erwin": "reiss-erwin",
    "REISS Jay": "reiss-jay",
    "REISS Mike": "reiss-mike",
    "REISSA Eleanor": "reissa-eleanor",
    "REITANO Tony": "reitano-tony",
    "REITER Brandt": "reiter-brandt",
    "REITER David": "reiter-david",
    "REITER Ginger": "reiter-ginger",
    "REITER Kathleen": "reiter-kathleen",
    "REITER Sy": "reiter-sy",
    "REITMAN-DOBI Lisa": "reitman-dobi-lisa",
    "REITMANN Max": "reitmann-max",
    "REITZ Daniel": "reitz-daniel",
    "REJANO ROMERO Daniel": "rejano-romero-daniel",
    "REJECTS REVENGE ": "rejects-revenge",
    "REKRUT Michael P": "rekrut-michael-p",
    "RELATIONSHIP, THE ": "relationship",
    "RELLA Concetta Rose": "rella-concetta-rose",
    "RELYEA Miriam": "relyea-miriam",
    "REMARQUE Erich Maria": "remarque-erich-maria",
    "REMICK Jane Claire": "remick-jane-claire",
    "REMINGTON Kevin": "remington-kevin",
    "REMINGTON Wendy": "remington-wendy",
    "REMLAP Steve Palmer": "remlap-steve-palmer",
    "REMMES Dan": "remmes-dan",
    "REMMLER Laura": "remmler-laura",
    "REMOLDE Sophia": "remolde-sophia",
    "REMPLE Jean": "remple-jean",
    "REMSHARDT Ralf": "remshardt-ralf",
    "REMY Alfred": "remy-alfred",
    "REMY Shae": "remy-shae",
    "RENARD Joe": "renard-joe",
    "RENARD Joseph": "renard-joseph",
    "RENARD Jules": "renard-jules",
    "RENAUD Bryan": "renaud-bryan",
    "RENAUD Nicole": "renaud-nicole",
    "RENAUD Noelle": "renaud-noelle",
    "RENDEROS Rafael Antonio": "renderos-rafael-antonio",
    "RENDERS Kim": "renders-kim",
    "RENDINO Mike": "rendino-mike",
    "RENDLE-SHORT Francesca": "rendle-short-francesca",
    "RENDON Marcie": "rendon-marcie",
    "RENE Norman": "rene-norman",
    "RENEE ": "renee",
    "RENE-LAWSON Taio": "rene-lawson-taio",
    "RENNA Kathy": "renna-kathy",
    "RENNARD Deborah": "rennard-deborah",
    "RENNIE Alexander": "rennie-alexander",
    "RENNISON Louise": "rennison-louise",
    "RENNOLDSON James": "rennoldson-james",
    "RENO Brian": "reno-brian",
    "RENO ": "reno",
    "RENSTEN Mary": "rensten-mary",
    "RENSTROM Christopher": "renstrom-christopher",
    "RENTELL Anne-Louise": "rentell-anne-louise",
    "RENTERIA Tanner": "renteria-tanner",
    "RENTZEL Chris": "rentzel-chris",
    "RENWICK David": "renwick-david",
    "RENZI Marta": "renzi-marta",
    "REOCH Ernest": "reoch-ernest",
    "REOLI John": "reoli-john",
    "REPICCI William": "repicci-william",
    "REPLINGER David Anthony": "replinger-david-anthony",
    "REPPE Rik": "reppe-rik",
    "REPPE Shona": "reppe-shona",
    "REPS Billy": "reps-billy",
    "REQUARDT Frauke": "requardt-frauke",
    "RESING Mary": "resing-mary",
    "RESINO Carmen": "resino-carmen",
    "RESNICK Jed": "resnick-jed",
    "RESNICK Lisa": "resnick-lisa",
    "RESNICK Patricia": "resnick-patricia",
    "RESNIK Muriel": "resnik-muriel",
    "RESPICIO Mae": "respicio-mae",
    "RESSEGGER Lorraine": "ressegger-lorraine",
    "RESSIEB George": "ressieb-george",
    "RESTA Jeff": "resta-jeff",
    "RESTAINO Cara": "restaino-cara",
    "RESTAK Jennifer": "restak-jennifer",
    "RESTO Andrew Loren": "resto-andrew-loren",
    "RESTO Max": "resto-max",
    "RESTREPO Federico": "restrepo-federico",
    "RESTUCCIA Paul": "restuccia-paul",
    "RESZCZYNSKI Maciek": "reszczynski-maciek",
    "RETALLACK Guy": "retallack-guy",
    "RETALLACK John": "retallack-john",
    "REUBEN Harry": "reuben-harry",
    "REUBENS Paul": "reubens-paul",
    "REULER Jack": "reuler-jack",
    "REUNING Jonathan": "reuning-jonathan",
    "REUTER Anna Helen": "reuter-anna-helen",
    "REVAN Rosie": "revan-rosie",
    "REVARD Vanessa": "revard-vanessa",
    "REVEL Kara": "revel-kara",
    "REVELES Nicolas": "reveles-nicolas",
    "REVELL Nick": "revell-nick",
    "REVELLE Lezlie": "revelle-lezlie",
    "REVENTBERG Med": "reventberg-med",
    "REVESZ Adam": "revesz-adam",
    "REVI Anastasia": "revi-anastasia",
    "REVILL Fiona": "revill-fiona",
    "REWSE Tamara": "rewse-tamara",
    "REX Sebastian": "rex-sebastian",
    "REXROTH Kenneth": "rexroth-kenneth",
    "REY Melanie": "rey-melanie",
    "REYCRAFT Sean": "reycraft-sean",
    "REYES Eddie": "reyes-eddie",
    "REYES Guillermo": "reyes-guillermo",
    "REYES Kristine M": "reyes-kristine-m",
    "REYES Rodney E": "reyes-rodney-e",
    "REYES Rosemary Cho": "reyes-rosemary-cho",
    "REYLAND Jim": "reyland-jim",
    "REYNA Laura": "reyna-laura",
    "REYNER Ruby Lynn": "reyner-ruby-lynn",
    "REYNISDOTTIR S Sunna": "reynisdottir-s-sunna",
    "REYNOLDS Amelia": "reynolds-amelia",
    "REYNOLDS Ania": "reynolds-ania",
    "REYNOLDS Anna": "reynolds-anna",
    "REYNOLDS Becky": "reynolds-becky",
    "REYNOLDS Billie": "reynolds-billie",
    "REYNOLDS Boyd": "reynolds-boyd",
    "REYNOLDS Bryan": "reynolds-bryan",
    "REYNOLDS Dorothy": "reynolds-dorothy",
    "REYNOLDS Edmond": "reynolds-edmond",
    "REYNOLDS Eugene": "reynolds-eugene",
    "REYNOLDS G": "reynolds-g",
    "REYNOLDS J Scott": "reynolds-j-scott",
    "REYNOLDS James": "reynolds-james",
    "REYNOLDS Jean": "reynolds-jean",
    "REYNOLDS Jeremiah": "reynolds-jeremiah",
    "REYNOLDS John": "reynolds-john",
    "REYNOLDS Jon": "reynolds-jon",
    "REYNOLDS Jonathan": "reynolds-jonathan",
    "REYNOLDS Joshua": "reynolds-joshua",
    "REYNOLDS Karen Wheeling": "reynolds-karen-wheeling",
    "REYNOLDS Kathleen": "reynolds-kathleen",
    "REYNOLDS Kim": "reynolds-kim",
    "REYNOLDS Kirsten": "reynolds-kirsten",
    "REYNOLDS Linda": "reynolds-linda",
    "REYNOLDS Mary": "reynolds-mary",
    "REYNOLDS Michael Todd": "reynolds-michael-todd",
    "REYNOLDS Neal": "reynolds-neal",
    "REYNOLDS Nicola": "reynolds-nicola",
    "REYNOLDS Norm": "reynolds-norm",
    "REYNOLDS Patrick": "reynolds-patrick",
    "REYNOLDS Peter": "reynolds-peter",
    "REYNOLDS Rebecca": "reynolds-rebecca",
    "REYNOLDS Roland": "reynolds-roland",
    "REYNOLDS Ryan": "reynolds-ryan",
    "REYNOLDS Sophie": "reynolds-sophie",
    "REYNOLDS Tim": "reynolds-tim",
    "REYNOLDS Timothy McCown": "reynolds-timothy-mccown",
    "REYNOLDS Vicki": "reynolds-vicki",
    "REYNOLDS Will": "reynolds-will",
    "REYNOSO Patricia Monica": "reynoso-patricia-monica",
    "REZA Yasmina": "reza-yasmina",
    "REZES John Michael": "rezes-john-michael",
    "REZNECK Abigail": "rezneck-abigail",
    "REZNIKOV Eugene": "reznikov-eugene",
    "REZNIKOV Hanon": "reznikov-hanon"
  }
};