export default {
  "metadata": {
    "results": 476,
    "timeStamp": "2025-12-05T21:30:21.375Z",
    "url": "https://www.doollee.com/PlaywrightsR/R_playwrights_g-l.php"
  },
  "authors": {
    "RHEE Ki Seung": "rhee-ki-seung",
    "RHEE Lally": "rhee-lally",
    "RHEE Margaret": "rhee-margaret",
    "RHEIM Marlene": "rheim-marlene",
    "RHEINFRANK Elizabeth Scales": "rheinfrank-elizabeth-scales",
    "RHETORIC Sandy": "rhetoric-sandy",
    "RHINDRESS Charlie": "rhindress-charlie",
    "RHINO QUARTET ": "rhino-quartet",
    "RHOADS Angela": "rhoads-angela",
    "RHOADS Kay": "rhoads-kay",
    "RHODES Albert": "rhodes-albert",
    "RHODES Amy": "rhodes-amy",
    "RHODES Carrolline": "rhodes-carrolline",
    "RHODES David": "rhodes-david",
    "RHODES Derek": "rhodes-derek",
    "RHODES Elizabeth": "rhodes-elizabeth",
    "RHODES Evan H": "rhodes-evan-h",
    "RHODES Graham A": "rhodes-graham-a",
    "RHODES Jamie": "rhodes-jamie",
    "RHODES Molly": "rhodes-molly",
    "RHODES Nancy": "rhodes-nancy",
    "RHODES Neil": "rhodes-neil",
    "RHODES Norman L": "rhodes-norman-l",
    "RHODES Rick": "rhodes-rick",
    "RHODES Spike": "rhodes-spike",
    "RHODES Vanessa": "rhodes-vanessa",
    "RHODES Vivian": "rhodes-vivian",
    "RHONE Trevor D": "rhone-trevor-d",
    "RHOTENBERRY Hudson": "rhotenberry-hudson",
    "RHUM AND CLAY ": "rhum-and-clay",
    "RHYS Gruff": "rhys-gruff",
    "RHYS Jean": "rhys-jean",
    "RHYS Manon": "rhys-manon",
    "RHYS Tim": "rhys-tim",
    "RIABKO Kyle": "riabko-kyle",
    "RIAD Alex": "riad-alex",
    "RIAIN Ailis Ni": "riain-ailis-ni",
    "RIANDA Leonora B": "rianda-leonora-b",
    "RIAZI Healah": "riazi-healah",
    "RIBALOW Meir Zvi": "ribalow-meir-zvi",
    "RIBBITS Thos": "ribbits-thos",
    "RIBEIRO Antonio": "ribeiro-antonio",
    "RIBMAN Ronald": "ribman-ronald",
    "RIBNIKOV Nikolai": "ribnikov-nikolai",
    "RICCA Mike": "ricca-mike",
    "RICCI Marilyn": "ricci-marilyn",
    "RICCIARDI Aaron": "ricciardi-aaron",
    "RICCIO Thomas": "riccio-thomas",
    "RICCORA Paola": "riccora-paola",
    "RICE Annabelle": "rice-annabelle",
    "RICE Ari": "rice-ari",
    "RICE Bernard": "rice-bernard",
    "RICE Carol": "rice-carol",
    "RICE Carol M": "rice-carol-m",
    "RICE Charles": "rice-charles",
    "RICE Claire": "rice-claire",
    "RICE Darcy": "rice-darcy",
    "RICE David": "rice-david",
    "RICE Dorothy": "rice-dorothy",
    "RICE Elmer": "rice-elmer",
    "RICE Emma": "rice-emma",
    "RICE Gitz": "rice-gitz",
    "RICE Gwendolyn": "rice-gwendolyn",
    "RICE Jacob": "rice-jacob",
    "RICE Jason T": "rice-jason-t",
    "RICE Jeremy": "rice-jeremy",
    "RICE John C": "rice-john-c",
    "RICE Kate": "rice-kate",
    "RICE Kevin": "rice-kevin",
    "RICE Luanne": "rice-luanne",
    "RICE Marni": "rice-marni",
    "RICE Michael": "rice-michael",
    "RICE Molly": "rice-molly",
    "RICE Nigel": "rice-nigel",
    "RICE Phil": "rice-phil",
    "RICE Simon": "rice-simon",
    "RICE Susan": "rice-susan",
    "RICE Tim": "rice-tim",
    "RICE Tori": "rice-tori",
    "RICE-GONZALEZ Charles": "rice-gonzalez-charles",
    "RICE-MARSH Rahima": "rice-marsh-rahima",
    "RICE-OXLEY Andrew": "rice-oxley-andrew",
    "RICH Carol O'Neal": "rich-carol-o-neal",
    "RICH Jonathan": "rich-jonathan",
    "RICH Katie": "rich-katie",
    "RICH Khristee": "rich-khristee",
    "RICH Paul": "rich-paul",
    "RICH Simon": "rich-simon",
    "RICH Stephanie": "rich-stephanie",
    "RICHARD Bill": "richard-bill",
    "RICHARD David": "richard-david",
    "RICHARD Dennis": "richard-dennis",
    "RICHARD Eric": "richard-eric",
    "RICHARD Mae": "richard-mae",
    "RICHARD N": "richard-n",
    "RICHARD Rafiq": "richard-rafiq",
    "RICHARD Sandy": "richard-sandy",
    "RICHARD-FOX David": "richard-fox-david",
    "RICHARDS Alison": "richards-alison",
    "RICHARDS Alun": "richards-alun",
    "RICHARDS Beah": "richards-beah",
    "RICHARDS Ben": "richards-ben",
    "RICHARDS Bernard": "richards-bernard",
    "RICHARDS Charles": "richards-charles",
    "RICHARDS Christopher": "richards-christopher",
    "RICHARDS Diane": "richards-diane",
    "RICHARDS E Claude": "richards-e-claude",
    "RICHARDS Elizabeth": "richards-elizabeth",
    "RICHARDS Gary": "richards-gary",
    "RICHARDS Gavin": "richards-gavin",
    "RICHARDS Graham": "richards-graham",
    "RICHARDS H M": "richards-h-m",
    "RICHARDS Holly": "richards-holly",
    "RICHARDS Huw": "richards-huw",
    "RICHARDS I A": "richards-i-a",
    "RICHARDS Jeremy": "richards-jeremy",
    "RICHARDS Joe": "richards-joe",
    "RICHARDS K": "richards-k",
    "RICHARDS Karie": "richards-karie",
    "RICHARDS Kelsey": "richards-kelsey",
    "RICHARDS Kenneth": "richards-kenneth",
    "RICHARDS Laura": "richards-laura",
    "RICHARDS Lexford": "richards-lexford",
    "RICHARDS Lily": "richards-lily",
    "RICHARDS Linsell": "richards-linsell",
    "RICHARDS Mark Richard": "richards-mark-richard",
    "RICHARDS Martyn": "richards-martyn",
    "RICHARDS Max B": "richards-max-b",
    "RICHARDS Mikeur": "richards-mikeur",
    "RICHARDS Nanci": "richards-nanci",
    "RICHARDS Paul": "richards-paul",
    "RICHARDS Peter": "richards-peter",
    "RICHARDS Rosemary": "richards-rosemary",
    "RICHARDS Ryan": "richards-ryan",
    "RICHARDS Scott Davenport": "richards-scott-davenport",
    "RICHARDS Stanley": "richards-stanley",
    "RICHARDS Tom": "richards-tom",
    "RICHARDS Victor": "richards-victor",
    "RICHARDS (FENN) Cheryl": "richards-cheryl",
    "RICHARDSON Alan": "richardson-alan",
    "RICHARDSON Ali": "richardson-ali",
    "RICHARDSON Annie": "richardson-annie",
    "RICHARDSON Bill": "richardson-bill",
    "RICHARDSON Christopher": "richardson-christopher",
    "RICHARDSON Damien": "richardson-damien",
    "RICHARDSON Diana": "richardson-diana",
    "RICHARDSON Drew": "richardson-drew",
    "RICHARDSON Emma": "richardson-emma",
    "RICHARDSON Esther": "richardson-esther",
    "RICHARDSON Evan": "richardson-evan",
    "RICHARDSON Helen E": "richardson-helen-e",
    "RICHARDSON Helen R": "richardson-helen-r",
    "RICHARDSON Howard": "richardson-howard",
    "RICHARDSON Jack": "richardson-jack",
    "RICHARDSON Jack (1)": "richardson-jack-1",
    "RICHARDSON Jael": "richardson-jael",
    "RICHARDSON James G": "richardson-james-g",
    "RICHARDSON John": "richardson-john",
    "RICHARDSON John (1)": "richardson-john-1",
    "RICHARDSON Julia": "richardson-julia",
    "RICHARDSON Karina": "richardson-karina",
    "RICHARDSON Lea": "richardson-lea",
    "RICHARDSON Leo": "richardson-leo",
    "RICHARDSON Lexford": "richardson-lexford",
    "RICHARDSON Mariah L": "richardson-mariah-l",
    "RICHARDSON Mel": "richardson-mel",
    "RICHARDSON Morgan": "richardson-morgan",
    "RICHARDSON Neal": "richardson-neal",
    "RICHARDSON Sally": "richardson-sally",
    "RICHARDSON Sam": "richardson-sam",
    "RICHARDSON Stan": "richardson-stan",
    "RICHARDSON Susan": "richardson-susan",
    "RICHARDSON Tashina": "richardson-tashina",
    "RICHARDSON Thomas": "richardson-thomas",
    "RICHARDSON Virgil": "richardson-virgil",
    "RICHARDSON Wendy": "richardson-wendy",
    "RICHARDSON William": "richardson-william",
    "RICHARDSON Wylie Reed": "richardson-wylie-reed",
    "RICHE Robert": "riche-robert",
    "RICHEL Stu": "richel-stu",
    "RICHENS Michael": "richens-michael",
    "RICHER Paula": "richer-paula",
    "RICHES Adam": "riches-adam",
    "RICHEY Christine": "richey-christine",
    "RICHIE Donald": "richie-donald",
    "RICHIE-LACY Sterline": "richie-lacy-sterline",
    "RICHLER Mordecai": "richler-mordecai",
    "RICHMAN Arthur": "richman-arthur",
    "RICHMAN Lincoln": "richman-lincoln",
    "RICHMAN Peter Mark": "richman-peter-mark",
    "RICHMAN Stuart": "richman-stuart",
    "RICHMOND David": "richmond-david",
    "RICHMOND Gillian": "richmond-gillian",
    "RICHMOND Jacob": "richmond-jacob",
    "RICHMOND Joan": "richmond-joan",
    "RICHMOND Kent": "richmond-kent",
    "RICHMOND Len": "richmond-len",
    "RICHMOND Michael": "richmond-michael",
    "RICHMOND Ray": "richmond-ray",
    "RICHMOND Robert": "richmond-robert",
    "RICHTER Carolyn": "richter-carolyn",
    "RICHTER Falk": "richter-falk",
    "RICHTER Jeremy F": "richter-jeremy-f",
    "RICHTER Stephen": "richter-stephen",
    "RICKARD Barb E": "rickard-barb-e",
    "RICKARD James": "rickard-james",
    "RICKARDS Dorothy": "rickards-dorothy",
    "RICKARDS Gareth": "rickards-gareth",
    "RICKARDS Rachael-Lee": "rickards-rachael-lee",
    "RICKER'S ISLAND INMATES ": "rickers-island-inmates",
    "RICKET Julian": "ricket-julian",
    "RICKETTS Cathryn": "ricketts-cathryn",
    "RICKETTS Rosemary": "ricketts-rosemary",
    "RICKETTS Wendell": "ricketts-wendell",
    "RICKMAN Alan": "rickman-alan",
    "RICKMAN Allen Lewis": "rickman-allen-lewis",
    "RICKMAN Tom": "rickman-tom",
    "RICKS Craig": "ricks-craig",
    "RIDDELL Chris": "riddell-chris",
    "RIDDELL Mike": "riddell-mike",
    "RIDDELL Patrick": "riddell-patrick",
    "RIDDLE Cynthia": "riddle-cynthia",
    "RIDEOUT George": "rideout-george",
    "RIDER Brian": "rider-brian",
    "RIDER Cyprian": "rider-cyprian",
    "RIDER Janice": "rider-janice",
    "RIDER Jennifer": "rider-jennifer",
    "RIDER Sue": "rider-sue",
    "RIDGE Antonia": "ridge-antonia",
    "RIDGE Mark A": "ridge-mark-a",
    "RIDGELY Tom": "ridgely-tom",
    "RIDGEWAY George": "ridgeway-george",
    "RIDGEWAY Laura": "ridgeway-laura",
    "RIDGEWAY Leslie": "ridgeway-leslie",
    "RIDGEWAY Rebecca": "ridgeway-rebecca",
    "RIDICULUSMUS ": "ridiculusmus",
    "RIDING Kathryn": "riding-kathryn",
    "RIDINGS Stephanie": "ridings-stephanie",
    "RIDLER Anne": "ridler-anne",
    "RIDLEY Arnold": "ridley-arnold",
    "RIDLEY Jane": "ridley-jane",
    "RIDLEY Philip": "ridley-philip",
    "RIDLEY Richard": "ridley-richard",
    "RIECHEL, JR Robert": "riechel-jr-robert",
    "RIEDEL Jonathan": "riedel-jonathan",
    "RIEDER Emily": "rieder-emily",
    "RIEDY David": "riedy-david",
    "RIEGER Corey": "rieger-corey",
    "RIEGER Matt": "rieger-matt",
    "RIEGLER Heidi": "riegler-heidi",
    "RIEHL Carl": "riehl-carl",
    "RIEHL Karen": "riehl-karen",
    "RIEKKI Ron": "riekki-ron",
    "RIELLY Justin": "rielly-justin",
    "RIEMAN-IHLI Susan": "rieman-ihli-susan",
    "RIEMER Robert": "riemer-robert",
    "RIESER Allan": "rieser-allan",
    "RIESER Thomas W": "rieser-thomas-w",
    "RIESSEN David": "riessen-david",
    "RIETTI Robert": "rietti-robert",
    "RIETTY Robert": "rietty-robert",
    "RIFFICE John Philip": "riffice-john-philip",
    "RIFKIN Don": "rifkin-don",
    "RIFKIN Frances": "rifkin-frances",
    "RIFKIN Leo": "rifkin-leo",
    "RIGAL Pierre": "rigal-pierre",
    "RIGANO David": "rigano-david",
    "RIGBY Annie": "rigby-annie",
    "RIGBY Harry": "rigby-harry",
    "RIGBY Kate": "rigby-kate",
    "RIGBY Ray": "rigby-ray",
    "RIGBY Robert": "rigby-robert",
    "RIGBY Ron": "rigby-ron",
    "RIGBY Victoria": "rigby-victoria",
    "RIGG Alex": "rigg-alex",
    "RIGG Dray": "rigg-dray",
    "RIGG Georgia": "rigg-georgia",
    "RIGG Kate": "rigg-kate",
    "RIGGAN Kaine": "riggan-kaine",
    "RIGGINS Caleb": "riggins-caleb",
    "RIGGS Dolores": "riggs-dolores",
    "RIGGS Henry": "riggs-henry",
    "RIGGS Kyle": "riggs-kyle",
    "RIGGS Lynn": "riggs-lynn",
    "RIGGS Mark Travis": "riggs-mark-travis",
    "RIGGS Rosee": "riggs-rosee",
    "RIGGS Thomas Lawrason": "riggs-thomas-lawrason",
    "RIGHT SIZE, THE ": "right-size-the",
    "RIGHTER Karen": "righter-karen",
    "RIGNEY Mark": "rigney-mark",
    "RIGNEY Shaun": "rigney-shaun",
    "RIGNEY Tracey": "rigney-tracey",
    "RIGONI Megan": "rigoni-megan",
    "RIGSBY Glynis": "rigsby-glynis",
    "RIJINDERS Gerardjan": "rijinders-gerardjan",
    "RIJS Ellen": "rijs-ellen",
    "RIKA Emma": "rika-emma",
    "RIKHYE Kiran": "rikhye-kiran",
    "RIKOF Hilary": "rikof-hilary",
    "RILEIGH Kendall": "rileigh-kendall",
    "RILEY Andy": "riley-andy",
    "RILEY Anne": "riley-anne",
    "RILEY Bradford": "riley-bradford",
    "RILEY Clayton": "riley-clayton",
    "RILEY Colin": "riley-colin",
    "RILEY David": "riley-david",
    "RILEY Dom": "riley-dom",
    "RILEY Jean": "riley-jean",
    "RILEY Jess": "riley-jess",
    "RILEY Jonathon": "riley-jonathon",
    "RILEY Kevin": "riley-kevin",
    "RILEY Lynne": "riley-lynne",
    "RILEY Martin": "riley-martin",
    "RILEY Melissa": "riley-melissa",
    "RILEY Ngaire": "riley-ngaire",
    "RILEY Nord": "riley-nord",
    "RILEY Norman": "riley-norman",
    "RILEY Paula": "riley-paula",
    "RILEY Peggy": "riley-peggy",
    "RILEY Richard": "riley-richard",
    "RILEY Robert": "riley-robert",
    "RILEY Sam": "riley-sam",
    "RILEY Sean": "riley-sean",
    "RILEY Terry": "riley-terry",
    "RILEY Ward James": "riley-ward-james",
    "RILKE Rainer Maria": "rilke-rainer-maria",
    "RILKE Rainier Maria": "rilke-rainier-maria",
    "RILL Marcus": "rill-marcus",
    "RIMALOWER Ben": "rimalower-ben",
    "RIMALOWER Lucy": "rimalower-lucy",
    "RIMAT Sylvia": "rimat-sylvia",
    "RIMEL Linda": "rimel-linda",
    "RIMINGTON Heather": "rimington-heather",
    "RIMINI PROTOKOLL ": "rimini-protokoll",
    "RIML Michele": "riml-michele",
    "RIMMER Andrew": "rimmer-andrew",
    "RIMMER David": "rimmer-david",
    "RIMMER Joanne": "rimmer-joanne",
    "RIMMER Laura": "rimmer-laura",
    "RIMMER Matthew": "rimmer-matthew",
    "RIMMER Thomas": "rimmer-thomas",
    "RINALDI Frank": "rinaldi-frank",
    "RINALDI Mike": "rinaldi-mike",
    "RINCON Andrew": "rincon-andrew",
    "RINE Adrian": "rine-adrian",
    "RINE Anthony": "rine-anthony",
    "RINEAR Sheila": "rinear-sheila",
    "RINEHART Mary Roberts": "rinehart-mary-roberts",
    "RINEHART Patricia": "rinehart-patricia",
    "RINFRET Robert": "rinfret-robert",
    "RING Dan": "ring-dan",
    "RINGER Mark": "ringer-mark",
    "RINGHAM Ben": "ringham-ben",
    "RINGHAM Hannah": "ringham-hannah",
    "RINGHAM John": "ringham-john",
    "RINGHAM Max": "ringham-max",
    "RINGHEIM Karin": "ringheim-karin",
    "RINGKAMP Jonathan": "ringkamp-jonathan",
    "RINGROSE Audrey": "ringrose-audrey",
    "RINGUET Louise": "ringuet-louise",
    "RINGWALD Gerry": "ringwald-gerry",
    "RINGWOOD Andrew": "ringwood-andrew",
    "RINGWOOD Gwen Pharis": "ringwood-gwen-pharis",
    "RINK Lynn Marie": "rink-lynn-marie",
    "RINKE Moritz": "rinke-moritz",
    "RINOS Los": "rinos-los",
    "RINTELS David W": "rintels-david-w",
    "RINTELS Jonathan": "rintels-jonathan",
    "RINTOUL Craig A": "rintoul-craig-a",
    "RINTOUL Douglas": "rintoul-douglas",
    "RINTOUL Harry": "rintoul-harry",
    "RIORDAN Amy": "riordan-amy",
    "RIORDAN Arthur": "riordan-arthur",
    "RIORDAN Megan": "riordan-megan",
    "RIORDON Christopher": "riordon-christopher",
    "RIORDON Michael": "riordon-michael",
    "RIOS Alvaro Saar": "rios-alvaro-saar",
    "RIOS Corina": "rios-corina",
    "RIOS Esther": "rios-esther",
    "RIOS Osvaldo": "rios-osvaldo",
    "RIOSLEY Lane": "riosley-lane",
    "RIOT GROUP, THE ": "riot-group",
    "RIPLEY Finnegan": "ripley-finnegan",
    "RIPLEY Graham": "ripley-graham",
    "RIPLEY R B": "ripley-r-b",
    "RIPLEY Ryan": "ripley-ryan",
    "RIPOLL Laila": "ripoll-laila",
    "RIPPEL Ildiko": "rippel-ildiko",
    "RIPPY Erica": "rippy-erica",
    "RIQUELME Juan": "riquelme-juan",
    "RISBRIDGER Adam": "risbridger-adam",
    "RISCO Gonzalo Rodriguez": "risco-gonzalo-rodriguez",
    "RISE PRODUCTIONS ": "rise-productions",
    "RISEBERO John": "risebero-john",
    "RISEDALE Karl": "risedale-karl",
    "RISEWKEL Hannah": "risewkel-hannah",
    "RISING CIRCLE THEATER COLLECTIVE ": "rising-circle-theater-collective",
    "RISK David": "risk-david",
    "RISO Stephanie": "riso-stephanie",
    "RISSER Arthur C": "risser-arthur-c",
    "RISSETTO Diana": "rissetto-diana",
    "RISTAU Todd": "ristau-todd",
    "RITCH Alyssa": "ritch-alyssa",
    "RITCHEY Julie": "ritchey-julie",
    "RITCHIE Aileen": "ritchie-aileen",
    "RITCHIE David": "ritchie-david",
    "RITCHIE J M": "ritchie-j-m",
    "RITCHIE J T": "ritchie-j-t",
    "RITCHIE Matthew": "ritchie-matthew",
    "RITCHIE Paul": "ritchie-paul",
    "RITCHIE Paula": "ritchie-paula",
    "RITCHIE R": "ritchie-r",
    "RITCHIE Rebecca": "ritchie-rebecca",
    "RITCHIE Shane": "ritchie-shane",
    "RITCHIE Stevie": "ritchie-stevie",
    "RITCHIE Tanya": "ritchie-tanya",
    "RITSCH Joseph": "ritsch-joseph",
    "RITSON Dylan": "ritson-dylan",
    "RITTBERG Ellen Pober": "rittberg-ellen-pober",
    "RITTENHOUSE Michele Raper": "rittenhouse-michele-raper",
    "RITTER Erika": "ritter-erika",
    "RITTER Jon": "ritter-jon",
    "RITTER Michel": "ritter-michel",
    "RITTER Scott": "ritter-scott",
    "RITTNER Hannah Erin": "rittner-hannah-erin",
    "RITTNER Roger": "rittner-roger",
    "RITZ Joseph": "ritz-joseph",
    "RITZ Melissa": "ritz-melissa",
    "RIVA Julia": "riva-julia",
    "RIVAL Mary Macdonald": "rival-mary-macdonald",
    "RIVAMONTE Lia": "rivamonte-lia",
    "RIVAS Fernando": "rivas-fernando",
    "RIVE Tristan": "rive-tristan",
    "RIVEDAL Joshua": "rivedal-joshua",
    "RIVEMALE Alexandre": "rivemale-alexandre",
    "RIVENBARK Tyler": "rivenbark-tyler",
    "RIVER Sol": "river-sol",
    "RIVER Susan": "river-susan",
    "RIVER PEOPLE ": "river-people",
    "RIVER UN ": "river-un",
    "RIVERA Carmen": "rivera-carmen",
    "RIVERA Chris": "rivera-chris",
    "RIVERA Cliff": "rivera-cliff",
    "RIVERA Dale": "rivera-dale",
    "RIVERA Delilah": "rivera-delilah",
    "RIVERA Don Darryl": "rivera-don-darryl",
    "RIVERA Javier": "rivera-javier",
    "RIVERA Jose": "rivera-jose",
    "RIVERA Marika": "rivera-marika",
    "RIVERA Marisol Tirell": "rivera-marisol-tirell",
    "RIVERA Randi": "rivera-randi",
    "RIVERA Roger": "rivera-roger",
    "RIVERA Takeo": "rivera-takeo",
    "RIVERS Carmen": "rivers-carmen",
    "RIVERS Conrad Kent": "rivers-conrad-kent",
    "RIVERS Felicia A": "rivers-felicia-a",
    "RIVERS Gwen Pharis": "rivers-gwen-pharis",
    "RIVERS Harrison David": "rivers-harrison-david",
    "RIVERS Joan": "rivers-joan",
    "RIVERS Louis": "rivers-louis",
    "RIVERS Lucy": "rivers-lucy",
    "RIVERS Sam": "rivers-sam",
    "RIVERS Steven": "rivers-steven",
    "RIVERS Susan": "rivers-susan",
    "RIVETTE Murray J": "rivette-murray-j",
    "RIVIECCIO Carlo": "rivieccio-carlo",
    "RIVIERE Jean Loup": "riviere-jean-loup",
    "RIVKIN Meghan": "rivkin-meghan",
    "RIX Jonathan": "rix-jonathan",
    "RIXON Jenny": "rixon-jenny",
    "RIZK Joumana": "rizk-joumana",
    "RIZZI Tony": "rizzi-tony",
    "RIZZO Francesca": "rizzo-francesca",
    "RIZZO Gino": "rizzo-gino",
    "RIZZO Roberto": "rizzo-roberto",
    "RIZZOLO Joey": "rizzolo-joey"
  }
};