export default {
  "metadata": {
    "results": 1015,
    "timeStamp": "2025-12-05T21:30:31.572Z",
    "url": "https://www.doollee.com/PlaywrightsR/R_playwrights_m-r.php"
  },
  "authors": {
    "RNO Sung": "rno-sung",
    "ROACH Alma E": "roach-alma-e",
    "ROACH Barry": "roach-barry",
    "ROACH Eric": "roach-eric",
    "ROACH Freddie": "roach-freddie",
    "ROACH Gavin": "roach-gavin",
    "ROACH J Barry": "roach-j-barry",
    "ROACH Julian": "roach-julian",
    "ROACH Lois": "roach-lois",
    "ROACH Matt": "roach-matt",
    "ROACH Mike": "roach-mike",
    "ROACH Robert": "roach-robert",
    "ROACH Sally": "roach-sally",
    "ROACH William": "roach-william",
    "ROACHE Renee": "roache-renee",
    "ROAD Ella": "road-ella",
    "ROADSIDE THEATER ": "roadside-theater",
    "ROBAK Edward": "robok-edward",
    "ROBARTES Michael": "robartes-michael",
    "ROBBE-GRILLET Catherine": "robbe-grillet-catherine",
    "ROBBERTS Mark": "robberts-mark",
    "ROBBINS Carrie": "robbins-carrie",
    "ROBBINS Cate": "robbins-cate",
    "ROBBINS Glyn": "robbins-glyn",
    "ROBBINS Heidi": "robbins-heidi",
    "ROBBINS Jane Marla": "robbins-jane-marla",
    "ROBBINS Jennifer": "robbins-jennifer",
    "ROBBINS Jerome": "robbins-jerome",
    "ROBBINS Jerry": "robbins-jerry",
    "ROBBINS Ken": "robbins-ken",
    "ROBBINS Kenneth": "robbins-kenneth",
    "ROBBINS Lindy": "robbins-lindy",
    "ROBBINS Norman": "robbins-norman",
    "ROBBINS Pamela": "robbins-pamela",
    "ROBBINS R D": "robbins-r-d",
    "ROBBINS Regina": "robbins-regina",
    "ROBBINS Sandy": "robbins-sandy",
    "ROBBINS Ted": "robbins-ted",
    "ROBBINS Tim": "robbins-tim",
    "ROBBINS Todd": "robbins-todd",
    "ROBELEN Spencer": "robelen-spencer",
    "ROBENS Bill": "robens-bill",
    "ROBERSON Arthur": "roberson-arthur",
    "ROBERSON Blythe": "roberson-blythe",
    "ROBERSON Jeffery": "roberson-jeffery",
    "ROBERSON William": "roberson-william",
    "ROBERSTON B A": "roberston-b-a",
    "ROBERT Everett": "robert-everett",
    "ROBERT Lauren": "robert-lauren",
    "ROBERTS Adam": "roberts-adam",
    "ROBERTS Aled": "roberts-aled",
    "ROBERTS Alistair": "roberts-alistair",
    "ROBERTS Andy": "roberts-andy",
    "ROBERTS Arwel": "roberts-arwel",
    "ROBERTS Bea": "roberts-bea",
    "ROBERTS Belinda": "roberts-belinda",
    "ROBERTS Ben": "roberts-ben",
    "ROBERTS Billy": "roberts-billy",
    "ROBERTS Blake": "roberts-blake",
    "ROBERTS Bonnie": "roberts-bonnie",
    "ROBERTS Charlotte": "roberts-charlotte",
    "ROBERTS Christine": "roberts-christine",
    "ROBERTS Christopher G": "roberts-christopher-g",
    "ROBERTS Cyril": "roberts-cyril",
    "ROBERTS D": "roberts-d",
    "ROBERTS Dafydd Wyn": "roberts-dafydd-wyn",
    "ROBERTS Daniel": "roberts-daniel",
    "ROBERTS David": "roberts-david",
    "ROBERTS David (1)": "roberts-david-1",
    "ROBERTS Deb": "roberts-deb",
    "ROBERTS Dmae": "roberts-dmae",
    "ROBERTS Don": "roberts-don",
    "ROBERTS Dowd": "roberts-dowd",
    "ROBERTS Dyfan": "roberts-dyfan",
    "ROBERTS Elizabeth": "roberts-elizabeth",
    "ROBERTS Emlyn": "roberts-emlyn",
    "ROBERTS Emma C": "roberts-emma-c",
    "ROBERTS Eric": "roberts-eric",
    "ROBERTS Frank": "roberts-frank",
    "ROBERTS Fred": "roberts-fred",
    "ROBERTS G K": "roberts-g-k",
    "ROBERTS Gavin": "roberts-gavin",
    "ROBERTS Gillian": "roberts-gillian",
    "ROBERTS Glyn": "roberts-glyn",
    "ROBERTS Helen": "roberts-helen",
    "ROBERTS Hugh": "roberts-hugh",
    "ROBERTS Hywel": "roberts-hywel",
    "ROBERTS Jeff": "roberts-jeff",
    "ROBERTS Jennifer Lynne": "roberts-jennifer-lynne",
    "ROBERTS Jimmy": "roberts-jimmy",
    "ROBERTS John": "roberts-john",
    "ROBERTS John C Q": "roberts-john-c-q",
    "ROBERTS John Henry": "roberts-john-henry",
    "ROBERTS John-Luke": "roberts-john-luke",
    "ROBERTS Julian": "roberts-julian",
    "ROBERTS Justin": "roberts-justin",
    "ROBERTS Kat": "roberts-kat",
    "ROBERTS Keenan": "roberts-keenan",
    "ROBERTS Ken": "roberts-ken",
    "ROBERTS Kevin": "roberts-kevin",
    "ROBERTS Lavinia": "roberts-lavinia",
    "ROBERTS M Younger": "roberts-m-younger",
    "ROBERTS Maria": "roberts-maria",
    "ROBERTS Mark": "roberts-mark",
    "ROBERTS Martyn": "roberts-martyn",
    "ROBERTS Matt": "roberts-matt",
    "ROBERTS Meade": "roberts-meade",
    "ROBERTS Meg": "roberts-meg",
    "ROBERTS Michael": "roberts-michael",
    "ROBERTS Mike": "roberts-mike",
    "ROBERTS Nedra Pezold": "roberts-nedra-pezold",
    "ROBERTS Owen": "roberts-owen",
    "ROBERTS Pastor Keenan": "roberts-pastor-keenan",
    "ROBERTS Paul": "roberts-paul",
    "ROBERTS Peter": "roberts-peter",
    "ROBERTS Phoebe": "roberts-phoebe",
    "ROBERTS Rhoda": "roberts-rhoda",
    "ROBERTS Rick": "roberts-rick",
    "ROBERTS Robin": "roberts-robin",
    "ROBERTS Sam": "roberts-sam",
    "ROBERTS Simon": "roberts-simon",
    "ROBERTS Sophie": "roberts-sophie",
    "ROBERTS Victoria (1)": "roberts-victoria-1",
    "ROBERTS Victoria (2)": "roberts-victoria-2",
    "ROBERTS Victoria Taylor": "roberts-victoria-taylor",
    "ROBERTS Wayne": "roberts-wayne",
    "ROBERTS Wiliam Owen": "roberts-wiliam-owen",
    "ROBERTS Zoe": "roberts-zoe",
    "ROBERTSON A S": "robertson-a-s",
    "ROBERTSON Aaron": "robertson-aaron",
    "ROBERTSON Ali": "robertson-ali",
    "ROBERTSON Allen": "robertson-allen",
    "ROBERTSON Brian": "robertson-brian",
    "ROBERTSON Colin": "robertson-colin",
    "ROBERTSON Craig": "robertson-craig",
    "ROBERTSON David": "robertson-david",
    "ROBERTSON Edith Anne": "robertson-edith-anne",
    "ROBERTSON Ellen": "robertson-ellen",
    "ROBERTSON Finlay": "robertson-finlay",
    "ROBERTSON Gary": "robertson-gary",
    "ROBERTSON Gavin": "robertson-gavin",
    "ROBERTSON Geoff": "robertson-geoff",
    "ROBERTSON Gill": "robertson-gill",
    "ROBERTSON Gina": "robertson-gina",
    "ROBERTSON Ian": "robertson-ian",
    "ROBERTSON J": "robertson-j",
    "ROBERTSON Jackie": "robertson-jackie",
    "ROBERTSON James": "robertson-james",
    "ROBERTSON Jane": "robertson-jane",
    "ROBERTSON Joe": "robertson-joe",
    "ROBERTSON Jon": "robertson-jon",
    "ROBERTSON Jono": "robertson-jono",
    "ROBERTSON Kelso": "robertson-kelso",
    "ROBERTSON Kyndal": "robertson-kyndal",
    "ROBERTSON Lanie": "robertson-lanie",
    "ROBERTSON Mark": "robertson-mark",
    "ROBERTSON Marta": "robertson-marta",
    "ROBERTSON Owen": "robertson-owen",
    "ROBERTSON Patrick": "robertson-patrick",
    "ROBERTSON Robin": "robertson-robin",
    "ROBERTSON Sarah": "robertson-sarah",
    "ROBERTSON Shane K": "robertson-shane-k",
    "ROBERTSON Tim": "robertson-tim",
    "ROBERTSON Toby": "robertson-toby",
    "ROBERTSON Will": "robertson-will",
    "ROBERTSON JR George": "robertson-jr-george",
    "ROBERTSON JR H W": "robertson-jr-h-w",
    "ROBERTS-ORR Izzy": "roberts-orr-izzy",
    "ROBERTZ Andreas": "robertz-andreas",
    "ROBIC Greg": "robic-greg",
    "ROBIDEAU Nick": "robideau-nick",
    "ROBIDOUX Michel": "robidoux-michel",
    "ROBIN Jon": "robin-jon",
    "ROBIN Kate": "robin-kate",
    "ROBIN Leo": "robin-leo",
    "ROBIN Marc": "robin-marc",
    "ROBINET Karen": "robinet-karen",
    "ROBINETTE John": "robinette-john",
    "ROBINETTE Joseph": "robinette-joseph",
    "ROBINOV Kyra": "robinov-kyra",
    "ROBINS Brian": "robins-brian",
    "ROBINS Catherine": "robins-catherine",
    "ROBINS D": "robins-d",
    "ROBINS Danny": "robins-danny",
    "ROBINS Doug": "robins-doug",
    "ROBINS Elizabeth": "robins-elizabeth",
    "ROBINS J D": "robins-j-d",
    "ROBINS Jenn": "robins-jenn",
    "ROBINS Jeremy": "robins-jeremy",
    "ROBINS Matthew": "robins-matthew",
    "ROBINS Serena B": "robins-serena-b",
    "ROBINSON A Monde": "robinson-a-monde",
    "ROBINSON Adam Z": "robinson-adam-z",
    "ROBINSON Alan": "robinson-alan",
    "ROBINSON Alice": "robinson-alice",
    "ROBINSON Andy": "robinson-andy",
    "ROBINSON Ashley Denise": "robinson-ashley-denise",
    "ROBINSON Barbara": "robinson-barbara",
    "ROBINSON Bec": "robinson-bec",
    "ROBINSON Ben": "robinson-ben",
    "ROBINSON Bertrand": "robinson-bertrand",
    "ROBINSON Betsy": "robinson-betsy",
    "ROBINSON Brenda": "robinson-brenda",
    "ROBINSON Brooke": "robinson-brooke",
    "ROBINSON Bruce J": "robinson-bruce-j",
    "ROBINSON C T": "robinson-c-t",
    "ROBINSON Carlon Campbell": "robinson-carlon-campbell",
    "ROBINSON Charles": "robinson-charles",
    "ROBINSON Chris": "robinson-chris",
    "ROBINSON Christina": "robinson-christina",
    "ROBINSON Cynthia G": "robinson-cynthia-g",
    "ROBINSON Daniel Marchese": "robinson-daniel-marchese",
    "ROBINSON David": "robinson-david",
    "ROBINSON David (1)": "robinson-david-1",
    "ROBINSON David Mitchell": "robinson-david-mitchell",
    "ROBINSON Dee": "robinson-dee",
    "ROBINSON Dennis": "robinson-dennis",
    "ROBINSON Drue": "robinson-drue",
    "ROBINSON Emma": "robinson-emma",
    "ROBINSON Fred": "robinson-fred",
    "ROBINSON Gawen": "robinson-gawen",
    "ROBINSON Giovanna": "robinson-giovanna",
    "ROBINSON Ian": "robinson-ian",
    "ROBINSON J E": "robinson-j-e",
    "ROBINSON J R": "robinson-j-r",
    "ROBINSON James": "robinson-james",
    "ROBINSON Jay": "robinson-jay",
    "ROBINSON Jean": "robinson-jean",
    "ROBINSON Jim": "robinson-jim",
    "ROBINSON John": "robinson-john",
    "ROBINSON Joshua": "robinson-joshua",
    "ROBINSON Judith": "robinson-judith",
    "ROBINSON Keith": "robinson-keith",
    "ROBINSON Ken": "robinson-ken",
    "ROBINSON Kristyn": "robinson-kristyn",
    "ROBINSON Lennox": "robinson-lennox",
    "ROBINSON Lindsey": "robinson-lindsey",
    "ROBINSON M": "robinson-m",
    "ROBINSON M Lynda": "robinson-m-lynda",
    "ROBINSON Mansel": "robinson-mansel",
    "ROBINSON Marc ": "robinson-marc",
    "ROBINSON Martha": "robinson-martha",
    "ROBINSON Matt": "robinson-matt",
    "ROBINSON Matthew": "robinson-matthew",
    "ROBINSON Meg": "robinson-meg",
    "ROBINSON Melvyn S": "robinson-melvyn-s",
    "ROBINSON Michael": "robinson-michael",
    "ROBINSON Michael (1)": "robinson-michael-1",
    "ROBINSON Muriel": "robinson-muriel",
    "ROBINSON Noel": "robinson-noel",
    "ROBINSON Pat D": "robinson-pat-d",
    "ROBINSON Patricia": "robinson-patricia",
    "ROBINSON Percy": "robinson-percy",
    "ROBINSON Peter": "robinson-peter",
    "ROBINSON Phyllis": "robinson-phyllis",
    "ROBINSON Piers Chater": "robinson-piers-chater",
    "ROBINSON R T": "robinson-r-t",
    "ROBINSON Rebecca": "robinson-rebecca",
    "ROBINSON Renee": "robinson-renee",
    "ROBINSON Richard": "robinson-richard",
    "ROBINSON Rick": "robinson-rick",
    "ROBINSON Rony": "robinson-rony",
    "ROBINSON Ruth": "robinson-ruth",
    "ROBINSON S Garrett": "robinson-s-garrett",
    "ROBINSON Sancia": "robinson-sancia",
    "ROBINSON Scott": "robinson-scott",
    "ROBINSON Stacey Karen": "robinson-stacey-karen",
    "ROBINSON Terrell": "robinson-terrell",
    "ROBINSON Thirzie": "robinson-thirzie",
    "ROBINSON Timothy Edward": "robinson-timothy-edward",
    "ROBINSON Tobias": "robinson-tobias",
    "ROBINSON Tyrone": "robinson-tyrone",
    "ROBINSON William": "robinson-william",
    "ROBINSONGRAHAM Rony": "robinsongraham-rony",
    "ROBISON Blake": "robison-blake",
    "ROBISON David V": "robison-david-v",
    "ROBLAN Alexis": "roblan-alexis",
    "ROBLEDO Jamie": "robledo-jamie",
    "ROBLES Humberto": "robles-humberto",
    "ROBLES Jessie": "robles-jessie",
    "ROBOFF Annie": "roboff-annie",
    "ROBSON Cheryl": "robson-cheryl",
    "ROBSON David": "robson-david",
    "ROBSON Diana": "robson-diana",
    "ROBSON Ed": "robson-ed",
    "ROBSON Elizabeth": "robson-elizabeth",
    "ROBSON Garry": "robson-garry",
    "ROBSON Heather": "robson-heather",
    "ROBSON James": "robson-james",
    "ROBSON M": "robson-m",
    "ROBSON Mark": "robson-mark",
    "ROBSON Michael": "robson-michael",
    "ROBSON Robert": "robson-robert",
    "ROBSON Robert (1)": "robson-robert-1",
    "ROBSON Simon": "robson-simon",
    "ROBSON-STUART Kate": "robson-stuart-kate",
    "ROBUNETTE Joseph": "robunette-joseph",
    "ROBY David": "roby-david",
    "ROBY John": "roby-john",
    "ROCA MariStella": "roca-maristella",
    "ROCAMORA Carol": "rocamora-carol",
    "ROCCO Karen": "rocco-karen",
    "ROCCO Vito": "rocco-vito",
    "ROCES Alejandro": "roces-alejandro",
    "ROCHA Renato": "rocha-renato",
    "ROCHA Sueli": "rocha-sueli",
    "ROCHANAHUSDIN Siwaraya": "rochanahusdin-siwaraya",
    "ROCHE Billy": "roche-billy",
    "ROCHE David": "roche-david",
    "ROCHE Dominic": "roche-dominic",
    "ROCHE Lorcan": "roche-lorcan",
    "ROCHE Louise": "roche-louise",
    "ROCHE Marcus": "roche-marcus",
    "ROCHE Martin": "roche-martin",
    "ROCHE Paul": "roche-paul",
    "ROCHE Stewart": "roche-stewart",
    "ROCHEFORT Damon": "rochefort-damon",
    "ROCHEL Allain": "rochel-allain",
    "ROCHLIN Brian E": "rochlin-brian-e",
    "ROCHON Anita": "rochon-anita",
    "ROCK Andrew": "rock-andrew",
    "ROCK Michael D": "rock-michael-d",
    "ROCKATANSKY Max": "rockatansky-max",
    "ROCKE William": "rocke-william",
    "ROCKEFELLER Jonathan": "rockefeller-jonathan",
    "ROCKER Pam": "rocker-pam",
    "ROCKETT James": "rockett-james",
    "ROCKEY Jeffery G": "rockey-jeffery-g",
    "ROCK-N-ROLLA Lola": "rock-n-rolla-lola",
    "ROCKWELL Eric": "rockwell-eric",
    "ROCKWELL Jeffrey": "rockwell-jeffrey",
    "ROCKWELL Juanita": "rockwell-juanita",
    "ROCKWELL Penny": "rockwell-penny",
    "ROCKWELL Rachel": "rockwell-rachel",
    "ROCKWELL Steve": "rockwell-steve",
    "ROCKWELL Thomas": "rockwell-thomas",
    "ROCKWOOD Glen": "rockwood-glen",
    "ROCKWOOD Jerry": "rockwood-jerry",
    "ROCKYMORE Maxie": "rockymore-maxie",
    "RODALE J I": "rodale-j-i",
    "RODBRO Ashley": "rodbro-ashley",
    "RODDA Peter": "rodda-peter",
    "RODDEN Katherine": "rodden-katherine",
    "RODDEN Lindsay": "rodden-lindsay",
    "RODDEN Rebecca": "rodden-rebecca",
    "RODDICK Elizabeth": "roddick-elizabeth",
    "RODEL Angela": "rodel-angela",
    "RODEN Shirlie": "roden-shirlie",
    "RODEN Tom": "roden-tom",
    "RODENBORN Marcy": "rodenborn-marcy",
    "RODENBURG Patsy": "rodenburg-patsy",
    "RODENWALD Heidi": "rodenwald-heidi",
    "RODERICK D B": "roderick-d-b",
    "RODERICK Michael": "roderick-michael",
    "RODERICK Ray": "roderick-ray",
    "RODEWALD Heidi": "rodewald-heidi",
    "RODEWALD Stew": "rodewald-stew",
    "RODGER Cruden": "rodger-cruden",
    "RODGER Douglas": "rodger-douglas",
    "RODGER Hannah": "rodger-hannah",
    "RODGER Victor": "rodger-victor",
    "RODGERS Bob": "rodgers-bob",
    "RODGERS Constance": "rodgers-constance",
    "RODGERS Don": "rodgers-don",
    "RODGERS James W": "rodgers-james-w",
    "RODGERS John": "rodgers-john",
    "RODGERS Mary": "rodgers-mary",
    "RODGERS Megan": "rodgers-megan",
    "RODGERS Ralph G": "rodgers-ralph-g",
    "RODGERS Richard": "rodgers-richard",
    "RODGERS Steve": "rodgers-steve",
    "RODI Robert": "rodi-robert",
    "RODIMOS Dimitri": "rodimos-dimitri",
    "RODIN Toby": "rodin-toby",
    "RODIONOV Alexander": "rodionov-alexander",
    "RODKIN Rs": "rodkin-rs",
    "RODLAND Jeffrey": "rodland-jeffrey",
    "RODNEY Carina": "rodney-carina",
    "RODOOR Oda": "rodoor-oda",
    "RODRIGUES Bella": "rodrigues-bella",
    "RODRIGUES Joffre": "rodrigues-joffre",
    "RODRIGUES Nelson": "rodrigues-nelson",
    "RODRIGUES Tiago": "rodrigues-tiago",
    "RODRIGUEZ Adrian": "rodriguez-adrian",
    "RODRIGUEZ Andres": "rodriguez-andres",
    "RODRIGUEZ Carlos": "rodriguez-carlos",
    "RODRIGUEZ Christopher": "rodriguez-christopher",
    "RODRIGUEZ Dailyn": "rodriguez-dailyn",
    "RODRIGUEZ Daniel": "rodriguez-daniel",
    "RODRIGUEZ David": "rodriguez-david",
    "RODRIGUEZ David E": "rodriguez-david-e",
    "RODRIGUEZ David Solomon": "rodriguez-david-solomon",
    "RODRIGUEZ Diane": "rodriguez-diane",
    "RODRIGUEZ Emilio": "rodriguez-emilio",
    "RODRIGUEZ Jamel": "rodriguez-jamel",
    "RODRIGUEZ Leo I": "rodriguez-leo-i",
    "RODRIGUEZ Lynda": "rodriguez-lynda",
    "RODRIGUEZ Marco Antonio": "rodriguez-marco-antonio",
    "RODRIGUEZ Maria Therese": "rodriguez-maria-therese",
    "RODRIGUEZ Ozvaldo": "rodriguez-ozvaldo",
    "RODRIGUEZ Percy": "rodriguez-percy",
    "RODRIGUEZ Raquel M": "rodriguez-raquel-m",
    "RODRIGUEZ Robin": "rodriguez-robin",
    "RODRIGUEZ Yolanda": "rodriguez-yolanda",
    "RODRIGUEZ Yubelky": "rodriguez-yubelky",
    "RODRIGUEZ-BADENDYCK Cynthia": "rodriguez-badendyck-cynthia",
    "RODWIN David": "rodwin-david",
    "RODWIN Phelim": "rodwin-phelim",
    "ROE Alex": "roe-alex",
    "ROE Billie": "roe-billie",
    "ROE Hannah": "roe-hannah",
    "ROE Owen": "roe-owen",
    "ROE Tom": "roe-tom",
    "ROEDER William": "roeder-william",
    "ROEL Frank": "roel-frank",
    "ROEST Paul Vander": "roest-paul-vander",
    "ROETS Jo": "roets-jo",
    "ROETZHEIM William": "roetzheim-william",
    "ROFES Eric": "rofes-eric",
    "ROFFEY Jack": "roffey-jack",
    "ROGAL Stan": "rogal-stan",
    "ROGALUS Paul": "rogalus-paul",
    "ROGAN Paul": "rogan-paul",
    "ROGEL Randy": "rogel-randy",
    "ROGER-LACAN Fabrice": "roger-lacan-fabrice",
    "ROGERS Aaron": "rogers-aaron",
    "ROGERS Ashley": "rogers-ashley",
    "ROGERS Ashley Lauren": "rogers-ashley-lauren",
    "ROGERS Ashley Michael": "rogers-ashley-michael",
    "ROGERS Betty": "rogers-betty",
    "ROGERS Brad": "rogers-brad",
    "ROGERS Brian": "rogers-brian",
    "ROGERS Catherine": "rogers-catherine",
    "ROGERS Cathy": "rogers-cathy",
    "ROGERS Corinna": "rogers-corinna",
    "ROGERS Danny": "rogers-danny",
    "ROGERS David": "rogers-david",
    "ROGERS David (2)": "rogers-david-2",
    "ROGERS Dean": "rogers-dean",
    "ROGERS Demelza": "rogers-demelza",
    "ROGERS Dulcy": "rogers-dulcy",
    "ROGERS Emily Brauer": "rogers-emily-brauer",
    "ROGERS Frank": "rogers-frank",
    "ROGERS Gemma": "rogers-gemma",
    "ROGERS Heather Lee": "rogers-heather-lee",
    "ROGERS Howard Emmett": "rogers-howard-emmett",
    "ROGERS J T": "rogers-j-t",
    "ROGERS James": "rogers-james",
    "ROGERS Jennifer": "rogers-jennifer",
    "ROGERS Jenny": "rogers-jenny",
    "ROGERS Joe": "rogers-joe",
    "ROGERS John": "rogers-john",
    "ROGERS June Walker": "rogers-june-walker",
    "ROGERS Kathleen": "rogers-kathleen",
    "ROGERS Leonard": "rogers-leonard",
    "ROGERS Lon E": "rogers-lon-e",
    "ROGERS Mac": "rogers-mac",
    "ROGERS Mark": "rogers-mark",
    "ROGERS Matt": "rogers-matt",
    "ROGERS Michael": "rogers-michael",
    "ROGERS Michael (1)": "rogers-michael-1",
    "ROGERS Rodney Lee": "rogers-rodney-lee",
    "ROGERS Rosie": "rogers-rosie",
    "ROGERS Sarah Jane": "rogers-sarah-jane",
    "ROGERS Shannon": "rogers-shannon",
    "ROGERS Stuart": "rogers-stuart",
    "ROGERS Susan": "rogers-susan",
    "ROGERS Terry": "rogers-terry",
    "ROGERS Thomas F": "rogers-thomas-f",
    "ROGERSON P B": "rogerson-p-b",
    "ROGGENKAMP Karen": "roggenkamp-karen",
    "ROGIN Deborah": "rogin-deborah",
    "ROGOFF Lynn": "rogoff-lynn",
    "ROGOFF Tamar": "rogoff-tamar",
    "ROGOSIN Roy M": "rogosin-roy-m",
    "ROGOW Zack": "rogow-zack",
    "ROGOZHINA Nadezhda": "rogozhina-nadezhda",
    "ROGUE THEATRE COMPANY ": "rogue-theatre-company",
    "ROHD Michael": "rohd-michael",
    "ROHDE Hege": "rohde-hege",
    "ROHDE Jokum": "rohde-jokum",
    "ROHDE Mary": "rohde-mary",
    "ROHMER Bret": "rohmer-bret",
    "ROHN Andrew": "rohn-andrew",
    "ROHRICK Jeff": "rohrick-jeff",
    "ROHRKEMPER John": "rohrkemper-john",
    "ROHRMAN Laura": "rohrman-laura",
    "ROISMAN Hanna M": "roisman-hanna-m",
    "ROISMAN Lois": "roisman-lois",
    "ROJAS Carlos E": "rojas-carlos-e",
    "ROJAS Felix": "rojas-felix",
    "ROJAS Francisco": "rojas-francisco",
    "ROJAS Julian": "rojas-julian",
    "ROJO Pedro Elgardo": "rojo-pedro-elgardo",
    "ROKICKI Robert": "rokicki-robert",
    "ROLAND Alan": "roland-alan",
    "ROLAND Betty": "roland-betty",
    "ROLAND Claude": "roland-claude",
    "ROLAND Joe": "roland-joe",
    "ROLAND Matthew Dryden": "roland-matthew-dryden",
    "ROLAND-ADAMS Gordon": "roland-adams-gordon",
    "ROLDAN JR Jose": "roldan-jr-jose",
    "ROLFE Phil": "rolfe-phil",
    "ROLLAND R": "rolland-r",
    "ROLLASON Emma": "rollason-emma",
    "ROLLE Kincaid": "rolle-kincaid",
    "ROLLESTON James": "rolleston-james",
    "ROLLING Steve": "rolling-steve",
    "ROLLINS Bridie": "rollins-bridie",
    "ROLLINS Bryant": "rollins-bryant",
    "ROLLINS Doug": "rollins-doug",
    "ROLLINS Hillary": "rollins-hillary",
    "ROLLINS Jack": "rollins-jack",
    "ROLLINS Joshua": "rollins-joshua",
    "ROLLINS Lisa Marie": "rollins-lisa-marie",
    "ROLLS Christopher": "rolls-christopher",
    "ROLLS Peter": "rolls-peter",
    "ROLOFF Michael": "roloff-michael",
    "ROLON Rosalba": "rolon-rosalba",
    "ROLSTON Adam": "rolston-adam",
    "ROLSTON Mark": "rolston-mark",
    "ROLVAAG Nils": "rolvaag-nils",
    "ROMAGNOLI Richard": "romagnoli-richard",
    "ROMAINE George": "romaine-george",
    "ROMAINE Jenny": "romaine-jenny",
    "ROMAINS Jules": "romains-jules",
    "ROMAN Arnie": "roman-arnie",
    "ROMAN Denise": "roman-denise",
    "ROMAN Frank": "roman-frank",
    "ROMAN J Anthony": "roman-j-anthony",
    "ROMAN Lawrence": "roman-lawrence",
    "ROMAN Mary": "roman-mary",
    "ROMAN Shay": "roman-shay",
    "ROMANES Alexa": "romanes-alexa",
    "ROMANO David J": "romano-david-j",
    "ROMANO Gail": "romano-gail",
    "ROMANO Gena": "romano-gena",
    "ROMANO Lawrence John": "romano-lawrence-john",
    "ROMANO Noelle": "romano-noelle",
    "ROMANOVSKY Ron": "romanovsky-ron",
    "ROMANS Bruce Marshall": "romans-bruce-marshall",
    "ROMANSKA Magda": "romanska-magda",
    "ROMANUS Amy": "romanus-amy",
    "ROMAY Diego": "romay-diego",
    "ROMBERGER Judy": "romberger-judy",
    "ROMCEVIC Nebojsa": "romcevic-nebojsa",
    "ROME Harold": "rome-harold",
    "ROMELE Eric": "romele-eric",
    "ROMEO Lia": "romeo-lia",
    "ROMER Marcus": "romer-marcus",
    "ROMERIL John": "romeril-john",
    "ROMERO Concha": "romero-concha",
    "ROMERO Elaine": "romero-elaine",
    "ROMERO Greg": "romero-greg",
    "ROMERO Jo": "romero-jo",
    "ROMERO Juliet Gilkes": "romero-juliet-gilkes",
    "ROMERO Mandy": "romero-mandy",
    "ROMERO Mia": "romero-mia",
    "ROMMA Sophia": "romma-sophia",
    "ROMOFF Anne Louise": "romoff-anne-louise",
    "RON Liat": "ron-liat",
    "RONALD Al": "ronald-al",
    "RONALD Rolanda": "ronald-rolanda",
    "RONALD Terry": "ronald-terry",
    "RONALDO Danny": "ronaldo-danny",
    "RONALDO David": "ronaldo-david",
    "RONAN John J": "ronan-john-j",
    "RONCONI Amanda": "ronconi-amanda",
    "RONDER Jack": "ronder-jack",
    "RONDER Tanya": "ronder-tanya",
    "RONIN Yael": "ronin-yael",
    "RONINSON Andy": "roninson-andy",
    "RONINSON Lennox": "roninson-lennox",
    "RONNELL Anne": "ronnell-anne",
    "RONNIE Julian": "ronnie-julian",
    "RONZONI Michaela": "ronzoni-michaela",
    "ROODNER Uri": "roodner-uri",
    "ROOFTHOOFT Dirk": "roofthooft-dirk",
    "ROOK Matthew": "rook-matthew",
    "ROOKE Alison": "rooke-alison",
    "ROOKE Leon": "rooke-leon",
    "ROOKE Michele": "rooke-michele",
    "ROOKS Paul": "rooks-paul",
    "ROOM Engine": "room-engine",
    "ROONEY Caroline": "rooney-caroline",
    "ROONEY Daniel": "rooney-daniel",
    "ROONEY Eamon": "rooney-eamon",
    "ROONEY John": "rooney-john",
    "ROONEY John P": "rooney-john-p",
    "ROONEY Tom": "rooney-tom",
    "ROOS Audrey": "roos-audrey",
    "ROOS Danielle": "roos-danielle",
    "ROOS Joanna": "roos-joanna",
    "ROOS Mark": "roos-mark",
    "ROOS William": "roos-william",
    "ROOSE Chris": "roose-chris",
    "ROOSE-EVANS James": "roose-evans-james",
    "ROOSEN Adelheid": "roosen-adelheid",
    "ROOST Garry": "roost-garry",
    "ROOT Lynn": "root-lynn",
    "ROOT Thomi": "root-thomi",
    "ROOTSAERT Cathleen": "rootsaert-cathleen",
    "ROPER Amelia": "roper-amelia",
    "ROPER Carol": "roper-carol",
    "ROPER Lizzie": "roper-lizzie",
    "ROPER Rebecca": "roper-rebecca",
    "ROPER Tony": "roper-tony",
    "ROQUES Richard": "roques-richard",
    "RORKE Julia": "rorke-julia",
    "ROSA Armando Nascimento": "rosa-armando-nascimento",
    "ROSA Dennis": "rosa-dennis",
    "ROSAGUT George": "rosagut-george",
    "ROSARIO Cathy": "rosario-cathy",
    "ROSATI Mark": "rosati-mark",
    "ROSBE Erica": "rosbe-erica",
    "ROSE Alison": "rose-alison",
    "ROSE Arianna": "rose-arianna",
    "ROSE Bashi": "rose-bashi",
    "ROSE Beverley": "rose-beverley",
    "ROSE Billy": "rose-billy",
    "ROSE Cassandra": "rose-cassandra",
    "ROSE Chuck": "rose-chuck",
    "ROSE Colin": "rose-colin",
    "ROSE Dawn": "rose-dawn",
    "ROSE Dilys": "rose-dilys",
    "ROSE Elizabeth": "rose-elizabeth",
    "ROSE Ellie": "rose-ellie",
    "ROSE Eric": "rose-eric",
    "ROSE Erika": "rose-erika",
    "ROSE Euan": "rose-euan",
    "ROSE Graeme": "rose-graeme",
    "ROSE Ian": "rose-ian",
    "ROSE Iris": "rose-iris",
    "ROSE J B": "rose-j-b",
    "ROSE James": "rose-james",
    "ROSE Julie": "rose-julie",
    "ROSE Kristin": "rose-kristin",
    "ROSE L Arthur": "rose-l-arthur",
    "ROSE Larson": "rose-larson",
    "ROSE Laura": "rose-laura",
    "ROSE Lesley Anne": "rose-lesley-anne",
    "ROSE Louisa": "rose-louisa",
    "ROSE Maggie": "rose-maggie",
    "ROSE Michael A": "rose-michael-a",
    "ROSE Morgan": "rose-morgan",
    "ROSE Peter": "rose-peter",
    "ROSE Peter (1)": "rose-peter-1",
    "ROSE Philip": "rose-philip",
    "ROSE Ralph": "rose-ralph",
    "ROSE Reginald": "rose-reginald",
    "ROSE Richard": "rose-richard",
    "ROSE Richard S": "rose-richard-s",
    "ROSE Robert": "rose-robert",
    "ROSE Ron": "rose-ron",
    "ROSE Sophie": "rose-sophie",
    "ROSE Stacey": "rose-stacey",
    "ROSE Tamara": "rose-tamara",
    "ROSE Tony": "rose-tony",
    "ROSE Virginia Jane": "rose-virginia-jane",
    "ROSEBA Lali": "roseba-lali",
    "ROSEBROCK Abby": "rosebrock-abby",
    "ROSEBY Paul": "roseby-paul",
    "ROSELL Xavier Rodriguez": "rosell-xavier-rodriguez",
    "ROSEMBLUM Joshua": "rosemblum-joshua",
    "ROSEN Adam": "rosen-adam",
    "ROSEN Allen": "rosen-allen",
    "ROSEN Bob": "rosen-bob",
    "ROSEN Dan": "rosen-dan",
    "ROSEN David": "rosen-david",
    "ROSEN Eric": "rosen-eric",
    "ROSEN Gloria": "rosen-gloria",
    "ROSEN Hanoch": "rosen-hanoch",
    "ROSEN Itmar": "rosen-itmar",
    "ROSEN Lawrence": "rosen-lawrence",
    "ROSEN Leon": "rosen-leon",
    "ROSEN Louis": "rosen-louis",
    "ROSEN Lynn": "rosen-lynn",
    "ROSEN Michael": "rosen-michael",
    "ROSEN Moe": "rosen-moe",
    "ROSEN Nathan": "rosen-nathan",
    "ROSEN Ruti": "rosen-ruti",
    "ROSEN Sam": "rosen-sam",
    "ROSEN Seymour M": "rosen-seymour-m",
    "ROSEN Sheldon": "rosen-sheldon",
    "ROSEN Steve": "rosen-steve",
    "ROSEN Sybil": "rosen-sybil",
    "ROSENBERG Andrew": "rosenberg-andrew",
    "ROSENBERG David": "rosenberg-david",
    "ROSENBERG Edgar": "rosenberg-edgar",
    "ROSENBERG Hollie": "rosenberg-hollie",
    "ROSENBERG Irene": "rosenberg-irene",
    "ROSENBERG James L": "rosenberg-james-l",
    "ROSENBERG Lynne": "rosenberg-lynne",
    "ROSENBERG Sam": "rosenberg-sam",
    "ROSENBLATT Julia B": "rosenblatt-julia-b",
    "ROSENBLATT Mark": "rosenblatt-mark",
    "ROSENBLATT Roger": "rosenblatt-roger",
    "ROSENBLUM Aaron": "rosenblum-aaron",
    "ROSENBLUM Joshua": "rosenblum-joshua",
    "ROSENBLUM Robert": "rosenblum-robert",
    "ROSENBURG Dave": "rosenburg-dave",
    "ROSENBURG Irene": "rosenburg-irene",
    "ROSENBURG Maurice": "rosenburg-maurice",
    "ROSENDORF Andrew": "rosendorf-andrew",
    "ROSENDORF Andrew L": "rosendorf-andrew-l",
    "ROSENDUFT Raimy Nurit": "rosenduft-raimy-nurit",
    "ROSENER George": "rosener-george",
    "ROSENFELD Jackie": "rosenfeld-jackie",
    "ROSENFELD Jessica": "rosenfeld-jessica",
    "ROSENFELD Julian": "rosenfeld-julian",
    "ROSENFELD Luanne Aronen": "rosenfeld-luanne-aronen",
    "ROSENFELD Seth Zvi": "rosenfeld-seth-zvi",
    "ROSENFELD Sydney": "rosenfeld-sydney",
    "ROSENFIELD Andrea": "rosenfield-andrea",
    "ROSENFIELD Ben": "rosenfield-ben",
    "ROSENFIELD Bill": "rosenfield-bill",
    "ROSENFIELD James": "rosenfield-james",
    "ROSENGREN Elizabeth": "rosengren-elizabeth",
    "ROSENSTEEL Christine": "rosensteel-christine",
    "ROSENSTOCK Gregory": "rosenstock-gregory",
    "ROSENSTOCK Kim": "rosenstock-kim",
    "ROSENSTOCK Milton": "rosenstock-milton",
    "ROSENSWEIG Harry": "rosensweig-harry",
    "ROSENTHAL Amy": "rosenthal-amy",
    "ROSENTHAL Andrew": "rosenthal-andrew",
    "ROSENTHAL Ben": "rosenthal-ben",
    "ROSENTHAL David S": "rosenthal-david-s",
    "ROSENTHAL Jack": "rosenthal-jack",
    "ROSENTHAL Lisa": "rosenthal-lisa",
    "ROSENTHAL Lucy": "rosenthal-lucy",
    "ROSENTHAL Mark E": "rosenthal-mark-e",
    "ROSENTHAL Mark Sam": "rosenthal-mark-sam",
    "ROSENTHAL Mason": "rosenthal-mason",
    "ROSENTHAL Pat": "rosenthal-pat",
    "ROSENTHAL Rachel": "rosenthal-rachel",
    "ROSENTHAL Tom": "rosenthal-tom",
    "ROSENTHAL Vanessa": "rosenthal-vanessa",
    "ROSENTHALL Andrew": "rosenthall-andrew",
    "ROSENTHAN Amy": "rosenthan-amy",
    "ROSENVINGE Annika": "rosenvinge-annika",
    "ROSENWINKEL Mark": "rosenwinkel-mark",
    "ROSER I PUIG Montserrat": "roser-i-puig-montserrat",
    "ROSICA Thomas": "rosica-thomas",
    "ROSICH Marc": "rosich-marc",
    "ROSIE George": "rosie-george",
    "ROSIELLO Rob": "rosiello-rob",
    "ROSIER Mel": "rosier-mel",
    "ROSIN Jordan": "rosin-jordan",
    "ROSIN Lindsey": "rosin-lindsey",
    "ROSIVACH Vincent I": "rosivach-vincent-i",
    "ROSKE Earl T": "roske-earl-t",
    "ROSLER Larry": "rosler-larry",
    "ROSLYN Lucy": "roslyn-lucy",
    "ROSOMAN Emma": "rosoman-emma",
    "ROSS Aden": "ross-aden",
    "ROSS Adrian": "ross-adrian",
    "ROSS Amelia": "ross-amelia",
    "ROSS Andrew Steven": "ross-andrew-steven",
    "ROSS Andy": "ross-andy",
    "ROSS Anita": "ross-anita",
    "ROSS Anna": "ross-anna",
    "ROSS Brad": "ross-brad",
    "ROSS Caroline": "ross-caroline",
    "ROSS Casey": "ross-casey",
    "ROSS Charles": "ross-charles",
    "ROSS Charles (1)": "ross-charles-1",
    "ROSS Charles (2)": "ross-charles-2",
    "ROSS Corinne": "ross-corinne",
    "ROSS D Campbell": "ross-d-campbell",
    "ROSS Dina": "ross-dina",
    "ROSS Donald": "ross-donald",
    "ROSS Fiona": "ross-fiona",
    "ROSS Gary Earl": "ross-gary-earl",
    "ROSS George": "ross-george",
    "ROSS Ian": "ross-ian",
    "ROSS James F": "ross-james-f",
    "ROSS Jerry": "ross-jerry",
    "ROSS John M": "ross-john-m",
    "ROSS Jonathan Adam": "ross-jonathan-adam",
    "ROSS Jonathan Todd": "ross-jonathan-todd",
    "ROSS Jordan": "ross-jordan",
    "ROSS Judith": "ross-judith",
    "ROSS Kathleen": "ross-kathleen",
    "ROSS Kenneth": "ross-kenneth",
    "ROSS Kenneth G": "ross-kenneth-g",
    "ROSS Kenneth N": "ross-kenneth-n",
    "ROSS Lally": "ross-lally",
    "ROSS Laura": "ross-laura",
    "ROSS Laurence": "ross-laurence",
    "ROSS Lesley": "ross-lesley",
    "ROSS Lisette Lecat": "ross-lisette-lecat",
    "ROSS Maggie": "ross-maggie",
    "ROSS Mark": "ross-mark",
    "ROSS Martha": "ross-martha",
    "ROSS Martin": "ross-martin",
    "ROSS Marty": "ross-marty",
    "ROSS Melissa": "ross-melissa",
    "ROSS Merry": "ross-merry",
    "ROSS Michael": "ross-michael",
    "ROSS Michael (1)": "ross-michael-1",
    "ROSS Monica Long": "ross-monica-long",
    "ROSS Murray": "ross-murray",
    "ROSS Nadia": "ross-nadia",
    "ROSS Nan": "ross-nan",
    "ROSS Patricia": "ross-patricia",
    "ROSS Raymond": "ross-raymond",
    "ROSS Ricky": "ross-ricky",
    "ROSS Robert": "ross-robert",
    "ROSS Robert S": "ross-robert-s",
    "ROSS Sharon Houck": "ross-sharon-houck",
    "ROSS Sid": "ross-sid",
    "ROSS Stan": "ross-stan",
    "ROSS Stella": "ross-stella",
    "ROSS Stuart": "ross-stuart",
    "ROSS Tana": "ross-tana",
    "ROSS Tasha M": "ross-tasha-m",
    "ROSS Tom": "ross-tom",
    "ROSS W E Dan": "ross-w-e-dan",
    "ROSS Yana": "ross-yana",
    "ROSSELSON Leon": "rosselson-leon",
    "ROSSER Austin": "rosser-austin",
    "ROSSER Peter": "rosser-peter",
    "ROSSER Tim ": "rosser-tim",
    "ROSSETT Alan": "rossett-alan",
    "ROSSI Carl A": "rossi-carl-a",
    "ROSSI Dana": "rossi-dana",
    "ROSSI Emily E": "rossi-emily-e",
    "ROSSI johnmichael": "rossi-johnmichael",
    "ROSSI Rhett": "rossi-rhett",
    "ROSSI Vittorio": "rossi-vittorio",
    "ROSSINI Emanuella": "rossini-emanuella",
    "ROSSMER David": "rossmer-david",
    "ROSSODI SAN SECONDO Pier Maria": "rossodi-san-secondo-pier-maria",
    "ROSS-SMITH Christopher": "ross-smith-christopher",
    "ROSS-WILLIAMS Joseph": "ross-williams-joseph",
    "ROST Leo": "rost-leo",
    "ROSTAND Edmond": "rostand-edmond",
    "ROSTEN Norman": "rosten-norman",
    "ROSTRON Bryan": "rostron-bryan",
    "ROSWITHA ": "roswitha",
    "ROSZAK Theodore": "roszak-theodore",
    "ROSZCZEDA Katarzyna": "roszczeda-katarzyna",
    "ROTELLA Alexander": "rotella-alexander",
    "ROTH Andrew Douglas": "roth-andrew-douglas",
    "ROTH Andy": "roth-andy",
    "ROTH Ari": "roth-ari",
    "ROTH Beatrice": "roth-beatrice",
    "ROTH Bernard": "roth-bernard",
    "ROTH Dan": "roth-dan",
    "ROTH Dieter": "roth-dieter",
    "ROTH Elliot": "roth-elliot",
    "ROTH Frederike": "roth-frederike",
    "ROTH J": "roth-j",
    "ROTH Julia": "roth-julia",
    "ROTH Lauren": "roth-lauren",
    "ROTH Lisa": "roth-lisa",
    "ROTH Mark J": "roth-mark-j",
    "ROTH Peter": "roth-peter",
    "ROTH Robbie": "roth-robbie",
    "ROTH Robert": "roth-robert",
    "ROTH Rudi": "roth-rudi",
    "ROTH S J": "roth-s-j",
    "ROTH Susan Austin": "roth-susan-austin",
    "ROTHAMMER Jean": "rothammer-jean",
    "ROTHBART Brad": "rothbart-brad",
    "ROTHBART Davy": "rothbart-davy",
    "ROTHE Jodi": "rothe-jodi",
    "ROTHENBERG Dan": "rothenberg-dan",
    "ROTHENBERG David": "rothenberg-david",
    "ROTHENBERG Jerome": "rothenberg-jerome",
    "ROTHENBURG David": "rothenburg-david",
    "ROTHERY Jason Patrick": "rothery-jason-patrick",
    "ROTHESFELD Seth Zvi": "rothesfeld-seth-zvi",
    "ROTHFIELD Evelyn": "rothfield-evelyn",
    "ROTHFIELD Tom": "rothfield-tom",
    "ROTHGARBER Herbert": "rothgarber-herbert",
    "ROTHKIN Andrew": "rothkin-andrew",
    "ROTHMAN Alyse": "rothman-alyse",
    "ROTHMAN-HICKS Zach": "rothman-hicks-zach",
    "ROTHNIE Jane": "rothnie-jane",
    "ROTHSCHILD Andrew": "rothschild-andrew",
    "ROTHSCHILD Kate": "rothschild-kate",
    "ROTHSCHILD Liz": "rothschild-liz",
    "ROTHSCHILD Michael": "rothschild-michael",
    "ROTHSEY Seamis": "rothsey-seamis",
    "ROTHSTADT David": "rothstadt-david",
    "ROTHSTEIN Caroline": "rothstein-caroline",
    "ROTHSTEIN Peter": "rothstein-peter",
    "ROTHSTEIN Robin": "rothstein-robin",
    "ROTHSTEIN Sharyn": "rothstein-sharyn",
    "ROTHWELL Brian": "rothwell-brian",
    "ROTHWELL Matt": "rothwell-matt",
    "ROTHWELL Naomi": "rothwell-naomi",
    "ROTHWELL Paul": "rothwell-paul",
    "ROTHWELL Talbot": "rothwell-talbot",
    "ROTIMI Ola": "rotimi-ola",
    "ROTMAN Brian": "rotman-brian",
    "ROTONDO Paolo": "rotondo-paolo",
    "ROTOZAZA ": "rotozaza",
    "ROTTENBERG Julie": "rottenberg-julie",
    "ROTTER Fritz": "rotter-fritz",
    "ROTTGER James": "rottger-james",
    "ROTTMANN Larry": "rottmann-larry",
    "ROTUNNO Oliver": "rotunno-oliver",
    "ROUECHE Terry": "roueche-terry",
    "ROUFAEAL Jon": "roufaeal-jon",
    "ROUGET-DIVET Nicholas": "rouget-divet-nicholas",
    "ROUGH William": "rough-william",
    "ROUGH AND TUMBLE THEATRE ": "rough-and-tumble-theatre",
    "ROUGH CUT THEATRE ": "rough-cut-theatre",
    "ROUGHTON A I": "roughton-a-i",
    "ROUKE Robert": "rouke-robert",
    "ROULET Bill": "roulet-bill",
    "ROULSTON Keith": "roulston-keith",
    "ROULSTON Michael": "roulston-michael",
    "ROUMAIN Daniel Bernard": "roumain-daniel-bernard",
    "ROUND N G": "round-n-g",
    "ROUND THE HAT RACK ": "round-the-hat-rack",
    "ROUNDS Monica": "rounds-monica",
    "ROUNDTHWAITE Julia": "roundthwaite-julia",
    "ROURKE Jeanette": "rourke-jeanette",
    "ROURKE Josie": "rourke-josie",
    "ROUSE Frances": "rouse-frances",
    "ROUSE Marc R": "rouse-marc-r",
    "ROUSE Mikel": "rouse-mikel",
    "ROUSE Robin": "rouse-robin",
    "ROUSSEL Raymond": "roussel-raymond",
    "ROUSSEL Sven H": "roussel-sven-h",
    "ROUSSEVE David": "rousseve-david",
    "ROUSSIN Andre": "roussin-andre",
    "ROUSSIN Claude": "roussin-claude",
    "ROUSSO Karen": "rousso-karen",
    "ROUTH Lewis": "routh-lewis",
    "ROUTLEDGE Derek": "routledge-derek",
    "ROUTLEDGE Ellie": "routledge-ellie",
    "ROUTLEDGE Sam": "routledge-sam",
    "ROUVEYROL April": "rouveyrol-april",
    "ROVEGNO Mia": "rovegno-mia",
    "ROVEN Glen": "roven-glen",
    "ROVING ROOTS ": "roving-roots",
    "ROWAN Alex A": "rowan-alex-a",
    "ROWAN Fred": "rowan-fred",
    "ROWAN Gemma": "rowan-gemma",
    "ROWAN Tom": "rowan-tom",
    "ROWBOTHAM Sheila": "rowbotham-sheila",
    "ROWDON Ben": "rowdon-ben",
    "ROWDON Maurice": "rowdon-maurice",
    "ROWE Chris": "rowe-chris",
    "ROWE Craig Acosta": "rowe-craig-acosta",
    "ROWE Dana P": "rowe-dana-p",
    "ROWE Dom": "rowe-dom",
    "ROWE Jonathan": "rowe-jonathan",
    "ROWE Nicholas": "rowe-nicholas",
    "ROWE Pat": "rowe-pat",
    "ROWE Peter": "rowe-peter",
    "ROWE Ricky": "rowe-ricky",
    "ROWE Sam": "rowe-sam",
    "ROWE Tony": "rowe-tony",
    "ROWE Vivian": "rowe-vivian",
    "ROWELL Barry": "rowell-barry",
    "ROWELL George": "rowell-george",
    "ROWELL Peter": "rowell-peter",
    "ROWELL Stephanie": "rowell-stephanie",
    "ROWELL Steve A": "rowell-steve-a",
    "ROWEN Azizah Hayes": "rowen-azizah-hayes",
    "ROWLAND James": "rowland-james",
    "ROWLAND Jana": "rowland-jana",
    "ROWLAND Jane": "rowland-jane",
    "ROWLAND Jennifer": "rowland-jennifer",
    "ROWLAND Joyce": "rowland-joyce",
    "ROWLAND L Susan": "rowland-l-susan",
    "ROWLAND Phelim": "rowland-phelim",
    "ROWLAND Sian": "rowland-sian",
    "ROWLANDS Graham": "rowlands-graham",
    "ROWLANDS Ian": "rowlands-ian",
    "ROWLANDS Paula": "rowlands-paula",
    "ROWLANDS Sioned": "rowlands-sioned",
    "ROWLEY David E": "rowley-david-e",
    "ROWLEY John": "rowley-john",
    "ROWLINSON Wiliam": "rowlinson-wiliam",
    "ROWNEY Marilyn": "rowney-marilyn",
    "ROWNTREE Phillip": "rowntree-phillip",
    "ROWSELL Terry": "rowsell-terry",
    "ROWSON Philip": "rowson-philip",
    "ROWSTON Melita": "rowston-melita",
    "ROXBOROUGH William": "roxborough-william",
    "ROXBURGH Richard": "roxburgh-richard",
    "ROXBURGH Ricky": "roxburgh-ricky",
    "ROY Anusree": "roy-anusree",
    "ROY Edward": "roy-edward",
    "ROY James": "roy-james",
    "ROY William": "roy-william",
    "ROYAL Bert V": "royal-bert-v",
    "ROYAL Peter": "royal-peter",
    "ROYALL P J": "royall-p-j",
    "ROYCE Adrien": "royce-adrien",
    "ROYCE Cheryl": "royce-cheryl",
    "ROYCE Graydon": "royce-graydon",
    "ROYCE Katherine": "royce-katherine",
    "ROYLANCE Stephen": "roylance-stephen",
    "ROYLE Derek S": "royle-derek-s",
    "ROYLE Trevor": "royle-trevor",
    "ROYS William": "roys-william",
    "ROYSTON Robert": "royston-robert",
    "ROZAKIS Gregory": "rozakis-gregory",
    "ROZEBOOM Cindy": "rozeboom-cindy",
    "ROZETT Joshua": "rozett-joshua",
    "ROZETT Louise": "rozett-louise",
    "ROZEWICZ Tadeusz": "rozewicz-tadeusz",
    "ROZHOVA Anzhela": "rozhova-anzhela",
    "ROZIE Fabrice": "rozie-fabrice",
    "ROZIN Seth": "rozin-seth",
    "ROZNOWSKI Rob": "roznowski-rob",
    "ROZO Pedro Migue": "rozo-pedro-migue",
    "ROZOVSKY Mark": "rozovsky-mark"
  }
};