export default {
  "metadata": {
    "results": 367,
    "timeStamp": "2025-12-05T21:30:33.681Z",
    "url": "https://www.doollee.com/PlaywrightsR/R_playwrights_s-z.php"
  },
  "authors": {
    "RT ": "rt",
    "RUBANO John": "rubano-john",
    "RUBANOFF Joseph": "rubanoff-joseph",
    "RUBELL Michael": "rubell-michael",
    "RUBEN Adam": "ruben-adam",
    "RUBEN Fred": "ruben-fred",
    "RUBEN Jose": "ruben-jose",
    "RUBENFELD Michael": "rubenfeld-michael",
    "RUBENFIELD Sheldon": "rubenfield-sheldon",
    "RUBENS Bernice": "rubens-bernice",
    "RUBENS Paul": "rubens-paul",
    "RUBENSTEIN Alan": "rubenstein-alan",
    "RUBENSTEIN Deidre": "rubenstein-deidre",
    "RUBENSTEIN Howard": "rubenstein-howard",
    "RUBENSTEIN Ken": "rubenstein-ken",
    "RUBESS Banuta": "rubess-banuta",
    "RUBIN Alex": "rubin-alex",
    "RUBIN Alexandra H": "rubin-alexandra-h",
    "RUBIN Amy": "rubin-amy",
    "RUBIN Brady": "rubin-brady",
    "RUBIN Brian P": "rubin-brian-p",
    "RUBIN Bruce Joel": "rubin-bruce-joel",
    "RUBIN Daniel J": "rubin-daniel-j",
    "RUBIN Danny": "rubin-danny",
    "RUBIN Ira": "rubin-ira",
    "RUBIN Laurie": "rubin-laurie",
    "RUBIN Leon": "rubin-leon",
    "RUBIN Paul": "rubin-paul",
    "RUBIN Penny": "rubin-penny",
    "RUBIN Rachel-Louise": "rubin-rachel-louise",
    "RUBIN Rich": "rubin-rich",
    "RUBIN Theodore": "rubin-theodore",
    "RUBINEK Saul": "rubinek-saul",
    "RUBINO George": "rubino-george",
    "RUBINOFF David": "rubinoff-david",
    "RUBINS Josh": "rubins-josh",
    "RUBINSKY Robert I": "rubinsky-robert-i",
    "RUBINSTEIN Amnon": "rubinstein-amnon",
    "RUBINSTEIN Dafna": "rubinstein-dafna",
    "RUBINSTEIN Gillian": "rubinstein-gillian",
    "RUBINSTEIN Ronit": "rubinstein-ronit",
    "RUBIO Jose Lopez": "rubio-jose-lopez",
    "RUBY Harry": "ruby-harry",
    "RUBY Michael": "ruby-michael",
    "RUBY Ray Jarvis": "ruby-ray-jarvis",
    "RUBY Thelma": "ruby-thelma",
    "RUCCELLO Annibale": "ruccello-annibale",
    "RUCH Alan": "ruch-alan",
    "RUCKER Gary": "rucker-gary",
    "RUCKER Kathy": "rucker-kathy",
    "RUCKER Libby": "rucker-libby",
    "RUCKER Nana Malaya": "rucker-nana-malaya",
    "RUCKSTAHL Katharina": "ruckstahl-katharina",
    "RUDAKOFF Judith": "rudakoff-judith",
    "RUDALL Nicholas": "rudall-nicholas",
    "RUDD Enid": "rudd-enid",
    "RUDD Jan": "rudd-jan",
    "RUDD Michael": "rudd-michael",
    "RUDD Rad": "rudd-rad",
    "RUDD Steele": "rudd-steele",
    "RUDDELL Nicholas": "ruddell-nicholas",
    "RUDDEN Liam": "rudden-liam",
    "RUDDER Hilary": "rudder-hilary",
    "RUDDER Robert S": "rudder-robert-s",
    "RUDE MECHANICALS ": "rude-mechanicals",
    "RUDEN Sarah": "ruden-sarah",
    "RUDERFER Joanne": "ruderfer-joanne",
    "RUDERMAN Gary": "ruderman-gary",
    "RUDET Jacqueline": "rudet-jacqueline",
    "RUDETSKY Seth": "rudetsky-seth",
    "RUDEZ Michael": "rudez-michael",
    "RUDGE Myles": "rudge-myles",
    "RUDHOLM Daniel": "rudholm-daniel",
    "RUDIC Laurance": "rudic-laurance",
    "RUDICK Leah": "rudick-leah",
    "RUDIE Evelyn": "rudie-evelyn",
    "RUDIK Roger": "rudik-roger",
    "RUDIN Marcia R": "rudin-marcia-r",
    "RUDKIN David": "rudkin-david",
    "RUDKIN Mark": "rudkin-mark",
    "RUDKIN Matt": "rudkin-matt",
    "RUDLIN John": "rudlin-john",
    "RUDMAN Damon": "rudman-damon",
    "RUDMAN Michael": "rudman-michael",
    "RUDNICK Eric": "rudnick-eric",
    "RUDNICK Paul": "rudnick-paul",
    "RUDOREN Gary": "rudoren-gary",
    "RUDRUM Adam": "rudrum-adam",
    "RUDY Linda": "rudy-linda",
    "RUDY Mikhail": "rudy-mikhail",
    "RUDY Stewart": "rudy-stewart",
    "RUE Victoria": "rue-victoria",
    "RUEBSAAT Norbet": "ruebsaat-norbet",
    "RUEFF Roger": "rueff-roger",
    "RUFF Sarah": "ruff-sarah",
    "RUFFIN Amber": "ruffin-amber",
    "RUFFIN Robert": "ruffin-robert",
    "RUFFINI Gene": "ruffini-gene",
    "RUFOLO Dana": "rufolo-dana",
    "RUGAMBA Dorcy": "rugamba-dorcy",
    "RUGANDA John": "ruganda-john",
    "RUGE Eugen": "ruge-eugen",
    "RUGGERI Emmanuel": "ruggeri-emmanuel",
    "RUGGIER Carole": "ruggier-carole",
    "RUGGIERO Rob": "ruggiero-rob",
    "RUGGINS Michael": "ruggins-michael",
    "RUHL J D": "ruhl-j-d",
    "RUHL Sarah": "ruhl-sarah",
    "RUHLMAN Armand A": "ruhlman-armand-a",
    "RUHM Gerhard": "ruhm-gerhard",
    "RUIVIVAR Anthony": "ruivivar-anthony",
    "RUIZ Jerry": "ruiz-jerry",
    "RUIZ Juan": "ruiz-juan",
    "RUIZ L Lopez": "ruiz-l-lopez",
    "RUIZ Mildred": "ruiz-mildred",
    "RUIZ Noelia": "ruiz-noelia",
    "RUIZ Sandra": "ruiz-sandra",
    "RUIZ William": "ruiz-william",
    "RUKOV Mogens": "rukov-mogens",
    "RULIN Alexander D": "rulin-alexander-d",
    "RUMBACH Jenn": "rumbach-jenn",
    "RUMBELOW Sam": "rumbelow-sam",
    "RUMBELOW Steven": "rumbelow-steven",
    "RUMBLE Patricia Barry": "rumble-patricia-barry",
    "RUMBLER William": "rumbler-william",
    "RUMENS Carol": "rumens-carol",
    "RUMMAGE THEATRE ": "rummage-theatre",
    "RUMMEL Chris": "rummel-chris",
    "RUMMOS Paul Erik": "rummos-paul-erik",
    "RUMNEY Michael": "rumney-michael",
    "RUMNEY Peter": "rumney-peter",
    "RUMOLI BROTHERS ": "rumoli-brothers",
    "RUNCIE James": "runcie-james",
    "RUNDLE Erika": "rundle-erika",
    "RUNDLE Guy": "rundle-guy",
    "RUNSWICK Daryl": "runswick-daryl",
    "RUNT ": "runt",
    "RUNYAN Robin": "runyan-robin",
    "RUNYON Damon": "runyon-damon",
    "RUOHONEN Laura": "ruohonen-laura",
    "RUPANI Om": "rupani-om",
    "RUPPE Jan": "ruppe-jan",
    "RUPPERT Katie": "ruppert-katie",
    "RUPPERT Timothy Lawrence": "ruppert-timothy-lawrence",
    "RUS J H": "rus-j-h",
    "RUSCH C": "rusch-c",
    "RUSCH Phoebe": "rusch-phoebe",
    "RUSCOLL Rick": "ruscoll-rick",
    "RUSCONI Paul": "rusconi-paul",
    "RUSEK Lily": "rusek-lily",
    "RUSH Catherine": "rush-catherine",
    "RUSH David": "rush-david",
    "RUSH Geoffrey": "rush-geoffrey",
    "RUSH Joanna": "rush-joanna",
    "RUSH John": "rush-john",
    "RUSH Kevin": "rush-kevin",
    "RUSH Lawrence": "rush-lawrence",
    "RUSH Michael": "rush-michael",
    "RUSHBROOKE James": "rushbrooke-james",
    "RUSHDEN Jack": "rushden-jack",
    "RUSHDIE Salman": "rushdie-salman",
    "RUSHFORTH Tony": "rushforth-tony",
    "RUSHIE Sinead": "rushie-sinead",
    "RUSHTON Willie": "rushton-willie",
    "RUSIECKI David": "rusiecki-david",
    "RUSJAN Jelena": "rusjan-jelena",
    "RUSK Rich": "rusk-rich",
    "RUSKIN Adina L": "ruskin-adina-l",
    "RUSKIN Sheila": "ruskin-sheila",
    "RUSS Adryan": "russ-adryan",
    "RUSS J R": "russ-j-r",
    "RUSS Joanna": "russ-joanna",
    "RUSS Travis": "russ-travis",
    "RUSSEL Charlotte M": "russel-charlotte-m",
    "RUSSEL Richard Scott": "russel-richard-scott",
    "RUSSELL A D": "russell-a-d",
    "RUSSELL A J": "russell-a-j",
    "RUSSELL Amy": "russell-amy",
    "RUSSELL Anne": "russell-anne",
    "RUSSELL Anne (1)": "russell-anne-1",
    "RUSSELL Bernadette": "russell-bernadette",
    "RUSSELL Bill": "russell-bill",
    "RUSSELL Brenda": "russell-brenda",
    "RUSSELL Charlie L": "russell-charlie-l",
    "RUSSELL David": "russell-david",
    "RUSSELL Dominique": "russell-dominique",
    "RUSSELL Douglas A": "russell-douglas-a",
    "RUSSELL Eileen": "russell-eileen",
    "RUSSELL Gareth": "russell-gareth",
    "RUSSELL Graham": "russell-graham",
    "RUSSELL Hamish": "russell-hamish",
    "RUSSELL Helen": "russell-helen",
    "RUSSELL Howard": "russell-howard",
    "RUSSELL Ivy": "russell-ivy",
    "RUSSELL Jack": "russell-jack",
    "RUSSELL Jacquie": "russell-jacquie",
    "RUSSELL James": "russell-james",
    "RUSSELL Jane": "russell-jane",
    "RUSSELL Jim": "russell-jim",
    "RUSSELL John C": "russell-john-c",
    "RUSSELL Keith": "russell-keith",
    "RUSSELL Lawrence": "russell-lawrence",
    "RUSSELL Lucy Joy": "russell-lucy-joy",
    "RUSSELL Madeleine": "russell-madeleine",
    "RUSSELL Mark": "russell-mark",
    "RUSSELL Mark (1)": "russell-mark-1",
    "RUSSELL Michael": "russell-michael",
    "RUSSELL Pamela": "russell-pamela",
    "RUSSELL Peter": "russell-peter",
    "RUSSELL R C": "russell-r-c",
    "RUSSELL Rebecca": "russell-rebecca",
    "RUSSELL Robert": "russell-robert",
    "RUSSELL Ronald": "russell-ronald",
    "RUSSELL Roy": "russell-roy",
    "RUSSELL Rupert": "russell-rupert",
    "RUSSELL Sheridan": "russell-sheridan",
    "RUSSELL Stephen": "russell-stephen",
    "RUSSELL Todd": "russell-todd",
    "RUSSELL Wiley": "russell-wiley",
    "RUSSELL Willy": "russell-willy",
    "RUSSELL Zack": "russell-zack",
    "RUSSELL-IDES Isabella": "russell-ides-isabella",
    "RUSSELL-KING Caroline": "russell-king-caroline",
    "RUSSELL-SMITH Kate": "russell-smith-kate",
    "RUSSO Dante": "russo-dante",
    "RUSSO Dennis": "russo-dennis",
    "RUSSO Kathleen": "russo-kathleen",
    "RUSSO Letizia": "russo-letizia",
    "RUSSO T Dello": "russo-t-dello",
    "RUST D": "rust-d",
    "RUST Lis": "rust-lis",
    "RUST Tony": "rust-tony",
    "RUSTAN John": "rustan-john",
    "RUSTIA Noel": "rustia-noel",
    "RUSTIN Dam": "rustin-dam",
    "RUSTIN Sandy": "rustin-sandy",
    "RUTH Deborah Dahsow": "ruth-deborah-dahsow",
    "RUTH Marianne": "ruth-marianne",
    "RUTH Michael": "ruth-michael",
    "RUTHERFORD Alistair": "rutherford-alistair",
    "RUTHERFORD Andrew": "rutherford-andrew",
    "RUTHERFORD Donna": "rutherford-donna",
    "RUTHERFORD Gavin": "rutherford-gavin",
    "RUTHERFORD John": "rutherford-john",
    "RUTHERFORD Kourtney": "rutherford-kourtney",
    "RUTHERFORD Luca": "rutherford-luca",
    "RUTHERFORD Lyndee-Jane": "rutherford-lyndee-jane",
    "RUTHERFORD Mervyn": "rutherford-mervyn",
    "RUTHERFORD Randy": "rutherford-randy",
    "RUTHERFORD Sarah": "rutherford-sarah",
    "RUTHERFORD Shevaun": "rutherford-shevaun",
    "RUTHERFORD Stanley": "rutherford-stanley",
    "RUTHERFORD-JOHNSON Elizabeth": "rutherford-johnson-elizabeth",
    "RUTKOWSKI Bill": "rutkowski-bill",
    "RUTMAN Leo": "rutman-leo",
    "RUTOWSKI Bill": "rutowski-bill",
    "RUTTER Alexandra": "rutter-alexandra",
    "RUTTER Matt": "rutter-matt",
    "RUTTER Peta": "rutter-peta",
    "RUTTERFORD Julie": "rutterford-julie",
    "RUTTY Lee": "rutty-lee",
    "RUX Carl Hancock": "rux-carl-hancock",
    "RUYLE Nancy": "ruyle-nancy",
    "RUZHYEV Yury": "ruzhyev-yury",
    "RUZICKOVA Ivana": "ruzickova-ivana",
    "RYALL Philip": "ryall-philip",
    "RYAN Adrian": "ryan-adrian",
    "RYAN Aine": "ryan-aine",
    "RYAN Alexander J": "ryan-alexander-j",
    "RYAN Andrew": "ryan-andrew",
    "RYAN Annie": "ryan-annie",
    "RYAN Anthony": "ryan-anthony",
    "RYAN Bridget": "ryan-bridget",
    "RYAN C Paul": "ryan-c-paul",
    "RYAN Cate": "ryan-cate",
    "RYAN Catherine": "ryan-catherine",
    "RYAN Cheyney": "ryan-cheyney",
    "RYAN Chris": "ryan-chris",
    "RYAN Colin": "ryan-colin",
    "RYAN Damien": "ryan-damien",
    "RYAN Daniel": "ryan-daniel",
    "RYAN Dee": "ryan-dee",
    "RYAN Duke": "ryan-duke",
    "RYAN Eileen": "ryan-eileen",
    "RYAN Gina": "ryan-gina",
    "RYAN Hannah": "ryan-hannah",
    "RYAN James": "ryan-james",
    "RYAN Jen": "ryan-jen",
    "RYAN Jim": "ryan-jim",
    "RYAN Joan": "ryan-joan",
    "RYAN Joanne": "ryan-joanne",
    "RYAN John": "ryan-john",
    "RYAN Josephine": "ryan-josephine",
    "RYAN Judith": "ryan-judith",
    "RYAN Julia": "ryan-julia",
    "RYAN Kate E": "ryan-kate-e",
    "RYAN Kate Moira": "ryan-kate-moira",
    "RYAN Kathryn": "ryan-kathryn",
    "RYAN Keelin": "ryan-keelin",
    "RYAN Leah": "ryan-leah",
    "RYAN Lucinda": "ryan-lucinda",
    "RYAN Marja-Lewis": "ryan-marja-lewis",
    "RYAN Mark": "ryan-mark",
    "RYAN Matthew": "ryan-matthew",
    "RYAN Michael": "ryan-michael",
    "RYAN Nancy": "ryan-nancy",
    "RYAN Nick": "ryan-nick",
    "RYAN Oscar": "ryan-oscar",
    "RYAN Paul": "ryan-paul",
    "RYAN Peter": "ryan-peter",
    "RYAN Peter Anthony": "ryan-peter-anthony",
    "RYAN Phil": "ryan-phil",
    "RYAN Phyllis": "ryan-phyllis",
    "RYAN Rich": "ryan-rich",
    "RYAN Robert C": "ryan-robert-c",
    "RYAN Sam": "ryan-sam",
    "RYAN Sarah": "ryan-sarah",
    "RYAN Sidney": "ryan-sidney",
    "RYAN Sonia": "ryan-sonia",
    "RYAN Tammy": "ryan-tammy",
    "RYAN Thomas": "ryan-thomas",
    "RYAN Toby Gordon": "ryan-toby-gordon",
    "RYAN Tracy": "ryan-tracy",
    "RYBACK B T": "ryback-b-t",
    "RYBACK Brett": "ryback-brett",
    "RYBECK Abe": "rybeck-abe",
    "RYBECK Brett": "rybeck-brett",
    "RYBIN Sofia": "rybin-sofia",
    "RYBURN Terri": "ryburn-terri",
    "RYCHETSKY Tomas": "rychetsky-tomas",
    "RYCKEWAERT Koba": "ryckewaert-koba",
    "RYCROFT Jamie": "rycroft-jamie",
    "RYDAL Emma": "rydal-emma",
    "RYDALCH Mattie Roquel": "rydalch-mattie-roquel",
    "RYDE David": "ryde-david",
    "RYDER Andrew Wells": "ryder-andrew-wells",
    "RYDER Charlie": "ryder-charlie",
    "RYDER Craig": "ryder-craig",
    "RYDER Lisa": "ryder-lisa",
    "RYDER Martin": "ryder-martin",
    "RYDER Richard": "ryder-richard",
    "RYDING David": "ryding-david",
    "RYDING Sue": "ryding-sue",
    "RYDZ Suzanne": "rydz-suzanne",
    "RYDZEL Molly": "rydzel-molly",
    "RYDZEWSKA Ewelina": "rydzewska-ewelina",
    "RYE Kevin Edward": "rye-kevin-edward",
    "RYECART Patrick": "ryecart-patrick",
    "RYERSON Florence": "ryerson-florence",
    "RYERSON Madelena": "ryerson-madelena",
    "RYERSON Stanley": "ryerson-stanley",
    "RYGA George": "ryga-george",
    "RYKEWAERT Koba": "rykewaert-koba",
    "RYLANCE Mark": "rylance-mark",
    "RYLANDS George": "rylands-george",
    "RYLSKI Nika": "rylski-nika",
    "RYLSKY Maksym": "rylsky-maksym",
    "RYMAN Chris": "ryman-chris",
    "RYMAN Will": "ryman-will",
    "RYMASZEWSKI Marek": "rymaszewski-marek",
    "RYNEARSON Marjie": "rynearson-marjie",
    "RYPP Howard": "rypp-howard",
    "RYSKIND Morrie": "ryskind-morrie",
    "RYTON Royce": "ryton-royce",
    "RYZUK Mary": "ryzuk-mary",
    "RZHEVSKY Nicholas": "rzhevsky-nicholas",
    "RZIGALINSKI Christopher": "rzigalinski-christopher"
  }
};