export default {
  "metadata": {
    "results": 1253,
    "timeStamp": "2025-12-05T21:31:08.237Z",
    "url": "https://www.doollee.com/PlaywrightsS/S_playwrights_g-l.php"
  },
  "authors": {
    "SGOUROS Michael": "sgouros-michael",
    "SHABAKA Khari K": "shabaka-khari-k",
    "SHABAN Nabil": "shaban-nabil",
    "SHABAN Shlomi": "shaban-shlomi",
    "SHABANGU Mncedisi": "shabangu-mncedisi",
    "SHABAZZ Ibn": "shabazz-ibn",
    "SHABAZZ Lasana": "shabazz-lasana",
    "SHABER David": "shaber-david",
    "SHACKERLEY-BENNETT Martine": "shackerley-bennett-martine",
    "SHACKLEFORD Lee Eric": "shackleford-lee-eric",
    "SHACKLETON Eliza": "shackleton-eliza",
    "SHADBOLT Maurice": "shadbolt-maurice",
    "SHADE Jeff": "shade-jeff",
    "SHADE Steve": "shade-steve",
    "SHADLER Renae": "shadler-renae",
    "SHADRAKE Bonnie": "shadrake-bonnie",
    "SHADWELL Thomas": "shadwell-thomas",
    "SHAEFER Sarah": "shaefer-sarah",
    "SHAFAGHI Lale": "shafaghi-lale",
    "SHAFAU Nikky Norton": "shafau-nikky-norton",
    "SHAFER Andrew": "shafer-andrew",
    "SHAFER Charles": "shafer-charles",
    "SHAFER Craig": "shafer-craig",
    "SHAFER Roxane": "shafer-roxane",
    "SHAFER Susan": "shafer-susan",
    "SHAFER Taddeus": "shafer-taddeus",
    "SHAFFER Anthony": "shaffer-anthony",
    "SHAFFER Diane": "shaffer-diane",
    "SHAFFER Gina": "shaffer-gina",
    "SHAFFER Janece": "shaffer-janece",
    "SHAFFER Peter": "shaffer-peter",
    "SHAFFER Tanya": "shaffer-tanya",
    "SHAFFRON Robert": "shaffron-robert",
    "SHAFIQ Afrah": "shafiq-afrah",
    "SHAFNER Shawn": "shafner-shawn",
    "SHAFRAN Evan": "shafran-evan",
    "SHAH Avin": "shah-avin",
    "SHAH Rajni": "shah-rajni",
    "SHAHADI Fred": "shahadi-fred",
    "SHAHAN Harvey": "shahan-harvey",
    "SHAHAN Melody": "shahan-melody",
    "SHAHEEN Qasim Riza": "shaheen-qasim-riza",
    "SHAHI Arya": "shahi-arya",
    "SHAIMAN Marc": "shaiman-marc",
    "SHAIN Alan": "shain-alan",
    "SHAINBERG Lawrence": "shainberg-lawrence",
    "SHAINE Laura": "shaine-laura",
    "SHAIRP Mordaunt": "shairp-mordaunt",
    "SHAKESPEARE Clive": "shakespeare-clive",
    "SHAKESPEARE R W": "shakespeare-r-w",
    "SHAKESPEARE William": "shakespeare-william",
    "SHAKTI Uma Kali": "shakti-uma-kali",
    "SHAKTI ": "shakti",
    "SHALE Kerry": "shale-kerry",
    "SHALLAT Phil": "shallat-phil",
    "SHALLOE Marki": "shalloe-marki",
    "SHALOM Binyamin": "shalom-binyamin",
    "SHAM Peter": "sham-peter",
    "SHAMAMIAN Lousine": "shamamian-lousine",
    "SHAMAN Will": "shaman-will",
    "SHAMANADZE Shadiman": "shamanadze-shadiman",
    "SHAMANS ": "shamans",
    "SHAMAS Laura": "shamas-laura",
    "SHAMAS Sandra": "shamas-sandra",
    "SHAMATA Michael": "shamata-michael",
    "SHAMBERGER Jared": "shamberger-jared",
    "SHAMBLIN Jack": "shamblin-jack",
    "SHAMBOLIC THEATRE ": "shambolic-theatre",
    "SHAMIEH Betty": "shamieh-betty",
    "SHAMSIE Kamila": "shamsie-kamila",
    "SHANAHAN Bryony": "shanahan-bryony",
    "SHANAHAN Dan": "shanahan-dan",
    "SHANAHAN Elizabeth": "shanahan-elizabeth",
    "SHANAHAN John": "shanahan-john",
    "SHANAHAN Pauline": "shanahan-pauline",
    "SHAND Charlie": "shand-charlie",
    "SHAND John": "shand-john",
    "SHAND Michael": "shand-michael",
    "SHAND Pamela": "shand-pamela",
    "SHAND Pat": "shand-pat",
    "SHAND William": "shand-william",
    "SHANDER Todd": "shander-todd",
    "SHANDLER Manju": "shandler-manju",
    "SHANE Aliza": "shane-aliza",
    "SHANE Joe": "shane-joe",
    "SHANE Nancy": "shane-nancy",
    "SHANE Tim": "shane-tim",
    "SHANER John Herman": "shaner-john-herman",
    "SHANGE Ntozake": "shange-ntozake",
    "SHANGHAI TARO DANCE COMPANY ": "shanghai-taro-dance-company",
    "SHANIAN Charlie": "shanian-charlie",
    "SHANIN Sandy": "shanin-sandy",
    "SHANK Adele Edling": "shank-adele-edling",
    "SHANK Terrence": "shank-terrence",
    "SHANK Theodore": "shank-theodore",
    "SHANKMAN Jim": "shankman-jim",
    "SHANKS Gabriel": "shanks-gabriel",
    "SHANKS Islay D": "shanks-islay-d",
    "SHANLEY Anita": "shanley-anita",
    "SHANLEY John Patrick": "shanley-john-patrick",
    "SHANMAN Ellen": "shanman-ellen",
    "SHANN Taylor": "shann-taylor",
    "SHANNON Bob": "shannon-bob",
    "SHANNON Caitlin": "shannon-caitlin",
    "SHANNON Edward": "shannon-edward",
    "SHANNON James Fdward": "shannon-james-fdward",
    "SHANNON Julie": "shannon-julie",
    "SHANNON Liam": "shannon-liam",
    "SHANNON Molly": "shannon-molly",
    "SHANNON Richard": "shannon-richard",
    "SHANNON Robert M": "shannon-robert-m",
    "SHANOFF T J": "shanoff-t-j",
    "SHANON ": "shanon",
    "SHANTA James": "shanta-james",
    "SHAPCOTT Margaret": "shapcott-margaret",
    "SHAPCOTT Thomas William": "shapcott-thomas-william",
    "SHAPER Hal": "shaper-hal",
    "SHAPIN Jan": "shapin-jan",
    "SHAPIRO Alan": "shapiro-alan",
    "SHAPIRO Alice": "shapiro-alice",
    "SHAPIRO Allan": "shapiro-allan",
    "SHAPIRO Anna D": "shapiro-anna-d",
    "SHAPIRO Arthur": "shapiro-arthur",
    "SHAPIRO Dan": "shapiro-dan",
    "SHAPIRO Herb": "shapiro-herb",
    "SHAPIRO Ira": "shapiro-ira",
    "SHAPIRO Isaac": "shapiro-isaac",
    "SHAPIRO Jacqui": "shapiro-jacqui",
    "SHAPIRO Leonardo": "shapiro-leonardo",
    "SHAPIRO Lisa Diana": "shapiro-lisa-diana",
    "SHAPIRO Mel": "shapiro-mel",
    "SHAPIRO Micah": "shapiro-micah",
    "SHAPIRO Michael Gordon": "shapiro-michael-gordon",
    "SHAPIRO Norman R": "shapiro-norman-r",
    "SHAPIRO Sidney": "shapiro-sidney",
    "SHAPIRO Steven A": "shapiro-steven-a",
    "SHAPIRO Todd": "shapiro-todd",
    "SHAPLAND Jo": "shapland-jo",
    "SHAPLIN Adriano": "shaplin-adriano",
    "SHAPTER Lisa": "shapter-lisa",
    "SHARAZUDDIN Iskandar": "sharazuddin-iskandar",
    "SHARBUTT Julie": "sharbutt-julie",
    "SHARE Robin": "share-robin",
    "SHARED EXPERIENCE ": "shared-experience",
    "SHARIF Bina": "sharif-bina",
    "SHARKEY Jack": "sharkey-jack",
    "SHARKEY Simon": "sharkey-simon",
    "SHARKEY Stephen": "sharkey-stephen",
    "SHARKEY Tom": "sharkey-tom",
    "SHARLAND Elizabeth": "sharland-elizabeth",
    "SHARLAND Mike": "sharland-mike",
    "SHARMA Akhil": "sharma-akhil",
    "SHARMA Haresh": "sharma-haresh",
    "SHARMA Monty": "sharma-monty",
    "SHARMA Nishita": "sharma-nishita",
    "SHARMA Partap": "sharma-partap",
    "SHARMA Pushkar": "sharma-pushkar",
    "SHARMA Rohini": "sharma-rohini",
    "SHARMAN Gopal": "sharman-gopal",
    "SHARMAN Jim": "sharman-jim",
    "SHARMAN Lindsay": "sharman-lindsay",
    "SHARMAN Miriam": "sharman-miriam",
    "SHARMAN Russell Leigh": "sharman-russell-leigh",
    "SHARMER Olly": "sharmer-olly",
    "SHARP Alastair": "sharp-alastair",
    "SHARP Anthony": "sharp-anthony",
    "SHARP Bob": "sharp-bob",
    "SHARP Cameron": "sharp-cameron",
    "SHARP Darren": "sharp-darren",
    "SHARP Ed": "sharp-ed",
    "SHARP John Paul": "sharp-john-paul",
    "SHARP Martin": "sharp-martin",
    "SHARP Michael": "sharp-michael",
    "SHARP Randall": "sharp-randall",
    "SHARP Randy": "sharp-randy",
    "SHARP Rebecca": "sharp-rebecca",
    "SHARP Sarah": "sharp-sarah",
    "SHARP Saundra": "sharp-saundra",
    "SHARP Sheree": "sharp-sheree",
    "SHARP Tim": "sharp-tim",
    "SHARP Tracey": "sharp-tracey",
    "SHARP Travis R": "sharp-travis-r",
    "SHARPE Alan": "sharpe-alan",
    "SHARPE Allan": "sharpe-allan",
    "SHARPE David": "sharpe-david",
    "SHARPE Lauren": "sharpe-lauren",
    "SHARPE Ted": "sharpe-ted",
    "SHARPE Tom": "sharpe-tom",
    "SHARPE William": "sharpe-william",
    "SHARPEN Gregory": "sharpen-gregory",
    "SHARPLES Robbie": "sharples-robbie",
    "SHARPLES Victoria": "sharples-victoria",
    "SHARPLESS Sheila": "sharpless-sheila",
    "SHARPLEY George": "sharpley-george",
    "SHARPLIN Scott": "sharplin-scott",
    "SHARPS Tristan": "sharps-tristan",
    "SHARPWIRE TC ": "sharpwire-tc",
    "SHARRAR Jack": "sharrar-jack",
    "SHARROCK Becci": "sharrock-becci",
    "SHARRON Nomi": "sharron-nomi",
    "SHARROW Robert": "sharrow-robert",
    "SHASHA Tamsin": "shasha-tamsin",
    "SHATROV Mikhail": "shatrov-mikhail",
    "SHATTNER Michael": "shattner-michael",
    "SHATZKY Joel": "shatzky-joel",
    "SHAUGHNESSY Alfred": "shaughnessy-alfred",
    "SHAUGHNESSY Darrin": "shaughnessy-darrin",
    "SHAUGHNESSY Lauren": "shaughnessy-lauren",
    "SHAVELSON Melville": "shavelson-melville",
    "SHAVER Erin": "shaver-erin",
    "SHAVER Molly": "shaver-molly",
    "SHAVER Vanessa": "shaver-vanessa",
    "SHAVERS Julie": "shavers-julie",
    "SHAW Andrew": "shaw-andrew",
    "SHAW Andy": "shaw-andy",
    "SHAW Arje": "shaw-arje",
    "SHAW Barnett": "shaw-barnett",
    "SHAW Ben": "shaw-ben",
    "SHAW Brynn": "shaw-brynn",
    "SHAW Chrissie": "shaw-chrissie",
    "SHAW Damon": "shaw-damon",
    "SHAW Dan Byam": "shaw-dan-byam",
    "SHAW Danny": "shaw-danny",
    "SHAW David": "shaw-david",
    "SHAW Di": "shaw-di",
    "SHAW Do": "shaw-do",
    "SHAW Don": "shaw-don",
    "SHAW Elizabeth": "shaw-elizabeth",
    "SHAW G Tito": "shaw-g-tito",
    "SHAW George Bernard": "shaw-george-bernard",
    "SHAW Gordon": "shaw-gordon",
    "SHAW Gwen Rosman": "shaw-gwen-rosman",
    "SHAW Irwin": "shaw-irwin",
    "SHAW James": "shaw-james",
    "SHAW Jane Catherine": "shaw-jane-catherine",
    "SHAW Janet": "shaw-janet",
    "SHAW John": "shaw-john",
    "SHAW Jonathan": "shaw-jonathan",
    "SHAW Kaefan": "shaw-kaefan",
    "SHAW Kate": "shaw-kate",
    "SHAW Kathleen": "shaw-kathleen",
    "SHAW Kevan": "shaw-kevan",
    "SHAW Kevin": "shaw-kevin",
    "SHAW Les": "shaw-les",
    "SHAW Lucy": "shaw-lucy",
    "SHAW Marjorie": "shaw-marjorie",
    "SHAW Martin": "shaw-martin",
    "SHAW Maxwell": "shaw-maxwell",
    "SHAW Melissa": "shaw-melissa",
    "SHAW Michael": "shaw-michael",
    "SHAW Patrick": "shaw-patrick",
    "SHAW Paul": "shaw-paul",
    "SHAW Peggy": "shaw-peggy",
    "SHAW Peter": "shaw-peter",
    "SHAW Raz": "shaw-raz",
    "SHAW Rebecca": "shaw-rebecca",
    "SHAW Robert": "shaw-robert",
    "SHAW Robert (1)": "shaw-robert-1",
    "SHAW Steve": "shaw-steve",
    "SHAW Willy": "shaw-willy",
    "SHAW Yasmin": "shaw-yasmin",
    "SHAWKAT Omar": "shawkat-omar",
    "SHAWN Allen": "shawn-allen",
    "SHAWN Wallace": "shawn-wallace",
    "SHAY Helen": "shay-helen",
    "SHAY Pat": "shay-pat",
    "SHAYS Felice": "shays-felice",
    "SHAZI Mthuili ka": "shazi-mthuili-ka",
    "SHCHERBAN Vladimir": "shcherban-vladimir",
    "SHE Lao": "she-lao",
    "SHE Marty": "she-marty",
    "SHE SHE POP ": "she-she-pop",
    "SHEA Ann Marie": "shea-ann-marie",
    "SHEA George": "shea-george",
    "SHEA Glenn": "shea-glenn",
    "SHEA Jack": "shea-jack",
    "SHEA John": "shea-john",
    "SHEA Marty": "shea-marty",
    "SHEA Steven": "shea-steven",
    "SHEAF Robert": "sheaf-robert",
    "SHEAHAN Matt": "sheahan-matt",
    "SHEAHAN P J": "sheahan-p-j",
    "SHEAHAN Philip": "sheahan-philip",
    "SHEALY Vanessa": "shealy-vanessa",
    "SHEANSHANG Emma": "sheanshang-emma",
    "SHEAR Claudia": "shear-claudia",
    "SHEAR Jon": "shear-jon",
    "SHEAR Steve": "shear-steve",
    "SHEAR Susan": "shear-susan",
    "SHEARER Bruce": "shearer-bruce",
    "SHEARER Don": "shearer-don",
    "SHEARER Harry": "shearer-harry",
    "SHEARER Jill": "shearer-jill",
    "SHEARER Troy": "shearer-troy",
    "SHEARGOLD Marty": "sheargold-marty",
    "SHEARIN John": "shearin-john",
    "SHEARMAN Alan": "shearman-alan",
    "SHEARMAN Robert": "shearman-robert",
    "SHEARS Carl L": "shears-carl-l",
    "SHEARS Jake": "shears-jake",
    "SHEARSMITH Reece": "shearsmith-reece",
    "SHEASBY Dave": "sheasby-dave",
    "SHECHTER Hofesh": "shechter-hofesh",
    "SHEDDEN John": "shedden-john",
    "SHEEDY M": "sheedy-m",
    "SHEEHAN Carly": "sheehan-carly",
    "SHEEHAN Emily": "sheehan-emily",
    "SHEEHAN Jim": "sheehan-jim",
    "SHEEHAN Johnny": "sheehan-johnny",
    "SHEEHAN Robert Louis": "sheehan-robert-louis",
    "SHEEHAN Teru": "sheehan-teru",
    "SHEEHAN-BUBLA Morgan": "sheehan-bubla-morgan",
    "SHEEHY Catherine": "sheehy-catherine",
    "SHEEHY John": "sheehy-john",
    "SHEEHY P F": "sheehy-p-f",
    "SHEELER Wade": "sheeler-wade",
    "SHEELEY Nelson": "sheeley-nelson",
    "SHEELEY Stuart L": "sheeley-stuart-l",
    "SHEERIN Jacinta": "sheerin-jacinta",
    "SHEERS Owen": "sheers-owen",
    "SHEFFER Erika": "sheffer-erika",
    "SHEFFER Isaiah": "sheffer-isaiah",
    "SHEFFER Stephen": "sheffer-stephen",
    "SHEFFIELD Buddy": "sheffield-buddy",
    "SHEFFIELD David": "sheffield-david",
    "SHEFFIELD Jo Ellen": "sheffield-jo-ellen",
    "SHEFLER Karen": "shefler-karen",
    "SHEFTON Frank": "shefton-frank",
    "SHEHADEH Raja": "shehadeh-raja",
    "SHEHORI Daniel": "shehori-daniel",
    "SHEHORI Steven": "shehori-steven",
    "SHEIK Duncan": "sheik-duncan",
    "SHEIKH Farhana": "sheikh-farhana",
    "SHEIKH Rehan": "sheikh-rehan",
    "SHEIKH Shan H": "sheikh-shan-h",
    "SHEIL Graham": "sheil-graham",
    "SHEILDS Frank": "sheilds-frank",
    "SHEIN Brian": "shein-brian",
    "SHEIN Ivana": "shein-ivana",
    "SHEINESS Marsha Lee": "sheiness-marsha-lee",
    "SHEINKIN Rachel": "sheinkin-rachel",
    "SHEINMEL Richard": "sheinmel-richard",
    "SHEKAR Madhuri": "shekar-madhuri",
    "SHELBURNE Peter": "shelburne-peter",
    "SHELBY Arnold": "shelby-arnold",
    "SHELBY-SZYSZKO Kimberly": "shelby-szyszko-kimberly",
    "SHELDON Bethany": "sheldon-bethany",
    "SHELDON Carol": "sheldon-carol",
    "SHELDON Deborah": "sheldon-deborah",
    "SHELDON Edward": "sheldon-edward",
    "SHELDON Glenn": "sheldon-glenn",
    "SHELDON James": "sheldon-james",
    "SHELDON Sidney": "sheldon-sidney",
    "SHELDRICK Peg": "sheldrick-peg",
    "SHELL Ray": "shell-ray",
    "SHELLAN David": "shellan-david",
    "SHELLEDY James Anthony": "shelledy-james-anthony",
    "SHELLENE June": "shellene-june",
    "SHELLEY Elsa": "shelley-elsa",
    "SHELLEY Gladys": "shelley-gladys",
    "SHELLEY Grace": "shelley-grace",
    "SHELLEY Guy": "shelley-guy",
    "SHELLEY Jonathan": "shelley-jonathan",
    "SHELLEY Juliet": "shelley-juliet",
    "SHELLEY Peter": "shelley-peter",
    "SHELLNER Sracie A": "shellner-sracie-a",
    "SHELPER Brendan": "shelper-brendan",
    "SHELTER Nir": "shelter-nir",
    "SHELTON Brian": "shelton-brian",
    "SHELTON Chris": "shelton-chris",
    "SHELTON Desi P": "shelton-desi-p",
    "SHELTON Frank A": "shelton-frank-a",
    "SHELTON Irving": "shelton-irving",
    "SHELTON Micki": "shelton-micki",
    "SHELTON Tom": "shelton-tom",
    "SHEM Samuel": "shem-samuel",
    "SHEN Hong": "shen-hong",
    "SHEN Ted": "shen-ted",
    "SHENEFELT Michael": "shenefelt-michael",
    "SHENGOLD Nina": "shengold-nina",
    "SHENOY Nandita": "shenoy-nandita",
    "SHENTON Pete": "shenton-pete",
    "SHEPARD Aaron": "shepard-aaron",
    "SHEPARD David A": "shepard-david-a",
    "SHEPARD Jane": "shepard-jane",
    "SHEPARD Joan": "shepard-joan",
    "SHEPARD Mark": "shepard-mark",
    "SHEPARD O-Lan": "shepard-o-lan",
    "SHEPARD Powell": "shepard-powell",
    "SHEPARD Sam": "shepard-sam",
    "SHEPARD Tina": "shepard-tina",
    "SHEPHARD John": "shephard-john",
    "SHEPHARD-MASSAT Sherry M": "shephard-massat-sherry-m",
    "SHEPHERD Andrew": "shepherd-andrew",
    "SHEPHERD Cariad": "shepherd-cariad",
    "SHEPHERD Catherine": "shepherd-catherine",
    "SHEPHERD Drey": "shepherd-drey",
    "SHEPHERD Geoff": "shepherd-geoff",
    "SHEPHERD Jack": "shepherd-jack",
    "SHEPHERD John": "shepherd-john",
    "SHEPHERD Kain": "shepherd-kain",
    "SHEPHERD Kristin": "shepherd-kristin",
    "SHEPHERD Michael": "shepherd-michael",
    "SHEPHERD Mike": "shepherd-mike",
    "SHEPLEY Michael": "shepley-michael",
    "SHEPP Archie": "shepp-archie",
    "SHEPPARD Chris": "sheppard-chris",
    "SHEPPARD Clare": "sheppard-clare",
    "SHEPPARD Gabrielle": "sheppard-gabrielle",
    "SHEPPARD Julian": "sheppard-julian",
    "SHEPPARD Pauline": "sheppard-pauline",
    "SHEPPARD Phil": "sheppard-phil",
    "SHEPPARD Robert": "sheppard-robert",
    "SHEPPARD Scott R": "sheppard-scott-r",
    "SHEPPARD T J": "sheppard-t-j",
    "SHEPPEARD David": "sheppeard-david",
    "SHEPPECK Neil": "sheppeck-neil",
    "SHEPPHARD Nona": "shepphard-nona",
    "SHEPTOCK Suzanne": "sheptock-suzanne",
    "SHER Anthony": "sher-anthony",
    "SHER Ben": "sher-ben",
    "SHER Benjamin": "sher-benjamin",
    "SHER Emil": "sher-emil",
    "SHER Jack": "sher-jack",
    "SHER Jeremy": "sher-jeremy",
    "SHER Judith Luck": "sher-judith-luck",
    "SHER Lee": "sher-lee",
    "SHER Stanley": "sher-stanley",
    "SHERBORNE Craig": "sherborne-craig",
    "SHERBUNDY Jason": "sherbundy-jason",
    "SHERER Dan": "sherer-dan",
    "SHERIDAN Andrew": "sheridan-andrew",
    "SHERIDAN Brian E": "sheridan-brian-e",
    "SHERIDAN Damian": "sheridan-damian",
    "SHERIDAN Gerry": "sheridan-gerry",
    "SHERIDAN Jim": "sheridan-jim",
    "SHERIDAN Joanna": "sheridan-joanna",
    "SHERIDAN Keelie": "sheridan-keelie",
    "SHERIDAN Linda": "sheridan-linda",
    "SHERIDAN Mary": "sheridan-mary",
    "SHERIDAN Matthew": "sheridan-matthew",
    "SHERIDAN Niall": "sheridan-niall",
    "SHERIDAN Noel": "sheridan-noel",
    "SHERIDAN Peter": "sheridan-peter",
    "SHERIDAN Philip": "sheridan-philip",
    "SHERIDAN Richard D": "sheridan-richard-d",
    "SHERIDAN Roseann": "sheridan-roseann",
    "SHERIFF David": "sheriff-david",
    "SHERIFF Jack": "sheriff-jack",
    "SHERIFF Noam": "sheriff-noam",
    "SHERIN Justin": "sherin-justin",
    "SHERLEY Emily": "sherley-emily",
    "SHERLOCK Andrew": "sherlock-andrew",
    "SHERLOCK Ceri": "sherlock-ceri",
    "SHERLOCK Di": "sherlock-di",
    "SHERLOCK Maureen": "sherlock-maureen",
    "SHERLOCK Ruth": "sherlock-ruth",
    "SHERMAN Allan": "sherman-allan",
    "SHERMAN Benjamin": "sherman-benjamin",
    "SHERMAN Bob": "sherman-bob",
    "SHERMAN Charles": "sherman-charles",
    "SHERMAN Charley": "sherman-charley",
    "SHERMAN Eileen Bluestone": "sherman-eileen-bluestone",
    "SHERMAN Erik": "sherman-erik",
    "SHERMAN Geoffrey": "sherman-geoffrey",
    "SHERMAN Geraldine": "sherman-geraldine",
    "SHERMAN Gregory": "sherman-gregory",
    "SHERMAN James": "sherman-james",
    "SHERMAN Jason": "sherman-jason",
    "SHERMAN Jimmie": "sherman-jimmie",
    "SHERMAN Jonathan Marc": "sherman-jonathan-marc",
    "SHERMAN Joseph": "sherman-joseph",
    "SHERMAN Josh": "sherman-josh",
    "SHERMAN Katharine": "sherman-katharine",
    "SHERMAN Malcolm": "sherman-malcolm",
    "SHERMAN Margo Lee": "sherman-margo-lee",
    "SHERMAN Martin": "sherman-martin",
    "SHERMAN Mike": "sherman-mike",
    "SHERMAN Patrick Jones": "sherman-patrick-jones",
    "SHERMAN Paul": "sherman-paul",
    "SHERMAN Peter": "sherman-peter",
    "SHERMAN Richard M": "sherman-richard-m",
    "SHERMAN Robert Al": "sherman-robert-al",
    "SHERMAN Robert B": "sherman-robert-b",
    "SHERMAN Robert J": "sherman-robert-j",
    "SHERMAN Sandy": "sherman-sandy",
    "SHERMAN Steve": "sherman-steve",
    "SHERMAN Stuart": "sherman-stuart",
    "SHERMAN Susan": "sherman-susan",
    "SHERMAN THEATRE COMPANY ": "sherman-theatre-company",
    "SHERR Jessica": "sherr-jessica",
    "SHERRARD Patrick": "sherrard-patrick",
    "SHERRAT Anna": "sherrat-anna",
    "SHERRIFF R C": "sherriff-r-c",
    "SHERRIN Ned": "sherrin-ned",
    "SHERRY John": "sherry-john",
    "SHERRY Peggy Meyer": "sherry-peggy-meyer",
    "SHERRYDEN Joanne": "sherryden-joanne",
    "SHERR-ZIARKO Emma": "sherr-ziarko-emma",
    "SHERSTINSKY Mark": "sherstinsky-mark",
    "SHERWIN Walter": "sherwin-walter",
    "SHERWOOD John": "sherwood-john",
    "SHERWOOD Kendall": "sherwood-kendall",
    "SHERWOOD Normandy Raven": "sherwood-normandy-raven",
    "SHERWOOD R A": "sherwood-r-a",
    "SHERWOOD Robert E": "sherwood-robert-e",
    "SHERWOOD Robert William": "sherwood-robert-william",
    "SHESHGELANI Elnaz": "sheshgelani-elnaz",
    "SHESHKALANI Saba": "sheshkalani-saba",
    "SHEVCHENKI Taras": "shevchenki-taras",
    "SHEVELOVE Burt": "shevelove-burt",
    "SHEVLIN Bernie": "shevlin-bernie",
    "SHEWELL Debbie": "shewell-debbie",
    "SHI Hu": "shi-hu",
    "SHIBLI Adania": "shibli-adania",
    "SHIDELER Ross": "shideler-ross",
    "SHIEL Graham": "shiel-graham",
    "SHIELD Harvey": "shield-harvey",
    "SHIELDS Carol": "shields-carol",
    "SHIELDS Catherine": "shields-catherine",
    "SHIELDS Frank": "shields-frank",
    "SHIELDS Henry": "shields-henry",
    "SHIELDS Lawrence": "shields-lawrence",
    "SHIELDS Malcolm": "shields-malcolm",
    "SHIELDS Sue": "shields-sue",
    "SHIELDS Tim": "shields-tim",
    "SHIELS George": "shiels-george",
    "SHIELS Ronan": "shiels-ronan",
    "SHIEN Brian": "shien-brian",
    "SHIENMEL Richard": "shienmel-richard",
    "SHIFENG Zheng": "shifeng-zheng",
    "SHIFFRIN A B": "shiffrin-a-b",
    "SHIFTING SANDS ": "shifting-sands",
    "SHIGENOBU Takaaki": "shigenobu-takaaki",
    "SHIH David": "shih-david",
    "SHIKINA Alice": "shikina-alice",
    "SHILL Steve": "shill-steve",
    "SHILLING Diane": "shilling-diane",
    "SHILLING Jason": "shilling-jason",
    "SHILLING Michael": "shilling-michael",
    "SHILLINGFORD Vicky": "shillingford-vicky",
    "SHILSON Ally": "shilson-ally",
    "SHILTO Ann Marie": "shilto-ann-marie",
    "SHILTON Paul": "shilton-paul",
    "SHIMANO Kirk": "shimano-kirk",
    "SHIMIZU Kunio": "shimizu-kunio",
    "SHIMKOVITZ Melissa": "shimkovitz-melissa",
    "SHIN Rob": "shin-rob",
    "SHINDLER Amy": "shindler-amy",
    "SHINE Ted": "shine-ted",
    "SHINEMAN Kirt": "shineman-kirt",
    "SHINER David": "shiner-david",
    "SHINER Malcolm": "shiner-malcolm",
    "SHINICK Kevin": "shinick-kevin",
    "SHINKAI Bill": "shinkai-bill",
    "SHINN Christopher": "shinn-christopher",
    "SHINOZUKA Megumi": "shinozuka-megumi",
    "SHIOMI R A": "shiomi-r-a",
    "SHIPLEY Lisa": "shipley-lisa",
    "SHIPLEY Sharyn": "shipley-sharyn",
    "SHIPMAN Dee": "shipman-dee",
    "SHIPMAN Willie B": "shipman-willie-b",
    "SHIRE David": "shire-david",
    "SHIREE Royal": "shiree-royal",
    "SHIREEN Deen": "shireen-deen",
    "SHIRIAN Shawn": "shirian-shawn",
    "SHIRLEY James": "shirley-james",
    "SHIRLEY Joan": "shirley-joan",
    "SHIRLEY Rae": "shirley-rae",
    "SHIROTA Jon": "shirota-jon",
    "SHIRRA Fiona": "shirra-fiona",
    "SHIRREFF David": "shirreff-david",
    "SHITAMOTO Elbert Manabu": "shitamoto-elbert-manabu",
    "SHIVELY Sarah": "shively-sarah",
    "SHKOLNIK Tom": "shkolnik-tom",
    "SHOAF Brian": "shoaf-brian",
    "SHOBA Naomi": "shoba-naomi",
    "SHOBERG James Michael": "shoberg-james-michael",
    "SHOCHIKU KABUKI COMPANY ": "shochiku-kabuki-company",
    "SHOCKLEY Ed": "shockley-ed",
    "SHOEMAKE Cory D": "shoemake-cory-d",
    "SHOFFNER Andrew": "shoffner-andrew",
    "SHOGO Ota": "shogo-ota",
    "SHOHAM Sigal": "shoham-sigal",
    "SHOLITON Faye": "sholiton-faye",
    "SHOLLEY Nick": "sholley-nick",
    "SHOMOV Roumen": "shomov-roumen",
    "SHONE James": "shone-james",
    "SHONTEL Rie": "shontel-rie",
    "SHOOK Estelle": "shook-estelle",
    "SHOOP Jo": "shoop-jo",
    "SHOPFRONT THEATRE FOR YOUNG PEOPLE ": "shopfront-theatre-for-young-people",
    "SHOPLAND David": "shopland-david",
    "SHORE Dan": "shore-dan",
    "SHORE Gary": "shore-gary",
    "SHORE Jake": "shore-jake",
    "SHORE Robert": "shore-robert",
    "SHORE Sam": "shore-sam",
    "SHORE Talia": "shore-talia",
    "SHORES Del": "shores-del",
    "SHORT Christopher": "short-christopher",
    "SHORT David": "short-david",
    "SHORT Donn": "short-donn",
    "SHORT Kevin": "short-kevin",
    "SHORT Marion": "short-marion",
    "SHORT Martin": "short-martin",
    "SHORT Quincy": "short-quincy",
    "SHORT Robin": "short-robin",
    "SHORT Ron": "short-ron",
    "SHORT TERM VISITOR PARKING ": "short-term-visitor-parking",
    "SHORTLAND Gaye": "shortland-gaye",
    "SHORTT Marion": "shortt-marion",
    "SHORTY Robert": "shorty-robert",
    "SHORTY Sharon": "shorty-sharon",
    "SHOSHAN Daniella": "shoshan-daniella",
    "SHOSHANNA Brenda": "shoshanna-brenda",
    "SHOSHANNA Yolanda": "shoshanna-yolanda",
    "SHOTLANDER Sandra": "shotlander-sandra",
    "SHOTWELL Judith": "shotwell-judith",
    "SHOUCHENG Li": "shoucheng-li",
    "SHOUFUKUTEI Showko": "shoufukutei-showko",
    "SHOULBERG Paul": "shoulberg-paul",
    "SHOULDICE Frank": "shouldice-frank",
    "SHOUT, THE ": "shout",
    "SHOWALTER Bob": "showalter-bob",
    "SHOWALTER Michael": "showalter-michael",
    "SHOWERS Susie": "showers-susie",
    "SHPILBERG Nikita": "shpilberg-nikita",
    "SHRAGGE Joseph": "shragge-joseph",
    "SHRATTER Jocelyn": "shratter-jocelyn",
    "SHREEVE Nathan": "shreeve-nathan",
    "SHRIER Zachary L": "shrier-zachary-l",
    "SHRIMPTON Martha": "shrimpton-martha",
    "SHRON Marina": "shron-marina",
    "SHROSBREE Ann": "shrosbree-ann",
    "SHRUBSHALL Peter": "shrubshall-peter",
    "SHRUBSOLE Nathan": "shrubsole-nathan",
    "SHTILIANOVA Lyubov": "shtilianova-lyubov",
    "SHUBERT John": "shubert-john",
    "SHUCAVAGE Milo": "shucavage-milo",
    "SHUDRAKA ": "shudraka",
    "SHUE Larry": "shue-larry",
    "SHUKERT Rachel": "shukert-rachel",
    "SHULER Jacob": "shuler-jacob",
    "SHULL Leo": "shull-leo",
    "SHULL Rebecca": "shull-rebecca",
    "SHULMAN Art": "shulman-art",
    "SHULMAN Max": "shulman-max",
    "SHULMAN Misha": "shulman-misha",
    "SHULMAN Morley": "shulman-morley",
    "SHULMAN Sarah": "shulman-sarah",
    "SHUMAN David": "shuman-david",
    "SHUMAN Earl": "shuman-earl",
    "SHUMAN Mort": "shuman-mort",
    "SHUMAN William": "shuman-william",
    "SHUMLIN Herman": "shumlin-herman",
    "SHUNT COLLECTIVE ": "shunt-collective",
    "SHUR Paulina": "shur-paulina",
    "SHURE Robert": "shure-robert",
    "SHURLING John": "shurling-john",
    "SHURTLEFF Michael": "shurtleff-michael",
    "SHURTZ Raymond King": "shurtz-raymond-king",
    "SHUTT Helen": "shutt-helen",
    "SHUTT Michael": "shutt-michael",
    "SHUTTLEWORTH Red": "shuttleworth-red",
    "SHVETSOV Arnold": "shvetsov-arnold",
    "SHYER Marlene Fanta": "shyer-marlene-fanta",
    "SHYRE Paul": "shyre-paul",
    "SHYSTERS, THE ": "shysters",
    "SHYZER Mark": "shyzer-mark",
    "SIADAT Fahad": "siadat-fahad",
    "SIAN Jessica": "sian-jessica",
    "SIBAI Hannah": "sibai-hannah",
    "SIBBALD George": "sibbald-george",
    "SIBBING Karen": "sibbing-karen",
    "SIBERELL Anne": "siberell-anne",
    "SIBLEY Brian": "sibley-brian",
    "SIBLEY Danielle": "sibley-danielle",
    "SIBLEY Eli": "sibley-eli",
    "SIBLEYRAS Gerald": "sibleyras-gerald",
    "SICES David": "sices-david",
    "SICHEL Kate": "sichel-kate",
    "SICHROVSKY Peter": "sichrovsky-peter",
    "SICKINGER Robert": "sickinger-robert",
    "SICKLES Scott C": "sickles-scott-c",
    "SICKMAN Mark": "sickman-mark",
    "SIDAWAY Marlene": "sidaway-marlene",
    "SIDDIQUI Aamera": "siddiqui-aamera",
    "SIDDIQUI Irfan": "siddiqui-irfan",
    "SIDDIQUI Mugeeb": "siddiqui-mugeeb",
    "SIDDONS Annie": "siddons-annie",
    "SIDE Richard": "side-richard",
    "SIDENBLADH Cecilia": "sidenbladh-cecilia",
    "SIDETRACK PERFORMANCE GROUP, THE ": "sidetrack-performance-group",
    "SIDETRACK THEATRE ": "sidetrack-theatre",
    "SIDGWICK Jonathan": "sidgwick-jonathan",
    "SIDHU Ranbir": "sidhu-ranbir",
    "SIDHWA Bapsi": "sidhwa-bapsi",
    "SIDHWA Yasmin": "sidhwa-yasmin",
    "SIDIROPOULOU Avra": "sidiropoulou-avra",
    "SIDNEY Terry": "sidney-terry",
    "SIDOTI Deanne": "sidoti-deanne",
    "SIE James": "sie-james",
    "SIEBEKING Brad": "siebeking-brad",
    "SIEBEN Pearl": "sieben-pearl",
    "SIEBERS Pierce": "siebers-pierce",
    "SIEBURTH Richard": "sieburth-richard",
    "SIEDMAN Eileen": "siedman-eileen",
    "SIEDMAN Robin": "siedman-robin",
    "SIEFERT Lynn": "siefert-lynn",
    "SIEFKEN Paul": "siefken-paul",
    "SIEG Katrin": "sieg-katrin",
    "SIEGAL Adam": "siegal-adam",
    "SIEGAL June": "siegal-june",
    "SIEGE PERILOUS ": "siege-perilous",
    "SIEGEL Carolyn": "siegel-carolyn",
    "SIEGEL D L": "siegel-d-l",
    "SIEGEL Jack": "siegel-jack",
    "SIEGEL Joel": "siegel-joel",
    "SIEGEL June": "siegel-june",
    "SIEGEL Larry": "siegel-larry",
    "SIEGEL Robert": "siegel-robert",
    "SIEGER Josef": "sieger-josef",
    "SIEGLER John": "siegler-john",
    "SIEH Kristen": "sieh-kristen",
    "SIEMENS Paul": "siemens-paul",
    "SIEMS Christin": "siems-christin",
    "SIENA James": "siena-james",
    "SIENEN Jonathan": "sienen-jonathan",
    "SIERENS Arne": "sierens-arne",
    "SIERRA Ruben": "sierra-ruben",
    "SIERRA Silvia": "sierra-silvia",
    "SIERZ Aleks": "sierz-aleks",
    "SIEVEKING Lance": "sieveking-lance",
    "SIEVERS Cameron": "sievers-cameron",
    "SIEWERT John": "siewert-john",
    "SIFFRE Labi": "siffre-labi",
    "SIFTON Claire": "sifton-claire",
    "SIFTON Paul": "sifton-paul",
    "SIGAL Sarah": "sigal-sarah",
    "SIGANOU-PARREN Kalliroi": "siganou-parren-kalliroi",
    "SIGAREV Vassily": "sigarev-vassily",
    "SIGGS Sam": "siggs-sam",
    "SIGL Matt": "sigl-matt",
    "SIGLEY Marjorie": "sigley-marjorie",
    "SIGNES Emil": "signes-emil",
    "SIGRID Jean": "sigrid-jean",
    "SIGUENZA Herbert": "siguenza-herbert",
    "SIKORA Adam": "sikora-adam",
    "SIKORA Stefan": "sikora-stefan",
    "SIKORSKA-MISZCZUK Malgorzata": "sikorska-miszczuk-malgorzata",
    "SIKORSKI Joy": "sikorski-joy",
    "SILAS Shelley": "silas-shelley",
    "SILBERG Bob": "silberg-bob",
    "SILBERG David": "silberg-david",
    "SILBERMAN Brian": "silberman-brian",
    "SILBERMAN Cori": "silberman-cori",
    "SILBERMAN Erica": "silberman-erica",
    "SILBERMAN Joel": "silberman-joel",
    "SILBERT Carla": "silbert-carla",
    "SILBERT Roxana": "silbert-roxana",
    "SILC Kathleen Flannery": "silc-kathleen-flannery",
    "SILENCE Mark": "silence-mark",
    "SILER Betty": "siler-betty",
    "SILER Ric": "siler-ric",
    "SILIPO Domenic": "silipo-domenic",
    "SILK Avril": "silk-avril",
    "SILK Ilkay": "silk-ilkay",
    "SILKIN Jon": "silkin-jon",
    "SILKO ": "silko",
    "SILL Alastair": "sill-alastair",
    "SILL Louise Morgan": "sill-louise-morgan",
    "SILL Peter": "sill-peter",
    "SILLIMAN Brian": "silliman-brian",
    "SILLIMAN Michael": "silliman-michael",
    "SILLITOE Alan": "sillitoe-alan",
    "SILLS Paul": "sills-paul",
    "SILO THEATRE ": "silo-theatre",
    "SILOVSKY Joseph": "silovsky-joseph",
    "SILPA Mitch": "silpa-mitch",
    "SILSBY Joan": "silsby-joan",
    "SILVA Dan": "silva-dan",
    "SILVA Hannah": "silva-hannah",
    "SILVA R Ernie": "silva-r-ernie",
    "SILVA Redley": "silva-redley",
    "SILVA Sasha": "silva-sasha",
    "SILVA Veronica": "silva-veronica",
    "SILVER Alf": "silver-alf",
    "SILVER Alisha": "silver-alisha",
    "SILVER Ben": "silver-ben",
    "SILVER Cynthia": "silver-cynthia",
    "SILVER Doug": "silver-doug",
    "SILVER Fred": "silver-fred",
    "SILVER Joan Micklin": "silver-joan-micklin",
    "SILVER Lauren": "silver-lauren",
    "SILVER Nicky": "silver-nicky",
    "SILVER R S": "silver-r-s",
    "SILVER Rachel": "silver-rachel",
    "SILVER Richard": "silver-richard",
    "SILVER Steve": "silver-steve",
    "SILVER Stuart": "silver-stuart",
    "SILVER Tina": "silver-tina",
    "SILVER Toni": "silver-toni",
    "SILVERBERG Marc": "silverberg-marc",
    "SILVERBRAND Dave": "silverbrand-dave",
    "SILVERIO Iris": "silverio-iris",
    "SILVERMAN Alex": "silverman-alex",
    "SILVERMAN Bret": "silverman-bret",
    "SILVERMAN David": "silverman-david",
    "SILVERMAN Ethan": "silverman-ethan",
    "SILVERMAN Jen": "silverman-jen",
    "SILVERMAN Judd Lear": "silverman-judd-lear",
    "SILVERMAN Leigh": "silverman-leigh",
    "SILVERMAN Rachel": "silverman-rachel",
    "SILVERMAN Sarah": "silverman-sarah",
    "SILVERMAN Stan": "silverman-stan",
    "SILVERMAN Steve": "silverman-steve",
    "SILVERSHER Michael": "silversher-michael",
    "SILVERSON P K": "silverson-p-k",
    "SILVERSTEIN Matt": "silverstein-matt",
    "SILVERSTEIN Shel": "silverstein-shel",
    "SILVERSTON Sandra": "silverston-sandra",
    "SILVERSTONE Michael": "silverstone-michael",
    "SILVESTRI Linda": "silvestri-linda",
    "SILVESTRINI Luca": "silvestrini-luca",
    "SILVIA Marc": "silvia-marc",
    "SILVIO Joe": "silvio-joe",
    "SILVIS Steffen": "silvis-steffen",
    "SIM Edward": "sim-edward",
    "SIMARD Andre": "simard-andre",
    "SIMARD Claire": "simard-claire",
    "SIMCKES Lazarre Seymour": "simckes-lazarre-seymour",
    "SIMCKES-JOFFE Hebron": "simckes-joffe-hebron",
    "SIMCOE Anthony": "simcoe-anthony",
    "SIME Lemn": "sime-lemn",
    "SIME Tom": "sime-tom",
    "SIMEK Stepan": "simek-stepan",
    "SIMELANE Thuli": "simelane-thuli",
    "SIMEON Christian": "simeon-christian",
    "SIMEON Roger": "simeon-roger",
    "SIMIC Lucy": "simic-lucy",
    "SIMINOVITCH Elinore": "siminovitch-elinore",
    "SIMKIN Peter": "simkin-peter",
    "SIMKINS Michael": "simkins-michael",
    "SIMKOVICH Caitlin": "simkovich-caitlin",
    "SIMMON Ken": "simmon-ken",
    "SIMMONDS Catherine": "simmonds-catherine",
    "SIMMONDS Hazel": "simmonds-hazel",
    "SIMMONDS Lake": "simmonds-lake",
    "SIMMONDS Peter": "simmonds-peter",
    "SIMMONS Ben": "simmons-ben",
    "SIMMONS Bret": "simmons-bret",
    "SIMMONS Candy": "simmons-candy",
    "SIMMONS Chris": "simmons-chris",
    "SIMMONS David": "simmons-david",
    "SIMMONS Dawn M": "simmons-dawn-m",
    "SIMMONS Forrest": "simmons-forrest",
    "SIMMONS Keith": "simmons-keith",
    "SIMMONS Kristy": "simmons-kristy",
    "SIMMONS Lydia": "simmons-lydia",
    "SIMMONS Mark-Leonard": "simmons-mark-leonard",
    "SIMMONS Paulanne": "simmons-paulanne",
    "SIMMONS Peggy": "simmons-peggy",
    "SIMMONS Pip": "simmons-pip",
    "SIMMONS Ria": "simmons-ria",
    "SIMMONS Wanda": "simmons-wanda",
    "SIMMONS, JR Godfrey L": "simmons-jr-godfrey-l",
    "SIMMS Gordon": "simms-gordon",
    "SIMMS Hugo": "simms-hugo",
    "SIMMS Joseph": "simms-joseph",
    "SIMMS Laura": "simms-laura",
    "SIMMS Ryiesha": "simms-ryiesha",
    "SIMMS Willard": "simms-willard",
    "SIMNER Barry": "simner-barry",
    "SIMO Ana Maria": "simo-ana-maria",
    "SIMON Adam": "simon-adam",
    "SIMON Amy": "simon-amy",
    "SIMON Andrea": "simon-andrea",
    "SIMON Andrew": "simon-andrew",
    "SIMON Barney": "simon-barney",
    "SIMON C": "simon-c",
    "SIMON C K": "simon-c-k",
    "SIMON Cliff": "simon-cliff",
    "SIMON Collin": "simon-collin",
    "SIMON Daniel": "simon-daniel",
    "SIMON Edith": "simon-edith",
    "SIMON Ellen": "simon-ellen",
    "SIMON Emily": "simon-emily",
    "SIMON Eric": "simon-eric",
    "SIMON Gladys": "simon-gladys",
    "SIMON Hugh": "simon-hugh",
    "SIMON John": "simon-john",
    "SIMON Katie": "simon-katie",
    "SIMON Laura": "simon-laura",
    "SIMON Lauren": "simon-lauren",
    "SIMON Levy Lee": "simon-levy-lee",
    "SIMON Lojo": "simon-lojo",
    "SIMON Lucy": "simon-lucy",
    "SIMON Luke": "simon-luke",
    "SIMON Marc": "simon-marc",
    "SIMON Mayo": "simon-mayo",
    "SIMON Michael": "simon-michael",
    "SIMON Nancy": "simon-nancy",
    "SIMON Neil": "simon-neil",
    "SIMON Noah": "simon-noah",
    "SIMON Paul": "simon-paul",
    "SIMON Richard": "simon-richard",
    "SIMON Richard L": "simon-richard-l",
    "SIMON Robert A": "simon-robert-a",
    "SIMON Samuel Alan": "simon-samuel-alan",
    "SIMON Sidney": "simon-sidney",
    "SIMON Steven": "simon-steven",
    "SIMON Zoe": "simon-zoe",
    "SIMON JR Levy Lee": "simon-jr-levy-lee",
    "SIMONA Sandy": "simona-sandy",
    "SIMONARSON Olafur Haukur": "simonarson-olafur-haukur",
    "SIMONCIC Steven": "simoncic-steven",
    "SIMONE Max": "simone-max",
    "SIMONE Nedra": "simone-nedra",
    "SIMONELLI Joe": "simonelli-joe",
    "SIMONOV Konstantin": "simonov-konstantin",
    "SIMONOVIC Gus": "simonovic-gus",
    "SIMONS Anita Yellin": "simons-anita-yellin",
    "SIMONS Bethany": "simons-bethany",
    "SIMONS Beverley": "simons-beverley",
    "SIMONS David": "simons-david",
    "SIMONS Jez": "simons-jez",
    "SIMONS John": "simons-john",
    "SIMONS Johnny": "simons-johnny",
    "SIMONS Josh": "simons-josh",
    "SIMONS Lake": "simons-lake",
    "SIMONS Manuel": "simons-manuel",
    "SIMONSEN Christian": "simonsen-christian",
    "SIMONSON Eric": "simonson-eric",
    "SIMONSON Karen": "simonson-karen",
    "SIMONSON Robert": "simonson-robert",
    "SIMPATICO David": "simpatico-david",
    "SIMPER Doug": "simper-doug",
    "SIMPKINS Michael": "simpkins-michael",
    "SIMPLE 8 ": "simple-8",
    "SIMPSON Alaine": "simpson-alaine",
    "SIMPSON Alan": "simpson-alan",
    "SIMPSON Aubrey": "simpson-aubrey",
    "SIMPSON Bland": "simpson-bland",
    "SIMPSON Brett": "simpson-brett",
    "SIMPSON Brock": "simpson-brock",
    "SIMPSON Caroline": "simpson-caroline",
    "SIMPSON Charly E": "simpson-charly-e",
    "SIMPSON Christine": "simpson-christine",
    "SIMPSON Dave": "simpson-dave",
    "SIMPSON Diana": "simpson-diana",
    "SIMPSON Ed": "simpson-ed",
    "SIMPSON Evan": "simpson-evan",
    "SIMPSON Fay": "simpson-fay",
    "SIMPSON Gerry": "simpson-gerry",
    "SIMPSON Gus": "simpson-gus",
    "SIMPSON H": "simpson-h",
    "SIMPSON Jeanmarie": "simpson-jeanmarie",
    "SIMPSON Kamal": "simpson-kamal",
    "SIMPSON Kristen": "simpson-kristen",
    "SIMPSON Lee": "simpson-lee",
    "SIMPSON Lesley Bird": "simpson-lesley-bird",
    "SIMPSON Linda": "simpson-linda",
    "SIMPSON Louis": "simpson-louis",
    "SIMPSON Maggie": "simpson-maggie",
    "SIMPSON Mark": "simpson-mark",
    "SIMPSON N": "simpson-n",
    "SIMPSON N F": "simpson-n-f",
    "SIMPSON Pete": "simpson-pete",
    "SIMPSON Robin": "simpson-robin",
    "SIMPSON Samuel E": "simpson-samuel-e",
    "SIMPSON Shari": "simpson-shari",
    "SIMPSON Thomas": "simpson-thomas",
    "SIMPSON Tim": "simpson-tim",
    "SIMS Julian": "sims-julian",
    "SIMS Mark": "sims-mark",
    "SIMS Marley": "sims-marley",
    "SIMS Neal": "sims-neal",
    "SIMS Rootie": "sims-rootie",
    "SIMULCIK JR Richard": "simulcik-jr-richard",
    "SINCERA PRODUCTIONS ": "sincera-productions",
    "SINCLAIR Alison": "sinclair-alison",
    "SINCLAIR Andrew": "sinclair-andrew",
    "SINCLAIR Bruce": "sinclair-bruce",
    "SINCLAIR Carol": "sinclair-carol",
    "SINCLAIR Frances": "sinclair-frances",
    "SINCLAIR Frederic": "sinclair-frederic",
    "SINCLAIR Gabrielle": "sinclair-gabrielle",
    "SINCLAIR Greg": "sinclair-greg",
    "SINCLAIR Harry": "sinclair-harry",
    "SINCLAIR Ian": "sinclair-ian",
    "SINCLAIR Lister": "sinclair-lister",
    "SINCLAIR Naomi": "sinclair-naomi",
    "SINCLAIR Samara": "sinclair-samara",
    "SINCLAIR Sasha": "sinclair-sasha",
    "SINCLAIR Stephen": "sinclair-stephen",
    "SINCLAIR Tracey": "sinclair-tracey",
    "SINCLAIRE Stephanie": "sinclaire-stephanie",
    "SINDELAR Shannon": "sindelar-shannon",
    "SINDELAR Susan": "sindelar-susan",
    "SINELNIKOFF Michael": "sinelnikoff-michael",
    "SINENSKY Joel": "sinensky-joel",
    "SINGER Blair": "singer-blair",
    "SINGER Campbell": "singer-campbell",
    "SINGER Daniel Rover": "singer-daniel-rover",
    "SINGER David S": "singer-david-s",
    "SINGER Elyse": "singer-elyse",
    "SINGER George": "singer-george",
    "SINGER Isaac Bashevis": "singer-isaac-bashevis",
    "SINGER Matt": "singer-matt",
    "SINGER Matty": "singer-matty",
    "SINGER Nicky": "singer-nicky",
    "SINGER Toby": "singer-toby",
    "SINGER Walter": "singer-walter",
    "SINGH Ashwin": "singh-ashwin",
    "SINGH Binda": "singh-binda",
    "SINGH Daljeet": "singh-daljeet",
    "SINGH Daljinder": "singh-daljinder",
    "SINGH Harmage": "singh-harmage",
    "SINGH Jitender": "singh-jitender",
    "SINGH Kay": "singh-kay",
    "SINGH Latvair": "singh-latvair",
    "SINGH Parminder": "singh-parminder",
    "SINGH R P": "singh-r-p",
    "SINGH Salman": "singh-salman",
    "SINGHARAY Ayndrilla": "singharay-ayndrilla",
    "SINGLE CARROT THEATRE ": "single-carrot-theatre",
    "SINGLETON Brian": "singleton-brian",
    "SINGLETON Erin": "singleton-erin",
    "SINGLETON Hannah": "singleton-hannah",
    "SINGLETON Jacqui": "singleton-jacqui",
    "SINGLETON Pat": "singleton-pat",
    "SINGTON Philip": "sington-philip",
    "SINHA Shamser": "sinha-shamser",
    "SINISSAAR Triin": "sinissaar-triin",
    "SINISTERRA Jose Sanchis": "sinisterra-jose-sanchis",
    "SINNER John": "sinner-john",
    "SINNOTT John": "sinnott-john",
    "SINNOTT Richard": "sinnott-richard",
    "SIPLING Dean": "sipling-dean",
    "SIPOS F J": "sipos-f-j",
    "SIPOS Jen": "sipos-jen",
    "SIPOS Liza": "sipos-liza",
    "SIRAGO Saul Paul": "sirago-saul-paul",
    "SIRCHROVSKY Peter": "sirchrovsky-peter",
    "SIRCOM Malcolm": "sircom-malcolm",
    "SIRERA Rodolf": "sirera-rodolf",
    "SIRETT Paul": "sirett-paul",
    "SIRIOLJOYNER ": "sirioljoyner",
    "SIRIU Maria Virginia": "siriu-maria-virginia",
    "SIRK David": "sirk-david",
    "SIRKER Jamuna Yvette": "sirker-jamuna-yvette",
    "SIROIS David Michael": "sirois-david-michael",
    "SIROIS Serge": "sirois-serge",
    "SIRONEN Gary": "sironen-gary",
    "SIROTA Eric B": "sirota-eric-b",
    "SIROTSKY Shirley": "sirotsky-shirley",
    "SISCO David": "sisco-david",
    "SISK Amanda": "sisk-amanda",
    "SISKIND Leda": "siskind-leda",
    "SISKIND Samara": "siskind-samara",
    "SISLEN Stephen": "sislen-stephen",
    "SISSAY Lemn": "sissay-lemn",
    "SISSLE Noble": "sissle-noble",
    "SISSMAN Terri": "sissman-terri",
    "SISSOM Tara": "sissom-tara",
    "SISSON C H": "sisson-c-h",
    "SISSON David": "sisson-david",
    "SISSON Richard": "sisson-richard",
    "SISSON Rosemary Anne": "sisson-rosemary-anne",
    "SISSONS Neil": "sissons-neil",
    "SISSONS Tara": "sissons-tara",
    "SISTER SYLVESTER ": "sister-sylvester",
    "SISTREN ": "sistren",
    "SITHOLE Tawone": "sithole-tawone",
    "SITKO Mark": "sitko-mark",
    "SITZMAN Steven E": "sitzman-steven-e",
    "SIVAK Tom": "sivak-tom",
    "SIVEKING Lance": "siveking-lance",
    "SIVITER Bill": "siviter-bill",
    "SIX Kevin": "six-kevin",
    "SIX Lidy": "six-lidy",
    "SIZE Michelle": "size-michelle",
    "SIZEMORE Jim": "sizemore-jim",
    "SIZEMORE Mike": "sizemore-mike",
    "SJOERDAMA Anne G": "sjoerdama-anne-g",
    "SJOERDSMA Al": "sjoerdsma-al",
    "SJOLIE SVEEN Amund": "sjolie-sveen-amund",
    "SKAGGS Randi": "skaggs-randi",
    "SKALA Libby": "skala-libby",
    "SKARMETA Antonio": "skarmeta-antonio",
    "SKARVELIS Jackie": "skarvelis-jackie",
    "SKARVELLIS J": "skarvellis-j",
    "SKATES Sina": "skates-sina",
    "SKEEF Eugene": "skeef-eugene",
    "SKEELE David": "skeele-david",
    "SKEKLERS TC ": "skeklers-tc",
    "SKELLERN Peter": "skellern-peter",
    "SKELLEY Michael": "skelley-michael",
    "SKELLY Michael": "skelly-michael",
    "SKELTON Geoffrey": "skelton-geoffrey",
    "SKELTON Ian": "skelton-ian",
    "SKELTON John": "skelton-john",
    "SKERRITT Gavin": "skerritt-gavin",
    "SKETTY THEATRE ": "sketty-theatre",
    "SKIBELL Joseph": "skibell-joseph",
    "SKIDMORE Pete": "skidmore-pete",
    "SKIDMORE Steve": "skidmore-steve",
    "SKILBECK Alison": "skilbeck-alison",
    "SKILBECK Lucy": "skilbeck-lucy",
    "SKILL Marjorie": "skill-marjorie",
    "SKILLEN Daphne": "skillen-daphne",
    "SKILLMAN Crystal": "skillman-crystal",
    "SKINNER Alisdair": "skinner-alisdair",
    "SKINNER Beth": "skinner-beth",
    "SKINNER Chris": "skinner-chris",
    "SKINNER Constance": "skinner-constance",
    "SKINNER Cornelia Otis": "skinner-cornelia-otis",
    "SKINNER Eliza": "skinner-eliza",
    "SKINNER Jeffrey": "skinner-jeffrey",
    "SKINNER Jonathan": "skinner-jonathan",
    "SKINNER Mark": "skinner-mark",
    "SKINNER Penelope": "skinner-penelope",
    "SKINNER Ryan": "skinner-ryan",
    "SKIPITARES Theodora": "skipitares-theodora",
    "SKIP-NEWELL Glen": "skip-newell-glen",
    "SKIRBOLL Melissa": "skirboll-melissa",
    "SKIRTED ISSUE ": "skirted-issue",
    "SKITCH Liz": "skitch-liz",
    "SKJOLD Soren": "skjold-soren",
    "SKLAIRE Karen": "sklaire-karen",
    "SKLAR David": "sklar-david",
    "SKLAR George": "sklar-george",
    "SKLAR Matthew": "sklar-matthew",
    "SKLOOT Rebecca": "skloot-rebecca",
    "SKOFF Judah": "skoff-judah",
    "SKOLNICK Zan": "skolnick-zan",
    "SKOREYKO Johanna": "skoreyko-johanna",
    "SKOUEN Arne": "skouen-arne",
    "SKOURTIS George": "skourtis-george",
    "SKRAASTAD Danielle": "skraastad-danielle",
    "SKRAM Amelie": "skram-amelie",
    "SKRETCH Keith": "skretch-keith",
    "SKRYNKA Stephen": "skrynka-stephen",
    "SKRZYPCZYK Zenon": "skrzypczyk-zenon",
    "SKUBIK Anna": "skubik-anna",
    "SKUBINNA David": "skubinna-david",
    "SKUGGEVIK Erik": "skuggevik-erik",
    "SKULLDUGGERY TC ": "skullduggery-tc",
    "SKULNICK Gregory": "skulnick-gregory",
    "SKURA Jennifer": "skura-jennifer",
    "SKVALA Dave": "skvala-dave",
    "SKY Sabri": "sky-sabri",
    "SKYDELL Deborah": "skydell-deborah",
    "SKYLER Tristine": "skyler-tristine",
    "SLABE Joe": "slabe-joe",
    "SLABOLEPSZY Paul": "slabolepszy-paul",
    "SLACK Kevin": "slack-kevin",
    "SLACK Matt": "slack-matt",
    "SLACK-EATON Jennifer": "slack-eaton-jennifer",
    "SLADE Bernard": "slade-bernard",
    "SLADE Julian": "slade-julian",
    "SLADE Laurie": "slade-laurie",
    "SLADE Marlain": "slade-marlain",
    "SLADE Michael": "slade-michael",
    "SLADE Stuart": "slade-stuart",
    "SLADE Susan": "slade-susan",
    "SLADE-JONES Rhys": "slade-jones-rhys",
    "SLADEK Milan": "sladek-milan",
    "SLADEN Gavin": "sladen-gavin",
    "SLADEN-SMITH Frank": "sladen-smith-frank",
    "SLAFF Jerry": "slaff-jerry",
    "SLAIGHT Brad": "slaight-brad",
    "SLAN Sam": "slan-sam",
    "SLANT GROUP ": "slant-group",
    "SLAPIKOFF Saul": "slapikoff-saul",
    "SLATER Arnold": "slater-arnold",
    "SLATER Barry": "slater-barry",
    "SLATER Clare": "slater-clare",
    "SLATER Douglas": "slater-douglas",
    "SLATER Elaine": "slater-elaine",
    "SLATER Ethan": "slater-ethan",
    "SLATER Glenn": "slater-glenn",
    "SLATER Ian": "slater-ian",
    "SLATER John D": "slater-john-d",
    "SLATER Katy": "slater-katy",
    "SLATER Maya": "slater-maya",
    "SLATER Michael": "slater-michael",
    "SLATER Paul": "slater-paul",
    "SLATER Simon": "slater-simon",
    "SLATER Steven": "slater-steven",
    "SLATER Tom": "slater-tom",
    "SLATKIN Marcia": "slatkin-marcia",
    "SLATTERY Ken": "slattery-ken",
    "SLATTERY Luke": "slattery-luke",
    "SLATTERY-CHRISTY David": "slattery-christy-david",
    "SLATTNE Hanna": "slattne-hanna",
    "SLAUGHTER Billy": "slaughter-billy",
    "SLAUGHTER Frank Gill": "slaughter-frank-gill",
    "SLAVEYKOV Jordan": "slaveykov-jordan",
    "SLAVICK Jason": "slavick-jason",
    "SLAVIN Helen": "slavin-helen",
    "SLAVKIN Viktor": "slavkin-viktor",
    "SLAVOVA Cornelia": "slavova-cornelia",
    "SLAVOVA Lilia": "slavova-lilia",
    "SLAYTON-HUGHES Helen": "slayton-hughes-helen",
    "SLEEP Ben": "sleep-ben",
    "SLEEPING WARRIOR THEATRE COMPANY ": "sleeping-warrior-theatre-company",
    "SLEEPWALK COLLECTIVE ": "sleepwalk-collective",
    "SLEIGH Tom": "sleigh-tom",
    "SLEISHMAN Jenna": "sleishman-jenna",
    "SLEPIAN Danielle": "slepian-danielle",
    "SLEVIN Debbie": "slevin-debbie",
    "SLEVIN Gerald": "slevin-gerald",
    "SLEZAK Gary": "slezak-gary",
    "SLIGHTLY ALTERED STATES ": "slightly-altered-states",
    "SLIM Fatboy": "slim-fatboy",
    "SLOAN Bob": "sloan-bob",
    "SLOAN Brian": "sloan-brian",
    "SLOAN Carolyn": "sloan-carolyn",
    "SLOAN Cathy": "sloan-cathy",
    "SLOAN Judith": "sloan-judith",
    "SLOAN Michael": "sloan-michael",
    "SLOAN Patty Gideon": "sloan-patty-gideon",
    "SLOBODNIK Zdenko": "slobodnik-zdenko",
    "SLOBODZIANEK Tadeusz": "slobodzianek-tadeusz",
    "SLOCOMB Bud": "slocomb-bud",
    "SLOCUM Barb": "slocum-barb",
    "SLOCUM Brandon Daughtry": "slocum-brandon-daughtry",
    "SLOMAN Carol": "sloman-carol",
    "SLOMAN Robert": "sloman-robert",
    "SLONE David": "slone-david",
    "SLONIKA Richard": "slonika-richard",
    "SLONIM Michelle": "slonim-michelle",
    "SLOT Tom": "slot-tom",
    "SLOTBOOM Carl": "slotboom-carl",
    "SLOTE Jessica": "slote-jessica",
    "SLOTNICK Myra": "slotnick-myra",
    "SLOUT William L": "slout-william-l",
    "SLOVER Tim": "slover-tim",
    "SLOVIC Spencer": "slovic-spencer",
    "SLOVO Gillian": "slovo-gillian",
    "SLOVO Shawn": "slovo-shawn",
    "SLOWACKI Juliusz": "slowacki-juliusz",
    "SLOWEY Mark": "slowey-mark",
    "SLUGENOVA-COCKRELL Katarina": "slugenova-cockrell-katarina",
    "SLUGOCKI Lillian Ann": "slugocki-lillian-ann",
    "SLUMMING-IT THEATRE COMPANY ": "slumming-it-theatre-company",
    "SLUNG LOW ": "slung-low",
    "SLUYTER Mariette": "sluyter-mariette",
    "SLUZNY Jim": "sluzny-jim",
    "SLYVIA-CLARNO Anne": "slyvia-clarno-anne",
    "SLYVIA-CLARNO Brianna": "slyvia-clarno-brianna"
  }
};