export default {
  "metadata": {
    "results": 903,
    "timeStamp": "2025-12-05T21:31:16.544Z",
    "url": "https://www.doollee.com/PlaywrightsS/S_playwrights_m-r.php"
  },
  "authors": {
    "SMALL Andrew": "small-andrew",
    "SMALL Caroline": "small-caroline",
    "SMALL Lothian": "small-lothian",
    "SMALL Michael W": "small-michael-w",
    "SMALL Neva": "small-neva",
    "SMALL Ralph": "small-ralph",
    "SMALL Stella": "small-stella",
    "SMALL Steve": "small-steve",
    "SMALL WONDER ": "small-wonder",
    "SMALL WORLD THEATRE ": "small-world-theatre",
    "SMALLEY Webster": "smalley-webster",
    "SMALLMAN Cheryl": "smallman-cheryl",
    "SMALLS Charlie": "smalls-charlie",
    "SMALLWOOD April": "smallwood-april",
    "SMALLWOOD Brian MacInnis": "smallwood-brian-macinnis",
    "SMALLWOOD Wendi": "smallwood-wendi",
    "SMART George": "smart-george",
    "SMART Mat": "smart-mat",
    "SMART Melinda": "smart-melinda",
    "SMART Mike": "smart-mike",
    "SMART Willy": "smart-willy",
    "SMARTT Dorothea": "smartt-dorothea",
    "SMEATON Grant": "smeaton-grant",
    "SMEATON John": "smeaton-john",
    "SMEDBERG Jordan": "smedberg-jordan",
    "SMEDLEY Olivia": "smedley-olivia",
    "SMERIN Jessica": "smerin-jessica",
    "SMERKANICH Nick": "smerkanich-nick",
    "SMET Christopher Warre": "smet-christopher-warre",
    "SMET Joeri": "smet-joeri",
    "SMETHURST Adam": "smethurst-adam",
    "SMETHURST William": "smethurst-william",
    "SMILAN Laurie": "smilan-laurie",
    "SMILES Roy": "smiles-roy",
    "SMILEY Charles W": "smiley-charles-w",
    "SMILEY Erin": "smiley-erin",
    "SMILEY Michael": "smiley-michael",
    "SMILEY Samuel": "smiley-samuel",
    "SMILEY Thea": "smiley-thea",
    "SMILEY Virginia": "smiley-virginia",
    "SMILLIE Ruth": "smillie-ruth",
    "SMILOVITZ Zach": "smilovitz-zach",
    "SMILOW David": "smilow-david",
    "SMIT Barto": "smit-barto",
    "SMIT Jonathan": "smit-jonathan",
    "SMITH A": "smith-a",
    "SMITH A C H": "smith-a-c-h",
    "SMITH Adam": "smith-adam",
    "SMITH Al": "smith-al",
    "SMITH Alena": "smith-alena",
    "SMITH Alexander McCall": "smith-alexander-mccall",
    "SMITH Ali": "smith-ali",
    "SMITH Allison": "smith-allison",
    "SMITH Amanda": "smith-amanda",
    "SMITH Andrew": "smith-andrew",
    "SMITH Andrew (1)": "smith-andrew-1",
    "SMITH Andrew Brian": "smith-andrew-brian",
    "SMITH Andrew J": "smith-andrew-j",
    "SMITH Andy": "smith-andy",
    "SMITH Angie": "smith-angie",
    "SMITH Anna Deavere": "smith-anna-deavere",
    "SMITH Anne": "smith-anne",
    "SMITH Anthony Patric": "smith-anthony-patric",
    "SMITH Arthur": "smith-arthur",
    "SMITH Ashley": "smith-ashley",
    "SMITH Auriol": "smith-auriol",
    "SMITH Barbara": "smith-barbara",
    "SMITH Barbara L": "smith-barbara-l",
    "SMITH Barry": "smith-barry",
    "SMITH Beccy": "smith-beccy",
    "SMITH Betty": "smith-betty",
    "SMITH Betty N": "smith-betty-n",
    "SMITH Beverly A": "smith-beverly-a",
    "SMITH Bob": "smith-bob",
    "SMITH Bradley Rand": "smith-bradley-rand",
    "SMITH Brandi J": "smith-brandi-j",
    "SMITH C J": "smith-c-j",
    "SMITH Campbell": "smith-campbell",
    "SMITH Carol": "smith-carol",
    "SMITH Caroline": "smith-caroline",
    "SMITH Casey": "smith-casey",
    "SMITH Cedric": "smith-cedric",
    "SMITH Charise Castro": "smith-charise-castro",
    "SMITH Charles (1)": "smith-charles-1",
    "SMITH Charles (2)": "smith-charles-2",
    "SMITH Charles J": "smith-charles-j",
    "SMITH Charles Rome": "smith-charles-rome",
    "SMITH Charlotte": "smith-charlotte",
    "SMITH Cheryl D": "smith-cheryl-d",
    "SMITH Chez": "smith-chez",
    "SMITH Chris": "smith-chris",
    "SMITH Chris Judge": "smith-chris-judge",
    "SMITH Christopher": "smith-christopher",
    "SMITH Clayton": "smith-clayton",
    "SMITH Clint": "smith-clint",
    "SMITH Colin": "smith-colin",
    "SMITH Conrad Sutton": "smith-conrad-sutton",
    "SMITH D Tucker": "smith-d-tucker",
    "SMITH Daniel": "smith-daniel",
    "SMITH Darius": "smith-darius",
    "SMITH Daron P": "smith-daron-p",
    "SMITH Dave": "smith-dave",
    "SMITH Dave (1)": "smith-dave-1",
    "SMITH David": "smith-david",
    "SMITH David F": "smith-david-f",
    "SMITH David G": "smith-david-g",
    "SMITH Dawn L": "smith-dawn-l",
    "SMITH DeAnne": "smith-deanne",
    "SMITH Deborah Salem": "smith-deborah-salem",
    "SMITH Demon": "smith-demon",
    "SMITH Denise": "smith-denise",
    "SMITH Dennis": "smith-dennis",
    "SMITH Derek": "smith-derek",
    "SMITH Djeniba": "smith-djeniba",
    "SMITH Dodie": "smith-dodie",
    "SMITH Donald": "smith-donald",
    "SMITH Donysha": "smith-donysha",
    "SMITH Duncan": "smith-duncan",
    "SMITH E Dale": "smith-e-dale",
    "SMITH Earl Hobson": "smith-earl-hobson",
    "SMITH Ebbe Roe": "smith-ebbe-roe",
    "SMITH Edward G": "smith-edward-g",
    "SMITH Elaine": "smith-elaine",
    "SMITH Elaine C": "smith-elaine-c",
    "SMITH Eleanor": "smith-eleanor",
    "SMITH Erin Denita": "smith-erin-denita",
    "SMITH Ethan": "smith-ethan",
    "SMITH Euan": "smith-euan",
    "SMITH Evan": "smith-evan",
    "SMITH Eyrin": "smith-eyrin",
    "SMITH Fiona Veitch": "smith-fiona-veitch",
    "SMITH Fleur": "smith-fleur",
    "SMITH Francesca": "smith-francesca",
    "SMITH Frank": "smith-frank",
    "SMITH G Bruce": "smith-g-bruce",
    "SMITH Gene Franklin": "smith-gene-franklin",
    "SMITH Glenn Allen": "smith-glenn-allen",
    "SMITH Gordon": "smith-gordon",
    "SMITH Grady": "smith-grady",
    "SMITH Grainne": "smith-grainne",
    "SMITH Gretchen Elizabeth": "smith-gretchen-elizabeth",
    "SMITH Harry B": "smith-harry-b",
    "SMITH Helen": "smith-helen",
    "SMITH Helen (1)": "smith-helen-1",
    "SMITH Iain Crichton": "smith-iain-crichton",
    "SMITH Ian": "smith-ian",
    "SMITH Ian Watt": "smith-ian-watt",
    "SMITH Imogen": "smith-imogen",
    "SMITH J A": "smith-j-a",
    "SMITH J D": "smith-j-d",
    "SMITH Jack": "smith-jack",
    "SMITH Jack (1)": "smith-jack-1",
    "SMITH Jackie": "smith-jackie",
    "SMITH Jamie": "smith-jamie",
    "SMITH Jane Denitz": "smith-jane-denitz",
    "SMITH Janet": "smith-janet",
    "SMITH Jay": "smith-jay",
    "SMITH Jay H": "smith-jay-h",
    "SMITH Jean": "smith-jean",
    "SMITH Jeffrey": "smith-jeffrey",
    "SMITH Jeffrey Dennis": "smith-jeffrey-dennis",
    "SMITH Jeffrey Harmon": "smith-jeffrey-harmon",
    "SMITH Jennifer": "smith-jennifer",
    "SMITH Jessica": "smith-jessica",
    "SMITH Jessica Grace": "smith-jessica-grace",
    "SMITH Jo": "smith-jo",
    "SMITH Joanie": "smith-joanie",
    "SMITH Jodi": "smith-jodi",
    "SMITH John": "smith-john",
    "SMITH John Owen": "smith-john-owen",
    "SMITH Jon": "smith-jon",
    "SMITH Jonathan": "smith-jonathan",
    "SMITH Josh": "smith-josh",
    "SMITH Joshua George": "smith-joshua-george",
    "SMITH Judith M": "smith-judith-m",
    "SMITH Julia": "smith-julia",
    "SMITH Julia Aston": "smith-julia-aston",
    "SMITH Julian Maynard": "smith-julian-maynard",
    "SMITH K": "smith-k",
    "SMITH Kat": "smith-kat",
    "SMITH Kate": "smith-kate",
    "SMITH Kay Nolte": "smith-kay-nolte",
    "SMITH Kellie": "smith-kellie",
    "SMITH Kenley": "smith-kenley",
    "SMITH Kim": "smith-kim",
    "SMITH Kimleigh": "smith-kimleigh",
    "SMITH Kirk": "smith-kirk",
    "SMITH Kirsta": "smith-kirsta",
    "SMITH Kirsten": "smith-kirsten",
    "SMITH Kirsten Holly": "smith-kirsten-holly",
    "SMITH Kraig": "smith-kraig",
    "SMITH Kylie Ann": "smith-kylie-ann",
    "SMITH Larry": "smith-larry",
    "SMITH Larry Alan": "smith-larry-alan",
    "SMITH Laura": "smith-laura",
    "SMITH Laurel": "smith-laurel",
    "SMITH Lawrence Gregory": "smith-lawrence-gregory",
    "SMITH Leanne": "smith-leanne",
    "SMITH Lee": "smith-lee",
    "SMITH Leo": "smith-leo",
    "SMITH Leonard": "smith-leonard",
    "SMITH Les": "smith-les",
    "SMITH Linda": "smith-linda",
    "SMITH Lisa Velten": "smith-lisa-velten",
    "SMITH Lois A": "smith-lois-a",
    "SMITH Louise": "smith-louise",
    "SMITH Lucy Kendrick": "smith-lucy-kendrick",
    "SMITH Luke": "smith-luke",
    "SMITH M": "smith-m",
    "SMITH Maggie": "smith-maggie",
    "SMITH Mal": "smith-mal",
    "SMITH Marc": "smith-marc",
    "SMITH Marc Adam": "smith-marc-adam",
    "SMITH Marc P": "smith-marc-p",
    "SMITH Marcia": "smith-marcia",
    "SMITH Margaret": "smith-margaret",
    "SMITH Marisa": "smith-marisa",
    "SMITH Mark E": "smith-mark-e",
    "SMITH Mark Landon": "smith-mark-landon",
    "SMITH Marrick": "smith-marrick",
    "SMITH Martha J": "smith-martha-j",
    "SMITH Matt": "smith-matt",
    "SMITH Matthew": "smith-matthew",
    "SMITH Matthew Buckley": "smith-matthew-buckley",
    "SMITH Matthew Graham": "smith-matthew-graham",
    "SMITH Matthew Stephen": "smith-matthew-stephen",
    "SMITH Mavis": "smith-mavis",
    "SMITH Maxine": "smith-maxine",
    "SMITH Mayo": "smith-mayo",
    "SMITH Mel": "smith-mel",
    "SMITH Melissa": "smith-melissa",
    "SMITH Micah": "smith-micah",
    "SMITH Michael": "smith-michael",
    "SMITH Michael (1)": "smith-michael-1",
    "SMITH Michael A": "smith-michael-a",
    "SMITH Michael O": "smith-michael-o",
    "SMITH Michael Patrick Flanagan": "smith-michael-patrick-flanagan",
    "SMITH Michael Roger": "smith-michael-roger",
    "SMITH Michael T": "smith-michael-t",
    "SMITH Mike": "smith-mike",
    "SMITH Milburn": "smith-milburn",
    "SMITH Nan": "smith-nan",
    "SMITH Natasha": "smith-natasha",
    "SMITH Nathan": "smith-nathan",
    "SMITH Neil": "smith-neil",
    "SMITH Nicole": "smith-nicole",
    "SMITH Nigel": "smith-nigel",
    "SMITH Noah": "smith-noah",
    "SMITH Noble Mason": "smith-noble-mason",
    "SMITH Othniel": "smith-othniel",
    "SMITH Otis": "smith-otis",
    "SMITH Patricia": "smith-patricia",
    "SMITH Patrick": "smith-patrick",
    "SMITH Patti": "smith-patti",
    "SMITH Paul": "smith-paul",
    "SMITH Paul Gerald": "smith-paul-gerald",
    "SMITH Paul J": "smith-paul-j",
    "SMITH Paul K": "smith-paul-k",
    "SMITH Paul Slade": "smith-paul-slade",
    "SMITH Peter": "smith-peter",
    "SMITH Peter L": "smith-peter-l",
    "SMITH Peter Wolf": "smith-peter-wolf",
    "SMITH Petra": "smith-petra",
    "SMITH Phil": "smith-phil",
    "SMITH Phoebe": "smith-phoebe",
    "SMITH Pip": "smith-pip",
    "SMITH Portia": "smith-portia",
    "SMITH R Brad": "smith-r-brad",
    "SMITH Rachel": "smith-rachel",
    "SMITH Randee": "smith-randee",
    "SMITH Raphael": "smith-raphael",
    "SMITH Rhoda K": "smith-rhoda-k",
    "SMITH Richard Harland": "smith-richard-harland",
    "SMITH Ritchie": "smith-ritchie",
    "SMITH Rob": "smith-rob",
    "SMITH Robert B": "smith-robert-b",
    "SMITH Robert Kimmel": "smith-robert-kimmel",
    "SMITH Robert Paul": "smith-robert-paul",
    "SMITH Rod": "smith-rod",
    "SMITH Roger": "smith-roger",
    "SMITH Roger Guenveur": "smith-roger-guenveur",
    "SMITH Roland": "smith-roland",
    "SMITH Rommi": "smith-rommi",
    "SMITH Ryan J-W": "smith-ryan-j-w",
    "SMITH Sampson": "smith-sampson",
    "SMITH Samuel": "smith-samuel",
    "SMITH Scott": "smith-scott",
    "SMITH Scott C": "smith-scott-c",
    "SMITH Selina Woolery": "smith-selina-woolery",
    "SMITH Simon": "smith-simon",
    "SMITH Stef": "smith-stef",
    "SMITH Stephanie": "smith-stephanie",
    "SMITH Stephen": "smith-stephen",
    "SMITH Stephen (1)": "smith-stephen-1",
    "SMITH Stephen Gregory": "smith-stephen-gregory",
    "SMITH Stephen L": "smith-stephen-l",
    "SMITH Steve": "smith-steve",
    "SMITH Steven": "smith-steven",
    "SMITH Steven Scott": "smith-steven-scott",
    "SMITH Sue": "smith-sue",
    "SMITH Sunny": "smith-sunny",
    "SMITH Surrey": "smith-surrey",
    "SMITH Susan": "smith-susan",
    "SMITH Susan Arnout": "smith-susan-arnout",
    "SMITH Suze": "smith-suze",
    "SMITH Sydney Bernard": "smith-sydney-bernard",
    "SMITH Sydney Goodsir": "smith-sydney-goodsir",
    "SMITH T C": "smith-t-c",
    "SMITH Tara": "smith-tara",
    "SMITH Tessa Cloudsley": "smith-tessa-cloudsley",
    "SMITH Timothy Allen": "smith-timothy-allen",
    "SMITH Timothy Jay": "smith-timothy-jay",
    "SMITH Tobias": "smith-tobias",
    "SMITH Tom": "smith-tom",
    "SMITH Tom (1)": "smith-tom-1",
    "SMITH Tom Morton": "smith-tom-morton",
    "SMITH Tommy": "smith-tommy",
    "SMITH Tracey Erin": "smith-tracey-erin",
    "SMITH Trevor": "smith-trevor",
    "SMITH Trevor T": "smith-trevor-t",
    "SMITH Val": "smith-val",
    "SMITH Val (1)": "smith-val-1",
    "SMITH Valerie": "smith-valerie",
    "SMITH Vance": "smith-vance",
    "SMITH Vanessa Claire": "smith-vanessa-claire",
    "SMITH Vernon Cole": "smith-vernon-cole",
    "SMITH Vincent": "smith-vincent",
    "SMITH W Gordon": "smith-w-gordon",
    "SMITH Wesley": "smith-wesley",
    "SMITH Wesley D": "smith-wesley-d",
    "SMITH William B": "smith-william-b",
    "SMITH William E": "smith-william-e",
    "SMITH William H": "smith-william-h",
    "SMITH Winchell": "smith-winchell",
    "SMITH Winifred": "smith-winifred",
    "SMITH Yvonne": "smith-yvonne",
    "SMITHER Elizabeth": "smither-elizabeth",
    "SMITHERMAN John D": "smitherman-john-d",
    "SMITH-ROY Susannah": "smith-roy-susannah",
    "SMITH-SLOMAN Christy": "smith-sloman-christy",
    "SMITHSON Norman": "smithson-norman",
    "SMITH-SOTO Mark": "smith-soto-mark",
    "SMITH-WILLIAMS Rebecca": "smith-williams-rebecca",
    "SMOCEK Ladislav": "smocek-ladislav",
    "SMOCK Bill": "smock-bill",
    "SMOCK Brett": "smock-brett",
    "SMOJIE Tanya": "smojie-tanya",
    "SMOKE AND OAKUM THEATRE ": "smoke-and-oakum-theatre",
    "SMOLENSKY Sheila": "smolensky-sheila",
    "SMOLIN Pauline": "smolin-pauline",
    "SMULLEN Eamonn": "smullen-eamonn",
    "SMULYAN Jane": "smulyan-jane",
    "SMURTHWAITE Kate": "smurthwaite-kate",
    "SMYRL David Langston": "smyrl-david-langston",
    "SMYTH Damian": "smyth-damian",
    "SMYTH Donaco": "smyth-donaco",
    "SMYTH Donna E": "smyth-donna-e",
    "SMYTH Eve": "smyth-eve",
    "SMYTH Matthew": "smyth-matthew",
    "SMYTHE Ingrid Hansen": "smythe-ingrid-hansen",
    "SMYTHE John": "smythe-john",
    "SMYTHE Norman": "smythe-norman",
    "SMYTHE Robert": "smythe-robert",
    "SMYTHE Vanessa": "smythe-vanessa",
    "SMYTHSON Rob": "smythson-rob",
    "SNAPE Sam": "snape-sam",
    "SNAPP Brian": "snapp-brian",
    "SNAVE Elmas": "snave-elmas",
    "SNEAD Ann": "snead-ann",
    "SNEDDON Gail": "sneddon-gail",
    "SNEE Dennis": "snee-dennis",
    "SNEE Emily": "snee-emily",
    "SNEE Richard": "snee-richard",
    "SNEED Anthony": "sneed-anthony",
    "SNEED Helen": "sneed-helen",
    "SNEED Pamela": "sneed-pamela",
    "SNEERINGER Susan E": "sneeringer-susan-e",
    "SNELGROVE Michael": "snelgrove-michael",
    "SNELL Gordon": "snell-gordon",
    "SNELL Ned": "snell-ned",
    "SNELL Steven": "snell-steven",
    "SNELL Tony": "snell-tony",
    "SNELLENBARGER Dan": "snellenbarger-dan",
    "SNELLING Andi": "snelling-andi",
    "SNELSON Chris": "snelson-chris",
    "SNIATYNSKI Caroline": "sniatynski-caroline",
    "SNIDER Solon": "snider-solon",
    "SNIDER Will": "snider-will",
    "SNIEDZE Erik": "sniedze-erik",
    "SNIPES Kevin Christopher": "snipes-kevin-christopher",
    "SNIPES Larry": "snipes-larry",
    "SNIPES Margaret F Taylor": "snipes-margaret-f-taylor",
    "SNOAD Peter": "snoad-peter",
    "SNODGRASS Cheryl": "snodgrass-cheryl",
    "SNODGRASS Dorothy": "snodgrass-dorothy",
    "SNODGRASS J": "snodgrass-j",
    "SNODGRASS Katherine": "snodgrass-katherine",
    "SNODGRASS William de Witt": "snodgrass-william-de-witt",
    "SNODIN David": "snodin-david",
    "SNOOK Dean": "snook-dean",
    "SNORTLAND Ellen": "snortland-ellen",
    "SNOW Brendan": "snow-brendan",
    "SNOW C P": "snow-c-p",
    "SNOW Chris": "snow-chris",
    "SNOW Jason Michael": "snow-jason-michael",
    "SNOW Jill": "snow-jill",
    "SNOW Peter": "snow-peter",
    "SNOW Pink": "snow-pink",
    "SNOW R P": "snow-r-p",
    "SNOW Zach": "snow-zach",
    "SNOWBALL Estelle": "snowball-estelle",
    "SNOWBALL Oliver": "snowball-oliver",
    "SNOWDEN William": "snowden-william",
    "SNOWDON Pericles": "snowdon-pericles",
    "SNOWDON Samuel Elliot": "snowdon-samuel-elliot",
    "SNUKAL Sherman": "snukal-sherman",
    "SNYDER Andrew": "snyder-andrew",
    "SNYDER Andy": "snyder-andy",
    "SNYDER Ben": "snyder-ben",
    "SNYDER Clint": "snyder-clint",
    "SNYDER Danielle": "snyder-danielle",
    "SNYDER Dannie": "snyder-dannie",
    "SNYDER Emily C A": "snyder-emily-c-a",
    "SNYDER Geraldine Ann": "snyder-geraldine-ann",
    "SNYDER Huck": "snyder-huck",
    "SNYDER Jennie": "snyder-jennie",
    "SNYDER Karen": "snyder-karen",
    "SNYDER Lauren": "snyder-lauren",
    "SNYDER Lynn": "snyder-lynn",
    "SNYDER Mark": "snyder-mark",
    "SNYDER Patricia Di Benedetto": "snyder-patricia-di-benedetto",
    "SNYDER Sara": "snyder-sara",
    "SNYDER Terry": "snyder-terry",
    "SNYDER William": "snyder-william",
    "SNYDER-EATON Travis": "snyder-eaton-travis",
    "SO Kevin": "so-kevin",
    "SO Sarita Keo Kossamak": "so-sarita-keo-kossamak",
    "SO PERCUSSION ": "so-percussion",
    "SOAMES David": "soames-david",
    "SOANS Robin": "soans-robin",
    "SOBAL Josua": "sobal-josua",
    "SOBCHAK Victor": "sobchak-victor",
    "SOBEL Dava": "sobel-dava",
    "SOBELLE Geoff": "sobelle-geoff",
    "SOBIESKI Sonya": "sobieski-sonya",
    "SOBIESKI Stacy": "sobieski-stacy",
    "SOBLER Alix": "sobler-alix",
    "SOBOL Isaac Bashevis": "sobol-isaac-bashevis",
    "SOBOL Joshua": "sobol-joshua",
    "SOBULE Jill": "sobule-jill",
    "SOCOL Gary": "socol-gary",
    "SOCOLOV Dan": "socolov-dan",
    "SOD Ted": "sod-ted",
    "SODARO Craig": "sodaro-craig",
    "SODARO George M Cohen": "sodaro-george-m-cohen",
    "SODEN Christopher": "soden-christopher",
    "SODERBERG Douglas": "soderberg-douglas",
    "SODERBERG Hjalmar": "soderberg-hjalmar",
    "SODERBLOM Anna": "soderblom-anna",
    "SODERBURG Douglas": "soderburg-douglas",
    "SODERHOLM Cynthia": "soderholm-cynthia",
    "SOEHNIE Frank": "soehnie-frank",
    "SOENS Dennis": "soens-dennis",
    "SOERENSEN Sidse Ploug": "soerensen-sidse-ploug",
    "SOETE George": "soete-george",
    "SOFE Emilie": "sofe-emilie",
    "SOFIA Dawn": "sofia-dawn",
    "SOFIAN Anahid": "sofian-anahid",
    "SOFOLA Zulu": "sofola-zulu",
    "SOFOWOTE Segun": "sofowote-segun",
    "SOFRONAS Peter Cosmas": "sofronas-peter-cosmas",
    "SOFTLEY Iain": "softley-iain",
    "SOFTLEY Robert": "softley-robert",
    "SOHN Charlie": "sohn-charlie",
    "SOHN Josh": "sohn-josh",
    "SOHNE Charlie": "sohne-charlie",
    "SOHOYE Ashmeed": "sohoye-ashmeed",
    "SOJKA Britteni": "sojka-britteni",
    "SOKEL Jaqueline": "sokel-jaqueline",
    "SOKEL Walter": "sokel-walter",
    "SOKOLOFF Marjorie": "sokoloff-marjorie",
    "SOKOLOSKI Thom": "sokoloski-thom",
    "SOKOLOW Julie": "sokolow-julie",
    "SOLANA Bernardo": "solana-bernardo",
    "SOLANAS Valerie": "solanas-valerie",
    "SOLAND Lisa": "soland-lisa",
    "SOLANKE Ade": "solanke-ade",
    "SOLANKI Shane": "solanki-shane",
    "SOLANO Bernardo": "solano-bernardo",
    "SOLANO Paula Weston": "solano-paula-weston",
    "SOLARI Jonathan": "solari-jonathan",
    "SOLAZZO Carole": "solazzo-carole",
    "SOLDAN James": "soldan-james",
    "SOLDATI Gemma": "soldati-gemma",
    "SOLE Michael": "sole-michael",
    "SOLEIMANPOUR Nassim": "soleimanpour-nassim",
    "SOLEMANI Sarah": "solemani-sarah",
    "SOLEYMANLOU Mani": "soleymanlou-mani",
    "SOLHEIM Bruce Olav": "solheim-bruce-olav",
    "SOLIMAN Laila": "soliman-laila",
    "SOLIS Alfred": "solis-alfred",
    "SOLIS Dulce Maria": "solis-dulce-maria",
    "SOLIS E Rodriguez": "solis-e-rodriguez",
    "SOLIS Octavio": "solis-octavio",
    "SOLLEY Marvin": "solley-marvin",
    "SOLLY Bill": "solly-bill",
    "SOLMS Kenny": "solms-kenny",
    "SOLO Bran": "solo-bran",
    "SOLOMAN Shana A": "soloman-shana-a",
    "SOLOMAN Stephanie Glass": "soloman-stephanie-glass",
    "SOLOMN Jessica": "solomn-jessica",
    "SOLOMON Barbara": "solomon-barbara",
    "SOLOMON Emily Bentley": "solomon-emily-bentley",
    "SOLOMON Foster": "solomon-foster",
    "SOLOMON Frank": "solomon-frank",
    "SOLOMON Jeffrey": "solomon-jeffrey",
    "SOLOMON Mark": "solomon-mark",
    "SOLOMON Michael": "solomon-michael",
    "SOLOMON Michal": "solomon-michal",
    "SOLOMON Rachel": "solomon-rachel",
    "SOLOMON Reva": "solomon-reva",
    "SOLOMON Rivka": "solomon-rivka",
    "SOLOMON Robert": "solomon-robert",
    "SOLOMON Samuel": "solomon-samuel",
    "SOLOMON Sarah": "solomon-sarah",
    "SOLOMON Shana": "solomon-shana",
    "SOLOMON Steve": "solomon-steve",
    "SOLONDZ Todd": "solondz-todd",
    "SOLORZANO Francisco": "solorzano-francisco",
    "SOLORZANO Sergio": "solorzano-sergio",
    "SOLOWAY Faith": "soloway-faith",
    "SOLOWAY Jill": "soloway-jill",
    "SOLTANOFF Phil": "soltanoff-phil",
    "SOLZHENITSYN Alexander": "solzhenitsyn-alexander",
    "SOMERS Arnold": "somers-arnold",
    "SOMERS Brendan": "somers-brendan",
    "SOMERSET Adam": "somerset-adam",
    "SOMERVILLE Dora": "somerville-dora",
    "SOMERVILLE Sarah": "somerville-sarah",
    "SOMERVILLE Steven": "somerville-steven",
    "SOMES Kelly": "somes-kelly",
    "SOMETIMES Alicia": "sometimes-alicia",
    "SOMIGLIANA Carlos": "somigliana-carlos",
    "SOMKIN Steven": "somkin-steven",
    "SOMLO David": "somlo-david",
    "SOMMA Abigail": "somma-abigail",
    "SOMMER Edith": "sommer-edith",
    "SOMMER Miah": "sommer-miah",
    "SOMMER Paul": "sommer-paul",
    "SOMMER Sam": "sommer-sam",
    "SOMMERFIELD Robert": "sommerfield-robert",
    "SOMMERFORD Daniel": "sommerford-daniel",
    "SOMMERS Aaron": "sommers-aaron",
    "SOMMERS Brenda": "sommers-brenda",
    "SOMMERS David": "sommers-david",
    "SOMMERS Karen": "sommers-karen",
    "SOMMERSTEIN Alan H": "sommerstein-alan-h",
    "SOMSEN Pennell": "somsen-pennell",
    "SON Diana": "son-diana",
    "SONDBERG Soren": "sondberg-soren",
    "SONDERFAN Derek": "sonderfan-derek",
    "SONDHEIM Stephen": "sondheim-stephen",
    "SONDHI Maya": "sondhi-maya",
    "SONG Celine": "song-celine",
    "SONG John": "song-john",
    "SONG Julie": "song-julie",
    "SONG Sue Jin": "song-sue-jin",
    "SONG OF THE GOAT ": "song-of-the-goat",
    "SONIA-WALLACE Brian": "sonia-wallace-brian",
    "SONLEY Peter": "sonley-peter",
    "SONNA Mark-Brian": "sonna-mark-brian",
    "SONNENBERG Ben": "sonnenberg-ben",
    "SONNENBLICK Mark": "sonnenblick-mark",
    "SONNENFELD Marion": "sonnenfeld-marion",
    "SONNENFELD W": "sonnenfeld-w",
    "SONTAG Susan": "sontag-susan",
    "SONY Jeremy": "sony-jeremy",
    "SOOLMAN Harvey": "soolman-harvey",
    "SOPER Mark": "soper-mark",
    "SOPER Tom": "soper-tom",
    "SOPHIE Damsel": "sophie-damsel",
    "SOPHOCLES ": "sophocles",
    "SORAN Jonas": "soran-jonas",
    "SORBELLO Donna": "sorbello-donna",
    "SORELL Walter": "sorell-walter",
    "SORENSEN Per-Olav": "sorensen-per-olav",
    "SORENSEN Rodger D": "sorensen-rodger-d",
    "SORENSEN Tawny": "sorensen-tawny",
    "SORENSON Karla": "sorenson-karla",
    "SORESI Gianmarco": "soresi-gianmarco",
    "SORGE Reinhard": "sorge-reinhard",
    "SORGENFREI Carol": "sorgenfrei-carol",
    "SORHEIM Carl J": "sorheim-carl-j",
    "SORIA Mario T": "soria-mario-t",
    "SORIANO Maria": "soriano-maria",
    "SORICE Bill": "sorice-bill",
    "SORICH Sjrdan": "sorich-sjrdan",
    "SORKIN Aaron": "sorkin-aaron",
    "SORKIN Joan Ross": "sorkin-joan-ross",
    "SORKIN N C": "sorkin-n-c",
    "SORKIN Rich": "sorkin-rich",
    "SORKIN Sarah": "sorkin-sarah",
    "SOROKA Robert": "soroka-robert",
    "SOROKIN Vladimir": "sorokin-vladimir",
    "SORRELL Martin": "sorrell-martin",
    "SORRENTINO Joseph": "sorrentino-joseph",
    "SORTOR Chris": "sortor-chris",
    "SOSA Diego": "sosa-diego",
    "SOSNA Shandell": "sosna-shandell",
    "SOSON Matt": "soson-matt",
    "SOSSI Ron": "sossi-ron",
    "SOSTEK Brian": "sostek-brian",
    "SOSTER John Richards": "soster-john-richards",
    "SOTELO Beverly": "sotelo-beverly",
    "SOTO Gary": "soto-gary",
    "SOTO Julie": "soto-julie",
    "SOTO Mario X": "soto-mario-x",
    "SOTO Merian": "soto-merian",
    "SOTTILE Alexis": "sottile-alexis",
    "SOUCY Peter": "soucy-peter",
    "SOUKI Juan": "souki-juan",
    "SOUKUP Martha": "soukup-martha",
    "SOUL Kesa Maya": "soul-kesa-maya",
    "SOULE Jeremy": "soule-jeremy",
    "SOULIS Billy": "soulis-billy",
    "SOULSBY Hannah": "soulsby-hannah",
    "SOULSBY Rhea": "soulsby-rhea",
    "SOUM Corinne": "soum-corinne",
    "SOUNDBOXED COLLECTIVE ": "soundboxed-collective",
    "SOUR Robert B": "sour-robert-b",
    "SOURDOUGH THEATRE ": "sourdough-theatre",
    "SOURVINOU-INWOOD Christiana": "sourvinou-inwood-christiana",
    "SOUSA Bruno": "sousa-bruno",
    "SOUSA Joseph": "sousa-joseph",
    "SOUTAR Annabel": "soutar-annabel",
    "SOUTER Peter": "souter-peter",
    "SOUTH Frank": "south-frank",
    "SOUTHALL Raymond": "southall-raymond",
    "SOUTHAM Barry": "southam-barry",
    "SOUTHARD Adam Emperor": "southard-adam-emperor",
    "SOUTHARD Ross": "southard-ross",
    "SOUTHERN Nile": "southern-nile",
    "SOUTHERS Mark Clayton": "southers-mark-clayton",
    "SOUTHGATE Patsy": "southgate-patsy",
    "SOUTHWORTH John": "southworth-john",
    "SOUTHWORTH Matthew": "southworth-matthew",
    "SOUTHWORTH Robbie": "southworth-robbie",
    "SOUTTER Andy": "soutter-andy",
    "SOUZA Adam": "souza-adam",
    "SOUZA Mark": "souza-mark",
    "SOWALSKY John": "sowalsky-john",
    "SOWANDE Bode": "sowande-bode",
    "SOWANS Elizabeth": "sowans-elizabeth",
    "SOWKA Natasha": "sowka-natasha",
    "SOWLE John": "sowle-john",
    "SOYA Carl Erik": "soya-carl-erik",
    "SOYINKA Wole": "soyinka-wole",
    "SOYMONOFF Nika": "soymonoff-nika",
    "SOZUTEKI Koe": "sozuteki-koe",
    "SPAFFORD Peter": "spafford-peter",
    "SPAGNOLA Jack": "spagnola-jack",
    "SPAGNOLETTI Nicholas": "spagnoletti-nicholas",
    "SPAIN Dagmar": "spain-dagmar",
    "SPALLEN Abbie": "spallen-abbie",
    "SPALTER Max": "spalter-max",
    "SPANGLER David": "spangler-david",
    "SPANGLER Matthew": "spangler-matthew",
    "SPANGNOLETTI Nicholas": "spangnoletti-nicholas",
    "SPANO Jon": "spano-jon",
    "SPANOS Nicholas": "spanos-nicholas",
    "SPARA Mike": "spara-mike",
    "SPARACINO Bricken": "sparacino-bricken",
    "SPARACIO Kate": "sparacio-kate",
    "SPARAGNA Ann C": "sparagna-ann-c",
    "SPARBER Max": "sparber-max",
    "SPARE CHANGE PRODUCTIONS ": "spare-change-productions",
    "SPARE TYRE ": "spare-tyre",
    "SPARGO Andie": "spargo-andie",
    "SPARGO Anthony": "spargo-anthony",
    "SPARK Muriel": "spark-muriel",
    "SPARKES Winifred": "sparkes-winifred",
    "SPARKLE AND DARK ": "sparkle-and-dark",
    "SPARKS John": "sparks-john",
    "SPARKS Mark": "sparks-mark",
    "SPARKS Richard": "sparks-richard",
    "SPARKS Rick": "sparks-rick",
    "SPARKS Ron": "sparks-ron",
    "SPARRELL Lisa": "sparrell-lisa",
    "SPARROW Alexander": "sparrow-alexander",
    "SPARROW Naomi": "sparrow-naomi",
    "SPATZ Ben": "spatz-ben",
    "SPEACE Oscar K": "speace-oscar-k",
    "SPEAK THEATER ARTS ": "speak-theater-arts",
    "SPEAKMAN Ray": "speakman-ray",
    "SPEAR Liz": "spear-liz",
    "SPEARMAN Kyle": "spearman-kyle",
    "SPEARS Laurel": "spears-laurel",
    "SPEARS Peter": "spears-peter",
    "SPEARS Steve J": "spears-steve-j",
    "SPEARS JONES Patricia": "spears-jones-patricia",
    "SPEARY Linus": "speary-linus",
    "SPECHT Kerstin": "specht-kerstin",
    "SPECIALE Tony": "speciale-tony",
    "SPECTACLE THEATRE ": "spectacle-theatre",
    "SPECTOR Donna": "spector-donna",
    "SPECTOR Hillary": "spector-hillary",
    "SPECTOR Jonathan": "spector-jonathan",
    "SPECTOR Laurie": "spector-laurie",
    "SPEDALIERI Francesca": "spedalieri-francesca",
    "SPEER Arthur": "speer-arthur",
    "SPEER Kathy": "speer-kathy",
    "SPEERS Neill": "speers-neill",
    "SPEERT Eleanore C": "speert-eleanore-c",
    "SPEHAR Steve": "spehar-steve",
    "SPEICHER Tim": "speicher-tim",
    "SPEIER Susanna": "speier-susanna",
    "SPEIGHT Johnny": "speight-johnny",
    "SPEIGHTS Stephen": "speights-stephen",
    "SPELLER John": "speller-john",
    "SPELMAN Jon": "spelman-jon",
    "SPELVIN George": "spelvin-george",
    "SPENCE Alan": "spence-alan",
    "SPENCE Amahra": "spence-amahra",
    "SPENCE Dave": "spence-dave",
    "SPENCE Janis": "spence-janis",
    "SPENCE Joe": "spence-joe",
    "SPENCE Kim": "spence-kim",
    "SPENCE Kisha T": "spence-kisha-t",
    "SPENCE Michael": "spence-michael",
    "SPENCE Peter": "spence-peter",
    "SPENCE Rachael": "spence-rachael",
    "SPENCE Wall": "spence-wall",
    "SPENCELEY Philip": "spenceley-philip",
    "SPENCER Ben": "spencer-ben",
    "SPENCER Brent": "spencer-brent",
    "SPENCER Camika": "spencer-camika",
    "SPENCER Charmaine": "spencer-charmaine",
    "SPENCER Christopher": "spencer-christopher",
    "SPENCER Colin": "spencer-colin",
    "SPENCER Dave": "spencer-dave",
    "SPENCER David": "spencer-david",
    "SPENCER Dennis": "spencer-dennis",
    "SPENCER Elizabeth": "spencer-elizabeth",
    "SPENCER Fabian": "spencer-fabian",
    "SPENCER Ginger": "spencer-ginger",
    "SPENCER Hayden": "spencer-hayden",
    "SPENCER Jay D": "spencer-jay-d",
    "SPENCER Martin": "spencer-martin",
    "SPENCER Melanie": "spencer-melanie",
    "SPENCER Phil": "spencer-phil",
    "SPENCER Ray": "spencer-ray",
    "SPENCER Steve": "spencer-steve",
    "SPENCER Stuart": "spencer-stuart",
    "SPENCER T J": "spencer-t-j",
    "SPENCER T J (1)": "spencer-t-j-1",
    "SPENCER Terie": "spencer-terie",
    "SPENCER Tim": "spencer-tim",
    "SPENCER Tom": "spencer-tom",
    "SPENCER W Grenville": "spencer-w-grenville",
    "SPENCER-JONES Alexandra": "spencer-jones-alexandra",
    "SPENDER Pauline": "spender-pauline",
    "SPENDER Stephen": "spender-stephen",
    "SPENSLEY Philip": "spensley-philip",
    "SPERA Robert": "spera-robert",
    "SPERINCK Jim": "sperinck-jim",
    "SPERLING Milton": "sperling-milton",
    "SPERLING Shoshana": "sperling-shoshana",
    "SPERO Wendy": "spero-wendy",
    "SPERR Martin": "sperr-martin",
    "SPERRING Benji": "sperring-benji",
    "SPEWACK Bella": "spewack-bella",
    "SPEWACK Sam": "spewack-sam",
    "SPEYER Chris": "speyer-chris",
    "SPEYER Melissa Lee": "speyer-melissa-lee",
    "SPHINX THEATRE COMPANY ": "berman-ed",
    "SPICE Sharron": "spice-sharron",
    "SPICER David": "spicer-david",
    "SPICER Kerrie": "spicer-kerrie",
    "SPIDERWOMAN THEATER ": "spiderwoman-theater",
    "SPIDLE Kyle": "spidle-kyle",
    "SPIEGEL Adam": "spiegel-adam",
    "SPIEGEL Alexis": "spiegel-alexis",
    "SPIEGEL David": "spiegel-david",
    "SPIEGEL Ruby Rae": "spiegel-ruby-rae",
    "SPIEGLER Ann-Giselle": "spiegler-ann-giselle",
    "SPIERING Frank": "spiering-frank",
    "SPIERS Hilary": "spiers-hilary",
    "SPIERS Ruth": "spiers-ruth",
    "SPIERS Steph": "spiers-steph",
    "SPIES Catherine": "spies-catherine",
    "SPIGELGASS Leonard": "spigelgass-leonard",
    "SPIGELMAN Alice": "spigelman-alice",
    "SPIKE THEATRE ": "spike-theatre",
    "SPILIOTI Chyssa": "spilioti-chyssa",
    "SPILLANE Bobby": "spillane-bobby",
    "SPILLER Ben": "spiller-ben",
    "SPILLER Buster": "spiller-buster",
    "SPILLERS John F": "spillers-john-f",
    "SPILLERS Michael Patrick": "spillers-michael-patrick",
    "SPILLMAN Ben": "spillman-ben",
    "SPINDEL Jerry": "spindel-jerry",
    "SPINETTI Victor": "spinetti-victor",
    "SPINK Ian": "spink-ian",
    "SPINK Reginald": "spink-reginald",
    "SPINK Tony": "spink-tony",
    "SPINKS Danielle": "spinks-danielle",
    "SPINKS Paul": "spinks-paul",
    "SPIRE Kevin": "spire-kevin",
    "SPIRO Ben": "spiro-ben",
    "SPIRO Benjamin": "spiro-benjamin",
    "SPIRO Bernard": "spiro-bernard",
    "SPIRO Gyorgy": "spiro-gyorgy",
    "SPIRO Peter": "spiro-peter",
    "SPITE Tim": "spite-tim",
    "SPITE Tony": "spite-tony",
    "SPITERALI Ellen": "spiterali-ellen",
    "SPITERI Kris": "spiteri-kris",
    "SPITFIRE COMPANY ": "spitfire-company",
    "SPITZ Marc": "spitz-marc",
    "SPITZER Lewis F": "spitzer-lewis-f",
    "SPITZER Murray": "spitzer-murray",
    "SPIVACK Anton": "spivack-anton",
    "SPIVAK Alice": "spivak-alice",
    "SPIVAK Gayatri Chakravorty": "spivak-gayatri-chakravorty",
    "SPLINTER David": "splinter-david",
    "SPLIT BRITCHES ": "split-britches",
    "SPLITTER Jenny": "splitter-jenny",
    "SPLITTER Phil": "splitter-phil",
    "SPODAREK Diane": "spodarek-diane",
    "SPOERLEIN Elise": "spoerlein-elise",
    "SPOLER Chuck": "spoler-chuck",
    "SPOLER Larry": "spoler-larry",
    "SPONTANEOUS COMBUSTION ": "spontaneous-combustion",
    "SPOOG Bea": "spoog-bea",
    "SPOONAMORE Stephen": "spoonamore-stephen",
    "SPOONER Cara": "spooner-cara",
    "SPOONER Dennis": "spooner-dennis",
    "SPOONER Jon": "spooner-jon",
    "SPORTELLI Paul": "sportelli-paul",
    "SPORTIELLO Tony": "sportiello-tony",
    "SPOSITO Dianne M": "sposito-dianne-m",
    "SPOTA George": "spota-george",
    "SPOTSWOOD Stephen": "spotswood-stephen",
    "SPOTTED STRIPES CIRCUS ": "spotted-stripes-circus",
    "SPOTTISWOODE Jonathan": "spottiswoode-jonathan",
    "SPOTTISWOODE Lily": "spottiswoode-lily",
    "SPOTTISWOODE Roger": "spottiswoode-roger",
    "SPOTTISWOODE Tracy": "spottiswoode-tracy",
    "SPRADLEY Benjamin": "spradley-benjamin",
    "SPRAGG Jennifer": "spragg-jennifer",
    "SPRAGUE Jason": "sprague-jason",
    "SPRAGUE Mortimer": "sprague-mortimer",
    "SPRAGUE Ryan": "sprague-ryan",
    "SPRATT Claire": "spratt-claire",
    "SPRAY Jessica": "spray-jessica",
    "SPREEN E Hunter": "spreen-e-hunter",
    "SPREGELBURD Rafael": "spregelburd-rafael",
    "SPRIGGE Elizabeth": "sprigge-elizabeth",
    "SPRINCHORN Evert": "sprinchorn-evert",
    "SPRING Barnaby": "spring-barnaby",
    "SPRING Bill": "spring-bill",
    "SPRING Danny": "spring-danny",
    "SPRINGATE Michael": "springate-michael",
    "SPRINKLE Annie": "sprinkle-annie",
    "SPRITZ Alice J": "spritz-alice-j",
    "SPROAT Ron": "sproat-ron",
    "SPROSTRANOVA Judith": "sprostranova-judith",
    "SPROSTY Matthew A": "sprosty-matthew-a",
    "SPROTT Fiona": "sprott-fiona",
    "SPROUL Jeff": "sproul-jeff",
    "SPROUL Linda": "sproul-linda",
    "SPROULL Hayley": "sproull-hayley",
    "SPROUSE Mary L": "sprouse-mary-l",
    "SPROXTON Morgan": "sproxton-morgan",
    "SPRUILL Daniel": "spruill-daniel",
    "SPRY Lib": "spry-lib",
    "SPTOTSWOOD Stephen": "sptotswood-stephen",
    "SPUN GLASS THEATRE ": "spun-glass-theatre",
    "SPUNDE Walter G": "spunde-walter-g",
    "SPUNKMEYER Johan": "spunkmeyer-johan",
    "SPUNNER Suzanne": "spunner-suzanne",
    "SPURGEON Dan": "spurgeon-dan",
    "SPURLING John": "spurling-john",
    "SPURNEY Jon": "spurney-jon",
    "SPURRIER James": "spurrier-james",
    "SPYCHER Lionel": "spycher-lionel",
    "SPYMONKEY ": "spymonkey",
    "SQUARE PEG THEATRE ": "square-peg-theatre",
    "SQUIBB Terence John": "squibb-terence-john",
    "SQUIER E G": "squier-e-g",
    "SQUIER William": "squier-william",
    "SQUILLARI Janine": "squillari-janine",
    "SQUIRE Aurin": "squire-aurin",
    "SQUIRE Zoe": "squire-zoe",
    "SQUIREK Mark": "squirek-mark",
    "SQUIRES Hayley": "squires-hayley",
    "SRAMEK Jean": "sramek-jean",
    "SRAUSS Bill": "srauss-bill",
    "SRBLJANOVIC Biljana": "srbljanovic-biljana",
    "SRIDHARAN Sathya": "sridharan-sathya",
    "SRINIVASAN Asha": "srinivasan-asha",
    "SRIRAM Nikhil": "sriram-nikhil",
    "SROKA Jerry": "sroka-jerry"
  }
};