export default {
  "metadata": {
    "results": 1376,
    "timeStamp": "2025-12-05T21:31:33.353Z",
    "url": "https://www.doollee.com/PlaywrightsS/S_playwrights_s-z.php"
  },
  "authors": {
    "SSEBANDEKE Isaac": "ssebandeke-isaac",
    "SSEKIRYANGKO Jackson": "ssekiryangko-jackson",
    "ST BERNARD Donna-Michelle": "st-bernard-donna-michelle",
    "ST CLAIR Andy": "st-clair-andy",
    "ST CLAIR Barbara": "st-clair-barbara",
    "ST CLAIR Jessica": "st-clair-jessica",
    "ST CLAIR John": "st-clair-john",
    "ST CLAIR Simone": "st-clair-simone",
    "ST CLAIR Sybil": "st-clair-sybil",
    "ST CLAIR Wesley": "st-clair-wesley",
    "ST GERMAIN Mark": "st-germain-mark",
    "ST JAMES Ann": "st-james-ann",
    "ST JAMES James": "st-james-james",
    "ST JOHANSER Joe": "st-johanser-joe",
    "ST JOHN Billy": "st-john-billy",
    "ST JOHN Christopher": "st-john-christopher",
    "ST JOHN Gordon": "st-john-gordon",
    "ST JOHN Wesley": "st-john-wesley",
    "ST JONES ": "st-jones",
    "ST LEDGER Will": "st-ledger-will",
    "ST MARTIN'S YOUTH ARTS CENTRE ": "st-martin-s-youth-arts-centre",
    "ST PIERRE Denise": "st-pierre-denise",
    "STAAB R C": "staab-r-c",
    "STAATS Amy": "staats-amy",
    "STAATS Andrea": "staats-andrea",
    "STABON HOUSE OPERA ": "stabon-house-opera",
    "STACE Christopher": "stace-christopher",
    "STACEY Paul": "stacey-paul",
    "STACHNIEWSKI Jan  ": "stachniewski-jan",
    "STACHURSKI Andrew": "stachurski-andrew",
    "STACHURSKI Christina": "stachurski-christina",
    "STACK Eric": "stack-eric",
    "STACK Steven": "stack-steven",
    "STACKHOUSE Kenneth": "stackhouse-kenneth",
    "STADD Arlene": "stadd-arlene",
    "STADT Judy": "stadt-judy",
    "STADTLANDER Erika": "stadtlander-erika",
    "STAFF Enid": "staff-enid",
    "STAFFA Rosanna": "staffa-rosanna",
    "STAFFORD Adam": "stafford-adam",
    "STAFFORD Janice": "stafford-janice",
    "STAFFORD Jenny": "stafford-jenny",
    "STAFFORD Jessica": "stafford-jessica",
    "STAFFORD Kate": "stafford-kate",
    "STAFFORD Kathleen": "stafford-kathleen",
    "STAFFORD Nick": "stafford-nick",
    "STAFFORD Pauline": "stafford-pauline",
    "STAFFORD Peggy": "stafford-peggy",
    "STAFFORD-CLARK Max": "stafford-clark-max",
    "STAGG Barry": "stagg-barry",
    "STAGG Chris": "stagg-chris",
    "STAGG Erin": "stagg-erin",
    "STAGG Philip": "stagg-philip",
    "STAGGS Chase": "staggs-chase",
    "STAHL Diana": "stahl-diana",
    "STAHL R Jim": "stahl-r-jim",
    "STAHL Raymund": "stahl-raymund",
    "STAHL Rebecca Lynn": "stahl-rebecca-lynn",
    "STAHL Stephen": "stahl-stephen",
    "STAHLHUTH Gayle": "stahlhuth-gayle",
    "STAIN, THE ": "stain-the",
    "STAINER Annie": "stainer-annie",
    "STAINES David": "staines-david",
    "STAINLAY Stephanie": "stainlay-stephanie",
    "STAINTON Linda": "stainton-linda",
    "STAIR Alistair (Bill)": "stair-alistair-bill",
    "STAIR Bill": "stair-bill",
    "STAITE Jackie": "staite-jackie",
    "STAJICH Steve": "stajich-steve",
    "STALEY Jessica": "staley-jessica",
    "STALHAM Dean": "stalham-dean",
    "STALLER David": "staller-david",
    "STALLINGS David": "stallings-david",
    "STALLINGS Larry": "stallings-larry",
    "STALLINGS Laurence": "stallings-laurence",
    "STALLONE Sylvester": "stallone-sylvester",
    "STALLWORTHY Simon": "stallworthy-simon",
    "STALOWITZ Andrea": "stalowitz-andrea",
    "STAMATELAKY Ellen": "stamatelaky-ellen",
    "STAMATIS Alexis": "stamatis-alexis",
    "STAMOS Dale Griffiths": "stamos-dale-griffiths",
    "STAMOS Deborah": "stamos-deborah",
    "STAMP Ellie": "stamp-ellie",
    "STAMP Joey": "stamp-joey",
    "STAMPEDE ": "stampede",
    "STAN Natalie": "stan-natalie",
    "STANBACK Thurman W": "stanback-thurman-w",
    "STANCATI Frank": "stancati-frank",
    "STANCATO Paul": "stancato-paul",
    "STANDERLINE Joe": "standerline-joe",
    "STANDJOFSKI Harry": "standjofski-harry",
    "STANDRING Sara": "standring-sara",
    "STANESCU Saviana": "stanescu-saviana",
    "STANEV Ivan": "stanev-ivan",
    "STANEY Helen": "staney-helen",
    "STANFORD Alan": "stanford-alan",
    "STANFORD Janet": "stanford-janet",
    "STANG Michael": "stang-michael",
    "STANGENBERG Carla": "stangenberg-carla",
    "STANHOPE Adele": "stanhope-adele",
    "STANIC Paula B": "stanic-paula-b",
    "STANIER M": "stanier-m",
    "STANIER Tom": "stanier-tom",
    "STANIEWSKI Wlodzimierz": "staniewski-wlodzimierz",
    "STANILAND Andrew": "staniland-andrew",
    "STANILAND Grace": "staniland-grace",
    "STANILOFF J S": "staniloff-j-s",
    "STANISAVILJEVIC Miodrag": "stanisaviljevic-miodrag",
    "STANISLAVSKAYA Katya": "stanislavskaya-katya",
    "STANKIEICZ Teresa": "stankieicz-teresa",
    "STANKOVIC Suzana": "stankovic-suzana",
    "STANLEY A J": "stanley-a-j",
    "STANLEY Alison": "stanley-alison",
    "STANLEY Andrew": "stanley-andrew",
    "STANLEY Dave": "stanley-dave",
    "STANLEY David": "stanley-david",
    "STANLEY Jack": "stanley-jack",
    "STANLEY James P": "stanley-james-p",
    "STANLEY Jeffrey": "stanley-jeffrey",
    "STANLEY Jessica": "stanley-jessica",
    "STANLEY John": "stanley-john",
    "STANLEY Mikayla": "stanley-mikayla",
    "STANLEY Ross": "stanley-ross",
    "STANLEY Talitha": "stanley-talitha",
    "STANLEY William": "stanley-william",
    "STANNARD Nigel": "stannard-nigel",
    "STANNARD Peter": "stannard-peter",
    "STAN'S CAFE ": "stans-cafe",
    "STANSELL Anna": "stansell-anna",
    "STANSELL Brent": "stansell-brent",
    "STANSELL Kymberlie": "stansell-kymberlie",
    "STANSHALL Vivian": "stanshall-vivian",
    "STANT David": "stant-david",
    "STANTON Andy": "stanton-andy",
    "STANTON Brian": "stanton-brian",
    "STANTON Denise": "stanton-denise",
    "STANTON Frances H": "stanton-frances-h",
    "STANTON Jane": "stanton-jane",
    "STANTON John": "stanton-john",
    "STANTON Phil": "stanton-phil",
    "STANTON Robert": "stanton-robert",
    "STANTON Roma": "stanton-roma",
    "STANTON Sophie": "stanton-sophie",
    "STANTON Susan Soon He": "stanton-susan-soon-he",
    "STANTON William": "stanton-william",
    "STAPLES Ian": "staples-ian",
    "STAPLES Laura": "staples-laura",
    "STAPLETON Berni": "stapleton-berni",
    "STAPLETON Jim": "stapleton-jim",
    "STAPLETON Lauren": "stapleton-lauren",
    "STAPLETON Noni": "stapleton-noni",
    "STAPLETON Terry": "stapleton-terry",
    "STAPP Elizabeth": "stapp-elizabeth",
    "STAPP Gary Ray": "stapp-gary-ray",
    "STAR Tracy": "star-tracy",
    "STARBUCK Ann": "starbuck-ann",
    "STARCATCHERS ": "starcatchers",
    "STARCHMAN Bryan": "starchman-bryan",
    "STARK Dianna": "stark-dianna",
    "STARK Jeff": "stark-jeff",
    "STARK Jenny": "stark-jenny",
    "STARK John": "stark-john",
    "STARK Michael K": "stark-michael-k",
    "STARK Susannah": "stark-susannah",
    "STARK Ulf": "stark-ulf",
    "STARK Wilma G": "stark-wilma-g",
    "STARKE Roland": "starke-roland",
    "STARKEY David": "starkey-david",
    "STARKEY Simon": "starkey-simon",
    "STARKID ": "starkid",
    "STARKIE Martin": "starkie-martin",
    "STARKIE Walter": "starkie-walter",
    "STARK-ORDISH Gaelle": "stark-ordish-gaelle",
    "STARKWEATHER David": "starkweather-david",
    "STARLIN Simon": "starlin-simon",
    "STARLITE Tammy Faye": "starlite-tammy-faye",
    "STARNES Timothy D": "starnes-timothy-d",
    "STAROSELSKY Edward": "staroselsky-edward",
    "STAROSTA Stephen": "starosta-stephen",
    "STARR Arigon": "starr-arigon",
    "STARR Ben": "starr-ben",
    "STARR Brian David Delaney": "starr-brian-david-delaney",
    "STARR Corrie": "starr-corrie",
    "STARR Floyd Favel": "starr-floyd-favel",
    "STARR Michael": "starr-michael",
    "STARR Nick": "starr-nick",
    "STARSMEARE D": "starsmeare-d",
    "START Danny": "start-danny",
    "STARTIN Simon": "startin-simon",
    "STARZYK Joe": "starzyk-joe",
    "STASSAERT Lucienne": "stassaert-lucienne",
    "STATEN Pat": "staten-pat",
    "STATHAM Keith": "statham-keith",
    "STATION HOUSE ": "station-house",
    "STATON Candice": "staton-candice",
    "STATON Frank H": "staton-frank-h",
    "STATON Owen": "staton-owen",
    "STAUBITZ Danielle": "staubitz-danielle",
    "STAUNTON Robert": "staunton-robert",
    "STAVEACRE Tony": "staveacre-tony",
    "STAVICK Tony": "stavick-tony",
    "STAVIS Barrie": "stavis-barrie",
    "STAVRINOU Lara": "stavrinou-lara",
    "STAY Mark": "stay-mark",
    "STAYTON Richard": "stayton-richard",
    "STAYTON Timothy": "stayton-timothy",
    "STE CROIX David": "ste-croix-david",
    "STEAD Steven": "stead-steven",
    "STEADMAN Pam Munson": "steadman-pam-munson",
    "STEADMAN Pamela J": "steadman-pamela-j",
    "STEADMAN Susan M": "steadman-susan-m",
    "STEAFEL Sheila": "steafel-sheila",
    "STEARNS David Patrick": "stearns-david-patrick",
    "STEARNS Donna": "stearns-donna",
    "STEARNS Elizabeth": "stearns-elizabeth",
    "STEARNS Jayne B": "stearns-jayne-b",
    "STEARNS Sharon": "stearns-sharon",
    "STEBBING Eve": "stebbing-eve",
    "STEBBINGS Paul": "stebbings-paul",
    "STEBBINGS Peter": "stebbings-peter",
    "STEDMAN Eric": "stedman-eric",
    "STEED Patrick": "steed-patrick",
    "STEED Ruth": "steed-ruth",
    "STEEL Beth": "steel-beth",
    "STEEL Emily": "steel-emily",
    "STEEL George": "steel-george",
    "STEEL Gordon": "steel-gordon",
    "STEEL John": "steel-john",
    "STEEL Judy": "steel-judy",
    "STEEL Liam": "steel-liam",
    "STEEL William A": "steel-william-a",
    "STEEL Zachary": "steel-zachary",
    "STEEL WASP THEATRE CO ": "steel-wasp-theatre-co",
    "STEELE Austin": "steele-austin",
    "STEELE Dan": "steele-dan",
    "STEELE Donald": "steele-donald",
    "STEELE Emily": "steele-emily",
    "STEELE Eve": "steele-eve",
    "STEELE Jevetta": "steele-jevetta",
    "STEELE John": "steele-john",
    "STEELE Kameron": "steele-kameron",
    "STEELE Lauren": "steele-lauren",
    "STEELE Lezley": "steele-lezley",
    "STEELE Lorie": "steele-lorie",
    "STEELE Matt": "steele-matt",
    "STEELE Max": "steele-max",
    "STEELE Mike": "steele-mike",
    "STEELE Mike (1)": "steele-mike-1",
    "STEELE Rebecca": "steele-rebecca",
    "STEELE Richard": "steele-richard",
    "STEELE Rosalie": "steele-rosalie",
    "STEELE Sir Richard": "steele-sir-richard",
    "STEELSMITH Mary": "steelsmith-mary",
    "STEELY Yvonne": "steely-yvonne",
    "STEEN David": "steen-david",
    "STEEN / SWEENEY ": "steen-sweeney",
    "STEEN III Charles Augustus": "steen-iii-charles-augustus",
    "STEEPWAYS PRODUCTIONS ": "steepways-productions",
    "STEER Matthew": "steer-matthew",
    "STEER Mike": "steer-mike",
    "STEFAN Kevin": "stefan-kevin",
    "STEFAN Peca": "stefan-peca",
    "STEFANOVSKI Goran": "stefanovski-goran",
    "STEFANSSON Davio": "stefansson-davio",
    "STEFE Milan": "stefe-milan",
    "STEFFAN Chuck": "steffan-chuck",
    "STEGEN Marc": "stegen-marc",
    "STEGER Lawrence": "steger-lawrence",
    "STEIGERWALD Karel": "steigerwald-karel",
    "STEIJN Robert": "steijn-robert",
    "STEIMAN Jim": "steiman-jim",
    "STEIN Adi": "stein-adi",
    "STEIN Anthony": "stein-anthony",
    "STEIN Daniel": "stein-daniel",
    "STEIN Daniel A": "stein-daniel-a",
    "STEIN Deborah": "stein-deborah",
    "STEIN Francine": "stein-francine",
    "STEIN Gertrude": "stein-gertrude",
    "STEIN James R": "stein-james-r",
    "STEIN Jared J": "stein-jared-j",
    "STEIN Joel": "stein-joel",
    "STEIN Joseph": "stein-joseph",
    "STEIN Julie": "stein-julie",
    "STEIN Lauren": "stein-lauren",
    "STEIN Lou": "stein-lou",
    "STEIN Mark": "stein-mark",
    "STEIN Meridee": "stein-meridee",
    "STEIN Myron S": "stein-myron-s",
    "STEIN Navida": "stein-navida",
    "STEIN Paul Nicolai": "stein-paul-nicolai",
    "STEIN Robert Illes": "stein-robert-illes",
    "STEIN Sol": "stein-sol",
    "STEIN Susan": "stein-susan",
    "STEIN Sylvester": "stein-sylvester",
    "STEINBAUM Linda Felton": "steinbaum-linda-felton",
    "STEINBECK John": "steinbeck-john",
    "STEINBERG Alan L": "steinberg-alan-l",
    "STEINBERG Douglas": "steinberg-douglas",
    "STEINBERG Eric": "steinberg-eric",
    "STEINBERG John": "steinberg-john",
    "STEINBERG Katherine": "steinberg-katherine",
    "STEINBERG Kevin": "steinberg-kevin",
    "STEINBERG Meredith": "steinberg-meredith",
    "STEINBRUNER Greg": "steinbruner-greg",
    "STEINER Ben": "steiner-ben",
    "STEINER Jane": "steiner-jane",
    "STEINER Riley": "steiner-riley",
    "STEINER Rudolf": "steiner-rudolf",
    "STEINER Sam": "steiner-sam",
    "STEINER Theron": "steiner-theron",
    "STEINFELD J J": "steinfeld-j-j",
    "STEINHAGEN Joe": "steinhagen-joe",
    "STEINHAGEN Jon": "steinhagen-jon",
    "STEINHARDT Herschel": "steinhardt-herschel",
    "STEINKELLNER Bill": "steinkellner-bill",
    "STEINKELLNER Cheri": "steinkellner-cheri",
    "STEINKELLNER Kit": "steinkellner-kit",
    "STEINMAN Jim": "steinman-jim",
    "STEINMAN Steve": "steinman-steve",
    "STEINMETZ Nicole F": "steinmetz-nicole-f",
    "STEINOUR Marcus": "steinour-marcus",
    "STEINR Jeff": "steinr-jeff",
    "STEINSSON Gudmundur": "steinsson-gudmundur",
    "STEINWACHS Ginka": "steinwachs-ginka",
    "STEINWEISS Leslie": "steinweiss-leslie",
    "STEIR Judith Shubow": "steir-judith-shubow",
    "STEITZER Jeff   ": "steitzer-jeff",
    "STELLA Bernardo": "stella-bernardo",
    "STELLA DEN HAAG ": "stella-den-haag",
    "STELLMACH Barbara": "stellmach-barbara",
    "STEMBRIDGE Gerard": "stembridge-gerard",
    "STEMM Rick": "stemm-rick",
    "STEMPLE Beth Campbell": "stemple-beth-campbell",
    "STENHAM Polly": "stenham-polly",
    "STENHOUSE Anne": "stenhouse-anne",
    "STENHOUSE James": "stenhouse-james",
    "STENHOUSE John": "stenhouse-john",
    "STENNETT Roger": "stennett-roger",
    "STENNING Stephen": "stenning-stephen",
    "STENT Malcolm": "stent-malcolm",
    "STEPANIAN Shahan": "stepanian-shahan",
    "STEPENBERG Alejandro": "stepenberg-alejandro",
    "STEPGHENSON Lola": "stepghenson-lola",
    "STEPHANOU Sofia": "stephanou-sofia",
    "STEPHEN Ian": "stephen-ian",
    "STEPHEN V Stephen": "stephen-v-stephen",
    "STEPHEN Venus": "stephen-venus",
    "STEPHENS Brad": "stephens-brad",
    "STEPHENS Carmel": "stephens-carmel",
    "STEPHENS Cecil G": "stephens-cecil-g",
    "STEPHENS Christine": "stephens-christine",
    "STEPHENS Connie": "stephens-connie",
    "STEPHENS Craig": "stephens-craig",
    "STEPHENS Cynthia": "stephens-cynthia",
    "STEPHENS Elizabeth": "stephens-elizabeth",
    "STEPHENS Geoff": "stephens-geoff",
    "STEPHENS Harry": "stephens-harry",
    "STEPHENS Jenny": "stephens-jenny",
    "STEPHENS Jon": "stephens-jon",
    "STEPHENS Jonty": "stephens-jonty",
    "STEPHENS Mick": "stephens-mick",
    "STEPHENS Minda": "stephens-minda",
    "STEPHENS Simon": "stephens-simon",
    "STEPHENS Thomas W": "stephens-thomas-w",
    "STEPHENS Ty": "stephens-ty",
    "STEPHENS Venus": "stephens-venus",
    "STEPHENSON Ann": "stephenson-ann",
    "STEPHENSON Clare": "stephenson-clare",
    "STEPHENSON Denise": "stephenson-denise",
    "STEPHENSON Jill": "stephenson-jill",
    "STEPHENSON Jonathan": "stephenson-jonathan",
    "STEPHENSON Lola": "stephenson-lola",
    "STEPHENSON Marcus Lee": "stephenson-marcus-lee",
    "STEPHENSON Pete": "stephenson-pete",
    "STEPHENSON R Rex": "stephenson-r-rex",
    "STEPHENSON Shelagh": "stephenson-shelagh",
    "STEPHENSON Stephanie": "stephenson-stephanie",
    "STEPIEN Meredith": "stepien-meredith",
    "STEPP Walt": "stepp-walt",
    "STEPPING STONES THEATRE STUDENTS ": "stepping-stones-theatre-students",
    "STEPPLING John": "steppling-john",
    "STEPT Sam": "stept-sam",
    "STERLING Anthony": "sterling-anthony",
    "STERLING Bryan B": "sterling-bryan-b",
    "STERLING Glenda": "sterling-glenda",
    "STERLING Linder": "sterling-linder",
    "STERLING Martin": "sterling-martin",
    "STERLING Pamela": "sterling-pamela",
    "STERLING Robert": "sterling-robert",
    "STERN Adrienne": "stern-adrienne",
    "STERN Alan": "stern-alan",
    "STERN Barbara": "stern-barbara",
    "STERN Buddy": "stern-buddy",
    "STERN Cheryl": "stern-cheryl",
    "STERN Claudia": "stern-claudia",
    "STERN Daniel": "stern-daniel",
    "STERN Gerd": "stern-gerd",
    "STERN Herb": "stern-herb",
    "STERN James": "stern-james",
    "STERN Marcus": "stern-marcus",
    "STERN Michaela": "stern-michaela",
    "STERN Nikki": "stern-nikki",
    "STERN Sarah": "stern-sarah",
    "STERN Tania": "stern-tania",
    "STERNBACH Gerald": "sternbach-gerald",
    "STERNBERG Darcy Heller": "sternberg-darcy-heller",
    "STERNBERG Hannah": "sternberg-hannah",
    "STERNBERG Pat": "beecham-dolly",
    "STERNBERG Rachel": "sternberg-rachel",
    "STERNBURG Janet": "sternburg-janet",
    "STERNE Emma Gelders": "sterne-emma-gelders",
    "STERNE Nicokola": "sterne-nicokola",
    "STERNER Jerry": "sterner-jerry",
    "STERNER III Joseph A": "sterner-iii-joseph-a",
    "STERNFIELD Allen": "sternfield-allen",
    "STERNHEIM Carl": "sternheim-carl",
    "STERNIN Robert": "sternin-robert",
    "STERNTHAL Burton": "sternthal-burton",
    "STERRITT Bill": "sterritt-bill",
    "STERRY Andrew": "sterry-andrew",
    "STERRY David Henry": "sterry-david-henry",
    "STERRY Taren": "sterry-taren",
    "STESS Ariel": "stess-ariel",
    "STETSON Jeffrey": "stetson-jeffrey",
    "STETSON Kent": "stetson-kent",
    "STEUR Nick": "steur-nick",
    "STEVANOVICH Vidosav": "stevanovich-vidosav",
    "STEVEN Allan": "steven-allan",
    "STEVEN Nicole": "steven-nicole",
    "STEVEN Phyl": "steven-phyl",
    "STEVENS Allan": "stevens-allan",
    "STEVENS Athena": "stevens-athena",
    "STEVENS Chambers": "stevens-chambers",
    "STEVENS Chris": "stevens-chris",
    "STEVENS Claudia": "stevens-claudia",
    "STEVENS David": "stevens-david",
    "STEVENS Dudley": "stevens-dudley",
    "STEVENS Ed": "stevens-ed",
    "STEVENS Elisabeth": "stevens-elisabeth",
    "STEVENS Emma": "stevens-emma",
    "STEVENS G W": "stevens-g-w",
    "STEVENS Gary": "stevens-gary",
    "STEVENS Henry H": "stevens-henry-h",
    "STEVENS Jack": "stevens-jack",
    "STEVENS Janeen": "stevens-janeen",
    "STEVENS Jean": "stevens-jean",
    "STEVENS Jeanette Mathewes": "stevens-jeanette-mathewes",
    "STEVENS Jef": "stevens-jef",
    "STEVENS John": "stevens-john",
    "STEVENS John A": "stevens-john-a",
    "STEVENS John Martin": "stevens-john-martin",
    "STEVENS Josephine": "stevens-josephine",
    "STEVENS June": "stevens-june",
    "STEVENS K S": "stevens-k-s",
    "STEVENS Laura": "stevens-laura",
    "STEVENS Leegrid": "stevens-leegrid",
    "STEVENS Leslie": "stevens-leslie",
    "STEVENS Marcus": "stevens-marcus",
    "STEVENS Mark": "stevens-mark",
    "STEVENS Matthew": "stevens-matthew",
    "STEVENS Michael": "stevens-michael",
    "STEVENS Oren": "stevens-oren",
    "STEVENS Philip": "stevens-philip",
    "STEVENS Ron Scott": "stevens-ron-scott",
    "STEVENS Ronald \"Smokey\"": "stevens-ronald",
    "STEVENS Ryan": "stevens-ryan",
    "STEVENS Sophie": "stevens-sophie",
    "STEVENS Tassos": "stevens-tassos",
    "STEVENS Thomas Wood": "stevens-thomas-wood",
    "STEVENS Wallace": "stevens-wallace",
    "STEVENS, JR George": "stevens-jr-george",
    "STEVENS-ESTABROOK Sarah": "stevens-estabrook-sarah",
    "STEVENS-GUILLE Gillian": "stevens-guille-gillian",
    "STEVENSON D E": "stevenson-d-e",
    "STEVENSON Den": "stevenson-den",
    "STEVENSON Devynne": "stevenson-devynne",
    "STEVENSON Elizabeth": "stevenson-elizabeth",
    "STEVENSON Gerda": "stevenson-gerda",
    "STEVENSON J V": "stevenson-j-v",
    "STEVENSON John": "stevenson-john",
    "STEVENSON Katrina": "stevenson-katrina",
    "STEVENSON Pam": "stevenson-pam",
    "STEVENSON Ricky": "stevenson-ricky",
    "STEVENSON III William Adell": "stevenson-iii-william-adell",
    "STEVENTON Gillian": "steventon-gillian",
    "STEVER Ed": "stever-ed",
    "STEW ": "stew",
    "STEWARD Artie": "steward-artie",
    "STEWARD Brian": "steward-brian",
    "STEWARD Ron": "steward-ron",
    "STEWARD Sam": "steward-sam",
    "STEWARD Victoria": "steward-victoria",
    "STEWART Allan": "stewart-allan",
    "STEWART Anastasia": "stewart-anastasia",
    "STEWART Angela D": "stewart-angela-d",
    "STEWART Anna": "stewart-anna",
    "STEWART Bob": "stewart-bob",
    "STEWART Brian": "stewart-brian",
    "STEWART Brian K": "stewart-brian-k",
    "STEWART Bruce": "stewart-bruce",
    "STEWART Cameron": "stewart-cameron",
    "STEWART Carol": "stewart-carol",
    "STEWART Cherie": "stewart-cherie",
    "STEWART Connie": "stewart-connie",
    "STEWART Craig": "stewart-craig",
    "STEWART Dave": "stewart-dave",
    "STEWART David": "stewart-david",
    "STEWART Delano": "stewart-delano",
    "STEWART Denise": "stewart-denise",
    "STEWART Donald Ogden": "stewart-donald-ogden",
    "STEWART Doug": "stewart-doug",
    "STEWART Douglas": "stewart-douglas",
    "STEWART Douglas Day": "stewart-douglas-day",
    "STEWART E Innes": "stewart-e-innes",
    "STEWART Ellen": "stewart-ellen",
    "STEWART Ellie": "stewart-ellie",
    "STEWART Ena Lamont": "stewart-ena-lamont",
    "STEWART Fiona": "stewart-fiona",
    "STEWART Gary": "stewart-gary",
    "STEWART Glenn M": "stewart-glenn-m",
    "STEWART Hal D": "stewart-hal-d",
    "STEWART J M": "stewart-j-m",
    "STEWART Jake": "stewart-jake",
    "STEWART James": "stewart-james",
    "STEWART Jamie": "stewart-jamie",
    "STEWART Jaye": "stewart-jaye",
    "STEWART Jesse": "stewart-jesse",
    "STEWART John D": "stewart-john-d",
    "STEWART Jon Lachlan": "stewart-jon-lachlan",
    "STEWART Jordan M": "stewart-jordan-m",
    "STEWART Joshua Hopton": "stewart-joshua-hopton",
    "STEWART Katharine": "stewart-katharine",
    "STEWART L": "stewart-l",
    "STEWART Lindsay": "stewart-lindsay",
    "STEWART Lucy": "stewart-lucy",
    "STEWART Mahonri": "stewart-mahonri",
    "STEWART Malcolm": "stewart-malcolm",
    "STEWART Martin": "stewart-martin",
    "STEWART Maurice": "stewart-maurice",
    "STEWART Michael": "stewart-michael",
    "STEWART Michael Kenneth": "stewart-michael-kenneth",
    "STEWART Nell": "stewart-nell",
    "STEWART Patrick": "stewart-patrick",
    "STEWART Paul": "stewart-paul",
    "STEWART Peter": "stewart-peter",
    "STEWART Reg": "stewart-reg",
    "STEWART Roderick": "stewart-roderick",
    "STEWART Ron": "stewart-ron",
    "STEWART Susan": "stewart-susan",
    "STEWART Tory": "stewart-tory",
    "STEWART Vanessa Claire": "stewart-vanessa-claire",
    "STEWART Victoria": "stewart-victoria",
    "STEWART William": "stewart-william",
    "STEWART Zachary": "stewart-zachary",
    "STEWART-BROWN Christi": "stewart-brown-christi",
    "STEWART-DAVID Mary": "stewart-david-mary",
    "STEWART-JONES Darren": "stewart-jones-darren",
    "STEWART-PARK Angela": "stewart-park-angela",
    "STEWART-TEWHIU Josephine": "stewart-tewhiu-josephine",
    "STEZIN Chris": "stezin-chris",
    "STIBBARD Lucas": "stibbard-lucas",
    "STICKLAND Eugene": "stickland-eugene",
    "STICKLEN Darien": "sticklen-darien",
    "STICKLES Jessica": "stickles-jessica",
    "STICKNEY Dorothy": "stickney-dorothy",
    "STICKNEY Phyllis Yvonne": "stickney-phyllis-yvonne",
    "STIENBLOCK Geoffrey": "stienblock-geoffrey",
    "STILES Chris": "stiles-chris",
    "STILES George": "stiles-george",
    "STILES Thelma Jackson": "stiles-thelma-jackson",
    "STILGOE Richard": "stilgoe-richard",
    "STILL James": "still-james",
    "STILL Melly": "still-melly",
    "STILLER Mike": "stiller-mike",
    "STILLER Robert": "stiller-robert",
    "STILLION Sarah": "stillion-sarah",
    "STILLITANO Carl": "stillitano-carl",
    "STILLMAN Deanne": "stillman-deanne",
    "STILLMAN Heidi": "stillman-heidi",
    "STILLS Paul": "stills-paul",
    "STILLSON Alan": "stillson-alan",
    "STIMAC Anthony": "stimac-anthony",
    "STIMAC Elias": "stimac-elias",
    "STIMPSON Candace": "stimpson-candace",
    "STIMPSON Nick": "stimpson-nick",
    "STIMPSON Tim": "stimpson-tim",
    "STIMSON Nick": "stimson-nick",
    "STINGER Laura Berlin": "stinger-laura-berlin",
    "STINGERSTEIN Jeffrey": "stingerstein-jeffrey",
    "STINSON Hank": "stinson-hank",
    "STINSON John": "stinson-john",
    "STINSON Kim": "stinson-kim",
    "STIRLING Glenda": "stirling-glenda",
    "STIRLING Martin": "stirling-martin",
    "STIRLING Richard": "stirling-richard",
    "STIRNER Brian": "stirner-brian",
    "STITT Don": "stitt-don",
    "STITT Georgia": "stitt-georgia",
    "STITT Milan": "stitt-milan",
    "STITZ Tim": "stitz-tim",
    "STIVEN Edwin": "stiven-edwin",
    "STIVENS Dal": "stivens-dal",
    "STIVICIC Tena": "stivicic-tena",
    "STOBEROCK Johanna": "stoberock-johanna",
    "STOCK James": "stock-james",
    "STOCK Michael": "stock-michael",
    "STOCK Mike": "stock-mike",
    "STOCKDALE Gary": "stockdale-gary",
    "STOCKENSTROM Truda": "stockenstrom-truda",
    "STOCKER Darja": "stocker-darja",
    "STOCKHAM Linda": "stockham-linda",
    "STOCKHAM Richard": "stockham-richard",
    "STOCKLEY Liz": "stockley-liz",
    "STOCKLEY Sandra": "stockley-sandra",
    "STOCKMAN Allison Arkell": "stockman-allison-arkell",
    "STOCKMAN Michael": "stockman-michael",
    "STOCKS Bryan": "stocks-bryan",
    "STOCKS Ian": "stocks-ian",
    "STOCKTON Anne": "stockton-anne",
    "STOCKTON Eliot": "stockton-eliot",
    "STOCKTON Phil": "stockton-phil",
    "STOCKTON Richard F": "stockton-richard-f",
    "STOCKWELL Alec": "stockwell-alec",
    "STOCKWELL Jeremy": "stockwell-jeremy",
    "STOCKWELL Richard": "stockwell-richard",
    "STOCKWELL Sally": "stockwell-sally",
    "STODDARD Christine": "stoddard-christine",
    "STODDART Hugh": "stoddart-hugh",
    "STODDART Kirsten": "stoddart-kirsten",
    "STODER Vinny": "stoder-vinny",
    "STODERL Susan": "stoderl-susan",
    "STOFFEL Matthew Thomas": "stoffel-matthew-thomas",
    "STOFFELS Anne": "stoffels-anne",
    "STOFFELS Erika": "stoffels-erika",
    "STOHL Hank": "stohl-hank",
    "STOHR-DANZIGER Flora": "stohr-danziger-flora",
    "STOIZ Robert": "stoiz-robert",
    "STOKER Willard": "stoker-willard",
    "STOKES Fregmonto": "stokes-fregmonto",
    "STOKES Herbert": "stokes-herbert",
    "STOKES Jack": "stokes-jack",
    "STOKES Jo": "stokes-jo",
    "STOKES Katie": "stokes-katie",
    "STOKES Leslie": "stokes-leslie",
    "STOKES Lianne": "stokes-lianne",
    "STOKES Mataara": "stokes-mataara",
    "STOKES Philip": "stokes-philip",
    "STOKES Rebecca Jane": "stokes-rebecca-jane",
    "STOKES Robert": "stokes-robert",
    "STOKES Sewell": "stokes-sewell",
    "STOKES Tony": "stokes-tony",
    "STOKLE Norman": "stokle-norman",
    "STOKLEY Margie": "stokley-margie",
    "STOKLOS Denise": "stoklos-denise",
    "STOLFI Daniel": "stolfi-daniel",
    "STOLLER Aaron": "stoller-aaron",
    "STOLLER Brad": "stoller-brad",
    "STOLLER Dani": "stoller-dani",
    "STOLLER Nick": "stoller-nick",
    "STOLLER Samuel Pitt": "stoller-samuel-pitt",
    "STOLOWITZ Andrea": "stolowitz-andrea",
    "STOLTE Chris": "stolte-chris",
    "STOLTZ Tom": "stoltz-tom",
    "STOLTZER Jeff": "stoltzer-jeff",
    "STOLTZFUS Robert": "stoltzfus-robert",
    "STOLZ Tom": "stolz-tom",
    "STOLZER Alan": "stolzer-alan",
    "STOLZER Jeff": "stolzer-jeff",
    "STOMP ": "stomp",
    "STONE Adam": "stone-adam",
    "STONE Arnold M": "stone-arnold-m",
    "STONE Barnaby": "stone-barnaby",
    "STONE Barry": "stone-barry",
    "STONE Ben": "stone-ben",
    "STONE Betty": "stone-betty",
    "STONE Bob": "stone-bob",
    "STONE Caroline": "stone-caroline",
    "STONE Claire": "stone-claire",
    "STONE Darius": "stone-darius",
    "STONE Doug": "stone-doug",
    "STONE Dudley": "stone-dudley",
    "STONE Gene": "stone-gene",
    "STONE Harry": "stone-harry",
    "STONE Joel": "stone-joel",
    "STONE Jonathan": "stone-jonathan",
    "STONE Ken": "stone-ken",
    "STONE Lauren": "stone-lauren",
    "STONE Lou": "stone-lou",
    "STONE Madeline": "stone-madeline",
    "STONE Matt": "stone-matt",
    "STONE Merritt": "stone-merritt",
    "STONE Michael": "stone-michael",
    "STONE Mike": "stone-mike",
    "STONE Natalie": "stone-natalie",
    "STONE Peter": "stone-peter",
    "STONE Rhashan": "stone-rhashan",
    "STONE Rich": "stone-rich",
    "STONE Richard": "stone-richard",
    "STONE Rick": "stone-rick",
    "STONE Robert J": "stone-robert-j",
    "STONE Rod": "stone-rod",
    "STONE Simon": "stone-simon",
    "STONE Tiffany": "stone-tiffany",
    "STONE Tod": "stone-tod",
    "STONE Trude": "stone-trude",
    "STONE Walter W": "stone-walter-w",
    "STONE Wilson": "stone-wilson",
    "STONE SOUP THEATRE ARTS ": "stone-soup-theatre-arts",
    "STONEBURGER Mark": "stoneburger-mark",
    "STONEKING Billy Marshall": "stoneking-billy-marshall",
    "STONES Ant": "stones-ant",
    "STOOP Bob": "stoop-bob",
    "STOPPARD Tom": "stoppard-tom",
    "STOPPELS June": "stoppels-june",
    "STOPPLEWORTH Rick": "stoppleworth-rick",
    "STORCK Patrick": "storck-patrick",
    "STORCKMAN Annette": "storckman-annette",
    "STOREN Mark": "storen-mark",
    "STORER Edward": "storer-edward",
    "STOREY Charles": "storey-charles",
    "STOREY David": "storey-david",
    "STOREY Evan": "storey-evan",
    "STOREY Isabel": "storey-isabel",
    "STOREY Ralph": "storey-ralph",
    "STOREY Raymond": "storey-raymond",
    "STOREY Robert": "storey-robert",
    "STORFER Peter": "storfer-peter",
    "STORGARD Johan": "storgard-johan",
    "STORIALE Paul Anthony": "storiale-paul-anthony",
    "STORK Charles Wharton": "stork-charles-wharton",
    "STORM Lesley": "storm-lesley",
    "STORM William": "storm-william",
    "STORM IN A TEACUP PRODUCTIONS ": "storm-in-a-teacup-productions",
    "STORNAIUOLO Vincenzo": "stornaiuolo-vincenzo",
    "STORNI Federico": "storni-federico",
    "STOROR Mark": "storor-mark",
    "STORY Anthony": "story-anthony",
    "STORZ Moni Lai": "storz-moni-lai",
    "STOTHERS John": "stothers-john",
    "STOTT Andrew": "stott-andrew",
    "STOTT Antonia": "stott-antonia",
    "STOTT David": "stott-david",
    "STOTT Ivan": "stott-ivan",
    "STOTT Mike": "stott-mike",
    "STOTTS Sara": "stotts-sara",
    "STOUR Robert": "stour-robert",
    "STOURTON Ivo": "stourton-ivo",
    "STOUT Callan": "stout-callan",
    "STOUT Heather N": "stout-heather-n",
    "STOUT Michael": "stout-michael",
    "STOVALL Jordan Kendall": "stovall-jordan-kendall",
    "STOVALL Paul Oakley": "stovall-paul-oakley",
    "STOVER Andi": "stover-andi",
    "STOVER Sally": "stover-sally",
    "STOVER Shelly": "stover-shelly",
    "STOVICH John": "stovich-john",
    "STOWE Gary": "stowe-gary",
    "STOWE John": "stowe-john",
    "STOWE Stephanie": "stowe-stephanie",
    "STOWELL J D": "stowell-j-d",
    "STOWELL Jim": "stowell-jim",
    "STOWERS Tony": "stowers-tony",
    "STRACHAN Alan": "strachan-alan",
    "STRACHAN Angus": "strachan-angus",
    "STRACHAN David": "strachan-david",
    "STRACHAN Keith": "strachan-keith",
    "STRACHAN Lindsay": "strachan-lindsay",
    "STRACHAN Liz": "strachan-liz",
    "STRACHAN Matthew": "strachan-matthew",
    "STRACHAN Tony": "strachan-tony",
    "STRACHAN Zoe": "strachan-zoe",
    "STRACHEN Barney": "strachen-barney",
    "STRACHEY Lytton": "strachey-lytton",
    "STRADLEY BJ": "stradley-bj",
    "STRADLING Matthew": "stradling-matthew",
    "STRAFFORD Steve": "strafford-steve",
    "STRAHS James": "strahs-james",
    "STRAHS Jim": "strahs-jim",
    "STRAIN Christopher": "strain-christopher",
    "STRAIN E H": "strain-e-h",
    "STRAITON Paschale": "straiton-paschale",
    "STRAMM August": "stramm-august",
    "STRANACK J": "stranack-j",
    "STRAND Bernie": "strand-bernie",
    "STRAND Chuck": "strand-chuck",
    "STRAND John": "strand-john",
    "STRAND Richard": "strand-richard",
    "STRANDGARD Maurice": "strandgard-maurice",
    "STRANDIN David": "strandin-david",
    "STRANG Dougie": "strang-dougie",
    "STRANGE Abigail": "strange-abigail",
    "STRANGE Elliot": "strange-elliot",
    "STRANGE Hedley": "strange-hedley",
    "STRANGE Liz": "strange-liz",
    "STRANGE Steven": "strange-steven",
    "STRANGE FRUIT ": "strange-fruit",
    "STRANGER THEATRE COMPANY ": "stranger-theatre-company",
    "STRANGIO Laurence": "strangio-laurence",
    "STRANGIO Steve": "strangio-steve",
    "STRASBERG John": "strasberg-john",
    "STRASFOGEL Ian": "strasfogel-ian",
    "STRASSER Robert": "strasser-robert",
    "STRASSER Walt F": "strasser-walt-f",
    "STRATAKOS Diamando": "stratakos-diamando",
    "STRATE Heidi": "strate-heidi",
    "STRATEGIER Felix": "strategier-felix",
    "STRATFORD Aoise": "stratford-aoise",
    "STRATFORD Helen": "stratford-helen",
    "STRATFORD Jonathan": "stratford-jonathan",
    "STRATH Deirdre": "strath-deirdre",
    "STRATHCONA TC ": "strathcona-tc",
    "STRATIEV Stanislav": "stratiev-stanislav",
    "STRATIS Zack": "stratis-zack",
    "STRATTON Allan": "stratton-allan",
    "STRATTON Chris": "stratton-chris",
    "STRATTON Dave": "stratton-dave",
    "STRATTON Neil": "stratton-neil",
    "STRAUGHAN Peter": "straughan-peter",
    "STRAUS Billy": "straus-billy",
    "STRAUSFELD Laura": "strausfeld-laura",
    "STRAUSS Adam": "strauss-adam",
    "STRAUSS Botho": "strauss-botho",
    "STRAUSS David": "strauss-david",
    "STRAUSSER Frank": "strausser-frank",
    "STRAUSSER Jeffrey": "strausser-jeffrey",
    "STRAUTMANN Jake": "strautmann-jake",
    "STRAVINSKY Igor": "stravinsky-igor",
    "STRAVRINOU Lara": "stravrinou-lara",
    "STRAW Ashley": "straw-ashley",
    "STRAWBRIDGE Jacqueline": "strawbridge-jacqueline",
    "STRAWBRIDGE Shane": "strawbridge-shane",
    "STRAWDERMAN Randy": "strawderman-randy",
    "STRAWHAN Gavin": "strawhan-gavin",
    "STRAYER Rachel": "strayer-rachel",
    "STREATFIELD Noel": "streatfield-noel",
    "STREEK Gordon": "streek-gordon",
    "STREERUWITZ Marlene": "streeruwitz-marlene",
    "STREET Andy": "street-andy",
    "STREET Angela": "street-angela",
    "STREET Ben": "street-ben",
    "STREET Catherine": "street-catherine",
    "STREET Sean": "street-sean",
    "STREET Stephanie": "street-stephanie",
    "STREET Tracey": "street-tracey",
    "STREIT Clifford": "streit-clifford",
    "STREITZ Paul": "streitz-paul",
    "STRELICH Thomas": "strelich-thomas",
    "STRELL Meghan": "strell-meghan",
    "STREMPEK William": "strempek-william",
    "STRETCH PEOPLE ": "stretch-people",
    "STRETE Craig Kee": "strete-craig-kee",
    "STRETRON Charles": "stretron-charles",
    "STREZIN Chris": "strezin-chris",
    "STRICKLAND Jon": "strickland-jon",
    "STRICKLAND Margot": "strickland-margot",
    "STRICKLAND Paul": "strickland-paul",
    "STRICKLAND Paul (2)": "strickland-paul-2",
    "STRICKLYN Ray": "stricklyn-ray",
    "STRICKSON Adam": "strickson-adam",
    "STRICKSON Mark": "strickson-mark",
    "STRICTLAND Eugene": "strictland-eugene",
    "STRID George L O": "strid-george-l-o",
    "STRIDE Gavin": "stride-gavin",
    "STRIDER Errol": "strider-errol",
    "STRIDINGER Kurt Richard": "stridinger-kurt-richard",
    "STRIETMAN Elsa": "strietman-elsa",
    "STRIFE Rashawn": "strife-rashawn",
    "STRIFF Erin": "striff-erin",
    "STRIJARDS Frans": "strijards-frans",
    "STRIKE THE MAN BAND ": "strike-the-man-band",
    "STRIMLING Arthur": "strimling-arthur",
    "STRINDBERG August": "strindberg-august",
    "STRINDEN Marie": "strinden-marie",
    "STRINES THEATRE ": "strines-theatre",
    "STRINGER Grant": "stringer-grant",
    "STRINGER Richard": "stringer-richard",
    "STRINGLE Bennie": "stringle-bennie",
    "STRINGS ATTACHED ": "strings-attached",
    "STRITCH Elaine": "stritch-elaine",
    "STRITMATTER Thomas": "stritmatter-thomas",
    "STROBECK Kris": "strobeck-kris",
    "STROBER Dean": "strober-dean",
    "STROBER Rena": "strober-rena",
    "STROBERT Ralf Richardt": "strobert-ralf-richardt",
    "STROCK David": "strock-david",
    "STROEH Dan": "stroeh-dan",
    "STROGANOV Aleksandr": "stroganov-aleksandr",
    "STROILI Paul": "stroili-paul",
    "STROMAN Susan": "stroman-susan",
    "STROMBERG Bob": "stromberg-bob",
    "STROMBERGS Vinetta": "strombergs-vinetta",
    "STRONACH Alan": "stronach-alan",
    "STRONACH Carey E": "stronach-carey-e",
    "STRONG J J": "strong-j-j",
    "STRONG Mark": "strong-mark",
    "STRONG Romaner Jack": "strong-romaner-jack",
    "STROPPEL Frederick": "stroppel-frederick",
    "STROTHER Shirlee": "strother-shirlee",
    "STROTHMANN Paige": "strothmann-paige",
    "STROUD Darrin Frederick": "stroud-darrin-frederick",
    "STROUD Matthew D": "stroud-matthew-d",
    "STROUD Pierre Vladimir": "stroud-pierre-vladimir",
    "STROUSE Benjamin": "strouse-benjamin",
    "STROUSE Charles": "strouse-charles",
    "STROUT Ben": "strout-ben",
    "STROZIER M Stefan": "strozier-m-stefan",
    "STROZIER Robert": "strozier-robert",
    "STRUDWICK Lynda": "strudwick-lynda",
    "STRUDWICK Natasha": "strudwick-natasha",
    "STRUS Lusia": "strus-lusia",
    "STRUZIK Mary": "struzik-mary",
    "STRYK Lydia": "stryk-lydia",
    "STRYKER Jeff": "stryker-jeff",
    "STUART Aimee": "stuart-aimee",
    "STUART Alexx": "stuart-alexx",
    "STUART Cameron": "stuart-cameron",
    "STUART Carolyn": "stuart-carolyn",
    "STUART David": "stuart-david",
    "STUART Francis": "stuart-francis",
    "STUART Harold": "stuart-harold",
    "STUART Jason": "stuart-jason",
    "STUART Jeremy": "stuart-jeremy",
    "STUART John": "stuart-john",
    "STUART Kelly": "stuart-kelly",
    "STUART Meg": "stuart-meg",
    "STUART Phillip": "stuart-phillip",
    "STUART Rosie": "stuart-rosie",
    "STUART Roy": "stuart-roy",
    "STUART Sebastian": "stuart-sebastian",
    "STUART Steven": "stuart-steven",
    "STUART Tom": "stuart-tom",
    "STUART Tyler": "stuart-tyler",
    "STUART Vicki": "stuart-vicki",
    "STUART-FISHER Amanda": "stuart-fisher-amanda",
    "STUBBINGS Diane": "stubbings-diane",
    "STUBBINGS Mark": "stubbings-mark",
    "STUBBLEFIELD Jerry": "stubblefield-jerry",
    "STUBBS Imogen": "stubbs-imogen",
    "STUBBS John Heath": "stubbs-john-heath",
    "STUBBS Nathan": "stubbs-nathan",
    "STUBBS Norman": "stubbs-norman",
    "STUBBS Sally": "stubbs-sally",
    "STUCCIO Donna": "stuccio-donna",
    "STUCHFIELD Tom": "stuchfield-tom",
    "STUDDIFORD Bill": "studdiford-bill",
    "STUDER Maureen Mary": "studer-maureen-mary",
    "STUDIO HINDERIK ": "studio-hinderik",
    "STUDIO MATEJKA ": "studio-matejka",
    "STUDLAR Bernhard": "studlar-bernhard",
    "STUDNEY Dan": "studney-dan",
    "STUEBING Travis": "stuebing-travis",
    "STUELPNER Ilana": "stuelpner-ilana",
    "STULL Graham": "stull-graham",
    "STULMAN Valerie": "stulman-valerie",
    "STUMBAUGH Melissa": "stumbaugh-melissa",
    "STUMER Lynda": "stumer-lynda",
    "STUMPF Berit": "stumpf-berit",
    "STUNT THEATER COMPANY ": "stunt-theater-company",
    "STUREK Joseph": "sturek-joseph",
    "STURGES Preston": "sturges-preston",
    "STURIANO Meg": "sturiano-meg",
    "STURMAN Daniel": "sturman-daniel",
    "STURMINGER Michael": "sturminger-michael",
    "STURNER Lynda": "sturner-lynda",
    "STURNICK Shawn": "sturnick-shawn",
    "STURROCK Danny": "sturrock-danny",
    "STURROCK Donald": "sturrock-donald",
    "STURROCK Tristan": "sturrock-tristan",
    "STUSSER Michael A": "stusser-michael-a",
    "STUTT Harry": "stutt-harry",
    "STUTTARD David": "stuttard-david",
    "STUTTE John": "stutte-john",
    "STUX Erica": "stux-erica",
    "STYLES Geinor": "styles-geinor",
    "STYLES Hunter": "styles-hunter",
    "STYNE Jule": "styne-jule",
    "STYNE Norman": "styne-norman",
    "SUA Ave": "sua-ave",
    "SUANDI ": "suandi",
    "SUAREZ Giselle": "suarez-giselle",
    "SUAREZ-PICO Tatiana": "suarez-pico-tatiana",
    "SUBASIC Colleen": "subasic-colleen",
    "SUBJECTIVE THEATRE COMPANY ": "subjective-theatre-company",
    "SUBLETT Robbie": "sublett-robbie",
    "SUBLETT Scott": "sublett-scott",
    "SUBLETTE Walter": "sublette-walter",
    "SUBRIN Jennifer": "subrin-jennifer",
    "SUB-SUBLIME ": "subsublime",
    "SUBVERT Michael": "subvert-michael",
    "SUCKE Greer": "sucke-greer",
    "SUDA Robert B": "suda-robert-b",
    "SUDDS Justin": "sudds-justin",
    "SUDERMANN H": "sudermann-h",
    "SUDRAKA King": "sudraka-king",
    "SUDWORTH Chris": "sudworth-chris",
    "SUEHSDORF David": "suehsdorf-david",
    "SUEKO Seema": "sueko-seema",
    "SUEPAUL Steven": "suepaul-steven",
    "SUGAREK Trisha": "sugarek-trisha",
    "SUGARMAN Eddie": "sugarman-eddie",
    "SUGARMAN Robert": "sugarman-robert",
    "SUGARMAN Sara": "sugarman-sara",
    "SUGERMAN Emily": "sugerman-emily",
    "SUGG Jeff": "sugg-jeff",
    "SUGGS Nate": "suggs-nate",
    "SUH Lloyd": "suh-lloyd",
    "SUICIDE KINGS ": "suicide-kings",
    "SUILEBHAN Gwydion": "suilebhan-gwydion",
    "SUITCASE ENSEMBLE, THE ": "suitcase-ensemble-the",
    "SUITCASE ROYALE ": "suitcase-royale",
    "SUKHAVO-KOBYLIN Alexander": "sukhavo-kobylin-alexander",
    "SULAIMAN Huzir": "sulaiman-huzir",
    "SULAN Kate": "sulan-kate",
    "SULATYCKY Warren": "sulatycky-warren",
    "SULBY Suaanne": "sulby-suaanne",
    "SULKIN Aaron": "sulkin-aaron",
    "SULKIN Sidney": "sulkin-sidney",
    "SULLEY Marc": "sulley-marc",
    "SULLIVAN Anita": "sullivan-anita",
    "SULLIVAN Anna": "sullivan-anna",
    "SULLIVAN Carrie J": "sullivan-carrie-j",
    "SULLIVAN Christopher": "sullivan-christopher",
    "SULLIVAN Daniel": "sullivan-daniel",
    "SULLIVAN Dustin": "sullivan-dustin",
    "SULLIVAN Edward C": "sullivan-edward-c",
    "SULLIVAN Ellen Davis": "sullivan-ellen-davis",
    "SULLIVAN Hannah": "sullivan-hannah",
    "SULLIVAN J R": "sullivan-j-r",
    "SULLIVAN Jim": "sullivan-jim",
    "SULLIVAN John": "sullivan-john",
    "SULLIVAN Kate": "sullivan-kate",
    "SULLIVAN Kathleen": "sullivan-kathleen",
    "SULLIVAN Ladd": "sullivan-ladd",
    "SULLIVAN Liam": "sullivan-liam",
    "SULLIVAN Lindsay": "sullivan-lindsay",
    "SULLIVAN May Miller": "sullivan-may-miller",
    "SULLIVAN Michael": "sullivan-michael",
    "SULLIVAN Michael Gene": "sullivan-michael-gene",
    "SULLIVAN Natalie": "sullivan-natalie",
    "SULLIVAN Philip": "sullivan-philip",
    "SULLIVAN Phoebe": "sullivan-phoebe",
    "SULLIVAN Rachel": "sullivan-rachel",
    "SULLIVAN Robert Scott": "sullivan-robert-scott",
    "SULLIVAN Ryan": "sullivan-ryan",
    "SULLIVAN Seamus": "sullivan-seamus",
    "SULLIVAN Sean": "sullivan-sean",
    "SULLIVAN Shannon": "sullivan-shannon",
    "SULLIVAN Victoria": "sullivan-victoria",
    "SULLY Kathleen": "sully-kathleen",
    "SULONG THEATRE COLLECTIVE ": "sulong-theatre-collective",
    "SULSONA Michael V": "sulsona-michael-v",
    "SULTAN Arne": "sultan-arne",
    "SULTER Maud": "sulter-maud",
    "SUMANGIL Eric \"Pogi\"": "sumangil-eric",
    "SUMAT Manjot": "sumat-manjot",
    "SUMBWANYAMBE Mwewa": "sumbwanyambe-mwewa",
    "SUMELJ Johnny": "sumelj-johnny",
    "SUMLAK-LANGLOIS Gordan": "sumlak-langlois-gordan",
    "SUMMER Donna": "summer-donna",
    "SUMMERFIELD Caroline": "summerfield-caroline",
    "SUMMERS Alex": "summers-alex",
    "SUMMERS Allison": "summers-allison",
    "SUMMERS Chris": "summers-chris",
    "SUMMERS David": "summers-david",
    "SUMMERS Elliot": "summers-elliot",
    "SUMMERS Faye B": "summers-faye-b",
    "SUMMERS Kevin": "summers-kevin",
    "SUMMERS Laura": "summers-laura",
    "SUMMERS Lee": "summers-lee",
    "SUMMERS Peter": "summers-peter",
    "SUMMERS Sian": "summers-sian",
    "SUMMERSKILL Clare": "summerskill-clare",
    "SUMMERVILLE Jill": "summerville-jill",
    "SUMMONS John": "summons-john",
    "SUMMY Irene M": "summy-irene-m",
    "SUMNER Alaric": "sumner-alaric",
    "SUMNER Derry": "sumner-derry",
    "SUMNER Jennifer": "sumner-jennifer",
    "SUMNER Jill": "sumner-jill",
    "SUMNER Naomi": "sumner-naomi",
    "SUMNER Willie": "sumner-willie",
    "SUMNER-PRITCHARD Dana": "sumner-pritchard-dana",
    "SUN Nilaja": "sun-nilaja",
    "SUN William": "sun-william",
    "SUN DUCK Ko": "sun-duck-ko",
    "SUNDANCER Mark": "sundancer-mark",
    "SUNDBY Karl": "sundby-karl",
    "SUNDE Karen": "sunde-karen",
    "SUNDE Sarah Cameron": "sunde-sarah-cameron",
    "SUNDERLAND Adam": "sunderland-adam",
    "SUNDGAARD Arnold": "sundgaard-arnold",
    "SUNDSTROM Barbara": "sundstrom-barbara",
    "SUNDSTROM Frank": "sundstrom-frank",
    "SUNDSTROM Jacqueline": "sundstrom-jacqueline",
    "SUNDUKIANZ Gabriel": "sundukianz-gabriel",
    "SUNI Erika": "suni-erika",
    "SUNSHINE Gary": "sunshine-gary",
    "SUNSHINE Madeline": "sunshine-madeline",
    "SUPPLE Glen": "supple-glen",
    "SUPPLE Tim": "supple-tim",
    "SUPPON Charles": "suppon-charles",
    "SURACI Philip": "suraci-philip",
    "SURCHILL Julie": "surchill-julie",
    "SURETTE Roy": "surette-roy",
    "SURFACE Mary Hall": "surface-mary-hall",
    "SURGAL Jon": "surgal-jon",
    "SUROVELL Maggie": "surovell-maggie",
    "SURRATT Janus": "surratt-janus",
    "SURREY Janet": "surrey-janet",
    "SURRIDGE Andre": "surridge-andre",
    "SURRIDGE Julia": "surridge-julia",
    "SURRIDGE Paul Howard": "surridge-paul-howard",
    "SUSI Lolly": "susi-lolly",
    "SUSKIND Patrick": "suskind-patrick",
    "SUSMAN David ": "susman-david",
    "SUSMAN Julia": "susman-julia",
    "SUSPECT CULTURE ": "suspect-culture",
    "SUSSMAN Bruce": "sussman-bruce",
    "SUSSMAN J R": "sussman-j-r",
    "SUSSMAN Samuel": "sussman-samuel",
    "SUTCLIFFE Jane": "sutcliffe-jane",
    "SUTCLIFFE Jill": "sutcliffe-jill",
    "SUTCLIFFE Thomas": "sutcliffe-thomas",
    "SUTCLIFFE William": "sutcliffe-william",
    "SUTER Barbara": "suter-barbara",
    "SUTER Eva": "suter-eva",
    "SUTER Tim": "suter-tim",
    "SUTHERLAND Dan": "sutherland-dan",
    "SUTHERLAND Donald": "sutherland-donald",
    "SUTHERLAND Donald (1)": "sutherland-donald-1",
    "SUTHERLAND Efua": "sutherland-efua",
    "SUTHERLAND H W": "sutherland-h-w",
    "SUTHERLAND Iain": "sutherland-iain",
    "SUTHERLAND John": "sutherland-john",
    "SUTHERLAND Letitia": "sutherland-letitia",
    "SUTHERLAND Malcolm": "sutherland-malcolm",
    "SUTHERLAND Richard": "sutherland-richard",
    "SUTHERLAND Robert Garioch": "sutherland-robert-garioch",
    "SUTHERLAND Roeg": "sutherland-roeg",
    "SUTHERLAND Ross": "sutherland-ross",
    "SUTHERLAND Sam": "sutherland-sam",
    "SUTHERLAND Samantha": "sutherland-samantha",
    "SUTHERLAND Thom": "sutherland-thom",
    "SUTHERLIN Richard": "sutherlin-richard",
    "SUTHERS Trevor": "suthers-trevor",
    "SUTIN Marcia": "sutin-marcia",
    "SUTOW Brian": "sutow-brian",
    "SUTPHIN-KOCHER Rachel": "sutphin-kocher-rachel",
    "SUTRO John": "sutro-john",
    "SUTTIE Isy": "suttie-isy",
    "SUTTON Al": "sutton-al",
    "SUTTON Brian": "sutton-brian",
    "SUTTON Chelsea": "sutton-chelsea",
    "SUTTON Eric Graham": "sutton-eric-graham",
    "SUTTON Joe": "sutton-joe",
    "SUTTON Joseph": "sutton-joseph",
    "SUTTON Keddy": "sutton-keddy",
    "SUTTON Kyle": "sutton-kyle",
    "SUTTON Lee": "sutton-lee",
    "SUTTON Malcolm": "sutton-malcolm",
    "SUTTON Michael": "sutton-michael",
    "SUTTON Nick": "sutton-nick",
    "SUTTON Peter": "sutton-peter",
    "SUTTON Sally": "sutton-sally",
    "SUTTON Shaun": "sutton-shaun",
    "SUTTON Tim": "sutton-tim",
    "SUTTON-WILLIAMS Natasha": "sutton-williams-natasha",
    "SUTTOR Lloyd": "suttor-lloyd",
    "SUWA Yoshiko": "suwa-yoshiko",
    "SUZMAN Janet": "suzman-janet",
    "SUZUE Toshiro": "suzue-toshiro",
    "SUZUKI Linda": "suzuki-linda",
    "SVANOE Bill": "svanoe-bill",
    "SVARC Lorne": "svarc-lorne",
    "SVARLIEN Diane Arnson": "svarlien-diane-arnson",
    "SVARTZ Evegeny": "svartz-evegeny",
    "SVEC J C": "svec-j-c",
    "SVEC Stephanie": "svec-stephanie",
    "SVEJCAR Eric": "svejcar-eric",
    "SVENDSEN Zoe": "svendsen-zoe",
    "SVENSSON Lucas": "svensson-lucas",
    "SVICH Caridad": "svich-caridad",
    "SVOBODA Andrew": "svoboda-andrew",
    "SVOBODA B M": "svoboda-b-m",
    "SVOBODA Heidi": "svoboda-heidi",
    "SVOBODA Stephen J": "svoboda-stephen-j",
    "SVOBODOVA Jana": "svobodova-jana",
    "SWACKER Frank Warren": "swacker-frank-warren",
    "SWADOS Elizabeth": "swados-elizabeth",
    "SWADOS Robin": "swados-robin",
    "SWAFFER Ben": "swaffer-ben",
    "SWAIN Bara": "swain-bara",
    "SWAIN Des": "swain-des",
    "SWAIN Elizabeth": "swain-elizabeth",
    "SWAIN Jennie": "swain-jennie",
    "SWAIN Justin": "swain-justin",
    "SWAIN Kirstie": "swain-kirstie",
    "SWAIN Marianka": "swain-marianka",
    "SWAIN Nigel": "swain-nigel",
    "SWALE Jessica": "swale-jessica",
    "SWALLOW Margaret": "swallow-margaret",
    "SWAN Annie S": "swan-annie-s",
    "SWAN Jon": "swan-jon",
    "SWAN Mary": "swan-mary",
    "SWANBORN Nancy": "swanborn-nancy",
    "SWANDER Mary": "swander-mary",
    "SWANER Mark": "swaner-mark",
    "SWANN Darius Leander": "swann-darius-leander",
    "SWANN Donald": "swann-donald",
    "SWANN Francis": "swann-francis",
    "SWANN Phil": "swann-phil",
    "SWANNELL Graham": "swannell-graham",
    "SWANNER Tom": "swanner-tom",
    "SWANSON C Denby": "swanson-c-denby",
    "SWANSON Chris Shaw": "swanson-chris-shaw",
    "SWANSON Curtis B": "swanson-curtis-b",
    "SWANSON Karen": "swanson-karen",
    "SWANSON Lorraine": "swanson-lorraine",
    "SWANSON Nina": "swanson-nina",
    "SWANSON Terry": "swanson-terry",
    "SWANSTROM Arthur": "swanstrom-arthur",
    "SWANTON James": "swanton-james",
    "SWARBRICK Lisa": "swarbrick-lisa",
    "SWARBRICK Stuart": "swarbrick-stuart",
    "SWART Jan": "swart-jan",
    "SWART Stephanie": "swart-stephanie",
    "SWARTZ Adam": "swartz-adam",
    "SWARTZ Burton Eugene": "swartz-burton-eugene",
    "SWARTZ Gary": "swartz-gary",
    "SWARTZ L Don": "swartz-l-don",
    "SWARTZ Larry": "swartz-larry",
    "SWARTZ Ted": "swartz-ted",
    "SWASH Colin": "swash-colin",
    "SWAYE Matthew": "swaye-matthew",
    "SWAYNE Herbert E": "swayne-herbert-e",
    "SWEARINGEN Joel": "swearingen-joel",
    "SWEARS Herbert": "swears-herbert",
    "SWEDEEN Staci": "swedeen-staci",
    "SWEEDMAN Krystal": "sweedman-krystal",
    "SWEEN Joan": "sween-joan",
    "SWEEN Scotti": "sween-scotti",
    "SWEENEY Adam": "sweeney-adam",
    "SWEENEY Christopher": "sweeney-christopher",
    "SWEENEY Claire": "sweeney-claire",
    "SWEENEY Dave": "sweeney-dave",
    "SWEENEY Eamonn": "sweeney-eamonn",
    "SWEENEY Emma Jane": "sweeney-emma-jane",
    "SWEENEY Jason": "sweeney-jason",
    "SWEENEY Jillian": "sweeney-jillian",
    "SWEENEY Jim": "sweeney-jim",
    "SWEENEY Julia": "sweeney-julia",
    "SWEENEY Mark": "sweeney-mark",
    "SWEENEY Martin": "sweeney-martin",
    "SWEENEY Niall": "sweeney-niall",
    "SWEENEY R L": "sweeney-r-l",
    "SWEENEY Roger L": "sweeney-roger-l",
    "SWEENEY S Daly": "sweeney-s-daly",
    "SWEENY Kate": "sweeny-kate",
    "SWEET Jeffrey": "sweet-jeffrey",
    "SWEET John": "sweet-john",
    "SWEET Karla": "sweet-karla",
    "SWEET Matthew": "sweet-matthew",
    "SWEET Nick": "sweet-nick",
    "SWEET Robert": "sweet-robert",
    "SWEETEN Ray": "sweeten-ray",
    "SWEETLOVE Betty": "sweetlove-betty",
    "SWEETMAN Rob": "sweetman-rob",
    "SWEITZER Letitia": "sweitzer-letitia",
    "SWEITZER Rod": "sweitzer-rod",
    "SWENSON Cole": "swenson-cole",
    "SWENSON L E": "swenson-l-e",
    "SWENSON Sven": "swenson-sven",
    "SWENSSON Evelyn": "swensson-evelyn",
    "SWERDLIN Morris": "swerdlin-morris",
    "SWERDLOW Robert": "swerdlow-robert",
    "SWEREN-BECKER Daniel": "sweren-becker-daniel",
    "SWERLING Jo": "swerling-jo",
    "SWET Peter": "swet-peter",
    "SWICORD Robin": "swicord-robin",
    "SWIFT Allan": "swift-allan",
    "SWIFT Allen": "swift-allen",
    "SWIFT Amanda": "swift-amanda",
    "SWIFT Carolyn": "swift-carolyn",
    "SWIFT Donna": "swift-donna",
    "SWIFT Glenn": "swift-glenn",
    "SWIFT Jeremy": "swift-jeremy",
    "SWIFT John": "swift-john",
    "SWIFT Kay": "swift-kay",
    "SWIFT Lee": "swift-lee",
    "SWIFT Michael": "swift-michael",
    "SWIFT Paul": "swift-paul",
    "SWIFT Steve": "swift-steve",
    "SWIFT Tom": "swift-tom",
    "SWIFT Tom (1)": "swift-tom-1",
    "SWIFT Tom (2)": "swift-tom-2",
    "SWIMM Tom": "swimm-tom",
    "SWIMMER ONE ": "swimmer-one",
    "SWINARSKI Arthur Marya": "swinarski-arthur-marya",
    "SWINBOURNE Charlie": "swinbourne-charlie",
    "SWINBOURNE Leigh": "swinbourne-leigh",
    "SWINBURNE Sonia": "swinburne-sonia",
    "SWINDLEY Ted": "swindley-ted",
    "SWINGLE Rich": "swingle-rich",
    "SWINGLER Peter": "swingler-peter",
    "SWINTON Rob": "swinton-rob",
    "SWIRSKY Stephanie": "swirsky-stephanie",
    "SWISHER Deborah": "swisher-deborah",
    "SWITZER Michael": "switzer-michael",
    "SWIVEL Mark": "swivel-mark",
    "SWNEY Chris": "swney-chris",
    "SWOBODA Gunter": "swoboda-gunter",
    "SWORD Leslie Lewis": "sword-leslie-lewis",
    "SWORTZELL Lowell": "swortzell-lowell",
    "SWYCHER Stephen": "swycher-stephen",
    "SY Jovanni": "sy-jovanni",
    "SYAL Meera": "syal-meera",
    "SYBORN Freddy": "syborn-freddy",
    "SYDNEY Ros": "sydney-ros",
    "SYDNEY FRONT, THE ": "sydney-front",
    "SYDORICK Tom": "sydorick-tom",
    "SYDOW Jack": "sydow-jack",
    "SYDOW Karl": "sydow-karl",
    "SYERS Andrew": "syers-andrew",
    "SYERS Karinne Keithley": "syers-karinne-keithley",
    "SYEVENS Dudley": "syevens-dudley",
    "SYKES C P": "sykes-c-p",
    "SYKES Chris": "sykes-chris",
    "SYKES Geoffrey": "sykes-geoffrey",
    "SYKES Katie": "sykes-katie",
    "SYKES Nick": "sykes-nick",
    "SYKES Pamela": "sykes-pamela",
    "SYLLA Kadiatou": "sylla-kadiatou",
    "SYLVAN Melanie": "sylvan-melanie",
    "SYLVANUS Erwin": "sylvanus-erwin",
    "SYLVESTRE Cleo": "sylvestre-cleo",
    "SYLVIA Kenneth": "sylvia-kenneth",
    "SYLVIA-CLARNO Brianna": "sylvia-clarno-brianna",
    "SYLVIS D J": "sylvis-d-j",
    "SYMES Benjamin": "symes-benjamin",
    "SYMES Phil": "symes-phil",
    "SYMINGTON Amy": "symington-amy",
    "SYMON Joe": "symon-joe",
    "SYMONDS Alexandria": "symonds-alexandria",
    "SYMONDS Bryn": "symonds-bryn",
    "SYMONDS Joel": "symonds-joel",
    "SYMONDS John": "symonds-john",
    "SYMONETTE-DIXON Kamal": "symonette-dixon-kamal",
    "SYMONLOE Paul": "symonloe-paul",
    "SYMONS Alan": "symons-alan",
    "SYMONS Arthur": "symons-arthur",
    "SYMONS Georgia": "symons-georgia",
    "SYMONS Natalie": "symons-natalie",
    "SYMS Aline": "syms-aline",
    "SYNAESTHETIC THEATRE ": "synaesthetic-theatre",
    "SYNDICATE, THE ": "syndicate",
    "SYNGE John": "synge-john",
    "SY-QUIA Hilary Collier": "sy-quia-hilary-collier",
    "SYRACUSE Paul": "syracuse-paul",
    "SYRIAN PLAYWRIGHT ": "syrian-playwright",
    "SYRON Lisa-Marie": "syron-lisa-marie",
    "SYS Matthieu": "sys-matthieu",
    "SYSWERDA Todd": "syswerda-todd",
    "SZAMEITAL Manfred": "szameital-manfred",
    "SZANTO George": "szanto-george",
    "SZATHMARI Jacquetta": "szathmari-jacquetta",
    "SZATHMARY Elizabeth": "szathmary-elizabeth",
    "SZEJNER Karolyn": "szejner-karolyn",
    "SZENTGYORGYI Tom": "szentgyorgyi-tom",
    "SZEPS Henri": "szeps-henri",
    "SZILAGY Andor": "szilagy-andor",
    "SZOGYI Alex": "szogyi-alex",
    "SZOMBATHY Michael": "szombathy-michael",
    "SZROEDER Bozena": "szroeder-bozena",
    "SZUMIGALSKI Anne": "szumigalski-anne",
    "SZYMKOWICZ Adam": "szymkowicz-adam",
    "SZYSZKOWITZ Gerald": "szyszkowitz-gerald"
  }
};