export default {
  "metadata": {
    "results": 552,
    "timeStamp": "2025-12-05T21:31:37.224Z",
    "url": "https://www.doollee.com/PlaywrightsT/T_playwrights_a-f.php"
  },
  "authors": {
    "TA Bihn Duy": "ta-bihn-duy",
    "TA TA DI DI TEATRO ": "ta-ta-di-di-teatro",
    "TABATABAI-KHATAMBAKHSH Nazli": "tabatabai-khatambakhsh-nazli",
    "TABATCHNICK Ian": "tabatchnick-ian",
    "TABELLIONE Keith": "tabellione-keith",
    "TABER Miles": "taber-miles",
    "TABER Richard": "taber-richard",
    "TABERN Peter": "tabern-peter",
    "TABERNER Stephen": "taberner-stephen",
    "TABIT Ramez": "tabit-ramez",
    "TABLO ": "tablo",
    "TABNICK Jeff": "tabnick-jeff",
    "TABORI George": "tabori-george",
    "TABORSKI Boleslaw": "taborski-boleslaw",
    "TACKETT Caren": "tackett-caren",
    "TACON Frederic": "tacon-frederic",
    "TACUHER Rozanne": "tacuher-rozanne",
    "TADMAN Betty": "tadman-betty",
    "TADROS Evelyn": "tadros-evelyn",
    "TAEGEL Mary Jane": "taegel-mary-jane",
    "T'AE-SOK Oh": "tae-sok-oh",
    "TAFEEN D": "tafeen-d",
    "TAFFETY PUNK THEATRE COMPANY ": "taffety-punk-theatre-company",
    "TAFT Thomas Woodall": "taft-thomas-woodall",
    "TAG TEATRO ": "tag-teatro",
    "TAG THEATRE ": "tag-theatre",
    "TAGG Kathleen": "tagg-kathleen",
    "TAGG Nick": "tagg-nick",
    "TAGGART Andrew": "taggart-andrew",
    "TAGGART Brian": "taggart-brian",
    "TAGGART Bronagh": "taggart-bronagh",
    "TAGGART Tom": "taggart-tom",
    "TAGHAVI Bita": "taghavi-bita",
    "TAGOE Ben": "tagoe-ben",
    "TAGORE Rabindranath": "tagore-rabindranath",
    "TAHA Dalia": "taha-dalia",
    "TAHN Andras": "tahn-andras",
    "TAIKEFF Stanley": "taikeff-stanley",
    "TAILO Edessa": "tailo-edessa",
    "TAINSH Jean": "tainsh-jean",
    "TAIRA Jennifer": "taira-jennifer",
    "TAIT James Fagan": "tait-james-fagan",
    "TAIT Lance": "tait-lance",
    "TAIT Melanie": "tait-melanie",
    "TAIT Paul": "tait-paul",
    "TAIT Peta": "tait-peta",
    "TAIT R Colin": "tait-r-colin",
    "TAITT Brandon": "taitt-brandon",
    "TAKACS Jeff": "takacs-jeff",
    "TAKAHASHI Suzi": "takahashi-suzi",
    "TAKAHASHI Yasunari": "takahashi-yasunari",
    "TAKAYA Ted T": "takaya-ted-t",
    "TAKEDA Suz": "takeda-suz",
    "TAKEI Kei": "takei-kei",
    "TAKENAKA Ro": "takenaka-ro",
    "TAKESHITA Vernon": "takeshita-vernon",
    "TAKLE Darrien": "takle-darrien",
    "TAL Adina": "tal-adina",
    "TALARICO Joseph": "talarico-joseph",
    "TALAVERA Richard": "talavera-richard",
    "TALAWA ": "talawa",
    "TALBERTH Kenneth": "talberth-kenneth",
    "TALBOT A J": "talbot-a-j",
    "TALBOT Charlie": "talbot-charlie",
    "TALBOT Pete": "talbot-pete",
    "TALBOT Richard": "talbot-richard",
    "TALBOT Scott": "talbot-scott",
    "TALBOT Sharon": "talbot-sharon",
    "TALBOT Sharon Taylor": "talbot-sharon-taylor",
    "TALBOT Story": "talbot-story",
    "TALBOTT Chris": "talbott-chris",
    "TALBOTT Daniel": "talbott-daniel",
    "TALBOTT Jeff": "talbott-jeff",
    "TALBUTT Lotty": "talbutt-lotty",
    "TALENT King": "talent-king",
    "TALENTI Francesca": "talenti-francesca",
    "TALEON-SONZA Jorshinelle": "taleon-sonza-jorshinelle",
    "TALGAROW Michelle": "talgarow-michelle",
    "TALIBAM! ": "talibam",
    "TALIJANCIC Ivan": "talijancic-ivan",
    "TALK Dorothy": "talk-dorothy",
    "TALKING BAND, THE ": "talking-band",
    "TALKING BIRDS THEATRE COMPANY ": "talking-birds-theatre-company",
    "TALKING PICTURES ": "talking-pictures",
    "TALKING TONGUES ": "talking-tongues",
    "TALKINGTON Marilee": "talkington-marilee",
    "TALL POPPEAS ": "tall-poppeas",
    "TALL STORIES ": "tall-stories",
    "TALLEN Ben": "tallen-ben",
    "TALLEY David": "talley-david",
    "TALLEY Frank": "talley-frank",
    "TALLEY Kevin": "talley-kevin",
    "TALLIS Frank": "tallis-frank",
    "TALLMAN Jim": "tallman-jim",
    "TALLMAN Randolph": "tallman-randolph",
    "TALLY Ted": "tally-ted",
    "TALLYRAND J B": "tallyrand-j-b",
    "TALMADGE Victor": "talmadge-victor",
    "TALMAN Eilidh": "talman-eilidh",
    "TALMAN Martha Ann": "talman-martha-ann",
    "TALMAN Pete": "talman-pete",
    "TALVE Arava": "talve-arava",
    "TALWAR Rajesh": "talwar-rajesh",
    "TAM TAM THEATRE ": "tam-tam-theatre",
    "TAMAKI Marika": "tamaki-marika",
    "TAMARIBUCHI Peter": "tamaribuchi-peter",
    "TAMASHA ": "tamasha",
    "TAMAYO Manny": "tamayo-manny",
    "TAMAYO Vanessa": "tamayo-vanessa",
    "TAMBLYN Ian": "tamblyn-ian",
    "TAMBORELLO Joe": "tamborello-joe",
    "TAMBORNINO Jeff": "tambornino-jeff",
    "TAMBORRA Lia": "tamborra-lia",
    "TAMBURINO Robert": "tamburino-robert",
    "TAMEZ Frank": "tamez-frank",
    "TAMLER Cory": "tamler-cory",
    "TAMMANY Susan": "tammany-susan",
    "TAMMI Tom": "tammi-tom",
    "TAMPIERI Susana": "tampieri-susana",
    "TAMS Emmett": "tams-emmett",
    "TAN Dora": "tan-dora",
    "TAN Joel": "tan-joel",
    "TAN Joel (1)": "tan-joel-1",
    "TAN Kelvin": "tan-kelvin",
    "TANAHASHI Hiroko": "tanahashi-hiroko",
    "TANAKA Chikao": "tanaka-chikao",
    "TANAKA Nin": "tanaka-nin",
    "TANAKA Yumiko": "tanaka-yumiko",
    "TANCHAREON Maurissa": "tanchareon-maurissa",
    "TANCOCK L W": "tancock-l-w",
    "TANCREDI Dominic R": "tancredi-dominic-r",
    "TANDAVANIT J Nick": "tandavanit-j-nick",
    "TANDOC-PICHEREAU Michelle": "tandoc-pichereau-michelle",
    "TANDY Stephanie": "tandy-stephanie",
    "TANENBAUM Isaiah": "tanenbaum-isaiah",
    "TANENBAUM Steven": "tanenbaum-steven",
    "TANER Haldun": "taner-haldun",
    "TANEY Retta": "taney-retta",
    "TANG Ken": "tang-ken",
    "TANG Lisa": "tang-lisa",
    "TANG Roger": "tang-roger",
    "TANGERDING Axel": "tangerding-axel",
    "TANGLAO-AQUAS Francis": "tanglao-aquas-francis",
    "TANGLED FEET ": "tangled-feet",
    "TANGREDI Frank": "tangredi-frank",
    "TANIS T C": "tanis-t-c",
    "TANITCH Robert": "tanitch-robert",
    "TANITH Mij": "tanith-mij",
    "TANKARD Meryl": "tankard-meryl",
    "TANKUS Edith": "tankus-edith",
    "TANKUS Nelle": "tankus-nelle",
    "TANNA Kiran": "tanna-kiran",
    "TANNAHILL Edward": "tannahill-edward",
    "TANNAHILL Jordan": "tannahill-jordan",
    "TANNEN Deborah": "tannen-deborah",
    "TANNEN Lee": "tannen-lee",
    "TANNENBAUM Jay": "tannenbaum-jay",
    "TANNER Chris": "tanner-chris",
    "TANNER Jim": "tanner-jim",
    "TANNER Justin": "tanner-justin",
    "TANNER Lian": "tanner-lian",
    "TANNER Rebecca": "tanner-rebecca",
    "TANNER Richard": "tanner-richard",
    "TANNER Tony": "tanner-tony",
    "TANNER Vickie": "tanner-vickie",
    "TANOVIC Tajna": "tanovic-tajna",
    "TANSEY June": "tansey-june",
    "TANTALO Joe": "tantalo-joe",
    "TANTALUS ": "tantalus",
    "TANTINA Pera": "tantina-pera",
    "TANVIR Ad Habib": "tanvir-ad-habib",
    "TANZABEL Nicole": "tanzabel-nicole",
    "TAPIA Jose": "tapia-jose",
    "TAPPAN Don": "tappan-don",
    "TAPPENDEN Jean": "tappenden-jean",
    "TAPPER Albert M": "tapper-albert-m",
    "TARA ": "tara",
    "TARANTO Paul": "taranto-paul",
    "TARATULA Philip": "taratula-philip",
    "TARAZEVITS Scott": "tarazevits-scott",
    "TARBELL Shirley": "tarbell-shirley",
    "TARBESCU Edith": "tarbescu-edith",
    "TARBOX Constance": "tarbox-constance",
    "TARDI Mark": "tardi-mark",
    "TARDIEU Jean": "tardieu-jean",
    "TARETT Carly": "tarett-carly",
    "TARGET MARGIN THEATER ": "target-margin-theater",
    "TARGUSE Vera": "targuse-vera",
    "TARJAN Karen": "tarjan-karen",
    "TARKAN Joshua": "tarkan-joshua",
    "TARKENTER Dave": "tarkenter-dave",
    "TARKER Kate": "tarker-kate",
    "TARKINGTON Booth": "tarkington-booth",
    "TARLIN Jona": "tarlin-jona",
    "TARLO Luna": "tarlo-luna",
    "TARLOFF Frank": "tarloff-frank",
    "TARLTON Jack": "tarlton-jack",
    "TARNAWSKY Nadia": "tarnawsky-nadia",
    "TARNOWSKI Stefan": "tarnowski-stefan",
    "TARRAB nat": "tarrab-nat",
    "TARRETT Carly": "tarrett-carly",
    "TARSKA Eugenia": "tarska-eugenia",
    "TARTAGLIA John": "tartaglia-john",
    "TARVER Ben": "tarver-ben",
    "TARZIOURA Miora": "tarzioura-miora",
    "TASANE Steve": "tasane-steve",
    "TASCA Ed": "tasca-ed",
    "TASCA Jules": "tasca-jules",
    "TASDANCE ": "tasdance",
    "TASHEVA Julia": "tasheva-julia",
    "TASHIRO Kikue": "tashiro-kikue",
    "TASHJIAN Gordon": "tashjian-gordon",
    "TASSI Aldo": "tassi-aldo",
    "TASSO Torquato": "tasso-torquato",
    "TATE Greg": "tate-greg",
    "TATE Joan": "tate-joan",
    "TATE Judy": "tate-judy",
    "TATE Vicky": "tate-vicky",
    "TATE-MANNING Anya": "tate-manning-anya",
    "TATHAM Lew": "tatham-lew",
    "TATLOCK Alison": "tatlock-alison",
    "TATTE Jaan": "tatte-jaan",
    "TATTENBAUM-FINE Emma": "tattenbaum-fine-emma",
    "TATUM James": "tatum-james",
    "TATUM Trey": "tatum-trey",
    "TAUB Michael": "taub-michael",
    "TAUB Shaina": "taub-shaina",
    "TAUB Yermiyahu Ahron": "taub-yermiyahu-ahron",
    "TAUBER Chaim": "tauber-chaim",
    "TAUBMAN Adina": "taubman-adina",
    "TAUDEVIN A J": "taudevin-a-j",
    "TAUFER Vito": "taufer-vito",
    "TAUREL Douglas": "taurel-douglas",
    "TAURISANO Marc": "taurisano-marc",
    "TAUSER Diane": "tauser-diane",
    "TAVANA Daria": "tavana-daria",
    "TAVEL Ronald": "tavel-ronald",
    "TAVENER John": "tavener-john",
    "TAVIANI Paolo": "taviani-paolo",
    "TAVIANI Vittorio": "taviani-vittorio",
    "TAW Harold": "taw-harold",
    "TAWIL Randa": "tawil-randa",
    "TAXI ": "taxi",
    "TAY Jean": "tay-jean",
    "TAYLOR A R": "taylor-a-r",
    "TAYLOR Abigail": "taylor-abigail",
    "TAYLOR Adam": "taylor-adam",
    "TAYLOR Alan C": "taylor-alan-c",
    "TAYLOR Alec": "taylor-alec",
    "TAYLOR Ali": "taylor-ali",
    "TAYLOR Andrew": "taylor-andrew",
    "TAYLOR Andrew Nicholas Compton": "taylor-andrew-nicholas-compton",
    "TAYLOR Ann": "taylor-ann",
    "TAYLOR Ann E": "taylor-ann-e",
    "TAYLOR Anni Lee": "taylor-anni-lee",
    "TAYLOR Anthony": "taylor-anthony",
    "TAYLOR B": "taylor-b",
    "TAYLOR Bernard J": "taylor-bernard-j",
    "TAYLOR Bill": "taylor-bill",
    "TAYLOR Bing": "taylor-bing",
    "TAYLOR C": "taylor-c",
    "TAYLOR Caroline Neisha": "taylor-caroline-neisha",
    "TAYLOR Cecil": "taylor-cecil",
    "TAYLOR Cecil P": "taylor-cecil-p",
    "TAYLOR Charles": "taylor-charles",
    "TAYLOR Charles A": "taylor-charles-a",
    "TAYLOR Chris": "taylor-chris",
    "TAYLOR Christopher": "taylor-christopher",
    "TAYLOR Clark": "taylor-clark",
    "TAYLOR Craig": "taylor-craig",
    "TAYLOR Dan": "taylor-dan",
    "TAYLOR Daniel": "taylor-daniel",
    "TAYLOR Daniel Lawrence": "taylor-daniel-lawrence",
    "TAYLOR Daren": "taylor-daren",
    "TAYLOR David": "taylor-david",
    "TAYLOR David Gobeil": "taylor-david-gobeil",
    "TAYLOR Dean": "taylor-dean",
    "TAYLOR Deanne": "taylor-deanne",
    "TAYLOR Deborah Porter": "taylor-deborah-porter",
    "TAYLOR Diane": "taylor-diane",
    "TAYLOR Dominic": "taylor-dominic",
    "TAYLOR Dominic J": "taylor-dominic-j",
    "TAYLOR Don": "taylor-don",
    "TAYLOR Douglas": "taylor-douglas",
    "TAYLOR Drew": "taylor-drew",
    "TAYLOR Drew Hayden": "taylor-drew-hayden",
    "TAYLOR Dwight": "taylor-dwight",
    "TAYLOR Ed": "taylor-ed",
    "TAYLOR Edward": "taylor-edward",
    "TAYLOR Elizabeth": "taylor-elizabeth",
    "TAYLOR Emily": "taylor-emily",
    "TAYLOR Emory": "taylor-emory",
    "TAYLOR George": "taylor-george",
    "TAYLOR George (1)": "taylor-george-1",
    "TAYLOR Gregg": "taylor-gregg",
    "TAYLOR Heather": "taylor-heather",
    "TAYLOR Helen": "taylor-helen",
    "TAYLOR Henry": "taylor-henry",
    "TAYLOR Hiram": "taylor-hiram",
    "TAYLOR Holland": "taylor-holland",
    "TAYLOR Ian": "taylor-ian",
    "TAYLOR Irma": "taylor-irma",
    "TAYLOR Jack": "taylor-jack",
    "TAYLOR Jackie": "taylor-jackie",
    "TAYLOR James": "taylor-james",
    "TAYLOR Jan": "taylor-jan",
    "TAYLOR Jane": "taylor-jane",
    "TAYLOR Jeanne": "taylor-jeanne",
    "TAYLOR Jeremy": "taylor-jeremy",
    "TAYLOR Jeremy (1)": "taylor-jeremy-1",
    "TAYLOR Jeremy James": "taylor-jeremy-james",
    "TAYLOR Joe": "taylor-joe",
    "TAYLOR Joelle": "taylor-joelle",
    "TAYLOR John": "taylor-john",
    "TAYLOR Jonathan": "taylor-jonathan",
    "TAYLOR Jonathan Lee": "taylor-jonathan-lee",
    "TAYLOR June": "taylor-june",
    "TAYLOR Justin": "taylor-justin",
    "TAYLOR Karen D": "taylor-karen-d",
    "TAYLOR Kelly": "taylor-kelly",
    "TAYLOR Ken": "taylor-ken",
    "TAYLOR Kenneth Alan": "taylor-kenneth-alan",
    "TAYLOR Kressmann": "taylor-kressmann",
    "TAYLOR Larry": "taylor-larry",
    "TAYLOR Leo": "taylor-leo",
    "TAYLOR Liz Fitzgerald": "taylor-liz-fitzgerald",
    "TAYLOR Louise": "taylor-louise",
    "TAYLOR Malcolm (1)": "taylor-malcolm-1",
    "TAYLOR Malcolm (2)": "taylor-malcolm-2",
    "TAYLOR Margaret F": "taylor-margaret-f",
    "TAYLOR Margie": "taylor-margie",
    "TAYLOR Markland": "taylor-markland",
    "TAYLOR Marsali": "taylor-marsali",
    "TAYLOR Martin J": "taylor-martin-j",
    "TAYLOR Matt": "taylor-matt",
    "TAYLOR Matthew": "taylor-matthew",
    "TAYLOR Mavis": "taylor-mavis",
    "TAYLOR Michael": "taylor-michael",
    "TAYLOR Mike": "taylor-mike",
    "TAYLOR Molly": "taylor-molly",
    "TAYLOR Morgan": "taylor-morgan",
    "TAYLOR Pam": "taylor-pam",
    "TAYLOR Patricia": "taylor-patricia",
    "TAYLOR Perry": "taylor-perry",
    "TAYLOR Peter": "taylor-peter",
    "TAYLOR Phoebe": "taylor-phoebe",
    "TAYLOR Ray": "taylor-ray",
    "TAYLOR Regina": "taylor-regina",
    "TAYLOR Renee": "taylor-renee",
    "TAYLOR Rey": "taylor-rey",
    "TAYLOR Richard": "taylor-richard",
    "TAYLOR Richard (1)": "taylor-richard-1",
    "TAYLOR Rob": "taylor-rob",
    "TAYLOR Robert": "taylor-robert",
    "TAYLOR Robert Leland": "taylor-robert-leland",
    "TAYLOR Rod": "taylor-rod",
    "TAYLOR Rodney \"Rhoda\"": "taylor-rodney-rhoda",
    "TAYLOR Ron": "taylor-ron",
    "TAYLOR Roslyn": "taylor-roslyn",
    "TAYLOR Russell": "taylor-russell",
    "TAYLOR Samuel": "taylor-samuel",
    "TAYLOR Sandy": "taylor-sandy",
    "TAYLOR Sara": "taylor-sara",
    "TAYLOR Scott": "taylor-scott",
    "TAYLOR Scott Marshall": "taylor-scott-marshall",
    "TAYLOR Simon Watson": "taylor-simon-watson",
    "TAYLOR Stayci": "taylor-stayci",
    "TAYLOR Step": "taylor-step",
    "TAYLOR Steve": "taylor-steve",
    "TAYLOR Theo": "taylor-theo",
    "TAYLOR Tom": "taylor-tom",
    "TAYLOR Tom (1)": "taylor-tom-1",
    "TAYLOR Tommy": "taylor-tommy",
    "TAYLOR Tony": "taylor-tony",
    "TAYLOR Venetia": "taylor-venetia",
    "TAYLOR W Allen": "taylor-w-allen",
    "TAYLOR Yana": "taylor-yana",
    "TAYLOR-BROWN Daniel": "taylor-brown-daniel",
    "TAYLOR-CORBETT Lynne": "taylor-corbett-lynne",
    "TAYLOR-ROWAN Joan": "taylor-rowan-joan",
    "TAYLOR-SMITH Kelly": "taylor-smith-kelly",
    "TAYMOR Danya": "taymor-danya",
    "TAYMOR Julie": "taymor-julie",
    "TAYPE ": "taype",
    "TAZEWELL Marlin T": "tazewell-marlin-t",
    "TCHEKHOV Anton": "tchekhov-anton",
    "TCHIAKPE Jennifer": "tchiakpe-jennifer",
    "TCHOREK M": "tchorek-m",
    "TE'A COMPANY, THE ": "te-a-company",
    "TEACEY A H": "teacey-a-h",
    "TEACHOUT Terry": "teachout-terry",
    "TEAGLE Rachel": "teagle-rachel",
    "TEAGUE Anthony": "teague-anthony",
    "TEAGUE Bob": "teague-bob",
    "TEAGUE Tony": "teague-tony",
    "TEAGUE JR Robert": "teague-robert",
    "TEAHAN Mimi": "teahan-mimi",
    "TEALE Leonard": "teale-leonard",
    "TEALE Polly": "teale-polly",
    "TEAM HAPPOU B-ZIN ": "team-happou-b-zin",
    "TEAM THUNDERBIRD ": "team-thunderbird",
    "TEAM, THE ": "team",
    "TEARE Jeff": "teare-jeff",
    "TEARLE David": "tearle-david",
    "TEATR LICEDEI ": "teatr-licedei",
    "TEATRAL YEN ": "teatral-yen",
    "TEATRE NIXTAYOLERO ": "teatre-nixtayolero",
    "TEATRET MOLLEN ": "teatret-mollen",
    "TEATRO Tag": "teatro-tag",
    "TEATRO DE ARTE POPULAR ": "teatro-de-arte-popular",
    "TEATRO DEL CARRETTO ": "teatro-del-carretto",
    "TEATRO DI PIAZZA O D'OCCASIONE ": "teatro-di-piazza-o-d-occasione",
    "TEATRO ENTRE ESCOMBROS ": "teatro-entre-escombros",
    "TEATRO KISMET ": "teatro-kismet",
    "TEATRO LINEA DE SOMBRA ": "teatro-linea-de-sombra",
    "TEATRON COMPANY ": "teatron-company",
    "TEBBUTT Gerry": "tebbutt-gerry",
    "TEBELAK John Michael": "tebelak-john-michael",
    "TEC Roland": "tec-roland",
    "TECER Armet Kutsi": "tecer-armet-kutsi",
    "TECKLENGBURG Nina": "tecklengburg-nina",
    "TEDDER Abi": "tedder-abi",
    "TEDESCHI John": "tedeschi-john",
    "TEDFORD Matthew": "tedford-matthew",
    "TEED Nick": "teed-nick",
    "TEEHAN John Wallace": "teehan-john-wallace",
    "TEEHAN Mimi": "teehan-mimi",
    "TEELE Mike": "teele-mike",
    "TEEMLEY Mitch": "teemley-mitch",
    "TEER Barbara Ann": "teer-barbara-ann",
    "TEETER J R": "teeter-j-r",
    "TEEVAN Colin": "teevan-colin",
    "TEGEL Peter": "tegel-peter",
    "TEGLAS Csaba": "teglas-csaba",
    "TEH Benjamin": "teh-benjamin",
    "TEH-HUI Cheng": "teh-hui-cheng",
    "TEI Chew Siah": "tei-chew-siah",
    "TEICHMANN Howard": "teichmann-howard",
    "TEIGEN Lene Therese": "teigen-lene-therese",
    "TEIRLER Lucy": "teirler-lucy",
    "TEIRSTEIN Andy": "teirstein-andy",
    "TEITEL Jay": "teitel-jay",
    "TEITEL N R": "teitel-n-r",
    "TEITELBAUM Maurice": "teitelbaum-maurice",
    "TEITLER Jeffrey": "teitler-jeffrey",
    "TEITLER Marc": "teitler-marc",
    "TEIXEIRA Cristina": "teixeira-cristina",
    "TEIXEIRA DE MATTOS Alexander": "teixeira-de-mattos-alexander",
    "TEKERIAN Anais Alexandra": "tekerian-anais-alexandra",
    "TELFAR Evangelina": "telfar-evangelina",
    "TELFER George": "telfer-george",
    "TELFER Paul": "telfer-paul",
    "TELL TALE HEARTS ": "tell-tale-hearts",
    "TELLER Dickdon": "teller-dickdon",
    "TELLER Ryan Michael": "teller-ryan-michael",
    "TELLER Zander": "teller-zander",
    "TELLER ": "teller",
    "TELLEZ Marc": "tellez-marc",
    "TELSON Bob": "telson-bob",
    "TELUSHKIN Joseph": "telushkin-joseph",
    "TEMERSON Catherine": "temerson-catherine",
    "TEMKIN Spencer": "temkin-spencer",
    "TEMPELSMAN Cathy": "tempelsman-cathy",
    "TEMPERLEY Stephen": "temperley-stephen",
    "TEMPEST Kate": "tempest-kate",
    "TEMPEST William": "tempest-william",
    "TEMPLE De Lisa": "temple-de-lisa",
    "TEMPLE Dura": "temple-dura",
    "TEMPLE Keith": "temple-keith",
    "TEMPLE Robert": "temple-robert",
    "TEMPLE THEATRE ": "temple-theatre",
    "TEMPLEMAN Eleanor Sy": "templeman-eleanor-sy",
    "TEMPLETON Andrew": "templeton-andrew",
    "TEMPLETON Fiona": "templeton-fiona",
    "TEMPLETON Lindsay": "templeton-lindsay",
    "TEMPLETON William": "templeton-william",
    "TEMPLETON-YOUNG Zoe": "templeton-young-zoe",
    "TEN Ritsaert": "ten-ritsaert",
    "TENDULKAR Vijay": "tendulkar-vijay",
    "TENENBOM Tuvia": "tenenbom-tuvia",
    "TENERIELLO Susan": "teneriello-susan",
    "TENGES Robert": "tenges-robert",
    "TENNANT Carrie": "tennant-carrie",
    "TENNANT K": "tennant-k",
    "TENNANT Kylie": "tennant-kylie",
    "TENNENT Karen": "tennent-karen",
    "TENNERIELLO Susan": "tenneriello-susan",
    "TENNEY Steve": "tenney-steve",
    "TENNISON Helen": "tennison-helen",
    "TENNYSON Izzy": "tennyson-izzy",
    "TENUTO Eva": "tenuto-eva",
    "TEODORO Jose": "teodoro-jose",
    "TEODOSIO Dennis": "teodosio-dennis",
    "TEPLICK Anne": "teplick-anne",
    "TEPPER Albert": "tepper-albert",
    "TEPPER Kirby": "tepper-kirby",
    "TEPPERMAN Julie": "tepperman-julie",
    "TEPPERMAN Shelley": "tepperman-shelley",
    "TEPPETT Finnius": "teppett-finnius",
    "TERAN Andi": "teran-andi",
    "TERAN Cash": "teran-cash",
    "TERAOKA Arlene A": "teraoka-arlene-a",
    "TERAYAMA Shuji": "terayama-shuji",
    "TERCIAN Gracie": "tercian-gracie",
    "TERENCE David": "terence-david",
    "TERENCE Phormio": "terence-phormio",
    "TERENCE Rae": "terence-rae",
    "TERENCE ": "terence",
    "TERERA Giles": "terera-giles",
    "TERESA Brett": "teresa-brett",
    "TERHUNE Edward": "terhune-edward",
    "TERIO Jody": "terio-jody",
    "TERONOVA Tanya": "teronova-tanya",
    "TERPSTRA Koos": "terpstra-koos",
    "TERRANOVA Frank": "terranova-frank",
    "TERRELL Anderson": "terrell-anderson",
    "TERRELL Ken": "terrell-ken",
    "TERRELL Vincent": "terrell-vincent",
    "TERRIAULT Daniel": "terriault-daniel",
    "TERRIS Chelsea": "terris-chelsea",
    "TERRITO Jim": "territo-jim",
    "TERRY Cory": "terry-cory",
    "TERRY Dane": "terry-dane",
    "TERRY John": "terry-john",
    "TERRY Keith": "terry-keith",
    "TERRY Mackenzie": "terry-mackenzie",
    "TERRY Megan": "terry-megan",
    "TERRY Michelle": "terry-michelle",
    "TERRY Rebecca Hope": "terry-rebecca-hope",
    "TERRYN Yahya": "terryn-yahya",
    "TERSMAN Ninna": "tersman-ninna",
    "TERSON Peter": "terson-peter",
    "TESH Jane": "tesh-jane",
    "TESHIGARA Saburo": "teshigara-saburo",
    "TESICH Nadja": "tesich-nadja",
    "TESICH Steve": "tesich-steve",
    "TESORI Jeanine": "tesori-jeanine",
    "TESSLER Gloria": "tessler-gloria",
    "TEST Matt": "test-matt",
    "TESTAMENT ": "testament",
    "TESTER Brian": "tester-brian",
    "TESTER Christopher": "tester-christopher",
    "TESTER Michael": "tester-michael",
    "TETENBAUM Abraham": "tetenbaum-abraham",
    "TETLEY Graeme": "tetley-graeme",
    "TEUBEN Sonia": "teuben-sonia",
    "TEVAL Ronald": "teval-ronald",
    "TEWARI Devang": "tewari-devang",
    "TEWHIU Josephine Stewart": "tewhiu-josephine-stewart",
    "TEWKESBURY Joan": "tewkesbury-joan",
    "TEY Josephine": "tey-josephine",
    "TEZCAN Feri": "tezcan-feri"
  }
};