export default {
  "metadata": {
    "results": 594,
    "timeStamp": "2025-12-05T21:31:41.574Z",
    "url": "https://www.doollee.com/PlaywrightsT/T_playwrights_g-l.php"
  },
  "authors": {
    "THACKER David": "thacker-david",
    "THACKER Jonathan": "thacker-jonathan",
    "THACKER Kit": "thacker-kit",
    "THACKER Russ": "thacker-russ",
    "THACKER Russell": "thacker-russell",
    "THACKER William": "thacker-william",
    "THACKERAY Lucy": "thackeray-lucy",
    "THACKERY Dan": "thackery-dan",
    "THAIN Paul": "thain-paul",
    "THAINE Craig": "thaine-craig",
    "THAINE Victoria": "thaine-victoria",
    "THAIN-GRAY Rachel": "thain-gray-rachel",
    "THAKRAR Asaita": "thakrar-asaita",
    "THALER Liz": "thaler-liz",
    "THALHEIMER Norman": "thalheimer-norman",
    "THANATOS Simon": "thanatos-simon",
    "THANE Adele": "thane-adele",
    "THANE John": "thane-john",
    "THARP Twyla": "tharp-twyla",
    "THAT WAS FAST ": "that-was-fast",
    "THATCHER Billy": "thatcher-billy",
    "THATCHER Kristine": "thatcher-kristine",
    "THAUBERGER Rudy": "thauberger-rudy",
    "THAW Morton": "thaw-morton",
    "THAYER Toni K": "thayer-toni-k",
    "THE DRILLING COMPAY NY ": "thedrillingcompany",
    "THE LIONS PART ": "the-lions-part",
    "THEATER ARETMIS ": "theater-aretmis",
    "THEATER OOBLECK, THE ": "theater-oobleck",
    "THEATER SGARAMUSCH ": "theater-sgaramusch",
    "THEATR FFYNNON ": "theatr-ffynnon",
    "THEATR IOLO ": "theatr-iolo",
    "THEATR LICEDEI ": "theatr-licedei",
    "THEATR NA N'OG ": "theatr-na-n-og",
    "THEATR POWYS ": "theatr-powys",
    "THEATR WEST GLAMORGAN ": "theatr-west-glamorgan",
    "THEATRE AD INFINITUM ": "theatre-ad-infinitum",
    "THEATRE AKHE ": "theatre-akhe",
    "THEATRE ALTERNATIVE ": "theatre-alternative",
    "THEATRE ASKEW ": "theatre-askew",
    "THEATRE BEATING ": "theatre-beating",
    "THEATRE BLACK COMPANY ": "theatre-black-company",
    "THEATRE BY DESIGN ": "theatre-by-design",
    "THEATRE COMPANY, THE ": "theatre-company-the",
    "THEATRE CRYPTIC ": "theatre-cryptic",
    "THEATRE DACAPO ": "theatre-dacapo",
    "THEATRE DE COMPLICITE ": "theatre-de-complicite",
    "THEATRE DE CUNT ": "theatre-de-cunt",
    "THEATRE DE LA HIS DE PAIN ": "theatre-de-la-his-de-pain",
    "THEATRE DE LA MANDRAGORE ": "theatre-de-la-mandragore",
    "THEATRE DE L'ABRE ": "theatre-de-l-abre",
    "THEATRE DE L'ANGE FOU ": "theatre-de-l-ange-fou",
    "THEATRE DE L'ATELIER ": "theatre-de-l-atelier",
    "THEATRE DE LE MIE PAIN ": "theatre-de-le-mie-pain",
    "THEATRE DE L'UNITE ": "theatre-de-unite",
    "THEATRE DELICATESSEN ": "theatre-delicatessen",
    "THEATRE DU MOUVEMENT ": "theatre-du-mouvement",
    "THEATRE DU PARTI-PRIS ": "theatre-du-parti-pris",
    "THEATRE DU RADEAU ": "theatre-du-radeau",
    "THEATRE EDIBLE ": "theatre-edible",
    "THEATRE IN CAHOOTS ": "theatre-in-cahoots",
    "THEATRE IN EDUCATION COMPANY ": "theatre-in-education-company",
    "THEATRE LAB ": "theatre-lab",
    "THEATRE LE RANELAGH ": "theatre-le-ranelagh",
    "THEATRE LOZHE ": "theatre-lozhe",
    "THEATRE MANJANA ": "theatre-manjana",
    "THEATRE MITU ": "theatre-mitu",
    "THEATRE MODO ": "theatre-modo",
    "THEATRE MURAILLE ": "theatre-muraille",
    "THEATRE O ": "theatre-o",
    "THEATRE OF IMAGINATION ": "theatre-of-imagination",
    "THEATRE OF MISTAKES ": "theatre-of-mistakes",
    "THEATRE OF THE EIGHTH DAY ": "theatre-of-the-eighth-day",
    "THEATRE OMNIBUS ": "theatre-omnibus",
    "THEATRE PRAPILE ": "theatre-prapile",
    "THEATRE PUR ": "theatre-pur",
    "THEATRE RE ": "theatre-re",
    "THEATRE ROUNDABOUT ": "theatre-roundabout",
    "THEATRE SANS FRONTIERES ": "theatre-sans-frontieres",
    "THEATRE SMITH-GILMOUR ": "theatre-smith-gilmour",
    "THEATRE STATE ": "theatre-state",
    "THEATRE TARQUIN ": "theatre-tarquin",
    "THEATRE TEMOIN ": "theatre-temoin",
    "THEATRE UNDER FIRE ": "theatre-under-fire",
    "THEATRE WHISPERS ": "theatre-whispers",
    "THEATRE WORKSHOP ": "theatre-workshop",
    "THEATREISRAELNEW Creative": "theatreisraelnew-creative",
    "THEATRE-RITES ": "theatre-rites",
    "THEATRESPORTS ": "theatresports",
    "THEBUS Jessica": "thebus-jessica",
    "THEERAKULSTIT Shyaporn": "theerakulstit-shyaporn",
    "THEINER George": "theiner-george",
    "THEIS Jack": "theis-jack",
    "THEIS Mickey": "theis-mickey",
    "THEISSEN Cherie Stewart": "theissen-cherie-stewart",
    "THEKWANA Kgosana": "thekwana-kgosana",
    "THELANDER Barbara K": "thelander-barbara-k",
    "THELIN Carl": "thelin-carl",
    "THELIN Toby": "thelin-toby",
    "THEOBALD Roslyn": "theobald-roslyn",
    "THEODORA Stephie": "theodora-stephie",
    "THEODORAKIS Maria": "theodorakis-maria",
    "THEODORAKIS Mikis": "theodorakis-mikis",
    "THEODORE Bobby": "theodore-bobby",
    "THEODORE Shank": "theodore-shank",
    "THEODORIDIS George": "theodoridis-george",
    "THEODOROU Michael": "theodorou-michael",
    "THEODOROU Patricia": "theodorou-patricia",
    "THERRIAULT Daniel": "therriault-daniel",
    "THERRIEN Joseph Jonah": "therrien-joseph-jonah",
    "THEVENOT Shelby": "thevenot-shelby",
    "THIAM Bamba": "thiam-bamba",
    "THIARAI Kully": "thiarai-kully",
    "THIBAUD Patrice": "thibaud-patrice",
    "THIBAULT Anne": "thibault-anne",
    "THIBODEAUX Sandra": "thibodeaux-sandra",
    "THIE Sharon": "thie-sharon",
    "THIELEN Aaron": "thielen-aaron",
    "THIEME Barbara": "thieme-barbara",
    "THIERREE James": "thierree-james",
    "THIES O F": "thies-o-f",
    "THIESSEN Cherie": "thiessen-cherie",
    "THIESSEN Vern": "thiessen-vern",
    "THIGPEN Sara": "thigpen-sara",
    "THINNES Walter": "thinnes-walter",
    "THIONE Lorenzo": "thione-lorenzo",
    "THIONG'O Ngugi Wa": "thiong-o-ngugi-wa",
    "THIRD ANGEL ": "third-angel",
    "THIRD RAIL PROJECTS ": "third-rail-projects",
    "THIRD WORLD REVELATIONISTS ": "third-world-revelationists",
    "THIRKELL Angela": "thirkell-angela",
    "THIRTEEN THEATRE COMPANY ": "thirteen-theatre-company",
    "THIRTLE Robert": "thirtle-robert",
    "THIRY Heather": "thiry-heather",
    "THISTLE Louise": "thistle-louise",
    "THIYAM Ratan": "thiyam-ratan",
    "THOJ A-Yia": "thoj-a-yia",
    "THOM C J": "thom-c-j",
    "THOM Jess": "thom-jess",
    "THOM Molly": "thom-molly",
    "THOM Paul": "thom-paul",
    "THOM Robert": "thom-robert",
    "THOM Sarah": "thom-sarah",
    "THOMALEN E": "thomalen-e",
    "THOMAN Camille": "thoman-camille",
    "THOMAS A C": "thomas-a-c",
    "THOMAS Aaron": "thomas-aaron",
    "THOMAS Alexander": "thomas-alexander",
    "THOMAS Angela": "thomas-angela",
    "THOMAS Annemarie Lewis": "thomas-annemarie-lewis",
    "THOMAS Annie": "thomas-annie",
    "THOMAS Ashley": "thomas-ashley",
    "THOMAS Basil": "thomas-basil",
    "THOMAS Blair": "thomas-blair",
    "THOMAS Bob": "thomas-bob",
    "THOMAS Buddy": "thomas-buddy",
    "THOMAS Caitlin": "thomas-caitlin",
    "THOMAS Carl": "thomas-carl",
    "THOMAS Cathy": "thomas-cathy",
    "THOMAS Charles": "thomas-charles",
    "THOMAS Charles Philip": "thomas-charles-philip",
    "THOMAS Chris": "thomas-chris",
    "THOMAS Colin": "thomas-colin",
    "THOMAS Cori": "thomas-cori",
    "THOMAS D D": "thomas-d-d",
    "THOMAS D M": "thomas-d-m",
    "THOMAS D Paul": "thomas-d-paul",
    "THOMAS David": "thomas-david",
    "THOMAS Dee Dee": "thomas-dee-dee",
    "THOMAS Derek": "thomas-derek",
    "THOMAS Dylan": "thomas-dylan",
    "THOMAS Eberle": "thomas-eberle",
    "THOMAS Ed": "thomas-ed",
    "THOMAS Edward": "thomas-edward",
    "THOMAS Edward J": "thomas-edward-j",
    "THOMAS Edwin": "thomas-edwin",
    "THOMAS Emily": "thomas-emily",
    "THOMAS Evan": "thomas-evan",
    "THOMAS Fatisha": "thomas-fatisha",
    "THOMAS Freyda": "thomas-freyda",
    "THOMAS Geraint": "thomas-geraint",
    "THOMAS Gerald": "thomas-gerald",
    "THOMAS Gwyn (1)": "thomas-gwyn-1",
    "THOMAS Gwyn (2)": "thomas-gwyn-2",
    "THOMAS Heidi": "thomas-heidi",
    "THOMAS Jacob": "thomas-jacob",
    "THOMAS Jeffrey": "thomas-jeffrey",
    "THOMAS Jerome": "thomas-jerome",
    "THOMAS Jessica": "thomas-jessica",
    "THOMAS Jill Charlotte": "thomas-jill-charlotte",
    "THOMAS Joshua": "thomas-joshua",
    "THOMAS Joyce Carol": "thomas-joyce-carol",
    "THOMAS Joye": "thomas-joye",
    "THOMAS Julie Grady": "thomas-julie-grady",
    "THOMAS Keith": "thomas-keith",
    "THOMAS L E": "thomas-l-e",
    "THOMAS L W": "thomas-l-w",
    "THOMAS Lee": "thomas-lee",
    "THOMAS Les": "thomas-les",
    "THOMAS Letty": "thomas-letty",
    "THOMAS Marie": "thomas-marie",
    "THOMAS Mark": "thomas-mark",
    "THOMAS Marlin": "thomas-marlin",
    "THOMAS Marlo": "thomas-marlo",
    "THOMAS Melba": "thomas-melba",
    "THOMAS Michael": "thomas-michael",
    "THOMAS Michael (1)": "thomas-michael-1",
    "THOMAS Michael (2)": "thomas-michael-2",
    "THOMAS Milly": "thomas-milly",
    "THOMAS Mitch Tawhi": "thomas-mitch-tawhi",
    "THOMAS Neil": "thomas-neil",
    "THOMAS Nick (1)": "thomas-nick-1",
    "THOMAS Nick (2)": "thomas-nick-2",
    "THOMAS Nicole": "thomas-nicole",
    "THOMAS Owen": "thomas-owen",
    "THOMAS Paul": "thomas-paul",
    "THOMAS Paul Berhard": "thomas-paul-berhard",
    "THOMAS Percy": "thomas-percy",
    "THOMAS Peter": "thomas-peter",
    "THOMAS Phi": "thomas-phi",
    "THOMAS Polly": "thomas-polly",
    "THOMAS R Eric": "thomas-r-eric",
    "THOMAS Ray": "thomas-ray",
    "THOMAS Renee": "thomas-renee",
    "THOMAS Rhys": "thomas-rhys",
    "THOMAS Richard": "thomas-richard",
    "THOMAS Richard (1)": "thomas-richard-1",
    "THOMAS Rick": "thomas-rick",
    "THOMAS Riley": "thomas-riley",
    "THOMAS Robert": "thomas-robert",
    "THOMAS Ruby": "thomas-ruby",
    "THOMAS Sam": "thomas-sam",
    "THOMAS Stan": "thomas-stan",
    "THOMAS Steve": "thomas-steve",
    "THOMAS Stuart": "thomas-stuart",
    "THOMAS Stuart (1)": "thomas-stuart-1",
    "THOMAS T C": "thomas-t-c",
    "THOMAS Thom": "thomas-thom",
    "THOMAS Tim": "thomas-tim",
    "THOMAS Trevor": "thomas-trevor",
    "THOMAS Valerie": "thomas-valerie",
    "THOMAS Valerie M": "thomas-valerie-m",
    "THOMAS Vaughn": "thomas-vaughn",
    "THOMAS Veona": "thomas-veona",
    "THOMAS II T Gaillard": "thomas-ii-t-gaillard",
    "THOMAS-FLETCHER Arlette": "thomas-fletcher-arlette",
    "THOMAS-HERRERA Edward": "thomas-herrera-edward",
    "THOMAS-JONES Anna": "thomas-jones-anna",
    "THOMAS-JONES Hagan": "thomas-jones-hagan",
    "THOMASON Ed": "thomason-ed",
    "THOMASON Jane": "thomason-jane",
    "THOMASON Kerrie": "thomason-kerrie",
    "THOMASON Shannon": "thomason-shannon",
    "THOMASSIAN Lilly": "thomassian-lilly",
    "THOMASSON Martin": "thomasson-martin",
    "THOMASSON Niles": "thomasson-niles",
    "THOME Andrea": "thome-andrea",
    "THOMEY Greg": "thomey-greg",
    "THOMPKINS Richard": "thompkins-richard",
    "THOMPSON Adam J": "thompson-adam-j",
    "THOMPSON Andrew": "thompson-andrew",
    "THOMPSON April Yvette": "thompson-april-yvette",
    "THOMPSON B C": "thompson-b-c",
    "THOMPSON Ben": "thompson-ben",
    "THOMPSON Ben (1)": "thompson-ben-1",
    "THOMPSON Bill": "thompson-bill",
    "THOMPSON Billy": "thompson-billy",
    "THOMPSON Brian": "thompson-brian",
    "THOMPSON Bruce": "thompson-bruce",
    "THOMPSON Bryony J": "thompson-bryony-j",
    "THOMPSON Carole": "thompson-carole",
    "THOMPSON Casey Leigh": "thompson-casey-leigh",
    "THOMPSON Chezia B": "thompson-chezia-b",
    "THOMPSON Chris": "thompson-chris",
    "THOMPSON Chris (1)": "thompson-chris-1",
    "THOMPSON D C": "thompson-d-c",
    "THOMPSON Daniel": "thompson-daniel",
    "THOMPSON Danny": "thompson-danny",
    "THOMPSON Davey": "thompson-davey",
    "THOMPSON David": "thompson-david",
    "THOMPSON Don": "thompson-don",
    "THOMPSON Dylan H": "thompson-dylan-h",
    "THOMPSON E R": "thompson-e-r",
    "THOMPSON Ella": "thompson-ella",
    "THOMPSON Eric": "thompson-eric",
    "THOMPSON Ernest": "thompson-ernest",
    "THOMPSON Fred": "thompson-fred",
    "THOMPSON Garland": "thompson-garland",
    "THOMPSON Geoff": "thompson-geoff",
    "THOMPSON Graeme": "thompson-graeme",
    "THOMPSON Greg": "thompson-greg",
    "THOMPSON Helena": "thompson-helena",
    "THOMPSON Hope": "thompson-hope",
    "THOMPSON Ian": "thompson-ian",
    "THOMPSON J Lee": "thompson-j-lee",
    "THOMPSON Jane E": "thompson-jane-e",
    "THOMPSON Jay": "thompson-jay",
    "THOMPSON Jeff": "thompson-jeff",
    "THOMPSON Jeremy": "thompson-jeremy",
    "THOMPSON Jessie": "thompson-jessie",
    "THOMPSON Jimmy": "thompson-jimmy",
    "THOMPSON Joe": "thompson-joe",
    "THOMPSON John": "thompson-john",
    "THOMPSON John Cargill": "thompson-john-cargill",
    "THOMPSON Johnnie": "thompson-johnnie",
    "THOMPSON John-Richard": "thompson-john-richard",
    "THOMPSON Joshua": "thompson-joshua",
    "THOMPSON Judith": "thompson-judith",
    "THOMPSON Kathleen Ann": "thompson-kathleen-ann",
    "THOMPSON Katie": "thompson-katie",
    "THOMPSON Katrina": "thompson-katrina",
    "THOMPSON Keisha": "thompson-keisha",
    "THOMPSON Keith": "thompson-keith",
    "THOMPSON Kester": "thompson-kester",
    "THOMPSON Kris": "thompson-kris",
    "THOMPSON Kristen": "thompson-kristen",
    "THOMPSON Larry": "thompson-larry",
    "THOMPSON Lee": "thompson-lee",
    "THOMPSON Lisa": "thompson-lisa",
    "THOMPSON Lloyd": "thompson-lloyd",
    "THOMPSON Lorraine": "thompson-lorraine",
    "THOMPSON Mark": "thompson-mark",
    "THOMPSON Mark (1)": "thompson-mark-1",
    "THOMPSON Matt": "thompson-matt",
    "THOMPSON Mervyn": "thompson-mervyn",
    "THOMPSON Michael": "thompson-michael",
    "THOMPSON Neville": "thompson-neville",
    "THOMPSON Nina": "thompson-nina",
    "THOMPSON Olivia": "thompson-olivia",
    "THOMPSON Pamela": "thompson-pamela",
    "THOMPSON Paul": "thompson-paul",
    "THOMPSON Paul (2)": "thompson-paul-2",
    "THOMPSON Paula": "thompson-paula",
    "THOMPSON Peggy": "thompson-peggy",
    "THOMPSON Peter": "thompson-peter",
    "THOMPSON R H": "thompson-r-h",
    "THOMPSON Richard": "thompson-richard",
    "THOMPSON Robert": "thompson-robert",
    "THOMPSON Rod": "thompson-rod",
    "THOMPSON Sam": "thompson-sam",
    "THOMPSON Selina": "thompson-selina",
    "THOMPSON Simon": "thompson-simon",
    "THOMPSON Sister Mary Francesca": "thompson-sister-mary-francesca",
    "THOMPSON Stella": "thompson-stella",
    "THOMPSON Stephanie Wright": "thompson-stephanie-wright",
    "THOMPSON Steve": "thompson-steve",
    "THOMPSON Steven": "thompson-steven",
    "THOMPSON Susan W": "thompson-susan-w",
    "THOMPSON Tazewell": "thompson-tazewell",
    "THOMPSON Therese": "thompson-therese",
    "THOMPSON Tierl": "thompson-tierl",
    "THOMPSON Todd": "thompson-todd",
    "THOMPSON Tom": "thompson-tom",
    "THOMPSON Trance": "thompson-trance",
    "THOMPSON-QUARTEY Sandra": "thompson-quartey-sandra",
    "THOMPSON-SCRETCHING Anne L": "thompson-scretching-anne-l",
    "THOMS Doug": "thoms-doug",
    "THOMSON Alexander M": "thompson-alexander-m",
    "THOMSON B C": "thomson-b-c",
    "THOMSON Clare": "thomson-clare",
    "THOMSON David": "thomson-david",
    "THOMSON David Mark": "thomson-david-mark",
    "THOMSON Edward": "thomson-edward",
    "THOMSON Jeff": "thomson-jeff",
    "THOMSON Katherine": "thomson-katherine",
    "THOMSON Kristen": "thomson-kristen",
    "THOMSON Leroy H": "thomson-leroy-h",
    "THOMSON Lloyd": "thomson-lloyd",
    "THOMSON Lynn M": "thomson-lynn-m",
    "THOMSON Mark": "thomson-mark",
    "THOMSON Richard": "thomson-richard",
    "THOMSON Rob": "thomson-rob",
    "THOMSON Sandy": "thomson-sandy",
    "THOMSON Stewart": "thomson-stewart",
    "THOMSON Wendy": "thomson-wendy",
    "THOMSON-KING Rachel": "thomson-king-rachel",
    "THONG Lisa": "thong-lisa",
    "THOPSON Fred": "thopson-fred",
    "THOR Saychay": "thor-saychay",
    "THORBURN Iain": "thorburn-iain",
    "THORBURN Peter": "thorburn-peter",
    "THORENS Dan": "thorens-dan",
    "THORESON Ryan": "thoreson-ryan",
    "THORINGTON Jack": "thorington-jack",
    "THORN Fiona": "thorn-fiona",
    "THORN Jesse": "thorn-jesse",
    "THORN John": "thorn-john",
    "THORN Rachel E": "thorn-rachel-e",
    "THORN Ronald Scott": "thorn-ronald-scott",
    "THORNBER Geoffrey": "thornber-geoffrey",
    "THORNBER Robin": "thornber-robin",
    "THORNBURG Stephen": "thornburg-stephen",
    "THORNE Anna V": "thorne-anna-v",
    "THORNE Jack": "thorne-jack",
    "THORNE Joan Vail": "thorne-joan-vail",
    "THORNE Philip": "thorne-philip",
    "THORNE Rasp": "thorne-rasp",
    "THORNE Stephen": "thorne-stephen",
    "THORNE Steven": "thorne-steven",
    "THORNE Tracy": "thorne-tracy",
    "THORNHILL Alan": "thornhill-alan",
    "THORNS Tricia": "thorns-tricia",
    "THORNTON Ashley": "thornton-ashley",
    "THORNTON Benjamin": "thornton-benjamin",
    "THORNTON Charles": "thornton-charles",
    "THORNTON Colin": "thornton-colin",
    "THORNTON Craig": "thornton-craig",
    "THORNTON Darren": "thornton-darren",
    "THORNTON E": "thornton-e",
    "THORNTON Jane": "thornton-jane",
    "THORNTON Kevin": "thornton-kevin",
    "THORNTON Megan": "thornton-megan",
    "THORNTON Peter": "thornton-peter",
    "THORNTON Rich": "thornton-rich",
    "THORNTON Robert": "thornton-robert",
    "THORNTON Roxanne": "thornton-roxanne",
    "THORNTON Susan": "thornton-susan",
    "THOROGOOD Anthony Edward": "thorogood-anthony-edward",
    "THORON Elise": "thoron-elise",
    "THORP Ken": "thorp-ken",
    "THORPE Adam": "thorpe-adam",
    "THORPE Brierley": "thorpe-brierley",
    "THORPE Chris": "thorpe-chris",
    "THORPE Jess": "thorpe-jess",
    "THORPE Joshua": "thorpe-joshua",
    "THORPE Stephanie": "thorpe-stephanie",
    "THORSTENSON Brian": "thorstenson-brian",
    "THOTTAM Jyoti": "thottam-jyoti",
    "THRASH Nate": "thrash-nate",
    "THRASHER Sunny": "thrasher-sunny",
    "THREE CROWS THEATRE ": "three-crows-theatre",
    "THREE WOMEN ": "three-women",
    "THREEDY Debora": "threedy-debora",
    "THRELFALL Andrew": "threlfall-andrew",
    "THRESHOLD THEATRE ": "threshold-theatre",
    "THRIST Megan": "thrist-megan",
    "THRONSON Ron": "thronson-ron",
    "THROPP Randall": "thropp-randall",
    "THROSSELL Ric": "throssell-ric",
    "THROTTLE ": "throttle",
    "THROWBRIDGE Alina R": "throwbridge-alina-r",
    "THROWER Emmitt": "thrower-emmitt",
    "THROWER Scott": "thrower-scott",
    "THRUN Oliver": "thrun-oliver",
    "THUAL Heloise": "thual-heloise",
    "THUESEN Stephanie": "thuesen-stephanie",
    "THUNA Lee": "thuna-lee",
    "THUNDER Brian": "thunder-brian",
    "THURBER James": "thurber-james",
    "THURBER Lucy": "thurber-lucy",
    "THUREEN Paul": "thureen-paul",
    "THURGOOD Margaret": "thurgood-margaret",
    "THURMAN Beverley": "thurman-beverley",
    "THURMAN Daniel": "thurman-daniel",
    "THURMAN Leo L": "thurman-leo-l",
    "THURSCHWELL Harry T": "thurschwell-harry-t",
    "THURSTON Alan": "thurston-alan",
    "THURSTON Angela": "thurston-angela",
    "THURSTON Cheryl": "thurston-cheryl",
    "THURSTON Robin": "thurston-robin",
    "THURSTON Shannon": "thurston-shannon",
    "THURY Fredrick H": "thury-fredrick-h",
    "THWAITE Emily": "thwaite-emily",
    "THWAITES Peter": "thwaites-peter",
    "TIANG Jeremy": "tiang-jeremy",
    "TIANGA David": "tianga-david",
    "TIATA FAHODZI ": "tiata-fahodzi",
    "TIBBETS Wayne": "tibbets-wayne",
    "TIBBETTS Christopher": "tibbetts-christopher",
    "TIBBETTS Mike": "tibbetts-mike",
    "TIBBEY Paul": "tibbey-paul",
    "TIBBLES George": "tibbles-george",
    "TICHENOR Austin": "tichenor-austin",
    "TICKELL Andrew": "tickell-andrew",
    "TICKNER Peter": "tickner-peter",
    "TIDHOLM Thomas": "tidholm-thomas",
    "TIDLER Charles": "tidler-charles",
    "TIDY Bill": "tidy-bill",
    "TIECK Ludwig": "tieck-ludwig",
    "TIEGER Danny": "tieger-danny",
    "TIEN Melisa": "tien-melisa",
    "TIERNAN Eleanor": "tiernan-eleanor",
    "TIERNEY Alicia": "tierney-alicia",
    "TIERNEY Andrea": "tierney-andrea",
    "TIERNEY Hanne": "tierney-hanne",
    "TIERNEY Jim": "tierney-jim",
    "TIERNEY Matthew F": "tierney-matthew-f",
    "TIERNEY Thomas": "tierney-thomas",
    "TIERNEY-KEOGH Lisa": "tierney-keogh-lisa",
    "TIFFANY John": "tiffany-john",
    "TIFFONEY James": "tiffoney-james",
    "TIFFOU Solvene": "tiffou-solvene",
    "TIGER Janet S": "tiger-janet-s",
    "TIGG Nick": "tigg-nick",
    "TIGHE Dylan": "tighe-dylan",
    "TIJSSENS Angelo": "tijssens-angelo",
    "TIKKANEN Marta": "tikkanen-marta",
    "TIKTIN Carl": "tiktin-carl",
    "TILAJCIK Peter": "tilajcik-peter",
    "TILBURY Peter": "tilbury-peter",
    "TILELLI Krysten": "tilelli-krysten",
    "TILFORD Michael": "tilford-michael",
    "TILL Benjamin": "till-benjamin",
    "TILL Lawrence": "till-lawrence",
    "TILL Richard": "till-richard",
    "TILLER Chrissie": "tiller-chrissie",
    "TILLER Steve": "tiller-steve",
    "TILLER Ted": "tiller-ted",
    "TILLERY Jodi Lynn": "tillery-jodi-lynn",
    "TILLETT Seth": "tillett-seth",
    "TILLEY Brian": "tilley-brian",
    "TILLEY Chris": "tilley-chris",
    "TILLEY Elspeth": "tilley-elspeth",
    "TILLEY Sam": "tilley-sam",
    "TILLING Andrew": "tilling-andrew",
    "TILLINGER Mark": "tillinger-mark",
    "TILLINGHAST Daven": "tillinghast-daven",
    "TILL-MOBLEY Mamie": "till-mobley-mamie",
    "TILLY Francois-Louis": "tilly-francois-louis",
    "TILLY Grant": "tilly-grant",
    "TILSLEY Frank": "tilsley-frank",
    "TILSON George Purefoy": "tilson-george-purefoy",
    "TIMBERS Alex": "timbers-alex",
    "TIMLIN John": "timlin-john",
    "TIMM Fred": "timm-fred",
    "TIMM Lee": "timm-lee",
    "TIMM Stephanie": "timm-stephanie",
    "TIMMERMANS Chris": "timmermans-chris",
    "TIMMERS Gerrit": "timmers-gerrit",
    "TIMMINS Philip": "timmins-philip",
    "TIMMONS Anne Miyamoto": "timmons-anne-miyamoto",
    "TIMMS Howard": "timms-howard",
    "TIMMS Nigel": "timms-nigel",
    "TIMMS Steve": "timms-steve",
    "TIMOTEO Farren": "timoteo-farren",
    "TIMPANO Marco": "timpano-marco",
    "TINALLI Italo": "tinalli-italo",
    "TINBERG Nalsey": "tinberg-nalsey",
    "TINDALL A J": "tindall-a-j",
    "TINDALL Adam": "tindall-adam",
    "TINDER THEATRE ": "tinder-theatre",
    "TINDLE Jacob": "tindle-jacob",
    "TING Eric": "ting-eric",
    "TING Steve": "ting-steve",
    "TINGLE, THE ": "tingle",
    "TINGLEY Kyle": "tingley-kyle",
    "TINGWELL Charles": "tingwell-charles",
    "TINGWELL Drew": "tingwell-drew",
    "TINKHAM David": "tinkham-david",
    "TINKLER Shaun": "tinkler-shaun",
    "TINNISWOOD Peter": "tinniswood-peter",
    "TINSLEY Bill": "tinsley-bill",
    "TINSLEY Herbert F": "tinsley-herbert-f",
    "TINSLEY Molly": "tinsley-molly",
    "TINSON Rod": "tinson-rod",
    "TIPE David": "tipe-david",
    "TIPLADY Steve": "tiplady-steve",
    "TIPPE Annie": "tippe-annie",
    "TIPPETS Melody Ventris-French": "tippets-melody-ventris-french",
    "TIPPING Richard": "tipping-richard",
    "TIPPLE Sarah": "tipple-sarah",
    "TIPTON Don": "tipton-don",
    "TIPTON John": "tipton-john",
    "TIRADO Candido": "tirado-candido",
    "TIRELLI Marisol": "tirelli-marisol",
    "TIRGRATH Tami": "tirgrath-tami",
    "TIRMAN Daniel": "tirman-daniel",
    "TIRMAZI Mazur": "tirmazi-mazur",
    "TIROSH-POLK Zohar": "tirosh-polk-zohar",
    "TISCHLER Jacob": "tischler-jacob",
    "TISCHLER Susan": "tischler-susan",
    "TISDALE Michael": "tisdale-michael",
    "TISDALL Laura": "tisdall-laura",
    "TISDALL Polly": "tisdall-polly",
    "TISE Rhiannon": "tise-rhiannon",
    "TISH Larry Jay": "tish-larry-jay",
    "TISI Emily": "tisi-emily",
    "TISSIAN Gabriel": "tissian-gabriel",
    "TISSOT John": "tissot-john",
    "TITCHENER David": "titchener-david",
    "TITELMAN Claire": "titelman-claire",
    "TITHERIDGE Georina": "titheridge-georina",
    "TITO Greg": "tito-greg",
    "TITTEL Christopher": "tittel-christopher",
    "TITTEL Jorg": "tittel-jorg",
    "TITTLE Ryan C": "tittle-ryan-c",
    "TITUS Jacob": "titus-jacob",
    "TJAARDSTRA Nick": "tjaardstra-nick",
    "TJADEN Joshua": "tjaden-joshua",
    "TJARKS Mark": "tjarks-mark",
    "TKACH Glen": "tkach-glen",
    "TKACHENKO Victor S": "tkachenko-victor-s",
    "TKACZ Virlana": "tkacz-virlana",
    "TLC CREATIVE ": "tlc-creative"
  }
};