export default {
  "metadata": {
    "results": 506,
    "timeStamp": "2025-12-05T21:31:45.033Z",
    "url": "https://www.doollee.com/PlaywrightsT/T_playwrights_m-r.php"
  },
  "authors": {
    "TOAL Anna": "toal-anna",
    "TOAL Patrick": "toal-patrick",
    "TOALSON Jeff": "toalson-jeff",
    "TOBIAS Charles": "tobias-charles",
    "TOBIAS Daniel": "tobias-daniel",
    "TOBIAS Fred": "tobias-fred",
    "TOBIAS John": "tobias-john",
    "TOBIAS Lawrence Hodge": "tobias-lawrence-hodge",
    "TOBIESSEN Josh": "tobiessen-josh",
    "TOBIN Miriam": "tobin-miriam",
    "TOBIN Niall": "tobin-niall",
    "TOBIN Robert": "tobin-robert",
    "TOBIN Scott": "tobin-scott",
    "TOBIS Scott Sanford": "tobis-scott-sanford",
    "TOBY Xavier": "toby-xavier",
    "TOCANTINS Terry": "tocantins-terry",
    "TOCKMAN Marin": "tockman-marin",
    "TODARO Mike": "todaro-mike",
    "TODD Albert": "todd-albert",
    "TODD Beverley": "todd-beverley",
    "TODD Chris": "todd-chris",
    "TODD David": "todd-david",
    "TODD Harold": "todd-harold",
    "TODD Matthew": "todd-matthew",
    "TODD Paul": "todd-paul",
    "TODD Ruthven": "todd-ruthven",
    "TODD Stephen": "todd-stephen",
    "TODD Susan": "todd-susan",
    "TODD Susan Gayle": "todd-susan-gayle",
    "TODD Will": "todd-will",
    "TODD THEATER TROUP ": "todd-theater-troup",
    "TODDIE Jean Lenox": "toddie-jean-lenox",
    "TODMAN Georgie": "todman-georgie",
    "TODOROV Niko Rendevski": "todorov-niko-rendevski",
    "TODOROV Peter": "todorov-peter",
    "TODOROVIC Damir": "todorovic-damir",
    "TOENTSCH Dan": "toentsch-dan",
    "TOFIL Ryan": "tofil-ryan",
    "TOFTE Amy": "tofte-amy",
    "TOGNOTTI Brian J": "tognotti-brian-j",
    "TOIBIN Colm": "toibin-colm",
    "TOILER Ernst": "toiler-ernst",
    "TOKATYAN Leon": "tokatyan-leon",
    "TOKHAI Gavin": "tokhai-gavin",
    "TOKSVIG Jenifer": "toksvig-jenifer",
    "TOKSVIG Sandi": "toksvig-sandi",
    "TOKUDA Marilyn": "tokuda-marilyn",
    "TOKUDANI Betty": "tokudani-betty",
    "TOLAN Kathleen": "tolan-kathleen",
    "TOLAN Peter": "tolan-peter",
    "TOLAN Stephanie": "tolan-stephanie",
    "TOLAND Chris": "toland-chris",
    "TOLCHINSKY David E": "tolchinsky-david-e",
    "TOLCSVAY Lazlo": "tolcsvay-lazlo",
    "TOLD BY AN IDIOT ": "told-by-an-idiot",
    "TOLER Celia": "toler-celia",
    "TOLES Jartu Gallashaw": "toles-jartu-gallashaw",
    "TOLINS Jonathan": "tolins-jonathan",
    "TOLIVER Cynthia O": "toliver-cynthia-o",
    "TOLK Alexandra": "tolk-alexandra",
    "TOLKIN Mel": "tolkin-mel",
    "TOLL Samuel": "toll-samuel",
    "TOLLEMACHE Lizzie": "tollemache-lizzie",
    "TOLLER Ernst": "toller-ernst",
    "TOLLEY Justin": "tolley-justin",
    "TOLLY Maria": "tolly-maria",
    "TOLMAN Rosco N": "tolman-rosco-n",
    "TOLMASOFF T H": "tolmasoff-t-h",
    "TOLPUTT Anna": "tolputt-anna",
    "TOLSON Georgina": "tolson-georgina",
    "TOLSON Melvin B": "tolson-melvin-b",
    "TOLSTOY Leo": "tolstoy-leo",
    "TOLTON Paul": "tolton-paul",
    "TOMAINE John": "tomaine-john",
    "TOMAINE Tony": "tomaine-tony",
    "TOMALIN Claire": "tomalin-claire",
    "TOMALIN Jo": "tomalin-jo",
    "TOMAS ": "tomas",
    "TOMASCHIK Stacey": "tomaschik-stacey",
    "TOMASELLI Angela": "tomaselli-angela",
    "TOMASINI Ernesto": "tomasini-ernesto",
    "TOMASINO Matthew": "tomasino-matthew",
    "TOMASKO Joy": "tomasko-joy",
    "TOMASO Carla": "tomaso-carla",
    "TOMASON Kerrie": "tomason-kerrie",
    "TOMASON Meredith": "tomason-meredith",
    "TOMASZUK Piotr": "tomaszuk-piotr",
    "TOME Gregg": "tome-gregg",
    "TOMELTY Joseph": "tomelty-joseph",
    "TOMELTY Rome": "tomelty-rome",
    "TOMERO Helena": "tomero-helena",
    "TOMICH Branislav": "tomich-branislav",
    "TOMIOKA Taeko": "tomioka-taeko",
    "TOMKO Kathleen": "tomko-kathleen",
    "TOMLIN Lily": "tomlin-lily",
    "TOMLIN Liz": "tomlin-liz",
    "TOMLINSON Alan": "tomlinson-alan",
    "TOMLINSON Charlie": "tomlinson-charlie",
    "TOMLINSON David": "tomlinson-david",
    "TOMLINSON John James": "tomlinson-john-james",
    "TOMLINSON Keith": "tomlinson-keith",
    "TOMLINSON Kevin": "tomlinson-kevin",
    "TOMLINSON Laraine": "tomlinson-laraine",
    "TOMLINSON Paul": "tomlinson-paul",
    "TOMLINSON Richard": "tomlinson-richard",
    "TOMLINSON Steven": "tomlinson-steven",
    "TOMMY Liesl": "tommy-liesl",
    "TOMOS Angharad": "tomos-angharad",
    "TOMPKINS James R": "tompkins-james-r",
    "TOMPKINS Jon": "tompkins-jon",
    "TOMPOS Doug": "tompos-doug",
    "TOMPSON Timothy": "tompson-timothy",
    "TOMSON Bob": "tomson-bob",
    "TOMSON Noah": "tomson-noah",
    "TOMYCZ Motrya": "tomycz-motrya",
    "TONER Joanne": "toner-joanne",
    "TONER Matt": "toner-matt",
    "TONER Michael": "toner-michael",
    "TONEY David Emerson": "toney-david-emerson",
    "TONG Christopher Karlin": "tong-christopher-karlin",
    "TONG Jean": "tong-jean",
    "TONG Merlynn": "tong-merlynn",
    "TONG Phil": "tong-phil",
    "TONG Winston": "tong-winston",
    "TONGE Jane": "tonge-jane",
    "TONGUE Donald": "tongue-donald",
    "TONGUE Ruth L": "tongue-ruth-l",
    "TONKIN Louise": "tonkin-louise",
    "TONKINSON Frank": "tonkinson-frank",
    "TONKONOGY Gertrude": "tonkonogy-gertrude",
    "TONON Jen": "tonon-jen",
    "TONOUCHI Lee": "tonouchi-lee",
    "TONY AND DEREK ": "tony-and-derek",
    "TOO MANY CHIEFS ": "too-many-chiefs",
    "TOOEY Jim": "tooey-jim",
    "TOOEY Rosemary Frisino": "tooey-rosemary-frisino",
    "TOOGOOD Sarah": "toogood-sarah",
    "TOOHER Michael": "tooher-michael",
    "TOOHEY Edwina": "toohey-edwina",
    "TOOHEY Rosemary Frisino": "toohey-rosemary-frisino",
    "TOOHEY Steve": "toohey-steve",
    "TOOK Barry": "took-barry",
    "TOOK Mary": "took-mary",
    "TOOKS Lenga": "tooks-lenga",
    "TOOLAN Donal": "toolan-donal",
    "TOOLIS Kevin": "toolis-kevin",
    "TOOMEY Michael F": "toomey-michael-f",
    "TOON Kate": "toon-kate",
    "TOOSEY Sally": "toosey-sally",
    "TOOT COLLECTIVE ": "toot-collective",
    "TOP OF THE WORLD ": "top-of-the-world",
    "TOPIARY Samuel": "topiary-samuel",
    "TOPLIFF John": "topliff-john",
    "TOPLISS Paul": "topliss-paul",
    "TOPO Ruby": "topo-ruby",
    "TOPOL Josef": "topol-josef",
    "TOPOR Tom": "topor-tom",
    "TOPP TWINS ": "topp-twins",
    "TOPPER Cosmo": "topper-cosmo",
    "TOPPER Manja": "topper-manja",
    "TOPPING Frank": "topping-frank",
    "TOPPINGS Michael": "toppings-michael",
    "TORDAFF John": "tordaff-john",
    "TORDAY Piers": "torday-piers",
    "TORDOFF Bill": "tordoff-bill",
    "TORDOFF John": "tordoff-john",
    "TORE John": "tore-john",
    "TORFASON Mikael": "torfason-mikael",
    "TORIEL Nathalie": "toriel-nathalie",
    "TORINO Michele": "torino-michele",
    "TORKOVA Bobby": "torkova-bobby",
    "TORN Tony": "torn-tony",
    "TORNQVIST Mia": "tornqvist-mia",
    "TORODE Sally": "torode-sally",
    "TOROK Frank S": "torok-frank-s",
    "TOROPOV Brandon": "toropov-brandon",
    "TOROSIAN Rebecca": "torosian-rebecca",
    "TORR Diane": "torr-diane",
    "TORR Oliver": "torr-oliver",
    "TORRANCE Alys": "torrance-alys",
    "TORRANCE Kirk": "torrance-kirk",
    "TORRENCE Jay": "torrence-jay",
    "TORRENS Jackie": "torrens-jackie",
    "TORRES Angelique": "torres-angelique",
    "TORRES Casimiro": "torres-casimiro",
    "TORRES Fiona J": "torres-fiona-j",
    "TORRES Joan": "torres-joan",
    "TORRES Maria Elena": "torres-maria-elena",
    "TORRES Susana": "torres-susana",
    "TORRES-CABASSA Angel S": "torres-cabassa-angel-s",
    "TORRUELLAS Elsia Cruz": "torruellas-elsia-cruz",
    "TORRY Andrew": "torry-andrew",
    "TORSION THEATRE ": "torsion-theatre",
    "TORSSON Bjorner": "torsson-bjorner",
    "TORTLADZE Sophie": "tortladze-sophie",
    "TORTOISE IN A NUTSHELL ": "tortoise-in-a-nutshell",
    "TORTORA Tony": "tortora-tony",
    "TORTORICI Julie": "tortorici-julie",
    "TORTURE PROJECT ENSEMBLE ": "torture-project-ensemble",
    "TOSCANO Bill": "toscano-bill",
    "TOSCANO Mario Cantu": "toscano-mario-cantu",
    "TOSCAS Dimitri": "toscas-dimitri",
    "TOSDEVIN Michael": "tosdevin-michael",
    "TOSH Julie": "tosh-julie",
    "TOSNEY Jim": "tosney-jim",
    "TOSSMANN Juergen K": "tossmann-juergen-k",
    "TOSTADO Ben": "tostado-ben",
    "TOTERAS ": "toteras",
    "TOTH Richard": "toth-richard",
    "TOTHEROH Dan": "totheroh-dan",
    "TOTMAN Richard": "totman-richard",
    "TOUBES Guy": "toubes-guy",
    "TOUCHSTONE THEATRE ": "touchstone-theatre",
    "TOUFEXIS Elias": "toufexis-elias",
    "TOUGH Jim": "tough-jim",
    "TOUPIN Catherine-Anne": "toupin-catherine-anne",
    "TOURELLE Wayne": "tourelle-wayne",
    "TOURINO Rebecca": "tourino-rebecca",
    "TOURNEY Michael": "tourney-michael",
    "TOURNIER Michel": "tournier-michel",
    "TOURNIS Anthony": "tournis-anthony",
    "TOUSSAINT Germono": "toussaint-germono",
    "TOUSSAINT Richard": "toussaint-richard",
    "TOUTAIN Andre D": "toutain-andre-d",
    "TOVATT Patrick": "tovatt-patrick",
    "TOVEY Noel": "tovey-noel",
    "TOVEY Russell": "tovey-russell",
    "TOW Jeremy": "tow-jeremy",
    "TOWARD Molly": "toward-molly",
    "TOWBIN Fredi": "towbin-fredi",
    "TOWER Michael Thomas": "tower-michael-thomas",
    "TOWERING INFERNO ": "towering-inferno",
    "TOWERS J Maxwell": "towers-j-maxwell",
    "TOWEY Siobhan": "towey-siobhan",
    "TOWLE W Ray": "towle-w-ray",
    "TOWLER Anthony": "towler-anthony",
    "TOWLER Jeremy": "towler-jeremy",
    "TOWNDROW Chris": "towndrow-chris",
    "TOWNEND JONES Elton": "townend-jones-elton",
    "TOWNLEY Kevin": "townley-kevin",
    "TOWNS Otis": "towns-otis",
    "TOWNSEND Ceri": "townsend-ceri",
    "TOWNSEND Henry": "townsend-henry",
    "TOWNSEND Ian": "townsend-ian",
    "TOWNSEND Jessica": "townsend-jessica",
    "TOWNSEND Jo": "townsend-jo",
    "TOWNSEND Laura": "townsend-laura",
    "TOWNSEND Mark": "townsend-mark",
    "TOWNSEND Paul": "townsend-paul",
    "TOWNSEND Pete": "townsend-pete",
    "TOWNSEND Sue": "townsend-sue",
    "TOWNSHEND Pete": "townshend-pete",
    "TOWSEY Lydia": "towsey-lydia",
    "TOY Barbara": "toy-barbara",
    "TOYAMA Tim": "toyama-tim",
    "TOYE Wendy": "toye-wendy",
    "TOYNE Simon": "toyne-simon",
    "TRACEY Damien": "tracey-damien",
    "TRACEY Debbie": "tracey-debbie",
    "TRACEY Katie": "tracey-katie",
    "TRACY Ann": "tracy-ann",
    "TRACY Carl": "tracy-carl",
    "TRACY Debbie": "tracy-debbie",
    "TRACY Jon": "tracy-jon",
    "TRACZ Joe": "tracz-joe",
    "TRADUP Troy": "tradup-troy",
    "TRAFFORD Steve": "trafford-steve",
    "TRAGER Oliver": "trager-oliver",
    "TRAHEY Jack": "trahey-jack",
    "TRAHEY Jane": "trahey-jane",
    "TRAIGER Larry": "traiger-larry",
    "TRAINA Anastasia": "traina-anastasia",
    "TRAINA Jose": "traina-jose",
    "TRAINER David": "trainer-david",
    "TRAINOR Kay": "trainor-kay",
    "TRAINOR Michael": "trainor-michael",
    "TRAINOR JR Dennis": "trainor-jr-dennis",
    "TRAKAL Daniela": "trakal-daniela",
    "TRAKTMAN Peggy": "traktman-peggy",
    "TRAMBLEY Estela Portillo": "trambley-estela-portillo",
    "TRAN Huu": "tran-huu",
    "TRAN Lan": "tran-lan",
    "TRAN Steven": "tran-steven",
    "TRAN Trieu": "tran-trieu",
    "TRANDAFIR Claudiu": "trandafir-claudiu",
    "TRANEN Jan": "tranen-jan",
    "TRANSFER THEATRE ": "transfer-theatre",
    "TRANSPORT THEATRE COMPANY ": "transport-theatre-company",
    "TRANTER Nigel": "tranter-nigel",
    "TRAPANI Sal": "trapani-sal",
    "TRAPNELL Nathan": "trapnell-nathan",
    "TRAPP Alison": "trapp-alison",
    "TRAPPER John Patrick": "trapper-john-patrick",
    "TRASH VAUDEVILLE ": "trash-vaudeville",
    "TRASK Josh Alan": "trask-josh-alan",
    "TRASK Larry": "trask-larry",
    "TRASK W R": "trask-w-r",
    "TRASLER Damian": "trasler-damian",
    "TRASS Vel": "trass-vel",
    "TRAUB Wayn": "traub-wayn",
    "TRAUBE Lucy": "traube-lucy",
    "TRAUSCH Monica": "trausch-monica",
    "TRAUSCH Susan": "trausch-susan",
    "TRAUT Karyn": "traut-karyn",
    "TRAV S D ": "trav-s-d",
    "TRAVELLING JEWISH THEATRE ": "travelling-jewish-theatre",
    "TRAVELLING LIGHT THEATRE COMPANY ": "travelling-light-theatre-company",
    "TRAVERS Alex": "travers-alex",
    "TRAVERS Ben": "travers-ben",
    "TRAVERS Brian": "travers-brian",
    "TRAVERS Hugh": "travers-hugh",
    "TRAVERS Joseph": "travers-joseph",
    "TRAVERS Martin": "travers-martin",
    "TRAVERSE Lans": "traverse-lans",
    "TRAVIS Bayla": "travis-bayla",
    "TRAVIS Bernie": "travis-bernie",
    "TRAVIS Bethani": "travis-bethani",
    "TRAVIS Greg": "travis-greg",
    "TRAVIS John": "travis-john",
    "TRAVIS Mandy": "travis-mandy",
    "TRAVIS Mark": "travis-mark",
    "TRAVIS Sarah": "travis-sarah",
    "TRAVIS Tara": "travis-tara",
    "TRAWICK-SMITH Ben": "trawick-smith-ben",
    "TRAYERS Linda": "trayers-linda",
    "TRAYLOR Gene": "traylor-gene",
    "TRAYNOR Billie": "traynor-billie",
    "TRAYNOR Joseph": "traynor-joseph",
    "TREACHER Graham": "treacher-graham",
    "TREACY Stephen Delos": "treacy-stephen-delos",
    "TREADWAY Amber": "treadway-amber",
    "TREADWELL Caroline": "treadwell-caroline",
    "TREADWELL Sophie": "treadwell-sophie",
    "TREANOR Tim": "treanor-tim",
    "TREASE Geoffrey": "trease-geoffrey",
    "TREAYS Jem": "treays-jem",
    "TREBOR-LANG Robert": "trebor-lang-robert",
    "TREDINNICK Miles": "tredinnick-miles",
    "TREE E Wayne": "tree-e-wayne",
    "TREE SHADOW THEATRE ": "tree-shadow-theatre",
    "TREEM Sarah": "treem-sarah",
    "TREEN Joe": "treen-joe",
    "TREGANZA Neil": "treganza-neil",
    "TREGENNA Catherine": "tregenna-catherine",
    "TREGENNA Jan": "tregenna-jan",
    "TREGLOAN Anna": "tregloan-anna",
    "TREHY Jody": "trehy-jody",
    "TREIBER Linda Lenzen": "treiber-linda-lenzen",
    "TREISCHMANN Catherine": "treischmann-catherine",
    "TREJOS Sandra": "trejos-sandra",
    "TRELEAVEN Lou": "treleaven-lou",
    "TRELLING Ursala": "trelling-ursala",
    "TREMAIN David": "tremain-david",
    "TREMAYNE Georgina": "tremayne-georgina",
    "TREMAYNE Hunter": "tremayne-hunter",
    "TREMBECKA Marysia": "trembecka-marysia",
    "TREMBLAY Brian": "tremblay-brian",
    "TREMBLAY Jason": "tremblay-jason",
    "TREMBLAY Jennifer": "tremblay-jennifer",
    "TREMBLAY Joey": "tremblay-joey",
    "TREMBLAY Larry": "tremblay-larry",
    "TREMBLAY Michel": "tremblay-michel",
    "TREMBLAY Renald": "tremblay-renald",
    "TREMLETT Peter": "tremlett-peter",
    "TRENCH Felix": "trench-felix",
    "TRENCH Zia": "trench-zia",
    "TRENIER Diane": "trenier-diane",
    "TRENT Jackie": "trent-jackie",
    "TRENTHAM Winifred": "trentham-winifred",
    "TRENTON Nadine": "trenton-nadine",
    "TREON Phil": "treon-phil",
    "TRESIZE Rachel": "tresize-rachel",
    "TRESLA Christopher": "tresla-christopher",
    "TRESSOR Alexander": "tressor-alexander",
    "TRESTER Michelle Marie": "trester-michelle-marie",
    "TRESTLE THEATRE ": "trestle-theatre",
    "TRESTON Lewis": "treston-lewis",
    "TRETHEWEY Natasha": "trethewey-natasha",
    "TRETIAKOFF David G": "tretiakoff-david-g",
    "TREUHAFT-ALI May": "treuhaft-ali-may",
    "TREVANNION Matthew": "trevannion-matthew",
    "TREVELLINI Giacondo": "trevellini-giacondo",
    "TREVELYAN Anthony": "trevelyan-anthony",
    "TREVELYAN Humphrey": "trevelyan-humphrey",
    "TREVELYAN R C": "trevelyan-r-c",
    "TREVENS Francine": "trevens-francine",
    "TREVENS Janine Nina": "trevens-janine-nina",
    "TREVERN Douglas": "trevern-douglas",
    "TREVES Simon": "treves-simon",
    "TREVILL Alastair": "trevill-alastair",
    "TREVINO Carlos": "trevino-carlos",
    "TREVINO Danusia": "trevino-danusia",
    "TREVIS Di": "trevis-di",
    "TREVOR Jon": "trevor-jon",
    "TREVOR Judith": "trevor-judith",
    "TREVOR Pat": "trevor-pat",
    "TREVOR William": "trevor-william",
    "TREYZ Russell": "treyz-russell",
    "TREZISE Keith": "trezise-keith",
    "TREZISE Rachel": "trezise-rachel",
    "TRIANA Jose": "triana-jose",
    "TRICKER Alan": "tricker-alan",
    "TRICKER Carole": "tricker-carole",
    "TRICKER George": "tricker-george",
    "TRICKSTER PRODUCTIONS ": "trickster-productions",
    "TRICKSTER THEATRE CO ": "trickster-theatre-co",
    "TRIDON Andre": "tridon-andre",
    "TRIESCHMANN Catherine": "trieschmann-catherine",
    "TRIESCHMANN Werner": "trieschmann-werner",
    "TRIFFITT Iain": "triffitt-iain",
    "TRIFKOVIC Nela": "trifkovic-nela",
    "TRIFONOV Yuri": "trifonov-yuri",
    "TRIGG John": "trigg-john",
    "TRIGGS Jason": "triggs-jason",
    "TRIGWELL-JONES Amy": "trigwell-jones-amy",
    "TRIGWELL-JONES Tony": "trigwell-jones-tony",
    "TRIKHA Rishi": "trikha-rishi",
    "TRIMMER Jon": "trimmer-jon",
    "TRINGHAM Annette": "tringham-annette",
    "TRINGHAM David": "tringham-david",
    "TRIPATHI Shalini": "tripathi-shalini",
    "TRIPE Robert": "tripe-robert",
    "TRIPICIAN Joe": "tripician-joe",
    "TRIPLE SHADOW ": "triple-shadow",
    "TRIPLETT Lori Lee": "triplett-lori-lee",
    "TRIPLETT William": "triplett-william",
    "TRIPP Ayasha": "tripp-ayasha",
    "TRIPP Miles": "tripp-miles",
    "TRIPP Peter": "tripp-peter",
    "TRIPPINI Roberto": "trippini-roberto",
    "TRISTAN Dorothy": "tristan-dorothy",
    "TRISTER Steve R": "trister-steve-r",
    "TRISTRAM David": "tristram-david",
    "TROCCHI Alexander": "trocchi-alexander",
    "TROCHIM Dennis": "trochim-dennis",
    "TROLI Tad": "troli-tad",
    "TROLL Bradley": "troll-bradley",
    "TRONE A L": "trone-a-l",
    "TRONES John": "trones-john",
    "TROOB Danny": "troob-danny",
    "TROOP Robert": "troop-robert",
    "TROOP Steve": "troop-steve",
    "TROOST Julie": "troost-julie",
    "TROOST Neil": "troost-neil",
    "TROOST Scott": "troost-scott",
    "TROPF Ralph": "tropf-ralph",
    "TROPICANA Carmelita": "tropicana-carmelita",
    "TROST Bastian": "trost-bastian",
    "TROTT F H": "trott-f-h",
    "TROTT Harry": "trott-harry",
    "TROTT Karen": "trott-karen",
    "TROTTER Carla": "trotter-carla",
    "TROTTER Catharine": "trotter-catharine",
    "TROTTER David": "trotter-david",
    "TROUBADOUR THEATER COMPANY ": "troubadour-theater-company",
    "TROUBLE AND STRIFE ": "trouble-and-strife",
    "TROUILLE Clovis": "trouille-clovis",
    "TROUNSON Kylie": "trounson-kylie",
    "TROUP Cynthia": "troup-cynthia",
    "TROUSDALE Donna": "trousdale-donna",
    "TROUT Steve": "trout-steve",
    "TROUTON David": "trouton-david",
    "TROW Eugenie": "trow-eugenie",
    "TROW George W S": "trow-george-w-s",
    "TROW Jack": "trow-jack",
    "TROWBRIDGE Dylan": "trowbridge-dylan",
    "TROWER Alison": "trower-alison",
    "TROY Hector": "troy-hector",
    "TROY Jonathan": "troy-jonathan",
    "TROY Mark": "troy-mark",
    "TROYANO Ela": "troyano-ela",
    "TRUAX James": "truax-james",
    "TRUBRIDGE Sam": "trubridge-sam",
    "TRUBY Angela": "truby-angela",
    "TRUDEAU Garry": "trudeau-garry",
    "TRUDELL David": "trudell-david",
    "TRUDELL Hilary": "trudell-hilary",
    "TRUDELLE Jeremy": "trudelle-jeremy",
    "TRUELOVE Gayann": "truelove-gayann",
    "TRUEMAN Brian": "trueman-brian",
    "TRUESDALE Tad": "truesdale-tad",
    "TRUITT Sara": "truitt-sara",
    "TRUJILLO Dan": "trujillo-dan",
    "TRULES Eric": "trules-eric",
    "TRULL Lee": "trull-lee",
    "TRULL Sylvia Riojas": "trull-sylvia-riojas",
    "TRULL Tommy": "trull-tommy",
    "TRUMAN Jill": "truman-jill",
    "TRUMBO Christopher": "trumbo-christopher",
    "TRUMBO Dalton": "trumbo-dalton",
    "TRUMBULL Matthew": "trumbull-matthew",
    "TRUNK Jonny": "trunk-jonny",
    "TRUPIA Paul": "trupia-paul",
    "TRUSCOTT Cristal Chanelle": "truscott-cristal-chanelle",
    "TRUSCOTT Julia": "truscott-julia",
    "TRUSITS Marie": "trusits-marie",
    "TRUSKINOFF David": "truskinoff-david",
    "TRUSS Jan": "truss-jan",
    "TRUSS Lynne": "truss-lynne",
    "TRUSSELL Paul": "trussell-paul",
    "TRUYTS Luk": "truyts-luk",
    "TRYKY Cheryl": "tryky-cheryl",
    "TRYPANIS C A": "trypanis-c-a",
    "TRZCINSKI Danielle": "trzcinski-danielle",
    "TRZCINSKI Edmund": "trzcinski-edmund",
    "TRZEBINSKI Andrzej": "trzebinski-andrzej"
  }
};