export default {
  "metadata": {
    "results": 141,
    "timeStamp": "2025-12-05T21:31:48.917Z",
    "url": "https://www.doollee.com/PlaywrightsU/U_playwrights_a-z.php"
  },
  "authors": {
    "UBANS Maris U": "ubans-maris-u",
    "UCAN Camille": "ucan-camille",
    "UCHIMA Keith": "uchima-keith",
    "UDALL Joe": "udall-joe",
    "UDDENBERG Erik": "uddenberg-erik",
    "UDELL Peter": "udell-peter",
    "UDKO Zach": "udko-zach",
    "UDOFF Yale": "udoff-yale",
    "UDOFIA Mfoniso": "udofia-mfoniso",
    "UDY Rebecca": "udy-rebecca",
    "UEBERROTH O G": "ueberroth-o-g",
    "UEDA Ikko": "ueda-ikko",
    "UEDA Mari": "ueda-mari",
    "UENO Watoku": "ueno-watoku",
    "UERFELT Hanna": "uerfelt-hanna",
    "UGURLU Zishan": "ugurlu-zishan",
    "UHDE Milan": "uhde-milan",
    "UHEHARA Denise": "uhehara-denise",
    "UHLAR Blaho": "uhlar-blaho",
    "UHLICH Doris": "uhlich-doris",
    "UHRY Alfred": "uhry-alfred",
    "UJIMA Leroy 'steppin-Razor'": "ujima-leroy",
    "UJVARI Milan": "ujvari-milan",
    "ULARU Nic": "ularu-nic",
    "ULFAN Greg": "ulfan-greg",
    "ULFANE Janine": "ulfane-janine",
    "ULLAH Aladdin": "ullah-aladdin",
    "ULLIAN Peter": "ullian-peter",
    "ULLMAN Marvin": "ullman-marvin",
    "ULLOM Shirley": "ullom-shirley",
    "ULLOTH Christopher": "ulloth-christopher",
    "ULRICH Dave": "ulrich-dave",
    "ULRICH Matt": "ulrich-matt",
    "ULRICH Maureen": "ulrich-maureen",
    "ULTZ ": "ultz",
    "ULUDAG Ugur": "uludag-ugur",
    "ULVAEUS Bjorn": "ulvaeus-bjorn",
    "ULZ Eva": "ulz-eva",
    "U-MAN ZOO ": "u-man-zoo",
    "UMANSKY Kaye": "umansky-kaye",
    "UMBILICAL BROTHERS, THE ": "umbilical-brothers-the",
    "UMBLE Rodney": "umble-rodney",
    "UME GROUP ": "ume-group",
    "UMESS Michael": "umess-michael",
    "UMLAUT SEVEN ": "umlaut-seven",
    "UMO ENSEMBLE ": "umo-ensemble",
    "UNASA Lailani": "unasa-lailani",
    "UNCANNY THEATRE ": "uncanny-theatre",
    "UNCOMMON TIME THEATER CO ": "uncommon-time-theater",
    "UNDERCURRENT ": "undercurrent",
    "UNDERFOOT THEATRE ": "underfoot-theatre",
    "UNDERHILL Geoffrey": "underhill-geoffrey",
    "UNDERHILL Jeff": "underhill-jeff",
    "UNDERHILL John Garrett": "underhill-john-garrett",
    "UNDERWOOD Dorothy": "underwood-dorothy",
    "UNDERWOOD Franklin": "underwood-franklin",
    "UNDERWOOD Larry": "underwood-larry",
    "UNDERWOOD M Lark": "underwood-m-lark",
    "UNDERWOOD Natalie": "underwood-natalie",
    "UNDERWOOD Nick": "underwood-nick",
    "UNDERWOOD Steve": "underwood-steve",
    "UNDERWOOD Temar": "underwood-temar",
    "UNDERWOOD-LEE Emily": "underwood-lee-emily",
    "UNEL Sinan": "unel-sinan",
    "UNGAR Jeff": "ungar-jeff",
    "UNGER Lisa": "unger-lisa",
    "UNGER Robert": "unger-robert",
    "UNGLAUB Leonard": "unglaub-leonard",
    "UNHIDDEN COLLECTIVE ": "unhidden-collective",
    "UNINVITED GUESTS ": "uninvited-guests",
    "UNITEC THIRD YEAR GRAD STUDENTS ": "unitec-third-year-grad-students",
    "UNITY THEATRE, THE ": "unity-theatre",
    "UNIVERSES ": "universes",
    "UNLIMITED THEATRE ": "unlimited-theatre",
    "UNPACKED THEATRE COMPANY ": "unpacked-theatre-company",
    "UNSWORTH Guy": "unsworth-guy",
    "UNTER Carole": "unter-carole",
    "UNTERBERG Andrew": "unterberg-andrew",
    "UNTITLED THEATRICS ": "untitled-theatrics",
    "UNUETA Enrique": "unueta-enrique",
    "UNWIN Paul": "unwin-paul",
    "UNWIN Sophie": "unwin-sophie",
    "UNWIN Stephen": "unwin-stephen",
    "UNWINOLD Paul": "unwinold-paul",
    "UPCHURCH Reenie": "upchurch-reenie",
    "UPDIKE John": "updike-john",
    "UPRICHARD Heather": "uprichard-heather",
    "UPSHER David": "upsher-david",
    "UPTON Andrew": "upton-andrew",
    "UPTON Jane": "upton-jane",
    "UPTON John": "upton-john",
    "UPTON Judy": "upton-judy",
    "UPWARD Michael": "upward-michael",
    "UPWARD Penelope": "upward-penelope",
    "URALE Makerita": "urale-makerita",
    "URANITSCH Kajetan": "uranitsch-kajetan",
    "URBAN Ken": "urban-ken",
    "URBAN THEATRE (HOUSTON, TEXAS) ": "urban-theatre",
    "URBINATI Rob": "urbinati-rob",
    "URCH Chris": "urch-chris",
    "URE Jean": "ure-jean",
    "URE Joan": "ure-joan",
    "URE Roslyn": "ure-roslyn",
    "UREMOVICH Matt": "uremovich-matt",
    "UREN Rhona": "uren-rhona",
    "UREN Tim": "uren-tim",
    "URFER Fred": "urfer-fred",
    "URIE Tom": "urie-tom",
    "URIS Leon": "uris-leon",
    "URIST Rachel": "urist-rachel",
    "URNOV Yury": "urnov-yury",
    "URNSONE Lou": "urnsone-lou",
    "URQUART Mark": "urquart-mark",
    "URQUART Ruth": "urquart-ruth",
    "URQUHART Gordon": "urquhart-gordon",
    "URQUHART John": "urquhart-john",
    "URQUHART Macgregor": "urquhart-macgregor",
    "URQUHART Philippa": "urquhart-philippa",
    "URSELL Geoffrey": "ursell-geoffrey",
    "URSILLO Bianca J": "ursillo-bianca-j",
    "URUETA Enrique": "urueta-enrique",
    "URWIN Claire": "urwin-claire",
    "URZUA David Arancibia": "urzua-david-arancibia",
    "USCHER Mitchell": "uscher-mitchell",
    "USDEN Adam": "usden-adam",
    "USHER Edward": "usher-edward",
    "USHER Sabrina": "usher-sabrina",
    "USHER Simon": "usher-simon",
    "USIGLI Rodolfo": "usigli-rodolfo",
    "USNER David": "usner-david",
    "USTINOV Peter": "ustinov-peter",
    "UTTER Andrew": "utter-andrew",
    "UTTERBACK Neal": "utterback-neal",
    "UTTLEY Jemma": "uttley-jemma",
    "UTTON Pip": "utton-pip",
    "UVA Anthony": "uva-anthony",
    "UWAZURIKE P Chudi": "uwazurike-p-chudi",
    "UYEHARA Denise": "uyehara-denise",
    "UYGUN Fatima": "uygun-fatima",
    "UYS Pieter Dirk": "uys-pieter-dirk",
    "UZURI Imani": "uzuri-imani"
  }
};