export default {
  "metadata": {
    "results": 1265,
    "timeStamp": "2025-12-05T21:32:05.925Z",
    "url": "https://www.doollee.com/PlaywrightsW/W_playwrights_a-f.php"
  },
  "authors": {
    "WAAGE Kirjan": "waage-kirjan",
    "WAAS Tommy": "waas-tommy",
    "WABLE Kesav M": "wable-kesav-m",
    "WACHOLTZ Michael": "wacholtz-michael",
    "WACHOVSKY Roderic": "wachovsky-roderic",
    "WACHTER Adam": "wachter-adam",
    "WACK Joe": "wack-joe",
    "WACKLER Rebecca": "wackler-rebecca",
    "WADDELL George": "waddell-george",
    "WADDEN Patrick": "wadden-patrick",
    "WADDINGHAM Lee": "waddingham-lee",
    "WADDINGTON James": "waddington-james",
    "WADDINGTON Martin": "waddington-martin",
    "WADDINGTON Rona": "waddington-rona",
    "WADDINGTON-FEATHER John": "waddington-feather-john",
    "WADDS Gillian M": "wadds-gillian-m",
    "WADE Bryan": "wade-bryan",
    "WADE Jerry": "wade-jerry",
    "WADE Joseph": "wade-joseph",
    "WADE Kevin": "wade-kevin",
    "WADE Laura": "wade-laura",
    "WADE Leslie Anne": "wade-leslie-anne",
    "WADE Lezlie Faith": "wade-lezlie-faith",
    "WADE Terry": "wade-terry",
    "WADE William": "wade-william",
    "WADHAM Leon": "wadham-leon",
    "WADLER Michael David": "wadler-michael-david",
    "WADLOW Trevor": "wadlow-trevor",
    "WADSWORTH Andrew C": "wadsworth-andrew-c",
    "WADSWORTH Kimberly": "wadsworth-kimberly",
    "WADSWORTH Michael": "wadsworth-michael",
    "WADSWORTH Stephen": "wadsworth-stephen",
    "WADUD Ali": "wadud-ali",
    "WAECHTER Frederick K": "waechter-frederick-k",
    "WAECHTER Joe": "waechter-joe",
    "WAEDEKIN James D": "waedekin-james-d",
    "WAFER Jenny": "wafer-jenny",
    "WAGENER T L": "wagener-t-l",
    "WAGENHEIM Kal": "wagenheim-kal",
    "WAGER Douglas C": "wager-douglas-c",
    "WAGG Jeremy": "wagg-jeremy",
    "WAGG Michael": "wagg-michael",
    "WAGGONER Joel": "waggoner-joel",
    "WAGGONER Miles": "waggoner-miles",
    "WAGGOTT Paul": "waggott-paul",
    "WAGNER Colleen": "wagner-colleen",
    "WAGNER Emma": "wagner-emma",
    "WAGNER Heinrich Leopold": "wagner-heinrich-leopold",
    "WAGNER Jane": "wagner-jane",
    "WAGNER Martin": "wagner-martin",
    "WAGNER Mary Michael": "wagner-mary-michael",
    "WAGNER Nick": "wagner-nick",
    "WAGNER Paula": "wagner-paula",
    "WAGNER Robin": "wagner-robin",
    "WAGNER Scott Patrick": "wagner-scott-patrick",
    "WAGNER Steven": "wagner-steven",
    "WAGNER T Brian": "wagner-t-brian",
    "WAGNER Warren": "wagner-warren",
    "WAGSTAFF Rachel": "wagstaff-rachel",
    "WAHL Joan": "wahl-joan",
    "WAHL Rachel": "wahl-rachel",
    "WAIGHT Quintin": "waight-quintin",
    "WAIN Daniel": "wain-daniel",
    "WAIN David": "wain-david",
    "WAIN John": "wain-john",
    "WAIN Nathalie": "wain-nathalie",
    "WAINE Harry": "waine-harry",
    "WAINER Kit": "wainer-kit",
    "WAINWRIGHT Jane": "wainwright-jane",
    "WAINWRIGHT Jeffrey": "wainwright-jeffrey",
    "WAINWRIGHT Nicholas": "wainwright-nicholas",
    "WAINWRIGHT Tom": "wainwright-tom",
    "WAISFELD Natasha": "waisfeld-natasha",
    "WAISMAN Carol": "waisman-carol",
    "WAIT Keith": "wait-keith",
    "WAITE Francesca": "waite-francesca",
    "WAITE Paul": "waite-paul",
    "WAITE Robyn": "waite-robyn",
    "WAITES Aline": "waites-aline",
    "WAITES Thomas G": "waites-thomas-g",
    "WAITE-SMITH Cicely": "waite-smith-cicely",
    "WAITS Richard E": "waits-richard-e",
    "WAITS Tom": "waits-tom",
    "WAITT Colin": "waitt-colin",
    "WAJSWOL Sharon": "wajswol-sharon",
    "WAKE Brian Hiroshi": "wake-brian-hiroshi",
    "WAKE Clive": "wake-clive",
    "WAKE David": "wake-david",
    "WAKEFIELD Colin": "wakefield-colin",
    "WAKEFIELD Jaques": "wakefield-jaques",
    "WAKEFIELD Lou": "wakefield-lou",
    "WAKELAM Stephen": "wakelam-stephen",
    "WAKELY Joshua": "wakely-joshua",
    "WAKEMAN Alan": "wakeman-alan",
    "WAKENSHAW Trygve": "wakenshaw-trygve",
    "WAKKA WAKKA ": "wakka-wakka",
    "WAKLEY Rosie": "wakley-rosie",
    "WAKRIM Hassan": "wakrim-hassan",
    "WAKULIK Anna": "wakulik-anna",
    "WALAT Kathryn": "walat-kathryn",
    "WALBECK Sean": "walbeck-sean",
    "WALBERT Kate": "walbert-kate",
    "WALBRIDGE David": "walbridge-david",
    "WALCH Gay": "walch-gay",
    "WALCH John": "walch-john",
    "WALCOTT Brenda": "walcott-brenda",
    "WALCOTT Derek": "walcott-derek",
    "WALCOTT Roderick": "walcott-roderick",
    "WALCUTT Judith": "walcutt-judith",
    "WALCZAK Michal": "walczak-michal",
    "WALD Malvin": "wald-malvin",
    "WALDAUER Kim": "waldauer-kim",
    "WALDEMAR JR Eric C": "waldemar-jr-eric-c",
    "WALDEN Josh": "walden-josh",
    "WALDEN Lilly": "walden-lilly",
    "WALDEN Lois": "walden-lois",
    "WALDEN Neil": "walden-neil",
    "WALDEN Stanley": "walden-stanley",
    "WALDEN William": "walden-william",
    "WALDINGER Jesse": "waldinger-jesse",
    "WALDMAN Ann": "waldman-ann",
    "WALDMAN Ayelet": "waldman-ayelet",
    "WALDMAN Robert": "waldman-robert",
    "WALDO Terry": "waldo-terry",
    "WALDRON Glenn": "waldron-glenn",
    "WALDRON Michael J": "waldron-michael-j",
    "WALDROP Mark": "waldrop-mark",
    "WALDSCHMIDT Andy": "waldschmidt-andy",
    "WALE Andrew": "wale-andrew",
    "WALE Mark": "wale-mark",
    "WALE Terry": "wale-terry",
    "WALES Robert": "wales-robert",
    "WALEY Arthur": "waley-arthur",
    "WALIDAH Hanifah": "walidah-hanifah",
    "WALKE David": "walke-david",
    "WALKEN Christopher": "walken-christopher",
    "WALKER Amanda": "walker-amanda",
    "WALKER Andy": "walker-andy",
    "WALKER Aubrey Danver": "walker-aubrey-danver",
    "WALKER Brandon": "walker-brandon",
    "WALKER Brandy": "walker-brandy",
    "WALKER Brian": "walker-brian",
    "WALKER Bruce": "walker-bruce",
    "WALKER Carol I": "walker-carol-i",
    "WALKER Cecilia Brie": "walker-cecilia-brie",
    "WALKER Celeste Bedford": "walker-celeste-bedford",
    "WALKER Charles R": "walker-charles-r",
    "WALKER Che": "walker-che",
    "WALKER Chet": "walker-chet",
    "WALKER Chris": "walker-chris",
    "WALKER Craig": "walker-craig",
    "WALKER David": "walker-david",
    "WALKER Dolores": "walker-dolores",
    "WALKER Dominic": "walker-dominic",
    "WALKER Evan": "walker-evan",
    "WALKER Fai": "walker-fai",
    "WALKER Fred": "walker-fred",
    "WALKER Gary": "walker-gary",
    "WALKER George F": "walker-george-f",
    "WALKER George Leitch": "walker-george-leitch",
    "WALKER Gerald": "walker-gerald",
    "WALKER Graham": "walker-graham",
    "WALKER Hadleigh": "walker-hadleigh",
    "WALKER Hannah Jane": "walker-hannah-jane",
    "WALKER Helen": "walker-helen",
    "WALKER Ian": "walker-ian",
    "WALKER James (1)": "walker-james-1",
    "WALKER James (2)": "walker-james-2",
    "WALKER Jessica": "walker-jessica",
    "WALKER John": "walker-john",
    "WALKER Johnnie": "walker-johnnie",
    "WALKER Jonelle": "walker-jonelle",
    "WALKER Joseph A": "walker-joseph-a",
    "WALKER June": "walker-june",
    "WALKER Leomi": "walker-leomi",
    "WALKER Luke": "walker-luke",
    "WALKER M": "walker-m",
    "WALKER M Burke": "walker-m-burke",
    "WALKER Margret": "walker-margret",
    "WALKER Mark": "walker-mark",
    "WALKER Martin": "walker-martin",
    "WALKER Maurice": "walker-maurice",
    "WALKER Melinda": "walker-melinda",
    "WALKER Michael": "walker-michael",
    "WALKER Michael Esdaile": "walker-michael-esdaile",
    "WALKER Michael I": "walker-michael-i",
    "WALKER Michael P": "walker-michael-p",
    "WALKER Michael Patrick": "walker-michael-patrick",
    "WALKER Michael Thomas": "walker-michael-thomas",
    "WALKER Neil": "walker-neil",
    "WALKER Nick": "walker-nick",
    "WALKER Nick (1)": "walker-nick-1",
    "WALKER Pattric": "walker-pattric",
    "WALKER Paul (1)": "walker-paul-1",
    "WALKER Paul (2)": "walker-paul-2",
    "WALKER Peter": "walker-peter",
    "WALKER Peter Lancaster": "walker-peter-lancaster",
    "WALKER Phil": "walker-phil",
    "WALKER Rebecca": "walker-rebecca",
    "WALKER Richard": "walker-richard",
    "WALKER Robert": "walker-robert",
    "WALKER Robert (1)": "walker-robert-1",
    "WALKER Scot": "walker-scot",
    "WALKER Steffi": "walker-steffi",
    "WALKER Stephanie": "walker-stephanie",
    "WALKER Stephanie Allison": "walker-stephanie-allison",
    "WALKER Steven Luke": "walker-steven-luke",
    "WALKER Stuart": "walker-stuart",
    "WALKER Sullivan": "walker-sullivan",
    "WALKER T C": "walker-t-c",
    "WALKER Tess": "walker-tess",
    "WALKER Trevor": "walker-trevor",
    "WALKER Wes": "walker-wes",
    "WALKER William": "walker-william",
    "WALKER William P Scot": "walker-william-p-scot",
    "WALKER-BLACK James": "walker-black-james",
    "WALKER-PEARSON Jack": "walker-pearson-jack",
    "WALKES W R": "walkes-w-r",
    "WALKHAM Kit": "walkham-kit",
    "WALKINSHAW Janette": "walkinshaw-janette",
    "WALL Alexandre": "wall-alexandre",
    "WALL Charles Heron": "wall-charles-heron",
    "WALL Christopher": "wall-christopher",
    "WALL Drew": "wall-drew",
    "WALL John C": "wall-john-c",
    "WALL Kay": "wall-kay",
    "WALL Max": "wall-max",
    "WALL Michael": "wall-michael",
    "WALL Mick": "wall-mick",
    "WALL Richard": "wall-richard",
    "WALL Todd": "wall-todd",
    "WALLABOUT Marcy": "wallabout-marcy",
    "WALLACE Aaron Anthony": "wallace-aaron-anthony",
    "WALLACE Adam": "wallace-adam",
    "WALLACE Art": "wallace-art",
    "WALLACE Basil A": "wallace-basil-a",
    "WALLACE Bethany": "wallace-bethany",
    "WALLACE Chris": "wallace-chris",
    "WALLACE Dale": "wallace-dale",
    "WALLACE Deborah": "wallace-deborah",
    "WALLACE Edgar": "wallace-edgar",
    "WALLACE G L": "wallace-g-l",
    "WALLACE Ian": "wallace-ian",
    "WALLACE Joan": "wallace-joan",
    "WALLACE John": "wallace-john",
    "WALLACE Jonathan": "wallace-jonathan",
    "WALLACE Joseph": "wallace-joseph",
    "WALLACE May": "wallace-may",
    "WALLACE Meri": "wallace-meri",
    "WALLACE Michael": "wallace-michael",
    "WALLACE Michelle": "wallace-michelle",
    "WALLACE Naomi": "wallace-naomi",
    "WALLACE Robert": "wallace-robert",
    "WALLACE Rudy": "wallace-rudy",
    "WALLACE Wendy": "wallace-wendy",
    "WALLACE-CRABBE Chris": "wallace-crabbe-chris",
    "WALLACH Eric": "wallach-eric",
    "WALLACH Ira": "wallach-ira",
    "WALLACH Mike": "wallach-mike",
    "WALLANCE David": "wallance-david",
    "WALLBANK Anna": "wallbank-anna",
    "WALLBANK Bob": "wallbank-bob",
    "WALLER Amy": "waller-amy",
    "WALLER Catherine": "waller-catherine",
    "WALLER G Hobson": "waller-g-hobson",
    "WALLER-BRIDGE Phoebe": "waller-bridge-phoebe",
    "WALLERSTEIN Michael": "wallerstein-michael",
    "WALLET James": "wallet-james",
    "WALLEY Arthur": "walley-arthur",
    "WALLEY Elizabeth": "walley-elizabeth",
    "WALLEY Richard": "walley-richard",
    "WALLIAMS David": "walliams-david",
    "WALLIN Samuel": "wallin-samuel",
    "WALLING Michael": "walling-michael",
    "WALLING Nisha": "walling-nisha",
    "WALLINGER Louise": "wallinger-louise",
    "WALLINGER Todd": "wallinger-todd",
    "WALLINGTON Laim": "wallington-laim",
    "WALLIS Cedric": "wallis-cedric",
    "WALLIS Daryl": "wallis-daryl",
    "WALLIS Gib": "wallis-gib",
    "WALLIS Ruth": "wallis-ruth",
    "WALLIS Shiv": "wallis-shiv",
    "WALLIS Steve": "wallis-steve",
    "WALLNER Melanie": "wallner-melanie",
    "WALLOCH Greg": "walloch-greg",
    "WALLOP Douglass": "wallop-douglass",
    "WALLOWITCH John": "wallowitch-john",
    "WALLS Bill": "walls-bill",
    "WALLS Erin": "walls-erin",
    "WALLS Joycelyn": "walls-joycelyn",
    "WALLWEIN Louise": "wallwein-louise",
    "WALLY David": "wally-david",
    "WALMSLEY Dewdrop": "walmsley-dewdrop",
    "WALMSLEY Kyle": "walmsley-kyle",
    "WALMSLEY Tom": "walmsley-tom",
    "WALPOLE Horace": "walpole-horace",
    "WALPUR Howard": "walpur-howard",
    "WALSER Martin": "walser-martin",
    "WALSER Theresia": "walser-theresia",
    "WALSH Addie": "walsh-addie",
    "WALSH Angela": "walsh-angela",
    "WALSH Ashley": "walsh-ashley",
    "WALSH Brian": "walsh-brian",
    "WALSH Catherine": "walsh-catherine",
    "WALSH Christopher M": "walsh-christopher-m",
    "WALSH Daniel": "walsh-daniel",
    "WALSH Denise": "walsh-denise",
    "WALSH Dermot": "walsh-dermot",
    "WALSH Des": "walsh-des",
    "WALSH Dick": "walsh-dick",
    "WALSH Edward J": "walsh-edward-j",
    "WALSH Enda": "walsh-enda",
    "WALSH Fiona": "walsh-fiona",
    "WALSH Forbes": "walsh-forbes",
    "WALSH Frances": "walsh-frances",
    "WALSH J K": "walsh-j-k",
    "WALSH Joe": "walsh-joe",
    "WALSH Keliher": "walsh-keliher",
    "WALSH Kenneth": "walsh-kenneth",
    "WALSH Kevin": "walsh-kevin",
    "WALSH Kylie": "walsh-kylie",
    "WALSH Lauren": "walsh-lauren",
    "WALSH Luella": "walsh-luella",
    "WALSH Malachy": "walsh-malachy",
    "WALSH Malia": "walsh-malia",
    "WALSH Mary Jane": "walsh-mary-jane",
    "WALSH Matt": "walsh-matt",
    "WALSH Megan": "walsh-megan",
    "WALSH Michael": "walsh-michael",
    "WALSH P Adam": "walsh-p-adam",
    "WALSH P J": "walsh-p-j",
    "WALSH Patrick": "walsh-patrick",
    "WALSH Paul": "walsh-paul",
    "WALSH Rebecca": "walsh-rebecca",
    "WALSH Ronnie": "walsh-ronnie",
    "WALSH Roseleen": "walsh-roseleen",
    "WALSH Sean": "walsh-sean",
    "WALSH Shelia": "walsh-shelia",
    "WALSH Stanley": "walsh-stanley",
    "WALSH Stephen": "walsh-stephen",
    "WALSH T J": "walsh-t-j",
    "WALSH Terrence W": "walsh-terrence-w",
    "WALSH Tom": "walsh-tom",
    "WALSHALSH Sarah": "walshalsh-sarah",
    "WALSHE David": "walshe-david",
    "WALSHE Dolores": "walshe-dolores",
    "WALSHE Stephen": "walshe-stephen",
    "WALSHE Vivienne": "walshe-vivienne",
    "WALSH-HARRINGTON Sophie": "walsh-harrington-sophie",
    "WALSOE-ENGEL Ingrid": "walsoe-engel-ingrid",
    "WALSTON Mark": "walston-mark",
    "WALTER Alice": "walter-alice",
    "WALTER Eugene": "walter-eugene",
    "WALTER Kristin": "walter-kristin",
    "WALTER Lisa": "walter-lisa",
    "WALTER Madeline": "walter-madeline",
    "WALTER Stephanie": "walter-stephanie",
    "WALTER Wilfrid": "walter-wilfrid",
    "WALTERS Adam": "walters-adam",
    "WALTERS Anne": "walters-anne",
    "WALTERS Brian": "walters-brian",
    "WALTERS Celeste": "walters-celeste",
    "WALTERS Chris": "walters-chris",
    "WALTERS Graham": "walters-graham",
    "WALTERS Howard": "walters-howard",
    "WALTERS Jess": "walters-jess",
    "WALTERS John": "walters-john",
    "WALTERS Leslie": "walters-leslie",
    "WALTERS Lucy": "walters-lucy",
    "WALTERS Steve": "walters-steve",
    "WALTERS Steven": "walters-steven",
    "WALTERS Steven Michael": "walters-steven-michael",
    "WALTERS Wendy S": "walters-wendy-s",
    "WALTIRE Ted": "waltire-ted",
    "WALTON Ali": "walton-ali",
    "WALTON Blake": "walton-blake",
    "WALTON Bob": "walton-bob",
    "WALTON Bradley": "walton-bradley",
    "WALTON Carmen": "walton-carmen",
    "WALTON Eric": "walton-eric",
    "WALTON Glen": "walton-glen",
    "WALTON J Michael": "walton-j-michael",
    "WALTON James": "walton-james",
    "WALTON Jim": "walton-jim",
    "WALTON John": "walton-john",
    "WALTON L J": "walton-l-j",
    "WALTON Rachael": "walton-rachael",
    "WALTON Tom": "walton-tom",
    "WALTOWER Earl": "waltower-earl",
    "WALUSCHKA Nina": "waluschka-nina",
    "WALWICZ Ania": "walwicz-ania",
    "WALWYN-GASTON Edie": "walwyn-gaston-edie",
    "WAMBERA Judith": "wambera-judith",
    "WAMPLER Claude": "wampler-claude",
    "WAMSER Shannon Michael": "wamser-shannon-michael",
    "WAN Choy Wai": "wan-choy-wai",
    "WAN Julia": "wan-julia",
    "WAND Kelly": "wand-kelly",
    "WAND Zosia": "wand-zosia",
    "WANDELL Joe": "wandell-joe",
    "WANDOR Michelene": "wandor-michelene",
    "WANDS Cynthia": "wands-cynthia",
    "WANG Ben": "wang-ben",
    "WANG Derrick": "wang-derrick",
    "WANG Holman": "wang-holman",
    "WANG Lucy": "wang-lucy",
    "WANG Nancy": "wang-nancy",
    "WANG Phil": "wang-phil",
    "WANG Xiaoli": "wang-xiaoli",
    "WANN Jim": "wann-jim",
    "WANNER Zukiswa": "wanner-zukiswa",
    "WANSHEL Jeff": "wanshel-jeff",
    "WANSLEY Sarah Elizabeth": "wansley-sarah-elizabeth",
    "WANZIE Michael": "wanzie-michael",
    "WAPP Bessie": "wapp-bessie",
    "WAPP Judy": "wapp-judy",
    "WAR THEATRE ": "war-theatre",
    "WARAKER D L": "waraker-d-l",
    "WARBECK Stephen": "warbeck-stephen",
    "WARBOYES Sally": "warboyes-sally",
    "WARBURTON Matthew": "warburton-matthew",
    "WARBURTON Nick": "warburton-nick",
    "WARBURTON Thomas": "warburton-thomas",
    "WARBUTON Richard": "warbuton-richard",
    "WARCHUS Matthew": "warchus-matthew",
    "WARD Alison Lynne": "ward-alison-lynne",
    "WARD Andrew": "ward-andrew",
    "WARD Angela": "ward-angela",
    "WARD Anna": "ward-anna",
    "WARD Annette": "ward-annette",
    "WARD Annie": "ward-annie",
    "WARD Beverly": "ward-beverly",
    "WARD Bradley": "ward-bradley",
    "WARD Brendan": "ward-brendan",
    "WARD Brendon Noel": "ward-brendon-noel",
    "WARD Bruce": "ward-bruce",
    "WARD Caroline": "ward-caroline",
    "WARD Charlie": "ward-charlie",
    "WARD Chris": "ward-chris",
    "WARD Christopher": "ward-christopher",
    "WARD Claudia": "ward-claudia",
    "WARD Colin C G N": "ward-colin-c-g-n",
    "WARD Daniel": "ward-daniel",
    "WARD Danielle": "ward-danielle",
    "WARD David": "ward-david",
    "WARD Dennis": "ward-dennis",
    "WARD Donald": "ward-donald",
    "WARD Douglas Turner": "ward-douglas-turner",
    "WARD Duncan": "ward-duncan",
    "WARD Edmund": "ward-edmund",
    "WARD Evelyn": "ward-evelyn",
    "WARD Francis": "ward-francis",
    "WARD Greg": "ward-greg",
    "WARD Jenny": "ward-jenny",
    "WARD Joe Patrick": "ward-joe-patrick",
    "WARD John": "ward-john",
    "WARD Jonathon": "ward-jonathon",
    "WARD Kirby": "ward-kirby",
    "WARD Kirk": "ward-kirk",
    "WARD Marjorie": "ward-marjorie",
    "WARD Mark": "ward-mark",
    "WARD Matthew": "ward-matthew",
    "WARD Milton Hood": "ward-milton-hood",
    "WARD Niall": "ward-niall",
    "WARD Nick": "ward-nick",
    "WARD Nick (1)": "ward-nick-1",
    "WARD Paul": "ward-paul",
    "WARD Philip": "ward-philip",
    "WARD R H": "ward-r-h",
    "WARD Richard": "ward-richard",
    "WARD Rob": "ward-rob",
    "WARD Ron": "ward-ron",
    "WARD Ruth": "ward-ruth",
    "WARD Sam": "ward-sam",
    "WARD Sheila": "ward-sheila",
    "WARD Simon": "ward-simon",
    "WARD Simon (1)": "ward-simon-1",
    "WARD Theodore": "ward-theodore",
    "WARD Thomas": "ward-thomas",
    "WARD Trisha": "ward-trisha",
    "WARD Val Gray": "ward-val-gray",
    "WARD Victoria": "ward-victoria",
    "WARD Wendy": "ward-wendy",
    "WARDELL Pam": "wardell-pam",
    "WARDIGO Nick": "wardigo-nick",
    "WARDLE Irving": "wardle-irving",
    "WARDLE John": "wardle-john",
    "WARDROBE James": "wardrobe-james",
    "WARDROBE ENSEMBLE ": "wardrobe-ensemble",
    "WARDROBE THEATRE ": "wardrobe-theatre-",
    "WARDROP Ewan": "wardrop-ewan",
    "WARDROP Jamie": "wardrop-jamie",
    "WARDROP Lewis": "wardrop-lewis",
    "WARD-THOMAS Tom": "ward-thomas-tom",
    "WARE Gerry": "ware-gerry",
    "WARE Harlan": "ware-harlan",
    "WARE Joan": "ware-joan",
    "WARE Kendra": "ware-kendra",
    "WARE Leon": "ware-leon",
    "WAREDEN Liv": "wareden-liv",
    "WAREN Mark": "waren-mark",
    "WAREN Richard": "waren-richard",
    "WARES Sacha": "wares-sacha",
    "WARGO Stephen": "wargo-stephen",
    "WARHOL Andy": "warhol-andy",
    "WARHURST M": "warhurst-m",
    "WARING Amanda": "waring-amanda",
    "WARING Barbara": "waring-barbara",
    "WARINGTON Robert": "warington-robert",
    "WARKENTIN Ellen": "warkentin-ellen",
    "WARKENTIN Veralyn": "warkentin-veralyn",
    "WARKENTINE Ellen": "warkentine-ellen",
    "WARLOCK Allen": "warlock-allen",
    "WARMAN Caroline": "warman-caroline",
    "WARMAN Evelyn": "warman-evelyn",
    "WARMFLASH Stuart": "warmflash-stuart",
    "WARNASCH Irving": "warnasch-irving",
    "WARNE Russell": "warne-russell",
    "WARNE Simon": "warne-simon",
    "WARNER Alan": "warner-alan",
    "WARNER Craig": "warner-craig",
    "WARNER Craig S": "warner-craig-s",
    "WARNER Deborah": "warner-deborah",
    "WARNER Francis": "warner-francis",
    "WARNER Jan": "warner-jan",
    "WARNER John Vincent": "warner-john-vincent",
    "WARNER Justin": "warner-justin",
    "WARNER Katy": "warner-katy",
    "WARNER Keziah": "warner-keziah",
    "WARNER Leo": "warner-leo",
    "WARNER Louise H": "warner-louise-h",
    "WARNER Marion": "warner-marion",
    "WARNER Matthew": "warner-matthew",
    "WARNER Michael": "warner-michael",
    "WARNER Victor": "warner-victor",
    "WARNOCK Allen": "warnock-allen",
    "WARNOCK Bill": "warnock-bill",
    "WARNOCK Bill (1)": "warnock-bill-1",
    "WARNOCK Colin": "warnock-colin",
    "WARNOCK Gwendolyn": "warnock-gwendolyn",
    "WARNOCK Kathleen": "warnock-kathleen",
    "WARR Jean": "warr-jean",
    "WARR Marilyn": "warr-marilyn",
    "WARR Michael": "warr-michael",
    "WARRACK David": "warrack-david",
    "WARREN Allan": "warren-allan",
    "WARREN Ann": "warren-ann",
    "WARREN Ben": "warren-ben",
    "WARREN Chandler": "warren-chandler",
    "WARREN Dianne": "warren-dianne",
    "WARREN F Brooke": "warren-f-brooke",
    "WARREN Frank": "warren-frank",
    "WARREN Gordon": "warren-gordon",
    "WARREN Harry": "warren-harry",
    "WARREN Jim": "warren-jim",
    "WARREN John": "warren-john",
    "WARREN Katie": "warren-katie",
    "WARREN Kyle": "warren-kyle",
    "WARREN Leslee": "warren-leslee",
    "WARREN Louise": "warren-louise",
    "WARREN Nick": "warren-nick",
    "WARREN Polly": "warren-polly",
    "WARREN Richard": "warren-richard",
    "WARREN Robert Penn": "warren-robert-penn",
    "WARREN Roger": "warren-roger",
    "WARREN Ryan": "warren-ryan",
    "WARREN Scott": "warren-scott",
    "WARREN Sloane": "warren-sloane",
    "WARREN Steve": "warren-steve",
    "WARREN Steven": "warren-steven",
    "WARRENDER Scott": "warrender-scott",
    "WARRENER Graham": "warrener-graham",
    "WARRENER Lowrie": "warrener-lowrie",
    "WARRIER Gopi": "warrier-gopi",
    "WARSAMA Yusra": "warsama-yusra",
    "WARSHAW Bettina Katie": "warshaw-bettina-katie",
    "WARSOFSKY Marilyn": "warsofsky-marilyn",
    "WARSZAWA T R": "warszawa-t-r",
    "WARWICK Brett": "warwick-brett",
    "WARWICK Doug": "warwick-doug",
    "WARWICK Edmund": "warwick-edmund",
    "WARWICK James": "warwick-james",
    "WARWICK Keith": "warwick-keith",
    "WARWICK Valerie": "warwick-valerie",
    "WASHBURN Anne": "washburn-anne",
    "WASHER Richard": "washer-richard",
    "WASHINGTON Ajene": "washington-ajene",
    "WASHINGTON Charles L B": "washington-charles-l-b",
    "WASHINGTON Denise": "washington-denise",
    "WASHINGTON Derek \"Duck\"": "washington-derek",
    "WASHINGTON Erwin": "washington-erwin",
    "WASHINGTON Ned": "washington-ned",
    "WASHINGTON Sam": "washington-sam",
    "WASHINGTON SR Von H": "washington-sr-von-h",
    "WASON Murray": "wason-murray",
    "WASON Oliver": "wason-oliver",
    "WASSENAAR Willem": "wassenaar-willem",
    "WASSER Frederick": "wasser-frederick",
    "WASSER Liz": "wasser-liz",
    "WASSERMAN Dale": "wasserman-dale",
    "WASSERMAN E H": "wasserman-e-h",
    "WASSERSTEIN Wendy": "wasserstein-wendy",
    "WASSNAAR Willem": "wassnaar-willem",
    "WASSON Steven": "wasson-steven",
    "WATADA Terry": "watada-terry",
    "WATCHURST Neville": "watchurst-neville",
    "WATERFIELD Carran": "waterfield-carran",
    "WATERHOUSE Betty Senk": "waterhouse-betty-senk",
    "WATERHOUSE Jackie": "waterhouse-jackie",
    "WATERHOUSE John": "waterhouse-john",
    "WATERHOUSE John C": "waterhouse-john-c",
    "WATERHOUSE Keith": "waterhouse-keith",
    "WATERHOUSE Margaret": "waterhouse-margaret",
    "WATERHOUSE Robert": "waterhouse-robert",
    "WATERHOUSE Steve": "waterhouse-steve",
    "WATERMAN Matthew": "waterman-matthew",
    "WATERMAN Peter": "waterman-peter",
    "WATERS C": "waters-c",
    "WATERS Craig": "waters-craig",
    "WATERS Jack": "waters-jack",
    "WATERS Janine": "waters-janine",
    "WATERS John": "waters-john",
    "WATERS Michael": "waters-michael",
    "WATERS Naomi": "waters-naomi",
    "WATERS Nicholas": "waters-nicholas",
    "WATERS Richard": "waters-richard",
    "WATERS Sarah": "waters-sarah",
    "WATERS Simon": "waters-simon",
    "WATERS Steve": "waters-steve",
    "WATERS Todd": "waters-todd",
    "WATERS JR Harry": "waters-jr-harry",
    "WATERTON Agnes": "waterton-agnes",
    "WATERWELL ": "waterwell",
    "WATES Rupert": "wates-rupert",
    "WATHEN Stephen": "wathen-stephen",
    "WATI Jaso": "wati-jaso",
    "WATKEYS Colin": "watkeys-colin",
    "WATKIN Ieuan": "watkin-ieuan",
    "WATKINS Andrew": "watkins-andrew",
    "WATKINS Bertie": "watkins-bertie",
    "WATKINS Brian": "watkins-brian",
    "WATKINS C G": "watkins-c-g",
    "WATKINS Christina Michelle": "watkins-christina-michelle",
    "WATKINS Christine": "watkins-christine",
    "WATKINS Daniel": "watkins-daniel",
    "WATKINS Dennis": "watkins-dennis",
    "WATKINS Evan": "watkins-evan",
    "WATKINS Gordon R": "watkins-gordon-r",
    "WATKINS Gwynne": "watkins-gwynne",
    "WATKINS Ieuan": "watkins-ieuan",
    "WATKINS Jonathan": "watkins-jonathan",
    "WATKINS June": "watkins-june",
    "WATKINS L E": "watkins-l-e",
    "WATKINS Malcolm": "watkins-malcolm",
    "WATKINS Martha Swintz": "watkins-martha-swintz",
    "WATKINS Maurine Dallas": "watkins-maurine-dallas",
    "WATKINS Neil": "watkins-neil",
    "WATKINS Patricia": "watkins-patricia",
    "WATKINS Rick": "watkins-rick",
    "WATKINS Susan": "watkins-susan",
    "WATKINS Vernon": "watkins-vernon",
    "WATKINSON Douglas": "watkinson-douglas",
    "WATKINSON Ivy": "watkinson-ivy",
    "WATKYN Arthur": "watkyn-arthur",
    "WATLING Claire": "watling-claire",
    "WATLING E F": "watling-e-f",
    "WATLING Peter": "watling-peter",
    "WATMOUGH David": "watmough-david",
    "WATSKY George": "watsky-george",
    "WATSON Aby": "watson-aby",
    "WATSON Ara": "watson-ara",
    "WATSON Ben": "watson-ben",
    "WATSON Bill": "watson-bill",
    "WATSON Daryl": "watson-daryl",
    "WATSON Dave": "watson-dave",
    "WATSON David": "watson-david",
    "WATSON David (2)": "watson-david-2",
    "WATSON David (3)": "watson-david-3",
    "WATSON Doc": "watson-doc",
    "WATSON Don": "watson-don",
    "WATSON Donald": "watson-donald",
    "WATSON Ed": "watson-ed",
    "WATSON Emily": "watson-emily",
    "WATSON Erica": "watson-erica",
    "WATSON Fiona": "watson-fiona",
    "WATSON Fred": "watson-fred",
    "WATSON G J": "watson-g-j",
    "WATSON Grant": "watson-grant",
    "WATSON Harmon": "watson-harmon",
    "WATSON Ian": "watson-ian",
    "WATSON Ian (1)": "watson-ian-1",
    "WATSON James": "watson-james",
    "WATSON Jessa": "watson-jessa",
    "WATSON Kate": "watson-kate",
    "WATSON Laura": "watson-laura",
    "WATSON Lyall": "watson-lyall",
    "WATSON M M": "watson-m-m",
    "WATSON Marion": "watson-marion",
    "WATSON Mark": "watson-mark",
    "WATSON Mark S": "watson-mark-s",
    "WATSON Murray": "watson-murray",
    "WATSON Neil": "watson-neil",
    "WATSON Nenagh": "watson-nenagh",
    "WATSON Nicole": "watson-nicole",
    "WATSON Nicole A": "watson-nicole-a",
    "WATSON Oscar": "watson-oscar",
    "WATSON Peter": "watson-peter",
    "WATSON Reg": "watson-reg",
    "WATSON Robert": "watson-robert",
    "WATSON Rom": "watson-rom",
    "WATSON Sally": "watson-sally",
    "WATSON Sam": "watson-sam",
    "WATSON Sara": "watson-sara",
    "WATSON T M": "watson-t-m",
    "WATSON Wilfred": "watson-wilfred",
    "WATSON William": "watson-william",
    "WATSON-JONES Brian": "watson-jones-brian",
    "WATT Alan": "watt-alan",
    "WATT Alison": "watt-alison",
    "WATT Billie Lou": "watt-billie-lou",
    "WATT Erik": "watt-erik",
    "WATT Hannah": "watt-hannah",
    "WATT Jenna": "watt-jenna",
    "WATTERS Mark": "watters-mark",
    "WATTERS Mary": "watters-mary",
    "WATTS Alan S": "watts-alan-s",
    "WATTS Andrea": "watts-andrea",
    "WATTS David": "watts-david",
    "WATTS Evan": "watts-evan",
    "WATTS Frances": "watts-frances",
    "WATTS Helen": "watts-helen",
    "WATTS Irene N": "watts-irene-n",
    "WATTS Jan": "watts-jan",
    "WATTS John": "watts-john",
    "WATTS John (1)": "watts-john-1",
    "WATTS Michael": "watts-michael",
    "WATTS Murray": "watts-murray",
    "WATTS Patrick": "watts-patrick",
    "WATTS Peter": "watts-peter",
    "WATTS Reggie": "watts-reggie",
    "WATTS Richard": "watts-richard",
    "WATTS Tim": "watts-tim",
    "WAUDBY Melissa": "waudby-melissa",
    "WAUGH Ed": "waugh-ed",
    "WAUGH Jen": "waugh-jen",
    "WAUGH Jennifer": "waugh-jennifer",
    "WAX Aysha": "wax-aysha",
    "WAX Emanuel": "wax-emanuel",
    "WAX Jamie": "wax-jamie",
    "WAX Jeffrey": "wax-jeffrey",
    "WAX Kenny": "wax-kenny",
    "WAX Ruby": "wax-ruby",
    "WAXMAN Howard": "waxman-howard",
    "WAY Brian": "way-brian",
    "WAY Bruce": "way-bruce",
    "WAY Charles": "way-charles",
    "WAY Jeff": "way-jeff",
    "WAY Phil": "way-phil",
    "WAY-AGLE Glendele": "way-agle-glendele",
    "WAYMON Sam": "waymon-sam",
    "WAYNE Doreen": "wayne-doreen",
    "WAYNE Jeff": "wayne-jeff",
    "WAYNE Jemma": "wayne-jemma",
    "WAYTE Darren": "wayte-darren",
    "WAYTOWITCH Jo-Ann": "waytowitch-jo-ann",
    "WAYWARD ": "wayward",
    "WEAGLY John": "weagly-john",
    "WEALE Edith": "weale-edith",
    "WEANIE Ian": "weanie-ian",
    "WEAR Peter": "wear-peter",
    "WEAR Susan": "wear-susan",
    "WEATHERALL Sarah": "weatherall-sarah",
    "WEATHERBY Iain": "weatherby-iain",
    "WEATHERFORD Margaret": "weatherford-margaret",
    "WEATHERILL Ben": "weatherill-ben",
    "WEATHERS Philip": "weathers-philip",
    "WEATHERSTONE C L": "weatherstone-c-l",
    "WEAVER Abiole Roselle": "weaver-abiole-roselle",
    "WEAVER Carl": "weaver-carl",
    "WEAVER Deke": "weaver-deke",
    "WEAVER Erin": "weaver-erin",
    "WEAVER Janice": "weaver-janice",
    "WEAVER Jesse": "weaver-jesse",
    "WEAVER John V A": "weaver-john-v-a",
    "WEAVER Lee": "weaver-lee",
    "WEAVER Lois": "weaver-lois",
    "WEAVER Megan": "weaver-megan",
    "WEAVER Ron": "weaver-ron",
    "WEAVER Shannon": "weaver-shannon",
    "WEAVER-HINCKS Ben": "weaver-hincks-ben",
    "WEB Paul": "web-paul",
    "WEBB Alex": "webb-alex",
    "WEBB Ben": "webb-ben",
    "WEBB Charlotte": "webb-charlotte",
    "WEBB Damaris": "webb-damaris",
    "WEBB Delma M": "webb-delma-m",
    "WEBB Denis": "webb-denis",
    "WEBB Derek": "webb-derek",
    "WEBB Don": "webb-don",
    "WEBB Eric": "webb-eric",
    "WEBB George": "webb-george",
    "WEBB Harriet": "webb-harriet",
    "WEBB Helena": "webb-helena",
    "WEBB James": "webb-james",
    "WEBB Jennie": "webb-jennie",
    "WEBB Jeremy": "webb-jeremy",
    "WEBB K": "webb-k",
    "WEBB Leonard": "webb-leonard",
    "WEBB Liz": "webb-liz",
    "WEBB Lorraine": "webb-lorraine",
    "WEBB Mary Matoula": "webb-mary-matoula",
    "WEBB Paul": "webb-paul",
    "WEBB Peter": "webb-peter",
    "WEBB Peter (1)": "webb-peter-1",
    "WEBB Robert Henning": "webb-robert-henning",
    "WEBB Stephen": "webb-stephen",
    "WEBB Steve": "webb-steve",
    "WEBB Steven": "webb-steven",
    "WEBB Terry": "webb-terry",
    "WEBB Tim": "webb-tim",
    "WEBB Tom": "webb-tom",
    "WEBB Troy": "webb-troy",
    "WEBB W W": "webb-w-w",
    "WEBBER Andrew Lloyd": "webber-andrew-lloyd",
    "WEBBER C E": "webber-c-e",
    "WEBBER Evan": "webber-evan",
    "WEBBER Holly": "webber-holly",
    "WEBBER James": "webber-james",
    "WEBBER Jennifer Wynne": "webber-jennifer-wynne",
    "WEBBER Jim": "webber-jim",
    "WEBBER Julian": "webber-julian",
    "WEBBER Katherine": "webber-katherine",
    "WEBBER Mark": "webber-mark",
    "WEBBER Tilly": "webber-tilly",
    "WEBER Adam": "weber-adam",
    "WEBER Anya": "weber-anya",
    "WEBER Barbara Pease": "weber-barbara-pease",
    "WEBER Carl": "weber-carl",
    "WEBER Emilia": "weber-emilia",
    "WEBER Frederica": "weber-frederica",
    "WEBER Guntram H": "weber-guntram-h",
    "WEBER Marc": "weber-marc",
    "WEBER Myles": "weber-myles",
    "WEBER Ruth": "weber-ruth",
    "WEBER Stephanie": "weber-stephanie",
    "WEBLINGS Dust": "weblings-dust",
    "WEBRE Septime": "webre-septime",
    "WEBRECK Erin": "webreck-erin",
    "WEBSTER Bill": "webster-bill",
    "WEBSTER Brenda": "webster-brenda",
    "WEBSTER Brett": "webster-brett",
    "WEBSTER Bryan C": "webster-bryan-c",
    "WEBSTER Catherine": "webster-catherine",
    "WEBSTER Don": "webster-don",
    "WEBSTER Donald": "webster-donald",
    "WEBSTER Dorcas": "webster-dorcas",
    "WEBSTER Gary": "webster-gary",
    "WEBSTER Greg": "webster-greg",
    "WEBSTER Jean": "webster-jean",
    "WEBSTER Jill": "webster-jill",
    "WEBSTER John": "webster-john",
    "WEBSTER Kate": "webster-kate",
    "WEBSTER Margaret": "webster-margaret",
    "WEBSTER Max": "webster-max",
    "WEBSTER Paul": "webster-paul",
    "WEBSTER Paul (1)": "webster-paul-1",
    "WEBSTER Paul Francis": "webster-paul-francis",
    "WEBSTER Peter": "webster-peter",
    "WEBSTER Suki": "webster-suki",
    "WEBSTER Tim": "webster-tim",
    "WEBSTER Tony": "webster-tony",
    "WECEL John": "wecel-john",
    "WECHER Jereme": "wecher-jereme",
    "WECHSLER Jeremy": "wechsler-jeremy",
    "WECHSLER Joel": "wechsler-joel",
    "WECHSLER Neil": "wechsler-neil",
    "WECHTER David": "wechter-david",
    "WECKESSER Josh": "weckesser-josh",
    "WEDDINGTON Andra": "weddington-andra",
    "WEDDINGTON Georgiana": "weddington-georgiana",
    "WEDEKIND Frank": "wedekind-frank",
    "WEED Dunstan": "weed-dunstan",
    "WEEDALL David": "weedall-david",
    "WEEDMAN Donald": "weedman-donald",
    "WEEDMAN Lauren": "weedman-lauren",
    "WEEDON Allen": "weedon-allen",
    "WEEKES Aidan": "weekes-aidan",
    "WEEKS Derek": "weeks-derek",
    "WEEKS Honeysuckle": "weeks-honeysuckle",
    "WEEKS Kimberly": "weeks-kimberly",
    "WEEKS Russell": "weeks-russell",
    "WEEMS Marianne": "weems-marianne",
    "WEEMS Mary E": "weems-mary-e",
    "WEEMS Michael": "weems-michael",
    "WEEMS Nancy": "weems-nancy",
    "WEESNER Robert": "weesner-robert",
    "WEETMAN Martin": "weetman-martin",
    "WEEWEES, THE ": "weewees",
    "WEGNER Zach": "wegner-zach",
    "WEGRZYN Marisa": "wegrzyn-marisa",
    "WEGSMAN Graciela Berger": "wegsman-graciela-berger",
    "WEHL Philippa": "wehl-philippa",
    "WEHLE Patricia": "wehle-patricia",
    "WEHLE Philippa": "wehle-philippa",
    "WEHNER Ros": "wehner-ros",
    "WEHRLI Michael": "wehrli-michael",
    "WEHRSPANN Andrew": "wehrspann-andrew",
    "WEI Bai": "wei-bai",
    "WEI Wen Xiao": "wei-xiao",
    "WEICHMANN Barbara": "weichmann-barbara",
    "WEIDA Nate": "weida-nate",
    "WEIDMAN Bob": "weidman-bob",
    "WEIDMAN Jerome": "weidman-jerome",
    "WEIDMAN John": "weidman-john",
    "WEIDNER Paul": "weidner-paul",
    "WEIGAND Randy": "weigand-randy",
    "WEIGH Anthony": "weigh-anthony",
    "WEIGHT Dickie": "weight-dickie",
    "WEIGHT Jenny": "weight-jenny",
    "WEIGHTMAN J": "weightman-j",
    "WEIGHTMAN Reece": "weightman-reece",
    "WEIHS Ronald": "weihs-ronald",
    "WEIKEL Chris": "weikel-chris",
    "WEIL Cara Vander": "weil-cara-vander",
    "WEIL Cynthia": "weil-cynthia",
    "WEIL Jung": "weil-jung",
    "WEIL Peggy": "weil-peggy",
    "WEIL Zoe": "weil-zoe",
    "WEILACHER Raymond": "weilacher-raymond",
    "WEILERT Michelle": "weilert-michelle",
    "WEILL Gus": "weill-gus",
    "WEILL Kurt": "weill-kurt",
    "WEIN Glenn": "wein-glenn",
    "WEINBERG Barry": "weinberg-barry",
    "WEINBERG Carol": "weinberg-carol",
    "WEINBERG Joanna": "weinberg-joanna",
    "WEINBERG Julie": "weinberg-julie",
    "WEINBERG Karen": "weinberg-karen",
    "WEINBERG Tom Wilson": "weinberg-tom-wilson",
    "WEINBERGER Eric H": "weinberger-eric-h",
    "WEINBERGER G J": "weinberger-g-j",
    "WEINBERGER Nathan": "weinberger-nathan",
    "WEINBERGER Wolfgang": "weinberger-wolfgang",
    "WEINBLATT Mic": "weinblatt-mic",
    "WEINE Max G": "weine-max-g",
    "WEINER Craig J": "weiner-craig-j",
    "WEINER Dave": "weiner-dave",
    "WEINER Erik": "weiner-erik",
    "WEINER Hope": "weiner-hope",
    "WEINER Jenny Rachel": "weiner-jenny-rachel",
    "WEINER Leslie": "weiner-leslie",
    "WEINER Marc": "weiner-marc",
    "WEINER Mark": "weiner-mark",
    "WEINER Matthew": "weiner-matthew",
    "WEINER Michael": "weiner-michael",
    "WEINER Randy": "weiner-randy",
    "WEINER Rex": "weiner-rex",
    "WEINER Ron": "weiner-ron",
    "WEINER Stephen": "weiner-stephen",
    "WEINER Wendy": "weiner-wendy",
    "WEINGARTEN Catherine": "weingarten-catherine",
    "WEINGARTEN Robert": "weingarten-robert",
    "WEINGARTEN Romain": "weingarten-romain",
    "WEINGARTEN Stacey": "weingarten-stacey",
    "WEINRAUB Bernard": "weinraub-bernard",
    "WEINREB Mischke": "weinreb-mischke",
    "WEINSTEIN Arnold": "weinstein-arnold",
    "WEINSTEIN Arnold (2)": "weinstein-arnold-2",
    "WEINSTEIN David": "weinstein-david",
    "WEINSTEIN Frederick": "weinstein-frederick",
    "WEINSTEIN Jo": "weinstein-jo",
    "WEINSTEIN John B": "weinstein-john-b",
    "WEINSTEIN Joshua Aaron": "weinstein-joshua-aaron",
    "WEINSTEIN Judith": "weinstein-judith",
    "WEINSTEIN Melanie Zoey": "weinstein-melanie-zoey",
    "WEINSTEIN Norman": "weinstein-norman",
    "WEINSTEIN Robert": "weinstein-robert",
    "WEINSTEIN Seth": "weinstein-seth",
    "WEINSTOCK Jack": "weinstock-jack",
    "WEINTHAL Eric": "weinthal-eric",
    "WEINTRAUB Dominic": "weintraub-dominic",
    "WEINTRAUB J": "weintraub-j",
    "WEINTRAUB William": "weintraub-william",
    "WEIR Andrew": "weir-andrew",
    "WEIR David": "weir-david",
    "WEIR Ian": "weir-ian",
    "WEIR Justin": "weir-justin",
    "WEIR Matt": "weir-matt",
    "WEIR Ryann": "weir-ryann",
    "WEIS Jakob": "weis-jakob",
    "WEISBERG Stve": "weisberg-stve",
    "WEISBORT Daniel": "weisbort-daniel",
    "WEISE Jillian": "weise-jillian",
    "WEISE Roy Alexander": "weise-roy-alexander",
    "WEISENHORN Guenther": "weisenhorn-guenther",
    "WEISER Eyal": "weiser-eyal",
    "WEISER Mark": "weiser-mark",
    "WEISER Mel": "weiser-mel",
    "WEISMAN Annie": "weisman-annie",
    "WEISMAN Herman M": "weisman-herman-m",
    "WEISMAN Jael": "weisman-jael",
    "WEISMAN Jerome": "weisman-jerome",
    "WEISMAN Roger": "weisman-roger",
    "WEISMAN Stefan": "weisman-stefan",
    "WEISMANN Paul": "weismann-paul",
    "WEISS Alison": "weiss-alison",
    "WEISS Carol": "weiss-carol",
    "WEISS Edith": "weiss-edith",
    "WEISS Ellen": "weiss-ellen",
    "WEISS Emily Chadick": "weiss-emily-chadick",
    "WEISS Ezra": "weiss-ezra",
    "WEISS George David": "weiss-george-david",
    "WEISS Glenn Laszlo": "weiss-glenn-laszlo",
    "WEISS Hanna Kalter": "weiss-hanna-kalter",
    "WEISS Jeff": "weiss-jeff",
    "WEISS Jeff P": "weiss-jeff-p",
    "WEISS Jenna": "weiss-jenna",
    "WEISS Joel": "weiss-joel",
    "WEISS Julia": "weiss-julia",
    "WEISS Marilyn": "weiss-marilyn",
    "WEISS Matthew": "weiss-matthew",
    "WEISS Natalie": "weiss-natalie",
    "WEISS Peter": "weiss-peter",
    "WEISS Peter (1)": "weiss-peter-1",
    "WEISS Peter Eliot": "weiss-peter-eliot",
    "WEISS Phillip W": "weiss-phillip-w",
    "WEISS Rich": "weiss-rich",
    "WEISS Samara": "weiss-samara",
    "WEISSENBORN Theodor": "weissenborn-theodor",
    "WEISSMAN Aaron": "weissman-aaron",
    "WEISSMAN Ed": "weissman-ed",
    "WEISSMAN Gabriel Vega": "weissman-gabriel-vega",
    "WEISSMAN Paul": "weissman-paul",
    "WEITZ Emily J": "weitz-emily-j",
    "WEITZ Marc Stuart": "weitz-marc-stuart",
    "WEITZ Paul": "weitz-paul",
    "WEITZMAN Ken": "weitzman-ken",
    "WELANDAWE-PREMATILLEK Arun": "welandawe-prematillek-arun",
    "WELBURN Tim": "welburn-tim",
    "WELBURN Vivienne": "welburn-vivienne",
    "WELCH Brian": "welch-brian",
    "WELCH Colin": "welch-colin",
    "WELCH Eric": "welch-eric",
    "WELCH John B": "welch-john-b",
    "WELCH Jon": "welch-jon",
    "WELCH Liz": "welch-liz",
    "WELCH Margaret": "welch-margaret",
    "WELCH Peter": "welch-peter",
    "WELCH Rachel": "welch-rachel",
    "WELCH Robert": "welch-robert",
    "WELCH Sean Michael": "welch-sean-michael",
    "WELCH Sybil": "welch-sybil",
    "WELCH William": "welch-william",
    "WELDEN Bess": "welden-bess",
    "WELDEN Nate": "welden-nate",
    "WELDON Fay": "weldon-fay",
    "WELDON Roger": "weldon-roger",
    "WELFARE Sue": "welfare-sue",
    "WELFARE STATE ": "welfare-state",
    "WELLAND Colin": "welland-colin",
    "WELLBURN Vivienne": "wellburn-vivienne",
    "WELLDON Christopher": "welldon-christopher",
    "WELLER Archie": "weller-archie",
    "WELLER Jeremy": "weller-jeremy",
    "WELLER Michael": "weller-michael",
    "WELLER Tammy": "weller-tammy",
    "WELLES Orson": "welles-orson",
    "WELLING Albert": "welling-albert",
    "WELLMAN Derek": "wellman-derek",
    "WELLMAN John": "wellman-john",
    "WELLMAN Mac": "wellman-mac",
    "WELLMAN Max": "wellman-max",
    "WELLMAN Nathan": "wellman-nathan",
    "WELLMAN Zoe": "wellman-zoe",
    "WELLMON Eddie": "wellmon-eddie",
    "WELLS Adam H": "wells-adam-h",
    "WELLS Alex": "wells-alex",
    "WELLS B K": "wells-b-k",
    "WELLS Bob": "wells-bob",
    "WELLS Charles": "wells-charles",
    "WELLS Chris": "wells-chris",
    "WELLS David": "wells-david",
    "WELLS Duncan": "wells-duncan",
    "WELLS Edward Crosby": "wells-edward-crosby",
    "WELLS Elizabeth Warren": "wells-elizabeth-warren",
    "WELLS Frank": "wells-frank",
    "WELLS H W": "wells-h-w",
    "WELLS Jason": "wells-jason",
    "WELLS Jennifer": "wells-jennifer",
    "WELLS John": "wells-john",
    "WELLS John S": "wells-john-s",
    "WELLS Ker": "wells-ker",
    "WELLS Krista": "wells-krista",
    "WELLS Mary": "wells-mary",
    "WELLS Mary Jane": "wells-mary-jane",
    "WELLS Matthew": "wells-matthew",
    "WELLS Michael": "wells-michael",
    "WELLS Orlando": "wells-orlando",
    "WELLS Patricia": "wells-patricia",
    "WELLS Paul": "wells-paul",
    "WELLS Philip": "wells-philip",
    "WELLS Robert": "wells-robert",
    "WELLS Roxanne": "wells-roxanne",
    "WELLS Tom": "wells-tom",
    "WELLS Tracy": "wells-tracy",
    "WELLS William K": "wells-william-k",
    "WELLS Win": "wells-win",
    "WELLWARTH George E": "wellwarth-george-e",
    "WELLWEIN Louise": "wellwein-louise",
    "WELSER Daniel": "welser-daniel",
    "WELSH Ann": "welsh-ann",
    "WELSH David": "welsh-david",
    "WELSH Irvine": "welsh-irvine",
    "WELSH Kenneth": "welsh-kenneth",
    "WELSH Louise": "welsh-louise",
    "WELSH Martin": "welsh-martin",
    "WELSH Rachel": "welsh-rachel",
    "WELSH Scott": "welsh-scott",
    "WELTON Mathew": "welton-mathew",
    "WELTY Eudora": "welty-eudora",
    "WELTY Rebecca": "welty-rebecca",
    "WELZ Gary": "welz-gary",
    "WELZENBACH Chris": "welzenbach-chris",
    "WEMBRIDGE David": "wembridge-david",
    "WEMETTE Jonathan": "wemette-jonathan",
    "WEMYSS Fred": "wemyss-fred",
    "WEN Shao": "wen-shao",
    "WENBORNE Joe": "wenborne-joe",
    "WENCKHEIM Nicholas": "wenckheim-nicholas",
    "WENDEN David": "wenden-david",
    "WENDKOS Gina": "wendkos-gina",
    "WENDT Albert": "wendt-albert",
    "WENE Brian": "wene-brian",
    "WENGROW Arnold": "wengrow-arnold",
    "WENLEY James": "wenley-james",
    "WENNER Kate": "wenner-kate",
    "WENSINGER Arthur S": "wensinger-arthur-s",
    "WENT Alex": "went-alex",
    "WENT Corbin": "went-corbin",
    "WENTHWORTH Tom": "wenthworth-tom",
    "WENTWORTH Scott": "wentworth-scott",
    "WENTWORTH Tom": "wentworth-tom",
    "WENZEL Jean-Paul": "wenzel-jean-paul",
    "WERBACHER Don": "werbacher-don",
    "WERBACHER Rich": "werbacher-rich",
    "WERENKO Tim": "werenko-tim",
    "WERENOWSKA Nicola": "werenowska-nicola",
    "WERFEL Franz": "werfel-franz",
    "WERNER Constantine": "werner-constantine",
    "WERNER Eric": "werner-eric",
    "WERNER Hans": "werner-hans",
    "WERNER Raymond": "werner-raymond",
    "WERNER Sven": "werner-sven",
    "WERNER William": "werner-william",
    "WERSE Stan": "werse-stan",
    "WERTENBAKER Timberlake": "wertenbaker-timberlake",
    "WERTH Lance": "werth-lance",
    "WERTHEIM Audrey": "wertheim-audrey",
    "WERTHEIM Micha": "wertheim-micha",
    "WERTIMER Frances": "wertimer-frances",
    "WERY Isabelle": "wery-isabelle",
    "WESCH Denise": "wesch-denise",
    "WESCHLER Daniel": "weschler-daniel",
    "WESCHLER Joel": "weschler-joel",
    "WESKER Arnold": "wesker-arnold",
    "WESLEY James": "wesley-james",
    "WESLEY Richard": "wesley-richard",
    "WESLEY Robbie": "wesley-robbie",
    "WESLEY Suzanne": "wesley-suzanne",
    "WESLEY-SMITH Martin": "wesley-smith-martin",
    "WESLEY-SMITH Peter": "wesley-smith-peter",
    "WESNER David": "wesner-david",
    "WESSBECHER Grace": "wessbecher-grace",
    "WESSELS Dan": "wessels-dan",
    "WESSENDORF Markus": "wessendorf-markus",
    "WEST Abigail": "west-abigail",
    "WEST Alison": "west-alison",
    "WEST Audrey": "west-audrey",
    "WEST Benedick": "west-benedick",
    "WEST Bernie": "west-bernie",
    "WEST Brian": "west-brian",
    "WEST Calamity": "west-calamity",
    "WEST Carolyn": "west-carolyn",
    "WEST Cat Hasson": "west-cat-hasson",
    "WEST Cheryl L": "west-cheryl-l",
    "WEST Corin": "west-corin",
    "WEST Dan": "west-dan",
    "WEST Danny": "west-danny",
    "WEST Darron L": "west-darron-l",
    "WEST David": "west-david",
    "WEST Dolly": "west-dolly",
    "WEST Don": "west-don",
    "WEST Ella": "west-ella",
    "WEST Grady": "west-grady",
    "WEST Greg": "west-greg",
    "WEST Jack": "west-jack",
    "WEST John Anthony": "west-john-anthony",
    "WEST John David": "west-john-david",
    "WEST Keith": "west-keith",
    "WEST Kevin Michael": "west-kevin-michael",
    "WEST L L": "west-l-l",
    "WEST Mae": "west-mae",
    "WEST Martin": "west-martin",
    "WEST Maurice Langlo": "west-maurice-langlo",
    "WEST Michael": "west-michael",
    "WEST Michael (1)": "west-michael-1",
    "WEST Monica": "west-monica",
    "WEST Morris": "west-morris",
    "WEST Nancy": "west-nancy",
    "WEST Richard": "west-richard",
    "WEST Ron": "west-ron",
    "WEST Sara": "west-sara",
    "WEST Sheila": "west-sheila",
    "WEST Thomas Edward": "west-thomas-edward",
    "WEST Trudy": "west-trudy",
    "WEST Vern": "west-vern",
    "WEST Wendy": "west-wendy",
    "WESTBROOK B R": "westbrook-b-r",
    "WESTBROOK Emanuel": "westbrook-emanuel",
    "WESTBROOK Kate": "westbrook-kate",
    "WESTBROOK Mark": "westbrook-mark",
    "WESTBROOK Mike": "westbrook-mike",
    "WESTBROOKE Simeon": "westbrooke-simeon",
    "WESTBURY Lou": "westbury-lou",
    "WESTEEN L Robert": "westeen-l-robert",
    "WESTERFIELD William": "westerfield-william",
    "WESTERGAARD Louise": "westergaard-louise",
    "WESTERKAMP Rick": "westerkamp-rick",
    "WESTERMAN Naomi": "westerman-naomi",
    "WESTERN Melissa": "western-melissa",
    "WESTERSIDE Andrew": "westerside-andrew",
    "WESTFALL Susan": "westfall-susan",
    "WESTFALL Susan J": "westfall-susan-j",
    "WESTHEIMER David": "westheimer-david",
    "WESTKAEMPER Lisa": "westkaemper-lisa",
    "WESTLAKE E J": "westlake-e-j",
    "WESTLAKE Hilary": "westlake-hilary",
    "WESTMACOTT Mary": "westmacott-mary",
    "WESTMORELAND Mackenzie": "westmoreland-mackenzie",
    "WESTON Alyson": "weston-alyson",
    "WESTON Fiona-Jane": "weston-fiona-jane",
    "WESTON Geoffrey": "weston-geoffrey",
    "WESTON Marcia": "weston-marcia",
    "WESTON Mark": "weston-mark",
    "WESTON Nicola": "weston-nicola",
    "WESTON Peter": "weston-peter",
    "WESTON R P": "weston-r-p",
    "WESTON Sarah": "weston-sarah",
    "WESTWOOD Chris": "westwood-chris",
    "WESTWOOD Matthew": "westwood-matthew",
    "WETHERALL Mole": "wetherall-mole",
    "WETMORE Andrew": "wetmore-andrew",
    "WETTIG Patricia": "wettig-patricia",
    "WETZEL Daniel": "wetzel-daniel",
    "WETZEL Jason": "wetzel-jason",
    "WETZEL Wes": "wetzel-wes",
    "WETZORK Laurel Moje": "wetzork-laurel-moje",
    "WEX Marilla": "wex-marilla",
    "WEXLER Alex": "wexler-alex",
    "WEXLER Ben": "wexler-ben",
    "WEXLER Matt": "wexler-matt",
    "WEXLER Norman": "wexler-norman",
    "WEXLER Shanan": "wexler-shanan",
    "WEYNAND David": "weynand-david"
  }
};