export default {
  "metadata": {
    "results": 456,
    "timeStamp": "2025-12-05T21:32:19.972Z",
    "url": "https://www.doollee.com/PlaywrightsW/W_playwrights_m-r.php"
  },
  "authors": {
    "WOCHNER Lee": "wochner-lee",
    "WODARZ Hans-Peter": "wodarz-hans-peter",
    "WODDIS Roger": "woddis-roger",
    "WODEHOUSE P G": "wodehouse-p-g",
    "WOERTENDYKE Ruis": "woertendyke-ruis",
    "WOHEAD Greg": "wohead-greg",
    "WOHL Bess": "wohl-bess",
    "WOHL David": "wohl-david",
    "WOHL Jack": "wohl-jack",
    "WOHLGEMUTH Joseph": "wohlgemuth-joseph",
    "WOHLMUT Patrick": "wohlmut-patrick",
    "WOINGUST Sylvia": "woingust-sylvia",
    "WOJCIESZEK Przemyslaw": "wojcieszek-przemyslaw",
    "WOJIECHOWSKI Andrew": "wojiechowski-andrew",
    "WOJNAROWICZ David": "wojnarowicz-david",
    "WOJTYLA Karol": "wojtyla-karol",
    "WOKER Daniel": "woker-daniel",
    "WOKUM Katie": "wokum-katie",
    "WOLCZ Nicky": "wolcz-nicky",
    "WOLD Kerry": "wold-kerry",
    "WOLDENBERG Larry": "woldenberg-larry",
    "WOLDIN Judd": "woldin-judd",
    "WOLES Robert": "woles-robert",
    "WOLF Alison Vodnoy": "wolf-alison-vodnoy",
    "WOLF Alli Sebastian": "wolf-alli-sebastian",
    "WOLF Andy": "wolf-andy",
    "WOLF Anna": "wolf-anna",
    "WOLF B": "wolf-b",
    "WOLF Carol": "wolf-carol",
    "WOLF Catherine": "wolf-catherine",
    "WOLF Charlie": "wolf-charlie",
    "WOLF David": "wolf-david",
    "WOLF Dorothy": "wolf-dorothy",
    "WOLF Emleigh": "wolf-emleigh",
    "WOLF Eve": "wolf-eve",
    "WOLF Garin": "wolf-garin",
    "WOLF Henry E": "wolf-henry-e",
    "WOLF Jeffrey": "wolf-jeffrey",
    "WOLF Jessica": "wolf-jessica",
    "WOLF Ken": "wolf-ken",
    "WOLF Kerry": "wolf-kerry",
    "WOLF Laurie": "wolf-laurie",
    "WOLF Lindsay": "wolf-lindsay",
    "WOLF Marc": "wolf-marc",
    "WOLF Melanie Jams": "wolf-melanie-jams",
    "WOLF Peter": "wolf-peter",
    "WOLF Rachel": "wolf-rachel",
    "WOLF Richard": "wolf-richard",
    "WOLF Sheldon": "wolf-sheldon",
    "WOLF Theodore B": "wolf-theodore-b",
    "WOLFE Barb": "wolfe-barb",
    "WOLFE Bernard": "wolfe-bernard",
    "WOLFE Chris": "wolfe-chris",
    "WOLFE Elton C": "wolfe-elton-c",
    "WOLFE George C": "wolfe-george-c",
    "WOLFE Gregory": "wolfe-gregory",
    "WOLFE Hannah": "wolfe-hannah",
    "WOLFE Jan H": "wolfe-jan-h",
    "WOLFE K C": "wolfe-k-c",
    "WOLFE Karina": "wolfe-karina",
    "WOLFE Lexi": "wolfe-lexi",
    "WOLFE M K": "wolfe-m-k",
    "WOLFE Ronald": "wolfe-ronald",
    "WOLFE Tom Matthew": "wolfe-tom-matthew",
    "WOLFE Wayne": "wolfe-wayne",
    "WOLFE Winifred": "wolfe-winifred",
    "WOLFF Andrea": "wolff-andrea",
    "WOLFF Becca": "wolff-becca",
    "WOLFF Christian": "wolff-christian",
    "WOLFF Egon": "wolff-egon",
    "WOLFF Isobel": "wolff-isobel",
    "WOLFF Jannie": "wolff-jannie",
    "WOLFF Joe Marcel": "wolff-joe-marcel",
    "WOLFF Paula": "wolff-paula",
    "WOLFF Ruth": "wolff-ruth",
    "WOLFFE Bart": "wolffe-bart",
    "WOLFGANG Johann": "wolfgang-johann",
    "WOLFGRAM EVANS Noel K": "wolfgram-evans-noel-k",
    "WOLFIT Margaret": "wolfit-margaret",
    "WOLFMAN Jonathan": "wolfman-jonathan",
    "WOLFMAN Judy": "wolfman-judy",
    "WOLFORD Jackson": "wolford-jackson",
    "WOLFOWITZ Leslie": "wolfowitz-leslie",
    "WOLFSON Archie": "wolfson-archie",
    "WOLFSON Jenni": "wolfson-jenni",
    "WOLFSON John": "wolfson-john",
    "WOLFSON Michael": "wolfson-michael",
    "WOLFSON Sam": "wolfson-sam",
    "WOLFSON Steven": "wolfson-steven",
    "WOLFSON Victor": "wolfson-victor",
    "WOLK Andy": "wolk-andy",
    "WOLK Emil": "wolk-emil",
    "WOLK Michael": "wolk-michael",
    "WOLLEN William": "wollen-william",
    "WOLLERTON Adam": "wollerton-adam",
    "WOLLMAN Rebecca": "wollman-rebecca",
    "WOLLNER Donald": "wollner-donald",
    "WOLLNER Martha": "wollner-martha",
    "WOLMAN Rebecca": "wolman-rebecca",
    "WOLPE Dan": "wolpe-dan",
    "WOLPE David": "wolpe-david",
    "WOLPE Sholeh": "wolpe-sholeh",
    "WOLPOW Daniel": "wolpow-daniel",
    "WOLSHIN Sandy": "wolshin-sandy",
    "WOLTER Lori": "wolter-lori",
    "WOLTON Joan": "wolton-joan",
    "WOLVERTON Mark": "wolverton-mark",
    "WOMACK Denise E": "womack-denise-e",
    "WOMACK Jack": "womack-jack",
    "WOMBLE David": "womble-david",
    "WOMBLE Ken": "womble-ken",
    "WOMBWEL Charmaine": "wombwel-charmaine",
    "WOMEN IN THEATRE ": "women-in-theatre",
    "WOMEN WRITE ": "women-write",
    "WOMEN-ESSENDON ": "women-essendon",
    "WOMEN'S THEATRE GROUP ": "women-s-theatre-group",
    "WONDERBOLT ": "wonderbolt",
    "WONG Adrienne": "wong-adrienne",
    "WONG Cary": "wong-cary",
    "WONG Chris": "wong-chris",
    "WONG Diane": "wong-diane",
    "WONG Diane Yen-Mei": "wong-diane-yen-mei",
    "WONG Eleanor": "wong-eleanor",
    "WONG Elizabeth": "wong-elizabeth",
    "WONG Gary": "wong-gary",
    "WONG James": "wong-james",
    "WONG Juliet": "wong-juliet",
    "WONG Kevin": "wong-kevin",
    "WONG Kristina": "wong-kristina",
    "WONG L L": "wong-l-l",
    "WONG Lane": "wong-lane",
    "WONG Larry": "wong-larry",
    "WONG Mel": "wong-mel",
    "WONG Ming": "wong-ming",
    "WONG Timothy C": "wong-timothy-c",
    "WONG Wyman": "wong-wyman",
    "WOO Alexander": "woo-alexander",
    "WOO Justin": "woo-justin",
    "WOOD Abbe": "wood-abbe",
    "WOOD Adam": "wood-adam",
    "WOOD Adolf": "wood-adolf",
    "WOOD Alexander": "wood-alexander",
    "WOOD Alice": "wood-alice",
    "WOOD Alison": "wood-alison",
    "WOOD Andrew": "wood-andrew",
    "WOOD Annie": "wood-annie",
    "WOOD Annie (1)": "wood-annie-1",
    "WOOD Annie Cusick": "wood-annie-cusick",
    "WOOD Anthony": "wood-anthony",
    "WOOD Antony": "wood-antony",
    "WOOD Barry": "wood-barry",
    "WOOD Beth": "wood-beth",
    "WOOD Brandon": "wood-brandon",
    "WOOD Casey": "wood-casey",
    "WOOD Charles": "wood-charles",
    "WOOD Craig M": "wood-craig-m",
    "WOOD Cyrus": "wood-cyrus",
    "WOOD David": "wood-david",
    "WOOD Dorothy": "wood-dorothy",
    "WOOD Emma": "wood-emma",
    "WOOD G": "wood-g",
    "WOOD George": "wood-george",
    "WOOD Helga": "wood-helga",
    "WOOD Hilary": "wood-hilary",
    "WOOD Jake": "wood-jake",
    "WOOD James": "wood-james",
    "WOOD Jamie": "wood-jamie",
    "WOOD John": "wood-john",
    "WOOD John (1)": "wood-john-1",
    "WOOD John C": "wood-john-c",
    "WOOD John Christopher": "wood-john-christopher",
    "WOOD John Lisbon": "wood-john-lisbon",
    "WOOD Kate": "wood-kate",
    "WOOD Kevin": "wood-kevin",
    "WOOD Kirk": "wood-kirk",
    "WOOD Mallory": "wood-mallory",
    "WOOD Margaret": "wood-margaret",
    "WOOD Maryrose": "wood-maryrose",
    "WOOD Matthew": "wood-matthew",
    "WOOD Maxine": "wood-maxine",
    "WOOD Michael": "wood-michael",
    "WOOD Nathan": "wood-nathan",
    "WOOD Nick": "wood-nick",
    "WOOD Patricia": "wood-patricia",
    "WOOD Paul": "wood-paul",
    "WOOD Peter": "wood-peter",
    "WOOD R H": "wood-r-h",
    "WOOD Regina": "wood-regina",
    "WOOD Rosanna": "wood-rosanna",
    "WOOD Sharon": "wood-sharon",
    "WOOD Stanley": "wood-stanley",
    "WOOD Stanton": "wood-stanton",
    "WOOD Steve": "wood-steve",
    "WOOD Stuart": "wood-stuart",
    "WOOD Timmy": "wood-timmy",
    "WOOD Tom": "wood-tom",
    "WOOD Trevor": "wood-trevor",
    "WOOD Victoria": "wood-victoria",
    "WOOD Waylon": "wood-waylon",
    "WOOD JR Ed": "wood-jr-ed",
    "WOODALL Ed": "woodall-ed",
    "WOODARD Charlayne": "woodard-charlayne",
    "WOODARD Tamilla": "woodard-tamilla",
    "WOODBRIDGE Geoff": "woodbridge-geoff",
    "WOODBURN John": "woodburn-john",
    "WOODBURY Brian": "woodbury-brian",
    "WOODBURY Heather": "woodbury-heather",
    "WOODBURY Liz": "woodbury-liz",
    "WOODBURY Mary": "woodbury-mary",
    "WOODCOCK George": "woodcock-george",
    "WOODCOCK Roz": "woodcock-roz",
    "WOODCOCK Sally": "woodcock-sally",
    "WOODCOCK-STEWART Jaz": "woodcock-stewart-jaz",
    "WOODEN John A": "wooden-john-a",
    "WOODEN Rod": "wooden-rod",
    "WOODFIELD Murray": "woodfield-murray",
    "WOODFORD Dennis": "woodford-dennis",
    "WOODGATE Neil": "woodgate-neil",
    "WOODHEAD Christine": "woodhead-christine",
    "WOODHEAD Matthew": "woodhead-matthew",
    "WOODHEAD Russell": "woodhead-russell",
    "WOODHOUSE Hugh": "woodhouse-hugh",
    "WOODHOUSE Jayne": "woodhouse-jayne",
    "WOODHOUSE Joe": "woodhouse-joe",
    "WOODHOUSE Nique": "woodhouse-nique",
    "WOODIWISS John C": "woodiwiss-john-c",
    "WOODLEY Chris": "woodley-chris",
    "WOODLEY Thom": "woodley-thom",
    "WOODMAN Lance": "woodman-lance",
    "WOODROOFE Matilda": "woodroofe-matilda",
    "WOODROW Jane Carter": "woodrow-jane-carter",
    "WOODRUFF Paul": "woodruff-paul",
    "WOODRUFF Robert": "woodruff-robert",
    "WOODRUFF SANZ Louise": "woodruff-sanz-louise",
    "WOODS Aubrey": "woods-aubrey",
    "WOODS Billy": "woods-billy",
    "WOODS Carol M": "woods-carol-m",
    "WOODS Christopher": "woods-christopher",
    "WOODS David": "woods-david",
    "WOODS Don": "woods-don",
    "WOODS Doris": "woods-doris",
    "WOODS Effie": "woods-effie",
    "WOODS Eugenia": "woods-eugenia",
    "WOODS Jacqueline": "woods-jacqueline",
    "WOODS Jill": "woods-jill",
    "WOODS John": "woods-john",
    "WOODS John E": "woods-john-e",
    "WOODS Kat": "woods-kat",
    "WOODS Katie": "woods-katie",
    "WOODS Keith": "woods-keith",
    "WOODS Lance": "woods-lance",
    "WOODS Lief": "woods-lief",
    "WOODS Nathaniel": "woods-nathaniel",
    "WOODS Nick": "woods-nick",
    "WOODS Pat": "woods-pat",
    "WOODS Phil": "woods-phil",
    "WOODS Rosemarie": "woods-rosemarie",
    "WOODS Sarah": "woods-sarah",
    "WOODS Simon": "woods-simon",
    "WOODS Valerie": "woods-valerie",
    "WOODS Vincent": "woods-vincent",
    "WOODS Wind D": "woods-wind-d",
    "WOODSON James": "woodson-james",
    "WOODSON Michele": "woodson-michele",
    "WOODSON Wendy": "woodson-wendy",
    "WOODWARD Donald": "woodward-donald",
    "WOODWARD Greer": "woodward-greer",
    "WOODWARD Meredith Bain": "woodward-meredith-bain",
    "WOODWARD Nathan": "woodward-nathan",
    "WOODWARD Peter": "woodward-peter",
    "WOODWOOD Michael": "woodwood-michael",
    "WOODY Diana Lee": "woody-diana-lee",
    "WOOF Emily": "woof-emily",
    "WOOF NOVA COLLABORATION  ": "woof-nova-collaboration",
    "WOOLAVER Lance Gerard": "woolaver-lance-gerard",
    "WOOLDRIDGE Hugh": "wooldridge-hugh",
    "WOOLDRIDGE Ian": "wooldridge-ian",
    "WOOLDRIDGE John": "wooldridge-john",
    "WOOLERY Laurie": "woolery-laurie",
    "WOOLEY Edith": "wooley-edith",
    "WOOLEY Robert": "wooley-robert",
    "WOOLEY Sarah": "wooley-sarah",
    "WOOLEY Sophie": "wooley-sophie",
    "WOOLF Ben": "woolf-ben",
    "WOOLF Christine": "woolf-christine",
    "WOOLF Danielle": "woolf-danielle",
    "WOOLF Dennis": "woolf-dennis",
    "WOOLF Henry": "woolf-henry",
    "WOOLF James": "woolf-james",
    "WOOLF Jan": "woolf-jan",
    "WOOLF Jessica": "woolf-jessica",
    "WOOLF Noel": "woolf-noel",
    "WOOLFE Colin": "woolfe-colin",
    "WOOLFE Eric": "woolfe-eric",
    "WOOLFORD Julian": "woolford-julian",
    "WOOLFORD Keo": "woolford-keo",
    "WOOLLAND Brian": "woolland-brian",
    "WOOLLARD Jane": "woollard-jane",
    "WOOLLCOMBE Carol": "woollcombe-carol",
    "WOOLLEY Edythe": "woolley-edythe",
    "WOOLLEY Sophie": "woolley-sophie",
    "WOOLNOUGH Graham": "woolnough-graham",
    "WOOLNOUGH Verity Rose": "woolnough-verity-rose",
    "WOOLVERTON Linda": "woolverton-linda",
    "WOON Henry": "woon-henry",
    "WOON-PING Chin": "woon-ping-chin",
    "WOOSLEY Carolyn": "woosley-carolyn",
    "WOOSTER GROUP, THE ": "wooster-group-the",
    "WOOTEN Arthur": "wooten-arthur",
    "WOOTEN Jamie": "wooten-jamie",
    "WOOTEN John J": "wooten-john-j",
    "WORBOYES Sally": "worboyes-sally",
    "WORDEN Annie": "worden-annie",
    "WORDSWORTH Sara": "wordsworth-sara",
    "WORK Valerie": "work-valerie",
    "WORK THEATRE COLLECTIVE ": "work-theatre-collective",
    "WORKING Scott": "working-scott",
    "WORKMAN Hawksley": "workman-hawksley",
    "WORKMAN James": "workman-james",
    "WORKSHOP 5 ": "workshop-5",
    "WORMAN Martin": "worman-martin",
    "WORMS Jeannine": "worms-jeannine",
    "WORNER Philip": "worner-philip",
    "WORRALL Jessica": "worrall-jessica",
    "WORREST S": "worrest-s",
    "WORSFOLD Susan": "worsfold-susan",
    "WORSLEY Dale": "worsley-dale",
    "WORSLEY Eleanor": "worsley-eleanor",
    "WORSLEY Greer": "worsley-greer",
    "WORSLEY Rachel": "worsley-rachel",
    "WORSLEY Victoria": "worsley-victoria",
    "WORTH Ben": "worth-ben",
    "WORTH Irene": "worth-irene",
    "WORTH Joan": "worth-joan",
    "WORTH Katharine": "worth-katharine",
    "WORTH Mark": "worth-mark",
    "WORTH Martin": "worth-martin",
    "WORTH Ruth": "worth-ruth",
    "WORTH Zoe": "worth-zoe",
    "WORTHAM Frank": "wortham-frank",
    "WORTHINGTON Etta L": "worthington-etta-l",
    "WORTLEY Christopher": "wortley-christopher",
    "WORTON Jenny": "worton-jenny",
    "WOTHERSPOON Ralph": "wotherspoon-ralph",
    "WOTKOWSKI Lucas": "wotkowski-lucas",
    "WOUDSTRA Karst": "woudstra-karst",
    "WOUK Herman": "wouk-herman",
    "WOUK Pagoon Kang": "wouk-pagoon-kang",
    "WOULFE Richard": "woulfe-richard",
    "WOULTERS Liliane": "woulters-liliane",
    "WOYCHUK Denis": "woychuk-denis",
    "WOZNIAK Phil": "wozniak-phil",
    "WRANGLER Jack": "wrangler-jack",
    "WRATH Andres": "wrath-andres",
    "WRAY David": "wray-david",
    "WRAY Elizabeth": "wray-elizabeth",
    "WRAY Fay": "wray-fay",
    "WRAY Phoebe": "wray-phoebe",
    "WRAY Robert Alexander": "wray-robert-alexander",
    "WRECKIO ENSEMBLE ": "wreckio-ensemble",
    "WREFORD-SINNOTT Vici": "wreford-sinnott-vici",
    "WREGGITT Andrew": "wreggitt-andrew",
    "WREN Demetrius": "wren-demetrius",
    "WREN Ed": "wren-ed",
    "WREN Edward": "wren-edward",
    "WREN Edwina": "wren-edwina",
    "WREN James": "wren-james",
    "WREN Peter": "wren-peter",
    "WRENN Bradley": "wrenn-bradley",
    "WRENN Bradley K": "wrenn-bradley-k",
    "WRENN H A": "wrenn-h-a",
    "WRENN Mary Jett Parsley": "wrenn-mary-jett-parsley",
    "WRENSHAW Susi": "wrenshaw-susi",
    "WRENTMORE Stephen": "wrentmore-stephen",
    "WRIGGLESWORTH John": "wrigglesworth-john",
    "WRIGHT A Colin": "wright-a-colin",
    "WRIGHT Aaron L": "wright-aaron-l",
    "WRIGHT Alexa": "wright-alexa",
    "WRIGHT Alexander": "wright-alexander",
    "WRIGHT Alison": "wright-alison",
    "WRIGHT Anthony": "wright-anthony",
    "WRIGHT Art": "wright-art",
    "WRIGHT Barbara": "wright-barbara",
    "WRIGHT Bil": "wright-bil",
    "WRIGHT Bob": "wright-bob",
    "WRIGHT Brian": "wright-brian",
    "WRIGHT Caroline": "wright-caroline",
    "WRIGHT Charles William": "wright-charles-william",
    "WRIGHT Chris": "wright-chris",
    "WRIGHT Christopher": "wright-christopher",
    "WRIGHT Clifford": "wright-clifford",
    "WRIGHT Craig": "wright-craig",
    "WRIGHT D Gordon": "wright-d-gordon",
    "WRIGHT Damian": "wright-damian",
    "WRIGHT Damon": "wright-damon",
    "WRIGHT Davern": "wright-davern",
    "WRIGHT David": "wright-david",
    "WRIGHT David Anthony": "wright-david-anthony",
    "WRIGHT David D": "wright-david-d",
    "WRIGHT Denise": "wright-denise",
    "WRIGHT Desiree": "wright-desiree",
    "WRIGHT Dorothy": "wright-dorothy",
    "WRIGHT Doug": "wright-doug",
    "WRIGHT Drew": "wright-drew",
    "WRIGHT Eric": "wright-eric",
    "WRIGHT Gary": "wright-gary",
    "WRIGHT Hilary Hadley": "wright-hilary-hadley",
    "WRIGHT Isabel": "wright-isabel",
    "WRIGHT Jacqueline": "wright-jacqueline",
    "WRIGHT James 'tappy'": "wright-james-tappy",
    "WRIGHT Jarret": "wright-jarret",
    "WRIGHT Jason": "wright-jason",
    "WRIGHT Jayne": "wright-jayne",
    "WRIGHT Jimmi": "wright-jimmi",
    "WRIGHT John": "wright-john",
    "WRIGHT Jonathan": "wright-jonathan",
    "WRIGHT Joseph Samuel": "wright-joseph-samuel",
    "WRIGHT Julia": "wright-julia",
    "WRIGHT K Siobhan": "wright-k-siobhan",
    "WRIGHT Lawrence": "wright-lawrence",
    "WRIGHT Lorna": "wright-lorna",
    "WRIGHT Luke": "wright-luke",
    "WRIGHT Mary-Anne Elizabeth": "wright-mary-anne-elizabeth",
    "WRIGHT Matthew": "wright-matthew",
    "WRIGHT Michael": "wright-michael",
    "WRIGHT Nathan": "wright-nathan",
    "WRIGHT Natii": "wright-natii",
    "WRIGHT Nicholas": "wright-nicholas",
    "WRIGHT Nick": "wright-nick",
    "WRIGHT Polly": "wright-polly",
    "WRIGHT R Hamilton": "wright-r-hamilton",
    "WRIGHT Rebecca": "wright-rebecca",
    "WRIGHT Richard": "wright-richard",
    "WRIGHT Robert": "wright-robert",
    "WRIGHT Samantha": "wright-samantha",
    "WRIGHT Sheila": "wright-sheila",
    "WRIGHT Stephen J": "wright-stephen-j",
    "WRIGHT Steve": "wright-steve",
    "WRIGHT Steven": "wright-steven",
    "WRIGHT Sue Ellen": "wright-sue-ellen",
    "WRIGHT T": "wright-t",
    "WRIGHT Tim": "wright-tim",
    "WRIGHT Tobias": "wright-tobias",
    "WRIGHT Tom": "wright-tom",
    "WRIGHT Tom (1)": "wright-tom-1",
    "WRIGHT Tom (2)": "wright-tom-2",
    "WRIGHT Tony": "wright-tony",
    "WRIGHT William H": "wright-william-h",
    "WRIGHT Yha Mourhia D": "wright-yha-mourhia-d",
    "WRIGHT JR John Leo": "wright-jr-john-leo",
    "WRIGHTSON Daryl": "wrightson-daryl",
    "WRIGLEY Sheena": "wrigley-sheena",
    "WRITES Sekou": "writes-sekou",
    "WROE Malcolm": "wroe-malcolm",
    "WRONG CROWD ": "wrong-crowd",
    "WRONSKI Szczesny": "wronski-szczesny"
  }
};