export default {
  "metadata": {
    "results": 80,
    "timeStamp": "2025-12-05T21:32:20.708Z",
    "url": "https://www.doollee.com/PlaywrightsW/W_playwrights_s-z.php"
  },
  "authors": {
    "WU Charles Quianzhi": "wu-charles-quianzhi",
    "WU Jade": "wu-jade",
    "WU Jianguo": "wu-jianguo",
    "WU Jing-Jyi": "wu-jing-jyi",
    "WU Joyce": "wu-joyce",
    "WU Simon": "wu-simon",
    "WU Sophie": "wu-sophie",
    "WUEHLER Ann": "wuehler-ann",
    "WULFFHART Michael": "wulffhart-michael",
    "WULP John": "wulp-john",
    "WUNDERLICH Larry": "wunderlich-larry",
    "WUNDERLIN Julie": "wunderlin-julie",
    "WUOLIJOKI Hella": "wuolijoki-hella",
    "WURLITZER Rudolph": "wurlitzer-rudolph",
    "WURRE WURRE ": "wurre-wurre",
    "WURTH Ines": "wurth-ines",
    "WURTZEL David": "wurtzel-david",
    "WURZINGER Frank": "wurzinger-frank",
    "WYANT Lynne": "wyant-lynne",
    "WYATT Alexa": "wyatt-alexa",
    "WYATT C S": "wyatt-c-s",
    "WYATT Colin": "wyatt-colin",
    "WYATT E A": "wyatt-e-a",
    "WYATT Eliza": "wyatt-eliza",
    "WYATT Elizabeth": "wyatt-elizabeth",
    "WYATT Keith": "wyatt-keith",
    "WYATT Marlow": "wyatt-marlow",
    "WYATT Matt": "wyatt-matt",
    "WYATT Rachel": "wyatt-rachel",
    "WYATT Randy": "wyatt-randy",
    "WYATT Sally": "wyatt-sally",
    "WYATT Stephen": "wyatt-stephen",
    "WYATT William": "wyatt-william",
    "WYATT Woodrow": "wyatt-woodrow",
    "WYATTE Farcita": "wyatte-farcita",
    "WYCHE Ronald": "wyche-ronald",
    "WYCHERLEY William": "wycherley-william",
    "WYCOFF Anne": "wycoff-anne",
    "WYE Angela": "wye-angela",
    "WYER Pete M": "wyer-pete-m",
    "WYETH Geo": "wyeth-geo",
    "WYKES Walter": "wykes-walter",
    "WYLD Hazel": "wyld-hazel",
    "WYLIE Annie": "wylie-annie",
    "WYLIE Betty Jane": "wylie-betty-jane",
    "WYLIE Jamie": "wylie-jamie",
    "WYLIE Kim Esop": "wylie-kim-esop",
    "WYLIE Laurie": "wylie-laurie",
    "WYLIE Norman": "wylie-norman",
    "WYLIE Stephen": "wylie-stephen",
    "WYLIE Sue": "wylie-sue",
    "WYLLIE Carolyn": "wyllie-carolyn",
    "WYLLIE David": "wyllie-david",
    "WYLLIE George": "wyllie-george",
    "WYLLIE Rosalind": "wyllie-rosalind",
    "WYMAN Joel": "wyman-joel",
    "WYMARK Olwen": "wymark-olwen",
    "WYN Heledd": "wyn-heledd",
    "WYNDHAM Asher": "wyndham-asher",
    "WYNDHAM-BELL Sherlock": "wyndham-bell-sherlock",
    "WYNER Barry": "wyner-barry",
    "WYNGATE Valerie": "wyngate-valerie",
    "WYNN Anthony": "wynn-anthony",
    "WYNN Ed": "wynn-ed",
    "WYNN Valerie": "wynn-valerie",
    "WYNNE Frank": "wynne-frank",
    "WYNNE Michael": "wynne-michael",
    "WYNNE-SIMMONS Robert": "wynne-simmons-robert",
    "WYNNE-WILLSON Peter": "wynne-willson-peter",
    "WYNTER Sylvia": "wynter-sylvia",
    "WYNTERS Chris": "wynters-chris",
    "WYRICK Mark": "wyrick-mark",
    "WYRICK Rebecca": "wyrick-rebecca",
    "WYSE Alex": "wyse-alex",
    "WYSE Lois": "wyse-lois",
    "WYSPIANSKI Stanislaw": "wyspianski-stanislaw",
    "WYSS Mark": "wyss-mark",
    "WYSSBROD Peter": "wyssbrod-peter",
    "WYTHE Laurence": "wythe-laurence",
    "WYVILL Kate": "wyvill-kate"
  }
};