export default {
  "metadata": {
    "results": 162,
    "timeStamp": "2025-12-05T21:32:27.421Z",
    "url": "https://www.doollee.com/PlaywrightsY/Y_playwrights_a-f.php"
  },
  "authors": {
    "YABLON Sharon": "yablon-sharon",
    "YABLONSKAYA Anna": "yablonskaya-anna",
    "YABLONSKY Yabo": "yablonsky-yabo",
    "YACO Pamela D": "yaco-pamela-d",
    "YACOUBI Ahmed": "yacoubi-ahmed",
    "YACOWITZ Caryn": "yacowitz-caryn",
    "YACYK Gabriella": "yacyk-gabriella",
    "YADAV Anu": "yadav-anu",
    "YAEGER Teddi": "yaeger-teddi",
    "YAFFE James": "yaffe-james",
    "YAGED Kim": "yaged-kim",
    "YAGER Jan": "yager-jan",
    "YAHP Beth": "yahp-beth",
    "YAHYAWI Samer": "yahyawi-samer",
    "YAITAINES Genna": "yaitaines-genna",
    "YAJKO Tony": "yajko-tony",
    "YAKIM Mina": "yakim-mina",
    "YAKIM Moni": "yakim-moni",
    "YAKIMOV Igor": "yakimov-igor",
    "YALE Kathleen Betsko": "yale-kathleen-betsko",
    "YALE Michael": "yale-michael",
    "YALFANI Mohsen": "yalfani-mohsen",
    "YALINIDREAM ": "yalinidream",
    "YALKUT Carolyn": "yalkut-carolyn",
    "YALMAN Tunc": "yalman-tunc",
    "YALOF Helen": "yalof-helen",
    "YALOM Ben": "yalom-ben",
    "YAMADA Natsuko": "yamada-natsuko",
    "YAMAGIWA ALFARO Rosanna": "yamagiwa-alfaro-rosanna",
    "YAMAMOTO Nami": "yamamoto-nami",
    "YAMAMURA Tim": "yamamura-tim",
    "YAMANAKA You-Ri": "yamanaka-you-ri",
    "YAMASHITA Karen Tei": "yamashita-karen-tei",
    "YAMAUCHI Wakako": "yamauchi-wakako",
    "YAMIN Eli": "yamin-eli",
    "YAN Li": "yan-li",
    "YAN Stephen": "yan-stephen",
    "YAN Xia": "yan-xia",
    "YANAGI Miwa": "yanagi-miwa",
    "YANAIHARA Mikuni": "yanaihara-mikuni",
    "YANCEY Dwayne": "yancey-dwayne",
    "YANCEY Phillip": "yancey-phillip",
    "YANELLI Bernard": "yanelli-bernard",
    "YANES Marianella": "yanes-marianella",
    "YANEZ Diana": "yanez-diana",
    "YANG Cha": "yang-cha",
    "YANG Jo": "yang-jo",
    "YANG Rob": "yang-rob",
    "YANG Sherie": "yang-sherie",
    "YANG Welly": "yang-welly",
    "YANG William": "yang-william",
    "YANIV Perri": "yaniv-perri",
    "YANKEE Luke": "yankee-luke",
    "YANKOWITZ Susan": "yankowitz-susan",
    "YANOMI ": "yanomi",
    "YAP Adeline": "yap-adeline",
    "YAPP Caitlin": "yapp-caitlin",
    "YARA ARTS GROUP ": "yara-arts-group",
    "YARAMA Neil": "yarama-neil",
    "YARBOROUGH John": "yarborough-john",
    "YARBOUGH Camille": "yarbough-camille",
    "YARBROUGH John": "yarbrough-john",
    "YARCHUN Deborah": "yarchun-deborah",
    "YARDLEY Nick": "yardley-nick",
    "YARJAH Maria": "yarjah-maria",
    "YARKER James": "yarker-james",
    "YARMOLINSKY Ben": "yarmolinsky-ben",
    "YARNALL Robert": "yarnall-robert",
    "YARROW Peter": "yarrow-peter",
    "YARSKY Michael": "yarsky-michael",
    "YASHI Seiichi": "yashi-seiichi",
    "YASHIN Allan": "yashin-allan",
    "YASHIRO Seiichi": "yashiro-seiichi",
    "YASTREMSKY Slava": "yastremsky-slava",
    "YASUR Itai": "yasur-itai",
    "YATES G D": "yates-g-d",
    "YATES Genevieve": "yates-genevieve",
    "YATES Graham": "yates-graham",
    "YATES J Michael": "yates-j-michael",
    "YATES Jenny": "yates-jenny",
    "YATES John": "yates-john",
    "YATES Karen": "yates-karen",
    "YATES Larry R": "yates-larry-r",
    "YATES Lizzi": "yates-lizzi",
    "YATES Michael": "yates-michael",
    "YATES Mick": "yates-mick",
    "YATES P": "yates-p",
    "YATES Paula": "yates-paula",
    "YATES Peter": "yates-peter",
    "YATES Robert": "yates-robert",
    "YATES Sonia": "yates-sonia",
    "YATES Tony": "yates-tony",
    "YATES Valmarie": "yates-valmarie",
    "YATSUNOV Artem": "yatsunov-artem",
    "YATTE James": "yatte-james",
    "YAVIN Naftali": "yavin-naftali",
    "YAW Sandra": "women-s-theatre-group",
    "YAWNEY Michael": "yawney-michael",
    "YAZBEC David": "yazbec-david",
    "YAZBEK Samir": "yazbek-samir",
    "YAZJI Liwaa": "yazji-liwaa",
    "YAZZIE Rhiana": "yazzie-rhiana",
    "YBARRA Stephanie": "ybarra-stephanie",
    "YDE Bob": "yde-bob",
    "YEAGER Delaney": "yeager-delaney",
    "YEAGER Jean W": "yeager-jean-w",
    "YEAGER MacKenzie": "yeager-mackenzie",
    "YEAGER Ruff": "yeager-ruff",
    "YEAKLE David": "yeakle-david",
    "YEAMAN Mike": "yeaman-mike",
    "YEARLEY John": "yearley-john",
    "YEATES Amy Powell": "yeates-amy-powell",
    "YEATES Cara": "yeates-cara",
    "YEATMAN James": "yeatman-james",
    "YEATON Dana": "yeaton-dana",
    "YEATS Jack B": "yeats-jack-b",
    "YEATS William Butler": "yeats-william-butler",
    "YEE Adam": "yee-adam",
    "YEE Betty Jane": "yee-betty-jane",
    "YEE Byron": "yee-byron",
    "YEE Carsey": "yee-carsey",
    "YEE David": "yee-david",
    "YEE Ivy": "yee-ivy",
    "YEE Lauren D": "yee-lauren-d",
    "YEGER Sheila": "yeger-sheila",
    "YEGHIAZARIAN Torange": "yeghiazarian-torange",
    "YEH Ching": "yeh-ching",
    "YELAVICH Blake": "yelavich-blake",
    "YELDHAM Peter": "yeldham-peter",
    "YELLAND T E": "yelland-t-e",
    "YELLEN Jack": "yellen-jack",
    "YELLEN Sherman": "yellen-sherman",
    "YELLOW EARTH THEATRE COMPANY ": "yellow-earth-theatre-company",
    "YELLOW ROBE JR William S": "yellow-robe-jr-william-s",
    "YELVINGTON Ramsey": "yelvington-ramsey",
    "YEN Anna": "yen-anna",
    "YENSER Chase Allen": "yenser-chase-allen",
    "YEO Amanda": "yeo-amanda",
    "YEOH Ben": "yeoh-ben",
    "YEOH Benjamin": "yeoh-benjamin",
    "YEOH Patrick": "yeoh-patrick",
    "YEOMAN Cal": "yeoman-cal",
    "YEOMAN Ian": "yeoman-ian",
    "YEOMAN Joann": "yeoman-joann",
    "YEOMANS Cal": "yeomans-cal",
    "YEOMANS Marianne": "yeomans-marianne",
    "YEP Lawrence": "yep-lawrence",
    "YERBY Lorees": "yerby-lorees",
    "YERGEAU Melanie": "yergeau-melanie",
    "YEROFEYEV Venedikt": "yerofeyev-venedikt",
    "YERUSHALMI Rina": "yerushalmi-rina",
    "YES David": "yes-david",
    "YES/NO PEOPLE ": "yes-no-people",
    "YESNOWITZ Amanda": "yesnowitz-amanda",
    "YESTON Maury": "yeston-maury",
    "YESUTIS Joseph": "yesutis-joseph",
    "YEUNG Norman": "yeung-norman",
    "YEUNG Ray": "yeung-ray",
    "YEVTUSHENKO Sasha": "yevtushenko-sasha",
    "YEW Chay": "yew-chay",
    "YEW Jeanette Oi-Suk": "yew-jeanette-oi-suk",
    "YEXIN Sha": "yexin-sha"
  }
};