export default {
  "metadata": {
    "results": 144,
    "timeStamp": "2025-12-05T21:32:33.681Z",
    "url": "https://www.doollee.com/PlaywrightsY/Y_playwrights_m-r.php"
  },
  "authors": {
    "YNYR Iola": "ynyr-iola",
    "YOCKEY Christopher": "yockey-christopher",
    "YOCKEY Steve": "yockey-steve",
    "YOCUM Sue": "yocum-sue",
    "YODER Rachel": "yoder-rachel",
    "YOGA Tripsichore": "yoga-tripsichore",
    "YOHANNES Miebaka": "yohannes-miebaka",
    "YOHE Tom": "yohe-tom",
    "YOKKO ": "yokko",
    "YOKOMORI Eric": "yokomori-eric",
    "YOLI ": "yoli",
    "YON Odon": "yon-odon",
    "YONDORF Wendy": "yondorf-wendy",
    "YONGE Jane": "yonge-jane",
    "YONKER Donald": "yonker-donald",
    "YOO Mia": "yoo-mia",
    "YOO-KIM Jin": "yoo-kim-jin",
    "YOON Bora": "yoon-bora",
    "YOON Jean": "yoon-jean",
    "YORCK Ruth Landshoff": "yorck-ruth-landshoff",
    "YORDAN Philip": "yordan-philip",
    "YORDY Jonathan": "yordy-jonathan",
    "YORIO Justin": "yorio-justin",
    "YORK Daniel": "york-daniel",
    "YORK Desiree Kristine": "york-desiree-kristine",
    "YORK Duke": "york-duke",
    "YORK Micky": "york-micky",
    "YORK Susannah": "york-susannah",
    "YORK Y": "york-y",
    "YORKEY Brian": "yorkey-brian",
    "YORKSHIRE ACTORS' COMPANY ": "yorkshire-actors-company",
    "YOSHIDA Kyoko": "yoshida-kyoko",
    "YOSHIMURA Connie": "yoshimura-connie",
    "YOSHIMURA James": "yoshimura-james",
    "YOSIPHON Lilac": "yosiphon-lilac",
    "YOSKOWITZ Jason": "yoskowitz-jason",
    "YOSOWITZ Philip": "yosowitz-philip",
    "YOSUSEF Marcus": "yosusef-marcus",
    "YOUDELL Rebecca": "youdell-rebecca",
    "YOUMANS William": "youmans-william",
    "YOUNG Alex Paul": "young-alex-paul",
    "YOUNG Allison": "young-allison",
    "YOUNG Andrew": "young-andrew",
    "YOUNG Ann Liv": "young-ann-liv",
    "YOUNG Anthony": "young-anthony",
    "YOUNG Ben": "young-ben",
    "YOUNG Benny": "young-benny",
    "YOUNG Blyth": "young-blyth",
    "YOUNG Caryl Gabrielle": "young-caryl-gabrielle",
    "YOUNG Clifford W": "young-clifford-w",
    "YOUNG Cy": "young-cy",
    "YOUNG Dalene": "young-dalene",
    "YOUNG Daniel Ray": "young-daniel-ray",
    "YOUNG Darren": "young-darren",
    "YOUNG Dave": "young-dave",
    "YOUNG David": "young-david",
    "YOUNG David (1)": "young-david-1",
    "YOUNG David L": "young-david-l",
    "YOUNG David S": "young-david-s",
    "YOUNG d'bi": "young-d-bi",
    "YOUNG Douglas": "young-douglas",
    "YOUNG Douglas C C": "young-douglas-c-c",
    "YOUNG Drew": "young-drew",
    "YOUNG Emily": "young-emily",
    "YOUNG Frank M": "young-frank-m",
    "YOUNG G H R": "young-g-h-r",
    "YOUNG Gaetan": "young-gaetan",
    "YOUNG Gail": "young-gail",
    "YOUNG Gail (1)": "young-gail-1",
    "YOUNG Gary": "young-gary",
    "YOUNG Gary (1)": "young-gary-1",
    "YOUNG Gina": "young-gina",
    "YOUNG Isabel Adomakoh": "young-isabel-adomakoh",
    "YOUNG Jason": "young-jason",
    "YOUNG Jeff": "young-jeff",
    "YOUNG Jeffrey": "young-jeffrey",
    "YOUNG Jerald Thomas": "young-jerald-thomas",
    "YOUNG Jingan": "young-jingan",
    "YOUNG Jonathan": "young-jonathan",
    "YOUNG Jonathan Taylor": "young-jonathan-taylor",
    "YOUNG Jordan R": "young-jordan-r",
    "YOUNG Joshua": "young-joshua",
    "YOUNG Justin": "young-justin",
    "YOUNG Karen": "young-karen",
    "YOUNG Kimberly": "young-kimberly",
    "YOUNG L Martina": "young-l-martina",
    "YOUNG Lee": "young-lee",
    "YOUNG Louisa": "young-louisa",
    "YOUNG Lucien": "young-lucien",
    "YOUNG Malcolm": "young-malcolm",
    "YOUNG Margaret Blair": "young-margaret-blair",
    "YOUNG Mark": "young-mark",
    "YOUNG Matt": "young-matt",
    "YOUNG Morna": "young-morna",
    "YOUNG Murray Lachlan": "young-murray-lachlan",
    "YOUNG Nic": "young-nic",
    "YOUNG Noreen": "young-noreen",
    "YOUNG O": "young-o",
    "YOUNG Owl": "young-owl",
    "YOUNG Patrick": "young-patrick",
    "YOUNG Patrick Eakin": "young-patrick-eakin",
    "YOUNG Paul": "young-paul",
    "YOUNG Paul David": "young-paul-david",
    "YOUNG Perry Deane": "young-perry-deane",
    "YOUNG Peter": "young-peter",
    "YOUNG Phil": "young-phil",
    "YOUNG Rachael": "young-rachael",
    "YOUNG Raymond": "young-raymond",
    "YOUNG Richard T": "young-richard-t",
    "YOUNG Rob": "young-rob",
    "YOUNG Sandra": "young-sandra",
    "YOUNG Sarah-Louise": "young-sarah-louise",
    "YOUNG Scott": "young-scott",
    "YOUNG Stanley": "young-stanley",
    "YOUNG Stark": "young-stark",
    "YOUNG Steven": "young-steven",
    "YOUNG Toby": "young-toby",
    "YOUNG Tracy": "young-tracy",
    "YOUNG William": "young-william",
    "YOUNG William B": "young-william-b",
    "YOUNG William R": "young-william-r",
    "YOUNG Willie Fong": "young-willie-fong",
    "YOUNG ARTISTS COUNCIL (YAC)  ": "young-artists-council",
    "YOUNG AT ART ": "young-at-art",
    "YOUNG III Clarence": "young-iii-clarence",
    "YOUNGBLOOD Shay": "youngblood-shay",
    "YOUNGER Greg": "younger-greg",
    "YOUNGER Kelly": "younger-kelly",
    "YOUNGER Martin": "younger-martin",
    "YOUNGER Rick": "younger-rick",
    "YOUNGERMAN Ethan": "youngerman-ethan",
    "YOUNGHUSBAND Carol": "younghusband-carol",
    "YOUNGHUSBAND Dominic": "younghusband-dominic",
    "YOUNGKINS Jerry": "youngkins-jerry",
    "YOUNGMAN Stephanie": "youngman-stephanie",
    "YOUNGQUIST Marion H": "youngquist-marion-h",
    "YOUNIS Madani": "younis-madani",
    "YOUNIS Sam": "younis-sam",
    "YOUNKIN Carol": "younkin-carol",
    "YOURGRAU Tug": "yourgrau-tug",
    "YOUSSEF Marcus": "youssef-marcus",
    "YOUSSEF Sarah": "youssef-sarah",
    "YOUSTRA Christopher": "youstra-christopher",
    "YOVICH Ursula": "yovich-ursula"
  }
};