export default {
  "metadata": {
    "results": 172,
    "timeStamp": "2025-12-05T21:32:40.249Z",
    "url": "https://www.doollee.com/PlaywrightsZ/Z_playwrights_a-f.php"
  },
  "authors": {
    "Z Pamela": "z-pamela",
    "ZABLE Arnold": "zable-arnold",
    "ZABLOTSKY Peter": "zablotsky-peter",
    "ZABORSKI Kathy": "zaborski-kathy",
    "ZABRAMNY Lucian": "zabramny-lucian",
    "ZAC David": "zac-david",
    "ZACARIAS Karen": "zacarias-karen",
    "ZACARIAS Ken": "zacarias-ken",
    "ZACCAR Eric": "zaccar-eric",
    "ZACCARIA Gary N": "zaccaria-gary-n",
    "ZACCARINI John Paul": "zaccarini-john-paul",
    "ZACEK Ray": "zacek-ray",
    "ZACHARI Peter": "zachari-peter",
    "ZACHARIAS Paul": "zacharias-paul",
    "ZACHARIASEN Gunnva": "zachariasen-gunnva",
    "ZACHARKO Larry": "zacharko-larry",
    "ZACHARY Alan": "zachary-alan",
    "ZACHARY Peter": "zachary-peter",
    "ZACHARY Saul": "zachary-saul",
    "ZACK Manuel": "zack-manuel",
    "ZACK Thomas W": "zack-thomas-w",
    "ZADE Maja": "zade-maja",
    "ZADEH Yasmin": "zadeh-yasmin",
    "ZADEK Zack": "zadek-zack",
    "ZADEL Andrew": "zadel-andrew",
    "ZADRA Dirk": "zadra-dirk",
    "ZADRAVEC Stefanie": "zadravec-stefanie",
    "ZAFFARANO Julie": "zaffarano-julie",
    "ZAFIR Elan": "zafir-elan",
    "ZAGER James": "zager-james",
    "ZAGET Bill": "zaget-bill",
    "ZAGONE Nick": "zagone-nick",
    "ZAGOREN Marc Alan": "zagoren-marc-alan",
    "ZAGREB YOUTH THEATRE OF COROATIA ": "zagreb-youth-theatre",
    "ZAGREDA Elza": "zagreda-elza",
    "ZAHN Curtis": "zahn-curtis",
    "ZAHRA Trevor": "zahra-trevor",
    "ZAILLIAN Nicholas": "zaillian-nicholas",
    "ZAITCHIK Daniel": "zaitchik-daniel",
    "ZAJAC Frank": "zajac-frank",
    "ZAJAC Matthew": "zajac-matthew",
    "ZAJDLIC Richard": "zajdlic-richard",
    "ZAJKO Betsy": "zajko-betsy",
    "ZAKARIAN Abi": "zakarian-abi",
    "ZAKKAI Jamil": "zakkai-jamil",
    "ZAKOSTELECKY Marek": "zakostelecky-marek",
    "ZAKOVA Vladimira": "zakova-vladimira",
    "ZALBEN Alex": "zalben-alex",
    "ZALBEN Jonathan": "zalben-jonathan",
    "ZALESINSKI Czarek": "zalesinski-czarek",
    "ZALEVSKY Dan": "zalevsky-dan",
    "ZALEY Jonathan M": "zaley-jonathan-m",
    "ZALMA Thea R": "zalma-thea-r",
    "ZALOOM Paul": "zaloom-paul",
    "ZAM Laura": "zam-laura",
    "ZAM Michael": "zam-michael",
    "ZAMAN Bobby": "zaman-bobby",
    "ZAMAN David": "zaman-david",
    "ZAMAN Hamza": "zaman-hamza",
    "ZAMAN Nancy Ann": "zaman-nancy-ann",
    "ZAMBETTI Elisabeth": "zambetti-elisabeth",
    "ZAMBO Clay": "zambo-clay",
    "ZAMBRANO Erik": "zambrano-erik",
    "ZAMM Michael": "zamm-michael",
    "ZAMMIT Nathan": "zammit-nathan",
    "ZAMPARUTTI Louise": "zamparutti-louise",
    "ZANCADA Antonio": "zancada-antonio",
    "ZANDER Peter": "zander-peter",
    "ZANE Adam": "zane-adam",
    "ZANGANA Rebin": "zangana-rebin",
    "ZANIBONI Kathryn": "zaniboni-kathryn",
    "ZANK Ric": "zank-ric",
    "ZANN Lenore": "zann-lenore",
    "ZAPAROWSKI Rick": "zaparowski-rick",
    "ZAPATA Carmen": "zapata-carmen",
    "ZAPATA Frank": "zapata-frank",
    "ZAPHIROPOULOU Angeliki": "zaphiropoulou-angeliki",
    "ZAPOLSKA Gabriella": "zapolska-gabriella",
    "ZAPOR John Randolph": "zapor-john-randolph",
    "ZAPPA Frank": "zappa-frank",
    "ZAPPA William": "zappa-william",
    "ZAPPAROLI Anna": "zapparoli-anna",
    "ZARATE Manuel": "zarate-manuel",
    "ZARAY Nicole": "zaray-nicole",
    "ZARECKI Phil Alan": "zarecki-phil-alan",
    "ZARECOR Janet": "zarecor-janet",
    "ZARILLO-GOULDIN Maggie": "zarillo-gouldin-maggie",
    "ZARITT Jesse": "zaritt-jesse",
    "ZARK Jenna": "zark-jenna",
    "ZARKIN Taylor": "zarkin-taylor",
    "ZARKO David": "zarko-david",
    "ZARRILLI Phillip": "zarrilli-phillip",
    "ZARROW Joe": "zarrow-joe",
    "ZASKO Elison": "zasko-elison",
    "ZASKY Derek": "zasky-derek",
    "ZASLOW Bob": "zaslow-bob",
    "ZATLIN Phyllis": "zatlin-phyllis",
    "ZAUBLER Elizabeth": "zaubler-elizabeth",
    "ZAVALA Hector": "zavala-hector",
    "ZAVARCE Alirio": "zavarce-alirio",
    "ZAVERI Bhadrakant": "zaveri-bhadrakant",
    "ZAVIN Benjamin": "zavin-benjamin",
    "ZAWADI Tantra": "zawadi-tantra",
    "ZAWADSKY Pat": "zawadsky-pat",
    "ZAY Tim": "zay-tim",
    "ZAYAS Jose": "zayas-jose",
    "ZAZZERA Stefano": "zazzera-stefano",
    "ZBIB Maya": "zbib-maya",
    "ZDARSKY Nicole": "zdarsky-nicole",
    "ZDYB Val": "zdyb-val",
    "ZDZIARSKI John": "zdziarski-john",
    "ZEAL Eleanor": "zeal-eleanor",
    "ZEANE Tony": "zeane-tony",
    "ZEBOOKER James": "zebooker-james",
    "ZECCOLA Joseph": "zeccola-joseph",
    "ZEDER Suzan": "zeder-suzan",
    "ZEDNIK Peter": "zednik-peter",
    "ZEE Eric Michael": "zee-eric-michael",
    "ZEEDERBERG Sharlene": "zeederberg-sharlene",
    "ZEEKTECH PRODUCTIONS ": "zeektech-productions",
    "ZEELANDBERG Lynn": "zeelandberg-lynn",
    "ZEEVI Yael (Yaya)": "zeevi-yael",
    "ZEFFIRO William": "zeffiro-william",
    "ZEGERMAN Alexis": "zegerman-alexis",
    "ZEGFELD Peter": "zegfeld-peter",
    "ZEGURA Mary": "zegura-mary",
    "ZEHENTBAUER Anna": "zehentbauer-anna",
    "ZEHETBAUER Alex": "zehetbauer-alex",
    "ZEIG Sande": "zeig-sande",
    "ZEIGER Henry": "zeiger-henry",
    "ZEIGER Shara Ashley": "zeiger-shara-ashley",
    "ZEINER Katie": "zeiner-katie",
    "ZEISSLER Paul Robert": "zeissler-paul-robert",
    "ZEITLER Amanda": "zeitler-amanda",
    "ZEITLIN Stanley": "zeitlin-stanley",
    "ZEITOUN Mary Lou": "zeitoun-mary-lou",
    "ZEL Allison Eve": "zel-allison-eve",
    "ZELDIN Alexander": "zeldin-alexander",
    "ZELENKA Petr": "zelenka-petr",
    "ZELEVINSKY Vladimir": "zelevinsky-vladimir",
    "ZELL Allison Eve": "zell-allison-eve",
    "ZELL Fran": "zell-fran",
    "ZELLER Felicia": "zeller-felicia",
    "ZELLER Florian": "zeller-florian",
    "ZELLER Joshua": "zeller-joshua",
    "ZELLER-ALEXIS Dana": "zeller-alexis-dana",
    "ZELLERS Rob": "zellers-rob",
    "ZELLERS Ron": "zellers-ron",
    "ZELLIOT Eleanor": "zelliot-eleanor",
    "ZELLNER Daniel": "zellner-daniel",
    "ZELLNIK David": "zellnik-david",
    "ZELLNIK Joseph S": "zellnik-joseph-s",
    "ZEMAN Jack": "zeman-jack",
    "ZEMECKIS Robert": "zemeckis-robert",
    "ZEMNIKIS Kelly Aija": "zemnikis-kelly-aija",
    "ZENDEH ": "zendeh",
    "ZENTZ Bob": "zentz-bob",
    "ZEPER Fran Waller": "zeper-fran-waller",
    "ZEPHANIAH Benjamin": "zephaniah-benjamin",
    "ZEPH-SOLOMON ": "zeph-solomon",
    "ZEPPA Justin": "zeppa-justin",
    "ZERCHER Sarah": "zercher-sarah",
    "ZEREGA Diane": "zerega-diane",
    "ZERLIN JR Walter": "zerlin-jr-walter",
    "ZEROTH Rich": "zeroth-rich",
    "ZERTUCHE Tony": "zertuche-tony",
    "ZERVUDACHI Laki": "zervudachi-laki",
    "ZEST THEATRE ": "zest-theatre",
    "ZETTELMAIER Joseph": "zettelmaier-joseph",
    "ZETTLER Michael": "zettler-michael",
    "ZETTS Mickey": "zetts-mickey",
    "ZEYTUNTSYAN Berge": "zeytuntsyan-berge"
  }
};