export default {
  "metadata": {
    "results": 92,
    "timeStamp": "2025-12-05T21:32:42.977Z",
    "url": "https://www.doollee.com/PlaywrightsZ/Z_playwrights_g-l.php"
  },
  "authors": {
    "ZGULADZE Ekha": "zguladze-ekha",
    "ZHADAN Serhiy": "zhadan-serhiy",
    "ZHAMBALOV Erzhena": "zhambalov-erzhena",
    "ZHAMBALOV Sayan": "zhambalov-sayan",
    "ZHAO Bing": "zhao-bing",
    "ZHIXIANG Qi": "zhixiang-qi",
    "ZHONG Estelle": "zhong-estelle",
    "ZHOU Jojo": "zhou-jojo",
    "ZHOU Simon": "zhou-simon",
    "ZI Michael Li Cha": "zi-michael-li-cha",
    "ZIA Aisha": "zia-aisha",
    "ZIALCITA V F": "zialcita-v-f",
    "ZIAS Pete": "zias-pete",
    "ZIBART Rosemary": "zibart-rosemary",
    "ZICCONE Matt": "ziccone-matt",
    "ZICCONE Matthew": "ziccone-matthew",
    "ZIDE Shane": "zide-shane",
    "ZIEBART Laren": "ziebart-laren",
    "ZIEBER Iris": "zieber-iris",
    "ZIEGENHAGEN Eric": "ziegenhagen-eric",
    "ZIEGFELD Derek": "ziegfeld-derek",
    "ZIEGLER Anna": "ziegler-anna",
    "ZIEGLER Francis J": "ziegler-francis-j",
    "ZIEGLER Irene": "ziegler-irene",
    "ZIEGLER Tom": "ziegler-tom",
    "ZIEMKE Lydia": "ziemke-lydia",
    "ZIEN Chip": "zien-chip",
    "ZIERING Linda A": "ziering-linda-a",
    "ZIEROLD Jack": "zierold-jack",
    "ZIFF Amy": "ziff-amy",
    "ZIFFER Arthur": "ziffer-arthur",
    "ZIGUN Dick": "zigun-dick",
    "ZILBER Howard": "zilber-howard",
    "ZILBERMAN Aaron": "zilberman-aaron",
    "ZILBERMAN Boris": "zilberman-boris",
    "ZILBOORG Gregory": "zilboorg-gregory",
    "ZILL Nicholas": "zill-nicholas",
    "ZILLMER H Lawrence": "zillmer-h-lawrence",
    "ZIMDAHL Catherine": "zimdahl-catherine",
    "ZIMET Paul": "zimet-paul",
    "ZIMMER Eleanor": "zimmer-eleanor",
    "ZIMMER Jacob": "zimmer-jacob",
    "ZIMMERMAN Aphra": "zimmerman-aphra",
    "ZIMMERMAN David R": "zimmerman-david-r",
    "ZIMMERMAN Guy": "zimmerman-guy",
    "ZIMMERMAN Jay Allen": "zimmerman-jay-allen",
    "ZIMMERMAN Martin": "zimmerman-martin",
    "ZIMMERMAN Mary": "zimmerman-mary",
    "ZIMMERMAN Michael": "zimmerman-michael",
    "ZIMMERMAN Paul": "zimmerman-paul",
    "ZIMMERMAN Rochele": "zimmerman-rochele",
    "ZIMMERMAN William": "zimmerman-william",
    "ZIMMERMAN Zach": "zimmerman-zach",
    "ZIMMERMAN Zoey": "zimmerman-zoey",
    "ZIMMERMANN Martin": "zimmermann-martin",
    "ZINDEL Paul": "zindel-paul",
    "ZINDIKA ": "zindika",
    "ZINK Sharon": "zink-sharon",
    "ZINN Howard": "zinn-howard",
    "ZINN Peter": "zinn-peter",
    "ZINNER Elmer": "zinner-elmer",
    "ZINOBER Richard": "zinober-richard",
    "ZIO Charles": "zio-charles",
    "ZION Gene": "zion-gene",
    "ZION Jed": "zion-jed",
    "ZIPES Jack": "zipes-jack",
    "ZIPF M": "zipf-m",
    "ZIPORYN Terra": "ziporyn-terra",
    "ZIPPEL David": "zippel-david",
    "ZIPPER Allen": "zipper-allen",
    "ZIPPER Gerald": "zipper-gerald",
    "ZIPPERER Eddie": "zipperer-eddie",
    "ZIPPI Daniel": "zippi-daniel",
    "ZIPPO ": "zippo",
    "ZIRIMU Elvania": "zirimu-elvania",
    "ZIRKA Jiri": "zirka-jiri",
    "ZITO Andrew": "zito-andrew",
    "ZITO Chuck": "zito-chuck",
    "ZITO Filomena": "zito-filomena",
    "ZITO George": "zito-george",
    "ZITO Joseph Jude": "zito-joseph-jude",
    "ZITTLE Greg": "zittle-greg",
    "ZITWER Barbara J": "zitwer-barbara-j",
    "ZIVANOVIC Judith": "zivanovic-judith",
    "ZIVETZ Carrie": "zivetz-carrie",
    "ZIZKA Blanka": "zizka-blanka",
    "ZIZKA Jiri": "zizka-jiri",
    "ZLATOS Laura": "zlatos-laura",
    "ZLOCHHAUER David": "zlochhauer-david",
    "ZLOOF Fouad": "zloof-fouad",
    "ZLOOF Serene": "zloof-serene",
    "ZLOTNIKOV Semyon": "zlotnikov-semyon"
  }
};