export default {
  "metadata": {
    "results": 44,
    "timeStamp": "2025-12-05T21:32:49.146Z",
    "url": "https://www.doollee.com/PlaywrightsZ/Z_playwrights_s-z.php"
  },
  "authors": {
    "ZSCHOKKE Matthias": "zschokke-matthias",
    "ZSIGOVICS Gabor": "zsigovics-gabor",
    "ZSITVA Imola": "zsitva-imola",
    "ZUABI Amir Nizar": "zuabi-amir-nizar",
    "ZUBAIR Faraz": "zubair-faraz",
    "ZUBER Ron": "zuber-ron",
    "ZUBIETA Mar": "zubieta-mar",
    "ZUCCOLO Greg": "zuccolo-greg",
    "ZUCKER Alex": "zucker-alex",
    "ZUCKER Elena": "zucker-elena",
    "ZUCKER Lindy": "zucker-lindy",
    "ZUCKER Sharon": "zucker-sharon",
    "ZUCKERMAN Harvey": "zuckerman-harvey",
    "ZUCKERMAN Martin": "zuckerman-martin",
    "ZUCKMAYER Carl": "zuckmayer-carl",
    "ZUDAK Catherine": "zudak-catherine",
    "ZUEV Vladimir": "zuev-vladimir",
    "ZUGUANG Wu": "zuguang-wu",
    "ZUKERMAN Nava": "zukerman-nava",
    "ZULIA Ernest": "zulia-ernest",
    "ZULLO Jack": "zullo-jack",
    "ZULLY Stewart Jay": "zully-stewart-jay",
    "ZULUETA Ignacio": "zulueta-ignacio",
    "ZUMBO Matthew J": "zumbo-matthew-j",
    "ZUMEL Enrique": "zumel-enrique",
    "ZUMPA & LALLERO ": "zumpa-lallero",
    "ZUNDEL Harry": "zundel-harry",
    "ZUNGRE Jonathan": "zungre-jonathan",
    "ZUPANCIC Neal": "zupancic-neal",
    "ZURBANO Maritess": "zurbano-maritess",
    "ZURIK Michael P": "zurik-michael-p",
    "ZURITSKY Elisa": "zuritsky-elisa",
    "ZURLA Martin": "zurla-martin",
    "ZUSY Jeannie": "zusy-jeannie",
    "ZVAIFLER Jan": "zvaifler-jan",
    "ZWART Nick": "zwart-nick",
    "ZWEIBEL Alan": "zweibel-alan",
    "ZWEIBEL William L": "zweibel-william-l",
    "ZWEIG Stefan": "zweig-stefan",
    "ZWEIGENBOM Dor": "zweigenbom-dor",
    "ZWICK Alexander": "zwick-alexander",
    "ZWIERS Jennifer": "zwiers-jennifer",
    "ZYLIN Svetlana": "zylin-svetlana",
    "ZYLSTRA Nicole": "zylstra-nicole"
  }
};