export default {
  "2 BIRDS 1 STONE ": "2-birds-1-stone",
  "2 TIL 5 YOUTH GROUP ": "2-til-5-youth-group",
  "2B THEATRE COMPANY ": "2b-theatre-company",
  "2HEADEDPIGEON ": "2headedpigeon",
  "2MAGPIES THEATRE ": "2magpies-theatre",
  "3 D COLLABORATIVE THEATRE ": "3-d-collaborative-theatre",
  "3 D THEATRE COMPANY ": "3-d-theatre-company",
  "5 FLIGHTS THEATER COMPANY ": "5-flights-theater-company",
  "7:84 THEATRE COMPANY ": "784-theatre-company",
  "AAAL Mahmoud Abdel": "aaal-mahmoud-abdel",
  "AAIRES Patrice": "aaires-patrice",
  "AAKHU Shepsu": "aakhu-shepsu",
  "AANERUD Ryan": "aanerud-ryan",
  "AANES Kirk": "aanes-kirk",
  "AAR-AL-DEAN ": "aar-al-dean",
  "AARON Caroline": "aaron-caroline",
  "AARON Hugh": "aaron-hugh",
  "AARON John": "aaron-john",
  "AARON Joyce": "aaron-joyce",
  "AARON Luned": "aaron-luned",
  "AARONS Leroy": "aarons-leroy",
  "AARONSON Jack": "aaronson-jack",
  "AARSVOLD Laurel Ann": "aarsvold-laurel-ann",
  "AASENG Mikhaila": "aaseng-mikhaila",
  "ABAD Mercedes": "abad-mercedes",
  "ABAFFY Rebecca": "abaffy-rebecca",
  "ABAKARI Damani": "abakari-damani",
  "ABALOS Brian": "abalos-brian",
  "ABATEMARCO Tony": "abatemarco-tony",
  "ABATSIS Elisa": "abatsis-elisa",
  "ABBA Marta": "abba-marta",
  "ABBADO Daniele": "abbado-daniele",
  "ABBADO Ovadia": "abbado-ovadia",
  "ABBATIELLO Danielle": "abbatiello-danielle",
  "ABBENSETTS Michael": "abbensetts-michael",
  "ABBIATI Roberto": "abbiati-roberto",
  "ABBINANTI David": "abbinanti-david",
  "ABBINANTI Jill": "abbinanti-jill",
  "ABBOT June": "abbot-june",
  "ABBOT Rick": "abbot-rick",
  "ABBOTT Ada G": "abbott-ada-g",
  "ABBOTT Ben": "abbott-ben",
  "ABBOTT Brian": "abbott-brian",
  "ABBOTT Brian (1)": "abbott-brian-1",
  "ABBOTT Chris": "abbott-chris",
  "ABBOTT George": "abbott-george",
  "ABBOTT Greg": "abbott-greg",
  "ABBOTT Jack Henry": "abbott-jack-henry",
  "ABBOTT Karen": "abbott-karen",
  "ABBOTT Laura": "abbott-laura",
  "ABBOTT Paul": "abbott-paul",
  "ABBOTT Sally": "abbott-sally",
  "ABBOTT Stephen": "abbott-stephen",
  "ABBOTT Steve": "abbott-steve",
  "ABBS Sean": "abbs-sean",
  "ABCEDE Angel": "abcede-angel",
  "ABDALLAH Mohammad Ibn": "abdallah-mohammad-ibn",
  "ABDEL-RAZEK Mariam": "abdel-razek-mariam",
  "ABDOH Reza": "abdoh-reza",
  "ABDUL Ban": "abdul-ban",
  "ABDULLAH Ahmed Maarifa": "abdullah-ahmed-maarifa",
  "ABDULRAZZAK Hassan": "abdulrazzak-hassan",
  "ABDU-RAHMAN Anadoula": "abdu-rahman-anadoula",
  "ABE Kobo": "abe-kobo",
  "ABEL David": "abel-david",
  "ABEL Douglas": "abel-douglas",
  "ABEL Duncan": "abel-duncan",
  "ABEL J G": "abel-j-g",
  "ABEL Leah James": "abel-leah-james",
  "ABEL Lionel": "abel-lionel",
  "ABEL Ron": "abel-ron",
  "ABEL Roysten": "abel-roysten",
  "ABELA Donna": "abela-donna",
  "ABELES David": "abeles-david",
  "ABELL Kjeld": "abell-kjeld",
  "ABELL Lionel": "abell-lionel",
  "ABELLA Cesar": "abella-cesar",
  "ABELMAN Brett": "abelman-brett",
  "ABERLIN Brooke": "aberlin-brooke",
  "ABERLINE Matthew": "aberline-matthew",
  "ABERNATHY Brian": "abernathy-brian",
  "ABERNATHY Charles": "abernathy-charles",
  "ABERNETHY Craig": "abernethy-craig",
  "ABERNETHY Margaret": "abernethy-margaret",
  "ABID Robert": "abid-robert",
  "ABINERI Daniel": "abineri-daniel",
  "ABINERI John": "abineri-john",
  "ABIODUNJI Syl": "abiodunji-syl",
  "ABKARIAN Catherine Schaub": "abkarian-catherine-schaub",
  "ABLEMAN Paul": "ableman-paul",
  "ABLESER Deanna Alisa": "ableser-deanna-alisa",
  "ABLEY Sean": "abley-sean",
  "ABNEY JR Robert": "abney-jr-robert",
  "ABOLAFIA David": "abolafia-david",
  "ABOSCH Danny": "abosch-danny",
  "ABOUD Morgan": "aboud-morgan",
  "ABOUDOMA Mohamed": "aboudoma-mohamed",
  "ABOUSSLEMAN Susan": "aboussleman-susan",
  "ABOVE THE CURVE ": "above-the-curve",
  "ABRACEN Alice": "abracen-alice",
  "ABRAHAM Adam": "abraham-adam",
  "ABRAHAM Anjali": "abraham-anjali",
  "ABRAHAMI Arnon": "abrahami-arnon",
  "ABRAHAMI Natalie": "abrahami-natalie",
  "ABRAHAMS Gary": "abrahams-gary",
  "ABRAHAMS Jody": "abrahams-jody",
  "ABRAHAMS Mark": "abrahams-mark",
  "ABRAHAMS Rehane": "abrahams-rehane",
  "ABRAHAMSE Fred": "abrahamse-fred",
  "ABRAHAMSEN Rita": "abrahamsen-rita",
  "ABRAHAMSON Daniel": "abrahamson-daniel",
  "ABRAHAMSON Terry": "abrahamson-terry",
  "ABRAMHOFF Sharyn": "abramhoff-sharyn",
  "ABRAMI Robert": "abrami-robert",
  "ABRAMOV Fyodor": "abramov-fyodor",
  "ABRAMOVIC Marina": "abramovic-marina",
  "ABRAMOVITZ Jill": "abramovitz-jill",
  "ABRAMOW Jaroslaw": "abramow-jaroslaw",
  "ABRAMOWITZ David": "abramowitz-david",
  "ABRAMOWITZ David Steven": "abramowitz-david-steven",
  "ABRAMS Abiola": "abrams-abiola",
  "ABRAMS Arthur": "abrams-arthur",
  "ABRAMS Jessica": "abrams-jessica",
  "ABRAMS Jules": "abrams-jules",
  "ABRAMS Leon": "abrams-leon",
  "ABRAMS Lesley": "abrams-lesley",
  "ABRAMS Marilyn": "abrams-marilyn",
  "ABRAMS T E": "abrams-t-e",
  "ABRAMS Tevia": "abrams-tevia",
  "ABRAMSON Deborah": "abramson-deborah",
  "ABRAMSON Dolores": "abramson-dolores",
  "ABRAMSON Donald": "abramson-donald",
  "ABRASH Merritt": "abrash-merritt",
  "ABREU Zaria": "abreu-zaria",
  "ABRIC Leon": "abric-leon",
  "ABROMAITIS Karin": "abromaitis-karin",
  "ABRONS Richard": "abrons-richard",
  "ABSE Dannie": "abse-dannie",
  "ABSOLUTE ZERO ": "absolute-zero",
  "ABUAH Anthony": "abuah-anthony",
  "ABUBA Ernest": "abuba-ernest",
  "ABUBAKARI Damani": "abubakari-damani",
  "ABU-HAMDEH Sharif": "abu-hamdeh-sharif",
  "ABULAFIA John": "abulafia-john",
  "ACADEMY PRODUCTIONS ": "academy-productions",
  "ACADEMY THEATRE COMPANY ": "academy-theatre-company",
  "ACASTER Kay": "acaster-kay",
  "ACAZ Mba": "acaz-mba",
  "ACCADEMIA DEGLI IGANNATI ": "accademia-degli-igannati",
  "ACCAME Jorge": "accame-jorge",
  "ACCIDENTAL COLLECTIVE ": "accidental-collective",
  "ACCIOLI Andy": "accioli-andy",
  "ACCUARDI Sara Jean": "accuardi-sara-jean",
  "ACCURSO Aron": "accurso-aron",
  "ACEVEDO Edgar": "acevedo-edgar",
  "ACEVEDO-JONES Lucille": "acevedo-jones-lucille",
  "ACHARD Marcel": "achard-marcel",
  "ACHEBE Chinua": "achebe-chinua",
  "ACHESON Kyle": "acheson-kyle",
  "ACHILLES Marcel": "achilles-marcel",
  "ACHOUR Lotfi": "achour-lotfi",
  "ACHTEM Jeff": "achtem-jeff",
  "ACHTERNBUSCH Herbert": "achternbusch-herbert",
  "ACHTMAN Michael": "achtman-michael",
  "ACIERTO Alejandro": "acierto-alejandro",
  "ACITO Marc": "acito-marc",
  "ACITO Tim": "acito-tim",
  "ACKAMOOR Idris": "ackamoor-idris",
  "ACKER Emily": "acker-emily",
  "ACKER Kathy": "acker-kathy",
  "ACKER Robert": "acker-robert",
  "ACKERLEY J R": "ackerley-j-r",
  "ACKERMAN Anthony": "ackerman-anthony",
  "ACKERMAN David": "ackerman-david",
  "ACKERMAN Emily": "ackerman-emily",
  "ACKERMAN Hal": "ackerman-hal",
  "ACKERMAN Julie": "ackerman-julie",
  "ACKERMAN Louis": "ackerman-louis",
  "ACKERMAN Marianne": "ackerman-marianne",
  "ACKERMAN Michelle S": "ackerman-michelle-s",
  "ACKERMAN Peter": "ackerman-peter",
  "ACKERMAN Peter William": "ackerman-peter-william",
  "ACKERMAN Rob": "ackerman-rob",
  "ACKERMAN Robert Allan": "ackerman-robert-allan",
  "ACKERMAN Robert Steven": "ackerman-robert-steven",
  "ACKERMANN Joan": "ackermann-joan",
  "ACKLAND Matthew": "ackland-matthew",
  "ACKLAND Rodney": "ackland-rodney",
  "ACKLEY Millie": "ackley-millie",
  "ACKLEY Steven": "ackley-steven",
  "ACKROYD Heather": "ackroyd-heather",
  "ACKROYD Peter": "ackroyd-peter",
  "ACKROYD Simon": "ackroyd-simon",
  "ACKROYD Timothy": "ackroyd-timothy",
  "ACLAND Robin": "acland-robin",
  "ACORD Leon": "acord-leon",
  "ACORN Milton": "acorn-milton",
  "ACOSTA Ann": "acosta-ann",
  "ACOSTA Bob": "acosta-bob",
  "ACOSTA Jon": "acosta-jon",
  "ACOSTA Martin": "acosta-martin",
  "ACQUAYE Saka": "acquaye-saka",
  "ACQUISTO Daniel S": "acquisto-daniel-s",
  "ACREE Nate": "acree-nate",
  "ACREMAN T S": "acreman-t-s",
  "ACS Janos": "acs-janos",
  "ACT Courtney": "act-courtney",
  "ACT IV THEATRE COMPANY ": "act-iv-theatre-company",
  "ACTION HERO ": "action-hero",
  "ACTION THEATRE OF LONDON ": "action-theatre-of-london",
  "ACTION TRANSPORT THEATRE ": "action-transport-theatre",
  "ACTON Niki": "acton-niki",
  "ACTOR TRAINING IRELAND ": "actor-training-ireland",
  "ACWORTH Elaine": "acworth-elaine",
  "ADABASHYA A": "adabashya-a",
  "ADAIAR Tom": "adaiar-tom",
  "ADAIR Aaron": "adair-aaron",
  "ADAIR Alexis": "adair-alexis",
  "ADAIR Arthur Maximillian": "adair-arthur-maximillian",
  "ADAIR Tom": "adair-tom",
  "ADAIR Zach": "adair-zach",
  "ADAM Agnes": "adam-agnes",
  "ADAM Bruce": "adam-bruce",
  "ADAM Henry": "adam-henry",
  "ADAM Jennifer": "adam-jennifer",
  "ADAM Roel": "adam-roel",
  "ADAM Ronald": "adam-ronald",
  "ADAM Vikas": "adam-vikas",
  "ADAM Vivien": "adam-vivien",
  "ADAMCZAK Shane": "adamczak-shane",
  "ADAMIS Anna": "adamis-anna",
  "ADAMO Frank": "adamo-frank",
  "ADAMOV Arthur": "adamov-arthur",
  "ADAMS Abigail": "adams-abigail",
  "ADAMS Alex": "adams-alex",
  "ADAMS Alison": "adams-alison",
  "ADAMS Allyson Lee": "adams-allyson-lee",
  "ADAMS Benjamin Mark": "adams-benjamin-mark",
  "ADAMS Bob": "adams-bob",
  "ADAMS Bob (1)": "adams-bob-1",
  "ADAMS Bonnie": "adams-bonnie",
  "ADAMS Brandt": "adams-brandt",
  "ADAMS Bruce": "adams-bruce",
  "ADAMS Chris": "adams-chris",
  "ADAMS Christopher": "adams-christopher",
  "ADAMS Christopher A": "adams-christopher-a",
  "ADAMS Claudia": "adams-claudia",
  "ADAMS Craig": "adams-craig",
  "ADAMS David": "adams-david",
  "ADAMS Desmond": "adams-desmond",
  "ADAMS Dianne": "adams-dianne",
  "ADAMS Douglas": "adams-douglas",
  "ADAMS Edward H": "adams-edward-h",
  "ADAMS Elissa": "adams-elissa",
  "ADAMS Elma": "adams-elma",
  "ADAMS Emma": "adams-emma",
  "ADAMS Genevieve": "adams-genevieve",
  "ADAMS Gill": "adams-gill",
  "ADAMS Glenda": "adams-glenda",
  "ADAMS Harley": "adams-harley",
  "ADAMS Harvey": "adams-harvey",
  "ADAMS Ian": "adams-ian",
  "ADAMS Ian (1)": "adams-ian-1",
  "ADAMS Janus": "adams-janus",
  "ADAMS Jeffrey": "adams-jeffrey",
  "ADAMS Johanna": "adams-johanna",
  "ADAMS John": "adams-john",
  "ADAMS Johnna": "adams-johnna",
  "ADAMS Jolene": "adams-jolene",
  "ADAMS Joseph K": "adams-joseph-k",
  "ADAMS Judith": "adams-judith",
  "ADAMS Justin": "adams-justin",
  "ADAMS Kim": "adams-kim",
  "ADAMS Knud": "adams-knud",
  "ADAMS Lee": "adams-lee",
  "ADAMS Leeann Hill": "adams-leeann-hill",
  "ADAMS Levi": "adams-levi",
  "ADAMS Liz Duffy": "adams-liz-duffy",
  "ADAMS Lyndsey": "adams-lyndsey",
  "ADAMS Marty": "adams-marty",
  "ADAMS Matt": "adams-matt",
  "ADAMS Nigel": "adams-nigel",
  "ADAMS Paul": "adams-paul",
  "ADAMS Philip": "adams-philip",
  "ADAMS Ray": "adams-ray",
  "ADAMS Ricci-Jane": "adams-ricci-jane",
  "ADAMS Richard": "adams-richard",
  "ADAMS Richard (1)": "adams-richard-1",
  "ADAMS Richard Elder": "adams-richard-elder",
  "ADAMS Russell": "adams-russell",
  "ADAMS S K": "adams-s-k",
  "ADAMS Sarah": "adams-sarah",
  "ADAMS Steve": "adams-steve",
  "ADAMS Terri Measel": "adams-terri-measel",
  "ADAMS Thomas": "adams-thomas",
  "ADAMS Tom": "adams-tom",
  "ADAMS Tony": "adams-tony",
  "ADAMS Triona": "adams-triona",
  "ADAMS Ty": "adams-ty",
  "ADAMSDALE Will": "adamsdale-will",
  "ADAMSON Ames": "adamson-ames",
  "ADAMSON C M": "adamson-c-m",
  "ADAMSON David": "adamson-david",
  "ADAMSON David D": "adamson-david-d",
  "ADAMSON Harold": "adamson-harold",
  "ADAMSON Isla": "adamson-isla",
  "ADAMSON Jean": "adamson-jean",
  "ADAMSON Jo J": "adamson-jo-j",
  "ADAMSON Luke": "adamson-luke",
  "ADAMSON Martin": "adamson-martin",
  "ADAMSON Robert": "adamson-robert",
  "ADAMSON Samuel": "adamson-samuel",
  "ADAMSON Swan": "adamson-swan",
  "ADAPTORS ": "adaptors",
  "ADARKAR Priya": "adarkar-priya",
  "ADASSINSKI Anton": "adassinski-anton",
  "ADDAI Levi David": "addai-levi-david",
  "ADDAMS Jane": "addams-jane",
  "ADDEFELA Adesha": "addefela-adesha",
  "ADDELSON Lenny": "addelson-lenny",
  "ADDERLEY Julian Cannonball": "adderley-julian-cannonball",
  "ADDERLEY Nat": "adderley-nat",
  "ADDESSO Richard": "addesso-richard",
  "ADDIE Brenda": "addie-brenda",
  "ADDINGTON Indira": "addington-indira",
  "ADDIS William": "addis-william",
  "ADDISON Elizabeth Caroline": "addison-elizabeth-caroline",
  "ADDISON Jeff": "addison-jeff",
  "ADDISON Joseph": "addison-joseph",
  "ADDO P K": "addo-p-k",
  "ADDO Patience": "addo-patience",
  "ADDYMAN Elizabeth": "addyman-elizabeth",
  "ADE Andrew": "ade-andrew",
  "ADEBAYO Mojisola": "adebayo-mojisola",
  "ADEBEJU Shaun": "adebeju-shaun",
  "ADEKOJE John": "adekoje-john",
  "ADELA Brigitte": "adela-brigitte",
  "ADELIZZI Tara": "adelizzi-tara",
  "ADELL Ilunga": "adell-ilunga",
  "ADELL Josh": "adell-josh",
  "ADELMAN Brenda": "adelman-brenda",
  "ADELMAN Louis C": "adelman-louis-c",
  "ADELMAN Melanie": "adelman-melanie",
  "ADELMAN Sara": "adelman-sara",
  "ADELSON Leonard": "adelson-leonard",
  "ADEMOLA Ade": "ademola-ade",
  "ADEN James": "aden-james",
  "ADENBERG Wolfgang": "adenberg-wolfgang",
  "ADEPEABA Ade": "adepeaba-ade",
  "ADER Robert": "ader-robert",
  "ADESINA Chrissie": "adesina-chrissie",
  "ADESON Martin": "adeson-martin",
  "ADETUNJI Lydia": "adetunji-lydia",
  "ADGEBOYEGA Peter": "adgeboyega-peter",
  "ADIGUN Bisi": "adigun-bisi",
  "ADINOLFI Carlo": "adinolfi-carlo",
  "ADISA ": "adisa",
  "ADJMI David": "adjmi-david",
  "ADJOSE Mariam": "adjose-mariam",
  "ADKIN Paul David": "adkin-paul-david",
  "ADKINS Keith Josef": "adkins-keith-josef",
  "ADKINS Mary": "adkins-mary",
  "ADKINS Nicole B": "adkins-nicole-b",
  "ADKINS Scott": "adkins-scott",
  "ADLAM Terry": "adlam-terry",
  "ADLEMAN Brenda": "adleman-brenda",
  "ADLEMAN Darrel": "adleman-darrel",
  "ADLEMAN Lauren Z": "adleman-lauren-z",
  "ADLEN Joel": "adlen-joel",
  "ADLER Beth Sharon": "adler-beth-sharon",
  "ADLER Charles": "adler-charles",
  "ADLER Fred": "adler-fred",
  "ADLER Gary": "adler-gary",
  "ADLER James": "adler-james",
  "ADLER Joyce Sparer": "adler-joyce-sparer",
  "ADLER Marion": "adler-marion",
  "ADLER Michael": "adler-michael",
  "ADLER Richard": "adler-richard",
  "ADLER Rosalind": "adler-rosalind",
  "ADLER Warren": "adler-warren",
  "ADMIRAAL Joop": "admiraal-joop",
  "ADOFF George": "adoff-george",
  "ADORIAN Simon": "adorian-simon",
  "ADORNING ": "adorning",
  "ADRALES May": "adrales-may",
  "ADREINI John": "adreini-john",
  "ADRIAN Benedicte": "adrian-benedicte",
  "ADRIAN Yvonne": "adrian-yvonne",
  "ADRIANO Frank": "adriano-frank",
  "ADSHEAD Kay": "adshead-kay",
  "ADUH Gwen": "aduh-gwen",
  "ADUM Peter": "adum-peter",
  "ADVENTURES IN MOTION PICTURES ": "adventures-in-motion-pictures",
  "ADYANTHAYA Aravind Enrique": "adyanthaya-aravind-enrique",
  "AEGERTER Geraline": "aegerter-geraline",
  "AELLEN Richard": "aellen-richard",
  "AERENSON Benjie": "aerenson-benjie",
  "AESCHYLUS ": "aeschylus",
  "AESQUIVEL Dakota": "aesquivel-dakota",
  "AF PETERSENS Caroline": "af-petersens-caroline",
  "AFFANADOR Maurissa": "affanador-maurissa",
  "AFFINITO A Giovanni": "affinito-a-giovanni",
  "AFFINITO Alfonso": "affinito-alfonso",
  "AFFLECK Judith": "affleck-judith",
  "AFFORD Max": "afford-max",
  "AFFOUMADO Sam": "affoumado-sam",
  "AFINOGENEV Alexander": "afinogenev-alexander",
  "AFRO-AMERICAN FOLKLORIC TROUPE ": "afro-american-folkloric-troupe",
  "AFRO-AMERICAN STUDIO ": "afro-american-studio",
  "AFTON Henry": "afton-henry",
  "AGABIAN Nancy": "agabian-nancy",
  "AGAMIAN Mariam": "agamian-mariam",
  "AGANS David J": "agans-david-j",
  "AGARD John": "agard-john",
  "AGARD Sandra": "agard-sandra",
  "AGATHA Sue": "agatha-sue",
  "AGBAJE Bola": "agbaje-bola",
  "AGBOLUAJE Oladipo": "agboluaje-oladipo",
  "AGBONLAHOR Charis": "agbonlahor-charis",
  "AGEE Joel": "agee-joel",
  "AGENT Sarah": "agent-sarah",
  "AGG Howard": "agg-howard",
  "AGISLAOU Yiannis": "agislaou-yiannis",
  "AGNEW F E M": "agnew-f-e-m",
  "AGNEW Pinky": "agnew-pinky",
  "AGNEW Steve": "agnew-steve",
  "AGNEW Will": "agnew-will",
  "AGNIEL Anna Marie": "agniel-anna-marie",
  "AGOSTON Gerty": "agoston-gerty",
  "AGRAWAL Nayna B": "agrawal-nayna-b",
  "AGRUPACION SENOR SERRANO ": "agrupacion-senor-serrano",
  "AGUEROS Jack": "agueros-jack",
  "AGUILA Kevin Del": "aguila-kevin-del",
  "AGUILAR Anthony": "aguilar-anthony",
  "AGUILAR Christopher Belen": "aguilar-christopher-belen",
  "AGUILER Louis": "aguiler-louis",
  "AGUILERA Carolina": "aguilera-carolina",
  "AGUILERA Yunior Garcia": "aguilera-yunior-garcia",
  "AGUIRRE Carmen": "aguirre-carmen",
  "AGUIRRE Isidora": "aguirre-isidora",
  "AGUIRRE Michael Allen": "aguirre-michael-allen",
  "AGUIRRE Mike": "aguirre-mike",
  "AGUIRRE-SACASA Roberto": "aguirre-sacasa-roberto",
  "AGULANSKY Leon": "agulansky-leon",
  "AGUSTIN Sandra": "agustin-sandra",
  "AGYEMANG Kofi": "agyemang-kofi",
  "AH HI Iaheto": "ah-hi-iaheto",
  "AHAD Nick": "ahad-nick",
  "AHAMED Masud": "ahamed-masud",
  "AHAMED Saikat": "ahamed-saikat",
  "AHARONI Michal": "aharoni-michal",
  "AHEARN Dan": "ahearn-dan",
  "AHERN Carrie": "ahern-carrie",
  "AHERN Lynne": "ahern-lynne",
  "AHERNS Lynn": "aherns-lynn",
  "AHIPENE Hori": "ahipene-hori",
  "AHLBOM Jakop": "ahlbom-jakop",
  "AHLERSMEYER Bob": "ahlersmeyer-bob",
  "AHLERT Richard": "ahlert-richard",
  "AHLFORS Bengt": "ahlfors-bengt",
  "AHLIN John": "ahlin-john",
  "AHLIN Margit": "ahlin-margit",
  "AHLQUIST Jane": "ahlquist-jane",
  "AHMAD Aamina": "ahmad-aamina",
  "AHMAD Dorothy": "ahmad-dorothy",
  "AHMAD Faizan": "ahmad-faizan",
  "AHMAD Marina Wolf": "ahmad-marina-wolf",
  "AHMAD Ruhksana": "ahmad-ruhksana",
  "AHMADI Nastaran": "ahmadi-nastaran",
  "AHMADZADEH Morteza": "ahmadzadeh-morteza",
  "AHMAN Aamina": "ahman-aamina",
  "AHMED Mediah": "ahmed-mediah",
  "AHMED Mukul": "ahmed-mukul",
  "AHMED Naylah": "ahmed-naylah",
  "AHMED Said Salah": "ahmed-said-salah",
  "AHMED Sharbari": "ahmed-sharbari",
  "AHMED Umar": "ahmed-umar",
  "AHN Byungkoo": "ahn-byungkoo",
  "AHNEN Pearl S": "ahnen-pearl-s",
  "AHNET Behsat": "ahnet-behsat",
  "AHOLA Robert Joseph": "ahola-robert-joseph",
  "AHONEN Derek": "ahonen-derek",
  "AHRENS Lynn": "ahrens-lynn",
  "AHRENS Renate": "ahrens-renate",
  "AHRONHEIM Adele": "ahronheim-adele",
  "AHSAM Richard": "ahsam-richard",
  "AIBEL Dan": "aibel-dan",
  "AICHER Sarah": "aicher-sarah",
  "AICHINGER Ilse": "aichinger-ilse",
  "AIDA Noriko": "aida-noriko",
  "AIDMAN Charles": "aidman-charles",
  "AIDOO Ama Ata (Christina)": "aidoo-ama-ata",
  "AIDOO Mina": "aidoo-mina",
  "AIKEN Alfred": "aiken-alfred",
  "AIKEN Conrad": "aiken-conrad",
  "AIKEN Ellen": "aiken-ellen",
  "AIKEN George": "aiken-george",
  "AIKEN Joan": "aiken-joan",
  "AIKEN III P Case": "aiken-iii-p-case",
  "AINARSSON Sveinn": "ainarsson-sveinn",
  "AINSCOW Faye": "ainscow-faye",
  "AINSLIE Maud": "ainslie-maud",
  "AINSWORTH Dave": "ainsworth-dave",
  "AINSWORTH Ford": "ainsworth-ford",
  "AINSWORTH Julia": "ainsworth-julia",
  "AINSWORTH Robert": "ainsworth-robert",
  "AIRES Jorge Cardosos": "aires-jorge-cardosos",
  "AISNER Keith": "aisner-keith",
  "AITA Deborah": "aita-deborah",
  "AITA Sean": "aita-sean",
  "AITCHISON Bill": "aitchison-bill",
  "AITCHTEY Rodney": "aitchtey-rodney",
  "AITKEN Ben": "aitken-ben",
  "AITKEN Dominic": "aitken-dominic",
  "AITKEN John": "aitken-john",
  "AITKEN Nikki": "aitken-nikki",
  "AITKEN Tamzin": "aitken-tamzin",
  "AJ ": "aj",
  "AJADI Adewale": "ajadi-adewale",
  "AJAMU ": "ajamu",
  "AJAYI Afolabi": "ajayi-afolabi",
  "AJEMIAN Chris": "ajemian-chris",
  "AJIBADE Yemi": "ajibade-yemi",
  "AJUONUMA Reg": "ajuonuma-reg",
  "AKALAITIS Joanne": "akalaitis-joanne",
  "AKAR John J": "akar-john-j",
  "AKEN Ann Wagooner": "aken-ann-wagooner",
  "AKERBAEK Tord": "akerbaek-tord",
  "AKEREDOLU Femi": "akeredolu-femi",
  "AKERFELT Hanna": "akerfelt-hanna",
  "AKERHOLT May-Britt": "akerholt-may-britt",
  "AKERLEY Kathleen": "akerley-kathleen",
  "AKERMAN Anthony": "akerman-anthony",
  "AKERS Dennis": "akers-dennis",
  "AKERS Mike": "akers-mike",
  "AKERS W M": "akers-w-m",
  "AKHTAR Ayad": "akhtar-ayad",
  "AKHTAR Selina": "akhtar-selina",
  "AKIMBO Deb'Bora": "akimbo-deb-bora",
  "AKIMOTO Matsuyo": "akimoto-matsuyo",
  "AKIN Ann": "akin-ann",
  "AKINSIPE Felix A": "akinsipe-felix-a",
  "AKIVA Maia": "akiva-maia",
  "AKIYAMA Daniel": "akiyama-daniel",
  "AKMAN Andrew": "akman-andrew",
  "AKRAM Yasmine": "akram-yasmine",
  "AKRIDGE Jayson": "akridge-jayson",
  "AKRILL Mark": "akrill-mark",
  "AKSYONOV Vasily": "aksyonov-vasily",
  "AL ASSADI Jawad": "al-assadi-jawad",
  "AL ATTAR Mohammad": "al-attar-mohammad",
  "ALABANZA Travis": "alabanza-travis",
  "ALAGIC Tea": "alagic-tea",
  "ALAGO Linda": "alago-linda",
  "ALAKIJA Olu": "alakija-olu",
  "AL-ALI Akkas": "al-ali-akkas",
  "ALAM Juan Shamsul": "alam-juan-shamsul",
  "ALAM Pervaiz": "alam-pervaiz",
  "ALAMAJI Jiwe": "alamaji-jiwe",
  "ALAMAZ Michael": "alamaz-michael",
  "AL-AMERI Abdul-Kareem": "al-ameri-abdul-kareem",
  "ALAMO Antonio": "alamo-antonio",
  "ALAN Glenn": "alan-glenn",
  "ALAN Scott": "alan-scott",
  "ALANCROFT Rick": "alancroft-rick",
  "ALARIC Terence": "alaric-terence",
  "ALASA Michelangelo": "alasa-michelangelo",
  "ALASSIO Saundra": "alassio-saundra",
  "ALAWJI Abdelrahim": "alawji-abdelrahim",
  "AL-AZRAKI A": "al-azraki-a",
  "ALAZRAQUI Carlos": "alazraqui-carlos",
  "ALBAKRI Zahim": "albakri-zahim",
  "ALBAN Carlo": "alban-carlo",
  "ALBANESE Eleanor": "albanese-eleanor",
  "ALBANESE James V": "albanese-james-v",
  "ALBANESE John": "albanese-john",
  "ALBANESE Michael": "albanese-michael",
  "ALBANO John": "albano-john",
  "ALBARELLA Joan": "albarella-joan",
  "ALBARN Damon": "albarn-damon",
  "AL-BASSAM Sulayman": "al-bassam-sulayman",
  "ALBATE Christopher": "albate-christopher",
  "ALBEE Edward": "albee-edward",
  "ALBERS Katherine": "albers-katherine",
  "ALBERT April": "albert-april",
  "ALBERT Carolyn": "albert-carolyn",
  "ALBERT Jan": "albert-jan",
  "ALBERT Jonathan": "albert-jonathan",
  "ALBERT Lauren Marie": "albert-lauren-marie",
  "ALBERT Lyle": "albert-lyle",
  "ALBERT Mark H": "albert-mark-h",
  "ALBERT Marvin": "albert-marvin",
  "ALBERT Michael Ross": "albert-michael-ross",
  "ALBERT Sandra J": "albert-sandra-j",
  "ALBERT Thomas": "albert-thomas",
  "ALBERTELLA Jorge": "albertella-jorge",
  "ALBERTIE Dante": "albertie-dante",
  "ALBERTO Luis": "alberto-luis",
  "ALBERTS David": "alberts-david",
  "ALBERTY R Patrick": "alberty-r-patrick",
  "ALBERY Peter": "albery-peter",
  "ALBERY Tim": "albery-tim",
  "ALBINO Mary": "albino-mary",
  "ALBISTON Lesley Ann": "albiston-lesley-ann",
  "ALBO Mike": "albo-mike",
  "ALBOM Mitch": "albom-mitch",
  "ALBON Nicola": "albon-nicola",
  "ALBORELLI H P": "alborelli-h-p",
  "ALBOROUGH Graham": "alborough-graham",
  "ALBREZZI Steve": "albrezzi-steve",
  "ALBRIGHT Dale": "albright-dale",
  "ALBRIGHT James": "albright-james",
  "ALBRIGHT Mia": "albright-mia",
  "ALBRIGHT Philip": "albright-philip",
  "ALBURY Barbara": "albury-barbara",
  "ALCANTARA Grace": "alcantara-grace",
  "ALCAREZ Jose": "alcarez-jose",
  "ALCID Edmond": "alcid-edmond",
  "ALCOFORADO Sister Mariana": "alcoforado-sister-mariana",
  "ALCORN Frank": "alcorn-frank",
  "ALCORN John": "alcorn-john",
  "ALCORN Seth": "alcorn-seth",
  "ALCORTA David": "alcorta-david",
  "ALCOTT Clapham": "alcott-clapham",
  "ALCOTT Louisa M": "alcott-louisa-m",
  "ALCOTT Todd": "alcott-todd",
  "ALDA Alan": "alda-alan",
  "ALDEN Jerome": "alden-jerome",
  "ALDEN Jonathan James": "alden-jonathan-james",
  "ALDEN Matt": "alden-matt",
  "ALDEN William": "alden-william",
  "ALDERMAN Elinor R": "alderman-elinor-r",
  "ALDERSON Jude": "alderson-jude",
  "ALDERSON Sophie": "alderson-sophie",
  "ALDERTON Alex": "alderton-alex",
  "ALDERTON Rob": "alderton-rob",
  "ALDIN Michele": "aldin-michele",
  "ALDOR Emil": "aldor-emil",
  "ALDOUS John": "aldous-john",
  "ALDRED David": "aldred-david",
  "ALDRIDGE Arthur": "aldridge-arthur",
  "ALDRIDGE James": "aldridge-james",
  "ALDRIDGE Ron": "aldridge-ron",
  "ALEANDRI Ernelise": "aleandri-ernelise",
  "ALED Gareth": "aled-gareth",
  "ALEGRIA Alonso": "alegria-alonso",
  "ALEGRIA Quiara": "alegria-quiara",
  "ALEICHEM Sholem": "aleichem-sholem",
  "ALEJANDRO Jan Michael": "alejandro-jan-michael",
  "ALEKAR Satish": "alekar-satish",
  "ALENICK Ashley": "alenick-ashley",
  "ALENIER Karren La Londe": "alenier-karren-la-londe",
  "ALESIA Dominick": "alesia-dominick",
  "ALESSANDRINI Gerald": "alessandrini-gerald",
  "ALESSI Lillian": "alessi-lillian",
  "ALETTE Carl": "alette-carl",
  "ALEX David": "alex-david",
  "ALEXANDER Aaron": "alexander-aaron",
  "ALEXANDER Alexa": "alexander-alexa",
  "ALEXANDER Annalita": "alexander-annalita",
  "ALEXANDER Ben": "alexander-ben",
  "ALEXANDER Bill": "alexander-bill",
  "ALEXANDER Brad": "alexander-brad",
  "ALEXANDER Constance": "alexander-constance",
  "ALEXANDER Darby": "alexander-darby",
  "ALEXANDER Donald W": "alexander-donald-w",
  "ALEXANDER E A": "alexander-e-a",
  "ALEXANDER Elaine": "alexander-elaine",
  "ALEXANDER Ewart": "alexander-ewart",
  "ALEXANDER F K": "alexander-f-k",
  "ALEXANDER Floyd Sephen": "alexander-floyd-sephen",
  "ALEXANDER Geraldine": "alexander-geraldine",
  "ALEXANDER Henry": "alexander-henry",
  "ALEXANDER Holmes": "alexander-holmes",
  "ALEXANDER J B": "alexander-j-b",
  "ALEXANDER Jackie": "alexander-jackie",
  "ALEXANDER Jane": "alexander-jane",
  "ALEXANDER Jeanne": "alexander-jeanne",
  "ALEXANDER Jill": "alexander-jill",
  "ALEXANDER Judy": "alexander-judy",
  "ALEXANDER Kathya": "alexander-kathya",
  "ALEXANDER Kevin": "alexander-kevin",
  "ALEXANDER Lawrence": "alexander-lawrence",
  "ALEXANDER Lee": "alexander-lee",
  "ALEXANDER Lewis M": "alexander-lewis-m",
  "ALEXANDER Linda Pace": "alexander-linda-pace",
  "ALEXANDER Lowell": "alexander-lowell",
  "ALEXANDER Luther": "alexander-luther",
  "ALEXANDER Maddy": "alexander-maddy",
  "ALEXANDER Mandy": "alexander-mandy",
  "ALEXANDER Meena": "alexander-meena",
  "ALEXANDER Megan": "alexander-megan",
  "ALEXANDER Michael": "alexander-michael",
  "ALEXANDER Myfanwy": "alexander-myfanwy",
  "ALEXANDER Nichol": "alexander-nichol",
  "ALEXANDER Paul": "alexander-paul",
  "ALEXANDER Paul (1)": "alexander-paul-1",
  "ALEXANDER Peter": "alexander-peter",
  "ALEXANDER Richard": "alexander-richard",
  "ALEXANDER Robert": "alexander-robert",
  "ALEXANDER Ronald": "alexander-ronald",
  "ALEXANDER Ross": "alexander-ross",
  "ALEXANDER Sascha": "alexander-sascha",
  "ALEXANDER Sharon": "alexander-sharon",
  "ALEXANDER Stephanie": "alexander-stephanie",
  "ALEXANDER Steven": "alexander-steven",
  "ALEXANDER Stewart": "alexander-stewart",
  "ALEXANDER Sue": "alexander-sue",
  "ALEXANDER Tania": "alexander-tania",
  "ALEXANDER Thorin": "alexander-thorin",
  "ALEXANDER Victor": "alexander-victor",
  "ALEXANDER Zakiyyah": "alexander-zakiyyah",
  "ALEXANDER III Alan": "alexander-iii-alan",
  "ALEXANDER SISTERS, THE ": "alexander-sisters",
  "ALEXANDERSSON David": "alexandersson-david",
  "ALEXANDRA ": "alexandra",
  "ALEXANDRATOS Jonathan": "alexandratos-jonathan",
  "ALEXANDRINO Du Carmo": "alexandrino-du-carmo",
  "ALEXANDRO Trish": "alexandro-trish",
  "ALEXANDROWICZ Conrad": "alexandrowicz-conrad",
  "ALEXIS Andre": "alexis-andre",
  "ALFARO Luis": "alfaro-luis",
  "ALFARO Rosanna Yamagiwa": "alfaro-rosanna-yamagiwa",
  "ALFIERI Richard": "alfieri-richard",
  "ALFIERI Vittorio": "alfieri-vittorio",
  "ALFONSO Mann": "alfonso-mann",
  "ALFORD David": "alford-david",
  "ALFORD Kenneth": "alford-kenneth",
  "ALFORD Lamar": "alford-lamar",
  "ALFORD Larry": "alford-larry",
  "ALFRED James T": "alfred-james-t",
  "ALFRED William": "alfred-william",
  "ALFREDS Mike": "alfreds-mike",
  "ALFSON Richie": "alfson-richie",
  "ALGER Richard": "alger-richard",
  "ALGIE Angus": "algie-angus",
  "ALGIE Daniel": "algie-daniel",
  "AL-HAKIM Tawfiq": "al-hakim-tawfiq",
  "ALI Dhanil": "ali-dhanil",
  "ALI Jamal": "ali-jamal",
  "ALI Lateef": "ali-lateef",
  "ALI Luqman": "ali-luqman",
  "ALI Ntare": "ali-ntare",
  "ALI Tariq": "ali-tariq",
  "ALI Wajahat": "ali-wajahat",
  "ALIANAK Hrant": "alianak-hrant",
  "ALIANIELLO Davis": "alianiello-davis",
  "ALIBAR Lucy": "alibar-lucy",
  "ALIBERTI Lucian": "aliberti-lucian",
  "ALIBERTI Vince": "aliberti-vince",
  "ALIBHAI-BROWN Yasmin": "alibhai-brown-yasmin",
  "ALICANDRO Daniel": "alicandro-daniel",
  "ALICK Claudia": "alick-claudia",
  "ALICK Jesse Cameron": "alick-jesse-cameron",
  "ALI-COLEMAN Khadijah": "ali-coleman-khadijah",
  "ALIPOOR Javaad": "alipoor-javaad",
  "ALISON David": "alison-david",
  "ALISON Joan": "alison-joan",
  "ALISON ANDREWS COMPANY ": "alison-andrews-company",
  "ALIX Francis": "alix-francis",
  "ALIZADEH Ali": "alizadeh-ali",
  "ALKAFRI Abdullah": "alkafri-abdullah",
  "AL-KASABA THEATRE ": "al-kasaba-theatre",
  "AL-KASSAB Sarah": "al-kassab-sarah",
  "ALL OR NOTHING ": "all-or-nothing",
  "ALLADICE Darryl E": "alladice-darryl-e",
  "ALLAIN Noel Joseph": "allain-noel-joseph",
  "ALLAIN Stephanie": "allain-stephanie",
  "ALLAN Amanda": "allan-amanda",
  "ALLAN Charlotte": "allan-charlotte",
  "ALLAN Dan": "allan-dan",
  "ALLAN Gene": "allan-gene",
  "ALLAN Laurence": "allan-laurence",
  "ALLAN Leigh": "allan-leigh",
  "ALLAN Lisa": "allan-lisa",
  "ALLAN Lotte": "allan-lotte",
  "ALLAN Robert": "allan-robert",
  "ALLAN Ross": "allan-ross",
  "ALLAN Ted": "allan-ted",
  "ALLANA Alam": "allana-alam",
  "ALLARD Brian": "allard-brian",
  "ALLARD Harry": "allard-harry",
  "ALLARD Janet": "allard-janet",
  "ALLAYIALIS Toni": "allayialis-toni",
  "ALLCOCK Jack": "allcock-jack",
  "ALLCROFT Charles": "allcroft-charles",
  "ALLDEN Richard": "allden-richard",
  "ALLDEN Rick": "allden-rick",
  "ALLDRIDGE John": "alldridge-john",
  "ALLEGRA Michael": "allegra-michael",
  "ALLEGRO John": "allegro-john",
  "ALLEMAN Ben": "alleman-ben",
  "ALLEMANN Bryce": "allemann-bryce",
  "ALLEN Albert": "allen-albert",
  "ALLEN Alex": "allen-alex",
  "ALLEN Andi": "allen-andi",
  "ALLEN Andrea": "allen-andrea",
  "ALLEN Anthony": "allen-anthony",
  "ALLEN Ashley": "allen-ashley",
  "ALLEN B C": "allen-b-c",
  "ALLEN Brooke": "allen-brooke",
  "ALLEN Catherine": "allen-catherine",
  "ALLEN Cathy Celesia": "allen-cathy-celesia",
  "ALLEN Claudia": "allen-claudia",
  "ALLEN Corey": "allen-corey",
  "ALLEN D E": "allen-d-e",
  "ALLEN David": "allen-david",
  "ALLEN Debbie": "allen-debbie",
  "ALLEN Dennis": "allen-dennis",
  "ALLEN Dominic John": "allen-dominic-john",
  "ALLEN Donald M": "allen-donald-m",
  "ALLEN Evelyn W": "allen-evelyn-w",
  "ALLEN Geoff": "allen-geoff",
  "ALLEN Graham": "allen-graham",
  "ALLEN Greg": "allen-greg",
  "ALLEN Ian": "allen-ian",
  "ALLEN Indi": "allen-indi",
  "ALLEN J Linn": "allen-j-linn",
  "ALLEN J P": "allen-j-p",
  "ALLEN Janet": "allen-janet",
  "ALLEN Jay Presson": "allen-jay-presson",
  "ALLEN Jennifer": "allen-jennifer",
  "ALLEN Jenny": "allen-jenny",
  "ALLEN Jim": "allen-jim",
  "ALLEN Jimmy": "allen-jimmy",
  "ALLEN Jo Harvey": "allen-jo-harvey",
  "ALLEN John": "allen-john",
  "ALLEN Joshua": "allen-joshua",
  "ALLEN Judith": "allen-judith",
  "ALLEN June": "allen-june",
  "ALLEN Justin": "allen-justin",
  "ALLEN Kimball": "allen-kimball",
  "ALLEN L H": "allen-l-h",
  "ALLEN Laurence": "allen-laurence",
  "ALLEN Laurie": "allen-laurie",
  "ALLEN Lisa Beth": "allen-lisa-beth",
  "ALLEN Lizzie": "allen-lizzie",
  "ALLEN Marilyn": "allen-marilyn",
  "ALLEN Marilyn M": "allen-marilyn-m",
  "ALLEN Martin": "allen-martin",
  "ALLEN Merridith": "allen-merridith",
  "ALLEN Michael (1)": "allen-michael-1",
  "ALLEN Michael (2)": "allen-michael-2",
  "ALLEN Morgan": "allen-morgan",
  "ALLEN Nathan": "allen-nathan",
  "ALLEN Nicholas": "allen-nicholas",
  "ALLEN Norman": "allen-norman",
  "ALLEN Olivia": "allen-olivia",
  "ALLEN Paul": "allen-paul",
  "ALLEN Paul (1)": "allen-paul-1",
  "ALLEN Peter": "allen-peter",
  "ALLEN Ralph G": "allen-ralph-g",
  "ALLEN Raymond": "allen-raymond",
  "ALLEN Renata": "allen-renata",
  "ALLEN Renee Bang": "allen-renee-bang",
  "ALLEN Richard": "allen-richard",
  "ALLEN Richard (1)": "allen-richard-1",
  "ALLEN Richard James": "allen-richard-james",
  "ALLEN Roger": "allen-roger",
  "ALLEN Roland": "allen-roland",
  "ALLEN Russell": "allen-russell",
  "ALLEN Seamus": "allen-seamus",
  "ALLEN Seth": "allen-seth",
  "ALLEN Stephen": "allen-stephen",
  "ALLEN Steve": "allen-steve",
  "ALLEN Stuart": "allen-stuart",
  "ALLEN Suzanne M": "allen-suzanne-m",
  "ALLEN Ted": "allen-ted",
  "ALLEN Terry": "allen-terry",
  "ALLEN Thoasena": "allen-thoasena",
  "ALLEN Tina Alexis": "allen-tina-alexis",
  "ALLEN Tony": "allen-tony",
  "ALLEN Trevor": "allen-trevor",
  "ALLEN Vera": "allen-vera",
  "ALLEN William": "allen-william",
  "ALLEN Woody": "allen-woody",
  "ALLEN II Dennis A": "allen-ii-dennis-a",
  "ALLENDE Isabel": "allende-isabel",
  "ALLEN-DUTTON Jordan": "allen-dutton-jordan",
  "ALLEN-MARTIN Tori": "allen-martin-tori",
  "ALLENSWORTH Carl": "allensworth-carl",
  "ALLENSWORTH Dorothy": "allensworth-dorothy",
  "ALLERDYCE James": "allerdyce-james",
  "ALLERS Roger": "allers-roger",
  "ALLEY Fred": "alley-fred",
  "ALLEY Rewl": "alley-rewl",
  "ALLEYNE Arthur": "alleyne-arthur",
  "ALLEYNE Carla Debbie": "alleyne-carla-debbie",
  "ALLING Bodil": "alling-bodil",
  "ALLINGHAM Phillip": "allingham-phillip",
  "ALLINSON C C": "allinson-c-c",
  "ALLISON Christina": "allison-christina",
  "ALLISON David": "allison-david",
  "ALLISON Diane": "allison-diane",
  "ALLISON Hugh": "allison-hugh",
  "ALLISON Hughes": "allison-hughes",
  "ALLISON John": "allison-john",
  "ALLISON Lynn": "allison-lynn",
  "ALLISON Susie": "allison-susie",
  "ALLMAN John": "allman-john",
  "ALLMAN Kevin": "allman-kevin",
  "ALLMAN Paul": "allman-paul",
  "ALLMAN Sheldon": "allman-sheldon",
  "ALLNUTT David": "allnutt-david",
  "ALLOWAY Katrina": "alloway-katrina",
  "ALLSHOUSE Aaron": "allshouse-aaron",
  "ALLSOPP Warwick": "allsopp-warwick",
  "ALLT Nicky": "allt-nicky",
  "ALLTOP Kayce": "alltop-kayce",
  "ALLTOP Michael": "alltop-michael",
  "ALLUM Dan": "allum-dan",
  "ALLWEIS Lian": "allweis-lian",
  "ALLWOOD Peter": "allwood-peter",
  "ALLWOOD Ralph": "allwood-ralph",
  "ALLWRIGHT Christophe": "allwright-christophe",
  "ALLY Usman": "ally-usman",
  "ALLYN David": "allyn-david",
  "ALLYN Richard": "allyn-richard",
  "ALMA THEATRE ": "alma-theatre",
  "ALMAGOR Dan": "almagor-dan",
  "ALMAN Michael Stuart": "alman-michael-stuart",
  "ALMANZA Joseph D": "almanza-joseph-d",
  "ALMARIO Andrea": "almario-andrea",
  "ALMASY Jessica": "almasy-jessica",
  "ALMAZ Michael": "almaz-michael",
  "ALMAZAN Raquel": "almazan-raquel",
  "ALMEDINGEN E M": "almedingen-e-m",
  "ALMEIDA David": "almeida-david",
  "ALMELA Laura": "almela-laura",
  "ALMELEK Yakup": "almelek-yakup",
  "ALMENDAREZ Liliana": "almendarez-liliana",
  "ALMERAZ Peilin Chou": "almeraz-peilin-chou",
  "ALMIRON Jennifer": "almiron-jennifer",
  "ALMODOVAR Pedro": "almodovar-pedro",
  "ALMOG Ronny": "almog-ronny",
  "ALMONACID Camilo": "almonacid-camilo",
  "ALMOND David": "almond-david",
  "ALMOND Scott": "almond-scott",
  "ALMOND Suzy": "almond-suzy",
  "ALMOND Todd": "almond-todd",
  "ALMOS Carolyn": "almos-carolyn",
  "ALMOS Matt": "almos-matt",
  "ALMOST HUMAN ": "almost-human",
  "ALMQUIST Gregg": "almquist-gregg",
  "ALOMA Rene": "aloma-rene",
  "ALON Aaron": "alon-aaron",
  "ALONG HUMAN LINES ": "along-human-lines",
  "ALONI Nissim": "aloni-nissim",
  "ALONSO Tom": "alonso-tom",
  "ALONZO Cecil": "alonzo-cecil",
  "ALONZO Chris": "alonzo-chris",
  "ALONZO Dan": "alonzo-dan",
  "ALPAUGH Craig": "alpaugh-craig",
  "ALPER Linda": "alper-linda",
  "ALPER Sam": "alper-sam",
  "ALPER Steven M": "alper-steven-m",
  "ALPERN Joanna": "alpern-joanna",
  "ALPERT Sidsel Taubo": "alpert-sidsel-taubo",
  "ALPHONSE George": "alphonse-george",
  "ALPRIN Paula": "alprin-paula",
  "AL-QADY Towfiq": "al-qady-towfiq",
  "AL-RAEE Nabil": "al-raee-nabil",
  "ALRAWI Karim": "alrawi-karim",
  "ALSBERG Arthur": "alsberg-arthur",
  "AL-SHAIKH Hanan": "al-shaikh-hanan",
  "ALSINA Laia": "alsina-laia",
  "ALSON Lawrence": "alson-lawrence",
  "ALSOO Timothy": "alsoo-timothy",
  "ALSOP Gulielma Fell": "alsop-gulielma-fell",
  "ALSPAUGH Johnny": "alspaugh-johnny",
  "ALSPAUGH Matt": "alspaugh-matt",
  "ALSTER Pamela": "alster-pamela",
  "ALSTON Quinn M": "alston-quinn-m",
  "ALSUP Glenn": "alsup-glenn",
  "ALTENBURG Andrew": "altenburg-andrew",
  "ALTENBURG Steve James": "altenburg-steve-james",
  "ALTER Brandon": "alter-brandon",
  "ALTER Eric": "alter-eric",
  "ALTER Gaby": "alter-gaby",
  "ALTER Louis": "alter-louis",
  "ALTERMAN Glenn": "alterman-glenn",
  "ALTERMAN Peter": "alterman-peter",
  "ALTERMAN Sara Faith": "alterman-sara-faith",
  "ALTERS Gerald": "alters-gerald",
  "ALTMAN Alison": "altman-alison",
  "ALTMAN Caroline": "altman-caroline",
  "ALTMAN Dennis": "altman-dennis",
  "ALTMAN Mark": "altman-mark",
  "ALTMAN Sean": "altman-sean",
  "ALTMAN Zach": "altman-zach",
  "ALTMANN Howard": "altmann-howard",
  "ALTOMARE Carlo": "altomare-carlo",
  "ALTON Andrea": "alton-andrea",
  "ALTROWS Rona": "altrows-rona",
  "ALTY Andrew": "alty-andrew",
  "ALUKO Tayo": "aluko-tayo",
  "ALUMIT Noel": "alumit-noel",
  "ALVARADO Albert": "alvarado-albert",
  "ALVARADO Mando": "alvarado-mando",
  "ALVAREZ Adolfo Perez": "alvarez-adolfo-perez",
  "ALVAREZ Boni B": "alvarez-boni-b",
  "ALVAREZ Bosco Israel Cayo": "alvarez-bosco-israel-cayo",
  "ALVAREZ Cesar": "alvarez-cesar",
  "ALVAREZ Geoffrey": "alvarez-geoffrey",
  "ALVAREZ Ivy": "alvarez-ivy",
  "ALVAREZ Jay": "alvarez-jay",
  "ALVAREZ John K": "alvarez-john-k",
  "ALVAREZ Lynne": "alvarez-lynne",
  "ALVAREZ Michael": "alvarez-michael",
  "ALVAREZ Nino": "alvarez-nino",
  "ALVARO Corrado": "alvaro-corrado",
  "ALVERSON Charles": "alverson-charles",
  "ALVIK David": "alvik-david",
  "ALVIN Raymond": "alvin-raymond",
  "ALVIS Justin": "alvis-justin",
  "ALWAJ Abdelrahim": "alwaj-abdelrahim",
  "ALWIN-HILL R": "alwin-hill-r",
  "AL-ZAIDI Ali Abdel-Nabi": "al-zaidi-ali-abdel-nabi",
  "ALZOUGBI Alian": "alzougbi-alian",
  "AMACKER Johnathan E": "amacker-johnathan-e",
  "AMADA Rich": "amada-rich",
  "AMADIO Liz": "amadio-liz",
  "AMADO Jorge": "amado-jorge",
  "AMADOR Fredericao": "amador-fredericao",
  "AMALRIK Andrey": "amalrik-andrey",
  "AMAN Michael": "aman-michael",
  "AMANDES Paul": "amandes-paul",
  "AMANI V": "amani-v",
  "AMANO Karen": "amano-karen",
  "AMARIS Lian": "amaris-lian",
  "AMAS Michele": "amas-michele",
  "AMATO E": "amato-e",
  "AMATO Joe": "amato-joe",
  "AMATO Mike": "amato-mike",
  "AMAYA Hector Humberto": "amaya-hector-humberto",
  "AMBACHER Richard J": "ambacher-richard-j",
  "AMBATIELOS Genna": "ambatielos-genna",
  "AMBERLEY Liz": "amberley-liz",
  "AMBERLEY Simon": "amberley-simon",
  "AMBERLY Liz": "amberly-liz",
  "AMBIENT Mark": "ambient-mark",
  "AMBLER Laura": "ambler-laura",
  "AMBLER Scott": "ambler-scott",
  "AMBROGI Davide": "ambrogi-davide",
  "AMBROSE David": "ambrose-david",
  "AMBROSE Joan": "ambrose-joan",
  "AMBROSE Joel": "ambrose-joel",
  "AMBROSE Kanika": "ambrose-kanika",
  "AMBROSE Mike": "ambrose-mike",
  "AMBROSINI Tommy": "ambrosini-tommy",
  "AMEEN Mark": "ameen-mark",
  "AMELIO Vincent": "amelio-vincent",
  "AMEN Luce": "amen-luce",
  "AMEND Howard T": "amend-howard-t",
  "AMENDOLA-ROGERS Adriana": "amendola-rogers-adriana",
  "AMENTA Mark": "amenta-mark",
  "AMERICAN LABORATORY, THE ": "american-laboratory",
  "AMERICAN REPERTORY THEATRE ": "american-repertory-theatre",
  "AMES Gustavo": "ames-gustavo",
  "AMES Jonathan": "ames-jonathan",
  "AMES Kirsten": "ames-kirsten",
  "AMESBURY Elisa": "amesbury-elisa",
  "AMEY Rachel": "amey-rachel",
  "AMICHAL-YEVIN Ada": "amichal-yevin-ada",
  "AMIDEI Aly Renee": "amidei-aly-renee",
  "AMIEL Denys": "amiel-denys",
  "AMIEL ": "amiel",
  "AMIES Brenton": "amies-brenton",
  "AMIES Stephanie Jayne": "amies-stephanie-jayne",
  "AMIN Dina": "amin-dina",
  "AMIRAULT Allison A": "amirault-allison-a",
  "AMIRKHANIAN Aida": "amirkhanian-aida",
  "AMIS Lola E": "amis-lola-e",
  "AMIS Martin": "amis-martin",
  "AMLEHN Paul": "amlehn-paul",
  "AMLEN Elinor": "amlen-elinor",
  "AMMA Sia": "amma-sia",
  "AMMAR Ryan": "ammar-ryan",
  "AMMERMAN John": "ammerman-john",
  "AMMIRATE Camilla": "ammirate-camilla",
  "AMO Thomas": "amo-thomas",
  "AMOASA Fasitua": "amoasa-fasitua",
  "AMOR Edward": "amor-edward",
  "AMOROS Larry": "amoros-larry",
  "AMOROSO Ronald": "amoroso-ronald",
  "AMOS Chris": "amos-chris",
  "AMOS Janet": "amos-janet",
  "AMOS Robert": "amos-robert",
  "AMOS Tori": "amos-tori",
  "AMOSA Fasitua": "amosa-fasitua",
  "AMPARANO Julie Ann": "amparano-julie-ann",
  "AMSBURY Beth": "amsbury-beth",
  "AMSBURY Zay": "amsbury-zay",
  "AMSTERDAM Diana": "amsterdam-diana",
  "AMUNDSEN Allen": "amundsen-allen",
  "AMUNDSON Connie": "amundson-connie",
  "AMY Remi": "amy-remi",
  "ANAGNOSTAKI Loula": "anagnostaki-loula",
  "ANALOGUE ": "analogue",
  "ANAND Mulk Raj": "anand-mulk-raj",
  "ANAST Jory": "anast-jory",
  "ANASTASI John": "anastasi-john",
  "ANASTASI Tom": "anastasi-tom",
  "ANASTASIO Trey": "anastasio-trey",
  "ANASTASSIOU Philip John": "anastassiou-philip-john",
  "ANCHANG Jude": "anchang-jude",
  "ANCHETA Karen": "ancheta-karen",
  "ANCLIFFE Leon": "ancliffe-leon",
  "ANCOWITZ Nancy": "ancowitz-nancy",
  "ANDERMAN Gunilla M": "anderman-gunilla-m",
  "ANDERS Christoph": "anders-christoph",
  "ANDERS Doug": "anders-doug",
  "ANDERSEN Anna": "andersen-anna",
  "ANDERSEN D R": "andersen-d-r",
  "ANDERSEN Dale": "andersen-dale",
  "ANDERSEN Daniel": "andersen-daniel",
  "ANDERSEN Dennis": "andersen-dennis",
  "ANDERSEN Emily": "andersen-emily",
  "ANDERSEN Lemon": "andersen-lemon",
  "ANDERSEN Mads Floor": "andersen-mads-floor",
  "ANDERSEN Mal": "andersen-mal",
  "ANDERSEN Marit": "andersen-marit",
  "ANDERSEN Mark": "andersen-mark",
  "ANDERSEN Paul": "andersen-paul",
  "ANDERSEN Suzanne": "andersen-suzanne",
  "ANDERSEN-BLOOMFIELD Doc": "andersen-bloomfield-doc",
  "ANDERSON Abigail": "anderson-abigail",
  "ANDERSON Adam C": "anderson-adam-c",
  "ANDERSON Adele": "anderson-adele",
  "ANDERSON Andre": "anderson-andre",
  "ANDERSON Andrew": "anderson-andrew",
  "ANDERSON Balfour": "anderson-balfour",
  "ANDERSON Barbara": "anderson-barbara",
  "ANDERSON Bart": "anderson-bart",
  "ANDERSON Beatrice": "anderson-beatrice",
  "ANDERSON Becca": "anderson-becca",
  "ANDERSON Ben": "anderson-ben",
  "ANDERSON Benedict": "anderson-benedict",
  "ANDERSON Bo": "anderson-bo",
  "ANDERSON Bonnie": "anderson-bonnie",
  "ANDERSON Brandon": "anderson-brandon",
  "ANDERSON Carol": "anderson-carol",
  "ANDERSON Cas": "anderson-cas",
  "ANDERSON Charlotte": "anderson-charlotte",
  "ANDERSON Chinita L": "anderson-chinita-l",
  "ANDERSON Christina": "anderson-christina",
  "ANDERSON Chuck": "anderson-chuck",
  "ANDERSON Clement": "anderson-clement",
  "ANDERSON Dana": "anderson-dana",
  "ANDERSON Daniel": "anderson-daniel",
  "ANDERSON Dave": "anderson-dave",
  "ANDERSON Davey": "anderson-davey",
  "ANDERSON David": "anderson-david",
  "ANDERSON Dean": "anderson-dean",
  "ANDERSON Dennis": "anderson-dennis",
  "ANDERSON Diana": "anderson-diana",
  "ANDERSON Donna Gay": "anderson-donna-gay",
  "ANDERSON Doug": "anderson-doug",
  "ANDERSON Douglas": "anderson-douglas",
  "ANDERSON Eliza": "anderson-eliza",
  "ANDERSON Ellen K": "anderson-ellen-k",
  "ANDERSON Emily": "anderson-emily",
  "ANDERSON Eric": "anderson-eric",
  "ANDERSON Erik": "anderson-erik",
  "ANDERSON Ernest": "anderson-ernest",
  "ANDERSON Eva": "anderson-eva",
  "ANDERSON Finn": "anderson-finn",
  "ANDERSON Freddy": "anderson-freddy",
  "ANDERSON Gai": "anderson-gai",
  "ANDERSON Gary L": "anderson-gary-l",
  "ANDERSON Graham": "anderson-graham",
  "ANDERSON Hilda": "anderson-hilda",
  "ANDERSON Iain F": "anderson-iain-f",
  "ANDERSON Ioanna": "anderson-ioanna",
  "ANDERSON J": "anderson-j",
  "ANDERSON Jane": "anderson-jane",
  "ANDERSON Jason": "anderson-jason",
  "ANDERSON Jen": "anderson-jen",
  "ANDERSON Jennifer Jean": "anderson-jennifer-jean",
  "ANDERSON Jim Tyler": "anderson-jim-tyler",
  "ANDERSON Jo": "anderson-jo",
  "ANDERSON John (1)": "anderson-john-1",
  "ANDERSON John (2)": "anderson-john-2",
  "ANDERSON John C": "anderson-john-c",
  "ANDERSON John Stuart": "anderson-john-stuart",
  "ANDERSON Joseph Reese": "anderson-joseph-reese",
  "ANDERSON Joy": "anderson-joy",
  "ANDERSON Jude": "anderson-jude",
  "ANDERSON Judy": "anderson-judy",
  "ANDERSON Julian": "anderson-julian",
  "ANDERSON Kate": "anderson-kate",
  "ANDERSON Kathleen McGhee": "anderson-kathleen-mcghee",
  "ANDERSON Kathy": "anderson-kathy",
  "ANDERSON Ken": "anderson-ken",
  "ANDERSON Kenneth": "anderson-kenneth",
  "ANDERSON Kent": "anderson-kent",
  "ANDERSON Kristen": "anderson-kristen",
  "ANDERSON Kyle": "anderson-kyle",
  "ANDERSON Laurie": "anderson-laurie",
  "ANDERSON Lea": "anderson-lea",
  "ANDERSON Lee": "anderson-lee",
  "ANDERSON Marilyn D": "anderson-marilyn-d",
  "ANDERSON Mark": "anderson-mark",
  "ANDERSON Mary": "anderson-mary",
  "ANDERSON Matthew S": "anderson-matthew-s",
  "ANDERSON Mattias": "anderson-mattias",
  "ANDERSON Maxwell": "anderson-maxwell",
  "ANDERSON Melody": "anderson-melody",
  "ANDERSON Michael": "anderson-michael",
  "ANDERSON Michael (1)": "anderson-michael-1",
  "ANDERSON Nancy K": "anderson-nancy-k",
  "ANDERSON Noel": "anderson-noel",
  "ANDERSON Odie": "anderson-odie",
  "ANDERSON Orjan": "anderson-orjan",
  "ANDERSON Pete": "anderson-pete",
  "ANDERSON Peter": "anderson-peter",
  "ANDERSON R A": "anderson-r-a",
  "ANDERSON Rachel": "anderson-rachel",
  "ANDERSON Randy": "anderson-randy",
  "ANDERSON Rica": "anderson-rica",
  "ANDERSON Richard": "anderson-richard",
  "ANDERSON Rita": "anderson-rita",
  "ANDERSON Rob Winn": "anderson-rob-winn",
  "ANDERSON Robert": "anderson-robert",
  "ANDERSON Robert A": "anderson-robert-a",
  'ANDERSON Robert Bruce "Bo"': "anderson-robert-bruce",
  "ANDERSON Rod": "anderson-rod",
  "ANDERSON Roger": "anderson-roger",
  "ANDERSON Ryan Vincent": "anderson-ryan-vincent",
  "ANDERSON Sara Pia": "anderson-sara-pia",
  "ANDERSON Shirley": "anderson-shirley",
  "ANDERSON Stanice": "anderson-stanice",
  "ANDERSON Steven": "anderson-steven",
  "ANDERSON Steven C": "anderson-steven-c",
  "ANDERSON T Dianne": "anderson-t-dianne",
  "ANDERSON Tammy": "anderson-tammy",
  "ANDERSON Trevor": "anderson-trevor",
  "ANDERSON Valdemar": "anderson-valdemar",
  "ANDERSON Valetta": "anderson-valetta",
  "ANDERSON Walt": "anderson-walt",
  "ANDERSON Will": "anderson-will",
  "ANDERSON COLLEGE SOUTH CAROLINA ": "anderson-college-south-carolina",
  "ANDERSON III T J": "anderson-iii-t-j",
  "ANDERSON-BLOOMFIELD Doc": "anderson-bloomfield-doc",
  "ANDERSON-COBB Nicole": "anderson-cobb-nicole",
  "ANDERSON-LOPEZ Kristen": "anderson-lopez-kristen",
  "ANDERSSON Benny": "andersson-benny",
  "ANDERSSON Kris": "andersson-kris",
  "ANDERSSON Mattias": "andersson-mattias",
  "ANDERSSON Ulla": "andersson-ulla",
  "ANDERT John": "andert-john",
  "ANDINO Eduardo": "andino-eduardo",
  "ANDO Yuka": "ando-yuka",
  "ANDOH Adjoa": "andoh-adjoa",
  "ANDOH-MENSON Kweku": "andoh-menson-kweku",
  "ANDOLORA Tom": "andolora-tom",
  "ANDRACCHI Erica": "andracchi-erica",
  "ANDRADE Christopher": "andrade-christopher",
  "ANDRADE Jorge": "andrade-jorge",
  "ANDRADE Monica": "andrade-monica",
  "ANDRADE Suzanne": "andrade-suzanne",
  "ANDRE Marion": "andre-marion",
  "ANDRE Rolls": "andre-rolls",
  "ANDRE Ty": "andre-ty",
  "ANDREACCHI Grace": "andreacchi-grace",
  "ANDREADI Ioli": "andreadi-ioli",
  "ANDREANI Sydney": "andreani-sydney",
  "ANDREAS Michael": "andreas-michael",
  "ANDREASON Don": "andreason-don",
  "ANDREI Amanda": "andrei-amanda",
  "ANDREI Julian": "andrei-julian",
  "ANDREINI John": "andreini-john",
  "ANDREIS Sandra Karloina": "andreis-sandra-karloina",
  "ANDREJKO David Alex": "andrejko-david-alex",
  "ANDRENELLI Cid": "andrenelli-cid",
  "ANDREOTTOLA Marc": "andreottola-marc",
  "ANDRES Brett": "andres-brett",
  "ANDREW Mark": "andrew-mark",
  "ANDREW Simon": "andrew-simon",
  "ANDREWA Peter": "andrewa-peter",
  "ANDREWARTHA Jessica": "andrewartha-jessica",
  "ANDREWS A P": "andrews-a-p",
  "ANDREWS Alison": "andrews-alison",
  "ANDREWS Andy": "andrews-andy",
  "ANDREWS Angeline": "andrews-angeline",
  "ANDREWS Bart": "andrews-bart",
  "ANDREWS Benedict": "andrews-benedict",
  "ANDREWS Beverley": "andrews-beverley",
  "ANDREWS Brian": "andrews-brian",
  "ANDREWS Casey Jay": "andrews-casey-jay",
  "ANDREWS Damon": "andrews-damon",
  "ANDREWS Debbie": "andrews-debbie",
  "ANDREWS Dwayne": "andrews-dwayne",
  "ANDREWS Graham": "andrews-graham",
  "ANDREWS Isobel": "andrews-isobel",
  "ANDREWS Jan": "andrews-jan",
  "ANDREWS Jenny": "andrews-jenny",
  "ANDREWS Jesse": "andrews-jesse",
  "ANDREWS John Neville": "andrews-john-neville",
  "ANDREWS Kate": "andrews-kate",
  "ANDREWS Kaye": "andrews-kaye",
  "ANDREWS Nick": "andrews-nick",
  "ANDREWS Norman": "andrews-norman",
  "ANDREWS Regina": "andrews-regina",
  "ANDREWS Richard": "andrews-richard",
  "ANDREWS Ross": "andrews-ross",
  "ANDREWS Stephen": "andrews-stephen",
  "ANDREWS Steve": "andrews-steve",
  "ANDREWS Tim": "andrews-tim",
  "ANDREWS Vicky": "andrews-vicky",
  "ANDREWS William": "andrews-william",
  "ANDREYEV Leonid": "andreyev-leonid",
  "ANDRIANO Vincent": "andriano-vincent",
  "ANDRIELLO Rita": "andriello-rita",
  "ANDRIST Eric": "andrist-eric",
  "ANDRON Ben": "andron-ben",
  "ANDRONICOS Kelly": "andronicos-kelly",
  "ANDRUCKI Martin": "andrucki-martin",
  "ANDRUSEWICZ Marie": "andrusewicz-marie",
  "ANELLI Paul": "anelli-paul",
  "ANFIELD Alexandria": "anfield-alexandria",
  "ANFILOGOFF Tim": "anfilogoff-tim",
  "ANG Gay Pin": "ang-gay-pin",
  "ANG Michelle": "ang-michelle",
  "ANGEL Leonard": "angel-leonard",
  "ANGEL Marie": "angel-marie",
  "ANGEL Nick": "angel-nick",
  "ANGEL Sabina": "angel-sabina",
  "ANGEL EXIT THEATRE ": "angel-exit-theatre",
  "ANGELICA Ethan": "angelica-ethan",
  "ANGELINI Claudio": "angelini-claudio",
  "ANGELINI Kieran": "angelini-kieran",
  "ANGELINI Tony": "angelini-tony",
  "ANGELL Glynis": "angell-glynis",
  "ANGELL Jeannette": "angell-jeannette",
  "ANGELO Judy Hart": "angelo-judy-hart",
  "ANGELOCH Alexandra": "angeloch-alexandra",
  "ANGELOS Maureen": "angelos-maureen",
  "ANGELOS Moe": "angelos-moe",
  "ANGELOU Maya": "angelou-maya",
  "ANGELS AND VIRGINS THEATRE COMPANY ": "angels-and-virgins-theatre-company",
  "ANGELS OF DISORDER ": "angels-of-disorder",
  "ANGELSON Sophie": "angelson-sophie",
  "ANGERSON Jeremy": "angerson-jeremy",
  "ANGLEY Cassie": "angley-cassie",
  "ANGLIN Michelle": "anglin-michelle",
  "ANGRESS Therese": "angress-therese",
  "ANGUS Gemma": "angus-gemma",
  "ANHALT Edward": "anhalt-edward",
  "ANHOLT Maddy": "anholt-maddy",
  "ANISSIMOVA Evelina": "anissimova-evelina",
  "ANKER Charlotte": "anker-charlotte",
  "ANKETELL Christine": "anketell-christine",
  "ANKUR PRODUCTIONS ADULT THEATRE WORKSHOP ": "ankur-productions-adult-theatre-workshop",
  "ANNA Anna": "anna-anna",
  "ANNA PROJECT ": "anna-project",
  "ANNAN Jim": "annan-jim",
  "ANNE Catherine": "anne-catherine",
  "ANNEN David": "annen-david",
  "ANNING Jane": "anning-jane",
  "ANNIS Melisa": "annis-melisa",
  "ANNOYANCE THEATER ": "annoyance-theater",
  "ANNTARES Tita": "anntares-tita",
  "ANON ": "anon",
  "ANONYMOUS ": "anonymous",
  "ANONYMOUS IRANIAN ": "anonymous-iranian",
  "ANOSA Rima": "anosa-rima",
  "ANOUILH Jean": "anouilh-jean",
  "ANSART Jim": "ansart-jim",
  "ANSDELL David": "ansdell-david",
  "ANSELL Adam J": "ansell-adam-j",
  "ANSELL Rod": "ansell-rod",
  "ANSELM Ludmila": "anselm-ludmila",
  "ANSELMI Barbara": "anselmi-barbara",
  "ANSELMI Marilynn Barner": "anselmi-marilynn-barner",
  "ANSELMO Christopher Michael": "anselmo-christopher-michael",
  "ANSELMO Tom": "anselmo-tom",
  "ANSKI Shalom": "anski-shalom",
  "ANSON Joe": "anson-joe",
  "ANSORGE Peter": "ansorge-peter",
  "ANSTRUTHER Gerald": "anstruther-gerald",
  "ANTAL Paul": "antal-paul",
  "ANTAR Eddie": "antar-eddie",
  "ANTHEIL George": "antheil-george",
  "ANTHILL THEATRE ": "anthill-theatre",
  "ANTHONY Adelina": "anthony-adelina",
  "ANTHONY Brian": "anthony-brian",
  "ANTHONY C L": "anthony-c-l",
  "ANTHONY Christina": "anthony-christina",
  "ANTHONY Dan": "anthony-dan",
  "ANTHONY Darren": "anthony-darren",
  "ANTHONY Earl": "anthony-earl",
  "ANTHONY Edward": "anthony-edward",
  "ANTHONY John": "anthony-john",
  "ANTHONY Marcus": "anthony-marcus",
  "ANTHONY Mark": "anthony-mark",
  "ANTHONY Meredith": "anthony-meredith",
  "ANTHONY Peter": "anthony-peter",
  "ANTHONY Robert": "anthony-robert",
  "ANTHONY Rock": "anthony-rock",
  "ANTHONY Terence": "anthony-terence",
  "ANTHONY Terrell": "anthony-terrell",
  "ANTHONY Trey": "anthony-trey",
  "ANTHONY ": "anthony",
  "ANTIEL Cory": "antiel-cory",
  "ANTLER THEATRE ": "antler-theatre",
  "ANTOLINI Jeanie": "antolini-jeanie",
  "ANTOLJAK Nina": "antoljak-nina",
  "ANTON Dorothy": "anton-dorothy",
  "ANTON Greg": "anton-greg",
  "ANTONACCI Greg": "antonacci-greg",
  "ANTONAKES Michael": "antonakes-michael",
  "ANTONE Tiffany": "antone-tiffany",
  "ANTONIO James": "antonio-james",
  "ANTONIO Raf": "antonio-raf",
  "ANTONIO Salvatore": "antonio-salvatore",
  "ANTONIOLI Courtney": "antonioli-courtney",
  "ANTONIOLI Siobhan": "antonioli-siobhan",
  "ANTONOCCI Greg": "antonocci-greg",
  "ANTROBUS John": "antrobus-john",
  "ANTRUM Janyia": "antrum-janyia",
  "ANU PRODUCTIONS ": "anu-productions",
  "ANWAR Keith": "anwar-keith",
  "ANWAR Subika": "anwar-subika",
  "ANWEN Gabrielle": "anwen-gabrielle",
  "ANYA Rain": "anya-rain",
  "ANZENGRUBER Ludwig": "anzengruber-ludwig",
  "ANZIA Lys": "anzia-lys",
  "ANZUELO David": "anzuelo-david",
  "AOKI Brenda Wong": "aoki-brenda-wong",
  "AOKI Dance": "aoki-dance",
  "AP EMRYS Jonathan": "ap-emrys-jonathan",
  "APARICIO Rebecca": "aparicio-rebecca",
  "APATICIO Ariel": "apaticio-ariel",
  "APELBAUM Stanley": "apelbaum-stanley",
  "APHRODITE Brigitte": "aphrodite-brigitte",
  "APIO Alan": "apio-alan",
  "APKER Susan": "apker-susan",
  "APLIN Jackie": "aplin-jackie",
  "APODACA Jackie": "apodaca-jackie",
  "APOLINAR Danny": "apolinar-danny",
  "APOLLINAIRE Guillaume": "apollinaire-guillaume",
  "APOLO Ignacio": "apolo-ignacio",
  "APONTE Marco": "aponte-marco",
  "APOSTOL Troy": "apostol-troy",
  "APOSTOLINA Steve": "apostolina-steve",
  "APPEL Allan": "appel-allan",
  "APPEL Camila": "appel-camila",
  "APPEL Dori": "appel-dori",
  "APPEL Elizabeth": "appel-elizabeth",
  "APPEL Greg": "appel-greg",
  "APPEL Jacob M": "appel-jacob-m",
  "APPEL Sonya": "appel-sonya",
  "APPELBAUM Marci": "appelbaum-marci",
  "APPELL Don": "appell-don",
  "APPELL Elizabeth": "appell-elizabeth",
  "APPINO Nikki": "appino-nikki",
  "APPLE Gary": "apple-gary",
  "APPLE Lawrence": "apple-lawrence",
  "APPLEBAUM Jessica Kaplow": "applebaum-jessica-kaplow",
  "APPLEBEE Bec": "applebee-bec",
  "APPLEBY Damian": "appleby-damian",
  "APPLEBY Jane": "appleby-jane",
  "APPLEBY Sue": "appleby-sue",
  "APPLEFORD David": "appleford-david",
  "APPLEGARTH Margaret T": "applegarth-margaret-t",
  "APPLEGATE Joe": "applegate-joe",
  "APPLEMAN Herbert": "appleman-herbert",
  "APPLEMAN M H": "appleman-m-h",
  "APPLETON Eric": "appleton-eric",
  "APPLIN Rebecca": "applin-rebecca",
  "APPOLLIS Basil": "appollis-basil",
  "APPRENTICED ACTORS COMPANY, THE ": "apprenticed-actors-company",
  "APPS Roy": "apps-roy",
  "APRAHAMIAN Steven": "aprahamian-steven",
  "APRILL Arnold": "aprill-arnold",
  "APSTEIN Theodore": "apstein-theodore",
  "APUKHTINE Alexis": "apukhtine-alexis",
  "APULEIUS ": "apuleius",
  "AQUENO Frank": "aqueno-frank",
  "AQUILA Pieter": "aquila-pieter",
  "AQUILANTE Michael Tommasone": "aquilante-michael-tommasone",
  "AQUILER Louis": "aquiler-louis",
  "AQUILINA Corinne": "aquilina-corinne",
  "AQUILINA Danielle": "aquilina-danielle",
  "AQUINO Nina": "aquino-nina",
  "AQUINO Regina": "aquino-regina",
  "ARACALANDANZA ": "aracalandanza",
  "ARAD GOCH ": "arad-goch",
  "ARAGNO Riccardo": "aragno-riccardo",
  "ARAGON Clyde James": "aragon-clyde-james",
  "ARAGON Joseph": "aragon-joseph",
  "ARAGON Louis": "aragon-louis",
  "ARAIZA Albert Antonio": "araiza-albert-antonio",
  "ARAIZA J Ed": "araiza-j-ed",
  "ARAKAWA Suzanne": "arakawa-suzanne",
  "ARAN Catherine": "aran-catherine",
  "ARANAS Pilbuen": "aranas-pilbuen",
  "ARANCIO Lawrence": "arancio-lawrence",
  "ARANEDA Cecilia": "araneda-cecilia",
  "ARANGIO Carmela": "arangio-carmela",
  "ARANHA Ray": "aranha-ray",
  "ARANSON Jack": "aranson-jack",
  "ARAPAI Arnette": "arapai-arnette",
  "ARATA Luis O": "arata-luis-o",
  "ARAUJO Luis": "araujo-luis",
  "ARAUJO Suzette": "araujo-suzette",
  "ARAVAYA Gene": "aravaya-gene",
  "ARBATOVA Maria": "arbatova-maria",
  "ARBEIT Rachel": "arbeit-rachel",
  "ARBER Gyda": "arber-gyda",
  "ARBER Steve": "arber-steve",
  "ARBERY Will": "arbery-will",
  "ARBUCIAS Joyce": "arbucias-joyce",
  "ARBUS Doon": "arbus-doon",
  "ARBUZOV Aleksei": "arbuzov-aleksei",
  "ARCA Jefferson": "arca-jefferson",
  "ARCADE Penny": "arcade-penny",
  "ARCESE Peter Vincent": "arcese-peter-vincent",
  "ARCH Jeff": "arch-jeff",
  "ARCHAMBAULT Francois": "archambault-francois",
  "ARCHBOLD Alan": "archbold-alan",
  "ARCHDEACON Sarah": "archdeacon-sarah",
  "ARCHER Daniel": "archer-daniel",
  "ARCHER Dudley": "archer-dudley",
  "ARCHER Elizabeth": "archer-elizabeth",
  "ARCHER Jeffrey": "archer-jeffrey",
  "ARCHER John": "archer-john",
  "ARCHER Kendall": "archer-kendall",
  "ARCHER Lavern": "archer-lavern",
  "ARCHER Robyn": "archer-robyn",
  "ARCHER Rodney": "archer-rodney",
  "ARCHER William": "archer-william",
  "ARCHIBALD Dan": "archibald-dan",
  "ARCHIBALD David": "archibald-david",
  "ARCHIBALD Douglas (Rupert)": "archibald-douglas-rupert",
  "ARCHIBALD Janet": "archibald-janet",
  "ARCHIBALD William": "archibald-william",
  "ARCIERI D T": "arcieri-d-t",
  "ARCINIEGAS Diego": "arciniegas-diego",
  "ARCO John R": "arco-john-r",
  "ARCURI Vincent James": "arcuri-vincent-james",
  "ARDAL Maja": "ardal-maja",
  "ARDEN Andrea": "arden-andrea",
  "ARDEN Annabel": "arden-annabel",
  "ARDEN Chris": "arden-chris",
  "ARDEN Ilayda": "arden-ilayda",
  "ARDEN Jane": "arden-jane",
  "ARDEN John": "arden-john",
  "ARDEN Leslie": "arden-leslie",
  "ARDERN Jonny": "ardern-jonny",
  "ARDERN Stuart": "ardern-stuart",
  "ARDIFF Karen": "ardiff-karen",
  "ARDITO Carlo": "ardito-carlo",
  "ARDITTI Michael": "arditti-michael",
  "ARDITTI Philip": "arditti-philip",
  "ARDO Zsuzsanna": "ardo-zsuzsanna",
  "ARDOLINO John": "ardolino-john",
  "ARDOV Viktor": "ardov-viktor",
  "ARDREY Robert": "ardrey-robert",
  "ARE David": "are-david",
  "ARELINA Pietro": "arelina-pietro",
  "AREMU Aduke": "aremu-aduke",
  "ARENDS Mark": "arends-mark",
  "ARENS Kellie": "arens-kellie",
  "ARENT Arthur": "arent-arthur",
  "ARETINO Pietro": "aretino-pietro",
  "ARGALL Liz": "argall-liz",
  "ARGALL T Gregory": "argall-t-gregory",
  "ARGENT Geoffrey Alan": "argent-geoffrey-alan",
  "ARGENT Rod": "argent-rod",
  "ARGENT Sarah": "argent-sarah",
  "ARGETSINGER Gerald S": "argetsinger-gerald-s",
  "ARGUE Karl": "argue-karl",
  "ARIADONE COMPANY ": "ariadone-company",
  "ARIAS Joey": "arias-joey",
  "ARIAS Leila": "arias-leila",
  "ARIAS Lola": "arias-lola",
  "ARIAS Maria-Jose Rague": "arias-maria-jose-rague",
  "ARIAS Roy": "arias-roy",
  "ARIAV Tali": "ariav-tali",
  "ARICO Ashley": "arico-ashley",
  "ARIEL TEATR ": "ariel-teatr",
  "ARIETI Olivia": "arieti-olivia",
  "ARIMOTO Kendra Chiyoko": "arimoto-kendra-chiyoko",
  "ARIN Jesper": "arin-jesper",
  "ARIOSTO Lodovico": "ariosto-lodovico",
  "ARISS Paddy": "ariss-paddy",
  "ARISS Peter": "ariss-peter",
  "ARISTARCO Maria": "aristarco-maria",
  "ARISTIDOU Dinos": "aristidou-dinos",
  "ARISTIZABAL Hector": "aristizabal-hector",
  "ARISTOPHANES ": "aristophanes",
  "ARIZA Rene": "ariza-rene",
  "ARIZMENDI Yareli": "arizmendi-yareli",
  "ARK THEATRE ": "ark-theatre",
  "ARKASS George": "arkass-george",
  "ARKEKETA Annette": "arkeketa-annette",
  "ARKHIPOV Alexander": "arkhipov-alexander",
  "ARKIN Alan": "arkin-alan",
  "ARKY Darian": "arky-darian",
  "ARKY Jake Marshall": "arky-jake-marshall",
  "ARLEN Albert": "arlen-albert",
  "ARLEN Harold": "arlen-harold",
  "ARLEN Michael": "arlen-michael",
  "ARLENE KARON STUDENTS ": "arlene-karon-students",
  "ARLETT Vera I": "arlett-vera-i",
  "ARLEY Catherine": "arley-catherine",
  "ARM Aaron": "arm-aaron",
  "ARMAH Esther": "armah-esther",
  "ARMAND Clara": "armand-clara",
  "ARMANDO Bruno": "armando-bruno",
  "ARMANI Nora": "armani-nora",
  "ARMBRUSTER Heidi": "armbruster-heidi",
  "ARME Robert": "arme-robert",
  "ARMENANTE Jillian": "armenante-jillian",
  "ARMENTO Kevin": "armento-kevin",
  "ARMENTO Paul": "armento-paul",
  "ARMER Jamie": "armer-jamie",
  "ARMES Helen": "armes-helen",
  "ARMESTO Carlos": "armesto-carlos",
  "ARMESTO Sebastian": "armesto-sebastian",
  "ARMFIELD Neil": "armfield-neil",
  "ARMIN Gerald": "armin-gerald",
  "ARMISTEAD Julian": "armistead-julian",
  "ARMITAGE Alex": "armitage-alex",
  "ARMITAGE Andy": "armitage-andy",
  "ARMITAGE Jenny": "armitage-jenny",
  "ARMITAGE Katharine": "armitage-katharine",
  "ARMITAGE Kimo": "armitage-kimo",
  "ARMITAGE Marigold": "armitage-marigold",
  "ARMITAGE Simon": "armitage-simon",
  "ARMITSTEAD Julian": "armitstead-julian",
  "ARMITT David": "armitt-david",
  "ARMOUR Toby": "armour-toby",
  "ARMSTRONG Alana": "armstrong-alana",
  "ARMSTRONG Anthony": "armstrong-anthony",
  "ARMSTRONG Billie Joe": "armstrong-billie-joe",
  "ARMSTRONG Bob": "armstrong-bob",
  "ARMSTRONG Caitlin": "armstrong-caitlin",
  "ARMSTRONG Charlotte": "armstrong-charlotte",
  "ARMSTRONG Craig": "armstrong-craig",
  "ARMSTRONG Dave": "armstrong-dave",
  "ARMSTRONG Doug": "armstrong-doug",
  "ARMSTRONG Frank": "armstrong-frank",
  "ARMSTRONG Gareth": "armstrong-gareth",
  "ARMSTRONG Gordon": "armstrong-gordon",
  "ARMSTRONG Ian": "armstrong-ian",
  "ARMSTRONG James": "armstrong-james",
  "ARMSTRONG Jo-Anne": "armstrong-jo-anne",
  "ARMSTRONG John": "armstrong-john",
  "ARMSTRONG Jon": "armstrong-jon",
  "ARMSTRONG Joy": "armstrong-joy",
  "ARMSTRONG Ken": "armstrong-ken",
  "ARMSTRONG Ken (1)": "armstrong-ken-1",
  "ARMSTRONG Margaret": "armstrong-margaret",
  "ARMSTRONG Michael": "armstrong-michael",
  "ARMSTRONG Neil": "armstrong-neil",
  "ARMSTRONG Robin": "armstrong-robin",
  "ARMSTRONG William": "armstrong-william",
  "ARMSTRONG-DE VREEZE Pamela": "armstrong-de-vreeze-pamela",
  "ARMSTRONG-TAYLOR Tim": "armstrong-taylor-tim",
  "ARNARSSON Thorleifur Orn": "arnarsson-thorleifur-orn",
  "ARNDT Walter": "arndt-walter",
  "ARNEL Seamus": "arnel-seamus",
  "ARNESON Donald": "arneson-donald",
  "ARNESON Heidi": "arneson-heidi",
  "ARNEST Lauren": "arnest-lauren",
  "ARNEST Mark": "arnest-mark",
  "ARNEY Helen": "arney-helen",
  "ARNFIELD Jane": "arnfield-jane",
  "ARNGRIM Alison": "arngrim-alison",
  "ARNHALT Edward": "arnhalt-edward",
  "ARNO Owen G": "arno-owen-g",
  "ARNOLD Andy": "arnold-andy",
  "ARNOLD Anthony": "arnold-anthony",
  "ARNOLD Ben": "arnold-ben",
  "ARNOLD Bill": "arnold-bill",
  "ARNOLD Bill (1)": "arnold-bill-1",
  "ARNOLD C D": "arnold-c-d",
  "ARNOLD Camilla": "arnold-camilla",
  "ARNOLD Damien": "arnold-damien",
  "ARNOLD Daniel": "arnold-daniel",
  "ARNOLD Diana": "arnold-diana",
  "ARNOLD Jessica": "arnold-jessica",
  "ARNOLD John": "arnold-john",
  "ARNOLD Josh": "arnold-josh",
  "ARNOLD Kenneth": "arnold-kenneth",
  "ARNOLD Lucy": "arnold-lucy",
  "ARNOLD Peter": "arnold-peter",
  "ARNOLD Scotty": "arnold-scotty",
  "ARNOLD William": "arnold-william",
  "ARNON Valerie": "arnon-valerie",
  "ARNOS Tori": "arnos-tori",
  "ARNOSKY Brian": "arnosky-brian",
  "ARNOTT Amanda": "arnott-amanda",
  "ARNOTT Deborah": "arnott-deborah",
  "ARNOTT Paul": "arnott-paul",
  "ARNOTT Peter": "arnott-peter",
  "ARNOTT Peter (1)": "arnott-peter-1",
  "ARNOTT Peter D": "arnott-peter-d",
  "ARNOTT W G": "arnott-w-g",
  "ARNSTEIN Felix G": "arnstein-felix-g",
  "ARNTSON Bruce": "amtson-bruce",
  "ARNTZ James": "arntz-james",
  "ARON Adrianne": "aron-adrianne",
  "ARON Geraldine": "aron-geraldine",
  "ARON Wendy": "aron-wendy",
  "ARONEAU Elisabeth": "aroneau-elisabeth",
  "ARONOFF Eddie": "aronoff-eddie",
  "ARONOFF Linda": "aronoff-linda",
  "ARONOFF Marc": "aronoff-marc",
  "ARONOV Michael": "aronov-michael",
  "ARONOVITCH Lawrence": "aronovitch-lawrence",
  "ARONOWITZ Sonya": "aronowitz-sonya",
  "ARONSON Alvin": "aronson-alvin",
  "ARONSON Barton": "aronson-barton",
  "ARONSON Billy": "aronson-billy",
  "ARONSON Henry": "aronson-henry",
  "ARONSON Linda": "aronson-linda",
  "ARONSON Shari": "aronson-shari",
  "ARONSON William": "aronson-william",
  "ARONSTEN Chris": "aronsten-chris",
  "ARONVITCH Lawrence": "aronvitch-lawrence",
  "ARORA Renu": "arora-renu",
  "AROUT Gabriel": "arout-gabriel",
  "ARQUEROS Joelle": "arqueros-joelle",
  "ARRABAL Fernando": "arrabal-fernando",
  "ARRAHALL ": "arrahall",
  "ARRAN Mathew": "arran-mathew",
  "ARRAND Ellen": "arrand-ellen",
  "ARREOLA Daniel": "arreola-daniel",
  "ARRICK Larry": "arrick-larry",
  "ARRIGHI Mel": "arrighi-mel",
  "ARRINGTON Don": "arrington-don",
  "ARRINGTON James": "arrington-james",
  "ARRINGTON John": "arrington-john",
  "ARRIVEE Alan": "arrivee-alan",
  "ARRIVI Fransisco": "arrivi-fransisco",
  "ARROWSMITH Beverly A": "arrowsmith-beverly-a",
  "ARROWSMITH William": "arrowsmith-william",
  "ARROYO Rane": "arroyo-rane",
  "ARSENAULT Cynthia Faith": "arsenault-cynthia-faith",
  "ARSENAULT Holly": "arsenault-holly",
  "ARSENEAUX Debbi": "arseneaux-debbi",
  "ARSHAD Sameer": "arshad-sameer",
  "ARSLANIAN Araxi": "arslanian-araxi",
  "ART HOUSE PRODUCTIONS ": "art-house-productions",
  "ARTAU Estrella": "artau-estrella",
  "ARTAUD Antonin": "artaud-antonin",
  "ARTHUR Alan": "arthur-alan",
  "ARTHUR Amy": "arthur-amy",
  "ARTHUR Andie": "arthur-andie",
  "ARTHUR Dave": "arthur-dave",
  "ARTHUR David": "arthur-david",
  "ARTHUR Dorne": "arthur-dorne",
  "ARTHUR Frank": "arthur-frank",
  "ARTHUR Robin": "arthur-robin",
  "ARTHUR Tabitha": "arthur-tabitha",
  "ARTHUR Tim": "arthur-tim",
  "ARTHUR Toni": "arthur-toni",
  "ARTICULATE ELBOW ": "articulate-elbow",
  "ARTIGUE Kevin": "artigue-kevin",
  "ARTISTE Cindy": "artiste-cindy",
  "ARUMBAKKAM Abhi": "arumbakkam-abhi",
  "ARUMEMI Victor": "arumemi-victor",
  "ARUNDEL Mark": "arundel-mark",
  "ARUNDEL Rex Howard": "arundel-rex-howard",
  "ARZEN Nic": "arzen-nic",
  "ARZOOMANIAN Ralph G": "arzoomanian-ralph-g",
  "ARZOUMANIAN Alexander": "arzoumanian-alexander",
  "ARZT Thomas": "arzt-thomas",
  "ASADOUR Zabel": "asadour-zabel",
  "ASAF George": "asaf-george",
  "ASARE Masi": "asare-masi",
  "ASARE-BEDIAKO Barbara K": "asare-bediako-barbara-k",
  "ASARO Tony": "asaro-tony",
  "ASBURY Peny": "asbury-peny",
  "ASCH Naomi": "asch-naomi",
  "ASCH Sholom": "asch-sholom",
  "ASCHER Kenny": "ascher-kenny",
  "ASCHOFF Maureen Jane": "aschoff-maureen-jane",
  "ASENSIO Ana": "asensio-ana",
  "ASERMELY Albert": "asermely-albert",
  "ASGARALI F N": "asgarali-f-n",
  "ASGOLD S": "asgold-s",
  "ASH Kathryn": "ash-kathryn",
  "ASH Kevin L": "ash-kevin-l",
  "ASH Margi-Brown": "ash-margi-brown",
  "ASHANTI Kahlil": "ashanti-kahlil",
  "ASHBERY John": "ashbery-john",
  "ASHBROOK Taylor": "ashbrook-taylor",
  "ASHBY James Sandlin": "ashby-james-sandlin",
  "ASHBY Sue": "ashby-sue",
  "ASHBY Sylvia": "ashby-sylvia",
  "ASHBY William Mobile": "ashby-william-mobile",
  "ASHBY-ROCK Jonathan": "ashby-rock-jonathan",
  "ASHCROFT Ceri": "ashcroft-ceri",
  "ASHCROFT Cloam": "ashcroft-cloam",
  "ASHCROFT Jefny": "ashcroft-jefny",
  "ASHCROFT Mike": "ashcroft-mike",
  "ASHDOWN Catharine": "ashdown-catharine",
  "ASHDOWN Niall": "ashdown-niall",
  "ASHDOWNE Olivia": "ashdowne-olivia",
  "ASHE Eugene": "ashe-eugene",
  "ASHE Keir": "ashe-keir",
  "ASHE Patrick": "ashe-patrick",
  "ASHEN Sophia": "ashen-sophia",
  "ASHER A B": "asher-a-b",
  "ASHER Cynthia Weiss": "asher-cynthia-weiss",
  "ASHER David": "asher-david",
  "ASHER Ron": "asher-ron",
  "ASHER Sandra Fenichel": "asher-sandra-fenichel",
  "ASHFORD David": "ashford-david",
  "ASHFORD John": "ashford-john",
  "ASHIZAWA Izumi": "ashizawa-izumi",
  "ASHKENASI Danny": "ashkenasi-danny",
  "ASHLEY Bob": "ashley-bob",
  "ASHLEY Christopher": "ashley-christopher",
  "ASHLEY Franklin": "ashley-franklin",
  "ASHLEY Jonathan": "ashley-jonathan",
  "ASHLEY Richard": "ashley-richard",
  "ASHLEY Trevor": "ashley-trevor",
  "ASHLEY William": "ashley-william",
  "ASHMAN Daniel": "ashman-daniel",
  "ASHMAN Howard": "ashman-howard",
  "ASHMORE Basil": "ashmore-basil",
  "ASHMORE Olly": "ashmore-olly",
  "ASHMORE Peter": "ashmore-peter",
  "ASHPITEL Ian": "ashpitel-ian",
  "ASHRAF Shazia": "ashraf-shazia",
  "ASHTON Barney": "ashton-barney",
  "ASHTON David": "ashton-david",
  "ASHTON E Bruce": "ashton-e-bruce",
  "ASHTON Emily": "ashton-emily",
  "ASHTON John": "ashton-john",
  "ASHTON Leandra": "ashton-leandra",
  "ASHTON Louisa": "ashton-louisa",
  "ASHTON Lysander": "ashton-lysander",
  "ASHTON Michael": "ashton-michael",
  "ASHTON Michael (1)": "ashton-michael-1",
  "ASHTON Michelle": "ashton-michelle",
  "ASHTON Nik": "ashton-nik",
  "ASHTON Penny": "ashton-penny",
  "ASHTON Wayne": "ashton-wayne",
  "ASHTON William": "ashton-william",
  "ASHTON Zawe": "ashton-zawe",
  "ASHWANDER Donald": "ashwander-donald",
  "ASHWELL Charlie": "ashwell-charlie",
  "ASHWORTH Arthur": "ashworth-arthur",
  "ASHWORTH Dan": "ashworth-dan",
  "AS-IF PRODUCTIONS ": "as-if-productions",
  "ASIIMWE Deborah": "asiimwe-deborah",
  "ASIKA Nkemba": "asika-nkemba",
  "ASIMOW Dyanne": "asimow-dyanne",
  "ASIS Stan": "asis-stan",
  "ASISTO Lesley": "asisto-lesley",
  "ASIYAMA Yaw": "asiyama-yaw",
  "ASIYANBI Bode": "asiyanbi-bode",
  "ASJES Alexa": "asjes-alexa",
  "ASKARI Brent": "askari-brent",
  "ASKEW Benjamin": "askew-benjamin",
  "ASKEW Maria": "askew-maria",
  "ASKHU Shepsu": "askhu-shepsu",
  "ASKIN Patrick": "askin-patrick",
  "ASKINS Rob": "askins-rob",
  "ASKINS Robert": "askins-robert",
  "ASLAN-LEVY Eylon": "aslan-levy-eylon",
  "ASMAR Tamara": "asmar-tamara",
  "ASMUNDSSON Doris R": "asmundsson-doris-r",
  "ASMUS James": "asmus-james",
  "ASMUSSEN Peter": "asmussen-peter",
  "ASPENGREN Kate": "aspengren-kate",
  "ASPINALL Mark": "aspinall-mark",
  "ASPINALL Steve": "aspinall-steve",
  "ASPINALL Tim": "aspinall-tim",
  "ASPLIN Henry": "asplin-henry",
  "ASRIEL Benjamin": "asriel-benjamin",
  "ASSAF Andrea": "assaf-andrea",
  "ASSANTE G A": "assante-g-a",
  "ASSANTE Isabelle": "assante-isabelle",
  "ASSEFA Yonas": "assefa-yonas",
  "ASSELIN Sara Jeanne": "asselin-sara-jeanne",
  "ASSELSTINE Robert": "asselstine-robert",
  "ASSEMBLY THEATRE PROJECT ": "assembly-theatre-project",
  "ASSENG Protais": "asseng-protais",
  "ASSINDER James": "assinder-james",
  "ASSINDER Peter": "assinder-peter",
  "ASSIS Luis": "assis-luis",
  "ASTBURY Tamsin": "astbury-tamsin",
  "ASTLE David": "astle-david",
  "ASTLE Robert": "astle-robert",
  "ASTLEY Tim": "astley-tim",
  "ASTON Manuel": "aston-manuel",
  "ASTON Mark": "aston-mark",
  "ASTON Matt": "aston-matt",
  "ASTON Nell": "aston-nell",
  "ASTORINO Amedeo": "astorino-amedeo",
  "ASTRACHAN Margot W": "astrachan-margot-w",
  "ASTRAL PLAYERS ": "astral-players",
  "ATABAI Kamyar": "atabai-kamyar",
  "ATACK Timothy X": "atack-timothy-x",
  "ATAIE Iraj Jannatie": "ataie-iraj-jannatie",
  "ATALLAH Mataz": "atallah-mataz",
  "ATCHESON Katie": "atcheson-katie",
  "ATEBE Camille": "atebe-camille",
  "ATENASIO Lisa": "atenasio-lisa",
  "ATERMAN Peter": "aterman-peter",
  "ATFIELD David": "atfield-david",
  "ATHAS-VAZQUEZ Geraldine": "athas-vazquez-geraldine",
  "ATHAYDE Roberto": "athayde-roberto",
  "ATHERDEN Geoffrey": "atherden-geoffrey",
  "ATHERTON Julie": "atherton-julie",
  "ATHEY Ron": "athey-ron",
  "ATIK Chiara": "atik-chiara",
  "ATIK Jeffery": "atik-jeffery",
  "ATIM Sheila": "atim-sheila",
  "ATKEY Mel": "atkey-mel",
  "ATKIN Barbara B": "atkin-barbara-b",
  "ATKIN Flora B": "atkin-flora-b",
  "ATKIN Louis": "atkin-louis",
  "ATKIN Mark": "atkin-mark",
  "ATKIN Pete": "atkin-pete",
  "ATKINS Alan": "atkins-alan",
  "ATKINS Damien": "atkins-damien",
  "ATKINS David": "atkins-david",
  "ATKINS Eileen": "atkins-eileen",
  "ATKINS Greg": "atkins-greg",
  "ATKINS John": "atkins-john",
  "ATKINS Nick": "atkins-nick",
  "ATKINS R J": "atkins-r-j",
  "ATKINS Richard": "atkins-richard",
  "ATKINS Russell": "atkins-russell",
  "ATKINS Sharif": "atkins-sharif",
  "ATKINS Stuart": "atkins-stuart",
  "ATKINSON Clinton J": "atkinson-clinton-j",
  "ATKINSON Crichton": "atkinson-crichton",
  "ATKINSON Dan": "atkinson-dan",
  "ATKINSON Dennis": "atkinson-dennis",
  "ATKINSON Dianne": "atkinson-dianne",
  "ATKINSON Harry": "atkinson-harry",
  "ATKINSON James": "atkinson-james",
  "ATKINSON James B": "atkinson-james-b",
  "ATKINSON Jason": "atkinson-jason",
  "ATKINSON Josh": "atkinson-josh",
  "ATKINSON Kate": "atkinson-kate",
  "ATKINSON Lawrence": "atkinson-lawrence",
  "ATKINSON Rebecca": "atkinson-rebecca",
  "ATKINSON Richard": "atkinson-richard",
  "ATKINSON Rowan": "atkinson-rowan",
  "ATKINSON Thomas M": "atkinson-thomas-m",
  "ATKINSON Tobin": "atkinson-tobin",
  "ATKINSON-LORD Rebecca": "atkinson-lord-rebecca",
  "ATLAKSON Philip": "atlakson-philip",
  "ATLAN Liliane": "atlan-liliane",
  "ATLAS Larry": "atlas-larry",
  "ATLAS GROUP ": "atlas-group",
  "ATRESBANDES ": "atresbandes",
  "ATTA Dean": "atta-dean",
  "ATTANAS John": "attanas-john",
  "ATTANASIE JR Steven": "attanasie-jr-steven",
  "ATTAR Farid Uddin": "attar-farid-uddin",
  "ATTAR Geula": "attar-geula",
  "ATTAR Shai Ben": "attar-shai-ben",
  "ATTAR Victor": "attar-victor",
  "ATTARD Tony": "attard-tony",
  "ATTAWAY Forrest": "attaway-forrest",
  "ATTEA Tom": "attea-tom",
  "ATTENWEILER Robert": "attenweiler-robert",
  "ATTERIDGE Harold": "atteridge-harold",
  "ATTIAS Daphna": "attias-daphna",
  "ATTIAS Erik": "attias-erik",
  "ATTINELLO Paul": "attinello-paul",
  "ATTIPOE Setor": "attipoe-setor",
  "ATTLEE Richard": "attlee-richard",
  "ATTRIDGE Steve": "attridge-steve",
  "ATTWOOD Alban": "attwood-alban",
  "ATTWOOD Thomas": "attwood-thomas",
  "ATUONA Diana Nneka": "atuona-diana-nneka",
  "ATWAL Sharanpreet Kaur": "atwal-sharanpreet-kaur",
  "ATWELL Gerry": "atwell-gerry",
  "ATWELL Sam": "atwell-sam",
  "ATWOOD Margaret": "atwood-margaret",
  "AUBIN Marc": "aubin-marc",
  "AUBREY Daniel": "aubrey-daniel",
  "AUBREY LC": "aubrey-lc",
  "AUBREY Stephen": "aubrey-stephen",
  "AUBURN David": "auburn-david",
  "AUDEN Scott": "auden-scott",
  "AUDEN W H": "auden-w-h",
  "AUDERGON Arlene": "audergon-arlene",
  "AUDIBERTI Jacques": "audiberti-jacques",
  "AUDIENCE, THE ": "audience",
  "AUDINI Lawrence": "audini-lawrence",
  "AUDLEY Elizabeth": "audley-elizabeth",
  "AUDLEY Matthew": "audley-matthew",
  "AUDLEY Natalie": "audley-natalie",
  "AUER Art": "auer-art",
  "AUER Nathan": "auer-nathan",
  "AUERBACH Arnold": "auerbach-arnold",
  "AUERBACH Kimberlee": "auerbach-kimberlee",
  "AUFRAY Gilles": "aufray-gilles",
  "AUGELLO Christina": "augello-christina",
  "AUGER Micheline": "auger-micheline",
  "AUGHEY Phil": "aughey-phil",
  "AUGIER Emile": "augier-emile",
  "AUGUST Ian": "august-ian",
  "AUGUST John": "august-john",
  "AUGUST June": "august-june",
  "AUGUST Kate": "august-kate",
  "AUGUSTANUS Xystus Betuluis": "augustanus-xystus-betuluis",
  "AUGUSTAS Isabela": "augustas-isabela",
  "AUGUSTAVE Hans": "augustave-hans",
  "AUGUSTIN Bill": "augustin-bill",
  "AUGUSTIN Jeff": "augustin-jeff",
  "AUGUSTIN William": "augustin-william",
  "AUGUSTINE John": "augustine-john",
  "AUGUSTINE Kevin": "augustine-kevin",
  "AUGUSTSON Scot": "augustson-scot",
  "AUKIN Liane": "aukin-liane",
  "AULA David": "aula-david",
  "AULD Eric K": "auld-eric-k",
  "AULETTA Robert": "auletta-robert",
  "AULICINO Armand": "aulicino-armand",
  "AULOV Vladimir": "aulov-vladimir",
  "AULTMAN Peggy": "aultman-peggy",
  "AUMILLER Tim": "aumiller-tim",
  "AUMUA Danny": "aumua-danny",
  "AUNAN Oda": "aunan-oda",
  "AURANSIA ": "auransia",
  "AURELIA THIERREE ": "aurelia-thierree",
  "AURELIUS Neville": "aurelius-neville",
  "AURERUS Leon": "aurerus-leon",
  "AURICOSTE Marianne": "auricoste-marianne",
  "AURORE Amontaine": "aurore-amontaine",
  "AURTHUR Robert Alan": "aurthur-robert-alan",
  "AUSBURN Garrison": "ausburn-garrison",
  "AUSLANDER Jordan": "auslander-jordan",
  "AUSTEN Alex": "austen-alex",
  "AUSTEN Alice": "austen-alice",
  "AUSTEN Leslie": "austen-leslie",
  "AUSTEN-PETERS Bolanle": "austen-peters-bolanle",
  "AUSTER Paul": "auster-paul",
  "AUSTER-ROSEN Megan": "auster-rosen-megan",
  "AUSTIN Alan": "austin-alan",
  "AUSTIN Alex": "austin-alex",
  "AUSTIN Brian": "austin-brian",
  "AUSTIN Daniel": "austin-daniel",
  "AUSTIN David": "austin-david",
  "AUSTIN Edward": "austin-edward",
  "AUSTIN Erin": "austin-erin",
  "AUSTIN Harry": "austin-harry",
  "AUSTIN Ian": "austin-ian",
  "AUSTIN Johnny": "austin-johnny",
  "AUSTIN Leslie": "austin-leslie",
  "AUSTIN Murray": "austin-murray",
  "AUSTIN Nigel": "austin-nigel",
  "AUSTIN Peter": "austin-peter",
  "AUSTIN Richard": "austin-richard",
  "AUSTIN Robert": "austin-robert",
  "AUSTRALIAN PERFORMING GROUP ": "australian-performing-group",
  "AUSUBEL Bobbi": "ausubel-bobbi",
  "AUTIER Paul": "autier-paul",
  "AVANT Lee": "avant-lee",
  "AVDI Anitgone": "avdi-anitgone",
  "AVELLA Frank J": "avella-frank-j",
  "AVELLA Mike": "avella-mike",
  "AVELONE Jesica": "avelone-jesica",
  "AVERIL Jerry": "averil-jerry",
  "AVERILL Jeanne": "averill-jeanne",
  "AVERILL Ric": "averill-ric",
  "AVERILL Will": "averill-will",
  "AVERILL-SNELL Ned": "averill-snell-ned",
  "AVERITT Dan": "averitt-dan",
  "AVERITT Suzan": "averitt-suzan",
  "AVERY Alan": "avery-alan",
  "AVERY Caryl S": "avery-caryl-s",
  "AVERY Eric F": "avery-eric-f",
  "AVERY H P": "avery-h-p",
  "AVERY Jacqueline": "avery-jacqueline",
  "AVERY John": "avery-john",
  "AVERY Juliana": "avery-juliana",
  "AVERY Lucy": "avery-lucy",
  "AVERY Mack": "avery-mack",
  "AVERY Matt": "avery-matt",
  "AVERY Peter": "avery-peter",
  "AVERY Stephen": "avery-stephen",
  "AVERY Wyckham": "avery-wyckham",
  "AVERY-CLARK Kenneth": "avery-clark-kenneth",
  "AVI ": "avi",
  "AVIDON Mallery": "avidon-mallery",
  "AVIDON Nelson": "avidon-nelson",
  "AVILA Elaine": "avila-elaine",
  "AVILA Juliette": "avila-juliette",
  "AVILA Tencha": "avila-tencha",
  "AVIS Meiret": "avis-meiret",
  "AVITAL Samuel": "avital-samuel",
  "AVNER Allan": "avner-allan",
  "AVNER Jon": "avner-jon",
  "AWAN Helen": "awan-helen",
  "AWDE Nick": "awde-nick",
  "AWEUSI Ali": "aweusi-ali",
  "AWKWARD ARTS ": "awkward-arts",
  "AWKWARD CITY ": "awkward-city",
  "AXELROD David": "axelrod-david",
  "AXELROD George": "axelrod-george",
  "AXELROD Laura": "axelrod-laura",
  "AXIS MIME THEATRE ": "axis-mime-theatre",
  "AXIS THEATRE COMPANY ": "axis-theatre-company",
  "AXLER Rachel": "axler-rachel",
  "AXLEROD David": "axlerod-david",
  "AXSTER Lilly": "axster-lilly",
  "AYACHE Makram": "ayache-makram",
  "AYALA Corina Katt": "ayala-corina-katt",
  "AYANOGLU Byron": "ayanoglu-byron",
  "AYBAR Trudy": "aybar-trudy",
  "AYCKBOURN Alan": "ayckbourn-alan",
  "AYCKBOURN Philip": "ayckbourn-philip",
  "AYCOCK Roger D": "aycock-roger-d",
  "AYERS Astrid": "ayers-astrid",
  "AYERS David H": "ayers-david-h",
  "AYERS Greg": "ayers-greg",
  "AYERS Marni": "ayers-marni",
  "AYERS Michael": "ayers-michael",
  "AYERS Shan R": "ayers-shan-r",
  "AYERS Trish": "ayers-trish",
  "AYERS Vivian": "ayers-vivian",
  "AYKROYD Juliet": "aykroyd-juliet",
  "AYLEN Leo": "aylen-leo",
  "AYLIN Simon": "aylin-simon",
  "AYLING Simon": "ayling-simon",
  "AYLOR Anne": "aylor-anne",
  "AYLWEN Ingraa": "aylwen-ingraa",
  "AYMAR Angels": "aymar-angels",
  "AYME Marcel": "ayme-marcel",
  "AYMER Geoff": "aymer-geoff",
  "AYMIE Alan": "aymie-alan",
  "AYOADE Richard": "ayoade-richard",
  "AYODEJI Julius": "ayodeji-julius",
  "AYRE Paul": "ayre-paul",
  "AYRES Tony": "ayres-tony",
  "AYRES Trish": "ayres-trish",
  "AYRES-FREDERICK Linda": "ayres-frederick-linda",
  "AYUB Zaf": "ayub-zaf",
  "AYVAS Emanuel": "ayvas-emanuel",
  "AYVAZIAN Leslie": "ayvazian-leslie",
  "AZAMA Michel": "azama-michel",
  "AZAR Raja": "azar-raja",
  "AZA-SELINGER George": "aza-selinger-george",
  "AZAZ Orit": "azaz-orit",
  "AZEVEDO Adrian": "azevedo-adrian",
  "AZEVEDO Marcos": "azevedo-marcos",
  "AZIMI Mohsen": "azimi-mohsen",
  "AZIZ Aya": "aziz-aya",
  "AZOUZ Josh": "azouz-josh",
  "AZRIEL Ilan": "azriel-ilan",
  "AZULAY-HASFARI Hana": "azulay-hasfari-hana",
  "AZURDIA Ivonne": "azurdia-ivonne",
  "AZZOUGA Saleem": "azzouga-saleem",
};
