export default {
  "F Rachael": "f-rachael",
  "FAAUGA-RENWICK Jacob": "faauga-renwick-jacob",
  "FABAL J Sebastian": "fabal-j-sebastian",
  "FABBRI Diego": "fabbri-diego",
  "FABER Max": "faber-max",
  "FABIAN Kevin": "fabian-kevin",
  "FABILLI Sophia": "fabilli-sophia",
  "FABIO Sarah Webster": "fabio-sarah-webster",
  "FABISCH Sue": "fabisch-sue",
  "FABRE Jan": "fabre-jan",
  "FABRY Andrew M": "fabry-andrew-m",
  "FABRY Joseph": "fabry-joseph",
  "FACCHINI Nullo": "facchini-nullo",
  "FACCINI Edmond": "faccini-edmond",
  "FACEY Mabel": "facey-mabel",
  "FACHMAN Valerie": "fachman-valerie",
  "FACOS James": "facos-james",
  "FADNER Jonathan James": "fadner-jonathan-james",
  "FAE Erica": "fae-erica",
  "FAFOUTAKIS Andrew": "fafoutakis-andrew",
  "FAGAN Alfred": "fagan-alfred",
  "FAGAN Bill": "fagan-bill",
  "FAGAN J B": "fagan-j-b",
  "FAGAN Kip": "fagan-kip",
  "FAGAN Patsy": "fagan-patsy",
  "FAGAN Stephanie": "fagan-stephanie",
  "FAGAN Stephen": "fagan-stephen",
  "FAGAN Valerie": "fagan-valerie",
  "FAGEN Graham": "fagen-graham",
  "FAGEN Richard": "fagen-richard",
  "FAGERSTROM Lena": "fagerstrom-lena",
  "FAGGETTER Robert": "faggetter-robert",
  "FAGIH Ahmed": "fagih-ahmed",
  "FAGLES Robert": "fagles-robert",
  "FAGON Alfred": "fagon-alfred",
  "FAHEY Lee Anne": "fahey-lee-anne",
  "FAHLSING Kate Tucker": "fahlsing-kate-tucker",
  "FAHN Jennie": "fahn-jennie",
  "FAHRINGER Barbara": "fahringer-barbara",
  "FAIGAO-HALL Linda": "faigao-hall-linda",
  "FAIL Seamus": "fail-seamus",
  "FAIL BETTER PRODUCTIONS ": "fail-better-productions",
  "FAINANU Dana": "fainanu-dana",
  "FAIR Marguerite": "fair-marguerite",
  "FAIR Ronald L": "fair-ronald-l",
  "FAIRBAIRN Michelle": "fairbairn-michelle",
  "FAIRBANKS Tasha": "fairbanks-tasha",
  "FAIRBROTHER William": "fairbrother-william",
  "FAIRCHILD William": "fairchild-william",
  "FAIRCLOUGH Jarrod": "fairclough-jarrod",
  "FAIRCLOUGH Steve": "fairclough-steve",
  "FAIRCLOUGH Troy Andrew": "fairclough-troy-andrew",
  "FAIREY Ellen": "fairey-ellen",
  "FAIRFIELD Joy Brooke": "fairfield-joy-brooke",
  "FAIRFOOT Tom": "fairfoot-tom",
  "FAIRLEY Barker": "fairley-barker",
  "FAIRLEY Brooke": "fairley-brooke",
  "FAIRLEY Drew": "fairley-drew",
  "FAIRLEY Ian": "fairley-ian",
  "FAIRLEY Juliette": "fairley-juliette",
  "FAIRLIGHT Ruth": "fairlight-ruth",
  "FAIRS Nigel": "fairs-nigel",
  "FAIRWEATHER Eileen": "fairweather-eileen",
  "FAISON George": "faison-george",
  "FAIT ACCOMPLI ": "fait-accompli",
  "FAITH Chris Fredrick": "faith-chris-fredrick",
  "FAITH Christopher": "faith-christopher",
  "FAITH Penny": "faith-penny",
  "FAITH Rhiannon": "faith-rhiannon",
  "FAITHFUL Richard": "faithful-richard",
  "FAKINOU Eugenia": "fakinou-eugenia",
  "FAKU Dorcas": "faku-dorcas",
  "FALAGAN Ted": "falagan-ted",
  "FALAR Hans": "falar-hans",
  "FALBERG Alex": "falberg-alex",
  "FALCO Raphael": "falco-raphael",
  "FALCON Lidia": "falcon-lidia",
  "FALCONE Beth": "falcone-beth",
  "FALCONER Joyce": "falconer-joyce",
  "FALEN James E": "falen-james-e",
  "FALES Nancy": "fales-nancy",
  "FALES Steven": "fales-steven",
  "FALETTO Jennifer": "faletto-jennifer",
  "FALETTO Rick": "faletto-rick",
  "FALIK Jennifer": "falik-jennifer",
  "FALION Jane": "falion-jane",
  "FALK Daniel": "falk-daniel",
  "FALK Eden": "falk-eden",
  "FALK Lee": "falk-lee",
  "FALKENBERG Peter": "falkenberg-peter",
  "FALL Christine": "fall-christine",
  "FALL Jef": "fall-jef",
  "FALL Nadia": "fall-nadia",
  "FALLA Jonathan": "falla-jonathan",
  "FALLADA Hans": "fallada-hans",
  "FALLEN Eric": "fallen-eric",
  "FALLERI Daniele": "falleri-daniele",
  "FALLICO Jessica": "fallico-jessica",
  "FALLIS Paden": "fallis-paden",
  "FALLON Courtney Frances": "fallon-courtney-frances",
  "FALLON Judy": "fallon-judy",
  "FALLON Kathleen Mary": "fallon-kathleen-mary",
  "FALLS Gregory A": "falls-gregory-a",
  "FALLS Jean Burch": "falls-jean-burch",
  "FALLS Jonathan": "falls-jonathan",
  "FALLS Robert": "falls-robert",
  "FALLSTEIN Bruce": "fallstein-bruce",
  "FALSTIE-JENSEN Anders": "falstie-jensen-anders",
  "FALVEY Erin": "falvey-erin",
  "FALZONE Jay": "falzone-jay",
  "FALZONE Paul": "falzone-paul",
  "FAM Bernadette": "fam-bernadette",
  "FAMILIE FLOZ ": "familie-floz",
  "FANALE Arlene Brent": "fanale-arlene-brent",
  "FANAN Den Svarta": "fanan-den-svarta",
  "FANCONI Dendra": "fanconi-dendra",
  "FANCONI Kendra": "fanconi-kendra",
  "FANCY Colin": "fancy-colin",
  "FANCY David": "fancy-david",
  "FANE Dave": "fane-dave",
  "FANELLI Michael": "fanelli-michael",
  "FANG Maggie": "fang-maggie",
  "FANG Wan": "fang-wan",
  "FANIZZI Christina": "fanizzi-christina",
  "FANN Al": "fann-al",
  "FANN Ernie": "fann-ernie",
  "FANNIN Hilary": "fannin-hilary",
  "FANNING Arnold Thomas": "fanning-arnold-thomas",
  "FANNING Peter": "fanning-peter",
  "FANNING Rio": "fanning-rio",
  "FANNON Timothy": "fannon-timothy",
  "FANSHAWE Simon": "fanshawe-simon",
  "FANTASIA Louis": "fantasia-louis",
  "FANTE Dan": "fante-dan",
  "FANTETTI Eufemia": "fantetti-eufemia",
  "FANTONI Barry": "fantoni-barry",
  "FARA Cynthia": "fara-cynthia",
  "FARABOUGH Laura": "farabough-laura",
  "FARADAY Sally": "faraday-sally",
  "FARAG Alfred": "farag-alfred",
  "FARAJIN Imad": "farajin-imad",
  "FARBER Evan": "farber-evan",
  "FARBER Gregory L": "farber-gregory-l",
  "FARBER Phoebe": "farber-phoebe",
  "FARBER Richard": "farber-richard",
  "FARBER Yael": "farber-yael",
  "FARBIARZ Elan Wolf": "farbiarz-elan-wolf",
  "FARBITNIK Igor": "farbitnik-igor",
  "FARBMAN Michele": "farbman-michele",
  "FARBMAN Rhea": "farbman-rhea",
  "FARCAS Stephanie Barton": "farcas-stephanie-barton",
  "FARDON Joshua": "fardon-joshua",
  "FARESS Souad": "faress-souad",
  "FARFAN Anna Patricia": "farfan-anna-patricia",
  "FARGAS Cristina": "fargas-cristina",
  "FARGHER Catherine": "fargher-catherine",
  "FARGNOLI Dave": "fargnoli-dave",
  "FARGOTSTEIN Narda L": "fargotstein-narda-l",
  "FARHI M Moris": "farhi-m-moris",
  "FARHOUD Abla": "farhoud-abla",
  "FARIA Stephen": "faria-stephen",
  "FARIAS Joann": "farias-joann",
  "FARIC Matjaz": "faric-matjaz",
  "FARINA Alison": "farina-alison",
  "FARIS Alexander": "faris-alexander",
  "FARISH Brian": "farish-brian",
  "FARJEON Eleanor": "farjeon-eleanor",
  "FARJEON Herbert": "farjeon-herbert",
  "FARKAS Endre": "farkas-endre",
  "FARKAS Karl": "farkas-karl",
  "FARLEY Alice": "farley-alice",
  "FARLEY Ashe": "farley-ashe",
  "FARLEY Keythe": "farley-keythe",
  "FARLEY Leo": "farley-leo",
  "FARLEY Richard": "farley-richard",
  "FARMER Andrew": "farmer-andrew",
  "FARMER Bonnie": "farmer-bonnie",
  "FARMER Buddy": "farmer-buddy",
  "FARMER Caroline": "farmer-caroline",
  "FARMER David": "farmer-david",
  "FARMER Frank": "farmer-frank",
  "FARMER Jennifer": "farmer-jennifer",
  "FARMER Jim": "farmer-jim",
  "FARMER Jonathan": "farmer-jonathan",
  "FARMER Lonnie": "farmer-lonnie",
  "FARMER Orran": "farmer-orran",
  "FARMERY Jan": "farmery-jan",
  "FARMILOE Dorothy": "farmiloe-dorothy",
  "FARNABY Simon": "farnaby-simon",
  "FARNAN Keith": "farnan-keith",
  "FARNDON John": "farndon-john",
  "FARNELL Ian": "farnell-ian",
  "FARNELL-WILSON Stephenie": "farnell-wilson-stephenie",
  "FARNEN Mark": "farnen-mark",
  "FARNSWORTH David": "farnsworth-david",
  "FARO Arline": "faro-arline",
  "FARO PRODUCTIONS ": "faro-productions",
  "FAROOQI Sahill": "farooqi-sahill",
  "FARQUHAR Angus": "farquhar-angus",
  "FARQUHAR George": "farquhar-george",
  "FARQUHAR Robert": "farquhar-robert",
  "FARQUHAR Simon": "farquhar-simon",
  "FARQUHAR-SMITH Ann": "farquhar-smith-ann",
  "FARR David": "farr-david",
  "FARR Gareth": "farr-gareth",
  "FARR Gareth (1)": "farr-gareth-1",
  "FARR Gordon": "farr-gordon",
  "FARR Jeanette D": "farr-jeanette-d",
  "FARR Jessica": "farr-jessica",
  "FARR Ju Row": "farr-ju-row",
  "FARR Maria Jansdotter": "farr-maria-jansdotter",
  "FARRAR Anne": "farrar-anne",
  "FARRAR Paxton": "farrar-paxton",
  "FARRAR Peter": "farrar-peter",
  "FARRAR Robert": "farrar-robert",
  "FARRELL Andy": "farrell-andy",
  "FARRELL Bernard": "farrell-bernard",
  "FARRELL Christine": "farrell-christine",
  "FARRELL Collette": "farrell-collette",
  "FARRELL Connor": "farrell-connor",
  "FARRELL David": "farrell-david",
  "FARRELL Eamonn": "farrell-eamonn",
  "FARRELL Fiona": "farrell-fiona",
  "FARRELL G E": "farrell-g-e",
  "FARRELL Gordon": "farrell-gordon",
  "FARRELL Helena C": "farrell-helena-c",
  "FARRELL Henry": "farrell-henry",
  "FARRELL Herman Daniel": "farrell-herman-daniel",
  "FARRELL James": "farrell-james",
  "FARRELL Joe": "farrell-joe",
  "FARRELL Lynne Topping": "farrell-lynne-topping",
  "FARRELL M J": "farrell-m-j",
  "FARRELL Sharon": "farrell-sharon",
  "FARRELL Susan": "farrell-susan",
  "FARRELL Tom": "farrell-tom",
  "FARRELL Will": "farrell-will",
  "FARRELL Windy Barnes": "farrell-windy-barnes",
  "FARRELL III Herman Daniel": "farrell-iii-herman-daniel",
  "FARRELLY Dan": "farrelly-dan",
  "FARRELLY Daniel J": "farrelly-daniel-j",
  "FARRELLY David": "farrelly-david",
  "FARRELLY Mark": "farrelly-mark",
  "FARRER John": "farrer-john",
  "FARRIER Jean": "farrier-jean",
  "FARRINGTON Connor": "farrington-connor",
  "FARRINGTON Reid": "farrington-reid",
  "FARRINGTON Sara": "farrington-sara",
  "FARRIS Elizabeth L": "farris-elizabeth-l",
  "FARRIS John": "farris-john",
  "FARRON-DIAMANTIS Lucia": "farron-diamantis-lucia",
  "FARROW Angie": "farrow-angie",
  "FARROW Graham": "farrow-graham",
  "FARROW Lawrence G": "farrow-lawrence-g",
  "FARROW Toby": "farrow-toby",
  "FARRUGGIA Cristina": "farruggia-cristina",
  "FARRUGGIA Robert": "farruggia-robert",
  "FARSAD Negin": "farsad-negin",
  "FARSON Daniel": "farson-daniel",
  "FARTHING Ann": "farthing-ann",
  "FARTHING Anna": "farthing-anna",
  "FARUGIA Lena": "farugia-lena",
  "FARWELL George": "farwell-george",
  "FARWELL James": "farwell-james",
  "FARWELL Mario": "farwell-mario",
  "FARZAN Mahmood": "farzan-mahmood",
  "FASO Nina": "faso-nina",
  "FASSBINDER Rainer Werner": "fassbinder-rainer-werner",
  "FAST Howard": "fast-howard",
  "FAST Raymond Vincent": "fast-raymond-vincent",
  "FASTHORSE Larissa": "fasthorse-larissa",
  "FATIMA Aizzah": "fatima-aizzah",
  "FATONE Charles": "fatone-charles",
  "FAUCHER Michaela": "faucher-michaela",
  "FAUCHER Sophie": "faucher-sophie",
  "FAUDREE Nathan": "faudree-nathan",
  "FAUGHAN George": "faughan-george",
  "FAULDS Stephen": "faulds-stephen",
  "FAULER Bernd": "fauler-bernd",
  "FAULKNER Alistair": "faulkner-alistair",
  "FAULKNER Karey": "faulkner-karey",
  "FAULKNER Michael": "faulkner-michael",
  "FAULKNER Trader": "faulkner-trader",
  "FAULKS Ben": "faulks-ben",
  "FAULTLESS Judith": "faultless-judith",
  "FAULTY OPTIC THEATRE OF ANIMATION ": "faulty-optic-theatre-of-animation",
  "FAUNTLEROY Shaun Bennet": "fauntleroy-shaun-bennet",
  "FAUQUEZ A": "fauquez-a",
  "FAUSS M Michael": "fauss-m-michael",
  "FAUSS Michael": "fauss-michael",
  "FAUST Bud": "faust-bud",
  "FAUTE Ivan": "faute-ivan",
  "FAUVELL James": "fauvell-james",
  "FAUX David": "faux-david",
  "FAUX-REAL THEATRE COMPANY ": "faux-real-theatre-company",
  "FAVA Antonio": "fava-antonio",
  "FAVALE Vincent P": "favale-vincent-p",
  "FAWCETT Jennifer": "fawcett-jennifer",
  "FAY Daniel P": "fay-daniel-p",
  "FAY Doreen": "fay-doreen",
  "FAY John": "fay-john",
  "FAY Kieran": "fay-kieran",
  "FAY Mary Helen": "fay-mary-helen",
  "FAY Michael": "fay-michael",
  "FAYE Doris": "faye-doris",
  "FAYE Habib": "faye-habib",
  "FAYE COLLIE Brenda": "faye-collie-brenda",
  "FAYNE Justin": "fayne-justin",
  "FAZAKERLEY John Joseph": "fazakerley-john-joseph",
  "FAZAKERLEY Lucina": "fazakerley-lucina",
  "FAZAL Zehra": "fazal-zehra",
  "FAZIO Daryl Lisa": "fazio-daryl-lisa",
  "FEARLEY John": "fearley-john",
  "FEATHER Ollie": "feather-ollie",
  "FEATHERSTONE Karen": "featherstone-karen",
  "FEATHERSTONE Vicky": "featherstone-vicky",
  "FEAVER Kendall": "feaver-kendall",
  "FEBLES Ulises Rodriquez": "febles-ulises-rodriquez",
  "FEBRUARY Terri Atkins": "february-terri-atkins",
  "FECHO L J": "fecho-l-j",
  "FECHTER Steven": "fechter-steven",
  "FEDDER Norman J": "fedder-norman-j",
  "FEDER Miriam": "feder-miriam",
  "FEDER-BIRNBAUM Jessica": "feder-birnbaum-jessica",
  "FEDERGREEN Ian": "federgreen-ian",
  "FEDERMAN Wendy": "federman-wendy",
  "FEDO Stephen": "fedo-stephen",
  "FEDOR Alexis": "fedor-alexis",
  "FEDOR Jennifer": "fedor-jennifer",
  "FEDORKO Joseph": "fedorko-joseph",
  "FEDUNKIW M P": "fedunkiw-m-p",
  "FEDY Emelia Symington": "fedy-emelia-symington",
  "FEEHAN Brian": "feehan-brian",
  "FEEHAN Christiaan": "feehan-christiaan",
  "FEEHILY Stella": "feehily-stella",
  "FEELEY Mat": "feeley-mat",
  "FEELY Kara": "feely-kara",
  "FEELY M J": "feely-m-j",
  "FEELY Terence": "feely-terence",
  "FEENAN Declan": "feenan-declan",
  "FEENY-WILLIAMS Rachel": "feeny-williams-rachel",
  "FEERST Ethan": "feerst-ethan",
  "FEESER Roman": "feeser-roman",
  "FEFER Ety": "fefer-ety",
  "FEFFER John": "feffer-john",
  "FEFFER Steve": "feffer-steve",
  "FEGAN Kevin": "fegan-kevin",
  "FEHILY Rachel": "fehily-rachel",
  "FEI Faye": "fei-faye",
  "FEIBLEMAN Peter": "feibleman-peter",
  "FEIFFER Halley": "feiffer-halley",
  "FEIFFER Jules": "feiffer-jules",
  "FEIFFER Kate": "feiffer-kate",
  "FEIGEL Ethan": "feigel-ethan",
  "FEIGELES Neil": "feigeles-neil",
  "FEIGELSON Teri": "feigelson-teri",
  "FEILBERT Edward Allen": "feilbert-edward-allen",
  "FEIN Adam I": "fein-adam-i",
  "FEIN Elizabeth": "fein-elizabeth",
  "FEIN Judith": "fein-judith",
  "FEINBERG Annah": "feinberg-annah",
  "FEINBERG Paul": "feinberg-paul",
  "FEINDEL Janet": "feindel-janet",
  "FEINGOLD Michael": "feingold-michael",
  "FEININGER Kathy": "feininger-kathy",
  "FEINSOD Arthur": "feinsod-arthur",
  "FEINSTEIN Brian J": "feinstein-brian-j",
  "FEINSTEIN Elaine": "feinstein-elaine",
  "FEINSTEIN Joe": "feinstein-joe",
  "FEINSTEIN Michael": "feinstein-michael",
  "FEIRSTEIN Frederick": "feirstein-frederick",
  "FEIST Aubrey": "feist-aubrey",
  "FEIST Gene": "feist-gene",
  "FEITLOWITZ Marguerite": "feitlowitz-marguerite",
  "FEJERMAN Daniela": "fejerman-daniela",
  "FEKETE Gyorgy": "fekete-gyorgy",
  "FEKETE Vladislava": "fekete-vladislava",
  "FELBABOV Vladislava": "felbabov-vladislava",
  "FELBAIN Leslie": "felbain-leslie",
  "FELBERBAUM Sheila": "felberbaum-sheila",
  "FELD April": "feld-april",
  "FELD Bruce": "feld-bruce",
  "FELD Michael": "feld-michael",
  "FELDBERG Rachel": "feldberg-rachel",
  "FELDE Kitty": "felde-kitty",
  "FELDER Hershey": "felder-hershey",
  "FELDER Louis": "felder-louis",
  "FELDER Sara": "felder-sara",
  "FELDER Susan": "felder-susan",
  "FELDHAUS-WEBER M": "feldhaus-weber-m",
  "FELDMAN Adam Matthew": "feldman-adam-matthew",
  "FELDMAN Benjamin": "feldman-benjamin",
  "FELDMAN Brian": "feldman-brian",
  "FELDMAN Charles": "feldman-charles",
  "FELDMAN David": "feldman-david",
  "FELDMAN Emily": "feldman-emily",
  "FELDMAN J Michael": "feldman-j-michael",
  "FELDMAN Jack": "feldman-jack",
  "FELDMAN Jonathan": "feldman-jonathan",
  "FELDMAN Joshua": "feldman-joshua",
  "FELDMAN L M": "feldman-l-m",
  "FELDMAN Lauren": "feldman-lauren",
  "FELDMAN Marty": "feldman-marty",
  "FELDMAN Nina": "feldman-nina",
  "FELDMAN Rebecca": "feldman-rebecca",
  "FELDMAN Sharon G": "feldman-sharon-g",
  "FELDMAN Susan": "feldman-susan",
  "FELDSER Jennifer Louise": "feldser-jennifer-louise",
  "FELDSHUH David": "feldshuh-david",
  "FELDSHUH Tovah": "feldshuh-tovah",
  "FELDSTEIN Jack": "feldstein-jack",
  "FELFELI Shadaan": "felfeli-shadaan",
  "FELIPE Carlos": "felipe-carlos",
  "FELIX Alberto": "felix-alberto",
  "FELIX Jessica Rose": "felix-jessica-rose",
  "FELIX Morton": "felix-morton",
  "FELL Alison": "fell-alison",
  "FELL Blair": "fell-blair",
  "FELL Ian": "fell-ian",
  "FELL Paula": "fell-paula",
  "FELLER Wende": "feller-wende",
  "FELLERATH David": "fellerath-david",
  "FELLMETH Michael Quixote": "fellmeth-michael-quixote",
  "FELLOWES Julian": "fellowes-julian",
  "FELLOWES Rory": "fellowes-rory",
  "FELLOWS Amanda": "fellows-amanda",
  "FELLOWS M S": "fellows-m-s",
  "FELLOWS Megan": "fellows-megan",
  "FELMAN Jyl Lynn": "felman-jyl-lynn",
  "FELS Michael David": "fels-michael-david",
  "FELSHMAN Neil I": "felshman-neil-i",
  "FELSTEIN Robert": "felstein-robert",
  "FELT Marilyn": "felt-marilyn",
  "FELTON-DANSKY Miriam": "felton-dansky-miriam",
  "FEMIA Gina": "femia-gina",
  "FEN Elisaveta": "fen-elisaveta",
  "FENADY Andrew": "fenady-andrew",
  "FENBERT Abbey Stephenie": "fenbert-abbey-stephenie",
  "FENCE Normous": "fence-normous",
  "FENDELL Melissa": "fendell-melissa",
  "FENDRICH Karen": "fendrich-karen",
  "FENDRICH Shubert": "fendrich-shubert",
  "FENDRICH Steven": "fendrich-steven",
  "FENEMORE Anna": "fenemore-anna",
  "FENLASON Michael": "fenlason-michael",
  "FENLEY Molissa": "fenley-molissa",
  "FENLEY Susan": "fenley-susan",
  "FENN Charles": "fenn-charles",
  "FENN Cheryl": "fenn-cheryl",
  "FENN Erasmus": "fenn-erasmus",
  "FENN John": "fenn-john",
  "FENN Rick": "fenn-rick",
  "FENNAH Alan": "fennah-alan",
  "FENNAH Rob": "fennah-rob",
  "FENNARIO David": "fennario-david",
  "FENNELL Denise": "fennell-denise",
  "FENNELL Emerald ": "fennell-emerald",
  "FENNELLY David": "fennelly-david",
  "FENNELLY Parker W": "fennelly-parker-w",
  "FENNESSY Aidan": "fennessy-aidan",
  "FENSOME Ben": "fensome-ben",
  "FENSTER Susan": "fenster-susan",
  "FENTIMAN Alan": "fentiman-alan",
  "FENTIMAN Andy": "fentiman-andy",
  "FENTIMAN-HALL Sam": "fentiman-hall-sam",
  "FENTON Daniel": "fenton-daniel",
  "FENTON Emma": "fenton-emma",
  "FENTON James": "fenton-james",
  "FENTON Jamie": "fenton-jamie",
  "FENTON Norman": "fenton-norman",
  "FENTON Patrick": "fenton-patrick",
  "FENTON Peter": "fenton-peter",
  "FENTON Rachel": "fenton-rachel",
  "FENTRESS Liz Bussey": "fentress-liz-bussey",
  "FENTZ Kirsten Danielle": "fentz-kirsten-danielle",
  "FENWICK Jean-Noel": "fenwick-jean-noel",
  "FERAL Mitch": "feral-mitch",
  "FERBER Ben": "ferber-ben",
  "FERBER David": "ferber-david",
  "FERBER Edna": "ferber-edna",
  "FERBER Lisa": "ferber-lisa",
  "FERCEC Goran": "fercec-goran",
  "FERDENZI Kaitlin": "ferdenzi-kaitlin",
  "FERDINAND Val": "ferdinand-val",
  "FERDINANDO Flick": "ferdinando-flick",
  "FERDMAN Bertie": "ferdman-bertie",
  "FERDON John": "ferdon-john",
  "FEREBEE Lauren": "ferebee-lauren",
  "FEREDAY Jeffrey": "fereday-jeffrey",
  "FEREIRA Tyler": "fereira-tyler",
  "FERENBACH Joshua": "ferenbach-joshua",
  "FERENTINOS Vicki": "ferentinos-vicki",
  "FERGUSON Alex": "ferguson-alex",
  "FERGUSON Alexander": "ferguson-alexander",
  "FERGUSON Alexander Thomas": "ferguson-alexander-thomas",
  "FERGUSON Alistair": "ferguson-alistair",
  "FERGUSON Annie": "ferguson-annie",
  "FERGUSON Ben": "ferguson-ben",
  "FERGUSON Brian": "ferguson-brian",
  "FERGUSON Caroline": "ferguson-caroline",
  "FERGUSON Cath": "ferguson-cath",
  "FERGUSON Charles W": "ferguson-charles-w",
  "FERGUSON Dugald": "ferguson-dugald",
  "FERGUSON Eric": "ferguson-eric",
  "FERGUSON Graham": "ferguson-graham",
  "FERGUSON Ian": "ferguson-ian",
  "FERGUSON James C": "ferguson-james-c",
  "FERGUSON Jason Paul": "ferguson-jason-paul",
  "FERGUSON John": "ferguson-john",
  "FERGUSON Jon": "ferguson-jon",
  "FERGUSON Kate": "ferguson-kate",
  "FERGUSON Keith": "ferguson-keith",
  "FERGUSON Keith Craig": "ferguson-keith-craig",
  "FERGUSON Lou": "ferguson-lou",
  "FERGUSON Lynn": "ferguson-lynn",
  "FERGUSON Marcia": "ferguson-marcia",
  "FERGUSON Maria": "ferguson-maria",
  "FERGUSON Naomi": "ferguson-naomi",
  "FERGUSON Paul": "ferguson-paul",
  "FERGUSON Rich": "ferguson-rich",
  "FERGUSON Ron": "ferguson-ron",
  "FERGUSON Ronnie": "ferguson-ronnie",
  "FERGUSON Ryann": "ferguson-ryann",
  "FERGUSON Scott": "ferguson-scott",
  "FERGUSON Travis": "ferguson-travis",
  "FERGUSON Trevor": "ferguson-trevor",
  "FERGUSSON Aly": "fergusson-aly",
  "FERGUSSON Jean": "fergusson-jean",
  "FERGUSSON Melissa": "fergusson-melissa",
  "FERGUSSON Patsy": "fergusson-patsy",
  "FERLINGHETTI Lawrence": "ferlingetti-lawrence",
  "FERLINGHETTI Synder": "ferlinghetti-synder",
  "FERLITA Ernest": "ferlita-ernest",
  "FERM Shayana": "ferm-shayana",
  "FERMAN Kathleen": "ferman-kathleen",
  "FERME Tjasa": "ferme-tjasa",
  "FERN Barbara": "fern-barbara",
  "FERNALD Alvin": "fernald-alvin",
  "FERNALD Chester Bailey": "fernald-chester-bailey",
  "FERNALD John": "fernald-john",
  "FERNANDEZ Elaine Bernadette": "fernandez-elaine-bernadette",
  "FERNANDEZ Evelina": "fernandez-evelina",
  "FERNANDEZ George": "fernandez-george",
  "FERNANDEZ Jose": "fernandez-jose",
  "FERNANDEZ Jose Ramon": "fernandez-jose-ramon",
  "FERNANDEZ Lucio": "fernandez-lucio",
  "FERNANDEZ M Rosario": "fernandez-m-rosario",
  "FERNANDEZ Pablo Armando": "fernandez-pablo-armando",
  "FERNANDEZ SANCHEZ Esteban": "fernandez-sanchez-esteban",
  "FERNANDEZ-ACHE Maria": "fernandez-ache-maria",
  "FERNEBOK Zachary": "fernebok-zachary",
  "FERRADA Renaldo Eugenio": "ferrada-renaldo-eugenio",
  "FERRAND Judy": "ferrand-judy",
  "FERRANTE Bob Jude": "ferrante-bob-jude",
  "FERRAR Gary": "ferrar-gary",
  "FERRARA D": "ferrara-d",
  "FERRARA Susan": "ferrara-susan",
  "FERRARI Carlos": "ferrari-carlos",
  "FERRARI Jay": "ferrari-jay",
  "FERRARI Lilie": "ferrari-lilie",
  "FERRARI Marianne": "ferrari-marianne",
  "FERRARO Brandon": "ferraro-brandon",
  "FERRATO Yolanda": "ferrato-yolanda",
  "FERREE Scott": "ferree-scott",
  "FERREIRA Antonio": "ferreira-antonio",
  "FERREIRA Michelle": "ferreira-michelle",
  "FERRELL Andy": "ferrell-andy",
  "FERRELL Cynthia Lewis": "ferrell-cynthia-lewis",
  "FERRELL Michael": "ferrell-michael",
  "FERRELL Will": "ferrell-will",
  "FERRENTINO Lindsey": "ferrentino-lindsey",
  "FERRER Jose": "ferrer-jose",
  "FERRERAS Alberto": "ferreras-alberto",
  "FERREYRA Shawn": "ferreyra-shawn",
  "FERRI Rolando": "ferri-rolando",
  "FERRIER George S": "ferrier-george-s",
  "FERRIERRE J P": "ferrierre-j-p",
  "FERRIGNI Ken": "ferrigni-ken",
  "FERRIS Alexander": "ferris-alexander",
  "FERRIS Amy": "ferris-amy",
  "FERRIS Jessica": "ferris-jessica",
  "FERRIS Ken": "ferris-ken",
  "FERRIS Monk": "ferris-monk",
  "FERRIS Tim": "ferris-tim",
  "FERRIS Walter": "ferris-walter",
  "FERRO Lee": "ferro-lee",
  "FERRY David": "ferry-david",
  "FERRY Simon": "ferry-simon",
  "FERVER Jack": "ferver-jack",
  "FESENMEIER Michael": "fesenmeier-michael",
  "FESETTE Nick": "fesette-nick",
  "FESSER Roman": "fesser-roman",
  "FESSEY Tamsin": "fessey-tamsin",
  "FETHERSTONE Patrick": "fetherstone-patrick",
  "FETST Aubrey": "fetst-aubrey",
  "FETTER C": "fetter-c",
  "FETTER Steve": "fetter-steve",
  "FETZER Bret": "fetzer-bret",
  "FEUER Cy": "feuer-cy",
  "FEUER Jed": "feuer-jed",
  "FEUERMAN Roger": "feuerman-roger",
  "FEUSTAL Kelly": "feustal-kelly",
  "FEUTINGER Josephine": "feutinger-josephine",
  "FEVERED SLEEP ": "fevered-sleep",
  "FEVURLY Megan": "fevurly-megan",
  "FEWSTER Angela": "fewster-angela",
  "FEY Tina": "fey-tina",
  "FEYDEAU Georges": "feydeau-georges",
  "FEYK Ryan": "feyk-ryan",
  "FFRENCH Courtney": "ffrench-courtney",
  "FIAT LUX ": "fiat-lux",
  "FIBER Jon": "fiber-jon",
  "FICH Arne": "fich-arne",
  "FICKETT Hal": "fickett-hal",
  "FICKMAN Andy": "fickman-andy",
  "FIDDAMAN Mark": "fiddaman-mark",
  "FIDLER Donald Carl": "fidler-donald-carl",
  "FIDLER Joyce": "fidler-joyce",
  "FIDLER Kathleen": "fidler-kathleen",
  "FIDLER Michael": "fidler-michael",
  "FIDRAM Christopher": "fidram-christopher",
  "FIEGEL Ethan": "fiegel-ethan",
  "FIEHN Stephen": "fiehn-stephen",
  "FIELBERT Ed": "fielbert-ed",
  "FIELD Andy": "field-andy",
  "FIELD Barbara": "field-barbara",
  "FIELD Betsy": "field-betsy",
  "FIELD Brad": "field-brad",
  "FIELD Crystal": "field-crystal",
  "FIELD David C": "field-david-c",
  "FIELD Doug": "field-doug",
  "FIELD Ivana Jilovcova": "field-ivana-jilovcova",
  "FIELD John": "field-john",
  "FIELD Jonathan": "field-jonathan",
  "FIELD Nathan": "field-nathan",
  "FIELD Nick": "field-nick",
  "FIELD Rachel": "field-rachel",
  "FIELD Thalia": "field-thalia",
  "FIELDEN Charlotte": "fielden-charlotte",
  "FIELDER David": "fielder-david",
  "FIELDER Jez": "fielder-jez",
  "FIELDING David": "fielding-david",
  "FIELDING Ethel": "fielding-ethel",
  "FIELDING Helen": "fielding-helen",
  "FIELDING Henry": "fielding-henry",
  "FIELDING Jonnie": "fielding-jonnie",
  "FIELDING Noel": "fielding-noel",
  "FIELDING Ollie": "fielding-ollie",
  "FIELDS Aaron William": "fields-aaron-william",
  "FIELDS Barbara": "fields-barbara",
  "FIELDS Ben": "fields-ben",
  "FIELDS Chip": "fields-chip",
  "FIELDS Dan": "fields-dan",
  "FIELDS Dorothy": "fields-dorothy",
  "FIELDS Herbert": "fields-herbert",
  "FIELDS Joel": "fields-joel",
  "FIELDS Joseph": "fields-joseph",
  "FIELDS Kirby": "fields-kirby",
  "FIELDS Lew M": "fields-lew-m",
  "FIELDS Maurice": "fields-maurice",
  "FIELDS Michael": "fields-michael",
  "FIELDS Mike": "fields-mike",
  "FIELDS Peter Anthony": "fields-peter-anthony",
  "FIELDS Robert": "fields-robert",
  "FIELDSON Peter": "fieldson-peter",
  "FIELDSTEEL Robert": "fieldsteel-robert",
  "FIENSTEIN Joe": "fienstein-joe",
  "FIERRO David": "fierro-david",
  "FIERSTEIN Harvey": "fierstein-harvey",
  "FIFE Cameron": "fife-cameron",
  "FIFE Graeme": "fife-graeme",
  "FIFE Stephen": "fife-stephen",
  "FIFIELD Tim": "fifield-tim",
  "FIGERT S Albert": "figert-s-albert",
  "FIGG Olly": "figg-olly",
  "FIGGIS Mike": "figgis-mike",
  "FIGLMILLER John": "figlmiller-john",
  "FIGS IN WIGS ": "figs-in-wigs",
  "FIGUEIREDO Franko": "figueiredo-franko",
  "FIGUEIREDO Guilherne": "figueiredo-guilherne",
  "FIGUEROA Stephanie": "figueroa-stephanie",
  "FIGURENTHEATER TUBINGEN ": "figurentheater-tubingen",
  "FILANGIERI Keith": "filangieri-keith",
  "FILAR Ella": "filar-ella",
  "FILES Gary": "files-gary",
  "FILEWOOD Alan": "filewood-alan",
  "FILHO Paulo Biscaia": "filho-paulo-biscaia",
  "FILIPOWICZ H": "filipowicz-h",
  "FILIPPUSDOTTIR Nina Dogg": "filippusdottir-nina-dogg",
  "FILL Simon": "fill-simon",
  "FILLEBROWN Chris": "fillebrown-chris",
  "FILLER Deb": "filler-deb",
  "FILLINGER Johan": "fillinger-johan",
  "FILLIS Brian": "fillis-brian",
  "FILLOUX Catherine": "filloux-catherine",
  "FILLOUX-BENNETT Henry": "filloux-bennett-henry",
  "FILMER Kath": "filmer-kath",
  "FILTER THEATRE ": "filter-theatre",
  "FINCH John": "finch-john",
  "FINCH Peter": "finch-peter",
  "FINCH Robert": "finch-robert",
  "FINCHAM Peter": "fincham-peter",
  "FINDLAY Bill": "findlay-bill",
  "FINDLAY Carly": "findlay-carly",
  "FINDLAY Iver": "findlay-iver",
  "FINDLAY Jim": "findlay-jim",
  "FINDLAY Sophie": "findlay-sophie",
  "FINDLEY Timothy": "findley-timothy",
  "FINDSEN Troels Hagen": "findsen-troels-hagen",
  "FINE Anne": "fine-anne",
  "FINE Kaethe": "fine-kaethe",
  "FINE Keni": "fine-keni",
  "FINE Lois": "fine-lois",
  "FINE Stan": "fine-stan",
  "FINE Zack": "fine-zack",
  "FINE CHISEL ": "fine-chisel",
  "FINEBERG Larry": "fineberg-larry",
  "FINEGOLD Stephen": "finegold-stephen",
  "FINEMAN Jake": "fineman-jake",
  "FINES Ian": "fines-ian",
  "FINFER June": "finfer-june",
  "FINGERMAN Dan": "fingerman-dan",
  "FINGLETON Anthony": "fingleton-anthony",
  "FINITSIS Dimitris": "finitsis-dimitris",
  "FINK Charlie": "fink-charlie",
  "FINK Enrico": "fink-enrico",
  "FINK Joseph": "fink-joseph",
  "FINK Len": "fink-len",
  "FINKE Michael Charles": "finke-michael-charles",
  "FINKEL Gertrude B": "finkel-gertrude-b",
  "FINKEL Ian": "finkel-ian",
  "FINKELSTEIN Brian": "finkelstein-brian",
  "FINKELSTEIN David": "finkelstein-david",
  "FINKELSTEIN Deborah": "finkelstein-deborah",
  "FINKELSTEIN Jerry": "finkelstein-jerry",
  "FINKELSTEIN Kevin": "finkelstein-kevin",
  "FINKELSTEIN Naomi": "finkelstein-naomi",
  "FINKLAIRE Lottie": "finklaire-lottie",
  "FINKLE David": "finkle-david",
  "FINKLE Kenny": "finkle-kenny",
  "FINKLEHOFFE Fred F": "finklehoffe-fred-f",
  "FINKLESTEIN Deborah": "finklestein-deborah",
  "FINKLESTEIN Harvey": "finklestein-harvey",
  "FINLAY Byjonas": "finlay-byjonas",
  "FINLAY Daniel": "finlay-daniel",
  "FINLAY Diane": "finlay-diane",
  "FINLAY Ian Hamilton": "finlay-ian-hamilton",
  "FINLAY Jonas": "finlay-jonas",
  "FINLAY Joseph": "finlay-joseph",
  "FINLAY Peter": "finlay-peter",
  "FINLAY Robertson": "finlay-robertson",
  "FINLAY Steve": "finlay-steve",
  "FINLAY Suzanne": "finlay-suzanne",
  "FINLAY Wes": "finlay-wes",
  "FINLAYSON Alex": "finlayson-alex",
  "FINLEY Becca": "finley-becca",
  "FINLEY Cory": "finley-cory",
  "FINLEY David": "finley-david",
  "FINLEY Harold": "finley-harold",
  "FINLEY Ian": "finley-ian",
  "FINLEY Karen": "finley-karen",
  "FINLEY Mark": "finley-mark",
  "FINMAN John": "finman-john",
  "FINN Ben": "finn-ben",
  "FINN Billy": "finn-billy",
  "FINN Crystal": "finn-crystal",
  "FINN Jeanne C": "finn-jeanne-c",
  "FINN Jeffrey": "finn-jeffrey",
  "FINN Mike": "finn-mike",
  "FINN Stephen": "finn-stephen",
  "FINN Tim": "finn-tim",
  "FINN William": "finn-william",
  "FINNAN Paschal": "finnan-paschal",
  "FINNEGAN Amy": "finnegan-amy",
  "FINNEGAN Billy": "finnegan-billy",
  "FINNEGAN Jack": "finnegan-jack",
  "FINNEGAN Joan": "finnegan-joan",
  "FINNEGAN Rosie": "finnegan-rosie",
  "FINNEGAN Seamus": "finnegan-seamus",
  "FINNEMORE John": "finnemore-john",
  "FINNERAN William B": "finneran-william-b",
  "FINNEY Charles": "finney-charles",
  "FINNEY Paul": "finney-paul",
  "FINNIGAN Bryan": "finnigan-bryan",
  "FINNIGAN David": "finnigan-david",
  "FINOCCHIARO Dominic": "finocchiaro-dominic",
  "FINSTERER Anni": "finsterer-anni",
  "FINSTROM Tony": "finstrom-tony",
  "FINTZI Ariel": "fintzi-ariel",
  "FINUCANE Moira": "finucane-moira",
  "FINZI Susannah": "finzi-susannah",
  "FIORE Jessamyn": "fiore-jessamyn",
  "FIORENTINO Tony": "fiorentino-tony",
  "FIORI Flippo": "fiori-flippo",
  "FIORI Lucy": "fiori-lucy",
  "FIORILLO John": "fiorillo-john",
  "FIRCHOW P E": "firchow-p-e",
  "FIRDA Andrew": "firda-andrew",
  "FIREBIRD THEATRE ": "firebird-theatre",
  "FIREHOUSE CREATIVE PRODUCTIONS ": "firehouse-creative-productions",
  "FIREHOUSE THEATRE ": "firehouse-theatre",
  "FIRKE Benjamin": "firke-benjamin",
  "FIRKUSNY-CALLEGARI Veronique": "firkusny-callegari-veronique",
  "FIRLA Brandon": "firla-brandon",
  "FIRLA Kurt": "firla-kurt",
  "FIRMAN Jon": "hoenig-ron-and-jon-firman",
  "FIRPO-CAPPIELLO Robert": "firpo-cappiello-robert",
  "FIRST Phoebe": "first-phoebe",
  "FIRST FLOOR ": "first-floor",
  "FIRSTBORN THEATRE ": "firstborn-theatre",
  "FIRTH Ivan": "firth-ivan",
  "FIRTH John": "firth-john",
  "FIRTH Mike": "firth-mike",
  "FIRTH Olivia": "firth-olivia",
  "FIRTH Simon": "firth-simon",
  "FIRTH Tim": "firth-tim",
  "FISCH Adam J": "fisch-adam-j",
  "FISCH Victor": "fisch-victor",
  "FISCHBEIN Dahlia": "fischbein-dahlia",
  "FISCHER Carl A": "fischer-carl-a",
  "FISCHER Corey": "fischer-corey",
  "FISCHER Eileen": "fischer-eileen",
  "FISCHER Ernest": "fischer-ernest",
  "FISCHER Esta": "fischer-esta",
  "FISCHER Ilene A": "fischer-ilene-a",
  "FISCHER Justin S": "fischer-justin-s",
  "FISCHER Kai": "fischer-kai",
  "FISCHER Kathleen": "fischer-kathleen",
  "FISCHER Kim": "fischer-kim",
  "FISCHER Lori": "fischer-lori",
  "FISCHER Margaret": "fischer-margaret",
  "FISCHER Saskia": "fischer-saskia",
  "FISCHER Stephen": "fischer-stephen",
  "FISCHER / SPACKMAN ": "fischer-spackman",
  "FISCHEROVA Daniela": "fischerova-daniela",
  "FISCHER-SMITH Jeffrey": "fischer-smith-jeffrey",
  "FISCHMAN Shelia": "fischman-shelia",
  "FISCHOFF George": "fischoff-george",
  "FISET Joan": "fiset-joan",
  "FISH Daniel": "fish-daniel",
  "FISH Mike": "fish-mike",
  "FISH & GAME ": "fish-game",
  "FISHAMBLE: THE NEW PLAY COMPANY ": "fishamble",
  "FISHBACK Dan": "fishback-dan",
  "FISHBANE Joel": "fishbane-joel",
  "FISHBEYN Anna": "fishbeyn-anna",
  "FISHBURNE Laurence": "fishburne-laurence",
  "FISHBURNE Rodes": "fishburne-rodes",
  "FISHELSON David": "fishelson-david",
  "FISHER Adrian": "fisher-adrian",
  "FISHER Aileen": "fisher-aileen",
  "FISHER Amanda Stuart": "fisher-amanda-stuart",
  "FISHER Bennett": "fisher-bennett",
  "FISHER Bob": "fisher-bob",
  "FISHER Brian": "fisher-brian",
  "FISHER Carrie": "fisher-carrie",
  "FISHER Charlie Edwin": "fisher-charlie-edwin",
  "FISHER Chris": "fisher-chris",
  "FISHER Corinne": "fisher-corinne",
  "FISHER D": "fisher-d",
  "FISHER Dorothy Canfield": "fisher-dorothy-canfield",
  "FISHER Ellen": "fisher-ellen",
  "FISHER Emma": "fisher-emma",
  "FISHER Fred J": "fisher-fred-j",
  "FISHER Gregg": "fisher-gregg",
  "FISHER Harriet": "fisher-harriet",
  "FISHER Jessica Marie": "fisher-jessica-marie",
  "FISHER Joel": "fisher-joel",
  "FISHER John": "fisher-john",
  "FISHER John (1)": "fisher-john-1",
  "FISHER Joseph": "fisher-joseph",
  "FISHER Kevin": "fisher-kevin",
  "FISHER Layna": "fisher-layna",
  "FISHER Mark": "fisher-mark",
  "FISHER Michael Shaw": "fisher-michael-shaw",
  "FISHER Nick": "fisher-nick",
  "FISHER P H": "fisher-p-h",
  "FISHER Robert": "fisher-robert",
  "FISHER Rodney": "fisher-rodney",
  "FISHER Shawn": "fisher-shawn",
  "FISHER Steve": "fisher-steve",
  "FISHER Steven": "fisher-steven",
  "FISHER T J": "fisher-t-j",
  "FISHER T Langdon": "fisher-t-langdon",
  "FISHER Thomas": "fisher-thomas",
  "FISHER Van Dirk": "fisher-van-dirk",
  "FISHER William": "fisher-william",
  "FISHER-JOHNSON Tomasin": "fisher-johnson-tomasin",
  "FISHMAN Andrew": "fishman-andrew",
  "FISHMAN Grace": "fishman-grace",
  "FISHMAN Howard": "fishman-howard",
  "FISHMAN Ian": "fishman-ian",
  "FISHMAN Joan": "fishman-joan",
  "FISHMAN Nancy": "fishman-nancy",
  "FISK Bruce": "fisk-bruce",
  "FISK Dorothy M": "fisk-dorothy-m",
  "FISKE Jeffrey": "fiske-jeffrey",
  "FISKE-HARRISON Alexander": "fiske-harrison-alexander",
  "FISKIN Gene": "fiskin-gene",
  "FISTER-OXMAN Ellen": "fister-oxman-ellen",
  "FITCH Alan": "fitch-alan",
  "FITCH Clyde": "fitch-clyde",
  "FITCH Georgia": "fitch-georgia",
  "FITCHETT Lucie": "fitchett-lucie",
  "FITCHETT Richard": "fitchett-richard",
  "FITE Jason": "fite-jason",
  "FITHIAN Diana": "fithian-diana",
  "FITHIAN Zachary": "fithian-zachary",
  "FITT Brad": "fitt-brad",
  "FITTOCK Chris": "fittock-chris",
  "FITTS Dudley": "fitts-dudley",
  "FITTS Jonathan": "fitts-jonathan",
  "FITZ Chris": "fitz-chris",
  "FITZGERAL Anna": "fitzgeral-anna",
  "FITZGERALD Ara": "fitzgerald-ara",
  "FITZGERALD Beth": "fitzgerald-beth",
  "FITZGERALD Brendan": "fitzgerald-brendan",
  "FITZGERALD Catherine": "fitzgerald-catherine",
  "FITZGERALD Constantine": "fitzgerald-constantine",
  "FITZGERALD Frank T": "fitzgerald-frank-t",
  "FITZGERALD Gary": "fitzgerald-gary",
  "FITZGERALD Gerald": "fitzgerald-gerald",
  "FITZGERALD Geraldine": "fitzgerald-geraldine",
  "FITZGERALD Grace": "fitzgerald-grace",
  "FITZGERALD Hugh": "fitzgerald-hugh",
  "FITZGERALD J": "fitzgerald-j",
  "FITZGERALD Jack": "fitzgerald-jack",
  "FITZGERALD James": "fitzgerald-james",
  "FITZGERALD Jim": "fitzgerald-jim",
  "FITZGERALD Jo": "fitzgerald-jo",
  "FITZGERALD Karen": "fitzgerald-karen",
  "FITZGERALD Kitty": "fitzgerald-kitty",
  "FITZGERALD Laura": "fitzgerald-laura",
  "FITZGERALD Lynne": "fitzgerald-lynne",
  "FITZGERALD M J": "fitzgerald-m-j",
  "FITZGERALD Maureen": "fitzgerald-maureen",
  "FITZGERALD Neil C": "fitzgerald-neil-c",
  "FITZGERALD Patrick": "fitzgerald-patrick",
  "FITZGERALD Patrik": "fitzgerald-patrik",
  "FITZGERALD Robert": "fitzgerald-robert",
  "FITZGERALD Ron": "fitzgerald-ron",
  "FITZGERALD Rosemary": "fitzgerald-rosemary",
  "FITZGERALD Sarah Moore": "fitzgerald-sarah-moore",
  "FITZ-GERALD Allen": "fitz-gerald-allen",
  "FITZGIBBEN Constantine": "fitzgibben-constantine",
  "FITZGIBBON Brian": "fitzgibbon-brian",
  "FITZGIBBON Emelie": "fitzgibbon-emelie",
  "FITZGIBBON Ger": "fitzgibbon-ger",
  "FITZGIBBON Sarah": "fitzgibbon-sarah",
  "FITZGIBBONS Mark": "fitzgibbons-mark",
  "FITZHUGH Ellen": "fitzhugh-ellen",
  "FITZJOHN Donald": "fitzjohn-donald",
  "FITZJOHN Eric": "fitzjohn-eric",
  "FITZMACKEN Tom": "fitzmacken-tom",
  "FITZMAURICE Annie": "fitzmaurice-annie",
  "FITZMAURICE George": "fitzmaurice-george",
  "FITZMORRIS Jim": "fitzmorris-jim",
  "FITZPATRICK Alexa": "fitzpatrick-alexa",
  "FITZPATRICK Ciaran": "fitzpatrick-ciaran",
  "FITZPATRICK Frank": "fitzpatrick-frank",
  "FITZPATRICK John": "fitzpatrick-john",
  "FITZPATRICK Julie": "fitzpatrick-julie",
  "FITZPATRICK Katy": "fitzpatrick-katy",
  "FITZPATRICK Kurt": "fitzpatrick-kurt",
  "FITZPATRICK Peter": "fitzpatrick-peter",
  "FITZPATRICK Rachel": "fitzpatrick-rachel",
  "FITZPATRICK Steve": "fitzpatrick-steve",
  "FITZPATRICK Tim": "fitzpatrick-tim",
  "FITZPATRICK Tom": "fitzpatrick-tom",
  "FITZPATRICK Tony": "fitzpatrick-tony",
  "FITZROY Kate": "fitzroy-kate",
  "FITZSIMMONS Kelly Jean": "fitzsimmons-kelly-jean",
  "FITZSIMMONS Michelle": "fitzsimmons-michelle",
  "FITZSIMONS Raymund": "fitzsimons-raymund",
  "FIUMANO-FARLEY Donna": "fiumano-farley-donna",
  "FIVE FLIGHTS THEATER COMPANY ": "five-flights-theater-company",
  "FIVE GALLANTS ": "five-gallants",
  "FIVE LESBIAN BROTHERS ": "five-lesbian-brothers",
  "FIX Michelle": "fix-michelle",
  "FIXEL Michael": "fixel-michael",
  "FIZZARD Anne": "fizzard-anne",
  "FJELDE Rolf": "fjelde-rolf",
  "FLACK Eamon": "flack-eamon",
  "FLACK Jonathan": "flack-jonathan",
  "FLACK Stuart": "flack-stuart",
  "FLACKS Diane": "flacks-diane",
  "FLACKS Matthew": "flacks-matthew",
  "FLADI Ulrich": "fladi-ulrich",
  "FLAGER Gwen": "flager-gwen",
  "FLAGG Ann": "flagg-ann",
  "FLAGG Kim": "flagg-kim",
  "FLAHAVEN Sean Patrick": "flahaven-sean-patrick",
  "FLAHERTY Katherine Bryant": "flaherty-katherine-bryant",
  "FLAHERTY Lanny": "flaherty-lanny",
  "FLAHERTY Nancy": "flaherty-nancy",
  "FLAHERTY Peter D": "flaherty-peter-d",
  "FLAHERTY Robert J": "flaherty-robert-j",
  "FLAHERTY Stephen": "flaherty-stephen",
  "FLAHERTY Tim": "flaherty-tim",
  "FLAHIVE Liz": "flahive-liz",
  "FLAKS Diana": "flaks-diana",
  "FLAME ": "flame",
  "FLAMING THEATRE ": "flaming-theatre",
  "FLANAGAN Alan": "flanagan-alan",
  "FLANAGAN Anne": "flanagan-anne",
  "FLANAGAN Christine": "flanagan-christine",
  "FLANAGAN Dennis": "flanagan-dennis",
  "FLANAGAN Elizabeth": "flanagan-elizabeth",
  "FLANAGAN Gerry": "flanagan-gerry",
  "FLANAGAN Hallie": "flanagan-hallie",
  "FLANAGAN John": "flanagan-john",
  "FLANAGAN June": "flanagan-june",
  "FLANAGAN Kristen M": "flanagan-kristen-m",
  "FLANAGAN Maile": "flanagan-maile",
  "FLANAGAN Mary": "flanagan-mary",
  "FLANAGAN Nicholas": "flanagan-nicholas",
  "FLANAGAN Peter J": "flanagan-peter-j",
  "FLANAGAN COLLECTIVE ": "flanagan-collective",
  "FLANDERS Ash": "flanders-ash",
  "FLANDERS Michael": "flanders-michael",
  "FLANIGAN Peter": "flanigan-peter",
  "FLANIGAN Tom": "flanigan-tom",
  "FLANNERY Gemma": "flannery-gemma",
  "FLANNERY Pauline": "flannery-pauline",
  "FLANNERY Peter": "flannery-peter",
  "FLANNERY Sheri": "flannery-sheri",
  "FLANNERY Timothy": "flannery-timothy",
  "FLANTZ Richard": "flantz-richard",
  "FLASKOVA Zuzana": "flaskova-zuzana",
  "FLATHER Patti": "flather-patti",
  "FLATRATE ": "flatrate",
  "FLATT Kate": "flatt-kate",
  "FLATT Robyn": "flatt-robyn",
  "FLATTO Michele": "flatto-michele",
  "FLAUM Becky": "flaum-becky",
  "FLAUTT Paula B": "flautt-paula-b",
  "FLAUTT Paula Y": "flautt-paula-y",
  "FLAVIN Dick": "flavin-dick",
  "FLAWS Christy": "flaws-christy",
  "FLAXMAN Gary": "flaxman-gary",
  "FLAXMAN John": "flaxman-john",
  "FLAYTON Leigh": "flayton-leigh",
  "FLECK Erin": "fleck-erin",
  "FLECK John": "fleck-john",
  "FLEET Greg": "fleet-greg",
  "FLEET Henry": "fleet-henry",
  "FLEISCHER Julie": "fleischer-julie",
  "FLEISCHHACKER D J": "fleischhacker-d-j",
  "FLEISCHMAN Paul": "fleischman-paul",
  "FLEISCHMAN Sid": "fleischman-sid",
  "FLEISCHMANN Emanuel": "fleischmann-emanuel",
  "FLEISCHMANN Stephanie": "fleischmann-stephanie",
  "FLEISHER David": "fleisher-david",
  "FLEISHMAN Alan Ross": "fleishman-alan-ross",
  "FLEISSER Marieluise": "fleisser-marieluise",
  "FLEITAS Christopher": "fleitas-christopher",
  "FLEITMAN Jessica": "fleitman-jessica",
  "FLEMING Amanda": "fleming-amanda",
  "FLEMING Anne": "fleming-anne",
  "FLEMING Anne (1)": "fleming-anne-1",
  "FLEMING Bill": "fleming-bill",
  "FLEMING Brian": "fleming-brian",
  "FLEMING Carolyn": "fleming-carolyn",
  "FLEMING Don": "fleming-don",
  "FLEMING Jack W": "fleming-jack-w",
  "FLEMING Jill": "fleming-jill",
  "FLEMING Jo": "fleming-jo",
  "FLEMING John": "fleming-john",
  "FLEMING Justin": "fleming-justin",
  "FLEMING Leon": "fleming-leon",
  "FLEMING Maureen": "fleming-maureen",
  "FLEMING Maurice": "fleming-maurice",
  "FLEMING Neil": "fleming-neil",
  "FLEMING Neil (2)": "fleming-neil-2",
  "FLEMING Peter": "fleming-peter",
  "FLEMING Sandra": "fleming-sandra",
  "FLEMING Tom": "fleming-tom",
  "FLEMINGS Renee": "flemings-renee",
  "FLEMMING Brian": "flemming-brian",
  "FLEMMING Denise B": "flemming-denise-b",
  "FLEMMING Maureen": "flemming-maureen",
  "FLESZAR Dewey": "fleszar-dewey",
  "FLETCHER Alan": "fletcher-alan",
  "FLETCHER Anthony": "fletcher-anthony",
  "FLETCHER B B": "fletcher-b-b",
  "FLETCHER Chris": "fletcher-chris",
  "FLETCHER Destiny Candyce P": "fletcher-destiny-candyce-p",
  "FLETCHER Eric": "fletcher-eric",
  "FLETCHER Gregory": "fletcher-gregory",
  "FLETCHER Hamish": "fletcher-hamish",
  "FLETCHER Hugh L": "fletcher-hugh-l",
  "FLETCHER Janine": "fletcher-janine",
  "FLETCHER Jeremy James": "fletcher-jeremy-james",
  "FLETCHER Joe": "fletcher-joe",
  "FLETCHER John": "fletcher-john",
  "FLETCHER Lucille": "fletcher-lucille",
  "FLETCHER Mark": "fletcher-mark",
  "FLETCHER Matt": "fletcher-matt",
  "FLETCHER Paddy": "fletcher-paddy",
  "FLETCHER Rebecca Joy": "fletcher-rebecca-joy",
  "FLETCHER Russell": "fletcher-russell",
  "FLETCHER Sophie": "fletcher-sophie",
  "FLETCHER Steven": "fletcher-steven",
  "FLEURANTIN Stephanie": "fleurantin-stephanie",
  "FLEURY Claire": "fleury-claire",
  "FLEURY Patrick": "fleury-patrick",
  "FLEWITT Lee": "flewitt-lee",
  "FLEXER Michael J": "flexer-michael-j",
  "FLEXIBLE DEADLOCK ": "flexible-deadlock",
  "FLICK Matt": "flick-matt",
  "FLICKER Bob": "flicker-bob",
  "FLICKER Theodore J": "flicker-theodore-j",
  "FLIND Sarah": "flind-sarah",
  "FLINN Kevin": "flinn-kevin",
  "FLINN Lewis": "flinn-lewis",
  "FLINT Austin": "flint-austin",
  "FLINT C S": "flint-c-s",
  "FLINT Daniel": "flint-daniel",
  "FLINT Diana": "flint-diana",
  "FLINTER Daniel": "flinter-daniel",
  "FLINTHAM Frazer": "flintham-frazer",
  "FLINTOFF Beth": "flintoff-beth",
  "FLINTOFF Ian": "flintoff-ian",
  "FLISAR Evald": "flisar-evald",
  "FLITTON Dave": "flitton-dave",
  "FLITTON Martin": "flitton-martin",
  "FLITTON Sheila": "flitton-sheila",
  "FLOATING PARTNERS ": "floating-partners",
  "FLODEN Lea": "floden-lea",
  "FLODEN Mary Lea": "floden-mary-lea",
  "FLOODS OF INK ": "floods-of-ink",
  "FLOR Robert Francis": "flor-robert-francis",
  "FLORA David": "flora-david",
  "FLOREN Kari": "floren-kari",
  "FLORENCE Rob": "florence-rob",
  "FLORENCIANI ": "florenciani",
  "FLORENTINO Alberto": "florentino-alberto",
  "FLORES Angel": "flores-angel",
  "FLORES David": "flores-david",
  "FLORES Derek": "flores-derek",
  "FLORES Dyan": "flores-dyan",
  "FLORES Elixeo": "flores-elixeo",
  "FLORES Guadalupe": "flores-guadalupe",
  "FLORES Lane": "flores-lane",
  "FLORES Ronald": "flores-ronald",
  "FLOREZ Dave": "florez-dave",
  "FLORI Alex": "flori-alex",
  "FLORIDO Blanca": "florido-blanca",
  "FLORIO Julie": "florio-julie",
  "FLORSCHUTZ Melanie": "florschutz-melanie",
  "FLORY Erin": "flory-erin",
  "FLORY Louise": "flory-louise",
  "FLORY Monica": "flory-monica",
  "FLOURAKIS Andreas": "flourakis-andreas",
  "FLOWER Alan": "flower-alan",
  "FLOWER Bettina": "flower-bettina",
  "FLOWER Cedric": "flower-cedric",
  "FLOWER Janice": "flower-janice",
  "FLOWER Pat": "flower-pat",
  "FLOWERS Herbert": "flowers-herbert",
  "FLOY Gregory": "floy-gregory",
  "FLOY Monica": "floy-monica",
  "FLOYD Jacquelyn": "floyd-jacquelyn",
  "FLOYD Lawrence": "floyd-lawrence",
  "FLOYD Peter M": "floyd-peter-m",
  "FLOYD Ronald": "floyd-ronald",
  "FLOYD-MILLER Cherryl": "floyd-miller-cherryl",
  "FLUDD III Quitmann": "fludd-quitmann",
  "FLUHARTY Jeff": "fluharty-jeff",
  "FLUHR James": "fluhr-james",
  "FLUHR Nancy Steffen": "fluhr-nancy-steffen",
  "FLUTUR Vasile": "flutur-vasile",
  "FLYING CARPET ": "flying-carpet",
  "FLYING EYE ": "flying-eye",
  "FLYING INVALID COMPANY ": "flying-invalid-company",
  "FLYING KARAMOZOV BROTHERS, THE ": "flying-karamozov-brothers",
  "FLYING MACHINE, THE ": "flying-machine-the",
  "FLYNN Adrian": "flynn-adrian",
  "FLYNN Bryan": "flynn-bryan",
  "FLYNN Clancy": "flynn-clancy",
  "FLYNN Dennis": "flynn-dennis",
  "FLYNN Dominic": "flynn-dominic",
  "FLYNN Don": "flynn-don",
  "FLYNN Frank": "flynn-frank",
  "FLYNN Gerard Mannix": "flynn-gerard-mannix",
  "FLYNN Graeme": "flynn-graeme",
  "FLYNN Jimmy": "flynn-jimmy",
  "FLYNN John": "flynn-john",
  "FLYNN Keely": "flynn-keely",
  "FLYNN Kelly": "flynn-kelly",
  "FLYNN Lance": "flynn-lance",
  "FLYNN Louis": "flynn-louis",
  "FLYNN Megan": "flynn-megan",
  "FLYNN Neil": "flynn-neil",
  "FLYNN Neil (2)": "flynn-neil-2",
  "FLYNN Nick": "flynn-nick",
  "FLYNN Nigel": "flynn-nigel",
  "FLYNN Patrick": "flynn-patrick",
  "FLYNN Paul": "flynn-paul",
  "FLYNN Robert L": "flynn-robertl",
  "FLYNN Thomas Fitzgerald": "flynn-thomas-fitzgerald",
  "FLYNN Tony": "flynn-tony",
  "FO Dario": "fo-dario",
  "FOAD Nathan": "foad-nathan",
  "FOARD Sylvia-elaine": "foard-sylvia-elaine",
  "FOBISTER Waawaate": "fobister-waawaate",
  "FODOR Kate": "fodor-kate",
  "FODOR Ladislaus": "fodor-ladislaus",
  "FOERSTER Wendy": "foerster-wendy",
  "FOFI David": "fofi-david",
  "FOG Nina": "fog-nina",
  "FOGARTY Benedict": "fogarty-benedict",
  "FOGARTY Matthew": "fogarty-matthew",
  "FOGARTY Molly": "fogarty-molly",
  "FOGARTY Nick": "fogarty-nick",
  "FOGARTY Ryan": "fogarty-ryan",
  "FOGARTY Sharon": "fogarty-sharon",
  "FOGARTY Sharon (1)": "fogarty-sharon-1",
  "FOGARTY Thom": "fogarty-thom",
  "FOGARTY-GRAVESON Gabriel": "fogarty-graveson-gabriel",
  "FOGEL Bryan": "fogel-bryan",
  "FOGEL Susanna": "fogel-susanna",
  "FOGELMAN Steven": "fogelman-steven",
  "FOGERSON Barbara": "fogerson-barbara",
  "FOGGO Cheryl": "foggo-cheryl",
  "FOGGO John": "foggo-john",
  "FOGLER Dan": "fogler-dan",
  "FOGLINO Paul": "foglino-paul",
  "FOLANI Femi": "folani-femi",
  "FOLAYAN Omodele": "folayan-omodele",
  "FOLDS Ben": "folds-ben",
  "FOLEY Chris": "foley-chris",
  "FOLEY Connor M": "foley-connor-m",
  "FOLEY Daniel": "foley-daniel",
  "FOLEY David": "foley-david",
  "FOLEY Erin": "foley-erin",
  "FOLEY J R": "foley-j-r",
  "FOLEY John": "foley-john",
  "FOLEY Laura-Jane": "foley-laura-jane",
  "FOLEY Melinda Corazon": "foley-melinda-corazon",
  "FOLEY Mike": "foley-mike",
  "FOLEY Patrick": "foley-patrick",
  "FOLEY Pete": "foley-pete",
  "FOLEY Peter": "foley-peter",
  "FOLEY Rosemary": "foley-rosemary",
  "FOLEY Sean": "foley-sean",
  "FOLEY Tim": "foley-tim",
  "FOLEY Tomaseen": "foley-tomaseen",
  "FOLEY Valerie": "foley-valerie",
  "FOLIE Mike": "folie-mike",
  "FOLINO Thomas F": "folino-thomas-f",
  "FOLK Roland": "folk-roland",
  "FOLLES ALLIEES ": "folles-alliees",
  "FOLLOWS Edwina": "follows-edwina",
  "FOLS Craig": "fols-craig",
  "FOLSCHINSKY Jeff": "folschinsky-jeff",
  "FOLSTEIN Ben": "folstein-ben",
  "FOLTZ Teri Ann": "foltz-teri-ann",
  "FOLWELL David": "folwell-david",
  "FON Bryn": "fon-bryn",
  "FONDA Jane": "fonda-jane",
  "FONDAKOWSKI Leigh": "fondakowski-leigh",
  "FONDREN Fred": "fondren-fred",
  "FONG Christopher": "fong-christopher",
  "FONG Gilbert C F": "fong-gilbert-c-f",
  "FONG Howard": "fong-howard",
  "FONG Jason": "fong-jason",
  "FONGENIE Vivian": "fongenie-vivian",
  "FONTAINE Robert": "fontaine-robert",
  "FONTAINE Ton": "fontaine-ton",
  "FONTANA Thomas M": "fontana-thomas-m",
  "FONTANES Chris": "fontanes-chris",
  "FONTAYNE Fine Time": "fontayne-fine-time",
  "FONTE Len": "fonte-len",
  "FONTEBOA Fidel": "fonteboa-fidel",
  "FONTECILLA Camilo": "fontecilla-camilo",
  "FONTENBOA Fidel": "fontenboa-fidel",
  "FONUA Lolo": "fonua-lolo",
  "FONVIZIN Denis Ivanovich": "fonvizin-denis-ivanovich",
  "FOOLS PROOF THEATRE ": "fools-proof-theatre",
  "FOON Dennis": "foon-dennis",
  "FOORD Isabelle": "foord-isabelle",
  "FOOT Alistair": "foot-alistair",
  "FOOT Lara": "foot-lara",
  "FOOTE Christina": "foote-christina",
  "FOOTE Daisy": "foote-daisy",
  "FOOTE Ethan": "foote-ethan",
  "FOOTE Graham": "foote-graham",
  "FOOTE Horton": "foote-horton",
  "FOOTE Magill": "foote-magill",
  "FOOTSBARN ": "footsbarn",
  "FOR Lee Joo": "for-lee-joo",
  "FOR WE ARE MANY ": "for-we-are-many",
  "FORAN Adrienne": "foran-adrienne",
  "FORAN Barney": "foran-barney",
  "FORBES Alastair": "forbes-alastair",
  "FORBES Annie": "forbes-annie",
  "FORBES C Scott": "forbes-c-scott",
  "FORBES Cameron": "forbes-cameron",
  "FORBES Caroline": "forbes-caroline",
  "FORBES Charles": "forbes-charles",
  "FORBES Fred J": "forbes-fred-j",
  "FORBES Jamie": "forbes-jamie",
  "FORBES Lynne": "forbes-lynne",
  "FORBES Michael": "forbes-michael",
  "FORBES Roger": "forbes-roger",
  "FORBES Thomas": "forbes-thomas",
  "FORBRITCH Joe": "forbritch-joe",
  "FORCED ENTERTAINMENT ": "forced-entertainment",
  "FORD Alan": "ford-alan",
  "FORD Andre": "ford-andre",
  "FORD Bethany": "ford-bethany",
  "FORD Brooke A": "ford-brooke-a",
  "FORD Charles": "ford-charles",
  "FORD Charlotte": "ford-charlotte",
  "FORD Corey": "ford-corey",
  "FORD David": "ford-david",
  "FORD David Douglas": "ford-david-douglas",
  "FORD David S": "ford-david-s",
  "FORD Ernest": "ford-ernest",
  "FORD Evelyn": "ford-evelyn",
  "FORD Fergus": "ford-fergus",
  "FORD Frank B": "ford-frank-b",
  "FORD Gaby": "ford-gaby",
  "FORD Garret": "ford-garret",
  "FORD James Robert": "ford-james-robert",
  "FORD James-Allen": "ford-james-allen",
  "FORD Jane": "ford-jane",
  "FORD Jason": "ford-jason",
  "FORD Joan": "ford-joan",
  "FORD Joe Taylor": "ford-joe-taylor",
  "FORD Joshua": "ford-joshua",
  "FORD Julie": "ford-julie",
  "FORD Laura": "ford-laura",
  "FORD Lin": "ford-lin",
  "FORD Megan": "ford-megan",
  "FORD Michael James": "ford-michael-james",
  "FORD Mick": "ford-mick",
  "FORD Nancy": "ford-nancy",
  "FORD Randy": "ford-randy",
  "FORD Robert": "ford-robert",
  "FORD Robert John": "ford-robert-john",
  "FORD Ruth": "ford-ruth",
  "FORD Sarah": "ford-sarah",
  "FORD Simon": "ford-simon",
  "FORD T Cat": "ford-t-cat",
  "FORD Tim": "ford-tim",
  "FORD Timothy": "ford-timothy",
  "FORD Tramaine Montell": "ford-tramaine-montell",
  "FORD William": "ford-william",
  "FORDE Adam": "forde-adam",
  "FORDE B Bil": "forde-b-bil",
  "FORDE Catherine": "forde-catherine",
  "FORDE Elizabeth": "forde-elizabeth",
  "FORDE Ida": "forde-ida",
  "FORDE Leila": "forde-leila",
  "FORDE Margery": "forde-margery",
  "FORDE Michael": "forde-michael",
  "FORDE Nigel": "forde-nigel",
  "FORDE Patricia": "forde-patricia",
  "FORDE Rogerson": "forde-rogerson",
  "FORDHAM Debra": "fordham-debra",
  "FORDHAM Finn": "fordham-finn",
  "FORDHAM Philippa": "fordham-philippa",
  "FORDHAM Rosy": "fordham-rosy",
  "FORDRED Chris": "fordred-chris",
  "FORDYCE Maxwell": "fordyce-maxwell",
  "FORDYCE Robin": "fordyce-robin",
  "FOREMAN Bridget": "foreman-bridget",
  "FOREMAN Cecilia": "foreman-cecilia",
  "FOREMAN Gill": "foreman-gill",
  "FOREMAN Karole": "foreman-karole",
  "FOREMAN Lauren": "foreman-lauren",
  "FOREMAN Martin": "foreman-martin",
  "FOREMAN Paul": "foreman-paul",
  "FOREMAN Richard": "foreman-richard",
  "FOREMAN Ronlin": "foreman-ronlin",
  "FOREMAN Sam": "foreman-sam",
  "FOREMAN Samuel L": "foreman-samuel-l",
  "FOREMAN Tom": "foreman-tom",
  "FORESMAN Becca": "foresman-becca",
  "FOREST Chris": "forest-chris",
  "FOREST D'yan": "forest-d-yan",
  "FOREST Jean": "forest-jean",
  "FOREST Robert": "forest-robert",
  "FORESTER Wayne": "forester-wayne",
  "FOREY Margaret": "forey-margaret",
  "FORGASH Adam": "forgash-adam",
  "FORGASZ Rachel": "forgasz-rachel",
  "FORGETTE Katie": "forgette-katie",
  "FORGIE Derek": "forgie-derek",
  "FORIER Elise": "forier-elise",
  "FORKBEARD FANTASY ": "forkbeard-fantasy",
  "FORMA Anthony": "forma-anthony",
  "FORMAN David": "forman-david",
  "FORMAN Joan": "forman-joan",
  "FORMAN John D": "forman-john-d",
  "FORMAN Sam": "forman-sam",
  "FORMAN Susan": "forman-susan",
  "FORMBY Dana Lynn": "formby-dana-lynn",
  "FORMISANO Laura": "formisano-laura",
  "FORNACE Sarah": "fornace-sarah",
  "FORNAROLA Drew": "fornarola-drew",
  "FORNES Maria Irene": "fornes-maria-irene",
  "FORNOFF Frederick H": "fornoff-frederick-h",
  "FORNSHELL Sarah": "fornshell-sarah",
  "FORRELL Lisa": "forrell-lisa",
  "FORREST Angela": "forrest-angela",
  "FORREST David": "forrest-david",
  "FORREST Diane": "forrest-diane",
  "FORREST Donald": "forrest-donald",
  "FORREST George": "forrest-george",
  "FORREST Robert": "forrest-robert",
  "FORREST Robert C": "forrest-robert-c",
  "FORRESTER Brian": "forrester-brian",
  "FORRESTER Lynne": "forrester-lynne",
  "FORREST-TURNER Lorraine": "forrest-turner-lorraine",
  "FORRISTAL Desmond": "forristal-desmond",
  "FORSAITH Ann": "forsaith-ann",
  "FORSBERG Julia": "forsberg-julia",
  "FORSBERG Kent": "forsberg-kent",
  "FORSBERG Rolf": "forsberg-rolf",
  "FORSHAW Robert Pierpont": "forshaw-robert-pierpont",
  "FORSHAY-LUNSFORD Cin": "forshay-lunsford-cin",
  "FORSSELL Boel": "forssell-boel",
  "FORSSELL Lars": "forssell-lars",
  "FORSTEN Michele": "forsten-michele",
  "FORSTER Benjamin": "forster-benjamin",
  "FORSTER David": "forster-david",
  "FORSTER Joan S": "forster-joan-s",
  "FORSTER John": "forster-john",
  "FORSTER Juliet": "forster-juliet",
  "FORSTER Michelanne": "forster-michelanne",
  "FORSYTH Anna": "forsyth-anna",
  "FORSYTH Anthony": "forsyth-anthony",
  "FORSYTH Frederick": "forsyth-frederick",
  "FORSYTH Graeme": "forsyth-graeme",
  "FORSYTH Ian": "forsyth-ian",
  "FORSYTH James": "forsyth-james",
  "FORSYTH Julian": "forsyth-julian",
  "FORSYTH Julie": "forsyth-julie",
  "FORSYTH Louise H": "forsyth-louise-h",
  "FORSYTH Margarete": "forsyth-margarete",
  "FORSYTH Oli": "forsyth-oli",
  "FORSYTH William": "forsyth-william",
  "FORSYTHE Drew": "forsythe-drew",
  "FORSYTHE Tracy": "forsythe-tracy",
  "FORSYTHE William": "forsythe-william",
  "FORT Bernadette": "fort-bernadette",
  "FORTE Gian Marco Lo": "forte-gian-marco-lo",
  "FORTE James": "forte-james",
  "FORTENBERRY Dorothy": "fortenberry-dorothy",
  "FORTEY Stuart": "fortey-stuart",
  "FORTH Laura J": "forth-laura-j",
  "FORTH Sally": "forth-sally",
  "FORTI Laura": "forti-laura",
  "FORTIN Larry Gene": "fortin-larry-gene",
  "FORTIN Simon": "fortin-simon",
  "FORTSON Deborah Lake": "fortson-deborah-lake",
  "FORTSON Leigh": "fortson-leigh",
  "FORTUNATI ": "fortunati",
  "FORTUNATO Raymond": "fortunato-raymond",
  "FORTUNE Eddie": "fortune-eddie",
  "FORTUNE James": "fortune-james",
  "FORTUNE Jaye": "fortune-jaye",
  "FORTUNE Rebekah": "fortune-rebekah",
  "FOSBERG Michael Sidney": "fosberg-michael-sidney",
  "FOSBROOK Michael": "fosbrook-michael",
  "FOS'I Opetaia": "fos-i-opetaia",
  "FOSKOLOU Nadia": "foskolou-nadia",
  "FOSS Lucas": "foss-lucas",
  "FOSS Rene": "foss-rene",
  "FOSSE Bob": "fosse-bob",
  "FOSSE Jon": "fosse-jon",
  "FOSSE Nicole": "fosse-nicole",
  "FOSSEY Eleanor": "fossey-eleanor",
  "FOSTER Abbie": "foster-abbie",
  "FOSTER Adam": "foster-adam",
  "FOSTER Alex": "foster-alex",
  "FOSTER Alison": "foster-alison",
  "FOSTER Andy": "foster-andy",
  "FOSTER Annette": "foster-annette",
  "FOSTER Ben": "foster-ben",
  "FOSTER Beverley Anne": "foster-beverley-anne",
  "FOSTER Brian": "foster-brian",
  "FOSTER Brian D": "foster-brian-d",
  "FOSTER C Stephen": "foster-c-stephen",
  "FOSTER Christine": "foster-christine",
  "FOSTER Dawn L": "foster-dawn-l",
  "FOSTER Dutton": "foster-dutton",
  "FOSTER Eden": "foster-eden",
  "FOSTER Emmett": "foster-emmett",
  "FOSTER F A": "foster-f-a",
  "FOSTER George Cecil": "foster-george-cecil",
  "FOSTER Gerard": "foster-gerard",
  "FOSTER Gordon": "foster-gordon",
  "FOSTER Gregory": "foster-gregory",
  "FOSTER Helen": "foster-helen",
  "FOSTER Hunter": "foster-hunter",
  "FOSTER Hutchins": "foster-hutchins",
  "FOSTER Jamie": "foster-jamie",
  "FOSTER Jessica": "foster-jessica",
  "FOSTER John": "foster-john",
  "FOSTER John Wilson": "foster-john-wilson",
  "FOSTER Joseph": "foster-joseph",
  "FOSTER K R S": "foster-k-r-s",
  "FOSTER Kate": "foster-kate",
  "FOSTER Keith": "foster-keith",
  "FOSTER Kimberly": "foster-kimberly",
  "FOSTER Kirk": "foster-kirk",
  "FOSTER Lucy": "foster-lucy",
  "FOSTER Mathew": "foster-mathew",
  "FOSTER Matthew": "foster-matthew",
  "FOSTER Michael": "foster-michael",
  "FOSTER Miranda": "foster-miranda",
  "FOSTER Murray": "foster-murray",
  "FOSTER Neal": "foster-neal",
  "FOSTER Norm": "foster-norm",
  "FOSTER Paul": "foster-paul",
  "FOSTER Paul B": "foster-paul-b",
  "FOSTER Rick": "foster-rick",
  "FOSTER Rosemary": "foster-rosemary",
  "FOSTER Skip": "foster-skip",
  "FOSTER Sophie": "foster-sophie",
  "FOSTER Stephen": "foster-stephen",
  "FOSTER Tony": "foster-tony",
  "FOSTER Winnie": "foster-winnie",
  "FOSTER (PAFOSTER) Paul": "foster-paul-2",
  "FOSTINI John": "fostini-john",
  "FOTHERGILL Robert": "fothergill-robert",
  "FOTHERINGHAM Elizabeth": "fotheringham-elizabeth",
  "FOTHERINGHAM Richard": "fotheringham-richard",
  "FOTI John": "foti-john",
  "FOTIS Matt": "fotis-matt",
  "FOTIS Mike": "fotis-mike",
  "FOUCARD Alexandra": "foucard-alexandra",
  "FOUCHE Gene": "fouche-gene",
  "FOUDY Austin": "foudy-austin",
  "FOUERE Olwen": "fouere-olwen",
  "FOULDS Adam": "foulds-adam",
  "FOULDS John": "foulds-john",
  "FOULTER James": "foulter-james",
  "FOUND Katie": "found-katie",
  "FOUNTAIN Bill": "fountain-bill",
  "FOUNTAIN Brooks Lyle": "fountain-brooks-lyle",
  "FOUNTAIN Nev": "fountain-nev",
  "FOUNTAIN Tim": "fountain-tim",
  "FOUR BROTHERS, THE ": "four-brothers",
  "FOUR HORSEMEN, THE ": "four-horsemen",
  "FOURACES George": "fouraces-george",
  "FOURIE Charles J": "fourie-charles-j",
  "FOURNIER Jack": "fournier-jack",
  "FOURNIER John": "fournier-john",
  "FOURSIGHT THEATRE ": "foursight-theatre",
  "FOURTH LEAF THEATRE COMPANY ": "fourth-leaf-theatre-company",
  "FOURTH MONKEY THEATRE COMPANY ": "fourth-monkey-theatre-company",
  "FOUST Joe": "foust-joe",
  "FOVARGE Oscar": "fovarge-oscar",
  "FOW Elizabeth": "fow-elizabeth",
  "FOWKES William": "fowkes-william",
  "FOWLER Arthur": "fowler-arthur",
  "FOWLER Darcy": "fowler-darcy",
  "FOWLER David Jean": "fowler-david-jean",
  "FOWLER Earl Leslie": "fowler-earl-leslie",
  "FOWLER Elizabeth Anne": "fowler-elizabeth-anne",
  "FOWLER Eric": "fowler-eric",
  "FOWLER Jeffrey Jay": "fowler-jeffrey-jay",
  "FOWLER Jeri": "fowler-jeri",
  "FOWLER Jim": "fowler-jim",
  "FOWLER John": "fowler-john",
  "FOWLER Jude": "fowler-jude",
  "FOWLER Kim": "fowler-kim",
  "FOWLER Mayhill": "fowler-mayhill",
  "FOWLER Molly": "fowler-molly",
  "FOWLER Stephanie": "fowler-stephanie",
  "FOWLER-WATT Duncan": "fowler-watt-duncan",
  "FOWLES John": "fowles-john",
  "FOWLIE Wallace": "fowlie-wallace",
  "FOX Adam": "fox-adam",
  "FOX Akiva": "fox-akiva",
  "FOX Albert (Al)": "fox-albert",
  "FOX Amy": "fox-amy",
  "FOX Anna": "fox-anna",
  "FOX Ben": "fox-ben",
  "FOX Brian": "fox-brian",
  "FOX Brooke": "fox-brooke",
  "FOX Bylesley": "fox-bylesley",
  "FOX Cenarth": "fox-cenarth",
  "FOX Charles": "fox-charles",
  "FOX Dave": "fox-dave",
  "FOX Dian": "fox-dian",
  "FOX Diana": "fox-diana",
  "FOX Ellen": "fox-ellen",
  "FOX Gabrielle": "fox-gabrielle",
  "FOX Helena": "fox-helena",
  "FOX Jamie M": "fox-jamie-m",
  "FOX John": "fox-john",
  "FOX Josh": "fox-josh",
  "FOX Julian": "fox-julian",
  "FOX Karen": "fox-karen",
  "FOX Kate": "fox-kate",
  "FOX Krys": "fox-krys",
  "FOX Lawrence B": "fox-lawrence-b",
  "FOX Liam": "fox-liam",
  "FOX Loren": "fox-loren",
  "FOX Louise": "fox-louise",
  "FOX Maggie": "fox-maggie",
  "FOX Martin": "fox-martin",
  "FOX Matt": "fox-matt",
  "FOX Matthew Stanford": "fox-matthew-stanford",
  "FOX Michael": "fox-michael",
  "FOX Molly": "fox-molly",
  "FOX Paul Hervey": "fox-paul-hervey",
  "FOX Phil": "fox-phil",
  "FOX Ray Errol": "fox-ray-errol",
  "FOX Raymond": "fox-raymond",
  "FOX Robbie": "fox-robbie",
  "FOX Sam": "fox-sam",
  "FOX Skylar": "fox-skylar",
  "FOX Stephen": "fox-stephen",
  "FOX Steve": "fox-steve",
  "FOX Terry Curtis": "fox-terry-curtis",
  "FOX Tom": "fox-tom",
  "FOX W H": "fox-w-h",
  "FOXALL Vince": "foxall-vince",
  "FOX-HARTIN Sam": "fox-hartin-sam",
  "FOXSMITH Daniel": "foxsmith-daniel",
  "FOXTON David": "foxton-david",
  "FOXWELL Chris": "foxwell-chris",
  "FOXX Daniel": "foxx-daniel",
  "FOXY AND HUSK ": "foxy-and-husk",
  "FOY Douglas B": "foy-douglas-b",
  "FOYLE Naomi": "foyle-naomi",
  "FOYSTER Brian": "foyster-brian",
  "FRACHT J Albert": "fracht-j-albert",
  "FRADKIN Allison": "fradkin-allison",
  "FRADRICH James": "fradrich-james",
  "FRAGOLA Christina": "fragola-christina",
  "FRAHM Frederick": "frahm-frederick",
  "FRAISTAT Ann": "fraistat-ann",
  "FRAISTAT Shawn": "fraistat-shawn",
  "FRAKES Jack": "frakes-jack",
  "FRALEY Brian D": "fraley-brian-d",
  "FRALLER Larry": "fraller-larry",
  "FRAM Dori": "fram-dori",
  "FRAME Alen": "frame-alen",
  "FRAME Arthur": "frame-arthur",
  "FRAME Chet": "frame-chet",
  "FRAME Janet": "frame-janet",
  "FRAME Ronald": "frame-ronald",
  "FRAN WEN ": "fran-wen",
  "FRANCABVILLA Christine": "francabvilla-christine",
  "FRANCE Anna Kay": "france-anna-kay",
  "FRANCE Jane": "france-jane",
  "FRANCE Juliann": "france-juliann",
  "FRANCE Michelle": "france-michelle",
  "FRANCE Peter": "france-peter",
  "FRANCE Richard": "france-richard",
  "FRANCES Charlotte": "frances-charlotte",
  "FRANCES Ruth": "frances-ruth",
  "FRANCESCA Undine": "francesca-undine",
  "FRANCESCHETTI Antonio": "franceschetti-antonio",
  "FRANCESCHI Antonia": "franceschi-antonia",
  "FRANCESCHILD Donna": "franceschild-donna",
  "FRANCESCHINA John": "franceschina-john",
  "FRANCESCHINI Crystal": "franceschini-crystal",
  "FRANCESCHINI John": "franceschini-john",
  "FRANCES-WHITE Deborah": "frances-white-deborah",
  "FRANCIERE Arlette": "franciere-arlette",
  "FRANCIS Alan": "francis-alan",
  "FRANCIS Alasdair": "francis-alasdair",
  "FRANCIS Ann Margaret": "francis-ann-margaret",
  "FRANCIS Ashton": "francis-ashton",
  "FRANCIS Ben": "francis-ben",
  "FRANCIS Cara": "francis-cara",
  "FRANCIS Clive": "francis-clive",
  "FRANCIS David": "francis-david",
  "FRANCIS Diane": "francis-diane",
  "FRANCIS Dominic": "francis-dominic",
  "FRANCIS Gordon": "francis-gordon",
  "FRANCIS James": "francis-james",
  "FRANCIS Jane Lloyd": "francis-jane-lloyd",
  "FRANCIS Jason": "francis-jason",
  "FRANCIS John Oswald": "francis-john-oswald",
  "FRANCIS Juliana": "francis-juliana",
  "FRANCIS Kati": "francis-kati",
  "FRANCIS Marvin": "francis-marvin",
  "FRANCIS Mary": "francis-mary",
  "FRANCIS Matthew (1)": "francis-matthew-1",
  "FRANCIS Matthew (2)": "francis-matthew-2",
  "FRANCIS Maurice": "francis-maurice",
  "FRANCIS Paul": "francis-paul",
  "FRANCIS Robert J": "francis-robert-j",
  "FRANCIS Seseen": "francis-seseen",
  "FRANCIS Silvano Griffith": "francis-silvano-griffith",
  "FRANCIS Simon": "francis-simon",
  "FRANCIS Stephen": "francis-stephen",
  "FRANCIS Thais": "francis-thais",
  "FRANCIS Tom": "francis-tom",
  "FRANCIS William": "francis-william",
  "FRANCISCO Sam": "francisco-sam",
  "FRANCKE Caroline": "francke-caroline",
  "FRANCO Cris": "franco-cris",
  "FRANCO Henry": "franco-henry",
  "FRANCO Steve": "franco-steve",
  "FRANCOEUR Bill": "francoeur-bill",
  "FRANCOIS Kat": "francois-kat",
  "FRANCOUER Bill": "francouer-bill",
  "FRANDIN Stephen": "frandin-stephen",
  "FRANDSEN Carl": "frandsen-carl",
  "FRANDSEN Erik": "frandsen-erik",
  "FRANDSEN Kenn L D": "frandsen-kenn-l-d",
  "FRANGIONE Lucia": "frangione-lucia",
  "FRANGUI Leah": "frangui-leah",
  "FRANK Alicia": "frank-alicia",
  "FRANK Andrew": "frank-andrew",
  "FRANK Chandra": "frank-chandra",
  "FRANK Charles": "frank-charles",
  "FRANK Chris": "frank-chris",
  "FRANK Cynthia": "frank-cynthia",
  "FRANK D F": "frank-d-f",
  "FRANK Daniel B": "frank-daniel-b",
  "FRANK Dieter": "frank-dieter",
  "FRANK Doug": "frank-doug",
  "FRANK Glenda": "frank-glenda",
  "FRANK Jessica": "frank-jessica",
  "FRANK Joseph": "frank-joseph",
  "FRANK Josh": "frank-josh",
  "FRANK Karen Ilene": "frank-karen-ilene",
  "FRANK Mathew": "frank-mathew",
  "FRANK Melvin": "frank-melvin",
  "FRANK Miguel": "frank-miguel",
  "FRANK Nancy Cooper": "frank-nancy-cooper",
  "FRANK Raccoon": "frank-raccoon",
  "FRANK Scott": "frank-scott",
  "FRANK T S": "frank-t-s",
  "FRANKAU Ronald": "frankau-ronald",
  "FRANKCOM Sarah": "frankcom-sarah",
  "FRANKEL Doris": "frankel-doris",
  "FRANKEL Etan": "frankel-etan",
  "FRANKEL J P": "frankel-j-p",
  "FRANKEL Leland": "frankel-leland",
  "FRANKEL Robert": "frankel-robert",
  "FRANKEL Ron": "frankel-ron",
  "FRANKEL Scott": "frankel-scott",
  "FRANKEN Gerardine": "franken-gerardine",
  "FRANKEN Rose": "franken-rose",
  "FRANKENBURG Daniel": "frankenburg-daniel",
  "FRANKFURT Asher": "frankfurt-asher",
  "FRANKLAND Emma": "frankland-emma",
  "FRANKLAND John": "frankland-john",
  "FRANKLAND Richard": "frankland-richard",
  "FRANKLAND Tom": "frankland-tom",
  "FRANKLE Sophie": "frankle-sophie",
  "FRANKLIN Anita": "franklin-anita",
  "FRANKLIN Annie": "franklin-annie",
  "FRANKLIN Brian Lee": "franklin-brian-lee",
  "FRANKLIN Caroline Kelly": "franklin-caroline-kelly",
  "FRANKLIN Clarence": "franklin-clarence",
  "FRANKLIN Clay": "franklin-clay",
  "FRANKLIN David": "franklin-david",
  "FRANKLIN Edward": "franklin-edward",
  "FRANKLIN Elizabeth": "franklin-elizabeth",
  "FRANKLIN Harold": "franklin-harold",
  "FRANKLIN J E": "franklin-j-e",
  "FRANKLIN Jennifer": "franklin-jennifer",
  "FRANKLIN Josh": "franklin-josh",
  "FRANKLIN Mary": "franklin-mary",
  "FRANKLIN Miles": "franklin-miles",
  "FRANKLIN Nicco": "franklin-nicco",
  "FRANKLIN Richard": "franklin-richard",
  "FRANKLIN Sandra": "franklin-sandra",
  "FRANKLIN Tim": "franklin-tim",
  "FRANKLIN Will": "franklin-will",
  "FRANKLIN-YOUNG (AKA IFE) Gail F": "franklin-young-gail-f",
  "FRANKONIS W A": "frankonis-w-a",
  "FRANKOVICH Virginia": "frankovich-virginia",
  "FRANKS Alan": "franks-alan",
  "FRANKS Cynthia": "franks-cynthia",
  "FRANKS Jennie": "franks-jennie",
  "FRANKS Richard": "franks-richard",
  "FRANKSON David": "frankson-david",
  "FRANTIC ASSEMBLY ": "frantic-assembly",
  "FRANZEN Jonathan": "franzen-jonathan",
  "FRANZESE Daniel": "franzese-daniel",
  "FRANZMANN Vivienne": "franzmann-vivienne",
  "FRASER Alan": "fraser-alan",
  "FRASER Alister": "fraser-alister",
  "FRASER Antonia": "fraser-antonia",
  "FRASER Barbara Means": "fraser-barbara-means",
  "FRASER Brad": "fraser-brad",
  "FRASER Bruce": "fraser-bruce",
  "FRASER Dan": "fraser-dan",
  "FRASER David Gustav": "fraser-david-gustav",
  "FRASER Dennie Sullivan": "fraser-dennie-sullivan",
  "FRASER Donald": "fraser-donald",
  "FRASER Douglas": "fraser-douglas",
  "FRASER Flip": "fraser-flip",
  "FRASER Flora": "fraser-flora",
  "FRASER Gilly": "fraser-gilly",
  "FRASER Graham": "fraser-graham",
  "FRASER Grant": "fraser-grant",
  "FRASER Hadley": "fraser-hadley",
  "FRASER Helen": "fraser-helen",
  "FRASER Ian": "fraser-ian",
  "FRASER Isabella": "fraser-isabella",
  "FRASER Jennifer": "fraser-jennifer",
  "FRASER Jessica": "fraser-jessica",
  "FRASER John AD": "fraser-john-ad",
  "FRASER Jon": "fraser-jon",
  "FRASER Kon": "fraser-kon",
  "FRASER Malcolm": "fraser-malcolm",
  "FRASER Mat": "fraser-mat",
  "FRASER Michael": "fraser-michael",
  "FRASER Olive": "fraser-olive",
  "FRASER P": "fraser-p",
  "FRASER Patti": "fraser-patti",
  "FRASER Paul": "fraser-paul",
  "FRASER Prudence": "fraser-prudence",
  "FRASER Robert": "fraser-robert",
  "FRASER Sonia": "fraser-sonia",
  "FRASER Steven": "fraser-steven",
  "FRASER Theo": "fraser-theo",
  "FRASER Toa": "fraser-toa",
  "FRASER William": "fraser-william",
  "FRASER Zach": "fraser-zach",
  "FRASER Zannie": "fraser-zannie",
  "FRASER-MUNRO Ronald": "fraser-munro-ronald",
  "FRATER Scott": "frater-scott",
  "FRATICELLI Rina": "fraticelli-rina",
  "FRATTARE Tom": "frattare-tom",
  "FRATTI Mario": "fratti-mario",
  "FRATTINI Di": "frattini-di",
  "FRATUS Tiziano": "fratus-tiziano",
  "FRAVAL Antoine": "fraval-antoine",
  "FRAWLEY Malcolm": "frawley-malcolm",
  "FRAY Jacques": "fray-jacques",
  "FRAYN Alan": "frayn-alan",
  "FRAYN Michael": "frayn-michael",
  "FRAZAO Joana": "frazao-joana",
  "FRAZAO Leticia": "frazao-leticia",
  "FRAZER Jenny": "frazer-jenny",
  "FRAZER Kon": "frazer-kon",
  "FRAZER Ronald": "frazer-ronald",
  "FRAZIER Hank": "frazier-hank",
  "FRAZIER Kati": "frazier-kati",
  "FRAZIER Kermit": "frazier-kermit",
  "FRAZIER JR Levi": "frazier-jr-levi",
  "FREAKSHOW ": "freakshow",
  "FRECHETTE Carole": "frechette-carol",
  "FRECHTMAN Bernard": "frechtman-bernard",
  "FREDA Jon": "freda-jon",
  "FREDEN Sofia": "freden-sofia",
  "FREDERICK David": "frederick-david",
  "FREDERICK Ifeyinwa": "frederick-ifeyinwa",
  "FREDERICK Jack": "frederick-jack",
  "FREDERICK HENDRICKS YOUTH ENSEMBLE OF ATLANTA ": "frederick-hendricks-youth-ensemble-of-atlanta",
  "FREDERICKS Claude": "fredericks-claude",
  "FREDERICKSON Christine M": "frederickson-christine-m",
  "FREDERICKSON David": "frederickson-david",
  "FREDMAN Richard": "fredman-richard",
  "FREDO John": "fredo-john",
  "FREDRIC Barnaby": "fredric-barnaby",
  "FREDRICK Judith": "fredrick-judith",
  "FREDRICKS Katherine Brann": "fredricks-katherine-brann",
  "FREDRICKSSON Kristin": "fredricksson-kristin",
  "FREDRO Aleksander": "fredro-aleksander",
  "FREE Alana Ruben": "free-alana-ruben",
  "FREE Colin": "free-colin",
  "FREE Kevin R": "free-kevin-r",
  "FREE Richard": "free-richard",
  "FREE Scott": "free-scott",
  "FREE SOUTHERN THEATRE ": "free-southern-theatre",
  "FREE STREET THEATER ENSEMBLE ": "free-street-theater-ensemble",
  "FREEBERG Debra L": "freeberg-debra-l",
  "FREEBURG Erin Alyssa": "freeburg-erin-alyssa",
  "FREED Amy": "freed-amy",
  "FREED Arthur": "freed-arthur",
  "FREED Donald": "freed-donald",
  "FREED Jenna Lauren": "freed-jenna-lauren",
  "FREED John": "freed-john",
  "FREED Judy": "freed-judy",
  "FREED Paul": "freed-paul",
  "FREEDMAN Ben": "freedman-ben",
  "FREEDMAN Colette": "freedman-colette",
  "FREEDMAN Gerald": "freedman-gerald",
  "FREEDMAN Harris W": "freedman-harris-w",
  "FREEDMAN John": "freedman-john",
  "FREEDMAN Max": "freedman-max",
  "FREEDMAN Philip": "freedman-philip",
  "FREEDMAN Rachel": "freedman-rachel",
  "FREEDMAN Robert L": "freedman-robert-l",
  "FREEDMAN Sylvia": "freedman-sylvia",
  "FREEDOM THEATRE ": "freedom-theatre",
  "FREEK George": "freek-george",
  "FREELAND Benjamin": "freeland-benjamin",
  "FREEMAN Aaron": "freeman-aaron",
  "FREEMAN Alan": "freeman-alan",
  "FREEMAN Brian": "freeman-brian",
  "FREEMAN Bud": "freeman-bud",
  "FREEMAN Carol": "freeman-carol",
  "FREEMAN Charles K": "freeman-charles-k",
  "FREEMAN Cyndi": "freeman-cyndi",
  "FREEMAN Dan": "freeman-dan",
  "FREEMAN Dave": "freeman-dave",
  "FREEMAN David": "freeman-david",
  "FREEMAN David (1)": "freeman-david-1",
  "FREEMAN David (2)": "freeman-david-2",
  "FREEMAN David E": "freeman-david-e",
  "FREEMAN Deborah": "freeman-deborah",
  "FREEMAN Dexter": "freeman-dexter",
  "FREEMAN Edward": "freeman-edward",
  "FREEMAN Elena": "freeman-elena",
  "FREEMAN Emily": "freeman-emily",
  "FREEMAN Everett": "freeman-everett",
  "FREEMAN Greg": "freeman-greg",
  "FREEMAN Jackie": "freeman-jackie",
  "FREEMAN Joanne": "freeman-joanne",
  "FREEMAN Jonathan Marshall": "freeman-jonathan-marshall",
  "FREEMAN Leayne": "freeman-leayne",
  "FREEMAN Lee": "freeman-lee",
  "FREEMAN Lucy": "freeman-lucy",
  "FREEMAN Maree": "freeman-maree",
  "FREEMAN Matt": "freeman-matt",
  "FREEMAN Matthew": "freeman-matthew",
  "FREEMAN Michael": "freeman-michael",
  "FREEMAN Nathan Ross": "freeman-nathan-ross",
  "FREEMAN Neal": "freeman-neal",
  "FREEMAN Papi Kymone": "freeman-papi-kymone",
  "FREEMAN Polly": "freeman-polly",
  "FREEMAN Sam": "freeman-sam",
  "FREEMAN Sam H": "freeman-sam-h",
  "FREEMAN Sandra": "freeman-sandra",
  "FREEMAN Scott": "freeman-scott",
  "FREEMAN Seth": "freeman-seth",
  "FREEMAN Stan": "freeman-stan",
  "FREEMAN Ted": "freeman-ted",
  "FREEMAN-SAYER Philip": "freeman-sayer-philip",
  "FREENAN Declan": "freenan-declan",
  "FREESE Ross": "freese-ross",
  "FREESON Jeremy": "freeson-jeremy",
  "FREESTONE Alan": "freestone-alan",
  "FREESTONE Elizabeth": "freestone-elizabeth",
  "FREI Nicki": "frei-nicki",
  "FREIBACH Shir": "freibach-shir",
  "FREIBERGER Jack 'Fry'": "freiberger-jack",
  "FREIBURG Johanna": "freiburg-johanna",
  "FREIDERICI Kathy": "freiderici-kathy",
  "FREIDLICH Max W": "freidlich-max-w",
  "FREIER Greg": "freier-greg",
  "FREIJ Julien": "freij-julien",
  "FREILICH Josh": "freilich-josh",
  "FREIMAN Lexi": "freiman-lexi",
  "FREIMAN Louis": "freiman-louis",
  "FREISTADT Berta": "freistadt-berta",
  "FREMI Edith": "fremi-edith",
  "FRENCH Amy": "french-amy",
  "FRENCH Arthur W": "french-arthur-w",
  "FRENCH David": "french-david",
  "FRENCH Dawn": "french-dawn",
  "FRENCH Jack": "french-jack",
  "FRENCH Judith": "french-judith",
  "FRENCH Lorna": "french-lorna",
  "FRENCH Michael": "french-michael",
  "FRENCH Patti": "french-patti",
  "FRENCH Robin": "french-robin",
  "FRENCH Sam": "french-sam",
  "FRENCH Samuel": "french-samuel",
  "FRENCH Segun Lee": "french-segun-lee",
  "FRENCH Timothy": "french-timothy",
  "FRENCH Vivian": "french-vivian",
  "FRENCH III Arthur W": "french-iii-arthur-w",
  "FRENI Edith": "freni-edith",
  "FRENI Nicole": "freni-nicole",
  "FRENKIEL Nevil": "frenkiel-nevil",
  "FRENZ Horst": "frenz-horst",
  "FRERE Jane": "frere-jane",
  "FRERICHS Sue": "frerichs-sue",
  "FRESCO Dylan": "fresco-dylan",
  "FRESCO TC ": "fresco-tc",
  "FRESSON Jeremy": "fresson-jeremy",
  "FREUND Anne": "freund-anne",
  "FREUND Philip": "freund-philip",
  "FREUNDT Michael": "freundt-michael",
  "FREWEN Arthur": "frewen-arthur",
  "FREY L W": "frey-l-w",
  "FREY Robert Irviing": "frey-robert-irviing",
  "FREYER Frederick Q": "freyer-frederick-q",
  "FREYMAN Jay": "freyman-jay",
  "FREZZA Marco": "frezza-marco",
  "FRIAR Kimon": "friar-kimon",
  "FRIBOURG Stephanie": "fribourg-stephanie",
  "FRICK Nancy": "frick-nancy",
  "FRICKER John": "fricker-john",
  "FRID Catherine": "frid-catherine",
  "FRIDEN Chris": "friden-chris",
  "FRIED Adam": "fried-adam",
  "FRIED Barbara": "fried-barbara",
  "FRIED Don": "fried-don",
  "FRIED Emanuel": "fried-emanuel",
  "FRIED Gerald": "fried-gerald",
  "FRIED Stephen": "fried-stephen",
  "FRIEDBERG William": "friedberg-william",
  "FRIEDEL Sarah": "friedel-sarah",
  "FRIEDENN Neva": "friedenn-neva",
  "FRIEDKIN Jenirose": "friedkin-jenirose",
  "FRIEDLAND Dahlia": "friedland-dahlia",
  "FRIEDMAN Alan Foster": "friedman-alan-foster",
  "FRIEDMAN Allan Jay": "friedman-allan-jay",
  "FRIEDMAN Bobby": "friedman-bobby",
  "FRIEDMAN Brad": "friedman-brad",
  "FRIEDMAN Bruce Jay": "friedman-bruce-jay",
  "FRIEDMAN Dan": "friedman-dan",
  "FRIEDMAN E Fisher": "friedman-e-fisher",
  "FRIEDMAN Edward": "friedman-edward",
  "FRIEDMAN Esther": "friedman-esther",
  "FRIEDMAN Eve": "friedman-eve",
  "FRIEDMAN Gary William": "friedman-gary-william",
  "FRIEDMAN Hannah": "friedman-hannah",
  "FRIEDMAN Jena": "friedman-jena",
  "FRIEDMAN Joel P": "friedman-joel-p",
  "FRIEDMAN Josh Ben": "friedman-josh-ben",
  "FRIEDMAN Karl": "friedman-karl",
  "FRIEDMAN Ken": "friedman-ken",
  "FRIEDMAN Leon": "friedman-leon",
  "FRIEDMAN Maria": "friedman-maria",
  "FRIEDMAN Mark": "friedman-mark",
  "FRIEDMAN Meridith": "friedman-meridith",
  "FRIEDMAN Michael": "friedman-michael",
  "FRIEDMAN Philip": "friedman-philip",
  "FRIEDMAN Robert Marc": "friedman-robert-marc",
  "FRIEDMAN Rosalind": "friedman-rosalind",
  "FRIEDMAN Rosemary": "friedman-rosemary",
  "FRIEDMAN Roy": "friedman-roy",
  "FRIEDMAN Seth": "friedman-seth",
  "FRIEDMAN Sheldon E": "friedman-sheldon-e",
  "FRIEDMAN Sherry": "friedman-sherry",
  "FRIEDMAN Steve": "friedman-steve",
  "FRIEDMAN Tracy": "friedman-tracy",
  "FRIEDMAN Zach": "friedman-zach",
  "FRIEDMAN Zack": "friedman-zack",
  "FRIEDRICH Nancy": "friedrich-nancy",
  "FRIEDRICHITHOSAS Jorg": "friedrichithosas-jorg",
  "FRIEL Brian": "friel-brian",
  "FRIEL George": "friel-george",
  "FRIEL Michael": "friel-michael",
  "FRIELBACH Shir": "frielbach-shir",
  "FRIEND Cassie": "friend-cassie",
  "FRIEND David": "friend-david",
  "FRIEND Michael": "friend-michael",
  "FRIEND Rick": "friend-rick",
  "FRIEND Simon": "friend-simon",
  "FRIERSON Andrea": "frierson-andrea",
  "FRIERSON Eddie": "frierson-eddie",
  "FRIERSON-TONEY Andrea": "frierson-toney-andrea",
  "FRIES Kenny": "fries-kenny",
  "FRIESEN Patrick": "friesen-patrick",
  "FRINGS Ketti": "frings-ketti",
  "FRINK Charles": "frink-charles",
  "FRINKE David": "frinke-david",
  "FRISBY Terence": "frisby-terence",
  "FRISCH Max": "frisch-max",
  "FRISCH Peter": "frisch-peter",
  "FRISCH Robert": "frisch-robert",
  "FRISHBERG Dave": "frishberg-dave",
  "FRISINO-TOOHEY Rosemary": "frisino-toohey-rosemary",
  "FRITH Bob": "frith-bob",
  "FRITH Daniel": "frith-daniel",
  "FRITH Roger": "frith-roger",
  "FRITH Tim": "frith-tim",
  "FRITSCH Werner": "fritsch-werner",
  "FRITSCHER Jack": "fritscher-jack",
  "FRITTS Tamara": "fritts-tamara",
  "FRITZ James": "fritz-james",
  "FRITZ John": "fritz-john",
  "FRITZ Joni": "fritz-joni",
  "FRITZIUS Eric": "fritzius-eric",
  "FRITZLER Jim": "fritzler-jim",
  "FROBERG Kristin Anna": "froberg-kristin-anna",
  "FROCHARDE Pierre": "frocharde-pierre",
  "FROCKT Deborah Lynn": "frockt-deborah-lynn",
  "FROEHLING Simon": "froehling-simon",
  "FROELICH Anne": "froelich-anne",
  "FROHARDT Robin": "frohardt-robin",
  "FROHLICH Pea": "frohlich-pea",
  "FROIDEVAUX Guillaumarc": "froidevaux-guillaumarc",
  "FROLOV Diane": "frolov-diane",
  "FROM THE STREET THEATRE COMPANY ": "from-the-street-theatre-company",
  "FROMSTEIN Ron": "fromstein-ron",
  "FRONT Jeremy": "front-jeremy",
  "FRONT LAWN, THE ": "front-lawn",
  "FRONT ROW THEATRE GROUP ": "front-row-theatre-group",
  "FROST Christopher": "frost-christopher",
  "FROST Cy": "frost-cy",
  "FROST Danny": "frost-danny",
  "FROST Emma": "frost-emma",
  "FROST Gina T": "frost-gina-t",
  "FROST Helen": "frost-helen",
  "FROST James": "frost-james",
  "FROST Joseph": "frost-joseph",
  "FROST Rex": "frost-rex",
  "FROST Rich": "frost-rich",
  "FROST Richard": "frost-richard",
  "FROST Robert": "frost-robert",
  "FROST Sadie": "frost-sadie",
  "FROST Shari D": "frost-shari-d",
  "FROST Warren": "frost-warren",
  "FROSTICK David": "frostick-david",
  "FROTE Jason": "frote-jason",
  "FROW Gerald": "frow-gerald",
  "FROZEN CHARLOTTE ": "frozen-charlotte",
  "FROZEN LIGHT ": "frozen-light",
  "FRUCHTMAN Stephen Michael": "fruchtman-stephen-michael",
  "FRUET William": "fruet-william",
  "FRUGE Wesley": "fruge-wesley",
  "FRUMIN Sue": "frumin-sue",
  "FRUTKIN Jill": "frutkin-jill",
  "FRY Christopher": "fry-christopher",
  "FRY Garry": "fry-garry",
  "FRY Jack": "fry-jack",
  "FRY Katie": "fry-katie",
  "FRY Michael": "fry-michael",
  "FRY Ray": "fry-ray",
  "FRY Richard": "fry-richard",
  "FRY Stephen": "fry-stephen",
  "FRY William": "fry-william",
  "FRY JR Gary Raymond": "fry-jr-gary-raymond",
  "FRYE Andrew": "frye-andrew",
  "FRYE Joy Beresford": "frye-joy-beresford",
  "FRYE Peter": "frye-peter",
  "FRYE Tom": "frye-tom",
  "FRYER Nick": "fryer-nick",
  "FU Josh": "fu-josh",
  "FUCHS Barbara": "fuchs-barbara",
  "FUCHS Carolyn": "fuchs-carolyn",
  "FUCHS Elinor": "fuchs-elinor",
  "FUCHS Francis": "fuchs-francis",
  "FUCHS Howard": "fuchs-howard",
  "FUCHS Ira Hayes": "fuchs-ira-hayes",
  "FUCHS Kenneth": "fuchs-kenneth",
  "FUCHS Siegmund": "fuchs-siegmund",
  "FUCILLA Joseph G": "fucilla-joseph-g",
  "FUDGE Anthony": "fudge-anthony",
  "FUEMANA Dianna": "fuemana-dianna",
  "FUENTES Carlos": "fuentes-carlos",
  "FUENTES Elizabeth": "fuentes-elizabeth",
  "FUENTES Martha Ayers": "fuentes-martha-ayers",
  "FUENTES Pablo": "fuentes-pablo",
  "FUENTES Susana": "fuentes-susana",
  "FUERSTENBERG Anna": "fuerstenberg-anna",
  "FUGARD Athol": "fugard-athol",
  "FUGATE James": "fugate-james",
  "FUGELSANG John": "fugelsang-john",
  "FUHER Kent": "fuher-kent",
  "FUHRER Gil": "fuhrer-gil",
  "FUJIKAWA Cynthia Gates": "fujikawa-cynthia-gates",
  "FUJIMOTO Paul": "fujimoto-paul",
  "FULCO David": "fulco-david",
  "FULCO Richard": "fulco-richard",
  "FULFORD Geoff": "fulford-geoff",
  "FULFORD John": "fulford-john",
  "FULFORD Robin": "fulford-robin",
  "FULGHUM Robert": "fulghum-robert",
  "FULHAM Mary": "fulham-mary",
  "FULKERTON Vance": "fulkerton-vance",
  "FULKS Amanda": "fulks-amanda",
  "FULKS Kadence": "fulks-kadence",
  "FULL FRONTAL THEATRE ": "full-frontal-theatre",
  "FULLARTON Morag": "fullarton-morag",
  "FULLER Charles": "fuller-charles",
  "FULLER David": "fuller-david",
  "FULLER David Gillam": "fuller-david-gillam",
  "FULLER Dean": "fuller-dean",
  "FULLER Elizabeth": "fuller-elizabeth",
  "FULLER Emily": "fuller-emily",
  "FULLER Frat": "fuller-frat",
  "FULLER Frit": "fuller-frit",
  "FULLER James": "fuller-james",
  "FULLER John G": "fuller-john-g",
  "FULLER Julie": "fuller-julie",
  "FULLER Katherine": "fuller-katherine",
  "FULLER Lorenzo": "fuller-lorenzo",
  "FULLER Sarah": "fuller-sarah",
  "FULLER Ted": "fuller-ted",
  "FULLERTON Morag": "fullerton-morag",
  "FULTHORPE Douglas": "fulthorpe-douglas",
  "FULTON Andrea J": "fulton-andrea-j",
  "FULTON Heather": "fulton-heather",
  "FULTON J M": "fulton-j-m",
  "FULTON Rikki": "fulton-rikki",
  "FULTON Will": "fulton-will",
  "FUMMEY Bruce": "fummey-bruce",
  "FUNG Josef": "fung-josef",
  "FUNG Rocelia": "fung-rocelia",
  "FURA DELS BAUS ": "fura-dels-baus",
  "FURBER Douglas": "furber-douglas",
  "FUREY Cate": "furey-cate",
  "FURLANI Jason": "furlani-jason",
  "FURLETTI Andressa": "furletti-andressa",
  "FURLONG David": "furlong-david",
  "FURLONG Ingrid": "furlong-ingrid",
  "FURLONG Tony": "furlong-tony",
  "FURMAN Roger": "furman-roger",
  "FURNELL John": "furnell-john",
  "FURNESS Mark": "furness-mark",
  "FURNISS Darren A": "furniss-darren-a",
  "FURNIVAL Christine": "furnival-christine",
  "FURSE Anna": "furse-anna",
  "FURSE John": "furse-john",
  "FURST Gretchen Klinedinst": "furst-gretchen-klinedinst",
  "FURST Joshua": "furst-joshua",
  "FURST Steve": "furst-steve",
  "FURTH George": "furth-george",
  "FURUMOTO David": "furumoto-david",
  "FUSARO Darrell": "fusaro-darrell",
  "FUSCO Anthony": "fusco-anthony",
  "FUSCO Coco": "fusco-coco",
  "FUSCO Robin": "fusco-robin",
  "FUSE THEATRE ": "fuse-theatre",
  "FUSEK-PETERS Andrew": "fusek-peters-andrew",
  "FUTCHER Michael": "futcher-michael",
  "FUTTERMAN Enid": "futterman-enid",
  "FYFE Jim": "fyfe-jim",
  "FYFE Peter": "fyfe-peter",
  "FYFFE Laurie": "fyffe-laurie",
  "FYLAKTAKI Penny": "fylaktaki-penny",
  "FYLEMAN Rose": "fyleman-rose",
  "FYLES Franklin": "fyles-franklin",
  "FYNN-AIDUENU Tristan": "fynn-aiduenu-tristan",
  "FYSA THEATRE ": "fysa-theatre",
  "FYWELL Tim": "fywell-tim",
};
