export default {
  "IACOZILLI Fabbiana": "iacozilli-fabbiana",
  "IACUCCI Carlo": "iacucci-carlo",
  "IANIRO Michelle": "ianiro-michelle",
  "IANNIELLO Antonio": "ianniello-antonio",
  "IANNUCCI Ammando": "iannucci-ammando",
  "IANNUZZI Dana A": "iannuzzi-dana-a",
  "IAOU Julius Amedee": "iaou-julius-amedee",
  "IASIELLO Emilio": "iasiello-emilio",
  "IBARGUENGOITIA Jorge": "ibarguengoitia-jorge",
  "IBBITSON John": "ibbitson-john",
  "IBERALL Helene": "iberall-helene",
  "IBERALL Thea": "iberall-thea",
  "IBEY Paul": "ibey-paul",
  "IBINI Matilda": "ibini-matilda",
  "IBRAGIMBEKOV Rustam": "ibragimbekov-rustam",
  "IBRAHIM Dina": "ibrahim-dina",
  "IBRAHIM George": "ibrahim-george",
  "IBRAHIM Omar": "ibrahim-omar",
  "IBRAHIM Sami": "ibrahim-sami",
  "IBRIHIM Khadija": "ibrihim-khadija",
  "IBSEN Henrik": "ibsen-henrik",
  "IBU Natalie": "ibu-natalie",
  "ICENHOWER E Scott": "icenhower-e-scott",
  "ICKE Robert": "icke-robert",
  "ICON THEATRE ": "icon-theatre",
  "ICONIS Joe": "iconis-joe",
  "IDA Endesha": "ida-endesha",
  "IDASZAK Kristin": "idaszak-kristin",
  "IDE Shigehiro": "ide-shigehiro",
  "IDES IsabElla Russell": "ides-isabella-russell",
  "IDLE Eric": "idle-eric",
  "IDLE MOTION ": "idle-motion",
  "IERARDI Robert": "ierardi-robert",
  "IF PERFORMANCE COLLECTIVE ": "if-performance-collective",
  "IFFLAND August Wilhelm": "iffland-august-wilhelm",
  "IFOPO Erolia": "ifopo-erolia",
  "IGER Arnold": "iger-arnold",
  "IGGULDEN Hal": "iggulden-hal",
  "IGNACIO Cynthia Q": "ignacio-cynthia-q",
  "IGNACIO Jose": "ignacio-jose",
  "IGNAS Lorelei": "ignas-lorelei",
  "IGNITE THEATRE ": "ignite-theatre",
  "IGOE Ben": "igoe-ben",
  "IGREJAS Manuel": "igrejas-manuel",
  "IGUH Thomas": "iguh-thomas",
  "IHIMAERA Witi": "ihimaera-witi",
  "IIZUKA Naomi": "iizuka-naomi",
  "IJAMES James": "ijames-james",
  "IJIMERE O": "ijimere-o",
  "IKAHEIMONEN-LINDGREN Silja": "ikaheimonen-lindgren-silja",
  "IKEDA John": "ikeda-john",
  "IKEUCHI Mansaku": "ikeuchi-mansaku",
  "IKO Momoko": "iko-momoko",
  "IKOKO Theresa": "ikoko-theresa",
  "IKOLI Tunde": "ikoli-tunde",
  "IKUMELO Gbemisola": "ikumelo-gbemisola",
  "ILAND Paula": "iland-paula",
  "ILBIJERRI THEATRE COMPANY ": "ilbijerri-theatre-company",
  "ILDAN Mehmet Murat": "ildan-mehmet-murat",
  "ILES Robert": "iles-robert",
  "ILGENFRITZ Pedro": "ilgenfritz-pedro",
  "ILIEV Konstantin": "iliev-konstantin",
  "ILIFFE David": "iliffe-david",
  "ILIFFE Roy": "iliffe-roy",
  "ILIKA Aaron J": "ilika-aaron-j",
  "ILLEGITIMATE PLAYERS, THE ": "illegitimate-players",
  "ILLIATOVITCH-GOLDMAN Sarah": "illiatovitch-goldman-sarah",
  "ILLICK Hilary": "illick-hilary",
  "ILLIS Mark": "illis-mark",
  "ILLOPOULOS George": "illopoulos-george",
  "ILOTT Craig": "ilott-craig",
  "ILSON Saul": "ilson-saul",
  "ILYASOVA Alla": "ilyasova-alla",
  "IMA Kim": "ima-kim",
  "IMAGINARY PEOPLE, THE ": "imaginary-people",
  "IMAI Masayuki": "imai-masayuki",
  "IMAN Yusef": "iman-yusef",
  "IMBODEN Christian": "imboden-christian",
  "IMBRIE Mccrae": "imbrie-mccrae",
  "IMBRIE Timothy": "imbrie-timothy",
  "IMFURST Mimi": "imfurst-mimi",
  "IMIELSKI Michal": "imielski-michal",
  "IMITATING THE DOG ": "imitating-the-dog",
  "IMLAY James": "imlay-james",
  "IMMS Peter": "imms-peter",
  "IMPERFECT PICTURES ": "imperfect-pictures",
  "IMPERIAL Dean": "imperial-dean",
  "IMPROBABLE THEATRE ": "improbable-theatre",
  "IMPROVISED THEATRE ": "improvised-theatre",
  "IMPROVISORS, THE ": "improvisors-the",
  "IN TRIPLICATE ": "in-triplicate",
  "INAD THEATRE COMPANY ": "inad-theatre-company",
  "INCAVO Jeff": "incavo-jeff",
  "INCE Caitlin": "ince-caitlin",
  "INCE James": "ince-james",
  "INCE Karen": "ince-karen",
  "INCROCCI Uma": "incrocci-uma",
  "INDEFINITE ARTICLES ": "indefinite-articles",
  "INDIANA Gary": "indiana-gary",
  "INDIANOS Elizabeth": "indianos-elizabeth",
  "INDOMITABLE IMPOSTER ": "indomitable-imposter",
  "INES Deborah A": "ines-deborah-a",
  "INFANTINO Lindsay": "infantino-lindsay",
  "INGALLS Jeremy": "ingalls-jeremy",
  "INGBER David": "ingber-david",
  "INGBER Hillary": "ingber-hillary",
  "INGE William": "inge-william",
  "INGEBORG Gertraud": "ingeborg-gertraud",
  "INGELBRECHT Suzanne": "ingelbrecht-suzanne",
  "INGERSON Martin": "ingerson-martin",
  "INGHAM Anna": "ingham-anna",
  "INGHAM Richard": "ingham-richard",
  "INGHAM Robert": "ingham-robert",
  "INGHAM William": "ingham-william",
  "INGIMARSSON Kristjan": "ingimarsson-kristjan",
  "INGLE Roisin": "ingle-roisin",
  "INGLEDEW David": "ingledew-david",
  "INGLETON Sue": "ingleton-sue",
  "INGLIS Andrea": "inglis-andrea",
  "INGLIS Daizie": "inglis-daizie",
  "INGLIS Rob": "inglis-rob",
  "INGOLD Jon": "ingold-jon",
  "INGOLDSBY Maeve": "ingoldsby-maeve",
  "INGOLDSBY Pat": "ingoldsby-pat",
  "INGRAFFI Sam": "ingraffi-sam",
  "INGRAHAM Elizabeth": "ingraham-elizabeth",
  "INGRAM Brettcardie": "ingram-brettcardie",
  "INGRAM F A": "ingram-f-a",
  "INGRAM James": "ingram-james",
  "INGRAM Joan": "ingram-joan",
  "INGRAMS Richard": "ingrams-richard",
  "INGRASCIOTTA Frank": "ingrasciotta-frank",
  "INGRASSIA Anthony": "ingrassia-anthony",
  "INGS Welby": "ings-welby",
  "INGULSRUD Leon": "ingulsrud-leon",
  "INHOON Che": "inhoon-che",
  "INKFISH ": "inkfish",
  "INLENDER Avraham": "inlender-avraham",
  "INMAN James": "inman-james",
  "INMAN Jim": "inman-jim",
  "INMAN Robert": "inman-robert",
  "INNAURATO Albert": "innaurato-albert",
  "INNEO Anthony": "inneo-anthony",
  "INNER PRINCESS ": "inner-princess",
  "INNES Gavin J": "innes-gavin-j",
  "INNES Molly": "innes-molly",
  "INNES Neil": "innes-neil",
  "INNES Peggy": "innes-peggy",
  "INNISS Michelle": "inniss-michelle",
  "INNOCENTI Giulia": "innocenti-giulia",
  "INNUINUIT THEATRE CO NALUJUK PLAYERS ": "innuinuit-theatre-co-nalujuk-players",
  "INOUE Hisashi": "inoue-hisashi",
  "INOUYE Lisa Toishigawa": "inouye-lisa-toishigawa",
  "INSOMNIAC PRODUCTIONS ": "insomniac-productions",
  "INSPECTOR SANDS ": "inspector-sands",
  "INSTANT CLASSICS ": "instant-classics",
  "INSTITUTE, THE ": "institute",
  "INSTON Robert": "inston-robert",
  "INSTONE Alfred": "instone-alfred",
  "INSUA Juan": "insua-juan",
  "INTRABARTOLO Damon": "intrabartolo-damon",
  "INTRAVIA Tim": "intravia-tim",
  "INTROCASO John C": "introcaso-john-c",
  "INTRODANS ENSEMBLE FOR YOUTH ": "introdans-ensemble-for-youth",
  "INTRONATI, THE ": "intronati",
  "IOAN Gareth": "ioan-gareth",
  "IOANNOU Lucy": "ioannou-lucy",
  "IOGNA Luciano": "iogna-luciano",
  "IOMHA ILDANACH ": "iomha-ildanach",
  "ION Vera": "ion-vera",
  "IONESCO Eugene": "ionesco-eugene",
  "IONESCO Marie-France": "ionesco-marie-france",
  "IONESCU Ion": "ionescu-ion",
  "IORDANOVA Elissaveta": "iordanova-elissaveta",
  "IOSIFESCU Mark": "iosifescu-mark",
  "IOTA ": "iota",
  "IOU THEATRE ": "iou-theatre",
  "IOVINO Brenda": "iovino-brenda",
  "IPPOLITO David": "ippolito-david",
  "IPSEN Carlotta": "ipsen-carlotta",
  "IRANI Anosh": "irani-anosh",
  "IRANI Kayhan": "irani-kayhan",
  "IRCINK Jeffrey James": "ircink-jeffrey-james",
  "IREDALE Jane": "iredale-jane",
  "IREDYNSKI Ireneusz": "iredynski-ireneusz",
  "IRELAND David": "ireland-david",
  "IRELAND David (1)": "ireland-david-1",
  "IRELAND John": "ireland-john",
  "IRELAND Kenny": "ireland-kenny",
  "IRELAND Stanley": "ireland-stanley",
  "IRELAND Vicky": "ireland-vicky",
  "IRELAND-REEVES Dan": "ireland-reeves-dan",
  "IRENE Maria": "irene-maria",
  "IRESON Richard": "ireson-richard",
  "IRETON Catherine": "ireton-catherine",
  "IREY Mary": "irey-mary",
  "IRGLOVA Marketa": "irglova-marketa",
  "IRIBARNE Louis": "iribarne-louis",
  "IRIGUCHI Mamoru": "iriguchi-mamoru",
  "IRION Nicholas Dean": "irion-nicholas-dean",
  "IRISH Gemma": "irish-gemma",
  "IRIZARRY Daniel": "irizarry-daniel",
  "IRIZARRY Richard": "irizarry-richard",
  "IRNAN Kasisi Yusef": "irnan-kasisi-yusef",
  "IRONDALE ENSEMBLE ": "irondale-ensemble",
  "IRONDUKE ": "ironduke",
  "IRONS Andrew": "irons-andrew",
  "IRONS Creighton Manning": "irons-creighton-manning",
  "IRONS David": "irons-david",
  "IRONSIDE Lewis": "ironside-lewis",
  "IRONSIDE Louisa": "ironside-louisa",
  "IRONSIDE Virginia": "ironside-virginia",
  "IRVIN J": "irvin-j",
  "IRVINE Anne": "irvine-anne",
  "IRVINE Barbara": "irvine-barbara",
  "IRVINE Dougal": "irvine-dougal",
  "IRVINE Douglas": "irvine-douglas",
  "IRVINE Will": "irvine-will",
  "IRVING George S": "irving-george-s",
  "IRVING Lee": "irving-lee",
  "IRVING Michael": "irving-michael",
  "IRVING Todd": "irving-todd",
  "IRVING Vaughn": "irving-vaughn",
  "IRVIS Erick": "irvis-erick",
  "IRVWN Will": "irvwn-will",
  "IRWIN Bill": "irwin-bill",
  "IRWIN Elizabeth": "irwin-elizabeth",
  "IRWIN Janet": "irwin-janet",
  "IRWIN Leonard": "irwin-leonard",
  "IRWIN Louis": "irwin-louis",
  "IRWIN Shari": "irwin-shari",
  "IRWIN Tamsin": "irwin-tamsin",
  "IRWIN Vera Rushforth": "irwin-vera-rushforth",
  "IRWIN Will": "irwin-will",
  "ISAAC Alberto": "isaac-alberto",
  "ISAAC Salio": "isaac-salio",
  "ISAACS Chris": "isaacs-chris",
  "ISAACS David": "isaacs-david",
  "ISAACS Herb": "isaacs-herb",
  "ISAACS Jerry": "isaacs-jerry",
  "ISAACS Naomi Karz": "isaacs-naomi-karz",
  "ISAACS Philip M": "isaacs-philip-m",
  "ISAACSON David": "isaacson-david",
  "ISAAK Isaak Esmail": "isaak-isaak-esmail",
  "ISAKSEN Ike": "isaksen-ike",
  "ISAROV Boris": "isarov-boris",
  "ISBELL John": "isbell-john",
  "ISBELL Tom": "isbell-tom",
  "ISCOVITZ Stephanie": "iscovitz-stephanie",
  "ISEMAN Jim": "iseman-jim",
  "ISEN Richard": "isen-richard",
  "ISENHOUR Thomas L": "isenhour-thomas-l",
  "ISHEE Suzanne": "ishee-suzanne",
  "ISHERWOOD Christopher": "isherwood-christopher",
  "ISHIGURO Kazuo": "ishiguro-kazuo",
  "ISHII Leslie": "ishii-leslie",
  "ISIS ": "isis",
  "ISITT Debbie": "isitt-debbie",
  "ISKANDER Helen": "iskander-helen",
  "ISKANDER Tarek": "iskander-tarek",
  "ISKAYEV E": "iskayev-e",
  "ISLE Mike": "isle-mike",
  "ISLER Seth": "isler-seth",
  "ISLEY Edwin L": "isley-edwin-l",
  "ISLINGTON YOUTH THEATRE ": "islington-youth-theatre",
  "ISOM Stacey": "isom-stacey",
  "ISOMAKI Mikko": "isomaki-mikko",
  "ISQUITH Betty Jane": "isquith-betty-jane",
  "ISRAEL Daniel Evan": "israel-daniel-evan",
  "ISRAEL Gissa G": "israel-gissa-g",
  "ISRAEL Henry": "israel-henry",
  "ISRAEL Joel": "israel-joel",
  "ISRAEL Sara": "israel-sara",
  "ISRAEL Steve Ben": "israel-steve-ben",
  "ISRAELI Henry": "israeli-henry",
  "ISRAELY Razia": "israely-razia",
  "ISREAL Sarah": "isreal-sarah",
  "ISSAK I E": "issak-i-e",
  "ISSAQ Lameece": "issaq-lameece",
  "ISSEL-PITRE Katie": "issel-pitre-katie",
  "ISSENDORF John": "issendorf-john",
  "ITALIANO Laura": "italiano-laura",
  "ITO Shoko": "ito-shoko",
  "ITO Teiji": "ito-teiji",
  "ITTE Lisa Levin": "itte-lisa-levin",
  "ITZIN Catherine": "itzin-catherine",
  "ITZKOW Ethan": "itzkow-ethan",
  "IVANOVICH Denis": "ivanovich-denis",
  "IVANOVICH Yahimovich Sergey": "ivanovich-yahimovich-sergey",
  "IVAY Jon": "ivay-jon",
  "IVERSON Aaron": "iverson-aaron",
  "IVERSON Roger": "iverson-roger",
  "IVERSON Ryan": "iverson-ryan",
  "IVES David": "ives-david",
  "IVES Denys": "ives-denys",
  "IVES Derek": "ives-derek",
  "IVES Philip": "ives-philip",
  "IVES Steve": "ives-steve",
  "IVES-MOIBA Mariama": "ives-moiba-mariama",
  "IVESON Mike": "iveson-mike",
  "IVISON Dawn": "ivison-dawn",
  "IVORY Terrence Tyrie": "ivory-terrence-tyrie",
  "IVORY William": "ivory-william",
  "IWAMOTO Gary": "iwamoto-gary",
  "IWASUK James": "iwasuk-james",
  "IWASZKO Danusia": "iwaszko-danusia",
  "IWATAKI Joel": "iwataki-joel",
  "IYENGAR Niranjan": "iyengar-niranjan",
  "IZBUDAK Mehmet": "izbudak-mehmet",
  "IZUKA Scott": "izuka-scott",
  "IZZO Ben": "izzo-ben",
};
