export default {
  "O Annie": "o-annie",
  "O BEIRN Seamus": "o-beirn-seamus",
  "O BRIAIN Art": "o-briain-art",
  "O BRIAIN Liam": "o-briain-liam",
  "O BRIAIN Michael": "o-briain-michael",
  "O BRIAIN Sean": "o-briain-sean",
  "O BRIEN John Edward": "o-brien-john-edward",
  "O BROIN Brian": "o-broin-brian",
  "O BROIN Leon": "o-broin-leon",
  "O BROIN Risteard": "o-broin-risteard",
  "O BROIN Ruairi": "o-broin-ruairi",
  "O BROIN Sean": "o-broin-sean",
  "O BROITHE Padraig": "o-broithe-padraig",
  "O CAIREALLAIN Gearoid": "o-caireallain-gearoid",
  "O CARRA Sean": "o-carra-sean",
  "O CATHAIN Muiris": "o-cathain-muiris",
  "O CATHAIN Padraig": "o-cathain-padraig",
  "O CEALLAIGH Liam": "o-ceallaigh-liam",
  "O CEALLAIGH Micheal": "o-ceallaigh-micheal",
  "O CEALLAIGH Rafael": "o-ceallaigh-rafael",
  "O CEALLAIGH Sean": "o-ceallaigh-sean",
  "O CEALLAIGH Tomas": "o-ceallaigh-tomas",
  "O CEARBHAILL Padraig": "o-cearbhaill-padraig",
  "O CIARGHUSA Colm": "o-ciarghusa-colm",
  "O CIARGHUSA Sean": "o-ciarghusa-sean",
  "O CLOCHARTAIGH Trevor": "o-clochartaigh-trevor",
  "O COISDEALBHA Sean": "o-coisdealbha-sean",
  "O CONAILL Bearnard": "o-conaill-bearnard",
  "O CONAILL Ciaran": "o-conaill-ciaran",
  "O CONAIRE Padraic": "o-conaire-padraic",
  "O CONAIRE Padraig Og": "o-conaire-padraig-og",
  "O CONAOLA Dara": "o-conaola-dara",
  "O CONCHUBHAIR Liam": "o-conchubhair-liam",
  "O CONCHUBHAIR Sean": "o-conchubhair-sean",
  "O CONCHUBHAIR Sean-Shean": "o-conchubhair-sean-shean",
  "O CONCHUIR Bosco": "o-conchuir-bosco",
  "O CONGHAILE Caoimhghin": "o-conghaile-caoimhghin",
  "O CONGHAILE Micheal": "o-conghaile-micheal",
  "O CORRBHUI Coilin": "o-corrbhui-coilin",
  "O CORRBUI Mairtin": "o-corrbui-mairtin",
  "O CREATHAIN Micheal": "o-creathain-micheal",
  "O CROININ Partholan": "o-croinin-partholan",
  "O CUILL Donal": "o-cuill-donal",
  "O CUINN Aindrias": "o-cuinn-aindrias",
  "O CUIV Shan": "o-cuiv-shan",
  "O CULAIN Peadar": "o-culain-peadar",
  "O DALAIGH Colm": "o-dalaigh-colm",
  "O DIOLUIN Tomas": "o-dioluin-tomas",
  "O DIREAIN Mairtin": "o-direain-mairtin",
  "O DOIBHLIN Breandan": "o-doibhlin-breandan",
  "O DOMHNAILL Aodh": "o-domhnaill-aodh",
  "O DOMHNAILL Liam": "o-domhnaill-liam",
  "O DOMHNAILL Maghnus": "o-domhnaill-maghnus",
  "O DOMHNAILL Padraig": "o-domhnaill-padraig",
  "O DONNCHADHA Tadhg": "o-donnchadha-tadhg",
  "O DROIGHNEAIN Micheal": "o-droighneain-micheal",
  "O DUBHGAIN Aodh": "o-dubhgain-aodh",
  "O DUIRINNE Seamus": "o-duirinne-seamus",
  "O FARACHAIN Roibeard": "o-farachain-roibeard",
  "O FATHARTA Macdara": "o-fatharta-macdara",
  "O FEINNEADHA P": "o-feinneadha-p",
  "O FLAITHEARTA Tom Saili": "o-flaithearta-tom-saili",
  "O FLATHARTA Antoine": "o-flatharta-antoine",
  "O FLOINN Criostoir": "o-floinn-criostoir",
  "O FOGHLU Colm": "o-foghlu-colm",
  "O FOGHLUDHA Risteard": "o-foghludha-risteard",
  "O FOGHLUDHA Sean": "o-foghludha-sean",
  "O GALLCHOIR Aindrias": "o-gallchoir-aindrias",
  "O GALLCHOIR Brid": "o-gallchoir-brid",
  "O GAORA Padraig": "o-gaora-padraig",
  "O GIOLLAGAIN Padhraig": "o-giollagain-padhraig",
  "O GOLDMAN A E": "o-goldman-a-e",
  "O GRIOFA Micheal": "o-griofa-micheal",
  "O HAIRT Padraig": "o-hairt-padraig",
  "O HALMHAIN Diarmuid": "o-halmhain-diarmuid",
  "O HANNRACHAIN Fachtna": "o-hannrachain-fachtna",
  "O HANNRACHAIN Peadar": "o-hannrachain-peadar",
  "O HAODHA Micheal": "o-haodha-micheal",
  "O HAODHA Seamus": "o-haodha-seamus",
  "O HAODHA Seamus (1)": "o-haodha-seamus-1",
  "O HAONGHUSA Traolach": "o-haonghusa-traolach",
  "O HEAGHRA Breandan": "o-heaghra-breandan",
  "O HEALUIGHTHE Tomas": "o-healuighthe-tomas",
  "O HEIDIRSCEOIL Sean": "o-heidirsceoil-sean",
  "O HEIGEARTAIGH Sean": "o-heigeartaigh-sean",
  "O HEIGHNEACHAIN Tomas": "o-heighneachain-tomas",
  "O HEITHIR Breandan": "o-heithir-breandan",
  "O HOGAIN Sean": "o-hogain-sean",
  "O HORAIN Sean": "o-horain-sean",
  "O HUAITHNE Daithi": "o-huaithne-daithi",
  "O LABHRADHA Alphonsus": "o-labhradha-alphonsus",
  "O LAIGHLEIS Re": "o-laighleis-re",
  "O LAOGHAIRE Liam": "o-laoghaire-liam",
  "O LOCHLAINN Gearoid": "o-lochlainn-gearoid",
  "O LOCHLAINN Sean": "o-lochlainn-sean",
  "O LOINGSIGH Amhlaoibh": "o-loingsigh-amhlaoibh",
  "O LOINGSIGH Fionan": "o-loingsigh-fionan",
  "O MAILLE Tomas S": "o-maille-tomas-s",
  "O MAOILEOIN Brian": "o-maoileoin-brian",
  "O MAONAIGH Proinsias": "o-maonaigh-proinsias",
  "O MATHUNA Coiril": "o-mathuna-coiril",
  "O MIODHACHAIN Proinsias": "o-miodhachain-proinsias",
  "O MORAIN An Canonach P": "o-morain-an-canonach-p",
  "O MUIRCHEARTAIGH Tomas": "o-muircheartaigh-tomas",
  "O MUIRTHILE Liam": "o-muirthile-liam",
  "O MUIRTHUILE Sean": "o-muirthuile-sean",
  "O MURCHADHA Diarmuid": "o-murchadha-diarmuid",
  "O MURCHU Liam": "o-murchu-liam",
  "O NEACHTAIN Eoghan": "o-neachtain-eoghan",
  "O NEACHTAIN Joe Steve": "o-neachtain-joe-steve",
  "O NEACHTAIN Padraig": "o-neachtain-padraig",
  "O NEACHTAIN Sean": "o-neachtain-sean",
  "O NEILL Eoghan": "o-neill-eoghan",
  "O NEILL Seamus": "o-neill-seamus",
  "O RAGHALLAIGH Caoimhin": "o-raghallaigh-caoimhin",
  "O RAGHALLAIGH Tomas": "o-raghallaigh-tomas",
  "O RAITHBHEARTAIGH Traolach": "o-raithbheartaigh-traolach",
  "O RIADA Sean": "o-riada-sean",
  "O RIAGAIN Brian": "o-riagain-brian",
  "O RIAIN Liam P": "o-riain-liam-p",
  "O RINN Liam": "o-rinn-liam",
  "O RIORDAIN Aodhan": "o-riordain-aodhan",
  "O RIORDAIN Domhnall": "o-riordain-domhnall",
  "O SCANAILL Tadhg": "o-scanaill-tadhg",
  "O SCOLAI Darach": "o-scolai-darach",
  "O SCOLAI Seamas": "o-scolai-seamas",
  "O SEAGHDHA Diarmuid": "o-seaghdha-diarmuid",
  "O SEAGHDHA Micheal": "o-seaghdha-micheal",
  "O SEAGHDHA Padraig": "o-seaghdha-padraig",
  "O SEAGHDHA Seamus": "o-seaghdha-seamus",
  "O SEARCAIGH Cathal": "o-searcaigh-cathal",
  "O SEOIGHE Tadhg S": "o-seoighe-tadhg-s",
  "O SIOCHFHRADHA Micheal": "o-siochfhradha-micheal",
  "O SIOCHFHRADHA Padraig": "o-siochfhradha-padraig",
  "O SIOCHRU Padraig": "o-siochru-padraig",
  "O SIORDAIN Niall": "o-siordain-niall",
  "O SLEIBHIN Gearoid": "o-sleibhin-gearoid",
  "O SNODAIGH Padraig": "o-snodaigh-padraig",
  "O SUILLEABHAIN Diarmuid (1)": "o-suilleabhain-diarmuid-1",
  "O SUILLEABHAIN Diarmuid (2)": "o-suilleabhain-diarmuid-2",
  "O SUILLEABHAIN Eoin": "o-suilleabhain-eoin",
  "O SUILLEABHAIN Micheal (2)": "o-suilleabhain-micheal-2",
  "O SUILLEABHAIN Micheal (3)": "o-suilleabhain-micheal-3",
  "O SUILLEABHAIN S": "o-suilleabhain-s",
  "O SUILLEABHAIN S L": "o-suilleabhain-s-l",
  "O SUILLEABHAIN Tomas": "o-suilleabhain-tomas",
  "O TALLAMHANN S": "o-tallamhann-s",
  "O TIGHEARNAIGH Gearoid": "o-tighearnaigh-gearoid",
  "O TUAIRISC Eoghan": "o-tuairisc-eoghan",
  "O TUAIRISC Padraig": "o-tuairisc-padraig",
  "O TUAMA Con": "o-tuama-con",
  "O TUAMA Seamus": "o-tuama-seamus",
  "O TUAMA Sean": "o-tuama-sean",
  "O TUAMA Tadhg": "o-tuama-tadhg",
  "OADES Roslyn": "oades-roslyn",
  "OAKES Bill": "oakes-bill",
  "OAKES Jimmy": "oakes-jimmy",
  "OAKES Kevin": "oakes-kevin",
  "OAKES Meredith": "oakes-meredith",
  "OAKES Michael": "oakes-michael",
  "OAKES Roy": "oakes-roy",
  "OAKES Russell J": "oakes-russell-j",
  "OAKES Vanessa": "oakes-vanessa",
  "OAKFIELD Tice": "oakfield-tice",
  "OAKLAND Ben": "oakland-ben",
  "OAKLEIGH Helen": "oakleigh-helen",
  "OAKLEY Barry": "oakley-barry",
  "OAKLEY George William": "oakley-george-william",
  "OAKLEY Mark Adrian": "oakley-mark-adrian",
  "OAKS John Thomas": "oaks-john-thomas",
  "OASTLER Henry": "oastler-henry",
  "OATES Alex": "oates-alex",
  "OATES Debbie": "oates-debbie",
  "OATES Joyce Carol": "oates-joyce-carol",
  "OATMAN Michael": "oatman-michael",
  "OBA Tunde": "oba-tunde",
  "OBAFEMI Olu": "obafemi-olu",
  "OBAN James": "oban-james",
  "OBANO Rex": "obano-rex",
  "OBARZANEK Gideon": "obarzanek-gideon",
  "OBASEKI Pedro": "obaseki-pedro",
  "OBASI Chuk": "obasi-chuk",
  "OBEDZINSKI Paul": "obedzinski-paul",
  "OBEIDALLAH Dean": "obeidallah-dean",
  "OBENEY Russell": "obeney-russell",
  "OBERACKER Richard": "oberacker-richard",
  "OBERFELDER Jody": "oberfelder-jody",
  "OBERG Richard": "oberg-richard",
  "OBERHAUSER Michael": "oberhauser-michael",
  "OBERMAN Sheldon": "oberman-sheldon",
  "OBERMAN Steven": "oberman-steven",
  "OBERMAN Tracy-Ann": "oberman-tracy-ann",
  "OBERMEIER Gerlinde": "obermeier-gerlinde",
  "OBERNDORFER Cory": "oberndorfer-cory",
  "OBERZAN Zachary": "oberzan-zachary",
  "OBEXER Margareth": "obexer-margareth",
  "OBEY Andre": "obey-andre",
  "OBIORA Chudi": "obiora-chudi",
  "OBISESAN Gbolahan": "obisesan-gbolahan",
  "OBLER Arch": "obler-arch",
  "OBLONGATA Donna": "oblongata-donna",
  "OBOLENSKY Kira": "obolensky-kira",
  "OBOLENSKY Masha": "obolensky-masha",
  "OBOLER Arch": "oboler-arch",
  "O'BOYLE Cis": "o-boyle-cis",
  "O'BOYLE John": "o-boyle-john",
  "O'BRANAGAIN Finn": "o-branagain-finn",
  "OBRENSKI Eve": "obrenski-eve",
  "O'BRIAIN BELL Rory": "o-briain-bell-rory",
  "O'BRIAN Ben": "o-brian-ben",
  "O'BRIEN Barret": "o-brien-barret",
  "O'BRIEN Caraid": "o-brien-caraid",
  "O'BRIEN Conor Cruise": "o-brien-conor-cruise",
  "O'BRIEN Dan": "o-brien-dan",
  "O'BRIEN Daniel": "o-brien-daniel",
  "O'BRIEN Daniel Richard": "o-brien-daniel-richard",
  "O'BRIEN Dara": "o-brien-dara",
  "O'BRIEN Eddie": "o-brien-eddie",
  "O'BRIEN Edna": "o-brien-edna",
  "O'BRIEN Elizabeth": "o-brien-elizabeth",
  "O'BRIEN Eric": "o-brien-eric",
  "O'BRIEN Eugene": "o-brien-eugene",
  "O'BRIEN Felix": "o-brien-felix",
  "O'BRIEN Flann": "o-brien-flann",
  "O'BRIEN Glenn": "o-brien-glenn",
  "O'BRIEN Jack": "o-brien-jack",
  "O'BRIEN Jaime": "o-brien-jaime",
  "O'BRIEN Jami": "o-brien-jami",
  "O'BRIEN John": "o-brien-john",
  "O'BRIEN John (1)": "o-brien-john-1",
  "O'BRIEN John Edward": "o-brien-john-edward",
  "O'BRIEN John Emmett": "o-brien-john-emmett",
  "O'BRIEN Julianne": "o-brien-julianne",
  "O'BRIEN Juliet": "o-brien-juliet",
  "O'BRIEN Justin": "o-brien-justin",
  "O'BRIEN Kate": "o-brien-kate",
  "O'BRIEN Liam": "o-brien-liam",
  "O'BRIEN Lorraine": "o-brien-lorraine",
  "O'BRIEN Lucy": "o-brien-lucy",
  "O'BRIEN Matte": "o-brien-matte",
  "O'BRIEN Maureen": "o-brien-maureen",
  "O'BRIEN Michael": "o-brien-michael",
  "O'BRIEN Michael (1)": "o-brien-michael-1",
  "O'BRIEN Michael (2)": "o-brien-michael-2",
  "O'BRIEN Paul": "o-brien-paul",
  "O'BRIEN Richard": "o-brien-richard",
  "O'BRIEN Robert": "o-brien-robert",
  "O'BRIEN Sean": "o-brien-sean",
  "O'BRIEN Sean (1)": "o-brien-sean-1",
  "O'BRIEN Sharon": "o-brien-sharon",
  "O'BRIEN Tim": "o-brien-tim",
  "O'BRIEN Tom": "o-brien-tom",
  "O'BRIEN Tom (1)": "o-brien-tom-1",
  "O'BRIEN Tom (2)": "o-brien-tom-2",
  "O'BRYANT Richard": "o-bryant-richard",
  "OBST Lynda": "obst-lynda",
  "O'BYRNE Joe": "o-byrne-joe",
  "O'BYRNE Joe (1)": "o-byrne-joe-1",
  "O'CALLAGHAN Briony": "o-callaghan-briony",
  "O'CALLAGHAN Jill": "o-callaghan-jill",
  "O'CALLAGHAN Ruth": "o-callaghan-ruth",
  "O'CARROLL Brendan": "o-carroll-brendan",
  "O'CARROLL Dean": "o-carroll-dean",
  "O'CARROLL Eilish": "o-carroll-eilish",
  "O'CARROLL Gavin": "o-carroll-gavin",
  "O'CARROLL Harriet": "o-carroll-harriet",
  "O'CASEY Sean": "o-casey-sean",
  "OCHI Yoshiaki": "ochi-yoshiaki",
  "OCHWAT Daniel Theodore": "ochwat-daniel-theodore",
  "OCKERBY Nerissa": "ockerby-nerissa",
  "OCKHAM'S RAZOR ": "ockhams-razor",
  "OCKRENT Ben": "ockrent-ben",
  "OCKRENT Mike": "ockrent-mike",
  "OCKS Matt": "ocks-matt",
  "O'CONNELL Andrew": "o-connell-andrew",
  "O'CONNELL Brendan": "o-connell-brendan",
  "O'CONNELL Chris": "o-connell-chris",
  "O'CONNELL E": "o-connell-e",
  "O'CONNELL Frances": "o-connell-frances",
  "O'CONNELL Geoffrey": "o-connell-geoffrey",
  "O'CONNELL James Mainard": "o-connell-james-mainard",
  "O'CONNELL Jason": "o-connell-jason",
  "O'CONNELL Kathryn Mainard": "o-connell-kathryn-mainard",
  "O'CONNELL Lorna": "o-connell-lorna",
  "O'CONNELL Oliver": "o-connell-oliver",
  "O'CONNELL Richard L": "o-connell-richard-l",
  "O'CONNELL Stephen": "o-connell-stephen",
  "O'CONNELL Steve": "o-connell-steve",
  "O'CONNELL Terence": "o-connell-terence",
  "O'CONNELL Trevor": "o-connell-trevor",
  "O'CONNELL Vincent": "o-connell-vincent",
  "O'CONNER Frank": "o-conner-frank",
  "O'CONNOR Anne-Marie": "o-connor-anne-marie",
  "O'CONNOR Bridget": "o-connor-bridget",
  "O'CONNOR Caroline": "o-connor-caroline",
  "O'CONNOR Catherine": "o-connor-catherine",
  "O'CONNOR Charles G": "o-connor-charles-g",
  "O'CONNOR Chris": "o-connor-chris",
  "O'CONNOR Chuck": "o-connor-chuck",
  "O'CONNOR Colin": "o-connor-colin",
  "O'CONNOR Conleth": "o-connor-conleth",
  "O'CONNOR Danny": "o-connor-danny",
  "O'CONNOR David": "o-connor-david",
  "O'CONNOR Deirdre": "o-connor-deirdre",
  "O'CONNOR Derek": "o-connor-derek",
  "O'CONNOR Desmond": "o-connor-desmond",
  "O'CONNOR Diegan": "o-connor-diegan",
  "O'CONNOR Edwin": "o-connor-edwin",
  "O'CONNOR Elizabeth": "o-connor-elizabeth",
  "O'CONNOR Eva": "o-connor-eva",
  "O'CONNOR Frank": "o-connor-frank",
  "O'CONNOR Garry": "o-connor-garry",
  "O'CONNOR Geraldine": "o-connor-geraldine",
  "O'CONNOR Helen": "o-connor-helen",
  "O'CONNOR James": "o-connor-james",
  "O'CONNOR James V": "o-connor-james-v",
  "O'CONNOR Jan": "o-connor-jan",
  "O'CONNOR Jim": "o-connor-jim",
  "O'CONNOR Joanne": "o-connor-joanne",
  "O'CONNOR John": "o-connor-john",
  "O'CONNOR Joseph": "o-connor-joseph",
  "O'CONNOR Kent": "o-connor-kent",
  "O'CONNOR Kevin": "o-connor-kevin",
  "O'CONNOR Kevin A": "o-connor-kevin-a",
  "O'CONNOR Luke": "o-connor-luke",
  "O'CONNOR Mariann M": "o-connor-mariann-m",
  "O'CONNOR Mark": "o-connor-mark",
  "O'CONNOR Martin": "o-connor-martin",
  "O'CONNOR Michael": "o-connor-michael",
  "O'CONNOR Milovan": "o-connor-milovan",
  "O'CONNOR Oria": "o-connor-oria",
  "O'CONNOR P J": "o-connor-p-j",
  "O'CONNOR Patricia": "o-connor-patricia",
  "O'CONNOR Patricia W": "o-connor-patricia-w",
  "O'CONNOR Patrick": "o-connor-patrick",
  "O'CONNOR Paul": "o-connor-paul",
  "O'CONNOR Penny": "o-connor-penny",
  "O'CONNOR Reg": "o-connor-reg",
  "O'CONNOR Robbie": "o-connor-robbie",
  "O'CONNOR Robert": "o-connor-robert",
  "O'CONNOR Ryan": "o-connor-ryan",
  "O'CONNOR Sara": "o-connor-sara",
  "O'CONNOR Sean": "o-connor-sean",
  "O'CONNOR Simon": "o-connor-simon",
  "O'CONNOR Steven Tylor": "o-connor-steven-tylor",
  "O'CONNOR Terry": "o-connor-terry",
  "O'CONNOR Trish": "o-connor-trish",
  "O'CONNOR Ulick": "o-connor-ulick",
  "O'CONOR Joseph": "o-conor-joseph",
  "O'DAY Michael C": "o-day-michael-c",
  "ODD MAN OUT ": "odd-man-out",
  "ODDBODIES ": "oddbodies",
  "ODDEN Denis": "odden-denis",
  "ODDMANOUT ": "oddmanout",
  "ODDY Nick": "oddy-nick",
  "O'DEBRA Tanya": "o-debra-tanya",
  "ODEMS Keninya": "odems-keninya",
  "ODEMS Kennyetta": "odems-kennyetta",
  "ODERBERG David S": "oderberg-david-s",
  "ODETS Clifford": "odets-clifford",
  "ODIA Thomas": "odia-thomas",
  "ODIMBA Chino": "odimba-chino",
  "ODIN TEATRET ": "odin-teatret",
  "O'DOHERTY Claudia": "o-doherty-claudia",
  "O'DOHERTY David": "o-doherty-david",
  "ODOM Alex": "odom-alex",
  "O'DONNACHADHA Cillian": "o-donnachadha-cillian",
  "O'DONNEL Sean": "o-donnel-sean",
  "O'DONNELL Bridget": "o-donnell-bridget",
  "O'DONNELL Chris": "o-donnell-chris",
  "O'DONNELL Daniel": "o-donnell-daniel",
  "O'DONNELL Darren": "o-donnell-darren",
  "O'DONNELL Dean": "o-donnell-dean",
  "O'DONNELL Frank": "o-donnell-frank",
  "O'DONNELL Geoffrey Decas": "o-donnell-geoffrey-decas",
  "O'DONNELL Jack": "o-donnell-jack",
  "O'DONNELL Jim": "o-donnell-jim",
  "O'DONNELL Joe": "o-donnell-joe",
  "O'DONNELL John P": "o-donnell-john-p",
  "O'DONNELL Karen": "o-donnell-karen",
  "O'DONNELL Kate": "o-donnell-kate",
  "O'DONNELL Kevin": "o-donnell-kevin",
  "O'DONNELL Kevin Kell": "o-donnell-kevin-kell",
  "O'DONNELL Margaret Ann": "o-donnell-margaret-ann",
  "O'DONNELL Mark": "o-donnell-mark",
  "O'DONNELL Peter": "o-donnell-peter",
  "O'DONNELL Richard P": "o-donnell-richard-p",
  "O'DONNELL Ronan": "o-donnell-ronan",
  "O'DONNELL Sean": "o-donnell-sean",
  "O'DONNELL Stephen": "o-donnell-stephen",
  "O'DONNELL Val": "o-donnell-val",
  "O'DONOGHUE John": "o-donoghue-john",
  "O'DONOGHUE Michael": "o-donoghue-michael",
  "O'DONOGHUE Noel": "o-donoghue-noel",
  "O'DONOGHUE Robert": "o-donoghue-robert",
  "O'DONOVAN John": "o-donovan-john",
  "O'DONOVAN John (1)": "o-donovan-john-1",
  "O'DONOVAN Terry": "o-donovan-terry",
  "O'DRISCOLL Ciaran": "o-driscoll-ciaran",
  "O'DRISCOLL Liam": "o-driscoll-liam",
  "O'DWYER Eamonn": "o-dwyer-eamonn",
  "O'DWYER Louise": "o-dwyer-louise",
  "O'DWYER Marion": "o-dwyer-marion",
  "O'DWYER Matthew": "o-dwyer-matthew",
  "OESER Kevin": "oeser-kevin",
  "OESTEREICH James": "oestereich-james",
  "OESTERMAN Philip": "oesterman-philip",
  "OESTREICHER Amy": "oestreicher-amy",
  "O'FARRELL John": "o-farrell-john",
  "O'FARRELL Joseph": "o-farrell-joseph",
  "O'FARRELL Padraic": "o-farrell-padraic",
  "O'FARRELL Rita": "o-farrell-rita",
  "O'FERRALL Courtney": "o-ferrall-courtney",
  "OFF LIMITS THEATRE COMPANY ": "off-limits-theatre-company",
  "OFFENBACH Gabby": "offenbach-gabby",
  "OFFER Judith": "offer-judith",
  "OFFORD Alexander": "offord-alexander",
  "OFFRICHT Kenneth": "offricht-kenneth",
  "O'FLAHERTY Michael": "o-flaherty-michael",
  "O'FLAHERTY Tracy": "o-flaherty-tracy",
  "O'FLAHERTY Wendy": "o-flaherty-wendy",
  "O'FLATHARTA Antoine": "o-flatharta-antoine",
  "OFLAZOGLU A Turzan": "oflazoglu-a-turzan",
  "O'FLYNN Criostoir": "o-flynn-criostoir",
  "O'FLYNN Mark": "o-flynn-mark",
  "O'FLYNN Niamh": "o-flynn-niamh",
  "OFORI Racheal": "ofori-racheal",
  "O'GARDEN Irene": "o-garden-irene",
  "OGATA Issey": "ogata-issey",
  "OGAWA Aya": "ogawa-aya",
  "OGAWA Ruby": "ogawa-ruby",
  "OGBORN Brandon": "ogborn-brandon",
  "OGBORN Michael": "ogborn-michael",
  "OGDEN Alan": "ogden-alan",
  "OGDEN Gill": "ogden-gill",
  "OGDEN Kevan": "ogden-kevan",
  "OGDEN Simon": "ogden-simon",
  "OGIDI Ann": "ogidi-ann",
  "OGILVIE David Ogilvie": "ogilvie-david-ogilvie",
  "OGILVY Ian": "ogilvy-ian",
  "OGILVY Kirstie": "ogilvy-kirstie",
  "OGILVY Rachel": "ogilvy-rachel",
  "OGILVY Tim": "ogilvy-tim",
  "OGLE Adam": "ogle-adam",
  "OGLE Mark D": "ogle-mark-d",
  "OGLE Sean": "ogle-sean",
  "OGLESBY Briandaniel": "oglesby-briandaniel",
  "OGLESBY Marshall": "oglesby-marshall",
  "OGLESBY Tamsin": "oglesby-tamsin",
  "OGNEV Ilya": "ognev-ilya",
  "O'GORMAN Keith": "o-gorman-keith",
  "O'GORMAN Simon": "o-gorman-simon",
  "O'GRADY Desmond": "o-grady-desmond",
  "O'GRADY Jennifer": "o-grady-jennifer",
  "O'GRADY Mairin": "o-grady-mairin",
  "O'GRADY Roderick": "o-grady-roderick",
  "OGRIN Dave": "ogrin-dave",
  "OGRYZKOV Nikolai": "ogryzkov-nikolai",
  "OGUNLEYE Foluke": "ogunleye-foluke",
  "OGUNS Femi": "oguns-femi",
  "OGUNTOKUN Wole": "oguntokun-wole",
  "OGUNYEMI Wale": "ogunyemi-wale",
  "OGWEN John": "ogwen-john",
  "OH Eugene": "oh-eugene",
  "OH Soon-teck": "oh-soon-teck",
  "OH Taesuk": "oh-taesuk",
  "OH Tony": "oh-tony",
  "O'HAGAN Andrew": "o-hagan-andrew",
  "O'HAGAN Jack": "o-hagan-jack",
  "O'HAGAN Lucy": "o-hagan-lucy",
  "O'HAGAN Mairin": "o-hagan-mairin",
  "O'HAGAN Terry": "o-hagan-terry",
  "O'HALLORAN Gretchen C": "o-halloran-gretchen-c",
  "O'HALLORAN Mark": "o-halloran-mark",
  "O'HANLON Ardal": "o-hanlon-ardal",
  "O'HANLON Emma": "o-hanlon-emma",
  "O'HANLON Jim": "o-hanlon-jim",
  "O'HANRAHAN Paul": "o-hanrahan-paul",
  "O'HARA David K": "o-hara-david-k",
  "O'HARA Frank": "o-hara-frank",
  "O'HARA James": "o-hara-james",
  "O'HARA John": "o-hara-john",
  "O'HARA John (1)": "o-hara-john-1",
  "O'HARA John (2)": "o-hara-john-2",
  "O'HARA Mary": "o-hara-mary",
  "O'HARA Michael Desmond": "o-hara-michael-desmond",
  "O'HARA Patricia": "o-hara-patricia",
  "O'HARA Riggs": "o-hara-riggs",
  "O'HARA Robert": "o-hara-robert",
  "O'HARE Caroline": "o-hare-caroline",
  "O'HARE Denis": "o-hare-denis",
  "O'HARE Eugene": "o-hare-eugene",
  "O'HARE Gaynor": "o-hare-gaynor",
  "O'HARE John": "o-hare-john",
  "O'HARE Kristian": "o-hare-kristian",
  "O'HARE Marcella": "o-hare-marcella",
  "O'HARRA Brooke": "o-harra-brooke",
  "OHASHI Yasuhiko": "ohashi-yasuhiko",
  "O'HAVER Sarah Kate": "o-haver-sarah-kate",
  "O'HEARN Kerry": "o-hearn-kerry",
  "O'HEARN Nigel": "o-hearn-nigel",
  "OHM Lori Allen": "ohm-lori-allen",
  "OHM Stephen": "ohm-stephen",
  "OHNO Yoshito": "ohno-yoshito",
  "O'HORA Margaret": "o-hora-margaret",
  "O'HORGAN Tom": "o-horgan-tom",
  "OHTA Shogo": "ohta-shogo",
  "OIDA Yoshi": "oida-yoshi",
  "OILART Luis": "oilart-luis",
  "OILY CART ": "oily-cart",
  "OIYE David": "oiye-david",
  "OJEDA Perry": "ojeda-perry",
  "OKADA Toshiki": "okada-toshiki",
  "OKADA Yutaka": "okada-yutaka",
  "OKAI Omar F": "okai-omar-f",
  "OKAMURA Akemi": "okamura-akemi",
  "O'KANE Maggie": "o-kane-maggie",
  "O'KASI Leann": "o-kasi-leann",
  "OKE Erin": "oke-erin",
  "O'KEEFE Andrew": "o-keefe-andrew",
  "O'KEEFE Catie": "o-keefe-catie",
  "O'KEEFE Damien": "o-keefe-damien",
  "O'KEEFE J F": "o-keefe-j-f",
  "O'KEEFE Jim": "o-keefe-jim",
  "O'KEEFE John": "o-keefe-john",
  "O'KEEFE Julia": "o-keefe-julia",
  "O'KEEFE Laurence": "o-keefe-laurence",
  "O'KEEFE Lester": "o-keefe-lester",
  "O'KEEFFE John": "o-keeffe-john",
  "O'KEEFFE Kelly": "o-keeffe-kelly",
  "O'KEEFFE Paul": "o-keeffe-paul",
  "O'KELL Hayley": "o-kell-hayley",
  "O'KELLY Donal": "o-kelly-donal",
  "O'KELLY Katie": "o-kelly-katie",
  "O'KELLY Seamus": "o-kelly-seamus",
  "OKEN Scott": "oken-scott",
  "OKIMOTO Jean Davies": "okimoto-jean-davies",
  "OKIN Matt": "okin-matt",
  "OKITA Dwight": "okita-dwight",
  "OKLADEK Mark": "okladek-mark",
  "OKLAHOMA D K": "oklahoma-d-k",
  "OKLOP Mika": "oklop-mika",
  "OKOH Janice": "okoh-janice",
  "OKOLI Onyi": "okoli-onyi",
  "OKOLI Tunde": "okoli-tunde",
  "OKPOKWASILI Okwui": "okpokwasili-okwui",
  "OKRAND Marc": "okrand-marc",
  "OKRANT Robyn": "okrant-robyn",
  "OKRENT Daniel": "okrent-daniel",
  "OKSANEN Sofi": "oksanen-sofi",
  "OKTEM Cigdem": "oktem-cigdem",
  "OKUN Stephanie": "okun-stephanie",
  "OLAFFSSON Olaf": "olaffsson-olaf",
  "OLAND Edith": "oland-edith",
  "OLAND Warner": "oland-warner",
  "OLANDER James F": "olander-james-f",
  "OLATUNJI Tunde": "olatunji-tunde",
  "OLBERT John": "olbert-john",
  "OLCOTT Nick": "olcott-nick",
  "OLDENDICK Tom": "oldendick-tom",
  "OLDERSHAW Jake": "oldershaw-jake",
  "OLDFIELD Ben": "oldfield-ben",
  "OLDFIELD Mary": "oldfield-mary",
  "OLDHAM Joseph": "oldham-joseph",
  "OLDHAM Reginald": "oldham-reginald",
  "OLDING Grant": "olding-grant",
  "OLDKNOW Charles": "oldknow-charles",
  "OLDKNOW Mark": "oldknow-mark",
  "O'LEARY Aileen": "o-leary-aileen",
  "O'LEARY Allen": "o-leary-allen",
  "O'LEARY Casey": "o-leary-casey",
  "O'LEARY Charlie": "o-leary-charlie",
  "O'LEARY Denise": "o-leary-denise",
  "O'LEARY Eileen": "o-leary-eileen",
  "O'LEARY Helen": "o-leary-helen",
  "O'LEARY Megan": "o-leary-megan",
  "O'LEARY Sarah": "o-leary-sarah",
  "O'LEARY Sean": "o-leary-sean",
  "O'LEARY Tim": "o-leary-tim",
  "OLEJNICZAK Alan": "olejniczak-alan",
  "OLER Kim": "oler-kim",
  "OLES Stephen": "oles-stephen",
  "OLESKER Lizzie": "olesker-lizzie",
  "OLESON-CORMACK Leif": "oleson-cormack-leif",
  "OLESZKO Mark": "oleszko-mark",
  "OLF Julian": "olf-julian",
  "OLFAT Beejan": "olfat-beejan",
  "OLFSON Lewy": "olfson-lewy",
  "OLIANSKY Joel": "oliansky-joel",
  "OLIENSIS Adam": "oliensis-adam",
  "OLINS Andrew": "olins-andrew",
  "OLIVA Ann Marie": "oliva-ann-marie",
  "OLIVA Judy Lee": "oliva-judy-lee",
  "OLIVARES Ivan": "olivares-ivan",
  "OLIVE Bruce": "olive-bruce",
  "OLIVE John": "olive-john",
  "OLIVER Amanda": "oliver-amanda",
  "OLIVER Anthony Michael": "oliver-anthony-michael",
  "OLIVER Brian": "oliver-brian",
  "OLIVER Bryan": "oliver-bryan",
  "OLIVER Christy": "oliver-christy",
  "OLIVER Clifford": "oliver-clifford",
  "OLIVER Donald": "oliver-donald",
  "OLIVER Donald (1)": "oliver-donald-1",
  "OLIVER Edgar": "oliver-edgar",
  "OLIVER Gordon": "oliver-gordon",
  "OLIVER Isaac": "oliver-isaac",
  "OLIVER Jake": "oliver-jake",
  "OLIVER Jill": "oliver-jill",
  "OLIVER Kathleen": "oliver-kathleen",
  "OLIVER Louise": "oliver-louise",
  "OLIVER Mark": "oliver-mark",
  "OLIVER Murray": "oliver-murray",
  "OLIVER Nancy": "oliver-nancy",
  "OLIVER Reggie": "oliver-reggie",
  "OLIVER Robert": "oliver-robert",
  "OLIVER Ryan Scott": "oliver-ryan-scott",
  "OLIVER Sean Harris": "oliver-sean-harris",
  "OLIVER Wilbert": "oliver-wilbert",
  "OLIVER William Stanley": "oliver-william-stanley",
  "OLIVEROS Pauline": "oliveros-pauline",
  "OLIVIA Sophie": "olivia-sophie",
  "OLIVIER Laurence": "olivier-laurence",
  "OLIVIERI Guy": "olivieri-guy",
  "OLLE Alex": "olle-alex",
  "OLLIES Amie-Jane": "ollies-amie-jane",
  "OLLSTEIN Laurel": "ollstein-laurel",
  "OLM James": "olm-james",
  "OLMI Veronique": "olmi-veronique",
  "OLMO Lauro": "olmo-lauro",
  "OLMOS Carlos": "olmos-carlos",
  "OLMOS Matthew Paul": "olmos-matthew-paul",
  "OLMS James": "olms-james",
  "OLMSTED Jeff": "olmsted-jeff",
  "OLNECK Madelaine": "olneck-madelaine",
  "OLNEY Nick": "olney-nick",
  "OLNEY Valerie": "olney-valerie",
  "OLOHAN Jack": "olohan-jack",
  "OLORUNTOBA-OJU Taiwo": "oloruntoba-oju-taiwo",
  "O'LOUGHLIN Alister": "o-loughlin-alister",
  "O'LOUGHLIN Em": "o-loughlin-em",
  "O'LOUGHLIN Siobhan": "o-loughlin-siobhan",
  "OLRY Stephane": "olry-stephane",
  "OLSEN Alfa-Betty": "olsen-alfa-betty",
  "OLSEN David": "olsen-david",
  "OLSEN Erik": "olsen-erik",
  "OLSEN Lorraine": "olsen-lorraine",
  "OLSEN Mark James": "olsen-mark-james",
  "OLSEN Mark V": "olsen-mark-v",
  "OLSEN Michael": "olsen-michael",
  "OLSEN Sven": "olsen-sven",
  "OLSEN Thomas W": "olsen-thomas-w",
  "OLSEN Tyler": "olsen-tyler",
  "OLSHANSKY Vladimir": "olshansky-vladimir",
  "OLSHER Laura": "olsher-laura",
  "OLSON Brandon": "olson-brandon",
  "OLSON Donald S": "olson-donald-s",
  "OLSON Doug": "olson-doug",
  "OLSON Ester E": "olson-ester-e",
  "OLSON John": "olson-john",
  "OLSON Joseph Allred": "olson-joseph-allred",
  "OLSON Lauren": "olson-lauren",
  "OLSON Mark": "olson-mark",
  "OLSON Marnie": "olson-marnie",
  "OLSON Neil": "olson-neil",
  "OLSON Paul": "olson-paul",
  "OLSON Phil": "olson-phil",
  "OLSON Richard Arthur": "olson-richard-arthur",
  "OLSON Thomas W": "olson-thomas-w",
  "OLSON Todd": "olson-todd",
  "OLSON Tyler": "olson-tyler",
  "OLSONI Kristen": "olsoni-kristen",
  "OLSSON Linda": "olsson-linda",
  "OLTHOF Linda": "olthof-linda",
  "OLTRA Vanessa": "oltra-vanessa",
  "OLUGWU Mewe": "olugwu-mewe",
  "OLWAGON Christiaan": "olwagon-christiaan",
  "OLYSLAEGERS Jeroen": "olyslaegers-jeroen",
  "O'MALLEY Fiona": "o-malley-fiona",
  "O'MALLEY Gerry": "o-malley-gerry",
  "O'MALLEY Glyn": "o-malley-glyn",
  "O'MALLEY Margaret": "o-malley-margaret",
  "O'MALLEY Mary": "o-malley-mary",
  "O'MALLEY Mike": "o-malley-mike",
  "O'MALLEY Sean T C": "o-malley-sean-t-c",
  "O'MALLEY Sybil": "o-malley-sybil",
  "O'MALLEY Tom": "o-malley-tom",
  "OMAN Severin": "oman-severin",
  "OMAR Cosh": "omar-cosh",
  "O'MARA Aisling": "o-mara-aisling",
  "OMARI Mariem": "omari-mariem",
  "OMATA Garrett H": "omata-garrett-h",
  "OMCHERI ": "omcheri",
  "OMDAHL Joel": "omdahl-joel",
  "OMIELAN Luisa": "omielan-luisa",
  "OMLIE Lisa": "omlie-lisa",
  "OMMANEY Lisa": "ommaney-lisa",
  "OMOROTIONMWAN Philana": "omorotionmwan-philana",
  "O'MORRISON Kevin": "o-morrison-kevin",
  "ON THE RUN ": "on-the-run",
  "O'NAN Ryan": "o-nan-ryan",
  "ONASHILE Adura": "onashile-adura",
  "ONBEKEND ": "onbekend",
  "ONBEKENDE Onbekend": "onbekende-onbekend",
  "ONDAATJE Michael": "ondaatje-michael",
  "ONDREJCAK Andrew": "ondrejcak-andrew",
  "ONE YELLOW RABBIT ": "one-yellow-rabbit",
  "O'NEAL Charles": "o-neal-charles",
  "O'NEAL Christopher": "o-neal-christopher",
  "O'NEAL James": "o-neal-james",
  "O'NEAL John": "o-neal-john",
  "O'NEAL Q": "o-neal-q",
  "O'NEAL S Denise": "o-neal-s-denise",
  "O'NEAL Shellie Kaye": "o-neal-shellie-kaye",
  "O'NEIL Dan": "o-neil-dan",
  "O'NEIL Mark": "o-neil-mark",
  "O'NEIL Miles": "o-neil-miles",
  "O'NEIL Patrick S": "o-neil-patrick-s",
  "O'NEIL Roy": "o-neil-roy",
  "O'NEIL Russell": "o-neil-russell",
  "O'NEIL Sean": "o-neil-sean",
  "O'NEIL Terrence": "o-neil-terrence",
  "O'NEIL Tom": "o-neil-tom",
  "O'NEIL William": "o-neil-william",
  "O'NEILL Brian": "o-neill-brian",
  "O'NEILL Cally": "o-neill-cally",
  "O'NEILL Catherine M": "o-neill-catherine-m",
  "O'NEILL Cecily": "o-neill-cecily",
  "O'NEILL Charles": "o-neill-charles",
  "O'NEILL Charlie": "o-neill-charlie",
  "O'NEILL Chris": "o-neill-chris",
  "O'NEILL Cordelia": "o-neill-cordelia",
  "O'NEILL Deborah": "o-neill-deborah",
  "O'NEILL Ellen": "o-neill-ellen",
  "O'NEILL Erica": "o-neill-erica",
  "O'NEILL Errol": "o-neill-errol",
  "O'NEILL Eugene": "o-neill-eugene",
  "O'NEILL Finnian": "o-neill-finnian",
  "O'NEILL James": "o-neill-james",
  "O'NEILL Jamie": "o-neill-jamie",
  "O'NEILL Jody": "o-neill-jody",
  "O'NEILL Jonathan": "o-neill-jonathan",
  "O'NEILL Karl": "o-neill-karl",
  "O'NEILL Kathleen A": "o-neill-kathleen-a",
  "O'NEILL Lesley Clare": "o-neill-lesley-clare",
  "O'NEILL Matt": "o-neill-matt",
  "O'NEILL Meghan": "o-neill-meghan",
  "O'NEILL Michael": "o-neill-michael",
  "O'NEILL Michael John": "o-neill-michael-john",
  "O'NEILL Nick": "o-neill-nick",
  "O'NEILL Noel": "o-neill-noel",
  "O'NEILL Owen": "o-neill-owen",
  "O'NEILL Randall": "o-neill-randall",
  "O'NEILL Rebecca Gorman": "o-neill-rebecca-gorman",
  "O'NEILL Richard": "o-neill-richard",
  "O'NEILL Richard Rai": "o-neill-richard-rai",
  "O'NEILL Rik": "o-neill-rik",
  "O'NEILL Rob": "o-neill-rob",
  "O'NEILL Robbie": "o-neill-robbie",
  "O'NEILL Rosary": "o-neill-rosary",
  "O'NEILL Russell": "o-neill-russell",
  "O'NEILL Sarah Jane": "o-neill-sarah-jane",
  "O'NEILL Seamus": "o-neill-seamus",
  "O'NEILL Sean": "o-neill-sean",
  "O'NEILL Shannon": "o-neill-shannon",
  "O'NEILL Stacy": "o-neill-stacy",
  "O'NEILL Tee": "o-neill-tee",
  "O'NEILL Terry": "o-neill-terry",
  "O'NEILL Thomas": "o-neill-thomas",
  "O'NEILL Tom": "o-neill-tom",
  "O'NEILL Vanessa": "o-neill-vanessa",
  "O'NEILL-BUTLER Marj": "o-neill-butler-marj",
  "ONEOHONE ": "oneohone",
  "ONETTI Antonio": "onetti-antonio",
  "ONG Han": "ong-han",
  "ONG Henry": "ong-henry",
  "ONG Nicholas": "ong-nicholas",
  "ONG Warren": "ong-warren",
  "ONI Julie Taiwo": "oni-julie-taiwo",
  "ONO Yoko": "ono-yoko",
  "ONODERA Kira": "onodera-kira",
  "ONORI Gianni": "onori-gianni",
  "ONROTT Barbara": "onrott-barbara",
  "ONSTAD Andrea": "onstad-andrea",
  "ONTROEREND GOED ": "ontroerend-goed",
  "ONWUEGBUTE Nduka": "onwuegbute-nduka",
  "ONWUEME Tess O": "onwueme-tess-o",
  "ONWURAH Chi": "onwurah-chi",
  "OOI Mike": "ooi-mike",
  "OOI Yang-May": "ooi-yang-may",
  "OOMEN Anne-Marie": "oomen-anne-marie",
  "OONDATJE Michael": "oondatje-michael",
  "OOSTHUYSEN Willem Stegmann": "oosthuysen-willem-stegmann",
  "OPAREI DeObia": "oparei-deobia",
  "OPATRNY Matthew": "opatrny-matthew",
  "OPELKA Gregg": "opelka-gregg",
  "OPEN CITY ": "open-city",
  "OPEN CLASP THEATRE COMPANY ": "open-clasp-theatre-company",
  "OPEN THEATRE ": "open-theatre",
  "OPENHEIMER JR Max": "openheimer-jr-max",
  "OPENSHAW Charles Elton": "openshaw-charles-elton",
  "OPHABOOM ": "ophaboom",
  "OPIE Jack": "opie-jack",
  "OPPENHEIM Jonas": "oppenheim-jonas",
  "OPPENHEIM Marella": "oppenheim-marella",
  "OPPENHEIM Yoni": "oppenheim-yoni",
  "OPPENHEIMER George": "oppenheimer-george",
  "OPPENHEIMER Jess": "oppenheimer-jess",
  "OPPENHEIMER Joel": "oppenheimer-joel",
  "OPROIU Okathrina": "oproiu-okathrina",
  "OPTRNY Matt": "optrny-matt",
  "ORAM Glynn": "oram-glynn",
  "ORAM Hiawyn": "oram-hiawyn",
  "ORAM Neil": "oram-neil",
  "ORBAN Judith": "orban-judith",
  "ORBAUM Jason": "orbaum-jason",
  "ORBISON Willie": "orbison-willie",
  "ORCHARD Matt": "orchard-matt",
  "ORCHID Ellen": "orchid-ellen",
  "ORCZY Baroness": "orczy-baroness",
  "ORDAZ Evangeline": "ordaz-evangeline",
  "ORDOVER Andrew C": "ordover-andrew-c",
  "ORDWAY Sally": "ordway-sally",
  "ORECK Les": "oreck-les",
  "O'REGAN Alan": "o-regan-alan",
  "O'REGAN Ed": "o-regan-ed",
  "O'REILLY Caitlin": "o-reilly-caitlin",
  "O'REILLY Christian": "o-reilly-christian",
  "O'REILLY Ciaran": "o-reilly-ciaran",
  "O'REILLY James": "o-reilly-james",
  "O'REILLY Kaite": "o-reilly-kaite",
  "O'REILLY Kate": "o-reilly-kate",
  "O'REILLY Kira": "o-reilly-kira",
  "O'REILLY Morgana": "o-reilly-morgana",
  "O'REILLY Niall": "o-reilly-niall",
  "O'REILLY P J": "o-reilly-p-j",
  "O'REILLY Wende": "o-reilly-wende",
  "OREM William": "orem-william",
  "ORENSTEIN Bernie": "orenstein-bernie",
  "ORENSTEIN Ellen": "orenstein-ellen",
  "ORENSTEIN Leo": "orenstein-leo",
  "OREZZOLI Hector": "orezzoli-hector",
  "ORF Kyle": "orf-kyle",
  "ORGAN Scott": "organ-scott",
  "ORGANIC THEATRE COMPANY, THE ": "organic-theatre-company",
  "ORI Lee": "ori-lee",
  "ORIJA Morayo": "orija-morayo",
  "O'RIORDAN Cathal": "o-riordan-cathal",
  "O'RIORDAN Kate": "o-riordan-kate",
  "O'RIORDAN Sean": "o-riordan-sean",
  "ORISTANO Mark": "oristano-mark",
  "ORKENY Istvan": "orkeny-istvan",
  "ORKIN Harvey": "orkin-harvey",
  "ORKOW Ben": "orkow-ben",
  "ORLANDERSMITH Dael": "orlandersmith-dael",
  "ORLANDI Marcus": "orlandi-marcus",
  "ORLANDO Dominic": "orlando-dominic",
  "ORLANDO Michael": "orlando-michael",
  "ORLANDO YOUTH ALLIANCE ": "orlando-youth-alliance",
  "ORLEY Emily": "orley-emily",
  "ORLIKOFF Rachel": "orlikoff-rachel",
  "ORLOCK John": "orlock-john",
  "ORLOFF Penny": "orloff-penny",
  "ORLOFF Rich": "orloff-rich",
  "ORLOV Stephen": "orlov-stephen",
  "ORMANDY Darren": "ormandy-darren",
  "ORME Anthony": "orme-anthony",
  "ORME H G": "orme-h-g",
  "ORMEROD John": "ormerod-john",
  "ORMEROD Nick": "ormerod-nick",
  "ORMISTON Fiona": "ormiston-fiona",
  "ORMOND Derek": "ormond-derek",
  "ORMONT David": "ormont-david",
  "ORMROD Phil": "ormrod-phil",
  "ORMSBY Alan": "ormsby-alan",
  "ORMSBY Phil": "ormsby-phil",
  "ORMSBY Rob": "ormsby-rob",
  "ORNADEL Cyril": "ornadel-cyril",
  "ORNDORFF Elizabeth": "orndorff-elizabeth",
  "ORNSTEIN J Alan": "ornstein-j-alan",
  "ORNSTEIN Tess R": "ornstein-tess-r",
  "ORONACHER Karen": "oronacher-karen",
  "OROPEZA Luis": "oropeza-luis",
  "O'RORK Denny": "o-rork-denny",
  "OROSKO Kirsty": "orosko-kirsty",
  "O'ROURKE Eamon": "o-rourke-eamon",
  "O'ROURKE P J": "o-rourke-p-j",
  "O'ROURKE Stephen": "o-rourke-stephen",
  "O'ROWE Mark": "o-rowe-mark",
  "OROZCO Beverly": "orozco-beverly",
  "OROZCO Hiram": "orozco-hiram",
  "ORR Anne Davey": "orr-anne-davey",
  "ORR Christine": "orr-christine",
  "ORR Elizabeth": "orr-elizabeth",
  "ORR Helen": "orr-helen",
  "ORR Jill": "orr-jill",
  "ORR John": "orr-john",
  "ORR Leonard H": "orr-leonard-h",
  "ORR Mary": "orr-mary",
  "ORR Megan": "orr-megan",
  "ORR Stuart": "orr-stuart",
  "ORR William": "orr-william",
  "ORRIOS Angel Gil": "orrios-angel-gil",
  "ORSLAND Chuck": "orsland-chuck",
  "ORTA Marisela Trevino": "orta-marisela-trevino",
  "ORTARDO Victor": "ortardo-victor",
  "ORTEGA Melody": "ortega-melody",
  "ORTESE Rebecca": "ortese-rebecca",
  "ORTHAL Cindy": "orthal-cindy",
  "ORTI Pilar": "orti-pilar",
  "ORTIZ Deborah Louise": "ortiz-deborah-louise",
  "ORTIZ James": "ortiz-james",
  "ORTIZ Lourdes": "ortiz-lourdes",
  "ORTIZ Santiago": "ortiz-santiago",
  "ORTIZ Tareke": "ortiz-tareke",
  "ORTIZ-PINATE Milta Iliana": "ortiz-pinate-milta-iliana",
  "ORTON Daisy": "orton-daisy",
  "ORTON Joe": "orton-joe",
  "ORTON Kimberley": "orton-kimberley",
  "ORTON Leslie": "orton-leslie",
  "ORTWEIN Terrance": "ortwein-terrance",
  "ORWELL Sonia": "orwell-sonia",
  "ORWIN Louise": "orwin-louise",
  "O'RYAN Conley": "o-ryan-conley",
  "ORYSHCHUK Nataliya": "oryshchuk-nataliya",
  "OSADIA ": "osadia",
  "OSAKWE Chima": "osakwe-chima",
  "OSATO Una Aya": "osato-una-aya",
  "OSBALDERSTON Jon": "osbalderston-jon",
  "OSBORN Louise": "osborn-louise",
  "OSBORN Matthew": "osborn-matthew",
  "OSBORN Paul": "osborn-paul",
  "OSBORN Tom": "osborn-tom",
  "OSBORNE Alan": "osborne-alan",
  "OSBORNE Charles": "osborne-charles",
  "OSBORNE Charles (1)": "osborne-charles-1",
  "OSBORNE Claudia": "osborne-claudia",
  "OSBORNE Hugh": "osborne-hugh",
  "OSBORNE Jason Dietz": "osborne-jason-dietz",
  "OSBORNE Jimmy": "osborne-jimmy",
  "OSBORNE John": "osborne-john",
  "OSBORNE John (1)": "osborne-john-1",
  "OSBORNE Joseph": "osborne-joseph",
  "OSBORNE Julia": "osborne-julia",
  "OSBORNE Melissa": "osborne-melissa",
  "OSBORNE Natalie": "osborne-natalie",
  "OSBORNE Nigel": "osborne-nigel",
  "OSBORNE Paul": "osborne-paul",
  "OSBORNE Rebecca": "osborne-rebecca",
  "OSBORNE Richard": "osborne-richard",
  "OSBORNE Roger": "osborne-roger",
  "OSBORNE Ron": "osborne-ron",
  "OSBORNE Tony": "osborne-tony",
  "OSBORNE Will": "osborne-will",
  "OSBORNE HUGHES John": "osborne-hughes-john",
  "OSBORN-LEE Azure D": "osborn-lee-azure-d",
  "OSBOURN Louise": "osbourn-louise",
  "OSBOURNE Jimmy": "osbourne-jimmy",
  "OSBOURNE Lloyd": "osbourne-lloyd",
  "OSCAR MIKE ": "oscar-mike",
  "OSEI-KUFFOUR Stacy": "osei-kuffour-stacy",
  "OSER Janice Auritt": "oser-janice-auritt",
  "OSGOOD Lawrence": "osgood-lawrence",
  "OSGOOD Nathan": "osgood-nathan",
  "O'SHAUGHNESSY Barunka": "o-shaughnessy-barunka",
  "O'SHAUGHNESSY Christopher": "o-shaughnessy-christopher",
  "O'SHAUGHNESSY Essie": "o-shaughnessy-essie",
  "O'SHAUGHNESSY Peter": "o-shaughnessy-peter",
  "O'SHEA Andrea": "o-shea-andrea",
  "O'SHEA Brendan": "o-shea-brendan",
  "O'SHEA Catherine": "o-shea-catherine",
  "O'SHEA Colm": "o-shea-colm",
  "O'SHEA Erin M": "o-shea-erin-m",
  "O'SHEA Gerard": "o-shea-gerard",
  "O'SHEA Heather": "o-shea-heather",
  "O'SHEA James": "o-shea-james",
  "O'SHEA Jennifer": "o-shea-jennifer",
  "O'SHEA John Donald": "o-shea-john-donald",
  "O'SHEA Marie Glancy": "o-shea-marie-glancy",
  "O'SHEA Shawn": "o-shea-shawn",
  "OSHO Andi": "osho-andi",
  "OSHODI Maria": "oshodi-maria",
  "OSIO Elaine": "osio-elaine",
  "OSIRIS Carlos": "osiris-carlos",
  "OSMAN Matthew": "osman-matthew",
  "OSMAN Nils": "osman-nils",
  "OSMENT Philip": "osment-philip",
  "OSMOND Adrian": "osmond-adrian",
  "OSMOND Gemma": "osmond-gemma",
  "OSMOND Gordon": "osmond-gordon",
  "OSMUNDSEN Dave": "osmundsen-dave",
  "OSNER Nigel": "osner-nigel",
  "OSOFISAN Femi": "osofisan-femi",
  "OSOFSKY Randy": "osofsky-randy",
  "OSORIO Pepon": "osorio-pepon",
  "OSPA Jon": "ospa-jon",
  "OSSA Felipe": "ossa-felipe",
  "OSSMAN A": "ossman-a",
  "OST Bob": "ost-bob",
  "OSTEN Suzanne": "osten-suzanne",
  "OSTER Michael": "oster-michael",
  "OSTER Tom": "oster-tom",
  "OSTERGREN Anna": "ostergren-anna",
  "OSTERMAIAR Albert": "ostermaiar-albert",
  "OSTERMAN Georg": "osterman-georg",
  "OSTREGA Jennifer": "ostrega-jennifer",
  "OSTROFF Alan": "ostroff-alan",
  "OSTROVSKY Alexander Nikolayevich": "ostrovsky-alexander-nikolayevich",
  "OSUCH Paul": "osuch-paul",
  "O'SULLIVAN Aileen": "o-sullivan-aileen",
  "O'SULLIVAN Alannah": "o-sullivan-alannah",
  "O'SULLIVAN Camille": "o-sullivan-camille",
  "O'SULLIVAN Ciara": "o-sullivan-ciara",
  "O'SULLIVAN Conor": "o-sullivan-conor",
  "O'SULLIVAN David": "o-sullivan-david",
  "O'SULLIVAN Evan": "o-sullivan-evan",
  "O'SULLIVAN Jennifer": "o-sullivan-jennifer",
  "O'SULLIVAN Kathleen": "o-sullivan-kathleen",
  "O'SULLIVAN Kathryn": "o-sullivan-kathryn",
  "O'SULLIVAN Lawrence": "o-sullivan-lawrence",
  "O'SULLIVAN Margaret": "o-sullivan-margaret",
  "O'SULLIVAN Matthew": "o-sullivan-matthew",
  "O'SULLIVAN Neil": "o-sullivan-neil",
  "O'SULLIVAN Nuala": "o-sullivan-nuala",
  "O'SULLIVAN Patrick": "o-sullivan-patrick",
  "O'SULLIVAN Richie": "o-sullivan-richie",
  "O'SULLIVAN Sam": "o-sullivan-sam",
  "O'SULLIVAN Stephen": "o-sullivan-stephen",
  "O'SULLIVAN Tom": "o-sullivan-tom",
  "O'SULLIVAN Vincent": "o-sullivan-vincent",
  "OSWALD Andrew": "oswald-andrew",
  "OSWALD Debra": "oswald-debra",
  "OSWALD Peter": "oswald-peter",
  "OSWALD Sally": "oswald-sally",
  "OSWALD Sylvan": "oswald-sylvan",
  "OSWALT Trevor": "oswalt-trevor",
  "OSWICK Ralph": "oswick-ralph",
  "OSWIN Cindy": "oswin-cindy",
  "OSWIN Leigh": "oswin-leigh",
  "OSZTREICHER Stephanie": "osztreicher-stephanie",
  "OTALVARO-HORMILLOSA Gigi": "otalvaro-hormillosa-gigi",
  "OTANO Brian": "otano-brian",
  "OTERO Felix": "otero-felix",
  "OTERO Nairoby": "otero-nairoby",
  "OTFINOSKI Steven": "otfinoski-steven",
  "OTHEN Duncan": "othen-duncan",
  "OTHER WAY WORKS ": "other-way-works",
  "OTHERS CLUB, THE ": "others-club",
  "O'THOMAS Mark": "o-thomas-mark",
  "OTIS Frank": "otis-frank",
  "OTIS Marilyn": "otis-marilyn",
  "O'TOOLE Austin": "o-toole-austin",
  "O'TOOLE Bet": "o-toole-bet",
  "O'TOOLE Esther": "o-toole-esther",
  "O'TOOLE James D B": "o-toole-james-d-b",
  "O'TOOLE John": "o-toole-john",
  "OTT Doyle": "ott-doyle",
  "OTT Gustavo": "ott-gustavo",
  "OTT J": "ott-j",
  "OTT John": "ott-john",
  "OTTANO Brian": "ottano-brian",
  "OTTE Charles": "otte-charles",
  "OTTEY Elma": "ottey-elma",
  "OTTO Rebecca B": "otto-rebecca-b",
  "OTTOSON Andy": "ottoson-andy",
  "OTWAY Travers": "otway-travers",
  "OUCHI Mieko": "ouchi-mieko",
  "OUELLETTE Joey": "ouellette-joey",
  "OULD Herman": "ould-herman",
  "OULTON Brian": "oulton-brian",
  "OURIQUE Lena": "ourique-lena",
  "OUSELLAM Naoufal": "ousellam-naoufal",
  "OUSSOREN Joanne": "oussoren-joanne",
  "OUTHOUSE PRODUCTIONS ": "outhouse-productions",
  "OUTLAN Anne": "outlan-anne",
  "OUTLAW Paul": "outlaw-paul",
  "OUTRAM Michelle": "outram-michelle",
  "OUTSIDE EDGE ": "outside-edge",
  "OUTWARDBOUND PROJET ": "outwardbound-projet",
  "OUTZEN Martin": "outzen-martin",
  "OUZOUNIAN Richard": "ouzounian-richard",
  "OUZOUNIDIS Christina": "ouzounidis-christina",
  "OVAL THEATRE GROUP OF LONDON ": "oval-theatre-group-of-london",
  "O'VALLE Violet": "o-valle-violet",
  "OVER THE EDGE ": "over-the-edge",
  "OVERBEY Kellie": "overbey-kellie",
  "OVERETT Adam": "overett-adam",
  "OVERMAN Sarah": "overman-sarah",
  "OVERMYER Eric": "overmyer-eric",
  "OVERSTREET Joe": "overstreet-joe",
  "OVERTON Bill": "overton-bill",
  "OVERTON David": "overton-david",
  "OVERTON Josh": "overton-josh",
  "OVERTON M": "overton-m",
  "OVERTON Marq": "overton-marq",
  "OVERTON Shawn": "overton-shawn",
  "OVERTREE Lee": "overtree-lee",
  "OWA ": "owa",
  "OWAD Steven": "owad-steven",
  "OWEN Alexander": "owen-alexander",
  "OWEN Alun": "owen-alun",
  "OWEN Amanda": "owen-amanda",
  "OWEN Armitage": "owen-armitage",
  "OWEN Ashleigh": "owen-ashleigh",
  "OWEN Beccy": "owen-beccy",
  "OWEN Bill": "owen-bill",
  "OWEN Bryan": "owen-bryan",
  "OWEN Carmel": "owen-carmel",
  "OWEN Chris": "owen-chris",
  "OWEN Christopher": "owen-christopher",
  "OWEN David": "owen-david",
  "OWEN Debbie": "owen-debbie",
  "OWEN Dilys": "owen-dilys",
  "OWEN E W": "owen-e-w",
  "OWEN Edward": "owen-edward",
  "OWEN Eluned": "owen-eluned",
  "OWEN Gabriel": "owen-gabriel",
  "OWEN Gareth": "owen-gareth",
  "OWEN Gary": "owen-gary",
  "OWEN George P": "owen-george-p",
  "OWEN Gregory J": "owen-gregory-j",
  "OWEN Harrison": "owen-harrison",
  "OWEN John": "owen-john",
  "OWEN John Glyn": "owen-john-glyn",
  "OWEN Jonathan": "owen-jonathan",
  "OWEN Kari Ann": "owen-kari-ann",
  "OWEN Katy": "owen-katy",
  "OWEN Ken": "owen-ken",
  "OWEN Laura": "owen-laura",
  "OWEN Luke": "owen-luke",
  "OWEN Lyla Hay": "owen-lyla-hay",
  "OWEN Mari Rhian": "owen-mari-rhian",
  "OWEN Mark": "owen-mark",
  "OWEN Matt": "owen-matt",
  "OWEN Rena": "owen-rena",
  "OWEN Richard": "owen-richard",
  "OWEN Robert": "owen-robert",
  "OWEN Sally": "owen-sally",
  "OWEN Sarah": "owen-sarah",
  "OWEN Sian": "owen-sian",
  "OWEN Susannah": "owen-susannah",
  "OWEN Will": "owen-will",
  "OWEN Will (1)": "owen-will-1",
  "OWEN Wynford Ellis": "owen-wynford-ellis",
  "OWENS Daniel W": "owens-daniel-w",
  "OWENS Greg": "owens-greg",
  "OWENS Ian Scott": "owens-ian-scott",
  "OWENS Jon Tyler": "owens-jon-tyler",
  "OWENS Jordana": "owens-jordana",
  "OWENS Kristopher": "owens-kristopher",
  "OWENS Lisa": "owens-lisa",
  "OWENS Robert": "owens-robert",
  "OWENS Rochelle": "owens-rochelle",
  "OWENS Ron": "owens-ron",
  "OWENS Sean": "owens-sean",
  "OWENS Sian": "owens-sian",
  "OWENS Stacia Saint": "owens-stacia-saint",
  "OWEN-WRIGHT Hannah": "owen-wright-hannah",
  "OWINGS Adrianne": "owings-adrianne",
  "OWREN Cate": "owren-cate",
  "OWUSU Martin": "owusu-martin",
  "OWUSU Nadia": "owusu-nadia",
  "OXENBOULD Jamie": "oxenbould-jamie",
  "OXFORD STAGE COMPANY ": "oxford-stage-company",
  "OXLEY Stephen": "oxley-stephen",
  "OXMAN Mark": "oxman-mark",
  "OYA Berkun": "oya-berkun",
  "OYAMA Sachi": "oyama-sachi",
  "OYAMO Ujamaa": "oyamo-ujamaa",
  "OYEDELE Obamola": "oyedele-obamola",
  "OYEDEPO Stella": "oyedepo-stella",
  "OYEN Alan": "oyen-alan",
  "OYEN Alexander Sage": "oyen-alexander-sage",
  "OYEWOLE Abiodun": "oyewole-abiodun",
  "OYEYEMI Helen": "oyeyemi-helen",
  "OYONO-MBIA Guillaume": "oyono-mbia-guillaume",
  "OZ Milo J": "oz-milo-j",
  "OZANICH David": "ozanich-david",
  "OZAWA Matthew": "ozawa-matthew",
  "OZBILGIN Handan": "ozbilgin-handan",
  "OZDOGRU Nuvit": "ozdogru-nuvit",
  "OZHABES Ozlem": "ozhabes-ozlem",
  "OZNIE Loren": "oznie-loren",
};
