export default {
  "TA Bihn Duy": "ta-bihn-duy",
  "TA TA DI DI TEATRO ": "ta-ta-di-di-teatro",
  "TABATABAI-KHATAMBAKHSH Nazli": "tabatabai-khatambakhsh-nazli",
  "TABATCHNICK Ian": "tabatchnick-ian",
  "TABELLIONE Keith": "tabellione-keith",
  "TABER Miles": "taber-miles",
  "TABER Richard": "taber-richard",
  "TABERN Peter": "tabern-peter",
  "TABERNER Stephen": "taberner-stephen",
  "TABIT Ramez": "tabit-ramez",
  "TABLO ": "tablo",
  "TABNICK Jeff": "tabnick-jeff",
  "TABORI George": "tabori-george",
  "TABORSKI Boleslaw": "taborski-boleslaw",
  "TACKETT Caren": "tackett-caren",
  "TACON Frederic": "tacon-frederic",
  "TACUHER Rozanne": "tacuher-rozanne",
  "TADMAN Betty": "tadman-betty",
  "TADROS Evelyn": "tadros-evelyn",
  "TAEGEL Mary Jane": "taegel-mary-jane",
  "T'AE-SOK Oh": "tae-sok-oh",
  "TAFEEN D": "tafeen-d",
  "TAFFETY PUNK THEATRE COMPANY ": "taffety-punk-theatre-company",
  "TAFT Thomas Woodall": "taft-thomas-woodall",
  "TAG TEATRO ": "tag-teatro",
  "TAG THEATRE ": "tag-theatre",
  "TAGG Kathleen": "tagg-kathleen",
  "TAGG Nick": "tagg-nick",
  "TAGGART Andrew": "taggart-andrew",
  "TAGGART Brian": "taggart-brian",
  "TAGGART Bronagh": "taggart-bronagh",
  "TAGGART Tom": "taggart-tom",
  "TAGHAVI Bita": "taghavi-bita",
  "TAGOE Ben": "tagoe-ben",
  "TAGORE Rabindranath": "tagore-rabindranath",
  "TAHA Dalia": "taha-dalia",
  "TAHN Andras": "tahn-andras",
  "TAIKEFF Stanley": "taikeff-stanley",
  "TAILO Edessa": "tailo-edessa",
  "TAINSH Jean": "tainsh-jean",
  "TAIRA Jennifer": "taira-jennifer",
  "TAIT James Fagan": "tait-james-fagan",
  "TAIT Lance": "tait-lance",
  "TAIT Melanie": "tait-melanie",
  "TAIT Paul": "tait-paul",
  "TAIT Peta": "tait-peta",
  "TAIT R Colin": "tait-r-colin",
  "TAITT Brandon": "taitt-brandon",
  "TAKACS Jeff": "takacs-jeff",
  "TAKAHASHI Suzi": "takahashi-suzi",
  "TAKAHASHI Yasunari": "takahashi-yasunari",
  "TAKAYA Ted T": "takaya-ted-t",
  "TAKEDA Suz": "takeda-suz",
  "TAKEI Kei": "takei-kei",
  "TAKENAKA Ro": "takenaka-ro",
  "TAKESHITA Vernon": "takeshita-vernon",
  "TAKLE Darrien": "takle-darrien",
  "TAL Adina": "tal-adina",
  "TALARICO Joseph": "talarico-joseph",
  "TALAVERA Richard": "talavera-richard",
  "TALAWA ": "talawa",
  "TALBERTH Kenneth": "talberth-kenneth",
  "TALBOT A J": "talbot-a-j",
  "TALBOT Charlie": "talbot-charlie",
  "TALBOT Pete": "talbot-pete",
  "TALBOT Richard": "talbot-richard",
  "TALBOT Scott": "talbot-scott",
  "TALBOT Sharon": "talbot-sharon",
  "TALBOT Sharon Taylor": "talbot-sharon-taylor",
  "TALBOT Story": "talbot-story",
  "TALBOTT Chris": "talbott-chris",
  "TALBOTT Daniel": "talbott-daniel",
  "TALBOTT Jeff": "talbott-jeff",
  "TALBUTT Lotty": "talbutt-lotty",
  "TALENT King": "talent-king",
  "TALENTI Francesca": "talenti-francesca",
  "TALEON-SONZA Jorshinelle": "taleon-sonza-jorshinelle",
  "TALGAROW Michelle": "talgarow-michelle",
  "TALIBAM! ": "talibam",
  "TALIJANCIC Ivan": "talijancic-ivan",
  "TALK Dorothy": "talk-dorothy",
  "TALKING BAND, THE ": "talking-band",
  "TALKING BIRDS THEATRE COMPANY ": "talking-birds-theatre-company",
  "TALKING PICTURES ": "talking-pictures",
  "TALKING TONGUES ": "talking-tongues",
  "TALKINGTON Marilee": "talkington-marilee",
  "TALL POPPEAS ": "tall-poppeas",
  "TALL STORIES ": "tall-stories",
  "TALLEN Ben": "tallen-ben",
  "TALLEY David": "talley-david",
  "TALLEY Frank": "talley-frank",
  "TALLEY Kevin": "talley-kevin",
  "TALLIS Frank": "tallis-frank",
  "TALLMAN Jim": "tallman-jim",
  "TALLMAN Randolph": "tallman-randolph",
  "TALLY Ted": "tally-ted",
  "TALLYRAND J B": "tallyrand-j-b",
  "TALMADGE Victor": "talmadge-victor",
  "TALMAN Eilidh": "talman-eilidh",
  "TALMAN Martha Ann": "talman-martha-ann",
  "TALMAN Pete": "talman-pete",
  "TALVE Arava": "talve-arava",
  "TALWAR Rajesh": "talwar-rajesh",
  "TAM TAM THEATRE ": "tam-tam-theatre",
  "TAMAKI Marika": "tamaki-marika",
  "TAMARIBUCHI Peter": "tamaribuchi-peter",
  "TAMASHA ": "tamasha",
  "TAMAYO Manny": "tamayo-manny",
  "TAMAYO Vanessa": "tamayo-vanessa",
  "TAMBLYN Ian": "tamblyn-ian",
  "TAMBORELLO Joe": "tamborello-joe",
  "TAMBORNINO Jeff": "tambornino-jeff",
  "TAMBORRA Lia": "tamborra-lia",
  "TAMBURINO Robert": "tamburino-robert",
  "TAMEZ Frank": "tamez-frank",
  "TAMLER Cory": "tamler-cory",
  "TAMMANY Susan": "tammany-susan",
  "TAMMI Tom": "tammi-tom",
  "TAMPIERI Susana": "tampieri-susana",
  "TAMS Emmett": "tams-emmett",
  "TAN Dora": "tan-dora",
  "TAN Joel": "tan-joel",
  "TAN Joel (1)": "tan-joel-1",
  "TAN Kelvin": "tan-kelvin",
  "TANAHASHI Hiroko": "tanahashi-hiroko",
  "TANAKA Chikao": "tanaka-chikao",
  "TANAKA Nin": "tanaka-nin",
  "TANAKA Yumiko": "tanaka-yumiko",
  "TANCHAREON Maurissa": "tanchareon-maurissa",
  "TANCOCK L W": "tancock-l-w",
  "TANCREDI Dominic R": "tancredi-dominic-r",
  "TANDAVANIT J Nick": "tandavanit-j-nick",
  "TANDOC-PICHEREAU Michelle": "tandoc-pichereau-michelle",
  "TANDY Stephanie": "tandy-stephanie",
  "TANENBAUM Isaiah": "tanenbaum-isaiah",
  "TANENBAUM Steven": "tanenbaum-steven",
  "TANER Haldun": "taner-haldun",
  "TANEY Retta": "taney-retta",
  "TANG Ken": "tang-ken",
  "TANG Lisa": "tang-lisa",
  "TANG Roger": "tang-roger",
  "TANGERDING Axel": "tangerding-axel",
  "TANGLAO-AQUAS Francis": "tanglao-aquas-francis",
  "TANGLED FEET ": "tangled-feet",
  "TANGREDI Frank": "tangredi-frank",
  "TANIS T C": "tanis-t-c",
  "TANITCH Robert": "tanitch-robert",
  "TANITH Mij": "tanith-mij",
  "TANKARD Meryl": "tankard-meryl",
  "TANKUS Edith": "tankus-edith",
  "TANKUS Nelle": "tankus-nelle",
  "TANNA Kiran": "tanna-kiran",
  "TANNAHILL Edward": "tannahill-edward",
  "TANNAHILL Jordan": "tannahill-jordan",
  "TANNEN Deborah": "tannen-deborah",
  "TANNEN Lee": "tannen-lee",
  "TANNENBAUM Jay": "tannenbaum-jay",
  "TANNER Chris": "tanner-chris",
  "TANNER Jim": "tanner-jim",
  "TANNER Justin": "tanner-justin",
  "TANNER Lian": "tanner-lian",
  "TANNER Rebecca": "tanner-rebecca",
  "TANNER Richard": "tanner-richard",
  "TANNER Tony": "tanner-tony",
  "TANNER Vickie": "tanner-vickie",
  "TANOVIC Tajna": "tanovic-tajna",
  "TANSEY June": "tansey-june",
  "TANTALO Joe": "tantalo-joe",
  "TANTALUS ": "tantalus",
  "TANTINA Pera": "tantina-pera",
  "TANVIR Ad Habib": "tanvir-ad-habib",
  "TANZABEL Nicole": "tanzabel-nicole",
  "TAPIA Jose": "tapia-jose",
  "TAPPAN Don": "tappan-don",
  "TAPPENDEN Jean": "tappenden-jean",
  "TAPPER Albert M": "tapper-albert-m",
  "TARA ": "tara",
  "TARANTO Paul": "taranto-paul",
  "TARATULA Philip": "taratula-philip",
  "TARAZEVITS Scott": "tarazevits-scott",
  "TARBELL Shirley": "tarbell-shirley",
  "TARBESCU Edith": "tarbescu-edith",
  "TARBOX Constance": "tarbox-constance",
  "TARDI Mark": "tardi-mark",
  "TARDIEU Jean": "tardieu-jean",
  "TARETT Carly": "tarett-carly",
  "TARGET MARGIN THEATER ": "target-margin-theater",
  "TARGUSE Vera": "targuse-vera",
  "TARJAN Karen": "tarjan-karen",
  "TARKAN Joshua": "tarkan-joshua",
  "TARKENTER Dave": "tarkenter-dave",
  "TARKER Kate": "tarker-kate",
  "TARKINGTON Booth": "tarkington-booth",
  "TARLIN Jona": "tarlin-jona",
  "TARLO Luna": "tarlo-luna",
  "TARLOFF Frank": "tarloff-frank",
  "TARLTON Jack": "tarlton-jack",
  "TARNAWSKY Nadia": "tarnawsky-nadia",
  "TARNOWSKI Stefan": "tarnowski-stefan",
  "TARRAB nat": "tarrab-nat",
  "TARRETT Carly": "tarrett-carly",
  "TARSKA Eugenia": "tarska-eugenia",
  "TARTAGLIA John": "tartaglia-john",
  "TARVER Ben": "tarver-ben",
  "TARZIOURA Miora": "tarzioura-miora",
  "TASANE Steve": "tasane-steve",
  "TASCA Ed": "tasca-ed",
  "TASCA Jules": "tasca-jules",
  "TASDANCE ": "tasdance",
  "TASHEVA Julia": "tasheva-julia",
  "TASHIRO Kikue": "tashiro-kikue",
  "TASHJIAN Gordon": "tashjian-gordon",
  "TASSI Aldo": "tassi-aldo",
  "TASSO Torquato": "tasso-torquato",
  "TATE Greg": "tate-greg",
  "TATE Joan": "tate-joan",
  "TATE Judy": "tate-judy",
  "TATE Vicky": "tate-vicky",
  "TATE-MANNING Anya": "tate-manning-anya",
  "TATHAM Lew": "tatham-lew",
  "TATLOCK Alison": "tatlock-alison",
  "TATTE Jaan": "tatte-jaan",
  "TATTENBAUM-FINE Emma": "tattenbaum-fine-emma",
  "TATUM James": "tatum-james",
  "TATUM Trey": "tatum-trey",
  "TAUB Michael": "taub-michael",
  "TAUB Shaina": "taub-shaina",
  "TAUB Yermiyahu Ahron": "taub-yermiyahu-ahron",
  "TAUBER Chaim": "tauber-chaim",
  "TAUBMAN Adina": "taubman-adina",
  "TAUDEVIN A J": "taudevin-a-j",
  "TAUFER Vito": "taufer-vito",
  "TAUREL Douglas": "taurel-douglas",
  "TAURISANO Marc": "taurisano-marc",
  "TAUSER Diane": "tauser-diane",
  "TAVANA Daria": "tavana-daria",
  "TAVEL Ronald": "tavel-ronald",
  "TAVENER John": "tavener-john",
  "TAVIANI Paolo": "taviani-paolo",
  "TAVIANI Vittorio": "taviani-vittorio",
  "TAW Harold": "taw-harold",
  "TAWIL Randa": "tawil-randa",
  "TAXI ": "taxi",
  "TAY Jean": "tay-jean",
  "TAYLOR A R": "taylor-a-r",
  "TAYLOR Abigail": "taylor-abigail",
  "TAYLOR Adam": "taylor-adam",
  "TAYLOR Alan C": "taylor-alan-c",
  "TAYLOR Alec": "taylor-alec",
  "TAYLOR Ali": "taylor-ali",
  "TAYLOR Andrew": "taylor-andrew",
  "TAYLOR Andrew Nicholas Compton": "taylor-andrew-nicholas-compton",
  "TAYLOR Ann": "taylor-ann",
  "TAYLOR Ann E": "taylor-ann-e",
  "TAYLOR Anni Lee": "taylor-anni-lee",
  "TAYLOR Anthony": "taylor-anthony",
  "TAYLOR B": "taylor-b",
  "TAYLOR Bernard J": "taylor-bernard-j",
  "TAYLOR Bill": "taylor-bill",
  "TAYLOR Bing": "taylor-bing",
  "TAYLOR C": "taylor-c",
  "TAYLOR Caroline Neisha": "taylor-caroline-neisha",
  "TAYLOR Cecil": "taylor-cecil",
  "TAYLOR Cecil P": "taylor-cecil-p",
  "TAYLOR Charles": "taylor-charles",
  "TAYLOR Charles A": "taylor-charles-a",
  "TAYLOR Chris": "taylor-chris",
  "TAYLOR Christopher": "taylor-christopher",
  "TAYLOR Clark": "taylor-clark",
  "TAYLOR Craig": "taylor-craig",
  "TAYLOR Dan": "taylor-dan",
  "TAYLOR Daniel": "taylor-daniel",
  "TAYLOR Daniel Lawrence": "taylor-daniel-lawrence",
  "TAYLOR Daren": "taylor-daren",
  "TAYLOR David": "taylor-david",
  "TAYLOR David Gobeil": "taylor-david-gobeil",
  "TAYLOR Dean": "taylor-dean",
  "TAYLOR Deanne": "taylor-deanne",
  "TAYLOR Deborah Porter": "taylor-deborah-porter",
  "TAYLOR Diane": "taylor-diane",
  "TAYLOR Dominic": "taylor-dominic",
  "TAYLOR Dominic J": "taylor-dominic-j",
  "TAYLOR Don": "taylor-don",
  "TAYLOR Douglas": "taylor-douglas",
  "TAYLOR Drew": "taylor-drew",
  "TAYLOR Drew Hayden": "taylor-drew-hayden",
  "TAYLOR Dwight": "taylor-dwight",
  "TAYLOR Ed": "taylor-ed",
  "TAYLOR Edward": "taylor-edward",
  "TAYLOR Elizabeth": "taylor-elizabeth",
  "TAYLOR Emily": "taylor-emily",
  "TAYLOR Emory": "taylor-emory",
  "TAYLOR George": "taylor-george",
  "TAYLOR George (1)": "taylor-george-1",
  "TAYLOR Gregg": "taylor-gregg",
  "TAYLOR Heather": "taylor-heather",
  "TAYLOR Helen": "taylor-helen",
  "TAYLOR Henry": "taylor-henry",
  "TAYLOR Hiram": "taylor-hiram",
  "TAYLOR Holland": "taylor-holland",
  "TAYLOR Ian": "taylor-ian",
  "TAYLOR Irma": "taylor-irma",
  "TAYLOR Jack": "taylor-jack",
  "TAYLOR Jackie": "taylor-jackie",
  "TAYLOR James": "taylor-james",
  "TAYLOR Jan": "taylor-jan",
  "TAYLOR Jane": "taylor-jane",
  "TAYLOR Jeanne": "taylor-jeanne",
  "TAYLOR Jeremy": "taylor-jeremy",
  "TAYLOR Jeremy (1)": "taylor-jeremy-1",
  "TAYLOR Jeremy James": "taylor-jeremy-james",
  "TAYLOR Joe": "taylor-joe",
  "TAYLOR Joelle": "taylor-joelle",
  "TAYLOR John": "taylor-john",
  "TAYLOR Jonathan": "taylor-jonathan",
  "TAYLOR Jonathan Lee": "taylor-jonathan-lee",
  "TAYLOR June": "taylor-june",
  "TAYLOR Justin": "taylor-justin",
  "TAYLOR Karen D": "taylor-karen-d",
  "TAYLOR Kelly": "taylor-kelly",
  "TAYLOR Ken": "taylor-ken",
  "TAYLOR Kenneth Alan": "taylor-kenneth-alan",
  "TAYLOR Kressmann": "taylor-kressmann",
  "TAYLOR Larry": "taylor-larry",
  "TAYLOR Leo": "taylor-leo",
  "TAYLOR Liz Fitzgerald": "taylor-liz-fitzgerald",
  "TAYLOR Louise": "taylor-louise",
  "TAYLOR Malcolm (1)": "taylor-malcolm-1",
  "TAYLOR Malcolm (2)": "taylor-malcolm-2",
  "TAYLOR Margaret F": "taylor-margaret-f",
  "TAYLOR Margie": "taylor-margie",
  "TAYLOR Markland": "taylor-markland",
  "TAYLOR Marsali": "taylor-marsali",
  "TAYLOR Martin J": "taylor-martin-j",
  "TAYLOR Matt": "taylor-matt",
  "TAYLOR Matthew": "taylor-matthew",
  "TAYLOR Mavis": "taylor-mavis",
  "TAYLOR Michael": "taylor-michael",
  "TAYLOR Mike": "taylor-mike",
  "TAYLOR Molly": "taylor-molly",
  "TAYLOR Morgan": "taylor-morgan",
  "TAYLOR Pam": "taylor-pam",
  "TAYLOR Patricia": "taylor-patricia",
  "TAYLOR Perry": "taylor-perry",
  "TAYLOR Peter": "taylor-peter",
  "TAYLOR Phoebe": "taylor-phoebe",
  "TAYLOR Ray": "taylor-ray",
  "TAYLOR Regina": "taylor-regina",
  "TAYLOR Renee": "taylor-renee",
  "TAYLOR Rey": "taylor-rey",
  "TAYLOR Richard": "taylor-richard",
  "TAYLOR Richard (1)": "taylor-richard-1",
  "TAYLOR Rob": "taylor-rob",
  "TAYLOR Robert": "taylor-robert",
  "TAYLOR Robert Leland": "taylor-robert-leland",
  "TAYLOR Rod": "taylor-rod",
  "TAYLOR Rodney "Rhoda"": "taylor-rodney-rhoda",
  "TAYLOR Ron": "taylor-ron",
  "TAYLOR Roslyn": "taylor-roslyn",
  "TAYLOR Russell": "taylor-russell",
  "TAYLOR Samuel": "taylor-samuel",
  "TAYLOR Sandy": "taylor-sandy",
  "TAYLOR Sara": "taylor-sara",
  "TAYLOR Scott": "taylor-scott",
  "TAYLOR Scott Marshall": "taylor-scott-marshall",
  "TAYLOR Simon Watson": "taylor-simon-watson",
  "TAYLOR Stayci": "taylor-stayci",
  "TAYLOR Step": "taylor-step",
  "TAYLOR Steve": "taylor-steve",
  "TAYLOR Theo": "taylor-theo",
  "TAYLOR Tom": "taylor-tom",
  "TAYLOR Tom (1)": "taylor-tom-1",
  "TAYLOR Tommy": "taylor-tommy",
  "TAYLOR Tony": "taylor-tony",
  "TAYLOR Venetia": "taylor-venetia",
  "TAYLOR W Allen": "taylor-w-allen",
  "TAYLOR Yana": "taylor-yana",
  "TAYLOR-BROWN Daniel": "taylor-brown-daniel",
  "TAYLOR-CORBETT Lynne": "taylor-corbett-lynne",
  "TAYLOR-ROWAN Joan": "taylor-rowan-joan",
  "TAYLOR-SMITH Kelly": "taylor-smith-kelly",
  "TAYMOR Danya": "taymor-danya",
  "TAYMOR Julie": "taymor-julie",
  "TAYPE ": "taype",
  "TAZEWELL Marlin T": "tazewell-marlin-t",
  "TCHEKHOV Anton": "tchekhov-anton",
  "TCHIAKPE Jennifer": "tchiakpe-jennifer",
  "TCHOREK M": "tchorek-m",
  "TE'A COMPANY, THE ": "te-a-company",
  "TEACEY A H": "teacey-a-h",
  "TEACHOUT Terry": "teachout-terry",
  "TEAGLE Rachel": "teagle-rachel",
  "TEAGUE Anthony": "teague-anthony",
  "TEAGUE Bob": "teague-bob",
  "TEAGUE Tony": "teague-tony",
  "TEAGUE JR Robert": "teague-robert",
  "TEAHAN Mimi": "teahan-mimi",
  "TEALE Leonard": "teale-leonard",
  "TEALE Polly": "teale-polly",
  "TEAM HAPPOU B-ZIN ": "team-happou-b-zin",
  "TEAM THUNDERBIRD ": "team-thunderbird",
  "TEAM, THE ": "team",
  "TEARE Jeff": "teare-jeff",
  "TEARLE David": "tearle-david",
  "TEATR LICEDEI ": "teatr-licedei",
  "TEATRAL YEN ": "teatral-yen",
  "TEATRE NIXTAYOLERO ": "teatre-nixtayolero",
  "TEATRET MOLLEN ": "teatret-mollen",
  "TEATRO Tag": "teatro-tag",
  "TEATRO DE ARTE POPULAR ": "teatro-de-arte-popular",
  "TEATRO DEL CARRETTO ": "teatro-del-carretto",
  "TEATRO DI PIAZZA O D'OCCASIONE ": "teatro-di-piazza-o-d-occasione",
  "TEATRO ENTRE ESCOMBROS ": "teatro-entre-escombros",
  "TEATRO KISMET ": "teatro-kismet",
  "TEATRO LINEA DE SOMBRA ": "teatro-linea-de-sombra",
  "TEATRON COMPANY ": "teatron-company",
  "TEBBUTT Gerry": "tebbutt-gerry",
  "TEBELAK John Michael": "tebelak-john-michael",
  "TEC Roland": "tec-roland",
  "TECER Armet Kutsi": "tecer-armet-kutsi",
  "TECKLENGBURG Nina": "tecklengburg-nina",
  "TEDDER Abi": "tedder-abi",
  "TEDESCHI John": "tedeschi-john",
  "TEDFORD Matthew": "tedford-matthew",
  "TEED Nick": "teed-nick",
  "TEEHAN John Wallace": "teehan-john-wallace",
  "TEEHAN Mimi": "teehan-mimi",
  "TEELE Mike": "teele-mike",
  "TEEMLEY Mitch": "teemley-mitch",
  "TEER Barbara Ann": "teer-barbara-ann",
  "TEETER J R": "teeter-j-r",
  "TEEVAN Colin": "teevan-colin",
  "TEGEL Peter": "tegel-peter",
  "TEGLAS Csaba": "teglas-csaba",
  "TEH Benjamin": "teh-benjamin",
  "TEH-HUI Cheng": "teh-hui-cheng",
  "TEI Chew Siah": "tei-chew-siah",
  "TEICHMANN Howard": "teichmann-howard",
  "TEIGEN Lene Therese": "teigen-lene-therese",
  "TEIRLER Lucy": "teirler-lucy",
  "TEIRSTEIN Andy": "teirstein-andy",
  "TEITEL Jay": "teitel-jay",
  "TEITEL N R": "teitel-n-r",
  "TEITELBAUM Maurice": "teitelbaum-maurice",
  "TEITLER Jeffrey": "teitler-jeffrey",
  "TEITLER Marc": "teitler-marc",
  "TEIXEIRA Cristina": "teixeira-cristina",
  "TEIXEIRA DE MATTOS Alexander": "teixeira-de-mattos-alexander",
  "TEKERIAN Anais Alexandra": "tekerian-anais-alexandra",
  "TELFAR Evangelina": "telfar-evangelina",
  "TELFER George": "telfer-george",
  "TELFER Paul": "telfer-paul",
  "TELL TALE HEARTS ": "tell-tale-hearts",
  "TELLER Dickdon": "teller-dickdon",
  "TELLER Ryan Michael": "teller-ryan-michael",
  "TELLER Zander": "teller-zander",
  "TELLER ": "teller",
  "TELLEZ Marc": "tellez-marc",
  "TELSON Bob": "telson-bob",
  "TELUSHKIN Joseph": "telushkin-joseph",
  "TEMERSON Catherine": "temerson-catherine",
  "TEMKIN Spencer": "temkin-spencer",
  "TEMPELSMAN Cathy": "tempelsman-cathy",
  "TEMPERLEY Stephen": "temperley-stephen",
  "TEMPEST Kate": "tempest-kate",
  "TEMPEST William": "tempest-william",
  "TEMPLE De Lisa": "temple-de-lisa",
  "TEMPLE Dura": "temple-dura",
  "TEMPLE Keith": "temple-keith",
  "TEMPLE Robert": "temple-robert",
  "TEMPLE THEATRE ": "temple-theatre",
  "TEMPLEMAN Eleanor Sy": "templeman-eleanor-sy",
  "TEMPLETON Andrew": "templeton-andrew",
  "TEMPLETON Fiona": "templeton-fiona",
  "TEMPLETON Lindsay": "templeton-lindsay",
  "TEMPLETON William": "templeton-william",
  "TEMPLETON-YOUNG Zoe": "templeton-young-zoe",
  "TEN Ritsaert": "ten-ritsaert",
  "TENDULKAR Vijay": "tendulkar-vijay",
  "TENENBOM Tuvia": "tenenbom-tuvia",
  "TENERIELLO Susan": "teneriello-susan",
  "TENGES Robert": "tenges-robert",
  "TENNANT Carrie": "tennant-carrie",
  "TENNANT K": "tennant-k",
  "TENNANT Kylie": "tennant-kylie",
  "TENNENT Karen": "tennent-karen",
  "TENNERIELLO Susan": "tenneriello-susan",
  "TENNEY Steve": "tenney-steve",
  "TENNISON Helen": "tennison-helen",
  "TENNYSON Izzy": "tennyson-izzy",
  "TENUTO Eva": "tenuto-eva",
  "TEODORO Jose": "teodoro-jose",
  "TEODOSIO Dennis": "teodosio-dennis",
  "TEPLICK Anne": "teplick-anne",
  "TEPPER Albert": "tepper-albert",
  "TEPPER Kirby": "tepper-kirby",
  "TEPPERMAN Julie": "tepperman-julie",
  "TEPPERMAN Shelley": "tepperman-shelley",
  "TEPPETT Finnius": "teppett-finnius",
  "TERAN Andi": "teran-andi",
  "TERAN Cash": "teran-cash",
  "TERAOKA Arlene A": "teraoka-arlene-a",
  "TERAYAMA Shuji": "terayama-shuji",
  "TERCIAN Gracie": "tercian-gracie",
  "TERENCE David": "terence-david",
  "TERENCE Phormio": "terence-phormio",
  "TERENCE Rae": "terence-rae",
  "TERENCE ": "terence",
  "TERERA Giles": "terera-giles",
  "TERESA Brett": "teresa-brett",
  "TERHUNE Edward": "terhune-edward",
  "TERIO Jody": "terio-jody",
  "TERONOVA Tanya": "teronova-tanya",
  "TERPSTRA Koos": "terpstra-koos",
  "TERRANOVA Frank": "terranova-frank",
  "TERRELL Anderson": "terrell-anderson",
  "TERRELL Ken": "terrell-ken",
  "TERRELL Vincent": "terrell-vincent",
  "TERRIAULT Daniel": "terriault-daniel",
  "TERRIS Chelsea": "terris-chelsea",
  "TERRITO Jim": "territo-jim",
  "TERRY Cory": "terry-cory",
  "TERRY Dane": "terry-dane",
  "TERRY John": "terry-john",
  "TERRY Keith": "terry-keith",
  "TERRY Mackenzie": "terry-mackenzie",
  "TERRY Megan": "terry-megan",
  "TERRY Michelle": "terry-michelle",
  "TERRY Rebecca Hope": "terry-rebecca-hope",
  "TERRYN Yahya": "terryn-yahya",
  "TERSMAN Ninna": "tersman-ninna",
  "TERSON Peter": "terson-peter",
  "TESH Jane": "tesh-jane",
  "TESHIGARA Saburo": "teshigara-saburo",
  "TESICH Nadja": "tesich-nadja",
  "TESICH Steve": "tesich-steve",
  "TESORI Jeanine": "tesori-jeanine",
  "TESSLER Gloria": "tessler-gloria",
  "TEST Matt": "test-matt",
  "TESTAMENT ": "testament",
  "TESTER Brian": "tester-brian",
  "TESTER Christopher": "tester-christopher",
  "TESTER Michael": "tester-michael",
  "TETENBAUM Abraham": "tetenbaum-abraham",
  "TETLEY Graeme": "tetley-graeme",
  "TEUBEN Sonia": "teuben-sonia",
  "TEVAL Ronald": "teval-ronald",
  "TEWARI Devang": "tewari-devang",
  "TEWHIU Josephine Stewart": "tewhiu-josephine-stewart",
  "TEWKESBURY Joan": "tewkesbury-joan",
  "TEY Josephine": "tey-josephine",
  "TEZCAN Feri": "tezcan-feri",
  "THACKER David": "thacker-david",
  "THACKER Jonathan": "thacker-jonathan",
  "THACKER Kit": "thacker-kit",
  "THACKER Russ": "thacker-russ",
  "THACKER Russell": "thacker-russell",
  "THACKER William": "thacker-william",
  "THACKERAY Lucy": "thackeray-lucy",
  "THACKERY Dan": "thackery-dan",
  "THAIN Paul": "thain-paul",
  "THAINE Craig": "thaine-craig",
  "THAINE Victoria": "thaine-victoria",
  "THAIN-GRAY Rachel": "thain-gray-rachel",
  "THAKRAR Asaita": "thakrar-asaita",
  "THALER Liz": "thaler-liz",
  "THALHEIMER Norman": "thalheimer-norman",
  "THANATOS Simon": "thanatos-simon",
  "THANE Adele": "thane-adele",
  "THANE John": "thane-john",
  "THARP Twyla": "tharp-twyla",
  "THAT WAS FAST ": "that-was-fast",
  "THATCHER Billy": "thatcher-billy",
  "THATCHER Kristine": "thatcher-kristine",
  "THAUBERGER Rudy": "thauberger-rudy",
  "THAW Morton": "thaw-morton",
  "THAYER Toni K": "thayer-toni-k",
  "THE DRILLING COMPAY NY ": "thedrillingcompany",
  "THE LIONS PART ": "the-lions-part",
  "THEATER ARETMIS ": "theater-aretmis",
  "THEATER OOBLECK, THE ": "theater-oobleck",
  "THEATER SGARAMUSCH ": "theater-sgaramusch",
  "THEATR FFYNNON ": "theatr-ffynnon",
  "THEATR IOLO ": "theatr-iolo",
  "THEATR LICEDEI ": "theatr-licedei",
  "THEATR NA N'OG ": "theatr-na-n-og",
  "THEATR POWYS ": "theatr-powys",
  "THEATR WEST GLAMORGAN ": "theatr-west-glamorgan",
  "THEATRE AD INFINITUM ": "theatre-ad-infinitum",
  "THEATRE AKHE ": "theatre-akhe",
  "THEATRE ALTERNATIVE ": "theatre-alternative",
  "THEATRE ASKEW ": "theatre-askew",
  "THEATRE BEATING ": "theatre-beating",
  "THEATRE BLACK COMPANY ": "theatre-black-company",
  "THEATRE BY DESIGN ": "theatre-by-design",
  "THEATRE COMPANY, THE ": "theatre-company-the",
  "THEATRE CRYPTIC ": "theatre-cryptic",
  "THEATRE DACAPO ": "theatre-dacapo",
  "THEATRE DE COMPLICITE ": "theatre-de-complicite",
  "THEATRE DE CUNT ": "theatre-de-cunt",
  "THEATRE DE LA HIS DE PAIN ": "theatre-de-la-his-de-pain",
  "THEATRE DE LA MANDRAGORE ": "theatre-de-la-mandragore",
  "THEATRE DE L'ABRE ": "theatre-de-l-abre",
  "THEATRE DE L'ANGE FOU ": "theatre-de-l-ange-fou",
  "THEATRE DE L'ATELIER ": "theatre-de-l-atelier",
  "THEATRE DE LE MIE PAIN ": "theatre-de-le-mie-pain",
  "THEATRE DE L'UNITE ": "theatre-de-unite",
  "THEATRE DELICATESSEN ": "theatre-delicatessen",
  "THEATRE DU MOUVEMENT ": "theatre-du-mouvement",
  "THEATRE DU PARTI-PRIS ": "theatre-du-parti-pris",
  "THEATRE DU RADEAU ": "theatre-du-radeau",
  "THEATRE EDIBLE ": "theatre-edible",
  "THEATRE IN CAHOOTS ": "theatre-in-cahoots",
  "THEATRE IN EDUCATION COMPANY ": "theatre-in-education-company",
  "THEATRE LAB ": "theatre-lab",
  "THEATRE LE RANELAGH ": "theatre-le-ranelagh",
  "THEATRE LOZHE ": "theatre-lozhe",
  "THEATRE MANJANA ": "theatre-manjana",
  "THEATRE MITU ": "theatre-mitu",
  "THEATRE MODO ": "theatre-modo",
  "THEATRE MURAILLE ": "theatre-muraille",
  "THEATRE O ": "theatre-o",
  "THEATRE OF IMAGINATION ": "theatre-of-imagination",
  "THEATRE OF MISTAKES ": "theatre-of-mistakes",
  "THEATRE OF THE EIGHTH DAY ": "theatre-of-the-eighth-day",
  "THEATRE OMNIBUS ": "theatre-omnibus",
  "THEATRE PRAPILE ": "theatre-prapile",
  "THEATRE PUR ": "theatre-pur",
  "THEATRE RE ": "theatre-re",
  "THEATRE ROUNDABOUT ": "theatre-roundabout",
  "THEATRE SANS FRONTIERES ": "theatre-sans-frontieres",
  "THEATRE SMITH-GILMOUR ": "theatre-smith-gilmour",
  "THEATRE STATE ": "theatre-state",
  "THEATRE TARQUIN ": "theatre-tarquin",
  "THEATRE TEMOIN ": "theatre-temoin",
  "THEATRE UNDER FIRE ": "theatre-under-fire",
  "THEATRE WHISPERS ": "theatre-whispers",
  "THEATRE WORKSHOP ": "theatre-workshop",
  "THEATREISRAELNEW Creative": "theatreisraelnew-creative",
  "THEATRE-RITES ": "theatre-rites",
  "THEATRESPORTS ": "theatresports",
  "THEBUS Jessica": "thebus-jessica",
  "THEERAKULSTIT Shyaporn": "theerakulstit-shyaporn",
  "THEINER George": "theiner-george",
  "THEIS Jack": "theis-jack",
  "THEIS Mickey": "theis-mickey",
  "THEISSEN Cherie Stewart": "theissen-cherie-stewart",
  "THEKWANA Kgosana": "thekwana-kgosana",
  "THELANDER Barbara K": "thelander-barbara-k",
  "THELIN Carl": "thelin-carl",
  "THELIN Toby": "thelin-toby",
  "THEOBALD Roslyn": "theobald-roslyn",
  "THEODORA Stephie": "theodora-stephie",
  "THEODORAKIS Maria": "theodorakis-maria",
  "THEODORAKIS Mikis": "theodorakis-mikis",
  "THEODORE Bobby": "theodore-bobby",
  "THEODORE Shank": "theodore-shank",
  "THEODORIDIS George": "theodoridis-george",
  "THEODOROU Michael": "theodorou-michael",
  "THEODOROU Patricia": "theodorou-patricia",
  "THERRIAULT Daniel": "therriault-daniel",
  "THERRIEN Joseph Jonah": "therrien-joseph-jonah",
  "THEVENOT Shelby": "thevenot-shelby",
  "THIAM Bamba": "thiam-bamba",
  "THIARAI Kully": "thiarai-kully",
  "THIBAUD Patrice": "thibaud-patrice",
  "THIBAULT Anne": "thibault-anne",
  "THIBODEAUX Sandra": "thibodeaux-sandra",
  "THIE Sharon": "thie-sharon",
  "THIELEN Aaron": "thielen-aaron",
  "THIEME Barbara": "thieme-barbara",
  "THIERREE James": "thierree-james",
  "THIES O F": "thies-o-f",
  "THIESSEN Cherie": "thiessen-cherie",
  "THIESSEN Vern": "thiessen-vern",
  "THIGPEN Sara": "thigpen-sara",
  "THINNES Walter": "thinnes-walter",
  "THIONE Lorenzo": "thione-lorenzo",
  "THIONG'O Ngugi Wa": "thiong-o-ngugi-wa",
  "THIRD ANGEL ": "third-angel",
  "THIRD RAIL PROJECTS ": "third-rail-projects",
  "THIRD WORLD REVELATIONISTS ": "third-world-revelationists",
  "THIRKELL Angela": "thirkell-angela",
  "THIRTEEN THEATRE COMPANY ": "thirteen-theatre-company",
  "THIRTLE Robert": "thirtle-robert",
  "THIRY Heather": "thiry-heather",
  "THISTLE Louise": "thistle-louise",
  "THIYAM Ratan": "thiyam-ratan",
  "THOJ A-Yia": "thoj-a-yia",
  "THOM C J": "thom-c-j",
  "THOM Jess": "thom-jess",
  "THOM Molly": "thom-molly",
  "THOM Paul": "thom-paul",
  "THOM Robert": "thom-robert",
  "THOM Sarah": "thom-sarah",
  "THOMALEN E": "thomalen-e",
  "THOMAN Camille": "thoman-camille",
  "THOMAS A C": "thomas-a-c",
  "THOMAS Aaron": "thomas-aaron",
  "THOMAS Alexander": "thomas-alexander",
  "THOMAS Angela": "thomas-angela",
  "THOMAS Annemarie Lewis": "thomas-annemarie-lewis",
  "THOMAS Annie": "thomas-annie",
  "THOMAS Ashley": "thomas-ashley",
  "THOMAS Basil": "thomas-basil",
  "THOMAS Blair": "thomas-blair",
  "THOMAS Bob": "thomas-bob",
  "THOMAS Buddy": "thomas-buddy",
  "THOMAS Caitlin": "thomas-caitlin",
  "THOMAS Carl": "thomas-carl",
  "THOMAS Cathy": "thomas-cathy",
  "THOMAS Charles": "thomas-charles",
  "THOMAS Charles Philip": "thomas-charles-philip",
  "THOMAS Chris": "thomas-chris",
  "THOMAS Colin": "thomas-colin",
  "THOMAS Cori": "thomas-cori",
  "THOMAS D D": "thomas-d-d",
  "THOMAS D M": "thomas-d-m",
  "THOMAS D Paul": "thomas-d-paul",
  "THOMAS David": "thomas-david",
  "THOMAS Dee Dee": "thomas-dee-dee",
  "THOMAS Derek": "thomas-derek",
  "THOMAS Dylan": "thomas-dylan",
  "THOMAS Eberle": "thomas-eberle",
  "THOMAS Ed": "thomas-ed",
  "THOMAS Edward": "thomas-edward",
  "THOMAS Edward J": "thomas-edward-j",
  "THOMAS Edwin": "thomas-edwin",
  "THOMAS Emily": "thomas-emily",
  "THOMAS Evan": "thomas-evan",
  "THOMAS Fatisha": "thomas-fatisha",
  "THOMAS Freyda": "thomas-freyda",
  "THOMAS Geraint": "thomas-geraint",
  "THOMAS Gerald": "thomas-gerald",
  "THOMAS Gwyn (1)": "thomas-gwyn-1",
  "THOMAS Gwyn (2)": "thomas-gwyn-2",
  "THOMAS Heidi": "thomas-heidi",
  "THOMAS Jacob": "thomas-jacob",
  "THOMAS Jeffrey": "thomas-jeffrey",
  "THOMAS Jerome": "thomas-jerome",
  "THOMAS Jessica": "thomas-jessica",
  "THOMAS Jill Charlotte": "thomas-jill-charlotte",
  "THOMAS Joshua": "thomas-joshua",
  "THOMAS Joyce Carol": "thomas-joyce-carol",
  "THOMAS Joye": "thomas-joye",
  "THOMAS Julie Grady": "thomas-julie-grady",
  "THOMAS Keith": "thomas-keith",
  "THOMAS L E": "thomas-l-e",
  "THOMAS L W": "thomas-l-w",
  "THOMAS Lee": "thomas-lee",
  "THOMAS Les": "thomas-les",
  "THOMAS Letty": "thomas-letty",
  "THOMAS Marie": "thomas-marie",
  "THOMAS Mark": "thomas-mark",
  "THOMAS Marlin": "thomas-marlin",
  "THOMAS Marlo": "thomas-marlo",
  "THOMAS Melba": "thomas-melba",
  "THOMAS Michael": "thomas-michael",
  "THOMAS Michael (1)": "thomas-michael-1",
  "THOMAS Michael (2)": "thomas-michael-2",
  "THOMAS Milly": "thomas-milly",
  "THOMAS Mitch Tawhi": "thomas-mitch-tawhi",
  "THOMAS Neil": "thomas-neil",
  "THOMAS Nick (1)": "thomas-nick-1",
  "THOMAS Nick (2)": "thomas-nick-2",
  "THOMAS Nicole": "thomas-nicole",
  "THOMAS Owen": "thomas-owen",
  "THOMAS Paul": "thomas-paul",
  "THOMAS Paul Berhard": "thomas-paul-berhard",
  "THOMAS Percy": "thomas-percy",
  "THOMAS Peter": "thomas-peter",
  "THOMAS Phi": "thomas-phi",
  "THOMAS Polly": "thomas-polly",
  "THOMAS R Eric": "thomas-r-eric",
  "THOMAS Ray": "thomas-ray",
  "THOMAS Renee": "thomas-renee",
  "THOMAS Rhys": "thomas-rhys",
  "THOMAS Richard": "thomas-richard",
  "THOMAS Richard (1)": "thomas-richard-1",
  "THOMAS Rick": "thomas-rick",
  "THOMAS Riley": "thomas-riley",
  "THOMAS Robert": "thomas-robert",
  "THOMAS Ruby": "thomas-ruby",
  "THOMAS Sam": "thomas-sam",
  "THOMAS Stan": "thomas-stan",
  "THOMAS Steve": "thomas-steve",
  "THOMAS Stuart": "thomas-stuart",
  "THOMAS Stuart (1)": "thomas-stuart-1",
  "THOMAS T C": "thomas-t-c",
  "THOMAS Thom": "thomas-thom",
  "THOMAS Tim": "thomas-tim",
  "THOMAS Trevor": "thomas-trevor",
  "THOMAS Valerie": "thomas-valerie",
  "THOMAS Valerie M": "thomas-valerie-m",
  "THOMAS Vaughn": "thomas-vaughn",
  "THOMAS Veona": "thomas-veona",
  "THOMAS II T Gaillard": "thomas-ii-t-gaillard",
  "THOMAS-FLETCHER Arlette": "thomas-fletcher-arlette",
  "THOMAS-HERRERA Edward": "thomas-herrera-edward",
  "THOMAS-JONES Anna": "thomas-jones-anna",
  "THOMAS-JONES Hagan": "thomas-jones-hagan",
  "THOMASON Ed": "thomason-ed",
  "THOMASON Jane": "thomason-jane",
  "THOMASON Kerrie": "thomason-kerrie",
  "THOMASON Shannon": "thomason-shannon",
  "THOMASSIAN Lilly": "thomassian-lilly",
  "THOMASSON Martin": "thomasson-martin",
  "THOMASSON Niles": "thomasson-niles",
  "THOME Andrea": "thome-andrea",
  "THOMEY Greg": "thomey-greg",
  "THOMPKINS Richard": "thompkins-richard",
  "THOMPSON Adam J": "thompson-adam-j",
  "THOMPSON Andrew": "thompson-andrew",
  "THOMPSON April Yvette": "thompson-april-yvette",
  "THOMPSON B C": "thompson-b-c",
  "THOMPSON Ben": "thompson-ben",
  "THOMPSON Ben (1)": "thompson-ben-1",
  "THOMPSON Bill": "thompson-bill",
  "THOMPSON Billy": "thompson-billy",
  "THOMPSON Brian": "thompson-brian",
  "THOMPSON Bruce": "thompson-bruce",
  "THOMPSON Bryony J": "thompson-bryony-j",
  "THOMPSON Carole": "thompson-carole",
  "THOMPSON Casey Leigh": "thompson-casey-leigh",
  "THOMPSON Chezia B": "thompson-chezia-b",
  "THOMPSON Chris": "thompson-chris",
  "THOMPSON Chris (1)": "thompson-chris-1",
  "THOMPSON D C": "thompson-d-c",
  "THOMPSON Daniel": "thompson-daniel",
  "THOMPSON Danny": "thompson-danny",
  "THOMPSON Davey": "thompson-davey",
  "THOMPSON David": "thompson-david",
  "THOMPSON Don": "thompson-don",
  "THOMPSON Dylan H": "thompson-dylan-h",
  "THOMPSON E R": "thompson-e-r",
  "THOMPSON Ella": "thompson-ella",
  "THOMPSON Eric": "thompson-eric",
  "THOMPSON Ernest": "thompson-ernest",
  "THOMPSON Fred": "thompson-fred",
  "THOMPSON Garland": "thompson-garland",
  "THOMPSON Geoff": "thompson-geoff",
  "THOMPSON Graeme": "thompson-graeme",
  "THOMPSON Greg": "thompson-greg",
  "THOMPSON Helena": "thompson-helena",
  "THOMPSON Hope": "thompson-hope",
  "THOMPSON Ian": "thompson-ian",
  "THOMPSON J Lee": "thompson-j-lee",
  "THOMPSON Jane E": "thompson-jane-e",
  "THOMPSON Jay": "thompson-jay",
  "THOMPSON Jeff": "thompson-jeff",
  "THOMPSON Jeremy": "thompson-jeremy",
  "THOMPSON Jessie": "thompson-jessie",
  "THOMPSON Jimmy": "thompson-jimmy",
  "THOMPSON Joe": "thompson-joe",
  "THOMPSON John": "thompson-john",
  "THOMPSON John Cargill": "thompson-john-cargill",
  "THOMPSON Johnnie": "thompson-johnnie",
  "THOMPSON John-Richard": "thompson-john-richard",
  "THOMPSON Joshua": "thompson-joshua",
  "THOMPSON Judith": "thompson-judith",
  "THOMPSON Kathleen Ann": "thompson-kathleen-ann",
  "THOMPSON Katie": "thompson-katie",
  "THOMPSON Katrina": "thompson-katrina",
  "THOMPSON Keisha": "thompson-keisha",
  "THOMPSON Keith": "thompson-keith",
  "THOMPSON Kester": "thompson-kester",
  "THOMPSON Kris": "thompson-kris",
  "THOMPSON Kristen": "thompson-kristen",
  "THOMPSON Larry": "thompson-larry",
  "THOMPSON Lee": "thompson-lee",
  "THOMPSON Lisa": "thompson-lisa",
  "THOMPSON Lloyd": "thompson-lloyd",
  "THOMPSON Lorraine": "thompson-lorraine",
  "THOMPSON Mark": "thompson-mark",
  "THOMPSON Mark (1)": "thompson-mark-1",
  "THOMPSON Matt": "thompson-matt",
  "THOMPSON Mervyn": "thompson-mervyn",
  "THOMPSON Michael": "thompson-michael",
  "THOMPSON Neville": "thompson-neville",
  "THOMPSON Nina": "thompson-nina",
  "THOMPSON Olivia": "thompson-olivia",
  "THOMPSON Pamela": "thompson-pamela",
  "THOMPSON Paul": "thompson-paul",
  "THOMPSON Paul (2)": "thompson-paul-2",
  "THOMPSON Paula": "thompson-paula",
  "THOMPSON Peggy": "thompson-peggy",
  "THOMPSON Peter": "thompson-peter",
  "THOMPSON R H": "thompson-r-h",
  "THOMPSON Richard": "thompson-richard",
  "THOMPSON Robert": "thompson-robert",
  "THOMPSON Rod": "thompson-rod",
  "THOMPSON Sam": "thompson-sam",
  "THOMPSON Selina": "thompson-selina",
  "THOMPSON Simon": "thompson-simon",
  "THOMPSON Sister Mary Francesca": "thompson-sister-mary-francesca",
  "THOMPSON Stella": "thompson-stella",
  "THOMPSON Stephanie Wright": "thompson-stephanie-wright",
  "THOMPSON Steve": "thompson-steve",
  "THOMPSON Steven": "thompson-steven",
  "THOMPSON Susan W": "thompson-susan-w",
  "THOMPSON Tazewell": "thompson-tazewell",
  "THOMPSON Therese": "thompson-therese",
  "THOMPSON Tierl": "thompson-tierl",
  "THOMPSON Todd": "thompson-todd",
  "THOMPSON Tom": "thompson-tom",
  "THOMPSON Trance": "thompson-trance",
  "THOMPSON-QUARTEY Sandra": "thompson-quartey-sandra",
  "THOMPSON-SCRETCHING Anne L": "thompson-scretching-anne-l",
  "THOMS Doug": "thoms-doug",
  "THOMSON Alexander M": "thompson-alexander-m",
  "THOMSON B C": "thomson-b-c",
  "THOMSON Clare": "thomson-clare",
  "THOMSON David": "thomson-david",
  "THOMSON David Mark": "thomson-david-mark",
  "THOMSON Edward": "thomson-edward",
  "THOMSON Jeff": "thomson-jeff",
  "THOMSON Katherine": "thomson-katherine",
  "THOMSON Kristen": "thomson-kristen",
  "THOMSON Leroy H": "thomson-leroy-h",
  "THOMSON Lloyd": "thomson-lloyd",
  "THOMSON Lynn M": "thomson-lynn-m",
  "THOMSON Mark": "thomson-mark",
  "THOMSON Richard": "thomson-richard",
  "THOMSON Rob": "thomson-rob",
  "THOMSON Sandy": "thomson-sandy",
  "THOMSON Stewart": "thomson-stewart",
  "THOMSON Wendy": "thomson-wendy",
  "THOMSON-KING Rachel": "thomson-king-rachel",
  "THONG Lisa": "thong-lisa",
  "THOPSON Fred": "thopson-fred",
  "THOR Saychay": "thor-saychay",
  "THORBURN Iain": "thorburn-iain",
  "THORBURN Peter": "thorburn-peter",
  "THORENS Dan": "thorens-dan",
  "THORESON Ryan": "thoreson-ryan",
  "THORINGTON Jack": "thorington-jack",
  "THORN Fiona": "thorn-fiona",
  "THORN Jesse": "thorn-jesse",
  "THORN John": "thorn-john",
  "THORN Rachel E": "thorn-rachel-e",
  "THORN Ronald Scott": "thorn-ronald-scott",
  "THORNBER Geoffrey": "thornber-geoffrey",
  "THORNBER Robin": "thornber-robin",
  "THORNBURG Stephen": "thornburg-stephen",
  "THORNE Anna V": "thorne-anna-v",
  "THORNE Jack": "thorne-jack",
  "THORNE Joan Vail": "thorne-joan-vail",
  "THORNE Philip": "thorne-philip",
  "THORNE Rasp": "thorne-rasp",
  "THORNE Stephen": "thorne-stephen",
  "THORNE Steven": "thorne-steven",
  "THORNE Tracy": "thorne-tracy",
  "THORNHILL Alan": "thornhill-alan",
  "THORNS Tricia": "thorns-tricia",
  "THORNTON Ashley": "thornton-ashley",
  "THORNTON Benjamin": "thornton-benjamin",
  "THORNTON Charles": "thornton-charles",
  "THORNTON Colin": "thornton-colin",
  "THORNTON Craig": "thornton-craig",
  "THORNTON Darren": "thornton-darren",
  "THORNTON E": "thornton-e",
  "THORNTON Jane": "thornton-jane",
  "THORNTON Kevin": "thornton-kevin",
  "THORNTON Megan": "thornton-megan",
  "THORNTON Peter": "thornton-peter",
  "THORNTON Rich": "thornton-rich",
  "THORNTON Robert": "thornton-robert",
  "THORNTON Roxanne": "thornton-roxanne",
  "THORNTON Susan": "thornton-susan",
  "THOROGOOD Anthony Edward": "thorogood-anthony-edward",
  "THORON Elise": "thoron-elise",
  "THORP Ken": "thorp-ken",
  "THORPE Adam": "thorpe-adam",
  "THORPE Brierley": "thorpe-brierley",
  "THORPE Chris": "thorpe-chris",
  "THORPE Jess": "thorpe-jess",
  "THORPE Joshua": "thorpe-joshua",
  "THORPE Stephanie": "thorpe-stephanie",
  "THORSTENSON Brian": "thorstenson-brian",
  "THOTTAM Jyoti": "thottam-jyoti",
  "THRASH Nate": "thrash-nate",
  "THRASHER Sunny": "thrasher-sunny",
  "THREE CROWS THEATRE ": "three-crows-theatre",
  "THREE WOMEN ": "three-women",
  "THREEDY Debora": "threedy-debora",
  "THRELFALL Andrew": "threlfall-andrew",
  "THRESHOLD THEATRE ": "threshold-theatre",
  "THRIST Megan": "thrist-megan",
  "THRONSON Ron": "thronson-ron",
  "THROPP Randall": "thropp-randall",
  "THROSSELL Ric": "throssell-ric",
  "THROTTLE ": "throttle",
  "THROWBRIDGE Alina R": "throwbridge-alina-r",
  "THROWER Emmitt": "thrower-emmitt",
  "THROWER Scott": "thrower-scott",
  "THRUN Oliver": "thrun-oliver",
  "THUAL Heloise": "thual-heloise",
  "THUESEN Stephanie": "thuesen-stephanie",
  "THUNA Lee": "thuna-lee",
  "THUNDER Brian": "thunder-brian",
  "THURBER James": "thurber-james",
  "THURBER Lucy": "thurber-lucy",
  "THUREEN Paul": "thureen-paul",
  "THURGOOD Margaret": "thurgood-margaret",
  "THURMAN Beverley": "thurman-beverley",
  "THURMAN Daniel": "thurman-daniel",
  "THURMAN Leo L": "thurman-leo-l",
  "THURSCHWELL Harry T": "thurschwell-harry-t",
  "THURSTON Alan": "thurston-alan",
  "THURSTON Angela": "thurston-angela",
  "THURSTON Cheryl": "thurston-cheryl",
  "THURSTON Robin": "thurston-robin",
  "THURSTON Shannon": "thurston-shannon",
  "THURY Fredrick H": "thury-fredrick-h",
  "THWAITE Emily": "thwaite-emily",
  "THWAITES Peter": "thwaites-peter",
  "TIANG Jeremy": "tiang-jeremy",
  "TIANGA David": "tianga-david",
  "TIATA FAHODZI ": "tiata-fahodzi",
  "TIBBETS Wayne": "tibbets-wayne",
  "TIBBETTS Christopher": "tibbetts-christopher",
  "TIBBETTS Mike": "tibbetts-mike",
  "TIBBEY Paul": "tibbey-paul",
  "TIBBLES George": "tibbles-george",
  "TICHENOR Austin": "tichenor-austin",
  "TICKELL Andrew": "tickell-andrew",
  "TICKNER Peter": "tickner-peter",
  "TIDHOLM Thomas": "tidholm-thomas",
  "TIDLER Charles": "tidler-charles",
  "TIDY Bill": "tidy-bill",
  "TIECK Ludwig": "tieck-ludwig",
  "TIEGER Danny": "tieger-danny",
  "TIEN Melisa": "tien-melisa",
  "TIERNAN Eleanor": "tiernan-eleanor",
  "TIERNEY Alicia": "tierney-alicia",
  "TIERNEY Andrea": "tierney-andrea",
  "TIERNEY Hanne": "tierney-hanne",
  "TIERNEY Jim": "tierney-jim",
  "TIERNEY Matthew F": "tierney-matthew-f",
  "TIERNEY Thomas": "tierney-thomas",
  "TIERNEY-KEOGH Lisa": "tierney-keogh-lisa",
  "TIFFANY John": "tiffany-john",
  "TIFFONEY James": "tiffoney-james",
  "TIFFOU Solvene": "tiffou-solvene",
  "TIGER Janet S": "tiger-janet-s",
  "TIGG Nick": "tigg-nick",
  "TIGHE Dylan": "tighe-dylan",
  "TIJSSENS Angelo": "tijssens-angelo",
  "TIKKANEN Marta": "tikkanen-marta",
  "TIKTIN Carl": "tiktin-carl",
  "TILAJCIK Peter": "tilajcik-peter",
  "TILBURY Peter": "tilbury-peter",
  "TILELLI Krysten": "tilelli-krysten",
  "TILFORD Michael": "tilford-michael",
  "TILL Benjamin": "till-benjamin",
  "TILL Lawrence": "till-lawrence",
  "TILL Richard": "till-richard",
  "TILLER Chrissie": "tiller-chrissie",
  "TILLER Steve": "tiller-steve",
  "TILLER Ted": "tiller-ted",
  "TILLERY Jodi Lynn": "tillery-jodi-lynn",
  "TILLETT Seth": "tillett-seth",
  "TILLEY Brian": "tilley-brian",
  "TILLEY Chris": "tilley-chris",
  "TILLEY Elspeth": "tilley-elspeth",
  "TILLEY Sam": "tilley-sam",
  "TILLING Andrew": "tilling-andrew",
  "TILLINGER Mark": "tillinger-mark",
  "TILLINGHAST Daven": "tillinghast-daven",
  "TILL-MOBLEY Mamie": "till-mobley-mamie",
  "TILLY Francois-Louis": "tilly-francois-louis",
  "TILLY Grant": "tilly-grant",
  "TILSLEY Frank": "tilsley-frank",
  "TILSON George Purefoy": "tilson-george-purefoy",
  "TIMBERS Alex": "timbers-alex",
  "TIMLIN John": "timlin-john",
  "TIMM Fred": "timm-fred",
  "TIMM Lee": "timm-lee",
  "TIMM Stephanie": "timm-stephanie",
  "TIMMERMANS Chris": "timmermans-chris",
  "TIMMERS Gerrit": "timmers-gerrit",
  "TIMMINS Philip": "timmins-philip",
  "TIMMONS Anne Miyamoto": "timmons-anne-miyamoto",
  "TIMMS Howard": "timms-howard",
  "TIMMS Nigel": "timms-nigel",
  "TIMMS Steve": "timms-steve",
  "TIMOTEO Farren": "timoteo-farren",
  "TIMPANO Marco": "timpano-marco",
  "TINALLI Italo": "tinalli-italo",
  "TINBERG Nalsey": "tinberg-nalsey",
  "TINDALL A J": "tindall-a-j",
  "TINDALL Adam": "tindall-adam",
  "TINDER THEATRE ": "tinder-theatre",
  "TINDLE Jacob": "tindle-jacob",
  "TING Eric": "ting-eric",
  "TING Steve": "ting-steve",
  "TINGLE, THE ": "tingle",
  "TINGLEY Kyle": "tingley-kyle",
  "TINGWELL Charles": "tingwell-charles",
  "TINGWELL Drew": "tingwell-drew",
  "TINKHAM David": "tinkham-david",
  "TINKLER Shaun": "tinkler-shaun",
  "TINNISWOOD Peter": "tinniswood-peter",
  "TINSLEY Bill": "tinsley-bill",
  "TINSLEY Herbert F": "tinsley-herbert-f",
  "TINSLEY Molly": "tinsley-molly",
  "TINSON Rod": "tinson-rod",
  "TIPE David": "tipe-david",
  "TIPLADY Steve": "tiplady-steve",
  "TIPPE Annie": "tippe-annie",
  "TIPPETS Melody Ventris-French": "tippets-melody-ventris-french",
  "TIPPING Richard": "tipping-richard",
  "TIPPLE Sarah": "tipple-sarah",
  "TIPTON Don": "tipton-don",
  "TIPTON John": "tipton-john",
  "TIRADO Candido": "tirado-candido",
  "TIRELLI Marisol": "tirelli-marisol",
  "TIRGRATH Tami": "tirgrath-tami",
  "TIRMAN Daniel": "tirman-daniel",
  "TIRMAZI Mazur": "tirmazi-mazur",
  "TIROSH-POLK Zohar": "tirosh-polk-zohar",
  "TISCHLER Jacob": "tischler-jacob",
  "TISCHLER Susan": "tischler-susan",
  "TISDALE Michael": "tisdale-michael",
  "TISDALL Laura": "tisdall-laura",
  "TISDALL Polly": "tisdall-polly",
  "TISE Rhiannon": "tise-rhiannon",
  "TISH Larry Jay": "tish-larry-jay",
  "TISI Emily": "tisi-emily",
  "TISSIAN Gabriel": "tissian-gabriel",
  "TISSOT John": "tissot-john",
  "TITCHENER David": "titchener-david",
  "TITELMAN Claire": "titelman-claire",
  "TITHERIDGE Georina": "titheridge-georina",
  "TITO Greg": "tito-greg",
  "TITTEL Christopher": "tittel-christopher",
  "TITTEL Jorg": "tittel-jorg",
  "TITTLE Ryan C": "tittle-ryan-c",
  "TITUS Jacob": "titus-jacob",
  "TJAARDSTRA Nick": "tjaardstra-nick",
  "TJADEN Joshua": "tjaden-joshua",
  "TJARKS Mark": "tjarks-mark",
  "TKACH Glen": "tkach-glen",
  "TKACHENKO Victor S": "tkachenko-victor-s",
  "TKACZ Virlana": "tkacz-virlana",
  "TLC CREATIVE ": "tlc-creative",
  "TOAL Anna": "toal-anna",
  "TOAL Patrick": "toal-patrick",
  "TOALSON Jeff": "toalson-jeff",
  "TOBIAS Charles": "tobias-charles",
  "TOBIAS Daniel": "tobias-daniel",
  "TOBIAS Fred": "tobias-fred",
  "TOBIAS John": "tobias-john",
  "TOBIAS Lawrence Hodge": "tobias-lawrence-hodge",
  "TOBIESSEN Josh": "tobiessen-josh",
  "TOBIN Miriam": "tobin-miriam",
  "TOBIN Niall": "tobin-niall",
  "TOBIN Robert": "tobin-robert",
  "TOBIN Scott": "tobin-scott",
  "TOBIS Scott Sanford": "tobis-scott-sanford",
  "TOBY Xavier": "toby-xavier",
  "TOCANTINS Terry": "tocantins-terry",
  "TOCKMAN Marin": "tockman-marin",
  "TODARO Mike": "todaro-mike",
  "TODD Albert": "todd-albert",
  "TODD Beverley": "todd-beverley",
  "TODD Chris": "todd-chris",
  "TODD David": "todd-david",
  "TODD Harold": "todd-harold",
  "TODD Matthew": "todd-matthew",
  "TODD Paul": "todd-paul",
  "TODD Ruthven": "todd-ruthven",
  "TODD Stephen": "todd-stephen",
  "TODD Susan": "todd-susan",
  "TODD Susan Gayle": "todd-susan-gayle",
  "TODD Will": "todd-will",
  "TODD THEATER TROUP ": "todd-theater-troup",
  "TODDIE Jean Lenox": "toddie-jean-lenox",
  "TODMAN Georgie": "todman-georgie",
  "TODOROV Niko Rendevski": "todorov-niko-rendevski",
  "TODOROV Peter": "todorov-peter",
  "TODOROVIC Damir": "todorovic-damir",
  "TOENTSCH Dan": "toentsch-dan",
  "TOFIL Ryan": "tofil-ryan",
  "TOFTE Amy": "tofte-amy",
  "TOGNOTTI Brian J": "tognotti-brian-j",
  "TOIBIN Colm": "toibin-colm",
  "TOILER Ernst": "toiler-ernst",
  "TOKATYAN Leon": "tokatyan-leon",
  "TOKHAI Gavin": "tokhai-gavin",
  "TOKSVIG Jenifer": "toksvig-jenifer",
  "TOKSVIG Sandi": "toksvig-sandi",
  "TOKUDA Marilyn": "tokuda-marilyn",
  "TOKUDANI Betty": "tokudani-betty",
  "TOLAN Kathleen": "tolan-kathleen",
  "TOLAN Peter": "tolan-peter",
  "TOLAN Stephanie": "tolan-stephanie",
  "TOLAND Chris": "toland-chris",
  "TOLCHINSKY David E": "tolchinsky-david-e",
  "TOLCSVAY Lazlo": "tolcsvay-lazlo",
  "TOLD BY AN IDIOT ": "told-by-an-idiot",
  "TOLER Celia": "toler-celia",
  "TOLES Jartu Gallashaw": "toles-jartu-gallashaw",
  "TOLINS Jonathan": "tolins-jonathan",
  "TOLIVER Cynthia O": "toliver-cynthia-o",
  "TOLK Alexandra": "tolk-alexandra",
  "TOLKIN Mel": "tolkin-mel",
  "TOLL Samuel": "toll-samuel",
  "TOLLEMACHE Lizzie": "tollemache-lizzie",
  "TOLLER Ernst": "toller-ernst",
  "TOLLEY Justin": "tolley-justin",
  "TOLLY Maria": "tolly-maria",
  "TOLMAN Rosco N": "tolman-rosco-n",
  "TOLMASOFF T H": "tolmasoff-t-h",
  "TOLPUTT Anna": "tolputt-anna",
  "TOLSON Georgina": "tolson-georgina",
  "TOLSON Melvin B": "tolson-melvin-b",
  "TOLSTOY Leo": "tolstoy-leo",
  "TOLTON Paul": "tolton-paul",
  "TOMAINE John": "tomaine-john",
  "TOMAINE Tony": "tomaine-tony",
  "TOMALIN Claire": "tomalin-claire",
  "TOMALIN Jo": "tomalin-jo",
  "TOMAS ": "tomas",
  "TOMASCHIK Stacey": "tomaschik-stacey",
  "TOMASELLI Angela": "tomaselli-angela",
  "TOMASINI Ernesto": "tomasini-ernesto",
  "TOMASINO Matthew": "tomasino-matthew",
  "TOMASKO Joy": "tomasko-joy",
  "TOMASO Carla": "tomaso-carla",
  "TOMASON Kerrie": "tomason-kerrie",
  "TOMASON Meredith": "tomason-meredith",
  "TOMASZUK Piotr": "tomaszuk-piotr",
  "TOME Gregg": "tome-gregg",
  "TOMELTY Joseph": "tomelty-joseph",
  "TOMELTY Rome": "tomelty-rome",
  "TOMERO Helena": "tomero-helena",
  "TOMICH Branislav": "tomich-branislav",
  "TOMIOKA Taeko": "tomioka-taeko",
  "TOMKO Kathleen": "tomko-kathleen",
  "TOMLIN Lily": "tomlin-lily",
  "TOMLIN Liz": "tomlin-liz",
  "TOMLINSON Alan": "tomlinson-alan",
  "TOMLINSON Charlie": "tomlinson-charlie",
  "TOMLINSON David": "tomlinson-david",
  "TOMLINSON John James": "tomlinson-john-james",
  "TOMLINSON Keith": "tomlinson-keith",
  "TOMLINSON Kevin": "tomlinson-kevin",
  "TOMLINSON Laraine": "tomlinson-laraine",
  "TOMLINSON Paul": "tomlinson-paul",
  "TOMLINSON Richard": "tomlinson-richard",
  "TOMLINSON Steven": "tomlinson-steven",
  "TOMMY Liesl": "tommy-liesl",
  "TOMOS Angharad": "tomos-angharad",
  "TOMPKINS James R": "tompkins-james-r",
  "TOMPKINS Jon": "tompkins-jon",
  "TOMPOS Doug": "tompos-doug",
  "TOMPSON Timothy": "tompson-timothy",
  "TOMSON Bob": "tomson-bob",
  "TOMSON Noah": "tomson-noah",
  "TOMYCZ Motrya": "tomycz-motrya",
  "TONER Joanne": "toner-joanne",
  "TONER Matt": "toner-matt",
  "TONER Michael": "toner-michael",
  "TONEY David Emerson": "toney-david-emerson",
  "TONG Christopher Karlin": "tong-christopher-karlin",
  "TONG Jean": "tong-jean",
  "TONG Merlynn": "tong-merlynn",
  "TONG Phil": "tong-phil",
  "TONG Winston": "tong-winston",
  "TONGE Jane": "tonge-jane",
  "TONGUE Donald": "tongue-donald",
  "TONGUE Ruth L": "tongue-ruth-l",
  "TONKIN Louise": "tonkin-louise",
  "TONKINSON Frank": "tonkinson-frank",
  "TONKONOGY Gertrude": "tonkonogy-gertrude",
  "TONON Jen": "tonon-jen",
  "TONOUCHI Lee": "tonouchi-lee",
  "TONY AND DEREK ": "tony-and-derek",
  "TOO MANY CHIEFS ": "too-many-chiefs",
  "TOOEY Jim": "tooey-jim",
  "TOOEY Rosemary Frisino": "tooey-rosemary-frisino",
  "TOOGOOD Sarah": "toogood-sarah",
  "TOOHER Michael": "tooher-michael",
  "TOOHEY Edwina": "toohey-edwina",
  "TOOHEY Rosemary Frisino": "toohey-rosemary-frisino",
  "TOOHEY Steve": "toohey-steve",
  "TOOK Barry": "took-barry",
  "TOOK Mary": "took-mary",
  "TOOKS Lenga": "tooks-lenga",
  "TOOLAN Donal": "toolan-donal",
  "TOOLIS Kevin": "toolis-kevin",
  "TOOMEY Michael F": "toomey-michael-f",
  "TOON Kate": "toon-kate",
  "TOOSEY Sally": "toosey-sally",
  "TOOT COLLECTIVE ": "toot-collective",
  "TOP OF THE WORLD ": "top-of-the-world",
  "TOPIARY Samuel": "topiary-samuel",
  "TOPLIFF John": "topliff-john",
  "TOPLISS Paul": "topliss-paul",
  "TOPO Ruby": "topo-ruby",
  "TOPOL Josef": "topol-josef",
  "TOPOR Tom": "topor-tom",
  "TOPP TWINS ": "topp-twins",
  "TOPPER Cosmo": "topper-cosmo",
  "TOPPER Manja": "topper-manja",
  "TOPPING Frank": "topping-frank",
  "TOPPINGS Michael": "toppings-michael",
  "TORDAFF John": "tordaff-john",
  "TORDAY Piers": "torday-piers",
  "TORDOFF Bill": "tordoff-bill",
  "TORDOFF John": "tordoff-john",
  "TORE John": "tore-john",
  "TORFASON Mikael": "torfason-mikael",
  "TORIEL Nathalie": "toriel-nathalie",
  "TORINO Michele": "torino-michele",
  "TORKOVA Bobby": "torkova-bobby",
  "TORN Tony": "torn-tony",
  "TORNQVIST Mia": "tornqvist-mia",
  "TORODE Sally": "torode-sally",
  "TOROK Frank S": "torok-frank-s",
  "TOROPOV Brandon": "toropov-brandon",
  "TOROSIAN Rebecca": "torosian-rebecca",
  "TORR Diane": "torr-diane",
  "TORR Oliver": "torr-oliver",
  "TORRANCE Alys": "torrance-alys",
  "TORRANCE Kirk": "torrance-kirk",
  "TORRENCE Jay": "torrence-jay",
  "TORRENS Jackie": "torrens-jackie",
  "TORRES Angelique": "torres-angelique",
  "TORRES Casimiro": "torres-casimiro",
  "TORRES Fiona J": "torres-fiona-j",
  "TORRES Joan": "torres-joan",
  "TORRES Maria Elena": "torres-maria-elena",
  "TORRES Susana": "torres-susana",
  "TORRES-CABASSA Angel S": "torres-cabassa-angel-s",
  "TORRUELLAS Elsia Cruz": "torruellas-elsia-cruz",
  "TORRY Andrew": "torry-andrew",
  "TORSION THEATRE ": "torsion-theatre",
  "TORSSON Bjorner": "torsson-bjorner",
  "TORTLADZE Sophie": "tortladze-sophie",
  "TORTOISE IN A NUTSHELL ": "tortoise-in-a-nutshell",
  "TORTORA Tony": "tortora-tony",
  "TORTORICI Julie": "tortorici-julie",
  "TORTURE PROJECT ENSEMBLE ": "torture-project-ensemble",
  "TOSCANO Bill": "toscano-bill",
  "TOSCANO Mario Cantu": "toscano-mario-cantu",
  "TOSCAS Dimitri": "toscas-dimitri",
  "TOSDEVIN Michael": "tosdevin-michael",
  "TOSH Julie": "tosh-julie",
  "TOSNEY Jim": "tosney-jim",
  "TOSSMANN Juergen K": "tossmann-juergen-k",
  "TOSTADO Ben": "tostado-ben",
  "TOTERAS ": "toteras",
  "TOTH Richard": "toth-richard",
  "TOTHEROH Dan": "totheroh-dan",
  "TOTMAN Richard": "totman-richard",
  "TOUBES Guy": "toubes-guy",
  "TOUCHSTONE THEATRE ": "touchstone-theatre",
  "TOUFEXIS Elias": "toufexis-elias",
  "TOUGH Jim": "tough-jim",
  "TOUPIN Catherine-Anne": "toupin-catherine-anne",
  "TOURELLE Wayne": "tourelle-wayne",
  "TOURINO Rebecca": "tourino-rebecca",
  "TOURNEY Michael": "tourney-michael",
  "TOURNIER Michel": "tournier-michel",
  "TOURNIS Anthony": "tournis-anthony",
  "TOUSSAINT Germono": "toussaint-germono",
  "TOUSSAINT Richard": "toussaint-richard",
  "TOUTAIN Andre D": "toutain-andre-d",
  "TOVATT Patrick": "tovatt-patrick",
  "TOVEY Noel": "tovey-noel",
  "TOVEY Russell": "tovey-russell",
  "TOW Jeremy": "tow-jeremy",
  "TOWARD Molly": "toward-molly",
  "TOWBIN Fredi": "towbin-fredi",
  "TOWER Michael Thomas": "tower-michael-thomas",
  "TOWERING INFERNO ": "towering-inferno",
  "TOWERS J Maxwell": "towers-j-maxwell",
  "TOWEY Siobhan": "towey-siobhan",
  "TOWLE W Ray": "towle-w-ray",
  "TOWLER Anthony": "towler-anthony",
  "TOWLER Jeremy": "towler-jeremy",
  "TOWNDROW Chris": "towndrow-chris",
  "TOWNEND JONES Elton": "townend-jones-elton",
  "TOWNLEY Kevin": "townley-kevin",
  "TOWNS Otis": "towns-otis",
  "TOWNSEND Ceri": "townsend-ceri",
  "TOWNSEND Henry": "townsend-henry",
  "TOWNSEND Ian": "townsend-ian",
  "TOWNSEND Jessica": "townsend-jessica",
  "TOWNSEND Jo": "townsend-jo",
  "TOWNSEND Laura": "townsend-laura",
  "TOWNSEND Mark": "townsend-mark",
  "TOWNSEND Paul": "townsend-paul",
  "TOWNSEND Pete": "townsend-pete",
  "TOWNSEND Sue": "townsend-sue",
  "TOWNSHEND Pete": "townshend-pete",
  "TOWSEY Lydia": "towsey-lydia",
  "TOY Barbara": "toy-barbara",
  "TOYAMA Tim": "toyama-tim",
  "TOYE Wendy": "toye-wendy",
  "TOYNE Simon": "toyne-simon",
  "TRACEY Damien": "tracey-damien",
  "TRACEY Debbie": "tracey-debbie",
  "TRACEY Katie": "tracey-katie",
  "TRACY Ann": "tracy-ann",
  "TRACY Carl": "tracy-carl",
  "TRACY Debbie": "tracy-debbie",
  "TRACY Jon": "tracy-jon",
  "TRACZ Joe": "tracz-joe",
  "TRADUP Troy": "tradup-troy",
  "TRAFFORD Steve": "trafford-steve",
  "TRAGER Oliver": "trager-oliver",
  "TRAHEY Jack": "trahey-jack",
  "TRAHEY Jane": "trahey-jane",
  "TRAIGER Larry": "traiger-larry",
  "TRAINA Anastasia": "traina-anastasia",
  "TRAINA Jose": "traina-jose",
  "TRAINER David": "trainer-david",
  "TRAINOR Kay": "trainor-kay",
  "TRAINOR Michael": "trainor-michael",
  "TRAINOR JR Dennis": "trainor-jr-dennis",
  "TRAKAL Daniela": "trakal-daniela",
  "TRAKTMAN Peggy": "traktman-peggy",
  "TRAMBLEY Estela Portillo": "trambley-estela-portillo",
  "TRAN Huu": "tran-huu",
  "TRAN Lan": "tran-lan",
  "TRAN Steven": "tran-steven",
  "TRAN Trieu": "tran-trieu",
  "TRANDAFIR Claudiu": "trandafir-claudiu",
  "TRANEN Jan": "tranen-jan",
  "TRANSFER THEATRE ": "transfer-theatre",
  "TRANSPORT THEATRE COMPANY ": "transport-theatre-company",
  "TRANTER Nigel": "tranter-nigel",
  "TRAPANI Sal": "trapani-sal",
  "TRAPNELL Nathan": "trapnell-nathan",
  "TRAPP Alison": "trapp-alison",
  "TRAPPER John Patrick": "trapper-john-patrick",
  "TRASH VAUDEVILLE ": "trash-vaudeville",
  "TRASK Josh Alan": "trask-josh-alan",
  "TRASK Larry": "trask-larry",
  "TRASK W R": "trask-w-r",
  "TRASLER Damian": "trasler-damian",
  "TRASS Vel": "trass-vel",
  "TRAUB Wayn": "traub-wayn",
  "TRAUBE Lucy": "traube-lucy",
  "TRAUSCH Monica": "trausch-monica",
  "TRAUSCH Susan": "trausch-susan",
  "TRAUT Karyn": "traut-karyn",
  "TRAV S D ": "trav-s-d",
  "TRAVELLING JEWISH THEATRE ": "travelling-jewish-theatre",
  "TRAVELLING LIGHT THEATRE COMPANY ": "travelling-light-theatre-company",
  "TRAVERS Alex": "travers-alex",
  "TRAVERS Ben": "travers-ben",
  "TRAVERS Brian": "travers-brian",
  "TRAVERS Hugh": "travers-hugh",
  "TRAVERS Joseph": "travers-joseph",
  "TRAVERS Martin": "travers-martin",
  "TRAVERSE Lans": "traverse-lans",
  "TRAVIS Bayla": "travis-bayla",
  "TRAVIS Bernie": "travis-bernie",
  "TRAVIS Bethani": "travis-bethani",
  "TRAVIS Greg": "travis-greg",
  "TRAVIS John": "travis-john",
  "TRAVIS Mandy": "travis-mandy",
  "TRAVIS Mark": "travis-mark",
  "TRAVIS Sarah": "travis-sarah",
  "TRAVIS Tara": "travis-tara",
  "TRAWICK-SMITH Ben": "trawick-smith-ben",
  "TRAYERS Linda": "trayers-linda",
  "TRAYLOR Gene": "traylor-gene",
  "TRAYNOR Billie": "traynor-billie",
  "TRAYNOR Joseph": "traynor-joseph",
  "TREACHER Graham": "treacher-graham",
  "TREACY Stephen Delos": "treacy-stephen-delos",
  "TREADWAY Amber": "treadway-amber",
  "TREADWELL Caroline": "treadwell-caroline",
  "TREADWELL Sophie": "treadwell-sophie",
  "TREANOR Tim": "treanor-tim",
  "TREASE Geoffrey": "trease-geoffrey",
  "TREAYS Jem": "treays-jem",
  "TREBOR-LANG Robert": "trebor-lang-robert",
  "TREDINNICK Miles": "tredinnick-miles",
  "TREE E Wayne": "tree-e-wayne",
  "TREE SHADOW THEATRE ": "tree-shadow-theatre",
  "TREEM Sarah": "treem-sarah",
  "TREEN Joe": "treen-joe",
  "TREGANZA Neil": "treganza-neil",
  "TREGENNA Catherine": "tregenna-catherine",
  "TREGENNA Jan": "tregenna-jan",
  "TREGLOAN Anna": "tregloan-anna",
  "TREHY Jody": "trehy-jody",
  "TREIBER Linda Lenzen": "treiber-linda-lenzen",
  "TREISCHMANN Catherine": "treischmann-catherine",
  "TREJOS Sandra": "trejos-sandra",
  "TRELEAVEN Lou": "treleaven-lou",
  "TRELLING Ursala": "trelling-ursala",
  "TREMAIN David": "tremain-david",
  "TREMAYNE Georgina": "tremayne-georgina",
  "TREMAYNE Hunter": "tremayne-hunter",
  "TREMBECKA Marysia": "trembecka-marysia",
  "TREMBLAY Brian": "tremblay-brian",
  "TREMBLAY Jason": "tremblay-jason",
  "TREMBLAY Jennifer": "tremblay-jennifer",
  "TREMBLAY Joey": "tremblay-joey",
  "TREMBLAY Larry": "tremblay-larry",
  "TREMBLAY Michel": "tremblay-michel",
  "TREMBLAY Renald": "tremblay-renald",
  "TREMLETT Peter": "tremlett-peter",
  "TRENCH Felix": "trench-felix",
  "TRENCH Zia": "trench-zia",
  "TRENIER Diane": "trenier-diane",
  "TRENT Jackie": "trent-jackie",
  "TRENTHAM Winifred": "trentham-winifred",
  "TRENTON Nadine": "trenton-nadine",
  "TREON Phil": "treon-phil",
  "TRESIZE Rachel": "tresize-rachel",
  "TRESLA Christopher": "tresla-christopher",
  "TRESSOR Alexander": "tressor-alexander",
  "TRESTER Michelle Marie": "trester-michelle-marie",
  "TRESTLE THEATRE ": "trestle-theatre",
  "TRESTON Lewis": "treston-lewis",
  "TRETHEWEY Natasha": "trethewey-natasha",
  "TRETIAKOFF David G": "tretiakoff-david-g",
  "TREUHAFT-ALI May": "treuhaft-ali-may",
  "TREVANNION Matthew": "trevannion-matthew",
  "TREVELLINI Giacondo": "trevellini-giacondo",
  "TREVELYAN Anthony": "trevelyan-anthony",
  "TREVELYAN Humphrey": "trevelyan-humphrey",
  "TREVELYAN R C": "trevelyan-r-c",
  "TREVENS Francine": "trevens-francine",
  "TREVENS Janine Nina": "trevens-janine-nina",
  "TREVERN Douglas": "trevern-douglas",
  "TREVES Simon": "treves-simon",
  "TREVILL Alastair": "trevill-alastair",
  "TREVINO Carlos": "trevino-carlos",
  "TREVINO Danusia": "trevino-danusia",
  "TREVIS Di": "trevis-di",
  "TREVOR Jon": "trevor-jon",
  "TREVOR Judith": "trevor-judith",
  "TREVOR Pat": "trevor-pat",
  "TREVOR William": "trevor-william",
  "TREYZ Russell": "treyz-russell",
  "TREZISE Keith": "trezise-keith",
  "TREZISE Rachel": "trezise-rachel",
  "TRIANA Jose": "triana-jose",
  "TRICKER Alan": "tricker-alan",
  "TRICKER Carole": "tricker-carole",
  "TRICKER George": "tricker-george",
  "TRICKSTER PRODUCTIONS ": "trickster-productions",
  "TRICKSTER THEATRE CO ": "trickster-theatre-co",
  "TRIDON Andre": "tridon-andre",
  "TRIESCHMANN Catherine": "trieschmann-catherine",
  "TRIESCHMANN Werner": "trieschmann-werner",
  "TRIFFITT Iain": "triffitt-iain",
  "TRIFKOVIC Nela": "trifkovic-nela",
  "TRIFONOV Yuri": "trifonov-yuri",
  "TRIGG John": "trigg-john",
  "TRIGGS Jason": "triggs-jason",
  "TRIGWELL-JONES Amy": "trigwell-jones-amy",
  "TRIGWELL-JONES Tony": "trigwell-jones-tony",
  "TRIKHA Rishi": "trikha-rishi",
  "TRIMMER Jon": "trimmer-jon",
  "TRINGHAM Annette": "tringham-annette",
  "TRINGHAM David": "tringham-david",
  "TRIPATHI Shalini": "tripathi-shalini",
  "TRIPE Robert": "tripe-robert",
  "TRIPICIAN Joe": "tripician-joe",
  "TRIPLE SHADOW ": "triple-shadow",
  "TRIPLETT Lori Lee": "triplett-lori-lee",
  "TRIPLETT William": "triplett-william",
  "TRIPP Ayasha": "tripp-ayasha",
  "TRIPP Miles": "tripp-miles",
  "TRIPP Peter": "tripp-peter",
  "TRIPPINI Roberto": "trippini-roberto",
  "TRISTAN Dorothy": "tristan-dorothy",
  "TRISTER Steve R": "trister-steve-r",
  "TRISTRAM David": "tristram-david",
  "TROCCHI Alexander": "trocchi-alexander",
  "TROCHIM Dennis": "trochim-dennis",
  "TROLI Tad": "troli-tad",
  "TROLL Bradley": "troll-bradley",
  "TRONE A L": "trone-a-l",
  "TRONES John": "trones-john",
  "TROOB Danny": "troob-danny",
  "TROOP Robert": "troop-robert",
  "TROOP Steve": "troop-steve",
  "TROOST Julie": "troost-julie",
  "TROOST Neil": "troost-neil",
  "TROOST Scott": "troost-scott",
  "TROPF Ralph": "tropf-ralph",
  "TROPICANA Carmelita": "tropicana-carmelita",
  "TROST Bastian": "trost-bastian",
  "TROTT F H": "trott-f-h",
  "TROTT Harry": "trott-harry",
  "TROTT Karen": "trott-karen",
  "TROTTER Carla": "trotter-carla",
  "TROTTER Catharine": "trotter-catharine",
  "TROTTER David": "trotter-david",
  "TROUBADOUR THEATER COMPANY ": "troubadour-theater-company",
  "TROUBLE AND STRIFE ": "trouble-and-strife",
  "TROUILLE Clovis": "trouille-clovis",
  "TROUNSON Kylie": "trounson-kylie",
  "TROUP Cynthia": "troup-cynthia",
  "TROUSDALE Donna": "trousdale-donna",
  "TROUT Steve": "trout-steve",
  "TROUTON David": "trouton-david",
  "TROW Eugenie": "trow-eugenie",
  "TROW George W S": "trow-george-w-s",
  "TROW Jack": "trow-jack",
  "TROWBRIDGE Dylan": "trowbridge-dylan",
  "TROWER Alison": "trower-alison",
  "TROY Hector": "troy-hector",
  "TROY Jonathan": "troy-jonathan",
  "TROY Mark": "troy-mark",
  "TROYANO Ela": "troyano-ela",
  "TRUAX James": "truax-james",
  "TRUBRIDGE Sam": "trubridge-sam",
  "TRUBY Angela": "truby-angela",
  "TRUDEAU Garry": "trudeau-garry",
  "TRUDELL David": "trudell-david",
  "TRUDELL Hilary": "trudell-hilary",
  "TRUDELLE Jeremy": "trudelle-jeremy",
  "TRUELOVE Gayann": "truelove-gayann",
  "TRUEMAN Brian": "trueman-brian",
  "TRUESDALE Tad": "truesdale-tad",
  "TRUITT Sara": "truitt-sara",
  "TRUJILLO Dan": "trujillo-dan",
  "TRULES Eric": "trules-eric",
  "TRULL Lee": "trull-lee",
  "TRULL Sylvia Riojas": "trull-sylvia-riojas",
  "TRULL Tommy": "trull-tommy",
  "TRUMAN Jill": "truman-jill",
  "TRUMBO Christopher": "trumbo-christopher",
  "TRUMBO Dalton": "trumbo-dalton",
  "TRUMBULL Matthew": "trumbull-matthew",
  "TRUNK Jonny": "trunk-jonny",
  "TRUPIA Paul": "trupia-paul",
  "TRUSCOTT Cristal Chanelle": "truscott-cristal-chanelle",
  "TRUSCOTT Julia": "truscott-julia",
  "TRUSITS Marie": "trusits-marie",
  "TRUSKINOFF David": "truskinoff-david",
  "TRUSS Jan": "truss-jan",
  "TRUSS Lynne": "truss-lynne",
  "TRUSSELL Paul": "trussell-paul",
  "TRUYTS Luk": "truyts-luk",
  "TRYKY Cheryl": "tryky-cheryl",
  "TRYPANIS C A": "trypanis-c-a",
  "TRZCINSKI Danielle": "trzcinski-danielle",
  "TRZCINSKI Edmund": "trzcinski-edmund",
  "TRZEBINSKI Andrzej": "trzebinski-andrzej",
  "TSAKALAKOS Niko": "tsakalakos-niko",
  "TSANEV Stefan": "tsanev-stefan",
  "TSANG Julie": "tsang-julie",
  "TSAO Andrew": "tsao-andrew",
  "TSAROV R J": "tsarov-r-j",
  "TSARO-WIWA Ken": "tsaro-wiwa-ken",
  "TSAVARIS Barri": "tsavaris-barri",
  "TSE Cassandra": "tse-cassandra",
  "TSE David K S": "tse-david-k-s",
  "TSE Mariko": "tse-mariko",
  "TSEGAYE Ato": "tsegaye-ato",
  "TSENDEAS Tony": "tsendeas-tony",
  "TSENG Muna": "tseng-muna",
  "TSIHLIS Jim": "tsihlis-jim",
  "TSIKURISHVILI Paata": "tsikurishvili-paata",
  "TSIOLKAS Christos": "tsiolkas-christos",
  "TSKURISHVIK Paata": "tskurishvik-paata",
  "TSOCANOS Niko": "tsocanos-niko",
  "TSO-LIANG Wang": "tso-liang-wang",
  "TSONOS Robert": "tsonos-robert",
  "TSUCHIDA Hideo": "tsuchida-hideo",
  "TSUEI Jennifer": "tsuei-jennifer",
  "TSUFURA D A": "tsufura-d-a",
  "TSUNEDA Keiko": "tsuneda-keiko",
  "TSUNODA Tomi": "tsunoda-tomi",
  "TSURUYA Namboku": "tsuruya-namboku",
  "TSUTSUMI Harue": "tsutsumi-harue",
  "TSVETAYEVA Marina": "tsvetayeva-marina",
  "TU Lin": "tu-lin",
  "TUAHINE Korina": "tuahine-korina",
  "TUALIMA Jeanie": "tualima-jeanie",
  "TUAN Alice": "tuan-alice",
  "TUCCILLO Liz": "tuccillo-liz",
  "TUCK Sarah": "tuck-sarah",
  "TUCK Sarah (1)": "tuck-sarah-1",
  "TUCK Thom": "tuck-thom",
  "TUCKER Brian": "tucker-brian",
  "TUCKER Bryan": "tucker-bryan",
  "TUCKER Colin": "tucker-colin",
  "TUCKER Dave": "tucker-dave",
  "TUCKER David": "tucker-david",
  "TUCKER Dianna": "tucker-dianna",
  "TUCKER Don": "tucker-don",
  "TUCKER Emily Rose": "tucker-emily-rose",
  "TUCKER Jessie": "tucker-jessie",
  "TUCKER John Bartholomew": "tucker-john-bartholomew",
  "TUCKER Kerry": "tucker-kerry",
  "TUCKER Lois": "tucker-lois",
  "TUCKER Michael": "tucker-michael",
  "TUCKER Paul": "tucker-paul",
  "TUCKER Seth": "tucker-seth",
  "TUCKER Shirley J": "tucker-shirley-j",
  "TUCKER II David A": "tucker-ii-david-a",
  "TUCKER-BOYER Samantha": "tucker-boyer-samantha",
  "TUCKETT Jennifer": "tuckett-jennifer",
  "TUCKETT Will": "tuckett-will",
  "TUDOR Johnny": "tudor-johnny",
  "TUDOR Nicholas": "tudor-nicholas",
  "TUDOR Tamara": "tudor-tamara",
  "TUDOR Wilf": "tudor-wilf",
  "TUFFNELL David": "tuffnell-david",
  "TUFT Sarah": "tuft-sarah",
  "TUGEND Harry": "tugend-harry",
  "TUGWELL Chris": "tugwell-chris",
  "TUGWELL Christopher": "tugwell-christopher",
  "TUHIWAI Woody": "tuhiwai-woody",
  "TUKIWAHO Boni": "tukiwaho-boni",
  "TULAINE Dikran": "tulaine-dikran",
  "TULCHINSKY Tanya": "tulchinsky-tanya",
  "TULLETT Dennis": "tullett-dennis",
  "TULLIN Norman": "tullin-norman",
  "TULLIS Adam": "tullis-adam",
  "TULLOCH Adam": "tulloch-adam",
  "TULLOCH Richard": "tulloch-richard",
  "TULLY Jillian": "tully-jillian",
  "TULLY John": "tully-john",
  "TUMARIN Boris": "tumarin-boris",
  "TUMBACO Julio": "tumbaco-julio",
  "TUMMINELLI Marc": "tumminelli-marc",
  "TUMMINIA Frank": "tumminia-frank",
  "TUMS Herb": "tums-herb",
  "TUNCER Kubilay QB": "tuncer-kubilay-qb",
  "TUNG Constantine": "tung-constantine",
  "TUNIS Sammy": "tunis-sammy",
  "TUNKS Benita": "tunks-benita",
  "TUNKS Wayne": "tunks-wayne",
  "TUNLEY Richard": "tunley-richard",
  "TUNNADINE Ishbel": "tunnadine-ishbel",
  "TUNNEY Kieran": "tunney-kieran",
  "TUNNEY Russ": "tunney-russ",
  "TUNNY Shane": "tunny-shane",
  "TUNOONIQ THEATRE ": "tunooniq-theatre",
  "TUNSTALL Darren": "tunstall-darren",
  "TUOHY Jim": "tuohy-jim",
  "TUOMY Nesta": "tuomy-nesta",
  "TUOTTI Joseph Dolan": "tuotti-joseph-dolan",
  "TURCO Raymond": "turco-raymond",
  "TURCO Robert": "turco-robert",
  "TURCO-LYON Kathleen": "turco-lyon-kathleen",
  "TURGENEV Ivan": "turgenev-ivan",
  "TURGEON Stephane": "turgeon-stephane",
  "TURIANO Ann": "turiano-ann",
  "TURICH Sam": "turich-sam",
  "TURISKYLIE Joyce": "turiskylie-joyce",
  "TURK T Tara": "turk-t-tara",
  "TURKNETT Clifford": "turknett-clifford",
  "TURLEY John": "turley-john",
  "TURLEY Simon": "turley-simon",
  "TURMAN Glynn": "turman-glynn",
  "TURNAGE Bryant": "turnage-bryant",
  "TURNAGE Caitlin": "turnage-caitlin",
  "TURNAGE Mark-Anthony": "turnage-mark-anthony",
  "TURNBOW Jill": "turnbow-jill",
  "TURNBULL Ceri": "turnbull-ceri",
  "TURNBULL Colin": "turnbull-colin",
  "TURNBULL Doreen": "turnbull-doreen",
  "TURNBULL Gael": "turnbull-gael",
  "TURNBULL Keith": "turnbull-keith",
  "TURNBULL Sarah": "turnbull-sarah",
  "TURNBULL Yvette": "turnbull-yvette",
  "TURNER Alex": "turner-alex",
  "TURNER Andrea": "turner-andrea",
  "TURNER Andrew W": "turner-andrew-w",
  "TURNER Anya": "turner-anya",
  "TURNER B E": "turner-b-e",
  "TURNER Beth": "turner-beth",
  "TURNER Brian": "turner-brian",
  "TURNER Carston": "turner-carston",
  "TURNER Cathy": "turner-cathy",
  "TURNER Claire": "turner-claire",
  "TURNER Dan": "turner-dan",
  "TURNER Daniel Frank": "turner-daniel-frank",
  "TURNER David": "turner-david",
  "TURNER Dennis": "turner-dennis",
  "TURNER Deron": "turner-deron",
  "TURNER Dick": "turner-dick",
  "TURNER Edwin N": "turner-edwin-n",
  "TURNER Elspeth": "turner-elspeth",
  "TURNER Eric G": "turner-eric-g",
  "TURNER Gerald": "turner-gerald",
  "TURNER Gerritt": "turner-gerritt",
  "TURNER Graeme": "turner-graeme",
  "TURNER Greg": "turner-greg",
  "TURNER Hellie": "turner-hellie",
  "TURNER Ida M": "turner-ida-m",
  "TURNER Ilana": "turner-ilana",
  "TURNER J Jehriko": "turner-j-jehriko",
  "TURNER J Max": "turner-j-max",
  "TURNER Jago": "turner-jago",
  "TURNER Jake": "turner-jake",
  "TURNER Jamie": "turner-jamie",
  "TURNER Jefferson": "turner-jefferson",
  "TURNER Jeremy": "turner-jeremy",
  "TURNER Jessica Jill": "turner-jessica-jill",
  "TURNER Jo": "turner-jo",
  "TURNER Joanna": "turner-joanna",
  "TURNER John": "turner-john",
  "TURNER John Hastings": "turner-john-hastings",
  "TURNER Joseph": "turner-joseph",
  "TURNER Josh": "turner-josh",
  "TURNER Judy": "turner-judy",
  "TURNER Kathleen": "turner-kathleen",
  "TURNER Katrine": "turner-katrine",
  "TURNER Knox": "turner-knox",
  "TURNER Laura": "turner-laura",
  "TURNER Laura V": "turner-laura-v",
  "TURNER Lindsey": "turner-lindsey",
  "TURNER Lisle": "turner-lisle",
  "TURNER Lloyd": "turner-lloyd",
  "TURNER Lot": "turner-lot",
  "TURNER Marilee": "turner-marilee",
  "TURNER Matthew": "turner-matthew",
  "TURNER Matthew (1)": "turner-matthew-1",
  "TURNER Nathan": "turner-nathan",
  "TURNER Nicholas": "turner-nicholas",
  "TURNER Pamela": "turner-pamela",
  "TURNER Paulene": "turner-paulene",
  "TURNER Peter": "turner-peter",
  "TURNER Philip": "turner-philip",
  "TURNER Richard": "turner-richard",
  "TURNER Robert": "turner-robert",
  "TURNER Robyn": "turner-robyn",
  "TURNER Shamira": "turner-shamira",
  "TURNER Steven": "turner-steven",
  "TURNER Susan": "turner-susan",
  "TURNER Susan Watson": "turner-susan-watson",
  "TURNER Timothy": "turner-timothy",
  "TURNER Tom": "turner-tom",
  "TURNER Wilbert": "turner-wilbert",
  "TURNER-CRAY Sue": "turner-cray-sue",
  "TURNEY Catherine": "turney-catherine",
  "TURNEY Walter": "turney-walter",
  "TURNLY Francis": "turnly-francis",
  "TURNOCK Dorothy": "turnock-dorothy",
  "TURNQUIST S Elizebeth": "turnquist-s-elizebeth",
  "TURO Peter": "turo-peter",
  "TUROFF Robert Ennis": "turoff-robert-ennis",
  "TURPIN Allan": "turpin-allan",
  "TURPIN David": "turpin-david",
  "TURPIN James": "turpin-james",
  "TURPIN John": "turpin-john",
  "TURPIN Walter": "turpin-walter",
  "TURRINI Peter": "turrini-peter",
  "TURTLE Richard": "turtle-richard",
  "TURTLE Rose": "turtle-rose",
  "TURTLETAUB Sol": "turtletaub-sol",
  "TURUNEN Saara": "turunen-saara",
  "TURVEY Angela": "turvey-angela",
  "TURVEY Jay": "turvey-jay",
  "TURVIN Mark S P": "turvin-mark-s-p",
  "TUSHINGHAM David": "tushingham-david",
  "TUSVIK Marit": "tusvik-marit",
  "TUTE Warren": "tute-warren",
  "TUTTLE Brian": "tuttle-brian",
  "TUTTLE Jon": "tuttle-jon",
  "TUTTLE Korde Arrington": "tuttle-korde-arrington",
  "TUTWILER Mary": "tutwiler-mary",
  "TU'U Louise": "tu-u-louise",
  "TUULIKKI Hanna": "tuulikki-hanna",
  "TUUP ": "tuup",
  "TUXBURY Georgia": "tuxbury-georgia",
  "TVEIT Terje": "tveit-terje",
  "TWADDLE Ron": "twaddle-ron",
  "TWAIN Mark": "twain-mark",
  "TWAITE Gillian": "twaite-gillian",
  "TWAITS Michael": "twaits-michael",
  "TWANG Bud": "twang-bud",
  "TWEEDY A E": "tweedy-a-e",
  "TWEEDY David": "tweedy-david",
  "TWEESDY A E": "tweesdy-a-e",
  "TWIDDY Brian": "twiddy-brian",
  "TWIGG Venetia": "twigg-venetia",
  "TWINAME Eric": "twiname-eric",
  "TWIST Basil": "twist-basil",
  "TWIST Derek": "twist-derek",
  "TWO REEL COMPANY ": "two-reel-company",
  "TWO42 THEATRE COMPANY ": "two42-theatre-company",
  "TWOHY Evan": "twohy-evan",
  "TWOMEY John": "twomey-john",
  "TWOREK Aaron": "tworek-aaron",
  "TWO-RIVERS E Donald": "two-rivers-e-donald",
  "TWYNKY ": "twynky",
  "TYCHYNA Pavlo": "tychyna-pavlo",
  "TYDEMAN Richard": "tydeman-richard",
  "TYE Katherine": "tye-katherine",
  "TYELELE Motshabi": "tyelele-motshabi",
  "TYERS Claire": "tyers-claire",
  "TYLBOR Eleanor": "tylbor-eleanor",
  "TYLER Ben": "tyler-ben",
  "TYLER Brian": "tyler-brian",
  "TYLER Cheever": "tyler-cheever",
  "TYLER Christian": "tyler-christian",
  "TYLER Ed": "tyler-ed",
  "TYLER Heather": "tyler-heather",
  "TYLER Justin": "tyler-justin",
  "TYLER Meghan": "tyler-meghan",
  "TYLER Robin": "tyler-robin",
  "TYLER Sean": "tyler-sean",
  "TYLER Tim": "tyler-tim",
  "TYLER William": "tyler-william",
  "TYNAN Kenneth": "tynan-kenneth",
  "TYNE Jason": "tyne-jason",
  "TYPE David": "type-david",
  "TYPE William": "type-william",
  "TYRE Travis": "tyre-travis",
  "TYREE E Wayne": "tyree-e-wayne",
  "TYRELL Jim": "tyrell-jim",
  "TYRELL Richard": "tyrell-richard",
  "TYRRELL Sean": "tyrrell-sean",
  "TYSE Rhiannon": "tyse-rhiannon",
  "TYSEN Nathan": "tysen-nathan",
  "TYSON Cleman": "tyson-cleman",
  "TYSON David": "tyson-david",
  "TYSON James": "tyson-james",
  "TYSON Juliana": "tyson-juliana",
  "TYSON Nathan": "tyson-nathan",
  "TZARA Tristan": "tzara-tristan",
  "TZE CHIEN Chong": "tze-chien-chong",
  "TZUR Zohar": "tzur-zohar",
};
