/**
 * Fixture data for scraping author bios and play data;
 * this is to be used only in development and testing.
 */

const authorFixtures: { [authorName: string]: string } = {
  "CARSON Anne": "carson-anne",
  "EURIPIDES ": "euripides",
  "KANE Sarah": "kane-sarah",
  "MAMET David": "mamet-david",

  // "2 BIRDS 1 STONE ": "2-birds-1-stone",
  // "2 TIL 5 YOUTH GROUP ": "2-til-5-youth-group",
  // "2B THEATRE COMPANY ": "2b-theatre-company",
  // "2HEADEDPIGEON ": "2headedpigeon",
  // "2MAGPIES THEATRE ": "2magpies-theatre",
  // "3 D COLLABORATIVE THEATRE ": "3-d-collaborative-theatre",
  // "3 D THEATRE COMPANY ": "3-d-theatre-company",
  // "5 FLIGHTS THEATER COMPANY ": "5-flights-theater-company",
  // "7:84 THEATRE COMPANY ": "784-theatre-company",
  // "AAAL Mahmoud Abdel": "aaal-mahmoud-abdel",
  // "AAIRES Patrice": "aaires-patrice",
  // "AAKHU Shepsu": "aakhu-shepsu",
  // "AANERUD Ryan": "aanerud-ryan",
  // "AANES Kirk": "aanes-kirk",
  // "AAR-AL-DEAN ": "aar-al-dean",
  // "AARON Caroline": "aaron-caroline",
  // "AARON Hugh": "aaron-hugh",
  // "AARON John": "aaron-john",
  // "AARON Joyce": "aaron-joyce",
  // "AARON Luned": "aaron-luned",
  // "AARONS Leroy": "aarons-leroy",
  // "AARONSON Jack": "aaronson-jack",
  // "AARSVOLD Laurel Ann": "aarsvold-laurel-ann",
  // "AASENG Mikhaila": "aaseng-mikhaila",
  // "ABAD Mercedes": "abad-mercedes",
  // "ABAFFY Rebecca": "abaffy-rebecca",
  // "ABAKARI Damani": "abakari-damani",
  // "ABALOS Brian": "abalos-brian",
  // "ABATEMARCO Tony": "abatemarco-tony",
  // "ABATSIS Elisa": "abatsis-elisa",
  // "ABBA Marta": "abba-marta",
  // "ABBADO Daniele": "abbado-daniele",
  // "ABBADO Ovadia": "abbado-ovadia",
  // "ABBATIELLO Danielle": "abbatiello-danielle",
  // "ABBENSETTS Michael": "abbensetts-michael",
  // "ABBIATI Roberto": "abbiati-roberto",
  // "ABBINANTI David": "abbinanti-david",
  // "ABBINANTI Jill": "abbinanti-jill",
  // "ABBOT June": "abbot-june",
  // "ABBOT Rick": "abbot-rick",
  // "ABBOTT Ada G": "abbott-ada-g",
  // "ABBOTT Ben": "abbott-ben",
  // "ABBOTT Brian": "abbott-brian",
  // "ABBOTT Brian (1)": "abbott-brian-1",
  // "ABBOTT Chris": "abbott-chris",
  // "ABBOTT George": "abbott-george",
  // "ABBOTT Greg": "abbott-greg",
  // "ABBOTT Jack Henry": "abbott-jack-henry",
  // "ABBOTT Karen": "abbott-karen",
  // "ABBOTT Laura": "abbott-laura",
  // "ABBOTT Paul": "abbott-paul",
  // "ABBOTT Sally": "abbott-sally",
  // "ABBOTT Stephen": "abbott-stephen",
  // "ABBOTT Steve": "abbott-steve",
  // "ABBS Sean": "abbs-sean",
  // "ABCEDE Angel": "abcede-angel",
  // "ABDALLAH Mohammad Ibn": "abdallah-mohammad-ibn",
  // "ABDEL-RAZEK Mariam": "abdel-razek-mariam",
  // "ABDOH Reza": "abdoh-reza",
  // "ABDUL Ban": "abdul-ban",
  // "ABDULLAH Ahmed Maarifa": "abdullah-ahmed-maarifa",
  // "ABDULRAZZAK Hassan": "abdulrazzak-hassan",
  // "ABDU-RAHMAN Anadoula": "abdu-rahman-anadoula",
  // "ABE Kobo": "abe-kobo",
  // "ABEL David": "abel-david",
  // "ABEL Douglas": "abel-douglas",
  // "ABEL Duncan": "abel-duncan",
  // "ABEL J G": "abel-j-g",
  // "ABEL Leah James": "abel-leah-james",
  // "ABEL Lionel": "abel-lionel",
  // "ABEL Ron": "abel-ron",
  // "ABEL Roysten": "abel-roysten",
  // "ABELA Donna": "abela-donna",
  // "ABELES David": "abeles-david",
  // "ABELL Kjeld": "abell-kjeld",
  // "ABELL Lionel": "abell-lionel",
  // "ABELLA Cesar": "abella-cesar",
  // "ABELMAN Brett": "abelman-brett",
  // "ABERLIN Brooke": "aberlin-brooke",
  // "ABERLINE Matthew": "aberline-matthew",
  // "ABERNATHY Brian": "abernathy-brian",
  // "ABERNATHY Charles": "abernathy-charles",
  // "ABERNETHY Craig": "abernethy-craig",
  // "ABERNETHY Margaret": "abernethy-margaret",
  // "ABID Robert": "abid-robert",
  // "ABINERI Daniel": "abineri-daniel",
  // "ABINERI John": "abineri-john",
  // "ABIODUNJI Syl": "abiodunji-syl",
  // "ABKARIAN Catherine Schaub": "abkarian-catherine-schaub",
  // "ABLEMAN Paul": "ableman-paul",
  // "ABLESER Deanna Alisa": "ableser-deanna-alisa",
  // "ABLEY Sean": "abley-sean",
  // "ABNEY JR Robert": "abney-jr-robert",
  // "ABOLAFIA David": "abolafia-david",
  // "ABOSCH Danny": "abosch-danny",
  // "ABOUD Morgan": "aboud-morgan",
  // "ABOUDOMA Mohamed": "aboudoma-mohamed",
  // "ABOUSSLEMAN Susan": "aboussleman-susan",
  // "ABOVE THE CURVE ": "above-the-curve",
  // "ABRACEN Alice": "abracen-alice",
};



export default authorFixtures;
