name: Integration Tests

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  integration-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Environment
        uses: ./.github/actions/setup-node-env

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps firefox

      - name: Run Integration Tests
        env:
          MONGO_URI: mongodb://test:10000
        run: yarn test:int --ci --json --outputFile=test-results.json

      - name: Upload Integration Test Results
        uses: actions/upload-artifact@v5
        if: ${{ !cancelled() }}
        with:
          name: integration-test-results
          path: test-results.json
          retention-days: 14
