name: Integration Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"
          package-manager-cache: false

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn
        run: corepack prepare yarn@4.12.0 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Download Playwright Browsers
        run: yarn dlx playwright install --with-deps

      - name: Run integration tests
        env:
          MONGO_URI: mongodb://test:10000
        run: yarn test:int

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
